# 1. requests 모듈
* HTTP프로토콜을 사용할 수 있게 해주는 모듈
* 파이썬 기본 모듈인 urllib보다 사용이 편리
* 따로 설치 필요 pip install requests/conda install requests

# 2. requests 모듈 사용법
* 1) 모듈 불러오기: import requests
* 2) url을 변수에 저장
* 3) url파라미터를 payload 라는 변수에 딕셔너리 형태로 저장
  * payload = {파라미터1 : value, 파라미터2 : value2}
* 4) headers 도 headers 라는 변수에 딕셔너리 형태로 저장
  * headers = {파라미터1 : value, 파라미터2 : value2}
* 5) HTTP요청 보내기 get, post
  * get: r= requests.get(url, params=payload, headers=headers)
  * post: r = requests.post(url, data={key:value})
* 6) 만들어진 url 확인: print(r.url)
* 7) 응답코드확인: print(r.status_code)
* 8) 응답 요소 출력: r.text, r.content, r.json()

In [ ]:
import requests
url = " "
payload = dict()
r = requsts.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.text, r.content, r.json()

In [ ]:
# !conda install requests

In [6]:
import requests
url = "https://openapi.naver.com/v1/search/blog"
keyword = "핀테크"
payload = dict(query=keyword, display=100, start=1, sort="date")
headers = {"X-Naver-Client-Id" : "", "X-Naver-Client-Secret" : ""}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()
response

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
200

{'lastBuildDate': 'Tue, 14 Oct 2025 11:15:30 +0900',
 'total': 476754,
 'start': 1,
 'display': 100,
 'items': [{'title': '급여통장 신규 개설 및 인터넷뱅킹 신청 방법',
   'link': 'https://blog.naver.com/elow1957/224040614815',
   'description': '다른 <b>핀테크</b> 서비스의 대안 서론 요즘 대부분의 금융거래가 온라인으로 이루어지고 있습니다. 이에... 다른 <b>핀테크</b> 서비스의 대안 최근에는 카카오뱅크, 케이뱅크 등 인터넷 전문은행을 통한 다양한 통장... ',
   'bloggername': '내가 좋아하는것들',
   'bloggerlink': 'blog.naver.com/elow1957',
   'postdate': '20251014'},
  {'title': '전망좋은주식 미국 주식 종목 중심 분석',
   'link': 'https://blog.naver.com/wwlcc28/224040612860',
   'description': '에너지 저장, 5G 통신, <b>핀테크</b> 분야 또한 안정적인 성장세를 보이고 있습니다. 이런 흐름 속에서 주목받는 기업들은 기술력, 수익 구조, 시장 점유율 세 가지 기준에서 공통된 특징을 가집니다. “지속... ',
   'bloggername': 'wwlcc28님의 블로그',
   'bloggerlink': 'blog.naver.com/wwlcc28',
   'postdate': '20251014'},
  {'title': '인도 ETF｜RISE 인도디지털성장·KODEX 인도Nifty50·TIGER... ',
   'link': 'https://blog.naver.com/notinghel/224040610822',
   'description': 'MarketVector 지수를 추종하며, 인도의 인터넷·<b>핀테크</b>·통신·클라우드 기업들이 중심입니다.... IT, <b>핀테크</b>, 통신 대형주, 금융, 에너지 소비재, 서비스, 자동차 최근 NAV 수준 약 10,300원 약 13... ',
   'bloggername': 'notinghel님의 블로그',
   'bloggerlink': 'blog.naver.com/notinghel',
   'postdate': '20251014'},
  {'title': '감성지능: <b>핀테크</b> 고객 경험의 미래',
   'link': 'https://blog.naver.com/pxjlpss565/224040607064',
   'description': '감성지능: <b>핀테크</b> 고객 경험의 미래 <b>핀테크</b> 산업은 빠르게 발전하고 있으며, 이에 따라 고객 경험에 대한 요구도 더욱 증가하고 있다. 최근 감성지능 기술의 발전으로 <b>핀테크</b> 기업들은 더욱 개인화된 서비스를... ',
   'bloggername': '운동과 공부가 취미',
   'bloggerlink': 'blog.naver.com/pxjlpss565',
   'postdate': '20251014'},
  {'title': '[신한투자증권 미국주식 주요이슈] 챗GPT 내 즉시 결제... ',
   'link': 'https://blog.naver.com/shinhansec_official/224040598934',
   'description': '구글과 쇼핑 전쟁 : 이번 기능은 오픈AI의 자체 기술인 ‘에이전틱 커머스 프로토콜’과 <b>핀테크</b> 기업 스트라이프(Stripe)와의 협력을 통해 구현됐고, 앞으로 장바구니 기능 및 글로벌 확장도 계획 중이에요.... ',
   'bloggername': '신한투자증권 공식 블로그',
   'bloggerlink': 'blog.naver.com/shinhansec_official',
   'postdate': '20251014'},
  {'title': '영문계약서, 어디서부터 봐야 할까? 기본 구조와 핵심 조항... ',
   'link': 'https://blog.naver.com/legal_lemonade/224040593334',
   'description': 'About the Authour 국내 대형은행 법무팀에서 10년 이상 국제금융, 신용장, 영문계약서 및 외국환규제 자문 등을 담당하고, <b>핀테크</b> 기업에서 해외 지급결제와 해외 진출 등 다양한 프로젝트를 수행한... ',
   'bloggername': '리걸 레몬에이드',
   'bloggerlink': 'blog.naver.com/legal_lemonade',
   'postdate': '20251014'},
  {'title': '비트코인관련주 코인베이스 다날 우리기술투자 주가 분석',
   'link': 'https://blog.naver.com/fashiongreen/224040588409',
   'description': "기반 <b>핀테크</b> / 결제 플랫폼 기업으로 암호화폐 결제 플랫폼인 다날<b>핀테크</b>를 개발해 '페이코인'을 실생활 결제에 적용하는 등의 경험을 가지고 있는데요 이러한 기술력을 기반으로 스테이블코인 사업 진출... ",
   'bloggername': '돈 되는 경제만 쉽고 빠르게',
   'bloggerlink': 'blog.naver.com/fashiongreen',
   'postdate': '20251014'},
  {'title': '신용점수 올리는 방법 2025 최신 기준 정리',
   'link': 'https://blog.naver.com/sssolution1858/224039350975',
   'description': '정확한 진단 정직한 처방 고객과 상생을 도모하는 에스에스솔루션 2025년 들어 신용점수 제도가 한층 더 정교해졌다. 단순히 연체 없이 대출을 갚는 것만으로는 점수를 높이기 어렵고, 금융사마다 평가 기준이... ',
   'bloggername': 'Sssolution',
   'bloggerlink': 'blog.naver.com/sssolution1858',
   'postdate': '20251014'},
  {'title': 'RISE 인도디지털성장 ETF 완전정리｜인도 디지털 인프라... ',
   'link': 'https://blog.naver.com/notinghel/224040584997',
   'description': '이 ETF는 인도의 IT·통신·<b>핀테크</b>·디지털 인프라 산업을 대표하는 상장기업들로 구성되어... 디지털 인프라, 온라인 서비스, 통신, <b>핀테크</b>, 클라우드 등 인도의 정보기술 기반 산업 성장을... ',
   'bloggername': 'notinghel님의 블로그',
   'bloggerlink': 'blog.naver.com/notinghel',
   'postdate': '20251014'},
  {'title': '시니어 마케팅, 60대·70대·80대, 같은 ‘시니어’로 묶어선... ',
   'link': 'https://blog.naver.com/trotnewsofficial/224040583199',
   'description': '평생교육, 디지털 고급 교육(<b>핀테크</b>, AI 활용)을 제공하세요. 여가·문화·관광 바우처를 적극 활용하세요. 70대 정책: 안전 관리 만성질환 예방 바우처, 보안·사기 예방 교육을 확대하세요. 디지털 서비스에 1:1... ',
   'bloggername': '시니어마케팅 연구소',
   'bloggerlink': 'blog.naver.com/trotnewsofficial',
   'postdate': '20251014'},
  {'title': '신한은행 2026년 동계 청년인턴 채용 완벽 가이드 - 금융권... ',
   'link': 'https://blog.naver.com/cymmcymm/224040566983',
   'description': '결합된 <b>핀테크</b> 시대에 꼭 필요한 경험을 쌓을 수 있는 기회랍니다. 신한은행 청년인턴 지원 자격 조건... 금융권 취업을 준비하고 계신 분들, IT와 금융을 결합한 <b>핀테크</b> 분야에 관심 있는 분들 모두에게 정말... ',
   'bloggername': 'Creater Y',
   'bloggerlink': 'blog.naver.com/cymmcymm',
   'postdate': '20251014'},
  {'title': '“솔라나 × 한국 스테이블코인 — 주식시장에서 주목할... ',
   'link': 'https://blog.naver.com/hmn1204/224040565408',
   'description': '증가 <b>핀테크</b> / 결제 플랫폼 스테이블코인 → 결제/송금/정산 활용 가능성, 자체 플랫폼 내 사용... <b>핀테크</b> / 결제 플랫폼 회사 (예: 토스 등) 실제 보도가 있듯 토스(Toss)가 “원화 기반 스테이블코인 발행”을... ',
   'bloggername': '억만덕후의 이시대 살아남는법',
   'bloggerlink': 'blog.naver.com/hmn1204',
   'postdate': '20251014'},
  {'title': '미국의 파이어족이 불러올 경제의 나비효과',
   'link': 'https://blog.naver.com/garts44/224040562087',
   'description': '오늘날의 <b>핀테크</b>, 국채, 디지털 자산이 같은 역할을 하고 있습니다. 5️⃣ 소비재·유통 도시화와 중산층의 등장으로 전국 유통망이 생겼고, 시어스의 카탈로그와 코카콜라는 그 시대의 아이콘이었습니다.... ',
   'bloggername': '오늘 질문은...',
   'bloggerlink': 'blog.naver.com/garts44',
   'postdate': '20251014'},
  {'title': '[<b>핀테크</b> 기자단] 2025 K-DATA·신용보즘기금·한국<b>핀테크</b>지... ',
   'link': 'https://blog.naver.com/koreafintech/224040557226',
   'description': '지난 9월 18일 디캠프 프론트원에서 진행된 2025 K-DATA·신용보즘기금· 한국<b>핀테크</b>지원센터 IR DAY 데모데이에 <b>핀테크</b> 대학생 기자단이 현장취재를 다녀왔습니다! 각 기관이 지원하는 유망 스타트업들을... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20251014'},
  {'title': '8월 서울 오피스 시장 분석 — 거래 급감에도 공실률은 하락',
   'link': 'https://blog.naver.com/jsh5015/224040557309',
   'description': 'AI, <b>핀테크</b>, 콘텐츠 업종 중심으로 오피스 입주 문의는 오히려 증가세.”  임대비용 — NOC 상승세... AI·<b>핀테크</b>·콘텐츠 산업 중심의 신규 오피스 수요 지속 하반기에는 강남·성수·여의도권 중심 재계약... ',
   'bloggername': '부동산과 경제 뉴스 정리, 분양 소식과 다양한 정보',
   'bloggerlink': 'blog.naver.com/jsh5015',
   'postdate': '20251014'},
  {'title': '증권사리포트 요약본 2025.10.14',
   'link': 'https://blog.naver.com/kwangpoong/224040556592',
   'description': '[035420] ˝AI, <b>핀테크</b>, 커머스˝ 모두 바쁨 ▶ 3Q25 Preview: 영업이익 5,579억원(+13.9% YoY)으로 컨센서스 하회 추정 ▶ 중장기 <b>핀테크</b> 사업 가치 부각 하나증권 이준호 카카오 [035720] 3분기 영업이익 1... ',
   'bloggername': '學習忍',
   'bloggerlink': 'blog.naver.com/kwangpoong',
   'postdate': '20251014'},
  {'title': '스테이블코인 결제시스템 3가지 핵심 변화 총정리',
   'link': 'https://blog.naver.com/law_sugarsquare/224035670742',
   'description': "* [상담문의]  02-563-5877  010-****-**** 카톡 '법무법인슈가스퀘어' 검색! 또는 카카오톡 상담링크  ****@sugar.legal #스테이블코인 #결제시스템 #<b>핀테크</b> #블록체인 #금융혁신",
   'bloggername': '법무법인 슈가스퀘어 블로그',
   'bloggerlink': 'blog.naver.com/law_sugarsquare',
   'postdate': '20251014'},
  {'title': '2025년 10월 14일 관심종목(주식)',
   'link': 'https://blog.naver.com/kk9550ch/224040546776',
   'description': 'idxno=3162806 아이티센피엔에스 - 통합 보안시스템+양자암호 솔루션 - <b>핀테크</b>, 스테이블코인 관련주 [특징주] 아이티센피엔에스, &quot;美 스테이블코인 규제법 통과&quot; 가상화폐 ... ',
   'bloggername': '재테크 in my life (feat.맛난음식)',
   'bloggerlink': 'blog.naver.com/kk9550ch',
   'postdate': '20251014'},
  {'title': '오늘자 이커머스 전망에 대해 알아보자',
   'link': 'https://blog.naver.com/pdion/224040542746',
   'description': '결제·<b>핀테크</b> 통합 BNPL(Buy Now Pay Later), 간편 결제, 디지털 월렛 등이 사용자 경험을 매끄럽게 할 것 마켓플레이스 재편 / 플랫폼 경쟁 플랫폼 간 제휴, 인수합병, 수수료 및 데이터 경쟁이 심화될 것 3. 기회... ',
   'bloggername': '피디온',
   'bloggerlink': 'blog.naver.com/pdion',
   'postdate': '20251014'},
  {'title': '코스피 시가총액 순위, 대한민국 TOP10 기업 성적표',
   'link': 'https://blog.naver.com/hanvit_lol/224040543213',
   'description': 'TOP10에 턱걸이로 안착했으며 <b>핀테크</b>, 콘텐츠, AI 삼박자를 앞세워서 제2의 도약을 노리고 있는 중이다. 이상으로 대한민국 경제의 심장인 코스피 TOP10 기업들의 역동적인 성적표 보았다. 25년의 성적표는 AI... ',
   'bloggername': '잘먹고 잘사는 오리좌',
   'bloggerlink': 'blog.naver.com/hanvit_lol',
   'postdate': '20251014'},
  {'title': '[비트코인 스탠다드]가 말하지 못한 것: GENIUS Act와 STABLE... ',
   'link': 'https://blog.naver.com/10000reading/224040540164',
   'description': '이 경우 카드 네트워크·은행 코어·<b>핀테크</b> 월렛이 스테이블코인 결제 레일을 품으며 **‘매끄러운... 은행-<b>핀테크</b>-카드사가 맺는 삼각 파트너십이 관건이다. 4) 체인 간 상호운용성과 계정 추상화 모바일... ',
   'bloggername': '일만리딩',
   'bloggerlink': 'blog.naver.com/10000reading',
   'postdate': '20251014'},
  {'title': '네이버·카카오, AI 전환으로 실적 폭발!',
   'link': 'https://blog.naver.com/smart-moneylog/224039305600',
   'description': '디지털 자산, <b>핀테크</b>, 블록체인 등 새로운 성장축이 확실히 잡히는 셈이죠. AI에다 가상자산까지... 앞으로의 관전 포인트 네이버는 AI로 쇼핑과 <b>핀테크</b>를, 카카오는 AI로 커뮤니케이션과 광고를 진화시키는... ',
   'bloggername': '스마트머니로그',
   'bloggerlink': 'blog.naver.com/smart-moneylog',
   'postdate': '20251014'},
  {'title': '비바리퍼블리카 주가 급등하는 이유, 2025년 상장 앞둔 토스의... ',
   'link': 'https://blog.naver.com/kwonmj1216/224022265678',
   'description': '최근 <b>핀테크</b> 업계에서 가장 뜨거운 관심을 받는 비바리퍼블리카에 대한 궁금증이었습니다. 실제로... 나 역시 <b>핀테크</b> 업계를 10년 넘게 지켜보면서 이만큼 탄탄한 실적 기반을 갖춘 회사를 본 적이 드물다고... ',
   'bloggername': '올인포',
   'bloggerlink': 'blog.naver.com/kwonmj1216',
   'postdate': '20251014'},
  {'title': 'AI가 리드하는 <b>핀테크</b> 혁신의 미래! : 서울 <b>핀테크</b> 위크 2025... ',
   'link': 'https://blog.naver.com/elmanproduction/224040539614',
   'description': '오늘은 서울 <b>핀테크</b> 위크 2025 홍보 영상 제작 후기를 들고 왔습니다. 로딩중,,, 글로번 <b>핀테크</b> 축제인 서울 <b>핀테크</b> 위크 2025가 곧 개최됩니다. 금융과 AI, <b>핀테크</b> 산업의 주요 이슈를 다루고 혁신적인... ',
   'bloggername': 'ELMAN 영상제작사',
   'bloggerlink': 'blog.naver.com/elmanproduction',
   'postdate': '20251014'},
  {'title': '벤처기업도 이제 ‘가상자산 거래업’을 할 수 있다!',
   'link': 'https://blog.naver.com/veteran01/224040538500',
   'description': '◆ 기대 효과 혁신 스타트업의 진입 확대: 블록체인 기술 기반의 <b>핀테크</b>, 거래 플랫폼, 토큰증권(STO) 등 다양한 영역에서 벤처기업들이 자유롭게 사업을 추진할 수 있습니다. 투자 활성화: 벤처기업 인증이... ',
   'bloggername': 'Not success but Service',
   'bloggerlink': 'blog.naver.com/veteran01',
   'postdate': '20251014'},
  {'title': '<b>핀테크</b>와 혁신의 만남 : 제4회 피노베이션 챌린지 행사 오프닝... ',
   'link': 'https://blog.naver.com/elmanproduction/224040533011',
   'description': '<b>핀테크</b>(Fintech)와 이노베이션(Innovation)을 합친 용어로, 서울시가 추진해온 프로그램입니다. <b>핀테크</b>, 인슈어테크, AI, 빅데이터 등 다양한 기술 역량을 가진 스타트업을 발굴하고, 금융사와의 공동 사업화를... ',
   'bloggername': 'ELMAN 영상제작사',
   'bloggerlink': 'blog.naver.com/elmanproduction',
   'postdate': '20251014'},
  {'title': '10월 14일. 투자자를 위한 뉴스 속 실마리 [자본시장 이슈... ',
   'link': 'https://blog.naver.com/numbersmembers/224040531979',
   'description': "https://www.insightkorea.co.kr/news/articleView.html?idxno=233417 Published on: 2025-10-13 15:34:00 가상자산 M&amp;A 3배 급증…금융·<b>핀테크</b> '합종연횡' 본격화 /전자신문 가상자산 업계 인수합병(M&amp;A) 발표가... ",
   'bloggername': 'M&A·지배구조·Deal·기업분석 뉴스 서비스 <넘버스>',
   'bloggerlink': 'blog.naver.com/numbersmembers',
   'postdate': '20251014'},
  {'title': '디지털 브레튼우즈의 서막: 달러·금의 시대를 넘어 블록체인... ',
   'link': 'https://blog.naver.com/10000reading/224040531447',
   'description': 'IMF·BIS와 함께 민간 PSP, <b>핀테크</b>, 은행 컨소시엄이 공동으로 의결권을 행사하여 권력 집중을 방지한다. 5~7년의 로드맵: 테스트넷에서 글로벌 표준으로 1단계에서는 CBDC 상호운용 최소규격과 디지털 SDR... ',
   'bloggername': '일만리딩',
   'bloggerlink': 'blog.naver.com/10000reading',
   'postdate': '20251014'},
  {'title': '[GPU Live] GPUaaS 서비스 GPU Live!',
   'link': 'https://blog.naver.com/nhn_injeinc/224039765197',
   'description': '✅ 금융·<b>핀테크</b> 산업 GPU Live는 금융기관에서 중요한 딥러닝 기반 이상거래 탐지(FDS), 신용평가 모델링, 고객 행동 분석 등대규모 연산이 필요한 금융 서비스 환경에 최적화되어 있습니다! GPU 자원을... ',
   'bloggername': 'NHN 인재아이엔씨',
   'bloggerlink': 'blog.naver.com/nhn_injeinc',
   'postdate': '20251014'},
  {'title': '채무통합대환대출조건 채무통합으로 시작하는 현명한 재무 관리',
   'link': 'https://blog.naver.com/my-loan-clinic/223949594538',
   'description': '금융사의 상품을 비교할 때 대출 비교 앱이나 <b>핀테크</b> 플랫폼을 적극 활용해 봐야 합니다. 통합 대출 시 발생할 수 있는 수수료나 추가 비용도 반드시 확인하셔야 합니다. 직접 금융 기관 상담이 어렵다면 전문가... ',
   'bloggername': '마이금융클리닉 공식블로그',
   'bloggerlink': 'blog.naver.com/my-loan-clinic',
   'postdate': '20251014'},
  {'title': '카드매출로 보증받는 법, 실전 가이드',
   'link': 'https://blog.naver.com/yj920621/224040121932',
   'description': '은행·<b>핀테크</b> 특례형) Tip: 현금 매출 비중이 높아도 카드·PG 매출 증빙 비율을 최대화하면 한도에 유리합니다. 준비물 체크리스트 - 필수 - 사업자등록증 사본 - 대표자 신분증 - 최근 6~12개월 카드매출 내역... ',
   'bloggername': '한국중소기업 지원센터',
   'bloggerlink': 'blog.naver.com/yj920621',
   'postdate': '20251014'},
  {'title': '가상자산: ‘벤처인증 허용’+‘대출 규제’ 병행… 산업은... ',
   'link': 'https://blog.naver.com/k3228452/224040522149',
   'description': '#가상자산 #크립토 #디지털자산 #벤처인증 #디지털자산기본법 #스테이블코인 #렌딩규제 #금리상한 #레버리지금지 #소비자보호 #공시의무 #내부통제 #준법감시 #리스크관리 #거래소 #커스터디 #<b>핀테크</b> #웹3',
   'bloggername': '한눈정책 – 핵심만 콕, 하루 한 장',
   'bloggerlink': 'blog.naver.com/k3228452',
   'postdate': '20251014'},
  {'title': 'Eat-Lancet이 제시한 이상적인 식단',
   'link': 'https://blog.naver.com/yelms/224040517993',
   'description': '이는 저렴한 식물성 단백질 기반의 간편식(HMR), 개인 맞춤형 구독 서비스, 혹은 건강한 식습관을 유도하는 챌린지 앱과 같은 <b>핀테크</b> 결합 서비스 등 무궁무진한 사업 기회를 의미한다. 2. 전통 식단의 보호와... ',
   'bloggername': '국경없는금융포럼',
   'bloggerlink': 'blog.naver.com/yelms',
   'postdate': '20251014'},
  {'title': '2025.10.14(화) 기업 리포트 요약 정리',
   'link': 'https://blog.naver.com/timulys/224040516473',
   'description': 'A035420 -˝AI, <b>핀테크</b>, 커머스˝ 모두 바쁨 3Q25 Preview: 영업이익 5,579억원(+13.9% YoY)으로 컨센서스 하회 추정 중장기 <b>핀테크</b> 사업 가치 부각 매수 320,000 262,500 SK증권 남효지 2025/10/14... ',
   'bloggername': '투자하는 행복',
   'bloggerlink': 'blog.naver.com/timulys',
   'postdate': '20251014'},
  {'title': '[TUO]10월14일 세계뉴스: 가자 휴전, 우크라 토마호크, EU... ',
   'link': 'https://blog.naver.com/world-response/224040514540',
   'description': '넷째, 유엔 사이버협약의 서명·비준 과정을 거치며 데이터 이전, 전자증거 교환, 플랫폼 책임 범위가 분명해지면 클라우드·보안·<b>핀테크</b> 기업의 규제 대응 비용과 수익 모델에도 변화가 생길 가능성이 큽니다.... ',
   'bloggername': '장대표의 인사이드 베트남',
   'bloggerlink': 'blog.naver.com/world-response',
   'postdate': '20251014'},
  {'title': 'Global Vicke 사기 투자 리딩방 미끼 완전 해부 (사칭)',
   'link': 'https://blog.naver.com/lucifer49329/224040508093',
   'description': '(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이 강민성 변호사',
   'bloggerlink': 'blog.naver.com/lucifer49329',
   'postdate': '20251014'},
  {'title': 'Angel❤️월세·전세금 부담 줄이는 혁신 서비스  보증금... ',
   'link': 'https://blog.naver.com/nyk34644/224040504261',
   'description': '이런 고민을 해결해주는 다양한 <b>핀테크</b> 서비스들이 등장하고 있어 관심이 집중되고 있습니다.... <b>핀테크</b> 스타트업 데브디에서 출시한 집업페이는 또 다른 혁신을 가져왔습니다. 바로 집주인의 동의 없이도... ',
   'bloggername': '작으면서 큰 부동산이야기',
   'bloggerlink': 'blog.naver.com/nyk34644',
   'postdate': '20251014'},
  {'title': '이직사유 예시 BEST 3, 면접 답변 꿀팁 총정리 &amp; 합격 전략!',
   'link': 'https://blog.naver.com/staffs00/224040498054',
   'description': '최근 <b>핀테크</b> 분야에 큰 관심을 갖게 되면서 귀사의 AI 기반 개인화 금융 서비스를 주목하게... 제가 보유한 대용량 데이터 처리 경험과 금융 도메인 지식을 바탕으로 귀사 AI <b>핀테크</b> 서비스의 안정성과 확장성... ',
   'bloggername': 'STAFFS STORY',
   'bloggerlink': 'blog.naver.com/staffs00',
   'postdate': '20251014'},
  {'title': '2030대가 선호하는 대기업 TOP10과 선택 이유',
   'link': 'https://blog.naver.com/rct190/224040494783',
   'description': '카카오 플랫폼, 콘텐츠, <b>핀테크</b> 등 영역을 넘나들며 혁신을 시도하는 모습이 2030대의 관심을 끌고 있습니다. “미래 가치가 기대된다”라는 평가와 함께 브랜드 이미지도 세련되고 젊은 감각이 강하다는... ',
   'bloggername': '파이어족의 경제, 금융 이야기',
   'bloggerlink': 'blog.naver.com/rct190',
   'postdate': '20251014'},
  {'title': '카카오페이 10월 14일 퀴즈 맞히고 복권 받기',
   'link': 'https://blog.naver.com/tkadla1422/224040494383',
   'description': '이처럼 통합 <b>핀테크</b> 플랫폼으로 진화하며 투자, 환전, 보험, 청구서 관리 등 다양한 금융 서비스를 통합 제공하는 점도 큰 강점입니다. 요약하면, 카카오페이는 카카오톡과의 완벽한 연동으로 쉽고 빠른 결제와... ',
   'bloggername': '김맹구의 탐구생활',
   'bloggerlink': 'blog.naver.com/tkadla1422',
   'postdate': '20251014'},
  {'title': '카카오뱅크 목표가 하향 대출 규제 속 성장 전망 분석 투자 전략!',
   'link': 'https://blog.naver.com/lottotem_economy/224040487251',
   'description': '가계대출 규제가 성장 전망치에 미친 구체적 영향 <b>핀테크</b> 리더로서 카카오뱅크는 저렴한 수신 확대를... 시장 컨센서스 비교 및 <b>핀테크</b> 주의 향후 주가 전망 KB증권이 제시한 28,000원의 목표주가는 최근 6개월... ',
   'bloggername': '경제톡',
   'bloggerlink': 'blog.naver.com/lottotem_economy',
   'postdate': '20251014'},
  {'title': '10/14 섹터별 현황',
   'link': 'https://blog.naver.com/mark-s/224040487497',
   'description': '93 <b>핀테크</b>(FinTech) 0.92 mRNA(메신저 리보핵산) 0.92 PCB(FPCB 등) 0.90 코로나19(치료제/백신 개발 등) 0.90 2025 상반기 신규상장 0.89 딥페이크(deepfake) 0.88 제습기 0.87 두나무(Dunamu) 0.86... ',
   'bloggername': 'Observer',
   'bloggerlink': 'blog.naver.com/mark-s',
   'postdate': '20251014'},
  {'title': '[보험업 컨설턴트 김희석] 2501014 주요 금융 뉴스',
   'link': 'https://blog.naver.com/cekhsgod/224040484905',
   'description': "독일 최대 인뱅 CEO 줄퇴진에 금감원 “<b>핀테크</b> 규제 완화 신중해야” (조선비즈, 10/13) 2.... 가상자산 M&amp;A 3배 급증…금융·<b>핀테크</b> '합종연횡' 본격화 (전자신문, 10/13) 6. ‘업비트 효과’ 넘어야... ",
   'bloggername': '벌교돌쇠의 성공 이야기',
   'bloggerlink': 'blog.naver.com/cekhsgod',
   'postdate': '20251014'},
  {'title': '5 best AI observability tools in 2025',
   'link': 'https://blog.naver.com/leejoon73/224040481556',
   'description': 'AI News <b>핀테크</b>(대출 승인가격) 특정 집단 승인율 급락 → 업스트림 파트너 데이터 시프트를 신속 진단·완화, 공정성·컴플라이언스 유지. AI News 고객지원(CX 추천) 특정 제품군에서 AI 추천이... ',
   'bloggername': 'leejoon73님의 블로그',
   'bloggerlink': 'blog.naver.com/leejoon73',
   'postdate': '20251014'},
  {'title': '금융 데이터 API, 누가 최강자? Plaid vs Yodlee vs... ',
   'link': 'https://blog.naver.com/standupandlight/224039728410',
   'description': '<b>핀테크</b> 핵심 기술, 3대 금융 데이터 API 완전 비교 Plaid vs Yodlee vs Finicity 상세 분석 <b>핀테크</b> 서비스의 핵심은 정확하고 빠른 금융 데이터 수집입니다. 이때 반드시 필요한 기술이 바로 금융 데이터... ',
   'bloggername': 'standupandlight',
   'bloggerlink': 'blog.naver.com/standupandlight',
   'postdate': '20251014'},
  {'title': 'NAVER 주가 전망, 목표주가와 재무제표까지 분석! 지금... ',
   'link': 'https://blog.naver.com/romantic_comedy_life/224040476869',
   'description': 'AI·클라우드·<b>핀테크</b> 등 신성장동력 사업 확장으로 다시 반등세를 보이고 있습니다. 오늘은... 광고, <b>핀테크</b>, 클라우드, 콘텐츠 등 최근 동향 : 네이버는 ‘AI 기술 고도화’를 핵심... ',
   'bloggername': '로코라이프 경제 블로그',
   'bloggerlink': 'blog.naver.com/romantic_comedy_life',
   'postdate': '20251014'},
  {'title': '카카오뱅크 오늘의퀴즈 카카오뱅크 퀴즈정답 10월 14일 8시',
   'link': 'https://blog.naver.com/chip8076/224040473064',
   'description': "카카오뱅크의 플랫폼 경쟁력과 <b>핀테크</b> 전략 제목:  모바일 금융 혁신! 카카오뱅크의 비대면 금융... **'매달 생활비 돌려받기'**와 같은 서비스는 이러한 <b>핀테크</b> 경쟁력을 보여주는 단적인 예시입니다. 3-1.... ",
   'bloggername': '똑답 - 똑똑한 돈버는 퀴즈정답 사이트',
   'bloggerlink': 'blog.naver.com/chip8076',
   'postdate': '20251014'},
  {'title': '[네카오] 평이한 3분기 예상, 4분기 네카오 모두 기대',
   'link': 'https://blog.naver.com/won2582/224040470032',
   'description': '- 스테이블코인 제도화 시 국민과의 접점 및 <b>핀테크</b> 역량을 바탕으로 유통 경쟁력을 갖출 수 있는 플랫폼도 결국 NAVER와 카카오다. - 1) AI 정책 (소버린 AI, 클라우드) 관련 사업을 영위하고, 2)... ',
   'bloggername': '자이로콰이',
   'bloggerlink': 'blog.naver.com/won2582',
   'postdate': '20251014'},
  {'title': '[10월14일]꿈밍이의 아침브리핑',
   'link': 'https://blog.naver.com/ggumlog/224040468317',
   'description': '플랫폼 / 콘텐츠 / <b>핀테크</b> NAVER, NHN KCP, 케이씨에스 NAVER는 AI 검색과 라인야후 재편 기대감, NHN KCP는 소비 회복 기반 전자결제주 반등, 케이씨에스는 암호화폐·<b>핀테크</b> 테마로 단기 모멘텀 부각. 바이오... ',
   'bloggername': '꿈밍이의 경제 놀이터',
   'bloggerlink': 'blog.naver.com/ggumlog',
   'postdate': '20251014'},
  {'title': '내가 레미틀리 글로벌에 투자한이유[미국투자일지]',
   'link': 'https://blog.naver.com/valueflowmind/224040248546',
   'description': '회사개요:  레미틀리 글로벌 (Remittly Global Inc., RELY) 레미틀리 글로벌(Remittly)는 글로벌 송금 서비스를 제공하는 <b>핀테크</b> 기업으로, 스마트폰 앱을 통해 이민자 및 해외 노동자들이 자국에 돈을 쉽게 보낼... ',
   'bloggername': '플로우멘티 님의 블로그',
   'bloggerlink': 'blog.naver.com/valueflowmind',
   'postdate': '20251014'},
  {'title': '블록체인 기술이 금융 시스템을 바꾸는 방식',
   'link': 'https://blog.naver.com/ho87623/224038583193',
   'description': '법적·제도적 장치 마련 필요 기술 표준화 부족 일반 사용자 접근성 개선 보안 사고 대응 체계 구축 그럼에도 불구하고, 글로벌 은행과 <b>핀테크</b> 기업, 정부 기관까지 블록체인에 주목하고 있으며, 앞으로 5년... ',
   'bloggername': 'Junsh',
   'bloggerlink': 'blog.naver.com/ho87623',
   'postdate': '20251014'},
  {'title': '하나금융지주 주식 10년간 배당금 역사와 핵심 이슈 정리... ',
   'link': 'https://blog.naver.com/joylove_u/224030439791',
   'description': '하나금융지주 주식 투자, 배당 외에 주목할 이슈 고금리 환경 : 은행 이자이익 확대 효과 지속 가계부채 관리 : 금융당국 규제 강화 가능성 디지털 금융 확대 : <b>핀테크</b> 경쟁력 강화, 비용 절감 효과 글로벌... ',
   'bloggername': '경제의 과거와 현재, 미래',
   'bloggerlink': 'blog.naver.com/joylove_u',
   'postdate': '20251014'},
  {'title': '[Google Cloud] 클라르나(Klarna)와의 전략적 AI 파트너십... ',
   'link': 'https://blog.naver.com/inter200_200/224040465790',
   'description': '진화한 <b>핀테크</b> 분야의 거대 기업입니다. 이미 자사의 고객 서비스 챗봇에 AI를 도입하여 전체... 및 <b>핀테크</b> 산업에서 얼마나 강력한 가치를 창출할 수 있는지를 입증하는 중요한 성공 사례(Success... ',
   'bloggername': 'LLM(AI) 전문 - Microsoft AI MVP',
   'bloggerlink': 'blog.naver.com/inter200_200',
   'postdate': '20251014'},
  {'title': '트럼프 새로운 중동의 역사적 새벽…가자전쟁 끝났다... ',

In [7]:
print(type(response))

<class 'dict'>

In [8]:
response['items']

[{'title': '급여통장 신규 개설 및 인터넷뱅킹 신청 방법',
  'link': 'https://blog.naver.com/elow1957/224040614815',
  'description': '다른 <b>핀테크</b> 서비스의 대안 서론 요즘 대부분의 금융거래가 온라인으로 이루어지고 있습니다. 이에... 다른 <b>핀테크</b> 서비스의 대안 최근에는 카카오뱅크, 케이뱅크 등 인터넷 전문은행을 통한 다양한 통장... ',
  'bloggername': '내가 좋아하는것들',
  'bloggerlink': 'blog.naver.com/elow1957',
  'postdate': '20251014'},
 {'title': '전망좋은주식 미국 주식 종목 중심 분석',
  'link': 'https://blog.naver.com/wwlcc28/224040612860',
  'description': '에너지 저장, 5G 통신, <b>핀테크</b> 분야 또한 안정적인 성장세를 보이고 있습니다. 이런 흐름 속에서 주목받는 기업들은 기술력, 수익 구조, 시장 점유율 세 가지 기준에서 공통된 특징을 가집니다. “지속... ',
  'bloggername': 'wwlcc28님의 블로그',
  'bloggerlink': 'blog.naver.com/wwlcc28',
  'postdate': '20251014'},
 {'title': '인도 ETF｜RISE 인도디지털성장·KODEX 인도Nifty50·TIGER... ',
  'link': 'https://blog.naver.com/notinghel/224040610822',
  'description': 'MarketVector 지수를 추종하며, 인도의 인터넷·<b>핀테크</b>·통신·클라우드 기업들이 중심입니다.... IT, <b>핀테크</b>, 통신 대형주, 금융, 에너지 소비재, 서비스, 자동차 최근 NAV 수준 약 10,300원 약 13... ',
  'bloggername': 'notinghel님의 블로그',
  'bloggerlink': 'blog.naver.com/notinghel',
  'postdate': '20251014'},
 {'title': '감성지능: <b>핀테크</b> 고객 경험의 미래',
  'link': 'https://blog.naver.com/pxjlpss565/224040607064',
  'description': '감성지능: <b>핀테크</b> 고객 경험의 미래 <b>핀테크</b> 산업은 빠르게 발전하고 있으며, 이에 따라 고객 경험에 대한 요구도 더욱 증가하고 있다. 최근 감성지능 기술의 발전으로 <b>핀테크</b> 기업들은 더욱 개인화된 서비스를... ',
  'bloggername': '운동과 공부가 취미',
  'bloggerlink': 'blog.naver.com/pxjlpss565',
  'postdate': '20251014'},
 {'title': '[신한투자증권 미국주식 주요이슈] 챗GPT 내 즉시 결제... ',
  'link': 'https://blog.naver.com/shinhansec_official/224040598934',
  'description': '구글과 쇼핑 전쟁 : 이번 기능은 오픈AI의 자체 기술인 ‘에이전틱 커머스 프로토콜’과 <b>핀테크</b> 기업 스트라이프(Stripe)와의 협력을 통해 구현됐고, 앞으로 장바구니 기능 및 글로벌 확장도 계획 중이에요.... ',
  'bloggername': '신한투자증권 공식 블로그',
  'bloggerlink': 'blog.naver.com/shinhansec_official',
  'postdate': '20251014'},
 {'title': '영문계약서, 어디서부터 봐야 할까? 기본 구조와 핵심 조항... ',
  'link': 'https://blog.naver.com/legal_lemonade/224040593334',
  'description': 'About the Authour 국내 대형은행 법무팀에서 10년 이상 국제금융, 신용장, 영문계약서 및 외국환규제 자문 등을 담당하고, <b>핀테크</b> 기업에서 해외 지급결제와 해외 진출 등 다양한 프로젝트를 수행한... ',
  'bloggername': '리걸 레몬에이드',
  'bloggerlink': 'blog.naver.com/legal_lemonade',
  'postdate': '20251014'},
 {'title': '비트코인관련주 코인베이스 다날 우리기술투자 주가 분석',
  'link': 'https://blog.naver.com/fashiongreen/224040588409',
  'description': "기반 <b>핀테크</b> / 결제 플랫폼 기업으로 암호화폐 결제 플랫폼인 다날<b>핀테크</b>를 개발해 '페이코인'을 실생활 결제에 적용하는 등의 경험을 가지고 있는데요 이러한 기술력을 기반으로 스테이블코인 사업 진출... ",
  'bloggername': '돈 되는 경제만 쉽고 빠르게',
  'bloggerlink': 'blog.naver.com/fashiongreen',
  'postdate': '20251014'},
 {'title': '신용점수 올리는 방법 2025 최신 기준 정리',
  'link': 'https://blog.naver.com/sssolution1858/224039350975',
  'description': '정확한 진단 정직한 처방 고객과 상생을 도모하는 에스에스솔루션 2025년 들어 신용점수 제도가 한층 더 정교해졌다. 단순히 연체 없이 대출을 갚는 것만으로는 점수를 높이기 어렵고, 금융사마다 평가 기준이... ',
  'bloggername': 'Sssolution',
  'bloggerlink': 'blog.naver.com/sssolution1858',
  'postdate': '20251014'},
 {'title': 'RISE 인도디지털성장 ETF 완전정리｜인도 디지털 인프라... ',
  'link': 'https://blog.naver.com/notinghel/224040584997',
  'description': '이 ETF는 인도의 IT·통신·<b>핀테크</b>·디지털 인프라 산업을 대표하는 상장기업들로 구성되어... 디지털 인프라, 온라인 서비스, 통신, <b>핀테크</b>, 클라우드 등 인도의 정보기술 기반 산업 성장을... ',
  'bloggername': 'notinghel님의 블로그',
  'bloggerlink': 'blog.naver.com/notinghel',
  'postdate': '20251014'},
 {'title': '시니어 마케팅, 60대·70대·80대, 같은 ‘시니어’로 묶어선... ',
  'link': 'https://blog.naver.com/trotnewsofficial/224040583199',
  'description': '평생교육, 디지털 고급 교육(<b>핀테크</b>, AI 활용)을 제공하세요. 여가·문화·관광 바우처를 적극 활용하세요. 70대 정책: 안전 관리 만성질환 예방 바우처, 보안·사기 예방 교육을 확대하세요. 디지털 서비스에 1:1... ',
  'bloggername': '시니어마케팅 연구소',
  'bloggerlink': 'blog.naver.com/trotnewsofficial',
  'postdate': '20251014'},
 {'title': '신한은행 2026년 동계 청년인턴 채용 완벽 가이드 - 금융권... ',
  'link': 'https://blog.naver.com/cymmcymm/224040566983',
  'description': '결합된 <b>핀테크</b> 시대에 꼭 필요한 경험을 쌓을 수 있는 기회랍니다. 신한은행 청년인턴 지원 자격 조건... 금융권 취업을 준비하고 계신 분들, IT와 금융을 결합한 <b>핀테크</b> 분야에 관심 있는 분들 모두에게 정말... ',
  'bloggername': 'Creater Y',
  'bloggerlink': 'blog.naver.com/cymmcymm',
  'postdate': '20251014'},
 {'title': '“솔라나 × 한국 스테이블코인 — 주식시장에서 주목할... ',
  'link': 'https://blog.naver.com/hmn1204/224040565408',
  'description': '증가 <b>핀테크</b> / 결제 플랫폼 스테이블코인 → 결제/송금/정산 활용 가능성, 자체 플랫폼 내 사용... <b>핀테크</b> / 결제 플랫폼 회사 (예: 토스 등) 실제 보도가 있듯 토스(Toss)가 “원화 기반 스테이블코인 발행”을... ',
  'bloggername': '억만덕후의 이시대 살아남는법',
  'bloggerlink': 'blog.naver.com/hmn1204',
  'postdate': '20251014'},
 {'title': '미국의 파이어족이 불러올 경제의 나비효과',
  'link': 'https://blog.naver.com/garts44/224040562087',
  'description': '오늘날의 <b>핀테크</b>, 국채, 디지털 자산이 같은 역할을 하고 있습니다. 5️⃣ 소비재·유통 도시화와 중산층의 등장으로 전국 유통망이 생겼고, 시어스의 카탈로그와 코카콜라는 그 시대의 아이콘이었습니다.... ',
  'bloggername': '오늘 질문은...',
  'bloggerlink': 'blog.naver.com/garts44',
  'postdate': '20251014'},
 {'title': '[<b>핀테크</b> 기자단] 2025 K-DATA·신용보즘기금·한국<b>핀테크</b>지... ',
  'link': 'https://blog.naver.com/koreafintech/224040557226',
  'description': '지난 9월 18일 디캠프 프론트원에서 진행된 2025 K-DATA·신용보즘기금· 한국<b>핀테크</b>지원센터 IR DAY 데모데이에 <b>핀테크</b> 대학생 기자단이 현장취재를 다녀왔습니다! 각 기관이 지원하는 유망 스타트업들을... ',
  'bloggername': '한국핀테크지원센터',
  'bloggerlink': 'blog.naver.com/koreafintech',
  'postdate': '20251014'},
 {'title': '8월 서울 오피스 시장 분석 — 거래 급감에도 공실률은 하락',
  'link': 'https://blog.naver.com/jsh5015/224040557309',
  'description': 'AI, <b>핀테크</b>, 콘텐츠 업종 중심으로 오피스 입주 문의는 오히려 증가세.”  임대비용 — NOC 상승세... AI·<b>핀테크</b>·콘텐츠 산업 중심의 신규 오피스 수요 지속 하반기에는 강남·성수·여의도권 중심 재계약... ',
  'bloggername': '부동산과 경제 뉴스 정리, 분양 소식과 다양한 정보',
  'bloggerlink': 'blog.naver.com/jsh5015',
  'postdate': '20251014'},
 {'title': '증권사리포트 요약본 2025.10.14',
  'link': 'https://blog.naver.com/kwangpoong/224040556592',
  'description': '[035420] ˝AI, <b>핀테크</b>, 커머스˝ 모두 바쁨 ▶ 3Q25 Preview: 영업이익 5,579억원(+13.9% YoY)으로 컨센서스 하회 추정 ▶ 중장기 <b>핀테크</b> 사업 가치 부각 하나증권 이준호 카카오 [035720] 3분기 영업이익 1... ',
  'bloggername': '學習忍',
  'bloggerlink': 'blog.naver.com/kwangpoong',
  'postdate': '20251014'},
 {'title': '스테이블코인 결제시스템 3가지 핵심 변화 총정리',
  'link': 'https://blog.naver.com/law_sugarsquare/224035670742',
  'description': "* [상담문의]  02-563-5877  010-****-**** 카톡 '법무법인슈가스퀘어' 검색! 또는 카카오톡 상담링크  ****@sugar.legal #스테이블코인 #결제시스템 #<b>핀테크</b> #블록체인 #금융혁신",
  'bloggername': '법무법인 슈가스퀘어 블로그',
  'bloggerlink': 'blog.naver.com/law_sugarsquare',
  'postdate': '20251014'},
 {'title': '2025년 10월 14일 관심종목(주식)',
  'link': 'https://blog.naver.com/kk9550ch/224040546776',
  'description': 'idxno=3162806 아이티센피엔에스 - 통합 보안시스템+양자암호 솔루션 - <b>핀테크</b>, 스테이블코인 관련주 [특징주] 아이티센피엔에스, &quot;美 스테이블코인 규제법 통과&quot; 가상화폐 ... ',
  'bloggername': '재테크 in my life (feat.맛난음식)',
  'bloggerlink': 'blog.naver.com/kk9550ch',
  'postdate': '20251014'},
 {'title': '오늘자 이커머스 전망에 대해 알아보자',
  'link': 'https://blog.naver.com/pdion/224040542746',
  'description': '결제·<b>핀테크</b> 통합 BNPL(Buy Now Pay Later), 간편 결제, 디지털 월렛 등이 사용자 경험을 매끄럽게 할 것 마켓플레이스 재편 / 플랫폼 경쟁 플랫폼 간 제휴, 인수합병, 수수료 및 데이터 경쟁이 심화될 것 3. 기회... ',
  'bloggername': '피디온',
  'bloggerlink': 'blog.naver.com/pdion',
  'postdate': '20251014'},
 {'title': '코스피 시가총액 순위, 대한민국 TOP10 기업 성적표',
  'link': 'https://blog.naver.com/hanvit_lol/224040543213',
  'description': 'TOP10에 턱걸이로 안착했으며 <b>핀테크</b>, 콘텐츠, AI 삼박자를 앞세워서 제2의 도약을 노리고 있는 중이다. 이상으로 대한민국 경제의 심장인 코스피 TOP10 기업들의 역동적인 성적표 보았다. 25년의 성적표는 AI... ',
  'bloggername': '잘먹고 잘사는 오리좌',
  'bloggerlink': 'blog.naver.com/hanvit_lol',
  'postdate': '20251014'},
 {'title': '[비트코인 스탠다드]가 말하지 못한 것: GENIUS Act와 STABLE... ',
  'link': 'https://blog.naver.com/10000reading/224040540164',
  'description': '이 경우 카드 네트워크·은행 코어·<b>핀테크</b> 월렛이 스테이블코인 결제 레일을 품으며 **‘매끄러운... 은행-<b>핀테크</b>-카드사가 맺는 삼각 파트너십이 관건이다. 4) 체인 간 상호운용성과 계정 추상화 모바일... ',
  'bloggername': '일만리딩',
  'bloggerlink': 'blog.naver.com/10000reading',
  'postdate': '20251014'},
 {'title': '네이버·카카오, AI 전환으로 실적 폭발!',
  'link': 'https://blog.naver.com/smart-moneylog/224039305600',
  'description': '디지털 자산, <b>핀테크</b>, 블록체인 등 새로운 성장축이 확실히 잡히는 셈이죠. AI에다 가상자산까지... 앞으로의 관전 포인트 네이버는 AI로 쇼핑과 <b>핀테크</b>를, 카카오는 AI로 커뮤니케이션과 광고를 진화시키는... ',
  'bloggername': '스마트머니로그',
  'bloggerlink': 'blog.naver.com/smart-moneylog',
  'postdate': '20251014'},
 {'title': '비바리퍼블리카 주가 급등하는 이유, 2025년 상장 앞둔 토스의... ',
  'link': 'https://blog.naver.com/kwonmj1216/224022265678',
  'description': '최근 <b>핀테크</b> 업계에서 가장 뜨거운 관심을 받는 비바리퍼블리카에 대한 궁금증이었습니다. 실제로... 나 역시 <b>핀테크</b> 업계를 10년 넘게 지켜보면서 이만큼 탄탄한 실적 기반을 갖춘 회사를 본 적이 드물다고... ',
  'bloggername': '올인포',
  'bloggerlink': 'blog.naver.com/kwonmj1216',
  'postdate': '20251014'},
 {'title': 'AI가 리드하는 <b>핀테크</b> 혁신의 미래! : 서울 <b>핀테크</b> 위크 2025... ',
  'link': 'https://blog.naver.com/elmanproduction/224040539614',
  'description': '오늘은 서울 <b>핀테크</b> 위크 2025 홍보 영상 제작 후기를 들고 왔습니다. 로딩중,,, 글로번 <b>핀테크</b> 축제인 서울 <b>핀테크</b> 위크 2025가 곧 개최됩니다. 금융과 AI, <b>핀테크</b> 산업의 주요 이슈를 다루고 혁신적인... ',
  'bloggername': 'ELMAN 영상제작사',
  'bloggerlink': 'blog.naver.com/elmanproduction',
  'postdate': '20251014'},
 {'title': '벤처기업도 이제 ‘가상자산 거래업’을 할 수 있다!',
  'link': 'https://blog.naver.com/veteran01/224040538500',
  'description': '◆ 기대 효과 혁신 스타트업의 진입 확대: 블록체인 기술 기반의 <b>핀테크</b>, 거래 플랫폼, 토큰증권(STO) 등 다양한 영역에서 벤처기업들이 자유롭게 사업을 추진할 수 있습니다. 투자 활성화: 벤처기업 인증이... ',
  'bloggername': 'Not success but Service',
  'bloggerlink': 'blog.naver.com/veteran01',
  'postdate': '20251014'},
 {'title': '<b>핀테크</b>와 혁신의 만남 : 제4회 피노베이션 챌린지 행사 오프닝... ',
  'link': 'https://blog.naver.com/elmanproduction/224040533011',
  'description': '<b>핀테크</b>(Fintech)와 이노베이션(Innovation)을 합친 용어로, 서울시가 추진해온 프로그램입니다. <b>핀테크</b>, 인슈어테크, AI, 빅데이터 등 다양한 기술 역량을 가진 스타트업을 발굴하고, 금융사와의 공동 사업화를... ',
  'bloggername': 'ELMAN 영상제작사',
  'bloggerlink': 'blog.naver.com/elmanproduction',
  'postdate': '20251014'},
 {'title': '10월 14일. 투자자를 위한 뉴스 속 실마리 [자본시장 이슈... ',
  'link': 'https://blog.naver.com/numbersmembers/224040531979',
  'description': "https://www.insightkorea.co.kr/news/articleView.html?idxno=233417 Published on: 2025-10-13 15:34:00 가상자산 M&amp;A 3배 급증…금융·<b>핀테크</b> '합종연횡' 본격화 /전자신문 가상자산 업계 인수합병(M&amp;A) 발표가... ",
  'bloggername': 'M&A·지배구조·Deal·기업분석 뉴스 서비스 <넘버스>',
  'bloggerlink': 'blog.naver.com/numbersmembers',
  'postdate': '20251014'},
 {'title': '디지털 브레튼우즈의 서막: 달러·금의 시대를 넘어 블록체인... ',
  'link': 'https://blog.naver.com/10000reading/224040531447',
  'description': 'IMF·BIS와 함께 민간 PSP, <b>핀테크</b>, 은행 컨소시엄이 공동으로 의결권을 행사하여 권력 집중을 방지한다. 5~7년의 로드맵: 테스트넷에서 글로벌 표준으로 1단계에서는 CBDC 상호운용 최소규격과 디지털 SDR... ',
  'bloggername': '일만리딩',
  'bloggerlink': 'blog.naver.com/10000reading',
  'postdate': '20251014'},
 {'title': '[GPU Live] GPUaaS 서비스 GPU Live!',
  'link': 'https://blog.naver.com/nhn_injeinc/224039765197',
  'description': '✅ 금융·<b>핀테크</b> 산업 GPU Live는 금융기관에서 중요한 딥러닝 기반 이상거래 탐지(FDS), 신용평가 모델링, 고객 행동 분석 등대규모 연산이 필요한 금융 서비스 환경에 최적화되어 있습니다! GPU 자원을... ',
  'bloggername': 'NHN 인재아이엔씨',
  'bloggerlink': 'blog.naver.com/nhn_injeinc',
  'postdate': '20251014'},
 {'title': '채무통합대환대출조건 채무통합으로 시작하는 현명한 재무 관리',
  'link': 'https://blog.naver.com/my-loan-clinic/223949594538',
  'description': '금융사의 상품을 비교할 때 대출 비교 앱이나 <b>핀테크</b> 플랫폼을 적극 활용해 봐야 합니다. 통합 대출 시 발생할 수 있는 수수료나 추가 비용도 반드시 확인하셔야 합니다. 직접 금융 기관 상담이 어렵다면 전문가... ',
  'bloggername': '마이금융클리닉 공식블로그',
  'bloggerlink': 'blog.naver.com/my-loan-clinic',
  'postdate': '20251014'},
 {'title': '카드매출로 보증받는 법, 실전 가이드',
  'link': 'https://blog.naver.com/yj920621/224040121932',
  'description': '은행·<b>핀테크</b> 특례형) Tip: 현금 매출 비중이 높아도 카드·PG 매출 증빙 비율을 최대화하면 한도에 유리합니다. 준비물 체크리스트 - 필수 - 사업자등록증 사본 - 대표자 신분증 - 최근 6~12개월 카드매출 내역... ',
  'bloggername': '한국중소기업 지원센터',
  'bloggerlink': 'blog.naver.com/yj920621',
  'postdate': '20251014'},
 {'title': '가상자산: ‘벤처인증 허용’+‘대출 규제’ 병행… 산업은... ',
  'link': 'https://blog.naver.com/k3228452/224040522149',
  'description': '#가상자산 #크립토 #디지털자산 #벤처인증 #디지털자산기본법 #스테이블코인 #렌딩규제 #금리상한 #레버리지금지 #소비자보호 #공시의무 #내부통제 #준법감시 #리스크관리 #거래소 #커스터디 #<b>핀테크</b> #웹3',
  'bloggername': '한눈정책 – 핵심만 콕, 하루 한 장',
  'bloggerlink': 'blog.naver.com/k3228452',
  'postdate': '20251014'},
 {'title': 'Eat-Lancet이 제시한 이상적인 식단',
  'link': 'https://blog.naver.com/yelms/224040517993',
  'description': '이는 저렴한 식물성 단백질 기반의 간편식(HMR), 개인 맞춤형 구독 서비스, 혹은 건강한 식습관을 유도하는 챌린지 앱과 같은 <b>핀테크</b> 결합 서비스 등 무궁무진한 사업 기회를 의미한다. 2. 전통 식단의 보호와... ',
  'bloggername': '국경없는금융포럼',
  'bloggerlink': 'blog.naver.com/yelms',
  'postdate': '20251014'},
 {'title': '2025.10.14(화) 기업 리포트 요약 정리',
  'link': 'https://blog.naver.com/timulys/224040516473',
  'description': 'A035420 -˝AI, <b>핀테크</b>, 커머스˝ 모두 바쁨 3Q25 Preview: 영업이익 5,579억원(+13.9% YoY)으로 컨센서스 하회 추정 중장기 <b>핀테크</b> 사업 가치 부각 매수 320,000 262,500 SK증권 남효지 2025/10/14... ',
  'bloggername': '투자하는 행복',
  'bloggerlink': 'blog.naver.com/timulys',
  'postdate': '20251014'},
 {'title': '[TUO]10월14일 세계뉴스: 가자 휴전, 우크라 토마호크, EU... ',
  'link': 'https://blog.naver.com/world-response/224040514540',
  'description': '넷째, 유엔 사이버협약의 서명·비준 과정을 거치며 데이터 이전, 전자증거 교환, 플랫폼 책임 범위가 분명해지면 클라우드·보안·<b>핀테크</b> 기업의 규제 대응 비용과 수익 모델에도 변화가 생길 가능성이 큽니다.... ',
  'bloggername': '장대표의 인사이드 베트남',
  'bloggerlink': 'blog.naver.com/world-response',
  'postdate': '20251014'},
 {'title': 'Global Vicke 사기 투자 리딩방 미끼 완전 해부 (사칭)',
  'link': 'https://blog.naver.com/lucifer49329/224040508093',
  'description': '(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
  'bloggername': '데이 강민성 변호사',
  'bloggerlink': 'blog.naver.com/lucifer49329',
  'postdate': '20251014'},
 {'title': 'Angel❤️월세·전세금 부담 줄이는 혁신 서비스  보증금... ',
  'link': 'https://blog.naver.com/nyk34644/224040504261',
  'description': '이런 고민을 해결해주는 다양한 <b>핀테크</b> 서비스들이 등장하고 있어 관심이 집중되고 있습니다.... <b>핀테크</b> 스타트업 데브디에서 출시한 집업페이는 또 다른 혁신을 가져왔습니다. 바로 집주인의 동의 없이도... ',
  'bloggername': '작으면서 큰 부동산이야기',
  'bloggerlink': 'blog.naver.com/nyk34644',
  'postdate': '20251014'},
 {'title': '이직사유 예시 BEST 3, 면접 답변 꿀팁 총정리 &amp; 합격 전략!',
  'link': 'https://blog.naver.com/staffs00/224040498054',
  'description': '최근 <b>핀테크</b> 분야에 큰 관심을 갖게 되면서 귀사의 AI 기반 개인화 금융 서비스를 주목하게... 제가 보유한 대용량 데이터 처리 경험과 금융 도메인 지식을 바탕으로 귀사 AI <b>핀테크</b> 서비스의 안정성과 확장성... ',
  'bloggername': 'STAFFS STORY',
  'bloggerlink': 'blog.naver.com/staffs00',
  'postdate': '20251014'},
 {'title': '2030대가 선호하는 대기업 TOP10과 선택 이유',
  'link': 'https://blog.naver.com/rct190/224040494783',
  'description': '카카오 플랫폼, 콘텐츠, <b>핀테크</b> 등 영역을 넘나들며 혁신을 시도하는 모습이 2030대의 관심을 끌고 있습니다. “미래 가치가 기대된다”라는 평가와 함께 브랜드 이미지도 세련되고 젊은 감각이 강하다는... ',
  'bloggername': '파이어족의 경제, 금융 이야기',
  'bloggerlink': 'blog.naver.com/rct190',
  'postdate': '20251014'},
 {'title': '카카오페이 10월 14일 퀴즈 맞히고 복권 받기',
  'link': 'https://blog.naver.com/tkadla1422/224040494383',
  'description': '이처럼 통합 <b>핀테크</b> 플랫폼으로 진화하며 투자, 환전, 보험, 청구서 관리 등 다양한 금융 서비스를 통합 제공하는 점도 큰 강점입니다. 요약하면, 카카오페이는 카카오톡과의 완벽한 연동으로 쉽고 빠른 결제와... ',
  'bloggername': '김맹구의 탐구생활',
  'bloggerlink': 'blog.naver.com/tkadla1422',
  'postdate': '20251014'},
 {'title': '카카오뱅크 목표가 하향 대출 규제 속 성장 전망 분석 투자 전략!',
  'link': 'https://blog.naver.com/lottotem_economy/224040487251',
  'description': '가계대출 규제가 성장 전망치에 미친 구체적 영향 <b>핀테크</b> 리더로서 카카오뱅크는 저렴한 수신 확대를... 시장 컨센서스 비교 및 <b>핀테크</b> 주의 향후 주가 전망 KB증권이 제시한 28,000원의 목표주가는 최근 6개월... ',
  'bloggername': '경제톡',
  'bloggerlink': 'blog.naver.com/lottotem_economy',
  'postdate': '20251014'},
 {'title': '10/14 섹터별 현황',
  'link': 'https://blog.naver.com/mark-s/224040487497',
  'description': '93 <b>핀테크</b>(FinTech) 0.92 mRNA(메신저 리보핵산) 0.92 PCB(FPCB 등) 0.90 코로나19(치료제/백신 개발 등) 0.90 2025 상반기 신규상장 0.89 딥페이크(deepfake) 0.88 제습기 0.87 두나무(Dunamu) 0.86... ',
  'bloggername': 'Observer',
  'bloggerlink': 'blog.naver.com/mark-s',
  'postdate': '20251014'},
 {'title': '[보험업 컨설턴트 김희석] 2501014 주요 금융 뉴스',
  'link': 'https://blog.naver.com/cekhsgod/224040484905',
  'description': "독일 최대 인뱅 CEO 줄퇴진에 금감원 “<b>핀테크</b> 규제 완화 신중해야” (조선비즈, 10/13) 2.... 가상자산 M&amp;A 3배 급증…금융·<b>핀테크</b> '합종연횡' 본격화 (전자신문, 10/13) 6. ‘업비트 효과’ 넘어야... ",
  'bloggername': '벌교돌쇠의 성공 이야기',
  'bloggerlink': 'blog.naver.com/cekhsgod',
  'postdate': '20251014'},
 {'title': '5 best AI observability tools in 2025',
  'link': 'https://blog.naver.com/leejoon73/224040481556',
  'description': 'AI News <b>핀테크</b>(대출 승인가격) 특정 집단 승인율 급락 → 업스트림 파트너 데이터 시프트를 신속 진단·완화, 공정성·컴플라이언스 유지. AI News 고객지원(CX 추천) 특정 제품군에서 AI 추천이... ',
  'bloggername': 'leejoon73님의 블로그',
  'bloggerlink': 'blog.naver.com/leejoon73',
  'postdate': '20251014'},
 {'title': '금융 데이터 API, 누가 최강자? Plaid vs Yodlee vs... ',
  'link': 'https://blog.naver.com/standupandlight/224039728410',
  'description': '<b>핀테크</b> 핵심 기술, 3대 금융 데이터 API 완전 비교 Plaid vs Yodlee vs Finicity 상세 분석 <b>핀테크</b> 서비스의 핵심은 정확하고 빠른 금융 데이터 수집입니다. 이때 반드시 필요한 기술이 바로 금융 데이터... ',
  'bloggername': 'standupandlight',
  'bloggerlink': 'blog.naver.com/standupandlight',
  'postdate': '20251014'},
 {'title': 'NAVER 주가 전망, 목표주가와 재무제표까지 분석! 지금... ',
  'link': 'https://blog.naver.com/romantic_comedy_life/224040476869',
  'description': 'AI·클라우드·<b>핀테크</b> 등 신성장동력 사업 확장으로 다시 반등세를 보이고 있습니다. 오늘은... 광고, <b>핀테크</b>, 클라우드, 콘텐츠 등 최근 동향 : 네이버는 ‘AI 기술 고도화’를 핵심... ',
  'bloggername': '로코라이프 경제 블로그',
  'bloggerlink': 'blog.naver.com/romantic_comedy_life',
  'postdate': '20251014'},
 {'title': '카카오뱅크 오늘의퀴즈 카카오뱅크 퀴즈정답 10월 14일 8시',
  'link': 'https://blog.naver.com/chip8076/224040473064',
  'description': "카카오뱅크의 플랫폼 경쟁력과 <b>핀테크</b> 전략 제목:  모바일 금융 혁신! 카카오뱅크의 비대면 금융... **'매달 생활비 돌려받기'**와 같은 서비스는 이러한 <b>핀테크</b> 경쟁력을 보여주는 단적인 예시입니다. 3-1.... ",
  'bloggername': '똑답 - 똑똑한 돈버는 퀴즈정답 사이트',
  'bloggerlink': 'blog.naver.com/chip8076',
  'postdate': '20251014'},
 {'title': '[네카오] 평이한 3분기 예상, 4분기 네카오 모두 기대',
  'link': 'https://blog.naver.com/won2582/224040470032',
  'description': '- 스테이블코인 제도화 시 국민과의 접점 및 <b>핀테크</b> 역량을 바탕으로 유통 경쟁력을 갖출 수 있는 플랫폼도 결국 NAVER와 카카오다. - 1) AI 정책 (소버린 AI, 클라우드) 관련 사업을 영위하고, 2)... ',
  'bloggername': '자이로콰이',
  'bloggerlink': 'blog.naver.com/won2582',
  'postdate': '20251014'},
 {'title': '[10월14일]꿈밍이의 아침브리핑',
  'link': 'https://blog.naver.com/ggumlog/224040468317',
  'description': '플랫폼 / 콘텐츠 / <b>핀테크</b> NAVER, NHN KCP, 케이씨에스 NAVER는 AI 검색과 라인야후 재편 기대감, NHN KCP는 소비 회복 기반 전자결제주 반등, 케이씨에스는 암호화폐·<b>핀테크</b> 테마로 단기 모멘텀 부각. 바이오... ',
  'bloggername': '꿈밍이의 경제 놀이터',
  'bloggerlink': 'blog.naver.com/ggumlog',
  'postdate': '20251014'},
 {'title': '내가 레미틀리 글로벌에 투자한이유[미국투자일지]',
  'link': 'https://blog.naver.com/valueflowmind/224040248546',
  'description': '회사개요:  레미틀리 글로벌 (Remittly Global Inc., RELY) 레미틀리 글로벌(Remittly)는 글로벌 송금 서비스를 제공하는 <b>핀테크</b> 기업으로, 스마트폰 앱을 통해 이민자 및 해외 노동자들이 자국에 돈을 쉽게 보낼... ',
  'bloggername': '플로우멘티 님의 블로그',
  'bloggerlink': 'blog.naver.com/valueflowmind',
  'postdate': '20251014'},
 {'title': '블록체인 기술이 금융 시스템을 바꾸는 방식',
  'link': 'https://blog.naver.com/ho87623/224038583193',
  'description': '법적·제도적 장치 마련 필요 기술 표준화 부족 일반 사용자 접근성 개선 보안 사고 대응 체계 구축 그럼에도 불구하고, 글로벌 은행과 <b>핀테크</b> 기업, 정부 기관까지 블록체인에 주목하고 있으며, 앞으로 5년... ',
  'bloggername': 'Junsh',
  'bloggerlink': 'blog.naver.com/ho87623',
  'postdate': '20251014'},
 {'title': '하나금융지주 주식 10년간 배당금 역사와 핵심 이슈 정리... ',
  'link': 'https://blog.naver.com/joylove_u/224030439791',
  'description': '하나금융지주 주식 투자, 배당 외에 주목할 이슈 고금리 환경 : 은행 이자이익 확대 효과 지속 가계부채 관리 : 금융당국 규제 강화 가능성 디지털 금융 확대 : <b>핀테크</b> 경쟁력 강화, 비용 절감 효과 글로벌... ',
  'bloggername': '경제의 과거와 현재, 미래',
  'bloggerlink': 'blog.naver.com/joylove_u',
  'postdate': '20251014'},
 {'title': '[Google Cloud] 클라르나(Klarna)와의 전략적 AI 파트너십... ',
  'link': 'https://blog.naver.com/inter200_200/224040465790',
  'description': '진화한 <b>핀테크</b> 분야의 거대 기업입니다. 이미 자사의 고객 서비스 챗봇에 AI를 도입하여 전체... 및 <b>핀테크</b> 산업에서 얼마나 강력한 가치를 창출할 수 있는지를 입증하는 중요한 성공 사례(Success... ',
  'bloggername': 'LLM(AI) 전문 - Microsoft AI MVP',
  'bloggerlink': 'blog.naver.com/inter200_200',
  'postdate': '20251014'},
 {'title': '트럼프 새로운 중동의 역사적 새벽…가자전쟁 끝났다... ',
  'link': 'https://blog.naver.com/greatwisdomperfect/224040463750',
  'description': '스테이블 코인 제도화 및 <b>핀테크</b> 관련주 NHN KCP(주봉) • 주요 내용: 구현철 부총리는 공공기관 통폐합 등 정부 구조 개편 방향을 밝히는 한편, 스테이블 코인 도입을 자본 유출입 리스크를 보완하며 혁신적인... ',
  'bloggername': '수익은 길게, 손실은 짧게',
  'bloggerlink': 'blog.naver.com/greatwisdomperfect',
  'postdate': '20251014'},
 {'title': '카카오페이 주가 전망, 금리 인하 기대에 반등 신호 포착될까?',
  'link': 'https://blog.naver.com/vipro/224040422483',

In [10]:
# import pandas as pd

In [11]:
# pd.DataFrame(response['items'])

,title,link,description,bloggername,bloggerlink,postdate
0,급여통장 신규 개설 및 인터넷뱅킹 신청 방법,https://blog.naver.com/elow1957/224040614815,다른 <b>핀테크</b> 서비스의 대안 서론 요즘 대부분의 금융거래가 온라인으로 이...,내가 좋아하는것들,blog.naver.com/elow1957,20251014
1,전망좋은주식 미국 주식 종목 중심 분석,https://blog.naver.com/wwlcc28/224040612860,"에너지 저장, 5G 통신, <b>핀테크</b> 분야 또한 안정적인 성장세를 보이고 ...",wwlcc28님의 블로그,blog.naver.com/wwlcc28,20251014
2,인도 ETF｜RISE 인도디지털성장·KODEX 인도Nifty50·TIGER...,https://blog.naver.com/notinghel/224040610822,"MarketVector 지수를 추종하며, 인도의 인터넷·<b>핀테크</b>·통신·클...",notinghel님의 블로그,blog.naver.com/notinghel,20251014
3,감성지능: <b>핀테크</b> 고객 경험의 미래,https://blog.naver.com/pxjlpss565/224040607064,감성지능: <b>핀테크</b> 고객 경험의 미래 <b>핀테크</b> 산업은 빠르게 ...,운동과 공부가 취미,blog.naver.com/pxjlpss565,20251014
4,[신한투자증권 미국주식 주요이슈] 챗GPT 내 즉시 결제...,https://blog.naver.com/shinhansec_official/224...,구글과 쇼핑 전쟁 : 이번 기능은 오픈AI의 자체 기술인 ‘에이전틱 커머스 프로토콜...,신한투자증권 공식 블로그,blog.naver.com/shinhansec_official,20251014
...,...,...,...,...,...,...
95,투자의 미래를 여는 열쇠: '디지털 자산' 알아보기!,https://blog.naver.com/jaysalon/224037601407,"비트코인, NFT(대체 불가능 토큰), 그리고 최근 큰 화두가 되고 있는 토큰증권(...",김제이님의 블로그,blog.naver.com/jaysalon,20251014
96,농협 햇살론뱅크 조건과 신청방법 후기 확인하기,https://sibauchi.tistory.com/1132,그리고 <b>핀테크</b> 기업의 경쟁 심화라는 복합적인 요인으로 인해 끊임없이 변...,Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평,https://sibauchi.tistory.com/,20251014
97,네이버 VS 카카오 왜? 안오르지 스트레스 주식,https://blog.naver.com/eyhs80/224040392311,"플랫폼 중심 사업 구조 카카오톡이라는 강력한 메신저 기반이 있고, 이 위에 광고, ...",정보는 본느 좋은 정보,blog.naver.com/eyhs80,20251014
98,근로복지공단 의료비대출 신청절차와 이용조건 정리,https://think-tank.tistory.com/894,그리고 <b>핀테크</b> 기업의 등장 등 다양한 요인에 의해 끊임없이 변화해왔습니...,think-tank.tistory.com,https://think-tank.tistory.com/,20251014
99,"정부지원 서민대출, 아는 사람만 챙겨가는 꿀팁 (서민금융대출)",https://blog.naver.com/grijoa0/224035563350,특히 요즘은 토스나 카카오뱅크 같은 <b>핀테크</b> 앱에서도 일부 상품 조회가 ...,Money Bridge와 함께 자산투자,blog.naver.com/grijoa0,20251014

In [59]:
import re
def text_clean(text):
    # html 태그를 없애는 정규표현식
    result = re.sub(r"</?[^>]+>", "", text)
    # 한글, 영문, 숫자 외의 모든 문자 제거 후 공백으로 변환
    result = re.sub(r"[^가-힣a-zA-Z0-9]", " ", result)
    result = result.replace("  ", " ").replace("  ", " ").replace("  ", " ")
    return result

In [13]:
result = {}
for item in response['items']:
    for key, value in item.items():
        if key in ["title", "description"]:
            result.setdefault(key, []).append(text_clean(value))
        else:
            result.setdefault(key, []).append(value)
result

{'title': ['급여통장 신규 개설 및 인터넷뱅킹 신청 방법',
  '전망좋은주식 미국 주식 종목 중심 분석',
  '인도 ETF RISE 인도디지털성장 KODEX 인도Nifty50 TIGER ',
  '감성지능 핀테크 고객 경험의 미래',
  ' 신한투자증권 미국주식 주요이슈 챗GPT 내 즉시 결제 ',
  '영문계약서 어디서부터 봐야 할까 기본 구조와 핵심 조항 ',
  '비트코인관련주 코인베이스 다날 우리기술투자 주가 분석',
  '신용점수 올리는 방법 2025 최신 기준 정리',
  'RISE 인도디지털성장 ETF 완전정리 인도 디지털 인프라 ',
  '시니어 마케팅 60대 70대 80대 같은 시니어 로 묶어선 ',
  '신한은행 2026년 동계 청년인턴 채용 완벽 가이드 금융권 ',
  ' 솔라나 한국 스테이블코인 주식시장에서 주목할 ',
  '미국의 파이어족이 불러올 경제의 나비효과',
  ' 핀테크 기자단 2025 K DATA 신용보즘기금 한국핀테크지 ',
  '8월 서울 오피스 시장 분석 거래 급감에도 공실률은 하락',
  '증권사리포트 요약본 2025 10 14',
  '스테이블코인 결제시스템 3가지 핵심 변화 총정리',
  '2025년 10월 14일 관심종목 주식 ',
  '오늘자 이커머스 전망에 대해 알아보자',
  '코스피 시가총액 순위 대한민국 TOP10 기업 성적표',
  ' 비트코인 스탠다드 가 말하지 못한 것 GENIUS Act와 STABLE ',
  '네이버 카카오 AI 전환으로 실적 폭발 ',
  '비바리퍼블리카 주가 급등하는 이유 2025년 상장 앞둔 토스의 ',
  'AI가 리드하는 핀테크 혁신의 미래 서울 핀테크 위크 2025 ',
  '벤처기업도 이제 가상자산 거래업 을 할 수 있다 ',
  '핀테크와 혁신의 만남 제4회 피노베이션 챌린지 행사 오프닝 ',
  '10월 14일 투자자를 위한 뉴스 속 실마리 자본시장 이슈 ',
  '디지털 브레튼우즈의 서막 달러 금의 시대를 넘어 블록체인 ',
  ' GPU Live GPUaaS 서비스 GPU Live ',
  '채무통합대환대출조건 채무통합으로 시작하는 현명한 재무 관리',
  '카드매출로 보증받는 법 실전 가이드',
  '가상자산 벤처인증 허용 대출 규제 병행 산업은 ',
  'Eat Lancet이 제시한 이상적인 식단',
  '2025 10 14 화 기업 리포트 요약 정리',
  ' TUO 10월14일 세계뉴스 가자 휴전 우크라 토마호크 EU ',
  'Global Vicke 사기 투자 리딩방 미끼 완전 해부 사칭 ',
  'Angel 월세 전세금 부담 줄이는 혁신 서비스 보증금 ',
  '이직사유 예시 BEST 3 면접 답변 꿀팁 총정리 amp 합격 전략 ',
  '2030대가 선호하는 대기업 TOP10과 선택 이유',
  '카카오페이 10월 14일 퀴즈 맞히고 복권 받기',
  '카카오뱅크 목표가 하향 대출 규제 속 성장 전망 분석 투자 전략 ',
  '10 14 섹터별 현황',
  ' 보험업 컨설턴트 김희석 2501014 주요 금융 뉴스',
  '5 best AI observability tools in 2025',
  '금융 데이터 API 누가 최강자 Plaid vs Yodlee vs ',
  'NAVER 주가 전망 목표주가와 재무제표까지 분석 지금 ',
  '카카오뱅크 오늘의퀴즈 카카오뱅크 퀴즈정답 10월 14일 8시',
  ' 네카오 평이한 3분기 예상 4분기 네카오 모두 기대',
  ' 10월14일 꿈밍이의 아침브리핑',
  '내가 레미틀리 글로벌에 투자한이유 미국투자일지 ',
  '블록체인 기술이 금융 시스템을 바꾸는 방식',
  '하나금융지주 주식 10년간 배당금 역사와 핵심 이슈 정리 ',
  ' Google Cloud 클라르나 Klarna 와의 전략적 AI 파트너십 ',
  '트럼프 새로운 중동의 역사적 새벽 가자전쟁 끝났다 ',
  '카카오페이 주가 전망 금리 인하 기대에 반등 신호 포착될까 ',
  'SK텔레콤 자급제 전용 요금제 Air 출시 약정 보조금 ',
  '광주은행 햇살론15 신청자격과 재대출 후기',
  ' 100개 주식의 오늘 10월 14일 증시 대탐험 ',
  ' 10월 14일 대한민국 증시 하이라이트 30개 주식의 오늘과 ',
  '리드코프 주부대출 신청조건과 재대출 가능여부 확인',
  '신한 쏠편한 비상금대출 신청 절차와 실제 이용 후기',
  '중국이 한국 국채 주식 부동산을 사들이는 이유는 ',
  '스테이블코인 이제 누가 어떻게 허가하고 무엇을 지켜야 ',
  ' 개인 중심 금융은 끝났다 이제는 가족 단위 플랫폼 경쟁 ',
  ' 산업 기업 직무분석 시리즈 45 핀테크 디지털 금융 취업 ',
  '신용사면 대상자 조회 방법 및 조건 나도 회복 가능할까 ',
  ' 2025년10월14일 화요일 미장 정리 amp 국장 준',
  '2026년 100 이상 쏴줄 주식 레드와이어 종목추천 및 ',
  '말레이시아 vs 한국 직장인 평균 연봉 물가 경제규모 ',
  '우리은행 사잇돌 대출 자격조건 및 한도 계산 방법',
  '말라위 vs 한국 직장인 평균 연봉 물가 경제규모 최저임금 ',
  '농협카드 단기대출 급전 필요할 때 활용하는 방법',
  '마카오 vs 한국 직장인 평균 연봉 물가 경제규모 최저임금 ',
  '4대보험 미가입자 대환대출 최적의 시기 선택 방법',
  ' 성투 2025년 10월 14일 장전아침시황 모닝브리핑 주식시황 ',
  '마이크로네시아 vs 한국 직장인 평균 연봉 물가 경제규모 ',
  '마셜제도 vs 한국 직장인 평균 연봉 물가 경제규모 최저임금 ',
  '사업자대환대출 금리 비교 핵심 꿀팁 완벽 분석',
  '2025년 10월14일 화 보험인기 검색어',
  '보험설계사 제보 제대로 된 보험생활 ',
  '2025년 10월14일 화 오늘의 5분 생활소식',
  '2025년 10월13일 월 오늘의 5분 생활소식',
  '2025년 10월14일 화 오늘의 1분 시사 경제 상식',
  '2025년 10월13일 월 오늘의 1분 시사 경제 상식',
  '2026년 트렌드코리아 요약본',
  '2025년 10월14일 화 노주영의 보험 뉴스 링크 소식',
  '2025년10월14일 화 노주영 5분뉴스브리핑 amp 보험소식 ',
  '2025년10월13일 월 노주영 5분뉴스브리핑 amp 보험소식 10월 ',
  '2025년10월2일 목 노주영 5분뉴스브리핑 amp 보험소식',
  '2025년10월1일 수 노주영 5분뉴스브리핑 amp 보험소식 10월 ',
  '케이뱅크 사업자대출 신청자격과 금리 혜택 총정리',
  '휴대폰 대출 간편 신청 방법과 신용 영향 분석',
  ' 달러패권 9장면 디지털 달러와 스테이블코인 코드로 진화한 ',
  '10월 14일 카카오페이 퀴즈 정답',
  '양자보안과 반도체의 만남 BTQ 테크놀로지가 여는 차세대 ',
  '투자의 미래를 여는 열쇠 디지털 자산 알아보기 ',
  '농협 햇살론뱅크 조건과 신청방법 후기 확인하기',
  '네이버 VS 카카오 왜 안오르지 스트레스 주식',
  '근로복지공단 의료비대출 신청절차와 이용조건 정리',
  '정부지원 서민대출 아는 사람만 챙겨가는 꿀팁 서민금융대출 '],
 'link': ['https://blog.naver.com/elow1957/224040614815',
  'https://blog.naver.com/wwlcc28/224040612860',
  'https://blog.naver.com/notinghel/224040610822',
  'https://blog.naver.com/pxjlpss565/224040607064',
  'https://blog.naver.com/shinhansec_official/224040598934',
  'https://blog.naver.com/legal_lemonade/224040593334',
  'https://blog.naver.com/fashiongreen/224040588409',
  'https://blog.naver.com/sssolution1858/224039350975',
  'https://blog.naver.com/notinghel/224040584997',
  'https://blog.naver.com/trotnewsofficial/224040583199',
  'https://blog.naver.com/cymmcymm/224040566983',
  'https://blog.naver.com/hmn1204/224040565408',
  'https://blog.naver.com/garts44/224040562087',
  'https://blog.naver.com/koreafintech/224040557226',
  'https://blog.naver.com/jsh5015/224040557309',
  'https://blog.naver.com/kwangpoong/224040556592',
  'https://blog.naver.com/law_sugarsquare/224035670742',
  'https://blog.naver.com/kk9550ch/224040546776',
  'https://blog.naver.com/pdion/224040542746',
  'https://blog.naver.com/hanvit_lol/224040543213',
  'https://blog.naver.com/10000reading/224040540164',
  'https://blog.naver.com/smart-moneylog/224039305600',
  'https://blog.naver.com/kwonmj1216/224022265678',
  'https://blog.naver.com/elmanproduction/224040539614',
  'https://blog.naver.com/veteran01/224040538500',
  'https://blog.naver.com/elmanproduction/224040533011',
  'https://blog.naver.com/numbersmembers/224040531979',
  'https://blog.naver.com/10000reading/224040531447',
  'https://blog.naver.com/nhn_injeinc/224039765197',
  'https://blog.naver.com/my-loan-clinic/223949594538',
  'https://blog.naver.com/yj920621/224040121932',
  'https://blog.naver.com/k3228452/224040522149',
  'https://blog.naver.com/yelms/224040517993',
  'https://blog.naver.com/timulys/224040516473',
  'https://blog.naver.com/world-response/224040514540',
  'https://blog.naver.com/lucifer49329/224040508093',
  'https://blog.naver.com/nyk34644/224040504261',
  'https://blog.naver.com/staffs00/224040498054',
  'https://blog.naver.com/rct190/224040494783',
  'https://blog.naver.com/tkadla1422/224040494383',
  'https://blog.naver.com/lottotem_economy/224040487251',
  'https://blog.naver.com/mark-s/224040487497',
  'https://blog.naver.com/cekhsgod/224040484905',
  'https://blog.naver.com/leejoon73/224040481556',
  'https://blog.naver.com/standupandlight/224039728410',
  'https://blog.naver.com/romantic_comedy_life/224040476869',
  'https://blog.naver.com/chip8076/224040473064',
  'https://blog.naver.com/won2582/224040470032',
  'https://blog.naver.com/ggumlog/224040468317',
  'https://blog.naver.com/valueflowmind/224040248546',
  'https://blog.naver.com/ho87623/224038583193',
  'https://blog.naver.com/joylove_u/224030439791',
  'https://blog.naver.com/inter200_200/224040465790',
  'https://blog.naver.com/greatwisdomperfect/224040463750',
  'https://blog.naver.com/vipro/224040422483',
  'https://blog.naver.com/futuretechinsights/224040438769',
  'https://sibauchi.tistory.com/1145',
  'https://blog.naver.com/cjrnrdmlskan/224040436480',
  'https://blog.naver.com/cjrnrdmlskan/224040435390',
  'https://sibauchi.tistory.com/1128',
  'https://sibauchi.tistory.com/1112',
  'https://blog.naver.com/h2otube/224026638318',
  'https://blog.naver.com/topec_eng/224040429132',
  'https://blog.naver.com/futuretechinsights/224040428790',
  'https://blog.naver.com/jobmasterplan/223988807886',
  'https://blog.naver.com/whitetree1288/224038430106',
  'https://blog.naver.com/krcn1215/224040423917',
  'https://blog.naver.com/jusik_men/224040421616',
  'https://blog.naver.com/lifetraveller/224040419934',
  'https://ilovefamily.tistory.com/535',
  'https://blog.naver.com/lifetraveller/224040418734',
  'https://think-tank.tistory.com/893',
  'https://blog.naver.com/lifetraveller/224040417366',
  'https://blog.naver.com/mgaoften/224040417049',
  'https://blog.naver.com/3030stockstory/224040416530',
  'https://blog.naver.com/lifetraveller/224040415614',
  'https://blog.naver.com/lifetraveller/224040414098',
  'https://blog.naver.com/mgaoften/224040412854',
  'https://blog.naver.com/dailynewsbriefing/224040405761',
  'https://blog.naver.com/dailynewsbriefing/224040405156',
  'https://blog.naver.com/dailynewsbriefing/224040404884',
  'https://blog.naver.com/dailynewsbriefing/224040404681',
  'https://blog.naver.com/dailynewsbriefing/224040403691',
  'https://blog.naver.com/dailynewsbriefing/224040403517',
  'https://blog.naver.com/dailynewsbriefing/224040402888',
  'https://blog.naver.com/dailynewsbriefing/224040402341',
  'https://blog.naver.com/dailynewsbriefing/224040401260',
  'https://blog.naver.com/dailynewsbriefing/224040401022',
  'https://blog.naver.com/dailynewsbriefing/224040400381',
  'https://blog.naver.com/dailynewsbriefing/224040400050',
  'https://sibauchi.tistory.com/1141',
  'https://ilovefamily.tistory.com/524',
  'https://blog.naver.com/red2x2/224036785614',
  'https://blog.naver.com/answernow_/224039873357',
  'https://blog.naver.com/honmoon_/224040252444',
  'https://blog.naver.com/jaysalon/224037601407',
  'https://sibauchi.tistory.com/1132',
  'https://blog.naver.com/eyhs80/224040392311',
  'https://think-tank.tistory.com/894',
  'https://blog.naver.com/grijoa0/224035563350'],
 'description': ['다른 핀테크 서비스의 대안 서론 요즘 대부분의 금융거래가 온라인으로 이루어지고 있습니다 이에 다른 핀테크 서비스의 대안 최근에는 카카오뱅크 케이뱅크 등 인터넷 전문은행을 통한 다양한 통장 ',
  '에너지 저장 5G 통신 핀테크 분야 또한 안정적인 성장세를 보이고 있습니다 이런 흐름 속에서 주목받는 기업들은 기술력 수익 구조 시장 점유율 세 가지 기준에서 공통된 특징을 가집니다 지속 ',
  'MarketVector 지수를 추종하며 인도의 인터넷 핀테크 통신 클라우드 기업들이 중심입니다 IT 핀테크 통신 대형주 금융 에너지 소비재 서비스 자동차 최근 NAV 수준 약 10 300원 약 13 ',
  '감성지능 핀테크 고객 경험의 미래 핀테크 산업은 빠르게 발전하고 있으며 이에 따라 고객 경험에 대한 요구도 더욱 증가하고 있다 최근 감성지능 기술의 발전으로 핀테크 기업들은 더욱 개인화된 서비스를 ',
  '구글과 쇼핑 전쟁 이번 기능은 오픈AI의 자체 기술인 에이전틱 커머스 프로토콜 과 핀테크 기업 스트라이프 Stripe 와의 협력을 통해 구현됐고 앞으로 장바구니 기능 및 글로벌 확장도 계획 중이에요 ',
  'About the Authour 국내 대형은행 법무팀에서 10년 이상 국제금융 신용장 영문계약서 및 외국환규제 자문 등을 담당하고 핀테크 기업에서 해외 지급결제와 해외 진출 등 다양한 프로젝트를 수행한 ',
  '기반 핀테크 결제 플랫폼 기업으로 암호화폐 결제 플랫폼인 다날핀테크를 개발해 페이코인 을 실생활 결제에 적용하는 등의 경험을 가지고 있는데요 이러한 기술력을 기반으로 스테이블코인 사업 진출 ',
  '정확한 진단 정직한 처방 고객과 상생을 도모하는 에스에스솔루션 2025년 들어 신용점수 제도가 한층 더 정교해졌다 단순히 연체 없이 대출을 갚는 것만으로는 점수를 높이기 어렵고 금융사마다 평가 기준이 ',
  '이 ETF는 인도의 IT 통신 핀테크 디지털 인프라 산업을 대표하는 상장기업들로 구성되어 디지털 인프라 온라인 서비스 통신 핀테크 클라우드 등 인도의 정보기술 기반 산업 성장을 ',
  '평생교육 디지털 고급 교육 핀테크 AI 활용 을 제공하세요 여가 문화 관광 바우처를 적극 활용하세요 70대 정책 안전 관리 만성질환 예방 바우처 보안 사기 예방 교육을 확대하세요 디지털 서비스에 1 1 ',
  '결합된 핀테크 시대에 꼭 필요한 경험을 쌓을 수 있는 기회랍니다 신한은행 청년인턴 지원 자격 조건 금융권 취업을 준비하고 계신 분들 IT와 금융을 결합한 핀테크 분야에 관심 있는 분들 모두에게 정말 ',
  '증가 핀테크 결제 플랫폼 스테이블코인 결제 송금 정산 활용 가능성 자체 플랫폼 내 사용 핀테크 결제 플랫폼 회사 예 토스 등 실제 보도가 있듯 토스 Toss 가 원화 기반 스테이블코인 발행 을 ',
  '오늘날의 핀테크 국채 디지털 자산이 같은 역할을 하고 있습니다 5 소비재 유통 도시화와 중산층의 등장으로 전국 유통망이 생겼고 시어스의 카탈로그와 코카콜라는 그 시대의 아이콘이었습니다 ',
  '지난 9월 18일 디캠프 프론트원에서 진행된 2025 K DATA 신용보즘기금 한국핀테크지원센터 IR DAY 데모데이에 핀테크 대학생 기자단이 현장취재를 다녀왔습니다 각 기관이 지원하는 유망 스타트업들을 ',
  'AI 핀테크 콘텐츠 업종 중심으로 오피스 입주 문의는 오히려 증가세 임대비용 NOC 상승세 AI 핀테크 콘텐츠 산업 중심의 신규 오피스 수요 지속 하반기에는 강남 성수 여의도권 중심 재계약 ',
  ' 035420 AI 핀테크 커머스 모두 바쁨 3Q25 Preview 영업이익 5 579억원 13 9 YoY 으로 컨센서스 하회 추정 중장기 핀테크 사업 가치 부각 하나증권 이준호 카카오 035720 3분기 영업이익 1 ',
  ' 상담문의 02 563 5877 010  카톡 법무법인슈가스퀘어 검색 또는 카카오톡 상담링크 sugar legal 스테이블코인 결제시스템 핀테크 블록체인 금융혁신',
  'idxno 3162806 아이티센피엔에스 통합 보안시스템 양자암호 솔루션 핀테크 스테이블코인 관련주 특징주 아이티센피엔에스 quot 스테이블코인 규제법 통과 quot 가상화폐 ',
  '결제 핀테크 통합 BNPL Buy Now Pay Later 간편 결제 디지털 월렛 등이 사용자 경험을 매끄럽게 할 것 마켓플레이스 재편 플랫폼 경쟁 플랫폼 간 제휴 인수합병 수수료 및 데이터 경쟁이 심화될 것 3 기회 ',
  'TOP10에 턱걸이로 안착했으며 핀테크 콘텐츠 AI 삼박자를 앞세워서 제2의 도약을 노리고 있는 중이다 이상으로 대한민국 경제의 심장인 코스피 TOP10 기업들의 역동적인 성적표 보았다 25년의 성적표는 AI ',
  '이 경우 카드 네트워크 은행 코어 핀테크 월렛이 스테이블코인 결제 레일을 품으며 매끄러운 은행 핀테크 카드사가 맺는 삼각 파트너십이 관건이다 4 체인 간 상호운용성과 계정 추상화 모바일 ',
  '디지털 자산 핀테크 블록체인 등 새로운 성장축이 확실히 잡히는 셈이죠 AI에다 가상자산까지 앞으로의 관전 포인트 네이버는 AI로 쇼핑과 핀테크를 카카오는 AI로 커뮤니케이션과 광고를 진화시키는 ',
  '최근 핀테크 업계에서 가장 뜨거운 관심을 받는 비바리퍼블리카에 대한 궁금증이었습니다 실제로 나 역시 핀테크 업계를 10년 넘게 지켜보면서 이만큼 탄탄한 실적 기반을 갖춘 회사를 본 적이 드물다고 ',
  '오늘은 서울 핀테크 위크 2025 홍보 영상 제작 후기를 들고 왔습니다 로딩중 글로번 핀테크 축제인 서울 핀테크 위크 2025가 곧 개최됩니다 금융과 AI 핀테크 산업의 주요 이슈를 다루고 혁신적인 ',
  ' 기대 효과 혁신 스타트업의 진입 확대 블록체인 기술 기반의 핀테크 거래 플랫폼 토큰증권 STO 등 다양한 영역에서 벤처기업들이 자유롭게 사업을 추진할 수 있습니다 투자 활성화 벤처기업 인증이 ',
  '핀테크 Fintech 와 이노베이션 Innovation 을 합친 용어로 서울시가 추진해온 프로그램입니다 핀테크 인슈어테크 AI 빅데이터 등 다양한 기술 역량을 가진 스타트업을 발굴하고 금융사와의 공동 사업화를 ',
  'https www insightkorea co kr news articleView html idxno 233417 Published on 2025 10 13 15 34 00 가상자산 M amp A 3배 급증 금융 핀테크 합종연횡 본격화 전자신문 가상자산 업계 인수합병 M amp A 발표가 ',
  'IMF BIS와 함께 민간 PSP 핀테크 은행 컨소시엄이 공동으로 의결권을 행사하여 권력 집중을 방지한다 5 7년의 로드맵 테스트넷에서 글로벌 표준으로 1단계에서는 CBDC 상호운용 최소규격과 디지털 SDR ',
  ' 금융 핀테크 산업 GPU Live는 금융기관에서 중요한 딥러닝 기반 이상거래 탐지 FDS 신용평가 모델링 고객 행동 분석 등대규모 연산이 필요한 금융 서비스 환경에 최적화되어 있습니다 GPU 자원을 ',
  '금융사의 상품을 비교할 때 대출 비교 앱이나 핀테크 플랫폼을 적극 활용해 봐야 합니다 통합 대출 시 발생할 수 있는 수수료나 추가 비용도 반드시 확인하셔야 합니다 직접 금융 기관 상담이 어렵다면 전문가 ',
  '은행 핀테크 특례형 Tip 현금 매출 비중이 높아도 카드 PG 매출 증빙 비율을 최대화하면 한도에 유리합니다 준비물 체크리스트 필수 사업자등록증 사본 대표자 신분증 최근 6 12개월 카드매출 내역 ',
  ' 가상자산 크립토 디지털자산 벤처인증 디지털자산기본법 스테이블코인 렌딩규제 금리상한 레버리지금지 소비자보호 공시의무 내부통제 준법감시 리스크관리 거래소 커스터디 핀테크 웹3',
  '이는 저렴한 식물성 단백질 기반의 간편식 HMR 개인 맞춤형 구독 서비스 혹은 건강한 식습관을 유도하는 챌린지 앱과 같은 핀테크 결합 서비스 등 무궁무진한 사업 기회를 의미한다 2 전통 식단의 보호와 ',
  'A035420 AI 핀테크 커머스 모두 바쁨 3Q25 Preview 영업이익 5 579억원 13 9 YoY 으로 컨센서스 하회 추정 중장기 핀테크 사업 가치 부각 매수 320 000 262 500 SK증권 남효지 2025 10 14 ',
  '넷째 유엔 사이버협약의 서명 비준 과정을 거치며 데이터 이전 전자증거 교환 플랫폼 책임 범위가 분명해지면 클라우드 보안 핀테크 기업의 규제 대응 비용과 수익 모델에도 변화가 생길 가능성이 큽니다 ',
  ' 사칭 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '이런 고민을 해결해주는 다양한 핀테크 서비스들이 등장하고 있어 관심이 집중되고 있습니다 핀테크 스타트업 데브디에서 출시한 집업페이는 또 다른 혁신을 가져왔습니다 바로 집주인의 동의 없이도 ',
  '최근 핀테크 분야에 큰 관심을 갖게 되면서 귀사의 AI 기반 개인화 금융 서비스를 주목하게 제가 보유한 대용량 데이터 처리 경험과 금융 도메인 지식을 바탕으로 귀사 AI 핀테크 서비스의 안정성과 확장성 ',
  '카카오 플랫폼 콘텐츠 핀테크 등 영역을 넘나들며 혁신을 시도하는 모습이 2030대의 관심을 끌고 있습니다 미래 가치가 기대된다 라는 평가와 함께 브랜드 이미지도 세련되고 젊은 감각이 강하다는 ',
  '이처럼 통합 핀테크 플랫폼으로 진화하며 투자 환전 보험 청구서 관리 등 다양한 금융 서비스를 통합 제공하는 점도 큰 강점입니다 요약하면 카카오페이는 카카오톡과의 완벽한 연동으로 쉽고 빠른 결제와 ',
  '가계대출 규제가 성장 전망치에 미친 구체적 영향 핀테크 리더로서 카카오뱅크는 저렴한 수신 확대를 시장 컨센서스 비교 및 핀테크 주의 향후 주가 전망 KB증권이 제시한 28 000원의 목표주가는 최근 6개월 ',
  '93 핀테크 FinTech 0 92 mRNA 메신저 리보핵산 0 92 PCB FPCB 등 0 90 코로나19 치료제 백신 개발 등 0 90 2025 상반기 신규상장 0 89 딥페이크 deepfake 0 88 제습기 0 87 두나무 Dunamu 0 86 ',
  '독일 최대 인뱅 CEO 줄퇴진에 금감원 핀테크 규제 완화 신중해야 조선비즈 10 13 2 가상자산 M amp A 3배 급증 금융 핀테크 합종연횡 본격화 전자신문 10 13 6 업비트 효과 넘어야 ',
  'AI News 핀테크 대출 승인가격 특정 집단 승인율 급락 업스트림 파트너 데이터 시프트를 신속 진단 완화 공정성 컴플라이언스 유지 AI News 고객지원 CX 추천 특정 제품군에서 AI 추천이 ',
  '핀테크 핵심 기술 3대 금융 데이터 API 완전 비교 Plaid vs Yodlee vs Finicity 상세 분석 핀테크 서비스의 핵심은 정확하고 빠른 금융 데이터 수집입니다 이때 반드시 필요한 기술이 바로 금융 데이터 ',
  'AI 클라우드 핀테크 등 신성장동력 사업 확장으로 다시 반등세를 보이고 있습니다 오늘은 광고 핀테크 클라우드 콘텐츠 등 최근 동향 네이버는 AI 기술 고도화 를 핵심 ',
  '카카오뱅크의 플랫폼 경쟁력과 핀테크 전략 제목 모바일 금융 혁신 카카오뱅크의 비대면 금융 매달 생활비 돌려받기 와 같은 서비스는 이러한 핀테크 경쟁력을 보여주는 단적인 예시입니다 3 1 ',
  ' 스테이블코인 제도화 시 국민과의 접점 및 핀테크 역량을 바탕으로 유통 경쟁력을 갖출 수 있는 플랫폼도 결국 NAVER와 카카오다 1 AI 정책 소버린 AI 클라우드 관련 사업을 영위하고 2 ',
  '플랫폼 콘텐츠 핀테크 NAVER NHN KCP 케이씨에스 NAVER는 AI 검색과 라인야후 재편 기대감 NHN KCP는 소비 회복 기반 전자결제주 반등 케이씨에스는 암호화폐 핀테크 테마로 단기 모멘텀 부각 바이오 ',
  '회사개요 레미틀리 글로벌 Remittly Global Inc RELY 레미틀리 글로벌 Remittly 는 글로벌 송금 서비스를 제공하는 핀테크 기업으로 스마트폰 앱을 통해 이민자 및 해외 노동자들이 자국에 돈을 쉽게 보낼 ',
  '법적 제도적 장치 마련 필요 기술 표준화 부족 일반 사용자 접근성 개선 보안 사고 대응 체계 구축 그럼에도 불구하고 글로벌 은행과 핀테크 기업 정부 기관까지 블록체인에 주목하고 있으며 앞으로 5년 ',
  '하나금융지주 주식 투자 배당 외에 주목할 이슈 고금리 환경 은행 이자이익 확대 효과 지속 가계부채 관리 금융당국 규제 강화 가능성 디지털 금융 확대 핀테크 경쟁력 강화 비용 절감 효과 글로벌 ',
  '진화한 핀테크 분야의 거대 기업입니다 이미 자사의 고객 서비스 챗봇에 AI를 도입하여 전체 및 핀테크 산업에서 얼마나 강력한 가치를 창출할 수 있는지를 입증하는 중요한 성공 사례 Success ',
  '스테이블 코인 제도화 및 핀테크 관련주 NHN KCP 주봉 주요 내용 구현철 부총리는 공공기관 통폐합 등 정부 구조 개편 방향을 밝히는 한편 스테이블 코인 도입을 자본 유출입 리스크를 보완하며 혁신적인 ',
  '대표 핀테크 플랫폼이다 이런 성장형 기업들은 금리가 높은 시기에는 미래 이익의 가치가 할인되어 단기적인 변동성은 있겠지만 중장기적으로 카카오페이는 한국 핀테크 산업을 대표하는 핵심 성장주로 ',
  'SK텔레콤이 새로운 자급제 전용 요금제 브랜드 Air 에어 를 공식 출시했습니다 Air 는 기존 이동통신사의 복잡한 요금 체계와 약정 보조금 중심의 구조에서 벗어나 심플하고 디지털 중심적인 ',
  '그리고 핀테크의 성장이라는 삼중고를 겪었습니다 금리 인상은 대출 수요를 위축시키고 연체율 핀테크 기업들은 간편한 대출 심사 및 실행 시스템을 통해 시장 점유율을 확대하고 있지만 고금리 논란과 ',
  'NAVER 262 500원 플랫폼 콘텐츠 핀테크 등 다각화된 사업 구조가 장점이자 복잡성 요소 기아 101 핀테크 경쟁력과 규제 흐름이 중요하다 삼양식품 1 429 000원 식품 사업 중심 소비 흐름 변화에 ',
  '포털 콘텐츠 핀테크 등 여러 축을 가진 NAVER 인터넷 경제의 흐름 변화와 함께 수익 구조 변화가 메신저 플랫폼 핀테크 모빌리티까지 카카오는 여러 사업 축을 긋고 있다 12 2차전지 소재 기업 ',
  '강화 핀테크 기업의 등장 등 다양한 요인에 의해 끊임없이 변화해왔습니다 특히 금리 인상은 대출 상환 부담을 가중시켜 신규 대출 신청을 망설이게 하는 요인으로 작용했습니다 동시에 핀테크 기업들은 ',
  '강화 핀테크 기업의 적극적인 참여 등 다양한 요인으로 인해 역동적인 변화를 겪었습니다 특히 금리 인상은 소비자들의 대출 부담을 가중시켰고 정부의 대출 규제는 대출 문턱을 높였습니다 반면 핀테크 ',
  '토스 핀테크 ETF 등 국채 금리와 채권형 펀드 중국 매도 시 금리 상승 가능 금리 변동성에 따른 채권 자금유입과리스크 핀테크중국투자 경제블로그 2025산업트렌드 한국주식중국자본 부동산투자이슈 ',
  'gov 현실 뉴욕 등 주 별 라이선스와 카드 핀테크 파트너십으로 달러 스테이블코인 우위 지속 6 일부 12 전면 시행 SBSB 핀테크 변호사 영국 적격 스테이블코인 발행 커스터디 허가 결제 ',
  '은행 카드사 핀테크 기업들이 앞다투어 가족 단위 자산관리 서비스를 내놓고 있죠 이는 단순히 한 사람의 고객을 붙잡는 것이 아니라 가족 전체를 하나의 고객 생태계로 묶어 장기 관계를 형성하려는 ',
  '서론 왜 핀테크 디지털 금융 산업인가 핀테크 디지털 금융 산업은 금융과 기술의 융합으로 빠르게 성장하며 금융 서비스의 패러다임을 바꾸고 있습니다 결제 송금 간편결제 해외송금 전자지갑 ',
  '나이스평가정보 NICE 코리아크레딧뷰로 KCB 등 신용평가사 홈페이지는 물론 토스 Toss 와 같은 핀테크 앱의 관련 메뉴를 통해서도 간편하게 조회가 가능합니다 이미 상환을 완료한 약 258만 명은 즉시 ',
  '코인 상승은 일부 게임 핀테크 관련주에 시행착오성 모멘텀 제공 5 오늘 트레이딩 포인트 한국 투자자용 핵심 인사이트 3가지 반도체 AI 관련 종목은 단기 모멘텀 강하지만 이벤트 리스크 존재 ',
  '레드와이어 Redwire 기업 심층 분석 우주 인프라에서 국방 기술 강자로의 도약 I 요약 본 보고서는 레드와이어 Redwire Corporation NYSE RDW 에 대한 종합적인 분석을 제공한다 레드와이어는 유산과 혁신 ',
  '핀테크 이슬람 금융 리스크 규제 결제 7 석유 가스 프로세스 HSE 무결성관리 회수개선 8 금융 핀테크 퀀트 리스크 11 공기업 공공데이터 정책 감사 12 콘텐츠 이벤트 관광 플랫폼 7 ',
  ' 지난 1년간 사잇돌 대출 시장은 금리 인상 대출 규제 변화 그리고 핀테크 기업들의 공격적인 진출 핀테크 플랫폼을 통한 사잇돌 대출 비교 및 신청 서비스가 더욱 확대될 것이며 은행들은 자체적인 ',
  '통신 모바일 핀테크 MFS 운영 에이전트 네트워크 현장 영업 10 식품 안전 검사 표준 품질 규격 금융 핀테크 리스크 퀀트 11 스마트시티 인프라 교통체계 12 콘텐츠 스포츠 MICE 13 ESG ',
  '핀테크 기업들의 공세적인 마케팅과 간편한 대출 절차는 기존 금융권에 긴장감을 불어넣었으며 플랫폼 또한 핀테크 기업과의 경쟁 심화에 따른 과도한 마케팅 경쟁을 지양하고 건전한 금융 생태계를 ',
  '현대 금융 리스크 규제 결제 핀테크 백오피스 10 빅헬스 전통의학 연계 R amp D 임상보조 운영 11 핀테크 결제 리스크 퀀트 리걸테크 11 콘텐츠 라이브이벤트 스포츠 관광 12 도시 인프라 ',
  '온라인 플랫폼 비교 핀테크 기업들이 제공하는 대출 비교 플랫폼을 활용하면 여러 금융기관의 대출 상품을 한 번에 비교할 수 있습니다 시간과 노력을 절약하고 자신에게 맞는 최적의 상품을 찾는데 도움이 ',
  '관련주 NAVER NHN KCP 뱅크웨어글로벌 등 네 카 토 지분 쥔 증권사들 스테이블코인 수혜 꽃놀이패 방긋 네이버 카카오 토스 등 이른바 국내 대표 핀테크 계열사 지분을 보유한 증권사들이 ',
  '금융핀테크 공공 경제규모와 산업구조 한국 명목 GDP는 최근치 기준 약 1조7천억 달러대 수출 금융 핀테크 데이터리스크 규제테크 결제 여신 IT 퀀트가 유망합니다 10 공기업 공공기관 에너지 ',
  '금융 핀테크 콘텐츠 2 경제규모와 구조 비교 한국 명목 GDP 약 1 71조 달러 2023년 수출 주도형 금융 핀테크 데이터리스크 퀀트 규제테크 10 공기업 공공기관 에너지 인프라 정책집행 지원 팁 ',
  '온라인 금리 비교 플랫폼 활용 은행연합회 소비자포털 핀테크 업체의 대출 비교 플랫폼 등 온라인에서 다양한 금융기관의 대출 상품을 한눈에 비교할 수 있습니다 간단한 정보 입력만으로 예상 금리와 한도를 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '사이버보안 핀테크 디지털전환 ESG경영 사회적책임투자 윤리적소비 가치소비 친환경 제로웨이스트 비건 동물복지 공정무역 기부 후원 봉사 나눔 상생 협력 소통 공감 존중 배려 이해 관용 정의 ',
  '그리고 핀테크 기업의 성장이라는 세 가지 주요 요인에 의해 크게 변화했습니다 금리 인상은 반면 케이뱅크를 포함한 핀테크 기업들은 비대면 대출 서비스를 통해 접근성을 높이며 시장 점유율을 ',
  '특히 핀테크 기술의 발전은 은행 방문 없이 서류 제출 없이 스마트폰 앱 하나로 대출을 받을 수 있는 그리고 핀테크 기업들의 활약이라는 삼박자가 맞물리면서 역동적인 변화를 겪었습니다 특히 고금리 ',
  '미국 유럽의 B2B 결제와 핀테크 DeFi Decentralizaed Finance 탈중앙화 금융 연동 영역에서 국채 중심의 고품질 준비금과 투명한 공시를 앞세워 규제 친화성을 확보하였고 그 결과 전통 금융과 연결된 제도권 ',
  '카카오페이 입장에서는 자사의 이미지를 글로벌 핀테크 플랫폼 으로 성장시키는 게 중요한 전략 중 하나예요 이런 전략이 실생활 속 콘텐츠에도 녹아들고 있기 때문에 퀴즈타임 역시 이 세계화된 흐름을 ',
  '이러한 변화는 단순히 보안 산업의 문제를 넘어 블록체인 AI 핀테크 국방 등 모든 데이터 기반 산업의 기반을 새로 짜는 수준의 전환점이 될 것으로 보입니다 양자보안 블록체인 새로운 신뢰 구조 ',
  '비트코인 NFT 대체 불가능 토큰 그리고 최근 큰 화두가 되고 있는 토큰증권 STO 까지 우리는 지금 디지털 자산 Digital Asset 이라는 새로운 경제 패러다임의 한가운데에 서 있습니다 더 이상 종이 서류나 실물 ',
  '그리고 핀테크 기업의 경쟁 심화라는 복합적인 요인으로 인해 끊임없이 변화해왔습니다 특히 금리 인상은 대출 문턱을 높여 저신용 저소득층의 자금 접근성을 악화시키는 주요 원인이 되었습니다 핀테크 ',

In [15]:
df = pd.DataFrame(result)
df.to_csv("./data/requests로naver_api데이터수집.csv", index=False, encoding="utf-8-sig")

# python-dotenv로 api  key 안전하게 사용하기
* .env 파일에 환경변수를 저장하고 python 코드에서 자동으로 불러오는 모듈
* pip install python-dotenv
* .env 파일을 만들어서 변수=값 형태로 내용 저장
``` python
from dotenv import load_dotenv
import os

load_dotenv()  # 같은 폴더에 .env 파일이 있을 경우 자동으로 불러옴
# 환경변수 내용 출력
user_id = os.getenv("Id")
secret = os.getenv("Secret")

```

# .env 경로를 다른 곳으로 주거나 이름을 바꾸고 싶을 때
* load_dotenv("경로및 파일명")
``` python
from dotenv import load_dotenv
import os

load_dotenv(dotenv_path="./data/.env_naver")  # ./data 폴더에 .env_naver 를 불러올 때
# 환경변수 내용 출력
user_id = os.getenv("Id")
secret = os.getenv("Secret")

```

In [17]:
from dotenv import load_dotenv
import os
load_dotenv()
import requests

user_id = os.getenv("Id")
user_secret = os.getenv("Secret")
url = "https://openapi.naver.com/v1/search/blog"
keyword = "핀테크"
payload = dict(query=keyword, display=100, start=1, sort="date")
headers = {"X-Naver-Client-Id" : user_id, "X-Naver-Client-Secret" : user_secret}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()
response

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
200

{'lastBuildDate': 'Tue, 14 Oct 2025 11:40:21 +0900',
 'total': 476763,
 'start': 1,
 'display': 100,
 'items': [{'title': '변화와 미래 전망:금융권 동향부터 디지털 혁신,<b>핀테크</b>까지',
   'link': 'https://blog.naver.com/dth73819/224040643226',
   'description': '금융산업 변화와 미래전망 : 금융권 동향부터 디지털 혁신, <b>핀테크</b> 까지 안녕하세요,금융에 관심있는 여러분! 최근 금융 산업은 빠르게 변화하고 있습니다. 전통 금융권은 물론, 디지털 금융과 <b>핀테크</b>까지... ',
   'bloggername': '삽살개',
   'bloggerlink': 'blog.naver.com/dth73819',
   'postdate': '20251014'},
  {'title': '[도약 프로그램] 2025 중소기업 지원, 도약(Jump-Up)... ',
   'link': 'https://blog.naver.com/fki_lsc/224040446624',
   'description': '서비스 <b>핀테크</b>, 인슈어테크, 로보어드바이저, 디지털 뱅킹 등 전문 및 교육 서비스 에듀테크, 온라인 교육 플랫폼, 디자인 컨설팅 등 친환경 및 스마트인프라 신재생에너지 태양광, 풍력, 수소에너지, 지열... ',
   'bloggername': '한경협중소기업협력센터',
   'bloggerlink': 'blog.naver.com/fki_lsc',
   'postdate': '20251014'},
  {'title': '실리콘밸리 <b>핀테크</b> 하프모어, 딥코어 리드 투자로 누적 35억 원... ',
   'link': 'https://blog.naver.com/ksvalley/224040630287',
   'description': '딥코어 관계자는 &quot;하프모어는 강력한 초기 성과와 넓은 금융 웰니스로의 확장 잠재력을 갖췄다&quot;며 투자 배경을 밝혔다.',
   'bloggername': 'k스타트업 밸리',
   'bloggerlink': 'blog.naver.com/ksvalley',
   'postdate': '20251014'},
  {'title': '2025년 10월 14일 - 15일 미국주식정보(25.10.14... ',
   'link': 'https://blog.naver.com/wnguddhkd/224040630301',
   'description': '기대 • <b>핀테크</b>: GS, PYPL(PayPal), MQ(Marqeta) ‘매도’ 하향 – 마진 압박 및 집중 리스크 지적 5️⃣ 자산시장 동향 • 채권시장 휴장(Columbus Day)으로 변동 제한. WTI $59.95, Gold $4,114로 상승... ',
   'bloggername': '호기심',
   'bloggerlink': 'blog.naver.com/wnguddhkd',
   'postdate': '20251014'},
  {'title': '[CTN정보]꼭 읽어야 할 서울시소식',
   'link': 'https://blog.naver.com/ggh7000/224040630580',
   'description': '(금) ‘(재)서울투자진흥재단 창립총회’ 개최…설립 전 주요사항 심의 및 의결 - 창립총회 이후, 법인설립 허가 및 등기 등 제반 절차 거쳐 10월말 출범 목표 - GFCI 3년 연속 Top10, <b>핀테크</b> 8위 최초... ',
   'bloggername': 'CTN신문사',
   'bloggerlink': 'blog.naver.com/ggh7000',
   'postdate': '20251014'},
  {'title': '가족간 차용증 이자율 부모자식 형제 작성법(양식 무료다운)',
   'link': 'https://blog.naver.com/kapbue/224040628117',
   'description': '<b>핀테크</b> 기반의 앱을 통해 변호사 검토가 포함된 계약서를 작성할 수 있으며, 본인 인증까지 완료되어 법적 효력을 갖출 수 있습니다. 전자 차용증은 종이보다 보관이 쉽고 분실 위험도 적어 요즘 많은 분들이... ',
   'bloggername': '호치스의 50억 만드는 부동산',
   'bloggerlink': 'blog.naver.com/kapbue',
   'postdate': '20251014'},
  {'title': '무직자도 OK! 지금 바로 대출 가능?',
   'link': 'https://blog.naver.com/himse/224040621180',
   'description': '<b>핀테크</b> 기술의 발전과 더불어 청년, 취업준비생, 사회초년생 등 다양한 계층을 위한 맞춤형 대출 상품이 쏟아져 나오고 있어요.은행 문턱이 높다고 좌절하지 마세요. 2금융권, <b>핀테크</b> 기업 등 다양한 곳에서... ',
   'bloggername': '아파트 담보대출 전문! OK자산관리대부',
   'bloggerlink': 'blog.naver.com/himse',
   'postdate': '20251014'},
  {'title': '2025년 노벨 경제학상 - “창조적 파괴”',
   'link': 'https://blog.naver.com/jeenu123/224040620030',
   'description': '✅ <b>핀테크</b>·디지털 금융: Toss 등 — 은행·결제 시스템의 경쟁 재구성 무엇이 바뀌었나: Toss 등 <b>핀테크</b>는 간편송금·금융서비스를 통해 전통 은행의 소매금융 일부를 잠식하고, 사용자 경험을 재정의.... ',
   'bloggername': 'Humus',
   'bloggerlink': 'blog.naver.com/jeenu123',
   'postdate': '20251014'},
  {'title': '패스트파이브, 올 상반기 재계약률 94%...‘믿고 찾는 사무실... ',
   'link': 'https://blog.naver.com/phenomdark/224040619773',
   'description': '실제 장기 입주 기업 중 한 곳인 글로벌 <b>핀테크</b> 기업 와이어바알리는 2019년 첫 입주 이후 6년 이상 패스트파이브를 거점 오피스로 사용해 왔다. 와이어바알리는 성장 단계마다 필요한 규모와 입지를 유연하게... ',
   'bloggername': 'SHOW MUST GO ON..',
   'bloggerlink': 'blog.naver.com/phenomdark',
   'postdate': '20251014'},
  {'title': '7편 – PG(Payment Gateway)란 무엇인가',
   'link': 'https://blog.naver.com/dydwo7151-/224040619374',
   'description': 'PG의 진화 – <b>핀테크</b>와 함께 가는 길 최근 PG 산업은 단순한 결제 중개를 넘어 데이터 기반 정산, 마케팅, 소비 분석을 제공하는 방향으로 발전하고 있습니다. 또한 블록체인 기술과 결합해, 국경 없는... ',
   'bloggername': 'dydwo7151-님의 블로그',
   'bloggerlink': 'blog.naver.com/dydwo7151-',
   'postdate': '20251014'},
  {'title': '전자금융공동망은 어떻게 진화했을까, 미래 금융의 뿌리',
   'link': 'https://blog.naver.com/rlocate/224040618979',
   'description': "넘어 '금융기관과 <b>핀테크</b> 기업의 연결 허브'로 확장되었습니다 <b>핀테크</b> 기업들은 중앙은행이 관리하는 공동망을 통해 은행의 핵심 결제 기능에 접근할 수 있게 되었고 이는 간편 송금, 간편 결제 등 다양한... ",
   'bloggername': '미소 지는 순간',
   'bloggerlink': 'blog.naver.com/rlocate',
   'postdate': '20251014'},
  {'title': '급여통장 신규 개설 및 인터넷뱅킹 신청 방법',
   'link': 'https://blog.naver.com/elow1957/224040614815',
   'description': '다른 <b>핀테크</b> 서비스의 대안 서론 요즘 대부분의 금융거래가 온라인으로 이루어지고 있습니다. 이에... 다른 <b>핀테크</b> 서비스의 대안 최근에는 카카오뱅크, 케이뱅크 등 인터넷 전문은행을 통한 다양한 통장... ',
   'bloggername': '내가 좋아하는것들',
   'bloggerlink': 'blog.naver.com/elow1957',
   'postdate': '20251014'},
  {'title': '전망좋은주식 미국 주식 종목 중심 분석',
   'link': 'https://blog.naver.com/wwlcc28/224040612860',
   'description': '에너지 저장, 5G 통신, <b>핀테크</b> 분야 또한 안정적인 성장세를 보이고 있습니다. 이런 흐름 속에서 주목받는 기업들은 기술력, 수익 구조, 시장 점유율 세 가지 기준에서 공통된 특징을 가집니다. “지속... ',
   'bloggername': 'wwlcc28님의 블로그',
   'bloggerlink': 'blog.naver.com/wwlcc28',
   'postdate': '20251014'},
  {'title': '인도 ETF｜RISE 인도디지털성장·KODEX 인도Nifty50·TIGER... ',
   'link': 'https://blog.naver.com/notinghel/224040610822',
   'description': 'MarketVector 지수를 추종하며, 인도의 인터넷·<b>핀테크</b>·통신·클라우드 기업들이 중심입니다.... IT, <b>핀테크</b>, 통신 대형주, 금융, 에너지 소비재, 서비스, 자동차 최근 NAV 수준 약 10,300원 약 13... ',
   'bloggername': 'notinghel님의 블로그',
   'bloggerlink': 'blog.naver.com/notinghel',
   'postdate': '20251014'},
  {'title': '감성지능: <b>핀테크</b> 고객 경험의 미래',
   'link': 'https://blog.naver.com/pxjlpss565/224040607064',
   'description': '감성지능: <b>핀테크</b> 고객 경험의 미래 <b>핀테크</b> 산업은 빠르게 발전하고 있으며, 이에 따라 고객 경험에 대한 요구도 더욱 증가하고 있다. 최근 감성지능 기술의 발전으로 <b>핀테크</b> 기업들은 더욱 개인화된 서비스를... ',
   'bloggername': '운동과 공부가 취미',
   'bloggerlink': 'blog.naver.com/pxjlpss565',
   'postdate': '20251014'},
  {'title': '[신한투자증권 미국주식 주요이슈] 챗GPT 내 즉시 결제... ',
   'link': 'https://blog.naver.com/shinhansec_official/224040598934',
   'description': '구글과 쇼핑 전쟁 : 이번 기능은 오픈AI의 자체 기술인 ‘에이전틱 커머스 프로토콜’과 <b>핀테크</b> 기업 스트라이프(Stripe)와의 협력을 통해 구현됐고, 앞으로 장바구니 기능 및 글로벌 확장도 계획 중이에요.... ',
   'bloggername': '신한투자증권 공식 블로그',
   'bloggerlink': 'blog.naver.com/shinhansec_official',
   'postdate': '20251014'},
  {'title': '영문계약서, 어디서부터 봐야 할까? 기본 구조와 핵심 조항... ',
   'link': 'https://blog.naver.com/legal_lemonade/224040593334',
   'description': 'About the Authour 국내 대형은행 법무팀에서 10년 이상 국제금융, 신용장, 영문계약서 및 외국환규제 자문 등을 담당하고, <b>핀테크</b> 기업에서 해외 지급결제와 해외 진출 등 다양한 프로젝트를 수행한... ',
   'bloggername': '리걸 레몬에이드',
   'bloggerlink': 'blog.naver.com/legal_lemonade',
   'postdate': '20251014'},
  {'title': '비트코인관련주 코인베이스 다날 우리기술투자 주가 분석',
   'link': 'https://blog.naver.com/fashiongreen/224040588409',
   'description': "기반 <b>핀테크</b> / 결제 플랫폼 기업으로 암호화폐 결제 플랫폼인 다날<b>핀테크</b>를 개발해 '페이코인'을 실생활 결제에 적용하는 등의 경험을 가지고 있는데요 이러한 기술력을 기반으로 스테이블코인 사업 진출... ",
   'bloggername': '돈 되는 경제만 쉽고 빠르게',
   'bloggerlink': 'blog.naver.com/fashiongreen',
   'postdate': '20251014'},
  {'title': '신용점수 올리는 방법 2025 최신 기준 정리',
   'link': 'https://blog.naver.com/sssolution1858/224039350975',
   'description': '정확한 진단 정직한 처방 고객과 상생을 도모하는 에스에스솔루션 2025년 들어 신용점수 제도가 한층 더 정교해졌다. 단순히 연체 없이 대출을 갚는 것만으로는 점수를 높이기 어렵고, 금융사마다 평가 기준이... ',
   'bloggername': 'Sssolution',
   'bloggerlink': 'blog.naver.com/sssolution1858',
   'postdate': '20251014'},
  {'title': 'RISE 인도디지털성장 ETF 완전정리｜인도 디지털 인프라... ',
   'link': 'https://blog.naver.com/notinghel/224040584997',
   'description': '이 ETF는 인도의 IT·통신·<b>핀테크</b>·디지털 인프라 산업을 대표하는 상장기업들로 구성되어... 디지털 인프라, 온라인 서비스, 통신, <b>핀테크</b>, 클라우드 등 인도의 정보기술 기반 산업 성장을... ',
   'bloggername': 'notinghel님의 블로그',
   'bloggerlink': 'blog.naver.com/notinghel',
   'postdate': '20251014'},
  {'title': '시니어 마케팅, 60대·70대·80대, 같은 ‘시니어’로 묶어선... ',
   'link': 'https://blog.naver.com/trotnewsofficial/224040583199',
   'description': '평생교육, 디지털 고급 교육(<b>핀테크</b>, AI 활용)을 제공하세요. 여가·문화·관광 바우처를 적극 활용하세요. 70대 정책: 안전 관리 만성질환 예방 바우처, 보안·사기 예방 교육을 확대하세요. 디지털 서비스에 1:1... ',
   'bloggername': '시니어마케팅 연구소',
   'bloggerlink': 'blog.naver.com/trotnewsofficial',
   'postdate': '20251014'},
  {'title': '신한은행 2026년 동계 청년인턴 채용 완벽 가이드 - 금융권... ',
   'link': 'https://blog.naver.com/cymmcymm/224040566983',
   'description': '결합된 <b>핀테크</b> 시대에 꼭 필요한 경험을 쌓을 수 있는 기회랍니다. 신한은행 청년인턴 지원 자격 조건... 금융권 취업을 준비하고 계신 분들, IT와 금융을 결합한 <b>핀테크</b> 분야에 관심 있는 분들 모두에게 정말... ',
   'bloggername': 'Creater Y',
   'bloggerlink': 'blog.naver.com/cymmcymm',
   'postdate': '20251014'},
  {'title': '“솔라나 × 한국 스테이블코인 — 주식시장에서 주목할... ',
   'link': 'https://blog.naver.com/hmn1204/224040565408',
   'description': '증가 <b>핀테크</b> / 결제 플랫폼 스테이블코인 → 결제/송금/정산 활용 가능성, 자체 플랫폼 내 사용... <b>핀테크</b> / 결제 플랫폼 회사 (예: 토스 등) 실제 보도가 있듯 토스(Toss)가 “원화 기반 스테이블코인 발행”을... ',
   'bloggername': '억만덕후의 이시대 살아남는법',
   'bloggerlink': 'blog.naver.com/hmn1204',
   'postdate': '20251014'},
  {'title': '미국의 파이어족이 불러올 경제의 나비효과',
   'link': 'https://blog.naver.com/garts44/224040562087',
   'description': '오늘날의 <b>핀테크</b>, 국채, 디지털 자산이 같은 역할을 하고 있습니다. 5️⃣ 소비재·유통 도시화와 중산층의 등장으로 전국 유통망이 생겼고, 시어스의 카탈로그와 코카콜라는 그 시대의 아이콘이었습니다.... ',
   'bloggername': '오늘 질문은...',
   'bloggerlink': 'blog.naver.com/garts44',
   'postdate': '20251014'},
  {'title': '[<b>핀테크</b> 기자단] 2025 K-DATA·신용보즘기금·한국<b>핀테크</b>지... ',
   'link': 'https://blog.naver.com/koreafintech/224040557226',
   'description': '지난 9월 18일 디캠프 프론트원에서 진행된 2025 K-DATA·신용보즘기금· 한국<b>핀테크</b>지원센터 IR DAY 데모데이에 <b>핀테크</b> 대학생 기자단이 현장취재를 다녀왔습니다! 각 기관이 지원하는 유망 스타트업들을... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20251014'},
  {'title': '8월 서울 오피스 시장 분석 — 거래 급감에도 공실률은 하락',
   'link': 'https://blog.naver.com/jsh5015/224040557309',
   'description': 'AI, <b>핀테크</b>, 콘텐츠 업종 중심으로 오피스 입주 문의는 오히려 증가세.”  임대비용 — NOC 상승세... AI·<b>핀테크</b>·콘텐츠 산업 중심의 신규 오피스 수요 지속 하반기에는 강남·성수·여의도권 중심 재계약... ',
   'bloggername': '부동산과 경제 뉴스 정리, 분양 소식과 다양한 정보',
   'bloggerlink': 'blog.naver.com/jsh5015',
   'postdate': '20251014'},
  {'title': '증권사리포트 요약본 2025.10.14',
   'link': 'https://blog.naver.com/kwangpoong/224040556592',
   'description': '[035420] ˝AI, <b>핀테크</b>, 커머스˝ 모두 바쁨 ▶ 3Q25 Preview: 영업이익 5,579억원(+13.9% YoY)으로 컨센서스 하회 추정 ▶ 중장기 <b>핀테크</b> 사업 가치 부각 하나증권 이준호 카카오 [035720] 3분기 영업이익 1... ',
   'bloggername': '學習忍',
   'bloggerlink': 'blog.naver.com/kwangpoong',
   'postdate': '20251014'},
  {'title': '스테이블코인 결제시스템 3가지 핵심 변화 총정리',
   'link': 'https://blog.naver.com/law_sugarsquare/224035670742',
   'description': "* [상담문의]  02-563-5877  010-****-**** 카톡 '법무법인슈가스퀘어' 검색! 또는 카카오톡 상담링크  ****@sugar.legal #스테이블코인 #결제시스템 #<b>핀테크</b> #블록체인 #금융혁신",
   'bloggername': '법무법인 슈가스퀘어 블로그',
   'bloggerlink': 'blog.naver.com/law_sugarsquare',
   'postdate': '20251014'},
  {'title': '2025년 10월 14일 관심종목(주식)',
   'link': 'https://blog.naver.com/kk9550ch/224040546776',
   'description': 'idxno=3162806 아이티센피엔에스 - 통합 보안시스템+양자암호 솔루션 - <b>핀테크</b>, 스테이블코인 관련주 [특징주] 아이티센피엔에스, &quot;美 스테이블코인 규제법 통과&quot; 가상화폐 ... ',
   'bloggername': '재테크 in my life (feat.맛난음식)',
   'bloggerlink': 'blog.naver.com/kk9550ch',
   'postdate': '20251014'},
  {'title': '오늘자 이커머스 전망에 대해 알아보자',
   'link': 'https://blog.naver.com/pdion/224040542746',
   'description': '결제·<b>핀테크</b> 통합 BNPL(Buy Now Pay Later), 간편 결제, 디지털 월렛 등이 사용자 경험을 매끄럽게 할 것 마켓플레이스 재편 / 플랫폼 경쟁 플랫폼 간 제휴, 인수합병, 수수료 및 데이터 경쟁이 심화될 것 3. 기회... ',
   'bloggername': '피디온',
   'bloggerlink': 'blog.naver.com/pdion',
   'postdate': '20251014'},
  {'title': '코스피 시가총액 순위, 대한민국 TOP10 기업 성적표',
   'link': 'https://blog.naver.com/hanvit_lol/224040543213',
   'description': 'TOP10에 턱걸이로 안착했으며 <b>핀테크</b>, 콘텐츠, AI 삼박자를 앞세워서 제2의 도약을 노리고 있는 중이다. 이상으로 대한민국 경제의 심장인 코스피 TOP10 기업들의 역동적인 성적표 보았다. 25년의 성적표는 AI... ',
   'bloggername': '잘먹고 잘사는 오리좌',
   'bloggerlink': 'blog.naver.com/hanvit_lol',
   'postdate': '20251014'},
  {'title': '[비트코인 스탠다드]가 말하지 못한 것: GENIUS Act와 STABLE... ',
   'link': 'https://blog.naver.com/10000reading/224040540164',
   'description': '이 경우 카드 네트워크·은행 코어·<b>핀테크</b> 월렛이 스테이블코인 결제 레일을 품으며 **‘매끄러운... 은행-<b>핀테크</b>-카드사가 맺는 삼각 파트너십이 관건이다. 4) 체인 간 상호운용성과 계정 추상화 모바일... ',
   'bloggername': '일만리딩',
   'bloggerlink': 'blog.naver.com/10000reading',
   'postdate': '20251014'},
  {'title': 'AI가 리드하는 <b>핀테크</b> 혁신의 미래! : 서울 <b>핀테크</b> 위크 2025... ',
   'link': 'https://blog.naver.com/elmanproduction/224040539614',
   'description': '오늘은 서울 <b>핀테크</b> 위크 2025 홍보 영상 제작 후기를 들고 왔습니다. 로딩중,,, 글로번 <b>핀테크</b> 축제인 서울 <b>핀테크</b> 위크 2025가 곧 개최됩니다. 금융과 AI, <b>핀테크</b> 산업의 주요 이슈를 다루고 혁신적인... ',
   'bloggername': 'ELMAN 영상제작사',
   'bloggerlink': 'blog.naver.com/elmanproduction',
   'postdate': '20251014'},
  {'title': '네이버·카카오, AI 전환으로 실적 폭발!',
   'link': 'https://blog.naver.com/smart-moneylog/224039305600',
   'description': '디지털 자산, <b>핀테크</b>, 블록체인 등 새로운 성장축이 확실히 잡히는 셈이죠. AI에다 가상자산까지... 앞으로의 관전 포인트 네이버는 AI로 쇼핑과 <b>핀테크</b>를, 카카오는 AI로 커뮤니케이션과 광고를 진화시키는... ',
   'bloggername': '스마트머니로그',
   'bloggerlink': 'blog.naver.com/smart-moneylog',
   'postdate': '20251014'},
  {'title': '비바리퍼블리카 주가 급등하는 이유, 2025년 상장 앞둔 토스의... ',
   'link': 'https://blog.naver.com/kwonmj1216/224022265678',
   'description': '최근 <b>핀테크</b> 업계에서 가장 뜨거운 관심을 받는 비바리퍼블리카에 대한 궁금증이었습니다. 실제로... 나 역시 <b>핀테크</b> 업계를 10년 넘게 지켜보면서 이만큼 탄탄한 실적 기반을 갖춘 회사를 본 적이 드물다고... ',
   'bloggername': '올인포',
   'bloggerlink': 'blog.naver.com/kwonmj1216',
   'postdate': '20251014'},
  {'title': '벤처기업도 이제 ‘가상자산 거래업’을 할 수 있다!',
   'link': 'https://blog.naver.com/veteran01/224040538500',
   'description': '◆ 기대 효과 혁신 스타트업의 진입 확대: 블록체인 기술 기반의 <b>핀테크</b>, 거래 플랫폼, 토큰증권(STO) 등 다양한 영역에서 벤처기업들이 자유롭게 사업을 추진할 수 있습니다. 투자 활성화: 벤처기업 인증이... ',
   'bloggername': 'Not success but Service',
   'bloggerlink': 'blog.naver.com/veteran01',
   'postdate': '20251014'},
  {'title': '<b>핀테크</b>와 혁신의 만남 : 제4회 피노베이션 챌린지 행사 오프닝... ',
   'link': 'https://blog.naver.com/elmanproduction/224040533011',
   'description': '<b>핀테크</b>(Fintech)와 이노베이션(Innovation)을 합친 용어로, 서울시가 추진해온 프로그램입니다. <b>핀테크</b>, 인슈어테크, AI, 빅데이터 등 다양한 기술 역량을 가진 스타트업을 발굴하고, 금융사와의 공동 사업화를... ',
   'bloggername': 'ELMAN 영상제작사',
   'bloggerlink': 'blog.naver.com/elmanproduction',
   'postdate': '20251014'},
  {'title': '디지털 브레튼우즈의 서막: 달러·금의 시대를 넘어 블록체인... ',
   'link': 'https://blog.naver.com/10000reading/224040531447',
   'description': 'IMF·BIS와 함께 민간 PSP, <b>핀테크</b>, 은행 컨소시엄이 공동으로 의결권을 행사하여 권력 집중을 방지한다. 5~7년의 로드맵: 테스트넷에서 글로벌 표준으로 1단계에서는 CBDC 상호운용 최소규격과 디지털 SDR... ',
   'bloggername': '일만리딩',
   'bloggerlink': 'blog.naver.com/10000reading',
   'postdate': '20251014'},
  {'title': '10월 14일. 투자자를 위한 뉴스 속 실마리 [자본시장 이슈... ',
   'link': 'https://blog.naver.com/numbersmembers/224040531979',
   'description': "https://www.insightkorea.co.kr/news/articleView.html?idxno=233417 Published on: 2025-10-13 15:34:00 가상자산 M&amp;A 3배 급증…금융·<b>핀테크</b> '합종연횡' 본격화 /전자신문 가상자산 업계 인수합병(M&amp;A) 발표가... ",
   'bloggername': 'M&A·지배구조·Deal·기업분석 뉴스 서비스 <넘버스>',
   'bloggerlink': 'blog.naver.com/numbersmembers',
   'postdate': '20251014'},
  {'title': '[GPU Live] GPUaaS 서비스 GPU Live!',
   'link': 'https://blog.naver.com/nhn_injeinc/224039765197',
   'description': '✅ 금융·<b>핀테크</b> 산업 GPU Live는 금융기관에서 중요한 딥러닝 기반 이상거래 탐지(FDS), 신용평가 모델링, 고객 행동 분석 등대규모 연산이 필요한 금융 서비스 환경에 최적화되어 있습니다! GPU 자원을... ',
   'bloggername': 'NHN 인재아이엔씨',
   'bloggerlink': 'blog.naver.com/nhn_injeinc',
   'postdate': '20251014'},
  {'title': '카드매출로 보증받는 법, 실전 가이드',
   'link': 'https://blog.naver.com/yj920621/224040121932',
   'description': '은행·<b>핀테크</b> 특례형) Tip: 현금 매출 비중이 높아도 카드·PG 매출 증빙 비율을 최대화하면 한도에 유리합니다. 준비물 체크리스트 - 필수 - 사업자등록증 사본 - 대표자 신분증 - 최근 6~12개월 카드매출 내역... ',
   'bloggername': '한국중소기업 지원센터',
   'bloggerlink': 'blog.naver.com/yj920621',
   'postdate': '20251014'},
  {'title': '채무통합대환대출조건 채무통합으로 시작하는 현명한 재무 관리',
   'link': 'https://blog.naver.com/my-loan-clinic/223949594538',
   'description': '금융사의 상품을 비교할 때 대출 비교 앱이나 <b>핀테크</b> 플랫폼을 적극 활용해 봐야 합니다. 통합 대출 시 발생할 수 있는 수수료나 추가 비용도 반드시 확인하셔야 합니다. 직접 금융 기관 상담이 어렵다면 전문가... ',
   'bloggername': '마이금융클리닉 공식블로그',
   'bloggerlink': 'blog.naver.com/my-loan-clinic',
   'postdate': '20251014'},
  {'title': '가상자산: ‘벤처인증 허용’+‘대출 규제’ 병행… 산업은... ',
   'link': 'https://blog.naver.com/k3228452/224040522149',
   'description': '#가상자산 #크립토 #디지털자산 #벤처인증 #디지털자산기본법 #스테이블코인 #렌딩규제 #금리상한 #레버리지금지 #소비자보호 #공시의무 #내부통제 #준법감시 #리스크관리 #거래소 #커스터디 #<b>핀테크</b> #웹3',
   'bloggername': '한눈정책 – 핵심만 콕, 하루 한 장',
   'bloggerlink': 'blog.naver.com/k3228452',
   'postdate': '20251014'},
  {'title': 'Eat-Lancet이 제시한 이상적인 식단',
   'link': 'https://blog.naver.com/yelms/224040517993',
   'description': '이는 저렴한 식물성 단백질 기반의 간편식(HMR), 개인 맞춤형 구독 서비스, 혹은 건강한 식습관을 유도하는 챌린지 앱과 같은 <b>핀테크</b> 결합 서비스 등 무궁무진한 사업 기회를 의미한다. 2. 전통 식단의 보호와... ',
   'bloggername': '국경없는금융포럼',
   'bloggerlink': 'blog.naver.com/yelms',
   'postdate': '20251014'},
  {'title': '2025.10.14(화) 기업 리포트 요약 정리',
   'link': 'https://blog.naver.com/timulys/224040516473',
   'description': 'A035420 -˝AI, <b>핀테크</b>, 커머스˝ 모두 바쁨 3Q25 Preview: 영업이익 5,579억원(+13.9% YoY)으로 컨센서스 하회 추정 중장기 <b>핀테크</b> 사업 가치 부각 매수 320,000 262,500 SK증권 남효지 2025/10/14... ',
   'bloggername': '투자하는 행복',
   'bloggerlink': 'blog.naver.com/timulys',
   'postdate': '20251014'},
  {'title': '[TUO]10월14일 세계뉴스: 가자 휴전, 우크라 토마호크, EU... ',
   'link': 'https://blog.naver.com/world-response/224040514540',
   'description': '넷째, 유엔 사이버협약의 서명·비준 과정을 거치며 데이터 이전, 전자증거 교환, 플랫폼 책임 범위가 분명해지면 클라우드·보안·<b>핀테크</b> 기업의 규제 대응 비용과 수익 모델에도 변화가 생길 가능성이 큽니다.... ',
   'bloggername': '장대표의 인사이드 베트남',
   'bloggerlink': 'blog.naver.com/world-response',
   'postdate': '20251014'},
  {'title': 'Global Vicke 사기 투자 리딩방 미끼 완전 해부 (사칭)',
   'link': 'https://blog.naver.com/lucifer49329/224040508093',
   'description': '(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이 강민성 변호사',
   'bloggerlink': 'blog.naver.com/lucifer49329',
   'postdate': '20251014'},
  {'title': 'Angel❤️월세·전세금 부담 줄이는 혁신 서비스  보증금... ',
   'link': 'https://blog.naver.com/nyk34644/224040504261',
   'description': '이런 고민을 해결해주는 다양한 <b>핀테크</b> 서비스들이 등장하고 있어 관심이 집중되고 있습니다.... <b>핀테크</b> 스타트업 데브디에서 출시한 집업페이는 또 다른 혁신을 가져왔습니다. 바로 집주인의 동의 없이도... ',
   'bloggername': '작으면서 큰 부동산이야기',
   'bloggerlink': 'blog.naver.com/nyk34644',
   'postdate': '20251014'},
  {'title': '이직사유 예시 BEST 3, 면접 답변 꿀팁 총정리 &amp; 합격 전략!',
   'link': 'https://blog.naver.com/staffs00/224040498054',
   'description': '최근 <b>핀테크</b> 분야에 큰 관심을 갖게 되면서 귀사의 AI 기반 개인화 금융 서비스를 주목하게... 제가 보유한 대용량 데이터 처리 경험과 금융 도메인 지식을 바탕으로 귀사 AI <b>핀테크</b> 서비스의 안정성과 확장성... ',
   'bloggername': 'STAFFS STORY',
   'bloggerlink': 'blog.naver.com/staffs00',
   'postdate': '20251014'},
  {'title': '2030대가 선호하는 대기업 TOP10과 선택 이유',
   'link': 'https://blog.naver.com/rct190/224040494783',
   'description': '카카오 플랫폼, 콘텐츠, <b>핀테크</b> 등 영역을 넘나들며 혁신을 시도하는 모습이 2030대의 관심을 끌고 있습니다. “미래 가치가 기대된다”라는 평가와 함께 브랜드 이미지도 세련되고 젊은 감각이 강하다는... ',
   'bloggername': '파이어족의 경제, 금융 이야기',
   'bloggerlink': 'blog.naver.com/rct190',
   'postdate': '20251014'},
  {'title': '카카오페이 10월 14일 퀴즈 맞히고 복권 받기',
   'link': 'https://blog.naver.com/tkadla1422/224040494383',
   'description': '이처럼 통합 <b>핀테크</b> 플랫폼으로 진화하며 투자, 환전, 보험, 청구서 관리 등 다양한 금융 서비스를 통합 제공하는 점도 큰 강점입니다. 요약하면, 카카오페이는 카카오톡과의 완벽한 연동으로 쉽고 빠른 결제와... ',
   'bloggername': '김맹구의 탐구생활',
   'bloggerlink': 'blog.naver.com/tkadla1422',
   'postdate': '20251014'},
  {'title': '카카오뱅크 목표가 하향 대출 규제 속 성장 전망 분석 투자 전략!',
   'link': 'https://blog.naver.com/lottotem_economy/224040487251',
   'description': '가계대출 규제가 성장 전망치에 미친 구체적 영향 <b>핀테크</b> 리더로서 카카오뱅크는 저렴한 수신 확대를... 시장 컨센서스 비교 및 <b>핀테크</b> 주의 향후 주가 전망 KB증권이 제시한 28,000원의 목표주가는 최근 6개월... ',
   'bloggername': '경제톡',
   'bloggerlink': 'blog.naver.com/lottotem_economy',
   'postdate': '20251014'},
  {'title': '10/14 섹터별 현황',
   'link': 'https://blog.naver.com/mark-s/224040487497',
   'description': '93 <b>핀테크</b>(FinTech) 0.92 mRNA(메신저 리보핵산) 0.92 PCB(FPCB 등) 0.90 코로나19(치료제/백신 개발 등) 0.90 2025 상반기 신규상장 0.89 딥페이크(deepfake) 0.88 제습기 0.87 두나무(Dunamu) 0.86... ',
   'bloggername': 'Observer',
   'bloggerlink': 'blog.naver.com/mark-s',
   'postdate': '20251014'},
  {'title': '[보험업 컨설턴트 김희석] 2501014 주요 금융 뉴스',
   'link': 'https://blog.naver.com/cekhsgod/224040484905',
   'description': "독일 최대 인뱅 CEO 줄퇴진에 금감원 “<b>핀테크</b> 규제 완화 신중해야” (조선비즈, 10/13) 2.... 가상자산 M&amp;A 3배 급증…금융·<b>핀테크</b> '합종연횡' 본격화 (전자신문, 10/13) 6. ‘업비트 효과’ 넘어야... ",

# .env파일명을 바꾸고 싶을 때

In [18]:
from dotenv import load_dotenv
import os
load_dotenv(dotenv_path="./data/.env_naver")
import requests

user_id = os.getenv("user_Id")
user_secret = os.getenv("user_Secret")
url = "https://openapi.naver.com/v1/search/blog"
keyword = "핀테크"
payload = dict(query=keyword, display=100, start=1, sort="date")
headers = {"X-Naver-Client-Id" : user_id, "X-Naver-Client-Secret" : user_secret}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()
response

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
200

{'lastBuildDate': 'Tue, 14 Oct 2025 11:47:40 +0900',
 'total': 476764,
 'start': 1,
 'display': 100,
 'items': [{'title': '네이버 업비트 두나무 관련주, 뱅크웨어글로벌 종목 분석',
   'link': 'https://blog.naver.com/luckyinnae/224040653772',
   'description': '네이버 두나무 인수 관련주 총정리 | 뱅크웨어글로벌 주가 전망과 투자전략 최근 <b>핀테크</b> 시장이... 결제·<b>핀테크</b> 인프라 공급사 NHN KCP, 쿠콘, 헥토파이낸셜, 다날 스테이블코인·결제 API 핵심 수혜주 금융 IT... ',
   'bloggername': '심소장의 아파트분양 리뷰',
   'bloggerlink': 'blog.naver.com/luckyinnae',
   'postdate': '20251014'},
  {'title': '쇼피파이 2분기 어닝콜 프리젠테이션 자료 분석',
   'link': 'https://blog.naver.com/hhr4376/224040649401',
   'description': 'https://s27.q4cdn.com/572064924/files/doc_presentations/2025/May/08/Investor-Overview-Deck-Q1-2025-2.pdf AI 활용 설정 사진 설명을 입력하세요. AI 활용 설정 사진 설명을 입력하세요. 해당 이미지는 쇼피파이(Shopify)의 주요... ',
   'bloggername': '생각이 돈이다',
   'bloggerlink': 'blog.naver.com/hhr4376',
   'postdate': '20251014'},
  {'title': '변화와 미래 전망:금융권 동향부터 디지털 혁신,<b>핀테크</b>까지',
   'link': 'https://blog.naver.com/dth73819/224040643226',
   'description': '금융산업 변화와 미래전망 : 금융권 동향부터 디지털 혁신, <b>핀테크</b> 까지 안녕하세요,금융에 관심있는 여러분! 최근 금융 산업은 빠르게 변화하고 있습니다. 전통 금융권은 물론, 디지털 금융과 <b>핀테크</b>까지... ',
   'bloggername': '삽살개',
   'bloggerlink': 'blog.naver.com/dth73819',
   'postdate': '20251014'},
  {'title': '[도약 프로그램] 2025 중소기업 지원, 도약(Jump-Up)... ',
   'link': 'https://blog.naver.com/fki_lsc/224040446624',
   'description': '서비스 <b>핀테크</b>, 인슈어테크, 로보어드바이저, 디지털 뱅킹 등 전문 및 교육 서비스 에듀테크, 온라인 교육 플랫폼, 디자인 컨설팅 등 친환경 및 스마트인프라 신재생에너지 태양광, 풍력, 수소에너지, 지열... ',
   'bloggername': '한경협중소기업협력센터',
   'bloggerlink': 'blog.naver.com/fki_lsc',
   'postdate': '20251014'},
  {'title': '2025년 10월 14일 - 15일 미국주식정보(25.10.14... ',
   'link': 'https://blog.naver.com/wnguddhkd/224040630301',
   'description': '기대 • <b>핀테크</b>: GS, PYPL(PayPal), MQ(Marqeta) ‘매도’ 하향 – 마진 압박 및 집중 리스크 지적 5️⃣ 자산시장 동향 • 채권시장 휴장(Columbus Day)으로 변동 제한. WTI $59.95, Gold $4,114로 상승... ',
   'bloggername': '호기심',
   'bloggerlink': 'blog.naver.com/wnguddhkd',
   'postdate': '20251014'},
  {'title': '실리콘밸리 <b>핀테크</b> 하프모어, 딥코어 리드 투자로 누적 35억 원... ',
   'link': 'https://blog.naver.com/ksvalley/224040630287',
   'description': '딥코어 관계자는 &quot;하프모어는 강력한 초기 성과와 넓은 금융 웰니스로의 확장 잠재력을 갖췄다&quot;며 투자 배경을 밝혔다.',
   'bloggername': 'k스타트업 밸리',
   'bloggerlink': 'blog.naver.com/ksvalley',
   'postdate': '20251014'},
  {'title': '[CTN정보]꼭 읽어야 할 서울시소식',
   'link': 'https://blog.naver.com/ggh7000/224040630580',
   'description': '(금) ‘(재)서울투자진흥재단 창립총회’ 개최…설립 전 주요사항 심의 및 의결 - 창립총회 이후, 법인설립 허가 및 등기 등 제반 절차 거쳐 10월말 출범 목표 - GFCI 3년 연속 Top10, <b>핀테크</b> 8위 최초... ',
   'bloggername': 'CTN신문사',
   'bloggerlink': 'blog.naver.com/ggh7000',
   'postdate': '20251014'},
  {'title': '가족간 차용증 이자율 부모자식 형제 작성법(양식 무료다운)',
   'link': 'https://blog.naver.com/kapbue/224040628117',
   'description': '<b>핀테크</b> 기반의 앱을 통해 변호사 검토가 포함된 계약서를 작성할 수 있으며, 본인 인증까지 완료되어 법적 효력을 갖출 수 있습니다. 전자 차용증은 종이보다 보관이 쉽고 분실 위험도 적어 요즘 많은 분들이... ',
   'bloggername': '호치스의 50억 만드는 부동산',
   'bloggerlink': 'blog.naver.com/kapbue',
   'postdate': '20251014'},
  {'title': '무직자도 OK! 지금 바로 대출 가능?',
   'link': 'https://blog.naver.com/himse/224040621180',
   'description': '<b>핀테크</b> 기술의 발전과 더불어 청년, 취업준비생, 사회초년생 등 다양한 계층을 위한 맞춤형 대출 상품이 쏟아져 나오고 있어요.은행 문턱이 높다고 좌절하지 마세요. 2금융권, <b>핀테크</b> 기업 등 다양한 곳에서... ',
   'bloggername': '아파트 담보대출 전문! OK자산관리대부',
   'bloggerlink': 'blog.naver.com/himse',
   'postdate': '20251014'},
  {'title': '2025년 노벨 경제학상 - “창조적 파괴”',
   'link': 'https://blog.naver.com/jeenu123/224040620030',
   'description': '✅ <b>핀테크</b>·디지털 금융: Toss 등 — 은행·결제 시스템의 경쟁 재구성 무엇이 바뀌었나: Toss 등 <b>핀테크</b>는 간편송금·금융서비스를 통해 전통 은행의 소매금융 일부를 잠식하고, 사용자 경험을 재정의.... ',
   'bloggername': 'Humus',
   'bloggerlink': 'blog.naver.com/jeenu123',
   'postdate': '20251014'},
  {'title': '7편 – PG(Payment Gateway)란 무엇인가',
   'link': 'https://blog.naver.com/dydwo7151-/224040619374',
   'description': 'PG의 진화 – <b>핀테크</b>와 함께 가는 길 최근 PG 산업은 단순한 결제 중개를 넘어 데이터 기반 정산, 마케팅, 소비 분석을 제공하는 방향으로 발전하고 있습니다. 또한 블록체인 기술과 결합해, 국경 없는... ',
   'bloggername': 'dydwo7151-님의 블로그',
   'bloggerlink': 'blog.naver.com/dydwo7151-',
   'postdate': '20251014'},
  {'title': '패스트파이브, 올 상반기 재계약률 94%...‘믿고 찾는 사무실... ',
   'link': 'https://blog.naver.com/phenomdark/224040619773',
   'description': '실제 장기 입주 기업 중 한 곳인 글로벌 <b>핀테크</b> 기업 와이어바알리는 2019년 첫 입주 이후 6년 이상 패스트파이브를 거점 오피스로 사용해 왔다. 와이어바알리는 성장 단계마다 필요한 규모와 입지를 유연하게... ',
   'bloggername': 'SHOW MUST GO ON..',
   'bloggerlink': 'blog.naver.com/phenomdark',
   'postdate': '20251014'},
  {'title': '전자금융공동망은 어떻게 진화했을까, 미래 금융의 뿌리',
   'link': 'https://blog.naver.com/rlocate/224040618979',
   'description': "넘어 '금융기관과 <b>핀테크</b> 기업의 연결 허브'로 확장되었습니다 <b>핀테크</b> 기업들은 중앙은행이 관리하는 공동망을 통해 은행의 핵심 결제 기능에 접근할 수 있게 되었고 이는 간편 송금, 간편 결제 등 다양한... ",
   'bloggername': '미소 지는 순간',
   'bloggerlink': 'blog.naver.com/rlocate',
   'postdate': '20251014'},
  {'title': '급여통장 신규 개설 및 인터넷뱅킹 신청 방법',
   'link': 'https://blog.naver.com/elow1957/224040614815',
   'description': '다른 <b>핀테크</b> 서비스의 대안 서론 요즘 대부분의 금융거래가 온라인으로 이루어지고 있습니다. 이에... 다른 <b>핀테크</b> 서비스의 대안 최근에는 카카오뱅크, 케이뱅크 등 인터넷 전문은행을 통한 다양한 통장... ',
   'bloggername': '내가 좋아하는것들',
   'bloggerlink': 'blog.naver.com/elow1957',
   'postdate': '20251014'},
  {'title': '전망좋은주식 미국 주식 종목 중심 분석',
   'link': 'https://blog.naver.com/wwlcc28/224040612860',
   'description': '에너지 저장, 5G 통신, <b>핀테크</b> 분야 또한 안정적인 성장세를 보이고 있습니다. 이런 흐름 속에서 주목받는 기업들은 기술력, 수익 구조, 시장 점유율 세 가지 기준에서 공통된 특징을 가집니다. “지속... ',
   'bloggername': 'wwlcc28님의 블로그',
   'bloggerlink': 'blog.naver.com/wwlcc28',
   'postdate': '20251014'},
  {'title': '인도 ETF｜RISE 인도디지털성장·KODEX 인도Nifty50·TIGER... ',
   'link': 'https://blog.naver.com/notinghel/224040610822',
   'description': 'MarketVector 지수를 추종하며, 인도의 인터넷·<b>핀테크</b>·통신·클라우드 기업들이 중심입니다.... IT, <b>핀테크</b>, 통신 대형주, 금융, 에너지 소비재, 서비스, 자동차 최근 NAV 수준 약 10,300원 약 13... ',
   'bloggername': 'notinghel님의 블로그',
   'bloggerlink': 'blog.naver.com/notinghel',
   'postdate': '20251014'},
  {'title': '감성지능: <b>핀테크</b> 고객 경험의 미래',
   'link': 'https://blog.naver.com/pxjlpss565/224040607064',
   'description': '감성지능: <b>핀테크</b> 고객 경험의 미래 <b>핀테크</b> 산업은 빠르게 발전하고 있으며, 이에 따라 고객 경험에 대한 요구도 더욱 증가하고 있다. 최근 감성지능 기술의 발전으로 <b>핀테크</b> 기업들은 더욱 개인화된 서비스를... ',
   'bloggername': '운동과 공부가 취미',
   'bloggerlink': 'blog.naver.com/pxjlpss565',
   'postdate': '20251014'},
  {'title': '[신한투자증권 미국주식 주요이슈] 챗GPT 내 즉시 결제... ',
   'link': 'https://blog.naver.com/shinhansec_official/224040598934',
   'description': '구글과 쇼핑 전쟁 : 이번 기능은 오픈AI의 자체 기술인 ‘에이전틱 커머스 프로토콜’과 <b>핀테크</b> 기업 스트라이프(Stripe)와의 협력을 통해 구현됐고, 앞으로 장바구니 기능 및 글로벌 확장도 계획 중이에요.... ',
   'bloggername': '신한투자증권 공식 블로그',
   'bloggerlink': 'blog.naver.com/shinhansec_official',
   'postdate': '20251014'},
  {'title': '영문계약서, 어디서부터 봐야 할까? 기본 구조와 핵심 조항... ',
   'link': 'https://blog.naver.com/legal_lemonade/224040593334',
   'description': 'About the Authour 국내 대형은행 법무팀에서 10년 이상 국제금융, 신용장, 영문계약서 및 외국환규제 자문 등을 담당하고, <b>핀테크</b> 기업에서 해외 지급결제와 해외 진출 등 다양한 프로젝트를 수행한... ',
   'bloggername': '리걸 레몬에이드',
   'bloggerlink': 'blog.naver.com/legal_lemonade',
   'postdate': '20251014'},
  {'title': '비트코인관련주 코인베이스 다날 우리기술투자 주가 분석',
   'link': 'https://blog.naver.com/fashiongreen/224040588409',
   'description': "기반 <b>핀테크</b> / 결제 플랫폼 기업으로 암호화폐 결제 플랫폼인 다날<b>핀테크</b>를 개발해 '페이코인'을 실생활 결제에 적용하는 등의 경험을 가지고 있는데요 이러한 기술력을 기반으로 스테이블코인 사업 진출... ",
   'bloggername': '돈 되는 경제만 쉽고 빠르게',
   'bloggerlink': 'blog.naver.com/fashiongreen',
   'postdate': '20251014'},
  {'title': '신용점수 올리는 방법 2025 최신 기준 정리',
   'link': 'https://blog.naver.com/sssolution1858/224039350975',
   'description': '정확한 진단 정직한 처방 고객과 상생을 도모하는 에스에스솔루션 2025년 들어 신용점수 제도가 한층 더 정교해졌다. 단순히 연체 없이 대출을 갚는 것만으로는 점수를 높이기 어렵고, 금융사마다 평가 기준이... ',
   'bloggername': 'Sssolution',
   'bloggerlink': 'blog.naver.com/sssolution1858',
   'postdate': '20251014'},
  {'title': 'RISE 인도디지털성장 ETF 완전정리｜인도 디지털 인프라... ',
   'link': 'https://blog.naver.com/notinghel/224040584997',
   'description': '이 ETF는 인도의 IT·통신·<b>핀테크</b>·디지털 인프라 산업을 대표하는 상장기업들로 구성되어... 디지털 인프라, 온라인 서비스, 통신, <b>핀테크</b>, 클라우드 등 인도의 정보기술 기반 산업 성장을... ',
   'bloggername': 'notinghel님의 블로그',
   'bloggerlink': 'blog.naver.com/notinghel',
   'postdate': '20251014'},
  {'title': '시니어 마케팅, 60대·70대·80대, 같은 ‘시니어’로 묶어선... ',
   'link': 'https://blog.naver.com/trotnewsofficial/224040583199',
   'description': '평생교육, 디지털 고급 교육(<b>핀테크</b>, AI 활용)을 제공하세요. 여가·문화·관광 바우처를 적극 활용하세요. 70대 정책: 안전 관리 만성질환 예방 바우처, 보안·사기 예방 교육을 확대하세요. 디지털 서비스에 1:1... ',
   'bloggername': '시니어마케팅 연구소',
   'bloggerlink': 'blog.naver.com/trotnewsofficial',
   'postdate': '20251014'},
  {'title': '신한은행 2026년 동계 청년인턴 채용 완벽 가이드 - 금융권... ',
   'link': 'https://blog.naver.com/cymmcymm/224040566983',
   'description': '결합된 <b>핀테크</b> 시대에 꼭 필요한 경험을 쌓을 수 있는 기회랍니다. 신한은행 청년인턴 지원 자격 조건... 금융권 취업을 준비하고 계신 분들, IT와 금융을 결합한 <b>핀테크</b> 분야에 관심 있는 분들 모두에게 정말... ',
   'bloggername': 'Creater Y',
   'bloggerlink': 'blog.naver.com/cymmcymm',
   'postdate': '20251014'},
  {'title': '“솔라나 × 한국 스테이블코인 — 주식시장에서 주목할... ',
   'link': 'https://blog.naver.com/hmn1204/224040565408',
   'description': '증가 <b>핀테크</b> / 결제 플랫폼 스테이블코인 → 결제/송금/정산 활용 가능성, 자체 플랫폼 내 사용... <b>핀테크</b> / 결제 플랫폼 회사 (예: 토스 등) 실제 보도가 있듯 토스(Toss)가 “원화 기반 스테이블코인 발행”을... ',
   'bloggername': '억만덕후의 이시대 살아남는법',
   'bloggerlink': 'blog.naver.com/hmn1204',
   'postdate': '20251014'},
  {'title': '미국의 파이어족이 불러올 경제의 나비효과',
   'link': 'https://blog.naver.com/garts44/224040562087',
   'description': '오늘날의 <b>핀테크</b>, 국채, 디지털 자산이 같은 역할을 하고 있습니다. 5️⃣ 소비재·유통 도시화와 중산층의 등장으로 전국 유통망이 생겼고, 시어스의 카탈로그와 코카콜라는 그 시대의 아이콘이었습니다.... ',
   'bloggername': '오늘 질문은...',
   'bloggerlink': 'blog.naver.com/garts44',
   'postdate': '20251014'},
  {'title': '[<b>핀테크</b> 기자단] 2025 K-DATA·신용보즘기금·한국<b>핀테크</b>지... ',
   'link': 'https://blog.naver.com/koreafintech/224040557226',
   'description': '지난 9월 18일 디캠프 프론트원에서 진행된 2025 K-DATA·신용보즘기금· 한국<b>핀테크</b>지원센터 IR DAY 데모데이에 <b>핀테크</b> 대학생 기자단이 현장취재를 다녀왔습니다! 각 기관이 지원하는 유망 스타트업들을... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20251014'},
  {'title': '8월 서울 오피스 시장 분석 — 거래 급감에도 공실률은 하락',
   'link': 'https://blog.naver.com/jsh5015/224040557309',
   'description': 'AI, <b>핀테크</b>, 콘텐츠 업종 중심으로 오피스 입주 문의는 오히려 증가세.”  임대비용 — NOC 상승세... AI·<b>핀테크</b>·콘텐츠 산업 중심의 신규 오피스 수요 지속 하반기에는 강남·성수·여의도권 중심 재계약... ',
   'bloggername': '부동산과 경제 뉴스 정리, 분양 소식과 다양한 정보',
   'bloggerlink': 'blog.naver.com/jsh5015',
   'postdate': '20251014'},
  {'title': '증권사리포트 요약본 2025.10.14',
   'link': 'https://blog.naver.com/kwangpoong/224040556592',
   'description': '[035420] ˝AI, <b>핀테크</b>, 커머스˝ 모두 바쁨 ▶ 3Q25 Preview: 영업이익 5,579억원(+13.9% YoY)으로 컨센서스 하회 추정 ▶ 중장기 <b>핀테크</b> 사업 가치 부각 하나증권 이준호 카카오 [035720] 3분기 영업이익 1... ',
   'bloggername': '學習忍',
   'bloggerlink': 'blog.naver.com/kwangpoong',
   'postdate': '20251014'},
  {'title': '스테이블코인 결제시스템 3가지 핵심 변화 총정리',
   'link': 'https://blog.naver.com/law_sugarsquare/224035670742',
   'description': "* [상담문의]  02-563-5877  010-****-**** 카톡 '법무법인슈가스퀘어' 검색! 또는 카카오톡 상담링크  ****@sugar.legal #스테이블코인 #결제시스템 #<b>핀테크</b> #블록체인 #금융혁신",
   'bloggername': '법무법인 슈가스퀘어 블로그',
   'bloggerlink': 'blog.naver.com/law_sugarsquare',
   'postdate': '20251014'},
  {'title': '2025년 10월 14일 관심종목(주식)',
   'link': 'https://blog.naver.com/kk9550ch/224040546776',
   'description': 'idxno=3162806 아이티센피엔에스 - 통합 보안시스템+양자암호 솔루션 - <b>핀테크</b>, 스테이블코인 관련주 [특징주] 아이티센피엔에스, &quot;美 스테이블코인 규제법 통과&quot; 가상화폐 ... ',
   'bloggername': '재테크 in my life (feat.맛난음식)',
   'bloggerlink': 'blog.naver.com/kk9550ch',
   'postdate': '20251014'},
  {'title': '오늘자 이커머스 전망에 대해 알아보자',
   'link': 'https://blog.naver.com/pdion/224040542746',
   'description': '결제·<b>핀테크</b> 통합 BNPL(Buy Now Pay Later), 간편 결제, 디지털 월렛 등이 사용자 경험을 매끄럽게 할 것 마켓플레이스 재편 / 플랫폼 경쟁 플랫폼 간 제휴, 인수합병, 수수료 및 데이터 경쟁이 심화될 것 3. 기회... ',
   'bloggername': '피디온',
   'bloggerlink': 'blog.naver.com/pdion',
   'postdate': '20251014'},
  {'title': '코스피 시가총액 순위, 대한민국 TOP10 기업 성적표',
   'link': 'https://blog.naver.com/hanvit_lol/224040543213',
   'description': 'TOP10에 턱걸이로 안착했으며 <b>핀테크</b>, 콘텐츠, AI 삼박자를 앞세워서 제2의 도약을 노리고 있는 중이다. 이상으로 대한민국 경제의 심장인 코스피 TOP10 기업들의 역동적인 성적표 보았다. 25년의 성적표는 AI... ',
   'bloggername': '잘먹고 잘사는 오리좌',
   'bloggerlink': 'blog.naver.com/hanvit_lol',
   'postdate': '20251014'},
  {'title': '[비트코인 스탠다드]가 말하지 못한 것: GENIUS Act와 STABLE... ',
   'link': 'https://blog.naver.com/10000reading/224040540164',
   'description': '이 경우 카드 네트워크·은행 코어·<b>핀테크</b> 월렛이 스테이블코인 결제 레일을 품으며 **‘매끄러운... 은행-<b>핀테크</b>-카드사가 맺는 삼각 파트너십이 관건이다. 4) 체인 간 상호운용성과 계정 추상화 모바일... ',
   'bloggername': '일만리딩',
   'bloggerlink': 'blog.naver.com/10000reading',
   'postdate': '20251014'},
  {'title': '네이버·카카오, AI 전환으로 실적 폭발!',
   'link': 'https://blog.naver.com/smart-moneylog/224039305600',
   'description': '디지털 자산, <b>핀테크</b>, 블록체인 등 새로운 성장축이 확실히 잡히는 셈이죠. AI에다 가상자산까지... 앞으로의 관전 포인트 네이버는 AI로 쇼핑과 <b>핀테크</b>를, 카카오는 AI로 커뮤니케이션과 광고를 진화시키는... ',
   'bloggername': '스마트머니로그',
   'bloggerlink': 'blog.naver.com/smart-moneylog',
   'postdate': '20251014'},
  {'title': '비바리퍼블리카 주가 급등하는 이유, 2025년 상장 앞둔 토스의... ',
   'link': 'https://blog.naver.com/kwonmj1216/224022265678',
   'description': '최근 <b>핀테크</b> 업계에서 가장 뜨거운 관심을 받는 비바리퍼블리카에 대한 궁금증이었습니다. 실제로... 나 역시 <b>핀테크</b> 업계를 10년 넘게 지켜보면서 이만큼 탄탄한 실적 기반을 갖춘 회사를 본 적이 드물다고... ',
   'bloggername': '올인포',
   'bloggerlink': 'blog.naver.com/kwonmj1216',
   'postdate': '20251014'},
  {'title': 'AI가 리드하는 <b>핀테크</b> 혁신의 미래! : 서울 <b>핀테크</b> 위크 2025... ',
   'link': 'https://blog.naver.com/elmanproduction/224040539614',
   'description': '오늘은 서울 <b>핀테크</b> 위크 2025 홍보 영상 제작 후기를 들고 왔습니다. 로딩중,,, 글로번 <b>핀테크</b> 축제인 서울 <b>핀테크</b> 위크 2025가 곧 개최됩니다. 금융과 AI, <b>핀테크</b> 산업의 주요 이슈를 다루고 혁신적인... ',
   'bloggername': 'ELMAN 영상제작사',
   'bloggerlink': 'blog.naver.com/elmanproduction',
   'postdate': '20251014'},
  {'title': '벤처기업도 이제 ‘가상자산 거래업’을 할 수 있다!',
   'link': 'https://blog.naver.com/veteran01/224040538500',
   'description': '◆ 기대 효과 혁신 스타트업의 진입 확대: 블록체인 기술 기반의 <b>핀테크</b>, 거래 플랫폼, 토큰증권(STO) 등 다양한 영역에서 벤처기업들이 자유롭게 사업을 추진할 수 있습니다. 투자 활성화: 벤처기업 인증이... ',
   'bloggername': 'Not success but Service',
   'bloggerlink': 'blog.naver.com/veteran01',
   'postdate': '20251014'},
  {'title': '<b>핀테크</b>와 혁신의 만남 : 제4회 피노베이션 챌린지 행사 오프닝... ',
   'link': 'https://blog.naver.com/elmanproduction/224040533011',
   'description': '<b>핀테크</b>(Fintech)와 이노베이션(Innovation)을 합친 용어로, 서울시가 추진해온 프로그램입니다. <b>핀테크</b>, 인슈어테크, AI, 빅데이터 등 다양한 기술 역량을 가진 스타트업을 발굴하고, 금융사와의 공동 사업화를... ',
   'bloggername': 'ELMAN 영상제작사',
   'bloggerlink': 'blog.naver.com/elmanproduction',
   'postdate': '20251014'},
  {'title': '10월 14일. 투자자를 위한 뉴스 속 실마리 [자본시장 이슈... ',
   'link': 'https://blog.naver.com/numbersmembers/224040531979',
   'description': "https://www.insightkorea.co.kr/news/articleView.html?idxno=233417 Published on: 2025-10-13 15:34:00 가상자산 M&amp;A 3배 급증…금융·<b>핀테크</b> '합종연횡' 본격화 /전자신문 가상자산 업계 인수합병(M&amp;A) 발표가... ",
   'bloggername': 'M&A·지배구조·Deal·기업분석 뉴스 서비스 <넘버스>',
   'bloggerlink': 'blog.naver.com/numbersmembers',
   'postdate': '20251014'},
  {'title': '디지털 브레튼우즈의 서막: 달러·금의 시대를 넘어 블록체인... ',
   'link': 'https://blog.naver.com/10000reading/224040531447',
   'description': 'IMF·BIS와 함께 민간 PSP, <b>핀테크</b>, 은행 컨소시엄이 공동으로 의결권을 행사하여 권력 집중을 방지한다. 5~7년의 로드맵: 테스트넷에서 글로벌 표준으로 1단계에서는 CBDC 상호운용 최소규격과 디지털 SDR... ',
   'bloggername': '일만리딩',
   'bloggerlink': 'blog.naver.com/10000reading',
   'postdate': '20251014'},
  {'title': '[GPU Live] GPUaaS 서비스 GPU Live!',
   'link': 'https://blog.naver.com/nhn_injeinc/224039765197',
   'description': '✅ 금융·<b>핀테크</b> 산업 GPU Live는 금융기관에서 중요한 딥러닝 기반 이상거래 탐지(FDS), 신용평가 모델링, 고객 행동 분석 등대규모 연산이 필요한 금융 서비스 환경에 최적화되어 있습니다! GPU 자원을... ',
   'bloggername': 'NHN 인재아이엔씨',
   'bloggerlink': 'blog.naver.com/nhn_injeinc',
   'postdate': '20251014'},
  {'title': '채무통합대환대출조건 채무통합으로 시작하는 현명한 재무 관리',
   'link': 'https://blog.naver.com/my-loan-clinic/223949594538',
   'description': '금융사의 상품을 비교할 때 대출 비교 앱이나 <b>핀테크</b> 플랫폼을 적극 활용해 봐야 합니다. 통합 대출 시 발생할 수 있는 수수료나 추가 비용도 반드시 확인하셔야 합니다. 직접 금융 기관 상담이 어렵다면 전문가... ',
   'bloggername': '마이금융클리닉 공식블로그',
   'bloggerlink': 'blog.naver.com/my-loan-clinic',
   'postdate': '20251014'},
  {'title': '카드매출로 보증받는 법, 실전 가이드',
   'link': 'https://blog.naver.com/yj920621/224040121932',
   'description': '은행·<b>핀테크</b> 특례형) Tip: 현금 매출 비중이 높아도 카드·PG 매출 증빙 비율을 최대화하면 한도에 유리합니다. 준비물 체크리스트 - 필수 - 사업자등록증 사본 - 대표자 신분증 - 최근 6~12개월 카드매출 내역... ',
   'bloggername': '한국중소기업 지원센터',
   'bloggerlink': 'blog.naver.com/yj920621',
   'postdate': '20251014'},
  {'title': '가상자산: ‘벤처인증 허용’+‘대출 규제’ 병행… 산업은... ',
   'link': 'https://blog.naver.com/k3228452/224040522149',
   'description': '#가상자산 #크립토 #디지털자산 #벤처인증 #디지털자산기본법 #스테이블코인 #렌딩규제 #금리상한 #레버리지금지 #소비자보호 #공시의무 #내부통제 #준법감시 #리스크관리 #거래소 #커스터디 #<b>핀테크</b> #웹3',
   'bloggername': '한눈정책 – 핵심만 콕, 하루 한 장',
   'bloggerlink': 'blog.naver.com/k3228452',
   'postdate': '20251014'},
  {'title': 'Eat-Lancet이 제시한 이상적인 식단',
   'link': 'https://blog.naver.com/yelms/224040517993',
   'description': '이는 저렴한 식물성 단백질 기반의 간편식(HMR), 개인 맞춤형 구독 서비스, 혹은 건강한 식습관을 유도하는 챌린지 앱과 같은 <b>핀테크</b> 결합 서비스 등 무궁무진한 사업 기회를 의미한다. 2. 전통 식단의 보호와... ',
   'bloggername': '국경없는금융포럼',
   'bloggerlink': 'blog.naver.com/yelms',
   'postdate': '20251014'},
  {'title': '2025.10.14(화) 기업 리포트 요약 정리',
   'link': 'https://blog.naver.com/timulys/224040516473',
   'description': 'A035420 -˝AI, <b>핀테크</b>, 커머스˝ 모두 바쁨 3Q25 Preview: 영업이익 5,579억원(+13.9% YoY)으로 컨센서스 하회 추정 중장기 <b>핀테크</b> 사업 가치 부각 매수 320,000 262,500 SK증권 남효지 2025/10/14... ',
   'bloggername': '투자하는 행복',
   'bloggerlink': 'blog.naver.com/timulys',
   'postdate': '20251014'},
  {'title': '[TUO]10월14일 세계뉴스: 가자 휴전, 우크라 토마호크, EU... ',
   'link': 'https://blog.naver.com/world-response/224040514540',
   'description': '넷째, 유엔 사이버협약의 서명·비준 과정을 거치며 데이터 이전, 전자증거 교환, 플랫폼 책임 범위가 분명해지면 클라우드·보안·<b>핀테크</b> 기업의 규제 대응 비용과 수익 모델에도 변화가 생길 가능성이 큽니다.... ',
   'bloggername': '장대표의 인사이드 베트남',
   'bloggerlink': 'blog.naver.com/world-response',
   'postdate': '20251014'},
  {'title': 'Global Vicke 사기 투자 리딩방 미끼 완전 해부 (사칭)',
   'link': 'https://blog.naver.com/lucifer49329/224040508093',
   'description': '(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이 강민성 변호사',
   'bloggerlink': 'blog.naver.com/lucifer49329',
   'postdate': '20251014'},
  {'title': 'Angel❤️월세·전세금 부담 줄이는 혁신 서비스  보증금... ',
   'link': 'https://blog.naver.com/nyk34644/224040504261',
   'description': '이런 고민을 해결해주는 다양한 <b>핀테크</b> 서비스들이 등장하고 있어 관심이 집중되고 있습니다.... <b>핀테크</b> 스타트업 데브디에서 출시한 집업페이는 또 다른 혁신을 가져왔습니다. 바로 집주인의 동의 없이도... ',
   'bloggername': '작으면서 큰 부동산이야기',
   'bloggerlink': 'blog.naver.com/nyk34644',
   'postdate': '20251014'},
  {'title': '이직사유 예시 BEST 3, 면접 답변 꿀팁 총정리 &amp; 합격 전략!',
   'link': 'https://blog.naver.com/staffs00/224040498054',
   'description': '최근 <b>핀테크</b> 분야에 큰 관심을 갖게 되면서 귀사의 AI 기반 개인화 금융 서비스를 주목하게... 제가 보유한 대용량 데이터 처리 경험과 금융 도메인 지식을 바탕으로 귀사 AI <b>핀테크</b> 서비스의 안정성과 확장성... ',
   'bloggername': 'STAFFS STORY',
   'bloggerlink': 'blog.naver.com/staffs00',
   'postdate': '20251014'},
  {'title': '2030대가 선호하는 대기업 TOP10과 선택 이유',
   'link': 'https://blog.naver.com/rct190/224040494783',
   'description': '카카오 플랫폼, 콘텐츠, <b>핀테크</b> 등 영역을 넘나들며 혁신을 시도하는 모습이 2030대의 관심을 끌고 있습니다. “미래 가치가 기대된다”라는 평가와 함께 브랜드 이미지도 세련되고 젊은 감각이 강하다는... ',
   'bloggername': '파이어족의 경제, 금융 이야기',
   'bloggerlink': 'blog.naver.com/rct190',
   'postdate': '20251014'},
  {'title': '카카오페이 10월 14일 퀴즈 맞히고 복권 받기',
   'link': 'https://blog.naver.com/tkadla1422/224040494383',
   'description': '이처럼 통합 <b>핀테크</b> 플랫폼으로 진화하며 투자, 환전, 보험, 청구서 관리 등 다양한 금융 서비스를 통합 제공하는 점도 큰 강점입니다. 요약하면, 카카오페이는 카카오톡과의 완벽한 연동으로 쉽고 빠른 결제와... ',
   'bloggername': '김맹구의 탐구생활',
   'bloggerlink': 'blog.naver.com/tkadla1422',
   'postdate': '20251014'},
  {'title': '카카오뱅크 목표가 하향 대출 규제 속 성장 전망 분석 투자 전략!',
   'link': 'https://blog.naver.com/lottotem_economy/224040487251',

# 네이버 API에서 수집가능한 최대 자료 모두 수집하기

In [28]:
start_num = 1
for i in range(1, 11):
    if start_num < 901:
        start_num += 100
        print(start_num)
    elif start_num >= 901:
        start_num += 99
        print(start_num)

101
201
301
401
501
601
701
801
901
1000

In [38]:
# while 문을 이용해야 함
page = 1
if response['total'] // 100 > 10:
    page = 10
else:
    page = response['total'] // 100 + 1

In [39]:
99 // 100 +1

1

# for문을 이용해 최대한 수집하기
* naver api는 start 파라미터 최대값 1000
* 1페이지당 100개씩 수집시 최대 11페이지까지 수집 가능

In [45]:
from dotenv import load_dotenv
import os
load_dotenv(dotenv_path="./data/.env_naver")
import requests

num = 1
all_data = []
for page in range(11):
    user_id = os.getenv("user_Id")
    user_secret = os.getenv("user_Secret")
    url = "https://openapi.naver.com/v1/search/blog"
    keyword = "핀테크"
    payload = dict(query=keyword, display=100, start=num, sort="date")
    headers = {"X-Naver-Client-Id" : user_id, "X-Naver-Client-Secret" : user_secret}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    response = r.json()
    all_data.append(pd.DataFrame(response['items']))    
    
    if num < 901:
        num += 100
    elif num >= 901:
        num += 99
    print(num)

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
200
101
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=date
200
201
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=date
200
301
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=date
200
401
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=date
200
501
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=date
200
601
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=date
200
701
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=date
200
801
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=date
200
901
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=date
200
1000
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=date
200
1099

In [48]:
final_result = pd.concat(all_data)
final_result

,title,link,description,bloggername,bloggerlink,postdate
0,더나은투자 사기 및 리딩방 미끼 경계 가이드 (사칭),https://blog.naver.com/dtive84494/224040773011,(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자...,데이 강민성 변호사,blog.naver.com/dtive84494,20251014
1,"2025년, ‘비은행의 시대’ — 보이지 않는 금융권력이...",https://blog.naver.com/nandahaha_/224040771863,금리상승 #유동성리스크 #레버리지위험 #DSR강화 #저축은행 #캐피탈사 #보험사 #...,발길이 이끄는 대로,blog.naver.com/nandahaha_,20251014
2,씨오비 사기 사칭 코인투자 겉만 번지르르한 말들,https://blog.naver.com/mongoli62869/224039786745,말들 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기...,daylaw 강민성 대표 변호사,blog.naver.com/mongoli62869,20251014
3,넥스볼트 사기 NexVault 사칭 로맨스스캠 거짓의 포장지,https://blog.naver.com/mongoli62869/224039783984,포장지 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사...,daylaw 강민성 대표 변호사,blog.naver.com/mongoli62869,20251014
4,"[칼럼] 비밀과 투명성 사이 — 빌더버그 회의, 그리고 글로벌...",https://blog.naver.com/84jojo/224040749131,새로운 엘리트 구조 ― 기술기업과 중앙은행의 결합 오늘날 빌더버그의 새로운 축은 테...,인문학과 블록체인(화폐) 혁명,blog.naver.com/84jojo,20251014
...,...,...,...,...,...,...
95,프레스티지 웰스(PWM) 주가 전망: 1330% 상승 가능성과 투자...,https://blog.naver.com/qazwxxsd123/224037047245,AI <b>핀테크</b> 전환 전략과 가능성 프레스티지 웰스는 AI <b>핀테크</...,주식 하는 사람님의 블로그,blog.naver.com/qazwxxsd123,20251010
96,골드마인 사기 피해 직후의 대응 절차 살펴보기 (사칭),https://blog.naver.com/crnivorous20772/2240364...,(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자...,데이 강민성 변호사,blog.naver.com/crnivorous20772,20251010
97,"공매도 뜻, 투자 전략, 위험 관리, 제도 개선",https://blog.naver.com/m0ney-m0ney/224020732428,"특히, 2025년 현재 <b>핀테크</b> 기업들이 제공하는 AI 기반 공매도 분석...",돈 버는 방법,blog.naver.com/m0ney-m0ney,20251010
98,[ETF 종목분석] ARKK vs ARKQ 캐시 우드의 두 혁신 ETF 완전...,https://blog.naver.com/cho1minho/224037034056,"75% 주요테마 AI, 바이오, <b>핀테크</b>, 혁신산업 전반 자율주행, 로봇...",밍민 blog,blog.naver.com/cho1minho,20251010
99,금산분리 완화가 대기업에 좋은 이유와 우려,https://blog.naver.com/limze11/224037028627,"특히 규제 완화가 정보통신기술(IT)이나 <b>핀테크</b> 분야와 연계될 경우, ...",진정한 자유,blog.naver.com/limze11,20251010

# while문을 이용해서 수집페이지까지 자동화 하기

In [51]:
from dotenv import load_dotenv
import os
load_dotenv(dotenv_path="./data/.env_naver")
import requests

total_page = 1
page = 1
num = 1

all_data = []
while page <= total_page:
    user_id = os.getenv("user_Id")
    user_secret = os.getenv("user_Secret")
    url = "https://openapi.naver.com/v1/search/blog"
    keyword = "핀테크"
    payload = dict(query=keyword, display=100, start=num, sort="date")
    headers = {"X-Naver-Client-Id" : user_id, "X-Naver-Client-Secret" : user_secret}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
#     print(r.status_code)
    response = r.json()
    all_data.append(response['items'])

    # 전체 페이지 계산
    if response['total'] // 100 > 11:
        total_page = 11
    else:
        total_page = response['total'] // 100 + 1
        
    # page 증가
    page += 1
    
    #num이 1000되도록 
    if num < 901:
        num += 100
    elif num >= 901:
        num += 99

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=date

In [52]:
len(all_data)

11

In [61]:
result = {}
for page in all_data:
    for item in page:
        for key, value in item.items():
            if key in ["title", "description"]:
                result.setdefault(key, []).append(text_clean(value))
            else:
                result.setdefault(key, []).append(value)
final_df = pd.DataFrame(result)
final_df

,title,link,description,bloggername,bloggerlink,postdate
0,금융 심사의 미래 신용점수 vs 소셜 신용 점수,https://blog.naver.com/ouoigno361/224040533855,이런 방식은 아직 국내에서는 본격적으로 도입되지 않았지만 해외에서는 이미 일부 핀테...,소비의미학,blog.naver.com/ouoigno361,20251014
1,달라진 신용대출 금리 체계와 금융 소비자에게 다가올 주요,https://blog.naver.com/ggudaofficial/224040799628,최근에는 FICO 점수 외에도 은행 자체 모델이나 핀테크 기업의 대안 신용평가가 활...,GGUDA,blog.naver.com/ggudaofficial,20251014
2,넥스볼트 사기 NexVault 로맨스스캠 리딩방 수법 정밀 분석,https://blog.naver.com/lucifer49329/224040661212,사칭 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대...,데이 강민성 변호사,blog.naver.com/lucifer49329,20251014
3,리사블룸 사기 lsabbact 사칭 팀미션 가면 뒤의 진짜 얼굴,https://blog.naver.com/mongoli62869/224039790424,얼굴 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응...,daylaw 강민성 대표 변호사,blog.naver.com/mongoli62869,20251014
4,2025 10 14 한국 경제 신문 lt 최근에 쇼핑했던 주식들과 최근,https://blog.naver.com/haileytax/224040789155,비자 비자는 페이팔과 같은 이유 푸투 홀딩스 상대적으로 규모가 작은 핀테크 및 투자...,Hailey Tax Blog,blog.naver.com/haileytax,20251014
...,...,...,...,...,...,...
1095,Ant Group Launches Ling 1T China s Trillion,https://blog.naver.com/xogml314/224037085114,이 중국 핀테크 대기업은 복잡한 추론과 고성능 컴퓨팅을 위해 설계된 이 강력한 새 ...,★삼각지로타리에~★1967,blog.naver.com/xogml314,20251010
1096,고금리 파킹통장 CMA 통장 금리 차이점 비교,https://blog.naver.com/moneytimestack/22403708...,파킹통장 CMA 운영 주체 은행 저축은행 핀테크 증권사 상품 상세 고금리 입출금 통...,시간&돈의 복리효과,blog.naver.com/moneytimestack,20251010
1097,카카오 미래 산업 확장 전략 AI 모빌리티 메타버스로 그리는,https://blog.naver.com/ansqodi/224037070218,특히 일본에서는 픽코마 멜론 카카오톡 글로벌 버전 통합 모델을 추진 중이며 동남아에...,오지랖한스푼,blog.naver.com/ansqodi,20251010
1098,양자컴퓨터 시대 글로벌 선도 기업부터 한국 현황 투자까지,https://blog.naver.com/myrnak/224037068268,아름답습니다 양자컴퓨터 QuantumComputing 큐비트 IonQ Rigetti...,"투자와 육아, 함께 크는 이야기",blog.naver.com/myrnak,20251010
1099,2025 10 10 오늘의 Coinnews,https://blog.naver.com/quent_field2025/2240370...,안녕하세요 Quent Field입니다 오늘의 10월10일 주요 코인뉴스 소식 전달드...,quent_field2025님의 블로그,blog.naver.com/quent_field2025,20251010

In [62]:
final_df.to_csv("./data/네이버api수집1100개.csv", index=False, encoding="utf-8-sig")