In [1]:
import pandas as pd
import requests
import re
import time
from bs4 import BeautifulSoup as bs

# 뉴스 목록, 날짜, id 수집

In [8]:
url1 = "https://fintech.or.kr/web/board/boardContentsList.do"
payload1 = dict(miv_pageNo=1, mode="W", board_id=6)
r1 = requests.post(url1, data=payload1)
soup = bs(r1.content, "lxml")
soup

<html><head><script language="javascript">
$(document).ready(function(){

	// 댓글수 노출여부 확인후 숨기기(미구현)

		$(".comment_cnt").hide();


	// 답변 노출여부 확인후 숨기기(미구현)

		$(".reply_status").hide();


	// 모바일 전용 페이지 숨기지
	//$(".mobile_list").hide();

	$(function() {

	});

	$("#searchtxt").keydown(function(key) {
		if (key.keyCode == 13) {
			search();
		}
	});
});
</script>
</head><body><div class="boardlist_top">
<ul class="box">
<li class="select">
<div class="optionbox">
<select id="searchkey" name="searchkey">
<option value="I">전체</option>
<option value="T">제목</option>
<option value="C">내용</option>
</select>
</div>
</li>
<li class="input">
<div class="inpbox"><input class="txt" id="searchtxt" name="searchtxt" placeholder="검색어 입력" title="검색어 입력" type="text" value=""/></div>
</li>
<li class="button">
<button class="btn3 bg_blue" onclick="search();" title="검색" type="button">검색</button>
<!-- <button type="button" class="btn3 bg_gray" title="재검색">재검색</button> -->
</li>
</ul>
</div>
<!--// list_table_area -->
<div class="boardlist">
<table>
<caption>게시판 목록</caption>
<colgroup>
<col style="width: 10%;"/>
<col style="width: 75%;"/>
<col style="width: 15%;"/>
</colgroup>
<thead>
<tr>
<th class="first" scope="col">
								번호



























								</th>
<th class="" scope="col">


								제목

























								</th>
<th class="last" scope="col">























								작성일




								</th>
</tr>
</thead>
<tbody>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('b4b0b17c318d45158645c81c1472e29a')">[금융보안원] 「데이터허브」 이용 안내</a>
</td>
<td class="last">





























								2025-09-17








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('51cb0e37c4064f2a985436e2ae3378df')">[국무조정실] 규제개혁신문고 제도 안내</a>
</td>
<td class="last">





























								2024-02-20








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('3c24d05040984c79a7cdfd2c921952eb')">[기술보증기금] 핀테크 기업을 위한 주요 보증상품 안내</a>
</td>
<td class="last">





























								2022-12-19








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('25f4360d5b9847a996828099e8d52ade')">[신용보증기금] 스타트업 지원 업무 안내</a>
</td>
<td class="last">





























								2022-12-19








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('9c16609a99ad4c55914ffa9a7f2d58b7')">[한국무역보험공사] K-Sure 수출컨설팅 사업 안내</a>
</td>
<td class="last">





























								2022-06-20








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('6b14460b5adc480aa050c4c535af8b72')">[한국예탁결제원] 예탁결제원 보유 데이터 활용 안내</a>
</td>
<td class="last">





























								2021-12-03








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('d4cbbeb3f9b3444cbf1856b48f9f2926')">[웰컴저축은행] 마이데이터 서비스 제휴 솔루션</a>
</td>
<td class="last">





























								2021-04-07








































							</td>
</tr>
<tr>
<td class="first">




									6815




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('f61663288d694d068e33d00054b22595')">[10/21 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-10-21








































							</td>
</tr>
<tr>
<td class="first">




									6814




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('760c4ae4b76f449aa23de004e8200bc5')">[10/20 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-10-20








































							</td>
</tr>
<tr>
<td class="first">




									6813




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('ad2eb2c521ab4e9fa32cb00a625cbd69')">[10/17 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-10-17








































							</td>
</tr>
<tr>
<td class="first">




									6812




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('c80032073f994fb4b669d70bb5917c18')">[10/16 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-10-16








































							</td>
</tr>
<tr>
<td class="first">




									6811




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('c579f3baf033478483098dc813b47e1f')">[10/15 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-10-15








































							</td>
</tr>
<tr>
<td class="first">




									6810




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('f7a7f75aa51045209c20eff82dc21e90')">[10/14 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-10-14








































							</td>
</tr>
<tr>
<td class="first">




									6809




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('b45fb58dc8094571a48344594ab19176')">[10/13 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-10-13








































							</td>
</tr>
<tr>
<td class="first">




									6808




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('aeea59af5aea4346a8d53ed2605993e5')">[10/10 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-10-10








































							</td>
</tr>
</tbody>
</table>
<!-- mobile -->
<ul class="list">
<li class="notice_line">
<a href="javascript:contentsView('b4b0b17c318d45158645c81c1472e29a')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[금융보안원] 「데이터허브」 이용 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-09-17</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('51cb0e37c4064f2a985436e2ae3378df')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[국무조정실] 규제개혁신문고 제도 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2024-02-20</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('3c24d05040984c79a7cdfd2c921952eb')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[기술보증기금] 핀테크 기업을 위한 주요 보증상품 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-12-19</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('25f4360d5b9847a996828099e8d52ade')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[신용보증기금] 스타트업 지원 업무 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-12-19</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('9c16609a99ad4c55914ffa9a7f2d58b7')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[한국무역보험공사] K-Sure 수출컨설팅 사업 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-06-20</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('6b14460b5adc480aa050c4c535af8b72')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[한국예탁결제원] 예탁결제원 보유 데이터 활용 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2021-12-03</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('d4cbbeb3f9b3444cbf1856b48f9f2926')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[웰컴저축은행] 마이데이터 서비스 제휴 솔루션



								</div>
</div>
<ul class="name">
<li>작성일 : 2021-04-07</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('f61663288d694d068e33d00054b22595')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[10/21 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-10-21</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('760c4ae4b76f449aa23de004e8200bc5')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[10/20 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-10-20</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('ad2eb2c521ab4e9fa32cb00a625cbd69')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[10/17 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-10-17</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('c80032073f994fb4b669d70bb5917c18')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[10/16 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-10-16</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('c579f3baf033478483098dc813b47e1f')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[10/15 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-10-15</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('f7a7f75aa51045209c20eff82dc21e90')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[10/14 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-10-14</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('b45fb58dc8094571a48344594ab19176')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[10/13 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-10-13</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('aeea59af5aea4346a8d53ed2605993e5')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[10/10 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-10-10</li>
</ul>
</a>
</li>
</ul>
<!--//mobile -->
</div>
<!--// list_table_area -->
<!-- button_area -->
<div class="btn_box ar">
</div>
<!--// button_area -->
<!-- paging_area -->
<div class="paging web_only">
<div class="box"><button class="btn-paging-first" onclick="go_Page(1)" title="처음" type="button">처음</button><button class="btn-paging-pre" onclick="return false;" title="이전" type="button">이전</button><span><a class="on" href="javascript:;">1</a><a href="javascript:go_Page(2);" title="2">2</a><a href="javascript:go_Page(3);" title="3">3</a><a href="javascript:go_Page(4);" title="4">4</a><a href="javascript:go_Page(5);" title="5">5</a><a href="javascript:go_Page(6);" title="6">6</a><a href="javascript:go_Page(7);" title="7">7</a><a href="javascript:go_Page(8);" title="8">8</a><a href="javascript:go_Page(9);" title="9">9</a><a href="javascript:go_Page(10);" title="10">10</a></span><button class="btn-paging-next" onclick="go_Page(11);" title="다음" type="button">다음</button><button class="btn-paging-last" onclick="go_Page(455)" title="마지막" type="button">마지막</button></div>
</div>
<!--// paging_area -->
<!-- paging_area -->
<div class="paging mobile_only">
<div class="box"><button class="btn-paging-first" onclick="go_Page(1)" title="처음" type="button">처음</button><button class="btn-paging-pre" onclick="return false;" title="이전" type="button">이전</button><span><a class="on" href="javascript:;">1</a><a href="javascript:go_Page(2);" title="2">2</a><a href="javascript:go_Page(3);" title="3">3</a><a href="javascript:go_Page(4);" title="4">4</a><a href="javascript:go_Page(5);" title="5">5</a></span><button class="btn-paging-next" onclick="go_Page(6);" title="다음" type="button">다음</button><button class="btn-paging-last" onclick="go_Page(455)" title="마지막" type="button">마지막</button></div>
</div>
<!--// paging_area --></body></html>

In [33]:
len(soup.select("a.txtl"))

15

In [55]:
len(soup.select("td.last"))

15

In [45]:
def text_clean(text):
    return re.sub("[^가-힣a-zA-Z0-9-]", "", text)

In [46]:
text_clean(soup.select("td.last")[0].text)

'2025-09-17'

In [47]:
contents_id_list = []
for date, content_list in zip(soup.select("td.last"), soup.select("a.txtl")):
    date = text_clean(date.text)
    contents_id = content_list['href'].split("'")[1]
    contents_id_list.append((date, contents_id))
contents_id_list

[('2025-09-17', 'b4b0b17c318d45158645c81c1472e29a'),
 ('2024-02-20', '51cb0e37c4064f2a985436e2ae3378df'),
 ('2022-12-19', '3c24d05040984c79a7cdfd2c921952eb'),
 ('2022-12-19', '25f4360d5b9847a996828099e8d52ade'),
 ('2022-06-20', '9c16609a99ad4c55914ffa9a7f2d58b7'),
 ('2021-12-03', '6b14460b5adc480aa050c4c535af8b72'),
 ('2021-04-07', 'd4cbbeb3f9b3444cbf1856b48f9f2926'),
 ('2025-10-21', 'f61663288d694d068e33d00054b22595'),
 ('2025-10-20', '760c4ae4b76f449aa23de004e8200bc5'),
 ('2025-10-17', 'ad2eb2c521ab4e9fa32cb00a625cbd69'),
 ('2025-10-16', 'c80032073f994fb4b669d70bb5917c18'),
 ('2025-10-15', 'c579f3baf033478483098dc813b47e1f'),
 ('2025-10-14', 'f7a7f75aa51045209c20eff82dc21e90'),
 ('2025-10-13', 'b45fb58dc8094571a48344594ab19176'),
 ('2025-10-10', 'aeea59af5aea4346a8d53ed2605993e5')]

# 날짜별 뉴스 모음에 들어가 해당 날짜 뉴스 모음 제목과 링크 수집하기

In [68]:
result = {}
for idx, (date, content_id) in enumerate(contents_id_list):
    print(f"{idx+1}/{len(contents_id_list)} {content_id} 수집중", end="\r")
    url2 = "https://fintech.or.kr/web/board/boardContentsView.do"
    payload2 = dict(miv_pageNo=1, mode="W", contents_id=content_id, board_id=6, searchkey="I")
    r2 = requests.post(url2, data=payload2)
    soup2 = bs(r2.content, "lxml")
    
    for td in soup2.select("tbody td"):
        if td.select_one("a") != None and td.select_one("a")['href'] != "https://fintech.or.kr/":
    #         print(td.select_one("a").text)
    #         print(td.select_one("a")['href'])
            result.setdefault("제목", []).append(td.select_one("a").text)
            result.setdefault("원문링크", []).append(td.select_one("a")['href'])
df = pd.DataFrame(result)

In [69]:
df

,제목,원문링크
0,"한국핀테크지원센터, 핀에듀 AI 활용 실무 온라인 교육 과정 5종 신규 개설",https://www.etnews.com/20251017000242
1,[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Aca...,https://fintech.or.kr/web/board/boardContentsV...
2,[한국핀테크지원센터] AICC 기반 금융 서비스 자동화 교육 과정 수강생 모집(~선착순),https://fintech.or.kr/web/board/boardContentsV...
3,[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생...,https://fintech.or.kr/web/board/boardContentsV...
4,[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지),https://fintech.or.kr/web/board/boardContentsV...
...,...,...
401,"美 셧다운·금리인하 기조에… 금·은·코인으로, 돈의 대이동",https://n.news.naver.com/mnews/article/008/000...
402,"“AI붐은 버블, 25년전 닷컴 때과 비슷”...IMF·영란은행, 증시 과열에 경고",https://n.news.naver.com/mnews/article/009/000...
403,[디캠프·한국핀테크지원센터] startup OI #금융권-스타트업 우수 협력 사례 ...,https://fintech.or.kr/web/board/boardContentsV...
404,[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시),https://fintech.or.kr/web/board/boardContentsV...
405,[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기...,https://fintech.or.kr/web/board/boardContentsV...

In [70]:
for title in df['제목']:
    print(title)

한국핀테크지원센터, 핀에듀 AI 활용 실무 온라인 교육 과정 5종 신규 개설
[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Academy’참여자 모집(~선착순 마감)
[한국핀테크지원센터] AICC 기반 금융 서비스 자동화 교육 과정 수강생 모집(~선착순)
[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)
[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지)
[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)
금융위원장 “금산분리 합리화, 실용적 방안 고민중…핀테크 지분 투자 확대 허용”
스테이블코인 법제화 가시화…금융위 “준비자산은 예금·국채 등으로 100% 보유 의무”
FIU "가상자산거래소 '오더북 공유', 개인정보 불법유출 감독할 것"
금융위원장 "부동산 자금쏠림 개선…필요시 즉각 추가 조치"
이억원 "금융소비자 보호…보이스피싱 금융권 책임 법제화"
금감원, 이번주 ‘홍콩 ELS’ 일부 과태료 결정
렌탈페이, 비영리단체·지자체와 손잡고 ‘상생 결제 문화’ 확산 나서…
리트러스트, 블록체인 기반 ESG 서비스 확장… NFT·EU 규제 대응 솔루션 선보여
‘4살 된’ 토스뱅크, 회원 1375만명 돌파…혁신기술로 ‘포용금융’ 실천
카카오뱅크, 글로벌 인력 채용 본격화…태국·인니 진출 박차
'車보험 비교·추천 서비스 2.0' 계약체결률 약진
네·카·토 '선불충전금'도 상속 가능
3분기 순익 5조 육박…4대 금융, '역대급 실적' 전망
‘항암보장’ vs ‘라이브청구’…펫보험 경쟁 2라운드 돌입
외국인도 현지서 국내주식 사고 판다… 하나증권, 통합계좌 첫 거래 성사
은행대리업, 효율·포용 '두마리 토끼' 잡을까
2금융권 고금리 상품 실종에… 예금자보호 1억 상향에도 머니무브 ‘아직’
은행권 ISA수익률 ‘상위 1%’, 국내 주식 비중 9배 껑충
손해율 악화·비용 부담…보험업계 3분기도 막막
39만명 2년간 ‘대출 갈아타기’ 21조원…1인당 이자 174만원 절감
기간·금액 최소화… ‘미니보험’으로 젊은층 공략
저축은행, '모임통장' 출시 임박…수익·신규 고객 동시에 노린다
손주들 용돈 고민?… 어린이-청소년 전용 금융상품 이용하세요
3가지 채권 포트폴리오로… 안정적 노후 자산관리를
AI 시대 열어갈 '금산분리 규제개혁'[금융시장 돋보기]
‘방향’ 못잡는 한은 금리 어디로 가나, 미국 연준 금리 격차 ‘벌어진다’
"이거 다 해도 돈 한 푼 안 내요" 비싼 시술 줄줄이…자동차보험 줄줄 샌다
[AI의 골든룰] AI 전환, 속도보다 중요한 것이 있다
[송민택 교수의 D-엣지] 데이터 주권과 금융의 민주화
"금리 변동성 최소화해야"…보험업계, 'ALM' 관리 시험대
국내은행 인니 금융시장 존재감 확 커졌다...업계 "더이상 소규모 은행 아니다"
NXT, 조각투자 플랫폼 인가전 참전…4파전 경쟁 ‘치열’(종합)
[강현철의 뉴스 솎아내기] ‘탈 달러화’가 밀어올린 국제 금값
[S리포트] ①"그림자에서 제도권으로"… 달라진 가상자산 위상
[S리포트] ②가상자산거래소의 '변신'… 중개업에서 '금융 플랫폼'으로
[한경에세이] 생산적 금융의 성공 열쇠
“비트코인, 주식처럼 산다”…日, 은행에 암호화폐 투자 ‘문호 개방’
중국 '생성형 AI' 사용자 5억명 넘어서…90% 이상이 중국 제품 써
[마켓인]금리인하에 유럽 PE '역대급 활황'…메가딜만 70건 넘을 듯
"트럼프표 관세, 소비자 고통 아직 …시간 문제" EBC 총재
3대 악재 덮친 美 차업계…희토류·알루미늄·반도체 공급난
[특파원 칼럼] 中 레드테크 뒤엔 AI 조기 교육
[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시)
[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기업 투자/협력- (프로그램별 상이)
[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Academy’참여자 모집(~선착순 마감)
[한국핀테크지원센터] AICC 기반 금융 서비스 자동화 교육 과정 수강생 모집(~선착순)
[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)
[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지)
[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)
국내 금값, 국제 가격보다 13% 높아…금감원 "투자 유의해야"
금융위 FIU, 캄보디아 범죄 관련자 금융거래 제한 검토
금융당국, 보험사 건전성 부담 완화…‘최종관찰만기 30년 적용’ 8년 늦춘다
정부, 금융권 全업권 해외송금 내역 실시간 통합관리 구축한다
이찬진 금감원장 “해킹 과징금, IT 보안투자 비용보다 많아야”
금감원, 즉시연금 불완전 판매 여부 살핀다
금감원, 고령층 위한 'FSS 시니어 금융 아카데미' 신설
헥토이노베이션, 디지털자산 지갑 사업으로 그룹사 전체에 시너지 창출
대출금리 절감이 유저경험 개선… '실질' 혜택 설계하는 뱅크샐러드
카카오뱅크, 중·저신용 개인사업자 대출 확대
토스뱅크, 이자만 내는 거치기간 1년 제공
다날, 'AI 기반 데이터 핀테크' 본격화…스타트업과 상생형 혁신 나서
포인트 모으며 펫 키운다…네이버페이 ‘페이펫’ 새 단장
주담대 보릿고개에 인뱅들도 '울상'
대출금리 연 4% 육박 고착화…좁혀지지 않는 예대금리차
보험료 할인·대출상환 유예…보험사들 '저출산' 지원사격
“디지털 뱅크런 대비하자”…한은, 은행 대출채권도 긴급여신 담보로 인정
충당금·유동성 규제 '이중폭탄'..상호금융 "지역금융 위축, 유예 필요"
3%대 고금리 자취 감췄다...저축은행 예금금리 3년여 만에 최저
[금융 라운지] 수수료 수익 줄자 …빅데이터서 해법 찾는 카드사
전문가들 "10월 금통위 '금리 동결' 유력"…추가 인하는 11월?
"해외 주식 '사상 최대'"…국내 증권사 '글로벌 브로커' 전환 가속
'책무구조도' 마저 무용지물?… 4대 은행 올해 금융사고액 1700억원, 사고 건수도 '사상 최대'
스테이블코인 '은행 필참'유력… 컨소시엄 구성 전쟁 시작됐다
은행들 문턱 더 높인다…연말까지 대출 절벽
'역대 최대' 밀린 카드 빚 1조 5천억 육박…4년새 2배 껑충
"가뭄 끝, 물줄기 터졌다"…헬스케어·AI·핀테크서 쏟아진 유니콘
‘프로젝트 한강’ 예금토큰 절반 이상 안 써
[정유신의 핀테크 스토리]글로벌 스테이블코인과 AI의 시너지
[ET톡] 원화스테이블코인, '활용 방안' 논의해야
[ET시론] 디지털 화폐 경쟁시대, 한국은?
AI 결제 올라탄 빅테크에 韓 지급결제 시장도 '들썩'
은행·증권 보안 투자 70% 늘릴 때… 카드·손보는 20% 찔끔[금융권 정보보호예산 큰 격차]
[매경데스크] 블록체인과 K팝이 만난다면
집에서 내 주식 찾고 현금배당금 조회…예결원 비대면 증권대행 서비스 주목
간편 청구 1년…‘실손 간소화’ 무엇이 달라졌나
[한경에세이] 디지털 금융이 바꿔 가는 세상
[사설] 日 스테이블코인 속도전, 우리도 본격 공론화 필요하다
中, 4중전회 키워드 ‘극심한 경쟁·디플레·과잉생산’ 복합된 ‘인볼류션(퇴행)’ 대응
WSJ, "트럼프, 상호 관세 완화하고 품목 관세는 확대"
日 3대 메가뱅크, 스테이블 코인 공동 발행 추진
[트럼프 스톡커] 월가에 퍼지는 '제2 SVB 공포', 무시해도 될까
中, 스테이블코인 '급제동'…알리바바·징둥 사업 중단
‘사상 처음’…엔비디아, 美서 최신 AI 칩 ‘블랙웰’ 생산
[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시)
[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기업 투자/협력- (프로그램별 상이)
[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Academy’참여자 모집(~선착순 마감)
[한국핀테크지원센터] AICC 기반 금융 서비스 자동화 교육 과정 수강생 모집(~선착순)
[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)
[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지)
[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)
금감원, 자사주 교환사채 공시기준 강화…“주주 영향 명시해야”
금감원, 신한투자증권에 '기관경고'…발행어음 인가는 가능
금융당국, 보험사 자산운용 '생산적 금융' 가도록 규제 합리화 추진
"규제우회·풍선효과 막아라"…금융당국, 대출관리 전방위 점검
금감원, 내년 감사인 지정 결과 사전통지…기업 1230곳 대상
아톤, 메리츠증권에 안면인식 솔루션 공급…화이트박스 암호화 기술 적용
토스뱅크, 아이서비스 보호자 2인 등록 가능…부모 함께 자녀 금융 관리
'업비트' 급한 불 끈 케이뱅크, IPO 신무기는 '사장님'
토스페이먼츠, 미스터홈즈와 업무협약 체결…부동산 거래 투명성 높인다
카카오페이 '택스리펀드' 출시, “해외 부가세 카카오페이머니로 받는다”
외국인 지난달 국내주식 6조680억 순매수…5개월 연속 '사자'
9월 가계대출 1.1조 증가…6개월 만에 최저 증가폭
한은 금통위 기준금리 '동결' 우세…연내 추가 인하도 '미지수'
댕냥이들 치료 후 실시간 보험급 지급 가능해진다…펫보험 혁신 주목
카드사, 일반 가맹점 수수료율 올리며 버텼는데… 당국 동결 요구에 수익성 비상
“대출한도 8600만원 증발”…10·15 대책이 바꾼 ‘스트레스 DSR의 계산법’
8월까지 4대 은행 금융사고액 1900억…작년 사고액 넘어
가계대출 규제가 부른 금리 왜곡… 코픽스 대폭 하락, 주담대는 ‘찔끔’
예탁금 80조 사상 최대… 개인 투자자도 참전 준비
신한·하나은행, 비대면 대출접수 중단…대출 보릿고개 현실화
이달만 8825억↑… 주담대 누르니 '마통' 부풀었다
어려운 문제를 쉽게 풀면 해답은 틀린다[퇴직연금 인사이트]
토큰증권 제도화 앞… 영국 ‘펀드 토큰화’ · 프랑스 ‘주식 토큰화’ 추진
[데스크라인]금융위, GA 정보유출 대응책 마련해야
AI가 이끄는 금융산업의 새로운 전환점 [삼일 이슈 프리즘]
[이슈플러스] 연이은 보안 사고, 금융권 '통합보안' 대안 떠오른다
증여성 해외송금 4조원 넘어… 美가 1조6000억 최다
퇴직연금 시장서 ‘로봇 투자 전문가’ 두각
외국인 근로자 본국 송금액 25조…송금 사각지대 우려
“토큰증권, 중소기업 자금조달 다변화의 새 기회로”
[투데이 窓]창업가정신 관점에서 본 네이버·두나무 빅딜
'글로벌 대장' 온다…바이낸스 韓 진출에 국내 거래소 '긴장'
[단독]한계 내몰리는 저신용자들… 20개 대부업체 연체율 10% 넘어
구글, 150억달러 들여 인도에 데이터센터 ...AI 허브로 부상하는 인도
금값 폭등에 웃는 이탈리아…“절대 안 팔아”, 미·독 이어 보유량 3위
트럼프, EV 보조금 칼 빼들자 GM·포드 줄줄이 '백기'...테슬라에 기회?
인재 22만명 빨아들인 홍콩, 주거비 '천정부지'
중국産 부품 줄이는 MS…빅테크 '脫중국' 속도
"은행 못 믿겠다"…'찐부자들' 돈 굴리는 방법 알고 보니 [글로벌 머니 X파일]
월러 美 Fed 이사 "고용 둔화 대응 위해 금리 0.25%P 내려야"…마이런은 '빅컷' 주장
[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시)
[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기업 투자/협력- (프로그램별 상이)
[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Academy’참여자 모집(~선착순 마감)
[한국핀테크지원센터] AICC 기반 금융 서비스 자동화 교육 과정 수강생 모집(~선착순)
[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)
[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지)
[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)
금감원, XBRL 공시시스템 국제표준 인증…"데이터 품질 우려 해소"
금융위 "스트레스DSR 금리 상향에 대출 한도 최대 14.7%↓"
금융위, ESG 공시 ‘글로벌 기준선’ 논의…국제정합성·투자자 신뢰 높인다
이억원 금융위원장, 보험사 CEO들 만난다… 부채 할인율 현실화 논의
금융위 “서민금융 대전환”…과징금으로 펀드 조성해 피해 신속 구제
금감원, 회계법인 지배구조·'네트워크 법인 비감사용역' 공시 추진
사회적 기여요구에 자금이탈까지... 금융硏 “은행권 생산금융 여력 하락 우려”
금융위, 정책설계부터 소비자 목소리 듣는다…평가위원회 신설
금융위 증선위, 회계처리 기준 위반 2개사 제재
금감원, 900억 전액 손실 낸 ‘벨기에 펀드’ 판매사 검사
케이뱅크, 고객 1500만 돌파…고속 성장세에 IPO 탄력 기대감 ‘쑥’
정산부터 대출까지 한 번에…네이버페이, 신한은행과 사업자 전용 '금융 패키지' 출시
렌탈페이, 월세카드결제 이용 고객 ‘런칭 3개월 만에 급증’
카카오뱅크, 1000조 개인사업자 여신 '출사표'…담보대출 전략은
토스 "앱인토스, 금융 넘어 생활서비스로 확장"… 출시 100일 만에 제휴 미니앱 200개 돌파
네·카·토·쿠 간편결제 4사, 선불충전금 2분기 연속 1조원대 유지
"3분기에도 장사 잘했네"… 연간 최대 실적 예고한 4대 금융
ELS 17만건… '건당 과태료' 폭탄 터지나
위험·안전 자산 모두 최고가…금융시장 ‘에브리싱 랠리’
하나·신한은행, 카카오·케이뱅크 비대면 대출 신청 일시중단
부동산 추가 대책에도 10월 금리동결 유력…"연내 인하 불투명"
[THE FINANCE] 고령화로 치매 인구 ‘급등’… 치매 보험 상품 출시
각국 외환보유액 달러 비중… 2001년 71% → 작년 57%
“추석 특수에 지갑 먼저 열었다” 이커머스, 3분기 선불충전금 16%↑
"금리 좀 내려주세요" 저축銀 대응 극과 극
은행들 턱밑까지 찬 '대출 총량'…더 센 규제에 '대출 절벽' 온다
되살아난 은행권 기술신용대출…9월에만 2.2조 늘려
IMF “3050억달러 스테이블코인 시장, 글로벌 금융 불안의 새 뇌관”
"금융산업, 부동산 PF서 벗어나 혁신기업 투자 늘려야"
스테이블코인, 美금융시스템 핵심으로… ‘달러 신뢰의 레일’ 놓는다
금융보안원, AI 활용 금융권 통합보안관제 고도화 추진
다른 회사 도입하니까 우리도 한다? AI로 뭘하고 싶은지, 먼저 질문하라
[데스크칼럼] AI 시대 은행, 사람도 신뢰도 잃었다
올해에만 가상자산 124조 해외 유출
[ET단상] 코인없는 블록체인은 허상이다
‘페이·코인’ 강자들의 빅딜… 초대형 금융플랫폼 예고[Who, What, Why]
해킹사고·디지털 전환 여파에 설 자리 잃어가는 카드모집인
[기고] 스테이블코인 발행사, 은행-핀테크 논쟁을 넘어 '자격 기준'으로
'생산적 금융' 이끌어갈 증권업…풀어야 할 숙제는
1.2경원 美 퇴직연금 시장 빗장 풀리나…트럼프發 ‘암호화폐 401(k)’ 법제화 시동
"1조달러 쏟아붓는다…오픈AI 5년 계획 마련중"
美 AI·크립토 총책 “가상자산 3년내 제도권 완전 편입…중국과의 AI 경쟁 이길 것”
"유럽서 장사하려면 기술 내놔"…EU, 中 기업에 '강제 기술 이전' 검토
美재무, 對中 관세 500% 가능성 시사…"中 희토류 통제에 동맹국 공조해야"
TSMC, 3Q '사상 최대 매출' 예약…독주체제 언제까지?
[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시)
[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기업 투자/협력- (프로그램별 상이)
[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Academy’참여자 모집(~선착순 마감)
[한국핀테크지원센터] AICC 기반 금융 서비스 자동화 교육 과정 수강생 모집(~선착순)
[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)
[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지)
[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)
통증치료로 둔갑한 피부미용…금감원, 보험사기 일당 131명 적발
이찬진 금감원장 “회계법인, 보수 경쟁 아닌 감사 품질 개선에 힘써야”
금감원, 7년간 카드사 67회 검사…롯데카드 가장 많아
명절 쉰 금감원, iM금융 검사 재돌입…하나금융도 검사 앞둬
권대영 금융위 부위원장 "MBK, 홈플러스 사태에 더 책임 보여야"
금감원 "유사투자자문업자 투자사기 주의…신고이력 살펴야"
K-핀테크, '대안신용평가' 모델로 '동남아 금융시장' 노린다
블록체인 기반 핀테크 스타트업 ‘크로스허브’, 시드 투자 8억 유치
핀다, 새 브랜드 캠페인 선봬…누구나 원하는 금융 찾는다
네이버페이(Npay), iM뱅크와 지역경제 활성화·디지털 결제 혁신 협력
카카오뱅크, 중·저신용 대출 누적 15조원 공급… "대안신용평가 고도화 효과"
"사기의심 계좌예요" 토스뱅크, 중고거래 사기 예방 시스템 도입
5대 은행, 가계대출 ↓ 생산적 금융↑… 가계·기업 '희비교차'
"대출 막힌다" 은행 영업점 전화 북새통… 가계대출 전방위 압박에 혼란
회사채 늘리는 대기업… 은행권은 '속앓이'
산업은행, 5000억 규모 한국형 녹색채권 발행…친환경 프로젝트 자금 지원
치솟는 원달러 환율…은행권, 한은 금통위 주목하는 이유
정부 규제 원투펀치에… 삼성·한화·교보생명, 주담대 4년만에 30조 붕괴
“낸 돈보다 돌려받는 금액이 더 많네”…목돈 마련에 좋다는 보험상품 주의할 점은
車할부금융으로 활로 찾는 카드사… 신한 업계 ‘선두’
해외여행 늘자 여행자보험 신계약 37% 증가
“일단 팔고 보자”...4대은행, 연체율 치솟자 부실채권 ‘패닉셀링’
저축은행, PF 부실 털기 총력…5차 정상화 펀드로 연체율 6%대 '정조준'
소비자 울리는 보험사 금리 인하…보험료 인상 ‘부메랑’ 되나 [서민금융 역설]
연기금풀 주간사 경쟁, 대형 운용사 ‘굳건’…증권사 ‘첫발’ 무산[마켓시그널]
금융위·한은 ‘기후 대응’ 아시아 13개국 중 8위…“기후금융 정책이 있으나 실행 미흡”
[블록체인 칼럼]관세 장벽 시대, 가상자산이 열어주는 무역 탈출구
돌아가신 아빠가 남긴 '숨은 유산'…어떻게 찾았나 봤더니
급등하는 환율, 흔들리는 원화…'원화 스테이블코인' 해법 될까
금융보안원, CSP 9개사와 손잡고 ‘금융권 클라우드 보안 참고서’ 발간
예금보호 1억 상향에…예보, 보험료율 재산정 착수
5대 금융 수장, 국감대신 미국 총출격…‘밸류업 세일즈’로 주가 견인한다
'스테이블 코인' 미국은 주목하고, 중국은 금지하고... 무엇이 정답일까
[기고] AI 혁신, 멀티터치의 종말
“키오스크 결제, 어렵지 않아요”…‘고령층 집중 금융교육’ 나서
보먼 연준 이사 “CBDC 추진 계획 없어…디지털자산·AI는 이해 우선 접근”
中이 쥐고 있는 美 숨통 틔워주려나...JP모건, 희토류·양자컴 등에 2000조 투자
금·은값 쭉쭉 오른다…금 4100달러 뚫고, 은파동 고점 돌파
美, 수입목재 10% 관세 발효…소파·주방찬장 등엔 25%(종합)
구글 22조, 아마존 18조…AI데이터센터 성지로 떠오르는 이 나라
파월, 10월 금리 인하 가능성 시사…"양적긴축은 곧 종료"
IMF, 올 세계 성장률 3.2%로 0.2%P 상향…"관세 부작용 에상보다 안 커"
[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시)
[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기업 투자/협력- (프로그램별 상이)
2025 핀테크 전문가 과정 ‘FinBoost Academy’(개발자 과정) 참가자 모집(~선착순)
[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Academy’참여자 모집(~선착순 마감)
[한국핀테크지원센터] 「제8회 핀테크 아이디어 공모전」(~10.14.)
[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)
[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지)
[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)
독일 최대 인뱅 CEO 줄퇴진에 금감원 “핀테크 규제 완화 신중해야”
소비자보호강화 속도내는 금융당국... 집단소송 전면확대 등 법안도 속속
[단독]금감원, 은행에 ELS 1차 제재안 발송…전체 과징금 최대 6800억 전망
국내외 경제 현안 산더미 속 '금융당국 개편' 속도 낼까
잇다른 금융권 해킹 피해에…‘비대면 은행’ 인뱅, 보안 투자 ‘쑥’
핀다, ‘우수 대부업 대출 비교 중개 서비스’ 개시… "금융 취약계층 대출 선택지 넓혀"
헥토그룹, '월렛원' 인수로 디지털지갑 사업 시작한다
케이뱅크, '사장님 부동산담보대출' 대환 상호금융권까지 확대
토스플레이스, 전국 20만 가맹점 돌파…젊은 상권 중심으로 확산
카카오뱅크, '우리아이통장·적금' 출시 한달여만에 10만명 돌파
신용사면자 대출 괜찮나…고심하는 은행
하나·신한카드, 트래블카드로 돌파구… 해외 사용액 두자릿수 증가
후기 고령자·치매머니 잡기…보험사 신탁 시장 주도권 경쟁 치열
“가족 단위로 묶는다” 금융권, '패밀리 금융' 경쟁 본격화
날개 단 금값에 金신탁 고공행진…서울서 2.1㎏ 맡긴 70대 사례도
자동차보험 긴급출동서비스, 섬·산간에도 내년부터 전면 적용
은행대리업 물꼬…리스크 관리는 숙제
[금융 라운지] "300만 외국인 잡자" 外人 특화카드 출시 러시
올 피싱 피해 1조3천억 육박… 총력 대응 나선 은행권
"보험료 오르기 전에 가입하세요"…공시이율 하락에 '막차 영업' 활개
금융지주 3분기 '역대급 실적' 전망…하반기엔 불황·대출규제 '변수'
관세 협상이 주담대 금리에도 영향…"변동형 금리가 더 낮네"
실손청구 전산화, 2단계 시행 초읽기…'3.3%' 저조한 병의원 참여가 숙제
보이지 않는 돈, 남겨진 흔적 : 블록체인의 투명한 역설 [가상자산 불공정거래 읽어주는 남자]
"못 사고 못 팔았다"… 증권사 전산장애, 5년 새 500건
[김호광 칼럼] 트럼프가 쏘아 올린 작은 공, 가상자산 도박장에 경종을 울리다
가상자산 M&A 3배 급증…금융·핀테크 '합종연횡' 본격화
‘업비트 효과’ 넘어야…케이뱅크, 추가 성장 돌파구는?
[전문가 기고]지역화폐, 스테이블코인으로 정책을 설계한다면
[현장에서]인니 빈부격차 한계…"지금은 버티는 시기" 국내은행들의 현실
[화요경제 항산항심] 쐐기문자~디지털화폐…화폐 본질은 신뢰다
앞면은 혁신, 뒷면은 불안…스테이블 코인은 던져졌다
[시론] 금융소비자보호, 금융 쇄신의 출발점
[로터리] 인공지능 시대 저작권의 역할
엔비디아, 벤처투자로 ‘AI 제국’ 건설...인프라·로봇·핵융합까지
오픈AI “아르헨티나에 35조 원 규모 투자 추진”
‘금값 폭등’ 중국 은행권, 고객들에 ‘투자 주의보’
세계 경제, 관세∙부채·AI 버블 ‘삼중 위험’ 직면
"땡큐 트럼프"…M&A 활황에 월가 호실적 전망
미·중, 시장 눈치 본다지만…다음달 2가지 더 틀어막을수도 있다는 중국
[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시)
[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기업 투자/협력- (프로그램별 상이)
2025 핀테크 전문가 과정 ‘FinBoost Academy’(개발자 과정) 참가자 모집(~선착순)
[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Academy’참여자 모집(~선착순 마감)
[한국핀테크지원센터] 「제8회 핀테크 아이디어 공모전」(~10.14.)
[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)
[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지)
[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)
금품 수수하고 대출 한도 높여준 은행원...금융당국 제재
'잊고 있던 내 돈 찾아볼까'...여기서 확인하고 '파인'
불법 출금 막는 ‘8가지 무료 금융 서비스’ 신청하세요
이것이 요즘 '금융 마케팅' 트렌드?… 핀테크 업체 '에임', 차별화된 전략 눈길
토스증권, 미국주식 배당금 ‘공휴일 지급’ 정례화
카카오페이證, 27일부터 넥스트레이드 메인 마켓도 참여[마켓시그널]
최고 年 7% 적금도 있네… 우리 아이 추석 용돈 통장 만들어볼까
"은행 왜 가요?" 2% 이자 그만…'은행 닮은 증권사'가 온다
“보험금 못 받은 고객 늘었다”… 보험사 의료자문 통한 '부지급' 급증
카드사, 해외결제 새 판 짠다…아시아 네트워크로 무게 이동
불법사금융예방대출 재원 2027년 고갈 전망... 수요 느는데 연체율도 급증
저축은행 7100억원 규모 5차 PF 펀드 조성…연체율 6% ‘목표’
은행권, 중기대출 확대 '부담'…유동성 완화로 숨통 트이나
생산적금융 다음 숙제는 녹색금융…은행 넘어 전금융권 확산
금 통장에 1조5000억 몰렸다…실버 투자도 사상 최대
신한-농협, 年 대출 목표 초과… 연말 ‘보릿고개’ 우려
외국인을 모셔라…금융권, 상품 경쟁 본격화
출연금은 금리에 50%만 반영…은행권, 연내 가산금리 산정체계 개정
[보푸라기]종신보험→연금으로…전환 전 '꼭' 따져보세요
‘간편지급’ 하루 1조원 돌파…이용액·건수 두자릿수 증가
[기고] 인공지능 혁신을 위한 골든 타임
요양병원서 '보험 판매' 길 열린다…생명보험·실버산업, 시너지 본격화
[기자24시] 저신용자 금리인하의 함정
"가계빚 뇌관은 규모 아닌 단기·변동금리…커버드본드 활성화 절실"
"기축통화국 아닌 韓, 원화 스테이블코인-CBDC 병행해야"
글로벌 결제 판도 대격변 … 현금 고집해온 日도 '코인 결제'
[솔선수법] 스테이블코인이 드리운 그림자
북한서도 전자결제 확대…스마트폰 인출 ATM도 보급
넓게, 더 넓게… 국내외 빅테크들 ‘AI 비서’ 영역 확장 경쟁
[천자칼럼] 코인 청산빔
[AI 시그널] 닷컴 버블 vs 혁신 파동…빅테크 거물들이 본 AI 거품론
“애플, 컴퓨터 비전 스타트업 '프롬프트AI' 인수 임박”
EU, 美규제완화 압박에 '우려해소 점검표'로 설득키로
"금 사자…" 미중 갈등 재점화, '안전자산 피난' 급류
희토류 통제에 美 왜 발끈하나… 中수준 도달까지 10여년 걸려
미중 사이에 낄 수퍼 새우는? 'AI 동메달' 노리는 국가들
[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시)
[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기업 투자/협력- (프로그램별 상이)
[한국핀테크지원센터] 2025년 제1차 직원 채용 공고 (~25.10.10 18:00)
2025 핀테크 전문가 과정 ‘FinBoost Academy’(개발자 과정) 참가자 모집(~선착순)
[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Academy’참여자 모집(~선착순 마감)
[한국핀테크지원센터] 「제8회 핀테크 아이디어 공모전」(~10.14.)
[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)
[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지)
[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)
"불법사금융, 이미 갚았다면?"…금융당국 대응요령 Q&A
산업부·금융위, 석유화학 재편 방안 논의…"지원 패키지 적극 검토"
이억원 "금융 유관기관 인프라 사고, 낱낱이 규명·책임 묻겠다"
금융당국, 적기시정조치 저축銀 경영평가 시작… 한곳은 유예종료
책무구조도 점검 끝낸 금감원…"4대 은행, 임원용 매뉴얼 초안 마련"
소비자보호 외치는 금감원…“건전성 감독 외면하면 안돼”
금융당국 최장 '30년 만기 고정금리' 주담대 추진한다…TF 운영
토스증권, 추석부터 미국주식 배당금 ‘공휴일 지급’ 정례화
카카오뱅크, 'K-패스 프렌즈 체크카드'…출시 8개월 만에 100만 장 돌파
인뱅 3사, 지방은행과 ‘공동대출’ 맞손…고객 유치 경쟁 총력
“모바일로 용돈 받고, QR로 장보고”…디지털 금융이 바꾼 추석 풍경
케이뱅크,업비트 실명계정 제휴 연장…IPO 추진에 ‘탄력’
“스테이블코인, 토스의 큰 전환점…슈퍼앱으로 승부”
핀다, 불법사금융 방지 위해 저신용자에 ‘우수대부업체’ 대안 제시
연휴 가족·친구가 낸 돈… 은행 모임통장으로 관리해볼까
“결제 넘어 슈퍼앱으로”…와우패스, 거래액 1조원 돌파
토스뱅크, 광주은행 이어 경남은행과 '공동대출'
명절 용돈으로 ‘아이통장’ 만들어볼까…용돈 실물카드도 인기
이젠 노인이 아니라 '파워 시니어'… 금융권, 60대 '황금 세대' 공략에 사활건 총력전
잠자는 내 예금 은행에만 20조원... 클릭 몇 번으로 찾는다
“3% 금리에 수수료 면제까지”… 은행권 ‘연금통장 경쟁’ 본격화
신한·KB·농협생명, AI 적극 도입…업무 효율·고객 서비스 혁신 본격화
연 7% 고금리 통장 찾는 금리노마드…추석 자금 굴릴 곳은?
은행서 다시 판매될 ELS…어떤 상품인가, 어떻게 투자할까
“273만 새로운 고객 잡아라”…은행권 외국인 고객 공략 ‘총력’
은행권 '트래블' 세계관 확장…국경 허물고 활용처 넓힌다
정기예금 10개중 4개, 기준금리 만큼도 이자 안줘
체크카드 시장, 간편결제·생활밀착 혜택이 대세…케이뱅크 ONE 1위
명절 특수 뒤 더 커질 가계부채 부담…카드 업계 건전성 '비상등' 켜지나
매년 최고 실적 새로 쓰는 은행, 서민금융 지원은 '반토막'
'과징금 후유증' 은행 자본비율 족쇄 푼다
5대 은행 보이스피싱 자율배상 10%뿐…'무과실 배상' 법제화 속도
퇴직금, 일시금보다 연금이 더 좋은 이유
[금융신뢰 재설계]③ 금융보안 새판, 규제와 신기술 접점 찾아야
달러의 시대, 영원한 건 없다?…글로벌 외환보유액 비중 20년만 ‘최저’ [투자360]
‘역대급’ 금통위 앞두고…11월 인하로 기우는 채권 시장
"앗 속았다" 보이스피싱 당해도…내 돈 지켜주는 '8가지 장치'
금이냐 은이냐 코인이냐…추석 연휴 재테크 삼파전
투자자 1000만 돌파했지만...가상자산 79조원 '해외 엑소더스'
"구글도 뛰어들었다"…글로벌 '코인 금융' 인프라 선점 경쟁 [한경 코알라]
지역 안방 떠나 해외진출… 인뱅 손잡고 신규 고객 유치도 [위기의 지방은행]
[AI돋보기] 추석 용돈, AI 투자앱에 맡겨도 될까
[PF 부실 점검]② 캐피탈사, 더딘 건전성 회복 '부실채권' 발목
[마켓스토리] 자산 토큰화는 도대체 왜 할까?
국내 스테이블코인 하루 거래 2천억원대로 축소…작년 말엔 1조
조각투자 플랫폼 인가전, NXT도 참전할까
[기고] 잔인한 이자율의 역사와 포용금융
"AI 에이전트 알아서 척척…구글·애플 앱마켓구조 점진적 붕괴"
[르포]“저축으론 돈 못 번다” 中 증권사에 줄 선 고객들
中 '디지털 실크로드' 질주…아프리카·유럽 AI패권 노린다
'미중 의존 줄이자'…EU, AI 활용 확대에 1조6천억 투입(종합)
트럼프 리스크, 日 돈풀기 우려에… 달러·엔화 ‘엑소더스’
트럼프 관세 후폭풍… 내년 세계 무역성장률 0.5%로 급락
美 셧다운·금리인하 기조에… 금·은·코인으로, 돈의 대이동
“AI붐은 버블, 25년전 닷컴 때과 비슷”...IMF·영란은행, 증시 과열에 경고
[디캠프·한국핀테크지원센터] startup OI #금융권-스타트업 우수 협력 사례 공모 (~10.10.)
[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시)
[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기업 투자/협력- (프로그램별 상이)

# 날짜별 리스트 + 뉴스모음 코드 합치기

In [ ]:
import pandas as pd
import requests
import re
import time
from bs4 import BeautifulSoup as bs

In [79]:
"핀테크 주요뉴스" in soup.select("a.txtl")[7].text

True

In [80]:
def fintech_news_list():
    url1 = "https://fintech.or.kr/web/board/boardContentsList.do"
    payload1 = dict(miv_pageNo=1, mode="W", board_id=6)
    r1 = requests.post(url1, data=payload1)
    soup = bs(r1.content, "lxml")
    contents_id_list = []
    for date, content_list in zip(soup.select("td.last"), soup.select("a.txtl")):
        if "핀테크 주요뉴스" in content_list.text:
            date = text_clean(date.text)
            contents_id = content_list['href'].split("'")[1]
            contents_id_list.append((date, contents_id))
    return contents_id_list

In [81]:
fintech_news_list()

[('2025-10-21', 'f61663288d694d068e33d00054b22595'),
 ('2025-10-20', '760c4ae4b76f449aa23de004e8200bc5'),
 ('2025-10-17', 'ad2eb2c521ab4e9fa32cb00a625cbd69'),
 ('2025-10-16', 'c80032073f994fb4b669d70bb5917c18'),
 ('2025-10-15', 'c579f3baf033478483098dc813b47e1f'),
 ('2025-10-14', 'f7a7f75aa51045209c20eff82dc21e90'),
 ('2025-10-13', 'b45fb58dc8094571a48344594ab19176'),
 ('2025-10-10', 'aeea59af5aea4346a8d53ed2605993e5')]

In [82]:
result = {}
contents_id_list = fintech_news_list()
for idx, (date, content_id) in enumerate(contents_id_list):
    print(f"{idx+1}/{len(contents_id_list)} {content_id} 수집중", end="\r")
    url2 = "https://fintech.or.kr/web/board/boardContentsView.do"
    payload2 = dict(miv_pageNo=1, mode="W", contents_id=content_id, board_id=6, searchkey="I")
    r2 = requests.post(url2, data=payload2)
    soup2 = bs(r2.content, "lxml")
    
    for td in soup2.select("tbody td"):
        if td.select_one("a") != None and td.select_one("a")['href'] != "https://fintech.or.kr/":
    #         print(td.select_one("a").text)
    #         print(td.select_one("a")['href'])
            result.setdefault("제목", []).append(td.select_one("a").text)
            result.setdefault("원문링크", []).append(td.select_one("a")['href'])
df = pd.DataFrame(result)

In [83]:
df

,제목,원문링크
0,"한국핀테크지원센터, 핀에듀 AI 활용 실무 온라인 교육 과정 5종 신규 개설",https://www.etnews.com/20251017000242
1,[한국핀테크지원센터] 2025 핀테크 전문가(개발자) 과정 ‘FinBoost Aca...,https://fintech.or.kr/web/board/boardContentsV...
2,[한국핀테크지원센터] AICC 기반 금융 서비스 자동화 교육 과정 수강생 모집(~선착순),https://fintech.or.kr/web/board/boardContentsV...
3,[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생...,https://fintech.or.kr/web/board/boardContentsV...
4,[한국핀테크지원센터] 2025년 핀테크 통번역존 운영(~예산 소진 시까지),https://fintech.or.kr/web/board/boardContentsV...
...,...,...
401,"美 셧다운·금리인하 기조에… 금·은·코인으로, 돈의 대이동",https://n.news.naver.com/mnews/article/008/000...
402,"“AI붐은 버블, 25년전 닷컴 때과 비슷”...IMF·영란은행, 증시 과열에 경고",https://n.news.naver.com/mnews/article/009/000...
403,[디캠프·한국핀테크지원센터] startup OI #금융권-스타트업 우수 협력 사례 ...,https://fintech.or.kr/web/board/boardContentsV...
404,[금융보안원] 「데이터허브」 기업 무료 이용 안내(상시),https://fintech.or.kr/web/board/boardContentsV...
405,[서울경제진흥원] 오픈이노베이션 프로그램 참여 기업 모집 -총 15개 대기업/중견기...,https://fintech.or.kr/web/board/boardContentsV...

In [56]:
from datetime import datetime

In [63]:
today = datetime.today()
formatted = today.strftime("%Y-%m-%d")
print(formatted)

2025-10-21

In [64]:
formatted == "2025-10-21"

True