In [2]:
import requests
import pandas as pd
import re
from dotenv import load_dotenv
import os
load_dotenv("./data/.env_naver")

True

In [28]:
page_num = 1
total_pages = 1

all_data = []
while page_num <= total_pages:
    url = "https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM"
    payload = dict(key=os.getenv("gg_data"), type="json", pIndex=page_num, pSize=1000)
    r = requests.get(url, params=payload)
    print(r.url)
#     print(r.status_code)
    if page_num == 1:
        total_pages = data['TBGGDLNGPRCAPTTRDSRCM'][0]['head'][0]['list_total_count'] // 1000 + 1  
    else:
        pass
     
    response = r.json()
    all_data.append(pd.DataFrame(response['TBGGDLNGPRCAPTTRDSRCM'][1]['row']))
    page_num += 1

df = pd.concat(all_data)
df = df.reset_index(drop=True)
df

https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=1&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=2&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=3&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=4&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=5&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=6&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=7&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=8&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=9&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=10&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=11&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=12&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=13&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=14&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=15&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=16&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=17&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=18&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=19&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=20&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=21&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=22&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=23&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=24&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=25&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=26&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=27&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=28&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=29&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=30&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=31&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=32&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=33&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=34&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=35&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=36&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=37&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=38&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=39&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=40&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=41&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=42&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=43&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=44&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=45&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=46&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=47&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=48&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=49&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=50&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=51&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=52&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=53&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=54&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=55&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=56&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=57&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=58&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=59&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=60&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=61&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=62&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=63&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=64&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=65&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=66&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=67&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=68&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=69&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=70&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=71&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=72&pSize=1000

https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=73&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=74&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=75&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=76&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=77&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=78&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=79&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=80&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=81&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=82&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=83&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=84&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=85&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=86&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=87&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=88&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=89&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=90&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=91&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=92&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=93&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=94&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=95&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=96&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=97&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=98&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=99&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=100&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=101&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=102&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=103&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=104&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=105&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=106&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=107&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=108&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=109&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=110&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=111&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=112&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=113&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=114&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=115&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=116&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=117&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=118&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=119&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=120&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=121&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=122&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=123&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=124&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=125&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=126&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=127&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=128&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=129&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=130&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=131&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=132&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=133&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=134&pSize=1000
https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=json&pIndex=135&pSize=1000

,NO,REFINE_STATE_CD,LOTNO_ADDR,LOTNO_ORIGNO,LOTNO_VICENO,HSCOMPLEX_NM,PRVTUSE_AR,CONTRACT_YM,CONTRACT_DAY,DELNG_AMT,...,REFINE_ZIPNO,REFINE_WGS84_LOGT,REFINE_WGS84_LAT,REFINE_MANAGE_NO,REFINE_RESLT_CD,REFINE_ADDR_DIV_CD,REFINE_SYS_DIV_CD,REFINE_DTM,REFINE_NOADMIT_YN,ADDR
0,134904,None,996,996,0,주공그린빌,84.80,2018-01,1~10,26900,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
1,134905,None,996,996,0,주공그린빌,75.95,2018-01,11~20,27000,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
2,134906,None,996,996,0,주공그린빌,84.51,2018-01,11~20,25500,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
3,134907,None,996,996,0,주공그린빌,59.92,2018-01,11~20,23700,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
4,134908,None,996,996,0,주공그린빌,84.80,2018-01,11~20,27450,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134837,269497,None,Jun-49,49,6,남수원현대,84.98,2018-10,11~20,14500,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134838,269498,None,Jun-49,49,6,남수원현대,59.98,2018-10,21~31,14600,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134839,269499,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,1~10,19000,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134840,269500,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,1~10,17800,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134841,269501,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,11~20,21900,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동

In [30]:
new_cols = ["번호",
"주소",
"지번주소",
"지번본번",
"지번부번",
"단지명",
"전용면적",
"계약연월",
"계약일",
"거래금액",
"층명",
"건축년도",
"도로명",
"정제완료여부",
"생성일자",
"정제지번주소",
"정제도로명주소",
"정제우편번호",
"정제WGS84경도",
"정제WGS84위도",
"정제관리번호",
"정제결과코드",
"정제주소구분코드",
"정제시스템구분코드",
"정제일시",
"정제불가여부",
"정제상태코드"]

In [31]:
df.columns = new_cols
df

,번호,주소,지번주소,지번본번,지번부번,단지명,전용면적,계약연월,계약일,거래금액,...,정제우편번호,정제WGS84경도,정제WGS84위도,정제관리번호,정제결과코드,정제주소구분코드,정제시스템구분코드,정제일시,정제불가여부,정제상태코드
0,134904,None,996,996,0,주공그린빌,84.80,2018-01,1~10,26900,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
1,134905,None,996,996,0,주공그린빌,75.95,2018-01,11~20,27000,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
2,134906,None,996,996,0,주공그린빌,84.51,2018-01,11~20,25500,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
3,134907,None,996,996,0,주공그린빌,59.92,2018-01,11~20,23700,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
4,134908,None,996,996,0,주공그린빌,84.80,2018-01,11~20,27450,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134837,269497,None,Jun-49,49,6,남수원현대,84.98,2018-10,11~20,14500,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134838,269498,None,Jun-49,49,6,남수원현대,59.98,2018-10,21~31,14600,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134839,269499,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,1~10,19000,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134840,269500,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,1~10,17800,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134841,269501,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,11~20,21900,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134842 entries, 0 to 134841
Data columns (total 27 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   번호         134842 non-null  int64
 1   주소         0 non-null       object
 2   지번주소       134840 non-null  object
 3   지번본번       134842 non-null  object
 4   지번부번       134842 non-null  object
 5   단지명        134842 non-null  object
 6   전용면적       134842 non-null  float64
 7   계약연월       134842 non-null  object
 8   계약일        134842 non-null  object
 9   거래금액       134842 non-null  int64
 10  층명         134842 non-null  object
 11  건축년도       134842 non-null  object
 12  도로명        134318 non-null  object
 13  정제완료여부     0 non-null       object
 14  생성일자       0 non-null       object
 15  정제지번주소     0 non-null       object
 16  정제도로명주소    0 non-null       object
 17  정제우편번호     0 non-null       object
 18  정제WGS84경도  0 non-null       object
 19  정제WGS84위도  0 non-null       object
 20  정제관리번호     0 non-null       object
 21  정제결과코드     0 non-null       object
 22  정제주소구분코드   0 non-null       object
 23  정제시스템구분코드  0 non-null       object
 24  정제일시       0 non-null       object
 25  정제불가여부     0 non-null       object
 26  정제상태코드     134842 non-null  object
dtypes: float64(1), int64(2), object(24)
memory usage: 27.8+ MB

In [41]:
df['도로명']

0         통일로802번길
1         통일로802번길
2         통일로802번길
3         통일로802번길
4         통일로802번길
            ...
134837         화산로
134838         화산로
134839         효행로
134840         효행로
134841         효행로
Name: 도로명, Length: 134842, dtype: object

In [40]:
df.columns

Index(['번호', '주소', '지번주소', '지번본번', '지번부번', '단지명', '전용면적', '계약연월', '계약일',
       '거래금액', '층명', '건축년도', '도로명', '정제완료여부', '생성일자', '정제지번주소', '정제도로명주소',
       '정제우편번호', '정제WGS84경도', '정제WGS84위도', '정제관리번호', '정제결과코드', '정제주소구분코드',
       '정제시스템구분코드', '정제일시', '정제불가여부', '정제상태코드'],
      dtype='object')

In [42]:
result_df = df[['번호', '단지명', '전용면적', '계약연월', '계약일', '거래금액', '정제상태코드']]
result_df

            번호         단지명   전용면적     계약연월    계약일   거래금액         정제상태코드
0       134904       주공그린빌  84.80  2018-01   1~10  26900  경기도 고양덕양구 관산동
1       134905       주공그린빌  75.95  2018-01  11~20  27000  경기도 고양덕양구 관산동
2       134906       주공그린빌  84.51  2018-01  11~20  25500  경기도 고양덕양구 관산동
3       134907       주공그린빌  59.92  2018-01  11~20  23700  경기도 고양덕양구 관산동
4       134908       주공그린빌  84.80  2018-01  11~20  27450  경기도 고양덕양구 관산동
...        ...         ...    ...      ...    ...    ...            ...
134837  269497       남수원현대  84.98  2018-10  11~20  14500    경기도 화성시 안녕동
134838  269498       남수원현대  59.98  2018-10  21~31  14600    경기도 화성시 안녕동
134839  269499  다솜마을동문굿모닝힐  84.99  2018-10   1~10  19000    경기도 화성시 안녕동
134840  269500  다솜마을동문굿모닝힐  84.99  2018-10   1~10  17800    경기도 화성시 안녕동
134841  269501  다솜마을동문굿모닝힐  84.99  2018-10  11~20  21900    경기도 화성시 안녕동

[134842 rows x 7 columns]

# XML로 가져와 정제하기

In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\haram4th\miniforge3\envs\test_env\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\haram4th\miniforge3\envs\test_env\lib\site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\haram4th\miniforge3\envs\test_env\lib\site-packages (from beautifulsoup4) (4.15.0)

In [2]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\haram4th\miniforge3\envs\test_env\lib\site-packages (6.0.2)

In [4]:
import requests
import pandas as pd
import re
from dotenv import load_dotenv
import os
load_dotenv("./data/.env_naver")

True

In [5]:
page_num = 1
total_pages = 1

url = "https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM"
payload = dict(key=os.getenv("gg_data"), type="xml", pIndex=page_num, pSize=1000)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)

https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?key=78c71dfbaa4e4a6da7ff4083edb8d6ac&type=xml&pIndex=1&pSize=1000
200

In [6]:
response = r.text
response

'<?xml version="1.0" encoding="UTF-8"?>\n\n<TBGGDLNGPRCAPTTRDSRCM>\n  <head>\n    <list_total_count>134842</list_total_count>\n    <RESULT>\n      <CODE>INFO-000</CODE>\n      <MESSAGE>정상 처리되었습니다.</MESSAGE>\n    </RESULT>\n    <api_version>1.0v</api_version>\n  </head>\n  <row>\n    <NO>134904</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>996</LOTNO_ADDR>\n    <LOTNO_ORIGNO>996</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.8</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>1~10</CONTRACT_DAY>\n    <DELNG_AMT>26900</DELNG_AMT>\n    <FLOOR_NM>5</FLOOR_NM>\n    <BUILD_YY>2003</BUILD_YY>\n    <ROAD_NM>통일로802번길</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 관산동</ADDR>\n  </row>\n  <row>\n    <NO>134905</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>996</LOTNO_ADDR>\n    <LOTNO_ORIGNO>996</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>\n    <PRVTUSE_AR>75.95</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>27000</DELNG_AMT>\n    <FLOOR_NM>10</FLOOR_NM>\n    <BUILD_YY>2003</BUILD_YY>\n    <ROAD_NM>통일로802번길</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 관산동</ADDR>\n  </row>\n  <row>\n    <NO>134906</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>996</LOTNO_ADDR>\n    <LOTNO_ORIGNO>996</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.51</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>25500</DELNG_AMT>\n    <FLOOR_NM>2</FLOOR_NM>\n    <BUILD_YY>2003</BUILD_YY>\n    <ROAD_NM>통일로802번길</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 관산동</ADDR>\n  </row>\n  <row>\n    <NO>134907</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>996</LOTNO_ADDR>\n    <LOTNO_ORIGNO>996</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>\n    <PRVTUSE_AR>59.92</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>23700</DELNG_AMT>\n    <FLOOR_NM>10</FLOOR_NM>\n    <BUILD_YY>2003</BUILD_YY>\n    <ROAD_NM>통일로802번길</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 관산동</ADDR>\n  </row>\n  <row>\n    <NO>134908</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>996</LOTNO_ADDR>\n    <LOTNO_ORIGNO>996</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.8</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>27450</DELNG_AMT>\n    <FLOOR_NM>4</FLOOR_NM>\n    <BUILD_YY>2003</BUILD_YY>\n    <ROAD_NM>통일로802번길</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 관산동</ADDR>\n  </row>\n  <row>\n    <NO>134909</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>983</LOTNO_ADDR>\n    <LOTNO_ORIGNO>983</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>74.98</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>37800</DELNG_AMT>\n    <FLOOR_NM>19</FLOOR_NM>\n    <BUILD_YY>2014</BUILD_YY>\n    <ROAD_NM>도래울로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134910</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>983</LOTNO_ADDR>\n    <LOTNO_ORIGNO>983</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.98</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>40000</DELNG_AMT>\n    <FLOOR_NM>24</FLOOR_NM>\n    <BUILD_YY>2014</BUILD_YY>\n    <ROAD_NM>도래울로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134911</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>983</LOTNO_ADDR>\n    <LOTNO_ORIGNO>983</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>74.98</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>36800</DELNG_AMT>\n    <FLOOR_NM>13</FLOOR_NM>\n    <BUILD_YY>2014</BUILD_YY>\n    <ROAD_NM>도래울로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134912</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>983</LOTNO_ADDR>\n    <LOTNO_ORIGNO>983</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.98</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>39500</DELNG_AMT>\n    <FLOOR_NM>21</FLOOR_NM>\n    <BUILD_YY>2014</BUILD_YY>\n    <ROAD_NM>도래울로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134913</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1011</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>59.92</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>1~10</CONTRACT_DAY>\n    <DELNG_AMT>34900</DELNG_AMT>\n    <FLOOR_NM>14</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울3로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134914</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1011</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>74.97</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>1~10</CONTRACT_DAY>\n    <DELNG_AMT>38000</DELNG_AMT>\n    <FLOOR_NM>11</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울3로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134915</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1011</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>59.74</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>34300</DELNG_AMT>\n    <FLOOR_NM>10</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울3로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134916</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1011</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>59.74</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>34900</DELNG_AMT>\n    <FLOOR_NM>10</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울3로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134917</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1011</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>59.74</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>21~31</CONTRACT_DAY>\n    <DELNG_AMT>34500</DELNG_AMT>\n    <FLOOR_NM>7</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울3로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134918</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1011</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>59.74</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>21~31</CONTRACT_DAY>\n    <DELNG_AMT>33600</DELNG_AMT>\n    <FLOOR_NM>19</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울3로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134919</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1103</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.98</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>1~10</CONTRACT_DAY>\n    <DELNG_AMT>39000</DELNG_AMT>\n    <FLOOR_NM>16</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134920</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1103</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.38</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>1~10</CONTRACT_DAY>\n    <DELNG_AMT>39300</DELNG_AMT>\n    <FLOOR_NM>10</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134921</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1103</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.38</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>40000</DELNG_AMT>\n    <FLOOR_NM>7</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFINE_DTM>\n    <REFINE_NOADMIT_YN></REFINE_NOADMIT_YN>\n    <ADDR>경기도 고양덕양구 도내동</ADDR>\n  </row>\n  <row>\n    <NO>134922</NO>\n    <REFINE_STATE_CD></REFINE_STATE_CD>\n    <LOTNO_ADDR>1103</LOTNO_ADDR>\n    <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>\n    <LOTNO_VICENO>0</LOTNO_VICENO>\n    <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>\n    <PRVTUSE_AR>84.93</PRVTUSE_AR>\n    <CONTRACT_YM>2018-01</CONTRACT_YM>\n    <CONTRACT_DAY>11~20</CONTRACT_DAY>\n    <DELNG_AMT>40700</DELNG_AMT>\n    <FLOOR_NM>9</FLOOR_NM>\n    <BUILD_YY>2013</BUILD_YY>\n    <ROAD_NM>도래울로</ROAD_NM>\n    <REFINE_CMPLT_YN></REFINE_CMPLT_YN>\n    <CREAT_DE></CREAT_DE>\n    <REFINE_LOTNO_ADDR></REFINE_LOTNO_ADDR>\n    <REFINE_ROADNM_ADDR></REFINE_ROADNM_ADDR>\n    <REFINE_ZIPNO></REFINE_ZIPNO>\n    <REFINE_WGS84_LOGT></REFINE_WGS84_LOGT>\n    <REFINE_WGS84_LAT></REFINE_WGS84_LAT>\n    <REFINE_MANAGE_NO></REFINE_MANAGE_NO>\n    <REFINE_RESLT_CD></REFINE_RESLT_CD>\n    <REFINE_ADDR_DIV_CD></REFINE_ADDR_DIV_CD>\n    <REFINE_SYS_DIV_CD></REFINE_SYS_DIV_CD>\n    <REFINE_DTM></REFIN

In [7]:
from bs4 import BeautifulSoup as bs

In [8]:
soup = bs(response, 'xml')
print(soup)

<?xml version="1.0" encoding="utf-8"?>
<TBGGDLNGPRCAPTTRDSRCM>
<head>
<list_total_count>134842</list_total_count>
<RESULT>
<CODE>INFO-000</CODE>
<MESSAGE>정상 처리되었습니다.</MESSAGE>
</RESULT>
<api_version>1.0v</api_version>
</head>
<row>
<NO>134904</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>996</LOTNO_ADDR>
<LOTNO_ORIGNO>996</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
<PRVTUSE_AR>84.8</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>1~10</CONTRACT_DAY>
<DELNG_AMT>26900</DELNG_AMT>
<FLOOR_NM>5</FLOOR_NM>
<BUILD_YY>2003</BUILD_YY>
<ROAD_NM>통일로802번길</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 관산동</ADDR>
</row>
<row>
<NO>134905</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>996</LOTNO_ADDR>
<LOTNO_ORIGNO>996</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
<PRVTUSE_AR>75.95</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>27000</DELNG_AMT>
<FLOOR_NM>10</FLOOR_NM>
<BUILD_YY>2003</BUILD_YY>
<ROAD_NM>통일로802번길</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 관산동</ADDR>
</row>
<row>
<NO>134906</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>996</LOTNO_ADDR>
<LOTNO_ORIGNO>996</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
<PRVTUSE_AR>84.51</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>25500</DELNG_AMT>
<FLOOR_NM>2</FLOOR_NM>
<BUILD_YY>2003</BUILD_YY>
<ROAD_NM>통일로802번길</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 관산동</ADDR>
</row>
<row>
<NO>134907</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>996</LOTNO_ADDR>
<LOTNO_ORIGNO>996</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
<PRVTUSE_AR>59.92</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>23700</DELNG_AMT>
<FLOOR_NM>10</FLOOR_NM>
<BUILD_YY>2003</BUILD_YY>
<ROAD_NM>통일로802번길</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 관산동</ADDR>
</row>
<row>
<NO>134908</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>996</LOTNO_ADDR>
<LOTNO_ORIGNO>996</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
<PRVTUSE_AR>84.8</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>27450</DELNG_AMT>
<FLOOR_NM>4</FLOOR_NM>
<BUILD_YY>2003</BUILD_YY>
<ROAD_NM>통일로802번길</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 관산동</ADDR>
</row>
<row>
<NO>134909</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>983</LOTNO_ADDR>
<LOTNO_ORIGNO>983</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>
<PRVTUSE_AR>74.98</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>37800</DELNG_AMT>
<FLOOR_NM>19</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134910</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>983</LOTNO_ADDR>
<LOTNO_ORIGNO>983</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>
<PRVTUSE_AR>84.98</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>40000</DELNG_AMT>
<FLOOR_NM>24</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134911</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>983</LOTNO_ADDR>
<LOTNO_ORIGNO>983</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>
<PRVTUSE_AR>74.98</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>36800</DELNG_AMT>
<FLOOR_NM>13</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134912</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>983</LOTNO_ADDR>
<LOTNO_ORIGNO>983</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>
<PRVTUSE_AR>84.98</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>39500</DELNG_AMT>
<FLOOR_NM>21</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134913</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1011</LOTNO_ADDR>
<LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
<PRVTUSE_AR>59.92</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>1~10</CONTRACT_DAY>
<DELNG_AMT>34900</DELNG_AMT>
<FLOOR_NM>14</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울3로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134914</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1011</LOTNO_ADDR>
<LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
<PRVTUSE_AR>74.97</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>1~10</CONTRACT_DAY>
<DELNG_AMT>38000</DELNG_AMT>
<FLOOR_NM>11</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울3로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134915</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1011</LOTNO_ADDR>
<LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
<PRVTUSE_AR>59.74</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>34300</DELNG_AMT>
<FLOOR_NM>10</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울3로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134916</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1011</LOTNO_ADDR>
<LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
<PRVTUSE_AR>59.74</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>34900</DELNG_AMT>
<FLOOR_NM>10</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울3로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134917</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1011</LOTNO_ADDR>
<LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
<PRVTUSE_AR>59.74</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>34500</DELNG_AMT>
<FLOOR_NM>7</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울3로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134918</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1011</LOTNO_ADDR>
<LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
<PRVTUSE_AR>59.74</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>33600</DELNG_AMT>
<FLOOR_NM>19</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울3로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134919</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1103</LOTNO_ADDR>
<LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
<PRVTUSE_AR>84.98</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>1~10</CONTRACT_DAY>
<DELNG_AMT>39000</DELNG_AMT>
<FLOOR_NM>16</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134920</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1103</LOTNO_ADDR>
<LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
<PRVTUSE_AR>84.38</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>1~10</CONTRACT_DAY>
<DELNG_AMT>39300</DELNG_AMT>
<FLOOR_NM>10</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134921</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1103</LOTNO_ADDR>
<LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
<PRVTUSE_AR>84.38</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>40000</DELNG_AMT>
<FLOOR_NM>7</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134922</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1103</LOTNO_ADDR>
<LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
<PRVTUSE_AR>84.93</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>40700</DELNG_AMT>
<FLOOR_NM>9</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134923</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1103</LOTNO_ADDR>
<LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
<PRVTUSE_AR>74.96</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>37300</DELNG_AMT>
<FLOOR_NM>8</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134924</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1103</LOTNO_ADDR>
<LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
<PRVTUSE_AR>74.96</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>37000</DELNG_AMT>
<FLOOR_NM>9</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134925</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>1103</LOTNO_ADDR>
<LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
<PRVTUSE_AR>84.38</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>40700</DELNG_AMT>
<FLOOR_NM>9</FLOOR_NM>
<BUILD_YY>2013</BUILD_YY>
<ROAD_NM>도래울로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 도내동</ADDR>
</row>
<row>
<NO>134926</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>365</LOTNO_ADDR>
<LOTNO_ORIGNO>365</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>동산마을22단지호반베르디움</HSCOMPLEX_NM>
<PRVTUSE_AR>84.95</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>1~10</CONTRACT_DAY>
<DELNG_AMT>52000</DELNG_AMT>
<FLOOR_NM>3</FLOOR_NM>
<BUILD_YY>2012</BUILD_YY>
<ROAD_NM>세솔로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 동산동</ADDR>
</row>
<row>
<NO>134927</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>365</LOTNO_ADDR>
<LOTNO_ORIGNO>365</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>동산마을22단지호반베르디움</HSCOMPLEX_NM>
<PRVTUSE_AR>84.95</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>11~20</CONTRACT_DAY>
<DELNG_AMT>52000</DELNG_AMT>
<FLOOR_NM>7</FLOOR_NM>
<BUILD_YY>2012</BUILD_YY>
<ROAD_NM>세솔로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 동산동</ADDR>
</row>
<row>
<NO>134928</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>306</LOTNO_ADDR>
<LOTNO_ORIGNO>306</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>고양삼송동원로얄듀크</HSCOMPLEX_NM>
<PRVTUSE_AR>116.52</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>60000</DELNG_AMT>
<FLOOR_NM>18</FLOOR_NM>
<BUILD_YY>2012</BUILD_YY>
<ROAD_NM>세솔로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 삼송동</ADDR>
</row>
<row>
<NO>134929</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>331</LOTNO_ADDR>
<LOTNO_ORIGNO>331</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
<PRVTUSE_AR>84.98</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>1~10</CONTRACT_DAY>
<DELNG_AMT>51500</DELNG_AMT>
<FLOOR_NM>15</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>덕수천1로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 삼송동</ADDR>
</row>
<row>
<NO>134930</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>331</LOTNO_ADDR>
<LOTNO_ORIGNO>331</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
<PRVTUSE_AR>99.82</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>57500</DELNG_AMT>
<FLOOR_NM>24</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>덕수천1로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 삼송동</ADDR>
</row>
<row>
<NO>134931</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>331</LOTNO_ADDR>
<LOTNO_ORIGNO>331</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
<PRVTUSE_AR>101.51</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>57800</DELNG_AMT>
<FLOOR_NM>15</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>덕수천1로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 삼송동</ADDR>
</row>
<row>
<NO>134932</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>331</LOTNO_ADDR>
<LOTNO_ORIGNO>331</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
<PRVTUSE_AR>84.98</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>51300</DELNG_AMT>
<FLOOR_NM>14</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>덕수천1로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>
<REFINE_ADDR_DIV_CD/>
<REFINE_SYS_DIV_CD/>
<REFINE_DTM/>
<REFINE_NOADMIT_YN/>
<ADDR>경기도 고양덕양구 삼송동</ADDR>
</row>
<row>
<NO>134933</NO>
<REFINE_STATE_CD/>
<LOTNO_ADDR>331</LOTNO_ADDR>
<LOTNO_ORIGNO>331</LOTNO_ORIGNO>
<LOTNO_VICENO>0</LOTNO_VICENO>
<HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
<PRVTUSE_AR>84.97</PRVTUSE_AR>
<CONTRACT_YM>2018-01</CONTRACT_YM>
<CONTRACT_DAY>21~31</CONTRACT_DAY>
<DELNG_AMT>51300</DELNG_AMT>
<FLOOR_NM>14</FLOOR_NM>
<BUILD_YY>2014</BUILD_YY>
<ROAD_NM>덕수천1로</ROAD_NM>
<REFINE_CMPLT_YN/>
<CREAT_DE/>
<REFINE_LOTNO_ADDR/>
<REFINE_ROADNM_ADDR/>
<REFINE_ZIPNO/>
<REFINE_WGS84_LOGT/>
<REFINE_WGS84_LAT/>
<REFINE_MANAGE_NO/>
<REFINE_RESLT_CD/>

In [12]:
total_page = int(soup.select_one("list_total_count").text) // 1000 + 1

In [14]:
aparts = soup.select("row")
aparts

[<row>
 <NO>134904</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>996</LOTNO_ADDR>
 <LOTNO_ORIGNO>996</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.8</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>1~10</CONTRACT_DAY>
 <DELNG_AMT>26900</DELNG_AMT>
 <FLOOR_NM>5</FLOOR_NM>
 <BUILD_YY>2003</BUILD_YY>
 <ROAD_NM>통일로802번길</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 관산동</ADDR>
 </row>,
 <row>
 <NO>134905</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>996</LOTNO_ADDR>
 <LOTNO_ORIGNO>996</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
 <PRVTUSE_AR>75.95</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>27000</DELNG_AMT>
 <FLOOR_NM>10</FLOOR_NM>
 <BUILD_YY>2003</BUILD_YY>
 <ROAD_NM>통일로802번길</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 관산동</ADDR>
 </row>,
 <row>
 <NO>134906</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>996</LOTNO_ADDR>
 <LOTNO_ORIGNO>996</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.51</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>25500</DELNG_AMT>
 <FLOOR_NM>2</FLOOR_NM>
 <BUILD_YY>2003</BUILD_YY>
 <ROAD_NM>통일로802번길</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 관산동</ADDR>
 </row>,
 <row>
 <NO>134907</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>996</LOTNO_ADDR>
 <LOTNO_ORIGNO>996</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
 <PRVTUSE_AR>59.92</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>23700</DELNG_AMT>
 <FLOOR_NM>10</FLOOR_NM>
 <BUILD_YY>2003</BUILD_YY>
 <ROAD_NM>통일로802번길</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 관산동</ADDR>
 </row>,
 <row>
 <NO>134908</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>996</LOTNO_ADDR>
 <LOTNO_ORIGNO>996</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>주공그린빌</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.8</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>27450</DELNG_AMT>
 <FLOOR_NM>4</FLOOR_NM>
 <BUILD_YY>2003</BUILD_YY>
 <ROAD_NM>통일로802번길</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 관산동</ADDR>
 </row>,
 <row>
 <NO>134909</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>983</LOTNO_ADDR>
 <LOTNO_ORIGNO>983</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>74.98</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>37800</DELNG_AMT>
 <FLOOR_NM>19</FLOOR_NM>
 <BUILD_YY>2014</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134910</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>983</LOTNO_ADDR>
 <LOTNO_ORIGNO>983</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.98</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>40000</DELNG_AMT>
 <FLOOR_NM>24</FLOOR_NM>
 <BUILD_YY>2014</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134911</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>983</LOTNO_ADDR>
 <LOTNO_ORIGNO>983</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>74.98</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>36800</DELNG_AMT>
 <FLOOR_NM>13</FLOOR_NM>
 <BUILD_YY>2014</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134912</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>983</LOTNO_ADDR>
 <LOTNO_ORIGNO>983</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을2단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.98</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>39500</DELNG_AMT>
 <FLOOR_NM>21</FLOOR_NM>
 <BUILD_YY>2014</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134913</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1011</LOTNO_ADDR>
 <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>59.92</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>1~10</CONTRACT_DAY>
 <DELNG_AMT>34900</DELNG_AMT>
 <FLOOR_NM>14</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울3로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134914</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1011</LOTNO_ADDR>
 <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>74.97</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>1~10</CONTRACT_DAY>
 <DELNG_AMT>38000</DELNG_AMT>
 <FLOOR_NM>11</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울3로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134915</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1011</LOTNO_ADDR>
 <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>59.74</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>34300</DELNG_AMT>
 <FLOOR_NM>10</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울3로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134916</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1011</LOTNO_ADDR>
 <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>59.74</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>34900</DELNG_AMT>
 <FLOOR_NM>10</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울3로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134917</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1011</LOTNO_ADDR>
 <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>59.74</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>21~31</CONTRACT_DAY>
 <DELNG_AMT>34500</DELNG_AMT>
 <FLOOR_NM>7</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울3로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134918</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1011</LOTNO_ADDR>
 <LOTNO_ORIGNO>1011</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을4단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>59.74</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>21~31</CONTRACT_DAY>
 <DELNG_AMT>33600</DELNG_AMT>
 <FLOOR_NM>19</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울3로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134919</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1103</LOTNO_ADDR>
 <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.98</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>1~10</CONTRACT_DAY>
 <DELNG_AMT>39000</DELNG_AMT>
 <FLOOR_NM>16</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134920</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1103</LOTNO_ADDR>
 <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.38</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>1~10</CONTRACT_DAY>
 <DELNG_AMT>39300</DELNG_AMT>
 <FLOOR_NM>10</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134921</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1103</LOTNO_ADDR>
 <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.38</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>40000</DELNG_AMT>
 <FLOOR_NM>7</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134922</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1103</LOTNO_ADDR>
 <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.93</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>40700</DELNG_AMT>
 <FLOOR_NM>9</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134923</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1103</LOTNO_ADDR>
 <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>74.96</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>37300</DELNG_AMT>
 <FLOOR_NM>8</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134924</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1103</LOTNO_ADDR>
 <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>74.96</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>21~31</CONTRACT_DAY>
 <DELNG_AMT>37000</DELNG_AMT>
 <FLOOR_NM>9</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134925</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>1103</LOTNO_ADDR>
 <LOTNO_ORIGNO>1103</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>엘에이치원흥도래울마을6단지</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.38</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>21~31</CONTRACT_DAY>
 <DELNG_AMT>40700</DELNG_AMT>
 <FLOOR_NM>9</FLOOR_NM>
 <BUILD_YY>2013</BUILD_YY>
 <ROAD_NM>도래울로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 도내동</ADDR>
 </row>,
 <row>
 <NO>134926</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>365</LOTNO_ADDR>
 <LOTNO_ORIGNO>365</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>동산마을22단지호반베르디움</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.95</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>1~10</CONTRACT_DAY>
 <DELNG_AMT>52000</DELNG_AMT>
 <FLOOR_NM>3</FLOOR_NM>
 <BUILD_YY>2012</BUILD_YY>
 <ROAD_NM>세솔로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 동산동</ADDR>
 </row>,
 <row>
 <NO>134927</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>365</LOTNO_ADDR>
 <LOTNO_ORIGNO>365</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>동산마을22단지호반베르디움</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.95</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>11~20</CONTRACT_DAY>
 <DELNG_AMT>52000</DELNG_AMT>
 <FLOOR_NM>7</FLOOR_NM>
 <BUILD_YY>2012</BUILD_YY>
 <ROAD_NM>세솔로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 동산동</ADDR>
 </row>,
 <row>
 <NO>134928</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>306</LOTNO_ADDR>
 <LOTNO_ORIGNO>306</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>고양삼송동원로얄듀크</HSCOMPLEX_NM>
 <PRVTUSE_AR>116.52</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>21~31</CONTRACT_DAY>
 <DELNG_AMT>60000</DELNG_AMT>
 <FLOOR_NM>18</FLOOR_NM>
 <BUILD_YY>2012</BUILD_YY>
 <ROAD_NM>세솔로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 삼송동</ADDR>
 </row>,
 <row>
 <NO>134929</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>331</LOTNO_ADDR>
 <LOTNO_ORIGNO>331</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.98</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>1~10</CONTRACT_DAY>
 <DELNG_AMT>51500</DELNG_AMT>
 <FLOOR_NM>15</FLOOR_NM>
 <BUILD_YY>2014</BUILD_YY>
 <ROAD_NM>덕수천1로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 삼송동</ADDR>
 </row>,
 <row>
 <NO>134930</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>331</LOTNO_ADDR>
 <LOTNO_ORIGNO>331</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
 <PRVTUSE_AR>99.82</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>21~31</CONTRACT_DAY>
 <DELNG_AMT>57500</DELNG_AMT>
 <FLOOR_NM>24</FLOOR_NM>
 <BUILD_YY>2014</BUILD_YY>
 <ROAD_NM>덕수천1로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 삼송동</ADDR>
 </row>,
 <row>
 <NO>134931</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>331</LOTNO_ADDR>
 <LOTNO_ORIGNO>331</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
 <PRVTUSE_AR>101.51</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>21~31</CONTRACT_DAY>
 <DELNG_AMT>57800</DELNG_AMT>
 <FLOOR_NM>15</FLOOR_NM>
 <BUILD_YY>2014</BUILD_YY>
 <ROAD_NM>덕수천1로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>
 <REFINE_SYS_DIV_CD/>
 <REFINE_DTM/>
 <REFINE_NOADMIT_YN/>
 <ADDR>경기도 고양덕양구 삼송동</ADDR>
 </row>,
 <row>
 <NO>134932</NO>
 <REFINE_STATE_CD/>
 <LOTNO_ADDR>331</LOTNO_ADDR>
 <LOTNO_ORIGNO>331</LOTNO_ORIGNO>
 <LOTNO_VICENO>0</LOTNO_VICENO>
 <HSCOMPLEX_NM>삼송 스타클래스</HSCOMPLEX_NM>
 <PRVTUSE_AR>84.98</PRVTUSE_AR>
 <CONTRACT_YM>2018-01</CONTRACT_YM>
 <CONTRACT_DAY>21~31</CONTRACT_DAY>
 <DELNG_AMT>51300</DELNG_AMT>
 <FLOOR_NM>14</FLOOR_NM>
 <BUILD_YY>2014</BUILD_YY>
 <ROAD_NM>덕수천1로</ROAD_NM>
 <REFINE_CMPLT_YN/>
 <CREAT_DE/>
 <REFINE_LOTNO_ADDR/>
 <REFINE_ROADNM_ADDR/>
 <REFINE_ZIPNO/>
 <REFINE_WGS84_LOGT/>
 <REFINE_WGS84_LAT/>
 <REFINE_MANAGE_NO/>
 <REFINE_RESLT_CD/>
 <REFINE_ADDR_DIV_CD/>

In [15]:
cols = ['NO', 'LOTNO_ADDR', 'LOTNO_ORIGNO', 'LOTNO_VICENO',
       'HSCOMPLEX_NM', 'PRVTUSE_AR', 'CONTRACT_YM', 'CONTRACT_DAY',
       'DELNG_AMT', 'FLOOR_NM', 'BUILD_YY', 'ROAD_NM', 'ADDR']

In [19]:
result ={}
for col in cols:
    for value in soup.select(col):
        result.setdefault(col, []).append(value.text)
    
df = pd.DataFrame(result)
df

,NO,LOTNO_ADDR,LOTNO_ORIGNO,LOTNO_VICENO,HSCOMPLEX_NM,PRVTUSE_AR,CONTRACT_YM,CONTRACT_DAY,DELNG_AMT,FLOOR_NM,BUILD_YY,ROAD_NM,ADDR
0,134904,996,996,0,주공그린빌,84.8,2018-01,1~10,26900,5,2003,통일로802번길,경기도 고양덕양구 관산동
1,134905,996,996,0,주공그린빌,75.95,2018-01,11~20,27000,10,2003,통일로802번길,경기도 고양덕양구 관산동
2,134906,996,996,0,주공그린빌,84.51,2018-01,11~20,25500,2,2003,통일로802번길,경기도 고양덕양구 관산동
3,134907,996,996,0,주공그린빌,59.92,2018-01,11~20,23700,10,2003,통일로802번길,경기도 고양덕양구 관산동
4,134908,996,996,0,주공그린빌,84.8,2018-01,11~20,27450,4,2003,통일로802번길,경기도 고양덕양구 관산동
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,136016,4,4,0,래미안슈르,136.63,2018-01,1~10,120000,13,2008,별양로,경기도 과천시 원문동
996,136017,4,4,0,래미안슈르,116.96,2018-01,1~10,103000,4,2008,별양로,경기도 과천시 원문동
997,136018,4,4,0,래미안슈르,59.97,2018-01,1~10,83000,20,2008,별양로,경기도 과천시 원문동
998,136019,4,4,0,래미안슈르,84.96,2018-01,1~10,90000,10,2008,별양로,경기도 과천시 원문동
999,136020,4,4,0,래미안슈르,84.96,2018-01,11~20,89000,1,2008,별양로,경기도 과천시 원문동

# XML 데이터 전체 수집하기

In [ ]:
import re
import os
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs
from dotenv import load_dotenv

load_dotenv("./data/.env_naver")

In [1]:
url="https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM"
payload = dict(KEY=os.getenv("gg_api"), Type="xml", pIndex=1, pSize=10)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.text
soup = bs(response, "xml")
soup

NameError: name 'os' is not defined

In [30]:
new_cols = ["번호",
"주소",
"지번주소",
"지번본번",
"지번부번",
"단지명",
"전용면적",
"계약연월",
"계약일",
"거래금액",
"층명",
"건축년도",
"도로명",
"정제완료여부",
"생성일자",
"정제지번주소",
"정제도로명주소",
"정제우편번호",
"정제WGS84경도",
"정제WGS84위도",
"정제관리번호",
"정제결과코드",
"정제주소구분코드",
"정제시스템구분코드",
"정제일시",
"정제불가여부",
"정제상태코드"]

In [31]:
df.columns = new_cols
df

,번호,주소,지번주소,지번본번,지번부번,단지명,전용면적,계약연월,계약일,거래금액,...,정제우편번호,정제WGS84경도,정제WGS84위도,정제관리번호,정제결과코드,정제주소구분코드,정제시스템구분코드,정제일시,정제불가여부,정제상태코드
0,134904,None,996,996,0,주공그린빌,84.80,2018-01,1~10,26900,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
1,134905,None,996,996,0,주공그린빌,75.95,2018-01,11~20,27000,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
2,134906,None,996,996,0,주공그린빌,84.51,2018-01,11~20,25500,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
3,134907,None,996,996,0,주공그린빌,59.92,2018-01,11~20,23700,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
4,134908,None,996,996,0,주공그린빌,84.80,2018-01,11~20,27450,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134837,269497,None,Jun-49,49,6,남수원현대,84.98,2018-10,11~20,14500,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134838,269498,None,Jun-49,49,6,남수원현대,59.98,2018-10,21~31,14600,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134839,269499,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,1~10,19000,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134840,269500,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,1~10,17800,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동
134841,269501,None,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,11~20,21900,...,None,None,None,None,None,None,None,None,None,경기도 화성시 안녕동

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134842 entries, 0 to 134841
Data columns (total 27 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   번호         134842 non-null  int64
 1   주소         0 non-null       object
 2   지번주소       134840 non-null  object
 3   지번본번       134842 non-null  object
 4   지번부번       134842 non-null  object
 5   단지명        134842 non-null  object
 6   전용면적       134842 non-null  float64
 7   계약연월       134842 non-null  object
 8   계약일        134842 non-null  object
 9   거래금액       134842 non-null  int64
 10  층명         134842 non-null  object
 11  건축년도       134842 non-null  object
 12  도로명        134318 non-null  object
 13  정제완료여부     0 non-null       object
 14  생성일자       0 non-null       object
 15  정제지번주소     0 non-null       object
 16  정제도로명주소    0 non-null       object
 17  정제우편번호     0 non-null       object
 18  정제WGS84경도  0 non-null       object
 19  정제WGS84위도  0 non-null       object
 20  정제관리번호     0 non-null       object
 21  정제결과코드     0 non-null       object
 22  정제주소구분코드   0 non-null       object
 23  정제시스템구분코드  0 non-null       object
 24  정제일시       0 non-null       object
 25  정제불가여부     0 non-null       object
 26  정제상태코드     134842 non-null  object
dtypes: float64(1), int64(2), object(24)
memory usage: 27.8+ MB

In [41]:
df['도로명']

0         통일로802번길
1         통일로802번길
2         통일로802번길
3         통일로802번길
4         통일로802번길
            ...
134837         화산로
134838         화산로
134839         효행로
134840         효행로
134841         효행로
Name: 도로명, Length: 134842, dtype: object

In [40]:
df.columns

Index(['번호', '주소', '지번주소', '지번본번', '지번부번', '단지명', '전용면적', '계약연월', '계약일',
       '거래금액', '층명', '건축년도', '도로명', '정제완료여부', '생성일자', '정제지번주소', '정제도로명주소',
       '정제우편번호', '정제WGS84경도', '정제WGS84위도', '정제관리번호', '정제결과코드', '정제주소구분코드',
       '정제시스템구분코드', '정제일시', '정제불가여부', '정제상태코드'],
      dtype='object')

In [42]:
result_df = df[['번호', '단지명', '전용면적', '계약연월', '계약일', '거래금액', '정제상태코드']]
result_df

            번호         단지명   전용면적     계약연월    계약일   거래금액         정제상태코드
0       134904       주공그린빌  84.80  2018-01   1~10  26900  경기도 고양덕양구 관산동
1       134905       주공그린빌  75.95  2018-01  11~20  27000  경기도 고양덕양구 관산동
2       134906       주공그린빌  84.51  2018-01  11~20  25500  경기도 고양덕양구 관산동
3       134907       주공그린빌  59.92  2018-01  11~20  23700  경기도 고양덕양구 관산동
4       134908       주공그린빌  84.80  2018-01  11~20  27450  경기도 고양덕양구 관산동
...        ...         ...    ...      ...    ...    ...            ...
134837  269497       남수원현대  84.98  2018-10  11~20  14500    경기도 화성시 안녕동
134838  269498       남수원현대  59.98  2018-10  21~31  14600    경기도 화성시 안녕동
134839  269499  다솜마을동문굿모닝힐  84.99  2018-10   1~10  19000    경기도 화성시 안녕동
134840  269500  다솜마을동문굿모닝힐  84.99  2018-10   1~10  17800    경기도 화성시 안녕동
134841  269501  다솜마을동문굿모닝힐  84.99  2018-10  11~20  21900    경기도 화성시 안녕동

[134842 rows x 7 columns]