# 데이터분석순서 (KDD 분석 방법론)
* 데이터 세트 선택: csv, excel, DB에서 데이터를 읽어옴
* 데이터 전처리: 데이터타입, 결측값, 이상값탐지, 데이터 분포 분석, 상관관계
* 데이터 변환(특성추출): 원본 데이터에서 새로운 데이터 생성, 삭제, 스케일링, 구간화
* 데이터 마이닝(모델 만들기, 분석): 분석에 적합한 알고리즘 선택, 모델 생성, 튜닝
* 결과 평가: 테스트 데이터를 이용해서 데이터 마이닝으로 만든 모델의 성능 평가

# 데이터 전처리
* 데이터 타입 변환
* 결측치 탐지 및 보간
* 이상치 탐지 및 처리
* 데이터 특성 파악(치우침, 분포 특성)
* 변수들 간의 상관관계 분석

In [1]:
import pandas as pd
import numpy as np

# 1. 데이터 세트 선택 및 로딩
* 데이터 로드후 head, tail, info, describe로 데이터의 구조 파악

In [2]:
data = pd.read_csv("./data/Titanic_train.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# 2. info()로 컬럼명, 결측치, 데이터 타입 파악

In [3]:
# 데이터가 너무 커서 Non-Null Count가 표시 안될 때: show_counts=True
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df = pd.read_csv("./data/movie_title_data.tsv", sep="\t")
df

C:\Users\haram4th\AppData\Local\Temp\ipykernel_14332\3591949980.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./data/movie_title_data.tsv", sep="\t")

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
8407394,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2010,\N,\N,"Action,Drama,Family"
8407395,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
8407396,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
8407397,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
8407398,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [5]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   tconst          8407399 non-null  object
 1   titleType       8407399 non-null  object
 2   primaryTitle    8407385 non-null  object
 3   originalTitle   8407385 non-null  object
 4   isAdult         8407399 non-null  object
 5   startYear       8407399 non-null  object
 6   endYear         8407399 non-null  object
 7   runtimeMinutes  8407399 non-null  object
 8   genres          8407389 non-null  object
dtypes: object(9)
memory usage: 577.3+ MB

In [6]:
df['runtimeMinutes'].astype(int)

ValueError: invalid literal for int() with base 10: '\\N'

In [7]:
df['runtimeMinutes'].unique()

array(['1', '5', '4', '12', '40', '2', '\\N', '0', '3', '20', '13', '6',
       '11', '9', '10', '8', '15', '21', '16', '14', '7', '24', '100',
       '17', '70', '90', '25', '120', '36', '18', '30', '19', '44', '38',
       '58', '45', '50', '34', '28', '22', '35', '42', '23', '51', '52',
       '60', '92', '56', '53', '31', '41', '48', '68', '33', '29', '71',
       '43', '46', '27', '32', '76', '85', '55', '121', '89', '26', '37',
       '69', '54', '150', '64', '96', '49', '61', '39', '101', '300',
       '57', '99', '110', '88', '86', '170', '72', '78', '75', '450',
       '148', '124', '220', '59', '63', '112', '1428', '84', '65', '74',
       '105', '310', '73', '82', '81', '199', '139', '109', '67', '219',
       '80', '195', '440', '77', '293', '97', '62', '47', '250', '421',
       '360', '180', '66', '93', '163', '400', '104', '95', '140', '165',
       '116', '83', '320', '125', '127', '138', '460', '350', '374',
       '480', '91', '87', '130', '108', '79', '136', '94', '600', '240',
       '117', '135', '146', '418', '330', '242', '223', '489', '98',
       '119', '122', '115', '207', '166', '106', '111', '145', '131',
       '243', '172', '167', '103', '157', '107', '248', '235', '184',
       '102', '380', '200', '133', '128', '143', '155', '137', '183',
       '210', '417', '141', '162', '153', '132', '129', '123', '144',
       '151', '114', '113', '359', '118', '126', '179', '260', '230',
       '168', '160', '142', '159', '185', '156', '215', '177', '213',
       '149', '147', '266', '152', '217', '158', '226', '164', '194',
       '225', '216', '227', '231', '218', '246', '279', '228', '229',
       '212', '236', '306', '257', '245', '197', '255', '323', '305',
       '328', '269', '176', '232', '258', '256', '281', '303', '290',
       '308', '224', '294', '252', '268', '204', '298', '299', '264',
       '211', '302', '238', '263', '134', '265', '205', '154', '237',
       '285', '267', '247', '186', '241', '289', '283', '270', '251',
       '278', '196', '261', '275', '280', '244', '189', '169', '284',
       '295', '201', '221', '192', '171', '193', '287', '161', '181',
       '175', '174', '173', '315', '182', '239', '178', '208', '188',
       '497', '209', '190', '327', '317', '191', '434', '234', '288',
       '438', '422', '378', '316', '340', '203', '253', '206', '344',
       '540', '476', '451', '321', '202', '348', '890', '309', '653',
       '431', '390', '187', '370', '396', '282', '471', '669', '467',
       '566', '286', '274', '763', '770', '311', '198', '500', '373',
       '382', '596', '1335', '588', '750', '273', '442', '599', '333',
       '614', '1256', '385', '780', '510', '475', '271', '291', '366',
       '840', '742', '931', '676', '547', '673', '358', '394', '301',
       '233', '381', '659', '752', '504', '410', '520', '720', '883',
       '313', '420', '778', '413', '402', '700', '272', '222', '924',
       '391', '561', '428', '437', '416', '367', '307', '304', '570',
       '569', '371', '415', '376', '870', '312', '572', '407', '331',
       '375', '436', '355', '353', '357', '873', '384', '1290', '345',
       '1620', '318', '335', '624', '680', '262', '398', '567', '606',
       '214', '501', '322', '834', '735', '1140', '522', '361', '276',
       '439', '314', '515', '762', '620', '528', '623', '537', '336',
       '341', '568', '571', '556', '386', '383', '650', '292', '343',
       '277', '698', '401', '377', '672', '465', '702', '660', '622',
       '356', '296', '1352', '1320', '395', '583', '665', '339', '259',
       '351', '388', '325', '1120', '254', '455', '554', '612', '616',
       '349', '458', '426', '1500', '630', '594', '1080', '485', '495',
       '347', '487', '1800', '577', '1440', '2800', '491', '338', '1100',
       '406', '3122', '776', '369', '297', '804', '445', '2382', '960',
       '615', '535', '392', '663', '693', '580', '425', '544', '5220',
       '877', '389', '464', '545', '640', '453', '446', '372', '629',
       '678', '1300', '352', '689', '793', '2925', '608', '2880', '1170',
       '462', '1084', '457', '550', '701', '657', '249', '530', '346',
       '574', '738', '1970', '354', '551', '1260', '1020', '1200', '646',
       '459', '579', '820', '704', '408', '552', '999', '710', '715',
       '3900', '514', '1664', '1215', '1755', '1710', '1035', '1370',
       '1350', '1410', '1380', '326', '1430', '585', '730', '364', '516',
       '705', '3600', '1973', '1196', '765', '2001', '1000', '2002',
       '502', '8400', '541', '2000', '1999', '414', '652', '1997', '1040',
       '1442', '598', '526', '334', '1248', '441', '543', '1773', '1932',
       '466', '538', '4800', '363', '2150', '403', '900', '527', '636',
       '575', '379', '412', '506', '800', '519', '469', '719', '429',
       '1441', '490', 'Reality-TV', '784', '474', '990', '368', '3285',
       '3300', '319', '461', '1400', '10062', '2018', '2160', '494',
       '342', '468', '387', '337', '634', '2004', 'Documentary', '13319',
       '1325', 'Talk-Show', '584', '573', '324', '478', '472', '329',
       '35791', 'Game-Show', '1444', '479', '28643', '1845', '675',
       '1445', '1174', '1050', '435', '498', '576', '332', '521', '2010',
       '1099', '483', '668', '785', '362', '499', '6000', '449', '496',
       '518', '539', '399', '670', '477', '712', '619',
       'Animation,Comedy,Family', '959', '512', '950', '546', '409',
       '443', '432', '456', '448', '559', '10000', '736', '470', '365',
       '444', '405', '830', '1009', '454', '447', '942', '7777', '452',
       '3087', '593', '503', '602', '481', '586', '397', '1452', '1554',
       '542', '850', '562', '2580', '961', '641', '964', '473', '885',
       '1268', '1134', '691', '1873', '1860', '783', '509', '2021', '553',
       '711', '484', '901', '930', '493', '1560', '1680', '430', '1568',
       '751', '761', '5700', '590', '845', '853', '513', '2400', '1669',
       '605', '1210', '865', '463', '642', '724', '1700', '842', '393',
       '9000', '613', '411', '557', '525', '810', '14400', '912', '703',
       '1584', '536', '532', '404', '625', '940', '795', '1470', '1411',
       '1716', '2288', '3000', '3077', '419', '43200', '936', '747',
       '1005', '1008', '1285', '655', '2565', '1151', '740', '549',
       '1644', '1207', '3240', '2905', '5460', '1068', '607', '433',
       '1415', '511', '685', '582', '684', '662', '661', '597', '1559',
       '771', '4080', '958', '492', '1044', '758', '914', '1616', '2070',
       '923', '789', '4162', '3825', '697', '1228', '482', '2015', '773',
       '1439', '1329', '1532', '548', '954', '5760', '746', '1184',
       '1179', '486', '423', '51420', '531', '601', '1750', '808', '1980',
       '2112', '716', '690', '755', '721', '424', '2088'], dtype=object)

In [8]:
df2 = df.iloc[2000110:2050110, :].copy()
df2

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
2000110,tt1181630,tvEpisode,Episode #1.1,Episode #1.1,0,2008,\N,\N,"Comedy,Game-Show"
2000111,tt11816310,tvEpisode,Episode #1.6000,Episode #1.6000,0,1979,\N,30,\N
2000112,tt11816312,tvEpisode,Building - Nest,Building - Nest,0,2009,\N,\N,Family
2000113,tt11816314,tvEpisode,Episode #1.1,Episode #1.1,0,2019,\N,\N,Talk-Show
2000114,tt11816316,tvSeries,Saturday Club,Saturday Club,0,2019,\N,3,"Animation,Family"
...,...,...,...,...,...,...,...,...,...
2050105,tt11903592,tvEpisode,Harvie vs. Hare,Harvie vs. Hare,0,2020,\N,22,"Comedy,Game-Show"
2050106,tt11903594,tvEpisode,Episode #16.101,Episode #16.101,0,\N,\N,\N,"Comedy,Drama,Music"
2050107,tt11903596,tvEpisode,Episode #16.102,Episode #16.102,0,\N,\N,\N,"Comedy,Drama,Music"
2050108,tt11903598,tvEpisode,Episode #16.104,Episode #16.104,0,\N,\N,\N,"Comedy,Drama,Music"
2050109,tt1190359,tvEpisode,Episode #1.165,Episode #1.165,0,2002,\N,60,Drama

In [9]:
df2['runtimeMinutes'].astype(int)

ValueError: invalid literal for int() with base 10: '\\N'

In [10]:
df2['runtimeMinutes'].unique()

array(['\\N', '30', '3', '43', '60', '70', '36', '48', '41', '12', '52',
       '66', '24', '7', '14', '4', '62', '42', '55', '8', '29', '64',
       '46', '54', '26', '25', '51', '28', '107', '45', '5', '58', '17',
       '6', '39', '59', '44', '99', '11', '90', '2', '23', '121', '22',
       '10', '97', '85', '9', '31', '150', '47', '183', '115', '56', '21',
       '49', '53', '13', '50', '15', '16', '40', '102', '110', '124',
       '67', '57', '360', '116', '86', '203', '154', '27', '117', '120',
       '280', '75', '199', '95', '94', '118', '20', '77', '71', '188',
       '105', '69', '176', '239', '156', '139', '72', '78', '153', '74',
       '1', '32', '18', '38', '101', '73', '169', '220', '180', '82',
       '88', '103', '100', '123', '84', '65', '35', '98', '80', '87',
       '122', '344', '96', '33', '37', '200', '34', '331', '190', '93',
       '133', '358', '91', '83', '179', '19', '136', '158', '111', '126',
       '63', '61', '142', '79', '76', '104', '108', '163', '119', '81',
       '109', '92', '68', '152', '140', '130', '167', '132', '114', '168',
       '162', '223', '106', '128', '175', '125', '112', '173', '210',
       '129', '516', '89', '240', '127', '141', '226', '144', '146',
       '300', '334', '135', '384', '148', '134', '181', '149', '221',
       '219', '170', '172', '230', '178', '165', '160', '143', '296',
       '145', '161', '600', '209', '151', '186', '131', '215', '138',
       '235', '293', '630', '157', '155', 'Talk-Show', '380', '201',
       '113', '213', '196', '137', '164', '147', '246', '584', '192',
       '242', '216', '166', '278', '273', '372'], dtype=object)

In [11]:
df[df['runtimeMinutes'] == "Talk-Show"]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
2030110,tt11868642,tvEpisode,GGN Heavyweight Championship Lungs With Mike T...,0,2020,\N,\N,Talk-Show,NaN

In [12]:
def to_num(df):
    print(df.shape)
    display(df)
    try:
        df['runtimeMinutes'] = int(df['runtimeMinutes'])
        return df
    except:
        if df['runtimeMinutes'] == '\\N':
            df['runtimeMinutes'] = 0
            return df
        else:
            df['genres'] = df['runtimeMinutes']
            df['runtimeMinutes'] = 0
            return df

In [13]:
df2.apply(to_num, axis=1)
df2

(9,)

tconst                   tt1181630
titleType                tvEpisode
primaryTitle          Episode #1.1
originalTitle         Episode #1.1
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2000110, dtype: object

(9,)

tconst                 tt11816310
titleType               tvEpisode
primaryTitle      Episode #1.6000
originalTitle     Episode #1.6000
isAdult                         0
startYear                    1979
endYear                        \N
runtimeMinutes                 30
genres                         \N
Name: 2000111, dtype: object

(9,)

tconst                 tt11816312
titleType               tvEpisode
primaryTitle      Building - Nest
originalTitle     Building - Nest
isAdult                         0
startYear                    2009
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2000112, dtype: object

(9,)

tconst              tt11816314
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2000113, dtype: object

(9,)

tconst                  tt11816316
titleType                 tvSeries
primaryTitle         Saturday Club
originalTitle        Saturday Club
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                   3
genres            Animation,Family
Name: 2000114, dtype: object

(9,)

tconst                              tt11816318
titleType                            tvEpisode
primaryTitle      Fingring, fotball og fienden
originalTitle     Fingring, fotball og fienden
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                                  Comedy
Name: 2000115, dtype: object

(9,)

tconst              tt1181631
titleType           tvEpisode
primaryTitle      Doppelspiel
originalTitle     Doppelspiel
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres            Crime,Drama
Name: 2000116, dtype: object

(9,)

tconst                tt11816320
titleType              tvEpisode
primaryTitle      Zombie Breasts
originalTitle     Zombie Breasts
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                43
genres                Reality-TV
Name: 2000117, dtype: object

(9,)

tconst                tt11816322
titleType              tvEpisode
primaryTitle       Episode #2.38
originalTitle      Episode #2.38
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2000118, dtype: object

(9,)

tconst               tt11816324
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000119, dtype: object

(9,)

tconst                                          tt11816326
titleType                                        tvEpisode
primaryTitle      Le cinéma, l'érotisme et la pornographie
originalTitle     Le cinéma, l'érotisme et la pornographie
isAdult                                                  0
startYear                                             1981
endYear                                                 \N
runtimeMinutes                                          70
genres                                                  \N
Name: 2000120, dtype: object

(9,)

tconst                                                 tt11816328
titleType                                                 tvMovie
primaryTitle      Amazonas - A sustainable Life in the Rainforest
originalTitle     Amazonas - A sustainable Life in the Rainforest
isAdult                                                         0
startYear                                                    2013
endYear                                                        \N
runtimeMinutes                                                 36
genres                                                Documentary
Name: 2000121, dtype: object

(9,)

tconst                                tt1181632
titleType                             tvEpisode
primaryTitle                   Barnum's Big Top
originalTitle                  Barnum's Big Top
isAdult                                       0
startYear                                  1991
endYear                                      \N
runtimeMinutes                               \N
genres            Biography,Documentary,History
Name: 2000122, dtype: object

(9,)

tconst               tt11816330
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000123, dtype: object

(9,)

tconst                        tt11816332
titleType                      tvEpisode
primaryTitle      Water - Boats and Fish
originalTitle     Water - Boats and Fish
isAdult                                0
startYear                           2009
endYear                               \N
runtimeMinutes                        \N
genres                            Family
Name: 2000124, dtype: object

(9,)

tconst                 tt11816334
titleType            tvMiniSeries
primaryTitle      Spielend leicht
originalTitle     Spielend leicht
isAdult                         0
startYear                    1963
endYear                      1964
runtimeMinutes                 30
genres                  Game-Show
Name: 2000125, dtype: object

(9,)

tconst               tt11816336
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000126, dtype: object

(9,)

tconst               tt11816338
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000127, dtype: object

(9,)

tconst               tt11816340
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2013
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000128, dtype: object

(9,)

tconst               tt11816342
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000129, dtype: object

(9,)

tconst             tt11816344
titleType           tvEpisode
primaryTitle      Water - Ice
originalTitle     Water - Ice
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres                 Family
Name: 2000130, dtype: object

(9,)

tconst                     tt11816346
titleType                   tvEpisode
primaryTitle      Ribniska policistka
originalTitle     Ribniska policistka
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                          Music
Name: 2000131, dtype: object

(9,)

tconst                                tt11816348
titleType                              tvEpisode
primaryTitle      Eine schwere Entscheidung (II)
originalTitle     Eine schwere Entscheidung (II)
isAdult                                        0
startYear                                   2005
endYear                                       \N
runtimeMinutes                                48
genres                    Documentary,Reality-TV
Name: 2000132, dtype: object

(9,)

tconst                  tt1181634
titleType               tvEpisode
primaryTitle      Én gang skyldig
originalTitle     Én gang skyldig
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 41
genres                Crime,Drama
Name: 2000133, dtype: object

(9,)

tconst               tt11816350
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000134, dtype: object

(9,)

tconst             tt11816352
titleType            tvSeries
primaryTitle      Jordmødrene
originalTitle     Jordmødrene
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2000135, dtype: object

(9,)

tconst               tt11816354
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000136, dtype: object

(9,)

tconst              tt11816356
titleType                short
primaryTitle          Adam Exe
originalTitle         Adam Exe
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              \N
genres            Sci-Fi,Short
Name: 2000137, dtype: object

(9,)

tconst               tt11816358
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000138, dtype: object

(9,)

tconst                                                    tt1181635
titleType                                                 tvEpisode
primaryTitle      Rauchen, Saufen, Fressen - Was verbietet der S...
originalTitle     Rauchen, Saufen, Fressen - Was verbietet der S...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2000139, dtype: object

(9,)

tconst               tt11816360
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000140, dtype: object

(9,)

tconst                           tt11816362
titleType                         tvEpisode
primaryTitle      Water - Aquatic Creatures
originalTitle     Water - Aquatic Creatures
isAdult                                   0
startYear                              2009
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2000141, dtype: object

(9,)

tconst               tt11816364
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000142, dtype: object

(9,)

tconst                                   tt11816366
titleType                                 tvEpisode
primaryTitle      Un monde disparu mythe ou réalité
originalTitle     Un monde disparu mythe ou réalité
isAdult                                           0
startYear                                      1981
endYear                                          \N
runtimeMinutes                                   \N
genres                                           \N
Name: 2000143, dtype: object

(9,)

tconst               tt11816368
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000144, dtype: object

(9,)

tconst                   tt1181636
titleType                tvEpisode
primaryTitle         Couples Skate
originalTitle        Couples Skate
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  12
genres            Animation,Comedy
Name: 2000145, dtype: object

(9,)

tconst               tt11816370
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000146, dtype: object

(9,)

tconst            tt11816372
titleType          tvEpisode
primaryTitle        Alicia 1
originalTitle       Alicia 1
isAdult                    1
startYear               2006
endYear                   \N
runtimeMinutes            43
genres                 Adult
Name: 2000147, dtype: object

(9,)

tconst               tt11816374
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000148, dtype: object

(9,)

tconst               tt11816378
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000149, dtype: object

(9,)

tconst                           tt1181637
titleType                        tvEpisode
primaryTitle      Era uma Vez um Casamento
originalTitle     Era uma Vez um Casamento
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres                      Comedy,Romance
Name: 2000150, dtype: object

(9,)

tconst               tt11816380
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000151, dtype: object

(9,)

tconst               tt11816382
titleType             tvEpisode
primaryTitle      Water - Ponds
originalTitle     Water - Ponds
isAdult                       0
startYear                  2009
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2000152, dtype: object

(9,)

tconst            tt11816384
titleType          tvEpisode
primaryTitle        Alicia 2
originalTitle       Alicia 2
isAdult                    1
startYear               2006
endYear                   \N
runtimeMinutes            52
genres                 Adult
Name: 2000153, dtype: object

(9,)

tconst                     tt11816386
titleType                   tvEpisode
primaryTitle      Folkets dyrevideoer
originalTitle     Folkets dyrevideoer
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2000154, dtype: object

(9,)

tconst                          tt11816388
titleType                        tvEpisode
primaryTitle      Water - Mud and Concrete
originalTitle     Water - Mud and Concrete
isAdult                                  0
startYear                             2009
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2000155, dtype: object

(9,)

tconst                                 tt1181638
titleType                               tvSeries
primaryTitle      BBC Africa Cup of Nations 2008
originalTitle     BBC Africa Cup of Nations 2008
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres                                     Sport
Name: 2000156, dtype: object

(9,)

tconst              tt11816390
titleType         tvMiniSeries
primaryTitle          7 Idiots
originalTitle         7 Idiots
isAdult                      0
startYear                 2019
endYear                   2020
runtimeMinutes              \N
genres               Adventure
Name: 2000157, dtype: object

(9,)

tconst            tt11816392
titleType          tvEpisode
primaryTitle      Jean Gabin
originalTitle     Jean Gabin
isAdult                    0
startYear               1981
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2000158, dtype: object

(9,)

tconst               tt11816394
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000159, dtype: object

(9,)

tconst               tt11816396
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000160, dtype: object

(9,)

tconst               tt11816398
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000161, dtype: object

(9,)

tconst                                tt1181639
titleType                             tvEpisode
primaryTitle      Age Ain't Nothin But a Number
originalTitle     Age Ain't Nothin But a Number
isAdult                                       0
startYear                                  2007
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2000162, dtype: object

(9,)

tconst                                tt11816400
titleType                              tvEpisode
primaryTitle      What to Wear - Socks and Shoes
originalTitle     What to Wear - Socks and Shoes
isAdult                                        0
startYear                                   2009
endYear                                       \N
runtimeMinutes                                \N
genres                                    Family
Name: 2000163, dtype: object

(9,)

tconst               tt11816402
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000164, dtype: object

(9,)

tconst               tt11816404
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000165, dtype: object

(9,)

tconst               tt11816406
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000166, dtype: object

(9,)

tconst               tt11816408
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000167, dtype: object

(9,)

tconst                          tt1181640
titleType                       tvEpisode
primaryTitle       A Day in the Country 2
originalTitle      A Day in the Country 2
isAdult                                 0
startYear                            2007
endYear                                \N
runtimeMinutes                         \N
genres            Animation,Comedy,Family
Name: 2000168, dtype: object

(9,)

tconst               tt11816410
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000169, dtype: object

(9,)

tconst                                 tt11816412
titleType                               tvEpisode
primaryTitle      Zhao Guo Pian: Lie Luan Zhi Guo
originalTitle     Zhao Guo Pian: Lie Luan Zhi Guo
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 66
genres                                Documentary
Name: 2000170, dtype: object

(9,)

tconst                                                   tt11816414
titleType                                                 tvEpisode
primaryTitle      Ian Blackford: Does the SNP have a winning str...
originalTitle     Ian Blackford: Does the SNP have a winning str...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2000171, dtype: object

(9,)

tconst                       tt11816416
titleType                     tvEpisode
primaryTitle             Episode #27.17
originalTitle            Episode #27.17
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres            Comedy,News,Talk-Show
Name: 2000172, dtype: object

(9,)

tconst                                  tt11816418
titleType                                    movie
primaryTitle      Mainu Pyar Kardie Parjaat Kudiye
originalTitle     Mainu Pyar Kardie Parjaat Kudiye
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Drama
Name: 2000173, dtype: object

(9,)

tconst                              tt1181641
titleType                           tvEpisode
primaryTitle      Episode dated 3 August 2006
originalTitle     Episode dated 3 August 2006
isAdult                                     0
startYear                                2006
endYear                                    \N
runtimeMinutes                             \N
genres                       Comedy,Talk-Show
Name: 2000174, dtype: object

(9,)

tconst                            tt11816420
titleType                          tvEpisode
primaryTitle      What to Wear - Fancy Dress
originalTitle     What to Wear - Fancy Dress
isAdult                                    0
startYear                               2009
endYear                                   \N
runtimeMinutes                            \N
genres                                Family
Name: 2000175, dtype: object

(9,)

tconst                               tt11816422
titleType                                 movie
primaryTitle      Arbitrium: The Final Decision
originalTitle     Arbitrium: The Final Decision
isAdult                                       0
startYear                                    \N
endYear                                      \N
runtimeMinutes                               \N
genres                       Action,Crime,Drama
Name: 2000176, dtype: object

(9,)

tconst                  tt11816424
titleType             tvMiniSeries
primaryTitle      Naturfotografene
originalTitle     Naturfotografene
isAdult                          0
startYear                     2015
endYear                       2015
runtimeMinutes                  \N
genres                 Documentary
Name: 2000177, dtype: object

(9,)

tconst                        tt11816426
titleType                      tvEpisode
primaryTitle      What to Wear - Outside
originalTitle     What to Wear - Outside
isAdult                                0
startYear                           2009
endYear                               \N
runtimeMinutes                        \N
genres                            Family
Name: 2000178, dtype: object

(9,)

tconst                          tt11816428
titleType                        tvEpisode
primaryTitle      What to Wear - for Sport
originalTitle     What to Wear - for Sport
isAdult                                  0
startYear                             2009
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2000179, dtype: object

(9,)

tconst                             tt1181642
titleType                          tvEpisode
primaryTitle             A Legacy of Amadeus
originalTitle            A Legacy of Amadeus
isAdult                                    0
startYear                               1999
endYear                                   \N
runtimeMinutes                            24
genres            Action,Adventure,Animation
Name: 2000180, dtype: object

(9,)

tconst                       tt11816430
titleType                         short
primaryTitle          The Last Question
originalTitle         The Last Question
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres            Horror,Short,Thriller
Name: 2000181, dtype: object

(9,)

tconst                               tt11816432
titleType                                 short
primaryTitle      Dichotomy, Duality, Divergent
originalTitle     Dichotomy, Duality, Divergent
isAdult                                       0
startYear                                    \N
endYear                                      \N
runtimeMinutes                               \N
genres                              Drama,Short
Name: 2000182, dtype: object

(9,)

tconst            tt11816436
titleType          tvEpisode
primaryTitle         Bolum 2
originalTitle        Bolum 2
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000183, dtype: object

(9,)

tconst                         tt11816438
titleType                       tvEpisode
primaryTitle      What to Wear - Costumes
originalTitle     What to Wear - Costumes
isAdult                                 0
startYear                            2009
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2000184, dtype: object

(9,)

tconst                             tt1181643
titleType                          tvEpisode
primaryTitle                 Beck Comes Back
originalTitle                Beck Comes Back
isAdult                                    0
startYear                               2000
endYear                                   \N
runtimeMinutes                            24
genres            Action,Adventure,Animation
Name: 2000185, dtype: object

(9,)

tconst                  tt11816440
titleType                tvEpisode
primaryTitle        Episode #1.746
originalTitle       Episode #1.746
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000186, dtype: object

(9,)

tconst                  tt11816442
titleType                tvEpisode
primaryTitle        Episode #1.747
originalTitle       Episode #1.747
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000187, dtype: object

(9,)

tconst                       tt11816444
titleType                         video
primaryTitle      Na Chui: Till the End
originalTitle     Na Chui: Till the End
isAdult                               1
startYear                          2020
endYear                              \N
runtimeMinutes                        7
genres                Adult,Music,Short
Name: 2000188, dtype: object

(9,)

tconst                  tt11816446
titleType                tvEpisode
primaryTitle        Episode #1.748
originalTitle       Episode #1.748
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000189, dtype: object

(9,)

tconst                                        tt11816448
titleType                                          short
primaryTitle      Yene Fikir Ethiopia (My Love Ethiopia)
originalTitle     Yene Fikir Ethiopia (My Love Ethiopia)
isAdult                                                0
startYear                                           2019
endYear                                               \N
runtimeMinutes                                        14
genres                                   Animation,Short
Name: 2000190, dtype: object

(9,)

tconst                             tt1181644
titleType                          tvEpisode
primaryTitle             Bring Back My Ghost
originalTitle            Bring Back My Ghost
isAdult                                    0
startYear                               1999
endYear                                   \N
runtimeMinutes                            24
genres            Action,Adventure,Animation
Name: 2000191, dtype: object

(9,)

tconst               tt11816450
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  1956
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000192, dtype: object

(9,)

tconst                  tt11816452
titleType                tvEpisode
primaryTitle        Episode #1.749
originalTitle       Episode #1.749
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000193, dtype: object

(9,)

tconst                              tt11816454
titleType                            tvEpisode
primaryTitle      Another Chance for Zaguresu"
originalTitle     Another Chance for Zaguresu"
isAdult                                      0
startYear                                 1998
endYear                                     \N
runtimeMinutes                              \N
genres                                  Sci-Fi
Name: 2000194, dtype: object

(9,)

tconst                          tt11816456
titleType                            video
primaryTitle      Darshan Raval: Asal Mein
originalTitle     Darshan Raval: Asal Mein
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                           4
genres                         Music,Short
Name: 2000195, dtype: object

(9,)

tconst                             tt1181645
titleType                          tvEpisode
primaryTitle                     Missing Cat
originalTitle                    Missing Cat
isAdult                                    0
startYear                               2000
endYear                                   \N
runtimeMinutes                            24
genres            Action,Adventure,Animation
Name: 2000196, dtype: object

(9,)

tconst                  tt11816460
titleType                tvEpisode
primaryTitle        Episode #1.751
originalTitle       Episode #1.751
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000197, dtype: object

(9,)

tconst                                tt11816462
titleType                              tvEpisode
primaryTitle      Chu Guo Pian: Gui Zu Zhi Shang
originalTitle     Chu Guo Pian: Gui Zu Zhi Shang
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                62
genres                               Documentary
Name: 2000198, dtype: object

(9,)

tconst               tt11816464
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000199, dtype: object

(9,)

tconst                      tt11816468
titleType                        video
primaryTitle      Jass Manak: Shopping
originalTitle     Jass Manak: Shopping
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       4
genres                     Music,Short
Name: 2000200, dtype: object

(9,)

tconst                             tt1181646
titleType                          tvEpisode
primaryTitle          The Call from the Past
originalTitle         The Call from the Past
isAdult                                    0
startYear                               1999
endYear                                   \N
runtimeMinutes                            24
genres            Action,Adventure,Animation
Name: 2000201, dtype: object

(9,)

tconst                         tt11816472
titleType                       tvEpisode
primaryTitle      Das Monster Eifersucht!
originalTitle     Das Monster Eifersucht!
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                   Drama,Reality-TV
Name: 2000202, dtype: object

(9,)

tconst               tt11816474
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000203, dtype: object

(9,)

tconst               tt11816476
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000204, dtype: object

(9,)

tconst                                 tt11816478
titleType                               tvEpisode
primaryTitle      Episode dated 19 September 1989
originalTitle     Episode dated 19 September 1989
isAdult                                         0
startYear                                    1989
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2000205, dtype: object

(9,)

tconst                             tt1181647
titleType                          tvEpisode
primaryTitle            Winter Night Phantom
originalTitle           Winter Night Phantom
isAdult                                    0
startYear                               2000
endYear                                   \N
runtimeMinutes                            24
genres            Action,Adventure,Animation
Name: 2000206, dtype: object

(9,)

tconst               tt11816480
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000207, dtype: object

(9,)

tconst                                 tt11816482
titleType                               tvEpisode
primaryTitle      Revealing Our Ancient Ancestors
originalTitle     Revealing Our Ancient Ancestors
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 48
genres               Adventure,Mystery,Reality-TV
Name: 2000208, dtype: object

(9,)

tconst               tt11816484
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000209, dtype: object

(9,)

tconst                tt11816486
titleType              tvEpisode
primaryTitle      Episode #1.277
originalTitle     Episode #1.277
isAdult                        0
startYear                   2003
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2000210, dtype: object

(9,)

tconst                             tt11816488
titleType                           tvEpisode
primaryTitle      Verhängnisvoller Ausverkauf
originalTitle     Verhängnisvoller Ausverkauf
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                       Drama,Reality-TV
Name: 2000211, dtype: object

(9,)

tconst                tt1181648
titleType             tvEpisode
primaryTitle      The Front Man
originalTitle     The Front Man
isAdult                       0
startYear                  1965
endYear                      \N
runtimeMinutes               \N
genres                 Thriller
Name: 2000212, dtype: object

(9,)

tconst                  tt11816490
titleType                tvEpisode
primaryTitle      He Made Me Do It
originalTitle     He Made Me Do It
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  42
genres                       Crime
Name: 2000213, dtype: object

(9,)

tconst                      tt11816492
titleType                    tvEpisode
primaryTitle      Godzilla's Insanity"
originalTitle     Godzilla's Insanity"
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres                          Sci-Fi
Name: 2000214, dtype: object

(9,)

tconst              tt11816494
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000215, dtype: object

(9,)

tconst              tt11816496
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000216, dtype: object

(9,)

tconst              tt11816498
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000217, dtype: object

(9,)

tconst                             tt1181649
titleType                           tvSeries
primaryTitle      Burari tochû gesha no tabi
originalTitle     Burari tochû gesha no tabi
isAdult                                    0
startYear                               1992
endYear                                   \N
runtimeMinutes                            30
genres                            Reality-TV
Name: 2000218, dtype: object

(9,)

tconst              tt11816500
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000219, dtype: object

(9,)

tconst              tt11816502
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000220, dtype: object

(9,)

tconst              tt11816504
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000221, dtype: object

(9,)

tconst              tt11816506
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000222, dtype: object

(9,)

tconst              tt11816508
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000223, dtype: object

(9,)

tconst                                                  tt1181650
titleType                                               tvEpisode
primaryTitle      A Real Case of Murder: People vs. Peter Manceri
originalTitle     A Real Case of Murder: People vs. Peter Manceri
isAdult                                                         0
startYear                                                    1961
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                           Documentary,News
Name: 2000224, dtype: object

(9,)

tconst              tt11816510
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000225, dtype: object

(9,)

tconst              tt11816512
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000226, dtype: object

(9,)

tconst              tt11816514
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000227, dtype: object

(9,)

tconst              tt11816516
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000228, dtype: object

(9,)

tconst              tt11816518
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000229, dtype: object

(9,)

tconst                          tt1181651
titleType                       tvEpisode
primaryTitle      Berlin: End of the Line
originalTitle     Berlin: End of the Line
isAdult                                 0
startYear                            1960
endYear                                \N
runtimeMinutes                         \N
genres                   Documentary,News
Name: 2000230, dtype: object

(9,)

tconst              tt11816520
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000231, dtype: object

(9,)

tconst              tt11816522
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000232, dtype: object

(9,)

tconst              tt11816524
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000233, dtype: object

(9,)

tconst                  tt11816526
titleType                tvEpisode
primaryTitle        Episode #1.752
originalTitle       Episode #1.752
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000234, dtype: object

(9,)

tconst                  tt11816528
titleType                tvEpisode
primaryTitle        Episode #1.753
originalTitle       Episode #1.753
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000235, dtype: object

(9,)

tconst                         tt1181652
titleType                      tvEpisode
primaryTitle      Biography of a Missile
originalTitle     Biography of a Missile
isAdult                                0
startYear                           1959
endYear                               \N
runtimeMinutes                        \N
genres                  Documentary,News
Name: 2000236, dtype: object

(9,)

tconst                  tt11816530
titleType                tvEpisode
primaryTitle        Episode #1.754
originalTitle       Episode #1.754
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000237, dtype: object

(9,)

tconst               tt11816532
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000238, dtype: object

(9,)

tconst               tt11816534
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000239, dtype: object

(9,)

tconst               tt11816536
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000240, dtype: object

(9,)

tconst                  tt11816538
titleType                tvEpisode
primaryTitle        Episode #1.755
originalTitle       Episode #1.755
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000241, dtype: object

(9,)

tconst                     tt1181653
titleType                  tvEpisode
primaryTitle      Iran: Brittle Ally
originalTitle     Iran: Brittle Ally
isAdult                            0
startYear                       1959
endYear                           \N
runtimeMinutes                    \N
genres              Documentary,News
Name: 2000242, dtype: object

(9,)

tconst                  tt11816540
titleType                tvEpisode
primaryTitle        Episode #1.756
originalTitle       Episode #1.756
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000243, dtype: object

(9,)

tconst                  tt11816542
titleType                tvEpisode
primaryTitle        Episode #1.757
originalTitle       Episode #1.757
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000244, dtype: object

(9,)

tconst                  tt11816544
titleType                tvEpisode
primaryTitle        Episode #1.758
originalTitle       Episode #1.758
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000245, dtype: object

(9,)

tconst                  tt11816546
titleType                tvEpisode
primaryTitle        Episode #1.759
originalTitle       Episode #1.759
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000246, dtype: object

(9,)

tconst                  tt11816548
titleType                tvEpisode
primaryTitle        Episode #1.760
originalTitle       Episode #1.760
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000247, dtype: object

(9,)

tconst                                                tt1181654
titleType                                             tvEpisode
primaryTitle      Our Election Day Illusions: The Beat Majority
originalTitle     Our Election Day Illusions: The Beat Majority
isAdult                                                       0
startYear                                                  1961
endYear                                                      \N
runtimeMinutes                                               \N
genres                                         Documentary,News
Name: 2000248, dtype: object

(9,)

tconst                     tt11816550
titleType                    tvSeries
primaryTitle                 Outburst
originalTitle                Outburst
isAdult                             0
startYear                        1996
endYear                          1996
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2000249, dtype: object

(9,)

tconst                       tt11816552
titleType                         short
primaryTitle                     Trauma
originalTitle                    Trauma
isAdult                               0
startYear                          2021
endYear                              \N
runtimeMinutes                       \N
genres            Horror,Short,Thriller
Name: 2000250, dtype: object

(9,)

tconst                  tt11816554
titleType                tvEpisode
primaryTitle        Episode #1.761
originalTitle       Episode #1.761
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000251, dtype: object

(9,)

tconst                  tt11816556
titleType                tvEpisode
primaryTitle        Episode #1.762
originalTitle       Episode #1.762
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000252, dtype: object

(9,)

tconst                                                   tt11816558
titleType                                                 tvEpisode
primaryTitle      Ai Weiwei: Huawei, Hong Kong and being an arti...
originalTitle     Ai Weiwei: Huawei, Hong Kong and being an arti...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2000253, dtype: object

(9,)

tconst                             tt1181655
titleType                          tvEpisode
primaryTitle      The Great Holiday Massacre
originalTitle     The Great Holiday Massacre
isAdult                                    0
startYear                               1960
endYear                                   \N
runtimeMinutes                            60
genres                      Documentary,News
Name: 2000254, dtype: object

(9,)

tconst                  tt11816560
titleType                tvEpisode
primaryTitle        Episode #1.763
originalTitle       Episode #1.763
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000255, dtype: object

(9,)

tconst                  tt11816562
titleType                tvEpisode
primaryTitle        Episode #1.764
originalTitle       Episode #1.764
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000256, dtype: object

(9,)

tconst                                                   tt11816564
titleType                                                     video
primaryTitle      Khesari Lal Yadav & Antra Singh Priyanka: Laha...
originalTitle     Khesari Lal Yadav & Antra Singh Priyanka: Laha...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    3
genres                                                  Music,Short
Name: 2000257, dtype: object

(9,)

tconst                                                   tt11816566
titleType                                                     short
primaryTitle      Keepers of the Forest: A Tribe of the Amazon i...
originalTitle     Keepers of the Forest: A Tribe of the Amazon i...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   24
genres                                            Documentary,Short
Name: 2000258, dtype: object

(9,)

tconst               tt11816568
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000259, dtype: object

(9,)

tconst                          tt1181656
titleType                       tvEpisode
primaryTitle      The Year of the Polaris
originalTitle     The Year of the Polaris
isAdult                                 0
startYear                            1960
endYear                                \N
runtimeMinutes                         \N
genres                   Documentary,News
Name: 2000260, dtype: object

(9,)

tconst               tt11816570
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000261, dtype: object

(9,)

tconst               tt11816572
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000262, dtype: object

(9,)

tconst               tt11816574
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000263, dtype: object

(9,)

tconst               tt11816576
titleType             tvEpisode
primaryTitle      Episode #2.16
originalTitle     Episode #2.16
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2000264, dtype: object

(9,)

tconst                tt11816578
titleType              tvEpisode
primaryTitle      Patrice Munsel
originalTitle     Patrice Munsel
isAdult                        0
startYear                   1954
endYear                       \N
runtimeMinutes                \N
genres                     Music
Name: 2000265, dtype: object

(9,)

tconst                            tt1181657
titleType                         tvEpisode
primaryTitle      Who Speaks for the South?
originalTitle     Who Speaks for the South?
isAdult                                   0
startYear                              1960
endYear                                  \N
runtimeMinutes                           \N
genres                     Documentary,News
Name: 2000266, dtype: object

(9,)

tconst                               tt11816580
titleType                             tvEpisode
primaryTitle      Episode dated 9 February 2000
originalTitle     Episode dated 9 February 2000
isAdult                                       0
startYear                                  2000
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2000267, dtype: object

(9,)

tconst            tt11816582
titleType            tvMovie
primaryTitle          Matsar
originalTitle         Matsar
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            55
genres                 Crime
Name: 2000268, dtype: object

(9,)

tconst                           tt11816584
titleType                         tvEpisode
primaryTitle      De boter heeft het gedaan
originalTitle     De boter heeft het gedaan
isAdult                                   0
startYear                              2016
endYear                                  \N
runtimeMinutes                           \N
genres                                Drama
Name: 2000269, dtype: object

(9,)

tconst              tt11816586
titleType                short
primaryTitle      L'Attraction
originalTitle     L'Attraction
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres            Sci-Fi,Short
Name: 2000270, dtype: object

(9,)

tconst              tt11816588
titleType                movie
primaryTitle      Yao qian shu
originalTitle     Yao qian shu
isAdult                      0
startYear                 1955
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000271, dtype: object

(9,)

tconst                          tt1181658
titleType                       tvEpisode
primaryTitle      Cable Today En Francais
originalTitle     Cable Today En Francais
isAdult                                 0
startYear                            1994
endYear                                \N
runtimeMinutes                         \N
genres                               News
Name: 2000272, dtype: object

(9,)

tconst                               tt11816592
titleType                             tvEpisode
primaryTitle      Episode dated 22 January 1999
originalTitle     Episode dated 22 January 1999
isAdult                                       0
startYear                                  1999
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2000273, dtype: object

(9,)

tconst                  tt11816594
titleType                tvEpisode
primaryTitle      Kapster vermoord
originalTitle     Kapster vermoord
isAdult                          0
startYear                     2017
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2000274, dtype: object

(9,)

tconst             tt11816596
titleType               video
primaryTitle        Cami: Ven
originalTitle       Cami: Ven
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes              3
genres            Music,Short
Name: 2000275, dtype: object

(9,)

tconst                              tt11816598
titleType                            tvEpisode
primaryTitle      Overseer of the Spirit World
originalTitle     Overseer of the Spirit World
isAdult                                      0
startYear                                 1998
endYear                                     \N
runtimeMinutes                              \N
genres                                  Sci-Fi
Name: 2000276, dtype: object

(9,)

tconst            tt1181659
titleType          tvSeries
primaryTitle       City '68
originalTitle      City '68
isAdult                   0
startYear              1967
endYear                1968
runtimeMinutes           60
genres                Drama
Name: 2000277, dtype: object

(9,)

tconst                               tt11816600
titleType                             tvEpisode
primaryTitle      Episode dated 29 January 1999
originalTitle     Episode dated 29 January 1999
isAdult                                       0
startYear                                  1999
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2000278, dtype: object

(9,)

tconst                             tt11816602
titleType                           tvEpisode
primaryTitle      Babysitten op ontvoerd kind
originalTitle     Babysitten op ontvoerd kind
isAdult                                     0
startYear                                2017
endYear                                    \N
runtimeMinutes                             \N
genres                                  Drama
Name: 2000279, dtype: object

(9,)

tconst                                                   tt11816604
titleType                                                 tvEpisode
primaryTitle      Sopupelejä, lahjussyytteitä, viihdebisnestä......
originalTitle     Sopupelejä, lahjussyytteitä, viihdebisnestä......
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000280, dtype: object

(9,)

tconst                         tt11816606
titleType                           video
primaryTitle      Black Box: Strike It Up
originalTitle     Black Box: Strike It Up
isAdult                                 0
startYear                            1991
endYear                                \N
runtimeMinutes                          3
genres                        Music,Short
Name: 2000281, dtype: object

(9,)

tconst                                tt11816608
titleType                              tvEpisode
primaryTitle      Kunnioita lastasi kuin itseäsi
originalTitle     Kunnioita lastasi kuin itseäsi
isAdult                                        0
startYear                                   1999
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2000282, dtype: object

(9,)

tconst                    tt1181660
titleType                  tvSeries
primaryTitle      Classic Britannia
originalTitle     Classic Britannia
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres                  Documentary
Name: 2000283, dtype: object

(9,)

tconst                      tt11816610
titleType                    tvEpisode
primaryTitle      The Massive Godzilla
originalTitle     The Massive Godzilla
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres                          Sci-Fi
Name: 2000284, dtype: object

(9,)

tconst                    tt11816612
titleType                  tvEpisode
primaryTitle      Radeloze bruidegom
originalTitle     Radeloze bruidegom
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                         Drama
Name: 2000285, dtype: object

(9,)

tconst            tt11816614
titleType              short
primaryTitle        Riverbed
originalTitle       Elveleie
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2000286, dtype: object

(9,)

tconst                             tt11816616
titleType                           tvEpisode
primaryTitle      Episode dated 12 March 1999
originalTitle     Episode dated 12 March 1999
isAdult                                     0
startYear                                1999
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2000287, dtype: object

(9,)

tconst                tt11816618
titleType              tvEpisode
primaryTitle      Episode #45.46
originalTitle     Episode #45.46
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2000288, dtype: object

(9,)

tconst            tt1181661
titleType         tvEpisode
primaryTitle        Laundry
originalTitle       Laundry
isAdult                   0
startYear                \N
endYear                  \N
runtimeMinutes           \N
genres            Animation
Name: 2000289, dtype: object

(9,)

tconst                                 tt11816620
titleType                               tvEpisode
primaryTitle      Mitä tappajan mielessä liikkuu?
originalTitle     Mitä tappajan mielessä liikkuu?
isAdult                                         0
startYear                                    1999
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2000290, dtype: object

(9,)

tconst                                  tt11816622
titleType                                tvEpisode
primaryTitle      Godzilla Intense Fighting Record
originalTitle     Godzilla Intense Fighting Record
isAdult                                          0
startYear                                     1998
endYear                                         \N
runtimeMinutes                                  \N
genres                                      Sci-Fi
Name: 2000291, dtype: object

(9,)

tconst                            tt11816624
titleType                          tvEpisode
primaryTitle      Ober met mentale beperking
originalTitle     Ober met mentale beperking
isAdult                                    0
startYear                               2018
endYear                                   \N
runtimeMinutes                            \N
genres                                 Drama
Name: 2000292, dtype: object

(9,)

tconst                           tt11816626
titleType                         tvEpisode
primaryTitle      Arrow is Arrows is Arrows
originalTitle     Arrow is Arrows is Arrows
isAdult                                   0
startYear                              1980
endYear                                  \N
runtimeMinutes                           \N
genres                     Animation,Family
Name: 2000293, dtype: object

(9,)

tconst                            tt11816628
titleType                          tvEpisode
primaryTitle      Episode dated 2 April 1999
originalTitle     Episode dated 2 April 1999
isAdult                                    0
startYear                               1999
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2000294, dtype: object

(9,)

tconst                  tt1181662
titleType               tvEpisode
primaryTitle      The Car Robbery
originalTitle     The Car Robbery
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                  Animation
Name: 2000295, dtype: object

(9,)

tconst                            tt11816630
titleType                          tvEpisode
primaryTitle      Episode dated 9 April 1999
originalTitle     Episode dated 9 April 1999
isAdult                                    0
startYear                               1999
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2000296, dtype: object

(9,)

tconst                                tt11816632
titleType                              tvEpisode
primaryTitle      Mortar This than Meets the Eye
originalTitle     Mortar This than Meets the Eye
isAdult                                        0
startYear                                   1980
endYear                                       \N
runtimeMinutes                                \N
genres                          Animation,Family
Name: 2000297, dtype: object

(9,)

tconst              tt11816634
titleType                short
primaryTitle         Book Club
originalTitle        Book Club
isAdult                      0
startYear                 2006
endYear                     \N
runtimeMinutes               8
genres            Comedy,Short
Name: 2000298, dtype: object

(9,)

tconst                                                tt11816636
titleType                                              tvEpisode
primaryTitle      The Frightening Photograph of the Spirit Beast
originalTitle     The Frightening Photograph of the Spirit Beast
isAdult                                                        0
startYear                                                   1998
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                    Sci-Fi
Name: 2000299, dtype: object

(9,)

tconst                             tt11816638
titleType                           tvEpisode
primaryTitle      Episode dated 16 April 1999
originalTitle     Episode dated 16 April 1999
isAdult                                     0
startYear                                1999
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2000300, dtype: object

(9,)

tconst                                tt1181663
titleType                             tvEpisode
primaryTitle      All Creatures Great and Small
originalTitle     All Creatures Great and Small
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               29
genres                              Documentary
Name: 2000301, dtype: object

(9,)

tconst                             tt11816640
titleType                           tvEpisode
primaryTitle      Episode dated 23 April 1999
originalTitle     Episode dated 23 April 1999
isAdult                                     0
startYear                                1999
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2000302, dtype: object

(9,)

tconst                      tt11816642
titleType                    tvEpisode
primaryTitle      King Caesar's Search
originalTitle     King Caesar's Search
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres                          Sci-Fi
Name: 2000303, dtype: object

(9,)

tconst                                   tt11816644
titleType                                 tvEpisode
primaryTitle      Han Guo Pian: Quan Shu De Dai Jia
originalTitle     Han Guo Pian: Quan Shu De Dai Jia
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   64
genres                                  Documentary
Name: 2000304, dtype: object

(9,)

tconst                             tt11816646
titleType                           tvEpisode
primaryTitle      Episode dated 30 April 1999
originalTitle     Episode dated 30 April 1999
isAdult                                     0
startYear                                1999
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2000305, dtype: object

(9,)

tconst                                                   tt11816648
titleType                                                 tvEpisode
primaryTitle      Rautavaarasta tuli säveltäjä melkein "vahingossa"
originalTitle     Rautavaarasta tuli säveltäjä melkein "vahingossa"
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000306, dtype: object

(9,)

tconst              tt1181664
titleType           tvEpisode
primaryTitle      Dragon Hunt
originalTitle     Dragon Hunt
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             46
genres            Documentary
Name: 2000307, dtype: object

(9,)

tconst                                 tt11816650
titleType                               tvEpisode
primaryTitle      Round and Round and Up and Down
originalTitle     Round and Round and Up and Down
isAdult                                         0
startYear                                    1980
endYear                                        \N
runtimeMinutes                                 \N
genres                           Animation,Family
Name: 2000308, dtype: object

(9,)

tconst                     tt11816652
titleType                   tvEpisode
primaryTitle      Torema vs. Godzilla
originalTitle     Torema vs. Godzilla
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres                         Sci-Fi
Name: 2000309, dtype: object

(9,)

tconst                           tt11816654
titleType                         tvEpisode
primaryTitle      Episode dated 14 May 1999
originalTitle     Episode dated 14 May 1999
isAdult                                   0
startYear                              1999
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2000310, dtype: object

(9,)

tconst                tt11816656
titleType              tvEpisode
primaryTitle      Stop Godzilla!
originalTitle     Stop Godzilla!
isAdult                        0
startYear                   1998
endYear                       \N
runtimeMinutes                \N
genres                    Sci-Fi
Name: 2000311, dtype: object

(9,)

tconst                                                   tt11816658
titleType                                                 tvEpisode
primaryTitle      Miten ihminen jaksaa silloin, kun onnettomuus ...
originalTitle     Miten ihminen jaksaa silloin, kun onnettomuus ...
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000312, dtype: object

(9,)

tconst                   tt1181665
titleType                tvEpisode
primaryTitle      Episode #1.10731
originalTitle     Episode #1.10731
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2000313, dtype: object

(9,)

tconst                                        tt11816660
titleType                                      tvEpisode
primaryTitle      Luovuutta ei voi ammentaa oppikirjasta
originalTitle     Luovuutta ei voi ammentaa oppikirjasta
isAdult                                                0
startYear                                           1999
endYear                                               \N
runtimeMinutes                                        \N
genres                                                \N
Name: 2000314, dtype: object

(9,)

tconst                  tt11816662
titleType                    short
primaryTitle      Mona Lisa's Eyes
originalTitle     Mona Lisa's Eyes
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                 Music,Short
Name: 2000315, dtype: object

(9,)

tconst                    tt11816664
titleType                  tvEpisode
primaryTitle      Hurry King Caesar!
originalTitle     Hurry King Caesar!
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres                        Sci-Fi
Name: 2000316, dtype: object

(9,)

tconst                                                   tt11816666
titleType                                                 tvEpisode
primaryTitle      Satu muuttui todeksi ja kaikki itku - lopultak...
originalTitle     Satu muuttui todeksi ja kaikki itku - lopultak...
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000317, dtype: object

(9,)

tconst                                                   tt11816668
titleType                                                 tvEpisode
primaryTitle      Kuningas alkoholi istui olkapäällä eikä uhmast...
originalTitle     Kuningas alkoholi istui olkapäällä eikä uhmast...
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000318, dtype: object

(9,)

tconst                   tt1181666
titleType                tvEpisode
primaryTitle      Episode #1.10738
originalTitle     Episode #1.10738
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2000319, dtype: object

(9,)

tconst                  tt11816670
titleType                tvEpisode
primaryTitle      Way to Go Nashi"
originalTitle     Way to Go Nashi"
isAdult                          0
startYear                     1998
endYear                         \N
runtimeMinutes                  \N
genres                      Sci-Fi
Name: 2000320, dtype: object

(9,)

tconst                  tt11816672
titleType                tvEpisode
primaryTitle       Spring Cleaning
originalTitle      Spring Cleaning
isAdult                          0
startYear                     1980
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2000321, dtype: object

(9,)

tconst                      tt11816674
titleType                    tvEpisode
primaryTitle      Lääkäri ilman rajoja
originalTitle     Lääkäri ilman rajoja
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      \N
genres                              \N
Name: 2000322, dtype: object

(9,)

tconst                               tt11816676
titleType                             tvEpisode
primaryTitle      Episode dated 11 January 1954
originalTitle     Episode dated 11 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2000323, dtype: object

(9,)

tconst                                                   tt11816678
titleType                                                 tvEpisode
primaryTitle      Murhia, tappouhkauksia ja pommeja- viime viikk...
originalTitle     Murhia, tappouhkauksia ja pommeja- viime viikk...
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000324, dtype: object

(9,)

tconst                  tt1181667
titleType               tvEpisode
primaryTitle      Episode #1.9599
originalTitle     Episode #1.9599
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2000325, dtype: object

(9,)

tconst                  tt11816680
titleType                tvEpisode
primaryTitle               Land Ho
originalTitle              Land Ho
isAdult                          0
startYear                     1980
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2000326, dtype: object

(9,)

tconst                                                   tt11816682
titleType                                                 tvEpisode
primaryTitle      Kuolema on yksi viimeisimmistä salaisuuksista,...
originalTitle     Kuolema on yksi viimeisimmistä salaisuuksista,...
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000327, dtype: object

(9,)

tconst                                      tt11816684
titleType                                    tvEpisode
primaryTitle      The House That Robin and Rosie Built
originalTitle     The House That Robin and Rosie Built
isAdult                                              0
startYear                                         1980
endYear                                             \N
runtimeMinutes                                      \N
genres                                Animation,Family
Name: 2000328, dtype: object

(9,)

tconst                                         tt11816686
titleType                                       tvEpisode
primaryTitle      Lyömisen syy on lyöjän korvien välissä.
originalTitle     Lyömisen syy on lyöjän korvien välissä.
isAdult                                                 0
startYear                                            1999
endYear                                                \N
runtimeMinutes                                         \N
genres                                                 \N
Name: 2000329, dtype: object

(9,)

tconst                                                tt11816688
titleType                                              tvEpisode
primaryTitle      Soldaty. Zdravstvuy rota, Novyy god! Special 1
originalTitle     Soldaty. Zdravstvuy rota, Novyy god! Special 1
isAdult                                                        0
startYear                                                   2004
endYear                                                       \N
runtimeMinutes                                                54
genres                                        Comedy,Crime,Drama
Name: 2000330, dtype: object

(9,)

tconst                              tt1181668
titleType                           tvEpisode
primaryTitle      Una luz al final del camino
originalTitle     Una luz al final del camino
isAdult                                     0
startYear                                2006
endYear                                    \N
runtimeMinutes                             \N
genres                 Adventure,Drama,Family
Name: 2000331, dtype: object

(9,)

tconst                                                tt11816690
titleType                                              tvEpisode
primaryTitle      Soldaty. Zdravstvuy rota, Novyy god! Special 2
originalTitle     Soldaty. Zdravstvuy rota, Novyy god! Special 2
isAdult                                                        0
startYear                                                   2004
endYear                                                       \N
runtimeMinutes                                                54
genres                                        Comedy,Crime,Drama
Name: 2000332, dtype: object

(9,)

tconst                                                   tt11816692
titleType                                                 tvEpisode
primaryTitle      Yhdessä vuosisadassa Suomi on kokenut järisytt...
originalTitle     Yhdessä vuosisadassa Suomi on kokenut järisytt...
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000333, dtype: object

(9,)

tconst                                                   tt11816694
titleType                                                 tvEpisode
primaryTitle      Anarkistimummoja, äitejä ja tyttäriä - ajatuks...
originalTitle     Anarkistimummoja, äitejä ja tyttäriä - ajatuks...
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000334, dtype: object

(9,)

tconst                tt1181669
titleType             tvEpisode
primaryTitle      Hal's TV Date
originalTitle     Hal's TV Date
isAdult                       0
startYear                  1959
endYear                      \N
runtimeMinutes               26
genres                   Comedy
Name: 2000335, dtype: object

(9,)

tconst                    tt1181670
titleType                 tvEpisode
primaryTitle      Lancer, Come Home
originalTitle     Lancer, Come Home
isAdult                           0
startYear                      1959
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2000336, dtype: object

(9,)

tconst            tt1181671
titleType         tvEpisode
primaryTitle       Moon Man
originalTitle      Moon Man
isAdult                   0
startYear              1959
endYear                  \N
runtimeMinutes           25
genres               Comedy
Name: 2000337, dtype: object

(9,)

tconst                      tt11816722
titleType                        short
primaryTitle       Maltese Translation
originalTitle      Maltese Translation
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      24
genres            Comedy,Romance,Short
Name: 2000338, dtype: object

(9,)

tconst                                                   tt11816728
titleType                                                 tvEpisode
primaryTitle      Onko Venäjästä tullut varkaiden paratiisi, jos...
originalTitle     Onko Venäjästä tullut varkaiden paratiisi, jos...
isAdult                                                           0
startYear                                                      1999
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2000339, dtype: object

(9,)

tconst                 tt1181672
titleType              tvEpisode
primaryTitle      Teacher's Pest
originalTitle     Teacher's Pest
isAdult                        0
startYear                   1959
endYear                       \N
runtimeMinutes                25
genres                    Comedy
Name: 2000340, dtype: object

(9,)

tconst                    tt11816730
titleType                  tvEpisode
primaryTitle            Episode #4.2
originalTitle           Episode #4.2
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000341, dtype: object

(9,)

tconst                   tt11816732
titleType                 tvEpisode
primaryTitle      Grumpy Neighbours
originalTitle     Grumpy Neighbours
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres             Animation,Family
Name: 2000342, dtype: object

(9,)

tconst                    tt11816734
titleType                  tvEpisode
primaryTitle            Episode #4.5
originalTitle           Episode #4.5
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000343, dtype: object

(9,)

tconst                    tt11816736
titleType                  tvEpisode
primaryTitle            Episode #4.4
originalTitle           Episode #4.4
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000344, dtype: object

(9,)

tconst                    tt11816738
titleType                  tvEpisode
primaryTitle            Episode #4.3
originalTitle           Episode #4.3
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000345, dtype: object

(9,)

tconst               tt1181673
titleType            tvEpisode
primaryTitle      Family Owned
originalTitle     Family Owned
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2000346, dtype: object

(9,)

tconst                    tt11816740
titleType                  tvEpisode
primaryTitle            Episode #4.6
originalTitle           Episode #4.6
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000347, dtype: object

(9,)

tconst                    tt11816742
titleType                  tvEpisode
primaryTitle            Episode #4.7
originalTitle           Episode #4.7
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000348, dtype: object

(9,)

tconst                    tt11816744
titleType                  tvEpisode
primaryTitle            Episode #4.8
originalTitle           Episode #4.8
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000349, dtype: object

(9,)

tconst                    tt11816748
titleType                  tvEpisode
primaryTitle           Episode #4.11
originalTitle          Episode #4.11
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000350, dtype: object

(9,)

tconst               tt1181674
titleType            tvEpisode
primaryTitle      Local Flavor
originalTitle     Local Flavor
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2000351, dtype: object

(9,)

tconst                    tt11816750
titleType                  tvEpisode
primaryTitle           Episode #4.12
originalTitle          Episode #4.12
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000352, dtype: object

(9,)

tconst                  tt11816752
titleType                tvEpisode
primaryTitle      Luopumisen aikaa
originalTitle     Luopumisen aikaa
isAdult                          0
startYear                     1999
endYear                         \N
runtimeMinutes                  \N
genres                          \N
Name: 2000353, dtype: object

(9,)

tconst                    tt11816754
titleType                  tvEpisode
primaryTitle           Episode #4.10
originalTitle          Episode #4.10
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000354, dtype: object

(9,)

tconst                    tt11816756
titleType                  tvEpisode
primaryTitle            Episode #4.9
originalTitle           Episode #4.9
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000355, dtype: object

(9,)

tconst                    tt11816758
titleType                  tvEpisode
primaryTitle           Episode #4.13
originalTitle          Episode #4.13
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000356, dtype: object

(9,)

tconst                tt1181675
titleType             tvEpisode
primaryTitle      One of a Kind
originalTitle     One of a Kind
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2000357, dtype: object

(9,)

tconst                    tt11816760
titleType                  tvEpisode
primaryTitle           Episode #4.14
originalTitle          Episode #4.14
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000358, dtype: object

(9,)

tconst                    tt11816762
titleType                  tvEpisode
primaryTitle           Episode #4.15
originalTitle          Episode #4.15
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000359, dtype: object

(9,)

tconst                    tt11816764
titleType                  tvEpisode
primaryTitle           Episode #4.17
originalTitle          Episode #4.17
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000360, dtype: object

(9,)

tconst                    tt11816766
titleType                  tvEpisode
primaryTitle           Episode #4.16
originalTitle          Episode #4.16
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000361, dtype: object

(9,)

tconst                    tt11816768
titleType                  tvEpisode
primaryTitle           Episode #4.18
originalTitle          Episode #4.18
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000362, dtype: object

(9,)

tconst             tt1181676
titleType          tvEpisode
primaryTitle       Open 24/7
originalTitle      Open 24/7
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000363, dtype: object

(9,)

tconst                    tt11816770
titleType                  tvEpisode
primaryTitle           Episode #4.19
originalTitle          Episode #4.19
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000364, dtype: object

(9,)

tconst              tt11816772
titleType                short
primaryTitle          The Hike
originalTitle         The Hike
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes               8
genres            Comedy,Short
Name: 2000365, dtype: object

(9,)

tconst                       tt11816774
titleType                     tvEpisode
primaryTitle      One Small Step for Jo
originalTitle     One Small Step for Jo
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                 Animation,Family
Name: 2000366, dtype: object

(9,)

tconst            tt11816776
titleType          tvEpisode
primaryTitle       Editia 14
originalTitle      Editia 14
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000367, dtype: object

(9,)

tconst            tt11816778
titleType          tvEpisode
primaryTitle          Gala 5
originalTitle         Gala 5
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000368, dtype: object

(9,)

tconst                tt1181677
titleType             tvEpisode
primaryTitle      Real Deal BBQ
originalTitle     Real Deal BBQ
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2000369, dtype: object

(9,)

tconst            tt11816780
titleType          tvEpisode
primaryTitle       Editia 15
originalTitle      Editia 15
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000370, dtype: object

(9,)

tconst            tt11816782
titleType          tvEpisode
primaryTitle       Editia 13
originalTitle      Editia 13
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000371, dtype: object

(9,)

tconst                  tt11816784
titleType                    movie
primaryTitle      Kingdom of Souls
originalTitle     Kingdom of Souls
isAdult                          0
startYear                       \N
endYear                         \N
runtimeMinutes                  \N
genres                     Fantasy
Name: 2000372, dtype: object

(9,)

tconst                                                   tt11816786
titleType                                                 tvEpisode
primaryTitle      The Kevin & Nikee Show - Coby Jackk - Stand-up...
originalTitle     The Kevin & Nikee Show - Coby Jackk - Stand-up...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2000373, dtype: object

(9,)

tconst                       tt11816788
titleType                     tvEpisode
primaryTitle      The Princess Rulebook
originalTitle     The Princess Rulebook
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                 Animation,Family
Name: 2000374, dtype: object

(9,)

tconst             tt1181678
titleType          tvEpisode
primaryTitle        Route 66
originalTitle       Route 66
isAdult                    0
startYear               2007
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000375, dtype: object

(9,)

tconst               tt11816792
titleType              tvSeries
primaryTitle      A Roupa Ideal
originalTitle     A Roupa Ideal
isAdult                       0
startYear                  2018
endYear                    2018
runtimeMinutes               \N
genres               Reality-TV
Name: 2000376, dtype: object

(9,)

tconst                  tt11816794
titleType                tvEpisode
primaryTitle        Tian's Pencils
originalTitle       Tian's Pencils
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2000377, dtype: object

(9,)

tconst                     tt11816798
titleType                   tvEpisode
primaryTitle           Another Chance
originalTitle          Another Chance
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     26
genres            Crime,Drama,Romance
Name: 2000378, dtype: object

(9,)

tconst               tt1181679
titleType            tvEpisode
primaryTitle      Seaside Eats
originalTitle     Seaside Eats
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2000379, dtype: object

(9,)

tconst                       tt11816800
titleType                     tvEpisode
primaryTitle      Little Birdie Caw Caw
originalTitle     Little Birdie Caw Caw
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                 Animation,Family
Name: 2000380, dtype: object

(9,)

tconst                    tt11816802
titleType                  tvEpisode
primaryTitle               Special 1
originalTitle              Special 1
isAdult                            0
startYear                       2004
endYear                           \N
runtimeMinutes                    51
genres            Comedy,Crime,Drama
Name: 2000381, dtype: object

(9,)

tconst                    tt11816804
titleType                  tvEpisode
primaryTitle               Special 2
originalTitle              Special 2
isAdult                            0
startYear                       2004
endYear                           \N
runtimeMinutes                    51
genres            Comedy,Crime,Drama
Name: 2000382, dtype: object

(9,)

tconst                             tt11816806
titleType                           tvEpisode
primaryTitle      John Kani: Art and activism
originalTitle     John Kani: Art and activism
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2000383, dtype: object

(9,)

tconst                  tt11816808
titleType                tvEpisode
primaryTitle          Noisy Babies
originalTitle         Noisy Babies
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2000384, dtype: object

(9,)

tconst                 tt1181680
titleType              tvEpisode
primaryTitle      Talkin' Turkey
originalTitle     Talkin' Turkey
isAdult                        0
startYear                   2007
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2000385, dtype: object

(9,)

tconst                      tt11816810
titleType                        short
primaryTitle                 Attention
originalTitle                Attention
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                       4
genres            Drama,Short,Thriller
Name: 2000386, dtype: object

(9,)

tconst                                                   tt11816812
titleType                                                 tvEpisode
primaryTitle      HWWS Special: SyFy Bartow's Harry Potter Sorti...
originalTitle     HWWS Special: SyFy Bartow's Harry Potter Sorti...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2000387, dtype: object

(9,)

tconst              tt11816814
titleType         tvMiniSeries
primaryTitle        Painkiller
originalTitle       Painkiller
isAdult                      0
startYear                 2022
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2000388, dtype: object

(9,)

tconst                                tt11816816
titleType                              tvEpisode
primaryTitle      Episode dated 21 December 2001
originalTitle     Episode dated 21 December 2001
isAdult                                        0
startYear                                   2001
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2000389, dtype: object

(9,)

tconst                    tt11816818
titleType                  tvEpisode
primaryTitle            Episode #5.4
originalTitle           Episode #5.4
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000390, dtype: object

(9,)

tconst                tt1181681
titleType             tvEpisode
primaryTitle      Totally Fried
originalTitle     Totally Fried
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2000391, dtype: object

(9,)

tconst                    tt11816820
titleType                  tvEpisode
primaryTitle            Episode #5.3
originalTitle           Episode #5.3
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000392, dtype: object

(9,)

tconst                    tt11816822
titleType                  tvEpisode
primaryTitle            Episode #5.5
originalTitle           Episode #5.5
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000393, dtype: object

(9,)

tconst                    tt11816824
titleType                  tvEpisode
primaryTitle            Episode #5.8
originalTitle           Episode #5.8
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000394, dtype: object

(9,)

tconst                    tt11816826
titleType                  tvEpisode
primaryTitle            Episode #5.6
originalTitle           Episode #5.6
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000395, dtype: object

(9,)

tconst                    tt11816828
titleType                  tvEpisode
primaryTitle            Episode #5.9
originalTitle           Episode #5.9
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000396, dtype: object

(9,)

tconst                  tt1181682
titleType               tvEpisode
primaryTitle      Viewer's Choice
originalTitle     Viewer's Choice
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                 Reality-TV
Name: 2000397, dtype: object

(9,)

tconst                    tt11816830
titleType                  tvEpisode
primaryTitle           Episode #5.11
originalTitle          Episode #5.11
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000398, dtype: object

(9,)

tconst                    tt11816832
titleType                  tvEpisode
primaryTitle            Episode #5.7
originalTitle           Episode #5.7
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000399, dtype: object

(9,)

tconst                    tt11816834
titleType                  tvEpisode
primaryTitle           Episode #5.10
originalTitle          Episode #5.10
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000400, dtype: object

(9,)

tconst                    tt11816836
titleType                  tvEpisode
primaryTitle           Episode #5.12
originalTitle          Episode #5.12
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000401, dtype: object

(9,)

tconst                 tt11816838
titleType                tvSeries
primaryTitle      Les 30 ans d'M6
originalTitle     Les 30 ans d'M6
isAdult                         0
startYear                    2017
endYear                      2017
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2000402, dtype: object

(9,)

tconst                             tt1181683
titleType                          tvEpisode
primaryTitle      L'espoir au compte-gouttes
originalTitle     L'espoir au compte-gouttes
isAdult                                    0
startYear                               1999
endYear                                   \N
runtimeMinutes                            \N
genres                                 Drama
Name: 2000403, dtype: object

(9,)

tconst                    tt11816840
titleType                  tvEpisode
primaryTitle           Episode #5.13
originalTitle          Episode #5.13
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000404, dtype: object

(9,)

tconst                    tt11816842
titleType                  tvEpisode
primaryTitle           Episode #5.15
originalTitle          Episode #5.15
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000405, dtype: object

(9,)

tconst                    tt11816844
titleType                  tvEpisode
primaryTitle           Episode #5.14
originalTitle          Episode #5.14
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000406, dtype: object

(9,)

tconst                    tt11816846
titleType                  tvEpisode
primaryTitle           Episode #5.16
originalTitle          Episode #5.16
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000407, dtype: object

(9,)

tconst                    tt11816848
titleType                  tvEpisode
primaryTitle           Episode #5.17
originalTitle          Episode #5.17
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000408, dtype: object

(9,)

tconst               tt1181684
titleType            tvEpisode
primaryTitle      Jack the Lad
originalTitle     Jack the Lad
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2000409, dtype: object

(9,)

tconst                    tt11816850
titleType                  tvEpisode
primaryTitle           Episode #5.18
originalTitle          Episode #5.18
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000410, dtype: object

(9,)

tconst                    tt11816852
titleType                  tvEpisode
primaryTitle           Episode #5.19
originalTitle          Episode #5.19
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000411, dtype: object

(9,)

tconst                                                   tt11816854
titleType                                                   tvMovie
primaryTitle      Electronic Dance Music - A Top Export from Ger...
originalTitle     Electronic Dance Music - A Top Export from Ger...
isAdult                                                           0
startYear                                                      2017
endYear                                                          \N
runtimeMinutes                                                   42
genres                                  Biography,Documentary,Music
Name: 2000412, dtype: object

(9,)

tconst              tt11816856
titleType             tvSeries
primaryTitle      Now Go Build
originalTitle     Now Go Build
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000413, dtype: object

(9,)

tconst                                tt11816858
titleType                              tvEpisode
primaryTitle      Role Models: Dress for Success
originalTitle     Role Models: Dress for Success
isAdult                                        1
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2000414, dtype: object

(9,)

tconst                   tt1181685
titleType                tvEpisode
primaryTitle         Trip or Treat
originalTitle        Trip or Treat
isAdult                          0
startYear                     1999
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Comedy
Name: 2000415, dtype: object

(9,)

tconst                    tt11816860
titleType                  tvEpisode
primaryTitle            Episode #6.2
originalTitle           Episode #6.2
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000416, dtype: object

(9,)

tconst                    tt11816862
titleType                  tvEpisode
primaryTitle            Episode #6.3
originalTitle           Episode #6.3
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000417, dtype: object

(9,)

tconst                    tt11816864
titleType                  tvEpisode
primaryTitle            Episode #6.4
originalTitle           Episode #6.4
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000418, dtype: object

(9,)

tconst                    tt11816866
titleType                  tvEpisode
primaryTitle            Episode #6.5
originalTitle           Episode #6.5
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000419, dtype: object

(9,)

tconst                    tt11816868
titleType                  tvEpisode
primaryTitle            Episode #6.6
originalTitle           Episode #6.6
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000420, dtype: object

(9,)

tconst            tt1181686
titleType         tvEpisode
primaryTitle          Pilot
originalTitle         Pilot
isAdult                   0
startYear              1983
endYear                  \N
runtimeMinutes           \N
genres            Talk-Show
Name: 2000421, dtype: object

(9,)

tconst                    tt11816870
titleType                  tvEpisode
primaryTitle            Episode #6.7
originalTitle           Episode #6.7
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000422, dtype: object

(9,)

tconst                    tt11816872
titleType                  tvEpisode
primaryTitle            Episode #6.8
originalTitle           Episode #6.8
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000423, dtype: object

(9,)

tconst                    tt11816874
titleType                  tvEpisode
primaryTitle            Episode #6.9
originalTitle           Episode #6.9
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000424, dtype: object

(9,)

tconst                    tt11816876
titleType                  tvEpisode
primaryTitle           Episode #6.10
originalTitle          Episode #6.10
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000425, dtype: object

(9,)

tconst                    tt11816878
titleType                  tvEpisode
primaryTitle           Episode #6.11
originalTitle          Episode #6.11
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000426, dtype: object

(9,)

tconst                                tt1181687
titleType                             tvEpisode
primaryTitle      Episode dated 30 January 2008
originalTitle     Episode dated 30 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                    Biography,Family,News
Name: 2000427, dtype: object

(9,)

tconst                    tt11816880
titleType                  tvEpisode
primaryTitle           Episode #6.12
originalTitle          Episode #6.12
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000428, dtype: object

(9,)

tconst                    tt11816882
titleType                  tvEpisode
primaryTitle           Episode #6.15
originalTitle          Episode #6.15
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000429, dtype: object

(9,)

tconst                    tt11816884
titleType                  tvEpisode
primaryTitle           Episode #6.14
originalTitle          Episode #6.14
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000430, dtype: object

(9,)

tconst                    tt11816886
titleType                  tvEpisode
primaryTitle           Episode #6.13
originalTitle          Episode #6.13
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000431, dtype: object

(9,)

tconst                    tt11816888
titleType                  tvEpisode
primaryTitle           Episode #6.16
originalTitle          Episode #6.16
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000432, dtype: object

(9,)

tconst                      tt1181688
titleType                    tvSeries
primaryTitle      Even Further Abroad
originalTitle     Even Further Abroad
isAdult                             0
startYear                        1997
endYear                          1999
runtimeMinutes                     28
genres                    Documentary
Name: 2000433, dtype: object

(9,)

tconst                     tt11816890
titleType                   tvEpisode
primaryTitle             Umamin ka na
originalTitle            Umamin ka na
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     25
genres            Crime,Drama,Romance
Name: 2000434, dtype: object

(9,)

tconst                                       tt11816892
titleType                                         movie
primaryTitle      Ishq e Qalandar (The beautiful Sindh)
originalTitle     Ishq e Qalandar (The beautiful Sindh)
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                      107
genres                                      Documentary
Name: 2000435, dtype: object

(9,)

tconst             tt11816894
titleType             tvMovie
primaryTitle         Nguoi Me
originalTitle        Nguoi Me
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             45
genres            Documentary
Name: 2000436, dtype: object

(9,)

tconst             tt11816896
titleType               short
primaryTitle       Nova Blanc
originalTitle      Nova Blanc
isAdult                     0
startYear                2016
endYear                    \N
runtimeMinutes              5
genres            Drama,Short
Name: 2000437, dtype: object

(9,)

tconst                   tt11816898
titleType                     movie
primaryTitle      Svetlana och Kurt
originalTitle     Svetlana och Kurt
isAdult                           0
startYear                      2013
endYear                          \N
runtimeMinutes                   58
genres                  Documentary
Name: 2000438, dtype: object

(9,)

tconst                   tt1181689
titleType                tvEpisode
primaryTitle        The 318th Bomb
originalTitle       The 318th Bomb
isAdult                          0
startYear                     1962
endYear                         \N
runtimeMinutes                  \N
genres            Documentary,News
Name: 2000439, dtype: object

(9,)

tconst              tt11816900
titleType                movie
primaryTitle      Bitter Sweet
originalTitle     Bitter Sweet
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2000440, dtype: object

(9,)

tconst               tt11816902
titleType             tvEpisode
primaryTitle      Wolfgang Puck
originalTitle     Wolfgang Puck
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2000441, dtype: object

(9,)

tconst              tt11816904
titleType            tvEpisode
primaryTitle      Border Grill
originalTitle     Border Grill
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000442, dtype: object

(9,)

tconst             tt11816906
titleType           tvEpisode
primaryTitle      Best Friend
originalTitle     Best Friend
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2000443, dtype: object

(9,)

tconst                  tt11816908
titleType                tvEpisode
primaryTitle      Pasta a la Raimi
originalTitle     Pasta a la Raimi
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                 Documentary
Name: 2000444, dtype: object

(9,)

tconst                        tt1181690
titleType                     tvEpisode
primaryTitle      Computers to Catwalks
originalTitle     Computers to Catwalks
isAdult                               0
startYear                          2005
endYear                              \N
runtimeMinutes                       \N
genres                       Reality-TV
Name: 2000445, dtype: object

(9,)

tconst                                 tt11816910
titleType                               tvEpisode
primaryTitle      Episode dated 30 September 1970
originalTitle     Episode dated 30 September 1970
isAdult                                         0
startYear                                    1970
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2000446, dtype: object

(9,)

tconst               tt11816912
titleType             tvEpisode
primaryTitle      Wexler's Deli
originalTitle     Wexler's Deli
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2000447, dtype: object

(9,)

tconst                   tt11816914
titleType                 tvEpisode
primaryTitle      Lovers' Last Time
originalTitle     Lovers' Last Time
isAdult                           1
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2000448, dtype: object

(9,)

tconst                                    tt11816916
titleType                                  tvEpisode
primaryTitle      Extra Helpings with Candace Nelson
originalTitle     Extra Helpings with Candace Nelson
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                   Documentary
Name: 2000449, dtype: object

(9,)

tconst                        tt11816918
titleType                       tvSeries
primaryTitle      Certains l'aiment show
originalTitle     Certains l'aiment show
isAdult                                0
startYear                           2010
endYear                             2011
runtimeMinutes                        \N
genres                            Comedy
Name: 2000450, dtype: object

(9,)

tconst                          tt1181691
titleType                       tvEpisode
primaryTitle      Green Thumb to Glue Gun
originalTitle     Green Thumb to Glue Gun
isAdult                                 0
startYear                            2005
endYear                                \N
runtimeMinutes                         \N
genres                         Reality-TV
Name: 2000451, dtype: object

(9,)

tconst            tt11816920
titleType          tvEpisode
primaryTitle       Balatkayo
originalTitle      Balatkayo
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            25
genres                 Drama
Name: 2000452, dtype: object

(9,)

tconst                               tt11816922
titleType                             tvEpisode
primaryTitle      Episode dated 14 January 1954
originalTitle     Episode dated 14 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                    Drama
Name: 2000453, dtype: object

(9,)

tconst                                                tt11816924
titleType                                                  video
primaryTitle      Amrit Maan Feat. Gurlej Akhtar: Subaah Jatt Da
originalTitle     Amrit Maan Feat. Gurlej Akhtar: Subaah Jatt Da
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                 4
genres                                               Music,Short
Name: 2000454, dtype: object

(9,)

tconst               tt11816926
titleType                 movie
primaryTitle             Portal
originalTitle            Portal
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres            Horror,Sci-Fi
Name: 2000455, dtype: object

(9,)

tconst              tt11816928
titleType                short
primaryTitle       Washed Away
originalTitle      Washed Away
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              17
genres            Horror,Short
Name: 2000456, dtype: object

(9,)

tconst                     tt1181692
titleType                   tvSeries
primaryTitle      For Amusement Only
originalTitle     For Amusement Only
isAdult                            0
startYear                       1968
endYear                           \N
runtimeMinutes                    60
genres                        Comedy
Name: 2000457, dtype: object

(9,)

tconst                         tt11816930
titleType                       tvEpisode
primaryTitle                 Fuel Trouble
originalTitle                Fuel Trouble
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres            Crime,Documentary,Drama
Name: 2000458, dtype: object

(9,)

tconst                                           tt11816932
titleType                                         tvEpisode
primaryTitle      2013/14 Group Stage: Chelsea vs. FC Basel
originalTitle     2013/14 Group Stage: Chelsea vs. FC Basel
isAdult                                                   0
startYear                                              2013
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Sport
Name: 2000459, dtype: object

(9,)

tconst             tt11816934
titleType               short
primaryTitle         Showdown
originalTitle        Showdown
isAdult                     0
startYear                2004
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2000460, dtype: object

(9,)

tconst                    tt11816936
titleType                      short
primaryTitle      Encounter with Joe
originalTitle     Encounter with Joe
isAdult                            0
startYear                       2022
endYear                           \N
runtimeMinutes                    \N
genres                         Short
Name: 2000461, dtype: object

(9,)

tconst                         tt11816938
titleType                       tvEpisode
primaryTitle                 Design Flaws
originalTitle                Design Flaws
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres            Crime,Documentary,Drama
Name: 2000462, dtype: object

(9,)

tconst               tt1181693
titleType            tvEpisode
primaryTitle           Fernweh
originalTitle          Fernweh
isAdult                      0
startYear                 1989
endYear                     \N
runtimeMinutes              52
genres            Drama,Family
Name: 2000463, dtype: object

(9,)

tconst               tt11816940
titleType             tvEpisode
primaryTitle       Episode #1.1
originalTitle      Episode #1.1
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               42
genres            Drama,Romance
Name: 2000464, dtype: object

(9,)

tconst               tt11816942
titleType             tvEpisode
primaryTitle      Episode #2.34
originalTitle     Episode #2.34
isAdult                       0
startYear                  1989
endYear                      \N
runtimeMinutes               \N
genres               Crime,News
Name: 2000465, dtype: object

(9,)

tconst                               tt11816946
titleType                                 short
primaryTitle      Oh Humsafar Hariket Acoustics
originalTitle     Oh Humsafar Hariket Acoustics
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                                6
genres                              Music,Short
Name: 2000466, dtype: object

(9,)

tconst                           tt11816948
titleType                         tvEpisode
primaryTitle      Still Mommy's Little Girl
originalTitle     Still Mommy's Little Girl
isAdult                                   1
startYear                              2020
endYear                                  \N
runtimeMinutes                           39
genres                                Adult
Name: 2000467, dtype: object

(9,)

tconst                 tt1181694
titleType               tvSeries
primaryTitle      Further Abroad
originalTitle     Further Abroad
isAdult                        0
startYear                   1994
endYear                       \N
runtimeMinutes                29
genres               Documentary
Name: 2000468, dtype: object

(9,)

tconst                 tt11816950
titleType                   video
primaryTitle      Muslim: My Lady
originalTitle     Muslim: My Lady
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                  4
genres                Music,Short
Name: 2000469, dtype: object

(9,)

tconst                                 tt11816952
titleType                               tvEpisode
primaryTitle      Episode dated 15 September 2014
originalTitle     Episode dated 15 September 2014
isAdult                                         0
startYear                                    2014
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2000470, dtype: object

(9,)

tconst               tt11816954
titleType             tvEpisode
primaryTitle      Episode #1.49
originalTitle     Episode #1.49
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2000471, dtype: object

(9,)

tconst                                 tt11816956
titleType                               tvEpisode
primaryTitle      Episode dated 26 September 2014
originalTitle     Episode dated 26 September 2014
isAdult                                         0
startYear                                    2014
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2000472, dtype: object

(9,)

tconst                                 tt11816958
titleType                               tvEpisode
primaryTitle      Episode dated 29 September 2014
originalTitle     Episode dated 29 September 2014
isAdult                                         0
startYear                                    2014
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2000473, dtype: object

(9,)

tconst                      tt1181695
titleType                   tvEpisode
primaryTitle         Episode #1.11484
originalTitle        Episode #1.11484
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2000474, dtype: object

(9,)

tconst                              tt11816960
titleType                            tvEpisode
primaryTitle      Episode dated 3 October 2014
originalTitle     Episode dated 3 October 2014
isAdult                                      0
startYear                                 2014
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2000475, dtype: object

(9,)

tconst                               tt11816962
titleType                             tvEpisode
primaryTitle      Episode dated 10 October 2014
originalTitle     Episode dated 10 October 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2000476, dtype: object

(9,)

tconst                           tt11816964
titleType                             movie
primaryTitle      Svetlana and Kurt forever
originalTitle     Svetlana and Kurt forever
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                           58
genres                          Documentary
Name: 2000477, dtype: object

(9,)

tconst               tt11816966
titleType             tvEpisode
primaryTitle      Episode #1.50
originalTitle     Episode #1.50
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2000478, dtype: object

(9,)

tconst                tt11816968
titleType           tvMiniSeries
primaryTitle      Magische Anden
originalTitle     Magische Anden
isAdult                        0
startYear                   2019
endYear                     2019
runtimeMinutes                \N
genres               Documentary
Name: 2000479, dtype: object

(9,)

tconst                   tt1181696
titleType                tvEpisode
primaryTitle          Episode #6.1
originalTitle         Episode #6.1
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2000480, dtype: object

(9,)

tconst                                                   tt11816970
titleType                                                     video
primaryTitle      Natti Natasha & Nicky Jam & Manuel Turizo & My...
originalTitle     Natti Natasha & Nicky Jam & Manuel Turizo & My...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    5
genres                                                  Music,Short
Name: 2000481, dtype: object

(9,)

tconst                 tt11816972
titleType               tvEpisode
primaryTitle      Episode #1.5395
originalTitle     Episode #1.5395
isAdult                         0
startYear                    1989
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2000482, dtype: object

(9,)

tconst                                                   tt11816974
titleType                                                 tvEpisode
primaryTitle      The First Console to EVER use Cartridges! The ...
originalTitle     The First Console to EVER use Cartridges! The ...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                    8
genres                                             Comedy,Talk-Show
Name: 2000483, dtype: object

(9,)

tconst                                 tt11816976
titleType                               tvEpisode
primaryTitle                         Episode #1.6
originalTitle                        Episode #1.6
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 59
genres            Adventure,Documentary,Game-Show
Name: 2000484, dtype: object

(9,)

tconst             tt11816978
titleType               short
primaryTitle       Aquaphobia
originalTitle      Vannskrekk
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             12
genres            Drama,Short
Name: 2000485, dtype: object

(9,)

tconst                     tt1181697
titleType                  tvEpisode
primaryTitle                Al dente
originalTitle               Al dente
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    48
genres            Comedy,Crime,Drama
Name: 2000486, dtype: object

(9,)

tconst                       tt11816980
titleType                     tvEpisode
primaryTitle      Ecuador und Kolumbien
originalTitle     Ecuador und Kolumbien
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       44
genres                      Documentary
Name: 2000487, dtype: object

(9,)

tconst                tt11816982
titleType               tvSeries
primaryTitle      Nostima & apla
originalTitle     Nostima & apla
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                25
genres                        \N
Name: 2000488, dtype: object

(9,)

tconst             tt11816984
titleType           tvEpisode
primaryTitle             Peru
originalTitle            Peru
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             44
genres            Documentary
Name: 2000489, dtype: object

(9,)

tconst             tt11816986
titleType           tvEpisode
primaryTitle         Bolivien
originalTitle        Bolivien
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             44
genres            Documentary
Name: 2000490, dtype: object

(9,)

tconst                           tt11816988
titleType                             movie
primaryTitle      Kenderaan Berat Ikut Kiri
originalTitle     Kenderaan Berat Ikut Kiri
isAdult                                   0
startYear                              2021
endYear                                  \N
runtimeMinutes                           99
genres                               Comedy
Name: 2000491, dtype: object

(9,)

tconst                             tt1181698
titleType                          tvEpisode
primaryTitle      Schatten der Vergangenheit
originalTitle     Schatten der Vergangenheit
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            48
genres                    Comedy,Crime,Drama
Name: 2000492, dtype: object

(9,)

tconst                                    tt11816990
titleType                                  tvEpisode
primaryTitle      Argentinien und Chile - Der Norden
originalTitle     Argentinien und Chile - Der Norden
isAdult                                            0
startYear                                       2019
endYear                                           \N
runtimeMinutes                                    44
genres                                   Documentary
Name: 2000493, dtype: object

(9,)

tconst                                   tt11816992
titleType                                 tvEpisode
primaryTitle      Argentinien und Chile - Der Süden
originalTitle     Argentinien und Chile - Der Süden
isAdult                                           0
startYear                                      2019
endYear                                          \N
runtimeMinutes                                   44
genres                                  Documentary
Name: 2000494, dtype: object

(9,)

tconst                   tt11816994
titleType                 tvEpisode
primaryTitle      Muling pagbabalik
originalTitle     Muling pagbabalik
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   29
genres                        Drama
Name: 2000495, dtype: object

(9,)

tconst              tt11816996
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000496, dtype: object

(9,)

tconst                 tt11816998
titleType               tvEpisode
primaryTitle      Auf Wiedersehen
originalTitle     Auf Wiedersehen
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2000497, dtype: object

(9,)

tconst                    tt1181699
titleType                 tvEpisode
primaryTitle      Imperio de carton
originalTitle     Imperio de carton
isAdult                           0
startYear                      1994
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2000498, dtype: object

(9,)

tconst                     tt11817000
titleType                       video
primaryTitle      Sofia Reyes: Idiota
originalTitle     Sofia Reyes: Idiota
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                      4
genres                    Music,Short
Name: 2000499, dtype: object

(9,)

tconst                     tt11817002
titleType                   tvEpisode
primaryTitle      Gong Yu Chu Zu Pt.2
originalTitle     Gong Yu Chu Zu Pt.2
isAdult                             0
startYear                        2010
endYear                            \N
runtimeMinutes                     11
genres                         Comedy
Name: 2000500, dtype: object

(9,)

tconst                                              tt11817004
titleType                                                movie
primaryTitle      Master of the White Crane Fist: Wong Yam-Lam
originalTitle     Master of the White Crane Fist: Wong Yam-Lam
isAdult                                                      0
startYear                                                 2019
endYear                                                     \N
runtimeMinutes                                              90
genres                                                  Action
Name: 2000501, dtype: object

(9,)

tconst                tt11817006
titleType           tvMiniSeries
primaryTitle      Der Kurz-Krimi
originalTitle     Der Kurz-Krimi
isAdult                        0
startYear                   1963
endYear                     1963
runtimeMinutes                 2
genres              Comedy,Crime
Name: 2000502, dtype: object

(9,)

tconst              tt11817008
titleType             tvSeries
primaryTitle      High Tension
originalTitle     High Tension
isAdult                      0
startYear                 1953
endYear                   1954
runtimeMinutes              30
genres                   Drama
Name: 2000503, dtype: object

(9,)

tconst                                    tt1181700
titleType                                 tvEpisode
primaryTitle      Los más codiciados... Los casados
originalTitle     Los más codiciados... Los casados
isAdult                                           0
startYear                                      1994
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Comedy
Name: 2000504, dtype: object

(9,)

tconst              tt11817010
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000505, dtype: object

(9,)

tconst              tt11817012
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000506, dtype: object

(9,)

tconst              tt11817014
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000507, dtype: object

(9,)

tconst              tt11817016
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000508, dtype: object

(9,)

tconst              tt11817018
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000509, dtype: object

(9,)

tconst                     tt1181701
titleType                  tvEpisode
primaryTitle      More Room for Baby
originalTitle     More Room for Baby
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres                    Reality-TV
Name: 2000510, dtype: object

(9,)

tconst              tt11817020
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000511, dtype: object

(9,)

tconst               tt11817022
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000512, dtype: object

(9,)

tconst               tt11817024
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000513, dtype: object

(9,)

tconst              tt11817026
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000514, dtype: object

(9,)

tconst              tt11817028
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000515, dtype: object

(9,)

tconst                        tt1181702
titleType                  tvMiniSeries
primaryTitle      A History of Tyneside
originalTitle     A History of Tyneside
isAdult                               0
startYear                          2006
endYear                            2006
runtimeMinutes                       \N
genres                      Documentary
Name: 2000516, dtype: object

(9,)

tconst               tt11817030
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000517, dtype: object

(9,)

tconst               tt11817032
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000518, dtype: object

(9,)

tconst                              tt11817034
titleType                            tvEpisode
primaryTitle      Episode dated 1 October 1970
originalTitle     Episode dated 1 October 1970
isAdult                                      0
startYear                                 1970
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2000519, dtype: object

(9,)

tconst               tt11817036
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000520, dtype: object

(9,)

tconst               tt11817038
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000521, dtype: object

(9,)

tconst              tt1181703
titleType           tvEpisode
primaryTitle      The Hotness
originalTitle     The Hotness
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             23
genres                 Comedy
Name: 2000522, dtype: object

(9,)

tconst               tt11817040
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000523, dtype: object

(9,)

tconst                               tt11817042
titleType                             tvEpisode
primaryTitle      Episode dated 23 January 2014
originalTitle     Episode dated 23 January 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2000524, dtype: object

(9,)

tconst                         tt11817044
titleType                           movie
primaryTitle      Somewhere Else Together
originalTitle     Somewhere Else Together
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                        121
genres              Adventure,Documentary
Name: 2000525, dtype: object

(9,)

tconst                        tt11817046
titleType                          video
primaryTitle      Singga: Dil Mutiyar Da
originalTitle     Singga: Dil Mutiyar Da
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                         3
genres                       Music,Short
Name: 2000526, dtype: object

(9,)

tconst                    tt11817048
titleType                  tvEpisode
primaryTitle      Li Zheng Shang You
originalTitle     Li Zheng Shang You
isAdult                            0
startYear                       2010
endYear                           \N
runtimeMinutes                     8
genres                        Comedy
Name: 2000527, dtype: object

(9,)

tconst               tt1181704
titleType            tvEpisode
primaryTitle      Where's Tom?
originalTitle     Where's Tom?
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              22
genres                  Comedy
Name: 2000528, dtype: object

(9,)

tconst                               tt11817050
titleType                             tvEpisode
primaryTitle      Episode dated 24 January 2014
originalTitle     Episode dated 24 January 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2000529, dtype: object

(9,)

tconst             tt11817052
titleType               video
primaryTitle       NK: Trymay
originalTitle      NK: Trymay
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes              3
genres            Music,Short
Name: 2000530, dtype: object

(9,)

tconst                      tt11817054
titleType                        movie
primaryTitle      Aathva Rang Premacha
originalTitle     Aathva Rang Premacha
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                           Drama
Name: 2000531, dtype: object

(9,)

tconst                                  tt11817056
titleType                                tvEpisode
primaryTitle      Course Management: Scott Fawcett
originalTitle     Course Management: Scott Fawcett
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                  Reality-TV
Name: 2000532, dtype: object

(9,)

tconst                                tt11817058
titleType                              tvEpisode
primaryTitle      Tony Finau and Boyd Summerhays
originalTitle     Tony Finau and Boyd Summerhays
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                Reality-TV
Name: 2000533, dtype: object

(9,)

tconst             tt1181705
titleType          tvEpisode
primaryTitle           Cheri
originalTitle          Cheri
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000534, dtype: object

(9,)

tconst             tt11817060
titleType               short
primaryTitle           Ungene
originalTitle          Ungene
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             12
genres            Drama,Short
Name: 2000535, dtype: object

(9,)

tconst                     tt11817062
titleType                tvMiniSeries
primaryTitle      Bevrijdingsjournaal
originalTitle     Bevrijdingsjournaal
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     10
genres               Documentary,News
Name: 2000536, dtype: object

(9,)

tconst                                               tt11817064
titleType                                                 movie
primaryTitle      Master of the Nine Dragon Fist: Wong Ching-Ho
originalTitle     Master of the Nine Dragon Fist: Wong Ching-Ho
isAdult                                                       0
startYear                                                  2019
endYear                                                      \N
runtimeMinutes                                               97
genres                                                   Action
Name: 2000537, dtype: object

(9,)

tconst                                                tt11817066
titleType                                              tvEpisode
primaryTitle      Mr. Pig & Mr. Mouse Have A Mess On Their Hands
originalTitle     Mr. Pig & Mr. Mouse Have A Mess On Their Hands
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                 Animation
Name: 2000538, dtype: object

(9,)

tconst            tt11817068
titleType              movie
primaryTitle       Town Mall
originalTitle      Town Mall
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            85
genres                Horror
Name: 2000539, dtype: object

(9,)

tconst             tt1181706
titleType          tvEpisode
primaryTitle           Marie
originalTitle          Marie
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000540, dtype: object

(9,)

tconst                          tt11817070
titleType                        tvEpisode
primaryTitle        Cacao Repays Her Debts
originalTitle       Cacao Repays Her Debts
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres            Animation,Comedy,Romance
Name: 2000541, dtype: object

(9,)

tconst                              tt11817072
titleType                            tvEpisode
primaryTitle      Hao Ku Lao Shi, Ni Hao Cool!
originalTitle     Hao Ku Lao Shi, Ni Hao Cool!
isAdult                                      0
startYear                                 2010
endYear                                     \N
runtimeMinutes                               9
genres                                  Comedy
Name: 2000542, dtype: object

(9,)

tconst                            tt11817074
titleType                          tvEpisode
primaryTitle      Summer Beach Cat Paradise!
originalTitle     Summer Beach Cat Paradise!
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            23
genres              Animation,Comedy,Romance
Name: 2000543, dtype: object

(9,)

tconst                          tt11817076
titleType                        tvEpisode
primaryTitle                 True Feelings
originalTitle                True Feelings
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          23
genres            Animation,Comedy,Romance
Name: 2000544, dtype: object

(9,)

tconst                           tt11817078
titleType                         tvEpisode
primaryTitle      Oh No! Bell Renewal Exams
originalTitle     Oh No! Bell Renewal Exams
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           23
genres             Animation,Comedy,Romance
Name: 2000545, dtype: object

(9,)

tconst             tt1181707
titleType          tvEpisode
primaryTitle          Tracey
originalTitle         Tracey
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2000546, dtype: object

(9,)

tconst                        tt11817080
titleType                      tvEpisode
primaryTitle               Your Rhapsody
originalTitle              Your Rhapsody
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Music
Name: 2000547, dtype: object

(9,)

tconst                        tt11817082
titleType                      tvEpisode
primaryTitle           TEPPAN IN THE BAG
originalTitle          TEPPAN IN THE BAG
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Music
Name: 2000548, dtype: object

(9,)

tconst                tt11817084
titleType                tvMovie
primaryTitle      Fatboy Racing!
originalTitle     Fatboy Racing!
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                28
genres               Documentary
Name: 2000549, dtype: object

(9,)

tconst                        tt11817086
titleType                      tvEpisode
primaryTitle              Mashumairesh!!
originalTitle             Mashumairesh!!
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Music
Name: 2000550, dtype: object

(9,)

tconst                        tt11817088
titleType                      tvEpisode
primaryTitle                    Platform
originalTitle                   Platform
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Music
Name: 2000551, dtype: object

(9,)

tconst               tt1181708
titleType             tvSeries
primaryTitle      The ITV Play
originalTitle     The ITV Play
isAdult                      0
startYear                 1968
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2000552, dtype: object

(9,)

tconst                      tt11817090
titleType                        video
primaryTitle      Divine: Gandhi Money
originalTitle     Divine: Gandhi Money
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       3
genres                     Music,Short
Name: 2000553, dtype: object

(9,)

tconst             tt11817092
titleType           tvEpisode
primaryTitle      Blurredface
originalTitle     Blurredface
isAdult                     0
startYear                2016
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2000554, dtype: object

(9,)

tconst                      tt11817094
titleType                        short
primaryTitle           Collecting Time
originalTitle     Syllegontas to hrono
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      31
genres               Documentary,Short
Name: 2000555, dtype: object

(9,)

tconst              tt11817096
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres               Game-Show
Name: 2000556, dtype: object

(9,)

tconst              tt11817098
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres               Game-Show
Name: 2000557, dtype: object

(9,)

tconst            tt1181709
titleType         tvEpisode
primaryTitle       Part One
originalTitle      Part One
isAdult                   0
startYear              1987
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2000558, dtype: object

(9,)

tconst              tt11817100
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2000559, dtype: object

(9,)

tconst                tt11817102
titleType              tvEpisode
primaryTitle      Skirts problem
originalTitle     Skirts problem
isAdult                        0
startYear                   2016
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000560, dtype: object

(9,)

tconst                  tt11817104
titleType                tvEpisode
primaryTitle        Episode #1.765
originalTitle       Episode #1.765
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000561, dtype: object

(9,)

tconst                  tt11817106
titleType                tvEpisode
primaryTitle        Episode #1.766
originalTitle       Episode #1.766
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000562, dtype: object

(9,)

tconst              tt11817108
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2000563, dtype: object

(9,)

tconst            tt1181710
titleType         tvEpisode
primaryTitle      Part Four
originalTitle     Part Four
isAdult                   0
startYear              1987
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2000564, dtype: object

(9,)

tconst                  tt11817110
titleType                tvEpisode
primaryTitle        Episode #1.767
originalTitle       Episode #1.767
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000565, dtype: object

(9,)

tconst                  tt11817112
titleType                tvEpisode
primaryTitle        Episode #1.768
originalTitle       Episode #1.768
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000566, dtype: object

(9,)

tconst                  tt11817114
titleType                tvEpisode
primaryTitle        Episode #1.769
originalTitle       Episode #1.769
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000567, dtype: object

(9,)

tconst              tt11817116
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000568, dtype: object

(9,)

tconst                  tt11817118
titleType                tvEpisode
primaryTitle        Episode #1.770
originalTitle       Episode #1.770
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000569, dtype: object

(9,)

tconst                                tt1181711
titleType                             tvEpisode
primaryTitle      Episode dated 8 November 2003
originalTitle     Episode dated 8 November 2003
isAdult                                       0
startYear                                  2003
endYear                                      \N
runtimeMinutes                               \N
genres                            Drama,Romance
Name: 2000570, dtype: object

(9,)

tconst              tt11817120
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000571, dtype: object

(9,)

tconst                  tt11817122
titleType                tvEpisode
primaryTitle        Episode #1.771
originalTitle       Episode #1.771
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000572, dtype: object

(9,)

tconst             tt11817126
titleType           tvEpisode
primaryTitle      The trigger
originalTitle     The trigger
isAdult                     0
startYear                2016
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2000573, dtype: object

(9,)

tconst              tt11817128
titleType                movie
primaryTitle      Saint Kizito
originalTitle     Saint Kizito
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2000574, dtype: object

(9,)

tconst                            tt1181712
titleType                          tvSeries
primaryTitle      Katy Brand's Big Ass Show
originalTitle     Katy Brand's Big Ass Show
isAdult                                   0
startYear                              2007
endYear                                  \N
runtimeMinutes                           30
genres                               Comedy
Name: 2000575, dtype: object

(9,)

tconst                  tt11817130
titleType                tvEpisode
primaryTitle      It's Complicated
originalTitle     It's Complicated
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  26
genres                       Drama
Name: 2000576, dtype: object

(9,)

tconst                  tt11817132
titleType                tvEpisode
primaryTitle        Episode #1.772
originalTitle       Episode #1.772
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000577, dtype: object

(9,)

tconst                  tt11817136
titleType                tvEpisode
primaryTitle        Episode #1.773
originalTitle       Episode #1.773
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000578, dtype: object

(9,)

tconst                tt11817138
titleType               tvSeries
primaryTitle      Age of Outrage
originalTitle     Age of Outrage
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                30
genres                    Comedy
Name: 2000579, dtype: object

(9,)

tconst                 tt1181713
titleType           tvMiniSeries
primaryTitle      Koini ochitara
originalTitle     Koini ochitara
isAdult                        0
startYear                   2005
endYear                       \N
runtimeMinutes                54
genres                   Romance
Name: 2000580, dtype: object

(9,)

tconst                     tt11817140
titleType                   tvEpisode
primaryTitle          Episode #1.6612
originalTitle         Episode #1.6612
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2000581, dtype: object

(9,)

tconst                  tt11817142
titleType                tvEpisode
primaryTitle        Episode #1.774
originalTitle       Episode #1.774
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000582, dtype: object

(9,)

tconst                  tt11817144
titleType                tvEpisode
primaryTitle        Episode #1.775
originalTitle       Episode #1.775
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000583, dtype: object

(9,)

tconst                     tt11817146
titleType                   tvEpisode
primaryTitle          Episode #1.6613
originalTitle         Episode #1.6613
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2000584, dtype: object

(9,)

tconst                           tt11817148
titleType                         tvEpisode
primaryTitle      Onora il padre e la madre
originalTitle     Onora il padre e la madre
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                   Comedy,Crime,Drama
Name: 2000585, dtype: object

(9,)

tconst                                    tt1181714
titleType                                 tvEpisode
primaryTitle      Between the Rack and a Hard Place
originalTitle     Between the Rack and a Hard Place
isAdult                                           0
startYear                                      2008
endYear                                          \N
runtimeMinutes                                   44
genres                        Drama,Mystery,Romance
Name: 2000586, dtype: object

(9,)

tconst            tt11817150
titleType              video
primaryTitle        ChrV-073
originalTitle       ChrV-073
isAdult                    1
startYear               2018
endYear                   \N
runtimeMinutes           150
genres                 Adult
Name: 2000587, dtype: object

(9,)

tconst                            tt11817152
titleType                          tvEpisode
primaryTitle      The first poor Polo player
originalTitle     The first poor Polo player
isAdult                                    0
startYear                               2016
endYear                                   \N
runtimeMinutes                            \N
genres                                Comedy
Name: 2000588, dtype: object

(9,)

tconst                  tt11817154
titleType                tvEpisode
primaryTitle        Episode #1.776
originalTitle       Episode #1.776
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000589, dtype: object

(9,)

tconst                     tt11817156
titleType                   tvEpisode
primaryTitle          Episode #1.6614
originalTitle         Episode #1.6614
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2000590, dtype: object

(9,)

tconst                  tt11817158
titleType                tvEpisode
primaryTitle        Episode #1.777
originalTitle       Episode #1.777
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000591, dtype: object

(9,)

tconst                tt1181715
titleType             tvEpisode
primaryTitle         Rope's End
originalTitle        Rope's End
isAdult                       0
startYear                  1958
endYear                      \N
runtimeMinutes               \N
genres            Drama,Mystery
Name: 2000592, dtype: object

(9,)

tconst                           tt11817160
titleType                         tvEpisode
primaryTitle               Reagan vs Carter
originalTitle              Reagan vs Carter
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres            Documentary,Drama,History
Name: 2000593, dtype: object

(9,)

tconst                  tt11817162
titleType                tvEpisode
primaryTitle        Episode #1.778
originalTitle       Episode #1.778
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000594, dtype: object

(9,)

tconst                   tt11817164
titleType                 tvEpisode
primaryTitle      Mexico - Acapulco
originalTitle     Mexico - Acapulco
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   47
genres                   Reality-TV
Name: 2000595, dtype: object

(9,)

tconst                     tt11817166
titleType                   tvEpisode
primaryTitle          Episode #1.6617
originalTitle         Episode #1.6617
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2000596, dtype: object

(9,)

tconst                                      tt11817168
titleType                                    tvEpisode
primaryTitle      Glendora's Valentine's Day Aftermath
originalTitle     Glendora's Valentine's Day Aftermath
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Short
Name: 2000597, dtype: object

(9,)

tconst                     tt1181716
titleType               tvMiniSeries
primaryTitle      Life in Cold Blood
originalTitle     Life in Cold Blood
isAdult                            0
startYear                       2008
endYear                         2008
runtimeMinutes                    \N
genres                   Documentary
Name: 2000598, dtype: object

(9,)

tconst                     tt11817170
titleType                   tvEpisode
primaryTitle          Episode #1.6618
originalTitle         Episode #1.6618
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2000599, dtype: object

(9,)

tconst                  tt11817172
titleType                tvEpisode
primaryTitle        Episode #1.779
originalTitle       Episode #1.779
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000600, dtype: object

(9,)

tconst                     tt11817174
titleType                   tvEpisode
primaryTitle          Episode #1.6619
originalTitle         Episode #1.6619
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2000601, dtype: object

(9,)

tconst              tt11817176
titleType                video
primaryTitle      NK: Obitsayu
originalTitle     NK: Obitsayu
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes               4
genres             Music,Short
Name: 2000602, dtype: object

(9,)

tconst                   tt11817178
titleType                 tvEpisode
primaryTitle         Melissa Croden
originalTitle        Melissa Croden
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000603, dtype: object

(9,)

tconst                 tt1181717
titleType              tvEpisode
primaryTitle        Episode #2.1
originalTitle       Episode #2.1
isAdult                        0
startYear                   2007
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000604, dtype: object

(9,)

tconst                  tt11817180
titleType                tvEpisode
primaryTitle        Episode #1.780
originalTitle       Episode #1.780
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000605, dtype: object

(9,)

tconst                         tt11817182
titleType                       tvEpisode
primaryTitle      The first checkers lady
originalTitle     The first checkers lady
isAdult                                 0
startYear                            2016
endYear                                \N
runtimeMinutes                         \N
genres                             Comedy
Name: 2000606, dtype: object

(9,)

tconst                  tt11817184
titleType                tvEpisode
primaryTitle        Episode #1.781
originalTitle       Episode #1.781
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000607, dtype: object

(9,)

tconst                  tt11817186
titleType                tvEpisode
primaryTitle        Episode #1.782
originalTitle       Episode #1.782
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000608, dtype: object

(9,)

tconst                  tt11817188
titleType                tvEpisode
primaryTitle        Episode #1.783
originalTitle       Episode #1.783
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000609, dtype: object

(9,)

tconst                    tt1181718
titleType                 tvEpisode
primaryTitle      The PT 73 Follies
originalTitle     The PT 73 Follies
isAdult                           0
startYear                      1965
endYear                          \N
runtimeMinutes                   25
genres                   Comedy,War
Name: 2000610, dtype: object

(9,)

tconst                  tt11817190
titleType                tvEpisode
primaryTitle        Episode #1.784
originalTitle       Episode #1.784
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000611, dtype: object

(9,)

tconst                  tt11817192
titleType                tvEpisode
primaryTitle        Episode #1.785
originalTitle       Episode #1.785
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000612, dtype: object

(9,)

tconst                   tt11817194
titleType                 tvEpisode
primaryTitle         Chris Smeltzer
originalTitle        Chris Smeltzer
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000613, dtype: object

(9,)

tconst                              tt11817196
titleType                            tvEpisode
primaryTitle      Episode dated 2 October 1970
originalTitle     Episode dated 2 October 1970
isAdult                                      0
startYear                                 1970
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2000614, dtype: object

(9,)

tconst                   tt11817198
titleType                 tvEpisode
primaryTitle      Isaiah Burkhalter
originalTitle     Isaiah Burkhalter
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000615, dtype: object

(9,)

tconst                                   tt1181719
titleType                                tvEpisode
primaryTitle      The Man Who Made Trouble: Part 1
originalTitle     The Man Who Made Trouble: Part 1
isAdult                                          0
startYear                                     1961
endYear                                         \N
runtimeMinutes                                  \N
genres                                 Crime,Drama
Name: 2000616, dtype: object

(9,)

tconst                                                   tt11817200
titleType                                                 tvEpisode
primaryTitle      Top 10 Craziest Family Guy Fan Theories (That ...
originalTitle     Top 10 Craziest Family Guy Fan Theories (That ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                             Comedy,Talk-Show
Name: 2000617, dtype: object

(9,)

tconst              tt11817202
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              51
genres               Game-Show
Name: 2000618, dtype: object

(9,)

tconst               tt11817204
titleType             tvEpisode
primaryTitle      Episode #2.35
originalTitle     Episode #2.35
isAdult                       0
startYear                  1989
endYear                      \N
runtimeMinutes               \N
genres               Crime,News
Name: 2000619, dtype: object

(9,)

tconst                  tt11817208
titleType                    video
primaryTitle      Poolside Affairs
originalTitle     Poolside Affairs
isAdult                          1
startYear                     2020
endYear                         \N
runtimeMinutes                 183
genres                       Adult
Name: 2000620, dtype: object

(9,)

tconst                        tt1181720
titleType                  tvMiniSeries
primaryTitle      Minami kun no koibito
originalTitle     Minami kun no koibito
isAdult                               0
startYear                          2004
endYear                              \N
runtimeMinutes                       \N
genres                          Romance
Name: 2000621, dtype: object

(9,)

tconst                            tt11817210
titleType                          tvEpisode
primaryTitle        Nitroglycerine Nightmare
originalTitle       Nitroglycerine Nightmare
isAdult                                    0
startYear                               2010
endYear                                   \N
runtimeMinutes                            \N
genres            Adventure,Animation,Comedy
Name: 2000622, dtype: object

(9,)

tconst                                                 tt11817212
titleType                                               tvEpisode
primaryTitle      Amazon Empire: The Rise and Reign of Jeff Bezos
originalTitle     Amazon Empire: The Rise and Reign of Jeff Bezos
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                115
genres                                           Documentary,News
Name: 2000623, dtype: object

(9,)

tconst                            tt11817214
titleType                          tvEpisode
primaryTitle                    The Magician
originalTitle                   The Magician
isAdult                                    0
startYear                               2010
endYear                                   \N
runtimeMinutes                            \N
genres            Adventure,Animation,Comedy
Name: 2000624, dtype: object

(9,)

tconst                tt11817216
titleType              tvEpisode
primaryTitle       Episode #1.21
originalTitle      Episode #1.21
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000625, dtype: object

(9,)

tconst                tt11817218
titleType              tvEpisode
primaryTitle       Episode #1.22
originalTitle      Episode #1.22
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000626, dtype: object

(9,)

tconst                 tt1181721
titleType               tvSeries
primaryTitle      Mousiki vradya
originalTitle     Mousiki vradya
isAdult                        0
startYear                   1976
endYear                       \N
runtimeMinutes                56
genres                     Music
Name: 2000627, dtype: object

(9,)

tconst                tt11817220
titleType              tvEpisode
primaryTitle       Episode #1.23
originalTitle      Episode #1.23
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000628, dtype: object

(9,)

tconst                tt11817222
titleType              tvEpisode
primaryTitle       Episode #1.24
originalTitle      Episode #1.24
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000629, dtype: object

(9,)

tconst                tt11817224
titleType              tvEpisode
primaryTitle       Episode #1.26
originalTitle      Episode #1.26
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000630, dtype: object

(9,)

tconst                tt11817226
titleType              tvEpisode
primaryTitle       Episode #1.25
originalTitle      Episode #1.25
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000631, dtype: object

(9,)

tconst                tt11817228
titleType              tvEpisode
primaryTitle       Episode #1.27
originalTitle      Episode #1.27
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000632, dtype: object

(9,)

tconst                        tt1181722
titleType                     tvEpisode
primaryTitle      A Very Brady Birthday
originalTitle     A Very Brady Birthday
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       21
genres                       Reality-TV
Name: 2000633, dtype: object

(9,)

tconst                tt11817230
titleType              tvEpisode
primaryTitle       Episode #1.28
originalTitle      Episode #1.28
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000634, dtype: object

(9,)

tconst                tt11817232
titleType              tvEpisode
primaryTitle       Episode #1.29
originalTitle      Episode #1.29
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000635, dtype: object

(9,)

tconst                tt11817234
titleType              tvEpisode
primaryTitle       Episode #1.30
originalTitle      Episode #1.30
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000636, dtype: object

(9,)

tconst                tt11817236
titleType              tvEpisode
primaryTitle       Episode #1.31
originalTitle      Episode #1.31
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000637, dtype: object

(9,)

tconst                tt11817238
titleType              tvEpisode
primaryTitle       Episode #1.32
originalTitle      Episode #1.32
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000638, dtype: object

(9,)

tconst                tt11817240
titleType              tvEpisode
primaryTitle       Episode #1.33
originalTitle      Episode #1.33
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000639, dtype: object

(9,)

tconst                   tt11817242
titleType                     short
primaryTitle             The Busboy
originalTitle            The Busboy
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   24
genres            Documentary,Short
Name: 2000640, dtype: object

(9,)

tconst                tt11817244
titleType              tvEpisode
primaryTitle       Episode #1.34
originalTitle      Episode #1.34
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000641, dtype: object

(9,)

tconst                tt11817246
titleType              tvEpisode
primaryTitle       Episode #1.35
originalTitle      Episode #1.35
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000642, dtype: object

(9,)

tconst                tt11817248
titleType              tvEpisode
primaryTitle       Episode #1.37
originalTitle      Episode #1.37
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000643, dtype: object

(9,)

tconst                tt11817250
titleType              tvEpisode
primaryTitle       Episode #1.36
originalTitle      Episode #1.36
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000644, dtype: object

(9,)

tconst                tt11817252
titleType              tvEpisode
primaryTitle       Episode #1.38
originalTitle      Episode #1.38
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000645, dtype: object

(9,)

tconst                tt11817254
titleType              tvEpisode
primaryTitle       Episode #1.39
originalTitle      Episode #1.39
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000646, dtype: object

(9,)

tconst               tt11817256
titleType             tvEpisode
primaryTitle      Morning Sex 2
originalTitle     Morning Sex 2
isAdult                       1
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2000647, dtype: object

(9,)

tconst                tt11817258
titleType              tvEpisode
primaryTitle       Episode #1.40
originalTitle      Episode #1.40
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2000648, dtype: object

(9,)

tconst            tt11817260
titleType          tvEpisode
primaryTitle           Pilot
originalTitle          Pilot
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2000649, dtype: object

(9,)

tconst                tt11817262
titleType              tvEpisode
primaryTitle      Episode #2.221
originalTitle     Episode #2.221
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000650, dtype: object

(9,)

tconst                        tt11817264
titleType                          video
primaryTitle      Sandra Cires: Dementes
originalTitle     Sandra Cires: Dementes
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2000651, dtype: object

(9,)

tconst                tt11817268
titleType              tvEpisode
primaryTitle      Episode #2.222
originalTitle     Episode #2.222
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000652, dtype: object

(9,)

tconst                tt11817270
titleType              tvEpisode
primaryTitle      Episode #2.224
originalTitle     Episode #2.224
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000653, dtype: object

(9,)

tconst                tt11817272
titleType              tvEpisode
primaryTitle      Episode #2.223
originalTitle     Episode #2.223
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000654, dtype: object

(9,)

tconst                tt11817274
titleType              tvEpisode
primaryTitle      Episode #2.225
originalTitle     Episode #2.225
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000655, dtype: object

(9,)

tconst                tt11817276
titleType              tvEpisode
primaryTitle      Episode #2.226
originalTitle     Episode #2.226
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000656, dtype: object

(9,)

tconst                tt11817278
titleType              tvEpisode
primaryTitle      Episode #2.227
originalTitle     Episode #2.227
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000657, dtype: object

(9,)

tconst                    tt1181727
titleType                 tvEpisode
primaryTitle      Meet My Nude Wife
originalTitle     Meet My Nude Wife
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   22
genres                   Reality-TV
Name: 2000658, dtype: object

(9,)

tconst                tt11817280
titleType              tvEpisode
primaryTitle      Episode #2.228
originalTitle     Episode #2.228
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000659, dtype: object

(9,)

tconst                tt11817282
titleType              tvEpisode
primaryTitle      Episode #2.229
originalTitle     Episode #2.229
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000660, dtype: object

(9,)

tconst                tt11817284
titleType              tvEpisode
primaryTitle      Episode #2.230
originalTitle     Episode #2.230
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000661, dtype: object

(9,)

tconst                tt11817286
titleType              tvEpisode
primaryTitle      Episode #2.231
originalTitle     Episode #2.231
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000662, dtype: object

(9,)

tconst                tt11817288
titleType              tvEpisode
primaryTitle      Episode #2.232
originalTitle     Episode #2.232
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000663, dtype: object

(9,)

tconst               tt1181728
titleType            tvEpisode
primaryTitle      On the Brink
originalTitle     On the Brink
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              22
genres              Reality-TV
Name: 2000664, dtype: object

(9,)

tconst                tt11817290
titleType              tvEpisode
primaryTitle      Episode #2.233
originalTitle     Episode #2.233
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000665, dtype: object

(9,)

tconst                tt11817292
titleType              tvEpisode
primaryTitle      Episode #2.234
originalTitle     Episode #2.234
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000666, dtype: object

(9,)

tconst                tt11817294
titleType              tvEpisode
primaryTitle      Episode #2.235
originalTitle     Episode #2.235
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000667, dtype: object

(9,)

tconst                tt11817296
titleType              tvEpisode
primaryTitle      Episode #2.236
originalTitle     Episode #2.236
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000668, dtype: object

(9,)

tconst                tt11817298
titleType              tvEpisode
primaryTitle      Episode #2.237
originalTitle     Episode #2.237
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000669, dtype: object

(9,)

tconst                tt11817300
titleType              tvEpisode
primaryTitle      Episode #2.238
originalTitle     Episode #2.238
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000670, dtype: object

(9,)

tconst                tt11817302
titleType              tvEpisode
primaryTitle      Episode #2.239
originalTitle     Episode #2.239
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000671, dtype: object

(9,)

tconst                tt11817304
titleType              tvEpisode
primaryTitle      Episode #2.240
originalTitle     Episode #2.240
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2000672, dtype: object

(9,)

tconst               tt11817306
titleType             tvEpisode
primaryTitle      Episode #2.21
originalTitle     Episode #2.21
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000673, dtype: object

(9,)

tconst               tt11817308
titleType             tvEpisode
primaryTitle      Episode #2.22
originalTitle     Episode #2.22
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000674, dtype: object

(9,)

tconst                   tt1181730
titleType                tvEpisode
primaryTitle      Wizyta tesciowej
originalTitle     Wizyta tesciowej
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  49
genres               Drama,Romance
Name: 2000675, dtype: object

(9,)

tconst               tt11817310
titleType             tvEpisode
primaryTitle      Episode #2.23
originalTitle     Episode #2.23
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000676, dtype: object

(9,)

tconst                   tt11817312
titleType                 tvEpisode
primaryTitle           Cody Purtell
originalTitle          Cody Purtell
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000677, dtype: object

(9,)

tconst               tt11817314
titleType             tvEpisode
primaryTitle      Episode #2.25
originalTitle     Episode #2.25
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000678, dtype: object

(9,)

tconst               tt11817316
titleType             tvEpisode
primaryTitle      Episode #2.24
originalTitle     Episode #2.24
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000679, dtype: object

(9,)

tconst               tt11817318
titleType             tvEpisode
primaryTitle      Episode #2.27
originalTitle     Episode #2.27
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000680, dtype: object

(9,)

tconst               tt11817320
titleType             tvEpisode
primaryTitle      Episode #2.26
originalTitle     Episode #2.26
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000681, dtype: object

(9,)

tconst               tt11817322
titleType             tvEpisode
primaryTitle      Episode #2.28
originalTitle     Episode #2.28
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000682, dtype: object

(9,)

tconst               tt11817324
titleType             tvEpisode
primaryTitle      Episode #2.29
originalTitle     Episode #2.29
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000683, dtype: object

(9,)

tconst               tt11817326
titleType             tvEpisode
primaryTitle      Episode #2.30
originalTitle     Episode #2.30
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000684, dtype: object

(9,)

tconst               tt11817328
titleType             tvEpisode
primaryTitle      Episode #2.31
originalTitle     Episode #2.31
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000685, dtype: object

(9,)

tconst                tt1181732
titleType             tvEpisode
primaryTitle             Balvan
originalTitle            Balvan
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000686, dtype: object

(9,)

tconst               tt11817330
titleType             tvEpisode
primaryTitle      Episode #2.33
originalTitle     Episode #2.33
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000687, dtype: object

(9,)

tconst               tt11817332
titleType             tvEpisode
primaryTitle      Episode #2.32
originalTitle     Episode #2.32
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000688, dtype: object

(9,)

tconst               tt11817334
titleType             tvEpisode
primaryTitle      Episode #2.35
originalTitle     Episode #2.35
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000689, dtype: object

(9,)

tconst               tt11817336
titleType             tvEpisode
primaryTitle      Episode #2.36
originalTitle     Episode #2.36
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000690, dtype: object

(9,)

tconst               tt11817338
titleType             tvEpisode
primaryTitle      Episode #2.34
originalTitle     Episode #2.34
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000691, dtype: object

(9,)

tconst                tt1181733
titleType             tvEpisode
primaryTitle             Cistka
originalTitle            Cistka
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000692, dtype: object

(9,)

tconst               tt11817340
titleType             tvEpisode
primaryTitle      Episode #2.37
originalTitle     Episode #2.37
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000693, dtype: object

(9,)

tconst               tt11817342
titleType             tvEpisode
primaryTitle      Episode #2.38
originalTitle     Episode #2.38
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000694, dtype: object

(9,)

tconst               tt11817344
titleType             tvEpisode
primaryTitle      Episode #2.39
originalTitle     Episode #2.39
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000695, dtype: object

(9,)

tconst               tt11817346
titleType             tvEpisode
primaryTitle      Episode #2.40
originalTitle     Episode #2.40
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000696, dtype: object

(9,)

tconst               tt11817348
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000697, dtype: object

(9,)

tconst                tt1181734
titleType             tvEpisode
primaryTitle           Diagnóza
originalTitle          Diagnóza
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000698, dtype: object

(9,)

tconst               tt11817350
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000699, dtype: object

(9,)

tconst               tt11817352
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000700, dtype: object

(9,)

tconst               tt11817354
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000701, dtype: object

(9,)

tconst                   tt11817356
titleType                  tvSeries
primaryTitle      Mafia Restaurants
originalTitle     Mafia Restaurants
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                   Reality-TV
Name: 2000702, dtype: object

(9,)

tconst               tt11817358
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000703, dtype: object

(9,)

tconst                tt1181735
titleType             tvEpisode
primaryTitle       Druhá rodina
originalTitle      Druhá rodina
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000704, dtype: object

(9,)

tconst               tt11817360
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000705, dtype: object

(9,)

tconst               tt11817362
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000706, dtype: object

(9,)

tconst               tt11817364
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000707, dtype: object

(9,)

tconst               tt11817366
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000708, dtype: object

(9,)

tconst               tt11817368
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000709, dtype: object

(9,)

tconst                tt1181736
titleType             tvEpisode
primaryTitle               Past
originalTitle              Past
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000710, dtype: object

(9,)

tconst               tt11817370
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000711, dtype: object

(9,)

tconst               tt11817372
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000712, dtype: object

(9,)

tconst               tt11817374
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000713, dtype: object

(9,)

tconst               tt11817376
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000714, dtype: object

(9,)

tconst               tt11817378
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000715, dtype: object

(9,)

tconst                tt1181737
titleType             tvEpisode
primaryTitle            Pomluva
originalTitle           Pomluva
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000716, dtype: object

(9,)

tconst               tt11817380
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000717, dtype: object

(9,)

tconst               tt11817382
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000718, dtype: object

(9,)

tconst               tt11817384
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000719, dtype: object

(9,)

tconst                   tt11817386
titleType                 tvEpisode
primaryTitle          Jeremy Purdue
originalTitle         Jeremy Purdue
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000720, dtype: object

(9,)

tconst               tt11817388
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000721, dtype: object

(9,)

tconst                tt1181738
titleType             tvEpisode
primaryTitle               Slib
originalTitle              Slib
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000722, dtype: object

(9,)

tconst               tt11817390
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000723, dtype: object

(9,)

tconst            tt11817392
titleType              movie
primaryTitle         Manuela
originalTitle        Manuela
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            90
genres                 Drama
Name: 2000724, dtype: object

(9,)

tconst               tt11817394
titleType             tvEpisode
primaryTitle      Episode #2.21
originalTitle     Episode #2.21
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000725, dtype: object

(9,)

tconst               tt11817396
titleType             tvEpisode
primaryTitle      Episode #2.22
originalTitle     Episode #2.22
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000726, dtype: object

(9,)

tconst               tt11817398
titleType             tvEpisode
primaryTitle      Episode #2.23
originalTitle     Episode #2.23
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000727, dtype: object

(9,)

tconst                tt1181739
titleType             tvEpisode
primaryTitle              Start
originalTitle             Start
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000728, dtype: object

(9,)

tconst                   tt11817400
titleType                 tvEpisode
primaryTitle          Jared Tordoff
originalTitle         Jared Tordoff
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000729, dtype: object

(9,)

tconst               tt11817402
titleType                 short
primaryTitle              Votes
originalTitle             Votes
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Mystery,Short
Name: 2000730, dtype: object

(9,)

tconst              tt11817404
titleType            tvEpisode
primaryTitle      In Treatment
originalTitle     In Treatment
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2000731, dtype: object

(9,)

tconst               tt11817406
titleType             tvEpisode
primaryTitle      Episode #2.24
originalTitle     Episode #2.24
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000732, dtype: object

(9,)

tconst               tt11817408
titleType             tvEpisode
primaryTitle      Episode #2.25
originalTitle     Episode #2.25
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000733, dtype: object

(9,)

tconst                tt1181740
titleType             tvEpisode
primaryTitle             Synové
originalTitle            Synové
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000734, dtype: object

(9,)

tconst               tt11817410
titleType             tvEpisode
primaryTitle      Episode #2.26
originalTitle     Episode #2.26
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000735, dtype: object

(9,)

tconst               tt11817412
titleType             tvEpisode
primaryTitle      Episode #2.27
originalTitle     Episode #2.27
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000736, dtype: object

(9,)

tconst               tt11817414
titleType             tvEpisode
primaryTitle      Episode #2.28
originalTitle     Episode #2.28
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000737, dtype: object

(9,)

tconst                             tt11817416
titleType                           tvEpisode
primaryTitle      Runaway or Targeted Runner?
originalTitle     Runaway or Targeted Runner?
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             42
genres                            Documentary
Name: 2000738, dtype: object

(9,)

tconst               tt11817418
titleType             tvEpisode
primaryTitle      Episode #2.29
originalTitle     Episode #2.29
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000739, dtype: object

(9,)

tconst                tt1181741
titleType             tvEpisode
primaryTitle          Tajemství
originalTitle         Tajemství
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000740, dtype: object

(9,)

tconst               tt11817420
titleType                 short
primaryTitle            Lekaime
originalTitle           Lekaime
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               \N
genres            Fantasy,Short
Name: 2000741, dtype: object

(9,)

tconst               tt11817422
titleType             tvEpisode
primaryTitle      Episode #2.30
originalTitle     Episode #2.30
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000742, dtype: object

(9,)

tconst               tt11817424
titleType             tvEpisode
primaryTitle      Episode #2.31
originalTitle     Episode #2.31
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000743, dtype: object

(9,)

tconst               tt11817426
titleType             tvEpisode
primaryTitle      Episode #2.32
originalTitle     Episode #2.32
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000744, dtype: object

(9,)

tconst               tt11817428
titleType             tvEpisode
primaryTitle      Episode #2.33
originalTitle     Episode #2.33
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000745, dtype: object

(9,)

tconst                tt1181742
titleType             tvEpisode
primaryTitle       Zatnuté zuby
originalTitle      Zatnuté zuby
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000746, dtype: object

(9,)

tconst               tt11817430
titleType             tvEpisode
primaryTitle      Episode #2.34
originalTitle     Episode #2.34
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000747, dtype: object

(9,)

tconst               tt11817432
titleType             tvEpisode
primaryTitle      Episode #2.35
originalTitle     Episode #2.35
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000748, dtype: object

(9,)

tconst                                         tt11817434
titleType                                       tvEpisode
primaryTitle      Hedgehogs, and Bats, and Genies, Oh My!
originalTitle     Hedgehogs, and Bats, and Genies, Oh My!
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                          Talk-Show
Name: 2000749, dtype: object

(9,)

tconst               tt11817436
titleType             tvEpisode
primaryTitle      Episode #2.36
originalTitle     Episode #2.36
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000750, dtype: object

(9,)

tconst               tt11817438
titleType             tvEpisode
primaryTitle      Episode #2.37
originalTitle     Episode #2.37
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000751, dtype: object

(9,)

tconst                tt1181743
titleType             tvEpisode
primaryTitle             Zpoved
originalTitle            Zpoved
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000752, dtype: object

(9,)

tconst             tt11817440
titleType               short
primaryTitle      Do It Again
originalTitle     Do It Again
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             10
genres                  Short
Name: 2000753, dtype: object

(9,)

tconst               tt11817442
titleType             tvEpisode
primaryTitle      Episode #2.38
originalTitle     Episode #2.38
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000754, dtype: object

(9,)

tconst               tt11817444
titleType             tvEpisode
primaryTitle      Episode #2.39
originalTitle     Episode #2.39
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000755, dtype: object

(9,)

tconst               tt11817446
titleType             tvEpisode
primaryTitle      Episode #2.40
originalTitle     Episode #2.40
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2000756, dtype: object

(9,)

tconst                                      tt11817448
titleType                                    tvEpisode
primaryTitle      Skipping School or Silenced Forever?
originalTitle     Skipping School or Silenced Forever?
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      42
genres                                     Documentary
Name: 2000757, dtype: object

(9,)

tconst                tt1181744
titleType             tvEpisode
primaryTitle              Úteky
originalTitle             Úteky
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2000758, dtype: object

(9,)

tconst                   tt11817450
titleType                 tvEpisode
primaryTitle            Maged Hammo
originalTitle           Maged Hammo
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000759, dtype: object

(9,)

tconst                tt11817452
titleType              tvEpisode
primaryTitle      Episode #1.261
originalTitle     Episode #1.261
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000760, dtype: object

(9,)

tconst                           tt11817454
titleType                         tvEpisode
primaryTitle      Suicide or Sinister Plot?
originalTitle     Suicide or Sinister Plot?
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           42
genres                          Documentary
Name: 2000761, dtype: object

(9,)

tconst                               tt11817456
titleType                             tvEpisode
primaryTitle      Episode dated 17 October 2014
originalTitle     Episode dated 17 October 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2000762, dtype: object

(9,)

tconst                tt11817458
titleType              tvEpisode
primaryTitle      Episode #1.262
originalTitle     Episode #1.262
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000763, dtype: object

(9,)

tconst              tt1181745
titleType           tvEpisode
primaryTitle      Återseendet
originalTitle     Återseendet
isAdult                     0
startYear                1972
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2000764, dtype: object

(9,)

tconst                tt11817460
titleType              tvEpisode
primaryTitle      Episode #1.263
originalTitle     Episode #1.263
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000765, dtype: object

(9,)

tconst                tt11817462
titleType              tvEpisode
primaryTitle      Episode #1.264
originalTitle     Episode #1.264
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000766, dtype: object

(9,)

tconst                tt11817464
titleType              tvEpisode
primaryTitle      Episode #1.266
originalTitle     Episode #1.266
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000767, dtype: object

(9,)

tconst                tt11817466
titleType              tvEpisode
primaryTitle      Episode #1.265
originalTitle     Episode #1.265
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000768, dtype: object

(9,)

tconst              tt1181746
titleType           tvEpisode
primaryTitle        Bioterror
originalTitle       Bioterror
isAdult                     0
startYear                2001
endYear                    \N
runtimeMinutes             90
genres            Documentary
Name: 2000769, dtype: object

(9,)

tconst                tt11817470
titleType              tvEpisode
primaryTitle      Episode #1.267
originalTitle     Episode #1.267
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000770, dtype: object

(9,)

tconst                tt11817472
titleType              tvEpisode
primaryTitle      Episode #1.268
originalTitle     Episode #1.268
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000771, dtype: object

(9,)

tconst                tt11817474
titleType              tvEpisode
primaryTitle      Episode #1.269
originalTitle     Episode #1.269
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000772, dtype: object

(9,)

tconst                tt11817476
titleType              tvEpisode
primaryTitle      Episode #1.270
originalTitle     Episode #1.270
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000773, dtype: object

(9,)

tconst                tt11817478
titleType              tvEpisode
primaryTitle      Episode #1.272
originalTitle     Episode #1.272
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000774, dtype: object

(9,)

tconst                tt1181747
titleType             tvEpisode
primaryTitle      Carola gästar
originalTitle     Carola gästar
isAdult                       0
startYear                  1998
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2000775, dtype: object

(9,)

tconst                tt11817480
titleType              tvEpisode
primaryTitle      Episode #1.271
originalTitle     Episode #1.271
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000776, dtype: object

(9,)

tconst                tt11817482
titleType              tvEpisode
primaryTitle      Episode #1.273
originalTitle     Episode #1.273
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000777, dtype: object

(9,)

tconst                tt11817484
titleType              tvEpisode
primaryTitle      Episode #1.274
originalTitle     Episode #1.274
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000778, dtype: object

(9,)

tconst                tt11817486
titleType              tvEpisode
primaryTitle      Episode #1.276
originalTitle     Episode #1.276
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000779, dtype: object

(9,)

tconst                tt11817488
titleType              tvEpisode
primaryTitle      Episode #1.275
originalTitle     Episode #1.275
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000780, dtype: object

(9,)

tconst                tt11817490
titleType              tvEpisode
primaryTitle      Episode #1.277
originalTitle     Episode #1.277
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000781, dtype: object

(9,)

tconst                tt11817492
titleType              tvEpisode
primaryTitle      Episode #1.278
originalTitle     Episode #1.278
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000782, dtype: object

(9,)

tconst                tt11817494
titleType              tvEpisode
primaryTitle      Episode #1.279
originalTitle     Episode #1.279
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000783, dtype: object

(9,)

tconst                tt11817496
titleType              tvEpisode
primaryTitle      Episode #1.280
originalTitle     Episode #1.280
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2000784, dtype: object

(9,)

tconst                   tt11817498
titleType                 tvEpisode
primaryTitle          Lucas Neufeld
originalTitle         Lucas Neufeld
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000785, dtype: object

(9,)

tconst               tt11817500
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000786, dtype: object

(9,)

tconst               tt11817502
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000787, dtype: object

(9,)

tconst               tt11817504
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000788, dtype: object

(9,)

tconst               tt11817506
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000789, dtype: object

(9,)

tconst               tt11817508
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000790, dtype: object

(9,)

tconst                                 tt1181750
titleType                              tvEpisode
primaryTitle      Episode dated 14 December 2007
originalTitle     Episode dated 14 December 2007
isAdult                                        0
startYear                                   2007
endYear                                       \N
runtimeMinutes                                \N
genres                                     Drama
Name: 2000791, dtype: object

(9,)

tconst               tt11817510
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000792, dtype: object

(9,)

tconst               tt11817512
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000793, dtype: object

(9,)

tconst               tt11817514
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000794, dtype: object

(9,)

tconst               tt11817516
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000795, dtype: object

(9,)

tconst               tt11817518
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000796, dtype: object

(9,)

tconst                   tt1181751
titleType                tvEpisode
primaryTitle      Episode #1.10144
originalTitle     Episode #1.10144
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2000797, dtype: object

(9,)

tconst                 tt11817520
titleType               tvEpisode
primaryTitle      Henry Armstrong
originalTitle     Henry Armstrong
isAdult                         0
startYear                    1954
endYear                        \N
runtimeMinutes                 \N
genres                         \N
Name: 2000798, dtype: object

(9,)

tconst               tt11817522
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000799, dtype: object

(9,)

tconst               tt11817524
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000800, dtype: object

(9,)

tconst               tt11817526
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000801, dtype: object

(9,)

tconst               tt11817528
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000802, dtype: object

(9,)

tconst                               tt1181752
titleType                            tvEpisode
primaryTitle      The Return of Paradise Hotel
originalTitle     The Return of Paradise Hotel
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              55
genres                      Reality-TV,Romance
Name: 2000803, dtype: object

(9,)

tconst               tt11817530
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000804, dtype: object

(9,)

tconst                tt11817532
titleType              tvEpisode
primaryTitle      Episode #16.79
originalTitle     Episode #16.79
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2000805, dtype: object

(9,)

tconst               tt11817534
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000806, dtype: object

(9,)

tconst               tt11817536
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000807, dtype: object

(9,)

tconst               tt11817538
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000808, dtype: object

(9,)

tconst                         tt1181753
titleType                      tvEpisode
primaryTitle           Underwater Menace
originalTitle          Underwater Menace
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        46
genres            Action,Adventure,Drama
Name: 2000809, dtype: object

(9,)

tconst               tt11817540
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000810, dtype: object

(9,)

tconst               tt11817542
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000811, dtype: object

(9,)

tconst               tt11817544
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000812, dtype: object

(9,)

tconst             tt11817546
titleType               short
primaryTitle         RubyBaby
originalTitle        RubyBaby
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             24
genres            Drama,Short
Name: 2000813, dtype: object

(9,)

tconst                   tt11817548
titleType                 tvEpisode
primaryTitle         Josh Mackenzie
originalTitle        Josh Mackenzie
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000814, dtype: object

(9,)

tconst                   tt1181754
titleType                tvEpisode
primaryTitle      Technology Bytes
originalTitle     Technology Bytes
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Comedy,Family
Name: 2000815, dtype: object

(9,)

tconst               tt11817550
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000816, dtype: object

(9,)

tconst               tt11817552
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000817, dtype: object

(9,)

tconst               tt11817554
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000818, dtype: object

(9,)

tconst               tt11817556
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000819, dtype: object

(9,)

tconst               tt11817558
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000820, dtype: object

(9,)

tconst                        tt1181755
titleType                     tvEpisode
primaryTitle      The Luck of the Irish
originalTitle     The Luck of the Irish
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres                    Comedy,Family
Name: 2000821, dtype: object

(9,)

tconst               tt11817560
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000822, dtype: object

(9,)

tconst               tt11817562
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000823, dtype: object

(9,)

tconst               tt11817564
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000824, dtype: object

(9,)

tconst             tt11817566
titleType               video
primaryTitle      NK: Daj mne
originalTitle     NK: Daj mne
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes              3
genres            Music,Short
Name: 2000825, dtype: object

(9,)

tconst               tt11817568
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000826, dtype: object

(9,)

tconst            tt1181756
titleType         tvEpisode
primaryTitle          Del 6
originalTitle         Del 6
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2000827, dtype: object

(9,)

tconst               tt11817570
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000828, dtype: object

(9,)

tconst               tt11817572
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000829, dtype: object

(9,)

tconst               tt11817574
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000830, dtype: object

(9,)

tconst               tt11817576
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000831, dtype: object

(9,)

tconst               tt11817578
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000832, dtype: object

(9,)

tconst                      tt1181757
titleType                   tvEpisode
primaryTitle      The Greatest Knight
originalTitle     The Greatest Knight
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Documentary,History
Name: 2000833, dtype: object

(9,)

tconst               tt11817580
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000834, dtype: object

(9,)

tconst               tt11817582
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000835, dtype: object

(9,)

tconst               tt11817584
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000836, dtype: object

(9,)

tconst               tt11817586
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000837, dtype: object

(9,)

tconst               tt11817588
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000838, dtype: object

(9,)

tconst                          tt1181758
titleType                       tvEpisode
primaryTitle      The Pharaoh's Lost City
originalTitle     The Pharaoh's Lost City
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                Documentary,History
Name: 2000839, dtype: object

(9,)

tconst               tt11817590
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000840, dtype: object

(9,)

tconst               tt11817592
titleType             tvEpisode
primaryTitle      Wife Meets Ex
originalTitle     Wife Meets Ex
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               26
genres                    Drama
Name: 2000841, dtype: object

(9,)

tconst               tt11817594
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000842, dtype: object

(9,)

tconst               tt11817596
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000843, dtype: object

(9,)

tconst               tt11817598
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000844, dtype: object

(9,)

tconst                      tt1181759
titleType                   tvEpisode
primaryTitle       The Ten Pound Poms
originalTitle      The Ten Pound Poms
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Documentary,History
Name: 2000845, dtype: object

(9,)

tconst               tt11817600
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000846, dtype: object

(9,)

tconst               tt11817602
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000847, dtype: object

(9,)

tconst               tt11817604
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000848, dtype: object

(9,)

tconst               tt11817606
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000849, dtype: object

(9,)

tconst               tt11817608
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000850, dtype: object

(9,)

tconst                tt1181760
titleType             tvEpisode
primaryTitle      Episode #39.5
originalTitle     Episode #39.5
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2000851, dtype: object

(9,)

tconst               tt11817610
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000852, dtype: object

(9,)

tconst               tt11817612
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000853, dtype: object

(9,)

tconst                                tt11817614
titleType                                  short
primaryTitle      Waarom bleef je niet voor mij?
originalTitle     Waarom bleef je niet voor mij?
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                25
genres                         Documentary,Short
Name: 2000854, dtype: object

(9,)

tconst               tt11817616
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000855, dtype: object

(9,)

tconst               tt11817618
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000856, dtype: object

(9,)

tconst                           tt1181761
titleType                        tvEpisode
primaryTitle      No Time Like the Present
originalTitle     No Time Like the Present
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres                          Reality-TV
Name: 2000857, dtype: object

(9,)

tconst            tt11817620
titleType          tvEpisode
primaryTitle       Roughouts
originalTitle      Roughouts
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2000858, dtype: object

(9,)

tconst               tt11817622
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000859, dtype: object

(9,)

tconst               tt11817624
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000860, dtype: object

(9,)

tconst               tt11817626
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000861, dtype: object

(9,)

tconst               tt11817628
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000862, dtype: object

(9,)

tconst                          tt1181762
titleType                       tvEpisode
primaryTitle                  El problema
originalTitle                 El problema
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2000863, dtype: object

(9,)

tconst               tt11817630
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000864, dtype: object

(9,)

tconst               tt11817632
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000865, dtype: object

(9,)

tconst               tt11817634
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2000866, dtype: object

(9,)

tconst                tt11817636
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000867, dtype: object

(9,)

tconst                                    tt11817638
titleType                                    tvMovie
primaryTitle      Ostatnia droga komendanta Ponurego
originalTitle     Ostatnia droga komendanta Ponurego
isAdult                                            0
startYear                                       1988
endYear                                           \N
runtimeMinutes                                    53
genres                                   Documentary
Name: 2000868, dtype: object

(9,)

tconst                          tt1181763
titleType                       tvEpisode
primaryTitle                   En el 2000
originalTitle                  En el 2000
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2000869, dtype: object

(9,)

tconst                tt11817640
titleType              tvEpisode
primaryTitle      Episode #16.96
originalTitle     Episode #16.96
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2000870, dtype: object

(9,)

tconst                tt11817642
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000871, dtype: object

(9,)

tconst                tt11817644
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000872, dtype: object

(9,)

tconst                tt11817646
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000873, dtype: object

(9,)

tconst                tt11817648
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000874, dtype: object

(9,)

tconst                          tt1181764
titleType                       tvEpisode
primaryTitle             Fallaste corazón
originalTitle            Fallaste corazón
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2000875, dtype: object

(9,)

tconst                tt11817650
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000876, dtype: object

(9,)

tconst                tt11817652
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000877, dtype: object

(9,)

tconst                tt11817654
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000878, dtype: object

(9,)

tconst                tt11817656
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000879, dtype: object

(9,)

tconst                tt11817658
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000880, dtype: object

(9,)

tconst                          tt1181765
titleType                       tvEpisode
primaryTitle              Peligro de amor
originalTitle             Peligro de amor
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2000881, dtype: object

(9,)

tconst                tt11817660
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000882, dtype: object

(9,)

tconst                tt11817664
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000883, dtype: object

(9,)

tconst                tt11817666
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000884, dtype: object

(9,)

tconst                tt11817668
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000885, dtype: object

(9,)

tconst                          tt1181766
titleType                       tvEpisode
primaryTitle           Persiana Americana
originalTitle          Persiana Americana
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2000886, dtype: object

(9,)

tconst                tt11817670
titleType              tvEpisode
primaryTitle      Episode #1.115
originalTitle     Episode #1.115
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000887, dtype: object

(9,)

tconst                tt11817672
titleType              tvEpisode
primaryTitle      Episode #1.117
originalTitle     Episode #1.117
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000888, dtype: object

(9,)

tconst                tt11817674
titleType              tvEpisode
primaryTitle      Episode #1.116
originalTitle     Episode #1.116
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000889, dtype: object

(9,)

tconst                tt11817676
titleType              tvEpisode
primaryTitle      Episode #1.119
originalTitle     Episode #1.119
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000890, dtype: object

(9,)

tconst                tt11817678
titleType              tvEpisode
primaryTitle      Episode #1.118
originalTitle     Episode #1.118
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000891, dtype: object

(9,)

tconst                          tt1181767
titleType                       tvEpisode
primaryTitle                    Que lloro
originalTitle                   Que lloro
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2000892, dtype: object

(9,)

tconst                tt11817680
titleType              tvEpisode
primaryTitle      Episode #1.120
originalTitle     Episode #1.120
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2000893, dtype: object

(9,)

tconst                 tt11817682
titleType               tvEpisode
primaryTitle      Episode #1.1601
originalTitle     Episode #1.1601
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2000894, dtype: object

(9,)

tconst                 tt11817686
titleType               tvEpisode
primaryTitle      Episode #16.110
originalTitle     Episode #16.110
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                         \N
Name: 2000895, dtype: object

(9,)

tconst                                tt11817688
titleType                              tvEpisode
primaryTitle      Episode dated 17 February 2020
originalTitle     Episode dated 17 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2000896, dtype: object

(9,)

tconst                                tt1181768
titleType                             tvEpisode
primaryTitle      Te extraño, te olvido, te amo
originalTitle     Te extraño, te olvido, te amo
isAdult                                       0
startYear                                  2004
endYear                                      \N
runtimeMinutes                               \N
genres                  Action,Adventure,Family
Name: 2000897, dtype: object

(9,)

tconst                        tt11817690
titleType                          video
primaryTitle      Veeblefetzer: La Notte
originalTitle     Veeblefetzer: La Notte
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2000898, dtype: object

(9,)

tconst                   tt11817692
titleType                 tvEpisode
primaryTitle            Randy Chung
originalTitle           Randy Chung
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000899, dtype: object

(9,)

tconst                                                  tt11817694
titleType                                                tvEpisode
primaryTitle      The Horrifying Results of Furby Face Transplants
originalTitle     The Horrifying Results of Furby Face Transplants
isAdult                                                          0
startYear                                                     2020
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                 Documentary
Name: 2000900, dtype: object

(9,)

tconst                     tt11817696
titleType                       short
primaryTitle      Denomination: Dread
originalTitle     Denomination: Dread
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     13
genres                   Horror,Short
Name: 2000901, dtype: object

(9,)

tconst                   tt11817698
titleType                 tvEpisode
primaryTitle         Josh Goodheart
originalTitle        Josh Goodheart
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000902, dtype: object

(9,)

tconst                      tt1181769
titleType                    tvSeries
primaryTitle      Vradya epitheorisis
originalTitle     Vradya epitheorisis
isAdult                             0
startYear                        1984
endYear                            \N
runtimeMinutes                     50
genres                         Comedy
Name: 2000903, dtype: object

(9,)

tconst                   tt11817700
titleType                 tvEpisode
primaryTitle      The Little Cobweb
originalTitle     The Little Cobweb
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2000904, dtype: object

(9,)

tconst            tt11817702
titleType          tvEpisode
primaryTitle      Episodio 1
originalTitle     Episodio 1
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2000905, dtype: object

(9,)

tconst            tt11817704
titleType          tvEpisode
primaryTitle      Episodio 2
originalTitle     Episodio 2
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2000906, dtype: object

(9,)

tconst            tt11817706
titleType              short
primaryTitle      Perfidious
originalTitle     Perfidious
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            15
genres                 Short
Name: 2000907, dtype: object

(9,)

tconst                   tt11817708
titleType                 tvEpisode
primaryTitle         Chad Anheliger
originalTitle        Chad Anheliger
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000908, dtype: object

(9,)

tconst                     tt1181770
titleType                  tvEpisode
primaryTitle           Episode #1.12
originalTitle          Episode #1.12
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2000909, dtype: object

(9,)

tconst            tt11817710
titleType          tvEpisode
primaryTitle      Episodio 3
originalTitle     Episodio 3
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2000910, dtype: object

(9,)

tconst            tt11817712
titleType          tvEpisode
primaryTitle      Episodio 4
originalTitle     Episodio 4
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2000911, dtype: object

(9,)

tconst            tt11817714
titleType          tvEpisode
primaryTitle      Episodio 5
originalTitle     Episodio 5
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2000912, dtype: object

(9,)

tconst             tt11817716
titleType           tvEpisode
primaryTitle        Eurocrime
originalTitle       Eurocrime
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             51
genres            Documentary
Name: 2000913, dtype: object

(9,)

tconst              tt11817718
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000914, dtype: object

(9,)

tconst                tt1181771
titleType             tvEpisode
primaryTitle      An Invitation
originalTitle     An Invitation
isAdult                       0
startYear                  1958
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2000915, dtype: object

(9,)

tconst             tt11817720
titleType           tvEpisode
primaryTitle           Aliens
originalTitle          Aliens
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             50
genres            Documentary
Name: 2000916, dtype: object

(9,)

tconst                     tt11817722
titleType                   tvEpisode
primaryTitle      Twinkle Little Star
originalTitle     Twinkle Little Star
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2000917, dtype: object

(9,)

tconst                     tt11817724
titleType                   tvEpisode
primaryTitle      American Gangster 1
originalTitle     American Gangster 1
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     50
genres                    Documentary
Name: 2000918, dtype: object

(9,)

tconst              tt11817726
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000919, dtype: object

(9,)

tconst                     tt11817728
titleType                   tvEpisode
primaryTitle      American Gangster 2
originalTitle     American Gangster 2
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     49
genres                    Documentary
Name: 2000920, dtype: object

(9,)

tconst             tt1181772
titleType          tvEpisode
primaryTitle      The Escort
originalTitle     The Escort
isAdult                    0
startYear               1958
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2000921, dtype: object

(9,)

tconst             tt11817730
titleType           tvEpisode
primaryTitle       Tijdreizen
originalTitle      Tijdreizen
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             52
genres            Documentary
Name: 2000922, dtype: object

(9,)

tconst              tt11817732
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000923, dtype: object

(9,)

tconst                   tt11817734
titleType                 tvEpisode
primaryTitle         Logan Demmings
originalTitle        Logan Demmings
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Sport
Name: 2000924, dtype: object

(9,)

tconst              tt11817736
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2000925, dtype: object

(9,)

tconst                 tt11817738
titleType               tvEpisode
primaryTitle        Roby Gattiker
originalTitle       Roby Gattiker
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2000926, dtype: object

(9,)

tconst            tt1181773
titleType         tvEpisode
primaryTitle      The Party
originalTitle     The Party
isAdult                   0
startYear              1958
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2000927, dtype: object

(9,)

tconst                    tt11817740
titleType                  tvEpisode
primaryTitle      Fabricio Coloccini
originalTitle     Fabricio Coloccini
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres               Sport,Talk-Show
Name: 2000928, dtype: object

(9,)

tconst               tt11817742
titleType             tvEpisode
primaryTitle      Episode #9.15
originalTitle     Episode #9.15
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000929, dtype: object

(9,)

tconst                 tt11817744
titleType               tvEpisode
primaryTitle       Bebe Contepomi
originalTitle      Bebe Contepomi
isAdult                         0
startYear                    2017
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2000930, dtype: object

(9,)

tconst               tt11817746
titleType             tvEpisode
primaryTitle      Episode #9.16
originalTitle     Episode #9.16
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000931, dtype: object

(9,)

tconst                                       tt11817748
titleType                                     tvEpisode
primaryTitle      Narcissism Disguised as Enlightenment
originalTitle     Narcissism Disguised as Enlightenment
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                             News
Name: 2000932, dtype: object

(9,)

tconst                                tt1181774
titleType                             tvEpisode
primaryTitle      Episode dated 2 February 2008
originalTitle     Episode dated 2 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2000933, dtype: object

(9,)

tconst                                    tt11817750
titleType                                      video
primaryTitle      Sergio Cammariere: Mano nella mano
originalTitle     Sergio Cammariere: Mano nella mano
isAdult                                            0
startYear                                       2014
endYear                                           \N
runtimeMinutes                                     4
genres                                   Music,Short
Name: 2000934, dtype: object

(9,)

tconst                 tt11817752
titleType               tvEpisode
primaryTitle         Magui Aicega
originalTitle        Magui Aicega
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2000935, dtype: object

(9,)

tconst               tt11817754
titleType             tvEpisode
primaryTitle      Episode #9.17
originalTitle     Episode #9.17
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000936, dtype: object

(9,)

tconst                  tt11817756
titleType                tvEpisode
primaryTitle      Mauro Camoranesi
originalTitle     Mauro Camoranesi
isAdult                          0
startYear                     2018
endYear                         \N
runtimeMinutes                  \N
genres             Sport,Talk-Show
Name: 2000937, dtype: object

(9,)

tconst                  tt11817758
titleType                tvEpisode
primaryTitle        Episode #1.786
originalTitle       Episode #1.786
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000938, dtype: object

(9,)

tconst               tt1181775
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2000939, dtype: object

(9,)

tconst               tt11817760
titleType             tvEpisode
primaryTitle      Episode #9.18
originalTitle     Episode #9.18
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000940, dtype: object

(9,)

tconst                                         tt11817762
titleType                                         tvShort
primaryTitle      Ponury, Nurt i ich zolnierze 1943-44 r.
originalTitle     Ponury, Nurt i ich zolnierze 1943-44 r.
isAdult                                                 0
startYear                                            1988
endYear                                                \N
runtimeMinutes                                         16
genres                          Documentary,History,Short
Name: 2000941, dtype: object

(9,)

tconst                  tt11817764
titleType                tvEpisode
primaryTitle        Episode #1.787
originalTitle       Episode #1.787
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000942, dtype: object

(9,)

tconst                     tt11817766
titleType                       short
primaryTitle                   Adamas
originalTitle                  Adamas
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres            Drama,Fantasy,Short
Name: 2000943, dtype: object

(9,)

tconst                           tt11817768
titleType                             short
primaryTitle      Where Little Demons Dwell
originalTitle     Where Little Demons Dwell
isAdult                                   0
startYear                              1985
endYear                                  \N
runtimeMinutes                           24
genres                                Short
Name: 2000944, dtype: object

(9,)

tconst               tt1181776
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2000945, dtype: object

(9,)

tconst                  tt11817770
titleType                tvEpisode
primaryTitle        Episode #1.788
originalTitle       Episode #1.788
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000946, dtype: object

(9,)

tconst                            tt11817772
titleType                          tvEpisode
primaryTitle      Pepi Nana's Favourite List
originalTitle     Pepi Nana's Favourite List
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                                Family
Name: 2000947, dtype: object

(9,)

tconst                  tt11817774
titleType                tvEpisode
primaryTitle        Episode #1.789
originalTitle       Episode #1.789
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000948, dtype: object

(9,)

tconst                              tt11817776
titleType                                video
primaryTitle      Paolo Zanardi: Non dirlo mai
originalTitle     Paolo Zanardi: Non dirlo mai
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                               4
genres                             Music,Short
Name: 2000949, dtype: object

(9,)

tconst               tt1181777
titleType            tvEpisode
primaryTitle      Episode #3.1
originalTitle     Episode #3.1
isAdult                      0
startYear                 1975
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2000950, dtype: object

(9,)

tconst                 tt11817780
titleType               tvEpisode
primaryTitle      Going Backwards
originalTitle     Going Backwards
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2000951, dtype: object

(9,)

tconst                  tt11817782
titleType                tvEpisode
primaryTitle        Episode #1.790
originalTitle       Episode #1.790
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000952, dtype: object

(9,)

tconst                  tt11817784
titleType                tvEpisode
primaryTitle        Episode #1.791
originalTitle       Episode #1.791
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2000953, dtype: object

(9,)

tconst                                tt11817786
titleType                              tvEpisode
primaryTitle      Episode dated 25 February 2020
originalTitle     Episode dated 25 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2000954, dtype: object

(9,)

tconst               tt11817788
titleType             tvEpisode
primaryTitle      Episode #9.19
originalTitle     Episode #9.19
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000955, dtype: object

(9,)

tconst               tt1181778
titleType            tvEpisode
primaryTitle      Episode #3.8
originalTitle     Episode #3.8
isAdult                      0
startYear                 1975
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2000956, dtype: object

(9,)

tconst                tt11817790
titleType              tvEpisode
primaryTitle      Old King Onion
originalTitle     Old King Onion
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2000957, dtype: object

(9,)

tconst                           tt11817792
titleType                         tvEpisode
primaryTitle      Dibillo Visits the Bridge
originalTitle     Dibillo Visits the Bridge
isAdult                                   0
startYear                              2019
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2000958, dtype: object

(9,)

tconst             tt11817794
titleType               short
primaryTitle            Steve
originalTitle           Steve
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             12
genres            Drama,Short
Name: 2000959, dtype: object

(9,)

tconst                         tt11817796
titleType                       tvEpisode
primaryTitle      Colly Wobble's Suitcase
originalTitle     Colly Wobble's Suitcase
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2000960, dtype: object

(9,)

tconst               tt11817798
titleType             tvEpisode
primaryTitle      Episode #9.20
originalTitle     Episode #9.20
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000961, dtype: object

(9,)

tconst               tt1181779
titleType            tvEpisode
primaryTitle      Episode #5.1
originalTitle     Episode #5.1
isAdult                      0
startYear                 1976
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2000962, dtype: object

(9,)

tconst                              tt11817800
titleType                            tvEpisode
primaryTitle      Episode dated 8 October 1999
originalTitle     Episode dated 8 October 1999
isAdult                                      0
startYear                                 1999
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2000963, dtype: object

(9,)

tconst               tt11817802
titleType             videoGame
primaryTitle      Bleeding Edge
originalTitle     Bleeding Edge
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Action
Name: 2000964, dtype: object

(9,)

tconst                          tt11817804
titleType                        tvEpisode
primaryTitle      Little Nana and the Tub!
originalTitle     Little Nana and the Tub!
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2000965, dtype: object

(9,)

tconst                     tt11817806
titleType                   tvEpisode
primaryTitle      A Hole in the Road!
originalTitle     A Hole in the Road!
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2000966, dtype: object

(9,)

tconst               tt11817808
titleType             tvEpisode
primaryTitle      Episode #9.21
originalTitle     Episode #9.21
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000967, dtype: object

(9,)

tconst               tt1181780
titleType            tvEpisode
primaryTitle      Episode #5.7
originalTitle     Episode #5.7
isAdult                      0
startYear                 1976
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2000968, dtype: object

(9,)

tconst                         tt11817810
titleType                       tvEpisode
primaryTitle      Lily Plant's Lovely Day
originalTitle     Lily Plant's Lovely Day
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2000969, dtype: object

(9,)

tconst               tt11817812
titleType             tvEpisode
primaryTitle      Episode #9.22
originalTitle     Episode #9.22
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2000970, dtype: object

(9,)

tconst            tt11817814
titleType              video
primaryTitle        NGod-119
originalTitle       NGod-119
isAdult                    1
startYear               2020
endYear                   \N
runtimeMinutes           121
genres                 Adult
Name: 2000971, dtype: object

(9,)

tconst                        tt11817816
titleType                   tvMiniSeries
primaryTitle      Op reis met Van Rossem
originalTitle     Op reis met Van Rossem
isAdult                                0
startYear                           2009
endYear                             2009
runtimeMinutes                        \N
genres                       Documentary
Name: 2000972, dtype: object

(9,)

tconst                tt11817818
titleType              tvEpisode
primaryTitle      Episode #13.17
originalTitle     Episode #13.17
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2000973, dtype: object

(9,)

tconst                        tt1181781
titleType                     tvEpisode
primaryTitle      William to the Rescue
originalTitle     William to the Rescue
isAdult                               0
startYear                          1994
endYear                              \N
runtimeMinutes                       \N
genres                 Animation,Family
Name: 2000974, dtype: object

(9,)

tconst                tt11817820
titleType              tvEpisode
primaryTitle      Episode #13.18
originalTitle     Episode #13.18
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2000975, dtype: object

(9,)

tconst                                                   tt11817822
titleType                                                     movie
primaryTitle      Don't Try to Understand: A Year in the Life of...
originalTitle     Don't Try to Understand: A Year in the Life of...
isAdult                                                           0
startYear                                                      2021
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                  Documentary
Name: 2000976, dtype: object

(9,)

tconst                tt11817824
titleType              tvEpisode
primaryTitle      Episode #13.19
originalTitle     Episode #13.19
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2000977, dtype: object

(9,)

tconst                tt11817826
titleType              tvEpisode
primaryTitle      Episode #13.20
originalTitle     Episode #13.20
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2000978, dtype: object

(9,)

tconst              tt11817828
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2000979, dtype: object

(9,)

tconst                               tt1181782
titleType                            tvEpisode
primaryTitle      The Presidential Joke Teller
originalTitle     The Presidential Joke Teller
isAdult                                      0
startYear                                 1984
endYear                                     \N
runtimeMinutes                              \N
genres                                  Comedy
Name: 2000980, dtype: object

(9,)

tconst                 tt11817830
titleType                   video
primaryTitle      Milf Craves Cum
originalTitle     Milf Craves Cum
isAdult                         1
startYear                    2008
endYear                        \N
runtimeMinutes                 64
genres                      Adult
Name: 2000981, dtype: object

(9,)

tconst                tt11817832
titleType              tvEpisode
primaryTitle      Episode #13.21
originalTitle     Episode #13.21
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2000982, dtype: object

(9,)

tconst                tt11817834
titleType              tvEpisode
primaryTitle      Episode #13.22
originalTitle     Episode #13.22
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2000983, dtype: object

(9,)

tconst              tt11817836
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2000984, dtype: object

(9,)

tconst                tt11817838
titleType              tvEpisode
primaryTitle      Episode #13.23
originalTitle     Episode #13.23
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2000985, dtype: object

(9,)

tconst                      tt1181783
titleType                   tvEpisode
primaryTitle      The Whole Enchilada
originalTitle     The Whole Enchilada
isAdult                             0
startYear                        1984
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2000986, dtype: object

(9,)

tconst              tt11817840
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2000987, dtype: object

(9,)

tconst            tt11817842
titleType          tvEpisode
primaryTitle             BBW
originalTitle            BBW
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2000988, dtype: object

(9,)

tconst                     tt11817844
titleType                       movie
primaryTitle      In Pursuit of Magic
originalTitle     In Pursuit of Magic
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Adventure,Biography
Name: 2000989, dtype: object

(9,)

tconst                       tt11817846
titleType                     tvEpisode
primaryTitle      Mr. Onion's Storybook
originalTitle     Mr. Onion's Storybook
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                           Family
Name: 2000990, dtype: object

(9,)

tconst                         tt11817848
titleType                       tvEpisode
primaryTitle      Colly Wobble's Flippers
originalTitle     Colly Wobble's Flippers
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2000991, dtype: object

(9,)

tconst                               tt1181784
titleType                            tvEpisode
primaryTitle      The Woman Who Came to Dinner
originalTitle     The Woman Who Came to Dinner
isAdult                                      0
startYear                                 1984
endYear                                     \N
runtimeMinutes                              \N
genres                                  Comedy
Name: 2000992, dtype: object

(9,)

tconst               tt11817850
titleType                 video
primaryTitle      NK: Peligroso
originalTitle     NK: Peligroso
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes                3
genres              Music,Short
Name: 2000993, dtype: object

(9,)

tconst               tt11817852
titleType             tvEpisode
primaryTitle      Episode #8.16
originalTitle     Episode #8.16
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2000994, dtype: object

(9,)

tconst                   tt11817854
titleType                 tvEpisode
primaryTitle      The Sleepy Castle
originalTitle     The Sleepy Castle
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2000995, dtype: object

(9,)

tconst                            tt11817856
titleType                          tvEpisode
primaryTitle      Mr Onion is Ready to Help!
originalTitle     Mr Onion is Ready to Help!
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                                Family
Name: 2000996, dtype: object

(9,)

tconst                      tt11817858
titleType                    tvEpisode
primaryTitle      The Little Lost Star
originalTitle     The Little Lost Star
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                          Family
Name: 2000997, dtype: object

(9,)

tconst                                tt1181785
titleType                                 video
primaryTitle      All In: A Wild Night in Vegas
originalTitle     All In: A Wild Night in Vegas
isAdult                                       1
startYear                                  2006
endYear                                      \N
runtimeMinutes                               90
genres                              Adult,Drama
Name: 2000998, dtype: object

(9,)

tconst                        tt11817860
titleType                      tvEpisode
primaryTitle             Episode #13.134
originalTitle            Episode #13.134
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Comedy,Drama,Game-Show
Name: 2000999, dtype: object

(9,)

tconst               tt11817862
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2001000, dtype: object

(9,)

tconst                             tt11817864
titleType                           tvEpisode
primaryTitle      Stories About Colly Wobble!
originalTitle     Stories About Colly Wobble!
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                 Family
Name: 2001001, dtype: object

(9,)

tconst                tt11817868
titleType              tvEpisode
primaryTitle      Who is Hiding?
originalTitle     Who is Hiding?
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2001002, dtype: object

(9,)

tconst                        tt1181786
titleType                         short
primaryTitle        A Mother's Distress
originalTitle     L'angoisse d'une mère
isAdult                               0
startYear                          1911
endYear                              \N
runtimeMinutes                       \N
genres                      Drama,Short
Name: 2001003, dtype: object

(9,)

tconst                     tt11817870
titleType                tvMiniSeries
primaryTitle      Broeders in Berlijn
originalTitle     Broeders in Berlijn
isAdult                             0
startYear                        2019
endYear                          2019
runtimeMinutes                     40
genres            Documentary,History
Name: 2001004, dtype: object

(9,)

tconst               tt11817872
titleType             tvEpisode
primaryTitle      Episode #8.17
originalTitle     Episode #8.17
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001005, dtype: object

(9,)

tconst                            tt11817874
titleType                          tvEpisode
primaryTitle                     Mai's Wagon
originalTitle                    Mai's Wagon
isAdult                                    0
startYear                               2016
endYear                                   \N
runtimeMinutes                            \N
genres            Adventure,Animation,Comedy
Name: 2001006, dtype: object

(9,)

tconst                  tt11817876
titleType                tvEpisode
primaryTitle        Episode #1.792
originalTitle       Episode #1.792
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001007, dtype: object

(9,)

tconst                          tt11817878
titleType                        tvEpisode
primaryTitle      Dibillo's Happy Birthday
originalTitle     Dibillo's Happy Birthday
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2001008, dtype: object

(9,)

tconst            tt1181787
titleType             short
primaryTitle       Antinoos
originalTitle      Antinoos
isAdult                   0
startYear              1991
endYear                  \N
runtimeMinutes            5
genres                Short
Name: 2001009, dtype: object

(9,)

tconst                  tt11817880
titleType                tvEpisode
primaryTitle        Episode #1.793
originalTitle       Episode #1.793
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001010, dtype: object

(9,)

tconst                  tt11817882
titleType                tvEpisode
primaryTitle        Episode #1.794
originalTitle       Episode #1.794
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001011, dtype: object

(9,)

tconst                               tt11817884
titleType                             tvEpisode
primaryTitle      Moon Baby Crosses the Bridge!
originalTitle     Moon Baby Crosses the Bridge!
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2001012, dtype: object

(9,)

tconst                          tt11817886
titleType                        tvEpisode
primaryTitle      The Upside-Down Princess
originalTitle     The Upside-Down Princess
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2001013, dtype: object

(9,)

tconst                                     tt11817888
titleType                                   tvEpisode
primaryTitle      Little Nana's Quiet and Noisy Story
originalTitle     Little Nana's Quiet and Noisy Story
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                         Family
Name: 2001014, dtype: object

(9,)

tconst            tt1181788
titleType             short
primaryTitle      Ascension
originalTitle     Ascension
isAdult                   0
startYear              1999
endYear                  \N
runtimeMinutes            3
genres                Short
Name: 2001015, dtype: object

(9,)

tconst               tt11817890
titleType             tvEpisode
primaryTitle      Episode #8.18
originalTitle     Episode #8.18
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001016, dtype: object

(9,)

tconst                                 tt11817892
titleType                               tvEpisode
primaryTitle      Episode dated 27 September 2019
originalTitle     Episode dated 27 September 2019
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2001017, dtype: object

(9,)

tconst                                   tt11817896
titleType                                 tvEpisode
primaryTitle      Mr. Onion and Dibillo in the Tub!
originalTitle     Mr. Onion and Dibillo in the Tub!
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Family
Name: 2001018, dtype: object

(9,)

tconst                                tt11817898
titleType                              tvEpisode
primaryTitle      Episode dated 16 December 2019
originalTitle     Episode dated 16 December 2019
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001019, dtype: object

(9,)

tconst                                                    tt1181789
titleType                                                     video
primaryTitle      The B-52's Time Capsule: Videos for a Future G...
originalTitle     The B-52's Time Capsule: Videos for a Future G...
isAdult                                                           0
startYear                                                      1998
endYear                                                          \N
runtimeMinutes                                                   60
genres                                                        Music
Name: 2001020, dtype: object

(9,)

tconst                                tt11817900
titleType                              tvEpisode
primaryTitle      Episode dated 26 November 2019
originalTitle     Episode dated 26 November 2019
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001021, dtype: object

(9,)

tconst                                 tt11817902
titleType                               tvEpisode
primaryTitle      Colly Wobble's Wellington Boots
originalTitle     Colly Wobble's Wellington Boots
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Family
Name: 2001022, dtype: object

(9,)

tconst                                tt11817904
titleType                              tvEpisode
primaryTitle      Episode dated 12 December 2019
originalTitle     Episode dated 12 December 2019
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001023, dtype: object

(9,)

tconst            tt11817906
titleType          tvEpisode
primaryTitle        Balloons
originalTitle       Balloons
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2001024, dtype: object

(9,)

tconst             tt11817908
titleType               short
primaryTitle         Devotion
originalTitle        Devotion
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              9
genres            Drama,Short
Name: 2001025, dtype: object

(9,)

tconst                            tt1181790
titleType                             movie
primaryTitle      The Billionaire's Vinegar
originalTitle     The Billionaire's Vinegar
isAdult                                   0
startYear                                \N
endYear                                  \N
runtimeMinutes                           \N
genres                                Drama
Name: 2001026, dtype: object

(9,)

tconst                   tt11817912
titleType                 tvEpisode
primaryTitle      Favourite Stories
originalTitle     Favourite Stories
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2001027, dtype: object

(9,)

tconst                              tt11817914
titleType                            tvEpisode
primaryTitle      Episode dated 16 August 2019
originalTitle     Episode dated 16 August 2019
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2001028, dtype: object

(9,)

tconst                tt11817916
titleType              videoGame
primaryTitle      The Pedestrian
originalTitle     The Pedestrian
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Adventure
Name: 2001029, dtype: object

(9,)

tconst                              tt11817918
titleType                            tvEpisode
primaryTitle      Episode dated 20 August 2019
originalTitle     Episode dated 20 August 2019
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2001030, dtype: object

(9,)

tconst                       tt1181791
titleType                        movie
primaryTitle               Black Death
originalTitle              Black Death
isAdult                              0
startYear                         2010
endYear                             \N
runtimeMinutes                     102
genres            Action,Drama,History
Name: 2001031, dtype: object

(9,)

tconst                    tt11817920
titleType                  tvEpisode
primaryTitle            Episode #7.2
originalTitle           Episode #7.2
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001032, dtype: object

(9,)

tconst                    tt11817922
titleType                  tvEpisode
primaryTitle            Episode #7.3
originalTitle           Episode #7.3
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001033, dtype: object

(9,)

tconst               tt11817924
titleType             tvEpisode
primaryTitle      Episode #8.19
originalTitle     Episode #8.19
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001034, dtype: object

(9,)

tconst                                tt11817926
titleType                              tvEpisode
primaryTitle      Episode dated 10 December 2019
originalTitle     Episode dated 10 December 2019
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001035, dtype: object

(9,)

tconst                    tt11817928
titleType                  tvEpisode
primaryTitle            Episode #7.5
originalTitle           Episode #7.5
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001036, dtype: object

(9,)

tconst              tt1181792
titleType               short
primaryTitle            Blind
originalTitle           Blind
isAdult                     0
startYear                1912
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2001037, dtype: object

(9,)

tconst                    tt11817930
titleType                  tvEpisode
primaryTitle            Episode #7.4
originalTitle           Episode #7.4
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001038, dtype: object

(9,)

tconst                          tt11817932
titleType                        tvEpisode
primaryTitle      Episode dated 8 May 2019
originalTitle     Episode dated 8 May 2019
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          \N
genres                                  \N
Name: 2001039, dtype: object

(9,)

tconst                                tt11817934
titleType                              tvEpisode
primaryTitle      Episode dated 25 February 2019
originalTitle     Episode dated 25 February 2019
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001040, dtype: object

(9,)

tconst              tt11817936
titleType            tvEpisode
primaryTitle      Eau secours!
originalTitle     Eau secours!
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              24
genres                  Family
Name: 2001041, dtype: object

(9,)

tconst               tt11817938
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               40
genres                    Crime
Name: 2001042, dtype: object

(9,)

tconst                                             tt1181793
titleType                                              video
primaryTitle      Blumfeld: Nackter als nackt/Live in Berlin
originalTitle     Blumfeld: Nackter als nackt/Live in Berlin
isAdult                                                    0
startYear                                               2007
endYear                                                   \N
runtimeMinutes                                           110
genres                                                 Music
Name: 2001043, dtype: object

(9,)

tconst                                           tt11817940
titleType                                             short
primaryTitle      The Real Rich Wives of Some City in Texas
originalTitle     The Real Rich Wives of Some City in Texas
isAdult                                                   0
startYear                                              2020
endYear                                                  \N
runtimeMinutes                                            6
genres                              Comedy,Reality-TV,Short
Name: 2001044, dtype: object

(9,)

tconst                    tt11817944
titleType                  tvEpisode
primaryTitle            Episode #7.7
originalTitle           Episode #7.7
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001045, dtype: object

(9,)

tconst                    tt11817946
titleType                  tvEpisode
primaryTitle            Episode #7.8
originalTitle           Episode #7.8
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001046, dtype: object

(9,)

tconst                    tt11817948
titleType                  tvEpisode
primaryTitle            Episode #7.6
originalTitle           Episode #7.6
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001047, dtype: object

(9,)

tconst                   tt1181794
titleType                tvSpecial
primaryTitle      Brit Awards 2008
originalTitle     Brit Awards 2008
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                       Music
Name: 2001048, dtype: object

(9,)

tconst                    tt11817950
titleType                  tvEpisode
primaryTitle            Episode #7.9
originalTitle           Episode #7.9
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001049, dtype: object

(9,)

tconst                    tt11817952
titleType                  tvEpisode
primaryTitle           Episode #7.10
originalTitle          Episode #7.10
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001050, dtype: object

(9,)

tconst                    tt11817954
titleType                  tvEpisode
primaryTitle           Episode #7.12
originalTitle          Episode #7.12
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001051, dtype: object

(9,)

tconst                    tt11817956
titleType                  tvEpisode
primaryTitle           Episode #7.11
originalTitle          Episode #7.11
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001052, dtype: object

(9,)

tconst                    tt11817958
titleType                  tvEpisode
primaryTitle           Episode #7.13
originalTitle          Episode #7.13
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001053, dtype: object

(9,)

tconst                        tt1181795
titleType                         movie
primaryTitle                    Bunraku
originalTitle                   Bunraku
isAdult                               0
startYear                          2010
endYear                              \N
runtimeMinutes                      124
genres            Action,Drama,Thriller
Name: 2001054, dtype: object

(9,)

tconst                    tt11817960
titleType                  tvEpisode
primaryTitle           Episode #7.15
originalTitle          Episode #7.15
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001055, dtype: object

(9,)

tconst                    tt11817962
titleType                  tvEpisode
primaryTitle           Episode #7.16
originalTitle          Episode #7.16
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001056, dtype: object

(9,)

tconst                    tt11817964
titleType                  tvEpisode
primaryTitle           Episode #7.14
originalTitle          Episode #7.14
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001057, dtype: object

(9,)

tconst                    tt11817966
titleType                  tvEpisode
primaryTitle            Episode #8.2
originalTitle           Episode #8.2
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001058, dtype: object

(9,)

tconst                    tt11817968
titleType                  tvEpisode
primaryTitle            Episode #8.4
originalTitle           Episode #8.4
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001059, dtype: object

(9,)

tconst                        tt1181796
titleType                         short
primaryTitle      Chief Fire Eye's Game
originalTitle     Chief Fire Eye's Game
isAdult                               0
startYear                          1911
endYear                              \N
runtimeMinutes                       \N
genres                    Short,Western
Name: 2001060, dtype: object

(9,)

tconst                    tt11817970
titleType                  tvEpisode
primaryTitle            Episode #8.3
originalTitle           Episode #8.3
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001061, dtype: object

(9,)

tconst                    tt11817972
titleType                  tvEpisode
primaryTitle            Episode #8.6
originalTitle           Episode #8.6
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001062, dtype: object

(9,)

tconst                    tt11817974
titleType                  tvEpisode
primaryTitle            Episode #8.5
originalTitle           Episode #8.5
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001063, dtype: object

(9,)

tconst                    tt11817976
titleType                  tvEpisode
primaryTitle            Episode #8.7
originalTitle           Episode #8.7
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001064, dtype: object

(9,)

tconst                    tt11817978
titleType                  tvEpisode
primaryTitle            Episode #8.8
originalTitle           Episode #8.8
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001065, dtype: object

(9,)

tconst                               tt1181797
titleType                                short
primaryTitle      Clark's Capture of Kaskaskia
originalTitle     Clark's Capture of Kaskaskia
isAdult                                      0
startYear                                 1911
endYear                                     \N
runtimeMinutes                              \N
genres                         Drama,Short,War
Name: 2001066, dtype: object

(9,)

tconst                    tt11817980
titleType                  tvEpisode
primaryTitle           Episode #8.11
originalTitle          Episode #8.11
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001067, dtype: object

(9,)

tconst                    tt11817982
titleType                  tvEpisode
primaryTitle           Episode #8.12
originalTitle          Episode #8.12
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001068, dtype: object

(9,)

tconst                    tt11817984
titleType                  tvEpisode
primaryTitle            Episode #8.9
originalTitle           Episode #8.9
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001069, dtype: object

(9,)

tconst                    tt11817986
titleType                  tvEpisode
primaryTitle           Episode #8.10
originalTitle          Episode #8.10
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001070, dtype: object

(9,)

tconst                    tt11817988
titleType                  tvEpisode
primaryTitle           Episode #8.15
originalTitle          Episode #8.15
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001071, dtype: object

(9,)

tconst                             tt1181798
titleType                              video
primaryTitle      The Clash: Music in Review
originalTitle     The Clash: Music in Review
isAdult                                    0
startYear                               2007
endYear                                   \N
runtimeMinutes                            67
genres                     Documentary,Music
Name: 2001072, dtype: object

(9,)

tconst                    tt11817990
titleType                  tvEpisode
primaryTitle           Episode #8.14
originalTitle          Episode #8.14
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001073, dtype: object

(9,)

tconst                    tt11817992
titleType                  tvEpisode
primaryTitle           Episode #8.13
originalTitle          Episode #8.13
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001074, dtype: object

(9,)

tconst                    tt11817994
titleType                  tvEpisode
primaryTitle           Episode #8.16
originalTitle          Episode #8.16
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001075, dtype: object

(9,)

tconst                    tt11817996
titleType                  tvEpisode
primaryTitle            Episode #9.4
originalTitle           Episode #9.4
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001076, dtype: object

(9,)

tconst                    tt11817998
titleType                  tvEpisode
primaryTitle            Episode #9.2
originalTitle           Episode #9.2
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001077, dtype: object

(9,)

tconst                                        tt1181799
titleType                                         video
primaryTitle      The Clash: The Clash's London Calling
originalTitle     The Clash: The Clash's London Calling
isAdult                                               0
startYear                                          2006
endYear                                              \N
runtimeMinutes                                       70
genres                                            Music
Name: 2001078, dtype: object

(9,)

tconst                    tt11818000
titleType                  tvEpisode
primaryTitle            Episode #9.3
originalTitle           Episode #9.3
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001079, dtype: object

(9,)

tconst                    tt11818002
titleType                  tvEpisode
primaryTitle            Episode #9.5
originalTitle           Episode #9.5
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001080, dtype: object

(9,)

tconst                    tt11818004
titleType                  tvEpisode
primaryTitle            Episode #9.6
originalTitle           Episode #9.6
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001081, dtype: object

(9,)

tconst                    tt11818006
titleType                  tvEpisode
primaryTitle            Episode #9.8
originalTitle           Episode #9.8
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001082, dtype: object

(9,)

tconst                    tt11818008
titleType                  tvEpisode
primaryTitle            Episode #9.7
originalTitle           Episode #9.7
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001083, dtype: object

(9,)

tconst                                         tt1181800
titleType                                          video
primaryTitle      The Clash: Tory Crimes and Other Tales
originalTitle     The Clash: Tory Crimes and Other Tales
isAdult                                                0
startYear                                           2008
endYear                                               \N
runtimeMinutes                                       115
genres                                             Music
Name: 2001084, dtype: object

(9,)

tconst                    tt11818010
titleType                  tvEpisode
primaryTitle            Episode #9.9
originalTitle           Episode #9.9
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001085, dtype: object

(9,)

tconst                    tt11818012
titleType                  tvEpisode
primaryTitle           Episode #9.11
originalTitle          Episode #9.11
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001086, dtype: object

(9,)

tconst                    tt11818014
titleType                  tvEpisode
primaryTitle           Episode #9.10
originalTitle          Episode #9.10
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001087, dtype: object

(9,)

tconst                    tt11818016
titleType                  tvEpisode
primaryTitle           Episode #9.12
originalTitle          Episode #9.12
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001088, dtype: object

(9,)

tconst                    tt11818018
titleType                  tvEpisode
primaryTitle           Episode #9.13
originalTitle          Episode #9.13
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001089, dtype: object

(9,)

tconst                               tt1181801
titleType                                video
primaryTitle      Clash: Up Close and Personal
originalTitle     Clash: Up Close and Personal
isAdult                                      0
startYear                                 2006
endYear                                     \N
runtimeMinutes                              57
genres             Biography,Documentary,Music
Name: 2001090, dtype: object

(9,)

tconst                    tt11818020
titleType                  tvEpisode
primaryTitle           Episode #9.15
originalTitle          Episode #9.15
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001091, dtype: object

(9,)

tconst                    tt11818022
titleType                  tvEpisode
primaryTitle           Episode #9.14
originalTitle          Episode #9.14
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001092, dtype: object

(9,)

tconst                    tt11818024
titleType                  tvEpisode
primaryTitle           Episode #9.16
originalTitle          Episode #9.16
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001093, dtype: object

(9,)

tconst                    tt11818026
titleType                  tvEpisode
primaryTitle           Episode #9.18
originalTitle          Episode #9.18
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001094, dtype: object

(9,)

tconst                    tt11818028
titleType                  tvEpisode
primaryTitle           Episode #9.17
originalTitle          Episode #9.17
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001095, dtype: object

(9,)

tconst                                  tt1181802
titleType                                   short
primaryTitle      Col. E.D. Baker, 1st California
originalTitle     Col. E.D. Baker, 1st California
isAdult                                         0
startYear                                    1911
endYear                                        \N
runtimeMinutes                                 \N
genres                            Drama,Short,War
Name: 2001096, dtype: object

(9,)

tconst                    tt11818030
titleType                  tvEpisode
primaryTitle           Episode #9.20
originalTitle          Episode #9.20
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001097, dtype: object

(9,)

tconst               tt11818032
titleType                 short
primaryTitle          Gemseeker
originalTitle         Gemseeker
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Fantasy,Short
Name: 2001098, dtype: object

(9,)

tconst                    tt11818034
titleType                  tvEpisode
primaryTitle           Episode #9.19
originalTitle          Episode #9.19
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001099, dtype: object

(9,)

tconst                  tt11818036
titleType                tvEpisode
primaryTitle      15 bile negre #2
originalTitle     15 bile negre #2
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  41
genres                      Comedy
Name: 2001100, dtype: object

(9,)

tconst                    tt11818038
titleType                  tvEpisode
primaryTitle           Episode #10.3
originalTitle          Episode #10.3
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001101, dtype: object

(9,)

tconst                   tt1181803
titleType                    short
primaryTitle      The Cossack Duke
originalTitle         Kosakfyrsten
isAdult                          0
startYear                     1911
endYear                         \N
runtimeMinutes                  \N
genres                 Drama,Short
Name: 2001102, dtype: object

(9,)

tconst                    tt11818040
titleType                  tvEpisode
primaryTitle           Episode #10.2
originalTitle          Episode #10.2
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001103, dtype: object

(9,)

tconst                    tt11818042
titleType                  tvEpisode
primaryTitle           Episode #10.5
originalTitle          Episode #10.5
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001104, dtype: object

(9,)

tconst                    tt11818044
titleType                  tvEpisode
primaryTitle           Episode #10.4
originalTitle          Episode #10.4
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001105, dtype: object

(9,)

tconst                    tt11818048
titleType                  tvEpisode
primaryTitle           Episode #10.6
originalTitle          Episode #10.6
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001106, dtype: object

(9,)

tconst                        tt1181804
titleType                         video
primaryTitle      Dave Gahan: Hourglass
originalTitle     Dave Gahan: Hourglass
isAdult                               0
startYear                          2007
endYear                              \N
runtimeMinutes                       45
genres                Documentary,Music
Name: 2001107, dtype: object

(9,)

tconst                    tt11818050
titleType                  tvEpisode
primaryTitle           Episode #10.7
originalTitle          Episode #10.7
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001108, dtype: object

(9,)

tconst                    tt11818052
titleType                  tvEpisode
primaryTitle           Episode #10.9
originalTitle          Episode #10.9
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001109, dtype: object

(9,)

tconst                    tt11818054
titleType                  tvEpisode
primaryTitle          Episode #10.11
originalTitle         Episode #10.11
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001110, dtype: object

(9,)

tconst                    tt11818056
titleType                  tvEpisode
primaryTitle          Episode #10.10
originalTitle         Episode #10.10
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001111, dtype: object

(9,)

tconst                    tt11818058
titleType                  tvEpisode
primaryTitle           Episode #10.8
originalTitle          Episode #10.8
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001112, dtype: object

(9,)

tconst                                                    tt1181805
titleType                                                     video
primaryTitle      Deine Lakaien & Die Neue Philharmonie Frankfur...
originalTitle     Deine Lakaien & Die Neue Philharmonie Frankfur...
isAdult                                                           0
startYear                                                      2007
endYear                                                          \N
runtimeMinutes                                                  360
genres                                                        Music
Name: 2001113, dtype: object

(9,)

tconst                    tt11818060
titleType                  tvEpisode
primaryTitle          Episode #10.13
originalTitle         Episode #10.13
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001114, dtype: object

(9,)

tconst                    tt11818062
titleType                  tvEpisode
primaryTitle          Episode #10.15
originalTitle         Episode #10.15
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001115, dtype: object

(9,)

tconst                    tt11818064
titleType                  tvEpisode
primaryTitle          Episode #10.12
originalTitle         Episode #10.12
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001116, dtype: object

(9,)

tconst                    tt11818066
titleType                  tvEpisode
primaryTitle          Episode #10.16
originalTitle         Episode #10.16
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001117, dtype: object

(9,)

tconst                    tt11818068
titleType                  tvEpisode
primaryTitle          Episode #10.14
originalTitle         Episode #10.14
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001118, dtype: object

(9,)

tconst                                                    tt1181806
titleType                                                     video
primaryTitle      Deine Lakaien - Live in Concert: White Lies-To...
originalTitle     Deine Lakaien - Live in Concert: White Lies-To...
isAdult                                                           0
startYear                                                      2003
endYear                                                          \N
runtimeMinutes                                                  116
genres                                                        Music
Name: 2001119, dtype: object

(9,)

tconst                    tt11818070
titleType                  tvEpisode
primaryTitle          Episode #10.17
originalTitle         Episode #10.17
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001120, dtype: object

(9,)

tconst                    tt11818072
titleType                  tvEpisode
primaryTitle          Episode #10.18
originalTitle         Episode #10.18
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001121, dtype: object

(9,)

tconst                    tt11818074
titleType                  tvEpisode
primaryTitle          Episode #10.19
originalTitle         Episode #10.19
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001122, dtype: object

(9,)

tconst                    tt11818076
titleType                  tvEpisode
primaryTitle          Episode #10.20
originalTitle         Episode #10.20
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001123, dtype: object

(9,)

tconst                  tt11818078
titleType                tvEpisode
primaryTitle        Episode #1.795
originalTitle       Episode #1.795
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001124, dtype: object

(9,)

tconst                      tt1181807
titleType                       short
primaryTitle        The Two Gardeners
originalTitle     Les deux jardiniers
isAdult                             0
startYear                        1911
endYear                            \N
runtimeMinutes                     \N
genres                   Comedy,Short
Name: 2001125, dtype: object

(9,)

tconst                    tt11818080
titleType                  tvEpisode
primaryTitle           Episode #11.3
originalTitle          Episode #11.3
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001126, dtype: object

(9,)

tconst                    tt11818082
titleType                  tvEpisode
primaryTitle           Episode #11.2
originalTitle          Episode #11.2
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001127, dtype: object

(9,)

tconst                    tt11818084
titleType                  tvEpisode
primaryTitle           Episode #11.4
originalTitle          Episode #11.4
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001128, dtype: object

(9,)

tconst                  tt11818086
titleType                tvEpisode
primaryTitle        Episode #1.796
originalTitle       Episode #1.796
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001129, dtype: object

(9,)

tconst                    tt11818088
titleType                  tvEpisode
primaryTitle           Episode #11.6
originalTitle          Episode #11.6
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001130, dtype: object

(9,)

tconst              tt1181808
titleType               short
primaryTitle            Dewey
originalTitle           Dewey
isAdult                     0
startYear                1911
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2001131, dtype: object

(9,)

tconst                    tt11818090
titleType                  tvEpisode
primaryTitle           Episode #11.5
originalTitle          Episode #11.5
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001132, dtype: object

(9,)

tconst                    tt11818092
titleType                  tvEpisode
primaryTitle           Episode #11.7
originalTitle          Episode #11.7
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001133, dtype: object

(9,)

tconst                    tt11818094
titleType                  tvEpisode
primaryTitle           Episode #11.8
originalTitle          Episode #11.8
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001134, dtype: object

(9,)

tconst                    tt11818096
titleType                  tvEpisode
primaryTitle           Episode #11.9
originalTitle          Episode #11.9
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001135, dtype: object

(9,)

tconst                  tt11818098
titleType                tvEpisode
primaryTitle        Episode #1.797
originalTitle       Episode #1.797
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001136, dtype: object

(9,)

tconst                        tt1181809
titleType                         short
primaryTitle      The Diamond Smugglers
originalTitle     The Diamond Smugglers
isAdult                               0
startYear                          1911
endYear                              \N
runtimeMinutes                       \N
genres                      Drama,Short
Name: 2001137, dtype: object

(9,)

tconst                    tt11818100
titleType                  tvEpisode
primaryTitle          Episode #11.11
originalTitle         Episode #11.11
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001138, dtype: object

(9,)

tconst                    tt11818102
titleType                  tvEpisode
primaryTitle          Episode #11.12
originalTitle         Episode #11.12
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001139, dtype: object

(9,)

tconst                    tt11818104
titleType                  tvEpisode
primaryTitle          Episode #11.10
originalTitle         Episode #11.10
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2001140, dtype: object

(9,)

tconst                        tt11818106
titleType                          video
primaryTitle      Hollywood So Not White
originalTitle     Hollywood So Not White
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                             Short
Name: 2001141, dtype: object

(9,)

tconst             tt11818108
titleType               short
primaryTitle              Duo
originalTitle             Duo
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             15
genres            Drama,Short
Name: 2001142, dtype: object

(9,)

tconst                         tt1181810
titleType                        tvMovie
primaryTitle      Divorce: Shariah Style
originalTitle     Divorce: Shariah Style
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        60
genres                       Documentary
Name: 2001143, dtype: object

(9,)

tconst                  tt11818110
titleType                tvEpisode
primaryTitle        Episode #1.798
originalTitle       Episode #1.798
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001144, dtype: object

(9,)

tconst                  tt11818112
titleType                tvEpisode
primaryTitle        Episode #1.799
originalTitle       Episode #1.799
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001145, dtype: object

(9,)

tconst                  tt11818114
titleType                tvEpisode
primaryTitle        Episode #1.800
originalTitle       Episode #1.800
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001146, dtype: object

(9,)

tconst                  tt11818116
titleType                tvEpisode
primaryTitle        Episode #1.801
originalTitle       Episode #1.801
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001147, dtype: object

(9,)

tconst                 tt11818118
titleType                   movie
primaryTitle      Mon Oncle Patof
originalTitle     Mon Oncle Patof
isAdult                         0
startYear                    2021
endYear                        \N
runtimeMinutes                 \N
genres                Documentary
Name: 2001148, dtype: object

(9,)

tconst                    tt1181811
titleType                     movie
primaryTitle       Drent und Herent
originalTitle      Drent und Herent
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   86
genres            Documentary,Sport
Name: 2001149, dtype: object

(9,)

tconst              tt11818120
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2001150, dtype: object

(9,)

tconst               tt11818122
titleType             tvEpisode
primaryTitle      Episode #2.23
originalTitle     Episode #2.23
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Comedy,Family
Name: 2001151, dtype: object

(9,)

tconst                            tt11818124
titleType                              video
primaryTitle      Thirsty for Some Titties 3
originalTitle     Thirsty for Some Titties 3
isAdult                                    1
startYear                               2018
endYear                                   \N
runtimeMinutes                           203
genres                                 Adult
Name: 2001152, dtype: object

(9,)

tconst                                            tt11818126
titleType                                          tvEpisode
primaryTitle      Rio Fredrika Meets a Giant Praying Mantis!
originalTitle     Rio Fredrika Meets a Giant Praying Mantis!
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                             Game-Show
Name: 2001153, dtype: object

(9,)

tconst             tt11818128
titleType           tvEpisode
primaryTitle      North Wales
originalTitle     North Wales
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2001154, dtype: object

(9,)

tconst                      tt1181812
titleType                       movie
primaryTitle      Egefalika epeisodia
originalTitle     Egefalika epeisodia
isAdult                             0
startYear                        1978
endYear                            \N
runtimeMinutes                     50
genres                             \N
Name: 2001155, dtype: object

(9,)

tconst            tt11818130
titleType          tvEpisode
primaryTitle      Episodio 6
originalTitle     Episodio 6
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001156, dtype: object

(9,)

tconst            tt11818132
titleType          tvEpisode
primaryTitle      Episodio 7
originalTitle     Episodio 7
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001157, dtype: object

(9,)

tconst                  tt11818134
titleType                tvEpisode
primaryTitle        Episode #1.802
originalTitle       Episode #1.802
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001158, dtype: object

(9,)

tconst                  tt11818136
titleType                tvEpisode
primaryTitle        Episode #1.803
originalTitle       Episode #1.803
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001159, dtype: object

(9,)

tconst                  tt11818138
titleType                tvEpisode
primaryTitle        Episode #1.804
originalTitle       Episode #1.804
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001160, dtype: object

(9,)

tconst                  tt1181813
titleType                   video
primaryTitle      Falco Symphonic
originalTitle     Falco Symphonic
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 56
genres                      Music
Name: 2001161, dtype: object

(9,)

tconst                  tt11818140
titleType                tvEpisode
primaryTitle        Episode #1.805
originalTitle       Episode #1.805
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001162, dtype: object

(9,)

tconst               tt11818142
titleType                 movie
primaryTitle      Unforgettable
originalTitle     Unforgettable
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2001163, dtype: object

(9,)

tconst                  tt11818144
titleType                tvEpisode
primaryTitle        Episode #1.806
originalTitle       Episode #1.806
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001164, dtype: object

(9,)

tconst              tt11818146
titleType                short
primaryTitle      Almost There
originalTitle     Almost There
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              14
genres                   Short
Name: 2001165, dtype: object

(9,)

tconst                  tt11818148
titleType                tvEpisode
primaryTitle        Episode #1.807
originalTitle       Episode #1.807
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001166, dtype: object

(9,)

tconst                     tt1181814
titleType                      video
primaryTitle      Fuck Me If You Can
originalTitle     Fuck Me If You Can
isAdult                            1
startYear                       2005
endYear                           \N
runtimeMinutes                    90
genres                         Adult
Name: 2001167, dtype: object

(9,)

tconst              tt11818150
titleType                short
primaryTitle      Interception
originalTitle     Interception
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Short
Name: 2001168, dtype: object

(9,)

tconst              tt11818152
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              29
genres             Documentary
Name: 2001169, dtype: object

(9,)

tconst                      tt11818154
titleType                    tvEpisode
primaryTitle      Rizmo 4: A New Hope!
originalTitle     Rizmo 4: A New Hope!
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                     154
genres                          Comedy
Name: 2001170, dtype: object

(9,)

tconst               tt11818156
titleType                 short
primaryTitle      That Was Easy
originalTitle     That Was Easy
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Short
Name: 2001171, dtype: object

(9,)

tconst            tt11818158
titleType          tvEpisode
primaryTitle      Episodio 8
originalTitle     Episodio 8
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001172, dtype: object

(9,)

tconst                                                  tt1181815
titleType                                                 tvShort
primaryTitle      Giles Wemmbley Hogg Goes Off.... to Glastonbury
originalTitle     Giles Wemmbley Hogg Goes Off.... to Glastonbury
isAdult                                                         0
startYear                                                    2007
endYear                                                        \N
runtimeMinutes                                                 27
genres                                                     Comedy
Name: 2001173, dtype: object

(9,)

tconst                       tt11818160
titleType                      tvSeries
primaryTitle      What's Your Medicine?
originalTitle     What's Your Medicine?
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres                       Reality-TV
Name: 2001174, dtype: object

(9,)

tconst                      tt11818162
titleType                    tvEpisode
primaryTitle             Episode #16.2
originalTitle            Episode #16.2
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      59
genres            Game-Show,Reality-TV
Name: 2001175, dtype: object

(9,)

tconst            tt11818164
titleType          tvEpisode
primaryTitle      Episodio 9
originalTitle     Episodio 9
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001176, dtype: object

(9,)

tconst             tt11818166
titleType           tvEpisode
primaryTitle      Episodio 10
originalTitle     Episodio 10
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2001177, dtype: object

(9,)

tconst                     tt11818168
titleType                    tvSeries
primaryTitle      Remy Bear & Friends
originalTitle     Remy Bear & Friends
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     10
genres                      Animation
Name: 2001178, dtype: object

(9,)

tconst                             tt1181816
titleType                              short
primaryTitle      The Waist Coat with Points
originalTitle             Le gilet à pointes
isAdult                                    0
startYear                               1911
endYear                                   \N
runtimeMinutes                            \N
genres                          Comedy,Short
Name: 2001179, dtype: object

(9,)

tconst              tt11818170
titleType                short
primaryTitle      The Necklace
originalTitle     The Necklace
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Short
Name: 2001180, dtype: object

(9,)

tconst                     tt11818172
titleType                       video
primaryTitle      Don't Tell My Wife!
originalTitle     Don't Tell My Wife!
isAdult                             1
startYear                        2019
endYear                            \N
runtimeMinutes                    117
genres            Adult,Drama,Romance
Name: 2001181, dtype: object

(9,)

tconst                      tt11818174
titleType                    tvEpisode
primaryTitle             Episode #16.3
originalTitle            Episode #16.3
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      29
genres            Game-Show,Reality-TV
Name: 2001182, dtype: object

(9,)

tconst            tt11818176
titleType              short
primaryTitle          Framed
originalTitle         Framed
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2001183, dtype: object

(9,)

tconst             tt11818178
titleType           tvEpisode
primaryTitle           Fuochi
originalTitle          Fuochi
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             \N
genres            Crime,Drama
Name: 2001184, dtype: object

(9,)

tconst                             tt1181817
titleType                              video
primaryTitle      God's Will: The Sex Factor
originalTitle     God's Will: The Sex Factor
isAdult                                    1
startYear                               2006
endYear                                   \N
runtimeMinutes                           120
genres                  Adult,Comedy,Fantasy
Name: 2001185, dtype: object

(9,)

tconst                  tt11818180
titleType                tvEpisode
primaryTitle        Episode #1.808
originalTitle       Episode #1.808
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001186, dtype: object

(9,)

tconst                                                   tt11818182
titleType                                                 tvEpisode
primaryTitle      The Secrets of Big Tobacco: Has Philip Morris ...
originalTitle     The Secrets of Big Tobacco: Has Philip Morris ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   26
genres                                             Documentary,News
Name: 2001187, dtype: object

(9,)

tconst              tt11818184
titleType                short
primaryTitle      Interference
originalTitle     Interference
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Short
Name: 2001188, dtype: object

(9,)

tconst             tt11818186
titleType           tvEpisode
primaryTitle            Vuoto
originalTitle           Vuoto
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Crime,Drama
Name: 2001189, dtype: object

(9,)

tconst                         tt11818188
titleType                        tvSeries
primaryTitle      Mnet Asian Music Awards
originalTitle     Mnet Asian Music Awards
isAdult                                 0
startYear                            1999
endYear                                \N
runtimeMinutes                        280
genres                              Music
Name: 2001190, dtype: object

(9,)

tconst                              tt1181818
titleType                               video
primaryTitle        Grand Union: A Short Film
originalTitle       Grand Union: A Short Film
isAdult                                     0
startYear                                2006
endYear                                    \N
runtimeMinutes                             21
genres            Biography,Documentary,Music
Name: 2001191, dtype: object

(9,)

tconst                             tt11818190
titleType                           tvEpisode
primaryTitle      Episode dated 15 April 2018
originalTitle     Episode dated 15 April 2018
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2001192, dtype: object

(9,)

tconst            tt11818192
titleType              short
primaryTitle       Stake Out
originalTitle      Stake Out
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2001193, dtype: object

(9,)

tconst                   tt11818194
titleType                 tvEpisode
primaryTitle      Rose rosse per te
originalTitle     Rose rosse per te
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                  Crime,Drama
Name: 2001194, dtype: object

(9,)

tconst                           tt11818196
titleType                         tvEpisode
primaryTitle      Episode dated 30 May 2018
originalTitle     Episode dated 30 May 2018
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2001195, dtype: object

(9,)

tconst                           tt11818198
titleType                         tvEpisode
primaryTitle      Episode dated 6 June 2018
originalTitle     Episode dated 6 June 2018
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2001196, dtype: object

(9,)

tconst                           tt1181819
titleType                          tvMovie
primaryTitle      The Great British Sunday
originalTitle     The Great British Sunday
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          58
genres                         Documentary
Name: 2001197, dtype: object

(9,)

tconst                             tt11818200
titleType                           tvEpisode
primaryTitle      Episode dated 9 August 2018
originalTitle     Episode dated 9 August 2018
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2001198, dtype: object

(9,)

tconst             tt11818202
titleType           tvEpisode
primaryTitle            Nozze
originalTitle           Nozze
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Crime,Drama
Name: 2001199, dtype: object

(9,)

tconst                              tt11818206
titleType                            tvEpisode
primaryTitle      Episode dated 16 August 2018
originalTitle     Episode dated 16 August 2018
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2001200, dtype: object

(9,)

tconst                   tt11818208
titleType                     short
primaryTitle      Get the Promotion
originalTitle     Get the Promotion
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                        Short
Name: 2001201, dtype: object

(9,)

tconst                  tt1181820
titleType                   video
primaryTitle      O gynaikas No 2
originalTitle     O gynaikas No 2
isAdult                         0
startYear                    1988
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2001202, dtype: object

(9,)

tconst             tt11818210
titleType           tvEpisode
primaryTitle           Sangue
originalTitle          Sangue
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Crime,Drama
Name: 2001203, dtype: object

(9,)

tconst                         tt11818212
titleType                           video
primaryTitle      Black and Blonde Vol. 5
originalTitle     Black and Blonde Vol. 5
isAdult                                 1
startYear                            2018
endYear                                \N
runtimeMinutes                        120
genres                      Adult,Romance
Name: 2001204, dtype: object

(9,)

tconst             tt11818214
titleType           tvEpisode
primaryTitle           Verità
originalTitle          Verità
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Crime,Drama
Name: 2001205, dtype: object

(9,)

tconst             tt11818216
titleType               short
primaryTitle      No Warranty
originalTitle     No Warranty
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                  Short
Name: 2001206, dtype: object

(9,)

tconst                                       tt11818218
titleType                                         short
primaryTitle      The Class of 2009: Last Day of School
originalTitle     The Class of 2009: Last Day of School
isAdult                                               0
startYear                                          2009
endYear                                              \N
runtimeMinutes                                        9
genres                                Documentary,Short
Name: 2001207, dtype: object

(9,)

tconst                       tt1181821
titleType                        short
primaryTitle        The Hobo's Roundup
originalTitle       The Hobo's Roundup
isAdult                              0
startYear                         1911
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Short,Western
Name: 2001208, dtype: object

(9,)

tconst               tt11818220
titleType          tvMiniSeries
primaryTitle      Roaming Focus
originalTitle     Roaming Focus
isAdult                       0
startYear                  2013
endYear                    2015
runtimeMinutes               \N
genres               Reality-TV
Name: 2001209, dtype: object

(9,)

tconst              tt11818222
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres             Documentary
Name: 2001210, dtype: object

(9,)

tconst                   tt11818226
titleType                   tvShort
primaryTitle       Dzieci w osiedlu
originalTitle      Dzieci w osiedlu
isAdult                           0
startYear                      1978
endYear                          \N
runtimeMinutes                   16
genres            Documentary,Short
Name: 2001211, dtype: object

(9,)

tconst              tt11818228
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres             Documentary
Name: 2001212, dtype: object

(9,)

tconst                           tt1181822
titleType                            short
primaryTitle      L'itinéraire de Dimitris
originalTitle     L'itinéraire de Dimitris
isAdult                                  0
startYear                             1991
endYear                                 \N
runtimeMinutes                          11
genres                               Short
Name: 2001213, dtype: object

(9,)

tconst              tt11818230
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres             Documentary
Name: 2001214, dtype: object

(9,)

tconst                           tt11818232
titleType                             video
primaryTitle      NK x Juan Magan: Lollipop
originalTitle     NK x Juan Magan: Lollipop
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                            3
genres                          Music,Short
Name: 2001215, dtype: object

(9,)

tconst              tt11818234
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres             Documentary
Name: 2001216, dtype: object

(9,)

tconst            tt11818236
titleType              short
primaryTitle         Hostage
originalTitle        Hostage
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2001217, dtype: object

(9,)

tconst                                tt11818238
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001218, dtype: object

(9,)

tconst            tt1181823
titleType             short
primaryTitle      Je t'aime
originalTitle     Je t'aime
isAdult                   0
startYear              1990
endYear                  \N
runtimeMinutes            3
genres                Short
Name: 2001219, dtype: object

(9,)

tconst              tt11818240
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres              Reality-TV
Name: 2001220, dtype: object

(9,)

tconst               tt11818242
titleType             tvEpisode
primaryTitle      Auf der Lauer
originalTitle     Auf der Lauer
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2001221, dtype: object

(9,)

tconst              tt11818244
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres             Documentary
Name: 2001222, dtype: object

(9,)

tconst              tt11818246
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2001223, dtype: object

(9,)

tconst              tt11818248
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              45
genres                      \N
Name: 2001224, dtype: object

(9,)

tconst                           tt1181824
titleType                            movie
primaryTitle      Le journal d'un dragueur
originalTitle     Le journal d'un dragueur
isAdult                                  1
startYear                             1980
endYear                                 \N
runtimeMinutes                          75
genres                               Adult
Name: 2001225, dtype: object

(9,)

tconst                  tt11818250
titleType                    short
primaryTitle      Nous étions deux
originalTitle     Nous étions deux
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                       Short
Name: 2001226, dtype: object

(9,)

tconst              tt11818252
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2001227, dtype: object

(9,)

tconst              tt11818254
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              22
genres              Reality-TV
Name: 2001228, dtype: object

(9,)

tconst                       tt11818256
titleType                         video
primaryTitle      Big Tits in Uniform 6
originalTitle     Big Tits in Uniform 6
isAdult                               1
startYear                          2012
endYear                              \N
runtimeMinutes                      199
genres                            Adult
Name: 2001229, dtype: object

(9,)

tconst              tt11818258
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2001230, dtype: object

(9,)

tconst            tt1181825
titleType             video
primaryTitle         Kaikin
originalTitle        Kaikin
isAdult                   1
startYear              2005
endYear                  \N
runtimeMinutes           \N
genres                Adult
Name: 2001231, dtype: object

(9,)

tconst                        tt11818260
titleType                      tvEpisode
primaryTitle                Episode #5.8
originalTitle               Episode #5.8
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        44
genres            Documentary,Reality-TV
Name: 2001232, dtype: object

(9,)

tconst              tt11818262
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2001233, dtype: object

(9,)

tconst                         tt11818264
titleType                       tvEpisode
primaryTitle           Ultimate Sacrifice
originalTitle          Ultimate Sacrifice
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         31
genres            Horror,Mystery,Thriller
Name: 2001234, dtype: object

(9,)

tconst              tt11818266
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2001235, dtype: object

(9,)

tconst              tt11818268
titleType                short
primaryTitle      My Sclerosis
originalTitle     My Sclerosis
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes               4
genres             Drama,Short
Name: 2001236, dtype: object

(9,)

tconst                     tt1181826
titleType                      movie
primaryTitle      Rent, No Utilities
originalTitle              Kaltmiete
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    48
genres                Horror,Mystery
Name: 2001237, dtype: object

(9,)

tconst                 tt11818270
titleType               tvEpisode
primaryTitle      Episode #1.1917
originalTitle     Episode #1.1917
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2001238, dtype: object

(9,)

tconst                                tt11818272
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2001239, dtype: object

(9,)

tconst                 tt11818274
titleType               tvEpisode
primaryTitle      Episode #1.1918
originalTitle     Episode #1.1918
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2001240, dtype: object

(9,)

tconst              tt11818276
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2001241, dtype: object

(9,)

tconst                 tt11818278
titleType               tvEpisode
primaryTitle      Episode #1.1919
originalTitle     Episode #1.1919
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2001242, dtype: object

(9,)

tconst                    tt1181827
titleType                     short
primaryTitle              Keratsini
originalTitle             Keratsini
isAdult                           0
startYear                      1978
endYear                          \N
runtimeMinutes                   21
genres            Documentary,Short
Name: 2001243, dtype: object

(9,)

tconst               tt11818280
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2000
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2001244, dtype: object

(9,)

tconst               tt11818282
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2000
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2001245, dtype: object

(9,)

tconst                              tt11818284
titleType                            tvEpisode
primaryTitle      Episode dated 5 October 1970
originalTitle     Episode dated 5 October 1970
isAdult                                      0
startYear                                 1970
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2001246, dtype: object

(9,)

tconst                 tt11818286
titleType               tvEpisode
primaryTitle      Born and Raised
originalTitle     Born and Raised
isAdult                         0
startYear                    2013
endYear                        \N
runtimeMinutes                 \N
genres                 Reality-TV
Name: 2001247, dtype: object

(9,)

tconst                  tt11818288
titleType                tvEpisode
primaryTitle        Episode #1.809
originalTitle       Episode #1.809
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001248, dtype: object

(9,)

tconst               tt1181828
titleType                short
primaryTitle        I koini gi
originalTitle       I koini gi
isAdult                      0
startYear                 1978
endYear                     \N
runtimeMinutes              15
genres            Comedy,Short
Name: 2001249, dtype: object

(9,)

tconst                  tt11818290
titleType                tvEpisode
primaryTitle        Episode #1.810
originalTitle       Episode #1.810
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001250, dtype: object

(9,)

tconst               tt11818292
titleType               tvMovie
primaryTitle      Derrota Final
originalTitle     Derrota Final
isAdult                       0
startYear                  1983
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2001251, dtype: object

(9,)

tconst                  tt11818294
titleType                tvEpisode
primaryTitle        Episode #1.811
originalTitle       Episode #1.811
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001252, dtype: object

(9,)

tconst                 tt11818296
titleType               tvEpisode
primaryTitle      Episode #1.1920
originalTitle     Episode #1.1920
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2001253, dtype: object

(9,)

tconst            tt11818298
titleType          tvEpisode
primaryTitle      Hey Ocean!
originalTitle     Hey Ocean!
isAdult                    0
startYear               2013
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2001254, dtype: object

(9,)

tconst                                      tt1181829
titleType                                     tvMovie
primaryTitle      Kyûkyoku no sabaibaru atakku Sasuke
originalTitle     Kyûkyoku no sabaibaru atakku Sasuke
isAdult                                             0
startYear                                        1997
endYear                                            \N
runtimeMinutes                                     \N
genres                                             \N
Name: 2001255, dtype: object

(9,)

tconst                 tt11818300
titleType               tvEpisode
primaryTitle      Episode #1.1921
originalTitle     Episode #1.1921
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2001256, dtype: object

(9,)

tconst                 tt11818302
titleType               tvEpisode
primaryTitle      Episode #1.1922
originalTitle     Episode #1.1922
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2001257, dtype: object

(9,)

tconst                 tt11818304
titleType               tvEpisode
primaryTitle      Episode #1.1924
originalTitle     Episode #1.1924
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2001258, dtype: object

(9,)

tconst                   tt11818306
titleType                     short
primaryTitle                My Land
originalTitle               My Land
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   12
genres            Documentary,Short
Name: 2001259, dtype: object

(9,)

tconst                   tt11818308
titleType                 tvEpisode
primaryTitle      Fin de l'histoire
originalTitle     Fin de l'histoire
isAdult                           0
startYear                      2012
endYear                          \N
runtimeMinutes                   26
genres                        Drama
Name: 2001260, dtype: object

(9,)

tconst             tt11818310
titleType               short
primaryTitle           Delete
originalTitle          Delete
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             11
genres            Drama,Short
Name: 2001261, dtype: object

(9,)

tconst                 tt11818312
titleType               tvEpisode
primaryTitle      Episode #1.1925
originalTitle     Episode #1.1925
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2001262, dtype: object

(9,)

tconst                            tt11818314
titleType                          tvEpisode
primaryTitle      The Doctor of Frankenstein
originalTitle     The Doctor of Frankenstein
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                      Sci-Fi,Talk-Show
Name: 2001263, dtype: object

(9,)

tconst             tt11818316
titleType           tvEpisode
primaryTitle      Hashtaggin'
originalTitle     Hashtaggin'
isAdult                     0
startYear                2013
endYear                    \N
runtimeMinutes             \N
genres             Reality-TV
Name: 2001264, dtype: object

(9,)

tconst              tt11818318
titleType            tvEpisode
primaryTitle      Episode #3.9
originalTitle     Episode #3.9
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             News,Sci-Fi
Name: 2001265, dtype: object

(9,)

tconst            tt1181831
titleType             short
primaryTitle       O lyhnos
originalTitle      O lyhnos
isAdult                   0
startYear              1994
endYear                  \N
runtimeMinutes           13
genres                Short
Name: 2001266, dtype: object

(9,)

tconst             tt11818320
titleType               short
primaryTitle            Faces
originalTitle           Faces
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes              7
genres            Drama,Short
Name: 2001267, dtype: object

(9,)

tconst                     tt11818322
titleType                   tvEpisode
primaryTitle      Les fleurs du drame
originalTitle     Les fleurs du drame
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2001268, dtype: object

(9,)

tconst                     tt11818324
titleType                tvMiniSeries
primaryTitle      Backyard Staycation
originalTitle     Backyard Staycation
isAdult                             0
startYear                        2019
endYear                          2019
runtimeMinutes                     \N
genres                     Reality-TV
Name: 2001269, dtype: object

(9,)

tconst                             tt11818326
titleType                           tvEpisode
primaryTitle      Episode dated 25 March 2013
originalTitle     Episode dated 25 March 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2001270, dtype: object

(9,)

tconst                             tt11818328
titleType                           tvEpisode
primaryTitle      Episode dated 26 March 2013
originalTitle     Episode dated 26 March 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2001271, dtype: object

(9,)

tconst                                           tt1181832
titleType                                            video
primaryTitle      London Calling: 25th Anniversary Edition
originalTitle     London Calling: 25th Anniversary Edition
isAdult                                                  0
startYear                                             2004
endYear                                                 \N
runtimeMinutes                                          60
genres                                   Documentary,Music
Name: 2001272, dtype: object

(9,)

tconst                             tt11818330
titleType                           tvEpisode
primaryTitle      Episode dated 27 March 2013
originalTitle     Episode dated 27 March 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2001273, dtype: object

(9,)

tconst             tt11818332
titleType           tvEpisode
primaryTitle       Episode 85
originalTitle      Episode 85
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            News,Sci-Fi
Name: 2001274, dtype: object

(9,)

tconst                             tt11818334
titleType                           tvEpisode
primaryTitle      Episode dated 28 March 2013
originalTitle     Episode dated 28 March 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2001275, dtype: object

(9,)

tconst                            tt11818336
titleType                          tvEpisode
primaryTitle      Episode dated 1 April 2013
originalTitle     Episode dated 1 April 2013
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2001276, dtype: object

(9,)

tconst                      tt11818338
titleType                    tvEpisode
primaryTitle              What a Duck!
originalTitle             What a Duck!
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001277, dtype: object

(9,)

tconst                     tt1181833
titleType                  videoGame
primaryTitle                Mafia II
originalTitle               Mafia II
isAdult                            0
startYear                       2010
endYear                           \N
runtimeMinutes                    \N
genres            Action,Crime,Drama
Name: 2001278, dtype: object

(9,)

tconst                        tt11818340
titleType                      tvEpisode
primaryTitle         Kentucky Route Zero
originalTitle        Kentucky Route Zero
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                         5
genres            Animation,Comedy,Short
Name: 2001279, dtype: object

(9,)

tconst                      tt11818344
titleType                    tvEpisode
primaryTitle       GFT- Girlfriend Tax
originalTitle      GFT- Girlfriend Tax
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001280, dtype: object

(9,)

tconst                                      tt11818346
titleType                                    tvSpecial
primaryTitle      Pancrase: Road to the Championship 1
originalTitle     Pancrase: Road to the Championship 1
isAdult                                              0
startYear                                         1994
endYear                                             \N
runtimeMinutes                                      59
genres                                           Sport
Name: 2001281, dtype: object

(9,)

tconst                         tt11818348
titleType                       tvEpisode
primaryTitle      TFW - That Feeling When
originalTitle     TFW - That Feeling When
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres               Comedy,Drama,Romance
Name: 2001282, dtype: object

(9,)

tconst                         tt1181834
titleType                          video
primaryTitle             Naked Surrender
originalTitle            Naked Surrender
isAdult                                0
startYear                           2006
endYear                               \N
runtimeMinutes                        95
genres            Drama,Romance,Thriller
Name: 2001283, dtype: object

(9,)

tconst                  tt11818350
titleType                tvEpisode
primaryTitle        Episode #1.812
originalTitle       Episode #1.812
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2001284, dtype: object

(9,)

tconst                   tt11818352
titleType                     short
primaryTitle        KV KRH kärjessä
originalTitle       KV KRH kärjessä
isAdult                           0
startYear                      1971
endYear                          \N
runtimeMinutes                    9
genres            Documentary,Short
Name: 2001285, dtype: object

(9,)

tconst                                           tt11818354
titleType                                         tvEpisode
primaryTitle      YAAS - An Enthusiastic Way of Saying Yes!
originalTitle     YAAS - An Enthusiastic Way of Saying Yes!
isAdult                                                   0
startYear                                              2019
endYear                                                  \N
runtimeMinutes                                           \N
genres                                 Comedy,Drama,Romance
Name: 2001286, dtype: object

(9,)

tconst                                       tt11818356
titleType                                     tvEpisode
primaryTitle      STAN - Combination of Stalker and Fan
originalTitle     STAN - Combination of Stalker and Fan
isAdult                                               0
startYear                                          2019
endYear                                              \N
runtimeMinutes                                       \N
genres                             Comedy,Drama,Romance
Name: 2001287, dtype: object

(9,)

tconst                         tt11818358
titleType                           movie
primaryTitle      Indifferent Enchantment
originalTitle     Indifferent Enchantment
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                      Drama,Romance
Name: 2001288, dtype: object

(9,)

tconst                          tt1181835
titleType                           short
primaryTitle      Making a Man of His Son
originalTitle     Making a Man of His Son
isAdult                                 0
startYear                            1911
endYear                                \N
runtimeMinutes                         \N
genres                        Drama,Short
Name: 2001289, dtype: object

(9,)

tconst             tt11818360
titleType               short
primaryTitle        Stesøstra
originalTitle       Stesøstra
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             10
genres            Drama,Short
Name: 2001290, dtype: object

(9,)

tconst                            tt11818362
titleType                          tvEpisode
primaryTitle      The Struggle is Real, Bro!
originalTitle     The Struggle is Real, Bro!
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                  Comedy,Drama,Romance
Name: 2001291, dtype: object

(9,)

tconst                      tt11818364
titleType                    tvEpisode
primaryTitle               Last Chance
originalTitle              Last Chance
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001292, dtype: object

(9,)

tconst                                                   tt11818366
titleType                                                     short
primaryTitle      I've Said and Done Things That No-One Will Eve...
originalTitle     I've Said and Done Things That No-One Will Eve...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    5
genres                                                  Drama,Short
Name: 2001293, dtype: object

(9,)

tconst                      tt11818368
titleType                     tvSeries
primaryTitle      Los ojos que vigilan
originalTitle     Los ojos que vigilan
isAdult                              0
startYear                         1967
endYear                             \N
runtimeMinutes                      \N
genres                           Drama
Name: 2001294, dtype: object

(9,)

tconst                 tt1181836
titleType                  short
primaryTitle      The Manicurist
originalTitle     The Manicurist
isAdult                        0
startYear                   1912
endYear                       \N
runtimeMinutes                \N
genres               Drama,Short
Name: 2001295, dtype: object

(9,)

tconst                 tt11818370
titleType               tvEpisode
primaryTitle         Episode #1.1
originalTitle        Episode #1.1
isAdult                         0
startYear                    2017
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2001296, dtype: object

(9,)

tconst                               tt11818372
titleType                             tvEpisode
primaryTitle      Episode dated 26 October 2017
originalTitle     Episode dated 26 October 2017
isAdult                                       0
startYear                                  2017
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001297, dtype: object

(9,)

tconst                 tt11818374
titleType               tvEpisode
primaryTitle         Episode #2.1
originalTitle        Episode #2.1
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2001298, dtype: object

(9,)

tconst                             tt11818376
titleType                           tvEpisode
primaryTitle      Episode dated 12 April 2018
originalTitle     Episode dated 12 April 2018
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2001299, dtype: object

(9,)

tconst                              tt11818378
titleType                            tvEpisode
primaryTitle      Episode dated 17 August 2018
originalTitle     Episode dated 17 August 2018
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2001300, dtype: object

(9,)

tconst                          tt1181837
titleType                           movie
primaryTitle      Me aformi mia parastasi
originalTitle     Me aformi mia parastasi
isAdult                                 0
startYear                            1978
endYear                                \N
runtimeMinutes                         45
genres                                 \N
Name: 2001301, dtype: object

(9,)

tconst                     tt11818380
titleType                   tvEpisode
primaryTitle           Episode #1.107
originalTitle          Episode #1.107
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2001302, dtype: object

(9,)

tconst             tt11818382
titleType           tvEpisode
primaryTitle      Het noorden
originalTitle     Het noorden
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2001303, dtype: object

(9,)

tconst             tt11818386
titleType           tvEpisode
primaryTitle      Compliments
originalTitle     Compliments
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2001304, dtype: object

(9,)

tconst                       tt11818388
titleType                     tvEpisode
primaryTitle      Drenthe en Overijssel
originalTitle     Drenthe en Overijssel
isAdult                               0
startYear                          2009
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2001305, dtype: object

(9,)

tconst                      tt1181838
titleType                   tvEpisode
primaryTitle      1971 Christmas Show
originalTitle     1971 Christmas Show
isAdult                             0
startYear                        1971
endYear                            \N
runtimeMinutes                     66
genres                         Comedy
Name: 2001306, dtype: object

(9,)

tconst             tt11818390
titleType           tvEpisode
primaryTitle       Gelderland
originalTitle      Gelderland
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2001307, dtype: object

(9,)

tconst            tt11818392
titleType          tvEpisode
primaryTitle       Body Roll
originalTitle      Body Roll
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001308, dtype: object

(9,)

tconst                 tt11818394
titleType               tvEpisode
primaryTitle      Naar het zuiden
originalTitle     Naar het zuiden
isAdult                         0
startYear                    2009
endYear                        \N
runtimeMinutes                 \N
genres                Documentary
Name: 2001309, dtype: object

(9,)

tconst                    tt11818396
titleType                  tvEpisode
primaryTitle      Limburg en Zeeland
originalTitle     Limburg en Zeeland
isAdult                            0
startYear                       2009
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2001310, dtype: object

(9,)

tconst             tt11818398
titleType           tvEpisode
primaryTitle       Het westen
originalTitle      Het westen
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2001311, dtype: object

(9,)

tconst                                      tt1181839
titleType                                       video
primaryTitle      Mute Film Presents Cabaret Voltaire
originalTitle     Mute Film Presents Cabaret Voltaire
isAdult                                             0
startYear                                        1990
endYear                                            \N
runtimeMinutes                                     85
genres                                          Music
Name: 2001312, dtype: object

(9,)

tconst            tt11818400
titleType          tvEpisode
primaryTitle          Part 2
originalTitle         Part 2
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2001313, dtype: object

(9,)

tconst            tt11818402
titleType          tvEpisode
primaryTitle            Burn
originalTitle           Burn
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001314, dtype: object

(9,)

tconst               tt11818404
titleType                 short
primaryTitle      Odds and Ends
originalTitle     Odds and Ends
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes                4
genres                    Short
Name: 2001315, dtype: object

(9,)

tconst              tt11818406
titleType            tvEpisode
primaryTitle      Panic Breath
originalTitle     Panic Breath
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2001316, dtype: object

(9,)

tconst                   tt11818408
titleType                  tvSeries
primaryTitle      Stranger Among Us
originalTitle     Stranger Among Us
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                        Crime
Name: 2001317, dtype: object

(9,)

tconst                                  tt1181840
titleType                                   movie
primaryTitle      Jack and the Cuckoo-Clock Heart
originalTitle       Jack et la mécanique du coeur
isAdult                                         0
startYear                                    2013
endYear                                        \N
runtimeMinutes                                 94
genres                  Adventure,Animation,Drama
Name: 2001318, dtype: object

(9,)

tconst                     tt11818410
titleType                   tvEpisode
primaryTitle                  Berlijn
originalTitle                 Berlijn
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres            Documentary,History
Name: 2001319, dtype: object

(9,)

tconst                     tt11818412
titleType                   tvEpisode
primaryTitle                  Leipzig
originalTitle                 Leipzig
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres            Documentary,History
Name: 2001320, dtype: object

(9,)

tconst                     tt11818414
titleType                   tvEpisode
primaryTitle                  Dresden
originalTitle                 Dresden
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres            Documentary,History
Name: 2001321, dtype: object

(9,)

tconst                            tt11818416
titleType                          tvEpisode
primaryTitle      Souviens-toi de cette date
originalTitle     Souviens-toi de cette date
isAdult                                    0
startYear                               2012
endYear                                   \N
runtimeMinutes                            26
genres                                 Drama
Name: 2001322, dtype: object

(9,)

tconst               tt11818418
titleType             tvEpisode
primaryTitle      Case #5695646
originalTitle     Case #5695646
isAdult                       1
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2001323, dtype: object

(9,)

tconst              tt1181841
titleType               short
primaryTitle             Neon
originalTitle            Neon
isAdult                     0
startYear                1980
endYear                    \N
runtimeMinutes              4
genres            Music,Short
Name: 2001324, dtype: object

(9,)

tconst               tt11818420
titleType             tvEpisode
primaryTitle      The Dex Files
originalTitle     The Dex Files
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               42
genres              Crime,Drama
Name: 2001325, dtype: object

(9,)

tconst                tt11818422
titleType                  movie
primaryTitle      The New Normal
originalTitle     The New Normal
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                75
genres               Documentary
Name: 2001326, dtype: object

(9,)

tconst            tt11818424
titleType          tvEpisode
primaryTitle         Candles
originalTitle        Candles
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001327, dtype: object

(9,)

tconst            tt11818426
titleType              movie
primaryTitle           Gritt
originalTitle          Gritt
isAdult                    0
startYear               2021
endYear                   \N
runtimeMinutes           118
genres                 Drama
Name: 2001328, dtype: object

(9,)

tconst            tt11818428
titleType          tvEpisode
primaryTitle       Handstand
originalTitle      Handstand
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001329, dtype: object

(9,)

tconst                    tt1181842
titleType                     short
primaryTitle          The Blue Nile
originalTitle              Nil bleu
isAdult                           0
startYear                      1911
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2001330, dtype: object

(9,)

tconst                        tt11818430
titleType                   tvMiniSeries
primaryTitle                The Drowning
originalTitle               The Drowning
isAdult                                0
startYear                           2021
endYear                             2021
runtimeMinutes                        \N
genres            Drama,Mystery,Thriller
Name: 2001331, dtype: object

(9,)

tconst            tt11818432
titleType          tvEpisode
primaryTitle      Belly Blow
originalTitle     Belly Blow
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001332, dtype: object

(9,)

tconst            tt11818434
titleType          tvEpisode
primaryTitle       City Girl
originalTitle      City Girl
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001333, dtype: object

(9,)

tconst                              tt11818436
titleType                            tvEpisode
primaryTitle      Episode dated 6 October 1970
originalTitle     Episode dated 6 October 1970
isAdult                                      0
startYear                                 1970
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2001334, dtype: object

(9,)

tconst               tt11818438
titleType          tvMiniSeries
primaryTitle      Otel 'Triumf'
originalTitle     Otel 'Triumf'
isAdult                       0
startYear                  2019
endYear                    2019
runtimeMinutes               20
genres             Comedy,Drama
Name: 2001335, dtype: object

(9,)

tconst                        tt1181843
titleType                       tvMovie
primaryTitle      Ningen no shômei 2001
originalTitle     Ningen no shômei 2001
isAdult                               0
startYear                          2001
endYear                              \N
runtimeMinutes                       \N
genres                               \N
Name: 2001336, dtype: object

(9,)

tconst               tt11818440
titleType             tvEpisode
primaryTitle       Episode #1.1
originalTitle      Episode #1.1
isAdult                       0
startYear                  1979
endYear                      \N
runtimeMinutes               \N
genres            Drama,Mystery
Name: 2001337, dtype: object

(9,)

tconst                        tt11818442
titleType                      tvEpisode
primaryTitle      Go MidWest For Fintech
originalTitle     Go MidWest For Fintech
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2001338, dtype: object

(9,)

tconst             tt11818444
titleType               movie
primaryTitle      Her and Him
originalTitle     Her and Him
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2001339, dtype: object

(9,)

tconst                        tt11818446
titleType                          short
primaryTitle      Cannoli and Corruption
originalTitle     Cannoli and Corruption
isAdult                                0
startYear                           2017
endYear                               \N
runtimeMinutes                         5
genres                       Crime,Short
Name: 2001340, dtype: object

(9,)

tconst                     tt11818448
titleType                   tvEpisode
primaryTitle                  Berlijn
originalTitle                 Berlijn
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres            Documentary,History
Name: 2001341, dtype: object

(9,)

tconst                  tt1181844
titleType                   short
primaryTitle      Out of the Dark
originalTitle     Out of the Dark
isAdult                         0
startYear                    1911
endYear                        \N
runtimeMinutes                 \N
genres              Short,Western
Name: 2001342, dtype: object

(9,)

tconst                                              tt11818450
titleType                                            tvEpisode
primaryTitle      The Snoogle Supreme Total Body Pillow on QVC
originalTitle     The Snoogle Supreme Total Body Pillow on QVC
isAdult                                                      0
startYear                                                 2020
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                  Family
Name: 2001343, dtype: object

(9,)

tconst            tt11818452
titleType           tvSeries
primaryTitle       Spoorloos
originalTitle      Spoorloos
isAdult                    0
startYear               2018
endYear                 2019
runtimeMinutes            60
genres                 Drama
Name: 2001344, dtype: object

(9,)

tconst                 tt11818454
titleType               tvEpisode
primaryTitle      Episode #1.5369
originalTitle     Episode #1.5369
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2001345, dtype: object

(9,)

tconst                 tt11818456
titleType               tvEpisode
primaryTitle      Episode #1.2765
originalTitle     Episode #1.2765
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2001346, dtype: object

(9,)

tconst                 tt11818458
titleType               tvEpisode
primaryTitle      Episode #1.2766
originalTitle     Episode #1.2766
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2001347, dtype: object

(9,)

tconst                 tt11818460
titleType               tvEpisode
primaryTitle      Episode #1.2767
originalTitle     Episode #1.2767
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2001348, dtype: object

(9,)

tconst                 tt11818462
titleType               tvEpisode
primaryTitle      Episode #1.2768
originalTitle     Episode #1.2768
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2001349, dtype: object

(9,)

tconst                 tt11818464
titleType               tvEpisode
primaryTitle      Episode #1.2769
originalTitle     Episode #1.2769
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2001350, dtype: object

(9,)

tconst                           tt11818466
titleType                         tvEpisode
primaryTitle      La mesera y el traficante
originalTitle     La mesera y el traficante
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                               Action
Name: 2001351, dtype: object

(9,)

tconst                        tt11818468
titleType                          video
primaryTitle      Evigheten: Eksistensen
originalTitle     Evigheten: Eksistensen
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2001352, dtype: object

(9,)

tconst                   tt1181846
titleType                    video
primaryTitle      Pick-Up Lines 52
originalTitle     Pick-Up Lines 52
isAdult                          1
startYear                     2000
endYear                         \N
runtimeMinutes                  90
genres                       Adult
Name: 2001353, dtype: object

(9,)

tconst                                tt11818474
titleType                                  short
primaryTitle      The Secret Dreams of Squidlets
originalTitle     The Secret Dreams of Squidlets
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                10
genres                           Animation,Short
Name: 2001354, dtype: object

(9,)

tconst                 tt11818476
titleType               tvEpisode
primaryTitle      Episode #1.1602
originalTitle     Episode #1.1602
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001355, dtype: object

(9,)

tconst                      tt11818478
titleType                        short
primaryTitle      Danny Paul: On Sight
originalTitle     Danny Paul: On Sight
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       3
genres                     Music,Short
Name: 2001356, dtype: object

(9,)

tconst                                               tt1181847
titleType                                                video
primaryTitle      Reijô kokuhaku yogosareta furisode higurashi
originalTitle     Reijô kokuhaku yogosareta furisode higurashi
isAdult                                                      0
startYear                                                 1999
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                      \N
Name: 2001357, dtype: object

(9,)

tconst                 tt11818480
titleType               tvEpisode
primaryTitle      Episode #1.1603
originalTitle     Episode #1.1603
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001358, dtype: object

(9,)

tconst                 tt11818482
titleType               tvEpisode
primaryTitle      Episode #1.1604
originalTitle     Episode #1.1604
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001359, dtype: object

(9,)

tconst                 tt11818484
titleType               tvEpisode
primaryTitle      Episode #1.1605
originalTitle     Episode #1.1605
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001360, dtype: object

(9,)

tconst                 tt11818486
titleType               tvEpisode
primaryTitle      Episode #1.1606
originalTitle     Episode #1.1606
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001361, dtype: object

(9,)

tconst                 tt11818488
titleType               tvEpisode
primaryTitle      Episode #1.1607
originalTitle     Episode #1.1607
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001362, dtype: object

(9,)

tconst              tt1181848
titleType               short
primaryTitle      Le scénario
originalTitle     Le scénario
isAdult                     0
startYear                1989
endYear                    \N
runtimeMinutes             11
genres                  Short
Name: 2001363, dtype: object

(9,)

tconst                            tt11818490
titleType                          tvEpisode
primaryTitle      Episode dated 2 March 2020
originalTitle     Episode dated 2 March 2020
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2001364, dtype: object

(9,)

tconst                 tt11818494
titleType               tvEpisode
primaryTitle      Episode #1.1608
originalTitle     Episode #1.1608
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001365, dtype: object

(9,)

tconst                 tt11818496
titleType               tvEpisode
primaryTitle      Episode #1.1610
originalTitle     Episode #1.1610
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001366, dtype: object

(9,)

tconst                 tt11818498
titleType               tvEpisode
primaryTitle      Episode #1.1611
originalTitle     Episode #1.1611
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001367, dtype: object

(9,)

tconst                         tt1181849
titleType                      tvEpisode
primaryTitle              Sharpe's Peril
originalTitle             Sharpe's Peril
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                       102
genres            Action,Adventure,Drama
Name: 2001368, dtype: object

(9,)

tconst                 tt11818500
titleType               tvEpisode
primaryTitle      Episode #1.1612
originalTitle     Episode #1.1612
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001369, dtype: object

(9,)

tconst                 tt11818502
titleType               tvEpisode
primaryTitle      Episode #1.1613
originalTitle     Episode #1.1613
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001370, dtype: object

(9,)

tconst                 tt11818504
titleType               tvEpisode
primaryTitle      Episode #1.1614
originalTitle     Episode #1.1614
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001371, dtype: object

(9,)

tconst                 tt11818506
titleType               tvEpisode
primaryTitle      Episode #1.1616
originalTitle     Episode #1.1616
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001372, dtype: object

(9,)

tconst                 tt11818508
titleType               tvEpisode
primaryTitle      Episode #1.1615
originalTitle     Episode #1.1615
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001373, dtype: object

(9,)

tconst               tt1181850
titleType                short
primaryTitle      Speed Dating
originalTitle     Speed Dating
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              30
genres                   Short
Name: 2001374, dtype: object

(9,)

tconst                 tt11818510
titleType               tvEpisode
primaryTitle      Episode #1.1617
originalTitle     Episode #1.1617
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001375, dtype: object

(9,)

tconst                 tt11818512
titleType               tvEpisode
primaryTitle      Episode #1.1618
originalTitle     Episode #1.1618
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001376, dtype: object

(9,)

tconst                 tt11818514
titleType               tvEpisode
primaryTitle      Episode #1.1619
originalTitle     Episode #1.1619
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001377, dtype: object

(9,)

tconst                   tt11818516
titleType                 tvEpisode
primaryTitle      2020: Auditions 2
originalTitle     2020: Auditions 2
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres              Game-Show,Music
Name: 2001378, dtype: object

(9,)

tconst                 tt11818518
titleType               tvEpisode
primaryTitle      Episode #1.1620
originalTitle     Episode #1.1620
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001379, dtype: object

(9,)

tconst                 tt11818520
titleType               tvEpisode
primaryTitle      Episode #1.1302
originalTitle     Episode #1.1302
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001380, dtype: object

(9,)

tconst                 tt11818522
titleType               tvEpisode
primaryTitle      Episode #1.1301
originalTitle     Episode #1.1301
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001381, dtype: object

(9,)

tconst                 tt11818526
titleType               tvEpisode
primaryTitle      Episode #1.1304
originalTitle     Episode #1.1304
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001382, dtype: object

(9,)

tconst                 tt11818528
titleType               tvEpisode
primaryTitle      Episode #1.1305
originalTitle     Episode #1.1305
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001383, dtype: object

(9,)

tconst                  tt1181852
titleType                   short
primaryTitle      The Three Calls
originalTitle     The Three Calls
isAdult                         0
startYear                    1911
endYear                        \N
runtimeMinutes                 \N
genres                Drama,Short
Name: 2001384, dtype: object

(9,)

tconst                 tt11818530
titleType               tvEpisode
primaryTitle      Episode #1.1306
originalTitle     Episode #1.1306
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001385, dtype: object

(9,)

tconst                 tt11818532
titleType               tvEpisode
primaryTitle      Episode #1.1307
originalTitle     Episode #1.1307
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001386, dtype: object

(9,)

tconst                     tt11818534
titleType                   tvEpisode
primaryTitle      Love Or Obsession ?
originalTitle     Love Or Obsession ?
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres                          Crime
Name: 2001387, dtype: object

(9,)

tconst                            tt11818536
titleType                          tvEpisode
primaryTitle      Episode dated 5 March 2020
originalTitle     Episode dated 5 March 2020
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2001388, dtype: object

(9,)

tconst                 tt11818538
titleType               tvEpisode
primaryTitle      Episode #1.1309
originalTitle     Episode #1.1309
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001389, dtype: object

(9,)

tconst                                           tt1181853
titleType                                          tvMovie
primaryTitle      To Kill a Burglar: The Tony Martin Story
originalTitle     To Kill a Burglar: The Tony Martin Story
isAdult                                                  0
startYear                                             2006
endYear                                                 \N
runtimeMinutes                                          60
genres                                         Documentary
Name: 2001390, dtype: object

(9,)

tconst                 tt11818540
titleType               tvEpisode
primaryTitle      Episode #1.1310
originalTitle     Episode #1.1310
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001391, dtype: object

(9,)

tconst                               tt11818542
titleType                             tvEpisode
primaryTitle      Episode dated 11 October 2018
originalTitle     Episode dated 11 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001392, dtype: object

(9,)

tconst                               tt11818544
titleType                             tvEpisode
primaryTitle      Episode dated 10 October 2018
originalTitle     Episode dated 10 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001393, dtype: object

(9,)

tconst                 tt11818546
titleType               tvEpisode
primaryTitle      Episode #1.1311
originalTitle     Episode #1.1311
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001394, dtype: object

(9,)

tconst                               tt11818548
titleType                             tvEpisode
primaryTitle      Episode dated 12 October 2018
originalTitle     Episode dated 12 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001395, dtype: object

(9,)

tconst                        tt1181854
titleType                         short
primaryTitle      Un tango sur un poème
originalTitle     Un tango sur un poème
isAdult                               0
startYear                          2000
endYear                              \N
runtimeMinutes                        6
genres                            Short
Name: 2001396, dtype: object

(9,)

tconst                               tt11818550
titleType                             tvEpisode
primaryTitle      Episode dated 17 October 2018
originalTitle     Episode dated 17 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001397, dtype: object

(9,)

tconst                               tt11818552
titleType                             tvEpisode
primaryTitle      Episode dated 19 October 2018
originalTitle     Episode dated 19 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001398, dtype: object

(9,)

tconst                 tt11818554
titleType               tvEpisode
primaryTitle      Episode #1.1313
originalTitle     Episode #1.1313
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001399, dtype: object

(9,)

tconst                               tt11818556
titleType                             tvEpisode
primaryTitle      Episode dated 30 October 2018
originalTitle     Episode dated 30 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001400, dtype: object

(9,)

tconst                               tt11818558
titleType                             tvEpisode
primaryTitle      Episode dated 16 October 2018
originalTitle     Episode dated 16 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001401, dtype: object

(9,)

tconst                              tt1181855
titleType                               short
primaryTitle      United States Cavalry Drill
originalTitle     United States Cavalry Drill
isAdult                                     0
startYear                                1911
endYear                                    \N
runtimeMinutes                             \N
genres                      Documentary,Short
Name: 2001402, dtype: object

(9,)

tconst                 tt11818560
titleType               tvEpisode
primaryTitle      Episode #1.1312
originalTitle     Episode #1.1312
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001403, dtype: object

(9,)

tconst                               tt11818562
titleType                             tvEpisode
primaryTitle      Episode dated 26 October 2018
originalTitle     Episode dated 26 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001404, dtype: object

(9,)

tconst                               tt11818564
titleType                             tvEpisode
primaryTitle      Episode dated 22 October 2018
originalTitle     Episode dated 22 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001405, dtype: object

(9,)

tconst                               tt11818566
titleType                             tvEpisode
primaryTitle      Episode dated 29 October 2018
originalTitle     Episode dated 29 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001406, dtype: object

(9,)

tconst                               tt11818568
titleType                             tvEpisode
primaryTitle      Episode dated 31 October 2018
originalTitle     Episode dated 31 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001407, dtype: object

(9,)

tconst                               tt11818570
titleType                             tvEpisode
primaryTitle      Episode dated 23 October 2018
originalTitle     Episode dated 23 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001408, dtype: object

(9,)

tconst                               tt11818574
titleType                             tvEpisode
primaryTitle      Episode dated 18 October 2018
originalTitle     Episode dated 18 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001409, dtype: object

(9,)

tconst                               tt11818576
titleType                             tvEpisode
primaryTitle      Episode dated 24 October 2018
originalTitle     Episode dated 24 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001410, dtype: object

(9,)

tconst                               tt11818578
titleType                             tvEpisode
primaryTitle      Episode dated 25 October 2018
originalTitle     Episode dated 25 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001411, dtype: object

(9,)

tconst                 tt11818580
titleType               tvEpisode
primaryTitle      Episode #1.1316
originalTitle     Episode #1.1316
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001412, dtype: object

(9,)

tconst                 tt11818582
titleType               tvEpisode
primaryTitle      Episode #1.1315
originalTitle     Episode #1.1315
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001413, dtype: object

(9,)

tconst                 tt11818584
titleType               tvEpisode
primaryTitle      Episode #1.1317
originalTitle     Episode #1.1317
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001414, dtype: object

(9,)

tconst                 tt11818586
titleType               tvEpisode
primaryTitle      Episode #1.1319
originalTitle     Episode #1.1319
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001415, dtype: object

(9,)

tconst                 tt11818588
titleType               tvEpisode
primaryTitle      Episode #1.1318
originalTitle     Episode #1.1318
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001416, dtype: object

(9,)

tconst                  tt1181858
titleType                   short
primaryTitle      A Village Flirt
originalTitle     A Village Flirt
isAdult                         0
startYear                    1911
endYear                        \N
runtimeMinutes                 \N
genres               Comedy,Short
Name: 2001417, dtype: object

(9,)

tconst                               tt11818590
titleType                             tvEpisode
primaryTitle      Episode dated 1 November 2018
originalTitle     Episode dated 1 November 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001418, dtype: object

(9,)

tconst                               tt11818592
titleType                             tvEpisode
primaryTitle      Episode dated 2 November 2018
originalTitle     Episode dated 2 November 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001419, dtype: object

(9,)

tconst                 tt11818594
titleType               tvEpisode
primaryTitle      Episode #1.1320
originalTitle     Episode #1.1320
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001420, dtype: object

(9,)

tconst                 tt11818596
titleType               tvEpisode
primaryTitle      Episode #1.1101
originalTitle     Episode #1.1101
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001421, dtype: object

(9,)

tconst                            tt11818598
titleType                          tvEpisode
primaryTitle      Episode dated 6 March 2020
originalTitle     Episode dated 6 March 2020
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2001422, dtype: object

(9,)

tconst                    tt1181859
titleType                     movie
primaryTitle      The Rolling Stone
originalTitle     Wakuraba nagarete
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                  120
genres                           \N
Name: 2001423, dtype: object

(9,)

tconst                 tt11818600
titleType               tvEpisode
primaryTitle      Episode #1.1102
originalTitle     Episode #1.1102
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001424, dtype: object

(9,)

tconst                    tt1181860
titleType                     movie
primaryTitle      When Clouds Clear
originalTitle     When Clouds Clear
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   77
genres                  Documentary
Name: 2001425, dtype: object

(9,)

tconst                 tt11818614
titleType               tvEpisode
primaryTitle      Episode #1.1109
originalTitle     Episode #1.1109
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001426, dtype: object

(9,)

tconst                 tt11818616
titleType               tvEpisode
primaryTitle      Episode #1.1110
originalTitle     Episode #1.1110
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001427, dtype: object

(9,)

tconst                 tt11818618
titleType               tvEpisode
primaryTitle      Episode #1.1111
originalTitle     Episode #1.1111
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001428, dtype: object

(9,)

tconst                 tt11818620
titleType               tvEpisode
primaryTitle      Episode #1.1112
originalTitle     Episode #1.1112
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001429, dtype: object

(9,)

tconst                 tt11818622
titleType               tvEpisode
primaryTitle      Episode #1.1113
originalTitle     Episode #1.1113
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001430, dtype: object

(9,)

tconst                 tt11818624
titleType                   movie
primaryTitle      Our Daily Bread
originalTitle     Our Daily Bread
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 71
genres                Documentary
Name: 2001431, dtype: object

(9,)

tconst                 tt11818626
titleType               tvEpisode
primaryTitle      Episode #1.1114
originalTitle     Episode #1.1114
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001432, dtype: object

(9,)

tconst                 tt11818628
titleType               tvEpisode
primaryTitle      Episode #1.1116
originalTitle     Episode #1.1116
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001433, dtype: object

(9,)

tconst            tt1181862
titleType             video
primaryTitle            Wir
originalTitle           Wir
isAdult                   0
startYear              2003
endYear                  \N
runtimeMinutes          188
genres                Music
Name: 2001434, dtype: object

(9,)

tconst                 tt11818630
titleType               tvEpisode
primaryTitle      Episode #1.1115
originalTitle     Episode #1.1115
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001435, dtype: object

(9,)

tconst                 tt11818632
titleType               tvEpisode
primaryTitle      Episode #1.1117
originalTitle     Episode #1.1117
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001436, dtype: object

(9,)

tconst                 tt11818634
titleType               tvEpisode
primaryTitle      Episode #1.1119
originalTitle     Episode #1.1119
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001437, dtype: object

(9,)

tconst                 tt11818636
titleType               tvEpisode
primaryTitle      Episode #1.1118
originalTitle     Episode #1.1118
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001438, dtype: object

(9,)

tconst                 tt11818638
titleType               tvEpisode
primaryTitle      Episode #1.1120
originalTitle     Episode #1.1120
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001439, dtype: object

(9,)

tconst                                 tt1181863
titleType                                  video
primaryTitle      Private Movies 29: Witch Bitch
originalTitle     Private Movies 29: Witch Bitch
isAdult                                        1
startYear                                   2006
endYear                                       \N
runtimeMinutes                               105
genres                                     Adult
Name: 2001440, dtype: object

(9,)

tconst                              tt11818640
titleType                            tvEpisode
primaryTitle      Episode dated 7 October 1970
originalTitle     Episode dated 7 October 1970
isAdult                                      0
startYear                                 1970
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2001441, dtype: object

(9,)

tconst                tt11818642
titleType              tvEpisode
primaryTitle      Episode #1.861
originalTitle     Episode #1.861
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001442, dtype: object

(9,)

tconst                tt11818644
titleType              tvEpisode
primaryTitle      Episode #1.863
originalTitle     Episode #1.863
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001443, dtype: object

(9,)

tconst                tt11818646
titleType              tvEpisode
primaryTitle      Episode #1.862
originalTitle     Episode #1.862
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001444, dtype: object

(9,)

tconst                 tt11818648
titleType                tvSeries
primaryTitle      Going Both Ways
originalTitle     Going Both Ways
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2001445, dtype: object

(9,)

tconst                     tt1181864
titleType                    tvMovie
primaryTitle      Yottsu no shûshifu
originalTitle     Yottsu no shûshifu
isAdult                            0
startYear                       2001
endYear                           \N
runtimeMinutes                    \N
genres                            \N
Name: 2001446, dtype: object

(9,)

tconst                tt11818650
titleType              tvEpisode
primaryTitle      Episode #1.864
originalTitle     Episode #1.864
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001447, dtype: object

(9,)

tconst                tt11818652
titleType              tvEpisode
primaryTitle      Episode #1.865
originalTitle     Episode #1.865
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001448, dtype: object

(9,)

tconst                tt11818656
titleType              tvEpisode
primaryTitle      Episode #1.866
originalTitle     Episode #1.866
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001449, dtype: object

(9,)

tconst                tt11818658
titleType              tvEpisode
primaryTitle      Episode #1.867
originalTitle     Episode #1.867
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001450, dtype: object

(9,)

tconst                  tt1181865
titleType                   short
primaryTitle      Zontani ekpombi
originalTitle     Zontani ekpombi
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 15
genres                      Short
Name: 2001451, dtype: object

(9,)

tconst                tt11818660
titleType              tvEpisode
primaryTitle      Episode #1.868
originalTitle     Episode #1.868
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001452, dtype: object

(9,)

tconst                tt11818662
titleType              tvEpisode
primaryTitle      Episode #1.869
originalTitle     Episode #1.869
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001453, dtype: object

(9,)

tconst                tt11818664
titleType              tvEpisode
primaryTitle      Episode #1.870
originalTitle     Episode #1.870
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001454, dtype: object

(9,)

tconst                                                   tt11818666
titleType                                                 tvEpisode
primaryTitle      Ibrahim Selim ile Bu Gece #20: Bensu Soral, Me...
originalTitle     Ibrahim Selim ile Bu Gece #20: Bensu Soral, Me...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                             Comedy,Talk-Show
Name: 2001455, dtype: object

(9,)

tconst                tt11818668
titleType              tvEpisode
primaryTitle      Episode #1.871
originalTitle     Episode #1.871
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001456, dtype: object

(9,)

tconst                tt11818670
titleType              tvEpisode
primaryTitle      Episode #1.872
originalTitle     Episode #1.872
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001457, dtype: object

(9,)

tconst                tt11818672
titleType              tvEpisode
primaryTitle      Episode #1.874
originalTitle     Episode #1.874
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001458, dtype: object

(9,)

tconst                tt11818674
titleType              tvEpisode
primaryTitle      Episode #1.873
originalTitle     Episode #1.873
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001459, dtype: object

(9,)

tconst                tt11818676
titleType              tvEpisode
primaryTitle      Episode #1.875
originalTitle     Episode #1.875
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001460, dtype: object

(9,)

tconst                tt11818678
titleType              tvEpisode
primaryTitle      Episode #1.876
originalTitle     Episode #1.876
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001461, dtype: object

(9,)

tconst                                        tt1181867
titleType                                     tvEpisode
primaryTitle      Era Uma Vez uma Despedida de Solteiro
originalTitle     Era Uma Vez uma Despedida de Solteiro
isAdult                                               0
startYear                                          2008
endYear                                              \N
runtimeMinutes                                       \N
genres                                   Comedy,Romance
Name: 2001462, dtype: object

(9,)

tconst                tt11818680
titleType              tvEpisode
primaryTitle      Episode #1.878
originalTitle     Episode #1.878
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001463, dtype: object

(9,)

tconst                tt11818682
titleType              tvEpisode
primaryTitle      Episode #1.877
originalTitle     Episode #1.877
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001464, dtype: object

(9,)

tconst                tt11818684
titleType              tvEpisode
primaryTitle      Episode #1.879
originalTitle     Episode #1.879
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001465, dtype: object

(9,)

tconst                tt11818686
titleType              tvEpisode
primaryTitle      Episode #1.880
originalTitle     Episode #1.880
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001466, dtype: object

(9,)

tconst                tt11818688
titleType              tvEpisode
primaryTitle           Pardon Me
originalTitle          Pardon Me
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            News,Talk-Show
Name: 2001467, dtype: object

(9,)

tconst                                      tt1181868
titleType                                   tvEpisode
primaryTitle      Sono yuruyaka na toki no naka ni...
originalTitle     Sono yuruyaka na toki no naka ni...
isAdult                                             0
startYear                                        2008
endYear                                            \N
runtimeMinutes                                     23
genres                         Animation,Comedy,Drama
Name: 2001468, dtype: object

(9,)

tconst                                tt11818690
titleType                                  movie
primaryTitle      Stalingrad: The Grain Elevator
originalTitle     Stalingrad: The Grain Elevator
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                53
genres                               Documentary
Name: 2001469, dtype: object

(9,)

tconst                tt11818692
titleType              tvEpisode
primaryTitle      Episode #1.641
originalTitle     Episode #1.641
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001470, dtype: object

(9,)

tconst                tt11818694
titleType              tvEpisode
primaryTitle      Episode #1.642
originalTitle     Episode #1.642
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001471, dtype: object

(9,)

tconst                tt11818696
titleType              tvEpisode
primaryTitle      Episode #1.643
originalTitle     Episode #1.643
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001472, dtype: object

(9,)

tconst                      tt11818698
titleType                    tvEpisode
primaryTitle      Règlement de comptes
originalTitle     Règlement de comptes
isAdult                              0
startYear                         2012
endYear                             \N
runtimeMinutes                      26
genres                           Drama
Name: 2001473, dtype: object

(9,)

tconst               tt1181869
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001474, dtype: object

(9,)

tconst                                     tt11818700
titleType                                       video
primaryTitle      Hedda Mae: Pride Goes Before a Fall
originalTitle     Hedda Mae: Pride Goes Before a Fall
isAdult                                             0
startYear                                          \N
endYear                                            \N
runtimeMinutes                                     \N
genres                                    Music,Short
Name: 2001475, dtype: object

(9,)

tconst                tt11818702
titleType              tvEpisode
primaryTitle      Episode #1.644
originalTitle     Episode #1.644
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001476, dtype: object

(9,)

tconst                  tt11818704
titleType                tvEpisode
primaryTitle         Episode #16.2
originalTitle        Episode #16.2
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  69
genres            Comedy,Game-Show
Name: 2001477, dtype: object

(9,)

tconst                tt11818706
titleType              tvEpisode
primaryTitle      Episode #1.645
originalTitle     Episode #1.645
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001478, dtype: object

(9,)

tconst                tt11818708
titleType              tvEpisode
primaryTitle      Episode #1.646
originalTitle     Episode #1.646
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001479, dtype: object

(9,)

tconst               tt1181870
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001480, dtype: object

(9,)

tconst                tt11818712
titleType              tvEpisode
primaryTitle      Episode #1.647
originalTitle     Episode #1.647
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001481, dtype: object

(9,)

tconst                tt11818714
titleType              tvEpisode
primaryTitle      Episode #1.648
originalTitle     Episode #1.648
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001482, dtype: object

(9,)

tconst                tt11818716
titleType              tvEpisode
primaryTitle      Episode #1.649
originalTitle     Episode #1.649
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001483, dtype: object

(9,)

tconst                tt11818718
titleType              tvEpisode
primaryTitle      Episode #1.650
originalTitle     Episode #1.650
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001484, dtype: object

(9,)

tconst               tt1181871
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001485, dtype: object

(9,)

tconst              tt11818720
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2001486, dtype: object

(9,)

tconst                tt11818722
titleType              tvEpisode
primaryTitle      Episode #1.651
originalTitle     Episode #1.651
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001487, dtype: object

(9,)

tconst                tt11818724
titleType              tvEpisode
primaryTitle      Episode #1.653
originalTitle     Episode #1.653
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001488, dtype: object

(9,)

tconst                tt11818726
titleType              tvEpisode
primaryTitle      Episode #1.652
originalTitle     Episode #1.652
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001489, dtype: object

(9,)

tconst                tt11818728
titleType              tvEpisode
primaryTitle      Episode #1.654
originalTitle     Episode #1.654
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001490, dtype: object

(9,)

tconst               tt1181872
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001491, dtype: object

(9,)

tconst                tt11818730
titleType              tvEpisode
primaryTitle      Episode #1.655
originalTitle     Episode #1.655
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001492, dtype: object

(9,)

tconst                    tt11818732
titleType                  tvEpisode
primaryTitle            Episode #8.2
originalTitle           Episode #8.2
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres            Reality-TV,Romance
Name: 2001493, dtype: object

(9,)

tconst                tt11818734
titleType              tvEpisode
primaryTitle      Episode #1.656
originalTitle     Episode #1.656
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001494, dtype: object

(9,)

tconst                tt11818736
titleType              tvEpisode
primaryTitle      Episode #1.657
originalTitle     Episode #1.657
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001495, dtype: object

(9,)

tconst                tt11818738
titleType              tvEpisode
primaryTitle      Episode #1.659
originalTitle     Episode #1.659
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001496, dtype: object

(9,)

tconst                         tt1181873
titleType                      tvEpisode
primaryTitle                  Viewer FAQ
originalTitle                 Viewer FAQ
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        21
genres            Documentary,Reality-TV
Name: 2001497, dtype: object

(9,)

tconst                tt11818740
titleType              tvEpisode
primaryTitle      Episode #1.658
originalTitle     Episode #1.658
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001498, dtype: object

(9,)

tconst                tt11818742
titleType              tvEpisode
primaryTitle      Episode #1.660
originalTitle     Episode #1.660
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001499, dtype: object

(9,)

tconst                tt11818744
titleType              tvEpisode
primaryTitle      Episode #1.381
originalTitle     Episode #1.381
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001500, dtype: object

(9,)

tconst                    tt11818746
titleType                  tvEpisode
primaryTitle            Episode #8.3
originalTitle           Episode #8.3
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres            Reality-TV,Romance
Name: 2001501, dtype: object

(9,)

tconst                tt11818748
titleType              tvEpisode
primaryTitle      Episode #1.383
originalTitle     Episode #1.383
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001502, dtype: object

(9,)

tconst                         tt1181874
titleType                      tvEpisode
primaryTitle          Winter Preparation
originalTitle         Winter Preparation
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        21
genres            Documentary,Reality-TV
Name: 2001503, dtype: object

(9,)

tconst                tt11818750
titleType              tvEpisode
primaryTitle      Episode #1.382
originalTitle     Episode #1.382
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001504, dtype: object

(9,)

tconst                   tt11818752
titleType                 tvEpisode
primaryTitle      Shalini Kidnapped
originalTitle     Shalini Kidnapped
isAdult                           0
startYear                        \N
endYear                          \N
runtimeMinutes                   \N
genres                        Crime
Name: 2001505, dtype: object

(9,)

tconst                   tt11818754
titleType              tvMiniSeries
primaryTitle      Dan Reviews Stuff
originalTitle     Dan Reviews Stuff
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2001506, dtype: object

(9,)

tconst                tt11818756
titleType              tvEpisode
primaryTitle      Episode #1.385
originalTitle     Episode #1.385
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001507, dtype: object

(9,)

tconst                    tt11818758
titleType                  tvEpisode
primaryTitle            Episode #8.4
originalTitle           Episode #8.4
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres            Reality-TV,Romance
Name: 2001508, dtype: object

(9,)

tconst                         tt1181875
titleType                      tvEpisode
primaryTitle          Family Photo Shoot
originalTitle         Family Photo Shoot
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        22
genres            Documentary,Reality-TV
Name: 2001509, dtype: object

(9,)

tconst                tt11818760
titleType              tvEpisode
primaryTitle      Episode #1.386
originalTitle     Episode #1.386
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001510, dtype: object

(9,)

tconst                tt11818762
titleType              tvEpisode
primaryTitle      Episode #1.387
originalTitle     Episode #1.387
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001511, dtype: object

(9,)

tconst                tt11818764
titleType              tvEpisode
primaryTitle      Episode #1.388
originalTitle     Episode #1.388
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001512, dtype: object

(9,)

tconst                tt11818766
titleType              tvEpisode
primaryTitle      Episode #1.389
originalTitle     Episode #1.389
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001513, dtype: object

(9,)

tconst                tt11818768
titleType              tvEpisode
primaryTitle      Episode #1.391
originalTitle     Episode #1.391
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001514, dtype: object

(9,)

tconst                               tt11818770
titleType                             tvEpisode
primaryTitle      Episode dated 6 November 2018
originalTitle     Episode dated 6 November 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001515, dtype: object

(9,)

tconst                                tt11818772
titleType                              tvEpisode
primaryTitle      Episode dated 12 November 2018
originalTitle     Episode dated 12 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001516, dtype: object

(9,)

tconst                tt11818774
titleType              tvEpisode
primaryTitle      Episode #1.390
originalTitle     Episode #1.390
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001517, dtype: object

(9,)

tconst                               tt11818776
titleType                             tvEpisode
primaryTitle      Episode dated 7 November 2018
originalTitle     Episode dated 7 November 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001518, dtype: object

(9,)

tconst                               tt11818778
titleType                             tvEpisode
primaryTitle      Episode dated 5 November 2018
originalTitle     Episode dated 5 November 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001519, dtype: object

(9,)

tconst                tt1181877
titleType          tvMiniSeries
primaryTitle      Om ett hjärta
originalTitle     Om ett hjärta
isAdult                       0
startYear                  2008
endYear                    2008
runtimeMinutes              176
genres                    Drama
Name: 2001520, dtype: object

(9,)

tconst                               tt11818780
titleType                             tvEpisode
primaryTitle      Episode dated 8 November 2018
originalTitle     Episode dated 8 November 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001521, dtype: object

(9,)

tconst                                tt11818782
titleType                              tvEpisode
primaryTitle      Episode dated 13 November 2018
originalTitle     Episode dated 13 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001522, dtype: object

(9,)

tconst                                tt11818784
titleType                              tvEpisode
primaryTitle      Episode dated 16 November 2018
originalTitle     Episode dated 16 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001523, dtype: object

(9,)

tconst                                tt11818786
titleType                              tvEpisode
primaryTitle      Episode dated 14 November 2018
originalTitle     Episode dated 14 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001524, dtype: object

(9,)

tconst                tt11818788
titleType              tvEpisode
primaryTitle      Episode #1.392
originalTitle     Episode #1.392
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001525, dtype: object

(9,)

tconst                               tt1181878
titleType                            tvEpisode
primaryTitle      ...Towa no... Inori wo......
originalTitle     ...Towa no... Inori wo......
isAdult                                      0
startYear                                 2001
endYear                                     \N
runtimeMinutes                              23
genres                        Animation,Comedy
Name: 2001526, dtype: object

(9,)

tconst                    tt11818790
titleType                  tvEpisode
primaryTitle            Episode #8.5
originalTitle           Episode #8.5
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres            Reality-TV,Romance
Name: 2001527, dtype: object

(9,)

tconst                                tt11818792
titleType                              tvEpisode
primaryTitle      Episode dated 26 November 2018
originalTitle     Episode dated 26 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001528, dtype: object

(9,)

tconst                                tt11818794
titleType                              tvEpisode
primaryTitle      Episode dated 28 November 2018
originalTitle     Episode dated 28 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001529, dtype: object

(9,)

tconst                                tt11818796
titleType                              tvEpisode
primaryTitle      Episode dated 19 November 2018
originalTitle     Episode dated 19 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001530, dtype: object

(9,)

tconst                                tt11818798
titleType                              tvEpisode
primaryTitle      Episode dated 23 November 2018
originalTitle     Episode dated 23 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001531, dtype: object

(9,)

tconst                      tt1181879
titleType                   tvEpisode
primaryTitle      Ai no obentô desuno
originalTitle     Ai no obentô desuno
isAdult                             0
startYear                        2001
endYear                            \N
runtimeMinutes                     23
genres               Animation,Comedy
Name: 2001532, dtype: object

(9,)

tconst                                tt11818800
titleType                              tvEpisode
primaryTitle      Episode dated 20 November 2018
originalTitle     Episode dated 20 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001533, dtype: object

(9,)

tconst                                tt11818802
titleType                              tvEpisode
primaryTitle      Episode dated 22 November 2018
originalTitle     Episode dated 22 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001534, dtype: object

(9,)

tconst                                tt11818804
titleType                              tvEpisode
primaryTitle      Episode dated 21 November 2018
originalTitle     Episode dated 21 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001535, dtype: object

(9,)

tconst                                tt11818806
titleType                              tvEpisode
primaryTitle      Episode dated 27 November 2018
originalTitle     Episode dated 27 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001536, dtype: object

(9,)

tconst                                tt11818808
titleType                              tvEpisode
primaryTitle      Episode dated 29 November 2018
originalTitle     Episode dated 29 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001537, dtype: object

(9,)

tconst                    tt1181880
titleType                 tvEpisode
primaryTitle      Aitai... onî chan
originalTitle     Aitai... onî chan
isAdult                           0
startYear                      2001
endYear                          \N
runtimeMinutes                   23
genres             Animation,Comedy
Name: 2001538, dtype: object

(9,)

tconst                tt11818810
titleType              tvEpisode
primaryTitle      Episode #1.393
originalTitle     Episode #1.393
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001539, dtype: object

(9,)

tconst                tt11818812
titleType              tvEpisode
primaryTitle      Episode #1.394
originalTitle     Episode #1.394
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001540, dtype: object

(9,)

tconst                tt11818814
titleType              tvEpisode
primaryTitle      Episode #1.396
originalTitle     Episode #1.396
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001541, dtype: object

(9,)

tconst                tt11818816
titleType              tvEpisode
primaryTitle      Episode #1.395
originalTitle     Episode #1.395
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001542, dtype: object

(9,)

tconst               tt11818818
titleType                 movie
primaryTitle      God's Country
originalTitle     God's Country
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                 Thriller
Name: 2001543, dtype: object

(9,)

tconst                           tt1181881
titleType                        tvEpisode
primaryTitle      Akini to shîkuretto tsuâ
originalTitle     Akini to shîkuretto tsuâ
isAdult                                  0
startYear                             2001
endYear                                 \N
runtimeMinutes                          23
genres                    Animation,Comedy
Name: 2001544, dtype: object

(9,)

tconst                                tt11818820
titleType                              tvEpisode
primaryTitle      Episode dated 30 November 2018
originalTitle     Episode dated 30 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001545, dtype: object

(9,)

tconst                tt11818822
titleType              tvEpisode
primaryTitle      Episode #1.397
originalTitle     Episode #1.397
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001546, dtype: object

(9,)

tconst                tt11818824
titleType              tvEpisode
primaryTitle      Episode #1.398
originalTitle     Episode #1.398
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001547, dtype: object

(9,)

tconst                tt11818826
titleType              tvEpisode
primaryTitle      Episode #1.399
originalTitle     Episode #1.399
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001548, dtype: object

(9,)

tconst                tt11818828
titleType              tvEpisode
primaryTitle      Episode #1.400
originalTitle     Episode #1.400
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001549, dtype: object

(9,)

tconst                        tt1181882
titleType                     tvEpisode
primaryTitle      Ani chama, cheki desu
originalTitle     Ani chama, cheki desu
isAdult                               0
startYear                          2001
endYear                              \N
runtimeMinutes                       23
genres                 Animation,Comedy
Name: 2001550, dtype: object

(9,)

tconst                               tt11818830
titleType                             tvEpisode
primaryTitle      Episode dated 3 December 2018
originalTitle     Episode dated 3 December 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001551, dtype: object

(9,)

tconst                tt11818832
titleType              tvEpisode
primaryTitle      Episode #1.142
originalTitle     Episode #1.142
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001552, dtype: object

(9,)

tconst                tt11818834
titleType              tvEpisode
primaryTitle      Episode #1.141
originalTitle     Episode #1.141
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001553, dtype: object

(9,)

tconst                tt11818836
titleType              tvEpisode
primaryTitle      Episode #1.143
originalTitle     Episode #1.143
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001554, dtype: object

(9,)

tconst                tt11818838
titleType              tvEpisode
primaryTitle      Episode #1.144
originalTitle     Episode #1.144
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001555, dtype: object

(9,)

tconst                   tt1181883
titleType                tvEpisode
primaryTitle        Aniki ni mî tû
originalTitle       Aniki ni mî tû
isAdult                          0
startYear                     2001
endYear                         \N
runtimeMinutes                  23
genres            Animation,Comedy
Name: 2001556, dtype: object

(9,)

tconst                tt11818840
titleType              tvEpisode
primaryTitle      Episode #1.145
originalTitle     Episode #1.145
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001557, dtype: object

(9,)

tconst                tt11818842
titleType              tvEpisode
primaryTitle      Episode #1.146
originalTitle     Episode #1.146
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001558, dtype: object

(9,)

tconst                               tt11818844
titleType                             tvEpisode
primaryTitle      Episode dated 7 December 2018
originalTitle     Episode dated 7 December 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001559, dtype: object

(9,)

tconst                tt11818846
titleType              tvEpisode
primaryTitle      Episode #1.147
originalTitle     Episode #1.147
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001560, dtype: object

(9,)

tconst               tt11818848
titleType             tvEpisode
primaryTitle      The First Try
originalTitle     The First Try
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2001561, dtype: object

(9,)

tconst                   tt1181884
titleType                tvEpisode
primaryTitle         Aniki to mêru
originalTitle        Aniki to mêru
isAdult                          0
startYear                     2001
endYear                         \N
runtimeMinutes                  23
genres            Animation,Comedy
Name: 2001562, dtype: object

(9,)

tconst                               tt11818850
titleType                             tvEpisode
primaryTitle      Episode dated 4 December 2018
originalTitle     Episode dated 4 December 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001563, dtype: object

(9,)

tconst                tt11818852
titleType              tvEpisode
primaryTitle      Episode #1.148
originalTitle     Episode #1.148
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001564, dtype: object

(9,)

tconst                               tt11818854
titleType                             tvEpisode
primaryTitle      Episode dated 5 December 2018
originalTitle     Episode dated 5 December 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001565, dtype: object

(9,)

tconst                tt11818856
titleType              tvEpisode
primaryTitle      Episode #1.149
originalTitle     Episode #1.149
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001566, dtype: object

(9,)

tconst                tt11818858
titleType              tvEpisode
primaryTitle      Episode #1.150
originalTitle     Episode #1.150
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001567, dtype: object

(9,)

tconst                   tt1181885
titleType                tvEpisode
primaryTitle        Aria no oribon
originalTitle       Aria no oribon
isAdult                          0
startYear                     2001
endYear                         \N
runtimeMinutes                  23
genres            Animation,Comedy
Name: 2001568, dtype: object

(9,)

tconst                                                   tt11818860
titleType                                                 tvEpisode
primaryTitle      Ambassador: Exposing UN Waste & Trump's Pro Ga...
originalTitle     Ambassador: Exposing UN Waste & Trump's Pro Ga...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2001569, dtype: object

(9,)

tconst                tt11818864
titleType              tvEpisode
primaryTitle      Episode #1.152
originalTitle     Episode #1.152
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001570, dtype: object

(9,)

tconst                                tt11818866
titleType                              tvEpisode
primaryTitle      Episode dated 12 December 2018
originalTitle     Episode dated 12 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001571, dtype: object

(9,)

tconst                                tt11818868
titleType                              tvEpisode
primaryTitle      Episode dated 11 December 2018
originalTitle     Episode dated 11 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001572, dtype: object

(9,)

tconst                     tt1181886
titleType                  tvEpisode
primaryTitle      Bakansu wa rabu yo
originalTitle     Bakansu wa rabu yo
isAdult                            0
startYear                       2001
endYear                           \N
runtimeMinutes                    23
genres              Animation,Comedy
Name: 2001573, dtype: object

(9,)

tconst                                tt11818870
titleType                              tvEpisode
primaryTitle      Episode dated 13 December 2018
originalTitle     Episode dated 13 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001574, dtype: object

(9,)

tconst                                tt11818872
titleType                              tvEpisode
primaryTitle      Episode dated 14 December 2018
originalTitle     Episode dated 14 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001575, dtype: object

(9,)

tconst                                tt11818874
titleType                              tvEpisode
primaryTitle      Episode dated 10 December 2018
originalTitle     Episode dated 10 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001576, dtype: object

(9,)

tconst                tt11818876
titleType              tvEpisode
primaryTitle      Episode #1.153
originalTitle     Episode #1.153
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001577, dtype: object

(9,)

tconst                tt11818878
titleType              tvEpisode
primaryTitle      Episode #1.154
originalTitle     Episode #1.154
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001578, dtype: object

(9,)

tconst                       tt1181887
titleType                    tvEpisode
primaryTitle      Boku no guradyuêshon
originalTitle     Boku no guradyuêshon
isAdult                              0
startYear                         2001
endYear                             \N
runtimeMinutes                      23
genres                Animation,Comedy
Name: 2001579, dtype: object

(9,)

tconst                tt11818880
titleType              tvEpisode
primaryTitle      Episode #1.155
originalTitle     Episode #1.155
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001580, dtype: object

(9,)

tconst                tt11818882
titleType              tvEpisode
primaryTitle      Episode #1.156
originalTitle     Episode #1.156
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001581, dtype: object

(9,)

tconst                tt11818884
titleType              tvEpisode
primaryTitle      Episode #1.157
originalTitle     Episode #1.157
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001582, dtype: object

(9,)

tconst                tt11818886
titleType              tvEpisode
primaryTitle      Episode #1.158
originalTitle     Episode #1.158
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001583, dtype: object

(9,)

tconst                 tt11818888
titleType               tvEpisode
primaryTitle      Episode #1.2944
originalTitle     Episode #1.2944
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2001584, dtype: object

(9,)

tconst                   tt1181888
titleType                tvEpisode
primaryTitle        Ganbatte, anî!
originalTitle       Ganbatte, anî!
isAdult                          0
startYear                     2001
endYear                         \N
runtimeMinutes                  23
genres            Animation,Comedy
Name: 2001585, dtype: object

(9,)

tconst                tt11818890
titleType              tvEpisode
primaryTitle      Episode #1.160
originalTitle     Episode #1.160
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2001586, dtype: object

(9,)

tconst              tt11818892
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001587, dtype: object

(9,)

tconst                      tt11818894
titleType                    tvEpisode
primaryTitle           Episode #1.1281
originalTitle          Episode #1.1281
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001588, dtype: object

(9,)

tconst                                tt11818896
titleType                              tvEpisode
primaryTitle      Episode dated 20 December 2018
originalTitle     Episode dated 20 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001589, dtype: object

(9,)

tconst                                tt11818898
titleType                              tvEpisode
primaryTitle      Episode dated 24 December 2018
originalTitle     Episode dated 24 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001590, dtype: object

(9,)

tconst                          tt1181889
titleType                       tvEpisode
primaryTitle      Hajimete no okyaku sama
originalTitle     Hajimete no okyaku sama
isAdult                                 0
startYear                            2001
endYear                                \N
runtimeMinutes                         23
genres                   Animation,Comedy
Name: 2001591, dtype: object

(9,)

tconst                                tt11818900
titleType                              tvEpisode
primaryTitle      Episode dated 27 December 2018
originalTitle     Episode dated 27 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001592, dtype: object

(9,)

tconst                                tt11818902
titleType                              tvEpisode
primaryTitle      Episode dated 17 December 2018
originalTitle     Episode dated 17 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001593, dtype: object

(9,)

tconst              tt11818904
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001594, dtype: object

(9,)

tconst                                tt11818906
titleType                              tvEpisode
primaryTitle      Episode dated 21 December 2018
originalTitle     Episode dated 21 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001595, dtype: object

(9,)

tconst                                tt11818908
titleType                              tvEpisode
primaryTitle      Episode dated 31 December 2018
originalTitle     Episode dated 31 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001596, dtype: object

(9,)

tconst                   tt1181890
titleType                tvEpisode
primaryTitle      Hontô no kimochi
originalTitle     Hontô no kimochi
isAdult                          0
startYear                     2001
endYear                         \N
runtimeMinutes                  23
genres            Animation,Comedy
Name: 2001597, dtype: object

(9,)

tconst                                tt11818910
titleType                              tvEpisode
primaryTitle      Episode dated 25 December 2018
originalTitle     Episode dated 25 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001598, dtype: object

(9,)

tconst                                tt11818912
titleType                              tvEpisode
primaryTitle      Episode dated 26 December 2018
originalTitle     Episode dated 26 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001599, dtype: object

(9,)

tconst                                tt11818914
titleType                              tvEpisode
primaryTitle      Episode dated 19 December 2018
originalTitle     Episode dated 19 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001600, dtype: object

(9,)

tconst                                tt11818916
titleType                              tvEpisode
primaryTitle      Episode dated 18 December 2018
originalTitle     Episode dated 18 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001601, dtype: object

(9,)

tconst                                tt11818918
titleType                              tvEpisode
primaryTitle      Episode dated 28 December 2018
originalTitle     Episode dated 28 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001602, dtype: object

(9,)

tconst                          tt1181891
titleType                       tvEpisode
primaryTitle      Itsu no hi ka futari de
originalTitle     Itsu no hi ka futari de
isAdult                                 0
startYear                            2001
endYear                                \N
runtimeMinutes                         23
genres                   Animation,Comedy
Name: 2001603, dtype: object

(9,)

tconst                  tt11818920
titleType                tvEpisode
primaryTitle      Crushed Hillside
originalTitle     Crushed Hillside
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                 Documentary
Name: 2001604, dtype: object

(9,)

tconst              tt11818922
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001605, dtype: object

(9,)

tconst                      tt11818924
titleType                    tvEpisode
primaryTitle           Episode #1.1283
originalTitle          Episode #1.1283
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001606, dtype: object

(9,)

tconst                      tt11818926
titleType                    tvEpisode
primaryTitle           Episode #1.1282
originalTitle          Episode #1.1282
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001607, dtype: object

(9,)

tconst                      tt11818928
titleType                    tvEpisode
primaryTitle           Episode #1.1284
originalTitle          Episode #1.1284
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001608, dtype: object

(9,)

tconst                    tt1181892
titleType                 tvEpisode
primaryTitle      Kaho, ganbacchau!
originalTitle     Kaho, ganbacchau!
isAdult                           0
startYear                      2001
endYear                          \N
runtimeMinutes                   24
genres             Animation,Comedy
Name: 2001609, dtype: object

(9,)

tconst                      tt11818930
titleType                    tvEpisode
primaryTitle           Episode #1.1285
originalTitle          Episode #1.1285
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001610, dtype: object

(9,)

tconst                      tt11818932
titleType                    tvEpisode
primaryTitle           Episode #1.1286
originalTitle          Episode #1.1286
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001611, dtype: object

(9,)

tconst                      tt11818934
titleType                    tvEpisode
primaryTitle           Episode #1.1287
originalTitle          Episode #1.1287
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001612, dtype: object

(9,)

tconst              tt11818936
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001613, dtype: object

(9,)

tconst                      tt11818938
titleType                    tvEpisode
primaryTitle           Episode #1.1288
originalTitle          Episode #1.1288
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001614, dtype: object

(9,)

tconst                   tt1181893
titleType                tvEpisode
primaryTitle      Koi suru kisetsu
originalTitle     Koi suru kisetsu
isAdult                          0
startYear                     2001
endYear                         \N
runtimeMinutes                  23
genres            Animation,Comedy
Name: 2001615, dtype: object

(9,)

tconst                        tt11818942
titleType                      tvEpisode
primaryTitle      Nenavizhu ponedel'niki
originalTitle     Nenavizhu ponedel'niki
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                            Comedy
Name: 2001616, dtype: object

(9,)

tconst                      tt11818944
titleType                    tvEpisode
primaryTitle           Episode #1.1290
originalTitle          Episode #1.1290
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001617, dtype: object

(9,)

tconst                      tt11818946
titleType                    tvEpisode
primaryTitle           Episode #1.1289
originalTitle          Episode #1.1289
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001618, dtype: object

(9,)

tconst                      tt11818948
titleType                    tvEpisode
primaryTitle           Episode #1.1291
originalTitle          Episode #1.1291
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001619, dtype: object

(9,)

tconst                   tt1181894
titleType                tvEpisode
primaryTitle        Kuma san doko?
originalTitle       Kuma san doko?
isAdult                          0
startYear                     2001
endYear                         \N
runtimeMinutes                  23
genres            Animation,Comedy
Name: 2001620, dtype: object

(9,)

tconst                      tt11818950
titleType                    tvEpisode
primaryTitle           Episode #1.1292
originalTitle          Episode #1.1292
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001621, dtype: object

(9,)

tconst              tt11818952
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2001622, dtype: object

(9,)

tconst                      tt11818954
titleType                    tvEpisode
primaryTitle           Episode #1.1293
originalTitle          Episode #1.1293
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001623, dtype: object

(9,)

tconst                     tt11818956
titleType                   tvEpisode
primaryTitle      Love and Flashcards
originalTitle     Love and Flashcards
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2001624, dtype: object

(9,)

tconst                      tt11818958
titleType                    tvEpisode
primaryTitle           Episode #1.1294
originalTitle          Episode #1.1294
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001625, dtype: object

(9,)

tconst                           tt1181895
titleType                        tvEpisode
primaryTitle      Kurisumasu ravu desutinî
originalTitle     Kurisumasu ravu desutinî
isAdult                                  0
startYear                             2001
endYear                                 \N
runtimeMinutes                          23
genres                    Animation,Comedy
Name: 2001626, dtype: object

(9,)

tconst                      tt11818960
titleType                    tvEpisode
primaryTitle           Episode #1.1295
originalTitle          Episode #1.1295
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001627, dtype: object

(9,)

tconst                      tt11818962
titleType                    tvEpisode
primaryTitle           Episode #1.1297
originalTitle          Episode #1.1297
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001628, dtype: object

(9,)

tconst                      tt11818964
titleType                    tvEpisode
primaryTitle           Episode #1.1296
originalTitle          Episode #1.1296
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001629, dtype: object

(9,)

tconst                      tt11818966
titleType                    tvEpisode
primaryTitle           Episode #1.1298
originalTitle          Episode #1.1298
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001630, dtype: object

(9,)

tconst                      tt11818968
titleType                    tvEpisode
primaryTitle           Episode #1.1299
originalTitle          Episode #1.1299
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001631, dtype: object

(9,)

tconst                     tt1181896
titleType                  tvEpisode
primaryTitle      Natsu ga kimashita
originalTitle     Natsu ga kimashita
isAdult                            0
startYear                       2001
endYear                           \N
runtimeMinutes                    23
genres              Animation,Comedy
Name: 2001632, dtype: object

(9,)

tconst                   tt11818970
titleType                     short
primaryTitle      Hello! Mom & Dad!
originalTitle     Hello! Mom & Dad!
isAdult                           0
startYear                        \N
endYear                          \N
runtimeMinutes                   \N
genres                 Horror,Short
Name: 2001633, dtype: object

(9,)

tconst                      tt11818972
titleType                    tvEpisode
primaryTitle           Episode #1.1300
originalTitle          Episode #1.1300
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001634, dtype: object

(9,)

tconst                      tt11818974
titleType                    tvEpisode
primaryTitle           Episode #1.1041
originalTitle          Episode #1.1041
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001635, dtype: object

(9,)

tconst                      tt11818976
titleType                    tvEpisode
primaryTitle           Episode #1.1042
originalTitle          Episode #1.1042
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001636, dtype: object

(9,)

tconst                      tt11818978
titleType                    tvEpisode
primaryTitle           Episode #1.1043
originalTitle          Episode #1.1043
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001637, dtype: object

(9,)

tconst                    tt1181897
titleType                 tvEpisode
primaryTitle      Okyû desuwa... po
originalTitle     Okyû desuwa... po
isAdult                           0
startYear                      2001
endYear                          \N
runtimeMinutes                   23
genres             Animation,Comedy
Name: 2001638, dtype: object

(9,)

tconst                      tt11818980
titleType                    tvEpisode
primaryTitle           Episode #1.1045
originalTitle          Episode #1.1045
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001639, dtype: object

(9,)

tconst                       tt11818982
titleType                         short
primaryTitle      Skuddene På Bergenhus
originalTitle     Skuddene På Bergenhus
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres                      Drama,Short
Name: 2001640, dtype: object

(9,)

tconst                      tt11818984
titleType                    tvEpisode
primaryTitle           Episode #1.1044
originalTitle          Episode #1.1044
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001641, dtype: object

(9,)

tconst                      tt11818986
titleType                    tvEpisode
primaryTitle           Episode #1.1046
originalTitle          Episode #1.1046
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001642, dtype: object

(9,)

tconst                      tt11818988
titleType                    tvEpisode
primaryTitle           Episode #1.1047
originalTitle          Episode #1.1047
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001643, dtype: object

(9,)

tconst                       tt1181898
titleType                    tvEpisode
primaryTitle      Onî chan to no natsu
originalTitle     Onî chan to no natsu
isAdult                              0
startYear                         2001
endYear                             \N
runtimeMinutes                      23
genres                Animation,Comedy
Name: 2001644, dtype: object

(9,)

tconst                      tt11818990
titleType                    tvEpisode
primaryTitle           Episode #1.1048
originalTitle          Episode #1.1048
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001645, dtype: object

(9,)

tconst                                tt11818992
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001646, dtype: object

(9,)

tconst                      tt11818994
titleType                    tvEpisode
primaryTitle           Episode #1.1049
originalTitle          Episode #1.1049
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001647, dtype: object

(9,)

tconst                      tt11818996
titleType                    tvEpisode
primaryTitle           Episode #1.1050
originalTitle          Episode #1.1050
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001648, dtype: object

(9,)

tconst                                tt11818998
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001649, dtype: object

(9,)

tconst                       tt1181899
titleType                    tvEpisode
primaryTitle      Onî chan wa ôji sama
originalTitle     Onî chan wa ôji sama
isAdult                              0
startYear                         2001
endYear                             \N
runtimeMinutes                      23
genres                Animation,Comedy
Name: 2001650, dtype: object

(9,)

tconst                      tt11819000
titleType                    tvEpisode
primaryTitle           Episode #1.1051
originalTitle          Episode #1.1051
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001651, dtype: object

(9,)

tconst                      tt11819002
titleType                    tvEpisode
primaryTitle           Episode #1.1052
originalTitle          Episode #1.1052
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001652, dtype: object

(9,)

tconst                              tt11819004
titleType                            tvEpisode
primaryTitle      Seasoning the Day in Iceland
originalTitle     Seasoning the Day in Iceland
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                              Reality-TV
Name: 2001653, dtype: object

(9,)

tconst                      tt11819006
titleType                    tvEpisode
primaryTitle           Episode #1.1053
originalTitle          Episode #1.1053
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001654, dtype: object

(9,)

tconst                      tt11819008
titleType                    tvEpisode
primaryTitle           Episode #1.1056
originalTitle          Episode #1.1056
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001655, dtype: object

(9,)

tconst                     tt1181900
titleType                  tvEpisode
primaryTitle      Onî chan, daisuki!
originalTitle     Onî chan, daisuki!
isAdult                            0
startYear                       2001
endYear                           \N
runtimeMinutes                    23
genres              Animation,Comedy
Name: 2001656, dtype: object

(9,)

tconst                      tt11819010
titleType                    tvEpisode
primaryTitle           Episode #1.1054
originalTitle          Episode #1.1054
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001657, dtype: object

(9,)

tconst                      tt11819012
titleType                    tvEpisode
primaryTitle           Episode #1.1055
originalTitle          Episode #1.1055
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001658, dtype: object

(9,)

tconst                   tt11819014
titleType                 tvEpisode
primaryTitle      Behind the Camera
originalTitle     Behind the Camera
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                  Documentary
Name: 2001659, dtype: object

(9,)

tconst                                tt11819016
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001660, dtype: object

(9,)

tconst                      tt11819018
titleType                    tvEpisode
primaryTitle           Episode #1.1057
originalTitle          Episode #1.1057
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001661, dtype: object

(9,)

tconst                    tt1181901
titleType                 tvEpisode
primaryTitle      Onî sama to issho
originalTitle     Onî sama to issho
isAdult                           0
startYear                      2001
endYear                          \N
runtimeMinutes                   23
genres             Animation,Comedy
Name: 2001662, dtype: object

(9,)

tconst                      tt11819020
titleType                    tvEpisode
primaryTitle           Episode #1.1058
originalTitle          Episode #1.1058
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001663, dtype: object

(9,)

tconst                      tt11819022
titleType                    tvEpisode
primaryTitle           Episode #1.1059
originalTitle          Episode #1.1059
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001664, dtype: object

(9,)

tconst                      tt11819026
titleType                    tvEpisode
primaryTitle           Episode #1.1060
originalTitle          Episode #1.1060
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001665, dtype: object

(9,)

tconst              tt11819028
titleType                short
primaryTitle      Langley Park
originalTitle     Langley Park
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2001666, dtype: object

(9,)

tconst                    tt1181902
titleType                 tvEpisode
primaryTitle      Sayonara no yokan
originalTitle     Sayonara no yokan
isAdult                           0
startYear                      2001
endYear                          \N
runtimeMinutes                   23
genres             Animation,Comedy
Name: 2001667, dtype: object

(9,)

tconst                      tt11819030
titleType                    tvEpisode
primaryTitle            Episode #1.821
originalTitle           Episode #1.821
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001668, dtype: object

(9,)

tconst                      tt11819032
titleType                    tvEpisode
primaryTitle            Episode #1.822
originalTitle           Episode #1.822
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001669, dtype: object

(9,)

tconst                      tt11819034
titleType                    tvEpisode
primaryTitle            Episode #1.823
originalTitle           Episode #1.823
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001670, dtype: object

(9,)

tconst                      tt11819036
titleType                    tvEpisode
primaryTitle            Episode #1.825
originalTitle           Episode #1.825
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001671, dtype: object

(9,)

tconst                      tt11819038
titleType                    tvEpisode
primaryTitle            Episode #1.824
originalTitle           Episode #1.824
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001672, dtype: object

(9,)

tconst                    tt1181903
titleType                 tvEpisode
primaryTitle      Yakusoku no shima
originalTitle     Yakusoku no shima
isAdult                           0
startYear                      2001
endYear                          \N
runtimeMinutes                   23
genres             Animation,Comedy
Name: 2001673, dtype: object

(9,)

tconst                      tt11819040
titleType                    tvEpisode
primaryTitle            Episode #1.826
originalTitle           Episode #1.826
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001674, dtype: object

(9,)

tconst                      tt11819042
titleType                    tvEpisode
primaryTitle            Episode #1.827
originalTitle           Episode #1.827
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001675, dtype: object

(9,)

tconst                      tt11819044
titleType                    tvEpisode
primaryTitle            Episode #1.828
originalTitle           Episode #1.828
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001676, dtype: object

(9,)

tconst                      tt11819046
titleType                    tvEpisode
primaryTitle            Episode #1.829
originalTitle           Episode #1.829
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001677, dtype: object

(9,)

tconst                                               tt11819048
titleType                                                 video
primaryTitle      A Colossal Tits Mama's Distorted Idea of Love
originalTitle     A Colossal Tits Mama's Distorted Idea of Love
isAdult                                                       1
startYear                                                  2019
endYear                                                      \N
runtimeMinutes                                              239
genres                                                    Adult
Name: 2001678, dtype: object

(9,)

tconst                                   tt1181904
titleType                                tvEpisode
primaryTitle      Anî to boku no magu cappu/Rinrin
originalTitle     Anî to boku no magu cappu/Rinrin
isAdult                                          0
startYear                                     2002
endYear                                         \N
runtimeMinutes                                  \N
genres                                   Animation
Name: 2001679, dtype: object

(9,)

tconst                      tt11819050
titleType                    tvEpisode
primaryTitle            Episode #1.830
originalTitle           Episode #1.830
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001680, dtype: object

(9,)

tconst                      tt11819052
titleType                    tvEpisode
primaryTitle            Episode #1.832
originalTitle           Episode #1.832
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001681, dtype: object

(9,)

tconst                      tt11819054
titleType                    tvEpisode
primaryTitle            Episode #1.831
originalTitle           Episode #1.831
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001682, dtype: object

(9,)

tconst                      tt11819056
titleType                    tvEpisode
primaryTitle            Episode #1.833
originalTitle           Episode #1.833
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001683, dtype: object

(9,)

tconst                      tt11819058
titleType                    tvEpisode
primaryTitle            Episode #1.834
originalTitle           Episode #1.834
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001684, dtype: object

(9,)

tconst                                      tt1181905
titleType                                   tvEpisode
primaryTitle      Ehehe... otomari no hi desu./Hinako
originalTitle     Ehehe... otomari no hi desu./Hinako
isAdult                                             0
startYear                                        2002
endYear                                            \N
runtimeMinutes                                     \N
genres                                      Animation
Name: 2001685, dtype: object

(9,)

tconst                      tt11819060
titleType                    tvEpisode
primaryTitle            Episode #1.835
originalTitle           Episode #1.835
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001686, dtype: object

(9,)

tconst                      tt11819062
titleType                    tvEpisode
primaryTitle            Episode #1.836
originalTitle           Episode #1.836
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001687, dtype: object

(9,)

tconst                      tt11819064
titleType                    tvEpisode
primaryTitle            Episode #1.837
originalTitle           Episode #1.837
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001688, dtype: object

(9,)

tconst                      tt11819066
titleType                    tvEpisode
primaryTitle            Episode #1.838
originalTitle           Episode #1.838
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001689, dtype: object

(9,)

tconst                      tt11819068
titleType                    tvEpisode
primaryTitle            Episode #1.839
originalTitle           Episode #1.839
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001690, dtype: object

(9,)

tconst                                      tt1181906
titleType                                   tvEpisode
primaryTitle      Himitsu no hanazono... nano!/Mamoru
originalTitle     Himitsu no hanazono... nano!/Mamoru
isAdult                                             0
startYear                                        2002
endYear                                            \N
runtimeMinutes                                     \N
genres                                      Animation
Name: 2001691, dtype: object

(9,)

tconst                      tt11819070
titleType                    tvEpisode
primaryTitle            Episode #1.840
originalTitle           Episode #1.840
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001692, dtype: object

(9,)

tconst                      tt11819072
titleType                    tvEpisode
primaryTitle            Episode #1.581
originalTitle           Episode #1.581
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001693, dtype: object

(9,)

tconst                      tt11819074
titleType                    tvEpisode
primaryTitle            Episode #1.582
originalTitle           Episode #1.582
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001694, dtype: object

(9,)

tconst                      tt11819076
titleType                    tvEpisode
primaryTitle            Episode #1.583
originalTitle           Episode #1.583
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001695, dtype: object

(9,)

tconst                      tt11819078
titleType                    tvEpisode
primaryTitle            Episode #1.584
originalTitle           Episode #1.584
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001696, dtype: object

(9,)

tconst                   tt1181907
titleType                tvEpisode
primaryTitle      Hâto deizu/Karen
originalTitle     Hâto deizu/Karen
isAdult                          0
startYear                     2002
endYear                         \N
runtimeMinutes                  \N
genres                   Animation
Name: 2001697, dtype: object

(9,)

tconst                 tt11819080
titleType               tvEpisode
primaryTitle       Spurned Again?
originalTitle      Spurned Again?
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                150
genres            Sport,Talk-Show
Name: 2001698, dtype: object

(9,)

tconst                      tt11819082
titleType                    tvEpisode
primaryTitle            Episode #1.585
originalTitle           Episode #1.585
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001699, dtype: object

(9,)

tconst                   tt11819084
titleType                     movie
primaryTitle      The Lotus Paradox
originalTitle     The Lotus Paradox
isAdult                           0
startYear                        \N
endYear                          \N
runtimeMinutes                   \N
genres                      Romance
Name: 2001700, dtype: object

(9,)

tconst                      tt11819086
titleType                    tvEpisode
primaryTitle            Episode #1.586
originalTitle           Episode #1.586
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001701, dtype: object

(9,)

tconst                      tt11819088
titleType                    tvEpisode
primaryTitle            Episode #1.588
originalTitle           Episode #1.588
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001702, dtype: object

(9,)

tconst                         tt1181908
titleType                      tvEpisode
primaryTitle      Mahô no kotoba/Chikage
originalTitle     Mahô no kotoba/Chikage
isAdult                                0
startYear                           2002
endYear                               \N
runtimeMinutes                        \N
genres                         Animation
Name: 2001703, dtype: object

(9,)

tconst                      tt11819092
titleType                    tvEpisode
primaryTitle            Episode #1.587
originalTitle           Episode #1.587
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001704, dtype: object

(9,)

tconst                      tt11819094
titleType                    tvEpisode
primaryTitle            Episode #1.589
originalTitle           Episode #1.589
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001705, dtype: object

(9,)

tconst                      tt11819096
titleType                    tvEpisode
primaryTitle            Episode #1.590
originalTitle           Episode #1.590
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001706, dtype: object

(9,)

tconst                       tt11819098
titleType                     tvEpisode
primaryTitle      Jojo Rabbit, Parasite
originalTitle     Jojo Rabbit, Parasite
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                             News
Name: 2001707, dtype: object

(9,)

tconst                       tt1181909
titleType                    tvEpisode
primaryTitle      Maron no giwaku/Aria
originalTitle     Maron no giwaku/Aria
isAdult                              0
startYear                         2002
endYear                             \N
runtimeMinutes                      \N
genres                       Animation
Name: 2001708, dtype: object

(9,)

tconst                      tt11819100
titleType                    tvEpisode
primaryTitle            Episode #1.592
originalTitle           Episode #1.592
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001709, dtype: object

(9,)

tconst                      tt11819102
titleType                    tvEpisode
primaryTitle            Episode #1.591
originalTitle           Episode #1.591
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001710, dtype: object

(9,)

tconst                      tt11819104
titleType                    tvEpisode
primaryTitle            Episode #1.593
originalTitle           Episode #1.593
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001711, dtype: object

(9,)

tconst                      tt11819108
titleType                    tvEpisode
primaryTitle            Episode #1.594
originalTitle           Episode #1.594
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001712, dtype: object

(9,)

tconst                              tt1181910
titleType                           tvEpisode
primaryTitle      Menkaibi nano desu!/Yotsuba
originalTitle     Menkaibi nano desu!/Yotsuba
isAdult                                     0
startYear                                2002
endYear                                    \N
runtimeMinutes                             \N
genres                              Animation
Name: 2001713, dtype: object

(9,)

tconst                      tt11819110
titleType                    tvEpisode
primaryTitle            Episode #1.595
originalTitle           Episode #1.595
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001714, dtype: object

(9,)

tconst                      tt11819112
titleType                    tvEpisode
primaryTitle            Episode #1.596
originalTitle           Episode #1.596
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001715, dtype: object

(9,)

tconst                      tt11819114
titleType                    tvEpisode
primaryTitle            Episode #1.597
originalTitle           Episode #1.597
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001716, dtype: object

(9,)

tconst                   tt11819116
titleType                     short
primaryTitle      Once Upon a Night
originalTitle     Once Upon a Night
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                  Drama,Short
Name: 2001717, dtype: object

(9,)

tconst                      tt11819118
titleType                    tvEpisode
primaryTitle            Episode #1.598
originalTitle           Episode #1.598
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001718, dtype: object

(9,)

tconst                                          tt1181911
titleType                                       tvEpisode
primaryTitle      Nagareru hoshi ni tsukinu negai wo/Kaho
originalTitle     Nagareru hoshi ni tsukinu negai wo/Kaho
isAdult                                                 0
startYear                                            2002
endYear                                                \N
runtimeMinutes                                         \N
genres                                          Animation
Name: 2001719, dtype: object

(9,)

tconst                      tt11819120
titleType                    tvEpisode
primaryTitle            Episode #1.599
originalTitle           Episode #1.599
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001720, dtype: object

(9,)

tconst                      tt11819122
titleType                    tvEpisode
primaryTitle            Episode #1.600
originalTitle           Episode #1.600
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001721, dtype: object

(9,)

tconst                      tt11819126
titleType                    tvEpisode
primaryTitle            Episode #1.181
originalTitle           Episode #1.181
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001722, dtype: object

(9,)

tconst                      tt11819128
titleType                    tvEpisode
primaryTitle            Episode #1.183
originalTitle           Episode #1.183
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001723, dtype: object

(9,)

tconst                                 tt1181912
titleType                              tvEpisode
primaryTitle      Omoide no takarabako/Shirayuki
originalTitle     Omoide no takarabako/Shirayuki
isAdult                                        0
startYear                                   2002
endYear                                       \N
runtimeMinutes                                \N
genres                                 Animation
Name: 2001724, dtype: object

(9,)

tconst                      tt11819130
titleType                    tvEpisode
primaryTitle            Episode #1.182
originalTitle           Episode #1.182
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001725, dtype: object

(9,)

tconst                      tt11819132
titleType                    tvEpisode
primaryTitle            Episode #1.184
originalTitle           Episode #1.184
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001726, dtype: object

(9,)

tconst                      tt11819134
titleType                        short
primaryTitle      Neuland: The Unknown
originalTitle     Neuland: The Unknown
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       3
genres                  Short,Thriller
Name: 2001727, dtype: object

(9,)

tconst                      tt11819136
titleType                    tvEpisode
primaryTitle            Episode #1.186
originalTitle           Episode #1.186
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001728, dtype: object

(9,)

tconst                      tt11819138
titleType                    tvEpisode
primaryTitle            Episode #1.185
originalTitle           Episode #1.185
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001729, dtype: object

(9,)

tconst                               tt1181913
titleType                            tvEpisode
primaryTitle      Onî sama no resutoran/Sakuya
originalTitle     Onî sama no resutoran/Sakuya
isAdult                                      0
startYear                                 2002
endYear                                     \N
runtimeMinutes                              \N
genres                               Animation
Name: 2001730, dtype: object

(9,)

tconst                      tt11819140
titleType                    tvEpisode
primaryTitle            Episode #1.187
originalTitle           Episode #1.187
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001731, dtype: object

(9,)

tconst                      tt11819142
titleType                    tvEpisode
primaryTitle            Episode #1.188
originalTitle           Episode #1.188
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001732, dtype: object

(9,)

tconst                      tt11819144
titleType                    tvEpisode
primaryTitle            Episode #1.189
originalTitle           Episode #1.189
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001733, dtype: object

(9,)

tconst                      tt11819146
titleType                    tvEpisode
primaryTitle            Episode #1.190
originalTitle           Episode #1.190
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001734, dtype: object

(9,)

tconst                      tt11819148
titleType                    tvEpisode
primaryTitle            Episode #1.191
originalTitle           Episode #1.191
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001735, dtype: object

(9,)

tconst                  tt1181914
titleType               tvEpisode
primaryTitle      Pyua kurisumasu
originalTitle     Pyua kurisumasu
isAdult                         0
startYear                    2002
endYear                        \N
runtimeMinutes                 \N
genres                  Animation
Name: 2001736, dtype: object

(9,)

tconst                      tt11819150
titleType                    tvEpisode
primaryTitle            Episode #1.192
originalTitle           Episode #1.192
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001737, dtype: object

(9,)

tconst                      tt11819152
titleType                    tvEpisode
primaryTitle            Episode #1.194
originalTitle           Episode #1.194
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001738, dtype: object

(9,)

tconst                      tt11819154
titleType                    tvEpisode
primaryTitle            Episode #1.193
originalTitle           Episode #1.193
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001739, dtype: object

(9,)

tconst                      tt11819156
titleType                    tvEpisode
primaryTitle            Episode #1.195
originalTitle           Episode #1.195
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001740, dtype: object

(9,)

tconst                      tt11819158
titleType                    tvEpisode
primaryTitle            Episode #1.196
originalTitle           Episode #1.196
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001741, dtype: object

(9,)

tconst                                  tt1181915
titleType                               tvEpisode
primaryTitle      Soba ni iruyone... aniki/Haruka
originalTitle     Soba ni iruyone... aniki/Haruka
isAdult                                         0
startYear                                    2002
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Animation
Name: 2001742, dtype: object

(9,)

tconst                                                   tt11819160
titleType                                                     video
primaryTitle      They Suffer to Bring You Joy: Shocking Truth A...
originalTitle     They Suffer to Bring You Joy: Shocking Truth A...
isAdult                                                           0
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                    2
genres                                            Documentary,Short
Name: 2001743, dtype: object

(9,)

tconst                      tt11819162
titleType                    tvEpisode
primaryTitle            Episode #1.197
originalTitle           Episode #1.197
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001744, dtype: object

(9,)

tconst                      tt11819164
titleType                    tvEpisode
primaryTitle            Episode #1.198
originalTitle           Episode #1.198
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001745, dtype: object

(9,)

tconst                    tt11819166
titleType                      short
primaryTitle      Wealth of a Nation
originalTitle     Wealth of a Nation
isAdult                            0
startYear                       1966
endYear                           \N
runtimeMinutes                    21
genres             Documentary,Short
Name: 2001746, dtype: object

(9,)

tconst                      tt11819168
titleType                    tvEpisode
primaryTitle            Episode #1.199
originalTitle           Episode #1.199
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001747, dtype: object

(9,)

tconst                          tt1181916
titleType                       tvEpisode
primaryTitle      Unmei no akai ito/Marie
originalTitle     Unmei no akai ito/Marie
isAdult                                 0
startYear                            2002
endYear                                \N
runtimeMinutes                         \N
genres                          Animation
Name: 2001748, dtype: object

(9,)

tconst                      tt11819170
titleType                    tvEpisode
primaryTitle            Episode #1.200
originalTitle           Episode #1.200
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2001749, dtype: object

(9,)

tconst                            tt11819174
titleType                              movie
primaryTitle      Rockefeller Vs. Tar Barrel
originalTitle     Rockefeller Vs. Tar Barrel
isAdult                                    0
startYear                                 \N
endYear                                   \N
runtimeMinutes                            \N
genres                               History
Name: 2001750, dtype: object

(9,)

tconst                tt11819176
titleType              tvEpisode
primaryTitle      Episode #1.221
originalTitle     Episode #1.221
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001751, dtype: object

(9,)

tconst                   tt11819178
titleType                     short
primaryTitle               Deylight
originalTitle              Deylight
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2001752, dtype: object

(9,)

tconst                          tt1181917
titleType                        tvSeries
primaryTitle       The Suite Life on Deck
originalTitle      The Suite Life on Deck
isAdult                                 0
startYear                            2008
endYear                              2011
runtimeMinutes                         30
genres            Action,Adventure,Comedy
Name: 2001753, dtype: object

(9,)

tconst                     tt11819180
titleType                   tvEpisode
primaryTitle       Punalipun kantajat
originalTitle      Punalipun kantajat
isAdult                             0
startYear                        2011
endYear                            \N
runtimeMinutes                     28
genres            Documentary,History
Name: 2001754, dtype: object

(9,)

tconst                                      tt11819182
titleType                                    tvEpisode
primaryTitle      Monte Carlo, Sweden, Mexico, Corsica
originalTitle     Monte Carlo, Sweden, Mexico, Corsica
isAdult                                              0
startYear                                         2017
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Sport
Name: 2001755, dtype: object

(9,)

tconst                                     tt11819184
titleType                                   tvEpisode
primaryTitle      Richard Dawkins Eugenics Livestream
originalTitle     Richard Dawkins Eugenics Livestream
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                           News
Name: 2001756, dtype: object

(9,)

tconst              tt11819186
titleType              tvMovie
primaryTitle      Onkel Jerome
originalTitle     Onkel Jerome
isAdult                      0
startYear                 1963
endYear                     \N
runtimeMinutes              22
genres                      \N
Name: 2001757, dtype: object

(9,)

tconst                              tt11819188
titleType                            tvEpisode
primaryTitle      Ya vsyo yeshchyo bezrabotnyy
originalTitle     Ya vsyo yeshchyo bezrabotnyy
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                  Comedy
Name: 2001758, dtype: object

(9,)

tconst                      tt11819190
titleType                    tvEpisode
primaryTitle                15 Minuten
originalTitle               15 Minuten
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Drama,Family,Romance
Name: 2001759, dtype: object

(9,)

tconst            tt11819192
titleType              movie
primaryTitle       #MonkLife
originalTitle      #MonkLife
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2001760, dtype: object

(9,)

tconst                         tt11819194
titleType                         tvMovie
primaryTitle      Journey Through History
originalTitle        Viaggio nella storia
isAdult                                 0
startYear                            1977
endYear                                \N
runtimeMinutes                         60
genres                        Documentary
Name: 2001761, dtype: object

(9,)

tconst                            tt11819196
titleType                          videoGame
primaryTitle      Strategic Mind: Blitzkrieg
originalTitle     Strategic Mind: Blitzkrieg
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                                   War
Name: 2001762, dtype: object

(9,)

tconst                                                   tt11819198
titleType                                                  tvSeries
primaryTitle      Torn from the Headlines: The New York Post Rep...
originalTitle     Torn from the Headlines: The New York Post Rep...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Crime
Name: 2001763, dtype: object

(9,)

tconst                                               tt1181919
titleType                                                movie
primaryTitle                   20th Century Boys 3: Redemption
originalTitle     20-seiki shônen: Saishû-shô - Bokura no hata
isAdult                                                      0
startYear                                                 2009
endYear                                                     \N
runtimeMinutes                                             156
genres                                       Adventure,Fantasy
Name: 2001764, dtype: object

(9,)

tconst                    tt11819200
titleType                      short
primaryTitle        Beneath the Skin
originalTitle       Beneath the Skin
isAdult                            0
startYear                       1981
endYear                           \N
runtimeMinutes                    12
genres            Crime,Drama,Horror
Name: 2001765, dtype: object

(9,)

tconst              tt11819202
titleType            tvEpisode
primaryTitle      Episode #6.9
originalTitle     Episode #6.9
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2001766, dtype: object

(9,)

tconst              tt11819204
titleType         tvMiniSeries
primaryTitle            Josiah
originalTitle           Josiah
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 History
Name: 2001767, dtype: object

(9,)

tconst                     tt11819206
titleType                   tvEpisode
primaryTitle           Chilen jälkeen
originalTitle          Chilen jälkeen
isAdult                             0
startYear                        2013
endYear                            \N
runtimeMinutes                     28
genres            Documentary,History
Name: 2001768, dtype: object

(9,)

tconst                                     tt11819208
titleType                                   tvEpisode
primaryTitle      Who Stole the Christmas Decorations
originalTitle     Who Stole the Christmas Decorations
isAdult                                             0
startYear                                        2019
endYear                                            \N
runtimeMinutes                                      9
genres                               Animation,Family
Name: 2001769, dtype: object

(9,)

tconst                                             tt1181920
titleType                                              movie
primaryTitle              20th Century Boys 2: The Last Hope
originalTitle     20-seiki shônen: Dai 2 shô - Saigo no kibô
isAdult                                                    0
startYear                                               2009
endYear                                                   \N
runtimeMinutes                                           139
genres                                         Drama,Fantasy
Name: 2001770, dtype: object

(9,)

tconst            tt11819210
titleType           tvSeries
primaryTitle       Your Show
originalTitle      Your Show
isAdult                    0
startYear               1954
endYear                 1954
runtimeMinutes            30
genres             Talk-Show
Name: 2001771, dtype: object

(9,)

tconst                                             tt11819212
titleType                                           tvEpisode
primaryTitle      Hossein Alizadeh's concert in Sweden-Part 1
originalTitle     Hossein Alizadeh's concert in Sweden-Part 1
isAdult                                                     0
startYear                                                2014
endYear                                                    \N
runtimeMinutes                                             \N
genres                                             Reality-TV
Name: 2001772, dtype: object

(9,)

tconst             tt11819214
titleType               short
primaryTitle            Reina
originalTitle           Reina
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2001773, dtype: object

(9,)

tconst                         tt11819216
titleType                           video
primaryTitle      Nising: Oh Snake, O Dog
originalTitle     Nising: Oh Snake, O Dog
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                          3
genres                        Music,Short
Name: 2001774, dtype: object

(9,)

tconst                                             tt11819218
titleType                                           tvEpisode
primaryTitle      Hossein Alizadeh's concert in Sweden-Part 2
originalTitle     Hossein Alizadeh's concert in Sweden-Part 2
isAdult                                                     0
startYear                                                2014
endYear                                                    \N
runtimeMinutes                                             \N
genres                                             Reality-TV
Name: 2001775, dtype: object

(9,)

tconst                  tt1181921
titleType                   short
primaryTitle      Beijing Holiday
originalTitle     Beijing Holiday
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 13
genres              Fantasy,Short
Name: 2001776, dtype: object

(9,)

tconst                tt11819222
titleType              tvEpisode
primaryTitle      Episode #1.222
originalTitle     Episode #1.222
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001777, dtype: object

(9,)

tconst                tt11819224
titleType              tvEpisode
primaryTitle      Episode #1.223
originalTitle     Episode #1.223
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001778, dtype: object

(9,)

tconst                tt11819226
titleType              tvEpisode
primaryTitle      Episode #1.224
originalTitle     Episode #1.224
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001779, dtype: object

(9,)

tconst                tt11819228
titleType              tvEpisode
primaryTitle      Episode #1.225
originalTitle     Episode #1.225
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001780, dtype: object

(9,)

tconst                          tt1181922
titleType                       tvSpecial
primaryTitle      Chrissy: Plain & Simple
originalTitle     Chrissy: Plain & Simple
isAdult                                 0
startYear                            2007
endYear                                \N
runtimeMinutes                         \N
genres                             Comedy
Name: 2001781, dtype: object

(9,)

tconst                tt11819230
titleType              tvEpisode
primaryTitle      Episode #1.226
originalTitle     Episode #1.226
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001782, dtype: object

(9,)

tconst                tt11819232
titleType              tvEpisode
primaryTitle      Episode #1.227
originalTitle     Episode #1.227
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001783, dtype: object

(9,)

tconst                tt11819236
titleType              tvEpisode
primaryTitle      Episode #1.228
originalTitle     Episode #1.228
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001784, dtype: object

(9,)

tconst                tt11819238
titleType              tvEpisode
primaryTitle      Episode #1.229
originalTitle     Episode #1.229
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001785, dtype: object

(9,)

tconst                    tt1181923
titleType                   tvMovie
primaryTitle      David Copperfield
originalTitle     David Copperfield
isAdult                           0
startYear                      1983
endYear                          \N
runtimeMinutes                   72
genres                    Animation
Name: 2001786, dtype: object

(9,)

tconst                tt11819240
titleType              tvEpisode
primaryTitle      Episode #1.231
originalTitle     Episode #1.231
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001787, dtype: object

(9,)

tconst                tt11819242
titleType              tvEpisode
primaryTitle      Episode #1.230
originalTitle     Episode #1.230
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001788, dtype: object

(9,)

tconst                tt11819244
titleType              tvEpisode
primaryTitle      Episode #1.232
originalTitle     Episode #1.232
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001789, dtype: object

(9,)

tconst                tt11819246
titleType              tvEpisode
primaryTitle      Episode #1.234
originalTitle     Episode #1.234
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001790, dtype: object

(9,)

tconst                tt11819248
titleType              tvEpisode
primaryTitle      Episode #1.233
originalTitle     Episode #1.233
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001791, dtype: object

(9,)

tconst                           tt1181924
titleType                         tvSeries
primaryTitle      Dix films pour en parler
originalTitle     Dix films pour en parler
isAdult                                  0
startYear                             2006
endYear                                 \N
runtimeMinutes                          \N
genres                               Short
Name: 2001792, dtype: object

(9,)

tconst                  tt11819252
titleType                    video
primaryTitle        Style Selected
originalTitle       Style Selected
isAdult                          0
startYear                     2018
endYear                         \N
runtimeMinutes                  \N
genres            Reality-TV,Short
Name: 2001793, dtype: object

(9,)

tconst            tt11819254
titleType          tvEpisode
primaryTitle       Radiation
originalTitle      Radiation
isAdult                    0
startYear               2012
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2001794, dtype: object

(9,)

tconst                                           tt11819256
titleType                                         tvEpisode
primaryTitle      Tiny Teen Cum Slut Sera Ryder Casting POV
originalTitle     Tiny Teen Cum Slut Sera Ryder Casting POV
isAdult                                                   1
startYear                                              2020
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Adult
Name: 2001795, dtype: object

(9,)

tconst                tt11819258
titleType              tvEpisode
primaryTitle      Episode #1.235
originalTitle     Episode #1.235
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001796, dtype: object

(9,)

tconst                                    tt1181925
titleType                                 tvSpecial
primaryTitle      The Donovan Concert: Live in L.A.
originalTitle     The Donovan Concert: Live in L.A.
isAdult                                           0
startYear                                      2007
endYear                                          \N
runtimeMinutes                                   78
genres                                        Music
Name: 2001797, dtype: object

(9,)

tconst                tt11819260
titleType              tvEpisode
primaryTitle      Episode #1.236
originalTitle     Episode #1.236
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001798, dtype: object

(9,)

tconst               tt11819262
titleType             tvEpisode
primaryTitle      Episode #1.51
originalTitle     Episode #1.51
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001799, dtype: object

(9,)

tconst               tt11819264
titleType             tvEpisode
primaryTitle      Episode #6.10
originalTitle     Episode #6.10
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001800, dtype: object

(9,)

tconst                     tt1181926
titleType                    tvMovie
primaryTitle      Great Expectations
originalTitle     Great Expectations
isAdult                            0
startYear                       1983
endYear                           \N
runtimeMinutes                    69
genres               Animation,Drama
Name: 2001801, dtype: object

(9,)

tconst                tt11819270
titleType              tvEpisode
primaryTitle      Episode #1.239
originalTitle     Episode #1.239
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001802, dtype: object

(9,)

tconst                tt11819272
titleType              tvEpisode
primaryTitle      Episode #1.240
originalTitle     Episode #1.240
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001803, dtype: object

(9,)

tconst                           tt11819274
titleType                         tvEpisode
primaryTitle      Carnavalskraker Challenge
originalTitle     Carnavalskraker Challenge
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2001804, dtype: object

(9,)

tconst                                               tt11819276
titleType                                             tvEpisode
primaryTitle      Lumps, Premature Ejaculation and a Dry Vagina
originalTitle     Lumps, Premature Ejaculation and a Dry Vagina
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               47
genres                                               Reality-TV
Name: 2001805, dtype: object

(9,)

tconst                tt11819278
titleType              tvEpisode
primaryTitle      Episode #1.241
originalTitle     Episode #1.241
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001806, dtype: object

(9,)

tconst                        tt1181927
titleType                         movie
primaryTitle               The Bone Man
originalTitle           Der Knochenmann
isAdult                               0
startYear                          2009
endYear                              \N
runtimeMinutes                      117
genres            Comedy,Crime,Thriller
Name: 2001807, dtype: object

(9,)

tconst                          tt11819280
titleType                          tvMovie
primaryTitle         On the Way to Dotsiko
originalTitle     Sulla strada per dotsiko
isAdult                                  0
startYear                             1980
endYear                                 \N
runtimeMinutes                          42
genres                         Documentary
Name: 2001808, dtype: object

(9,)

tconst               tt11819282
titleType             tvEpisode
primaryTitle      Episode #1.52
originalTitle     Episode #1.52
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001809, dtype: object

(9,)

tconst                tt11819284
titleType              tvEpisode
primaryTitle      Episode #1.242
originalTitle     Episode #1.242
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001810, dtype: object

(9,)

tconst                tt11819286
titleType              tvEpisode
primaryTitle      Episode #1.244
originalTitle     Episode #1.244
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001811, dtype: object

(9,)

tconst                tt11819288
titleType              tvEpisode
primaryTitle      Episode #1.243
originalTitle     Episode #1.243
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001812, dtype: object

(9,)

tconst               tt1181928
titleType                short
primaryTitle       Moviebonics
originalTitle      Moviebonics
isAdult                      0
startYear                 2006
endYear                     \N
runtimeMinutes               9
genres            Comedy,Short
Name: 2001813, dtype: object

(9,)

tconst                tt11819290
titleType              tvEpisode
primaryTitle      Episode #1.245
originalTitle     Episode #1.245
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001814, dtype: object

(9,)

tconst               tt11819292
titleType             tvEpisode
primaryTitle      Episode #1.53
originalTitle     Episode #1.53
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001815, dtype: object

(9,)

tconst                tt11819294
titleType              tvEpisode
primaryTitle      Episode #1.246
originalTitle     Episode #1.246
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001816, dtype: object

(9,)

tconst                tt11819296
titleType              tvEpisode
primaryTitle      Episode #1.247
originalTitle     Episode #1.247
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001817, dtype: object

(9,)

tconst                tt11819298
titleType               tvSeries
primaryTitle      Pavitra Bhagya
originalTitle     Pavitra Bhagya
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                22
genres                     Drama
Name: 2001818, dtype: object

(9,)

tconst            tt1181929
titleType             video
primaryTitle          Raven
originalTitle         Raven
isAdult                   1
startYear              2002
endYear                  \N
runtimeMinutes           \N
genres                Adult
Name: 2001819, dtype: object

(9,)

tconst                tt11819300
titleType              tvEpisode
primaryTitle      Episode #1.248
originalTitle     Episode #1.248
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001820, dtype: object

(9,)

tconst                                            tt11819302
titleType                                              video
primaryTitle      Look at My SEX! Please Bukkake Me A Lot! 2
originalTitle     Look at My SEX! Please Bukkake Me A Lot! 2
isAdult                                                    1
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            62
genres                                                 Adult
Name: 2001821, dtype: object

(9,)

tconst                tt11819304
titleType              tvEpisode
primaryTitle      Episode #1.249
originalTitle     Episode #1.249
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001822, dtype: object

(9,)

tconst                tt11819306
titleType              tvEpisode
primaryTitle      Episode #1.250
originalTitle     Episode #1.250
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001823, dtype: object

(9,)

tconst                tt11819308
titleType              tvEpisode
primaryTitle      Episode #1.251
originalTitle     Episode #1.251
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001824, dtype: object

(9,)

tconst                            tt1181930
titleType                           tvMovie
primaryTitle      S Club 7: Special Edition
originalTitle     S Club 7: Special Edition
isAdult                                   0
startYear                              2001
endYear                                  \N
runtimeMinutes                           \N
genres                               Comedy
Name: 2001825, dtype: object

(9,)

tconst                tt11819310
titleType              tvEpisode
primaryTitle      Episode #1.252
originalTitle     Episode #1.252
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001826, dtype: object

(9,)

tconst                tt11819312
titleType              tvEpisode
primaryTitle      Episode #1.253
originalTitle     Episode #1.253
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001827, dtype: object

(9,)

tconst                tt11819314
titleType              tvEpisode
primaryTitle      Episode #1.254
originalTitle     Episode #1.254
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001828, dtype: object

(9,)

tconst                tt11819316
titleType              tvEpisode
primaryTitle      Episode #1.255
originalTitle     Episode #1.255
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001829, dtype: object

(9,)

tconst                tt11819318
titleType              tvEpisode
primaryTitle      Episode #1.256
originalTitle     Episode #1.256
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001830, dtype: object

(9,)

tconst                                                    tt1181931
titleType                                                     movie
primaryTitle      Scenes from the Sex Struggles at North Beverly...
originalTitle     Scenes from the Sex Struggles at North Beverly...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   62
genres                                                Drama,Romance
Name: 2001831, dtype: object

(9,)

tconst                tt11819320
titleType              tvEpisode
primaryTitle      Episode #1.258
originalTitle     Episode #1.258
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001832, dtype: object

(9,)

tconst                tt11819322
titleType              tvEpisode
primaryTitle      Episode #1.259
originalTitle     Episode #1.259
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001833, dtype: object

(9,)

tconst                tt11819324
titleType              tvEpisode
primaryTitle      Episode #1.257
originalTitle     Episode #1.257
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001834, dtype: object

(9,)

tconst                tt11819326
titleType              tvEpisode
primaryTitle      Episode #1.260
originalTitle     Episode #1.260
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001835, dtype: object

(9,)

tconst               tt11819328
titleType             tvEpisode
primaryTitle      Episode #1.54
originalTitle     Episode #1.54
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001836, dtype: object

(9,)

tconst                   tt1181932
titleType                    video
primaryTitle      Shameless Desire
originalTitle     Shameless Desire
isAdult                          1
startYear                     1997
endYear                         \N
runtimeMinutes                 115
genres                       Adult
Name: 2001837, dtype: object

(9,)

tconst                                     tt11819330
titleType                                   tvEpisode
primaryTitle      O drobizu, paleontologih in ratraku
originalTitle     O drobizu, paleontologih in ratraku
isAdult                                             0
startYear                                        2014
endYear                                            \N
runtimeMinutes                                     \N
genres                                  Comedy,Family
Name: 2001838, dtype: object

(9,)

tconst               tt11819332
titleType             tvEpisode
primaryTitle      Take The Shot
originalTitle     Take The Shot
isAdult                       1
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2001839, dtype: object

(9,)

tconst               tt11819334
titleType             tvEpisode
primaryTitle      Episode #1.55
originalTitle     Episode #1.55
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001840, dtype: object

(9,)

tconst                                   tt11819336
titleType                                 tvEpisode
primaryTitle      Walking Children in Nature Part 1
originalTitle     Walking Children in Nature Part 1
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                             Comedy,Talk-Show
Name: 2001841, dtype: object

(9,)

tconst                tt11819338
titleType              tvEpisode
primaryTitle      Episode #1.501
originalTitle     Episode #1.501
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001842, dtype: object

(9,)

tconst                    tt1181933
titleType                     video
primaryTitle      Summer Encounters
originalTitle     Summer Encounters
isAdult                           1
startYear                      2007
endYear                          \N
runtimeMinutes                  153
genres                        Adult
Name: 2001843, dtype: object

(9,)

tconst                                    tt11819340
titleType                                  tvEpisode
primaryTitle      O mikrocipu, barvah in strojevodji
originalTitle     O mikrocipu, barvah in strojevodji
isAdult                                            0
startYear                                       2014
endYear                                           \N
runtimeMinutes                                    \N
genres                                 Comedy,Family
Name: 2001844, dtype: object

(9,)

tconst                tt11819342
titleType              tvEpisode
primaryTitle      Episode #1.502
originalTitle     Episode #1.502
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001845, dtype: object

(9,)

tconst               tt11819344
titleType             tvEpisode
primaryTitle      Episode #1.56
originalTitle     Episode #1.56
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001846, dtype: object

(9,)

tconst                       tt11819346
titleType                         video
primaryTitle      22-Pistepirkko: Birdy
originalTitle     22-Pistepirkko: Birdy
isAdult                               0
startYear                          1992
endYear                              \N
runtimeMinutes                        4
genres                      Music,Short
Name: 2001847, dtype: object

(9,)

tconst                                tt11819348
titleType                              tvEpisode
primaryTitle      Episode dated 22 November 2016
originalTitle     Episode dated 22 November 2016
isAdult                                        0
startYear                                   2016
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001848, dtype: object

(9,)

tconst                      tt1181934
titleType                       movie
primaryTitle      Speakerman: The Boo
originalTitle      Supîkâman: The Boo
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     77
genres                        Fantasy
Name: 2001849, dtype: object

(9,)

tconst                                tt11819350
titleType                              tvEpisode
primaryTitle      Episode dated 28 November 2016
originalTitle     Episode dated 28 November 2016
isAdult                                        0
startYear                                   2016
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001850, dtype: object

(9,)

tconst                                tt11819352
titleType                              tvEpisode
primaryTitle      Episode dated 20 December 2016
originalTitle     Episode dated 20 December 2016
isAdult                                        0
startYear                                   2016
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001851, dtype: object

(9,)

tconst                       tt11819354
titleType                     tvEpisode
primaryTitle                 Baba Olmak
originalTitle                Baba Olmak
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres            Action,Crime,Thriller
Name: 2001852, dtype: object

(9,)

tconst                                      tt11819356
titleType                                    tvEpisode
primaryTitle      O prezveceni romantiki in eko obleki
originalTitle     O prezveceni romantiki in eko obleki
isAdult                                              0
startYear                                         2014
endYear                                             \N
runtimeMinutes                                      \N
genres                                   Comedy,Family
Name: 2001853, dtype: object

(9,)

tconst                     tt11819358
titleType                   tvEpisode
primaryTitle           Episode #1.201
originalTitle          Episode #1.201
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001854, dtype: object

(9,)

tconst                            tt1181935
titleType                             video
primaryTitle      Varg Veum - Din til døden
originalTitle     Varg Veum - Din til døden
isAdult                                   0
startYear                              2008
endYear                                  \N
runtimeMinutes                           86
genres                 Crime,Drama,Thriller
Name: 2001855, dtype: object

(9,)

tconst                                tt11819360
titleType                              tvEpisode
primaryTitle      Episode dated 29 December 2016
originalTitle     Episode dated 29 December 2016
isAdult                                        0
startYear                                   2016
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2001856, dtype: object

(9,)

tconst                              tt11819362
titleType                            tvEpisode
primaryTitle      Episode dated 3 January 2017
originalTitle     Episode dated 3 January 2017
isAdult                                      0
startYear                                 2017
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2001857, dtype: object

(9,)

tconst                         tt11819364
titleType                       tvEpisode
primaryTitle      To telos mias trilogias
originalTitle     To telos mias trilogias
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                        Documentary
Name: 2001858, dtype: object

(9,)

tconst                     tt11819366
titleType                   tvEpisode
primaryTitle           Episode #1.202
originalTitle          Episode #1.202
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001859, dtype: object

(9,)

tconst                     tt11819368
titleType                   tvEpisode
primaryTitle           Episode #1.203
originalTitle          Episode #1.203
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001860, dtype: object

(9,)

tconst                        tt1181936
titleType                         video
primaryTitle      Varg Veum - Tornerose
originalTitle     Varg Veum - Tornerose
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       90
genres                   Crime,Thriller
Name: 2001861, dtype: object

(9,)

tconst                     tt11819370
titleType                   tvEpisode
primaryTitle           Episode #1.205
originalTitle          Episode #1.205
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001862, dtype: object

(9,)

tconst                     tt11819372
titleType                   tvEpisode
primaryTitle           Episode #1.204
originalTitle          Episode #1.204
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001863, dtype: object

(9,)

tconst               tt11819374
titleType             tvEpisode
primaryTitle      Episode #2.24
originalTitle     Episode #2.24
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Comedy,Family
Name: 2001864, dtype: object

(9,)

tconst                     tt11819376
titleType                   tvEpisode
primaryTitle           Episode #1.206
originalTitle          Episode #1.206
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001865, dtype: object

(9,)

tconst                     tt11819378
titleType                   tvEpisode
primaryTitle           Episode #1.207
originalTitle          Episode #1.207
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001866, dtype: object

(9,)

tconst                                                  tt1181937
titleType                                                   video
primaryTitle      Shûji Terayama & Shuntarô Tanikawa Video Letter
originalTitle     Video Letter Shuji Terayama & Shuntaro Tanikawa
isAdult                                                         0
startYear                                                    1983
endYear                                                        \N
runtimeMinutes                                                 74
genres                              Biography,Documentary,Fantasy
Name: 2001867, dtype: object

(9,)

tconst                     tt11819380
titleType                   tvEpisode
primaryTitle           Episode #1.208
originalTitle          Episode #1.208
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001868, dtype: object

(9,)

tconst                     tt11819382
titleType                   tvEpisode
primaryTitle           Episode #1.209
originalTitle          Episode #1.209
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001869, dtype: object

(9,)

tconst                     tt11819386
titleType                   tvEpisode
primaryTitle           Episode #1.210
originalTitle          Episode #1.210
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001870, dtype: object

(9,)

tconst                     tt11819388
titleType                   tvEpisode
primaryTitle           Episode #1.211
originalTitle          Episode #1.211
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001871, dtype: object

(9,)

tconst                                tt1181938
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2008
originalTitle     Episode dated 4 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2001872, dtype: object

(9,)

tconst                     tt11819390
titleType                   tvEpisode
primaryTitle           Episode #1.212
originalTitle          Episode #1.212
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001873, dtype: object

(9,)

tconst                     tt11819392
titleType                   tvEpisode
primaryTitle           Episode #1.214
originalTitle          Episode #1.214
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001874, dtype: object

(9,)

tconst                     tt11819394
titleType                   tvEpisode
primaryTitle           Episode #1.213
originalTitle          Episode #1.213
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001875, dtype: object

(9,)

tconst                     tt11819396
titleType                   tvEpisode
primaryTitle           Episode #1.216
originalTitle          Episode #1.216
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001876, dtype: object

(9,)

tconst                     tt11819398
titleType                   tvEpisode
primaryTitle           Episode #1.215
originalTitle          Episode #1.215
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001877, dtype: object

(9,)

tconst                tt1181939
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001878, dtype: object

(9,)

tconst                     tt11819400
titleType                   tvEpisode
primaryTitle           Episode #1.217
originalTitle          Episode #1.217
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001879, dtype: object

(9,)

tconst                     tt11819402
titleType                   tvEpisode
primaryTitle           Episode #1.218
originalTitle          Episode #1.218
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001880, dtype: object

(9,)

tconst                     tt11819404
titleType                   tvEpisode
primaryTitle           Episode #1.219
originalTitle          Episode #1.219
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001881, dtype: object

(9,)

tconst               tt11819406
titleType             tvEpisode
primaryTitle      Episode #1.57
originalTitle     Episode #1.57
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001882, dtype: object

(9,)

tconst                     tt11819408
titleType                   tvEpisode
primaryTitle           Episode #1.220
originalTitle          Episode #1.220
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001883, dtype: object

(9,)

tconst                     tt11819410
titleType                   tvEpisode
primaryTitle           Episode #1.441
originalTitle          Episode #1.441
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001884, dtype: object

(9,)

tconst                     tt11819412
titleType                   tvEpisode
primaryTitle           Episode #1.442
originalTitle          Episode #1.442
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001885, dtype: object

(9,)

tconst                     tt11819414
titleType                   tvEpisode
primaryTitle           Episode #1.443
originalTitle          Episode #1.443
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001886, dtype: object

(9,)

tconst                     tt11819416
titleType                   tvEpisode
primaryTitle           Episode #1.444
originalTitle          Episode #1.444
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001887, dtype: object

(9,)

tconst                     tt11819418
titleType                   tvEpisode
primaryTitle           Episode #1.445
originalTitle          Episode #1.445
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001888, dtype: object

(9,)

tconst                          tt1181941
titleType                       tvEpisode
primaryTitle         Action League Rocks!
originalTitle        Action League Rocks!
isAdult                                 0
startYear                            2001
endYear                                \N
runtimeMinutes                         \N
genres            Animation,Comedy,Family
Name: 2001889, dtype: object

(9,)

tconst                                     tt11819422
titleType                                       video
primaryTitle      Things That Died That Won't Go Away
originalTitle     Things That Died That Won't Go Away
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                      1
genres                              Documentary,Short
Name: 2001890, dtype: object

(9,)

tconst                   tt11819424
titleType                     short
primaryTitle       Something to Say
originalTitle      Something to Say
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   32
genres            Documentary,Short
Name: 2001891, dtype: object

(9,)

tconst                   tt11819426
titleType                 tvEpisode
primaryTitle          Episode #3.12
originalTitle         Episode #3.12
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Fantasy
Name: 2001892, dtype: object

(9,)

tconst                     tt11819428
titleType                   tvEpisode
primaryTitle           Episode #1.446
originalTitle          Episode #1.446
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001893, dtype: object

(9,)

tconst                                tt1181942
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2001894, dtype: object

(9,)

tconst                     tt11819430
titleType                   tvEpisode
primaryTitle           Episode #1.447
originalTitle          Episode #1.447
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001895, dtype: object

(9,)

tconst                                     tt11819432
titleType                                   tvEpisode
primaryTitle      O urjenju, jamah in lovljenju vetra
originalTitle     O urjenju, jamah in lovljenju vetra
isAdult                                             0
startYear                                        2014
endYear                                            \N
runtimeMinutes                                     \N
genres                                  Comedy,Family
Name: 2001896, dtype: object

(9,)

tconst                     tt11819434
titleType                   tvEpisode
primaryTitle           Episode #1.449
originalTitle          Episode #1.449
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001897, dtype: object

(9,)

tconst                     tt11819436
titleType                   tvEpisode
primaryTitle           Episode #1.448
originalTitle          Episode #1.448
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001898, dtype: object

(9,)

tconst                     tt11819438
titleType                   tvEpisode
primaryTitle           Episode #1.450
originalTitle          Episode #1.450
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001899, dtype: object

(9,)

tconst                        tt1181943
titleType                     tvEpisode
primaryTitle            Episode #1.3004
originalTitle           Episode #1.3004
isAdult                               0
startYear                          1981
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2001900, dtype: object

(9,)

tconst            tt11819440
titleType          tvEpisode
primaryTitle       56. Bolum
originalTitle      56. Bolum
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2001901, dtype: object

(9,)

tconst                     tt11819442
titleType                   tvEpisode
primaryTitle           Episode #1.451
originalTitle          Episode #1.451
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001902, dtype: object

(9,)

tconst                     tt11819444
titleType                   tvEpisode
primaryTitle           Episode #1.452
originalTitle          Episode #1.452
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001903, dtype: object

(9,)

tconst               tt11819448
titleType             tvEpisode
primaryTitle      Episode #1.58
originalTitle     Episode #1.58
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001904, dtype: object

(9,)

tconst                        tt1181944
titleType                     tvEpisode
primaryTitle            Episode #1.3005
originalTitle           Episode #1.3005
isAdult                               0
startYear                          1981
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2001905, dtype: object

(9,)

tconst                     tt11819450
titleType                   tvEpisode
primaryTitle           Episode #1.453
originalTitle          Episode #1.453
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001906, dtype: object

(9,)

tconst                tt11819452
titleType                  movie
primaryTitle      The Over/Under
originalTitle     The Over/Under
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2001907, dtype: object

(9,)

tconst                     tt11819454
titleType                   tvEpisode
primaryTitle           Episode #1.454
originalTitle          Episode #1.454
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001908, dtype: object

(9,)

tconst                     tt11819456
titleType                   tvEpisode
primaryTitle           Episode #1.455
originalTitle          Episode #1.455
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001909, dtype: object

(9,)

tconst                     tt11819458
titleType                   tvEpisode
primaryTitle           Episode #1.456
originalTitle          Episode #1.456
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001910, dtype: object

(9,)

tconst                        tt1181945
titleType                     tvEpisode
primaryTitle            Episode #1.3006
originalTitle           Episode #1.3006
isAdult                               0
startYear                          1981
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2001911, dtype: object

(9,)

tconst                     tt11819460
titleType                   tvEpisode
primaryTitle           Episode #1.458
originalTitle          Episode #1.458
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001912, dtype: object

(9,)

tconst                     tt11819462
titleType                   tvEpisode
primaryTitle           Episode #1.457
originalTitle          Episode #1.457
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001913, dtype: object

(9,)

tconst                     tt11819464
titleType                   tvEpisode
primaryTitle           Episode #1.459
originalTitle          Episode #1.459
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001914, dtype: object

(9,)

tconst                                                   tt11819466
titleType                                                 tvEpisode
primaryTitle      Masked Looters Vs Nicole Black Balls Deep Anal...
originalTitle     Masked Looters Vs Nicole Black Balls Deep Anal...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2001915, dtype: object

(9,)

tconst                     tt11819468
titleType                   tvEpisode
primaryTitle           Episode #1.460
originalTitle          Episode #1.460
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001916, dtype: object

(9,)

tconst                        tt1181946
titleType                     tvEpisode
primaryTitle            Episode #1.3009
originalTitle           Episode #1.3009
isAdult                               0
startYear                          1981
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2001917, dtype: object

(9,)

tconst               tt11819470
titleType             tvEpisode
primaryTitle      Episode #1.59
originalTitle     Episode #1.59
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001918, dtype: object

(9,)

tconst             tt11819472
titleType           tvEpisode
primaryTitle           Türkei
originalTitle          Türkei
isAdult                     0
startYear                2012
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2001919, dtype: object

(9,)

tconst                     tt11819474
titleType                   tvEpisode
primaryTitle           Episode #1.701
originalTitle          Episode #1.701
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001920, dtype: object

(9,)

tconst                     tt11819476
titleType                   tvEpisode
primaryTitle           Episode #1.702
originalTitle          Episode #1.702
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001921, dtype: object

(9,)

tconst             tt11819478
titleType           tvEpisode
primaryTitle          Libanon
originalTitle         Libanon
isAdult                     0
startYear                2012
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2001922, dtype: object

(9,)

tconst                        tt1181947
titleType                     tvEpisode
primaryTitle            Episode #1.3010
originalTitle           Episode #1.3010
isAdult                               0
startYear                          1981
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2001923, dtype: object

(9,)

tconst                     tt11819480
titleType                   tvEpisode
primaryTitle           Episode #1.703
originalTitle          Episode #1.703
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001924, dtype: object

(9,)

tconst                     tt11819482
titleType                   tvEpisode
primaryTitle           Episode #1.704
originalTitle          Episode #1.704
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001925, dtype: object

(9,)

tconst             tt11819484
titleType           tvEpisode
primaryTitle           Israel
originalTitle          Israel
isAdult                     0
startYear                2012
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2001926, dtype: object

(9,)

tconst                     tt11819486
titleType                   tvEpisode
primaryTitle           Episode #1.705
originalTitle          Episode #1.705
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001927, dtype: object

(9,)

tconst                     tt11819488
titleType                   tvEpisode
primaryTitle           Episode #1.706
originalTitle          Episode #1.706
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001928, dtype: object

(9,)

tconst                        tt1181948
titleType                     tvEpisode
primaryTitle            Episode #1.9778
originalTitle           Episode #1.9778
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2001929, dtype: object

(9,)

tconst                     tt11819490
titleType                   tvEpisode
primaryTitle           Episode #1.707
originalTitle          Episode #1.707
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001930, dtype: object

(9,)

tconst                     tt11819492
titleType                   tvEpisode
primaryTitle           Episode #1.708
originalTitle          Episode #1.708
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001931, dtype: object

(9,)

tconst                     tt11819494
titleType                   tvEpisode
primaryTitle           Episode #1.709
originalTitle          Episode #1.709
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001932, dtype: object

(9,)

tconst                     tt11819496
titleType                   tvEpisode
primaryTitle           Episode #1.710
originalTitle          Episode #1.710
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001933, dtype: object

(9,)

tconst                     tt11819498
titleType                   tvEpisode
primaryTitle           Episode #1.711
originalTitle          Episode #1.711
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001934, dtype: object

(9,)

tconst                        tt1181949
titleType                     tvEpisode
primaryTitle            Episode #1.9820
originalTitle           Episode #1.9820
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2001935, dtype: object

(9,)

tconst               tt11819500
titleType             tvEpisode
primaryTitle      Episode #1.60
originalTitle     Episode #1.60
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001936, dtype: object

(9,)

tconst                     tt11819502
titleType                   tvEpisode
primaryTitle           Episode #1.712
originalTitle          Episode #1.712
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001937, dtype: object

(9,)

tconst                     tt11819504
titleType                   tvEpisode
primaryTitle           Episode #1.713
originalTitle          Episode #1.713
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001938, dtype: object

(9,)

tconst                     tt11819506
titleType                   tvEpisode
primaryTitle           Episode #1.714
originalTitle          Episode #1.714
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001939, dtype: object

(9,)

tconst                     tt11819508
titleType                   tvEpisode
primaryTitle           Episode #1.716
originalTitle          Episode #1.716
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001940, dtype: object

(9,)

tconst                      tt1181950
titleType                   tvEpisode
primaryTitle      Lichfield Cathedral
originalTitle     Lichfield Cathedral
isAdult                             0
startYear                        2005
endYear                            \N
runtimeMinutes                     \N
genres                     Reality-TV
Name: 2001941, dtype: object

(9,)

tconst                     tt11819510
titleType                   tvEpisode
primaryTitle           Episode #1.715
originalTitle          Episode #1.715
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001942, dtype: object

(9,)

tconst                     tt11819512
titleType                   tvEpisode
primaryTitle           Episode #1.717
originalTitle          Episode #1.717
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001943, dtype: object

(9,)

tconst                     tt11819514
titleType                   tvEpisode
primaryTitle           Episode #1.718
originalTitle          Episode #1.718
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001944, dtype: object

(9,)

tconst                     tt11819516
titleType                   tvEpisode
primaryTitle           Episode #1.719
originalTitle          Episode #1.719
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001945, dtype: object

(9,)

tconst                                     tt11819518
titleType                                   tvEpisode
primaryTitle      O pesnikih, arheologih in rokenrolu
originalTitle     O pesnikih, arheologih in rokenrolu
isAdult                                             0
startYear                                        2014
endYear                                            \N
runtimeMinutes                                     \N
genres                                  Comedy,Family
Name: 2001946, dtype: object

(9,)

tconst                            tt1181951
titleType                         tvEpisode
primaryTitle      A Night in with the Girls
originalTitle     A Night in with the Girls
isAdult                                   0
startYear                              1997
endYear                                  \N
runtimeMinutes                           \N
genres                          Documentary
Name: 2001947, dtype: object

(9,)

tconst                     tt11819520
titleType                   tvEpisode
primaryTitle           Episode #1.720
originalTitle          Episode #1.720
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001948, dtype: object

(9,)

tconst                     tt11819522
titleType                   tvEpisode
primaryTitle           Episode #1.941
originalTitle          Episode #1.941
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001949, dtype: object

(9,)

tconst                     tt11819524
titleType                   tvEpisode
primaryTitle           Episode #1.942
originalTitle          Episode #1.942
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001950, dtype: object

(9,)

tconst                     tt11819526
titleType                   tvEpisode
primaryTitle           Episode #1.943
originalTitle          Episode #1.943
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001951, dtype: object

(9,)

tconst               tt11819528
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001952, dtype: object

(9,)

tconst                tt1181952
titleType             tvEpisode
primaryTitle      Episode #13.9
originalTitle     Episode #13.9
isAdult                       0
startYear                  1980
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2001953, dtype: object

(9,)

tconst                     tt11819530
titleType                   tvEpisode
primaryTitle           Episode #1.945
originalTitle          Episode #1.945
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001954, dtype: object

(9,)

tconst                     tt11819532
titleType                   tvEpisode
primaryTitle           Episode #1.944
originalTitle          Episode #1.944
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001955, dtype: object

(9,)

tconst                     tt11819534
titleType                   tvEpisode
primaryTitle           Episode #1.946
originalTitle          Episode #1.946
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001956, dtype: object

(9,)

tconst                     tt11819536
titleType                   tvEpisode
primaryTitle           Episode #1.947
originalTitle          Episode #1.947
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001957, dtype: object

(9,)

tconst                     tt11819538
titleType                   tvEpisode
primaryTitle           Episode #1.948
originalTitle          Episode #1.948
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001958, dtype: object

(9,)

tconst                                tt1181953
titleType                             tvEpisode
primaryTitle      Episode dated 23 October 2007
originalTitle     Episode dated 23 October 2007
isAdult                                       0
startYear                                  2007
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2001959, dtype: object

(9,)

tconst                     tt11819540
titleType                   tvEpisode
primaryTitle           Episode #1.950
originalTitle          Episode #1.950
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001960, dtype: object

(9,)

tconst                     tt11819542
titleType                   tvEpisode
primaryTitle           Episode #1.949
originalTitle          Episode #1.949
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001961, dtype: object

(9,)

tconst                        tt11819544
titleType                      tvEpisode
primaryTitle           Wasser und Hiphop
originalTitle          Wasser und Hiphop
isAdult                                0
startYear                           2013
endYear                               \N
runtimeMinutes                        60
genres            Documentary,Reality-TV
Name: 2001962, dtype: object

(9,)

tconst                     tt11819546
titleType                   tvEpisode
primaryTitle           Episode #1.951
originalTitle          Episode #1.951
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001963, dtype: object

(9,)

tconst                     tt11819548
titleType                   tvEpisode
primaryTitle           Episode #1.952
originalTitle          Episode #1.952
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001964, dtype: object

(9,)

tconst               tt1181954
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 1983
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2001965, dtype: object

(9,)

tconst                     tt11819550
titleType                   tvEpisode
primaryTitle           Episode #1.953
originalTitle          Episode #1.953
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001966, dtype: object

(9,)

tconst                     tt11819552
titleType                   tvEpisode
primaryTitle           Episode #1.954
originalTitle          Episode #1.954
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001967, dtype: object

(9,)

tconst                     tt11819554
titleType                   tvEpisode
primaryTitle           Episode #1.955
originalTitle          Episode #1.955
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001968, dtype: object

(9,)

tconst                        tt11819556
titleType                      tvEpisode
primaryTitle        Freestyle in Kampala
originalTitle       Freestyle in Kampala
isAdult                                0
startYear                           2013
endYear                               \N
runtimeMinutes                        60
genres            Documentary,Reality-TV
Name: 2001969, dtype: object

(9,)

tconst                     tt11819558
titleType                   tvEpisode
primaryTitle           Episode #1.956
originalTitle          Episode #1.956
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001970, dtype: object

(9,)

tconst               tt1181955
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 1984
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2001971, dtype: object

(9,)

tconst                     tt11819560
titleType                   tvEpisode
primaryTitle           Episode #1.957
originalTitle          Episode #1.957
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001972, dtype: object

(9,)

tconst                     tt11819562
titleType                   tvEpisode
primaryTitle           Episode #1.958
originalTitle          Episode #1.958
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001973, dtype: object

(9,)

tconst                     tt11819564
titleType                   tvEpisode
primaryTitle           Episode #1.959
originalTitle          Episode #1.959
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001974, dtype: object

(9,)

tconst                     tt11819566
titleType                   tvEpisode
primaryTitle           Episode #1.960
originalTitle          Episode #1.960
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001975, dtype: object

(9,)

tconst               tt11819568
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001976, dtype: object

(9,)

tconst                    tt1181956
titleType                 tvEpisode
primaryTitle      Pernille er rejst
originalTitle     Pernille er rejst
isAdult                           0
startYear                      1985
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2001977, dtype: object

(9,)

tconst                     tt11819570
titleType                   tvEpisode
primaryTitle          Episode #1.1141
originalTitle         Episode #1.1141
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001978, dtype: object

(9,)

tconst                     tt11819572
titleType                   tvEpisode
primaryTitle          Episode #1.1142
originalTitle         Episode #1.1142
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001979, dtype: object

(9,)

tconst                     tt11819574
titleType                   tvEpisode
primaryTitle          Episode #1.1143
originalTitle         Episode #1.1143
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001980, dtype: object

(9,)

tconst                     tt11819576
titleType                   tvEpisode
primaryTitle          Episode #1.1144
originalTitle         Episode #1.1144
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001981, dtype: object

(9,)

tconst                                 tt1181957
titleType                              tvEpisode
primaryTitle      Man skal passe på de vilde dyr
originalTitle     Man skal passe på de vilde dyr
isAdult                                        0
startYear                                   1988
endYear                                       \N
runtimeMinutes                                \N
genres                                    Family
Name: 2001982, dtype: object

(9,)

tconst                     tt11819580
titleType                   tvEpisode
primaryTitle          Episode #1.1145
originalTitle         Episode #1.1145
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001983, dtype: object

(9,)

tconst                     tt11819582
titleType                   tvEpisode
primaryTitle          Episode #1.1146
originalTitle         Episode #1.1146
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001984, dtype: object

(9,)

tconst                     tt11819584
titleType                   tvEpisode
primaryTitle          Episode #1.1147
originalTitle         Episode #1.1147
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001985, dtype: object

(9,)

tconst                     tt11819586
titleType                   tvEpisode
primaryTitle          Episode #1.1148
originalTitle         Episode #1.1148
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001986, dtype: object

(9,)

tconst                     tt11819588
titleType                   tvEpisode
primaryTitle          Episode #1.1149
originalTitle         Episode #1.1149
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001987, dtype: object

(9,)

tconst                           tt1181958
titleType                        tvEpisode
primaryTitle      Måske er det en lille én
originalTitle     Måske er det en lille én
isAdult                                  0
startYear                             1988
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2001988, dtype: object

(9,)

tconst                     tt11819590
titleType                   tvEpisode
primaryTitle          Episode #1.1150
originalTitle         Episode #1.1150
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001989, dtype: object

(9,)

tconst                     tt11819592
titleType                   tvEpisode
primaryTitle          Episode #1.1151
originalTitle         Episode #1.1151
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001990, dtype: object

(9,)

tconst                     tt11819594
titleType                   tvEpisode
primaryTitle          Episode #1.1152
originalTitle         Episode #1.1152
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001991, dtype: object

(9,)

tconst                     tt11819596
titleType                   tvEpisode
primaryTitle          Episode #1.1153
originalTitle         Episode #1.1153
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001992, dtype: object

(9,)

tconst                                                   tt11819598
titleType                                                 tvEpisode
primaryTitle      WWE Superstars: Ali, Apollo Crews, Naomi, Natalya
originalTitle     WWE Superstars: Ali, Apollo Crews, Naomi, Natalya
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                         Game-Show,Reality-TV
Name: 2001993, dtype: object

(9,)

tconst            tt1181959
titleType         tvEpisode
primaryTitle      Spøgelser
originalTitle     Spøgelser
isAdult                   0
startYear              1988
endYear                  \N
runtimeMinutes           \N
genres               Family
Name: 2001994, dtype: object

(9,)

tconst                                                  tt11819600
titleType                                                tvEpisode
primaryTitle      O klekljih, anoreksiji in elektricnih drazljajih
originalTitle     O klekljih, anoreksiji in elektricnih drazljajih
isAdult                                                          0
startYear                                                     2014
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                               Comedy,Family
Name: 2001995, dtype: object

(9,)

tconst                     tt11819602
titleType                   tvEpisode
primaryTitle          Episode #1.1155
originalTitle         Episode #1.1155
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001996, dtype: object

(9,)

tconst                     tt11819604
titleType                   tvEpisode
primaryTitle          Episode #1.1154
originalTitle         Episode #1.1154
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001997, dtype: object

(9,)

tconst               tt11819606
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2001998, dtype: object

(9,)

tconst                     tt11819608
titleType                   tvEpisode
primaryTitle          Episode #1.1156
originalTitle         Episode #1.1156
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2001999, dtype: object

(9,)

tconst                         tt1181960
titleType                      tvEpisode
primaryTitle      Bamse bliver inviteret
originalTitle     Bamse bliver inviteret
isAdult                                0
startYear                           1986
endYear                               \N
runtimeMinutes                        \N
genres                            Family
Name: 2002000, dtype: object

(9,)

tconst                     tt11819610
titleType                   tvEpisode
primaryTitle          Episode #1.1157
originalTitle         Episode #1.1157
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002001, dtype: object

(9,)

tconst                                               tt11819612
titleType                                             tvEpisode
primaryTitle      Dana Wolf And Jackie Rogen Get Each Other Wet
originalTitle     Dana Wolf And Jackie Rogen Get Each Other Wet
isAdult                                                       1
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                    Adult
Name: 2002002, dtype: object

(9,)

tconst                     tt11819614
titleType                   tvEpisode
primaryTitle          Episode #1.1158
originalTitle         Episode #1.1158
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002003, dtype: object

(9,)

tconst                     tt11819616
titleType                   tvEpisode
primaryTitle          Episode #1.1159
originalTitle         Episode #1.1159
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002004, dtype: object

(9,)

tconst                     tt11819618
titleType                   tvEpisode
primaryTitle          Episode #1.1160
originalTitle         Episode #1.1160
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002005, dtype: object

(9,)

tconst                       tt1181961
titleType                    tvEpisode
primaryTitle      Bamse får røde hunde
originalTitle     Bamse får røde hunde
isAdult                              0
startYear                         1988
endYear                             \N
runtimeMinutes                      \N
genres                          Family
Name: 2002006, dtype: object

(9,)

tconst               tt11819620
titleType              tvSeries
primaryTitle      House Sitting
originalTitle     House Sitting
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002007, dtype: object

(9,)

tconst               tt11819622
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002008, dtype: object

(9,)

tconst                                                   tt11819624
titleType                                                 tvEpisode
primaryTitle      O sajmirijih, vojaski ladji in eksoticnih sadezih
originalTitle     O sajmirijih, vojaski ladji in eksoticnih sadezih
isAdult                                                           0
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2002009, dtype: object

(9,)

tconst                      tt11819626
titleType                     tvSeries
primaryTitle      Sommelier's Notebook
originalTitle     Sommelier's Notebook
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2002010, dtype: object

(9,)

tconst                                   tt11819628
titleType                                 tvEpisode
primaryTitle      Paisley Bennett Gets Wild Fucking
originalTitle     Paisley Bennett Gets Wild Fucking
isAdult                                           1
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2002011, dtype: object

(9,)

tconst                      tt1181962
titleType                   tvEpisode
primaryTitle      Bamse har en fløjte
originalTitle     Bamse har en fløjte
isAdult                             0
startYear                        1987
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2002012, dtype: object

(9,)

tconst                                   tt11819630
titleType                                 tvEpisode
primaryTitle      Trump Pardons Countless Criminals
originalTitle     Trump Pardons Countless Criminals
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                    Talk-Show
Name: 2002013, dtype: object

(9,)

tconst                     tt11819632
titleType                   tvEpisode
primaryTitle          Episode #1.1401
originalTitle         Episode #1.1401
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002014, dtype: object

(9,)

tconst                tt11819634
titleType                  movie
primaryTitle               Jalil
originalTitle              Jalil
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes               115
genres            Drama,Thriller
Name: 2002015, dtype: object

(9,)

tconst                     tt11819636
titleType                   tvEpisode
primaryTitle          Episode #1.1402
originalTitle         Episode #1.1402
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002016, dtype: object

(9,)

tconst                     tt11819638
titleType                   tvEpisode
primaryTitle          Episode #1.1403
originalTitle         Episode #1.1403
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002017, dtype: object

(9,)

tconst                                                    tt1181963
titleType                                                 tvEpisode
primaryTitle      Bamse har gjort Kylling lille, så han må gøre ...
originalTitle     Bamse har gjort Kylling lille, så han må gøre ...
isAdult                                                           0
startYear                                                      1988
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Family
Name: 2002018, dtype: object

(9,)

tconst                     tt11819640
titleType                   tvEpisode
primaryTitle          Episode #1.1404
originalTitle         Episode #1.1404
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002019, dtype: object

(9,)

tconst                     tt11819642
titleType                   tvEpisode
primaryTitle          Episode #1.1405
originalTitle         Episode #1.1405
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002020, dtype: object

(9,)

tconst                                              tt11819644
titleType                                            tvEpisode
primaryTitle      Not So Innocent Hottie Liv Wild Fucking LIVE
originalTitle     Not So Innocent Hottie Liv Wild Fucking LIVE
isAdult                                                      1
startYear                                                 2020
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                   Adult
Name: 2002021, dtype: object

(9,)

tconst                     tt11819646
titleType                   tvEpisode
primaryTitle          Episode #1.1406
originalTitle         Episode #1.1406
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002022, dtype: object

(9,)

tconst                     tt11819648
titleType                   tvEpisode
primaryTitle          Episode #1.1407
originalTitle         Episode #1.1407
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002023, dtype: object

(9,)

tconst                                  tt1181964
titleType                               tvEpisode
primaryTitle      Det var mig, der så hende først
originalTitle     Det var mig, der så hende først
isAdult                                         0
startYear                                    1986
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Family
Name: 2002024, dtype: object

(9,)

tconst                     tt11819650
titleType                   tvEpisode
primaryTitle          Episode #1.1408
originalTitle         Episode #1.1408
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002025, dtype: object

(9,)

tconst                     tt11819652
titleType                   tvEpisode
primaryTitle          Episode #1.1409
originalTitle         Episode #1.1409
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002026, dtype: object

(9,)

tconst                     tt11819654
titleType                   tvEpisode
primaryTitle          Episode #1.1410
originalTitle         Episode #1.1410
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002027, dtype: object

(9,)

tconst                     tt11819656
titleType                   tvEpisode
primaryTitle          Episode #1.1411
originalTitle         Episode #1.1411
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002028, dtype: object

(9,)

tconst                     tt11819658
titleType                   tvEpisode
primaryTitle          Episode #1.1413
originalTitle         Episode #1.1413
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002029, dtype: object

(9,)

tconst                               tt1181965
titleType                            tvEpisode
primaryTitle      En lille kylling med kyse på
originalTitle     En lille kylling med kyse på
isAdult                                      0
startYear                                 1988
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2002030, dtype: object

(9,)

tconst                     tt11819660
titleType                   tvEpisode
primaryTitle          Episode #1.1412
originalTitle         Episode #1.1412
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002031, dtype: object

(9,)

tconst                     tt11819662
titleType                   tvEpisode
primaryTitle          Episode #1.1415
originalTitle         Episode #1.1415
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002032, dtype: object

(9,)

tconst                     tt11819664
titleType                   tvEpisode
primaryTitle          Episode #1.1414
originalTitle         Episode #1.1414
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002033, dtype: object

(9,)

tconst               tt11819666
titleType             tvEpisode
primaryTitle      Episode #4.23
originalTitle     Episode #4.23
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres              Comedy,News
Name: 2002034, dtype: object

(9,)

tconst                     tt11819668
titleType                   tvEpisode
primaryTitle          Episode #1.1416
originalTitle         Episode #1.1416
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002035, dtype: object

(9,)

tconst              tt1181966
titleType           tvEpisode
primaryTitle      Farvel Luna
originalTitle     Farvel Luna
isAdult                     0
startYear                1986
endYear                    \N
runtimeMinutes             \N
genres                 Family
Name: 2002036, dtype: object

(9,)

tconst                     tt11819670
titleType                   tvEpisode
primaryTitle          Episode #1.1417
originalTitle         Episode #1.1417
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002037, dtype: object

(9,)

tconst                     tt11819672
titleType                   tvEpisode
primaryTitle          Episode #1.1418
originalTitle         Episode #1.1418
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002038, dtype: object

(9,)

tconst                     tt11819674
titleType                   tvEpisode
primaryTitle          Episode #1.1419
originalTitle         Episode #1.1419
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002039, dtype: object

(9,)

tconst                     tt11819676
titleType                   tvEpisode
primaryTitle          Episode #1.1420
originalTitle         Episode #1.1420
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002040, dtype: object

(9,)

tconst                     tt11819678
titleType                   tvEpisode
primaryTitle          Episode #1.1661
originalTitle         Episode #1.1661
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002041, dtype: object

(9,)

tconst              tt1181967
titleType           tvEpisode
primaryTitle      Goddag igen
originalTitle     Goddag igen
isAdult                     0
startYear                1986
endYear                    \N
runtimeMinutes             \N
genres                 Family
Name: 2002042, dtype: object

(9,)

tconst                     tt11819680
titleType                   tvEpisode
primaryTitle          Episode #1.1662
originalTitle         Episode #1.1662
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002043, dtype: object

(9,)

tconst                     tt11819682
titleType                   tvEpisode
primaryTitle          Episode #1.1663
originalTitle         Episode #1.1663
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002044, dtype: object

(9,)

tconst                     tt11819684
titleType                   tvEpisode
primaryTitle          Episode #1.1664
originalTitle         Episode #1.1664
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002045, dtype: object

(9,)

tconst                   tt11819686
titleType                     movie
primaryTitle      Chasing Childhood
originalTitle     Chasing Childhood
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   78
genres                  Documentary
Name: 2002046, dtype: object

(9,)

tconst                     tt11819688
titleType                   tvEpisode
primaryTitle          Episode #1.1665
originalTitle         Episode #1.1665
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002047, dtype: object

(9,)

tconst                    tt1181968
titleType                 tvEpisode
primaryTitle      Hyggedag med Aske
originalTitle     Hyggedag med Aske
isAdult                           0
startYear                      1986
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2002048, dtype: object

(9,)

tconst                     tt11819690
titleType                   tvEpisode
primaryTitle          Episode #1.1666
originalTitle         Episode #1.1666
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002049, dtype: object

(9,)

tconst                     tt11819692
titleType                   tvEpisode
primaryTitle          Episode #1.1667
originalTitle         Episode #1.1667
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002050, dtype: object

(9,)

tconst                     tt11819694
titleType                   tvEpisode
primaryTitle          Episode #1.1668
originalTitle         Episode #1.1668
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002051, dtype: object

(9,)

tconst                     tt11819696
titleType                   tvEpisode
primaryTitle          Episode #1.1669
originalTitle         Episode #1.1669
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002052, dtype: object

(9,)

tconst                     tt11819698
titleType                   tvEpisode
primaryTitle          Episode #1.1670
originalTitle         Episode #1.1670
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002053, dtype: object

(9,)

tconst               tt1181969
titleType            tvEpisode
primaryTitle      Løst arbejde
originalTitle     Løst arbejde
isAdult                      0
startYear                 1988
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2002054, dtype: object

(9,)

tconst                 tt11819700
titleType               tvEpisode
primaryTitle      Episode #1.1927
originalTitle     Episode #1.1927
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2002055, dtype: object

(9,)

tconst                     tt11819702
titleType                   tvEpisode
primaryTitle          Episode #1.1671
originalTitle         Episode #1.1671
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002056, dtype: object

(9,)

tconst                     tt11819704
titleType                   tvEpisode
primaryTitle          Episode #1.1672
originalTitle         Episode #1.1672
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002057, dtype: object

(9,)

tconst                                            tt11819706
titleType                                           tvSeries
primaryTitle      I Can Do That! - Die große Promi-Challenge
originalTitle     I Can Do That! - Die große Promi-Challenge
isAdult                                                    0
startYear                                               2016
endYear                                                 2016
runtimeMinutes                                            \N
genres                                             Game-Show
Name: 2002058, dtype: object

(9,)

tconst                                                   tt11819708
titleType                                                 tvEpisode
primaryTitle      O uporabnih odpadkih, lokostrelstvu in racunal...
originalTitle     O uporabnih odpadkih, lokostrelstvu in racunal...
isAdult                                                           0
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2002059, dtype: object

(9,)

tconst                 tt1181970
titleType              tvEpisode
primaryTitle      Myggen sværmer
originalTitle     Myggen sværmer
isAdult                        0
startYear                   1986
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2002060, dtype: object

(9,)

tconst                     tt11819710
titleType                   tvEpisode
primaryTitle          Episode #1.1673
originalTitle         Episode #1.1673
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002061, dtype: object

(9,)

tconst                     tt11819712
titleType                   tvEpisode
primaryTitle          Episode #1.1675
originalTitle         Episode #1.1675
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002062, dtype: object

(9,)

tconst                     tt11819714
titleType                   tvEpisode
primaryTitle          Episode #1.1674
originalTitle         Episode #1.1674
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002063, dtype: object

(9,)

tconst                     tt11819716
titleType                   tvEpisode
primaryTitle          Episode #1.1676
originalTitle         Episode #1.1676
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002064, dtype: object

(9,)

tconst                     tt11819718
titleType                   tvEpisode
primaryTitle          Episode #1.1677
originalTitle         Episode #1.1677
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002065, dtype: object

(9,)

tconst            tt1181971
titleType         tvEpisode
primaryTitle        Sporleg
originalTitle       Sporleg
isAdult                   0
startYear              1988
endYear                  \N
runtimeMinutes           \N
genres               Family
Name: 2002066, dtype: object

(9,)

tconst                     tt11819720
titleType                   tvEpisode
primaryTitle          Episode #1.1678
originalTitle         Episode #1.1678
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002067, dtype: object

(9,)

tconst                     tt11819722
titleType                   tvEpisode
primaryTitle          Episode #1.1680
originalTitle         Episode #1.1680
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002068, dtype: object

(9,)

tconst                     tt11819724
titleType                   tvEpisode
primaryTitle          Episode #1.1679
originalTitle         Episode #1.1679
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002069, dtype: object

(9,)

tconst                      tt11819726
titleType                     tvSeries
primaryTitle      Making It... In Ohio
originalTitle     Making It... In Ohio
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                          Comedy
Name: 2002070, dtype: object

(9,)

tconst                            tt11819728
titleType                          tvEpisode
primaryTitle      Shark Tank Colombia (2019)
originalTitle     Shark Tank Colombia (2019)
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                            Reality-TV
Name: 2002071, dtype: object

(9,)

tconst             tt1181972
titleType          tvEpisode
primaryTitle      Svampejagt
originalTitle     Svampejagt
isAdult                    0
startYear               1988
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2002072, dtype: object

(9,)

tconst                     tt11819730
titleType                   tvEpisode
primaryTitle          Episode #1.1901
originalTitle         Episode #1.1901
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002073, dtype: object

(9,)

tconst                          tt11819732
titleType                        tvEpisode
primaryTitle      Inside Eveline's Hot Ass
originalTitle     Inside Eveline's Hot Ass
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2002074, dtype: object

(9,)

tconst                     tt11819734
titleType                   tvEpisode
primaryTitle          Episode #1.1902
originalTitle         Episode #1.1902
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002075, dtype: object

(9,)

tconst                       tt11819736
titleType                         movie
primaryTitle         A Winter's Journey
originalTitle        A Winter's Journey
isAdult                               0
startYear                          2022
endYear                              \N
runtimeMinutes                       \N
genres            Animation,Drama,Music
Name: 2002076, dtype: object

(9,)

tconst                     tt11819738
titleType                   tvEpisode
primaryTitle          Episode #1.1903
originalTitle         Episode #1.1903
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002077, dtype: object

(9,)

tconst            tt1181973
titleType         tvEpisode
primaryTitle       Vaskedag
originalTitle      Vaskedag
isAdult                   0
startYear              1988
endYear                  \N
runtimeMinutes           \N
genres               Family
Name: 2002078, dtype: object

(9,)

tconst                    tt11819740
titleType                  tvEpisode
primaryTitle      My Sweet Surrender
originalTitle     My Sweet Surrender
isAdult                            1
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2002079, dtype: object

(9,)

tconst                     tt11819742
titleType                   tvEpisode
primaryTitle          Episode #1.1904
originalTitle         Episode #1.1904
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002080, dtype: object

(9,)

tconst                     tt11819744
titleType                   tvEpisode
primaryTitle          Episode #1.1905
originalTitle         Episode #1.1905
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002081, dtype: object

(9,)

tconst                                        tt11819746
titleType                                      tvEpisode
primaryTitle      O rozicah, lutkah in toaletnem papirju
originalTitle     O rozicah, lutkah in toaletnem papirju
isAdult                                                0
startYear                                           2014
endYear                                               \N
runtimeMinutes                                        \N
genres                                     Comedy,Family
Name: 2002082, dtype: object

(9,)

tconst                     tt11819748
titleType                   tvEpisode
primaryTitle          Episode #1.1907
originalTitle         Episode #1.1907
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002083, dtype: object

(9,)

tconst                                                    tt1181974
titleType                                                 tvEpisode
primaryTitle      Viola kan være glad for, at det ikke er en tro...
originalTitle     Viola kan være glad for, at det ikke er en tro...
isAdult                                                           0
startYear                                                      1988
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Family
Name: 2002084, dtype: object

(9,)

tconst                     tt11819750
titleType                   tvEpisode
primaryTitle          Episode #1.1906
originalTitle         Episode #1.1906
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002085, dtype: object

(9,)

tconst                     tt11819752
titleType                   tvEpisode
primaryTitle          Episode #1.1908
originalTitle         Episode #1.1908
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002086, dtype: object

(9,)

tconst                     tt11819754
titleType                   tvEpisode
primaryTitle          Episode #1.1910
originalTitle         Episode #1.1910
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002087, dtype: object

(9,)

tconst                     tt11819756
titleType                   tvEpisode
primaryTitle          Episode #1.1909
originalTitle         Episode #1.1909
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002088, dtype: object

(9,)

tconst                     tt11819758
titleType                   tvEpisode
primaryTitle          Episode #1.1911
originalTitle         Episode #1.1911
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002089, dtype: object

(9,)

tconst                  tt1181975
titleType               tvEpisode
primaryTitle         Episode #2.5
originalTitle        Episode #2.5
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres            Biography,Music
Name: 2002090, dtype: object

(9,)

tconst                     tt11819760
titleType                   tvEpisode
primaryTitle          Episode #1.1913
originalTitle         Episode #1.1913
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002091, dtype: object

(9,)

tconst                     tt11819762
titleType                   tvEpisode
primaryTitle          Episode #1.1912
originalTitle         Episode #1.1912
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002092, dtype: object

(9,)

tconst             tt11819764
titleType               short
primaryTitle       Stand Firm
originalTitle      Stand Firm
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             21
genres            Drama,Short
Name: 2002093, dtype: object

(9,)

tconst                     tt11819766
titleType                   tvEpisode
primaryTitle          Episode #1.1914
originalTitle         Episode #1.1914
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002094, dtype: object

(9,)

tconst                     tt11819768
titleType                   tvEpisode
primaryTitle          Episode #1.1915
originalTitle         Episode #1.1915
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002095, dtype: object

(9,)

tconst                              tt1181976
titleType                           tvEpisode
primaryTitle      Episode dated 13 April 1994
originalTitle     Episode dated 13 April 1994
isAdult                                     0
startYear                                1994
endYear                                    \N
runtimeMinutes                             \N
genres                  Comedy,Game-Show,News
Name: 2002096, dtype: object

(9,)

tconst                     tt11819770
titleType                   tvEpisode
primaryTitle          Episode #1.1916
originalTitle         Episode #1.1916
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002097, dtype: object

(9,)

tconst                     tt11819774
titleType                   tvEpisode
primaryTitle          Episode #1.1917
originalTitle         Episode #1.1917
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002098, dtype: object

(9,)

tconst                     tt11819776
titleType                   tvEpisode
primaryTitle          Episode #1.1918
originalTitle         Episode #1.1918
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002099, dtype: object

(9,)

tconst                     tt11819778
titleType                   tvEpisode
primaryTitle          Episode #1.1919
originalTitle         Episode #1.1919
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002100, dtype: object

(9,)

tconst                                          tt1181977
titleType                                       tvEpisode
primaryTitle      Kako je propao rock'n'roll na mom otoku
originalTitle     Kako je propao rock'n'roll na mom otoku
isAdult                                                 0
startYear                                            2008
endYear                                                \N
runtimeMinutes                                         \N
genres                                             Comedy
Name: 2002101, dtype: object

(9,)

tconst                     tt11819780
titleType                   tvEpisode
primaryTitle          Episode #1.1920
originalTitle         Episode #1.1920
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2002102, dtype: object

(9,)

tconst                         tt11819782
titleType                       tvEpisode
primaryTitle      Hatef and lasting songs
originalTitle     Hatef and lasting songs
isAdult                                 0
startYear                            2014
endYear                                \N
runtimeMinutes                         \N
genres                         Reality-TV
Name: 2002103, dtype: object

(9,)

tconst                      tt11819784
titleType                    tvEpisode
primaryTitle      Morning Teenage Love
originalTitle     Morning Teenage Love
isAdult                              1
startYear                         2020
endYear                             \N
runtimeMinutes                      26
genres                           Adult
Name: 2002104, dtype: object

(9,)

tconst                                tt1181978
titleType                             tvEpisode
primaryTitle      Man Accused of Poisoning Wife
originalTitle     Man Accused of Poisoning Wife
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                          News,Reality-TV
Name: 2002105, dtype: object

(9,)

tconst                tt11819794
titleType              tvEpisode
primaryTitle      Episode #1.121
originalTitle     Episode #1.121
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002106, dtype: object

(9,)

tconst                   tt11819798
titleType                 tvEpisode
primaryTitle      Cars! Cars! Cars!
originalTitle     Cars! Cars! Cars!
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                   Reality-TV
Name: 2002107, dtype: object

(9,)

tconst                                 tt1181979
titleType                              tvEpisode
primaryTitle      Episode dated 16 November 1967
originalTitle     Episode dated 16 November 1967
isAdult                                        0
startYear                                   1967
endYear                                       \N
runtimeMinutes                                25
genres                                    Family
Name: 2002108, dtype: object

(9,)

tconst                                     tt11819802
titleType                                   tvEpisode
primaryTitle      O rolkah, gepardih in gnilih jajcih
originalTitle     O rolkah, gepardih in gnilih jajcih
isAdult                                             0
startYear                                        2014
endYear                                            \N
runtimeMinutes                                     \N
genres                                  Comedy,Family
Name: 2002109, dtype: object

(9,)

tconst                                tt11819804
titleType                              tvEpisode
primaryTitle      Opernball - Die Gesprächsrunde
originalTitle     Opernball - Die Gesprächsrunde
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                               Documentary
Name: 2002110, dtype: object

(9,)

tconst                tt11819808
titleType              tvEpisode
primaryTitle      Episode #1.122
originalTitle     Episode #1.122
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002111, dtype: object

(9,)

tconst                                tt1181980
titleType                             tvEpisode
primaryTitle      Episode dated 25 October 1971
originalTitle     Episode dated 25 October 1971
isAdult                                       0
startYear                                  1971
endYear                                      \N
runtimeMinutes                               25
genres                                   Family
Name: 2002112, dtype: object

(9,)

tconst                           tt11819810
titleType                             video
primaryTitle      Patron & Ati242: WhatsApp
originalTitle     Patron & Ati242: WhatsApp
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                            3
genres                          Music,Short
Name: 2002113, dtype: object

(9,)

tconst                tt11819812
titleType              tvEpisode
primaryTitle      Episode #1.123
originalTitle     Episode #1.123
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002114, dtype: object

(9,)

tconst                tt11819814
titleType              tvEpisode
primaryTitle      Episode #1.124
originalTitle     Episode #1.124
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002115, dtype: object

(9,)

tconst                tt11819816
titleType              tvEpisode
primaryTitle      Episode #1.125
originalTitle     Episode #1.125
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002116, dtype: object

(9,)

tconst                tt11819818
titleType              tvEpisode
primaryTitle      Episode #1.126
originalTitle     Episode #1.126
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002117, dtype: object

(9,)

tconst                            tt1181981
titleType                         tvEpisode
primaryTitle      Episode dated 7 June 1973
originalTitle     Episode dated 7 June 1973
isAdult                                   0
startYear                              1973
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2002118, dtype: object

(9,)

tconst                tt11819820
titleType              tvEpisode
primaryTitle      Episode #1.127
originalTitle     Episode #1.127
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002119, dtype: object

(9,)

tconst               tt11819822
titleType             tvEpisode
primaryTitle       Episode #1.2
originalTitle      Episode #1.2
isAdult                       0
startYear                  1979
endYear                      \N
runtimeMinutes               \N
genres            Drama,Mystery
Name: 2002120, dtype: object

(9,)

tconst                tt11819824
titleType              tvEpisode
primaryTitle      Episode #1.128
originalTitle     Episode #1.128
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002121, dtype: object

(9,)

tconst               tt11819826
titleType               tvMovie
primaryTitle      Onaj zutokosi
originalTitle     Onaj zutokosi
isAdult                       0
startYear                  1967
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002122, dtype: object

(9,)

tconst                tt11819828
titleType              tvEpisode
primaryTitle      Episode #1.129
originalTitle     Episode #1.129
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002123, dtype: object

(9,)

tconst                             tt1181982
titleType                          tvEpisode
primaryTitle      Episode dated 11 June 1973
originalTitle     Episode dated 11 June 1973
isAdult                                    0
startYear                               1973
endYear                                   \N
runtimeMinutes                            \N
genres                                Family
Name: 2002124, dtype: object

(9,)

tconst                tt11819830
titleType              tvEpisode
primaryTitle      Episode #1.131
originalTitle     Episode #1.131
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002125, dtype: object

(9,)

tconst                  tt11819832
titleType                tvEpisode
primaryTitle      All In... My Ass
originalTitle     All In... My Ass
isAdult                          1
startYear                     2010
endYear                         \N
runtimeMinutes                  16
genres                       Adult
Name: 2002126, dtype: object

(9,)

tconst                tt11819834
titleType              tvEpisode
primaryTitle      Episode #1.130
originalTitle     Episode #1.130
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002127, dtype: object

(9,)

tconst                tt11819836
titleType              tvEpisode
primaryTitle      Episode #1.132
originalTitle     Episode #1.132
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002128, dtype: object

(9,)

tconst                tt11819838
titleType              tvEpisode
primaryTitle      Episode #1.134
originalTitle     Episode #1.134
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002129, dtype: object

(9,)

tconst                            tt1181983
titleType                         tvEpisode
primaryTitle      Episode dated 23 May 1974
originalTitle     Episode dated 23 May 1974
isAdult                                   0
startYear                              1974
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2002130, dtype: object

(9,)

tconst                tt11819840
titleType              tvEpisode
primaryTitle      Episode #1.133
originalTitle     Episode #1.133
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002131, dtype: object

(9,)

tconst                tt11819842
titleType              tvEpisode
primaryTitle      Episode #1.135
originalTitle     Episode #1.135
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002132, dtype: object

(9,)

tconst                tt11819844
titleType              tvEpisode
primaryTitle      Episode #1.136
originalTitle     Episode #1.136
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002133, dtype: object

(9,)

tconst                tt11819846
titleType              tvEpisode
primaryTitle      Episode #1.138
originalTitle     Episode #1.138
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002134, dtype: object

(9,)

tconst                tt11819848
titleType              tvEpisode
primaryTitle      Episode #1.137
originalTitle     Episode #1.137
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002135, dtype: object

(9,)

tconst                              tt1181984
titleType                           tvEpisode
primaryTitle      Episode dated 20 March 1975
originalTitle     Episode dated 20 March 1975
isAdult                                     0
startYear                                1975
endYear                                    \N
runtimeMinutes                             \N
genres                                 Family
Name: 2002136, dtype: object

(9,)

tconst                                                   tt11819850
titleType                                                 tvEpisode
primaryTitle      Natasha Teen plays with huge dildos before DAP...
originalTitle     Natasha Teen plays with huge dildos before DAP...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002137, dtype: object

(9,)

tconst                tt11819852
titleType              tvEpisode
primaryTitle         Épisode 664
originalTitle        Épisode 664
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                28
genres            Crime,Thriller
Name: 2002138, dtype: object

(9,)

tconst                tt11819854
titleType              tvEpisode
primaryTitle      Episode #1.139
originalTitle     Episode #1.139
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002139, dtype: object

(9,)

tconst                                                   tt11819856
titleType                                                     video
primaryTitle      HappyToursTravel Commercial, 'Las mejores tari...
originalTitle     HappyToursTravel Commercial, 'Las mejores tari...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Short
Name: 2002140, dtype: object

(9,)

tconst                tt11819858
titleType              tvEpisode
primaryTitle      Episode #1.140
originalTitle     Episode #1.140
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002141, dtype: object

(9,)

tconst                             tt1181985
titleType                          tvEpisode
primaryTitle      Episode dated 3 April 1980
originalTitle     Episode dated 3 April 1980
isAdult                                    0
startYear                               1980
endYear                                   \N
runtimeMinutes                            \N
genres                                Family
Name: 2002142, dtype: object

(9,)

tconst                tt11819860
titleType              tvEpisode
primaryTitle      Episode #1.321
originalTitle     Episode #1.321
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002143, dtype: object

(9,)

tconst                                           tt11819862
titleType                                         tvEpisode
primaryTitle      O barmanstvu, bmxih in lucki v hladilniku
originalTitle     O barmanstvu, bmxih in lucki v hladilniku
isAdult                                                   0
startYear                                              2014
endYear                                                  \N
runtimeMinutes                                           \N
genres                                        Comedy,Family
Name: 2002144, dtype: object

(9,)

tconst                tt11819864
titleType              tvEpisode
primaryTitle      Episode #1.322
originalTitle     Episode #1.322
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002145, dtype: object

(9,)

tconst                tt11819866
titleType              tvEpisode
primaryTitle      Episode #1.323
originalTitle     Episode #1.323
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002146, dtype: object

(9,)

tconst             tt11819868
titleType               short
primaryTitle            Clara
originalTitle           Clara
isAdult                     0
startYear                1981
endYear                    \N
runtimeMinutes             28
genres            Drama,Short
Name: 2002147, dtype: object

(9,)

tconst                                tt1181986
titleType                             tvEpisode
primaryTitle      Episode dated 16 October 2006
originalTitle     Episode dated 16 October 2006
isAdult                                       0
startYear                                  2006
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2002148, dtype: object

(9,)

tconst                tt11819870
titleType              tvEpisode
primaryTitle      Episode #1.324
originalTitle     Episode #1.324
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002149, dtype: object

(9,)

tconst                tt11819872
titleType              tvEpisode
primaryTitle      Episode #1.325
originalTitle     Episode #1.325
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002150, dtype: object

(9,)

tconst                tt11819874
titleType              tvEpisode
primaryTitle      Episode #1.326
originalTitle     Episode #1.326
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002151, dtype: object

(9,)

tconst                tt11819876
titleType              tvEpisode
primaryTitle      Episode #1.327
originalTitle     Episode #1.327
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002152, dtype: object

(9,)

tconst                        tt1181987
titleType                     tvEpisode
primaryTitle       Celebration of Death
originalTitle      Celebration of Death
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres            Adventure,Crime,Drama
Name: 2002153, dtype: object

(9,)

tconst                tt11819880
titleType              tvEpisode
primaryTitle      Episode #1.329
originalTitle     Episode #1.329
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002154, dtype: object

(9,)

tconst                tt11819882
titleType              tvEpisode
primaryTitle      Episode #1.328
originalTitle     Episode #1.328
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002155, dtype: object

(9,)

tconst                                               tt11819884
titleType                                             tvEpisode
primaryTitle      Natasha Teen balls deep anal & DP 3on1 SZ2162
originalTitle     Natasha Teen balls deep anal & DP 3on1 SZ2162
isAdult                                                       1
startYear                                                  2019
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                    Adult
Name: 2002156, dtype: object

(9,)

tconst                tt11819886
titleType              tvEpisode
primaryTitle      Episode #1.330
originalTitle     Episode #1.330
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002157, dtype: object

(9,)

tconst                tt11819888
titleType              tvEpisode
primaryTitle      Episode #1.331
originalTitle     Episode #1.331
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002158, dtype: object

(9,)

tconst                               tt1181988
titleType                            tvEpisode
primaryTitle      Episode dated 3 January 2008
originalTitle     Episode dated 3 January 2008
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2002159, dtype: object

(9,)

tconst                                          tt11819890
titleType                                            movie
primaryTitle      Pokémon the Movie: Secrets of the Jungle
originalTitle             Gekijouban Poketto monsutâ: koko
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          99
genres                          Action,Adventure,Animation
Name: 2002160, dtype: object

(9,)

tconst                tt11819892
titleType              tvEpisode
primaryTitle      Episode #1.332
originalTitle     Episode #1.332
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002161, dtype: object

(9,)

tconst                tt11819894
titleType              tvEpisode
primaryTitle      Episode #1.333
originalTitle     Episode #1.333
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002162, dtype: object

(9,)

tconst                tt11819896
titleType              tvEpisode
primaryTitle      Episode #1.334
originalTitle     Episode #1.334
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002163, dtype: object

(9,)

tconst                tt11819898
titleType              tvEpisode
primaryTitle      Episode #1.335
originalTitle     Episode #1.335
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002164, dtype: object

(9,)

tconst                                tt1181989
titleType                             tvEpisode
primaryTitle      Episode dated 10 January 2008
originalTitle     Episode dated 10 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2002165, dtype: object

(9,)

tconst                tt11819900
titleType              tvEpisode
primaryTitle      Episode #1.337
originalTitle     Episode #1.337
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002166, dtype: object

(9,)

tconst                tt11819902
titleType              tvEpisode
primaryTitle      Episode #1.336
originalTitle     Episode #1.336
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002167, dtype: object

(9,)

tconst                tt11819904
titleType              tvEpisode
primaryTitle      Episode #1.338
originalTitle     Episode #1.338
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002168, dtype: object

(9,)

tconst                tt11819906
titleType              tvEpisode
primaryTitle      Episode #1.339
originalTitle     Episode #1.339
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002169, dtype: object

(9,)

tconst                tt11819908
titleType              tvEpisode
primaryTitle      Episode #1.340
originalTitle     Episode #1.340
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002170, dtype: object

(9,)

tconst                                tt1181990
titleType                             tvEpisode
primaryTitle      Episode dated 11 January 2008
originalTitle     Episode dated 11 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2002171, dtype: object

(9,)

tconst                tt11819910
titleType              tvEpisode
primaryTitle      Episode #1.121
originalTitle     Episode #1.121
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002172, dtype: object

(9,)

tconst                                              tt11819912
titleType                                            tvEpisode
primaryTitle      O kolcanju, glasbi v bazenu in cistih cestah
originalTitle     O kolcanju, glasbi v bazenu in cistih cestah
isAdult                                                      0
startYear                                                 2014
endYear                                                     \N
runtimeMinutes                                              \N
genres                                           Comedy,Family
Name: 2002173, dtype: object

(9,)

tconst                tt11819914
titleType                  short
primaryTitle      Wedding Runner
originalTitle     Wedding Runner
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                 2
genres              Comedy,Short
Name: 2002174, dtype: object

(9,)

tconst                                                   tt11819916
titleType                                                 tvEpisode
primaryTitle      Doubleanalized Natasha Teen Gets 2 BBC Balls D...
originalTitle     Doubleanalized Natasha Teen Gets 2 BBC Balls D...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002175, dtype: object

(9,)

tconst                tt11819918
titleType              tvEpisode
primaryTitle      Episode #1.122
originalTitle     Episode #1.122
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002176, dtype: object

(9,)

tconst                                tt1181991
titleType                             tvEpisode
primaryTitle      Episode dated 17 January 2008
originalTitle     Episode dated 17 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2002177, dtype: object

(9,)

tconst                tt11819920
titleType              tvEpisode
primaryTitle      Episode #1.123
originalTitle     Episode #1.123
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002178, dtype: object

(9,)

tconst                tt11819922
titleType              tvEpisode
primaryTitle      Episode #1.124
originalTitle     Episode #1.124
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002179, dtype: object

(9,)

tconst                tt11819924
titleType              tvEpisode
primaryTitle      Episode #1.126
originalTitle     Episode #1.126
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002180, dtype: object

(9,)

tconst                tt11819926
titleType              tvEpisode
primaryTitle      Episode #1.125
originalTitle     Episode #1.125
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002181, dtype: object

(9,)

tconst                tt11819928
titleType              tvEpisode
primaryTitle      Episode #1.127
originalTitle     Episode #1.127
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002182, dtype: object

(9,)

tconst                                tt1181992
titleType                             tvEpisode
primaryTitle      Episode dated 18 January 2008
originalTitle     Episode dated 18 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2002183, dtype: object

(9,)

tconst                tt11819930
titleType              tvEpisode
primaryTitle      Episode #1.128
originalTitle     Episode #1.128
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002184, dtype: object

(9,)

tconst                tt11819932
titleType              tvEpisode
primaryTitle      Episode #1.129
originalTitle     Episode #1.129
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002185, dtype: object

(9,)

tconst                                                   tt11819934
titleType                                                     video
primaryTitle      Sons of Apollo: Live with the Plovdiv Psychoti...
originalTitle     Sons of Apollo: Live with the Plovdiv Psychoti...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                  153
genres                                                        Music
Name: 2002186, dtype: object

(9,)

tconst                tt11819936
titleType              tvEpisode
primaryTitle      Episode #1.131
originalTitle     Episode #1.131
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002187, dtype: object

(9,)

tconst                tt11819938
titleType              tvEpisode
primaryTitle      Episode #1.130
originalTitle     Episode #1.130
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002188, dtype: object

(9,)

tconst                                tt1181993
titleType                             tvEpisode
primaryTitle      Episode dated 24 January 2008
originalTitle     Episode dated 24 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2002189, dtype: object

(9,)

tconst                tt11819942
titleType              tvEpisode
primaryTitle      Episode #1.133
originalTitle     Episode #1.133
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002190, dtype: object

(9,)

tconst                tt11819944
titleType              tvEpisode
primaryTitle      Episode #1.132
originalTitle     Episode #1.132
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002191, dtype: object

(9,)

tconst                tt11819946
titleType              tvEpisode
primaryTitle      Episode #1.134
originalTitle     Episode #1.134
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002192, dtype: object

(9,)

tconst                tt11819948
titleType              tvEpisode
primaryTitle      Episode #1.135
originalTitle     Episode #1.135
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002193, dtype: object

(9,)

tconst                                tt1181994
titleType                             tvEpisode
primaryTitle      Episode dated 25 January 2008
originalTitle     Episode dated 25 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2002194, dtype: object

(9,)

tconst                tt11819950
titleType              tvEpisode
primaryTitle      Episode #1.136
originalTitle     Episode #1.136
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002195, dtype: object

(9,)

tconst                tt11819952
titleType              tvEpisode
primaryTitle      Episode #1.137
originalTitle     Episode #1.137
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002196, dtype: object

(9,)

tconst                tt11819956
titleType              tvEpisode
primaryTitle      Episode #1.139
originalTitle     Episode #1.139
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002197, dtype: object

(9,)

tconst                tt11819958
titleType              tvEpisode
primaryTitle      Episode #1.138
originalTitle     Episode #1.138
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002198, dtype: object

(9,)

tconst                                tt1181995
titleType                             tvEpisode
primaryTitle      Episode dated 31 January 2008
originalTitle     Episode dated 31 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2002199, dtype: object

(9,)

tconst                                    tt11819960
titleType                                  tvEpisode
primaryTitle      O lupingih, sabljanju in crepinjah
originalTitle     O lupingih, sabljanju in crepinjah
isAdult                                            0
startYear                                       2014
endYear                                           \N
runtimeMinutes                                    \N
genres                                 Comedy,Family
Name: 2002200, dtype: object

(9,)

tconst                tt11819962
titleType              tvEpisode
primaryTitle      Episode #1.140
originalTitle     Episode #1.140
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2002201, dtype: object

(9,)

tconst               tt11819964
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002202, dtype: object

(9,)

tconst                 tt11819966
titleType               tvEpisode
primaryTitle      Episode #1.1928
originalTitle     Episode #1.1928
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2002203, dtype: object

(9,)

tconst                          tt11819968
titleType                        tvEpisode
primaryTitle      The Bachelorette Present
originalTitle     The Bachelorette Present
isAdult                                  1
startYear                             2010
endYear                                 \N
runtimeMinutes                          18
genres                               Adult
Name: 2002204, dtype: object

(9,)

tconst                                tt1181996
titleType                             tvEpisode
primaryTitle      Episode dated 1 February 2008
originalTitle     Episode dated 1 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2002205, dtype: object

(9,)

tconst               tt11819970
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002206, dtype: object

(9,)

tconst               tt11819972
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002207, dtype: object

(9,)

tconst               tt11819974
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002208, dtype: object

(9,)

tconst               tt11819976
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002209, dtype: object

(9,)

tconst               tt11819978
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002210, dtype: object

(9,)

tconst                     tt1181997
titleType                  tvEpisode
primaryTitle      A Question of Duty
originalTitle     A Question of Duty
isAdult                            0
startYear                       1958
endYear                           \N
runtimeMinutes                    \N
genres                       Western
Name: 2002211, dtype: object

(9,)

tconst               tt11819980
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002212, dtype: object

(9,)

tconst               tt11819982
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002213, dtype: object

(9,)

tconst               tt11819984
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002214, dtype: object

(9,)

tconst               tt11819986
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002215, dtype: object

(9,)

tconst               tt11819988
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002216, dtype: object

(9,)

tconst                 tt1181998
titleType              tvEpisode
primaryTitle      Border Raiders
originalTitle     Border Raiders
isAdult                        0
startYear                   1957
endYear                       \N
runtimeMinutes                \N
genres                   Western
Name: 2002217, dtype: object

(9,)

tconst               tt11819990
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002218, dtype: object

(9,)

tconst               tt11819992
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002219, dtype: object

(9,)

tconst               tt11819994
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002220, dtype: object

(9,)

tconst               tt11819996
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002221, dtype: object

(9,)

tconst               tt11819998
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002222, dtype: object

(9,)

tconst                        tt1181999
titleType                     tvEpisode
primaryTitle      Female of the Species
originalTitle     Female of the Species
isAdult                               0
startYear                          1958
endYear                              \N
runtimeMinutes                       \N
genres                          Western
Name: 2002223, dtype: object

(9,)

tconst               tt11820000
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002224, dtype: object

(9,)

tconst               tt11820002
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002225, dtype: object

(9,)

tconst               tt11820004
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002226, dtype: object

(9,)

tconst                tt11820006
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002227, dtype: object

(9,)

tconst                tt11820008
titleType              tvEpisode
primaryTitle      Episode #1.281
originalTitle     Episode #1.281
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002228, dtype: object

(9,)

tconst            tt1182000
titleType         tvEpisode
primaryTitle      Iron John
originalTitle     Iron John
isAdult                   0
startYear              1958
endYear                  \N
runtimeMinutes           \N
genres              Western
Name: 2002229, dtype: object

(9,)

tconst                tt11820010
titleType              tvEpisode
primaryTitle      Episode #1.283
originalTitle     Episode #1.283
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002230, dtype: object

(9,)

tconst                tt11820012
titleType              tvEpisode
primaryTitle      Episode #1.282
originalTitle     Episode #1.282
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002231, dtype: object

(9,)

tconst                       tt11820014
titleType                     tvEpisode
primaryTitle      Les yeux de la colère
originalTitle     Les yeux de la colère
isAdult                               0
startYear                          2012
endYear                              \N
runtimeMinutes                       \N
genres                            Drama
Name: 2002232, dtype: object

(9,)

tconst                tt11820016
titleType              tvEpisode
primaryTitle      Episode #1.284
originalTitle     Episode #1.284
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002233, dtype: object

(9,)

tconst                tt11820018
titleType              tvEpisode
primaryTitle      Episode #1.285
originalTitle     Episode #1.285
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002234, dtype: object

(9,)

tconst               tt1182001
titleType            tvEpisode
primaryTitle      Late Arrival
originalTitle     Late Arrival
isAdult                      0
startYear                 1958
endYear                     \N
runtimeMinutes              30
genres                 Western
Name: 2002235, dtype: object

(9,)

tconst                tt11820020
titleType              tvEpisode
primaryTitle      Episode #1.286
originalTitle     Episode #1.286
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002236, dtype: object

(9,)

tconst                tt11820022
titleType              tvEpisode
primaryTitle      Episode #1.287
originalTitle     Episode #1.287
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002237, dtype: object

(9,)

tconst                tt11820024
titleType              tvEpisode
primaryTitle      Episode #1.288
originalTitle     Episode #1.288
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002238, dtype: object

(9,)

tconst                tt11820026
titleType              tvEpisode
primaryTitle      Episode #1.289
originalTitle     Episode #1.289
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002239, dtype: object

(9,)

tconst                tt11820028
titleType              tvEpisode
primaryTitle      Episode #1.290
originalTitle     Episode #1.290
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002240, dtype: object

(9,)

tconst              tt1182002
titleType           tvEpisode
primaryTitle      One Man War
originalTitle     One Man War
isAdult                     0
startYear                1958
endYear                    \N
runtimeMinutes             \N
genres                Western
Name: 2002241, dtype: object

(9,)

tconst                tt11820030
titleType              tvEpisode
primaryTitle      Episode #1.291
originalTitle     Episode #1.291
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002242, dtype: object

(9,)

tconst                                     tt11820032
titleType                                   tvEpisode
primaryTitle      MY HOUSE IS HAUNTED (screams heard)
originalTitle     MY HOUSE IS HAUNTED (screams heard)
isAdult                                             0
startYear                                        2017
endYear                                            \N
runtimeMinutes                                     \N
genres                    Adventure,Documentary,Drama
Name: 2002243, dtype: object

(9,)

tconst                tt11820034
titleType              tvEpisode
primaryTitle      Episode #1.293
originalTitle     Episode #1.293
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002244, dtype: object

(9,)

tconst                tt11820036
titleType              tvEpisode
primaryTitle      Episode #1.292
originalTitle     Episode #1.292
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002245, dtype: object

(9,)

tconst                tt11820038
titleType              tvEpisode
primaryTitle      Episode #1.294
originalTitle     Episode #1.294
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002246, dtype: object

(9,)

tconst                 tt1182003
titleType              tvEpisode
primaryTitle      Pound of Flesh
originalTitle     Pound of Flesh
isAdult                        0
startYear                   1958
endYear                       \N
runtimeMinutes                \N
genres                   Western
Name: 2002247, dtype: object

(9,)

tconst                tt11820040
titleType              tvEpisode
primaryTitle      Episode #1.295
originalTitle     Episode #1.295
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002248, dtype: object

(9,)

tconst                tt11820042
titleType              tvEpisode
primaryTitle      Episode #1.296
originalTitle     Episode #1.296
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002249, dtype: object

(9,)

tconst                tt11820044
titleType              tvEpisode
primaryTitle      Episode #1.298
originalTitle     Episode #1.298
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002250, dtype: object

(9,)

tconst                tt11820046
titleType              tvEpisode
primaryTitle      Episode #1.297
originalTitle     Episode #1.297
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002251, dtype: object

(9,)

tconst                 tt11820048
titleType               tvEpisode
primaryTitle      Episode #1.1929
originalTitle     Episode #1.1929
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2002252, dtype: object

(9,)

tconst              tt1182004
titleType           tvEpisode
primaryTitle      Private War
originalTitle     Private War
isAdult                     0
startYear                1957
endYear                    \N
runtimeMinutes             \N
genres                Western
Name: 2002253, dtype: object

(9,)

tconst                tt11820050
titleType              tvEpisode
primaryTitle      Episode #1.299
originalTitle     Episode #1.299
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002254, dtype: object

(9,)

tconst                tt11820052
titleType              tvEpisode
primaryTitle      Episode #1.300
originalTitle     Episode #1.300
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002255, dtype: object

(9,)

tconst                   tt11820054
titleType                 tvEpisode
primaryTitle      The Chase Begins!
originalTitle     The Chase Begins!
isAdult                           0
startYear                      2011
endYear                          \N
runtimeMinutes                   30
genres                       Action
Name: 2002256, dtype: object

(9,)

tconst                                    tt11820056
titleType                                  tvEpisode
primaryTitle      Maruti Gets Trapped In Bali's Plan
originalTitle     Maruti Gets Trapped In Bali's Plan
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                       Fantasy
Name: 2002257, dtype: object

(9,)

tconst                tt11820058
titleType              tvEpisode
primaryTitle      Episode #1.562
originalTitle     Episode #1.562
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002258, dtype: object

(9,)

tconst                           tt1182005
titleType                        tvEpisode
primaryTitle      Quiet Day at Fort Lowell
originalTitle     Quiet Day at Fort Lowell
isAdult                                  0
startYear                             1957
endYear                                 \N
runtimeMinutes                          30
genres                             Western
Name: 2002259, dtype: object

(9,)

tconst                tt11820060
titleType              tvEpisode
primaryTitle      Episode #1.561
originalTitle     Episode #1.561
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002260, dtype: object

(9,)

tconst                tt11820062
titleType              tvEpisode
primaryTitle      Episode #1.563
originalTitle     Episode #1.563
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002261, dtype: object

(9,)

tconst                tt11820064
titleType              tvEpisode
primaryTitle      Episode #1.564
originalTitle     Episode #1.564
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002262, dtype: object

(9,)

tconst                             tt11820066
titleType                           tvEpisode
primaryTitle         2017 CONSPIRACY THEORIES
originalTitle        2017 CONSPIRACY THEORIES
isAdult                                     0
startYear                                2017
endYear                                    \N
runtimeMinutes                             \N
genres            Adventure,Documentary,Drama
Name: 2002263, dtype: object

(9,)

tconst                tt11820068
titleType              tvEpisode
primaryTitle      Episode #1.565
originalTitle     Episode #1.565
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002264, dtype: object

(9,)

tconst                         tt1182006
titleType                      tvEpisode
primaryTitle      Rescue of the Stranger
originalTitle     Rescue of the Stranger
isAdult                                0
startYear                           1958
endYear                               \N
runtimeMinutes                        \N
genres                           Western
Name: 2002265, dtype: object

(9,)

tconst                tt11820070
titleType              tvEpisode
primaryTitle      Episode #1.566
originalTitle     Episode #1.566
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002266, dtype: object

(9,)

tconst                tt11820072
titleType              tvEpisode
primaryTitle      Episode #1.567
originalTitle     Episode #1.567
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002267, dtype: object

(9,)

tconst                tt11820074
titleType              tvEpisode
primaryTitle      Episode #1.569
originalTitle     Episode #1.569
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002268, dtype: object

(9,)

tconst                tt11820076
titleType              tvEpisode
primaryTitle      Episode #1.568
originalTitle     Episode #1.568
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002269, dtype: object

(9,)

tconst                tt11820078
titleType              tvEpisode
primaryTitle      Episode #1.570
originalTitle     Episode #1.570
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002270, dtype: object

(9,)

tconst                      tt1182007
titleType                   tvEpisode
primaryTitle      The Captain's Leave
originalTitle     The Captain's Leave
isAdult                             0
startYear                        1958
endYear                            \N
runtimeMinutes                     30
genres                        Western
Name: 2002271, dtype: object

(9,)

tconst                tt11820080
titleType              tvEpisode
primaryTitle      Episode #1.571
originalTitle     Episode #1.571
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002272, dtype: object

(9,)

tconst            tt11820082
titleType          tvEpisode
primaryTitle      Fitting In
originalTitle     Fitting In
isAdult                    0
startYear               2011
endYear                   \N
runtimeMinutes            30
genres                Action
Name: 2002273, dtype: object

(9,)

tconst                tt11820084
titleType              tvEpisode
primaryTitle      Episode #1.572
originalTitle     Episode #1.572
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002274, dtype: object

(9,)

tconst                tt11820086
titleType              tvEpisode
primaryTitle      Episode #1.573
originalTitle     Episode #1.573
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002275, dtype: object

(9,)

tconst                tt11820088
titleType              tvEpisode
primaryTitle      Episode #1.574
originalTitle     Episode #1.574
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002276, dtype: object

(9,)

tconst                    tt1182008
titleType                 tvEpisode
primaryTitle      The Court Martial
originalTitle     The Court Martial
isAdult                           0
startYear                      1958
endYear                          \N
runtimeMinutes                   \N
genres                      Western
Name: 2002277, dtype: object

(9,)

tconst                tt11820090
titleType              tvEpisode
primaryTitle      Episode #1.575
originalTitle     Episode #1.575
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002278, dtype: object

(9,)

tconst                tt11820092
titleType              tvEpisode
primaryTitle      Episode #1.576
originalTitle     Episode #1.576
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002279, dtype: object

(9,)

tconst                tt11820094
titleType              tvEpisode
primaryTitle      Episode #1.577
originalTitle     Episode #1.577
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002280, dtype: object

(9,)

tconst                tt11820096
titleType              tvEpisode
primaryTitle      Episode #1.578
originalTitle     Episode #1.578
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002281, dtype: object

(9,)

tconst                tt11820098
titleType              tvEpisode
primaryTitle      Episode #1.579
originalTitle     Episode #1.579
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002282, dtype: object

(9,)

tconst             tt1182009
titleType          tvEpisode
primaryTitle      The Coward
originalTitle     The Coward
isAdult                    0
startYear               1957
endYear                   \N
runtimeMinutes            30
genres               Western
Name: 2002283, dtype: object

(9,)

tconst                tt11820100
titleType              tvEpisode
primaryTitle      Episode #1.580
originalTitle     Episode #1.580
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002284, dtype: object

(9,)

tconst                  tt11820102
titleType                    movie
primaryTitle      Murderful Wonder
originalTitle     Murderful Wonder
isAdult                          0
startYear                     2021
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Mystery
Name: 2002285, dtype: object

(9,)

tconst                tt11820104
titleType              tvEpisode
primaryTitle      Episode #1.721
originalTitle     Episode #1.721
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002286, dtype: object

(9,)

tconst                                tt11820106
titleType                              tvEpisode
primaryTitle      I Played the Ouija Board Alone
originalTitle     I Played the Ouija Board Alone
isAdult                                        0
startYear                                   2017
endYear                                       \N
runtimeMinutes                                \N
genres               Adventure,Documentary,Drama
Name: 2002287, dtype: object

(9,)

tconst                     tt1182010
titleType                  tvEpisode
primaryTitle      The Dispatch Rider
originalTitle     The Dispatch Rider
isAdult                            0
startYear                       1958
endYear                           \N
runtimeMinutes                    \N
genres                       Western
Name: 2002288, dtype: object

(9,)

tconst              tt11820110
titleType                short
primaryTitle            A Team
originalTitle           A Team
isAdult                      0
startYear                 2016
endYear                     \N
runtimeMinutes              23
genres            Action,Short
Name: 2002289, dtype: object

(9,)

tconst                             tt11820112
titleType                        tvMiniSeries
primaryTitle      The Chronicles of Rokamboll
originalTitle     The Chronicles of Rokamboll
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                              6
genres                                  Drama
Name: 2002290, dtype: object

(9,)

tconst                tt11820114
titleType              tvEpisode
primaryTitle      Episode #1.722
originalTitle     Episode #1.722
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002291, dtype: object

(9,)

tconst            tt11820116
titleType              short
primaryTitle            Just
originalTitle           Just
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2002292, dtype: object

(9,)

tconst                tt11820118
titleType              tvEpisode
primaryTitle      Episode #1.723
originalTitle     Episode #1.723
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002293, dtype: object

(9,)

tconst            tt1182011
titleType         tvEpisode
primaryTitle       The Duel
originalTitle      The Duel
isAdult                   0
startYear              1958
endYear                  \N
runtimeMinutes           \N
genres              Western
Name: 2002294, dtype: object

(9,)

tconst                tt11820120
titleType              tvEpisode
primaryTitle      Episode #1.724
originalTitle     Episode #1.724
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002295, dtype: object

(9,)

tconst                 tt11820122
titleType               tvEpisode
primaryTitle      I Feel So Naked
originalTitle     I Feel So Naked
isAdult                         1
startYear                    2010
endYear                        \N
runtimeMinutes                 20
genres                      Adult
Name: 2002296, dtype: object

(9,)

tconst                tt11820124
titleType              tvEpisode
primaryTitle      Episode #1.725
originalTitle     Episode #1.725
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002297, dtype: object

(9,)

tconst                tt11820126
titleType              tvEpisode
primaryTitle      Episode #1.726
originalTitle     Episode #1.726
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002298, dtype: object

(9,)

tconst                tt11820128
titleType              tvEpisode
primaryTitle      Episode #1.727
originalTitle     Episode #1.727
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002299, dtype: object

(9,)

tconst                         tt1182012
titleType                      tvEpisode
primaryTitle      The Eight-for-Five Men
originalTitle     The Eight-for-Five Men
isAdult                                0
startYear                           1958
endYear                               \N
runtimeMinutes                        \N
genres                           Western
Name: 2002300, dtype: object

(9,)

tconst                tt11820130
titleType              tvEpisode
primaryTitle      Episode #1.728
originalTitle     Episode #1.728
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002301, dtype: object

(9,)

tconst                tt11820132
titleType              tvEpisode
primaryTitle      Episode #1.729
originalTitle     Episode #1.729
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002302, dtype: object

(9,)

tconst                tt11820134
titleType              tvEpisode
primaryTitle      Episode #1.730
originalTitle     Episode #1.730
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002303, dtype: object

(9,)

tconst                tt11820136
titleType              tvEpisode
primaryTitle      Friend and Foe
originalTitle     Friend and Foe
isAdult                        0
startYear                   2011
endYear                       \N
runtimeMinutes                30
genres                    Action
Name: 2002304, dtype: object

(9,)

tconst                tt11820138
titleType              tvEpisode
primaryTitle      Episode #1.731
originalTitle     Episode #1.731
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002305, dtype: object

(9,)

tconst                  tt1182013
titleType               tvEpisode
primaryTitle      The Gatling Gun
originalTitle     The Gatling Gun
isAdult                         0
startYear                    1957
endYear                        \N
runtimeMinutes                 30
genres                    Western
Name: 2002306, dtype: object

(9,)

tconst                tt11820140
titleType              tvEpisode
primaryTitle      Episode #1.732
originalTitle     Episode #1.732
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002307, dtype: object

(9,)

tconst                tt11820142
titleType              tvEpisode
primaryTitle      Episode #1.734
originalTitle     Episode #1.734
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002308, dtype: object

(9,)

tconst                                    tt11820144
titleType                                    tvMovie
primaryTitle      Crni sneg: Balada o jednom milionu
originalTitle     Crni sneg: Balada o jednom milionu
isAdult                                            0
startYear                                       1966
endYear                                           \N
runtimeMinutes                                    \N
genres                                        Comedy
Name: 2002309, dtype: object

(9,)

tconst                tt11820146
titleType              tvEpisode
primaryTitle      Episode #1.733
originalTitle     Episode #1.733
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002310, dtype: object

(9,)

tconst                tt11820148
titleType              tvEpisode
primaryTitle      Episode #1.735
originalTitle     Episode #1.735
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002311, dtype: object

(9,)

tconst            tt1182014
titleType         tvEpisode
primaryTitle       The Gift
originalTitle      The Gift
isAdult                   0
startYear              1957
endYear                  \N
runtimeMinutes           30
genres              Western
Name: 2002312, dtype: object

(9,)

tconst                tt11820150
titleType              tvEpisode
primaryTitle      Episode #1.736
originalTitle     Episode #1.736
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002313, dtype: object

(9,)

tconst                tt11820152
titleType              tvEpisode
primaryTitle      Episode #1.737
originalTitle     Episode #1.737
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002314, dtype: object

(9,)

tconst                tt11820154
titleType              tvEpisode
primaryTitle      Episode #1.738
originalTitle     Episode #1.738
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002315, dtype: object

(9,)

tconst                tt11820156
titleType              tvEpisode
primaryTitle      Episode #1.739
originalTitle     Episode #1.739
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002316, dtype: object

(9,)

tconst                tt11820158
titleType              tvEpisode
primaryTitle      Episode #1.740
originalTitle     Episode #1.740
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002317, dtype: object

(9,)

tconst                   tt1182015
titleType                tvEpisode
primaryTitle      The Indian Scout
originalTitle     The Indian Scout
isAdult                          0
startYear                     1958
endYear                         \N
runtimeMinutes                  \N
genres                     Western
Name: 2002318, dtype: object

(9,)

tconst                                tt11820160
titleType                              tvEpisode
primaryTitle      Shannon Secure Sweater Bondage
originalTitle     Shannon Secure Sweater Bondage
isAdult                                        1
startYear                                   2010
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2002319, dtype: object

(9,)

tconst                tt11820162
titleType              tvEpisode
primaryTitle      Episode #1.941
originalTitle     Episode #1.941
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002320, dtype: object

(9,)

tconst                tt11820164
titleType              tvEpisode
primaryTitle      Episode #1.942
originalTitle     Episode #1.942
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002321, dtype: object

(9,)

tconst                tt11820166
titleType              tvEpisode
primaryTitle      Episode #1.943
originalTitle     Episode #1.943
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002322, dtype: object

(9,)

tconst                tt11820168
titleType              tvEpisode
primaryTitle      Episode #1.944
originalTitle     Episode #1.944
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002323, dtype: object

(9,)

tconst                 tt1182016
titleType              tvEpisode
primaryTitle      The Politician
originalTitle     The Politician
isAdult                        0
startYear                   1958
endYear                       \N
runtimeMinutes                \N
genres                   Western
Name: 2002324, dtype: object

(9,)

tconst                tt11820170
titleType              tvEpisode
primaryTitle      Episode #1.946
originalTitle     Episode #1.946
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002325, dtype: object

(9,)

tconst                tt11820172
titleType              tvEpisode
primaryTitle      Episode #1.945
originalTitle     Episode #1.945
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002326, dtype: object

(9,)

tconst                tt11820174
titleType              tvEpisode
primaryTitle      Episode #1.947
originalTitle     Episode #1.947
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002327, dtype: object

(9,)

tconst                tt11820176
titleType              tvEpisode
primaryTitle      Totally Warped
originalTitle     Totally Warped
isAdult                        0
startYear                   2011
endYear                       \N
runtimeMinutes                30
genres                    Action
Name: 2002328, dtype: object

(9,)

tconst                tt11820178
titleType              tvEpisode
primaryTitle      Episode #1.948
originalTitle     Episode #1.948
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002329, dtype: object

(9,)

tconst                                     tt1182017
titleType                                  tvEpisode
primaryTitle      The Strange Death of Trooper Jones
originalTitle     The Strange Death of Trooper Jones
isAdult                                            0
startYear                                       1958
endYear                                           \N
runtimeMinutes                                    30
genres                                       Western
Name: 2002330, dtype: object

(9,)

tconst                tt11820180
titleType              tvEpisode
primaryTitle      Episode #1.949
originalTitle     Episode #1.949
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002331, dtype: object

(9,)

tconst            tt11820182
titleType          tvEpisode
primaryTitle      Kim Marvel
originalTitle     Kim Marvel
isAdult                    1
startYear               2010
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2002332, dtype: object

(9,)

tconst                             tt11820184
titleType                           tvEpisode
primaryTitle         I Shouldn't of Done This
originalTitle        I Shouldn't of Done This
isAdult                                     0
startYear                                2017
endYear                                    \N
runtimeMinutes                             \N
genres            Adventure,Documentary,Drama
Name: 2002333, dtype: object

(9,)

tconst                tt11820186
titleType              tvEpisode
primaryTitle      Episode #1.950
originalTitle     Episode #1.950
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002334, dtype: object

(9,)

tconst                tt11820188
titleType              tvEpisode
primaryTitle      Episode #1.951
originalTitle     Episode #1.951
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002335, dtype: object

(9,)

tconst                             tt1182018
titleType                          tvEpisode
primaryTitle      Episode dated 1 March 1983
originalTitle     Episode dated 1 March 1983
isAdult                                    0
startYear                               1983
endYear                                   \N
runtimeMinutes                            \N
genres                                  News
Name: 2002336, dtype: object

(9,)

tconst                tt11820190
titleType              tvEpisode
primaryTitle      Episode #1.953
originalTitle     Episode #1.953
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002337, dtype: object

(9,)

tconst                tt11820192
titleType              tvEpisode
primaryTitle      Episode #1.952
originalTitle     Episode #1.952
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002338, dtype: object

(9,)

tconst                tt11820194
titleType              tvEpisode
primaryTitle      Episode #1.954
originalTitle     Episode #1.954
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002339, dtype: object

(9,)

tconst                        tt11820196
titleType                      tvEpisode
primaryTitle      Wendy - Bound Outdoors
originalTitle     Wendy - Bound Outdoors
isAdult                                1
startYear                           2010
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2002340, dtype: object

(9,)

tconst                tt11820198
titleType              tvEpisode
primaryTitle      Episode #1.955
originalTitle     Episode #1.955
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002341, dtype: object

(9,)

tconst                              tt1182019
titleType                           tvEpisode
primaryTitle      Episode dated 15 March 1984
originalTitle     Episode dated 15 March 1984
isAdult                                     0
startYear                                1984
endYear                                    \N
runtimeMinutes                             \N
genres                                   News
Name: 2002342, dtype: object

(9,)

tconst                tt11820200
titleType              tvEpisode
primaryTitle      Episode #1.957
originalTitle     Episode #1.957
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002343, dtype: object

(9,)

tconst                tt11820202
titleType              tvEpisode
primaryTitle      Episode #1.956
originalTitle     Episode #1.956
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002344, dtype: object

(9,)

tconst                tt11820204
titleType              tvEpisode
primaryTitle      Episode #1.958
originalTitle     Episode #1.958
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002345, dtype: object

(9,)

tconst                                 tt11820206
titleType                               tvEpisode
primaryTitle      Aryana Sayeed- an Afghan singer
originalTitle     Aryana Sayeed- an Afghan singer
isAdult                                         0
startYear                                    2014
endYear                                        \N
runtimeMinutes                                 \N
genres                                 Reality-TV
Name: 2002346, dtype: object

(9,)

tconst                tt11820208
titleType              tvEpisode
primaryTitle      Episode #1.959
originalTitle     Episode #1.959
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002347, dtype: object

(9,)

tconst                              tt1182020
titleType                           tvEpisode
primaryTitle      Episode dated 22 March 1984
originalTitle     Episode dated 22 March 1984
isAdult                                     0
startYear                                1984
endYear                                    \N
runtimeMinutes                             \N
genres                                   News
Name: 2002348, dtype: object

(9,)

tconst                tt11820212
titleType              tvEpisode
primaryTitle      Episode #1.960
originalTitle     Episode #1.960
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002349, dtype: object

(9,)

tconst                tt11820214
titleType              tvEpisode
primaryTitle      Hidden Powers!
originalTitle     Hidden Powers!
isAdult                        0
startYear                   2011
endYear                       \N
runtimeMinutes                30
genres                    Action
Name: 2002350, dtype: object

(9,)

tconst                                tt11820216
titleType                              tvEpisode
primaryTitle      Sandra's Flying Mummification!
originalTitle     Sandra's Flying Mummification!
isAdult                                        1
startYear                                   2010
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2002351, dtype: object

(9,)

tconst                             tt11820218
titleType                           tvEpisode
primaryTitle      POPULAR CONSPIRACY THEORIES
originalTitle     POPULAR CONSPIRACY THEORIES
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres            Adventure,Documentary,Drama
Name: 2002352, dtype: object

(9,)

tconst                                tt1182021
titleType                             tvEpisode
primaryTitle      Episode dated 20 October 1986
originalTitle     Episode dated 20 October 1986
isAdult                                       0
startYear                                  1986
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2002353, dtype: object

(9,)

tconst                                                   tt11820222
titleType                                                 tvEpisode
primaryTitle      Petite blondie Natasha Teen XXX ass fucked in ...
originalTitle     Petite blondie Natasha Teen XXX ass fucked in ...
isAdult                                                           1
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002354, dtype: object

(9,)

tconst               tt11820224
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002355, dtype: object

(9,)

tconst                tt11820226
titleType              tvEpisode
primaryTitle      Layla Mercedes
originalTitle     Layla Mercedes
isAdult                        1
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2002356, dtype: object

(9,)

tconst               tt11820228
titleType             tvEpisode
primaryTitle      Episode #1.42
originalTitle     Episode #1.42
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002357, dtype: object

(9,)

tconst                             tt1182022
titleType                          tvEpisode
primaryTitle      Episode dated 4 April 1990
originalTitle     Episode dated 4 April 1990
isAdult                                    0
startYear                               1990
endYear                                   \N
runtimeMinutes                            \N
genres                        News,Talk-Show
Name: 2002358, dtype: object

(9,)

tconst                   tt11820230
titleType                     short
primaryTitle                  Oeste
originalTitle                 Oeste
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   38
genres            Documentary,Short
Name: 2002359, dtype: object

(9,)

tconst               tt11820232
titleType             tvEpisode
primaryTitle      Episode #1.43
originalTitle     Episode #1.43
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002360, dtype: object

(9,)

tconst               tt11820234
titleType             tvEpisode
primaryTitle      Episode #1.44
originalTitle     Episode #1.44
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002361, dtype: object

(9,)

tconst               tt11820236
titleType             tvEpisode
primaryTitle      Episode #1.45
originalTitle     Episode #1.45
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002362, dtype: object

(9,)

tconst               tt11820238
titleType             tvEpisode
primaryTitle      Episode #1.46
originalTitle     Episode #1.46
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002363, dtype: object

(9,)

tconst                tt1182023
titleType             tvEpisode
primaryTitle      Before a Fall
originalTitle     Before a Fall
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002364, dtype: object

(9,)

tconst                 tt11820240
titleType               tvEpisode
primaryTitle      Episode #15.127
originalTitle     Episode #15.127
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 60
genres            Sport,Talk-Show
Name: 2002365, dtype: object

(9,)

tconst               tt11820242
titleType             tvEpisode
primaryTitle      Episode #1.47
originalTitle     Episode #1.47
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002366, dtype: object

(9,)

tconst               tt11820244
titleType             tvEpisode
primaryTitle      Episode #1.48
originalTitle     Episode #1.48
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002367, dtype: object

(9,)

tconst                 tt11820246
titleType               tvEpisode
primaryTitle      Episode #15.128
originalTitle     Episode #15.128
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 60
genres            Sport,Talk-Show
Name: 2002368, dtype: object

(9,)

tconst                                 tt11820248
titleType                               tvEpisode
primaryTitle      Miss Sasha and the BIG ballgag!
originalTitle     Miss Sasha and the BIG ballgag!
isAdult                                         1
startYear                                    2010
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2002369, dtype: object

(9,)

tconst            tt1182024
titleType         tvEpisode
primaryTitle      Alexandra
originalTitle     Alexandra
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                Crime
Name: 2002370, dtype: object

(9,)

tconst               tt11820250
titleType             tvEpisode
primaryTitle      Episode #1.49
originalTitle     Episode #1.49
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002371, dtype: object

(9,)

tconst               tt11820254
titleType             tvEpisode
primaryTitle      Episode #1.50
originalTitle     Episode #1.50
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002372, dtype: object

(9,)

tconst               tt11820256
titleType             tvEpisode
primaryTitle      Episode #1.51
originalTitle     Episode #1.51
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002373, dtype: object

(9,)

tconst                       tt11820258
titleType                         short
primaryTitle      Estas Mãos São Minhas
originalTitle     Estas Mãos São Minhas
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                        8
genres                Documentary,Short
Name: 2002374, dtype: object

(9,)

tconst            tt1182025
titleType         tvEpisode
primaryTitle       Frédéric
originalTitle      Frédéric
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                Crime
Name: 2002375, dtype: object

(9,)

tconst                      tt11820260
titleType                    tvEpisode
primaryTitle      The Footjob Audition
originalTitle     The Footjob Audition
isAdult                              1
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2002376, dtype: object

(9,)

tconst               tt11820262
titleType             tvEpisode
primaryTitle      Episode #1.52
originalTitle     Episode #1.52
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002377, dtype: object

(9,)

tconst                 tt11820264
titleType               tvEpisode
primaryTitle      Episode #15.129
originalTitle     Episode #15.129
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 60
genres            Sport,Talk-Show
Name: 2002378, dtype: object

(9,)

tconst                             tt11820266
titleType                           tvEpisode
primaryTitle      I PLAYED THE OUIJA BOARD...
originalTitle     I PLAYED THE OUIJA BOARD...
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres            Adventure,Documentary,Drama
Name: 2002379, dtype: object

(9,)

tconst               tt11820268
titleType             tvEpisode
primaryTitle      Episode #1.54
originalTitle     Episode #1.54
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002380, dtype: object

(9,)

tconst                          tt1182026
titleType                       tvEpisode
primaryTitle      Oste ascendente vergine
originalTitle     Oste ascendente vergine
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                Comedy,Drama,Family
Name: 2002381, dtype: object

(9,)

tconst                      tt11820270
titleType                    tvEpisode
primaryTitle      An Ocean of Trouble!
originalTitle     An Ocean of Trouble!
isAdult                              0
startYear                         2011
endYear                             \N
runtimeMinutes                      30
genres                          Action
Name: 2002382, dtype: object

(9,)

tconst               tt11820272
titleType             tvEpisode
primaryTitle      Episode #1.55
originalTitle     Episode #1.55
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002383, dtype: object

(9,)

tconst               tt11820274
titleType             tvEpisode
primaryTitle      Episode #1.53
originalTitle     Episode #1.53
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002384, dtype: object

(9,)

tconst               tt11820276
titleType             tvEpisode
primaryTitle      Episode #1.56
originalTitle     Episode #1.56
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002385, dtype: object

(9,)

tconst               tt11820278
titleType             tvEpisode
primaryTitle      Episode #1.57
originalTitle     Episode #1.57
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002386, dtype: object

(9,)

tconst                          tt1182027
titleType                       tvEpisode
primaryTitle      Se la bomba non scoppia
originalTitle     Se la bomba non scoppia
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                Comedy,Drama,Family
Name: 2002387, dtype: object

(9,)

tconst                    tt11820280
titleType                  tvEpisode
primaryTitle      Wendy - Bound Maid
originalTitle     Wendy - Bound Maid
isAdult                            1
startYear                       2010
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2002388, dtype: object

(9,)

tconst             tt11820282
titleType            tvSeries
primaryTitle      Zhong Cheng
originalTitle     Zhong Cheng
isAdult                     0
startYear                2001
endYear                  2001
runtimeMinutes             \N
genres                  Drama
Name: 2002389, dtype: object

(9,)

tconst                 tt11820284
titleType               tvEpisode
primaryTitle      Episode #15.130
originalTitle     Episode #15.130
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 60
genres            Sport,Talk-Show
Name: 2002390, dtype: object

(9,)

tconst               tt11820286
titleType             tvEpisode
primaryTitle      Episode #1.58
originalTitle     Episode #1.58
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002391, dtype: object

(9,)

tconst               tt11820288
titleType             tvEpisode
primaryTitle      Episode #1.59
originalTitle     Episode #1.59
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002392, dtype: object

(9,)

tconst               tt1182028
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 1975
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2002393, dtype: object

(9,)

tconst                 tt11820290
titleType               tvEpisode
primaryTitle      Episode #15.131
originalTitle     Episode #15.131
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 60
genres            Sport,Talk-Show
Name: 2002394, dtype: object

(9,)

tconst               tt11820292
titleType             tvEpisode
primaryTitle      Episode #1.60
originalTitle     Episode #1.60
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002395, dtype: object

(9,)

tconst               tt11820294
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002396, dtype: object

(9,)

tconst                              tt11820296
titleType                            tvEpisode
primaryTitle      Sandra, Classic car Bondage!
originalTitle     Sandra, Classic car Bondage!
isAdult                                      1
startYear                                 2010
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2002397, dtype: object

(9,)

tconst                                                   tt11820298
titleType                                                 tvEpisode
primaryTitle      Down on the Farm: Conversations with Legendary...
originalTitle     Down on the Farm: Conversations with Legendary...
isAdult                                                           0
startYear                                                      2011
endYear                                                          \N
runtimeMinutes                                                   55
genres                                                  Documentary
Name: 2002398, dtype: object

(9,)

tconst                                tt1182029
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2008
originalTitle     Episode dated 4 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2002399, dtype: object

(9,)

tconst                               tt11820300
titleType                             tvEpisode
primaryTitle      Episode dated 3 February 2020
originalTitle     Episode dated 3 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002400, dtype: object

(9,)

tconst            tt11820302
titleType          tvEpisode
primaryTitle          Mai Ly
originalTitle         Mai Ly
isAdult                    1
startYear               2010
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2002401, dtype: object

(9,)

tconst               tt11820304
titleType             tvEpisode
primaryTitle      Episode #1.42
originalTitle     Episode #1.42
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002402, dtype: object

(9,)

tconst               tt11820306
titleType             tvEpisode
primaryTitle      Episode #1.43
originalTitle     Episode #1.43
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002403, dtype: object

(9,)

tconst                               tt11820308
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2020
originalTitle     Episode dated 4 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               60
genres                                       \N
Name: 2002404, dtype: object

(9,)

tconst                   tt1182030
titleType                tvEpisode
primaryTitle          Episode #2.6
originalTitle         Episode #2.6
isAdult                          0
startYear                     1998
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2002405, dtype: object

(9,)

tconst                               tt11820310
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2020
originalTitle     Episode dated 5 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002406, dtype: object

(9,)

tconst               tt11820312
titleType             tvEpisode
primaryTitle      Episode #1.44
originalTitle     Episode #1.44
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002407, dtype: object

(9,)

tconst               tt11820314
titleType             tvEpisode
primaryTitle      Episode #1.46
originalTitle     Episode #1.46
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002408, dtype: object

(9,)

tconst               tt11820316
titleType             tvEpisode
primaryTitle      Episode #1.45
originalTitle     Episode #1.45
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002409, dtype: object

(9,)

tconst                                 tt11820318
titleType                               tvEpisode
primaryTitle      The Dumbest Idea I've Ever Made
originalTitle     The Dumbest Idea I've Ever Made
isAdult                                         0
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                Adventure,Documentary,Drama
Name: 2002410, dtype: object

(9,)

tconst                                     tt1182031
titleType                                  tvEpisode
primaryTitle      Butch Cassidy and the Sundance Kid
originalTitle     Butch Cassidy and the Sundance Kid
isAdult                                            0
startYear                                       2002
endYear                                           \N
runtimeMinutes                                    \N
genres                           Documentary,History
Name: 2002411, dtype: object

(9,)

tconst               tt11820320
titleType             tvEpisode
primaryTitle      Episode #1.47
originalTitle     Episode #1.47
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002412, dtype: object

(9,)

tconst                            tt11820322
titleType                          tvEpisode
primaryTitle      Wendy - Spreader Bar Bound
originalTitle     Wendy - Spreader Bar Bound
isAdult                                    1
startYear                               2010
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2002413, dtype: object

(9,)

tconst               tt11820324
titleType             tvEpisode
primaryTitle      Episode #1.48
originalTitle     Episode #1.48
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002414, dtype: object

(9,)

tconst                               tt11820326
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2020
originalTitle     Episode dated 6 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002415, dtype: object

(9,)

tconst               tt11820328
titleType             tvEpisode
primaryTitle      Episode #1.49
originalTitle     Episode #1.49
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002416, dtype: object

(9,)

tconst                         tt1182032
titleType                      tvEpisode
primaryTitle                Episode #7.5
originalTitle               Episode #7.5
isAdult                                0
startYear                           2007
endYear                               \N
runtimeMinutes                        \N
genres            Family,Game-Show,Music
Name: 2002417, dtype: object

(9,)

tconst               tt11820330
titleType             tvEpisode
primaryTitle      Episode #1.50
originalTitle     Episode #1.50
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002418, dtype: object

(9,)

tconst               tt11820332
titleType             tvEpisode
primaryTitle      Episode #1.51
originalTitle     Episode #1.51
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002419, dtype: object

(9,)

tconst                               tt11820334
titleType                             tvEpisode
primaryTitle      Sandra's Pantyhose Encasement
originalTitle     Sandra's Pantyhose Encasement
isAdult                                       1
startYear                                  2010
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2002420, dtype: object

(9,)

tconst                               tt11820336
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2020
originalTitle     Episode dated 7 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002421, dtype: object

(9,)

tconst               tt11820338
titleType             tvEpisode
primaryTitle      Episode #1.52
originalTitle     Episode #1.52
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002422, dtype: object

(9,)

tconst                         tt1182033
titleType                      tvEpisode
primaryTitle                Episode #7.6
originalTitle               Episode #7.6
isAdult                                0
startYear                           2007
endYear                               \N
runtimeMinutes                        \N
genres            Family,Game-Show,Music
Name: 2002423, dtype: object

(9,)

tconst               tt11820340
titleType             tvEpisode
primaryTitle      Episode #1.54
originalTitle     Episode #1.54
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002424, dtype: object

(9,)

tconst               tt11820342
titleType             tvEpisode
primaryTitle      Episode #1.53
originalTitle     Episode #1.53
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002425, dtype: object

(9,)

tconst               tt11820344
titleType             tvEpisode
primaryTitle      Episode #1.55
originalTitle     Episode #1.55
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002426, dtype: object

(9,)

tconst               tt11820346
titleType             tvEpisode
primaryTitle      Episode #1.57
originalTitle     Episode #1.57
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002427, dtype: object

(9,)

tconst               tt11820348
titleType             tvEpisode
primaryTitle      Episode #1.56
originalTitle     Episode #1.56
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002428, dtype: object

(9,)

tconst                  tt1182034
titleType               tvEpisode
primaryTitle      Episode #1.9600
originalTitle     Episode #1.9600
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2002429, dtype: object

(9,)

tconst               tt11820350
titleType             tvEpisode
primaryTitle      Episode #1.58
originalTitle     Episode #1.58
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002430, dtype: object

(9,)

tconst               tt11820352
titleType             tvEpisode
primaryTitle      Episode #1.59
originalTitle     Episode #1.59
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002431, dtype: object

(9,)

tconst            tt11820354
titleType          tvEpisode
primaryTitle         La JAPP
originalTitle        La JAPP
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2002432, dtype: object

(9,)

tconst                             tt11820356
titleType                           tvEpisode
primaryTitle             We've Made a Mistake
originalTitle            We've Made a Mistake
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres            Adventure,Documentary,Drama
Name: 2002433, dtype: object

(9,)

tconst               tt11820358
titleType             tvEpisode
primaryTitle      Episode #1.60
originalTitle     Episode #1.60
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002434, dtype: object

(9,)

tconst                tt1182035
titleType             tvEpisode
primaryTitle      Episode #15.6
originalTitle     Episode #15.6
isAdult                       0
startYear                  1987
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2002435, dtype: object

(9,)

tconst                 tt11820360
titleType               tvEpisode
primaryTitle      Nikki Sebastian
originalTitle     Nikki Sebastian
isAdult                         1
startYear                    2010
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2002436, dtype: object

(9,)

tconst               tt11820362
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002437, dtype: object

(9,)

tconst               tt11820364
titleType             tvEpisode
primaryTitle      Episode #1.42
originalTitle     Episode #1.42
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002438, dtype: object

(9,)

tconst               tt11820366
titleType             tvEpisode
primaryTitle      Episode #1.43
originalTitle     Episode #1.43
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002439, dtype: object

(9,)

tconst               tt11820368
titleType             tvEpisode
primaryTitle      Episode #1.44
originalTitle     Episode #1.44
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002440, dtype: object

(9,)

tconst                tt1182036
titleType             tvEpisode
primaryTitle      The Job Ahead
originalTitle     The Job Ahead
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002441, dtype: object

(9,)

tconst               tt11820370
titleType             tvEpisode
primaryTitle      Episode #1.46
originalTitle     Episode #1.46
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002442, dtype: object

(9,)

tconst               tt11820372
titleType             tvEpisode
primaryTitle      Episode #1.45
originalTitle     Episode #1.45
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002443, dtype: object

(9,)

tconst               tt11820374
titleType             tvEpisode
primaryTitle      Episode #1.47
originalTitle     Episode #1.47
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002444, dtype: object

(9,)

tconst               tt11820376
titleType             tvEpisode
primaryTitle      Episode #1.49
originalTitle     Episode #1.49
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002445, dtype: object

(9,)

tconst               tt11820378
titleType             tvEpisode
primaryTitle      Episode #1.48
originalTitle     Episode #1.48
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002446, dtype: object

(9,)

tconst                 tt1182037
titleType              tvEpisode
primaryTitle      Sound and Fury
originalTitle     Sound and Fury
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002447, dtype: object

(9,)

tconst               tt11820380
titleType             tvEpisode
primaryTitle      Episode #1.50
originalTitle     Episode #1.50
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002448, dtype: object

(9,)

tconst            tt11820384
titleType              video
primaryTitle        VRTm-483
originalTitle       VRTm-483
isAdult                    1
startYear               2020
endYear                   \N
runtimeMinutes           120
genres                 Adult
Name: 2002449, dtype: object

(9,)

tconst               tt11820386
titleType             tvEpisode
primaryTitle      Episode #1.51
originalTitle     Episode #1.51
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002450, dtype: object

(9,)

tconst               tt11820388
titleType             tvEpisode
primaryTitle      Episode #1.52
originalTitle     Episode #1.52
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002451, dtype: object

(9,)

tconst                             tt1182038
titleType                          tvEpisode
primaryTitle                  Get Rid of It!
originalTitle                 Get Rid of It!
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            \N
genres            Drama,Reality-TV,Talk-Show
Name: 2002452, dtype: object

(9,)

tconst               tt11820390
titleType             tvEpisode
primaryTitle      Episode #1.53
originalTitle     Episode #1.53
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002453, dtype: object

(9,)

tconst               tt11820392
titleType             tvEpisode
primaryTitle      Episode #1.54
originalTitle     Episode #1.54
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002454, dtype: object

(9,)

tconst               tt11820394
titleType             tvEpisode
primaryTitle      Hogtied Wendy
originalTitle     Hogtied Wendy
isAdult                       1
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2002455, dtype: object

(9,)

tconst               tt11820396
titleType             tvEpisode
primaryTitle      Episode #1.55
originalTitle     Episode #1.55
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002456, dtype: object

(9,)

tconst                             tt11820398
titleType                           tvEpisode
primaryTitle       Conspiracy Theories Teaser
originalTitle      Conspiracy Theories Teaser
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres            Adventure,Documentary,Drama
Name: 2002457, dtype: object

(9,)

tconst                             tt1182039
titleType                          tvEpisode
primaryTitle               Internet Mistakes
originalTitle              Internet Mistakes
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            \N
genres            Drama,Reality-TV,Talk-Show
Name: 2002458, dtype: object

(9,)

tconst               tt11820400
titleType             tvEpisode
primaryTitle      Episode #1.56
originalTitle     Episode #1.56
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002459, dtype: object

(9,)

tconst               tt11820402
titleType             tvEpisode
primaryTitle      Episode #1.57
originalTitle     Episode #1.57
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002460, dtype: object

(9,)

tconst               tt11820404
titleType             tvEpisode
primaryTitle      Episode #1.58
originalTitle     Episode #1.58
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002461, dtype: object

(9,)

tconst                                   tt11820406
titleType                                 tvEpisode
primaryTitle      Bernie Now Leading Every New Poll
originalTitle     Bernie Now Leading Every New Poll
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                               News,Talk-Show
Name: 2002462, dtype: object

(9,)

tconst                   tt11820408
titleType                 tvEpisode
primaryTitle      Am Boden zerstört
originalTitle     Am Boden zerstört
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                Drama,Romance
Name: 2002463, dtype: object

(9,)

tconst                                   tt1182040
titleType                                tvEpisode
primaryTitle      My Big Fat Spoiled Family Member
originalTitle     My Big Fat Spoiled Family Member
isAdult                                          0
startYear                                     2008
endYear                                         \N
runtimeMinutes                                  \N
genres                  Drama,Reality-TV,Talk-Show
Name: 2002464, dtype: object

(9,)

tconst               tt11820410
titleType             tvEpisode
primaryTitle      Episode #1.59
originalTitle     Episode #1.59
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002465, dtype: object

(9,)

tconst                  tt11820412
titleType                tvEpisode
primaryTitle      My Job Interview
originalTitle     My Job Interview
isAdult                          1
startYear                     2010
endYear                         \N
runtimeMinutes                  20
genres                       Adult
Name: 2002466, dtype: object

(9,)

tconst                            tt11820414
titleType                          tvEpisode
primaryTitle      In the Kitchen with Sandra
originalTitle     In the Kitchen with Sandra
isAdult                                    1
startYear                               2010
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2002467, dtype: object

(9,)

tconst               tt11820416
titleType             tvEpisode
primaryTitle      Episode #1.60
originalTitle     Episode #1.60
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002468, dtype: object

(9,)

tconst               tt11820418
titleType             tvEpisode
primaryTitle              Kasal
originalTitle             Kasal
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2002469, dtype: object

(9,)

tconst                             tt1182041
titleType                          tvEpisode
primaryTitle          New Year's Resolutions
originalTitle         New Year's Resolutions
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            \N
genres            Drama,Reality-TV,Talk-Show
Name: 2002470, dtype: object

(9,)

tconst                      tt11820420
titleType                    tvEpisode
primaryTitle      Natasha Teen Casting
originalTitle     Natasha Teen Casting
isAdult                              1
startYear                         2018
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2002471, dtype: object

(9,)

tconst               tt11820422
titleType             tvEpisode
primaryTitle      Opposite Day!
originalTitle     Opposite Day!
isAdult                       0
startYear                  2011
endYear                      \N
runtimeMinutes               30
genres                   Action
Name: 2002472, dtype: object

(9,)

tconst                                        tt11820424
titleType                                      tvEpisode
primaryTitle      The World Changing Conspiracy Theories
originalTitle     The World Changing Conspiracy Theories
isAdult                                                0
startYear                                           2019
endYear                                               \N
runtimeMinutes                                        \N
genres                       Adventure,Documentary,Drama
Name: 2002473, dtype: object

(9,)

tconst              tt11820426
titleType            tvEpisode
primaryTitle      Tabita Bound
originalTitle     Tabita Bound
isAdult                      1
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2002474, dtype: object

(9,)

tconst                                tt11820428
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                      News,Sport,Talk-Show
Name: 2002475, dtype: object

(9,)

tconst                             tt1182042
titleType                          tvEpisode
primaryTitle          The Baggy Pants Debate
originalTitle         The Baggy Pants Debate
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            \N
genres            Drama,Reality-TV,Talk-Show
Name: 2002476, dtype: object

(9,)

tconst                                         tt11820430
titleType                                       tvEpisode
primaryTitle      Sandra & Misty - Snatched Secretarties!
originalTitle     Sandra & Misty - Snatched Secretarties!
isAdult                                                 1
startYear                                            2010
endYear                                                \N
runtimeMinutes                                         \N
genres                                              Adult
Name: 2002477, dtype: object

(9,)

tconst                tt11820432
titleType              tvEpisode
primaryTitle      Hannah's Back!
originalTitle     Hannah's Back!
isAdult                        0
startYear                   2011
endYear                       \N
runtimeMinutes                30
genres                    Action
Name: 2002478, dtype: object

(9,)

tconst                                               tt11820434
titleType                                             tvEpisode
primaryTitle      The World Changing Conspiracy Theories Part 3
originalTitle     The World Changing Conspiracy Theories Part 3
isAdult                                                       0
startYear                                                  2019
endYear                                                      \N
runtimeMinutes                                               \N
genres                              Adventure,Documentary,Drama
Name: 2002479, dtype: object

(9,)

tconst              tt11820436
titleType            tvEpisode
primaryTitle      Hogtied Anna
originalTitle     Hogtied Anna
isAdult                      1
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2002480, dtype: object

(9,)

tconst               tt11820438
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002481, dtype: object

(9,)

tconst                        tt1182043
titleType                     tvEpisode
primaryTitle                  Bob Fosse
originalTitle                 Bob Fosse
isAdult                               0
startYear                          1999
endYear                              \N
runtimeMinutes                       \N
genres            Biography,Documentary
Name: 2002482, dtype: object

(9,)

tconst                tt11820440
titleType                  short
primaryTitle      Into the Bleak
originalTitle     Into the Bleak
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                 3
genres               Drama,Short
Name: 2002483, dtype: object

(9,)

tconst               tt11820442
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002484, dtype: object

(9,)

tconst               tt11820444
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002485, dtype: object

(9,)

tconst                           tt11820446
titleType                         tvEpisode
primaryTitle      Shannon is VERY Ticklish!
originalTitle     Shannon is VERY Ticklish!
isAdult                                   1
startYear                              2010
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2002486, dtype: object

(9,)

tconst               tt11820448
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002487, dtype: object

(9,)

tconst                                tt1182044
titleType                             tvEpisode
primaryTitle      Episode dated 26 January 2006
originalTitle     Episode dated 26 January 2006
isAdult                                       0
startYear                                  2006
endYear                                      \N
runtimeMinutes                               \N
genres                      Crime,Drama,Romance
Name: 2002488, dtype: object

(9,)

tconst                               tt11820450
titleType                             tvEpisode
primaryTitle      Episode dated 3 February 2020
originalTitle     Episode dated 3 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2002489, dtype: object

(9,)

tconst               tt11820452
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002490, dtype: object

(9,)

tconst                               tt11820454
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2020
originalTitle     Episode dated 6 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2002491, dtype: object

(9,)

tconst                                                tt11820456
titleType                                           tvMiniSeries
primaryTitle      Renovation Realities: Dale Jr. & Amy Earnhardt
originalTitle     Renovation Realities: Dale Jr. & Amy Earnhardt
isAdult                                                        0
startYear                                                   2018
endYear                                                     2018
runtimeMinutes                                                \N
genres                                               Documentary
Name: 2002492, dtype: object

(9,)

tconst                                    tt11820458
titleType                                  tvEpisode
primaryTitle      Mutli-layered Gag - all On Screen.
originalTitle     Mutli-layered Gag - all On Screen.
isAdult                                            1
startYear                                       2010
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2002493, dtype: object

(9,)

tconst                                tt1182045
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                      Crime,Drama,Romance
Name: 2002494, dtype: object

(9,)

tconst                               tt11820460
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2020
originalTitle     Episode dated 7 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2002495, dtype: object

(9,)

tconst            tt11820462
titleType          tvEpisode
primaryTitle       Fly, Rai!
originalTitle      Fly, Rai!
isAdult                    0
startYear               2011
endYear                   \N
runtimeMinutes            30
genres                Action
Name: 2002496, dtype: object

(9,)

tconst                               tt11820464
titleType                             tvEpisode
primaryTitle      Episode dated 3 February 2020
originalTitle     Episode dated 3 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002497, dtype: object

(9,)

tconst             tt11820466
titleType           tvEpisode
primaryTitle      Angela Ryan
originalTitle     Angela Ryan
isAdult                     1
startYear                2010
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2002498, dtype: object

(9,)

tconst                 tt11820468
titleType               tvEpisode
primaryTitle      Gonzalo Quesada
originalTitle     Gonzalo Quesada
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2002499, dtype: object

(9,)

tconst                tt1182046
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  1993
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2002500, dtype: object

(9,)

tconst                               tt11820470
titleType                             tvEpisode
primaryTitle      The Dark Side of Conspiracies
originalTitle     The Dark Side of Conspiracies
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres              Adventure,Documentary,Drama
Name: 2002501, dtype: object

(9,)

tconst                 tt11820472
titleType               tvEpisode
primaryTitle        Hugo Lamadrid
originalTitle       Hugo Lamadrid
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2002502, dtype: object

(9,)

tconst                               tt11820474
titleType                             tvEpisode
primaryTitle      Sandra Silvers & Kymber Stone
originalTitle     Sandra Silvers & Kymber Stone
isAdult                                       1
startYear                                  2010
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2002503, dtype: object

(9,)

tconst               tt11820476
titleType              tvSeries
primaryTitle      Island Nation
originalTitle     Island Nation
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               48
genres            Drama,History
Name: 2002504, dtype: object

(9,)

tconst                               tt11820478
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2020
originalTitle     Episode dated 6 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002505, dtype: object

(9,)

tconst                                tt1182047
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2008
originalTitle     Episode dated 4 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2002506, dtype: object

(9,)

tconst                                                   tt11820480
titleType                                                 tvEpisode
primaryTitle      Ayer y Hoy: Especial de San Valentin/Honorio c...
originalTitle     Ayer y Hoy: Especial de San Valentin/Honorio c...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                             Comedy,Talk-Show
Name: 2002507, dtype: object

(9,)

tconst                                     tt11820482
titleType                                   tvEpisode
primaryTitle      Shannon - Wonder Woman in Distress!
originalTitle     Shannon - Wonder Woman in Distress!
isAdult                                             1
startYear                                        2010
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2002508, dtype: object

(9,)

tconst                               tt11820484
titleType                             tvEpisode
primaryTitle      Sandra's geometric suspension
originalTitle     Sandra's geometric suspension
isAdult                                       1
startYear                                  2010
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2002509, dtype: object

(9,)

tconst                               tt11820486
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2020
originalTitle     Episode dated 6 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002510, dtype: object

(9,)

tconst                     tt11820488
titleType                   tvEpisode
primaryTitle      General's Daughter!
originalTitle     General's Daughter!
isAdult                             0
startYear                        2011
endYear                            \N
runtimeMinutes                     30
genres                         Action
Name: 2002511, dtype: object

(9,)

tconst                              tt1182048
titleType                           tvEpisode
primaryTitle      Episode dated 20 March 2001
originalTitle     Episode dated 20 March 2001
isAdult                                     0
startYear                                2001
endYear                                    \N
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2002512, dtype: object

(9,)

tconst                             tt11820490
titleType                           tvEpisode
primaryTitle         Exploring Haunted Forest
originalTitle        Exploring Haunted Forest
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres            Adventure,Documentary,Drama
Name: 2002513, dtype: object

(9,)

tconst                                                   tt11820492
titleType                                                 tvEpisode
primaryTitle      Special Deliveries: Celebrity Mothers Talk Str...
originalTitle     Special Deliveries: Celebrity Mothers Talk Str...
isAdult                                                           0
startYear                                                      2011
endYear                                                          \N
runtimeMinutes                                                   74
genres                                                  Documentary
Name: 2002514, dtype: object

(9,)

tconst                           tt11820496
titleType                             short
primaryTitle      Kalani - Gift from Heaven
originalTitle     Kalani - Gift from Heaven
isAdult                                   0
startYear                              2019
endYear                                  \N
runtimeMinutes                           25
genres                    Documentary,Short
Name: 2002515, dtype: object

(9,)

tconst                       tt11820498
titleType                     tvEpisode
primaryTitle      Shannon Spread Eagled
originalTitle     Shannon Spread Eagled
isAdult                               1
startYear                          2010
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2002516, dtype: object

(9,)

tconst                  tt1182049
titleType               tvEpisode
primaryTitle      Episode #1.3702
originalTitle     Episode #1.3702
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2002517, dtype: object

(9,)

tconst                   tt11820500
titleType                 tvEpisode
primaryTitle      Follow the Leader
originalTitle     Follow the Leader
isAdult                           0
startYear                      2011
endYear                          \N
runtimeMinutes                   30
genres                       Action
Name: 2002518, dtype: object

(9,)

tconst                    tt11820502
titleType                  tvEpisode
primaryTitle      Shannon Mummified!
originalTitle     Shannon Mummified!
isAdult                            1
startYear                       2010
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2002519, dtype: object

(9,)

tconst                          tt11820504
titleType                        tvEpisode
primaryTitle      Brasil 2014: 09/07/14 #1
originalTitle     Brasil 2014: 09/07/14 #1
isAdult                                  0
startYear                             2014
endYear                                 \N
runtimeMinutes                          \N
genres                                  \N
Name: 2002520, dtype: object

(9,)

tconst                 tt11820506
titleType               tvEpisode
primaryTitle      Shannon - Tamed
originalTitle     Shannon - Tamed
isAdult                         1
startYear                    2010
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2002521, dtype: object

(9,)

tconst                       tt11820508
titleType                     tvEpisode
primaryTitle      Sandra's Creepy Motel
originalTitle     Sandra's Creepy Motel
isAdult                               1
startYear                          2010
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2002522, dtype: object

(9,)

tconst                    tt1182050
titleType                  tvSeries
primaryTitle      The Family Silver
originalTitle     The Family Silver
isAdult                           0
startYear                      2005
endYear                          \N
runtimeMinutes                   \N
genres                  Documentary
Name: 2002523, dtype: object

(9,)

tconst                   tt11820510
titleType                 tvEpisode
primaryTitle      Betty Jaded Bound
originalTitle     Betty Jaded Bound
isAdult                           1
startYear                      2010
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2002524, dtype: object

(9,)

tconst                  tt11820512
titleType                tvEpisode
primaryTitle      All Together Now
originalTitle     All Together Now
isAdult                          0
startYear                     2011
endYear                         \N
runtimeMinutes                  30
genres                      Action
Name: 2002525, dtype: object

(9,)

tconst                              tt11820514
titleType                            tvEpisode
primaryTitle      The Voices of the Paranormal
originalTitle     The Voices of the Paranormal
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres             Adventure,Documentary,Drama
Name: 2002526, dtype: object

(9,)

tconst                                                tt11820516
titleType                                              tvEpisode
primaryTitle      Rechter Terror - Neue Dimension der Bedrohung?
originalTitle     Rechter Terror - Neue Dimension der Bedrohung?
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                 Talk-Show
Name: 2002527, dtype: object

(9,)

tconst                                           tt11820518
titleType                                         tvEpisode
primaryTitle      Celeste's Colorful Capture with tickling!
originalTitle     Celeste's Colorful Capture with tickling!
isAdult                                                   1
startYear                                              2010
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Adult
Name: 2002528, dtype: object

(9,)

tconst                       tt1182051
titleType                    tvEpisode
primaryTitle             Episode #1.58
originalTitle            Episode #1.58
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2002529, dtype: object

(9,)

tconst                                             tt11820520
titleType                                           tvEpisode
primaryTitle      Sandra - Torn pantyhose - Tightly Pole Tied
originalTitle     Sandra - Torn pantyhose - Tightly Pole Tied
isAdult                                                     1
startYear                                                2010
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                  Adult
Name: 2002530, dtype: object

(9,)

tconst              tt11820522
titleType            tvEpisode
primaryTitle      Perfect Pets
originalTitle     Perfect Pets
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              30
genres                  Action
Name: 2002531, dtype: object

(9,)

tconst                     tt11820524
titleType                    tvSeries
primaryTitle      Ek Duje Ke Vaaste 2
originalTitle     Ek Duje Ke Vaaste 2
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     22
genres                        Romance
Name: 2002532, dtype: object

(9,)

tconst                                tt11820526
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2002533, dtype: object

(9,)

tconst                                   tt11820528
titleType                                 tvEpisode
primaryTitle      Christina Carter Bound and Gagged
originalTitle     Christina Carter Bound and Gagged
isAdult                                           1
startYear                                      2010
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2002534, dtype: object

(9,)

tconst                 tt1182052
titleType              tvEpisode
primaryTitle      Episode #16.10
originalTitle     Episode #16.10
isAdult                        0
startYear                   2007
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2002535, dtype: object

(9,)

tconst                 tt11820530
titleType               tvEpisode
primaryTitle        Signal & Void
originalTitle       Signal & Void
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2002536, dtype: object

(9,)

tconst                                   tt11820532
titleType                                 tvEpisode
primaryTitle      Shannon - Washing her dirty feet!
originalTitle     Shannon - Washing her dirty feet!
isAdult                                           1
startYear                                      2010
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2002537, dtype: object

(9,)

tconst               tt11820534
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2005
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2002538, dtype: object

(9,)

tconst              tt11820536
titleType            tvEpisode
primaryTitle      Road to Ruin
originalTitle     Road to Ruin
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              30
genres                  Action
Name: 2002539, dtype: object

(9,)

tconst                            tt11820538
titleType                          tvEpisode
primaryTitle      Wendy's Blind Date Bondage
originalTitle     Wendy's Blind Date Bondage
isAdult                                    1
startYear                               2010
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2002540, dtype: object

(9,)

tconst                 tt1182053
titleType              tvEpisode
primaryTitle      Episode #16.11
originalTitle     Episode #16.11
isAdult                        0
startYear                   2007
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2002541, dtype: object

(9,)

tconst                                tt11820540
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2002542, dtype: object

(9,)

tconst            tt11820542
titleType          tvEpisode
primaryTitle          P.E.I.
originalTitle         P.E.I.
isAdult                    0
startYear               2013
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2002543, dtype: object

(9,)

tconst            tt11820544
titleType          tvEpisode
primaryTitle       Obesi-tas
originalTitle      Obesi-tas
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2002544, dtype: object

(9,)

tconst                                    tt11820546
titleType                                  tvEpisode
primaryTitle      Bound on the Farm - Sandra Silvers
originalTitle     Bound on the Farm - Sandra Silvers
isAdult                                            1
startYear                                       2010
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2002545, dtype: object

(9,)

tconst                                                   tt11820548
titleType                                                 tvEpisode
primaryTitle      The Return of The World Changing Conspiracy Th...
originalTitle     The Return of The World Changing Conspiracy Th...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                  Adventure,Documentary,Drama
Name: 2002546, dtype: object

(9,)

tconst                 tt1182054
titleType              tvEpisode
primaryTitle      Episode #16.12
originalTitle     Episode #16.12
isAdult                        0
startYear                   2007
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2002547, dtype: object

(9,)

tconst                   tt11820550
titleType                 tvEpisode
primaryTitle      Scream of a Dream
originalTitle     Scream of a Dream
isAdult                           0
startYear                      2012
endYear                          \N
runtimeMinutes                   30
genres                       Action
Name: 2002548, dtype: object

(9,)

tconst                       tt11820552
titleType                     tvEpisode
primaryTitle      Kira Special Delivery
originalTitle     Kira Special Delivery
isAdult                               1
startYear                          2010
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2002549, dtype: object

(9,)

tconst                                 tt11820554
titleType                               tvEpisode
primaryTitle      Shannon - Bound Bathing Beauty!
originalTitle     Shannon - Bound Bathing Beauty!
isAdult                                         1
startYear                                    2010
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2002550, dtype: object

(9,)

tconst                                  tt11820556
titleType                                tvEpisode
primaryTitle      The Dark Secrets of The Internet
originalTitle     The Dark Secrets of The Internet
isAdult                                          0
startYear                                     2019
endYear                                         \N
runtimeMinutes                                  \N
genres                 Adventure,Documentary,Drama
Name: 2002551, dtype: object

(9,)

tconst             tt11820558
titleType           tvEpisode
primaryTitle           Teil 1
originalTitle          Teil 1
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             52
genres            Documentary
Name: 2002552, dtype: object

(9,)

tconst                tt1182055
titleType             tvEpisode
primaryTitle      Episode #16.9
originalTitle     Episode #16.9
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2002553, dtype: object

(9,)

tconst              tt11820560
titleType            tvEpisode
primaryTitle      A Tori Story
originalTitle     A Tori Story
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              30
genres                  Action
Name: 2002554, dtype: object

(9,)

tconst                           tt11820562
titleType                         tvEpisode
primaryTitle      Bikini Vacation Invasion!
originalTitle     Bikini Vacation Invasion!
isAdult                                   1
startYear                              2010
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2002555, dtype: object

(9,)

tconst                                tt11820564
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2002556, dtype: object

(9,)

tconst             tt11820566
titleType           tvEpisode
primaryTitle           Teil 2
originalTitle          Teil 2
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             52
genres            Documentary
Name: 2002557, dtype: object

(9,)

tconst                  tt1182056
titleType               tvEpisode
primaryTitle      Aflevering 3566
originalTitle     Aflevering 3566
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2002558, dtype: object

(9,)

tconst                                tt11820570
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2002559, dtype: object

(9,)

tconst            tt11820572
titleType              short
primaryTitle        Massacre
originalTitle       Massacre
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            26
genres                 Short
Name: 2002560, dtype: object

(9,)

tconst                 tt11820574
titleType               tvEpisode
primaryTitle         Mario Markic
originalTitle        Mario Markic
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2002561, dtype: object

(9,)

tconst                                                   tt11820576
titleType                                                 tvEpisode
primaryTitle      Sandra Silvers & JJ Plush Prelude to a Kiss Pa...
originalTitle     Sandra Silvers & JJ Plush Prelude to a Kiss Pa...
isAdult                                                           1
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002562, dtype: object

(9,)

tconst                              tt11820578
titleType                            tvEpisode
primaryTitle      The Truth About The Internet
originalTitle     The Truth About The Internet
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres             Adventure,Documentary,Drama
Name: 2002563, dtype: object

(9,)

tconst               tt1182057
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 1987
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2002564, dtype: object

(9,)

tconst                                                   tt11820580
titleType                                                 tvEpisode
primaryTitle      Sandra Silvers & JJ Plush Prelude to a Kiss Pa...
originalTitle     Sandra Silvers & JJ Plush Prelude to a Kiss Pa...
isAdult                                                           1
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002565, dtype: object

(9,)

tconst                  tt11820582
titleType                tvEpisode
primaryTitle      Abandoned Prison
originalTitle     Abandoned Prison
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres                  Reality-TV
Name: 2002566, dtype: object

(9,)

tconst                                tt11820584
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                 News,Reality-TV,Talk-Show
Name: 2002567, dtype: object

(9,)

tconst                                       tt11820586
titleType                                     tvEpisode
primaryTitle      Vom Riesengebirge bis zu den Karpaten
originalTitle     Vom Riesengebirge bis zu den Karpaten
isAdult                                               0
startYear                                          2014
endYear                                              \N
runtimeMinutes                                       43
genres                                      Documentary
Name: 2002568, dtype: object

(9,)

tconst                                                   tt11820588
titleType                                                 tvEpisode
primaryTitle      Sandra & Shannon Sweater Bound Secretaries Part 1
originalTitle     Sandra & Shannon Sweater Bound Secretaries Part 1
isAdult                                                           1
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002569, dtype: object

(9,)

tconst                tt1182058
titleType             tvEpisode
primaryTitle       Episode #3.1
originalTitle      Episode #3.1
isAdult                       0
startYear                  2000
endYear                      \N
runtimeMinutes               \N
genres            Comedy,Family
Name: 2002570, dtype: object

(9,)

tconst                       tt11820590
titleType                     tvEpisode
primaryTitle      José "Chucho" Acasuso
originalTitle     José "Chucho" Acasuso
isAdult                               0
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                  Sport,Talk-Show
Name: 2002571, dtype: object

(9,)

tconst                                tt11820592
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2002572, dtype: object

(9,)

tconst                                                   tt11820594
titleType                                                 tvEpisode
primaryTitle      Vom Stettiner Haff bis zu den Sümpfen der Biebrza
originalTitle     Vom Stettiner Haff bis zu den Sümpfen der Biebrza
isAdult                                                           0
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   43
genres                                                  Documentary
Name: 2002573, dtype: object

(9,)

tconst                                                   tt11820596
titleType                                                 tvEpisode
primaryTitle      Sandra & Shannon Sweater Bound Secretaries Part 2
originalTitle     Sandra & Shannon Sweater Bound Secretaries Part 2
isAdult                                                           1
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002574, dtype: object

(9,)

tconst              tt11820598
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002575, dtype: object

(9,)

tconst                tt1182059
titleType             tvEpisode
primaryTitle      Episode #1.46
originalTitle     Episode #1.46
isAdult                       0
startYear                  1984
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002576, dtype: object

(9,)

tconst              tt11820602
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002577, dtype: object

(9,)

tconst              tt11820604
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002578, dtype: object

(9,)

tconst                                       tt11820606
titleType                                     tvEpisode
primaryTitle      Von Masuren bis zu den Ostseestränden
originalTitle     Von Masuren bis zu den Ostseestränden
isAdult                                               0
startYear                                          2014
endYear                                              \N
runtimeMinutes                                       43
genres                                      Documentary
Name: 2002579, dtype: object

(9,)

tconst                         tt11820608
titleType                       tvEpisode
primaryTitle      María del Pilar Pereyra
originalTitle     María del Pilar Pereyra
isAdult                                 0
startYear                            2018
endYear                                \N
runtimeMinutes                         \N
genres                    Sport,Talk-Show
Name: 2002580, dtype: object

(9,)

tconst                tt11820610
titleType              tvEpisode
primaryTitle      Elayne Manella
originalTitle     Elayne Manella
isAdult                        1
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2002581, dtype: object

(9,)

tconst              tt11820612
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002582, dtype: object

(9,)

tconst              tt11820614
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002583, dtype: object

(9,)

tconst                                           tt11820616
titleType                                         tvEpisode
primaryTitle      Sandra & Shannon, Gag-Kissing Secretaries
originalTitle     Sandra & Shannon, Gag-Kissing Secretaries
isAdult                                                   1
startYear                                              2010
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Adult
Name: 2002584, dtype: object

(9,)

tconst              tt11820618
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002585, dtype: object

(9,)

tconst                   tt1182061
titleType                tvEpisode
primaryTitle      Allegro moderato
originalTitle     Allegro moderato
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2002586, dtype: object

(9,)

tconst              tt11820620
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002587, dtype: object

(9,)

tconst              tt11820622
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002588, dtype: object

(9,)

tconst               tt11820624
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002589, dtype: object

(9,)

tconst                                tt11820626
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                      Reality-TV,Talk-Show
Name: 2002590, dtype: object

(9,)

tconst                                           tt11820628
titleType                                         tvEpisode
primaryTitle      Sandra Silvers - Shipping a Girl Overseas
originalTitle     Sandra Silvers - Shipping a Girl Overseas
isAdult                                                   1
startYear                                              2010
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Adult
Name: 2002591, dtype: object

(9,)

tconst                   tt1182062
titleType                tvEpisode
primaryTitle          Episode #1.3
originalTitle         Episode #1.3
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Music,Reality-TV
Name: 2002592, dtype: object

(9,)

tconst               tt11820630
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002593, dtype: object

(9,)

tconst               tt11820632
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002594, dtype: object

(9,)

tconst               tt11820634
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002595, dtype: object

(9,)

tconst               tt11820636
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002596, dtype: object

(9,)

tconst                 tt11820638
titleType               tvEpisode
primaryTitle      David Trezeguet
originalTitle     David Trezeguet
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2002597, dtype: object

(9,)

tconst                      tt1182063
titleType                   tvEpisode
primaryTitle             Episode #2.1
originalTitle            Episode #2.1
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2002598, dtype: object

(9,)

tconst              tt11820640
titleType            tvEpisode
primaryTitle      Dog Sledding
originalTitle     Dog Sledding
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002599, dtype: object

(9,)

tconst               tt11820642
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002600, dtype: object

(9,)

tconst            tt11820644
titleType          tvEpisode
primaryTitle      Jetta Luna
originalTitle     Jetta Luna
isAdult                    1
startYear               2010
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2002601, dtype: object

(9,)

tconst               tt11820646
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002602, dtype: object

(9,)

tconst               tt11820648
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002603, dtype: object

(9,)

tconst                      tt1182064
titleType                   tvEpisode
primaryTitle             Episode #2.2
originalTitle            Episode #2.2
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2002604, dtype: object

(9,)

tconst                                 tt11820650
titleType                               tvEpisode
primaryTitle      Saint Paul's Cemetery - Ivy, VA
originalTitle     Saint Paul's Cemetery - Ivy, VA
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 14
genres                                Documentary
Name: 2002605, dtype: object

(9,)

tconst               tt11820652
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002606, dtype: object

(9,)

tconst               tt11820654
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002607, dtype: object

(9,)

tconst                 tt11820656
titleType               tvEpisode
primaryTitle        Leonel Pernía
originalTitle       Leonel Pernía
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2002608, dtype: object

(9,)

tconst                  tt1182065
titleType               tvEpisode
primaryTitle      Episode #1.2227
originalTitle     Episode #1.2227
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2002609, dtype: object

(9,)

tconst                                tt11820660
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2002610, dtype: object

(9,)

tconst                                                   tt11820662
titleType                                                 tvEpisode
primaryTitle      Explore Your Options: Doulas, Birth Centers & ...
originalTitle     Explore Your Options: Doulas, Birth Centers & ...
isAdult                                                           0
startYear                                                      2011
endYear                                                          \N
runtimeMinutes                                                  101
genres                                                  Documentary
Name: 2002611, dtype: object

(9,)

tconst               tt11820664
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002612, dtype: object

(9,)

tconst              tt11820666
titleType            tvEpisode
primaryTitle      Julie Simone
originalTitle     Julie Simone
isAdult                      1
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2002613, dtype: object

(9,)

tconst                          tt11820668
titleType                        tvEpisode
primaryTitle      A Hideous Turn of Events
originalTitle     A Hideous Turn of Events
isAdult                                  0
startYear                             2012
endYear                                 \N
runtimeMinutes                          30
genres                              Action
Name: 2002614, dtype: object

(9,)

tconst                tt1182066
titleType             tvEpisode
primaryTitle      Episode #4.16
originalTitle     Episode #4.16
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002615, dtype: object

(9,)

tconst                 tt11820670
titleType               tvEpisode
primaryTitle        Juan Taratuto
originalTitle       Juan Taratuto
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2002616, dtype: object

(9,)

tconst                            tt11820672
titleType                          tvEpisode
primaryTitle      Sandra's Strict Strappado!
originalTitle     Sandra's Strict Strappado!
isAdult                                    1
startYear                               2010
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2002617, dtype: object

(9,)

tconst                             tt11820674
titleType                               movie
primaryTitle      Thank You for Your Patience
originalTitle     Thank You for Your Patience
isAdult                                     0
startYear                                2021
endYear                                    \N
runtimeMinutes                             60
genres                                Romance
Name: 2002618, dtype: object

(9,)

tconst                tt11820676
titleType              tvEpisode
primaryTitle      Episode #1.201
originalTitle     Episode #1.201
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002619, dtype: object

(9,)

tconst                tt11820678
titleType              tvEpisode
primaryTitle      Episode #1.202
originalTitle     Episode #1.202
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002620, dtype: object

(9,)

tconst                tt1182067
titleType             tvEpisode
primaryTitle      Episode #4.17
originalTitle     Episode #4.17
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2002621, dtype: object

(9,)

tconst                tt11820680
titleType              tvEpisode
primaryTitle      Episode #1.204
originalTitle     Episode #1.204
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002622, dtype: object

(9,)

tconst                tt11820682
titleType              tvEpisode
primaryTitle      Episode #1.203
originalTitle     Episode #1.203
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002623, dtype: object

(9,)

tconst                                                   tt11820684
titleType                                                 tvEpisode
primaryTitle      Carter Family Cemetery - Berkmar, Albemarle Co...
originalTitle     Carter Family Cemetery - Berkmar, Albemarle Co...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    2
genres                                                  Documentary
Name: 2002624, dtype: object

(9,)

tconst                        tt11820686
titleType                      tvEpisode
primaryTitle      JJ Plush, Ring Gagged!
originalTitle     JJ Plush, Ring Gagged!
isAdult                                1
startYear                           2010
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2002625, dtype: object

(9,)

tconst                tt11820688
titleType              tvEpisode
primaryTitle      Episode #1.206
originalTitle     Episode #1.206
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002626, dtype: object

(9,)

tconst                  tt1182068
titleType               tvEpisode
primaryTitle      Episode #24.128
originalTitle     Episode #24.128
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002627, dtype: object

(9,)

tconst                tt11820690
titleType              tvEpisode
primaryTitle      Episode #1.205
originalTitle     Episode #1.205
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002628, dtype: object

(9,)

tconst                tt11820692
titleType              tvEpisode
primaryTitle      Episode #1.207
originalTitle     Episode #1.207
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002629, dtype: object

(9,)

tconst                tt11820694
titleType              tvEpisode
primaryTitle      Episode #1.208
originalTitle     Episode #1.208
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002630, dtype: object

(9,)

tconst                tt11820696
titleType              tvEpisode
primaryTitle      Episode #1.209
originalTitle     Episode #1.209
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002631, dtype: object

(9,)

tconst                tt11820698
titleType              tvEpisode
primaryTitle      Episode #1.210
originalTitle     Episode #1.210
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002632, dtype: object

(9,)

tconst                  tt1182069
titleType               tvEpisode
primaryTitle      Episode #24.129
originalTitle     Episode #24.129
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002633, dtype: object

(9,)

tconst                          tt11820700
titleType                        tvEpisode
primaryTitle      Wendy Tied Arms to Sides
originalTitle     Wendy Tied Arms to Sides
isAdult                                  1
startYear                             2010
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2002634, dtype: object

(9,)

tconst                tt11820702
titleType              tvEpisode
primaryTitle      Episode #1.211
originalTitle     Episode #1.211
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002635, dtype: object

(9,)

tconst                tt11820704
titleType              tvEpisode
primaryTitle      Episode #1.213
originalTitle     Episode #1.213
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002636, dtype: object

(9,)

tconst                tt11820706
titleType              tvEpisode
primaryTitle      Episode #1.212
originalTitle     Episode #1.212
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002637, dtype: object

(9,)

tconst                       tt11820708
titleType                     tvEpisode
primaryTitle      A Fleeting Friendship
originalTitle     A Fleeting Friendship
isAdult                               0
startYear                          2012
endYear                              \N
runtimeMinutes                       30
genres                           Action
Name: 2002638, dtype: object

(9,)

tconst                  tt1182070
titleType               tvEpisode
primaryTitle      Episode #24.130
originalTitle     Episode #24.130
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002639, dtype: object

(9,)

tconst                tt11820710
titleType              tvEpisode
primaryTitle      Episode #1.214
originalTitle     Episode #1.214
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002640, dtype: object

(9,)

tconst                                     tt11820712
titleType                                   tvEpisode
primaryTitle      Sandra Silvers - Bottoms up Bondage
originalTitle     Sandra Silvers - Bottoms up Bondage
isAdult                                             1
startYear                                        2010
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2002641, dtype: object

(9,)

tconst                 tt11820714
titleType               tvEpisode
primaryTitle       Mariano Pernía
originalTitle      Mariano Pernía
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2002642, dtype: object

(9,)

tconst                tt11820716
titleType              tvEpisode
primaryTitle      Episode #1.215
originalTitle     Episode #1.215
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002643, dtype: object

(9,)

tconst                tt11820718
titleType              tvEpisode
primaryTitle      Episode #1.217
originalTitle     Episode #1.217
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002644, dtype: object

(9,)

tconst                  tt1182071
titleType               tvEpisode
primaryTitle      Episode #24.132
originalTitle     Episode #24.132
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002645, dtype: object

(9,)

tconst                tt11820720
titleType              tvEpisode
primaryTitle      Episode #1.216
originalTitle     Episode #1.216
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002646, dtype: object

(9,)

tconst                                                   tt11820722
titleType                                                   tvMovie
primaryTitle      Second Sight Paranormal TV Bon Secour Spirits ...
originalTitle                       Bon Secour Spirits of the River
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Drama
Name: 2002647, dtype: object

(9,)

tconst                tt11820724
titleType              tvEpisode
primaryTitle      Episode #1.218
originalTitle     Episode #1.218
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002648, dtype: object

(9,)

tconst                tt11820726
titleType              tvEpisode
primaryTitle      Episode #1.220
originalTitle     Episode #1.220
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002649, dtype: object

(9,)

tconst                tt11820728
titleType              tvEpisode
primaryTitle      Episode #1.219
originalTitle     Episode #1.219
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002650, dtype: object

(9,)

tconst                  tt1182072
titleType               tvEpisode
primaryTitle      Episode #24.135
originalTitle     Episode #24.135
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002651, dtype: object

(9,)

tconst                                                   tt11820730
titleType                                                 tvEpisode
primaryTitle      Mount Calvary Baptist Church New Cemetery - Iv...
originalTitle     Mount Calvary Baptist Church New Cemetery - Iv...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    2
genres                                                  Documentary
Name: 2002652, dtype: object

(9,)

tconst                tt11820732
titleType              tvEpisode
primaryTitle      Daddy Day Care
originalTitle     Daddy Day Care
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                41
genres                Reality-TV
Name: 2002653, dtype: object

(9,)

tconst                tt11820734
titleType              tvEpisode
primaryTitle      Episode #1.375
originalTitle     Episode #1.375
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2002654, dtype: object

(9,)

tconst                                             tt11820736
titleType                                           tvEpisode
primaryTitle      Sandra Silves - Strictly Secured Secretary!
originalTitle     Sandra Silves - Strictly Secured Secretary!
isAdult                                                     1
startYear                                                2010
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                  Adult
Name: 2002655, dtype: object

(9,)

tconst             tt11820738
titleType           tvEpisode
primaryTitle      Family Time
originalTitle     Family Time
isAdult                     0
startYear                2012
endYear                    \N
runtimeMinutes             30
genres                 Action
Name: 2002656, dtype: object

(9,)

tconst                  tt1182073
titleType               tvEpisode
primaryTitle      Episode #24.138
originalTitle     Episode #24.138
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002657, dtype: object

(9,)

tconst              tt11820740
titleType            tvEpisode
primaryTitle      Kendra James
originalTitle     Kendra James
isAdult                      1
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2002658, dtype: object

(9,)

tconst                                tt11820742
titleType                              tvEpisode
primaryTitle      Episode dated 18 February 2020
originalTitle     Episode dated 18 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2002659, dtype: object

(9,)

tconst                                tt11820744
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2002660, dtype: object

(9,)

tconst                                                   tt11820746
titleType                                                     movie
primaryTitle      Clouds: Echoes of Nature - Relaxation with Mus...
originalTitle     Clouds: Echoes of Nature - Relaxation with Mus...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                  120
genres                                            Documentary,Music
Name: 2002661, dtype: object

(9,)

tconst                     tt11820748
titleType                   videoGame
primaryTitle      Grip: Combat Racing
originalTitle     Grip: Combat Racing
isAdult                             0
startYear                        2018
endYear                            \N
runtimeMinutes                     \N
genres                         Action
Name: 2002662, dtype: object

(9,)

tconst                  tt1182074
titleType               tvEpisode
primaryTitle      Episode #24.148
originalTitle     Episode #24.148
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002663, dtype: object

(9,)

tconst                           tt11820750
titleType                         tvEpisode
primaryTitle      Celeste's Romantic Hogtie
originalTitle     Celeste's Romantic Hogtie
isAdult                                   1
startYear                              2010
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2002664, dtype: object

(9,)

tconst                                    tt11820752
titleType                                  tvEpisode
primaryTitle      Sandra's Strict Hogtie, By Request
originalTitle     Sandra's Strict Hogtie, By Request
isAdult                                            1
startYear                                       2010
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2002665, dtype: object

(9,)

tconst                                                 tt11820754
titleType                                               tvEpisode
primaryTitle      Woodfolk Family Cemetery - Albemarle County, VA
originalTitle     Woodfolk Family Cemetery - Albemarle County, VA
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                  1
genres                                                Documentary
Name: 2002666, dtype: object

(9,)

tconst                  tt11820756
titleType                tvEpisode
primaryTitle      Misfit Marauders
originalTitle     Misfit Marauders
isAdult                          0
startYear                     2012
endYear                         \N
runtimeMinutes                  30
genres                      Action
Name: 2002667, dtype: object

(9,)

tconst                                   tt11820758
titleType                                 tvEpisode
primaryTitle      Kerri Taylor - Bound by DGBondage
originalTitle     Kerri Taylor - Bound by DGBondage
isAdult                                           1
startYear                                      2010
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2002668, dtype: object

(9,)

tconst                  tt1182075
titleType               tvEpisode
primaryTitle      Episode #24.149
originalTitle     Episode #24.149
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002669, dtype: object

(9,)

tconst                                 tt11820760
titleType                               tvEpisode
primaryTitle      Jane Ember - Bound In the Bronx
originalTitle     Jane Ember - Bound In the Bronx
isAdult                                         1
startYear                                    2010
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2002670, dtype: object

(9,)

tconst                                        tt11820762
titleType                                      tvEpisode
primaryTitle      Oakwood Cemetery - Charlottesville, VA
originalTitle     Oakwood Cemetery - Charlottesville, VA
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        18
genres                                       Documentary
Name: 2002671, dtype: object

(9,)

tconst                    tt11820764
titleType                  tvEpisode
primaryTitle             Épisode 388
originalTitle            Épisode 388
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    22
genres            Comedy,Crime,Drama
Name: 2002672, dtype: object

(9,)

tconst               tt11820766
titleType             tvEpisode
primaryTitle      Time - Monday
originalTitle     Time - Monday
isAdult                       0
startYear                  1993
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2002673, dtype: object

(9,)

tconst                    tt11820768
titleType                  tvEpisode
primaryTitle      Hale vs. MacDonald
originalTitle     Hale vs. MacDonald
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    22
genres              Comedy,Game-Show
Name: 2002674, dtype: object

(9,)

tconst                  tt1182076
titleType               tvEpisode
primaryTitle      Episode #24.150
originalTitle     Episode #24.150
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002675, dtype: object

(9,)

tconst                    tt11820770
titleType                  tvEpisode
primaryTitle      A Chilling Reunion
originalTitle     A Chilling Reunion
isAdult                            0
startYear                       2012
endYear                           \N
runtimeMinutes                    30
genres                        Action
Name: 2002676, dtype: object

(9,)

tconst                                                tt11820772
titleType                                              tvEpisode
primaryTitle      The VBAC Dilemma: What Your Options Really Are
originalTitle     The VBAC Dilemma: What Your Options Really Are
isAdult                                                        0
startYear                                                   2011
endYear                                                       \N
runtimeMinutes                                                51
genres                                               Documentary
Name: 2002677, dtype: object

(9,)

tconst                                  tt11820774
titleType                                tvEpisode
primaryTitle      Operation Dragon Strike!, Part 1
originalTitle     Operation Dragon Strike!, Part 1
isAdult                                          0
startYear                                     2012
endYear                                         \N
runtimeMinutes                                  30
genres                                      Action
Name: 2002678, dtype: object

(9,)

tconst                          tt11820776
titleType                        tvEpisode
primaryTitle      Sandwiches met mayonaise
originalTitle     Sandwiches met mayonaise
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                              Comedy
Name: 2002679, dtype: object

(9,)

tconst                tt11820778
titleType              tvEpisode
primaryTitle      Time - Tuesday
originalTitle     Time - Tuesday
isAdult                        0
startYear                   1993
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2002680, dtype: object

(9,)

tconst                  tt1182077
titleType               tvEpisode
primaryTitle      Episode #24.152
originalTitle     Episode #24.152
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002681, dtype: object

(9,)

tconst                                  tt11820780
titleType                                tvEpisode
primaryTitle      Operation Dragon Strike!, Part 2
originalTitle     Operation Dragon Strike!, Part 2
isAdult                                          0
startYear                                     2012
endYear                                         \N
runtimeMinutes                                  30
genres                                      Action
Name: 2002682, dtype: object

(9,)

tconst            tt11820782
titleType          tvEpisode
primaryTitle       Hommeland
originalTitle      Hommeland
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2002683, dtype: object

(9,)

tconst                  tt11820784
titleType                tvEpisode
primaryTitle      Time - Wednesday
originalTitle     Time - Wednesday
isAdult                          0
startYear                     1993
endYear                         \N
runtimeMinutes                  \N
genres                      Family
Name: 2002684, dtype: object

(9,)

tconst                              tt11820786
titleType                            tvEpisode
primaryTitle      2019 Mnet Asian Music Awards
originalTitle     2019 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2002685, dtype: object

(9,)

tconst                  tt11820788
titleType                tvEpisode
primaryTitle      Out of Character
originalTitle     Out of Character
isAdult                          0
startYear                     2012
endYear                         \N
runtimeMinutes                  30
genres                      Action
Name: 2002686, dtype: object

(9,)

tconst                  tt1182078
titleType               tvEpisode
primaryTitle      Episode #24.153
originalTitle     Episode #24.153
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002687, dtype: object

(9,)

tconst                 tt11820790
titleType               tvEpisode
primaryTitle      Time - Thursday
originalTitle     Time - Thursday
isAdult                         0
startYear                    1993
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2002688, dtype: object

(9,)

tconst                tt11820792
titleType              tvEpisode
primaryTitle      Les Invisibles
originalTitle     Les Invisibles
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2002689, dtype: object

(9,)

tconst                                      tt11820794
titleType                                        video
primaryTitle      Trailer Trauma V: 70s Action Attack!
originalTitle     Trailer Trauma V: 70s Action Attack!
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                     183
genres                                          Action
Name: 2002690, dtype: object

(9,)

tconst               tt11820796
titleType             tvEpisode
primaryTitle      Time - Friday
originalTitle     Time - Friday
isAdult                       0
startYear                  1993
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2002691, dtype: object

(9,)

tconst                                        tt11820798
titleType                                      tvEpisode
primaryTitle      Sandra & Shannon - Bondage and Kissing
originalTitle     Sandra & Shannon - Bondage and Kissing
isAdult                                                1
startYear                                           2010
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Adult
Name: 2002692, dtype: object

(9,)

tconst                  tt1182079
titleType               tvEpisode
primaryTitle      Episode #24.168
originalTitle     Episode #24.168
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2002693, dtype: object

(9,)

tconst                 tt11820802
titleType               tvEpisode
primaryTitle      Gate to Destiny
originalTitle     Gate to Destiny
isAdult                         0
startYear                    2012
endYear                        \N
runtimeMinutes                 30
genres                     Action
Name: 2002694, dtype: object

(9,)

tconst            tt11820804
titleType          tvEpisode
primaryTitle              RV
originalTitle             RV
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2002695, dtype: object

(9,)

tconst                tt11820806
titleType              tvEpisode
primaryTitle      Bikini Try-Ons
originalTitle     Bikini Try-Ons
isAdult                        1
startYear                   2020
endYear                       \N
runtimeMinutes                59
genres                     Adult
Name: 2002696, dtype: object

(9,)

tconst            tt11820808
titleType              movie
primaryTitle           Beast
originalTitle          Beast
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2002697, dtype: object

(9,)

tconst                   tt1182080
titleType                tvEpisode
primaryTitle         Episode #11.1
originalTitle        Episode #11.1
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2002698, dtype: object

(9,)

tconst            tt11820810
titleType          tvEpisode
primaryTitle         Morgane
originalTitle        Morgane
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2002699, dtype: object

(9,)

tconst                      tt11820812
titleType                    tvSpecial
primaryTitle      HGTV Dream Home 2018
originalTitle     HGTV Dream Home 2018
isAdult                              0
startYear                         2018
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2002700, dtype: object

(9,)

tconst                              tt11820816
titleType                            tvEpisode
primaryTitle      Closely with Jivan Gasparyan
originalTitle     Closely with Jivan Gasparyan
isAdult                                      0
startYear                                 2014
endYear                                     \N
runtimeMinutes                              \N
genres                              Reality-TV
Name: 2002701, dtype: object

(9,)

tconst                  tt11820818
titleType                tvEpisode
primaryTitle      Le Dernier Homme
originalTitle     Le Dernier Homme
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2002702, dtype: object

(9,)

tconst                      tt1182081
titleType                   tvEpisode
primaryTitle             Episode #2.5
originalTitle            Episode #2.5
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002703, dtype: object

(9,)

tconst                tt11820822
titleType              tvEpisode
primaryTitle      Le Soulèvement
originalTitle     Le Soulèvement
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2002704, dtype: object

(9,)

tconst                    tt11820824
titleType                   tvSeries
primaryTitle      Wrapped in Bondage
originalTitle     Wrapped in Bondage
isAdult                            1
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2002705, dtype: object

(9,)

tconst                                                   tt11820826
titleType                                                 tvEpisode
primaryTitle      SLUMDOG MILLIONAIRE director Danny Boyle on Th...
originalTitle     SLUMDOG MILLIONAIRE director Danny Boyle on Th...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2002706, dtype: object

(9,)

tconst                 tt11820828
titleType               tvEpisode
primaryTitle      Episode #1.7322
originalTitle     Episode #1.7322
isAdult                         0
startYear                    2002
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2002707, dtype: object

(9,)

tconst                      tt1182082
titleType                   tvEpisode
primaryTitle             Episode #1.6
originalTitle            Episode #1.6
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002708, dtype: object

(9,)

tconst            tt11820832
titleType          tvEpisode
primaryTitle           Pilot
originalTitle          Pilot
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2002709, dtype: object

(9,)

tconst             tt11820834
titleType               short
primaryTitle         Obsesión
originalTitle        Obsesión
isAdult                     0
startYear                1985
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2002710, dtype: object

(9,)

tconst                                                   tt11820838
titleType                                                 tvEpisode
primaryTitle      Blonde group sex addict Natasha Teen DAP'ed ba...
originalTitle     Blonde group sex addict Natasha Teen DAP'ed ba...
isAdult                                                           1
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002711, dtype: object

(9,)

tconst                      tt1182083
titleType                   tvEpisode
primaryTitle             Episode #1.7
originalTitle            Episode #1.7
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002712, dtype: object

(9,)

tconst                                                   tt11820840
titleType                                                 tvEpisode
primaryTitle      Son of Rambow: Nick Goldsmith Interview with T...
originalTitle     Son of Rambow: Nick Goldsmith Interview with T...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2002713, dtype: object

(9,)

tconst                 tt11820842
titleType               tvEpisode
primaryTitle      Episode #1.7328
originalTitle     Episode #1.7328
isAdult                         0
startYear                    2002
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2002714, dtype: object

(9,)

tconst                   tt11820844
titleType                     short
primaryTitle                 Tonbau
originalTitle                Tonbau
isAdult                           0
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2002715, dtype: object

(9,)

tconst                                        tt11820846
titleType                                      tvSpecial
primaryTitle      Behind the Build: HGTV Dream Home 2018
originalTitle     Behind the Build: HGTV Dream Home 2018
isAdult                                                0
startYear                                           2017
endYear                                               \N
runtimeMinutes                                        \N
genres                                       Documentary
Name: 2002716, dtype: object

(9,)

tconst                                                   tt11820848
titleType                                                 tvEpisode
primaryTitle      Shoot 'Em Up: Director Michael Davis with Thin...
originalTitle     Shoot 'Em Up: Director Michael Davis with Thin...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2002717, dtype: object

(9,)

tconst                      tt1182084
titleType                   tvEpisode
primaryTitle             Episode #1.8
originalTitle            Episode #1.8
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002718, dtype: object

(9,)

tconst                    tt11820850
titleType                      movie
primaryTitle              The Keeper
originalTitle             The Keeper
isAdult                            0
startYear                         \N
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Sport
Name: 2002719, dtype: object

(9,)

tconst                     tt11820852
titleType                   tvEpisode
primaryTitle          Cursed Paradise
originalTitle         Cursed Paradise
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     42
genres            Documentary,Mystery
Name: 2002720, dtype: object

(9,)

tconst               tt11820856
titleType             tvEpisode
primaryTitle      Experiments 2
originalTitle     Experiments 2
isAdult                       1
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2002721, dtype: object

(9,)

tconst                     tt11820858
titleType                   tvEpisode
primaryTitle      Ham-navazan Concert
originalTitle     Ham-navazan Concert
isAdult                             0
startYear                        2014
endYear                            \N
runtimeMinutes                     \N
genres                     Reality-TV
Name: 2002722, dtype: object

(9,)

tconst                      tt1182085
titleType                   tvEpisode
primaryTitle            Episode #1.19
originalTitle           Episode #1.19
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002723, dtype: object

(9,)

tconst               tt11820860
titleType             tvEpisode
primaryTitle      Experiments 3
originalTitle     Experiments 3
isAdult                       1
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2002724, dtype: object

(9,)

tconst              tt11820862
titleType                movie
primaryTitle      American Zoo
originalTitle     American Zoo
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2002725, dtype: object

(9,)

tconst                                tt11820864
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2002726, dtype: object

(9,)

tconst                       tt11820866
titleType                     tvEpisode
primaryTitle      Small Cars Big on BBQ
originalTitle     Small Cars Big on BBQ
isAdult                               0
startYear                          2014
endYear                              \N
runtimeMinutes                       \N
genres                       Reality-TV
Name: 2002727, dtype: object

(9,)

tconst                          tt11820868
titleType                        tvEpisode
primaryTitle      Africa's Cursed Mountain
originalTitle     Africa's Cursed Mountain
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          42
genres                 Documentary,Mystery
Name: 2002728, dtype: object

(9,)

tconst                      tt1182086
titleType                   tvEpisode
primaryTitle            Episode #1.20
originalTitle           Episode #1.20
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002729, dtype: object

(9,)

tconst                                     tt11820872
titleType                                   tvSpecial
primaryTitle      Celebrity Parade for Cerebral Palsy
originalTitle     Celebrity Parade for Cerebral Palsy
isAdult                                             0
startYear                                        1953
endYear                                            \N
runtimeMinutes                                     \N
genres                                         Family
Name: 2002730, dtype: object

(9,)

tconst               tt11820874
titleType                 movie
primaryTitle      Poison Fields
originalTitle     Poison Fields
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2002731, dtype: object

(9,)

tconst             tt11820878
titleType               short
primaryTitle         Guide On
originalTitle        Guide On
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             16
genres            Drama,Short
Name: 2002732, dtype: object

(9,)

tconst                      tt1182087
titleType                   tvEpisode
primaryTitle            Episode #1.21
originalTitle           Episode #1.21
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002733, dtype: object

(9,)

tconst            tt11820880
titleType          tvEpisode
primaryTitle         Nova 'Q
originalTitle        Nova 'Q
isAdult                    0
startYear               2014
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2002734, dtype: object

(9,)

tconst               tt11820884
titleType                 short
primaryTitle      Another Place
originalTitle     Another Place
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres             Sci-Fi,Short
Name: 2002735, dtype: object

(9,)

tconst                     tt11820886
titleType                   tvEpisode
primaryTitle      Chevy SSR Tailgater
originalTitle     Chevy SSR Tailgater
isAdult                             0
startYear                        2014
endYear                            \N
runtimeMinutes                     \N
genres                     Reality-TV
Name: 2002736, dtype: object

(9,)

tconst                     tt11820888
titleType                   tvEpisode
primaryTitle         Invisible Empire
originalTitle        Invisible Empire
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     42
genres            Documentary,Mystery
Name: 2002737, dtype: object

(9,)

tconst                      tt1182088
titleType                   tvEpisode
primaryTitle            Episode #1.22
originalTitle           Episode #1.22
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002738, dtype: object

(9,)

tconst                 tt11820890
titleType                 tvMovie
primaryTitle      Weather Hunters
originalTitle     Weather Hunters
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                  Animation
Name: 2002739, dtype: object

(9,)

tconst                             tt11820892
titleType                           tvEpisode
primaryTitle      Vintage Truck Gets Grilling
originalTitle     Vintage Truck Gets Grilling
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres                             Reality-TV
Name: 2002740, dtype: object

(9,)

tconst                    tt11820894
titleType                   tvSeries
primaryTitle      Rules of the World
originalTitle     Rules of the World
isAdult                            0
startYear                         \N
endYear                           \N
runtimeMinutes                    \N
genres                        Comedy
Name: 2002741, dtype: object

(9,)

tconst                                                   tt11820896
titleType                                                 tvEpisode
primaryTitle      Daniela Ray learns how to fuck like a porn sta...
originalTitle     Daniela Ray learns how to fuck like a porn sta...
isAdult                                                           1
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002742, dtype: object

(9,)

tconst                               tt11820898
titleType                             tvEpisode
primaryTitle      Episode dated 17 October 2014
originalTitle     Episode dated 17 October 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002743, dtype: object

(9,)

tconst                      tt1182089
titleType                   tvEpisode
primaryTitle            Episode #1.23
originalTitle           Episode #1.23
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002744, dtype: object

(9,)

tconst                     tt11820900
titleType                   tvEpisode
primaryTitle      El Trojan Tailgater
originalTitle     El Trojan Tailgater
isAdult                             0
startYear                        2014
endYear                            \N
runtimeMinutes                     \N
genres                     Reality-TV
Name: 2002745, dtype: object

(9,)

tconst                               tt11820902
titleType                             tvEpisode
primaryTitle      Episode dated 20 October 2014
originalTitle     Episode dated 20 October 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002746, dtype: object

(9,)

tconst                tt11820904
titleType                  short
primaryTitle        Souviens toi
originalTitle       Souviens toi
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            Short,Thriller
Name: 2002747, dtype: object

(9,)

tconst                               tt11820906
titleType                             tvEpisode
primaryTitle      Episode dated 3 November 2014
originalTitle     Episode dated 3 November 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002748, dtype: object

(9,)

tconst                               tt11820908
titleType                             tvEpisode
primaryTitle      Episode dated 7 November 2014
originalTitle     Episode dated 7 November 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2002749, dtype: object

(9,)

tconst                      tt1182090
titleType                   tvEpisode
primaryTitle            Episode #1.24
originalTitle           Episode #1.24
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2002750, dtype: object

(9,)

tconst                                                   tt11820910
titleType                                                 tvEpisode
primaryTitle      Daniela Ray is back to take two cocks in the a...
originalTitle     Daniela Ray is back to take two cocks in the a...
isAdult                                                           1
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002751, dtype: object

(9,)

tconst                              tt11820912
titleType                            tvEpisode
primaryTitle      Cardinals Grilling Golf Cart
originalTitle     Cardinals Grilling Golf Cart
isAdult                                      0
startYear                                 2014
endYear                                     \N
runtimeMinutes                              \N
genres                              Reality-TV
Name: 2002752, dtype: object

(9,)

tconst                      tt11820914
titleType                        short
primaryTitle      Una noche en tu casa
originalTitle     Una noche en tu casa
isAdult                              0
startYear                         1986
endYear                             \N
runtimeMinutes                      \N
genres             Drama,Fantasy,Short
Name: 2002753, dtype: object

(9,)

tconst                                tt11820916
titleType                              tvEpisode
primaryTitle      Episode dated 17 November 2014
originalTitle     Episode dated 17 November 2014
isAdult                                        0
startYear                                   2014
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2002754, dtype: object

(9,)

tconst                  tt11820918
titleType                    short
primaryTitle      Hope: The Turtle
originalTitle     Hope: The Turtle
isAdult                          0
startYear                       \N
endYear                         \N
runtimeMinutes                  \N
genres             Animation,Short
Name: 2002755, dtype: object

(9,)

tconst                    tt1182091
titleType                 tvEpisode
primaryTitle           Ben and Josh
originalTitle          Ben and Josh
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   45
genres            Documentary,Drama
Name: 2002756, dtype: object

(9,)

tconst                    tt11820920
titleType                  tvEpisode
primaryTitle      52 Ford BBQ Smoker
originalTitle     52 Ford BBQ Smoker
isAdult                            0
startYear                       2014
endYear                           \N
runtimeMinutes                    \N
genres                    Reality-TV
Name: 2002757, dtype: object

(9,)

tconst                                                   tt11820922
titleType                                                 tvEpisode
primaryTitle      Daniela Ray comes back to get fucked like a bi...
originalTitle     Daniela Ray comes back to get fucked like a bi...
isAdult                                                           1
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002758, dtype: object

(9,)

tconst                 tt11820924
titleType               tvEpisode
primaryTitle      Diahann Carroll
originalTitle     Diahann Carroll
isAdult                         0
startYear                    1954
endYear                        \N
runtimeMinutes                 \N
genres                  Game-Show
Name: 2002759, dtype: object

(9,)

tconst                      tt11820926
titleType                    tvEpisode
primaryTitle      Ralph Right Reaction
originalTitle     Ralph Right Reaction
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2002760, dtype: object

(9,)

tconst                tt11820928
titleType              tvEpisode
primaryTitle      Top Fuel Diner
originalTitle     Top Fuel Diner
isAdult                        0
startYear                   2014
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2002761, dtype: object

(9,)

tconst                    tt1182092
titleType                 tvEpisode
primaryTitle        Dawn and Fabian
originalTitle       Dawn and Fabian
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   45
genres            Documentary,Drama
Name: 2002762, dtype: object

(9,)

tconst            tt11820930
titleType              short
primaryTitle       Headspace
originalTitle      Headspace
isAdult                    0
startYear               2016
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2002763, dtype: object

(9,)

tconst                                                   tt11820932
titleType                                                 tvEpisode
primaryTitle      Daniela Ray comes back to get fucked by black ...
originalTitle     Daniela Ray comes back to get fucked by black ...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002764, dtype: object

(9,)

tconst                          tt11820934
titleType                        tvEpisode
primaryTitle      School Bus Gets Grilling
originalTitle     School Bus Gets Grilling
isAdult                                  0
startYear                             2014
endYear                                 \N
runtimeMinutes                          \N
genres                          Reality-TV
Name: 2002765, dtype: object

(9,)

tconst              tt11820936
titleType            tvEpisode
primaryTitle      Victor Borge
originalTitle     Victor Borge
isAdult                      0
startYear                 1954
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2002766, dtype: object

(9,)

tconst             tt11820938
titleType            tvSeries
primaryTitle      World Class
originalTitle     World Class
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres             Reality-TV
Name: 2002767, dtype: object

(9,)

tconst               tt1182093
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002768, dtype: object

(9,)

tconst                            tt11820940
titleType                          tvEpisode
primaryTitle      The World's Largest Smoker
originalTitle     The World's Largest Smoker
isAdult                                    0
startYear                               2014
endYear                                   \N
runtimeMinutes                            \N
genres                            Reality-TV
Name: 2002769, dtype: object

(9,)

tconst                     tt11820942
titleType                   tvEpisode
primaryTitle               Evil Woods
originalTitle              Evil Woods
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Documentary,Mystery
Name: 2002770, dtype: object

(9,)

tconst              tt11820944
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 1967
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2002771, dtype: object

(9,)

tconst                             tt11820946
titleType                           tvEpisode
primaryTitle      Oyster Grilling Fire Engine
originalTitle     Oyster Grilling Fire Engine
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres                             Reality-TV
Name: 2002772, dtype: object

(9,)

tconst                                     tt11820948
titleType                                   tvEpisode
primaryTitle      Daniela Ray 3on1 Airtight DP SZ2250
originalTitle     Daniela Ray 3on1 Airtight DP SZ2250
isAdult                                             1
startYear                                        2019
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2002773, dtype: object

(9,)

tconst                                   tt1182094
titleType                                tvEpisode
primaryTitle      Julie Jensen: Suicide or Murder?
originalTitle     Julie Jensen: Suicide or Murder?
isAdult                                          0
startYear                                     2008
endYear                                         \N
runtimeMinutes                                  \N
genres                                  Reality-TV
Name: 2002774, dtype: object

(9,)

tconst                   tt11820950
titleType                     movie
primaryTitle      The Portable Door
originalTitle     The Portable Door
isAdult                           0
startYear                      2022
endYear                          \N
runtimeMinutes                   \N
genres                      Fantasy
Name: 2002775, dtype: object

(9,)

tconst               tt11820952
titleType             tvEpisode
primaryTitle      El Camino BBQ
originalTitle     El Camino BBQ
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2002776, dtype: object

(9,)

tconst                    tt11820954
titleType                  tvEpisode
primaryTitle      Kirkwood & Goodman
originalTitle     Kirkwood & Goodman
isAdult                            0
startYear                       1954
endYear                           \N
runtimeMinutes                    \N
genres                        Comedy
Name: 2002777, dtype: object

(9,)

tconst                  tt11820958
titleType                tvEpisode
primaryTitle      1962 Porsche BBQ
originalTitle     1962 Porsche BBQ
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres                  Reality-TV
Name: 2002778, dtype: object

(9,)

tconst                                   tt1182095
titleType                                tvEpisode
primaryTitle      Supermodels Starving for Success
originalTitle     Supermodels Starving for Success
isAdult                                          0
startYear                                     1993
endYear                                         \N
runtimeMinutes                                  \N
genres                                   Talk-Show
Name: 2002779, dtype: object

(9,)

tconst             tt11820960
titleType           tvEpisode
primaryTitle      Roger Price
originalTitle     Roger Price
isAdult                     0
startYear                1954
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2002780, dtype: object

(9,)

tconst               tt11820966
titleType              tvSeries
primaryTitle      Rambler Ranch
originalTitle     Rambler Ranch
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2002781, dtype: object

(9,)

tconst                           tt11820968
titleType                         tvEpisode
primaryTitle      High School Grilling Jeep
originalTitle     High School Grilling Jeep
isAdult                                   0
startYear                              2014
endYear                                  \N
runtimeMinutes                           \N
genres                           Reality-TV
Name: 2002782, dtype: object

(9,)

tconst               tt1182096
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1975
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002783, dtype: object

(9,)

tconst                      tt11820970
titleType                     tvSeries
primaryTitle      Au pays des Mitchifs
originalTitle     Au pays des Mitchifs
isAdult                              0
startYear                         2017
endYear                             \N
runtimeMinutes                      22
genres                     Documentary
Name: 2002784, dtype: object

(9,)

tconst                       tt11820972
titleType                       tvMovie
primaryTitle      Sick Day Morning Show
originalTitle     Sick Day Morning Show
isAdult                               0
startYear                          2013
endYear                              \N
runtimeMinutes                       22
genres                           Comedy
Name: 2002785, dtype: object

(9,)

tconst                         tt11820974
titleType                       tvEpisode
primaryTitle      Inspection Day on Sodor
originalTitle     Inspection Day on Sodor
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                          9
genres                   Animation,Family
Name: 2002786, dtype: object

(9,)

tconst                                         tt11820976
titleType                                       tvEpisode
primaryTitle      Daniela Ray #1 - Bukkake - First Camera
originalTitle     Daniela Ray #1 - Bukkake - First Camera
isAdult                                                 1
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                                 \N
Name: 2002787, dtype: object

(9,)

tconst                                          tt11820978
titleType                                        tvEpisode
primaryTitle      Daniela Ray #1 - Bukkake - Second Camera
originalTitle     Daniela Ray #1 - Bukkake - Second Camera
isAdult                                                  1
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                                  \N
Name: 2002788, dtype: object

(9,)

tconst                                tt1182097
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2002789, dtype: object

(9,)

tconst                     tt11820980
titleType                   tvSpecial
primaryTitle      Travel Channel Star
originalTitle     Travel Channel Star
isAdult                             0
startYear                        2015
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2002790, dtype: object

(9,)

tconst                   tt11820982
titleType                 tvEpisode
primaryTitle      Tailgating Tundra
originalTitle     Tailgating Tundra
isAdult                           0
startYear                      2014
endYear                          \N
runtimeMinutes                   \N
genres                   Reality-TV
Name: 2002791, dtype: object

(9,)

tconst                                              tt11820984
titleType                                            tvEpisode
primaryTitle      Daniela Ray #1 - Bukkake - Behind the Scence
originalTitle     Daniela Ray #1 - Bukkake - Behind the Scence
isAdult                                                      1
startYear                                                 2020
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                      \N
Name: 2002792, dtype: object

(9,)

tconst                 tt11820988
titleType               tvEpisode
primaryTitle      Episode #1.1931
originalTitle     Episode #1.1931
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2002793, dtype: object

(9,)

tconst                                tt1182098
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2002794, dtype: object

(9,)

tconst                tt11820990
titleType              tvEpisode
primaryTitle      Georgia-Part 1
originalTitle     Georgia-Part 1
isAdult                        0
startYear                   2014
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2002795, dtype: object

(9,)

tconst                                     tt11820994
titleType                                       movie
primaryTitle      Xiang Gang Dong Jing mi yue lu xing
originalTitle     Xiang Gang Dong Jing mi yue lu xing
isAdult                                             0
startYear                                        1957
endYear                                            \N
runtimeMinutes                                     \N
genres                                         Comedy
Name: 2002796, dtype: object

(9,)

tconst                  tt11820996
titleType                    short
primaryTitle      Here's the Thing
originalTitle     Here's the Thing
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                Comedy,Short
Name: 2002797, dtype: object

(9,)

tconst                                     tt11820998
titleType                                   tvEpisode
primaryTitle      O judu, gumbkih in gnusnih napitkih
originalTitle     O judu, gumbkih in gnusnih napitkih
isAdult                                             0
startYear                                        2014
endYear                                            \N
runtimeMinutes                                     \N
genres                                  Comedy,Family
Name: 2002798, dtype: object

(9,)

tconst                          tt1182099
titleType                       tvEpisode
primaryTitle              Art+Science=Fun
originalTitle             Art+Science=Fun
isAdult                                 0
startYear                            1997
endYear                                \N
runtimeMinutes                         \N
genres            Animation,Comedy,Family
Name: 2002799, dtype: object

(9,)

tconst                           tt11821000
titleType                      tvMiniSeries
primaryTitle      American Television Icons
originalTitle     American Television Icons
isAdult                                   0
startYear                              2000
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2002800, dtype: object

(9,)

tconst                                           tt11821002
titleType                                         tvEpisode
primaryTitle      O zlikrofih, boksu in napihljivih misicah
originalTitle     O zlikrofih, boksu in napihljivih misicah
isAdult                                                   0
startYear                                              2014
endYear                                                  \N
runtimeMinutes                                           \N
genres                                        Comedy,Family
Name: 2002801, dtype: object

(9,)

tconst             tt11821004
titleType               short
primaryTitle            Chaos
originalTitle           Chaos
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2002802, dtype: object

(9,)

tconst                           tt11821006
titleType                         tvEpisode
primaryTitle      A Grilling Gift for Santa
originalTitle     A Grilling Gift for Santa
isAdult                                   0
startYear                              2014
endYear                                  \N
runtimeMinutes                           \N
genres                           Reality-TV
Name: 2002803, dtype: object

(9,)

tconst                                       tt11821008
titleType                                     tvEpisode
primaryTitle      Sir Topham Hatt's Christmas Surprise!
originalTitle     Sir Topham Hatt's Christmas Surprise!
isAdult                                               0
startYear                                          2019
endYear                                              \N
runtimeMinutes                                        9
genres                                 Animation,Family
Name: 2002804, dtype: object

(9,)

tconst                       tt1182100
titleType                    tvEpisode
primaryTitle      Antio, kyrie ypourge
originalTitle     Antio, kyrie ypourge
isAdult                              0
startYear                         2005
endYear                             \N
runtimeMinutes                      \N
genres                          Comedy
Name: 2002805, dtype: object

(9,)

tconst                 tt11821010
titleType               tvEpisode
primaryTitle      Episode #1.1933
originalTitle     Episode #1.1933
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 24
genres              Drama,Romance
Name: 2002806, dtype: object

(9,)

tconst                tt11821012
titleType              tvEpisode
primaryTitle      Georgia-Part 2
originalTitle     Georgia-Part 2
isAdult                        0
startYear                   2014
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2002807, dtype: object

(9,)

tconst                                                   tt11821014
titleType                                                 tvEpisode
primaryTitle      O ledenih skulpturah, prijaznem Gasperju in no...
originalTitle     O ledenih skulpturah, prijaznem Gasperju in no...
isAdult                                                           0
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2002808, dtype: object

(9,)

tconst                                      tt11821016
titleType                                        movie
primaryTitle      The Incredible Hulik and His Beavers
originalTitle     The Incredible Hulik and His Beavers
isAdult                                              0
startYear                                         2002
endYear                                             \N
runtimeMinutes                                      50
genres                                     Documentary
Name: 2002809, dtype: object

(9,)

tconst               tt11821018
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002810, dtype: object

(9,)

tconst                tt1182101
titleType             tvEpisode
primaryTitle       Episode #1.7
originalTitle      Episode #1.7
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               53
genres            Drama,Romance
Name: 2002811, dtype: object

(9,)

tconst                     tt11821020
titleType                       short
primaryTitle                Incidente
originalTitle               Incidente
isAdult                             0
startYear                        1988
endYear                            \N
runtimeMinutes                     12
genres            Crime,Drama,Fantasy
Name: 2002812, dtype: object

(9,)

tconst                                   tt11821022
titleType                                 tvEpisode
primaryTitle      Maintaining Your Grilling Machine
originalTitle     Maintaining Your Grilling Machine
isAdult                                           0
startYear                                      2015
endYear                                          \N
runtimeMinutes                                   \N
genres                                   Reality-TV
Name: 2002813, dtype: object

(9,)

tconst                 tt11821024
titleType               tvEpisode
primaryTitle      Episode #1.8746
originalTitle     Episode #1.8746
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 22
genres              Drama,Romance
Name: 2002814, dtype: object

(9,)

tconst                                                   tt11821026
titleType                                                 tvEpisode
primaryTitle      Bill Hayes, Sandra Deel, Jimmy Nelson & Danny ...
originalTitle     Bill Hayes, Sandra Deel, Jimmy Nelson & Danny ...
isAdult                                                           0
startYear                                                      1954
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                          Comedy,Family,Music
Name: 2002815, dtype: object

(9,)

tconst                 tt11821028
titleType                tvSeries
primaryTitle      ESPN Nexo Chile
originalTitle     ESPN Nexo Chile
isAdult                         0
startYear                    2017
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2002816, dtype: object

(9,)

tconst                                                  tt1182102
titleType                                               tvEpisode
primaryTitle      Holly Robinson Peete, Doug Flutie, Toni Braxton
originalTitle     Holly Robinson Peete, Doug Flutie, Toni Braxton
isAdult                                                         0
startYear                                                    2008
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                             News,Talk-Show
Name: 2002817, dtype: object

(9,)

tconst                 tt11821030
titleType               tvEpisode
primaryTitle      Episode #1.8747
originalTitle     Episode #1.8747
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 22
genres              Drama,Romance
Name: 2002818, dtype: object

(9,)

tconst                 tt11821032
titleType               tvEpisode
primaryTitle      Welcome to Suhn
originalTitle     Welcome to Suhn
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 30
genres                     Action
Name: 2002819, dtype: object

(9,)

tconst            tt11821034
titleType              movie
primaryTitle       Vibration
originalTitle      Vibration
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            73
genres                Horror
Name: 2002820, dtype: object

(9,)

tconst             tt11821036
titleType            tvSeries
primaryTitle      Heaux Phase
originalTitle     Heaux Phase
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2002821, dtype: object

(9,)

tconst               tt11821038
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002822, dtype: object

(9,)

tconst                                  tt1182103
titleType                               tvEpisode
primaryTitle      Michael Moore and Ari Fleischer
originalTitle     Michael Moore and Ari Fleischer
isAdult                                         0
startYear                                    2008
endYear                                        \N
runtimeMinutes                                 \N
genres                             News,Talk-Show
Name: 2002823, dtype: object

(9,)

tconst                              tt11821040
titleType                            tvEpisode
primaryTitle      O odrih, slavi in metronomih
originalTitle     O odrih, slavi in metronomih
isAdult                                      0
startYear                                 2015
endYear                                     \N
runtimeMinutes                              \N
genres                           Comedy,Family
Name: 2002824, dtype: object

(9,)

tconst              tt11821042
titleType                short
primaryTitle       First Birth
originalTitle      First Birth
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2002825, dtype: object

(9,)

tconst                 tt11821046
titleType               tvEpisode
primaryTitle      Tai Chi Racers!
originalTitle     Tai Chi Racers!
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 30
genres                     Action
Name: 2002826, dtype: object

(9,)

tconst                         tt11821048
titleType                       tvEpisode
primaryTitle      Pandora the Maid part 1
originalTitle     Pandora the Maid part 1
isAdult                                 1
startYear                            2007
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2002827, dtype: object

(9,)

tconst                        tt1182104
titleType                     tvEpisode
primaryTitle      New Holloway Evidence
originalTitle     New Holloway Evidence
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres                   News,Talk-Show
Name: 2002828, dtype: object

(9,)

tconst                           tt11821050
titleType                         tvEpisode
primaryTitle      Fayth in 3 different ties
originalTitle     Fayth in 3 different ties
isAdult                                   1
startYear                              2007
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2002829, dtype: object

(9,)

tconst              tt11821052
titleType            tvEpisode
primaryTitle      The Incident
originalTitle     The Incident
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              30
genres                  Action
Name: 2002830, dtype: object

(9,)

tconst               tt11821054
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002831, dtype: object

(9,)

tconst            tt11821056
titleType          tvEpisode
primaryTitle        Lockdown
originalTitle       Lockdown
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Adventure
Name: 2002832, dtype: object

(9,)

tconst                                     tt11821058
titleType                                   tvEpisode
primaryTitle      O voditeljih, badmintonu in zemljah
originalTitle     O voditeljih, badmintonu in zemljah
isAdult                                             0
startYear                                        2015
endYear                                            \N
runtimeMinutes                                     \N
genres                                  Comedy,Family
Name: 2002833, dtype: object

(9,)

tconst                                 tt1182105
titleType                              tvEpisode
primaryTitle      Episode dated 25 November 1967
originalTitle     Episode dated 25 November 1967
isAdult                                        0
startYear                                   1967
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2002834, dtype: object

(9,)

tconst                       tt11821060
titleType                     tvEpisode
primaryTitle      Elaine shocks Pandora
originalTitle     Elaine shocks Pandora
isAdult                               1
startYear                          2007
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2002835, dtype: object

(9,)

tconst                       tt11821064
titleType                     tvEpisode
primaryTitle      Tournament of Chasers
originalTitle     Tournament of Chasers
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       30
genres                           Action
Name: 2002836, dtype: object

(9,)

tconst                          tt11821066
titleType                        tvEpisode
primaryTitle      Britney Brooks in 2 ties
originalTitle     Britney Brooks in 2 ties
isAdult                                  1
startYear                             2007
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2002837, dtype: object

(9,)

tconst                   tt11821068
titleType                  tvSeries
primaryTitle      Stand Up Sessions
originalTitle     Stand Up Sessions
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   45
genres                       Comedy
Name: 2002838, dtype: object

(9,)

tconst                                       tt1182106
titleType                                    tvEpisode
primaryTitle      Steve Irwin/Paul Giamatti/The Zutons
originalTitle     Steve Irwin/Paul Giamatti/The Zutons
isAdult                                              0
startYear                                         2004
endYear                                             \N
runtimeMinutes                                      \N
genres                          Comedy,Music,Talk-Show
Name: 2002839, dtype: object

(9,)

tconst                                 tt11821070
titleType                               tvEpisode
primaryTitle      Samantha Grace's rude awakening
originalTitle     Samantha Grace's rude awakening
isAdult                                         1
startYear                                    2007
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2002840, dtype: object

(9,)

tconst               tt11821072
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002841, dtype: object

(9,)

tconst             tt11821074
titleType           tvEpisode
primaryTitle              Soy
originalTitle             Soy
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2002842, dtype: object

(9,)

tconst                       tt11821076
titleType                     tvEpisode
primaryTitle      Pandora and her watch
originalTitle     Pandora and her watch
isAdult                               1
startYear                          2007
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2002843, dtype: object

(9,)

tconst                          tt11821078
titleType                        tvEpisode
primaryTitle      Filming Love Drama Story
originalTitle     Filming Love Drama Story
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                               Drama
Name: 2002844, dtype: object

(9,)

tconst                                 tt1182107
titleType                              tvEpisode
primaryTitle      Invasion of the Booby Hatchers
originalTitle     Invasion of the Booby Hatchers
isAdult                                        0
startYear                                   1981
endYear                                       \N
runtimeMinutes                                \N
genres                          Animation,Family
Name: 2002845, dtype: object

(9,)

tconst               tt11821080
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002846, dtype: object

(9,)

tconst                                                 tt11821082
titleType                                                 tvMovie
primaryTitle      Fascism in the Family: Al Jazeera Correspondent
originalTitle     Fascism in the Family: Al Jazeera Correspondent
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 50
genres                                                Documentary
Name: 2002847, dtype: object

(9,)

tconst               tt11821084
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002848, dtype: object

(9,)

tconst                         tt11821086
titleType                           movie
primaryTitle      Night of the Salamander
originalTitle     Night of the Salamander
isAdult                                 0
startYear                            2001
endYear                                \N
runtimeMinutes                         51
genres                        Documentary
Name: 2002849, dtype: object

(9,)

tconst                                                   tt11821088
titleType                                                 tvEpisode
primaryTitle      Alene Dalton (The Story Princess), Charlie Rug...
originalTitle     Alene Dalton (The Story Princess), Charlie Rug...
isAdult                                                           0
startYear                                                      1954
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                          Comedy,Family,Music
Name: 2002850, dtype: object

(9,)

tconst                            tt1182108
titleType                      tvMiniSeries
primaryTitle      The Legend of Liam Clancy
originalTitle     The Legend of Liam Clancy
isAdult                                   0
startYear                              2006
endYear                                  \N
runtimeMinutes                           \N
genres                          Documentary
Name: 2002851, dtype: object

(9,)

tconst                                     tt11821090
titleType                                   tvEpisode
primaryTitle      Battle for Los Angeles/Easy Brees-y
originalTitle     Battle for Los Angeles/Easy Brees-y
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                    120
genres                           News,Sport,Talk-Show
Name: 2002852, dtype: object

(9,)

tconst               tt11821092
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002853, dtype: object

(9,)

tconst                                tt11821094
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2002854, dtype: object

(9,)

tconst                                                   tt11821096
titleType                                                     video
primaryTitle      ED chiryô: Iryô konsheruju takimoto rie - Kaku...
originalTitle     ED chiryô: Iryô konsheruju takimoto rie - Kaku...
isAdult                                                           1
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                  169
genres                                            Adult,Documentary
Name: 2002855, dtype: object

(9,)

tconst                             tt11821098
titleType                           tvSpecial
primaryTitle      Alexandre Santos - Stand Up
originalTitle     Alexandre Santos - Stand Up
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                            220
genres                                 Comedy
Name: 2002856, dtype: object

(9,)

tconst                  tt1182109
titleType               tvEpisode
primaryTitle      Episode #12.104
originalTitle     Episode #12.104
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2002857, dtype: object

(9,)

tconst                     tt11821100
titleType                   tvEpisode
primaryTitle             Rusty Draper
originalTitle            Rusty Draper
isAdult                             0
startYear                        1954
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Family,Music
Name: 2002858, dtype: object

(9,)

tconst              tt11821102
titleType                short
primaryTitle        Bad Tenant
originalTitle       Bad Tenant
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              10
genres            Comedy,Short
Name: 2002859, dtype: object

(9,)

tconst                                       tt11821104
titleType                                     tvEpisode
primaryTitle      Runaway Lilith/The Hughesville Howler
originalTitle     Runaway Lilith/The Hughesville Howler
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                       Action,Adventure,Animation
Name: 2002860, dtype: object

(9,)

tconst                             tt11821106
titleType                           tvEpisode
primaryTitle      Faye "Tartan Upskirt Tease"
originalTitle     Faye "Tartan Upskirt Tease"
isAdult                                     1
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2002861, dtype: object

(9,)

tconst                      tt11821108
titleType                        short
primaryTitle         One Hell of a Day
originalTitle        One Hell of a Day
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Fantasy,Short
Name: 2002862, dtype: object

(9,)

tconst                  tt1182110
titleType               tvEpisode
primaryTitle      Episode #12.105
originalTitle     Episode #12.105
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2002863, dtype: object

(9,)

tconst               tt11821110
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002864, dtype: object

(9,)

tconst                   tt11821112
titleType                     short
primaryTitle      El cometa perdido
originalTitle     El cometa perdido
isAdult                           0
startYear                        \N
endYear                          \N
runtimeMinutes                   \N
genres                        Short
Name: 2002865, dtype: object

(9,)

tconst                          tt11821114
titleType                        tvEpisode
primaryTitle      Lexus "Take A Good Look"
originalTitle     Lexus "Take A Good Look"
isAdult                                  1
startYear                             2015
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2002866, dtype: object

(9,)

tconst               tt11821116
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002867, dtype: object

(9,)

tconst                            tt11821118
titleType                           tvSeries
primaryTitle      Son of wolverine and storm
originalTitle     Son of wolverine and storm
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                Sci-Fi
Name: 2002868, dtype: object

(9,)

tconst              tt1182111
titleType            tvSeries
primaryTitle          Léargas
originalTitle         Léargas
isAdult                     0
startYear                1996
endYear                  2008
runtimeMinutes             \N
genres            Documentary
Name: 2002869, dtype: object

(9,)

tconst                        tt11821120
titleType                      tvEpisode
primaryTitle      Nicole "Dirty Pervert"
originalTitle     Nicole "Dirty Pervert"
isAdult                                1
startYear                           2015
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2002870, dtype: object

(9,)

tconst            tt11821122
titleType              movie
primaryTitle        Obsidian
originalTitle       Obsidian
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes           101
genres                Horror
Name: 2002871, dtype: object

(9,)

tconst                     tt11821124
titleType                       short
primaryTitle              Enajenación
originalTitle             Enajenación
isAdult                             0
startYear                        1995
endYear                            \N
runtimeMinutes                     11
genres            Drama,Fantasy,Short
Name: 2002872, dtype: object

(9,)

tconst               tt11821126
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002873, dtype: object

(9,)

tconst                  tt11821128
titleType                    video
primaryTitle      Jota y Deby-Malo
originalTitle     Jota y Deby-Malo
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                 Music,Short
Name: 2002874, dtype: object

(9,)

tconst                   tt1182112
titleType                tvEpisode
primaryTitle        Episode #3.228
originalTitle       Episode #3.228
isAdult                          0
startYear                     1975
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2002875, dtype: object

(9,)

tconst                            tt11821130
titleType                              movie
primaryTitle      Spring: The Return of Life
originalTitle     Spring: The Return of Life
isAdult                                    0
startYear                               2014
endYear                                   \N
runtimeMinutes                            49
genres                           Documentary
Name: 2002876, dtype: object

(9,)

tconst               tt11821132
titleType             tvEpisode
primaryTitle      Chasernapped!
originalTitle     Chasernapped!
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               30
genres                   Action
Name: 2002877, dtype: object

(9,)

tconst                                                   tt11821134
titleType                                                 tvEpisode
primaryTitle      Swallow Salo Welcomes Kaylani Kao For a Blowjo...
originalTitle     Swallow Salo Welcomes Kaylani Kao For a Blowjo...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2002878, dtype: object

(9,)

tconst               tt11821136
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002879, dtype: object

(9,)

tconst               tt1182113
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002880, dtype: object

(9,)

tconst            tt11821140
titleType          tvEpisode
primaryTitle          Ílhavo
originalTitle         Ílhavo
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2002881, dtype: object

(9,)

tconst                                    tt11821142
titleType                                  tvEpisode
primaryTitle      Go Go dancer gives him a VIP dance
originalTitle     Go Go dancer gives him a VIP dance
isAdult                                            1
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2002882, dtype: object

(9,)

tconst               tt11821144
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002883, dtype: object

(9,)

tconst               tt11821146
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002884, dtype: object

(9,)

tconst                                                   tt11821148
titleType                                                 tvEpisode
primaryTitle      Al Bernie, Dorothy Day, Scott McKay, Joan Morg...
originalTitle     Al Bernie, Dorothy Day, Scott McKay, Joan Morg...
isAdult                                                           0
startYear                                                      1954
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                          Comedy,Family,Music
Name: 2002885, dtype: object

(9,)

tconst                  tt1182114
titleType               tvEpisode
primaryTitle      The Truth Hurts
originalTitle     The Truth Hurts
isAdult                         0
startYear                    1965
endYear                        \N
runtimeMinutes                 30
genres                 Comedy,War
Name: 2002886, dtype: object

(9,)

tconst                    tt11821152
titleType                  tvEpisode
primaryTitle      False Alarm Part 2
originalTitle     False Alarm Part 2
isAdult                            1
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2002887, dtype: object

(9,)

tconst               tt11821156
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002888, dtype: object

(9,)

tconst                                tt1182115
titleType                             tvEpisode
primaryTitle      Episode dated 2 February 2006
originalTitle     Episode dated 2 February 2006
isAdult                                       0
startYear                                  2006
endYear                                      \N
runtimeMinutes                               \N
genres                            Drama,Romance
Name: 2002889, dtype: object

(9,)

tconst                                                   tt11821160
titleType                                                 tvEpisode
primaryTitle      Hitler vs Vader 3. Epic Rap Battles of History...
originalTitle     Hitler vs Vader 3. Epic Rap Battles of History...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                    6
genres                                                    Talk-Show
Name: 2002890, dtype: object

(9,)

tconst                       tt11821164
titleType                         short
primaryTitle      Live What You Believe
originalTitle     Live What You Believe
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                            Short
Name: 2002891, dtype: object

(9,)

tconst                         tt11821166
titleType                       tvEpisode
primaryTitle      Showdown Against Mishka
originalTitle     Showdown Against Mishka
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         30
genres                             Action
Name: 2002892, dtype: object

(9,)

tconst                          tt11821168
titleType                        tvEpisode
primaryTitle      DFP Academy: Dick's Pics
originalTitle     DFP Academy: Dick's Pics
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2002893, dtype: object

(9,)

tconst                            tt1182116
titleType                         tvEpisode
primaryTitle      The Mother of All In-Laws
originalTitle     The Mother of All In-Laws
isAdult                                   0
startYear                              1995
endYear                                  \N
runtimeMinutes                           \N
genres                       Comedy,Romance
Name: 2002894, dtype: object

(9,)

tconst              tt11821170
titleType                short
primaryTitle       Halloween 4
originalTitle      Halloween 4
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres            Horror,Short
Name: 2002895, dtype: object

(9,)

tconst                               tt11821172
titleType                             tvEpisode
primaryTitle      Three Coins 'n' She's Poutin'
originalTitle     Three Coins 'n' She's Poutin'
isAdult                                       1
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2002896, dtype: object

(9,)

tconst               tt11821174
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002897, dtype: object

(9,)

tconst             tt11821176
titleType               short
primaryTitle      The Present
originalTitle         Sunmool
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             43
genres            Drama,Short
Name: 2002898, dtype: object

(9,)

tconst                       tt11821178
titleType                         movie
primaryTitle      Sumatra's Last Tigers
originalTitle     Sumatra's Last Tigers
isAdult                               0
startYear                          2015
endYear                              \N
runtimeMinutes                       46
genres                      Documentary
Name: 2002899, dtype: object

(9,)

tconst               tt1182117
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002900, dtype: object

(9,)

tconst                                                   tt11821180
titleType                                                 tvEpisode
primaryTitle      Einstein vs Stephen Hawking Epic Rap Battles o...
originalTitle     Einstein vs Stephen Hawking Epic Rap Battles o...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                    9
genres                                                    Talk-Show
Name: 2002901, dtype: object

(9,)

tconst                               tt11821182
titleType                             tvEpisode
primaryTitle      DFP Academy: Private Tutoring
originalTitle     DFP Academy: Private Tutoring
isAdult                                       1
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2002902, dtype: object

(9,)

tconst                 tt11821184
titleType               tvEpisode
primaryTitle      Rub-a-dub-dub 2
originalTitle     Rub-a-dub-dub 2
isAdult                         1
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2002903, dtype: object

(9,)

tconst                                          tt11821186
titleType                                        tvEpisode
primaryTitle      Georgia-Persian Rock & Metal Fest-Part 3
originalTitle     Georgia-Persian Rock & Metal Fest-Part 3
isAdult                                                  0
startYear                                             2014
endYear                                                 \N
runtimeMinutes                                          \N
genres                                          Reality-TV
Name: 2002904, dtype: object

(9,)

tconst                                                   tt11821188
titleType                                                   tvMovie
primaryTitle      Second Sight Paranormal TV the Haunting of the...
originalTitle                        The Haunting of the Malaga Inn
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   27
genres                                                        Drama
Name: 2002905, dtype: object

(9,)

tconst                tt1182118
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2002906, dtype: object

(9,)

tconst                                                   tt11821190
titleType                                                 tvEpisode
primaryTitle      Donald Trump vs Hillary Clinton Epic Rap Battl...
originalTitle     Donald Trump vs Hillary Clinton Epic Rap Battl...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                   11
genres                                                    Talk-Show
Name: 2002907, dtype: object

(9,)

tconst                                        tt11821192
titleType                                      tvEpisode
primaryTitle      DFP Academy: She Saw Sadie in Person 2
originalTitle     DFP Academy: She Saw Sadie in Person 2
isAdult                                                1
startYear                                           2018
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Adult
Name: 2002908, dtype: object

(9,)

tconst               tt11821194
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002909, dtype: object

(9,)

tconst                        tt11821196
titleType                      tvEpisode
primaryTitle      Hand in the Cookie Jar
originalTitle     Hand in the Cookie Jar
isAdult                                1
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2002910, dtype: object

(9,)

tconst              tt11821198
titleType            tvEpisode
primaryTitle      Episode #3.7
originalTitle     Episode #3.7
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              29
genres               Talk-Show
Name: 2002911, dtype: object

(9,)

tconst                tt1182119
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2002912, dtype: object

(9,)

tconst              tt11821200
titleType            tvEpisode
primaryTitle      Episode #3.8
originalTitle     Episode #3.8
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              59
genres               Talk-Show
Name: 2002913, dtype: object

(9,)

tconst                                                   tt11821202
titleType                                                     short
primaryTitle      Proibida a Entrada a Pessoas Estranhas aos Navios
originalTitle     Proibida a Entrada a Pessoas Estranhas aos Navios
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   22
genres                                            Documentary,Short
Name: 2002914, dtype: object

(9,)

tconst                                          tt11821204
titleType                                        tvEpisode
primaryTitle      DFP Academy: Not in Kansas Anymore Pt. 2
originalTitle     DFP Academy: Not in Kansas Anymore Pt. 2
isAdult                                                  1
startYear                                             2018
endYear                                                 \N
runtimeMinutes                                          \N
genres                                               Adult
Name: 2002915, dtype: object

(9,)

tconst                                  tt11821206
titleType                                    short
primaryTitle      Able Me - Disability Boxing Club
originalTitle     Able Me - Disability Boxing Club
isAdult                                          0
startYear                                     2019
endYear                                         \N
runtimeMinutes                                   1
genres                             Biography,Short
Name: 2002916, dtype: object

(9,)

tconst                                     tt11821208
titleType                                   tvEpisode
primaryTitle      DFP Academy: Disciplinary Doctrines
originalTitle     DFP Academy: Disciplinary Doctrines
isAdult                                             1
startYear                                        2018
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2002917, dtype: object

(9,)

tconst                tt1182120
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2002918, dtype: object

(9,)

tconst               tt11821210
titleType             tvEpisode
primaryTitle      Episode #4.88
originalTitle     Episode #4.88
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2002919, dtype: object

(9,)

tconst                                    tt11821212
titleType                                  tvEpisode
primaryTitle      Electro Neurological Functionality
originalTitle     Electro Neurological Functionality
isAdult                                            1
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2002920, dtype: object

(9,)

tconst                               tt11821214
titleType                             tvEpisode
primaryTitle      DFP Academy: Student Feedback
originalTitle     DFP Academy: Student Feedback
isAdult                                       1
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2002921, dtype: object

(9,)

tconst              tt11821216
titleType              tvShort
primaryTitle          Senataur
originalTitle         Senataur
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              21
genres            Comedy,Short
Name: 2002922, dtype: object

(9,)

tconst                        tt11821218
titleType                      tvEpisode
primaryTitle      DFP Academy: Mirth Day
originalTitle     DFP Academy: Mirth Day
isAdult                                1
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2002923, dtype: object

(9,)

tconst               tt1182121
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002924, dtype: object

(9,)

tconst                     tt11821220
titleType                       short
primaryTitle      Un Giorno di estate
originalTitle     Un Giorno di estate
isAdult                             0
startYear                        2009
endYear                            \N
runtimeMinutes                      4
genres                          Short
Name: 2002925, dtype: object

(9,)

tconst                                       tt11821222
titleType                                     tvEpisode
primaryTitle      DFP Academy: Breaking in the New Girl
originalTitle     DFP Academy: Breaking in the New Girl
isAdult                                               1
startYear                                          2018
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Adult
Name: 2002926, dtype: object

(9,)

tconst                           tt11821224
titleType                         tvEpisode
primaryTitle      Hasta La Fashionista Baby
originalTitle     Hasta La Fashionista Baby
isAdult                                   1
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2002927, dtype: object

(9,)

tconst                             tt11821226
titleType                           tvEpisode
primaryTitle                  Episode #21.136
originalTitle                 Episode #21.136
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Comedy,Game-Show,Reality-TV
Name: 2002928, dtype: object

(9,)

tconst               tt11821228
titleType             tvEpisode
primaryTitle      Episode #11.2
originalTitle     Episode #11.2
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002929, dtype: object

(9,)

tconst               tt1182122
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002930, dtype: object

(9,)

tconst                                      tt11821230
titleType                                    tvEpisode
primaryTitle      DFP Academy: Inspecting the New Girl
originalTitle     DFP Academy: Inspecting the New Girl
isAdult                                              1
startYear                                         2018
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Adult
Name: 2002931, dtype: object

(9,)

tconst                                   tt11821232
titleType                                 tvEpisode
primaryTitle      DFP Academy: What Dreams May Come
originalTitle     DFP Academy: What Dreams May Come
isAdult                                           1
startYear                                      2018
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2002932, dtype: object

(9,)

tconst                             tt11821234
titleType                           tvEpisode
primaryTitle                  Episode #21.137
originalTitle                 Episode #21.137
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Comedy,Game-Show,Reality-TV
Name: 2002933, dtype: object

(9,)

tconst                         tt11821238
titleType                       tvEpisode
primaryTitle      Two Tickets to Paradise
originalTitle     Two Tickets to Paradise
isAdult                                 1
startYear                            2018
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2002934, dtype: object

(9,)

tconst               tt1182123
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002935, dtype: object

(9,)

tconst                                          tt11821242
titleType                                        tvEpisode
primaryTitle      DFP Academy: Not in Kansas Anymore Pt. 3
originalTitle     DFP Academy: Not in Kansas Anymore Pt. 3
isAdult                                                  1
startYear                                             2018
endYear                                                 \N
runtimeMinutes                                          \N
genres                                               Adult
Name: 2002936, dtype: object

(9,)

tconst               tt11821244
titleType             tvEpisode
primaryTitle      We Goin Again
originalTitle     We Goin Again
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2002937, dtype: object

(9,)

tconst              tt11821246
titleType            tvEpisode
primaryTitle      Bare Minimum
originalTitle     Bare Minimum
isAdult                      1
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2002938, dtype: object

(9,)

tconst                                          tt11821248
titleType                                        tvEpisode
primaryTitle      DFP Academy: Not in Kansas Anymore Pt. 4
originalTitle     DFP Academy: Not in Kansas Anymore Pt. 4
isAdult                                                  1
startYear                                             2018
endYear                                                 \N
runtimeMinutes                                          \N
genres                                               Adult
Name: 2002939, dtype: object

(9,)

tconst               tt1182124
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002940, dtype: object

(9,)

tconst                             tt11821250
titleType                           tvEpisode
primaryTitle      DFP Academy: Scavenger Hunt
originalTitle     DFP Academy: Scavenger Hunt
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2002941, dtype: object

(9,)

tconst                   tt11821252
titleType                 tvEpisode
primaryTitle      Good Doc, Bad Doc
originalTitle     Good Doc, Bad Doc
isAdult                           1
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2002942, dtype: object

(9,)

tconst                                  tt11821254
titleType                                tvEpisode
primaryTitle      DFP Academy: Akira & Luci Part 1
originalTitle     DFP Academy: Akira & Luci Part 1
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2002943, dtype: object

(9,)

tconst                      tt11821256
titleType                    tvEpisode
primaryTitle              Episode #1.7
originalTitle             Episode #1.7
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002944, dtype: object

(9,)

tconst                        tt11821258
titleType                      tvEpisode
primaryTitle      DFP Academy: The Bruja
originalTitle     DFP Academy: The Bruja
isAdult                                1
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2002945, dtype: object

(9,)

tconst               tt1182125
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002946, dtype: object

(9,)

tconst                      tt11821260
titleType                    tvEpisode
primaryTitle              Episode #1.8
originalTitle             Episode #1.8
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002947, dtype: object

(9,)

tconst                       tt11821262
titleType                     tvEpisode
primaryTitle               Episode #1.1
originalTitle              Episode #1.1
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Fantasy,Romance
Name: 2002948, dtype: object

(9,)

tconst                                  tt11821264
titleType                                tvEpisode
primaryTitle      DFP Academy: Akira & Luci Part 2
originalTitle     DFP Academy: Akira & Luci Part 2
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2002949, dtype: object

(9,)

tconst                  tt11821266
titleType                    movie
primaryTitle      The Goose Gospel
originalTitle     The Goose Gospel
isAdult                          0
startYear                     2012
endYear                         \N
runtimeMinutes                  \N
genres                       Sport
Name: 2002950, dtype: object

(9,)

tconst                             tt11821268
titleType                           tvEpisode
primaryTitle      DFP Academy: Stress Testing
originalTitle     DFP Academy: Stress Testing
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2002951, dtype: object

(9,)

tconst               tt1182126
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002952, dtype: object

(9,)

tconst                           tt11821270
titleType                         tvEpisode
primaryTitle      DFP Academy: Making Piece
originalTitle     DFP Academy: Making Piece
isAdult                                   1
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2002953, dtype: object

(9,)

tconst                      tt11821272
titleType                    tvEpisode
primaryTitle              Episode #1.9
originalTitle             Episode #1.9
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002954, dtype: object

(9,)

tconst                                 tt11821274
titleType                               tvEpisode
primaryTitle      Episode dated 10 September 2018
originalTitle     Episode dated 10 September 2018
isAdult                                         0
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2002955, dtype: object

(9,)

tconst                                 tt11821276
titleType                               tvEpisode
primaryTitle      DFP Academy: Itchin' & Bitchin'
originalTitle     DFP Academy: Itchin' & Bitchin'
isAdult                                         1
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2002956, dtype: object

(9,)

tconst                 tt11821278
titleType               tvEpisode
primaryTitle         Episode #3.1
originalTitle        Episode #3.1
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2002957, dtype: object

(9,)

tconst               tt1182127
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2002958, dtype: object

(9,)

tconst                      tt11821280
titleType                    tvEpisode
primaryTitle             Episode #1.10
originalTitle            Episode #1.10
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002959, dtype: object

(9,)

tconst                           tt11821282
titleType                         tvEpisode
primaryTitle      Episode dated 15 May 2019
originalTitle     Episode dated 15 May 2019
isAdult                                   0
startYear                              2019
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2002960, dtype: object

(9,)

tconst                           tt11821284
titleType                         tvEpisode
primaryTitle      Episode dated 21 May 2019
originalTitle     Episode dated 21 May 2019
isAdult                                   0
startYear                              2019
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2002961, dtype: object

(9,)

tconst                      tt11821286
titleType                    tvEpisode
primaryTitle             Episode #1.11
originalTitle            Episode #1.11
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002962, dtype: object

(9,)

tconst                         tt11821288
titleType                           short
primaryTitle      Bagel Bite Fright Night
originalTitle     Bagel Bite Fright Night
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                       Comedy,Short
Name: 2002963, dtype: object

(9,)

tconst                              tt1182128
titleType                           tvEpisode
primaryTitle      Elementary, My Dear Murdoch
originalTitle     Elementary, My Dear Murdoch
isAdult                                     0
startYear                                2008
endYear                                    \N
runtimeMinutes                             48
genres                    Crime,Drama,Mystery
Name: 2002964, dtype: object

(9,)

tconst                                          tt11821290
titleType                                        tvEpisode
primaryTitle      DFP Academy: One Switch to Rule Them All
originalTitle     DFP Academy: One Switch to Rule Them All
isAdult                                                  1
startYear                                             2018
endYear                                                 \N
runtimeMinutes                                          \N
genres                                               Adult
Name: 2002965, dtype: object

(9,)

tconst                            tt11821292
titleType                          tvEpisode
primaryTitle      Episode dated 24 July 2019
originalTitle     Episode dated 24 July 2019
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2002966, dtype: object

(9,)

tconst                      tt11821294
titleType                    tvEpisode
primaryTitle           Niña de cristal
originalTitle          Niña de cristal
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2002967, dtype: object

(9,)

tconst                      tt11821296
titleType                    tvEpisode
primaryTitle             Episode #1.12
originalTitle            Episode #1.12
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002968, dtype: object

(9,)

tconst                                        tt11821298
titleType                                      tvEpisode
primaryTitle      DFP Academy: Happy Birthday Ms. Brooks
originalTitle     DFP Academy: Happy Birthday Ms. Brooks
isAdult                                                1
startYear                                           2018
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Adult
Name: 2002969, dtype: object

(9,)

tconst                                     tt1182129
titleType                                  tvEpisode
primaryTitle      Baltimore Colts vs. Dallas Cowboys
originalTitle     Baltimore Colts vs. Dallas Cowboys
isAdult                                            0
startYear                                       1978
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Sport
Name: 2002970, dtype: object

(9,)

tconst                      tt11821300
titleType                    tvEpisode
primaryTitle             Episode #1.13
originalTitle            Episode #1.13
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002971, dtype: object

(9,)

tconst                                  tt11821302
titleType                                tvEpisode
primaryTitle      DFP Academy: Akira & Luci Part 3
originalTitle     DFP Academy: Akira & Luci Part 3
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2002972, dtype: object

(9,)

tconst                              tt11821304
titleType                            tvEpisode
primaryTitle      DFP Academy: The Roomie Show
originalTitle     DFP Academy: The Roomie Show
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2002973, dtype: object

(9,)

tconst                      tt11821306
titleType                    tvEpisode
primaryTitle             Episode #1.14
originalTitle            Episode #1.14
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002974, dtype: object

(9,)

tconst            tt11821308
titleType          tvEpisode
primaryTitle      Scoundrels
originalTitle     Scoundrels
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2002975, dtype: object

(9,)

tconst                                      tt1182130
titleType                                   tvEpisode
primaryTitle      Dallas Cowboys vs. Cleveland Browns
originalTitle     Dallas Cowboys vs. Cleveland Browns
isAdult                                             0
startYear                                        1979
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Sport
Name: 2002976, dtype: object

(9,)

tconst                      tt11821310
titleType                    tvEpisode
primaryTitle             Episode #1.15
originalTitle            Episode #1.15
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002977, dtype: object

(9,)

tconst                                               tt11821312
titleType                                             tvEpisode
primaryTitle      Haikyuu 1x14 REACTION!! "The Tough Opponents"
originalTitle     Haikyuu 1x14 REACTION!! "The Tough Opponents"
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               28
genres                                                Talk-Show
Name: 2002978, dtype: object

(9,)

tconst               tt11821314
titleType             tvEpisode
primaryTitle      The Interview
originalTitle     The Interview
isAdult                       1
startYear                  2018
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2002979, dtype: object

(9,)

tconst                                  tt11821316
titleType                                tvEpisode
primaryTitle      DFP Academy: Round Robin - Sadie
originalTitle     DFP Academy: Round Robin - Sadie
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2002980, dtype: object

(9,)

tconst                      tt11821318
titleType                    tvEpisode
primaryTitle             Episode #1.16
originalTitle            Episode #1.16
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002981, dtype: object

(9,)

tconst                                         tt1182131
titleType                                      tvEpisode
primaryTitle      Philadelphia Eagles vs. Dallas Cowboys
originalTitle     Philadelphia Eagles vs. Dallas Cowboys
isAdult                                                0
startYear                                           1979
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Sport
Name: 2002982, dtype: object

(9,)

tconst                              tt11821320
titleType                            tvEpisode
primaryTitle      Big Bird Singing Bein' Green
originalTitle     Big Bird Singing Bein' Green
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2002983, dtype: object

(9,)

tconst                     tt11821322
titleType                   tvEpisode
primaryTitle      The Osaka Encounter
originalTitle     The Osaka Encounter
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres                  Drama,Romance
Name: 2002984, dtype: object

(9,)

tconst                                     tt11821324
titleType                                   tvEpisode
primaryTitle      DFP Academy: Double Itch Plus Karma
originalTitle     DFP Academy: Double Itch Plus Karma
isAdult                                             1
startYear                                        2018
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2002985, dtype: object

(9,)

tconst                                tt11821326
titleType                                  short
primaryTitle      This is What I Look Like Naked
originalTitle     This is What I Look Like Naked
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                              Comedy,Short
Name: 2002986, dtype: object

(9,)

tconst                     tt11821328
titleType                   tvEpisode
primaryTitle      Aunt Nikki's Nieces
originalTitle     Aunt Nikki's Nieces
isAdult                             1
startYear                        2018
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2002987, dtype: object

(9,)

tconst                                tt1182132
titleType                             tvEpisode
primaryTitle      Episode dated 5 November 1980
originalTitle     Episode dated 5 November 1980
isAdult                                       0
startYear                                  1980
endYear                                      \N
runtimeMinutes                               \N
genres                         Documentary,News
Name: 2002988, dtype: object

(9,)

tconst                      tt11821330
titleType                    tvEpisode
primaryTitle             Episode #1.17
originalTitle            Episode #1.17
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002989, dtype: object

(9,)

tconst                                tt11821332
titleType                              tvEpisode
primaryTitle      DFP Academy: Incentive Program
originalTitle     DFP Academy: Incentive Program
isAdult                                        1
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2002990, dtype: object

(9,)

tconst               tt11821334
titleType             tvEpisode
primaryTitle      Episode #7.24
originalTitle     Episode #7.24
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2002991, dtype: object

(9,)

tconst                                      tt11821336
titleType                                    tvEpisode
primaryTitle      DFP Academy: Setting Up the New Girl
originalTitle     DFP Academy: Setting Up the New Girl
isAdult                                              1
startYear                                         2018
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Adult
Name: 2002992, dtype: object

(9,)

tconst                      tt11821338
titleType                    tvEpisode
primaryTitle             Episode #1.18
originalTitle            Episode #1.18
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002993, dtype: object

(9,)

tconst                   tt1182133
titleType                tvEpisode
primaryTitle      Booze and Hisses
originalTitle     Booze and Hisses
isAdult                          0
startYear                     2006
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2002994, dtype: object

(9,)

tconst              tt11821340
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2002995, dtype: object

(9,)

tconst              tt11821342
titleType                movie
primaryTitle      Wager Danger
originalTitle     Wager Danger
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2002996, dtype: object

(9,)

tconst                                 tt11821344
titleType                               tvEpisode
primaryTitle      DFP Academy: A Teachable Moment
originalTitle     DFP Academy: A Teachable Moment
isAdult                                         1
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2002997, dtype: object

(9,)

tconst                      tt11821346
titleType                    tvEpisode
primaryTitle             Episode #1.19
originalTitle            Episode #1.19
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2002998, dtype: object

(9,)

tconst                     tt11821348
titleType                   tvEpisode
primaryTitle      The Talking Snowman
originalTitle     The Talking Snowman
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     85
genres               Animation,Family
Name: 2002999, dtype: object

(9,)

tconst                            tt1182134
titleType                         tvEpisode
primaryTitle      Episode dated 20 May 1996
originalTitle     Episode dated 20 May 1996
isAdult                                   0
startYear                              1996
endYear                                  \N
runtimeMinutes                           \N
genres                                 News
Name: 2003000, dtype: object

(9,)

tconst                              tt11821350
titleType                              tvShort
primaryTitle      Voila! les sales de concerts
originalTitle     Voila! les sales de concerts
isAdult                                      0
startYear                                 2009
endYear                                     \N
runtimeMinutes                              10
genres                 Documentary,Music,Short
Name: 2003001, dtype: object

(9,)

tconst                      tt11821352
titleType                    tvEpisode
primaryTitle             Episode #1.20
originalTitle            Episode #1.20
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,History
Name: 2003002, dtype: object

(9,)

tconst                          tt11821354
titleType                        tvEpisode
primaryTitle      DFP Academy: Confessions
originalTitle     DFP Academy: Confessions
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2003003, dtype: object

(9,)

tconst                                      tt11821358
titleType                                    tvEpisode
primaryTitle      DFP Academy: Round Robin - Cassandra
originalTitle     DFP Academy: Round Robin - Cassandra
isAdult                                              1
startYear                                         2018
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Adult
Name: 2003004, dtype: object

(9,)

tconst                tt1182135
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres              Comedy,News
Name: 2003005, dtype: object

(9,)

tconst              tt11821360
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003006, dtype: object

(9,)

tconst              tt11821362
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003007, dtype: object

(9,)

tconst              tt11821364
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003008, dtype: object

(9,)

tconst                       tt11821366
titleType                     tvEpisode
primaryTitle               Episode #1.2
originalTitle              Episode #1.2
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Fantasy,Romance
Name: 2003009, dtype: object

(9,)

tconst                             tt11821368
titleType                           tvEpisode
primaryTitle      DFP Academy: Sister Visit 1
originalTitle     DFP Academy: Sister Visit 1
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2003010, dtype: object

(9,)

tconst                tt1182136
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres              Comedy,News
Name: 2003011, dtype: object

(9,)

tconst              tt11821370
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003012, dtype: object

(9,)

tconst              tt11821372
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003013, dtype: object

(9,)

tconst              tt11821374
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003014, dtype: object

(9,)

tconst              tt11821376
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003015, dtype: object

(9,)

tconst                tt11821378
titleType                  movie
primaryTitle      Living the Map
originalTitle     Living the Map
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2003016, dtype: object

(9,)

tconst                tt1182137
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres              Comedy,News
Name: 2003017, dtype: object

(9,)

tconst                             tt11821380
titleType                           tvEpisode
primaryTitle      xxxInsanityxxx can't escape
originalTitle     xxxInsanityxxx can't escape
isAdult                                     1
startYear                                2007
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2003018, dtype: object

(9,)

tconst              tt11821382
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003019, dtype: object

(9,)

tconst               tt11821384
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003020, dtype: object

(9,)

tconst                      tt11821386
titleType                    tvEpisode
primaryTitle              La mala vida
originalTitle             La mala vida
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2003021, dtype: object

(9,)

tconst                   tt11821388
titleType                 tvEpisode
primaryTitle      Pandora in 3 ties
originalTitle     Pandora in 3 ties
isAdult                           1
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2003022, dtype: object

(9,)

tconst                             tt1182138
titleType                          tvEpisode
primaryTitle      Episode dated 28 July 1983
originalTitle     Episode dated 28 July 1983
isAdult                                    0
startYear                               1983
endYear                                   \N
runtimeMinutes                            \N
genres                                  News
Name: 2003023, dtype: object

(9,)

tconst               tt11821390
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003024, dtype: object

(9,)

tconst                      tt11821392
titleType                    tvEpisode
primaryTitle          La hija de nadie
originalTitle         La hija de nadie
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2003025, dtype: object

(9,)

tconst                                                 tt11821394
titleType                                               tvEpisode
primaryTitle      Being Attacked by a Fully Trained Bodyguard Dog
originalTitle     Being Attacked by a Fully Trained Bodyguard Dog
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 15
genres                                          Comedy,Reality-TV
Name: 2003026, dtype: object

(9,)

tconst                        tt11821396
titleType                      tvEpisode
primaryTitle      Lynn Winters in 3 ties
originalTitle     Lynn Winters in 3 ties
isAdult                                1
startYear                           2007
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2003027, dtype: object

(9,)

tconst               tt11821398
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003028, dtype: object

(9,)

tconst                        tt1182139
titleType                     tvEpisode
primaryTitle              Episode #3.71
originalTitle             Episode #3.71
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres            Comedy,News,Talk-Show
Name: 2003029, dtype: object

(9,)

tconst               tt11821400
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003030, dtype: object

(9,)

tconst                         tt11821402
titleType                       tvEpisode
primaryTitle      Pandora the maid part 2
originalTitle     Pandora the maid part 2
isAdult                                 1
startYear                            2007
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2003031, dtype: object

(9,)

tconst               tt11821404
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003032, dtype: object

(9,)

tconst               tt11821406
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003033, dtype: object

(9,)

tconst               tt11821408
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003034, dtype: object

(9,)

tconst                                  tt1182140
titleType                               tvEpisode
primaryTitle      Episode dated 16 September 1989
originalTitle     Episode dated 16 September 1989
isAdult                                         0
startYear                                    1989
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2003035, dtype: object

(9,)

tconst                      tt11821410
titleType                    tvEpisode
primaryTitle      Cuestión de dignidad
originalTitle     Cuestión de dignidad
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2003036, dtype: object

(9,)

tconst               tt11821412
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003037, dtype: object

(9,)

tconst                       tt11821414
titleType                     tvEpisode
primaryTitle               Episode #1.3
originalTitle              Episode #1.3
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Fantasy,Romance
Name: 2003038, dtype: object

(9,)

tconst               tt11821416
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003039, dtype: object

(9,)

tconst                 tt11821418
titleType               tvEpisode
primaryTitle      Episode #1.1935
originalTitle     Episode #1.1935
isAdult                         0
startYear                    1995
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2003040, dtype: object

(9,)

tconst                         tt1182141
titleType                      tvEpisode
primaryTitle               Episode #3.22
originalTitle              Episode #3.22
isAdult                                0
startYear                           1994
endYear                               \N
runtimeMinutes                        \N
genres            Comedy,Game-Show,Music
Name: 2003041, dtype: object

(9,)

tconst               tt11821420
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003042, dtype: object

(9,)

tconst                            tt11821422
titleType                          tvEpisode
primaryTitle      Gypsy stuggels for freedom
originalTitle     Gypsy stuggels for freedom
isAdult                                    1
startYear                               2007
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2003043, dtype: object

(9,)

tconst               tt11821424
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003044, dtype: object

(9,)

tconst                                    tt11821426
titleType                                  tvEpisode
primaryTitle      Samantha Grace in Japanese Bondage
originalTitle     Samantha Grace in Japanese Bondage
isAdult                                            1
startYear                                       2007
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2003045, dtype: object

(9,)

tconst               tt11821428
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003046, dtype: object

(9,)

tconst                                tt1182142
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2008
originalTitle     Episode dated 4 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               60
genres                           News,Talk-Show
Name: 2003047, dtype: object

(9,)

tconst            tt11821430
titleType              movie
primaryTitle        La Pampa
originalTitle       La Pampa
isAdult                    0
startYear               2021
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003048, dtype: object

(9,)

tconst                   tt11821432
titleType                 tvEpisode
primaryTitle      Pandora Struggles
originalTitle     Pandora Struggles
isAdult                           1
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2003049, dtype: object

(9,)

tconst               tt11821434
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003050, dtype: object

(9,)

tconst              tt11821436
titleType            tvEpisode
primaryTitle      Hughes/Harry
originalTitle     Hughes/Harry
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Crime
Name: 2003051, dtype: object

(9,)

tconst                    tt11821438
titleType                  tvEpisode
primaryTitle      The Tokyo New Year
originalTitle     The Tokyo New Year
isAdult                            0
startYear                         \N
endYear                           \N
runtimeMinutes                    \N
genres                 Drama,Romance
Name: 2003052, dtype: object

(9,)

tconst            tt1182143
titleType         tvEpisode
primaryTitle      The Quest
originalTitle     The Quest
isAdult                   0
startYear              2003
endYear                  \N
runtimeMinutes           \N
genres            Adventure
Name: 2003053, dtype: object

(9,)

tconst               tt11821440
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003054, dtype: object

(9,)

tconst               tt11821442
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003055, dtype: object

(9,)

tconst                                tt11821444
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                               180
genres                                        \N
Name: 2003056, dtype: object

(9,)

tconst             tt11821446
titleType           tvEpisode
primaryTitle      Talia Favia
originalTitle     Talia Favia
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2003057, dtype: object

(9,)

tconst               tt11821448
titleType                 video
primaryTitle      Ellis: N.Y.E.
originalTitle     Ellis: N.Y.E.
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes                3
genres              Music,Short
Name: 2003058, dtype: object

(9,)

tconst                tt1182144
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                  1986
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2003059, dtype: object

(9,)

tconst               tt11821450
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres             Action,Drama
Name: 2003060, dtype: object

(9,)

tconst              tt11821452
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003061, dtype: object

(9,)

tconst                       tt11821454
titleType                     tvEpisode
primaryTitle               Episode #1.4
originalTitle              Episode #1.4
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Fantasy,Romance
Name: 2003062, dtype: object

(9,)

tconst               tt1182145
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 1987
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2003063, dtype: object

(9,)

tconst                   tt11821460
titleType                 tvEpisode
primaryTitle      Maria João Bastos
originalTitle     Maria João Bastos
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2003064, dtype: object

(9,)

tconst               tt11821462
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003065, dtype: object

(9,)

tconst               tt11821464
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003066, dtype: object

(9,)

tconst                     tt11821466
titleType                       short
primaryTitle                   Unbind
originalTitle                  Unbind
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                      6
genres            Comedy,Horror,Short
Name: 2003067, dtype: object

(9,)

tconst               tt11821468
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003068, dtype: object

(9,)

tconst                 tt1182146
titleType              tvEpisode
primaryTitle      Episode #3.129
originalTitle     Episode #3.129
isAdult                        0
startYear                   1989
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2003069, dtype: object

(9,)

tconst               tt11821470
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003070, dtype: object

(9,)

tconst               tt11821472
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003071, dtype: object

(9,)

tconst               tt11821474
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003072, dtype: object

(9,)

tconst               tt11821476
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003073, dtype: object

(9,)

tconst               tt11821478
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003074, dtype: object

(9,)

tconst                                 tt1182147
titleType                              tvEpisode
primaryTitle      Episode dated 22 November 1970
originalTitle     Episode dated 22 November 1970
isAdult                                        0
startYear                                   1970
endYear                                       \N
runtimeMinutes                                \N
genres                                   Musical
Name: 2003075, dtype: object

(9,)

tconst               tt11821480
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  1993
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003076, dtype: object

(9,)

tconst                                 tt11821482
titleType                               tvEpisode
primaryTitle      A Good Cause/Shoot for the Moon
originalTitle     A Good Cause/Shoot for the Moon
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                 Adventure,Animation,Comedy
Name: 2003077, dtype: object

(9,)

tconst                         tt11821484
titleType                           short
primaryTitle                404 Not Found
originalTitle     Chajeul su eopsseupnida
isAdult                                 0
startYear                            2018
endYear                                \N
runtimeMinutes                         28
genres                        Drama,Short
Name: 2003078, dtype: object

(9,)

tconst                       tt11821486
titleType                     tvEpisode
primaryTitle               Episode #1.5
originalTitle              Episode #1.5
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Fantasy,Romance
Name: 2003079, dtype: object

(9,)

tconst               tt11821488
titleType             tvEpisode
primaryTitle      Episode #4.17
originalTitle     Episode #4.17
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003080, dtype: object

(9,)

tconst                             tt1182148
titleType                          tvEpisode
primaryTitle      Episode dated 3 March 1987
originalTitle     Episode dated 3 March 1987
isAdult                                    0
startYear                               1987
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2003081, dtype: object

(9,)

tconst                    tt11821490
titleType                  tvEpisode
primaryTitle      Exploring Asia Rae
originalTitle     Exploring Asia Rae
isAdult                            1
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2003082, dtype: object

(9,)

tconst                                                   tt11821492
titleType                                                 tvEpisode
primaryTitle      2 Absolute Beginners Experience the Dancing Gl...
originalTitle     2 Absolute Beginners Experience the Dancing Gl...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   22
genres                                            Comedy,Reality-TV
Name: 2003083, dtype: object

(9,)

tconst               tt11821494
titleType             tvEpisode
primaryTitle      Episode #4.18
originalTitle     Episode #4.18
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003084, dtype: object

(9,)

tconst                         tt11821496
titleType                       tvEpisode
primaryTitle      DIY Geriatric Simulator
originalTitle     DIY Geriatric Simulator
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         18
genres                  Comedy,Reality-TV
Name: 2003085, dtype: object

(9,)

tconst               tt11821498
titleType             tvEpisode
primaryTitle      Episode #4.19
originalTitle     Episode #4.19
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003086, dtype: object

(9,)

tconst                                 tt1182149
titleType                              tvEpisode
primaryTitle                             Magic 1
originalTitle                            Magic 1
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres            Documentary,History,Reality-TV
Name: 2003087, dtype: object

(9,)

tconst               tt11821500
titleType             tvEpisode
primaryTitle      Episode #4.20
originalTitle     Episode #4.20
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003088, dtype: object

(9,)

tconst               tt11821502
titleType             tvEpisode
primaryTitle      Episode #4.21
originalTitle     Episode #4.21
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003089, dtype: object

(9,)

tconst                          tt11821506
titleType                        tvEpisode
primaryTitle                      Unending
originalTitle                     Unending
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres            Action,Animation,Fantasy
Name: 2003090, dtype: object

(9,)

tconst               tt11821508
titleType             tvEpisode
primaryTitle      Episode #4.22
originalTitle     Episode #4.22
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003091, dtype: object

(9,)

tconst                                 tt1182150
titleType                              tvEpisode
primaryTitle                             Magic 2
originalTitle                            Magic 2
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres            Documentary,History,Reality-TV
Name: 2003092, dtype: object

(9,)

tconst               tt11821512
titleType             tvEpisode
primaryTitle      Episode #4.23
originalTitle     Episode #4.23
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003093, dtype: object

(9,)

tconst                                        tt11821514
titleType                                          short
primaryTitle      Bengale ou Avant que le Bonheur Frappe
originalTitle     Bengale ou Avant que le Bonheur Frappe
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        13
genres                                       Drama,Short
Name: 2003094, dtype: object

(9,)

tconst                   tt11821516
titleType                 tvEpisode
primaryTitle      The Mermaid Story
originalTitle     The Mermaid Story
isAdult                           0
startYear                        \N
endYear                          \N
runtimeMinutes                   \N
genres                Drama,Romance
Name: 2003095, dtype: object

(9,)

tconst                             tt11821518
titleType                           tvEpisode
primaryTitle      DFP Academy: Sister Visit 2
originalTitle     DFP Academy: Sister Visit 2
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2003096, dtype: object

(9,)

tconst                                 tt1182151
titleType                              tvEpisode
primaryTitle                             Magic 3
originalTitle                            Magic 3
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres            Documentary,History,Reality-TV
Name: 2003097, dtype: object

(9,)

tconst               tt11821520
titleType             tvEpisode
primaryTitle      Episode #4.24
originalTitle     Episode #4.24
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003098, dtype: object

(9,)

tconst                       tt11821522
titleType                         movie
primaryTitle      Dark City of Villains
originalTitle     Dark City of Villains
isAdult                               0
startYear                          2021
endYear                              \N
runtimeMinutes                       \N
genres                            Crime
Name: 2003099, dtype: object

(9,)

tconst              tt11821524
titleType                video
primaryTitle       BigHead Big
originalTitle      BigHead Big
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2003100, dtype: object

(9,)

tconst                           tt11821526
titleType                         tvEpisode
primaryTitle      DFP Academy: Red vs Black
originalTitle     DFP Academy: Red vs Black
isAdult                                   1
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2003101, dtype: object

(9,)

tconst                                    tt11821528
titleType                                  tvEpisode
primaryTitle      Arrow 4x7 REACTION!! "Brotherhood"
originalTitle     Arrow 4x7 REACTION!! "Brotherhood"
isAdult                                            0
startYear                                       2015
endYear                                           \N
runtimeMinutes                                    29
genres                                     Talk-Show
Name: 2003102, dtype: object

(9,)

tconst                                 tt1182152
titleType                              tvEpisode
primaryTitle                             Magic 4
originalTitle                            Magic 4
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres            Documentary,History,Reality-TV
Name: 2003103, dtype: object

(9,)

tconst               tt11821530
titleType             tvEpisode
primaryTitle      Episode #4.25
originalTitle     Episode #4.25
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003104, dtype: object

(9,)

tconst                             tt11821532
titleType                           tvEpisode
primaryTitle      DFP Academy: Sister Visit 3
originalTitle     DFP Academy: Sister Visit 3
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2003105, dtype: object

(9,)

tconst               tt11821534
titleType             tvEpisode
primaryTitle      Episode #4.26
originalTitle     Episode #4.26
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003106, dtype: object

(9,)

tconst                                             tt11821536
titleType                                           tvEpisode
primaryTitle      Arrow 4x8 REACTION!! "Legends of Yesterday"
originalTitle     Arrow 4x8 REACTION!! "Legends of Yesterday"
isAdult                                                     0
startYear                                                2015
endYear                                                    \N
runtimeMinutes                                             28
genres                                              Talk-Show
Name: 2003107, dtype: object

(9,)

tconst                             tt11821538
titleType                           tvEpisode
primaryTitle      DFP Academy: Sister Visit 4
originalTitle     DFP Academy: Sister Visit 4
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2003108, dtype: object

(9,)

tconst                                 tt1182153
titleType                              tvEpisode
primaryTitle                             Magic 5
originalTitle                            Magic 5
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres            Documentary,History,Reality-TV
Name: 2003109, dtype: object

(9,)

tconst               tt11821540
titleType             tvEpisode
primaryTitle      Episode #4.27
originalTitle     Episode #4.27
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003110, dtype: object

(9,)

tconst                                          tt11821542
titleType                                        tvEpisode
primaryTitle      Georgia-Persian Rock & Metal Fest-Part 4
originalTitle     Georgia-Persian Rock & Metal Fest-Part 4
isAdult                                                  0
startYear                                             2014
endYear                                                 \N
runtimeMinutes                                          \N
genres                                          Reality-TV
Name: 2003111, dtype: object

(9,)

tconst                       tt11821544
titleType                     tvEpisode
primaryTitle      Gently the First Time
originalTitle     Gently the First Time
isAdult                               1
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2003112, dtype: object

(9,)

tconst               tt11821546
titleType             tvEpisode
primaryTitle      Episode #4.28
originalTitle     Episode #4.28
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003113, dtype: object

(9,)

tconst                                               tt11821548
titleType                                             tvEpisode
primaryTitle      Flash/Arrow Crossover Viewer Q&A DISCUSSION!!
originalTitle     Flash/Arrow Crossover Viewer Q&A DISCUSSION!!
isAdult                                                       0
startYear                                                  2015
endYear                                                      \N
runtimeMinutes                                               38
genres                                                Talk-Show
Name: 2003114, dtype: object

(9,)

tconst                                 tt1182154
titleType                              tvEpisode
primaryTitle                      Women in Magic
originalTitle                     Women in Magic
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres            Documentary,History,Reality-TV
Name: 2003115, dtype: object

(9,)

tconst               tt11821552
titleType             tvEpisode
primaryTitle      Episode #4.29
originalTitle     Episode #4.29
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003116, dtype: object

(9,)

tconst                                   tt11821554
titleType                                 tvEpisode
primaryTitle      DFP Academy: Round Robin - Reagan
originalTitle     DFP Academy: Round Robin - Reagan
isAdult                                           1
startYear                                      2018
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2003117, dtype: object

(9,)

tconst               tt11821556
titleType             tvEpisode
primaryTitle      Episode #4.30
originalTitle     Episode #4.30
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2003118, dtype: object

(9,)

tconst                      tt11821558
titleType                    tvEpisode
primaryTitle      Don't Be Such a Baby
originalTitle     Don't Be Such a Baby
isAdult                              1
startYear                         2018
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2003119, dtype: object

(9,)

tconst                                tt1182155
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2008
originalTitle     Episode dated 4 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                     News,Sport,Talk-Show
Name: 2003120, dtype: object

(9,)

tconst                                    tt11821560
titleType                                  tvEpisode
primaryTitle      DFP Academy: A New Sheriff in Town
originalTitle     DFP Academy: A New Sheriff in Town
isAdult                                            1
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2003121, dtype: object

(9,)

tconst                               tt11821562
titleType                             tvEpisode
primaryTitle      DFP Academy: Old School Rules
originalTitle     DFP Academy: Old School Rules
isAdult                                       1
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2003122, dtype: object

(9,)

tconst                       tt11821564
titleType                     tvEpisode
primaryTitle               Episode #1.6
originalTitle              Episode #1.6
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Fantasy,Romance
Name: 2003123, dtype: object

(9,)

tconst                      tt11821566
titleType                        movie
primaryTitle      The Devil's Daughter
originalTitle     The Devil's Daughter
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres                          Action
Name: 2003124, dtype: object

(9,)

tconst                           tt11821568
titleType                         tvEpisode
primaryTitle      Martin Balsam, Hal Cooper
originalTitle     Martin Balsam, Hal Cooper
isAdult                                   0
startYear                              1954
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2003125, dtype: object

(9,)

tconst               tt1182156
titleType             tvSeries
primaryTitle      Parking Wars
originalTitle     Parking Wars
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              30
genres              Reality-TV
Name: 2003126, dtype: object

(9,)

tconst                           tt11821570
titleType                         tvEpisode
primaryTitle      DFP Academy: Nanite SNAFU
originalTitle     DFP Academy: Nanite SNAFU
isAdult                                   1
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2003127, dtype: object

(9,)

tconst                          tt11821572
titleType                        tvEpisode
primaryTitle      DFP Academy: Tit for Tat
originalTitle     DFP Academy: Tit for Tat
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2003128, dtype: object

(9,)

tconst                                tt11821574
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003129, dtype: object

(9,)

tconst                                 tt11821576
titleType                                   short
primaryTitle      Great Monsters Walk These Halls
originalTitle     Great Monsters Walk These Halls
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                          Documentary,Short
Name: 2003130, dtype: object

(9,)

tconst                                      tt11821578
titleType                                    tvEpisode
primaryTitle      DFP Academy: A New Sheriff in Town 2
originalTitle     DFP Academy: A New Sheriff in Town 2
isAdult                                              1
startYear                                         2018
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Adult
Name: 2003131, dtype: object

(9,)

tconst                 tt1182157
titleType              tvEpisode
primaryTitle      Episode #2.101
originalTitle     Episode #2.101
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2003132, dtype: object

(9,)

tconst                              tt11821580
titleType                            tvEpisode
primaryTitle      DFP Academy: Maria's Madness
originalTitle     DFP Academy: Maria's Madness
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2003133, dtype: object

(9,)

tconst                         tt11821582
titleType                           movie
primaryTitle        As the Village Sleeps
originalTitle       As the Village Sleeps
isAdult                                 0
startYear                            2021
endYear                                \N
runtimeMinutes                         82
genres            Horror,Mystery,Thriller
Name: 2003134, dtype: object

(9,)

tconst               tt11821586
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2003135, dtype: object

(9,)

tconst                                   tt11821588
titleType                                 tvEpisode
primaryTitle      DFP Academy: Prank Within a Prank
originalTitle     DFP Academy: Prank Within a Prank
isAdult                                           1
startYear                                      2018
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2003136, dtype: object

(9,)

tconst                 tt1182158
titleType              tvEpisode
primaryTitle      Episode #2.102
originalTitle     Episode #2.102
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2003137, dtype: object

(9,)

tconst                          tt11821590
titleType                        tvEpisode
primaryTitle      Dance, Dance, Revelation
originalTitle     Dance, Dance, Revelation
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2003138, dtype: object

(9,)

tconst                             tt11821592
titleType                           tvEpisode
primaryTitle      DFP Academy: Clerical Error
originalTitle     DFP Academy: Clerical Error
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2003139, dtype: object

(9,)

tconst                       tt11821594
titleType                     tvEpisode
primaryTitle      Aunt Nikki's Nieces 2
originalTitle     Aunt Nikki's Nieces 2
isAdult                               1
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2003140, dtype: object

(9,)

tconst                                            tt11821596
titleType                                          tvEpisode
primaryTitle      DFP Academy: A New Sheriff in Town Round 3
originalTitle     DFP Academy: A New Sheriff in Town Round 3
isAdult                                                    1
startYear                                               2018
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                 Adult
Name: 2003141, dtype: object

(9,)

tconst                                      tt11821598
titleType                                    tvEpisode
primaryTitle      DFP Academy: Recruiting the New Girl
originalTitle     DFP Academy: Recruiting the New Girl
isAdult                                              1
startYear                                         2018
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Adult
Name: 2003142, dtype: object

(9,)

tconst                                 tt1182159
titleType                              tvEpisode
primaryTitle      Episode dated 21 November 1983
originalTitle     Episode dated 21 November 1983
isAdult                                        0
startYear                                   1983
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2003143, dtype: object

(9,)

tconst                                            tt11821600
titleType                                          tvEpisode
primaryTitle      DFP Academy: A New Sheriff in Town Round 4
originalTitle     DFP Academy: A New Sheriff in Town Round 4
isAdult                                                    1
startYear                                               2018
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                 Adult
Name: 2003144, dtype: object

(9,)

tconst                        tt11821602
titleType                      tvEpisode
primaryTitle      DFP Academy: Open Wide
originalTitle     DFP Academy: Open Wide
isAdult                                1
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2003145, dtype: object

(9,)

tconst                               tt11821604
titleType                                 video
primaryTitle      The Things I've Been Stealing
originalTitle     The Things I've Been Stealing
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                              Drama,Short
Name: 2003146, dtype: object

(9,)

tconst                              tt11821606
titleType                            tvEpisode
primaryTitle      DFP Academy: Control Subject
originalTitle     DFP Academy: Control Subject
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2003147, dtype: object

(9,)

tconst                                tt11821608
titleType                              tvEpisode
primaryTitle      DFP Academy: A Sincere Apology
originalTitle     DFP Academy: A Sincere Apology
isAdult                                        1
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2003148, dtype: object

(9,)

tconst                                tt1182160
titleType                             tvEpisode
primaryTitle      Episode dated 24 October 1984
originalTitle     Episode dated 24 October 1984
isAdult                                       0
startYear                                  1984
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2003149, dtype: object

(9,)

tconst                                tt11821610
titleType                              tvEpisode
primaryTitle      Episode dated 17 February 2020
originalTitle     Episode dated 17 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003150, dtype: object

(9,)

tconst                                tt11821612
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003151, dtype: object

(9,)

tconst                                tt11821614
titleType                              tvEpisode
primaryTitle      Episode dated 24 February 2020
originalTitle     Episode dated 24 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003152, dtype: object

(9,)

tconst                               tt11821616
titleType                             tvEpisode
primaryTitle      DFP Academy: Busted for Booze
originalTitle     DFP Academy: Busted for Booze
isAdult                                       1
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2003153, dtype: object

(9,)

tconst                                            tt11821618
titleType                                          tvEpisode
primaryTitle      DFP Academy: A New Sheriff in Town Round 5
originalTitle     DFP Academy: A New Sheriff in Town Round 5
isAdult                                                    1
startYear                                               2018
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                 Adult
Name: 2003154, dtype: object

(9,)

tconst                              tt11821620
titleType                            tvEpisode
primaryTitle      DFP Academy: Spring Break-In
originalTitle     DFP Academy: Spring Break-In
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2003155, dtype: object

(9,)

tconst                                            tt11821622
titleType                                          tvEpisode
primaryTitle      DFP Academy: A New Sheriff in Town Round 6
originalTitle     DFP Academy: A New Sheriff in Town Round 6
isAdult                                                    1
startYear                                               2018
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                 Adult
Name: 2003156, dtype: object

(9,)

tconst                       tt11821624
titleType                     tvEpisode
primaryTitle               Episode #1.7
originalTitle              Episode #1.7
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Fantasy,Romance
Name: 2003157, dtype: object

(9,)

tconst                                             tt11821626
titleType                                               short
primaryTitle      When a Guy Friend Suddenly Looks Attractive
originalTitle     When a Guy Friend Suddenly Looks Attractive
isAdult                                                     0
startYear                                                2018
endYear                                                    \N
runtimeMinutes                                             13
genres                                           Comedy,Short
Name: 2003158, dtype: object

(9,)

tconst                                       tt11821628
titleType                                     tvEpisode
primaryTitle      DFP Academy: A Lesson for the Teacher
originalTitle     DFP Academy: A Lesson for the Teacher
isAdult                                               1
startYear                                          2018
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Adult
Name: 2003159, dtype: object

(9,)

tconst                                       tt1182162
titleType                                    tvEpisode
primaryTitle      Run Away Runway/I Scream, You Scream
originalTitle     Run Away Runway/I Scream, You Scream
isAdult                                              0
startYear                                         2008
endYear                                             \N
runtimeMinutes                                      23
genres                         Action,Animation,Comedy
Name: 2003160, dtype: object

(9,)

tconst                                             tt11821632
titleType                                           tvEpisode
primaryTitle      DFP Academy: Property of the Science Club 1
originalTitle     DFP Academy: Property of the Science Club 1
isAdult                                                     1
startYear                                                2018
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                  Adult
Name: 2003161, dtype: object

(9,)

tconst                                 tt11821634
titleType                               tvEpisode
primaryTitle      Does 'Sonic' Boom Spell Sequel?
originalTitle     Does 'Sonic' Boom Spell Sequel?
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                  3
genres                                 News,Short
Name: 2003162, dtype: object

(9,)

tconst                                     tt11821636
titleType                                   tvEpisode
primaryTitle      DFP Academy: A Lesson for the Class
originalTitle     DFP Academy: A Lesson for the Class
isAdult                                             1
startYear                                        2018
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2003163, dtype: object

(9,)

tconst            tt11821638
titleType              video
primaryTitle          Manche
originalTitle         Manche
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes             7
genres                 Short
Name: 2003164, dtype: object

(9,)

tconst                                                    tt1182163
titleType                                                 tvEpisode
primaryTitle      It's a Mud, Mud, Mud, Mud World/The Ballad of ...
originalTitle     It's a Mud, Mud, Mud, Mud World/The Ballad of ...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   23
genres                                      Action,Animation,Comedy
Name: 2003165, dtype: object

(9,)

tconst                                           tt11821640
titleType                                         tvEpisode
primaryTitle      DFP Academy: Property of the Science Club
originalTitle     DFP Academy: Property of the Science Club
isAdult                                                   1
startYear                                              2018
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Adult
Name: 2003166, dtype: object

(9,)

tconst                                  tt11821642
titleType                                tvEpisode
primaryTitle      DFP Academy: The New Gym Teacher
originalTitle     DFP Academy: The New Gym Teacher
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2003167, dtype: object

(9,)

tconst                                tt11821644
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003168, dtype: object

(9,)

tconst                                                   tt11821646
titleType                                                 tvEpisode
primaryTitle      Forgive and Forget It/Spot That Hero/A Jingle ...
originalTitle     Forgive and Forget It/Spot That Hero/A Jingle ...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   24
genres                                      Animation,Comedy,Family
Name: 2003169, dtype: object

(9,)

tconst                                              tt1182164
titleType                                           tvEpisode
primaryTitle      Ready for the Betty's/The Flying Fishmonger
originalTitle     Ready for the Betty's/The Flying Fishmonger
isAdult                                                     0
startYear                                                2008
endYear                                                    \N
runtimeMinutes                                             23
genres                                Action,Animation,Comedy
Name: 2003170, dtype: object

(9,)

tconst                      tt11821650
titleType                    tvEpisode
primaryTitle           Abrazar la vida
originalTitle          Abrazar la vida
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2003171, dtype: object

(9,)

tconst                                                tt11821652
titleType                                              tvEpisode
primaryTitle      Dino Bots/A Couple of Good Sports/Pappy's Pals
originalTitle     Dino Bots/A Couple of Good Sports/Pappy's Pals
isAdult                                                        0
startYear                                                   2001
endYear                                                       \N
runtimeMinutes                                                24
genres                                   Animation,Comedy,Family
Name: 2003172, dtype: object

(9,)

tconst               tt11821656
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2003173, dtype: object

(9,)

tconst                      tt11821658
titleType                        short
primaryTitle      Mountaineer Spinning
originalTitle     Mountaineer Spinning
isAdult                              0
startYear                         2004
endYear                             \N
runtimeMinutes                      26
genres                           Short
Name: 2003174, dtype: object

(9,)

tconst                       tt1182165
titleType                    tvEpisode
primaryTitle             Episode #1.11
originalTitle            Episode #1.11
isAdult                              0
startYear                         2004
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2003175, dtype: object

(9,)

tconst              tt11821660
titleType            tvEpisode
primaryTitle      Dance Beat 2
originalTitle     Dance Beat 2
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2003176, dtype: object

(9,)

tconst                                                   tt11821662
titleType                                                 tvEpisode
primaryTitle      Trump Pardons International Mafia Connected Cr...
originalTitle     Trump Pardons International Mafia Connected Cr...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2003177, dtype: object

(9,)

tconst             tt11821664
titleType               short
primaryTitle           Ashock
originalTitle         Asyokeu
isAdult                     0
startYear                2013
endYear                    \N
runtimeMinutes             23
genres            Drama,Short
Name: 2003178, dtype: object

(9,)

tconst               tt11821666
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2003179, dtype: object

(9,)

tconst                tt11821668
titleType              tvEpisode
primaryTitle      Funny Business
originalTitle     Funny Business
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Game-Show
Name: 2003180, dtype: object

(9,)

tconst                  tt1182166
titleType               tvEpisode
primaryTitle      Ah, la famille!
originalTitle     Ah, la famille!
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 88
genres               Comedy,Drama
Name: 2003181, dtype: object

(9,)

tconst                                        tt11821670
titleType                                      tvEpisode
primaryTitle      Huff Po on Hairy Pits and Stubbly Bits
originalTitle     Huff Po on Hairy Pits and Stubbly Bits
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        \N
genres                                              News
Name: 2003182, dtype: object

(9,)

tconst            tt11821672
titleType           tvSeries
primaryTitle       Video Jam
originalTitle      Video Jam
isAdult                    0
startYear               1992
endYear                   \N
runtimeMinutes            \N
genres                 Music
Name: 2003183, dtype: object

(9,)

tconst            tt11821674
titleType          tvEpisode
primaryTitle           Manon
originalTitle          Manon
isAdult                    0
startYear               1954
endYear                   \N
runtimeMinutes            \N
genres                 Music
Name: 2003184, dtype: object

(9,)

tconst            tt11821676
titleType            tvMovie
primaryTitle        Mr Write
originalTitle       Mr Write
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2003185, dtype: object

(9,)

tconst                     tt11821678
titleType                   tvEpisode
primaryTitle      He's Not Itsy Bitsy
originalTitle     He's Not Itsy Bitsy
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                      Game-Show
Name: 2003186, dtype: object

(9,)

tconst                   tt1182167
titleType                tvEpisode
primaryTitle          Episode #1.6
originalTitle         Episode #1.6
isAdult                          0
startYear                     2002
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2003187, dtype: object

(9,)

tconst                            tt11821680
titleType                            tvMovie
primaryTitle      Christmas at the Allistair
originalTitle     Christmas at the Allistair
isAdult                                    0
startYear                                 \N
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2003188, dtype: object

(9,)

tconst               tt11821682
titleType             tvEpisode
primaryTitle      Dippity Do-Da
originalTitle     Dippity Do-Da
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2003189, dtype: object

(9,)

tconst                     tt11821686
titleType                   tvEpisode
primaryTitle      It's the Wheel Deal
originalTitle     It's the Wheel Deal
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                      Game-Show
Name: 2003190, dtype: object

(9,)

tconst                                    tt11821688
titleType                                  tvEpisode
primaryTitle      Food Unwrapped Does Christmas 2016
originalTitle     Food Unwrapped Does Christmas 2016
isAdult                                            0
startYear                                       2016
endYear                                           \N
runtimeMinutes                                    \N
genres                            Comedy,Documentary
Name: 2003191, dtype: object

(9,)

tconst                   tt1182168
titleType                tvEpisode
primaryTitle           Big Pimpin'
originalTitle          Big Pimpin'
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003192, dtype: object

(9,)

tconst                   tt11821690
titleType                   tvMovie
primaryTitle        Chant grégorien
originalTitle       Chant grégorien
isAdult                           0
startYear                      1981
endYear                          \N
runtimeMinutes                   60
genres            Documentary,Music
Name: 2003193, dtype: object

(9,)

tconst                                             tt11821692
titleType                                           tvEpisode
primaryTitle      Top 10 Dark Stories Behind Children's Books
originalTitle     Top 10 Dark Stories Behind Children's Books
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             \N
genres                                       Comedy,Talk-Show
Name: 2003194, dtype: object

(9,)

tconst                   tt11821694
titleType                 tvEpisode
primaryTitle      Let's Have a Ball
originalTitle     Let's Have a Ball
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                    Game-Show
Name: 2003195, dtype: object

(9,)

tconst               tt11821696
titleType             tvEpisode
primaryTitle      Pair Apparent
originalTitle     Pair Apparent
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2003196, dtype: object

(9,)

tconst             tt11821698
titleType           tvEpisode
primaryTitle      Dino Might!
originalTitle     Dino Might!
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres              Game-Show
Name: 2003197, dtype: object

(9,)

tconst                   tt1182169
titleType                tvEpisode
primaryTitle        Boys vs. Girls
originalTitle       Boys vs. Girls
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003198, dtype: object

(9,)

tconst                 tt11821700
titleType               tvEpisode
primaryTitle      Episode #1.2690
originalTitle     Episode #1.2690
isAdult                         0
startYear                    1985
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2003199, dtype: object

(9,)

tconst                                                   tt11821702
titleType                                                 tvEpisode
primaryTitle      Chrono Trigger - Part 1: The time travelling a...
originalTitle     Chrono Trigger - Part 1: The time travelling a...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2003200, dtype: object

(9,)

tconst                   tt11821704
titleType                 tvEpisode
primaryTitle      Four on the Floor
originalTitle     Four on the Floor
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                    Game-Show
Name: 2003201, dtype: object

(9,)

tconst                                 tt11821706
titleType                               tvEpisode
primaryTitle      Wine Experts Taste Dogshit Wine
originalTitle     Wine Experts Taste Dogshit Wine
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2003202, dtype: object

(9,)

tconst                                                   tt11821708
titleType                                                 tvEpisode
primaryTitle      POWERFUL Fan Made Bernie Ad Will Bring a Tear ...
originalTitle     POWERFUL Fan Made Bernie Ad Will Bring a Tear ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2003203, dtype: object

(9,)

tconst                         tt1182170
titleType                      tvEpisode
primaryTitle      Breaking the Girl Code
originalTitle     Breaking the Girl Code
isAdult                                0
startYear                           2007
endYear                               \N
runtimeMinutes                        22
genres                  Drama,Reality-TV
Name: 2003204, dtype: object

(9,)

tconst                                                   tt11821712
titleType                                                 tvEpisode
primaryTitle      Paul Young interview/Paul King interview/Madon...
originalTitle     Paul Young interview/Paul King interview/Madon...
isAdult                                                           0
startYear                                                      1985
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Music
Name: 2003205, dtype: object

(9,)

tconst               tt11821714
titleType             tvEpisode
primaryTitle          The Chase
originalTitle         The Chase
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2003206, dtype: object

(9,)

tconst            tt11821716
titleType              movie
primaryTitle        ReturnME
originalTitle       ReturnME
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2003207, dtype: object

(9,)

tconst                  tt11821718
titleType                    short
primaryTitle      Purgatory Lounge
originalTitle     Purgatory Lounge
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                 Drama,Short
Name: 2003208, dtype: object

(9,)

tconst                    tt1182171
titleType                 tvEpisode
primaryTitle      Enjoy Your Flight
originalTitle     Enjoy Your Flight
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   22
genres             Drama,Reality-TV
Name: 2003209, dtype: object

(9,)

tconst                       tt11821724
titleType                     tvEpisode
primaryTitle      The Instant Chemistry
originalTitle     The Instant Chemistry
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres                    Drama,Romance
Name: 2003210, dtype: object

(9,)

tconst                         tt11821726
titleType                           movie
primaryTitle      The Good Samaritan 2020
originalTitle     The Good Samaritan 2020
isAdult                                 0
startYear                            2021
endYear                                \N
runtimeMinutes                         \N
genres                              Drama
Name: 2003211, dtype: object

(9,)

tconst                   tt1182172
titleType                tvEpisode
primaryTitle         Friends Again
originalTitle        Friends Again
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003212, dtype: object

(9,)

tconst                                                   tt11821730
titleType                                                     short
primaryTitle      The San Diego International Kids' Film Festiva...
originalTitle     The San Diego International Kids' Film Festiva...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Documentary,Short
Name: 2003213, dtype: object

(9,)

tconst                 tt11821734
titleType               tvEpisode
primaryTitle      Episode #1.2691
originalTitle     Episode #1.2691
isAdult                         0
startYear                    1985
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2003214, dtype: object

(9,)

tconst                    tt11821736
titleType                      short
primaryTitle      Six Weeks from Now
originalTitle     Six Weeks from Now
isAdult                            0
startYear                         \N
endYear                           \N
runtimeMinutes                    \N
genres                 Romance,Short
Name: 2003215, dtype: object

(9,)

tconst                  tt11821738
titleType                tvEpisode
primaryTitle      The VelociPastor
originalTitle     The VelociPastor
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2003216, dtype: object

(9,)

tconst                   tt1182173
titleType                tvEpisode
primaryTitle          Gettin' Down
originalTitle         Gettin' Down
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003217, dtype: object

(9,)

tconst                                   tt11821742
titleType                                     movie
primaryTitle      The Animated Mind of Oliver Sacks
originalTitle     The Animated Mind of Oliver Sacks
isAdult                                           0
startYear                                        \N
endYear                                          \N
runtimeMinutes                                   \N
genres                        Animation,Documentary
Name: 2003218, dtype: object

(9,)

tconst                                         tt11821746
titleType                                       tvEpisode
primaryTitle      Top 10 Nintendo Exclusive Games of 2020
originalTitle     Top 10 Nintendo Exclusive Games of 2020
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                   Comedy,Talk-Show
Name: 2003219, dtype: object

(9,)

tconst            tt11821748
titleType          tvEpisode
primaryTitle           Robot
originalTitle          Robot
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003220, dtype: object

(9,)

tconst                       tt1182174
titleType                    tvEpisode
primaryTitle      Getting Wet and Wild
originalTitle     Getting Wet and Wild
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      22
genres                Drama,Reality-TV
Name: 2003221, dtype: object

(9,)

tconst            tt11821750
titleType          tvEpisode
primaryTitle        The BOSS
originalTitle       The BOSS
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003222, dtype: object

(9,)

tconst                             tt11821752
titleType                           tvEpisode
primaryTitle      Shark and Pig share a latte
originalTitle     Shark and Pig share a latte
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres                                 Comedy
Name: 2003223, dtype: object

(9,)

tconst                          tt11821754
titleType                        tvEpisode
primaryTitle      This Is How We'll Die...
originalTitle     This Is How We'll Die...
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          21
genres                   Comedy,Reality-TV
Name: 2003224, dtype: object

(9,)

tconst                                               tt11821756
titleType                                                 video
primaryTitle      The Sweet - 50th Anniversary Multi Media Show
originalTitle     The Sweet - 50th Anniversary Multi Media Show
isAdult                                                       0
startYear                                                  2018
endYear                                                      \N
runtimeMinutes                                               60
genres                                                    Music
Name: 2003225, dtype: object

(9,)

tconst                                  tt11821758
titleType                                tvEpisode
primaryTitle      Garnet - Effective Ballbusting 3
originalTitle     Garnet - Effective Ballbusting 3
isAdult                                          1
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2003226, dtype: object

(9,)

tconst                   tt1182175
titleType                tvEpisode
primaryTitle            Girl Fight
originalTitle           Girl Fight
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  21
genres            Drama,Reality-TV
Name: 2003227, dtype: object

(9,)

tconst                    tt11821760
titleType                  tvEpisode
primaryTitle      The Little Mermaid
originalTitle     The Little Mermaid
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                        Comedy
Name: 2003228, dtype: object

(9,)

tconst            tt11821762
titleType          tvEpisode
primaryTitle            Jack
originalTitle           Jack
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003229, dtype: object

(9,)

tconst                 tt11821766
titleType               tvEpisode
primaryTitle      Delta Lulu Daze
originalTitle     Delta Lulu Daze
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2003230, dtype: object

(9,)

tconst                        tt11821768
titleType                      tvEpisode
primaryTitle      The New York City Poem
originalTitle     The New York City Poem
isAdult                                0
startYear                             \N
endYear                               \N
runtimeMinutes                        \N
genres                     Drama,Romance
Name: 2003231, dtype: object

(9,)

tconst                      tt1182176
titleType                   tvEpisode
primaryTitle      Hittin' the Hot Tub
originalTitle     Hittin' the Hot Tub
isAdult                             0
startYear                        2007
endYear                            \N
runtimeMinutes                     \N
genres               Drama,Reality-TV
Name: 2003232, dtype: object

(9,)

tconst                                       tt11821770
titleType                                     tvEpisode
primaryTitle      Top 10 Movie Flops of the Last Decade
originalTitle     Top 10 Movie Flops of the Last Decade
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       14
genres                                 Comedy,Talk-Show
Name: 2003233, dtype: object

(9,)

tconst                 tt11821772
titleType               tvEpisode
primaryTitle      Episode #1.2692
originalTitle     Episode #1.2692
isAdult                         0
startYear                    1985
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2003234, dtype: object

(9,)

tconst                     tt11821774
titleType                   tvEpisode
primaryTitle      Sweet Valley Actors
originalTitle     Sweet Valley Actors
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2003235, dtype: object

(9,)

tconst                 tt11821776
titleType                tvSeries
primaryTitle      Still Breathing
originalTitle     Still Breathing
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 46
genres                      Drama
Name: 2003236, dtype: object

(9,)

tconst              tt11821778
titleType            tvEpisode
primaryTitle      Robot Reboot
originalTitle     Robot Reboot
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2003237, dtype: object

(9,)

tconst                    tt1182177
titleType                 tvEpisode
primaryTitle      Mardi Gras Mayhem
originalTitle     Mardi Gras Mayhem
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   22
genres             Drama,Reality-TV
Name: 2003238, dtype: object

(9,)

tconst                        tt11821780
titleType                       tvSeries
primaryTitle      What's Happening in LA
originalTitle     What's Happening in LA
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2003239, dtype: object

(9,)

tconst                       tt11821784
titleType                         video
primaryTitle      Ellis: Something Blue
originalTitle     Ellis: Something Blue
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                        4
genres                      Music,Short
Name: 2003240, dtype: object

(9,)

tconst                                                   tt11821786
titleType                                                 tvEpisode
primaryTitle      Another Top 10 Disney Scenes You Didn't Know W...
originalTitle     Another Top 10 Disney Scenes You Didn't Know W...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2003241, dtype: object

(9,)

tconst                                     tt11821788
titleType                                   tvEpisode
primaryTitle      Aerobics Instructor Needs a Footrub
originalTitle     Aerobics Instructor Needs a Footrub
isAdult                                             1
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2003242, dtype: object

(9,)

tconst                   tt1182178
titleType                tvEpisode
primaryTitle            Mini Crush
originalTitle           Mini Crush
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003243, dtype: object

(9,)

tconst                     tt11821790
titleType                       short
primaryTitle      One Actor Short - 1
originalTitle     One Actor Short - 1
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                      9
genres                    Drama,Short
Name: 2003244, dtype: object

(9,)

tconst                                                   tt11821792
titleType                                                  tvSeries
primaryTitle      Otome Game no Hametsu Flag shika Nai Akuyaku R...
originalTitle     My Next Life as a Villainess: All Routes Lead ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   24
genres                                       Animation,Comedy,Drama
Name: 2003245, dtype: object

(9,)

tconst              tt11821794
titleType            tvEpisode
primaryTitle      Episode #5.1
originalTitle     Episode #5.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2003246, dtype: object

(9,)

tconst                     tt11821796
titleType                   tvEpisode
primaryTitle      The Viking Stranger
originalTitle     The Viking Stranger
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres                  Drama,Romance
Name: 2003247, dtype: object

(9,)

tconst                   tt1182179
titleType                tvEpisode
primaryTitle          Off the Hook
originalTitle         Off the Hook
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003248, dtype: object

(9,)

tconst                                   tt11821802
titleType                                 tvEpisode
primaryTitle      Schtick Shopping - Happy Go Lucky
originalTitle     Schtick Shopping - Happy Go Lucky
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Comedy
Name: 2003249, dtype: object

(9,)

tconst                            tt11821806
titleType                          tvEpisode
primaryTitle      Portrait de Gérard Philipe
originalTitle     Portrait de Gérard Philipe
isAdult                                    0
startYear                               1979
endYear                                   \N
runtimeMinutes                            60
genres                           Documentary
Name: 2003250, dtype: object

(9,)

tconst                             tt11821808
titleType                           tvEpisode
primaryTitle                     Mae Williams
originalTitle                    Mae Williams
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2003251, dtype: object

(9,)

tconst                   tt1182180
titleType                tvEpisode
primaryTitle         Second Fiddle
originalTitle        Second Fiddle
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003252, dtype: object

(9,)

tconst                             tt11821810
titleType                           tvEpisode
primaryTitle           Capt. Samuel W. Magill
originalTitle          Capt. Samuel W. Magill
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2003253, dtype: object

(9,)

tconst                             tt11821812
titleType                           tvEpisode
primaryTitle                   Yvonne Kennedy
originalTitle                  Yvonne Kennedy
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2003254, dtype: object

(9,)

tconst                             tt11821814
titleType                           tvEpisode
primaryTitle      The Viking Stranger Part II
originalTitle     The Viking Stranger Part II
isAdult                                     0
startYear                                  \N
endYear                                    \N
runtimeMinutes                             \N
genres                          Drama,Romance
Name: 2003255, dtype: object

(9,)

tconst               tt11821816
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2003256, dtype: object

(9,)

tconst                     tt11821818
titleType                       movie
primaryTitle               Double Dad
originalTitle            Pai em Dobro
isAdult                             0
startYear                        2021
endYear                            \N
runtimeMinutes                    103
genres            Comedy,Drama,Family
Name: 2003257, dtype: object

(9,)

tconst                   tt1182181
titleType                tvEpisode
primaryTitle       Suddenly Single
originalTitle      Suddenly Single
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003258, dtype: object

(9,)

tconst                                    tt11821820
titleType                                   tvSeries
primaryTitle      Nextdoor the [unaffiliated] Series
originalTitle     Nextdoor the [unaffiliated] Series
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                        Comedy
Name: 2003259, dtype: object

(9,)

tconst                     tt11821822
titleType                       video
primaryTitle      Ellis: Embarrassing
originalTitle     Ellis: Embarrassing
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                      3
genres                    Music,Short
Name: 2003260, dtype: object

(9,)

tconst                     tt11821824
titleType                       movie
primaryTitle           Bullseye Bella
originalTitle          Bullseye Bella
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003261, dtype: object

(9,)

tconst             tt11821826
titleType               short
primaryTitle          Hospice
originalTitle         Hospice
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2003262, dtype: object

(9,)

tconst                 tt11821828
titleType               tvEpisode
primaryTitle      The Last Target
originalTitle     The Last Target
isAdult                         0
startYear                    1998
endYear                        \N
runtimeMinutes                 \N
genres                     Sci-Fi
Name: 2003263, dtype: object

(9,)

tconst                   tt1182182
titleType                tvEpisode
primaryTitle             The Birds
originalTitle            The Birds
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003264, dtype: object

(9,)

tconst                             tt11821830
titleType                           tvEpisode
primaryTitle      Mobilization is Impossible!
originalTitle     Mobilization is Impossible!
isAdult                                     0
startYear                                1998
endYear                                    \N
runtimeMinutes                             \N
genres                                 Sci-Fi
Name: 2003265, dtype: object

(9,)

tconst                        tt11821832
titleType                      tvEpisode
primaryTitle      The Bone Marrow Biopsy
originalTitle     The Bone Marrow Biopsy
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2003266, dtype: object

(9,)

tconst                             tt11821834
titleType                           tvEpisode
primaryTitle                       Clyde Lamb
originalTitle                      Clyde Lamb
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2003267, dtype: object

(9,)

tconst            tt11821836
titleType          tvEpisode
primaryTitle      Separation
originalTitle     Separation
isAdult                    0
startYear               1998
endYear                   \N
runtimeMinutes            \N
genres                Sci-Fi
Name: 2003268, dtype: object

(9,)

tconst               tt11821838
titleType             tvEpisode
primaryTitle      Well Done Son
originalTitle     Well Done Son
isAdult                       0
startYear                  1998
endYear                      \N
runtimeMinutes               \N
genres                   Sci-Fi
Name: 2003269, dtype: object

(9,)

tconst                        tt1182183
titleType                     tvEpisode
primaryTitle      The Honeymoon Is Over
originalTitle     The Honeymoon Is Over
isAdult                               0
startYear                          2007
endYear                              \N
runtimeMinutes                       22
genres                 Drama,Reality-TV
Name: 2003270, dtype: object

(9,)

tconst                   tt11821840
titleType                 tvEpisode
primaryTitle         Cavs Crumbling
originalTitle        Cavs Crumbling
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   30
genres            Comedy,News,Sport
Name: 2003271, dtype: object

(9,)

tconst                             tt11821842
titleType                           tvEpisode
primaryTitle                 Carl J. Sedlmayr
originalTitle                Carl J. Sedlmayr
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2003272, dtype: object

(9,)

tconst                                   tt11821844
titleType                                 tvEpisode
primaryTitle      Reaction to my Bone Marrow Biopsy
originalTitle     Reaction to my Bone Marrow Biopsy
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                  Documentary
Name: 2003273, dtype: object

(9,)

tconst              tt11821846
titleType            tvEpisode
primaryTitle      The Two Suns
originalTitle     The Two Suns
isAdult                      0
startYear                 1998
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2003274, dtype: object

(9,)

tconst             tt11821848
titleType               short
primaryTitle          Botched
originalTitle         Botched
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             11
genres            Crime,Short
Name: 2003275, dtype: object

(9,)

tconst                   tt1182184
titleType                tvEpisode
primaryTitle          The New Girl
originalTitle         The New Girl
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  23
genres            Drama,Reality-TV
Name: 2003276, dtype: object

(9,)

tconst                              tt11821850
titleType                            tvEpisode
primaryTitle      Godzilla Island is Drying Up
originalTitle     Godzilla Island is Drying Up
isAdult                                      0
startYear                                 1998
endYear                                     \N
runtimeMinutes                              \N
genres                                  Sci-Fi
Name: 2003277, dtype: object

(9,)

tconst                        tt11821852
titleType                      tvEpisode
primaryTitle      Zaguresu's Last Chance
originalTitle     Zaguresu's Last Chance
isAdult                                0
startYear                           1998
endYear                               \N
runtimeMinutes                        \N
genres                            Sci-Fi
Name: 2003278, dtype: object

(9,)

tconst                  tt11821854
titleType                    short
primaryTitle      Garbage Solitude
originalTitle     Garbage Solitude
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                       Short
Name: 2003279, dtype: object

(9,)

tconst                       tt11821858
titleType                     tvEpisode
primaryTitle      Forest Fire Outbreak!
originalTitle     Forest Fire Outbreak!
isAdult                               0
startYear                          1998
endYear                              \N
runtimeMinutes                       \N
genres                           Sci-Fi
Name: 2003280, dtype: object

(9,)

tconst                     tt1182185
titleType                  tvEpisode
primaryTitle      Whining and Dining
originalTitle     Whining and Dining
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    22
genres              Drama,Reality-TV
Name: 2003281, dtype: object

(9,)

tconst               tt11821860
titleType          tvMiniSeries
primaryTitle      Lip lock 2020
originalTitle     Lip lock 2020
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes              100
genres                    Drama
Name: 2003282, dtype: object

(9,)

tconst                     tt11821862
titleType                       video
primaryTitle      Mai Kino: The Waves
originalTitle     Mai Kino: The Waves
isAdult                             0
startYear                        2016
endYear                            \N
runtimeMinutes                      4
genres                    Music,Short
Name: 2003283, dtype: object

(9,)

tconst                                                   tt11821864
titleType                                                 tvEpisode
primaryTitle      Establishment Dems Hold 'Stop Cenk Uygur' Meeting
originalTitle     Establishment Dems Hold 'Stop Cenk Uygur' Meeting
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2003284, dtype: object

(9,)

tconst                             tt11821866
titleType                           tvEpisode
primaryTitle                   Helen Kelleher
originalTitle                  Helen Kelleher
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2003285, dtype: object

(9,)

tconst              tt11821868
titleType            tvEpisode
primaryTitle      The Simpsons
originalTitle     The Simpsons
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2003286, dtype: object

(9,)

tconst                   tt1182186
titleType                tvEpisode
primaryTitle               Tourism
originalTitle              Tourism
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  22
genres            Drama,Reality-TV
Name: 2003287, dtype: object

(9,)

tconst            tt11821872
titleType              movie
primaryTitle         Visitor
originalTitle        Visitor
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            60
genres              Thriller
Name: 2003288, dtype: object

(9,)

tconst            tt11821874
titleType          tvEpisode
primaryTitle        Markheim
originalTitle       Markheim
isAdult                    0
startYear               1953
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003289, dtype: object

(9,)

tconst             tt11821876
titleType               short
primaryTitle        Displaced
originalTitle       Displaced
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2003290, dtype: object

(9,)

tconst                              tt11821878
titleType                            tvEpisode
primaryTitle      The Flame for Battle Returns
originalTitle     The Flame for Battle Returns
isAdult                                      0
startYear                                 1998
endYear                                     \N
runtimeMinutes                              \N
genres                                  Sci-Fi
Name: 2003291, dtype: object

(9,)

tconst                tt1182187
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                  1991
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003292, dtype: object

(9,)

tconst            tt11821880
titleType              short
primaryTitle       All Done!
originalTitle      All Done!
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes             5
genres                 Short
Name: 2003293, dtype: object

(9,)

tconst                                 tt11821882
titleType                               tvEpisode
primaryTitle      The Artificial Sun's Weak Point
originalTitle     The Artificial Sun's Weak Point
isAdult                                         0
startYear                                    1998
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Sci-Fi
Name: 2003294, dtype: object

(9,)

tconst                                tt11821884
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2003295, dtype: object

(9,)

tconst            tt11821886
titleType          tvEpisode
primaryTitle       Boys Club
originalTitle      Boys Club
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                  News
Name: 2003296, dtype: object

(9,)

tconst                 tt11821888
titleType                   movie
primaryTitle      Thalli Pogathey
originalTitle     Thalli Pogathey
isAdult                         0
startYear                    2021
endYear                        \N
runtimeMinutes                123
genres                      Drama
Name: 2003297, dtype: object

(9,)

tconst                               tt11821890
titleType                             tvEpisode
primaryTitle      Guneet's engagement in danger
originalTitle     Guneet's engagement in danger
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                    Drama
Name: 2003298, dtype: object

(9,)

tconst                                tt11821892
titleType                              tvSpecial
primaryTitle      Kichuta Prem Bakita Bhalobasha
originalTitle     Kichuta Prem Bakita Bhalobasha
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                     Drama
Name: 2003299, dtype: object

(9,)

tconst                 tt11821894
titleType                   short
primaryTitle      Polar Opposites
originalTitle     Polar Opposites
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 10
genres                Drama,Short
Name: 2003300, dtype: object

(9,)

tconst                    tt11821896
titleType                      short
primaryTitle      Kokhono Na Kokhono
originalTitle     Kokhono Na Kokhono
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                   Drama,Short
Name: 2003301, dtype: object

(9,)

tconst                           tt11821898
titleType                             movie
primaryTitle      Rebirth: Voice of Silence
originalTitle     Rebirth: Voice of Silence
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           85
genres                Drama,Mystery,Romance
Name: 2003302, dtype: object

(9,)

tconst                                tt1182189
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2003303, dtype: object

(9,)

tconst                tt11821900
titleType              tvEpisode
primaryTitle      Johnny Desmond
originalTitle     Johnny Desmond
isAdult                        0
startYear                   1954
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2003304, dtype: object

(9,)

tconst              tt11821902
titleType                video
primaryTitle           Don Jon
originalTitle          Don Jon
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2003305, dtype: object

(9,)

tconst                   tt11821904
titleType                     video
primaryTitle      Ellis: Fall Apart
originalTitle     Ellis: Fall Apart
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                    4
genres                  Music,Short
Name: 2003306, dtype: object

(9,)

tconst              tt11821906
titleType         tvMiniSeries
primaryTitle        Telephonic
originalTitle       Telephonic
isAdult                      0
startYear                 2018
endYear                   2018
runtimeMinutes              \N
genres                  Horror
Name: 2003307, dtype: object

(9,)

tconst                                           tt11821908
titleType                                         tvEpisode
primaryTitle      Charles Aznavour face aux téléspectateurs
originalTitle     Charles Aznavour face aux téléspectateurs
isAdult                                                   0
startYear                                              1989
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                   \N
Name: 2003308, dtype: object

(9,)

tconst                               tt1182190
titleType                            tvEpisode
primaryTitle      Thomas Järvheden/Ulf Larsson
originalTitle     Thomas Järvheden/Ulf Larsson
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                        Comedy,Talk-Show
Name: 2003309, dtype: object

(9,)

tconst                       tt11821910
titleType                      tvSeries
primaryTitle      Plural No. 3rd Person
originalTitle     Plural No. 3rd Person
isAdult                               0
startYear                          2019
endYear                            2019
runtimeMinutes                       \N
genres                            Drama
Name: 2003310, dtype: object

(9,)

tconst              tt11821912
titleType                movie
primaryTitle            NTR 30
originalTitle           NTR 30
isAdult                      0
startYear                 2022
endYear                     \N
runtimeMinutes              \N
genres            Action,Drama
Name: 2003311, dtype: object

(9,)

tconst                         tt11821914
titleType                       tvEpisode
primaryTitle                      Árboles
originalTitle                     Árboles
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres            Animation,Comedy,Family
Name: 2003312, dtype: object

(9,)

tconst              tt11821916
titleType         tvMiniSeries
primaryTitle      Tinder Bhabi
originalTitle     Tinder Bhabi
isAdult                      0
startYear                 2019
endYear                   2019
runtimeMinutes              \N
genres                   Drama
Name: 2003313, dtype: object

(9,)

tconst              tt11821918
titleType         tvMiniSeries
primaryTitle        Gangstuber
originalTitle       Gangstuber
isAdult                      0
startYear                 2019
endYear                   2019
runtimeMinutes              \N
genres                   Drama
Name: 2003314, dtype: object

(9,)

tconst                                tt1182191
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2008
originalTitle     Episode dated 4 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2003315, dtype: object

(9,)

tconst                   tt11821920
titleType              tvMiniSeries
primaryTitle      Shondeher Obokash
originalTitle     Shondeher Obokash
isAdult                           0
startYear                      2019
endYear                        2019
runtimeMinutes                   \N
genres                        Drama
Name: 2003316, dtype: object

(9,)

tconst                   tt11821924
titleType              tvMiniSeries
primaryTitle      The Sandwich Shop
originalTitle     The Sandwich Shop
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2003317, dtype: object

(9,)

tconst                      tt11821926
titleType                    tvEpisode
primaryTitle            Episode #42.48
originalTitle           Episode #42.48
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            News,Sport,Talk-Show
Name: 2003318, dtype: object

(9,)

tconst               tt11821928
titleType             tvEpisode
primaryTitle      The True Crue
originalTitle     The True Crue
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2003319, dtype: object

(9,)

tconst               tt1182192
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2003320, dtype: object

(9,)

tconst                      tt11821930
titleType                    tvEpisode
primaryTitle            Episode #42.49
originalTitle           Episode #42.49
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            News,Sport,Talk-Show
Name: 2003321, dtype: object

(9,)

tconst                         tt11821932
titleType                           short
primaryTitle      1963: Good Night Skopje
originalTitle     1963: Good Night Skopje
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         30
genres                  Documentary,Short
Name: 2003322, dtype: object

(9,)

tconst                       tt11821936
titleType                       tvMovie
primaryTitle      Anatomy of Black Love
originalTitle     Anatomy of Black Love
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2003323, dtype: object

(9,)

tconst              tt11821938
titleType                short
primaryTitle             Ellie
originalTitle            Ellie
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Horror,Short
Name: 2003324, dtype: object

(9,)

tconst                                tt1182193
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                            Drama,Romance
Name: 2003325, dtype: object

(9,)

tconst                               tt11821940
titleType                              tvSeries
primaryTitle      On the Spot with Mike Maguire
originalTitle     On the Spot with Mike Maguire
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                               Reality-TV
Name: 2003326, dtype: object

(9,)

tconst                tt11821942
titleType              tvEpisode
primaryTitle        Episode #5.1
originalTitle       Episode #5.1
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003327, dtype: object

(9,)

tconst                tt11821944
titleType              tvEpisode
primaryTitle        Episode #5.2
originalTitle       Episode #5.2
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003328, dtype: object

(9,)

tconst                tt11821946
titleType              tvEpisode
primaryTitle        Episode #5.3
originalTitle       Episode #5.3
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003329, dtype: object

(9,)

tconst            tt11821948
titleType              short
primaryTitle           Lotus
originalTitle          Lotus
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2003330, dtype: object

(9,)

tconst                tt1182194
titleType             tvEpisode
primaryTitle      Episode #2.23
originalTitle     Episode #2.23
isAdult                       0
startYear                  1984
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2003331, dtype: object

(9,)

tconst                tt11821950
titleType              tvEpisode
primaryTitle        Episode #5.4
originalTitle       Episode #5.4
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003332, dtype: object

(9,)

tconst                tt11821952
titleType              tvEpisode
primaryTitle        Episode #5.5
originalTitle       Episode #5.5
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003333, dtype: object

(9,)

tconst                tt11821956
titleType              tvEpisode
primaryTitle        Episode #1.2
originalTitle       Episode #1.2
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2003334, dtype: object

(9,)

tconst            tt11821958
titleType              movie
primaryTitle        Chenkodi
originalTitle       Chenkodi
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003335, dtype: object

(9,)

tconst                tt1182195
titleType             tvEpisode
primaryTitle      Episode #3.15
originalTitle     Episode #3.15
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2003336, dtype: object

(9,)

tconst                tt11821960
titleType              tvEpisode
primaryTitle        Episode #5.6
originalTitle       Episode #5.6
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003337, dtype: object

(9,)

tconst                tt11821962
titleType              tvEpisode
primaryTitle        Episode #1.3
originalTitle       Episode #1.3
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2003338, dtype: object

(9,)

tconst                tt11821964
titleType              tvEpisode
primaryTitle        Episode #5.7
originalTitle       Episode #5.7
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003339, dtype: object

(9,)

tconst                tt11821966
titleType              tvEpisode
primaryTitle        Episode #5.8
originalTitle       Episode #5.8
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003340, dtype: object

(9,)

tconst               tt1182196
titleType            tvEpisode
primaryTitle      Episode #5.9
originalTitle     Episode #5.9
isAdult                      0
startYear                 1986
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2003341, dtype: object

(9,)

tconst                tt11821970
titleType              tvEpisode
primaryTitle        Episode #5.9
originalTitle       Episode #5.9
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003342, dtype: object

(9,)

tconst                tt11821972
titleType              tvEpisode
primaryTitle       Episode #5.10
originalTitle      Episode #5.10
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003343, dtype: object

(9,)

tconst                                       tt11821974
titleType                                     tvEpisode
primaryTitle      Yves Montand face aux téléspectateurs
originalTitle     Yves Montand face aux téléspectateurs
isAdult                                               0
startYear                                          1984
endYear                                              \N
runtimeMinutes                                       \N
genres                                               \N
Name: 2003344, dtype: object

(9,)

tconst                tt11821976
titleType              tvEpisode
primaryTitle       Episode #5.11
originalTitle      Episode #5.11
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003345, dtype: object

(9,)

tconst                tt11821978
titleType              tvEpisode
primaryTitle       Episode #5.12
originalTitle      Episode #5.12
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003346, dtype: object

(9,)

tconst                tt1182197
titleType             tvEpisode
primaryTitle      Episode #5.22
originalTitle     Episode #5.22
isAdult                       0
startYear                  1987
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2003347, dtype: object

(9,)

tconst                tt11821980
titleType              tvEpisode
primaryTitle       Episode #5.14
originalTitle      Episode #5.14
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003348, dtype: object

(9,)

tconst                tt11821982
titleType              tvEpisode
primaryTitle       Episode #5.13
originalTitle      Episode #5.13
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003349, dtype: object

(9,)

tconst                tt11821984
titleType              tvEpisode
primaryTitle       Episode #5.15
originalTitle      Episode #5.15
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003350, dtype: object

(9,)

tconst                tt11821986
titleType              tvEpisode
primaryTitle       Episode #5.16
originalTitle      Episode #5.16
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003351, dtype: object

(9,)

tconst                tt11821988
titleType              tvEpisode
primaryTitle       Episode #5.18
originalTitle      Episode #5.18
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003352, dtype: object

(9,)

tconst                tt1182198
titleType             tvEpisode
primaryTitle         Bad Sister
originalTitle        Bad Sister
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2003353, dtype: object

(9,)

tconst                tt11821990
titleType              tvEpisode
primaryTitle       Episode #5.17
originalTitle      Episode #5.17
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003354, dtype: object

(9,)

tconst                tt11821992
titleType              tvEpisode
primaryTitle       Episode #5.19
originalTitle      Episode #5.19
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003355, dtype: object

(9,)

tconst                tt11821994
titleType              tvEpisode
primaryTitle       Episode #5.20
originalTitle      Episode #5.20
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2003356, dtype: object

(9,)

tconst                                      tt11821996
titleType                                    tvEpisode
primaryTitle      Alain Delon face aux télespectateurs
originalTitle     Alain Delon face aux télespectateurs
isAdult                                              0
startYear                                         1989
endYear                                             \N
runtimeMinutes                                      \N
genres                                              \N
Name: 2003357, dtype: object

(9,)

tconst            tt11821998
titleType          tvEpisode
primaryTitle          Part 3
originalTitle         Part 3
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2003358, dtype: object

(9,)

tconst                tt1182199
titleType             tvEpisode
primaryTitle          Husband 2
originalTitle         Husband 2
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2003359, dtype: object

(9,)

tconst                        tt11822000
titleType                          short
primaryTitle          Your Onion's Burnt
originalTitle         Your Onion's Burnt
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Short
Name: 2003360, dtype: object

(9,)

tconst                tt11822002
titleType                  movie
primaryTitle      Pidikittapulli
originalTitle     Pidikittapulli
isAdult                        0
startYear                   2021
endYear                       \N
runtimeMinutes                \N
genres                  Thriller
Name: 2003361, dtype: object

(9,)

tconst            tt11822004
titleType          tvEpisode
primaryTitle          Part 4
originalTitle         Part 4
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2003362, dtype: object

(9,)

tconst                 tt11822006
titleType                   movie
primaryTitle      South of Dakota
originalTitle     South of Dakota
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2003363, dtype: object

(9,)

tconst                tt1182200
titleType             tvEpisode
primaryTitle           New Home
originalTitle          New Home
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2003364, dtype: object

(9,)

tconst              tt11822010
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              49
genres               Game-Show
Name: 2003365, dtype: object

(9,)

tconst              tt11822012
titleType                short
primaryTitle        Dirty Pool
originalTitle       Dirty Pool
isAdult                      0
startYear                 2016
endYear                     \N
runtimeMinutes               2
genres            Comedy,Short
Name: 2003366, dtype: object

(9,)

tconst                                     tt11822014
titleType                                   tvEpisode
primaryTitle      Zhi yi: Wo xin chang dan - Di si ji
originalTitle     Zhi yi: Wo xin chang dan - Di si ji
isAdult                                             0
startYear                                        2000
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Drama
Name: 2003367, dtype: object

(9,)

tconst                      tt11822016
titleType                        video
primaryTitle      Ellis: All This Time
originalTitle     Ellis: All This Time
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                       4
genres                     Music,Short
Name: 2003368, dtype: object

(9,)

tconst            tt11822018
titleType          tvEpisode
primaryTitle          Plants
originalTitle         Plants
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003369, dtype: object

(9,)

tconst                                tt1182201
titleType                             tvEpisode
primaryTitle      Encontronazos y desencuentros
originalTitle     Encontronazos y desencuentros
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                      Comedy,Drama,Family
Name: 2003370, dtype: object

(9,)

tconst            tt11822020
titleType              movie
primaryTitle         Thozhan
originalTitle        Thozhan
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003371, dtype: object

(9,)

tconst            tt11822022
titleType          tvEpisode
primaryTitle         Tongues
originalTitle        Tongues
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003372, dtype: object

(9,)

tconst                tt11822026
titleType              tvEpisode
primaryTitle      Episode #1.306
originalTitle     Episode #1.306
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2003373, dtype: object

(9,)

tconst            tt11822028
titleType          tvEpisode
primaryTitle      Meditation
originalTitle     Meditation
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003374, dtype: object

(9,)

tconst                               tt1182202
titleType                            tvEpisode
primaryTitle      Episode dated 1 October 2007
originalTitle     Episode dated 1 October 2007
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                    Comedy,Drama,Romance
Name: 2003375, dtype: object

(9,)

tconst                  tt11822032
titleType                    movie
primaryTitle      The Next 12 Days
originalTitle     The Next 12 Days
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                     Romance
Name: 2003376, dtype: object

(9,)

tconst            tt11822036
titleType          tvEpisode
primaryTitle           Kambo
originalTitle          Kambo
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003377, dtype: object

(9,)

tconst            tt11822038
titleType            tvMovie
primaryTitle       Adulting.
originalTitle      Adulting.
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            30
genres                 Drama
Name: 2003378, dtype: object

(9,)

tconst                               tt1182203
titleType                            tvEpisode
primaryTitle      Episode dated 2 October 2007
originalTitle     Episode dated 2 October 2007
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                    Comedy,Drama,Romance
Name: 2003379, dtype: object

(9,)

tconst                            tt11822040
titleType                          tvEpisode
primaryTitle      Lou Perez - At the Minimum
originalTitle     Lou Perez - At the Minimum
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2003380, dtype: object

(9,)

tconst                  tt11822042
titleType                tvEpisode
primaryTitle      15 bile negre #1
originalTitle     15 bile negre #1
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  42
genres                      Comedy
Name: 2003381, dtype: object

(9,)

tconst                                        tt11822044
titleType                                      tvEpisode
primaryTitle      In Conversation with Robin Coste Lewis
originalTitle     In Conversation with Robin Coste Lewis
isAdult                                                0
startYear                                           2019
endYear                                               \N
runtimeMinutes                                        \N
genres                                              News
Name: 2003382, dtype: object

(9,)

tconst              tt11822046
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              85
genres               Talk-Show
Name: 2003383, dtype: object

(9,)

tconst                         tt11822048
titleType                       tvEpisode
primaryTitle      Rata, cap de piatra! #2
originalTitle     Rata, cap de piatra! #2
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         48
genres                             Comedy
Name: 2003384, dtype: object

(9,)

tconst                               tt1182204
titleType                            tvEpisode
primaryTitle      Episode dated 3 October 2007
originalTitle     Episode dated 3 October 2007
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                    Comedy,Drama,Romance
Name: 2003385, dtype: object

(9,)

tconst                         tt11822050
titleType                       tvEpisode
primaryTitle      Rata, cap de piatra! #1
originalTitle     Rata, cap de piatra! #1
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         49
genres                             Comedy
Name: 2003386, dtype: object

(9,)

tconst                                tt11822052
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003387, dtype: object

(9,)

tconst               tt11822054
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                  2015
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2003388, dtype: object

(9,)

tconst                             tt11822058
titleType                           tvEpisode
primaryTitle              Brian O'Dea/Pat Nee
originalTitle             Brian O'Dea/Pat Nee
isAdult                                     0
startYear                                2016
endYear                                    \N
runtimeMinutes                             46
genres            Biography,Crime,Documentary
Name: 2003389, dtype: object

(9,)

tconst                               tt1182205
titleType                            tvEpisode
primaryTitle      Episode dated 4 October 2007
originalTitle     Episode dated 4 October 2007
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                    Comedy,Drama,Romance
Name: 2003390, dtype: object

(9,)

tconst                                       tt11822060
titleType                                     tvEpisode
primaryTitle      Cucked: GOP Revives Mass Amnesty Bill
originalTitle     Cucked: GOP Revives Mass Amnesty Bill
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                             News
Name: 2003391, dtype: object

(9,)

tconst                                            tt11822062
titleType                                          tvEpisode
primaryTitle      Frank 'The Irishman' Sheeran/Whitey Bulger
originalTitle     Frank 'The Irishman' Sheeran/Whitey Bulger
isAdult                                                    0
startYear                                               2016
endYear                                                   \N
runtimeMinutes                                            \N
genres                           Biography,Crime,Documentary
Name: 2003392, dtype: object

(9,)

tconst                tt11822068
titleType              tvEpisode
primaryTitle      Trollstigvegen
originalTitle     Trollstigvegen
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2003393, dtype: object

(9,)

tconst                       tt1182206
titleType                    tvEpisode
primaryTitle      Spirituality Seekers
originalTitle     Spirituality Seekers
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2003394, dtype: object

(9,)

tconst                       tt11822070
titleType                     tvEpisode
primaryTitle      Girlfriend Getaways 2
originalTitle     Girlfriend Getaways 2
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                 Family,Game-Show
Name: 2003395, dtype: object

(9,)

tconst                                                   tt11822072
titleType                                                 tvEpisode
primaryTitle      America for Sale??? Bezos and Bloomberg Pledge...
originalTitle     America for Sale??? Bezos and Bloomberg Pledge...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2003396, dtype: object

(9,)

tconst               tt11822074
titleType                 short
primaryTitle      Monsoon Clips
originalTitle     Monsoon Clips
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               12
genres                    Short
Name: 2003397, dtype: object

(9,)

tconst               tt11822076
titleType             tvEpisode
primaryTitle         Hot N Cold
originalTitle        Hot N Cold
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2003398, dtype: object

(9,)

tconst                                               tt1182207
titleType                                            tvEpisode
primaryTitle      Billy J Kramer & the Dakotas, Dick & Dee Dee
originalTitle     Billy J Kramer & the Dakotas, Dick & Dee Dee
isAdult                                                      0
startYear                                                 1964
endYear                                                     \N
runtimeMinutes                                              \N
genres                                            Family,Music
Name: 2003399, dtype: object

(9,)

tconst                 tt11822086
titleType               tvEpisode
primaryTitle      Episode #36.117
originalTitle     Episode #36.117
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                  Game-Show
Name: 2003400, dtype: object

(9,)

tconst                                      tt1182208
titleType                                   tvEpisode
primaryTitle      Nelly & The St. Lunatics/Spooks/B2K
originalTitle     Nelly & The St. Lunatics/Spooks/B2K
isAdult                                             0
startYear                                        2001
endYear                                            \N
runtimeMinutes                                     \N
genres                                Music,Talk-Show
Name: 2003401, dtype: object

(9,)

tconst                 tt11822090
titleType               tvEpisode
primaryTitle      Episode #36.118
originalTitle     Episode #36.118
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                  Game-Show
Name: 2003402, dtype: object

(9,)

tconst            tt11822092
titleType           tvSeries
primaryTitle      Hvem lyver
originalTitle     Hvem lyver
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Game-Show
Name: 2003403, dtype: object

(9,)

tconst                 tt11822094
titleType                   short
primaryTitle      Stardust Memory
originalTitle     Stardust Memory
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres              Romance,Short
Name: 2003404, dtype: object

(9,)

tconst                     tt11822096
titleType                       short
primaryTitle      Blood on My Vuitton
originalTitle     Blood on My Vuitton
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                   Comedy,Short
Name: 2003405, dtype: object

(9,)

tconst            tt11822098
titleType              movie
primaryTitle         Hostage
originalTitle        Hostage
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres              Thriller
Name: 2003406, dtype: object

(9,)

tconst                                                    tt1182209
titleType                                                 tvEpisode
primaryTitle      Rachelle Ferrell/Changing Faces/Lil Bow Wow Fe...
originalTitle     Rachelle Ferrell/Changing Faces/Lil Bow Wow Fe...
isAdult                                                           0
startYear                                                      2000
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                              Music,Talk-Show
Name: 2003407, dtype: object

(9,)

tconst                              tt11822100
titleType                            tvEpisode
primaryTitle      Learning Numbers From 1 to 9
originalTitle     Learning Numbers From 1 to 9
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                         Animation,Short
Name: 2003408, dtype: object

(9,)

tconst                                      tt11822102
titleType                                    tvEpisode
primaryTitle      Superhero Helps with Gumball Machine
originalTitle     Superhero Helps with Gumball Machine
isAdult                                              0
startYear                                         2018
endYear                                             \N
runtimeMinutes                                      \N
genres                                 Animation,Short
Name: 2003409, dtype: object

(9,)

tconst                         tt11822106
titleType                       tvEpisode
primaryTitle      Making World Cup Trophy
originalTitle     Making World Cup Trophy
isAdult                                 0
startYear                            2018
endYear                                \N
runtimeMinutes                         \N
genres                    Animation,Short
Name: 2003410, dtype: object

(9,)

tconst                 tt11822108
titleType               tvEpisode
primaryTitle           At The Zoo
originalTitle          At The Zoo
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2003411, dtype: object

(9,)

tconst                                     tt1182210
titleType                                  tvEpisode
primaryTitle      Tamia/Avant/Ced Featuring C. Black
originalTitle     Tamia/Avant/Ced Featuring C. Black
isAdult                                            0
startYear                                       2000
endYear                                           \N
runtimeMinutes                                    \N
genres                               Music,Talk-Show
Name: 2003412, dtype: object

(9,)

tconst                        tt11822110
titleType                      tvEpisode
primaryTitle      Disorder Sleeping Time
originalTitle     Disorder Sleeping Time
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                   Animation,Short
Name: 2003413, dtype: object

(9,)

tconst             tt11822112
titleType            tvSeries
primaryTitle      Filmbonanza
originalTitle     Filmbonanza
isAdult                     0
startYear                2010
endYear                  2014
runtimeMinutes             \N
genres              Talk-Show
Name: 2003414, dtype: object

(9,)

tconst                                tt11822114
titleType                              tvEpisode
primaryTitle      Policeman Helping Other Babies
originalTitle     Policeman Helping Other Babies
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                           Animation,Short
Name: 2003415, dtype: object

(9,)

tconst                                       tt11822118
titleType                                         movie
primaryTitle      Carola Neher - Todesursache unbekannt
originalTitle     Carola Neher - Todesursache unbekannt
isAdult                                               0
startYear                                          2015
endYear                                              \N
runtimeMinutes                                       45
genres                                        Biography
Name: 2003416, dtype: object

(9,)

tconst                          tt1182211
titleType                       tvEpisode
primaryTitle                   Mommentary
originalTitle                  Mommentary
isAdult                                 0
startYear                            2001
endYear                                \N
runtimeMinutes                         \N
genres            Animation,Comedy,Sci-Fi
Name: 2003417, dtype: object

(9,)

tconst                              tt11822120
titleType                            tvEpisode
primaryTitle      Funny Time at the Playground
originalTitle     Funny Time at the Playground
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                         Animation,Short
Name: 2003418, dtype: object

(9,)

tconst                       tt11822122
titleType                     tvEpisode
primaryTitle      New Ice Cream Machine
originalTitle     New Ice Cream Machine
isAdult                               0
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                  Animation,Short
Name: 2003419, dtype: object

(9,)

tconst                          tt11822124
titleType                        tvEpisode
primaryTitle      Playing With Magic Molds
originalTitle     Playing With Magic Molds
isAdult                                  0
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                     Animation,Short
Name: 2003420, dtype: object

(9,)

tconst             tt11822126
titleType               short
primaryTitle           Mütter
originalTitle          Mütter
isAdult                     0
startYear                2016
endYear                    \N
runtimeMinutes             30
genres            Drama,Short
Name: 2003421, dtype: object

(9,)

tconst                                 tt11822128
titleType                               tvEpisode
primaryTitle      Yellow Baby Buy New Online Doll
originalTitle     Yellow Baby Buy New Online Doll
isAdult                                         0
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                            Animation,Short
Name: 2003422, dtype: object

(9,)

tconst                      tt1182212
titleType                   tvEpisode
primaryTitle      Het oog van de beer
originalTitle     Het oog van de beer
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                   Action,Drama
Name: 2003423, dtype: object

(9,)

tconst                 tt11822130
titleType               tvEpisode
primaryTitle          Adopt a Pet
originalTitle         Adopt a Pet
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2003424, dtype: object

(9,)

tconst                                        tt11822132
titleType                                      tvEpisode
primaryTitle      Rainbow Fashion Style With Yellow Baby
originalTitle     Rainbow Fashion Style With Yellow Baby
isAdult                                                0
startYear                                           2018
endYear                                               \N
runtimeMinutes                                        \N
genres                                   Animation,Short
Name: 2003425, dtype: object

(9,)

tconst                             tt11822134
titleType                           tvEpisode
primaryTitle                    Loyal Subject
originalTitle                   Loyal Subject
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             84
genres            Biography,Documentary,Drama
Name: 2003426, dtype: object

(9,)

tconst                 tt11822136
titleType               tvEpisode
primaryTitle      Making Pancakes
originalTitle     Making Pancakes
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2003427, dtype: object

(9,)

tconst                    tt11822138
titleType                      movie
primaryTitle      The Mona Lisa Five
originalTitle     The Mona Lisa Five
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                   105
genres                        Comedy
Name: 2003428, dtype: object

(9,)

tconst                         tt1182213
titleType                      tvEpisode
primaryTitle      Javier Bardem/Amy Ryan
originalTitle     Javier Bardem/Amy Ryan
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2003429, dtype: object

(9,)

tconst                            tt11822140
titleType                          tvEpisode
primaryTitle      Babysitting Little Kittens
originalTitle     Babysitting Little Kittens
isAdult                                    0
startYear                               2018
endYear                                   \N
runtimeMinutes                            \N
genres                       Animation,Short
Name: 2003430, dtype: object

(9,)

tconst                                  tt11822142
titleType                                tvEpisode
primaryTitle      A Retrospective Of Devil May Cry
originalTitle     A Retrospective Of Devil May Cry
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                      Comedy
Name: 2003431, dtype: object

(9,)

tconst                                tt11822144
titleType                              tvEpisode
primaryTitle      Nicolay Ramm og Herman Flesvig
originalTitle     Nicolay Ramm og Herman Flesvig
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                 Game-Show
Name: 2003432, dtype: object

(9,)

tconst                         tt1182214
titleType                      tvEpisode
primaryTitle      Oscar Nominees Special
originalTitle     Oscar Nominees Special
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2003433, dtype: object

(9,)

tconst                               tt11822150
titleType                             tvEpisode
primaryTitle      Astrid S og Kjartan Lauritzen
originalTitle     Astrid S og Kjartan Lauritzen
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                                Game-Show
Name: 2003434, dtype: object

(9,)

tconst                                tt11822154
titleType                              tvEpisode
primaryTitle      Isabel Raad og Kristine Ullebø
originalTitle     Isabel Raad og Kristine Ullebø
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                 Game-Show
Name: 2003435, dtype: object

(9,)

tconst                 tt11822156
titleType               tvEpisode
primaryTitle      Jonas og Martha
originalTitle     Jonas og Martha
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                  Game-Show
Name: 2003436, dtype: object

(9,)

tconst                                    tt11822158
titleType                                  tvEpisode
primaryTitle      Jonis Josef og Christian Mikkelsen
originalTitle     Jonis Josef og Christian Mikkelsen
isAdult                                            0
startYear                                       2019
endYear                                           \N
runtimeMinutes                                    \N
genres                                     Game-Show
Name: 2003437, dtype: object

(9,)

tconst                                           tt1182215
titleType                                        tvEpisode
primaryTitle      Maza: Ta ihni mias allis pragmatikotitas
originalTitle     Maza: Ta ihni mias allis pragmatikotitas
isAdult                                                  0
startYear                                             2005
endYear                                                 \N
runtimeMinutes                                          \N
genres                                         Documentary
Name: 2003438, dtype: object

(9,)

tconst                          tt11822160
titleType                        tvEpisode
primaryTitle      Amalie Olsen og Randulle
originalTitle     Amalie Olsen og Randulle
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          \N
genres                           Game-Show
Name: 2003439, dtype: object

(9,)

tconst                                    tt11822162
titleType                                  tvEpisode
primaryTitle      Anniken Jørgensen og Joakim Kleven
originalTitle     Anniken Jørgensen og Joakim Kleven
isAdult                                            0
startYear                                       2019
endYear                                           \N
runtimeMinutes                                    \N
genres                                     Game-Show
Name: 2003440, dtype: object

(9,)

tconst                            tt11822164
titleType                          tvEpisode
primaryTitle      Murdrocks og Henrik Farley
originalTitle     Murdrocks og Henrik Farley
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                             Game-Show
Name: 2003441, dtype: object

(9,)

tconst                                 tt11822166
titleType                               tvEpisode
primaryTitle      Ulrikke Falch og Gisle Agledahl
originalTitle     Ulrikke Falch og Gisle Agledahl
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Game-Show
Name: 2003442, dtype: object

(9,)

tconst                            tt11822168
titleType                          tvEpisode
primaryTitle      Piateed og Martin Lepperød
originalTitle     Piateed og Martin Lepperød
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                             Game-Show
Name: 2003443, dtype: object

(9,)

tconst                tt1182216
titleType             tvEpisode
primaryTitle      Episode #5.20
originalTitle     Episode #5.20
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2003444, dtype: object

(9,)

tconst            tt11822170
titleType          tvEpisode
primaryTitle       The Hotel
originalTitle      The Hotel
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Crime
Name: 2003445, dtype: object

(9,)

tconst                                tt11822172
titleType                                  video
primaryTitle      The Bachelor: Princess Edition
originalTitle     The Bachelor: Princess Edition
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                              Comedy,Short
Name: 2003446, dtype: object

(9,)

tconst                    tt11822174
titleType                  tvEpisode
primaryTitle        Schlüsselmomente
originalTitle       Schlüsselmomente
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003447, dtype: object

(9,)

tconst                        tt11822176
titleType                      tvEpisode
primaryTitle      Die Frau auf der Insel
originalTitle     Die Frau auf der Insel
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                Comedy,Crime,Drama
Name: 2003448, dtype: object

(9,)

tconst                     tt11822178
titleType                    tvSeries
primaryTitle      I Larsens leilighet
originalTitle     I Larsens leilighet
isAdult                             0
startYear                        2015
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2003449, dtype: object

(9,)

tconst                      tt1182217
titleType                   tvEpisode
primaryTitle           Episode #13.60
originalTitle          Episode #13.60
isAdult                             0
startYear                        2007
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2003450, dtype: object

(9,)

tconst                               tt11822180
titleType                             tvEpisode
primaryTitle      Episode dated 23 October 2014
originalTitle     Episode dated 23 October 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2003451, dtype: object

(9,)

tconst                              tt11822182
titleType                            tvEpisode
primaryTitle      Episode dated 9 October 2014
originalTitle     Episode dated 9 October 2014
isAdult                                      0
startYear                                 2014
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2003452, dtype: object

(9,)

tconst                              tt11822184
titleType                            tvEpisode
primaryTitle      Episode dated 2 October 2014
originalTitle     Episode dated 2 October 2014
isAdult                                      0
startYear                                 2014
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2003453, dtype: object

(9,)

tconst                 tt11822186
titleType               tvEpisode
primaryTitle      Bjørn Sundquist
originalTitle     Bjørn Sundquist
isAdult                         0
startYear                    2015
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2003454, dtype: object

(9,)

tconst             tt11822188
titleType           tvEpisode
primaryTitle      Liv Ullmann
originalTitle     Liv Ullmann
isAdult                     0
startYear                2016
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2003455, dtype: object

(9,)

tconst             tt1182218
titleType          tvEpisode
primaryTitle      Doctor Who
originalTitle     Doctor Who
isAdult                    0
startYear               1996
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2003456, dtype: object

(9,)

tconst               tt11822190
titleType             tvEpisode
primaryTitle      Kari Simonsen
originalTitle     Kari Simonsen
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2003457, dtype: object

(9,)

tconst                       tt11822192
titleType                      tvSeries
primaryTitle      A Tribe Called Sketch
originalTitle     A Tribe Called Sketch
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                           Comedy
Name: 2003458, dtype: object

(9,)

tconst                tt11822194
titleType              tvEpisode
primaryTitle       Episode #2.24
originalTitle      Episode #2.24
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2003459, dtype: object

(9,)

tconst             tt11822196
titleType           tvEpisode
primaryTitle      Linn Skåber
originalTitle     Linn Skåber
isAdult                     0
startYear                2015
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2003460, dtype: object

(9,)

tconst                   tt11822198
titleType                 tvEpisode
primaryTitle      Ingar Helge Gimle
originalTitle     Ingar Helge Gimle
isAdult                           0
startYear                      2015
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2003461, dtype: object

(9,)

tconst                tt1182219
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2003462, dtype: object

(9,)

tconst             tt11822200
titleType               short
primaryTitle          Stopped
originalTitle         Stopped
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes              5
genres            Drama,Short
Name: 2003463, dtype: object

(9,)

tconst                                                   tt11822202
titleType                                                 tvEpisode
primaryTitle      The Priest's Confession: What the Bishops Knew...
originalTitle     The Priest's Confession: What the Bishops Knew...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                             Documentary,News
Name: 2003464, dtype: object

(9,)

tconst              tt11822206
titleType         tvMiniSeries
primaryTitle             Scoot
originalTitle            Scoot
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2003465, dtype: object

(9,)

tconst             tt11822208
titleType               short
primaryTitle              Sum
originalTitle             Sum
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes              9
genres            Drama,Short
Name: 2003466, dtype: object

(9,)

tconst                                tt1182220
titleType                             tvEpisode
primaryTitle      Episode dated 3 December 1993
originalTitle     Episode dated 3 December 1993
isAdult                                       0
startYear                                  1993
endYear                                      \N
runtimeMinutes                               \N
genres                              Documentary
Name: 2003467, dtype: object

(9,)

tconst                    tt11822214
titleType                  tvEpisode
primaryTitle      Fishing Baby Shark
originalTitle     Fishing Baby Shark
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres               Animation,Short
Name: 2003468, dtype: object

(9,)

tconst                               tt11822218
titleType                             tvEpisode
primaryTitle      Draupadi Proves Her Innocence
originalTitle     Draupadi Proves Her Innocence
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                Drama,War
Name: 2003469, dtype: object

(9,)

tconst                   tt1182221
titleType                tvEpisode
primaryTitle      Mom vs. Daughter
originalTitle     Mom vs. Daughter
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  43
genres                  Reality-TV
Name: 2003470, dtype: object

(9,)

tconst                   tt11822220
titleType                     short
primaryTitle           Heavy Breath
originalTitle          Heavy Breath
isAdult                           0
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2003471, dtype: object

(9,)

tconst            tt11822222
titleType          tvEpisode
primaryTitle        Honestly
originalTitle       Honestly
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003472, dtype: object

(9,)

tconst                        tt11822224
titleType                          short
primaryTitle         Trapped in Darkness
originalTitle        Trapped in Darkness
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        29
genres            Animation,Horror,Short
Name: 2003473, dtype: object

(9,)

tconst                tt11822226
titleType              tvEpisode
primaryTitle      Episode #1.159
originalTitle     Episode #1.159
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2003474, dtype: object

(9,)

tconst                       tt11822228
titleType                     tvEpisode
primaryTitle      Homicide on the Rails
originalTitle     Homicide on the Rails
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       42
genres                            Crime
Name: 2003475, dtype: object

(9,)

tconst                     tt1182222
titleType                   tvSeries
primaryTitle      Turnin' to Country
originalTitle     Turnin' to Country
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres                    Reality-TV
Name: 2003476, dtype: object

(9,)

tconst                                                  tt11822234
titleType                                                    video
primaryTitle      Kokujin kyodai mara VS gen'eki kokutai karate-ka
originalTitle     Kokujin kyodai mara VS gen'eki kokutai karate-ka
isAdult                                                          0
startYear                                                     2014
endYear                                                         \N
runtimeMinutes                                                 120
genres                                                      Action
Name: 2003477, dtype: object

(9,)

tconst                        tt11822236
titleType                          movie
primaryTitle      The Secret of Princess
originalTitle     The Secret of Princess
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                            Action
Name: 2003478, dtype: object

(9,)

tconst                                                   tt11822238
titleType                                                 tvEpisode
primaryTitle      4 Ways You're Failing At Being An Adult You're...
originalTitle     4 Ways You're Failing At Being An Adult You're...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                      Comedy,Reality-TV,Short
Name: 2003479, dtype: object

(9,)

tconst                 tt1182223
titleType              tvEpisode
primaryTitle      Cyber Bullying
originalTitle     Cyber Bullying
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2003480, dtype: object

(9,)

tconst                         tt11822240
titleType                           short
primaryTitle      Don't Talk to Strangers
originalTitle     Don't Talk to Strangers
isAdult                                 0
startYear                            2015
endYear                                \N
runtimeMinutes                         \N
genres                        Crime,Short
Name: 2003481, dtype: object

(9,)

tconst                                tt11822242
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2003482, dtype: object

(9,)

tconst                tt11822244
titleType                  movie
primaryTitle      Manje Bistre 3
originalTitle     Manje Bistre 3
isAdult                        0
startYear                   2021
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2003483, dtype: object

(9,)

tconst            tt11822248
titleType              movie
primaryTitle        Handyman
originalTitle       Handyman
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Horror
Name: 2003484, dtype: object

(9,)

tconst                         tt1182224
titleType                      tvEpisode
primaryTitle           Asedio (1ª parte)
originalTitle          Asedio (1ª parte)
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres            Action,Adventure,Crime
Name: 2003485, dtype: object

(9,)

tconst                    tt11822250
titleType                  tvEpisode
primaryTitle      Mei Li Da Diao Cha
originalTitle     Mei Li Da Diao Cha
isAdult                            0
startYear                       2010
endYear                           \N
runtimeMinutes                     7
genres                        Comedy
Name: 2003486, dtype: object

(9,)

tconst                tt11822252
titleType                  video
primaryTitle      Way. Way. Back
originalTitle     Way. Way. Back
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres               Music,Short
Name: 2003487, dtype: object

(9,)

tconst                                                   tt11822254
titleType                                                 tvEpisode
primaryTitle      College Kids React To College Kids Reacting To...
originalTitle     College Kids React To College Kids Reacting To...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2003488, dtype: object

(9,)

tconst              tt11822256
titleType            tvEpisode
primaryTitle      Ian McKellen
originalTitle     Ian McKellen
isAdult                      0
startYear                 1981
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2003489, dtype: object

(9,)

tconst                               tt11822258
titleType                             tvEpisode
primaryTitle      Episode dated 2 November 2018
originalTitle     Episode dated 2 November 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2003490, dtype: object

(9,)

tconst               tt1182225
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 2006
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003491, dtype: object

(9,)

tconst                 tt11822262
titleType               tvEpisode
primaryTitle           Bill Cosby
originalTitle          Bill Cosby
isAdult                         0
startYear                    1971
endYear                        \N
runtimeMinutes                 64
genres            Music,Talk-Show
Name: 2003492, dtype: object

(9,)

tconst                tt11822264
titleType              tvEpisode
primaryTitle       Episode #4.24
originalTitle      Episode #4.24
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2003493, dtype: object

(9,)

tconst              tt11822266
titleType            tvEpisode
primaryTitle      Leckerbissen
originalTitle     Leckerbissen
isAdult                      0
startYear                 1963
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2003494, dtype: object

(9,)

tconst                        tt11822268
titleType                      tvEpisode
primaryTitle      Traumschlösser am Meer
originalTitle     Traumschlösser am Meer
isAdult                                0
startYear                           1963
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2003495, dtype: object

(9,)

tconst               tt1182226
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 2006
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003496, dtype: object

(9,)

tconst               tt11822270
titleType             tvEpisode
primaryTitle      Europas Uhren
originalTitle     Europas Uhren
isAdult                       0
startYear                  1963
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2003497, dtype: object

(9,)

tconst                  tt11822272
titleType                tvEpisode
primaryTitle      Türme und Flüsse
originalTitle     Türme und Flüsse
isAdult                          0
startYear                     1963
endYear                         \N
runtimeMinutes                  \N
genres                 Documentary
Name: 2003498, dtype: object

(9,)

tconst                            tt11822274
titleType                          tvEpisode
primaryTitle      Europas bekannteste Garden
originalTitle     Europas bekannteste Garden
isAdult                                    0
startYear                               1963
endYear                                   \N
runtimeMinutes                            \N
genres                           Documentary
Name: 2003499, dtype: object

(9,)

tconst                    tt11822276
titleType                  tvEpisode
primaryTitle      Früchte des Meeres
originalTitle     Früchte des Meeres
isAdult                            0
startYear                       1963
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2003500, dtype: object

(9,)

tconst                    tt11822278
titleType                  tvEpisode
primaryTitle      Flüsse und Brücken
originalTitle     Flüsse und Brücken
isAdult                            0
startYear                       1964
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2003501, dtype: object

(9,)

tconst                          tt1182227
titleType                       tvEpisode
primaryTitle                Episode #3.25
originalTitle               Episode #3.25
isAdult                                 0
startYear                            1991
endYear                                \N
runtimeMinutes                         \N
genres            Crime,Documentary,Drama
Name: 2003502, dtype: object

(9,)

tconst                   tt11822280
titleType                 tvEpisode
primaryTitle      Tore in die Ferne
originalTitle     Tore in die Ferne
isAdult                           0
startYear                      1964
endYear                          \N
runtimeMinutes                   \N
genres                  Documentary
Name: 2003503, dtype: object

(9,)

tconst                            tt11822282
titleType                          tvEpisode
primaryTitle      Phantastische Landschaften
originalTitle     Phantastische Landschaften
isAdult                                    0
startYear                               1963
endYear                                   \N
runtimeMinutes                            \N
genres                           Documentary
Name: 2003504, dtype: object

(9,)

tconst                                  tt11822284
titleType                                tvEpisode
primaryTitle      Wei Guo Pian: Shi Ren De Mo Zhou
originalTitle     Wei Guo Pian: Shi Ren De Mo Zhou
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  65
genres                                 Documentary
Name: 2003505, dtype: object

(9,)

tconst                    tt11822286
titleType                  tvEpisode
primaryTitle      Ying Xiong Jiu Mei
originalTitle     Ying Xiong Jiu Mei
isAdult                            0
startYear                       2010
endYear                           \N
runtimeMinutes                     8
genres                        Comedy
Name: 2003506, dtype: object

(9,)

tconst                         tt11822288
titleType                       tvEpisode
primaryTitle      Wie sie einander grüßen
originalTitle     Wie sie einander grüßen
isAdult                                 0
startYear                            1964
endYear                                \N
runtimeMinutes                         \N
genres                        Documentary
Name: 2003507, dtype: object

(9,)

tconst                      tt1182228
titleType                   tvEpisode
primaryTitle            Episode #1.10
originalTitle           Episode #1.10
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2003508, dtype: object

(9,)

tconst                tt11822290
titleType              tvEpisode
primaryTitle      Europas Märkte
originalTitle     Europas Märkte
isAdult                        0
startYear                   1964
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2003509, dtype: object

(9,)

tconst                                 tt11822292
titleType                                   short
primaryTitle      Art Riot: Post-Soviet Actionism
originalTitle     Art Riot: Post-Soviet Actionism
isAdult                                         0
startYear                                    2017
endYear                                        \N
runtimeMinutes                                 12
genres                          Documentary,Short
Name: 2003510, dtype: object

(9,)

tconst                tt11822294
titleType              tvEpisode
primaryTitle      Vincent Scully
originalTitle     Vincent Scully
isAdult                        0
startYear                   1979
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2003511, dtype: object

(9,)

tconst                  tt11822296
titleType                tvEpisode
primaryTitle      Jie Ai Shun Bian
originalTitle     Jie Ai Shun Bian
isAdult                          0
startYear                     2010
endYear                         \N
runtimeMinutes                   5
genres                      Comedy
Name: 2003512, dtype: object

(9,)

tconst                tt11822298
titleType              tvEpisode
primaryTitle      Surprise Party
originalTitle     Surprise Party
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                 9
genres                    Comedy
Name: 2003513, dtype: object

(9,)

tconst                      tt1182229
titleType                   tvEpisode
primaryTitle            Episode #1.11
originalTitle           Episode #1.11
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2003514, dtype: object

(9,)

tconst                       tt11822300
titleType                     tvEpisode
primaryTitle      Kaalil Chuttiya Valli
originalTitle     Kaalil Chuttiya Valli
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       14
genres                     Comedy,Short
Name: 2003515, dtype: object

(9,)

tconst                             tt11822302
titleType                           tvEpisode
primaryTitle      2018 MAMA Premiere in Korea
originalTitle     2018 MAMA Premiere in Korea
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Music
Name: 2003516, dtype: object

(9,)

tconst                                 tt11822304
titleType                               tvEpisode
primaryTitle      2018 MAMA Fans' Choice in Japan
originalTitle     2018 MAMA Fans' Choice in Japan
isAdult                                         0
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Music
Name: 2003517, dtype: object

(9,)

tconst                        tt11822306
titleType                      tvEpisode
primaryTitle      2018 MAMA in Hong Kong
originalTitle     2018 MAMA in Hong Kong
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Music
Name: 2003518, dtype: object

(9,)

tconst              tt11822308
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2003519, dtype: object

(9,)

tconst                          tt1182230
titleType                       tvEpisode
primaryTitle                  Enloquéceme
originalTitle                 Enloquéceme
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2003520, dtype: object

(9,)

tconst                               tt11822310
titleType                             tvEpisode
primaryTitle      2017 MAMA Premiere in Vietnam
originalTitle     2017 MAMA Premiere in Vietnam
isAdult                                       0
startYear                                  2017
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2003521, dtype: object

(9,)

tconst              tt11822312
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2003522, dtype: object

(9,)

tconst              tt11822314
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2003523, dtype: object

(9,)

tconst                    tt11822316
titleType                  tvEpisode
primaryTitle      2017 MAMA in Japan
originalTitle     2017 MAMA in Japan
isAdult                            0
startYear                       2017
endYear                           \N
runtimeMinutes                    \N
genres                         Music
Name: 2003524, dtype: object

(9,)

tconst                        tt11822318
titleType                      tvEpisode
primaryTitle      2017 MAMA in Hong Kong
originalTitle     2017 MAMA in Hong Kong
isAdult                                0
startYear                           2017
endYear                               \N
runtimeMinutes                        \N
genres                             Music
Name: 2003525, dtype: object

(9,)

tconst                          tt1182231
titleType                       tvEpisode
primaryTitle             Entra en mi vida
originalTitle            Entra en mi vida
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2003526, dtype: object

(9,)

tconst                              tt11822322
titleType                            tvEpisode
primaryTitle      2016 Mnet Asian Music Awards
originalTitle     2016 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2016
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2003527, dtype: object

(9,)

tconst                tt11822324
titleType              tvEpisode
primaryTitle      Sevda Baskadir
originalTitle     Sevda Baskadir
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2003528, dtype: object

(9,)

tconst                              tt11822326
titleType                            tvEpisode
primaryTitle      2015 Mnet Asian Music Awards
originalTitle     2015 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2015
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2003529, dtype: object

(9,)

tconst                    tt11822328
titleType                  tvEpisode
primaryTitle      A Pandoran Wedding
originalTitle     A Pandoran Wedding
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    36
genres                    Reality-TV
Name: 2003530, dtype: object

(9,)

tconst                          tt1182232
titleType                       tvEpisode
primaryTitle                   Kilometros
originalTitle                  Kilometros
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2003531, dtype: object

(9,)

tconst                              tt11822330
titleType                            tvEpisode
primaryTitle      2014 Mnet Asian Music Awards
originalTitle     2014 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2014
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2003532, dtype: object

(9,)

tconst                              tt11822332
titleType                            tvEpisode
primaryTitle      2013 Mnet Asian Music Awards
originalTitle     2013 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2013
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2003533, dtype: object

(9,)

tconst                              tt11822334
titleType                            tvEpisode
primaryTitle      2012 Mnet Asian Music Awards
originalTitle     2012 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2012
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2003534, dtype: object

(9,)

tconst              tt11822336
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2003535, dtype: object

(9,)

tconst                              tt11822338
titleType                            tvEpisode
primaryTitle      2011 Mnet Asian Music Awards
originalTitle     2011 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2011
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2003536, dtype: object

(9,)

tconst                          tt1182233
titleType                       tvEpisode
primaryTitle                    Puede ser
originalTitle                   Puede ser
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Family
Name: 2003537, dtype: object

(9,)

tconst              tt11822340
titleType            tvEpisode
primaryTitle      Episode #2.9
originalTitle     Episode #2.9
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2003538, dtype: object

(9,)

tconst                     tt11822342
titleType                   tvEpisode
primaryTitle      Yeniden Sever Misin
originalTitle     Yeniden Sever Misin
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                 Comedy,Romance
Name: 2003539, dtype: object

(9,)

tconst                                tt11822344
titleType                              tvEpisode
primaryTitle      Episode dated 22 February 2020
originalTitle     Episode dated 22 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                          Comedy,Talk-Show
Name: 2003540, dtype: object

(9,)

tconst                              tt11822346
titleType                            tvEpisode
primaryTitle      2010 Mnet Asian Music Awards
originalTitle     2010 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2010
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2003541, dtype: object

(9,)

tconst                             tt11822348
titleType                           tvEpisode
primaryTitle      Qi Guo Pian: Jin Sui Zhi Mi
originalTitle     Qi Guo Pian: Jin Sui Zhi Mi
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             65
genres                            Documentary
Name: 2003542, dtype: object

(9,)

tconst                                tt1182234
titleType                             tvEpisode
primaryTitle                 Geoffrey Robertson
originalTitle                Geoffrey Robertson
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres            Biography,Documentary,History
Name: 2003543, dtype: object

(9,)

tconst                tt11822350
titleType              tvEpisode
primaryTitle      Episode #10.16
originalTitle     Episode #10.16
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2003544, dtype: object

(9,)

tconst                  tt11822352
titleType                tvEpisode
primaryTitle        Episode #1.813
originalTitle       Episode #1.813
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003545, dtype: object

(9,)

tconst                                 tt11822354
titleType                               tvEpisode
primaryTitle      Existenzieller Kostümwettbewerb
originalTitle     Existenzieller Kostümwettbewerb
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                           Drama,Reality-TV
Name: 2003546, dtype: object

(9,)

tconst                  tt11822356
titleType                tvEpisode
primaryTitle        Episode #1.814
originalTitle       Episode #1.814
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003547, dtype: object

(9,)

tconst                             tt11822358
titleType                           tvEpisode
primaryTitle      Von der Bettkante gestoßen!
originalTitle     Von der Bettkante gestoßen!
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                       Drama,Reality-TV
Name: 2003548, dtype: object

(9,)

tconst                   tt1182235
titleType                tvEpisode
primaryTitle           Sir William
originalTitle          Sir William
isAdult                          0
startYear                     1994
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2003549, dtype: object

(9,)

tconst              tt11822360
titleType         tvMiniSeries
primaryTitle      Ushi & Dushi
originalTitle     Ushi & Dushi
isAdult                      0
startYear                 2009
endYear                   2009
runtimeMinutes              35
genres                  Comedy
Name: 2003550, dtype: object

(9,)

tconst                  tt11822362
titleType                tvEpisode
primaryTitle        Episode #1.815
originalTitle       Episode #1.815
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003551, dtype: object

(9,)

tconst                      tt11822364
titleType                    tvEpisode
primaryTitle                   Lanetli
originalTitle                  Lanetli
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2003552, dtype: object

(9,)

tconst              tt11822368
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003553, dtype: object

(9,)

tconst                 tt1182236
titleType              tvEpisode
primaryTitle      Episode #10.30
originalTitle     Episode #10.30
isAdult                        0
startYear                   1990
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2003554, dtype: object

(9,)

tconst               tt11822370
titleType          tvMiniSeries
primaryTitle      Ushi & Loesie
originalTitle     Ushi & Loesie
isAdult                       0
startYear                  2010
endYear                    2010
runtimeMinutes               35
genres                   Comedy
Name: 2003555, dtype: object

(9,)

tconst               tt11822372
titleType                 movie
primaryTitle      The Rage Doll
originalTitle     The Rage Doll
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Horror
Name: 2003556, dtype: object

(9,)

tconst                       tt11822374
titleType                         short
primaryTitle                   Slasher?
originalTitle                  Slasher?
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres            Comedy,Short,Thriller
Name: 2003557, dtype: object

(9,)

tconst              tt11822376
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003558, dtype: object

(9,)

tconst                tt11822378
titleType               tvSeries
primaryTitle      Ambos for Hire
originalTitle     Ambos for Hire
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2003559, dtype: object

(9,)

tconst                              tt1182237
titleType                           tvEpisode
primaryTitle      20 Years of Radio 1 Special
originalTitle     20 Years of Radio 1 Special
isAdult                                     0
startYear                                1987
endYear                                    \N
runtimeMinutes                             35
genres                              Talk-Show
Name: 2003560, dtype: object

(9,)

tconst                              tt11822380
titleType                            tvEpisode
primaryTitle      2009 Mnet Asian Music Awards
originalTitle     2009 Mnet Asian Music Awards
isAdult                                      0
startYear                                 2009
endYear                                     \N
runtimeMinutes                              \N
genres                                   Music
Name: 2003561, dtype: object

(9,)

tconst                             tt11822382
titleType                           tvEpisode
primaryTitle      2008 Mnet Km Music Festival
originalTitle     2008 Mnet Km Music Festival
isAdult                                     0
startYear                                2008
endYear                                    \N
runtimeMinutes                             \N
genres                                  Music
Name: 2003562, dtype: object

(9,)

tconst             tt11822384
titleType               movie
primaryTitle         Kafa Coh
originalTitle        Kafa Coh
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Crime,Drama
Name: 2003563, dtype: object

(9,)

tconst                             tt11822386
titleType                           tvEpisode
primaryTitle      2007 Mnet Km Music Festival
originalTitle     2007 Mnet Km Music Festival
isAdult                                     0
startYear                                2007
endYear                                    \N
runtimeMinutes                             \N
genres                                  Music
Name: 2003564, dtype: object

(9,)

tconst                             tt11822388
titleType                           tvEpisode
primaryTitle      2006 Mnet Km Music Festival
originalTitle     2006 Mnet Km Music Festival
isAdult                                     0
startYear                                2006
endYear                                    \N
runtimeMinutes                             \N
genres                                  Music
Name: 2003565, dtype: object

(9,)

tconst                    tt1182238
titleType                 tvEpisode
primaryTitle      Wogan's Radio Fun
originalTitle     Wogan's Radio Fun
isAdult                           0
startYear                      1987
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2003566, dtype: object

(9,)

tconst                          tt11822390
titleType                        tvEpisode
primaryTitle      Spotlight on Vicky Dalli
originalTitle     Spotlight on Vicky Dalli
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                               Music
Name: 2003567, dtype: object

(9,)

tconst                  tt11822392
titleType                    movie
primaryTitle      7 Deadly Masters
originalTitle     7 Deadly Masters
isAdult                          0
startYear                       \N
endYear                         \N
runtimeMinutes                  \N
genres                      Action
Name: 2003568, dtype: object

(9,)

tconst                                   tt11822394
titleType                                 tvEpisode
primaryTitle      2005 Mnet Km Music Video Festival
originalTitle     2005 Mnet Km Music Video Festival
isAdult                                           0
startYear                                      2005
endYear                                          \N
runtimeMinutes                                   \N
genres                                           \N
Name: 2003569, dtype: object

(9,)

tconst                                          tt11822396
titleType                                        tvEpisode
primaryTitle      The Caddy and the Daddy Part 2: Bareback
originalTitle     The Caddy and the Daddy Part 2: Bareback
isAdult                                                  1
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                               Adult
Name: 2003570, dtype: object

(9,)

tconst                   tt11822398
titleType                  tvSeries
primaryTitle      Ushi & The Family
originalTitle     Ushi & The Family
isAdult                           0
startYear                      2011
endYear                        2012
runtimeMinutes                   35
genres                       Comedy
Name: 2003571, dtype: object

(9,)

tconst                                   tt11822400
titleType                                 tvEpisode
primaryTitle      2004 Mnet Km Music Video Festival
originalTitle     2004 Mnet Km Music Video Festival
isAdult                                           0
startYear                                      2004
endYear                                          \N
runtimeMinutes                                   \N
genres                                           \N
Name: 2003572, dtype: object

(9,)

tconst                                tt11822402
titleType                              tvEpisode
primaryTitle      2003 Mnet Music Video Festival
originalTitle     2003 Mnet Music Video Festival
isAdult                                        0
startYear                                   2003
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003573, dtype: object

(9,)

tconst                                tt11822404
titleType                              tvEpisode
primaryTitle      2002 Mnet Music Video Festival
originalTitle     2002 Mnet Music Video Festival
isAdult                                        0
startYear                                   2002
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003574, dtype: object

(9,)

tconst                                tt11822406
titleType                              tvEpisode
primaryTitle      2001 Mnet Music Video Festival
originalTitle     2001 Mnet Music Video Festival
isAdult                                        0
startYear                                   2001
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003575, dtype: object

(9,)

tconst                                tt11822408
titleType                              tvEpisode
primaryTitle      2000 Mnet Music Video Festival
originalTitle     2000 Mnet Music Video Festival
isAdult                                        0
startYear                                   2000
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003576, dtype: object

(9,)

tconst                tt1182240
titleType             tvEpisode
primaryTitle      Episode #9.22
originalTitle     Episode #9.22
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2003577, dtype: object

(9,)

tconst                tt11822410
titleType                  short
primaryTitle      Lunas de Marte
originalTitle     Lunas de Marte
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres               Drama,Short
Name: 2003578, dtype: object

(9,)

tconst                              tt11822412
titleType                            tvEpisode
primaryTitle      1999 Mnet Video Music Awards
originalTitle     1999 Mnet Video Music Awards
isAdult                                      0
startYear                                 1999
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2003579, dtype: object

(9,)

tconst                     tt11822414
titleType                   tvEpisode
primaryTitle      Made for Loving You
originalTitle     Made for Loving You
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     35
genres                     Reality-TV
Name: 2003580, dtype: object

(9,)

tconst                         tt11822416
titleType                        tvSeries
primaryTitle      Wie het laatst lacht...
originalTitle     Wie het laatst lacht...
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                             Comedy
Name: 2003581, dtype: object

(9,)

tconst                tt11822418
titleType              tvEpisode
primaryTitle      Wedding GOALS!
originalTitle     Wedding GOALS!
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2003582, dtype: object

(9,)

tconst                   tt1182241
titleType             tvMiniSeries
primaryTitle      The Writing Code
originalTitle     The Writing Code
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                 180
genres                 Documentary
Name: 2003583, dtype: object

(9,)

tconst                           tt11822420
titleType                         tvEpisode
primaryTitle      He Has a Secret: Bareback
originalTitle     He Has a Secret: Bareback
isAdult                                   1
startYear                              2019
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2003584, dtype: object

(9,)

tconst                         tt11822422
titleType                       tvEpisode
primaryTitle      Te Amo, Mi Amor, Again!
originalTitle     Te Amo, Mi Amor, Again!
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                         Reality-TV
Name: 2003585, dtype: object

(9,)

tconst                                 tt11822424
titleType                               tvEpisode
primaryTitle      Spotlight on Carlisle Forrester
originalTitle     Spotlight on Carlisle Forrester
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Music
Name: 2003586, dtype: object

(9,)

tconst            tt11822426
titleType          tvEpisode
primaryTitle       Marry ME!
originalTitle      Marry ME!
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2003587, dtype: object

(9,)

tconst                  tt1182242
titleType               tvEpisode
primaryTitle      Episode #1.8824
originalTitle     Episode #1.8824
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2003588, dtype: object

(9,)

tconst                                           tt11822430
titleType                                          tvSeries
primaryTitle      The Modern Mensch with Martin Mendelstein
originalTitle     The Modern Mensch with Martin Mendelstein
isAdult                                                   0
startYear                                              2015
endYear                                                  \N
runtimeMinutes                                           \N
genres                                               Comedy
Name: 2003589, dtype: object

(9,)

tconst              tt11822432
titleType            tvEpisode
primaryTitle      Chci být sám
originalTitle     Chci být sám
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003590, dtype: object

(9,)

tconst                            tt11822434
titleType                          tvEpisode
primaryTitle      The Manny Part 1: Bareback
originalTitle     The Manny Part 1: Bareback
isAdult                                    1
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2003591, dtype: object

(9,)

tconst                 tt11822436
titleType               tvSpecial
primaryTitle      Oi sinä nainen!
originalTitle     Oi sinä nainen!
isAdult                         0
startYear                    1976
endYear                        \N
runtimeMinutes                 \N
genres                      Music
Name: 2003592, dtype: object

(9,)

tconst            tt11822438
titleType              movie
primaryTitle          Dhauli
originalTitle         Dhauli
isAdult                    0
startYear               2015
endYear                   \N
runtimeMinutes           120
genres                Family
Name: 2003593, dtype: object

(9,)

tconst                         tt1182243
titleType                      tvEpisode
primaryTitle      Cemu sluze prijatelji?
originalTitle     Cemu sluze prijatelji?
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres                            Comedy
Name: 2003594, dtype: object

(9,)

tconst                                 tt11822440
titleType                               tvEpisode
primaryTitle      Na plovárne s Martinem Vackárem
originalTitle     Na plovárne s Martinem Vackárem
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Talk-Show
Name: 2003595, dtype: object

(9,)

tconst                 tt11822442
titleType                   movie
primaryTitle      Myramid Origins
originalTitle     Myramid Origins
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres             Drama,Thriller
Name: 2003596, dtype: object

(9,)

tconst                        tt11822444
titleType                      tvEpisode
primaryTitle      Bringing Home the Meat
originalTitle     Bringing Home the Meat
isAdult                                1
startYear                           2019
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2003597, dtype: object

(9,)

tconst             tt11822446
titleType               short
primaryTitle          Tic Tac
originalTitle         Tic Tac
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2003598, dtype: object

(9,)

tconst                 tt11822448
titleType               tvEpisode
primaryTitle          Buy New Car
originalTitle         Buy New Car
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2003599, dtype: object

(9,)

tconst                 tt1182244
titleType              tvEpisode
primaryTitle      Romeo i Julija
originalTitle     Romeo i Julija
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2003600, dtype: object

(9,)

tconst                                    tt11822450
titleType                                  tvEpisode
primaryTitle      Banging the Butt Burglar: Bareback
originalTitle     Banging the Butt Burglar: Bareback
isAdult                                            1
startYear                                       2019
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2003601, dtype: object

(9,)

tconst                tt11822452
titleType              tvEpisode
primaryTitle       Episode #1.19
originalTitle      Episode #1.19
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2003602, dtype: object

(9,)

tconst                       tt11822454
titleType                      tvSeries
primaryTitle      Typisch Carlo & Irene
originalTitle     Typisch Carlo & Irene
isAdult                               0
startYear                          2014
endYear                            2014
runtimeMinutes                       30
genres                        Game-Show
Name: 2003603, dtype: object

(9,)

tconst                     tt11822456
titleType                   tvEpisode
primaryTitle      Makes Big Hamburger
originalTitle     Makes Big Hamburger
isAdult                             0
startYear                        2018
endYear                            \N
runtimeMinutes                     \N
genres                Animation,Short
Name: 2003604, dtype: object

(9,)

tconst                   tt11822458
titleType                 tvEpisode
primaryTitle      Learning Vehicles
originalTitle     Learning Vehicles
isAdult                           0
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres              Animation,Short
Name: 2003605, dtype: object

(9,)

tconst                   tt1182245
titleType                tvEpisode
primaryTitle      Siromastvo je IN
originalTitle     Siromastvo je IN
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2003606, dtype: object

(9,)

tconst                                 tt11822460
titleType                               tvEpisode
primaryTitle      Do Babysitting with Yellow Baby
originalTitle     Do Babysitting with Yellow Baby
isAdult                                         0
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                            Animation,Short
Name: 2003607, dtype: object

(9,)

tconst                            tt11822462
titleType                          tvEpisode
primaryTitle      Make Traditional Chocolate
originalTitle     Make Traditional Chocolate
isAdult                                    0
startYear                               2018
endYear                                   \N
runtimeMinutes                            \N
genres                       Animation,Short
Name: 2003608, dtype: object

(9,)

tconst                 tt11822466
titleType               tvEpisode
primaryTitle       A Running Race
originalTitle      A Running Race
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2003609, dtype: object

(9,)

tconst                         tt11822468
titleType                       tvEpisode
primaryTitle      He's Always Hard for Me
originalTitle     He's Always Hard for Me
isAdult                                 1
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2003610, dtype: object

(9,)

tconst               tt1182246
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003611, dtype: object

(9,)

tconst                tt11822470
titleType              tvEpisode
primaryTitle      Episode #14.36
originalTitle     Episode #14.36
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2003612, dtype: object

(9,)

tconst              tt11822472
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              60
genres               Talk-Show
Name: 2003613, dtype: object

(9,)

tconst                    tt11822474
titleType                      video
primaryTitle      M83: Steve McQueen
originalTitle     M83: Steve McQueen
isAdult                            0
startYear                       2012
endYear                           \N
runtimeMinutes                     4
genres                   Music,Short
Name: 2003614, dtype: object

(9,)

tconst                 tt11822476
titleType                tvSeries
primaryTitle       Teaterkrönikan
originalTitle      Teaterkrönikan
isAdult                         0
startYear                    1983
endYear                      1987
runtimeMinutes                 45
genres            Drama,Talk-Show
Name: 2003615, dtype: object

(9,)

tconst                          tt11822478
titleType                        tvEpisode
primaryTitle      How to Make a Green Baby
originalTitle     How to Make a Green Baby
isAdult                                  0
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                     Animation,Short
Name: 2003616, dtype: object

(9,)

tconst                                          tt1182247
titleType                                           video
primaryTitle      28 Weeks Later: Getting Into the Action
originalTitle     28 Weeks Later: Getting Into the Action
isAdult                                                 0
startYear                                            2007
endYear                                                \N
runtimeMinutes                                          7
genres                                  Documentary,Short
Name: 2003617, dtype: object

(9,)

tconst                     tt11822480
titleType                   tvEpisode
primaryTitle      Yellow Baby Make Up
originalTitle     Yellow Baby Make Up
isAdult                             0
startYear                        2018
endYear                            \N
runtimeMinutes                     \N
genres                Animation,Short
Name: 2003618, dtype: object

(9,)

tconst                                tt11822482
titleType                              tvEpisode
primaryTitle      Unexpected Roommates: Bareback
originalTitle     Unexpected Roommates: Bareback
isAdult                                        1
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2003619, dtype: object

(9,)

tconst                     tt11822484
titleType                   tvEpisode
primaryTitle      Learning House Room
originalTitle     Learning House Room
isAdult                             0
startYear                        2018
endYear                            \N
runtimeMinutes                     \N
genres                Animation,Short
Name: 2003620, dtype: object

(9,)

tconst                                tt11822488
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003621, dtype: object

(9,)

tconst                               tt1182248
titleType                                video
primaryTitle      28 Weeks Later: The Infected
originalTitle     28 Weeks Later: The Infected
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                               7
genres                       Documentary,Short
Name: 2003622, dtype: object

(9,)

tconst                tt11822490
titleType              tvEpisode
primaryTitle      Domestic Bliss
originalTitle     Domestic Bliss
isAdult                        1
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2003623, dtype: object

(9,)

tconst             tt11822492
titleType               movie
primaryTitle      Small Chops
originalTitle     Small Chops
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             98
genres                  Drama
Name: 2003624, dtype: object

(9,)

tconst                                tt11822494
titleType                              tvEpisode
primaryTitle      Episode dated 12 November 2017
originalTitle     Episode dated 12 November 2017
isAdult                                        0
startYear                                   2017
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003625, dtype: object

(9,)

tconst            tt11822496
titleType              movie
primaryTitle       Dead Hide
originalTitle      Dead Hide
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres               Western
Name: 2003626, dtype: object

(9,)

tconst                        tt11822498
titleType                       tvSeries
primaryTitle      Mar a última fronteira
originalTitle     Mar a última fronteira
isAdult                                0
startYear                           2019
endYear                             2020
runtimeMinutes                        \N
genres                       Documentary
Name: 2003627, dtype: object

(9,)

tconst                                       tt1182249
titleType                                      tvMovie
primaryTitle      Akwaaba Ghana - Willkommen in Afrika
originalTitle     Akwaaba Ghana - Willkommen in Afrika
isAdult                                              0
startYear                                         2008
endYear                                             \N
runtimeMinutes                                      59
genres                                     Documentary
Name: 2003628, dtype: object

(9,)

tconst                               tt11822500
titleType                             tvEpisode
primaryTitle      Episode dated 12 October 2017
originalTitle     Episode dated 12 October 2017
isAdult                                       0
startYear                                  2017
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2003629, dtype: object

(9,)

tconst             tt11822502
titleType               short
primaryTitle        Fast Love
originalTitle       Fast Love
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes             29
genres            Drama,Short
Name: 2003630, dtype: object

(9,)

tconst              tt11822504
titleType                movie
primaryTitle      Costa Blanca
originalTitle     Costa Blanca
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003631, dtype: object

(9,)

tconst                           tt11822506
titleType                         tvEpisode
primaryTitle      Episode dated 15 May 2016
originalTitle     Episode dated 15 May 2016
isAdult                                   0
startYear                              2016
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2003632, dtype: object

(9,)

tconst            tt11822508
titleType           tvSeries
primaryTitle        Muqaddar
originalTitle       Muqaddar
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003633, dtype: object

(9,)

tconst             tt1182250
titleType            tvMovie
primaryTitle      Alpha 2001
originalTitle     Alpha 2001
isAdult                    0
startYear               1970
endYear                   \N
runtimeMinutes            80
genres                Sci-Fi
Name: 2003634, dtype: object

(9,)

tconst                      tt11822510
titleType                        movie
primaryTitle      One Night in England
originalTitle     One Night in England
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres                        Thriller
Name: 2003635, dtype: object

(9,)

tconst                 tt11822512
titleType            tvMiniSeries
primaryTitle      Kajsa och Johan
originalTitle     Kajsa och Johan
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                  1
genres                     Comedy
Name: 2003636, dtype: object

(9,)

tconst                           tt11822514
titleType                             movie
primaryTitle      Ascension (Serendipitous)
originalTitle     Ascension (Serendipitous)
isAdult                                   0
startYear                                \N
endYear                                  \N
runtimeMinutes                           \N
genres                               Sci-Fi
Name: 2003637, dtype: object

(9,)

tconst                  tt11822516
titleType                    short
primaryTitle      Der Doppelnelson
originalTitle     Der Doppelnelson
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  20
genres                       Short
Name: 2003638, dtype: object

(9,)

tconst            tt11822518
titleType          tvEpisode
primaryTitle            Arif
originalTitle           Arif
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2003639, dtype: object

(9,)

tconst              tt1182251
titleType               short
primaryTitle      Antitheseis
originalTitle     Antitheseis
isAdult                     0
startYear                1978
endYear                    \N
runtimeMinutes             40
genres                  Short
Name: 2003640, dtype: object

(9,)

tconst                tt11822520
titleType              tvEpisode
primaryTitle      Konsert - Arif
originalTitle     Konsert - Arif
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2003641, dtype: object

(9,)

tconst              tt11822522
titleType            tvEpisode
primaryTitle      Freddy Kalas
originalTitle     Freddy Kalas
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2003642, dtype: object

(9,)

tconst                        tt11822524
titleType                      tvEpisode
primaryTitle      Konsert - Freddy Kalas
originalTitle     Konsert - Freddy Kalas
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2003643, dtype: object

(9,)

tconst            tt11822526
titleType          tvEpisode
primaryTitle           Dagny
originalTitle          Dagny
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2003644, dtype: object

(9,)

tconst                 tt11822528
titleType               tvEpisode
primaryTitle      Konsert - Dagny
originalTitle     Konsert - Dagny
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2003645, dtype: object

(9,)

tconst                      tt1182252
titleType                     tvMovie
primaryTitle      Bajo el mismo cielo
originalTitle     Bajo el mismo cielo
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     87
genres                          Drama
Name: 2003646, dtype: object

(9,)

tconst                  tt11822530
titleType                tvEpisode
primaryTitle      Konsert - Aurora
originalTitle     Konsert - Aurora
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2003647, dtype: object

(9,)

tconst                  tt11822532
titleType                    short
primaryTitle      Des Solitudes...
originalTitle     Des Solitudes...
isAdult                          0
startYear                     2018
endYear                         \N
runtimeMinutes                  18
genres                       Short
Name: 2003648, dtype: object

(9,)

tconst            tt11822534
titleType          tvEpisode
primaryTitle          Aurora
originalTitle         Aurora
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2003649, dtype: object

(9,)

tconst                       tt11822536
titleType                     tvEpisode
primaryTitle      Konsert - Highasakite
originalTitle     Konsert - Highasakite
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2003650, dtype: object

(9,)

tconst             tt11822538
titleType           tvEpisode
primaryTitle      Highasakite
originalTitle     Highasakite
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2003651, dtype: object

(9,)

tconst                             tt1182253
titleType                              video
primaryTitle      Birth of the Graphic Novel
originalTitle     Birth of the Graphic Novel
isAdult                                    0
startYear                               2007
endYear                                   \N
runtimeMinutes                            13
genres                     Documentary,Short
Name: 2003652, dtype: object

(9,)

tconst              tt11822540
titleType             tvSeries
primaryTitle      Khoob Seerat
originalTitle     Khoob Seerat
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003653, dtype: object

(9,)

tconst            tt11822542
titleType          tvEpisode
primaryTitle        Astrid S
originalTitle       Astrid S
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2003654, dtype: object

(9,)

tconst                    tt11822544
titleType                  tvEpisode
primaryTitle      Konsert - Astrid S
originalTitle     Konsert - Astrid S
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2003655, dtype: object

(9,)

tconst                tt11822546
titleType           tvMiniSeries
primaryTitle      Escape Attempt
originalTitle     Escape Attempt
isAdult                        0
startYear                   2021
endYear                       \N
runtimeMinutes                \N
genres                    Sci-Fi
Name: 2003656, dtype: object

(9,)

tconst                       tt11822548
titleType                         short
primaryTitle      Killing Small Animals
originalTitle     Killing Small Animals
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       11
genres             Drama,Horror,Mystery
Name: 2003657, dtype: object

(9,)

tconst            tt1182254
titleType             video
primaryTitle         Blades
originalTitle        Blades
isAdult                   1
startYear              2002
endYear                  \N
runtimeMinutes           90
genres                Adult
Name: 2003658, dtype: object

(9,)

tconst                    tt11822550
titleType                  tvEpisode
primaryTitle      The Porcelain Doll
originalTitle     The Porcelain Doll
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres              Fantasy,Thriller
Name: 2003659, dtype: object

(9,)

tconst                               tt11822552
titleType                             tvEpisode
primaryTitle      The World is Different for Us
originalTitle     The World is Different for Us
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                         Fantasy,Thriller
Name: 2003660, dtype: object

(9,)

tconst                            tt11822554
titleType                          tvEpisode
primaryTitle      My Temple Will Be My Grave
originalTitle     My Temple Will Be My Grave
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                      Fantasy,Thriller
Name: 2003661, dtype: object

(9,)

tconst                             tt11822556
titleType                           tvEpisode
primaryTitle      Episode dated 17 March 2013
originalTitle     Episode dated 17 March 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2003662, dtype: object

(9,)

tconst                  tt11822558
titleType                tvEpisode
primaryTitle         Come to Mamma
originalTitle        Come to Mamma
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Fantasy,Thriller
Name: 2003663, dtype: object

(9,)

tconst                                    tt1182255
titleType                                     short
primaryTitle      Bourani, to panygiri tou Tyrnavou
originalTitle     Bourani, to panygiri tou Tyrnavou
isAdult                                           0
startYear                                      1978
endYear                                          \N
runtimeMinutes                                   40
genres                            Documentary,Short
Name: 2003664, dtype: object

(9,)

tconst                 tt11822560
titleType               videoGame
primaryTitle      Hellfire Attack
originalTitle     Hellfire Attack
isAdult                         0
startYear                    1988
endYear                        \N
runtimeMinutes                 \N
genres                     Action
Name: 2003665, dtype: object

(9,)

tconst                tt11822562
titleType                  movie
primaryTitle      Kotô no kaijin
originalTitle     Kotô no kaijin
isAdult                        0
startYear                   1927
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2003666, dtype: object

(9,)

tconst                   tt11822564
titleType                 tvEpisode
primaryTitle      A Hard Day's Pick
originalTitle     A Hard Day's Pick
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                   Reality-TV
Name: 2003667, dtype: object

(9,)

tconst                     tt11822566
titleType                   tvEpisode
primaryTitle      The Dead Have Risen
originalTitle     The Dead Have Risen
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres               Fantasy,Thriller
Name: 2003668, dtype: object

(9,)

tconst                                                   tt11822568
titleType                                                     video
primaryTitle      Freddie Jackson: Rock Me Tonight (For Old Time...
originalTitle     Freddie Jackson: Rock Me Tonight (For Old Time...
isAdult                                                           0
startYear                                                      1985
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2003669, dtype: object

(9,)

tconst                    tt1182256
titleType                     short
primaryTitle        The Bronze Idol
originalTitle       The Bronze Idol
isAdult                           0
startYear                      1914
endYear                          \N
runtimeMinutes                   \N
genres            Crime,Drama,Short
Name: 2003670, dtype: object

(9,)

tconst                  tt11822570
titleType                tvEpisode
primaryTitle          Heal Thyself
originalTitle         Heal Thyself
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Fantasy,Thriller
Name: 2003671, dtype: object

(9,)

tconst                  tt11822572
titleType                tvEpisode
primaryTitle           Block Party
originalTitle          Block Party
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Fantasy,Thriller
Name: 2003672, dtype: object

(9,)

tconst                        tt11822574
titleType                          short
primaryTitle      First Turn on the Left
originalTitle          Loulla Âal-Lissar
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                         9
genres                Comedy,Drama,Short
Name: 2003673, dtype: object

(9,)

tconst                  tt11822576
titleType                tvEpisode
primaryTitle        Episode #1.816
originalTitle       Episode #1.816
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003674, dtype: object

(9,)

tconst                  tt11822578
titleType                tvEpisode
primaryTitle        Episode #1.817
originalTitle       Episode #1.817
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003675, dtype: object

(9,)

tconst                      tt1182257
titleType                       movie
primaryTitle            God's Offices
originalTitle     Les bureaux de Dieu
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                    122
genres                   Comedy,Drama
Name: 2003676, dtype: object

(9,)

tconst             tt11822580
titleType           tvEpisode
primaryTitle          Jakarta
originalTitle         Jakarta
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003677, dtype: object

(9,)

tconst                                tt11822582
titleType                           tvMiniSeries
primaryTitle      Kashmakash: Kya Sahi Kya Galat
originalTitle     Kashmakash: Kya Sahi Kya Galat
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                               Crime,Drama
Name: 2003678, dtype: object

(9,)

tconst                                  tt11822584
titleType                                    video
primaryTitle      Freddie Jackson: You Are My Lady
originalTitle     Freddie Jackson: You Are My Lady
isAdult                                          0
startYear                                     1985
endYear                                         \N
runtimeMinutes                                   5
genres                                 Music,Short
Name: 2003679, dtype: object

(9,)

tconst             tt11822586
titleType           tvEpisode
primaryTitle        Singapore
originalTitle       Singapore
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003680, dtype: object

(9,)

tconst                  tt11822588
titleType                tvEpisode
primaryTitle        Episode #1.818
originalTitle       Episode #1.818
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003681, dtype: object

(9,)

tconst                               tt1182258
titleType                                video
primaryTitle      Böhse Onkelz - Vaya con tioz
originalTitle     Böhse Onkelz - Vaya con tioz
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                             344
genres                       Documentary,Music
Name: 2003682, dtype: object

(9,)

tconst                            tt11822590
titleType                           tvSeries
primaryTitle                     Zlatá maska
originalTitle                    Zlatá maska
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2003683, dtype: object

(9,)

tconst                                                   tt11822592
titleType                                                     video
primaryTitle      Freddie Jackson: He'll Never Love You (Like I Do)
originalTitle     Freddie Jackson: He'll Never Love You (Like I Do)
isAdult                                                           0
startYear                                                      1985
endYear                                                          \N
runtimeMinutes                                                    5
genres                                                  Music,Short
Name: 2003684, dtype: object

(9,)

tconst                                              tt11822594
titleType                                                short
primaryTitle      Tortun: A Poetry of A Girl Who Fell to Earth
originalTitle     Tortun: A Poetry of A Girl Who Fell to Earth
isAdult                                                      0
startYear                                                 2019
endYear                                                     \N
runtimeMinutes                                              \N
genres                                             Drama,Short
Name: 2003685, dtype: object

(9,)

tconst            tt11822596
titleType          tvEpisode
primaryTitle       Episode 1
originalTitle      Episode 1
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003686, dtype: object

(9,)

tconst                                                  tt11822598
titleType                                                    video
primaryTitle      Freddie Jackson & Melba Moore: A Little Bit More
originalTitle     Freddie Jackson & Melba Moore: A Little Bit More
isAdult                                                          0
startYear                                                     1986
endYear                                                         \N
runtimeMinutes                                                   4
genres                                                 Music,Short
Name: 2003687, dtype: object

(9,)

tconst                                                    tt1182259
titleType                                                   tvMovie
primaryTitle      Can You Hear Me Now: The Evolution of Gospel M...
originalTitle     Can You Hear Me Now: The Evolution of Gospel M...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                  Documentary
Name: 2003688, dtype: object

(9,)

tconst                  tt11822600
titleType                tvEpisode
primaryTitle        Episode #1.819
originalTitle       Episode #1.819
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003689, dtype: object

(9,)

tconst                  tt11822602
titleType                tvEpisode
primaryTitle        Episode #1.820
originalTitle       Episode #1.820
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003690, dtype: object

(9,)

tconst            tt11822604
titleType          tvEpisode
primaryTitle       Episode 1
originalTitle      Episode 1
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003691, dtype: object

(9,)

tconst                  tt11822606
titleType                tvEpisode
primaryTitle        Episode #1.821
originalTitle       Episode #1.821
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003692, dtype: object

(9,)

tconst                  tt11822608
titleType                tvEpisode
primaryTitle        Episode #1.822
originalTitle       Episode #1.822
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003693, dtype: object

(9,)

tconst                       tt1182260
titleType                    tvSpecial
primaryTitle      The Chevy Chase Show
originalTitle     The Chevy Chase Show
isAdult                              0
startYear                         1977
endYear                             \N
runtimeMinutes                      60
genres                          Comedy
Name: 2003694, dtype: object

(9,)

tconst              tt11822610
titleType         tvMiniSeries
primaryTitle        WTF Chef?!
originalTitle       WTF Chef?!
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2003695, dtype: object

(9,)

tconst                             tt11822612
titleType                               video
primaryTitle      Freddie Jackson: Tasty Love
originalTitle     Freddie Jackson: Tasty Love
isAdult                                     0
startYear                                1986
endYear                                    \N
runtimeMinutes                              4
genres                            Music,Short
Name: 2003696, dtype: object

(9,)

tconst                  tt11822614
titleType                tvEpisode
primaryTitle        Episode #1.823
originalTitle       Episode #1.823
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003697, dtype: object

(9,)

tconst                  tt11822616
titleType                tvEpisode
primaryTitle        Episode #1.824
originalTitle       Episode #1.824
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003698, dtype: object

(9,)

tconst                  tt11822618
titleType                tvEpisode
primaryTitle        Episode #1.825
originalTitle       Episode #1.825
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003699, dtype: object

(9,)

tconst                                           tt1182261
titleType                                            video
primaryTitle      Code Red: The Making of '28 Weeks Later'
originalTitle     Code Red: The Making of '28 Weeks Later'
isAdult                                                  0
startYear                                             2007
endYear                                                 \N
runtimeMinutes                                          14
genres                                   Documentary,Short
Name: 2003700, dtype: object

(9,)

tconst                   tt11822620
titleType                     short
primaryTitle            Deliverance
originalTitle               Enfiraj
isAdult                           0
startYear                      2014
endYear                          \N
runtimeMinutes                   23
genres            Documentary,Short
Name: 2003701, dtype: object

(9,)

tconst                  tt11822622
titleType                tvEpisode
primaryTitle        Episode #1.826
originalTitle       Episode #1.826
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003702, dtype: object

(9,)

tconst                                tt11822624
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2003703, dtype: object

(9,)

tconst                                               tt11822626
titleType                                                 video
primaryTitle      Freddie Jackson: Have You Ever Loved Somebody
originalTitle     Freddie Jackson: Have You Ever Loved Somebody
isAdult                                                       0
startYear                                                  1986
endYear                                                      \N
runtimeMinutes                                                4
genres                                              Music,Short
Name: 2003704, dtype: object

(9,)

tconst                  tt11822628
titleType                tvEpisode
primaryTitle        Episode #1.827
originalTitle       Episode #1.827
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003705, dtype: object

(9,)

tconst                          tt1182262
titleType                           video
primaryTitle      Colour Silurian Overlay
originalTitle     Colour Silurian Overlay
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                          5
genres                  Documentary,Short
Name: 2003706, dtype: object

(9,)

tconst                  tt11822630
titleType                tvEpisode
primaryTitle        Episode #1.828
originalTitle       Episode #1.828
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003707, dtype: object

(9,)

tconst                                                   tt11822632
titleType                                                 tvEpisode
primaryTitle      Politik-Krise in Thüringen/Wachsender Antisemi...
originalTitle     Politik-Krise in Thüringen/Wachsender Antisemi...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                  Documentary,News,Reality-TV
Name: 2003708, dtype: object

(9,)

tconst                  tt11822634
titleType                tvEpisode
primaryTitle        Episode #1.829
originalTitle       Episode #1.829
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003709, dtype: object

(9,)

tconst                  tt11822636
titleType                tvEpisode
primaryTitle        Episode #1.830
originalTitle       Episode #1.830
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003710, dtype: object

(9,)

tconst                  tt11822638
titleType                tvEpisode
primaryTitle        Episode #1.831
originalTitle       Episode #1.831
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003711, dtype: object

(9,)

tconst                           tt1182263
titleType                            short
primaryTitle      The Cost of Carelessness
originalTitle     The Cost of Carelessness
isAdult                                  0
startYear                             1913
endYear                                 \N
runtimeMinutes                          14
genres                   Documentary,Short
Name: 2003712, dtype: object

(9,)

tconst                        tt11822640
titleType                      tvEpisode
primaryTitle      Projecting Cock Part 3
originalTitle     Projecting Cock Part 3
isAdult                                1
startYear                           2019
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2003713, dtype: object

(9,)

tconst                  tt11822642
titleType                tvEpisode
primaryTitle        Episode #1.832
originalTitle       Episode #1.832
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003714, dtype: object

(9,)

tconst                                 tt11822644
titleType                                   video
primaryTitle      Neil Cicierega: Wndrwll (Audio)
originalTitle     Neil Cicierega: Wndrwll (Audio)
isAdult                                         0
startYear                                    2014
endYear                                        \N
runtimeMinutes                                  3
genres                         Comedy,Music,Short
Name: 2003715, dtype: object

(9,)

tconst                  tt11822646
titleType                tvEpisode
primaryTitle        Episode #1.833
originalTitle       Episode #1.833
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003716, dtype: object

(9,)

tconst                  tt11822648
titleType                tvEpisode
primaryTitle        Episode #1.834
originalTitle       Episode #1.834
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003717, dtype: object

(9,)

tconst                                         tt1182264
titleType                                          video
primaryTitle      Crocumentary: Bringing Gustave to Life
originalTitle     Crocumentary: Bringing Gustave to Life
isAdult                                                0
startYear                                           2007
endYear                                               \N
runtimeMinutes                                        \N
genres                                 Documentary,Short
Name: 2003718, dtype: object

(9,)

tconst                  tt11822650
titleType                tvEpisode
primaryTitle        Episode #1.835
originalTitle       Episode #1.835
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003719, dtype: object

(9,)

tconst                                                 tt11822652
titleType                                                   video
primaryTitle      Freddie Jackson: I Don't Want to Lose Your Love
originalTitle     Freddie Jackson: I Don't Want to Lose Your Love
isAdult                                                         0
startYear                                                    1987
endYear                                                        \N
runtimeMinutes                                                  4
genres                                                Music,Short
Name: 2003720, dtype: object

(9,)

tconst                  tt11822654
titleType                tvEpisode
primaryTitle        Episode #1.836
originalTitle       Episode #1.836
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003721, dtype: object

(9,)

tconst                  tt11822656
titleType                tvEpisode
primaryTitle        Episode #1.837
originalTitle       Episode #1.837
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003722, dtype: object

(9,)

tconst                  tt11822658
titleType                tvEpisode
primaryTitle        Episode #1.838
originalTitle       Episode #1.838
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003723, dtype: object

(9,)

tconst              tt1182265
titleType               video
primaryTitle      Deep Plunge
originalTitle     Deep Plunge
isAdult                     1
startYear                2003
endYear                    \N
runtimeMinutes            115
genres                  Adult
Name: 2003724, dtype: object

(9,)

tconst                                tt11822660
titleType                                  video
primaryTitle      Freddie Jackson: Nice 'N' Slow
originalTitle     Freddie Jackson: Nice 'N' Slow
isAdult                                        0
startYear                                   1988
endYear                                       \N
runtimeMinutes                                 4
genres                               Music,Short
Name: 2003725, dtype: object

(9,)

tconst                tt11822662
titleType                  short
primaryTitle      Eternal Escape
originalTitle     Eternal Escape
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres              Sci-Fi,Short
Name: 2003726, dtype: object

(9,)

tconst             tt11822664
titleType           tvEpisode
primaryTitle           Bergen
originalTitle          Bergen
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             18
genres            Documentary
Name: 2003727, dtype: object

(9,)

tconst                            tt11822666
titleType                              short
primaryTitle      Le Vent Souffle Où Il Veut
originalTitle     Le Vent Souffle Où Il Veut
isAdult                                    0
startYear                               2014
endYear                                   \N
runtimeMinutes                            \N
genres                                 Short
Name: 2003728, dtype: object

(9,)

tconst             tt11822668
titleType           tvEpisode
primaryTitle           Berlin
originalTitle          Berlin
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003729, dtype: object

(9,)

tconst                    tt1182266
titleType                     short
primaryTitle                 Degrop
originalTitle                Degrop
isAdult                           0
startYear                      1978
endYear                          \N
runtimeMinutes                   10
genres            Documentary,Short
Name: 2003730, dtype: object

(9,)

tconst                                   tt11822670
titleType                                 tvEpisode
primaryTitle      Big and Little - Trees and Bodies
originalTitle     Big and Little - Trees and Bodies
isAdult                                           0
startYear                                      2009
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Family
Name: 2003731, dtype: object

(9,)

tconst             tt11822672
titleType           tvEpisode
primaryTitle        Cape Town
originalTitle       Cape Town
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003732, dtype: object

(9,)

tconst                tt11822674
titleType              tvEpisode
primaryTitle      Rio De Janeiro
originalTitle     Rio De Janeiro
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2003733, dtype: object

(9,)

tconst             tt11822676
titleType           tvEpisode
primaryTitle            Porto
originalTitle           Porto
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003734, dtype: object

(9,)

tconst                  tt11822678
titleType                tvEpisode
primaryTitle      Rivals: Bareback
originalTitle     Rivals: Bareback
isAdult                          1
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                       Adult
Name: 2003735, dtype: object

(9,)

tconst                    tt1182267
titleType                     video
primaryTitle             The Depths
originalTitle            The Depths
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   32
genres            Documentary,Short
Name: 2003736, dtype: object

(9,)

tconst             tt11822680
titleType           tvEpisode
primaryTitle        Amsterdam
originalTitle       Amsterdam
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003737, dtype: object

(9,)

tconst                                        tt11822682
titleType                                          video
primaryTitle      Freddie Jackson: You and I Got a Thang
originalTitle     Freddie Jackson: You and I Got a Thang
isAdult                                                0
startYear                                           1989
endYear                                               \N
runtimeMinutes                                         4
genres                                       Music,Short
Name: 2003738, dtype: object

(9,)

tconst                                tt11822684
titleType                              tvEpisode
primaryTitle      Big and Little - Changing Size
originalTitle     Big and Little - Changing Size
isAdult                                        0
startYear                                   2009
endYear                                       \N
runtimeMinutes                                \N
genres                                    Family
Name: 2003739, dtype: object

(9,)

tconst                                   tt11822688
titleType                                 tvEpisode
primaryTitle      Breaking All Christmas Traditions
originalTitle     Breaking All Christmas Traditions
isAdult                                           0
startYear                                      2019
endYear                                          \N
runtimeMinutes                                    9
genres                             Animation,Family
Name: 2003740, dtype: object

(9,)

tconst             tt1182268
titleType              video
primaryTitle      Desert Sol
originalTitle     Desert Sol
isAdult                    1
startYear               2004
endYear                   \N
runtimeMinutes            90
genres                 Adult
Name: 2003741, dtype: object

(9,)

tconst                                      tt11822690
titleType                                        movie
primaryTitle      Tottenham Hotspur vs Manchester City
originalTitle     Tottenham Hotspur vs Manchester City
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      90
genres                                           Sport
Name: 2003742, dtype: object

(9,)

tconst                            tt11822692
titleType                          tvEpisode
primaryTitle                    Episode #1.1
originalTitle                   Episode #1.1
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2003743, dtype: object

(9,)

tconst                            tt11822694
titleType                          tvEpisode
primaryTitle      Big and Little - Creatures
originalTitle     Big and Little - Creatures
isAdult                                    0
startYear                               2009
endYear                                   \N
runtimeMinutes                            \N
genres                                Family
Name: 2003744, dtype: object

(9,)

tconst                            tt11822696
titleType                          tvEpisode
primaryTitle      The Manny Part 2: Bareback
originalTitle     The Manny Part 2: Bareback
isAdult                                    1
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2003745, dtype: object

(9,)

tconst                          tt11822698
titleType                            movie
primaryTitle      Liverpool vs Southampton
originalTitle     Liverpool vs Southampton
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          95
genres                              Action
Name: 2003746, dtype: object

(9,)

tconst                 tt1182269
titleType                  movie
primaryTitle      Dolls for Hire
originalTitle     Dolls for Hire
isAdult                        0
startYear                   1967
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2003747, dtype: object

(9,)

tconst                       tt11822700
titleType                     tvEpisode
primaryTitle              David Plouffe
originalTitle             David Plouffe
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       30
genres            Comedy,News,Talk-Show
Name: 2003748, dtype: object

(9,)

tconst                       tt11822702
titleType                     tvEpisode
primaryTitle                Nina Dobrev
originalTitle               Nina Dobrev
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       25
genres            Comedy,News,Talk-Show
Name: 2003749, dtype: object

(9,)

tconst                                       tt11822704
titleType                                     tvEpisode
primaryTitle      Big and Little - Buildings and Robots
originalTitle     Big and Little - Buildings and Robots
isAdult                                               0
startYear                                          2009
endYear                                              \N
runtimeMinutes                                       \N
genres                                           Family
Name: 2003750, dtype: object

(9,)

tconst                               tt11822706
titleType                                 video
primaryTitle      Freddie Jackson: All Over You
originalTitle     Freddie Jackson: All Over You
isAdult                                       0
startYear                                  1990
endYear                                      \N
runtimeMinutes                                5
genres                              Music,Short
Name: 2003751, dtype: object

(9,)

tconst                       tt11822708
titleType                     tvEpisode
primaryTitle             Judith Heumann
originalTitle            Judith Heumann
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       31
genres            Comedy,News,Talk-Show
Name: 2003752, dtype: object

(9,)

tconst                                 tt1182270
titleType                                  short
primaryTitle      The Dramatic Story of the Vote
originalTitle     The Dramatic Story of the Vote
isAdult                                        0
startYear                                   1913
endYear                                       \N
runtimeMinutes                                \N
genres                               Drama,Short
Name: 2003753, dtype: object

(9,)

tconst                       tt11822710
titleType                     tvEpisode
primaryTitle             Nneka Ogwumike
originalTitle            Nneka Ogwumike
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       31
genres            Comedy,News,Talk-Show
Name: 2003754, dtype: object

(9,)

tconst                        tt11822712
titleType                      tvEpisode
primaryTitle      Colombian Double Cross
originalTitle     Colombian Double Cross
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        44
genres                 Documentary,Drama
Name: 2003755, dtype: object

(9,)

tconst                               tt11822714
titleType                                 video
primaryTitle      Freddie Jackson: Love Me Down
originalTitle     Freddie Jackson: Love Me Down
isAdult                                       0
startYear                                  1990
endYear                                      \N
runtimeMinutes                                4
genres                              Music,Short
Name: 2003756, dtype: object

(9,)

tconst                                 tt11822716
titleType                               tvEpisode
primaryTitle      Episode dated 12 September 1984
originalTitle     Episode dated 12 September 1984
isAdult                                         0
startYear                                    1984
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2003757, dtype: object

(9,)

tconst                                      tt11822718
titleType                                        movie
primaryTitle      Wolverhampton Wanderers vs Liverpool
originalTitle     Wolverhampton Wanderers vs Liverpool
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      96
genres                                          Action
Name: 2003758, dtype: object

(9,)

tconst                    tt1182271
titleType                     short
primaryTitle      Eftyhismeni genia
originalTitle     Eftyhismeni genia
isAdult                           0
startYear                      1978
endYear                          \N
runtimeMinutes                   23
genres                 Sci-Fi,Short
Name: 2003759, dtype: object

(9,)

tconst                              tt11822720
titleType                                video
primaryTitle      Freddie Jackson: Do Me Again
originalTitle     Freddie Jackson: Do Me Again
isAdult                                      0
startYear                                 1991
endYear                                     \N
runtimeMinutes                               5
genres                             Music,Short
Name: 2003760, dtype: object

(9,)

tconst                                              tt11822722
titleType                                            tvEpisode
primaryTitle      Big and Little - Clocks, Rockets and Insects
originalTitle     Big and Little - Clocks, Rockets and Insects
isAdult                                                      0
startYear                                                 2009
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                  Family
Name: 2003761, dtype: object

(9,)

tconst               tt11822724
titleType             tvEpisode
primaryTitle      Spécial Garbo
originalTitle     Spécial Garbo
isAdult                       0
startYear                  1986
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2003762, dtype: object

(9,)

tconst                              tt11822726
titleType                                video
primaryTitle      Freddie Jackson: Main Course
originalTitle     Freddie Jackson: Main Course
isAdult                                      0
startYear                                 1991
endYear                                     \N
runtimeMinutes                               4
genres                             Music,Short
Name: 2003763, dtype: object

(9,)

tconst                                tt11822728
titleType                              tvEpisode
primaryTitle      Hair - Different Types of hair
originalTitle     Hair - Different Types of hair
isAdult                                        0
startYear                                   1992
endYear                                       \N
runtimeMinutes                                \N
genres                                    Family
Name: 2003764, dtype: object

(9,)

tconst                    tt1182272
titleType                   tvMovie
primaryTitle               Eldorado
originalTitle              Eldorado
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   88
genres            Documentary,Music
Name: 2003765, dtype: object

(9,)

tconst               tt11822730
titleType             tvEpisode
primaryTitle      Hair - Horses
originalTitle     Hair - Horses
isAdult                       0
startYear                  1992
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2003766, dtype: object

(9,)

tconst                                                   tt11822732
titleType                                                     video
primaryTitle      Freddie Jackson: I Could Use a Little Love (Ri...
originalTitle     Freddie Jackson: I Could Use a Little Love (Ri...
isAdult                                                           0
startYear                                                      1992
endYear                                                          \N
runtimeMinutes                                                    5
genres                                                  Music,Short
Name: 2003767, dtype: object

(9,)

tconst                 tt11822734
titleType               tvEpisode
primaryTitle      Hair - Echidnas
originalTitle     Hair - Echidnas
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2003768, dtype: object

(9,)

tconst                   tt11822736
titleType                 tvEpisode
primaryTitle      Hair - Silly Hair
originalTitle     Hair - Silly Hair
isAdult                           0
startYear                      1992
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2003769, dtype: object

(9,)

tconst                     tt11822738
titleType                   tvEpisode
primaryTitle      Hair - Washing Hair
originalTitle     Hair - Washing Hair
isAdult                             0
startYear                        1992
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2003770, dtype: object

(9,)

tconst                              tt1182273
titleType                               video
primaryTitle        Fad Gadget by Frank Tovey
originalTitle       Fad Gadget by Frank Tovey
isAdult                                     0
startYear                                2006
endYear                                    \N
runtimeMinutes                            150
genres            Biography,Documentary,Music
Name: 2003771, dtype: object

(9,)

tconst                                  tt11822740
titleType                                    video
primaryTitle      Freddie Jackson: Can I Touch You
originalTitle     Freddie Jackson: Can I Touch You
isAdult                                          0
startYear                                     1992
endYear                                         \N
runtimeMinutes                                   4
genres                                 Music,Short
Name: 2003772, dtype: object

(9,)

tconst                                    tt11822742
titleType                                      video
primaryTitle      Freddie Jackson: Me and Mrs. Jones
originalTitle     Freddie Jackson: Me and Mrs. Jones
isAdult                                            0
startYear                                       1992
endYear                                           \N
runtimeMinutes                                     4
genres                                   Music,Short
Name: 2003773, dtype: object

(9,)

tconst                       tt11822744
titleType                         movie
primaryTitle      Viva La Musica Cubana
originalTitle     Viva La Musica Cubana
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2003774, dtype: object

(9,)

tconst                   tt11822746
titleType                 tvEpisode
primaryTitle      A Teacher's Crush
originalTitle     A Teacher's Crush
isAdult                           1
startYear                      2011
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2003775, dtype: object

(9,)

tconst                                 tt11822748
titleType                                   video
primaryTitle      Freddie Jackson: Make Love Easy
originalTitle     Freddie Jackson: Make Love Easy
isAdult                                         0
startYear                                    1993
endYear                                        \N
runtimeMinutes                                  4
genres                                Music,Short
Name: 2003776, dtype: object

(9,)

tconst                    tt1182274
titleType                     short
primaryTitle                 G.S.O.
originalTitle                G.S.O.
isAdult                           0
startYear                      1957
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2003777, dtype: object

(9,)

tconst                 tt11822750
titleType                   short
primaryTitle      El sueño de Eva
originalTitle     El sueño de Eva
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres              Fantasy,Short
Name: 2003778, dtype: object

(9,)

tconst                     tt11822752
titleType                       movie
primaryTitle      The Northwest Derby
originalTitle     The Northwest Derby
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     97
genres                         Action
Name: 2003779, dtype: object

(9,)

tconst                         tt11822754
titleType                       tvEpisode
primaryTitle      Aiden Ward & Shane Cook
originalTitle     Aiden Ward & Shane Cook
isAdult                                 1
startYear                            2020
endYear                                \N
runtimeMinutes                         33
genres                              Adult
Name: 2003780, dtype: object

(9,)

tconst                                   tt11822756
titleType                                     video
primaryTitle      Freddie Jackson: Was It Something
originalTitle     Freddie Jackson: Was It Something
isAdult                                           0
startYear                                      1994
endYear                                          \N
runtimeMinutes                                    5
genres                                  Music,Short
Name: 2003781, dtype: object

(9,)

tconst                     tt11822758
titleType                   tvEpisode
primaryTitle             Episode #1.1
originalTitle            Episode #1.1
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003782, dtype: object

(9,)

tconst                          tt1182275
titleType                           short
primaryTitle      The Glutton's Nightmare
originalTitle     The Glutton's Nightmare
isAdult                                 0
startYear                            1901
endYear                                \N
runtimeMinutes                         \N
genres                              Short
Name: 2003783, dtype: object

(9,)

tconst                    tt11822760
titleType                  tvEpisode
primaryTitle           Episode #12.2
originalTitle          Episode #12.2
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003784, dtype: object

(9,)

tconst                    tt11822762
titleType                  tvEpisode
primaryTitle           Episode #12.3
originalTitle          Episode #12.3
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003785, dtype: object

(9,)

tconst                    tt11822764
titleType                  tvEpisode
primaryTitle           Episode #12.5
originalTitle          Episode #12.5
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003786, dtype: object

(9,)

tconst                    tt11822766
titleType                  tvEpisode
primaryTitle           Episode #12.4
originalTitle          Episode #12.4
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003787, dtype: object

(9,)

tconst                    tt11822768
titleType                  tvEpisode
primaryTitle           Episode #12.6
originalTitle          Episode #12.6
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003788, dtype: object

(9,)

tconst                    tt1182276
titleType                     video
primaryTitle      Going Underground
originalTitle     Going Underground
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2003789, dtype: object

(9,)

tconst                                     tt11822770
titleType                                       video
primaryTitle      Freddie Jackson: Rub Up Against You
originalTitle     Freddie Jackson: Rub Up Against You
isAdult                                             0
startYear                                        1995
endYear                                            \N
runtimeMinutes                                      5
genres                                    Music,Short
Name: 2003790, dtype: object

(9,)

tconst                    tt11822772
titleType                  tvEpisode
primaryTitle           Episode #12.7
originalTitle          Episode #12.7
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003791, dtype: object

(9,)

tconst                    tt11822774
titleType                  tvEpisode
primaryTitle          Episode #12.11
originalTitle         Episode #12.11
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003792, dtype: object

(9,)

tconst                    tt11822776
titleType                  tvEpisode
primaryTitle           Episode #12.8
originalTitle          Episode #12.8
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003793, dtype: object

(9,)

tconst                    tt11822778
titleType                  tvEpisode
primaryTitle          Episode #12.10
originalTitle         Episode #12.10
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003794, dtype: object

(9,)

tconst                        tt1182277
titleType                         movie
primaryTitle      Guns of Billy the Kid
originalTitle     Guns of Billy the Kid
isAdult                               0
startYear                          1967
endYear                              \N
runtimeMinutes                       \N
genres                           Action
Name: 2003795, dtype: object

(9,)

tconst                     tt11822780
titleType                   tvEpisode
primaryTitle             Episode #1.2
originalTitle            Episode #1.2
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003796, dtype: object

(9,)

tconst                    tt11822782
titleType                  tvEpisode
primaryTitle           Episode #12.9
originalTitle          Episode #12.9
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003797, dtype: object

(9,)

tconst                    tt11822784
titleType                  tvEpisode
primaryTitle          Episode #12.12
originalTitle         Episode #12.12
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003798, dtype: object

(9,)

tconst                    tt11822786
titleType                  tvEpisode
primaryTitle          Episode #12.13
originalTitle         Episode #12.13
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003799, dtype: object

(9,)

tconst                    tt11822788
titleType                  tvEpisode
primaryTitle          Episode #12.14
originalTitle         Episode #12.14
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003800, dtype: object

(9,)

tconst                               tt1182278
titleType                                video
primaryTitle      Oi gynaikes mou trellathikan
originalTitle     Oi gynaikes mou trellathikan
isAdult                                      0
startYear                                 1986
endYear                                     \N
runtimeMinutes                             117
genres                                  Comedy
Name: 2003801, dtype: object

(9,)

tconst                    tt11822790
titleType                  tvEpisode
primaryTitle          Episode #12.15
originalTitle         Episode #12.15
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003802, dtype: object

(9,)

tconst                    tt11822792
titleType                  tvEpisode
primaryTitle          Episode #12.16
originalTitle         Episode #12.16
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003803, dtype: object

(9,)

tconst                    tt11822794
titleType                  tvEpisode
primaryTitle          Episode #12.17
originalTitle         Episode #12.17
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003804, dtype: object

(9,)

tconst                                        tt11822796
titleType                                          video
primaryTitle      Freddie Jackson: (I Want To) Thank You
originalTitle     Freddie Jackson: (I Want To) Thank You
isAdult                                                0
startYear                                           1995
endYear                                               \N
runtimeMinutes                                         5
genres                                       Music,Short
Name: 2003805, dtype: object

(9,)

tconst                    tt11822798
titleType                  tvEpisode
primaryTitle          Episode #12.19
originalTitle         Episode #12.19
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003806, dtype: object

(9,)

tconst                    tt1182279
titleType                     movie
primaryTitle      Hari ng Lansangan
originalTitle     Hari ng Lansangan
isAdult                           0
startYear                      1965
endYear                          \N
runtimeMinutes                   \N
genres                       Action
Name: 2003807, dtype: object

(9,)

tconst                                   tt11822800
titleType                                     movie
primaryTitle      Manchester City vs Crystal Palace
originalTitle     Manchester City vs Crystal Palace
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   97
genres                                       Action
Name: 2003808, dtype: object

(9,)

tconst                    tt11822802
titleType                  tvEpisode
primaryTitle          Episode #12.18
originalTitle         Episode #12.18
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003809, dtype: object

(9,)

tconst                    tt11822804
titleType                  tvEpisode
primaryTitle          Episode #12.20
originalTitle         Episode #12.20
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003810, dtype: object

(9,)

tconst                    tt11822806
titleType                  tvEpisode
primaryTitle          Episode #12.21
originalTitle         Episode #12.21
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003811, dtype: object

(9,)

tconst                    tt11822808
titleType                  tvEpisode
primaryTitle          Episode #12.22
originalTitle         Episode #12.22
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003812, dtype: object

(9,)

tconst                                       tt1182280
titleType                                        video
primaryTitle      Hello Sailor!: Making the Sea Devils
originalTitle     Hello Sailor!: Making the Sea Devils
isAdult                                              0
startYear                                         2008
endYear                                             \N
runtimeMinutes                                      37
genres                               Documentary,Short
Name: 2003813, dtype: object

(9,)

tconst                    tt11822810
titleType                  tvEpisode
primaryTitle          Episode #12.23
originalTitle         Episode #12.23
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003814, dtype: object

(9,)

tconst                    tt11822812
titleType                  tvEpisode
primaryTitle          Episode #12.24
originalTitle         Episode #12.24
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003815, dtype: object

(9,)

tconst                    tt11822814
titleType                  tvEpisode
primaryTitle          Episode #12.26
originalTitle         Episode #12.26
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003816, dtype: object

(9,)

tconst                    tt11822816
titleType                  tvEpisode
primaryTitle          Episode #12.25
originalTitle         Episode #12.25
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003817, dtype: object

(9,)

tconst                    tt11822818
titleType                  tvEpisode
primaryTitle          Episode #12.29
originalTitle         Episode #12.29
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003818, dtype: object

(9,)

tconst                                        tt1182281
titleType                                         video
primaryTitle      The Hills Have Eyes 2: Mutant Attacks
originalTitle     The Hills Have Eyes 2: Mutant Attacks
isAdult                                               0
startYear                                          2007
endYear                                              \N
runtimeMinutes                                       10
genres                                Documentary,Short
Name: 2003819, dtype: object

(9,)

tconst                    tt11822820
titleType                  tvEpisode
primaryTitle          Episode #12.27
originalTitle         Episode #12.27
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003820, dtype: object

(9,)

tconst                    tt11822822
titleType                  tvEpisode
primaryTitle          Episode #12.28
originalTitle         Episode #12.28
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003821, dtype: object

(9,)

tconst                    tt11822824
titleType                  tvEpisode
primaryTitle          Episode #12.31
originalTitle         Episode #12.31
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003822, dtype: object

(9,)

tconst                    tt11822826
titleType                  tvEpisode
primaryTitle          Episode #12.30
originalTitle         Episode #12.30
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003823, dtype: object

(9,)

tconst                    tt11822828
titleType                  tvEpisode
primaryTitle          Episode #12.32
originalTitle         Episode #12.32
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003824, dtype: object

(9,)

tconst                  tt1182282
titleType                   short
primaryTitle      El hombre feliz
originalTitle     El hombre feliz
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 14
genres                      Short
Name: 2003825, dtype: object

(9,)

tconst                    tt11822830
titleType                  tvEpisode
primaryTitle          Episode #12.33
originalTitle         Episode #12.33
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003826, dtype: object

(9,)

tconst                    tt11822832
titleType                  tvEpisode
primaryTitle          Episode #12.36
originalTitle         Episode #12.36
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003827, dtype: object

(9,)

tconst                    tt11822834
titleType                  tvEpisode
primaryTitle          Episode #12.34
originalTitle         Episode #12.34
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003828, dtype: object

(9,)

tconst                    tt11822836
titleType                  tvEpisode
primaryTitle          Episode #12.35
originalTitle         Episode #12.35
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003829, dtype: object

(9,)

tconst                     tt11822838
titleType                   tvEpisode
primaryTitle             Episode #1.3
originalTitle            Episode #1.3
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003830, dtype: object

(9,)

tconst                            tt1182283
titleType                             movie
primaryTitle      I'll See You in September
originalTitle     I'll See You in September
isAdult                                   0
startYear                              1967
endYear                                  \N
runtimeMinutes                           \N
genres                       Comedy,Musical
Name: 2003831, dtype: object

(9,)

tconst                    tt11822840
titleType                  tvEpisode
primaryTitle          Episode #12.37
originalTitle         Episode #12.37
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003832, dtype: object

(9,)

tconst                    tt11822842
titleType                  tvEpisode
primaryTitle          Episode #12.39
originalTitle         Episode #12.39
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003833, dtype: object

(9,)

tconst                    tt11822844
titleType                  tvEpisode
primaryTitle          Episode #12.38
originalTitle         Episode #12.38
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003834, dtype: object

(9,)

tconst                    tt11822846
titleType                  tvEpisode
primaryTitle          Episode #12.40
originalTitle         Episode #12.40
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003835, dtype: object

(9,)

tconst                    tt11822848
titleType                  tvEpisode
primaryTitle          Episode #12.41
originalTitle         Episode #12.41
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003836, dtype: object

(9,)

tconst                                                    tt1182284
titleType                                                   tvMovie
primaryTitle      Ich bin ein weißer Afrikaner - Abschied von Je...
originalTitle     Ich bin ein weißer Afrikaner - Abschied von Je...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   55
genres                                                  Documentary
Name: 2003837, dtype: object

(9,)

tconst                    tt11822850
titleType                  tvEpisode
primaryTitle          Episode #12.42
originalTitle         Episode #12.42
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003838, dtype: object

(9,)

tconst                    tt11822852
titleType                  tvEpisode
primaryTitle          Episode #12.43
originalTitle         Episode #12.43
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003839, dtype: object

(9,)

tconst                    tt11822854
titleType                  tvEpisode
primaryTitle          Episode #12.44
originalTitle         Episode #12.44
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003840, dtype: object

(9,)

tconst                    tt11822856
titleType                  tvEpisode
primaryTitle          Episode #12.45
originalTitle         Episode #12.45
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003841, dtype: object

(9,)

tconst                    tt11822858
titleType                  tvEpisode
primaryTitle          Episode #12.46
originalTitle         Episode #12.46
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003842, dtype: object

(9,)

tconst                              tt1182285
titleType                             tvMovie
primaryTitle      Ich trag' im Herzen drin...
originalTitle     Ich trag' im Herzen drin...
isAdult                                     0
startYear                                1969
endYear                                    \N
runtimeMinutes                             \N
genres                              Biography
Name: 2003843, dtype: object

(9,)

tconst              tt11822860
titleType                short
primaryTitle      The Passerby
originalTitle       De Passant
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              17
genres             Drama,Short
Name: 2003844, dtype: object

(9,)

tconst                    tt11822862
titleType                  tvEpisode
primaryTitle          Episode #12.47
originalTitle         Episode #12.47
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003845, dtype: object

(9,)

tconst                    tt11822864
titleType                  tvEpisode
primaryTitle          Episode #12.49
originalTitle         Episode #12.49
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003846, dtype: object

(9,)

tconst                    tt11822866
titleType                  tvEpisode
primaryTitle          Episode #12.48
originalTitle         Episode #12.48
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003847, dtype: object

(9,)

tconst                    tt11822868
titleType                  tvEpisode
primaryTitle          Episode #12.50
originalTitle         Episode #12.50
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2003848, dtype: object

(9,)

tconst                                                    tt1182286
titleType                                                 tvSpecial
primaryTitle      Ich will Spaß - Die 80er-Jahre-Pop-und-Schlage...
originalTitle     Ich will Spaß - Die 80er-Jahre-Pop-und-Schlage...
isAdult                                                           0
startYear                                                      2004
endYear                                                          \N
runtimeMinutes                                                  200
genres                                 Biography,Comedy,Documentary
Name: 2003849, dtype: object

(9,)

tconst                     tt11822870
titleType                   tvEpisode
primaryTitle             Episode #1.4
originalTitle            Episode #1.4
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003850, dtype: object

(9,)

tconst                                tt11822872
titleType                                  movie
primaryTitle      Tottenham Hotspur vs Liverpool
originalTitle     Tottenham Hotspur vs Liverpool
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                97
genres                                    Action
Name: 2003851, dtype: object

(9,)

tconst                     tt11822874
titleType                   tvEpisode
primaryTitle             Episode #1.5
originalTitle            Episode #1.5
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003852, dtype: object

(9,)

tconst                                         tt11822876
titleType                                           video
primaryTitle      Najee & Freddie Jackson: All I Ever Ask
originalTitle     Najee & Freddie Jackson: All I Ever Ask
isAdult                                                 0
startYear                                            1993
endYear                                                \N
runtimeMinutes                                          4
genres                                        Music,Short
Name: 2003853, dtype: object

(9,)

tconst                                 tt1182287
titleType                              tvEpisode
primaryTitle      Bob Marley: I Shot the Sheriff
originalTitle     Bob Marley: I Shot the Sheriff
isAdult                                        0
startYear                                   2007
endYear                                       \N
runtimeMinutes                                35
genres                         Documentary,Music
Name: 2003854, dtype: object

(9,)

tconst                     tt11822880
titleType                   tvEpisode
primaryTitle             Episode #1.6
originalTitle            Episode #1.6
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003855, dtype: object

(9,)

tconst                               tt11822882
titleType                                 movie
primaryTitle      Liverpool vs Sheffield United
originalTitle     Liverpool vs Sheffield United
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               95
genres                                       \N
Name: 2003856, dtype: object

(9,)

tconst             tt11822884
titleType           tvEpisode
primaryTitle          Tuscany
originalTitle         Tuscany
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003857, dtype: object

(9,)

tconst                  tt11822888
titleType                tvEpisode
primaryTitle        Episode #1.839
originalTitle       Episode #1.839
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003858, dtype: object

(9,)

tconst                          tt1182288
titleType                       tvEpisode
primaryTitle      Chuck Berry: Maybellene
originalTitle     Chuck Berry: Maybellene
isAdult                                 0
startYear                            2007
endYear                                \N
runtimeMinutes                         35
genres                  Documentary,Music
Name: 2003859, dtype: object

(9,)

tconst             tt11822890
titleType               short
primaryTitle             Mall
originalTitle            Mall
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              7
genres            Drama,Short
Name: 2003860, dtype: object

(9,)

tconst                  tt11822892
titleType                tvEpisode
primaryTitle        Episode #1.840
originalTitle       Episode #1.840
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003861, dtype: object

(9,)

tconst                     tt11822894
titleType                   tvEpisode
primaryTitle             Episode #1.8
originalTitle            Episode #1.8
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003862, dtype: object

(9,)

tconst                  tt11822896
titleType                tvEpisode
primaryTitle        Episode #1.841
originalTitle       Episode #1.841
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003863, dtype: object

(9,)

tconst                                        tt11822898
titleType                                        tvMovie
primaryTitle               Stalin and the Katyn Massacre
originalTitle     Les bourreaux de Staline - Katyn, 1940
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        97
genres                               Documentary,History
Name: 2003864, dtype: object

(9,)

tconst                                  tt1182289
titleType                               tvEpisode
primaryTitle      Elvis Presley: Heartbreak Hotel
originalTitle     Elvis Presley: Heartbreak Hotel
isAdult                                         0
startYear                                    2007
endYear                                        \N
runtimeMinutes                                 35
genres                          Documentary,Music
Name: 2003865, dtype: object

(9,)

tconst                  tt11822900
titleType                tvEpisode
primaryTitle        Episode #1.842
originalTitle       Episode #1.842
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003866, dtype: object

(9,)

tconst                     tt11822902
titleType                   tvEpisode
primaryTitle             Episode #1.9
originalTitle            Episode #1.9
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003867, dtype: object

(9,)

tconst                  tt11822904
titleType                tvEpisode
primaryTitle        Episode #1.843
originalTitle       Episode #1.843
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003868, dtype: object

(9,)

tconst                  tt11822906
titleType                tvEpisode
primaryTitle        Episode #1.844
originalTitle       Episode #1.844
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003869, dtype: object

(9,)

tconst             tt11822908
titleType           tvEpisode
primaryTitle        Marrakesh
originalTitle       Marrakesh
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003870, dtype: object

(9,)

tconst                         tt1182290
titleType                      tvEpisode
primaryTitle      Madonna: Like a Virgin
originalTitle     Madonna: Like a Virgin
isAdult                                0
startYear                           2007
endYear                               \N
runtimeMinutes                        35
genres                 Documentary,Music
Name: 2003871, dtype: object

(9,)

tconst                                                   tt11822910
titleType                                                     video
primaryTitle      Melba Moore Feat. Freddie Jackson: I Can't Com...
originalTitle     Melba Moore Feat. Freddie Jackson: I Can't Com...
isAdult                                                           0
startYear                                                      1988
endYear                                                          \N
runtimeMinutes                                                    5
genres                                                  Music,Short
Name: 2003872, dtype: object

(9,)

tconst                     tt11822912
titleType                   tvEpisode
primaryTitle            Episode #1.10
originalTitle           Episode #1.10
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003873, dtype: object

(9,)

tconst                  tt11822914
titleType                tvEpisode
primaryTitle        Episode #1.845
originalTitle       Episode #1.845
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003874, dtype: object

(9,)

tconst             tt11822916
titleType           tvEpisode
primaryTitle           Israel
originalTitle          Israel
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003875, dtype: object

(9,)

tconst                  tt11822918
titleType                tvEpisode
primaryTitle        Episode #1.846
originalTitle       Episode #1.846
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003876, dtype: object

(9,)

tconst                                   tt1182291
titleType                                tvEpisode
primaryTitle      Nirvana: Smells Like Teen Spirit
originalTitle     Nirvana: Smells Like Teen Spirit
isAdult                                          0
startYear                                     2007
endYear                                         \N
runtimeMinutes                                  35
genres                           Documentary,Music
Name: 2003877, dtype: object

(9,)

tconst                     tt11822920
titleType                   tvEpisode
primaryTitle            Episode #1.11
originalTitle           Episode #1.11
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003878, dtype: object

(9,)

tconst                  tt11822922
titleType                tvEpisode
primaryTitle        Episode #1.847
originalTitle       Episode #1.847
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003879, dtype: object

(9,)

tconst                                                 tt11822924
titleType                                               tvEpisode
primaryTitle      La casa de las locas XVI - El comisario fracasa
originalTitle     La casa de las locas XVI - El comisario fracasa
isAdult                                                         0
startYear                                                    1974
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                      Drama
Name: 2003880, dtype: object

(9,)

tconst             tt11822926
titleType           tvEpisode
primaryTitle         Florence
originalTitle        Florence
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003881, dtype: object

(9,)

tconst                  tt11822928
titleType                tvEpisode
primaryTitle        Episode #1.848
originalTitle       Episode #1.848
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003882, dtype: object

(9,)

tconst                                       tt1182292
titleType                                    tvEpisode
primaryTitle      Run DMC and Aerosmith: Walk This Way
originalTitle     Run DMC and Aerosmith: Walk This Way
isAdult                                              0
startYear                                         2007
endYear                                             \N
runtimeMinutes                                      35
genres                               Documentary,Music
Name: 2003883, dtype: object

(9,)

tconst                     tt11822930
titleType                   tvEpisode
primaryTitle            Episode #1.12
originalTitle           Episode #1.12
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2003884, dtype: object

(9,)

tconst                                             tt11822932
titleType                                           tvEpisode
primaryTitle      La casa de las locas XVII - El reo de Melun
originalTitle     La casa de las locas XVII - El reo de Melun
isAdult                                                     0
startYear                                                1974
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                  Drama
Name: 2003885, dtype: object

(9,)

tconst                  tt11822934
titleType                tvEpisode
primaryTitle        Episode #1.849
originalTitle       Episode #1.849
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003886, dtype: object

(9,)

tconst                             tt11822936
titleType                           tvEpisode
primaryTitle      Italy and the Mediterranean
originalTitle     Italy and the Mediterranean
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                            Documentary
Name: 2003887, dtype: object

(9,)

tconst                     tt11822938
titleType                   tvEpisode
primaryTitle            Episode #1.13
originalTitle           Episode #1.13
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     35
genres            Comedy,Drama,Family
Name: 2003888, dtype: object

(9,)

tconst                                        tt1182293
titleType                                     tvEpisode
primaryTitle      The Beatles: I Want to Hold Your Hand
originalTitle     The Beatles: I Want to Hold Your Hand
isAdult                                               0
startYear                                          2007
endYear                                              \N
runtimeMinutes                                       35
genres                                Documentary,Music
Name: 2003889, dtype: object

(9,)

tconst                                      tt11822940
titleType                                        movie
primaryTitle      Liverpool vs Wolverhampton Wanderers
originalTitle     Liverpool vs Wolverhampton Wanderers
isAdult                                              0
startYear                                         2019
endYear                                             \N
runtimeMinutes                                      97
genres                                          Action
Name: 2003890, dtype: object

(9,)

tconst                     tt11822942
titleType                   tvEpisode
primaryTitle            Episode #1.14
originalTitle           Episode #1.14
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     33
genres            Comedy,Drama,Family
Name: 2003891, dtype: object

(9,)

tconst                              tt11822944
titleType                            tvEpisode
primaryTitle      Journalist - Clueless Expert
originalTitle     Journalist - Clueless Expert
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                     Comedy,Drama,Sci-Fi
Name: 2003892, dtype: object

(9,)

tconst                        tt11822946
titleType                      tvEpisode
primaryTitle      Amman and the Dead Sea
originalTitle     Amman and the Dead Sea
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2003893, dtype: object

(9,)

tconst                  tt11822948
titleType                tvEpisode
primaryTitle        Episode #1.850
originalTitle       Episode #1.850
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003894, dtype: object

(9,)

tconst                              tt1182294
titleType                           tvEpisode
primaryTitle      The Bee Gees: Stayin' Alive
originalTitle     The Bee Gees: Stayin' Alive
isAdult                                     0
startYear                                2007
endYear                                    \N
runtimeMinutes                             35
genres                      Documentary,Music
Name: 2003895, dtype: object

(9,)

tconst                                                  tt11822950
titleType                                                tvEpisode
primaryTitle      La casa de las locas XVIII - Los ases en la mano
originalTitle     La casa de las locas XVIII - Los ases en la mano
isAdult                                                          0
startYear                                                     1974
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                       Drama
Name: 2003896, dtype: object

(9,)

tconst                  tt11822952
titleType                tvEpisode
primaryTitle        Episode #1.851
originalTitle       Episode #1.851
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003897, dtype: object

(9,)

tconst                     tt11822954
titleType                   tvEpisode
primaryTitle            Episode #1.15
originalTitle           Episode #1.15
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     31
genres            Comedy,Drama,Family
Name: 2003898, dtype: object

(9,)

tconst                     tt11822956
titleType                   tvEpisode
primaryTitle            Episode #1.16
originalTitle           Episode #1.16
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     37
genres            Comedy,Drama,Family
Name: 2003899, dtype: object

(9,)

tconst                                                tt11822958
titleType                                              tvEpisode
primaryTitle      La casa de las locas XIX - El día de San Telmo
originalTitle     La casa de las locas XIX - El día de San Telmo
isAdult                                                        0
startYear                                                   1974
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                     Drama
Name: 2003900, dtype: object

(9,)

tconst                                  tt1182295
titleType                               tvEpisode
primaryTitle      The Ramones: I Wanna Be Sedated
originalTitle     The Ramones: I Wanna Be Sedated
isAdult                                         0
startYear                                    2003
endYear                                        \N
runtimeMinutes                                 35
genres                          Documentary,Music
Name: 2003901, dtype: object

(9,)

tconst            tt11822960
titleType              short
primaryTitle           Rages
originalTitle          Rages
isAdult                    0
startYear               2018
endYear                   \N
runtimeMinutes            30
genres                 Short
Name: 2003902, dtype: object

(9,)

tconst                                    tt11822962
titleType                                  tvEpisode
primaryTitle      Qin Guo Pian: Wei Shen Me Shi Qin?
originalTitle     Qin Guo Pian: Wei Shen Me Shi Qin?
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    66
genres                                   Documentary
Name: 2003903, dtype: object

(9,)

tconst                     tt11822964
titleType                   tvEpisode
primaryTitle            Episode #1.17
originalTitle           Episode #1.17
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     40
genres            Comedy,Drama,Family
Name: 2003904, dtype: object

(9,)

tconst                                                   tt11822966
titleType                                                     short
primaryTitle      Yorgos Psailas - A portrait of the British Cem...
originalTitle     Yorgos Psailas - A portrait of the British Cem...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   20
genres                                            Documentary,Short
Name: 2003905, dtype: object

(9,)

tconst                                   tt11822968
titleType                                     video
primaryTitle      Freddie Jackson: I Don't Wanna Go
originalTitle     Freddie Jackson: I Don't Wanna Go
isAdult                                           0
startYear                                      2010
endYear                                          \N
runtimeMinutes                                    5
genres                                  Music,Short
Name: 2003906, dtype: object

(9,)

tconst                                 tt1182296
titleType                                  video
primaryTitle      Kante - Die Tiere sind unruhig
originalTitle     Kante - Die Tiere sind unruhig
isAdult                                        0
startYear                                   2006
endYear                                       \N
runtimeMinutes                                \N
genres                   Documentary,Music,Short
Name: 2003907, dtype: object

(9,)

tconst                  tt11822970
titleType                tvEpisode
primaryTitle        Episode #1.852
originalTitle       Episode #1.852
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003908, dtype: object

(9,)

tconst                     tt11822972
titleType                   tvEpisode
primaryTitle            Episode #1.18
originalTitle           Episode #1.18
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     34
genres            Comedy,Drama,Family
Name: 2003909, dtype: object

(9,)

tconst                             tt11822974
titleType                               movie
primaryTitle      Leicester City vs Liverpool
originalTitle     Leicester City vs Liverpool
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             95
genres                                 Action
Name: 2003910, dtype: object

(9,)

tconst                  tt11822976
titleType                tvEpisode
primaryTitle        Episode #1.853
originalTitle       Episode #1.853
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003911, dtype: object

(9,)

tconst                                                  tt11822978
titleType                                                  tvMovie
primaryTitle      Zwischen Tag und Traum - In der Vorstadt Europas
originalTitle     Zwischen Tag und Traum - In der Vorstadt Europas
isAdult                                                          0
startYear                                                     1964
endYear                                                         \N
runtimeMinutes                                                  40
genres                                                 Documentary
Name: 2003912, dtype: object

(9,)

tconst              tt1182297
titleType               short
primaryTitle      Kapoia mera
originalTitle     Kapoia mera
isAdult                     0
startYear                1978
endYear                    \N
runtimeMinutes             26
genres                  Short
Name: 2003913, dtype: object

(9,)

tconst                     tt11822980
titleType                   tvEpisode
primaryTitle            Episode #1.19
originalTitle           Episode #1.19
isAdult                             0
startYear                        2012
endYear                            \N
runtimeMinutes                     43
genres            Comedy,Drama,Family
Name: 2003914, dtype: object

(9,)

tconst            tt11822986
titleType              short
primaryTitle        Bad Trip
originalTitle       Bad Trip
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            14
genres                 Short
Name: 2003915, dtype: object

(9,)

tconst                                       tt11822988
titleType                                         movie
primaryTitle      Manchester United vs Newcastle United
originalTitle     Manchester United vs Newcastle United
isAdult                                               0
startYear                                          2019
endYear                                              \N
runtimeMinutes                                       90
genres                                            Sport
Name: 2003916, dtype: object

(9,)

tconst                       tt1182298
titleType                      tvMovie
primaryTitle      Komödie der Irrungen
originalTitle     Komödie der Irrungen
isAdult                              0
startYear                         1970
endYear                             \N
runtimeMinutes                      60
genres                          Comedy
Name: 2003917, dtype: object

(9,)

tconst                                                   tt11822990
titleType                                                 tvEpisode
primaryTitle      La casa de las locas XX - La larga noche de Fa...
originalTitle     La casa de las locas XX - La larga noche de Fa...
isAdult                                                           0
startYear                                                      1974
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Drama
Name: 2003918, dtype: object

(9,)

tconst                        tt11822992
titleType                          short
primaryTitle             Everyday ZOMBIE
originalTitle            Everyday ZOMBIE
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                        41
genres            Comedy,Musical,Romance
Name: 2003919, dtype: object

(9,)

tconst                             tt11822994
titleType                            tvSeries
primaryTitle      Sleepless Society: Insomnia
originalTitle     Sleepless Society: Insomnia
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                 Drama,Mystery,Thriller
Name: 2003920, dtype: object

(9,)

tconst                tt11822996
titleType                  movie
primaryTitle      LFC versus WFC
originalTitle     LFC versus WFC
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                96
genres                     Sport
Name: 2003921, dtype: object

(9,)

tconst                                 tt11822998
titleType                            tvMiniSeries
primaryTitle      The Trials of Gabriel Fernandez
originalTitle     The Trials of Gabriel Fernandez
isAdult                                         0
startYear                                    2020
endYear                                      2020
runtimeMinutes                                331
genres                          Crime,Documentary
Name: 2003922, dtype: object

(9,)

tconst                        tt1182299
titleType                         video
primaryTitle      Lacrimosa: Lichtjahre
originalTitle     Lacrimosa: Lichtjahre
isAdult                               0
startYear                          2007
endYear                              \N
runtimeMinutes                      190
genres                Documentary,Music
Name: 2003923, dtype: object

(9,)

tconst                                                   tt11823000
titleType                                                     movie
primaryTitle      Carabao Cup Semi-Final Manchester United vs Ma...
originalTitle     Carabao Cup Semi-Final Manchester United vs Ma...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   95
genres                                                        Sport
Name: 2003924, dtype: object

(9,)

tconst              tt11823002
titleType            tvEpisode
primaryTitle      The Old Ones
originalTitle     The Old Ones
isAdult                      0
startYear                 1953
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2003925, dtype: object

(9,)

tconst                        tt11823004
titleType                          movie
primaryTitle      Monterrey vs Liverpool
originalTitle     Monterrey vs Liverpool
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                        93
genres                            Action
Name: 2003926, dtype: object

(9,)

tconst            tt11823006
titleType          tvEpisode
primaryTitle      Brain Wash
originalTitle     Brain Wash
isAdult                    0
startYear               1953
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003927, dtype: object

(9,)

tconst                          tt1182300
titleType                           movie
primaryTitle      Let's Go Merry Go Round
originalTitle     Let's Go Merry Go Round
isAdult                                 0
startYear                            1967
endYear                                \N
runtimeMinutes                         \N
genres                            Musical
Name: 2003928, dtype: object

(9,)

tconst                                tt11823010
titleType                              tvEpisode
primaryTitle      Not as a Wota, but as a Person
originalTitle     Not as a Wota, but as a Person
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                24
genres                                 Animation
Name: 2003929, dtype: object

(9,)

tconst                tt11823012
titleType              tvEpisode
primaryTitle      The Golden Cat
originalTitle     The Golden Cat
isAdult                        0
startYear                   1953
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2003930, dtype: object

(9,)

tconst                    tt11823014
titleType                      video
primaryTitle      Nika Turkovic: Raj
originalTitle     Nika Turkovic: Raj
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                     3
genres                   Music,Short
Name: 2003931, dtype: object

(9,)

tconst                          tt11823016
titleType                        tvEpisode
primaryTitle                     Tea Party
originalTitle                    Tea Party
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Fantasy
Name: 2003932, dtype: object

(9,)

tconst                                                   tt11823018
titleType                                                 tvSpecial
primaryTitle      Carabao Cup Quarter-Final Aston Villa vs Liver...
originalTitle     Carabao Cup Quarter-Final Aston Villa vs Liver...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   93
genres                                                   Reality-TV
Name: 2003933, dtype: object

(9,)

tconst                                         tt1182301
titleType                                          short
primaryTitle      Lieutenant Rose and the Stolen Bullion
originalTitle     Lieutenant Rose and the Stolen Bullion
isAdult                                                0
startYear                                           1913
endYear                                               \N
runtimeMinutes                                        \N
genres                                   Adventure,Short
Name: 2003934, dtype: object

(9,)

tconst            tt11823020
titleType              movie
primaryTitle           Karma
originalTitle          Karma
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003935, dtype: object

(9,)

tconst                            tt11823022
titleType                          tvEpisode
primaryTitle      Episode dated 24 June 1966
originalTitle     Episode dated 24 June 1966
isAdult                                    0
startYear                               1966
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2003936, dtype: object

(9,)

tconst                     tt11823024
titleType                   tvEpisode
primaryTitle      A Melody For Murder
originalTitle     A Melody For Murder
isAdult                             0
startYear                        1953
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2003937, dtype: object

(9,)

tconst                          tt11823026
titleType                        tvEpisode
primaryTitle      Keeper - Clueless Expert
originalTitle     Keeper - Clueless Expert
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          \N
genres                 Comedy,Drama,Sci-Fi
Name: 2003938, dtype: object

(9,)

tconst                tt11823028
titleType               tvSeries
primaryTitle      Fary: Hexagone
originalTitle     Fary: Hexagone
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2003939, dtype: object

(9,)

tconst                                            tt1182302
titleType                                             short
primaryTitle      Lights and Shadows in a City of a Million
originalTitle     Lights and Shadows in a City of a Million
isAdult                                                   0
startYear                                              1920
endYear                                                  \N
runtimeMinutes                                            7
genres                                    Documentary,Short
Name: 2003940, dtype: object

(9,)

tconst                      tt11823030
titleType                    tvEpisode
primaryTitle      The Captain Sees Red
originalTitle     The Captain Sees Red
isAdult                              0
startYear                         1953
endYear                             \N
runtimeMinutes                      \N
genres                           Drama
Name: 2003941, dtype: object

(9,)

tconst                           tt11823032
titleType                             movie
primaryTitle      FIFA Club World Cup Final
originalTitle     FIFA Club World Cup Final
isAdult                                   0
startYear                              2019
endYear                                  \N
runtimeMinutes                          133
genres                               Action
Name: 2003942, dtype: object

(9,)

tconst                             tt11823034
titleType                               short
primaryTitle          O Presidente Veste Nada
originalTitle         O Presidente Veste Nada
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres            Animation,Documentary,Short
Name: 2003943, dtype: object

(9,)

tconst                  tt11823036
titleType                tvEpisode
primaryTitle      The Faceless Man
originalTitle     The Faceless Man
isAdult                          0
startYear                     1953
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2003944, dtype: object

(9,)

tconst                                  tt11823038
titleType                                tvEpisode
primaryTitle      2019-20: Osasuna vs. Real Madrid
originalTitle     2019-20: Osasuna vs. Real Madrid
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  94
genres                                       Sport
Name: 2003945, dtype: object

(9,)

tconst                                 tt1182303
titleType                              tvSpecial
primaryTitle      Macy's Thanksgiving Day Parade
originalTitle     Macy's Thanksgiving Day Parade
isAdult                                        0
startYear                                   1989
endYear                                       \N
runtimeMinutes                                \N
genres                              Family,Music
Name: 2003946, dtype: object

(9,)

tconst                                          tt11823040
titleType                                        tvEpisode
primaryTitle      2019-20: Real Madrid vs. Atletico Madrid
originalTitle     2019-20: Real Madrid vs. Atletico Madrid
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          95
genres                                               Sport
Name: 2003947, dtype: object

(9,)

tconst                      tt11823042
titleType                    tvEpisode
primaryTitle      Crime and Punishment
originalTitle     Crime and Punishment
isAdult                              0
startYear                         1953
endYear                             \N
runtimeMinutes                      \N
genres                           Drama
Name: 2003948, dtype: object

(9,)

tconst                                          tt11823044
titleType                                        tvEpisode
primaryTitle      Top 10 Anticipated Action Movies of 2020
originalTitle     Top 10 Anticipated Action Movies of 2020
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                    Comedy,Talk-Show
Name: 2003949, dtype: object

(9,)

tconst                               tt11823046
titleType                             tvEpisode
primaryTitle      Brecht, opera och rockmusikal
originalTitle     Brecht, opera och rockmusikal
isAdult                                       0
startYear                                  1986
endYear                                      \N
runtimeMinutes                               \N
genres                          Drama,Talk-Show
Name: 2003950, dtype: object

(9,)

tconst                            tt11823048
titleType                          tvEpisode
primaryTitle               Invisible Daltons
originalTitle              Invisible Daltons
isAdult                                    0
startYear                               2010
endYear                                   \N
runtimeMinutes                            \N
genres            Adventure,Animation,Comedy
Name: 2003951, dtype: object

(9,)

tconst                          tt1182304
titleType                           video
primaryTitle      Madness: Divine Madness
originalTitle     Madness: Divine Madness
isAdult                                 0
startYear                            2002
endYear                                \N
runtimeMinutes                        103
genres                       Comedy,Music
Name: 2003952, dtype: object

(9,)

tconst                 tt11823050
titleType               tvEpisode
primaryTitle                Jagad
originalTitle               Jagad
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 45
genres            Action,Thriller
Name: 2003953, dtype: object

(9,)

tconst                 tt11823052
titleType               tvEpisode
primaryTitle             Skyldig?
originalTitle            Skyldig?
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 47
genres            Action,Thriller
Name: 2003954, dtype: object

(9,)

tconst                 tt11823054
titleType               tvEpisode
primaryTitle          Levande död
originalTitle         Levande död
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 46
genres            Action,Thriller
Name: 2003955, dtype: object

(9,)

tconst                 tt11823056
titleType               tvEpisode
primaryTitle            Liksäcken
originalTitle           Liksäcken
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 46
genres            Action,Thriller
Name: 2003956, dtype: object

(9,)

tconst                 tt11823058
titleType               tvEpisode
primaryTitle                Hatet
originalTitle               Hatet
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 46
genres            Action,Thriller
Name: 2003957, dtype: object

(9,)

tconst                    tt1182305
titleType                     short
primaryTitle      March of Progress
originalTitle     March of Progress
isAdult                           0
startYear                      1945
endYear                          \N
runtimeMinutes                   21
genres            Documentary,Short
Name: 2003958, dtype: object

(9,)

tconst                 tt11823060
titleType               tvEpisode
primaryTitle               Sveket
originalTitle              Sveket
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 46
genres            Action,Thriller
Name: 2003959, dtype: object

(9,)

tconst                  tt11823062
titleType                tvEpisode
primaryTitle      Escape Into Fear
originalTitle     Escape Into Fear
isAdult                          0
startYear                     1953
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2003960, dtype: object

(9,)

tconst                 tt11823064
titleType               tvEpisode
primaryTitle               Mexiko
originalTitle              Mexiko
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 46
genres            Action,Thriller
Name: 2003961, dtype: object

(9,)

tconst                 tt11823066
titleType               tvEpisode
primaryTitle            Drömhuset
originalTitle           Drömhuset
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 46
genres            Action,Thriller
Name: 2003962, dtype: object

(9,)

tconst                       tt11823068
titleType                     tvEpisode
primaryTitle      Vanessa Bell Calloway
originalTitle     Vanessa Bell Calloway
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2003963, dtype: object

(9,)

tconst             tt1182306
titleType              short
primaryTitle      Le masseur
originalTitle     Le masseur
isAdult                    0
startYear               1996
endYear                   \N
runtimeMinutes            10
genres                 Short
Name: 2003964, dtype: object

(9,)

tconst                       tt11823070
titleType                         short
primaryTitle      A Voice for the Ocean
originalTitle     A Voice for the Ocean
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                Documentary,Short
Name: 2003965, dtype: object

(9,)

tconst                           tt11823072
titleType                         tvEpisode
primaryTitle      And Then There Were Three
originalTitle     And Then There Were Three
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                                Drama
Name: 2003966, dtype: object

(9,)

tconst            tt11823074
titleType          tvEpisode
primaryTitle          Kurupt
originalTitle         Kurupt
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2003967, dtype: object

(9,)

tconst                                        tt11823076
titleType                                   tvMiniSeries
primaryTitle                                  Tiger King
originalTitle     Tiger King: Murder, Mayhem and Madness
isAdult                                                0
startYear                                           2020
endYear                                             2020
runtimeMinutes                                       358
genres                       Biography,Crime,Documentary
Name: 2003968, dtype: object

(9,)

tconst            tt11823078
titleType          tvEpisode
primaryTitle         Cooties
originalTitle        Cooties
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2003969, dtype: object

(9,)

tconst                      tt1182307
titleType                       short
primaryTitle      A Message for Women
originalTitle     A Message for Women
isAdult                             0
startYear                        1945
endYear                            \N
runtimeMinutes                     18
genres                          Short
Name: 2003970, dtype: object

(9,)

tconst                         tt11823080
titleType                       tvEpisode
primaryTitle      The House and the Brain
originalTitle     The House and the Brain
isAdult                                 0
startYear                            1953
endYear                                \N
runtimeMinutes                         \N
genres                              Drama
Name: 2003971, dtype: object

(9,)

tconst             tt11823082
titleType           tvEpisode
primaryTitle      Omar Miller
originalTitle     Omar Miller
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2003972, dtype: object

(9,)

tconst                      tt11823084
titleType                    tvEpisode
primaryTitle            Episode #11.25
originalTitle           Episode #11.25
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                     120
genres            News,Sport,Talk-Show
Name: 2003973, dtype: object

(9,)

tconst                              tt11823086
titleType                                movie
primaryTitle      Atletico Madrid vs Liverpool
originalTitle     Atletico Madrid vs Liverpool
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              97
genres                                  Action
Name: 2003974, dtype: object

(9,)

tconst                                         tt11823088
titleType                                        tvSeries
primaryTitle      100 Humans: Life's Questions. Answered.
originalTitle                                  100 Humans
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                         Reality-TV
Name: 2003975, dtype: object

(9,)

tconst                               tt1182308
titleType                                short
primaryTitle             Miss Glady's Vacation
originalTitle     Miss Gladeye Slip's Vacation
isAdult                                      0
startYear                                 1913
endYear                                     \N
runtimeMinutes                              \N
genres                            Comedy,Short
Name: 2003976, dtype: object

(9,)

tconst            tt11823090
titleType          tvEpisode
primaryTitle       Joe Torry
originalTitle      Joe Torry
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2003977, dtype: object

(9,)

tconst                          tt11823092
titleType                            movie
primaryTitle      Barcelona vs Real Madrid
originalTitle     Barcelona vs Real Madrid
isAdult                                  0
startYear                             2010
endYear                                 \N
runtimeMinutes                          93
genres                              Action
Name: 2003978, dtype: object

(9,)

tconst                     tt11823094
titleType                       short
primaryTitle      Let There Be Colour
originalTitle     Let There Be Colour
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     16
genres              Documentary,Short
Name: 2003979, dtype: object

(9,)

tconst                  tt11823096
titleType                tvEpisode
primaryTitle        Episode #1.854
originalTitle       Episode #1.854
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003980, dtype: object

(9,)

tconst                  tt11823098
titleType                tvEpisode
primaryTitle        Episode #1.855
originalTitle       Episode #1.855
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003981, dtype: object

(9,)

tconst                 tt1182309
titleType                  short
primaryTitle      Misty Mountain
originalTitle     Misty Mountain
isAdult                        0
startYear                   2007
endYear                       \N
runtimeMinutes                31
genres               Drama,Short
Name: 2003982, dtype: object

(9,)

tconst                  tt11823100
titleType                tvEpisode
primaryTitle        Episode #1.856
originalTitle       Episode #1.856
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003983, dtype: object

(9,)

tconst              tt11823102
titleType             tvSeries
primaryTitle      Ulven kommer
originalTitle     Ulven kommer
isAdult                      0
startYear                 2020
endYear                   2020
runtimeMinutes              59
genres             Crime,Drama
Name: 2003984, dtype: object

(9,)

tconst                        tt11823106
titleType                      tvEpisode
primaryTitle      Norén, Teater Galeasen
originalTitle     Norén, Teater Galeasen
isAdult                                0
startYear                           1987
endYear                               \N
runtimeMinutes                        \N
genres                   Drama,Talk-Show
Name: 2003985, dtype: object

(9,)

tconst                      tt11823108
titleType                    tvEpisode
primaryTitle      The Mistletow Racket
originalTitle     The Mistletow Racket
isAdult                              0
startYear                         1953
endYear                             \N
runtimeMinutes                      \N
genres                           Drama
Name: 2003986, dtype: object

(9,)

tconst                                           tt1182310
titleType                                            short
primaryTitle      Mrs. Rabbit's Husband Takes the Shilling
originalTitle     Mrs. Rabbit's Husband Takes the Shilling
isAdult                                                  0
startYear                                             1913
endYear                                                 \N
runtimeMinutes                                          \N
genres                                        Comedy,Short
Name: 2003987, dtype: object

(9,)

tconst                  tt11823110
titleType                tvEpisode
primaryTitle        Episode #1.857
originalTitle       Episode #1.857
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003988, dtype: object

(9,)

tconst             tt11823112
titleType               movie
primaryTitle      Chiaroscuro
originalTitle     Chiaroscuro
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2003989, dtype: object

(9,)

tconst                          tt11823114
titleType                        tvEpisode
primaryTitle             She!? Is an Idol!
originalTitle            She!? Is an Idol!
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2003990, dtype: object

(9,)

tconst                  tt11823118
titleType                tvEpisode
primaryTitle        Episode #1.858
originalTitle       Episode #1.858
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003991, dtype: object

(9,)

tconst             tt1182311
titleType              movie
primaryTitle      Malamuerte
originalTitle     Malamuerte
isAdult                    0
startYear               2009
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2003992, dtype: object

(9,)

tconst                  tt11823120
titleType                tvEpisode
primaryTitle        Episode #1.859
originalTitle       Episode #1.859
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003993, dtype: object

(9,)

tconst                                     tt11823122
titleType                                   tvEpisode
primaryTitle      Special Training! Tatsu the Spartan
originalTitle     Special Training! Tatsu the Spartan
isAdult                                             0
startYear                                        1983
endYear                                            \N
runtimeMinutes                                     24
genres                       Animation,Comedy,Romance
Name: 2003994, dtype: object

(9,)

tconst                  tt11823124
titleType                tvEpisode
primaryTitle        Episode #1.860
originalTitle       Episode #1.860
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003995, dtype: object

(9,)

tconst                              tt11823126
titleType                            tvEpisode
primaryTitle      Conquering Avalanche Country
originalTitle     Conquering Avalanche Country
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              42
genres                     Documentary,History
Name: 2003996, dtype: object

(9,)

tconst                  tt11823128
titleType                tvEpisode
primaryTitle        Episode #1.861
originalTitle       Episode #1.861
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2003997, dtype: object

(9,)

tconst                    tt1182312
titleType                     short
primaryTitle      Un mundo numérico
originalTitle     Un mundo numérico
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   14
genres                        Short
Name: 2003998, dtype: object

(9,)

tconst                          tt11823130
titleType                        tvEpisode
primaryTitle      It's Out!? Someone Saw!?
originalTitle     It's Out!? Someone Saw!?
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2003999, dtype: object

(9,)

tconst                  tt11823132
titleType                tvEpisode
primaryTitle        Episode #1.862
originalTitle       Episode #1.862
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004000, dtype: object

(9,)

tconst                          tt11823134
titleType                            movie
primaryTitle      The Temptation of Gracie
originalTitle     The Temptation of Gracie
isAdult                                  0
startYear                               \N
endYear                                 \N
runtimeMinutes                          \N
genres                               Drama
Name: 2004001, dtype: object

(9,)

tconst                tt11823136
titleType              tvEpisode
primaryTitle      Black vs White
originalTitle     Black vs White
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                27
genres                     Drama
Name: 2004002, dtype: object

(9,)

tconst                          tt11823138
titleType                        tvEpisode
primaryTitle                 Ringside Love
originalTitle                Ringside Love
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004003, dtype: object

(9,)

tconst                    tt1182313
titleType                     video
primaryTitle         Musical Scales
originalTitle        Musical Scales
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   14
genres            Documentary,Short
Name: 2004004, dtype: object

(9,)

tconst                       tt11823140
titleType                     tvEpisode
primaryTitle      The Last Man on Earth
originalTitle     The Last Man on Earth
isAdult                               0
startYear                          1953
endYear                              \N
runtimeMinutes                       \N
genres                            Drama
Name: 2004005, dtype: object

(9,)

tconst                  tt11823142
titleType                tvEpisode
primaryTitle        Episode #1.863
originalTitle       Episode #1.863
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004006, dtype: object

(9,)

tconst                                        tt11823144
titleType                                      tvEpisode
primaryTitle      A Broken Heart Tastes Like Natsumikan?
originalTitle     A Broken Heart Tastes Like Natsumikan?
isAdult                                                0
startYear                                           1983
endYear                                               \N
runtimeMinutes                                        24
genres                          Animation,Comedy,Romance
Name: 2004007, dtype: object

(9,)

tconst                        tt11823146
titleType                          short
primaryTitle      Jamaika Onto New Paths
originalTitle     Jamaika Onto New Paths
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                        14
genres                 Documentary,Short
Name: 2004008, dtype: object

(9,)

tconst                  tt11823148
titleType                tvEpisode
primaryTitle        Episode #1.864
originalTitle       Episode #1.864
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004009, dtype: object

(9,)

tconst                           tt1182314
titleType                        tvSpecial
primaryTitle      NY Giants Victory Parade
originalTitle     NY Giants Victory Parade
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          90
genres                                News
Name: 2004010, dtype: object

(9,)

tconst                          tt11823150
titleType                        tvEpisode
primaryTitle        Ahh!! Romeo and Juliet
originalTitle       Ahh!! Romeo and Juliet
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004011, dtype: object

(9,)

tconst                  tt11823152
titleType                tvEpisode
primaryTitle        Episode #1.865
originalTitle       Episode #1.865
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004012, dtype: object

(9,)

tconst                tt11823154
titleType              tvEpisode
primaryTitle       Episode #2.39
originalTitle      Episode #2.39
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2004013, dtype: object

(9,)

tconst              tt11823156
titleType            tvEpisode
primaryTitle      The number 1
originalTitle     The number 1
isAdult                      0
startYear                 2016
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004014, dtype: object

(9,)

tconst                  tt11823158
titleType                tvEpisode
primaryTitle        Episode #1.866
originalTitle       Episode #1.866
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004015, dtype: object

(9,)

tconst                     tt1182315
titleType                      movie
primaryTitle       Dark Buenos Aires
originalTitle     Negro Buenos Aires
isAdult                            0
startYear                       2010
endYear                           \N
runtimeMinutes                    90
genres                      Thriller
Name: 2004016, dtype: object

(9,)

tconst                                       tt11823160
titleType                                     tvEpisode
primaryTitle      Blow, Wind! Kotatsu's Counterattack!!
originalTitle     Blow, Wind! Kotatsu's Counterattack!!
isAdult                                               0
startYear                                          1983
endYear                                              \N
runtimeMinutes                                       24
genres                         Animation,Comedy,Romance
Name: 2004017, dtype: object

(9,)

tconst                  tt11823162
titleType                tvEpisode
primaryTitle        Episode #1.867
originalTitle       Episode #1.867
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004018, dtype: object

(9,)

tconst                          tt11823164
titleType                        tvEpisode
primaryTitle          Substitute Date Plan
originalTitle         Substitute Date Plan
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004019, dtype: object

(9,)

tconst                  tt11823166
titleType                tvEpisode
primaryTitle        Episode #1.868
originalTitle       Episode #1.868
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004020, dtype: object

(9,)

tconst                          tt11823168
titleType                        tvEpisode
primaryTitle            Suzume's Boyfriend
originalTitle           Suzume's Boyfriend
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004021, dtype: object

(9,)

tconst                                                    tt1182316
titleType                                                     short
primaryTitle      Panorama de l'arrivée en gare de Perrache pris...
originalTitle     Panorama de l'arrivée en gare de Perrache pris...
isAdult                                                           0
startYear                                                      1896
endYear                                                          \N
runtimeMinutes                                                    1
genres                                            Documentary,Short
Name: 2004022, dtype: object

(9,)

tconst                  tt11823170
titleType                tvEpisode
primaryTitle        Episode #1.869
originalTitle       Episode #1.869
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004023, dtype: object

(9,)

tconst                  tt11823172
titleType                tvEpisode
primaryTitle        Episode #1.870
originalTitle       Episode #1.870
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004024, dtype: object

(9,)

tconst              tt11823174
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              91
genres               Talk-Show
Name: 2004025, dtype: object

(9,)

tconst                      tt11823176
titleType                    tvEpisode
primaryTitle      The Ghost of Macbeth
originalTitle     The Ghost of Macbeth
isAdult                              0
startYear                         1954
endYear                             \N
runtimeMinutes                      \N
genres                           Drama
Name: 2004026, dtype: object

(9,)

tconst                                   tt11823178
titleType                                 tvEpisode
primaryTitle      Anita Cordell and Sharonne Lanier
originalTitle     Anita Cordell and Sharonne Lanier
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                    Talk-Show
Name: 2004027, dtype: object

(9,)

tconst                                         tt1182317
titleType                                          video
primaryTitle      Pass It On: The History Boys on Screen
originalTitle     Pass It On: The History Boys on Screen
isAdult                                                0
startYear                                           2007
endYear                                               \N
runtimeMinutes                                        13
genres                                 Documentary,Short
Name: 2004028, dtype: object

(9,)

tconst                          tt11823180
titleType                        tvEpisode
primaryTitle      The ABCs of Love Lessons
originalTitle     The ABCs of Love Lessons
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004029, dtype: object

(9,)

tconst                  tt11823182
titleType                tvEpisode
primaryTitle        Episode #1.871
originalTitle       Episode #1.871
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004030, dtype: object

(9,)

tconst                  tt11823184
titleType                tvEpisode
primaryTitle        Episode #1.872
originalTitle       Episode #1.872
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004031, dtype: object

(9,)

tconst                          tt11823186
titleType                        tvEpisode
primaryTitle           Panic on the Shore!
originalTitle          Panic on the Shore!
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004032, dtype: object

(9,)

tconst                  tt11823188
titleType                tvEpisode
primaryTitle        Episode #1.873
originalTitle       Episode #1.873
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004033, dtype: object

(9,)

tconst                tt1182318
titleType                 short
primaryTitle      La pièce d'or
originalTitle     La pièce d'or
isAdult                       0
startYear                  1964
endYear                      \N
runtimeMinutes               18
genres                    Short
Name: 2004034, dtype: object

(9,)

tconst                          tt11823190
titleType                         tvSeries
primaryTitle      Voice of the Artist Live
originalTitle     Voice of the Artist Live
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                           Talk-Show
Name: 2004035, dtype: object

(9,)

tconst                             tt11823192
titleType                           tvEpisode
primaryTitle      Youth Is a Test of Courage!
originalTitle     Youth Is a Test of Courage!
isAdult                                     0
startYear                                1983
endYear                                    \N
runtimeMinutes                             24
genres               Animation,Comedy,Romance
Name: 2004036, dtype: object

(9,)

tconst                                               tt11823194
titleType                                             tvEpisode
primaryTitle      Top 10 Most Anticipated Horror Movies of 2020
originalTitle     Top 10 Most Anticipated Horror Movies of 2020
isAdult                                                       0
startYear                                                  2019
endYear                                                      \N
runtimeMinutes                                               \N
genres                                         Comedy,Talk-Show
Name: 2004037, dtype: object

(9,)

tconst                          tt11823196
titleType                        tvEpisode
primaryTitle       Hibari Goes for Broke!!
originalTitle      Hibari Goes for Broke!!
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004038, dtype: object

(9,)

tconst             tt11823198
titleType           tvEpisode
primaryTitle      Bobby Brown
originalTitle     Bobby Brown
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2004039, dtype: object

(9,)

tconst                    tt1182319
titleType                     short
primaryTitle          Place du Pont
originalTitle         Place du Pont
isAdult                           0
startYear                      1897
endYear                          \N
runtimeMinutes                    1
genres            Documentary,Short
Name: 2004040, dtype: object

(9,)

tconst                          tt11823200
titleType                        tvEpisode
primaryTitle        Exciting Love Triangle
originalTitle       Exciting Love Triangle
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004041, dtype: object

(9,)

tconst                       tt11823202
titleType                     tvEpisode
primaryTitle      Go Way From My Window
originalTitle     Go Way From My Window
isAdult                               0
startYear                          1954
endYear                              \N
runtimeMinutes                       \N
genres                            Drama
Name: 2004042, dtype: object

(9,)

tconst                                          tt11823204
titleType                                            movie
primaryTitle      The Empowerment of Elizabeth Jane Newson
originalTitle     The Empowerment of Elizabeth Jane Newson
isAdult                                                  0
startYear                                               \N
endYear                                                 \N
runtimeMinutes                                          \N
genres                                               Drama
Name: 2004043, dtype: object

(9,)

tconst                          tt11823206
titleType                        tvEpisode
primaryTitle       Seiji-san's Intense Day
originalTitle      Seiji-san's Intense Day
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004044, dtype: object

(9,)

tconst                             tt11823208
titleType                             tvMovie
primaryTitle      Chokotto Kyoto ni Sundemita
originalTitle     Chokotto Kyoto ni Sundemita
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             74
genres                                  Drama
Name: 2004045, dtype: object

(9,)

tconst                                    tt1182320
titleType                                   tvMovie
primaryTitle      Das Protokoll; Halali; Die Glocke
originalTitle     Das Protokoll; Halali; Die Glocke
isAdult                                           0
startYear                                      1970
endYear                                          \N
runtimeMinutes                                   65
genres                                        Crime
Name: 2004046, dtype: object

(9,)

tconst            tt11823210
titleType          tvEpisode
primaryTitle      Kyla Pratt
originalTitle     Kyla Pratt
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2004047, dtype: object

(9,)

tconst                          tt11823212
titleType                        tvEpisode
primaryTitle        Tsugumi's Second Love!
originalTitle       Tsugumi's Second Love!
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004048, dtype: object

(9,)

tconst                               tt11823214
titleType                             tvEpisode
primaryTitle      Dad's (Hidden) Romance Album!
originalTitle     Dad's (Hidden) Romance Album!
isAdult                                       0
startYear                                  1983
endYear                                      \N
runtimeMinutes                               24
genres                 Animation,Comedy,Romance
Name: 2004049, dtype: object

(9,)

tconst                          tt11823216
titleType                        tvEpisode
primaryTitle       Flirt! Lovey-dovey Love
originalTitle      Flirt! Lovey-dovey Love
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004050, dtype: object

(9,)

tconst            tt11823218
titleType          tvEpisode
primaryTitle       Erica Ash
originalTitle      Erica Ash
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2004051, dtype: object

(9,)

tconst                              tt1182321
titleType                             tvMovie
primaryTitle                Randale und Liebe
originalTitle               Randale und Liebe
isAdult                                     0
startYear                                1981
endYear                                    \N
runtimeMinutes                             62
genres            Biography,Documentary,Music
Name: 2004052, dtype: object

(9,)

tconst            tt11823220
titleType          tvEpisode
primaryTitle        Talkdown
originalTitle       Talkdown
isAdult                    0
startYear               1954
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2004053, dtype: object

(9,)

tconst                 tt11823222
titleType               tvEpisode
primaryTitle      Episode #15.156
originalTitle     Episode #15.156
isAdult                         0
startYear                    1999
endYear                        \N
runtimeMinutes                 \N
genres                         \N
Name: 2004054, dtype: object

(9,)

tconst            tt11823224
titleType          tvEpisode
primaryTitle      The winner
originalTitle     The winner
isAdult                    0
startYear               2016
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2004055, dtype: object

(9,)

tconst                 tt11823226
titleType               tvEpisode
primaryTitle      Episode #15.157
originalTitle     Episode #15.157
isAdult                         0
startYear                    1999
endYear                        \N
runtimeMinutes                 \N
genres                         \N
Name: 2004056, dtype: object

(9,)

tconst                  tt11823228
titleType                tvEpisode
primaryTitle      John Witherspoon
originalTitle     John Witherspoon
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2004057, dtype: object

(9,)

tconst                                             tt1182322
titleType                                            tvMovie
primaryTitle          The Oligarchs: The Struggle for Russia
originalTitle     The Rise and Fall of the Russian Oligarchs
isAdult                                                    0
startYear                                               2006
endYear                                                   \N
runtimeMinutes                                            83
genres                                           Documentary
Name: 2004058, dtype: object

(9,)

tconst                          tt11823230
titleType                        tvEpisode
primaryTitle        Look the Mafia's Bride
originalTitle       Look the Mafia's Bride
isAdult                                  0
startYear                             1983
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Comedy,Romance
Name: 2004059, dtype: object

(9,)

tconst                            tt11823232
titleType                          tvEpisode
primaryTitle      How Do You Do!? House Call
originalTitle     How Do You Do!? House Call
isAdult                                    0
startYear                               1983
endYear                                   \N
runtimeMinutes                            24
genres              Animation,Comedy,Romance
Name: 2004060, dtype: object

(9,)

tconst                                   tt11823234
titleType                                 tvEpisode
primaryTitle      Women's Wrestling! Rie vs. Hibari
originalTitle     Women's Wrestling! Rie vs. Hibari
isAdult                                           0
startYear                                      1983
endYear                                          \N
runtimeMinutes                                   24
genres                     Animation,Comedy,Romance
Name: 2004061, dtype: object

(9,)

tconst                           tt11823236
titleType                         tvEpisode
primaryTitle      Lovely! School Takarazuka
originalTitle     Lovely! School Takarazuka
isAdult                                   0
startYear                              1983
endYear                                  \N
runtimeMinutes                           24
genres             Animation,Comedy,Romance
Name: 2004062, dtype: object

(9,)

tconst                                                tt11823238
titleType                                              tvEpisode
primaryTitle      Opening Today! The Story of Detective Kurikara
originalTitle     Opening Today! The Story of Detective Kurikara
isAdult                                                        0
startYear                                                   1983
endYear                                                       \N
runtimeMinutes                                                24
genres                                  Animation,Comedy,Romance
Name: 2004063, dtype: object

(9,)

tconst                  tt1182323
titleType                 tvMovie
primaryTitle         The Sea Wolf
originalTitle         Der Seewolf
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                179
genres            Adventure,Drama
Name: 2004064, dtype: object

(9,)

tconst                                                   tt11823240
titleType                                                 tvEpisode
primaryTitle      Frightening!! The Strange Event on the Souther...
originalTitle     Frightening!! The Strange Event on the Souther...
isAdult                                                           0
startYear                                                      1983
endYear                                                          \N
runtimeMinutes                                                   24
genres                                     Animation,Comedy,Romance
Name: 2004065, dtype: object

(9,)

tconst                                       tt11823244
titleType                                     tvEpisode
primaryTitle      Love Under the Shade of a Palm Tree!!
originalTitle     Love Under the Shade of a Palm Tree!!
isAdult                                               0
startYear                                          1983
endYear                                              \N
runtimeMinutes                                       24
genres                         Animation,Comedy,Romance
Name: 2004066, dtype: object

(9,)

tconst              tt11823246
titleType            tvEpisode
primaryTitle            Tanzen
originalTitle           Tanzen
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2004067, dtype: object

(9,)

tconst                                               tt11823248
titleType                                             tvEpisode
primaryTitle      Festivals Are Scary! Baseball Is Also Scary!!
originalTitle     Festivals Are Scary! Baseball Is Also Scary!!
isAdult                                                       0
startYear                                                  1983
endYear                                                      \N
runtimeMinutes                                               24
genres                                 Animation,Comedy,Romance
Name: 2004068, dtype: object

(9,)

tconst                    tt1182324
titleType                     movie
primaryTitle      So Happy Together
originalTitle     So Happy Together
isAdult                           0
startYear                      1967
endYear                          \N
runtimeMinutes                   \N
genres              Musical,Romance
Name: 2004069, dtype: object

(9,)

tconst                           tt11823250
titleType                         tvEpisode
primaryTitle      Ibari's Pure Love Curve!?
originalTitle     Ibari's Pure Love Curve!?
isAdult                                   0
startYear                              1983
endYear                                  \N
runtimeMinutes                           24
genres             Animation,Comedy,Romance
Name: 2004070, dtype: object

(9,)

tconst                tt11823252
titleType              tvEpisode
primaryTitle      Episode #1.278
originalTitle     Episode #1.278
isAdult                        0
startYear                   2003
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2004071, dtype: object

(9,)

tconst                           tt11823254
titleType                         tvEpisode
primaryTitle      The Bad Kid Gang Is Here!
originalTitle     The Bad Kid Gang Is Here!
isAdult                                   0
startYear                              1983
endYear                                  \N
runtimeMinutes                           24
genres             Animation,Comedy,Romance
Name: 2004072, dtype: object

(9,)

tconst                    tt11823256
titleType                  tvEpisode
primaryTitle      Only Crypto: Day 2
originalTitle     Only Crypto: Day 2
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2004073, dtype: object

(9,)

tconst                tt11823258
titleType                  movie
primaryTitle      Maiden No More
originalTitle     Maiden No More
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004074, dtype: object

(9,)

tconst                                        tt1182325
titleType                                         movie
primaryTitle      Die starke Susi - Boxen zum Überleben
originalTitle     Die starke Susi - Boxen zum Überleben
isAdult                                               0
startYear                                          2007
endYear                                              \N
runtimeMinutes                                       45
genres                      Biography,Documentary,Sport
Name: 2004075, dtype: object

(9,)

tconst                                         tt11823260
titleType                                       tvEpisode
primaryTitle      Exactly Like Hiroko! The Love Bomb Girl
originalTitle     Exactly Like Hiroko! The Love Bomb Girl
isAdult                                                 0
startYear                                            1983
endYear                                                \N
runtimeMinutes                                         24
genres                           Animation,Comedy,Romance
Name: 2004076, dtype: object

(9,)

tconst             tt11823262
titleType           tvEpisode
primaryTitle            Pilot
originalTitle           Pilot
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2004077, dtype: object

(9,)

tconst                                     tt11823264
titleType                                   tvEpisode
primaryTitle      Watch Out for the Mouse Kid Thief!!
originalTitle     Watch Out for the Mouse Kid Thief!!
isAdult                                             0
startYear                                        1983
endYear                                            \N
runtimeMinutes                                     24
genres                       Animation,Comedy,Romance
Name: 2004078, dtype: object

(9,)

tconst                                       tt11823266
titleType                                     tvEpisode
primaryTitle      Invite Everyone to a Merry Birthday!!
originalTitle     Invite Everyone to a Merry Birthday!!
isAdult                                               0
startYear                                          1983
endYear                                              \N
runtimeMinutes                                       24
genres                         Animation,Comedy,Romance
Name: 2004079, dtype: object

(9,)

tconst                   tt11823268
titleType                 tvEpisode
primaryTitle      Striker's therapy
originalTitle     Striker's therapy
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2004080, dtype: object

(9,)

tconst                                 tt1182326
titleType                                  video
primaryTitle      They Came from Beneath the Sea
originalTitle     They Came from Beneath the Sea
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                13
genres                         Documentary,Short
Name: 2004081, dtype: object

(9,)

tconst                                                   tt11823270
titleType                                                 tvEpisode
primaryTitle      Fairy SF!? The Pillow's Genji Hibari Picture S...
originalTitle     Fairy SF!? The Pillow's Genji Hibari Picture S...
isAdult                                                           0
startYear                                                      1984
endYear                                                          \N
runtimeMinutes                                                   24
genres                                     Animation,Comedy,Romance
Name: 2004082, dtype: object

(9,)

tconst                      tt11823272
titleType                    tvEpisode
primaryTitle      The Invisible Island
originalTitle     The Invisible Island
isAdult                              0
startYear                         1954
endYear                             \N
runtimeMinutes                      \N
genres                           Drama
Name: 2004083, dtype: object

(9,)

tconst                                                   tt11823274
titleType                                                 tvEpisode
primaryTitle      Pandemonium!! Hibari is Kousaku, Kousaku is Hi...
originalTitle     Pandemonium!! Hibari is Kousaku, Kousaku is Hi...
isAdult                                                           0
startYear                                                      1984
endYear                                                          \N
runtimeMinutes                                                   24
genres                                     Animation,Comedy,Romance
Name: 2004084, dtype: object

(9,)

tconst                    tt11823276
titleType                  tvEpisode
primaryTitle           Episode #13.2
originalTitle          Episode #13.2
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004085, dtype: object

(9,)

tconst                            tt11823278
titleType                          tvEpisode
primaryTitle      Ahem! Shouwa's Okita-kun!!
originalTitle     Ahem! Shouwa's Okita-kun!!
isAdult                                    0
startYear                               1984
endYear                                   \N
runtimeMinutes                            24
genres              Animation,Comedy,Romance
Name: 2004086, dtype: object

(9,)

tconst                         tt1182327
titleType                          video
primaryTitle      Tindersticks: Bareback
originalTitle     Tindersticks: Bareback
isAdult                                0
startYear                           2005
endYear                               \N
runtimeMinutes                        45
genres                             Music
Name: 2004087, dtype: object

(9,)

tconst                    tt11823280
titleType                  tvEpisode
primaryTitle           Episode #13.3
originalTitle          Episode #13.3
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004088, dtype: object

(9,)

tconst                    tt11823282
titleType                  tvEpisode
primaryTitle           Episode #13.4
originalTitle          Episode #13.4
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004089, dtype: object

(9,)

tconst               tt11823284
titleType             tvEpisode
primaryTitle      Episode #2.31
originalTitle     Episode #2.31
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2004090, dtype: object

(9,)

tconst                    tt11823286
titleType                  tvEpisode
primaryTitle           Episode #13.6
originalTitle          Episode #13.6
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004091, dtype: object

(9,)

tconst                                         tt11823288
titleType                                       tvEpisode
primaryTitle      Superhuman Hibari?! Leap Through Time!!
originalTitle     Superhuman Hibari?! Leap Through Time!!
isAdult                                                 0
startYear                                            1984
endYear                                                \N
runtimeMinutes                                         24
genres                           Animation,Comedy,Romance
Name: 2004092, dtype: object

(9,)

tconst                                                   tt1182328
titleType                                                    video
primaryTitle      Tocotronic produzieren Album Nr. 8: Kapitulation
originalTitle     Tocotronic produzieren Album Nr. 8: Kapitulation
isAdult                                                          0
startYear                                                     2007
endYear                                                         \N
runtimeMinutes                                                  20
genres                                     Documentary,Music,Short
Name: 2004093, dtype: object

(9,)

tconst                    tt11823290
titleType                  tvEpisode
primaryTitle           Episode #13.5
originalTitle          Episode #13.5
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004094, dtype: object

(9,)

tconst                    tt11823292
titleType                  tvEpisode
primaryTitle           Episode #13.7
originalTitle          Episode #13.7
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004095, dtype: object

(9,)

tconst              tt11823294
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004096, dtype: object

(9,)

tconst                    tt11823296
titleType                  tvEpisode
primaryTitle           Episode #13.8
originalTitle          Episode #13.8
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004097, dtype: object

(9,)

tconst              tt11823298
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004098, dtype: object

(9,)

tconst                             tt1182329
titleType                          tvSpecial
primaryTitle              Tränen lügen nicht
originalTitle             Tränen lügen nicht
isAdult                                    0
startYear                               1999
endYear                                   \N
runtimeMinutes                            \N
genres            Comedy,Documentary,History
Name: 2004099, dtype: object

(9,)

tconst                    tt11823300
titleType                  tvEpisode
primaryTitle           Episode #13.9
originalTitle          Episode #13.9
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004100, dtype: object

(9,)

tconst                    tt11823302
titleType                  tvEpisode
primaryTitle          Episode #13.12
originalTitle         Episode #13.12
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004101, dtype: object

(9,)

tconst                    tt11823304
titleType                  tvEpisode
primaryTitle          Episode #13.10
originalTitle         Episode #13.10
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004102, dtype: object

(9,)

tconst                    tt11823308
titleType                  tvEpisode
primaryTitle          Episode #13.13
originalTitle         Episode #13.13
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004103, dtype: object

(9,)

tconst                                      tt1182330
titleType                                       video
primaryTitle      Die tödliche Doris: Gehörlose Musik
originalTitle     Die tödliche Doris: Gehörlose Musik
isAdult                                             0
startYear                                        2006
endYear                                            \N
runtimeMinutes                                     40
genres                                    Music,Short
Name: 2004104, dtype: object

(9,)

tconst                    tt11823310
titleType                  tvEpisode
primaryTitle          Episode #13.11
originalTitle         Episode #13.11
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004105, dtype: object

(9,)

tconst              tt11823312
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004106, dtype: object

(9,)

tconst              tt11823314
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004107, dtype: object

(9,)

tconst                    tt11823316
titleType                  tvEpisode
primaryTitle          Episode #13.15
originalTitle         Episode #13.15
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004108, dtype: object

(9,)

tconst                    tt11823318
titleType                  tvEpisode
primaryTitle          Episode #13.16
originalTitle         Episode #13.16
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004109, dtype: object

(9,)

tconst                         tt1182331
titleType                      tvSpecial
primaryTitle      UFC 81: Breaking Point
originalTitle     UFC 81: Breaking Point
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                       180
genres                             Sport
Name: 2004110, dtype: object

(9,)

tconst                    tt11823320
titleType                  tvEpisode
primaryTitle          Episode #13.14
originalTitle         Episode #13.14
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004111, dtype: object

(9,)

tconst                    tt11823322
titleType                  tvEpisode
primaryTitle          Episode #13.19
originalTitle         Episode #13.19
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004112, dtype: object

(9,)

tconst                    tt11823324
titleType                  tvEpisode
primaryTitle          Episode #13.17
originalTitle         Episode #13.17
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004113, dtype: object

(9,)

tconst                    tt11823326
titleType                  tvEpisode
primaryTitle          Episode #13.18
originalTitle         Episode #13.18
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004114, dtype: object

(9,)

tconst              tt11823328
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004115, dtype: object

(9,)

tconst                                tt1182332
titleType                             tvSpecial
primaryTitle      Ultimate Bedrooms for Romance
originalTitle     Ultimate Bedrooms for Romance
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                               Reality-TV
Name: 2004116, dtype: object

(9,)

tconst                    tt11823330
titleType                  tvEpisode
primaryTitle          Episode #13.20
originalTitle         Episode #13.20
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004117, dtype: object

(9,)

tconst                    tt11823332
titleType                  tvEpisode
primaryTitle          Episode #13.22
originalTitle         Episode #13.22
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004118, dtype: object

(9,)

tconst                    tt11823334
titleType                  tvEpisode
primaryTitle          Episode #13.21
originalTitle         Episode #13.21
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004119, dtype: object

(9,)

tconst                    tt11823336
titleType                  tvEpisode
primaryTitle          Episode #13.23
originalTitle         Episode #13.23
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004120, dtype: object

(9,)

tconst              tt11823338
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004121, dtype: object

(9,)

tconst                    tt1182333
titleType                     movie
primaryTitle      Walang pagkalupig
originalTitle     Walang pagkalupig
isAdult                           0
startYear                      1962
endYear                          \N
runtimeMinutes                   \N
genres                   Action,War
Name: 2004122, dtype: object

(9,)

tconst                    tt11823340
titleType                  tvEpisode
primaryTitle          Episode #13.24
originalTitle         Episode #13.24
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004123, dtype: object

(9,)

tconst                    tt11823342
titleType                  tvEpisode
primaryTitle          Episode #13.25
originalTitle         Episode #13.25
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004124, dtype: object

(9,)

tconst                    tt11823344
titleType                  tvEpisode
primaryTitle          Episode #13.27
originalTitle         Episode #13.27
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004125, dtype: object

(9,)

tconst                    tt11823346
titleType                  tvEpisode
primaryTitle          Episode #13.26
originalTitle         Episode #13.26
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004126, dtype: object

(9,)

tconst              tt11823348
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004127, dtype: object

(9,)

tconst                    tt1182334
titleType                     video
primaryTitle      What Lies Beneath
originalTitle     What Lies Beneath
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   36
genres            Documentary,Short
Name: 2004128, dtype: object

(9,)

tconst                    tt11823350
titleType                  tvEpisode
primaryTitle          Episode #13.29
originalTitle         Episode #13.29
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004129, dtype: object

(9,)

tconst                  tt11823352
titleType                tvEpisode
primaryTitle      A jewish athlete
originalTitle     A jewish athlete
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2004130, dtype: object

(9,)

tconst                    tt11823354
titleType                  tvEpisode
primaryTitle          Episode #13.28
originalTitle         Episode #13.28
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004131, dtype: object

(9,)

tconst                    tt11823356
titleType                  tvEpisode
primaryTitle          Episode #13.31
originalTitle         Episode #13.31
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004132, dtype: object

(9,)

tconst                    tt11823358
titleType                  tvEpisode
primaryTitle          Episode #13.30
originalTitle         Episode #13.30
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004133, dtype: object

(9,)

tconst                         tt1182335
titleType                      tvEpisode
primaryTitle      Who Kidnapped Shergar?
originalTitle     Who Kidnapped Shergar?
isAdult                                0
startYear                           2004
endYear                               \N
runtimeMinutes                        \N
genres               Documentary,History
Name: 2004134, dtype: object

(9,)

tconst                    tt11823360
titleType                  tvEpisode
primaryTitle          Episode #13.33
originalTitle         Episode #13.33
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004135, dtype: object

(9,)

tconst                    tt11823362
titleType                  tvEpisode
primaryTitle          Episode #13.32
originalTitle         Episode #13.32
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004136, dtype: object

(9,)

tconst                tt11823364
titleType              tvEpisode
primaryTitle      Episode #1.123
originalTitle     Episode #1.123
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2004137, dtype: object

(9,)

tconst              tt11823366
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004138, dtype: object

(9,)

tconst                    tt11823368
titleType                  tvEpisode
primaryTitle          Episode #13.36
originalTitle         Episode #13.36
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004139, dtype: object

(9,)

tconst                                        tt1182336
titleType                                     tvSpecial
primaryTitle      XI premios Max de las artes escénicas
originalTitle     XI premios Max de las artes escénicas
isAdult                                               0
startYear                                          2008
endYear                                              \N
runtimeMinutes                                       \N
genres                                               \N
Name: 2004140, dtype: object

(9,)

tconst                    tt11823370
titleType                  tvEpisode
primaryTitle          Episode #13.34
originalTitle         Episode #13.34
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004141, dtype: object

(9,)

tconst                    tt11823372
titleType                  tvEpisode
primaryTitle          Episode #13.35
originalTitle         Episode #13.35
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004142, dtype: object

(9,)

tconst              tt11823374
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004143, dtype: object

(9,)

tconst                    tt11823376
titleType                  tvEpisode
primaryTitle          Episode #13.38
originalTitle         Episode #13.38
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004144, dtype: object

(9,)

tconst                    tt11823378
titleType                  tvEpisode
primaryTitle          Episode #13.40
originalTitle         Episode #13.40
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004145, dtype: object

(9,)

tconst            tt1182337
titleType             movie
primaryTitle      Yesterday
originalTitle     Yesterday
isAdult                   0
startYear              1967
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2004146, dtype: object

(9,)

tconst                    tt11823380
titleType                  tvEpisode
primaryTitle          Episode #13.37
originalTitle         Episode #13.37
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004147, dtype: object

(9,)

tconst                    tt11823382
titleType                  tvEpisode
primaryTitle          Episode #13.39
originalTitle         Episode #13.39
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004148, dtype: object

(9,)

tconst                    tt11823384
titleType                  tvEpisode
primaryTitle          Episode #13.41
originalTitle         Episode #13.41
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004149, dtype: object

(9,)

tconst                    tt11823386
titleType                  tvEpisode
primaryTitle          Episode #13.42
originalTitle         Episode #13.42
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004150, dtype: object

(9,)

tconst                    tt11823388
titleType                  tvEpisode
primaryTitle          Episode #13.43
originalTitle         Episode #13.43
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004151, dtype: object

(9,)

tconst                                  tt1182338
titleType                                 tvMovie
primaryTitle      El último golpe de Tony Soprano
originalTitle     El último golpe de Tony Soprano
isAdult                                         0
startYear                                    2008
endYear                                        \N
runtimeMinutes                                 \N
genres                                Documentary
Name: 2004152, dtype: object

(9,)

tconst            tt11823390
titleType          tvEpisode
primaryTitle         For You
originalTitle        For You
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2004153, dtype: object

(9,)

tconst                    tt11823392
titleType                  tvEpisode
primaryTitle          Episode #13.44
originalTitle         Episode #13.44
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004154, dtype: object

(9,)

tconst                    tt11823394
titleType                  tvEpisode
primaryTitle          Episode #13.46
originalTitle         Episode #13.46
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004155, dtype: object

(9,)

tconst                    tt11823396
titleType                  tvEpisode
primaryTitle          Episode #13.45
originalTitle         Episode #13.45
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004156, dtype: object

(9,)

tconst                    tt11823398
titleType                  tvEpisode
primaryTitle          Episode #13.47
originalTitle         Episode #13.47
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004157, dtype: object

(9,)

tconst               tt1182339
titleType                video
primaryTitle      Black Out #6
originalTitle     Black Out #6
isAdult                      1
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2004158, dtype: object

(9,)

tconst                    tt11823400
titleType                  tvEpisode
primaryTitle          Episode #13.49
originalTitle         Episode #13.49
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004159, dtype: object

(9,)

tconst                    tt11823402
titleType                  tvEpisode
primaryTitle          Episode #13.51
originalTitle         Episode #13.51
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004160, dtype: object

(9,)

tconst                    tt11823404
titleType                  tvEpisode
primaryTitle          Episode #13.48
originalTitle         Episode #13.48
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004161, dtype: object

(9,)

tconst                    tt11823406
titleType                  tvEpisode
primaryTitle          Episode #13.50
originalTitle         Episode #13.50
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004162, dtype: object

(9,)

tconst                    tt11823408
titleType                  tvEpisode
primaryTitle          Episode #13.52
originalTitle         Episode #13.52
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004163, dtype: object

(9,)

tconst                                           tt1182340
titleType                                            video
primaryTitle      The Curse of Lizzie Borden 2: Prom Night
originalTitle     The Curse of Lizzie Borden 2: Prom Night
isAdult                                                  0
startYear                                             2008
endYear                                                 \N
runtimeMinutes                                          95
genres                                              Horror
Name: 2004164, dtype: object

(9,)

tconst            tt11823410
titleType          tvEpisode
primaryTitle        Adulting
originalTitle       Adulting
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2004165, dtype: object

(9,)

tconst                    tt11823412
titleType                  tvEpisode
primaryTitle          Episode #13.53
originalTitle         Episode #13.53
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004166, dtype: object

(9,)

tconst                    tt11823414
titleType                  tvEpisode
primaryTitle          Episode #13.55
originalTitle         Episode #13.55
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004167, dtype: object

(9,)

tconst                    tt11823416
titleType                  tvEpisode
primaryTitle          Episode #13.54
originalTitle         Episode #13.54
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004168, dtype: object

(9,)

tconst                    tt11823418
titleType                  tvEpisode
primaryTitle          Episode #13.58
originalTitle         Episode #13.58
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004169, dtype: object

(9,)

tconst                    tt11823420
titleType                  tvEpisode
primaryTitle          Episode #13.57
originalTitle         Episode #13.57
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004170, dtype: object

(9,)

tconst                    tt11823422
titleType                  tvEpisode
primaryTitle          Episode #13.56
originalTitle         Episode #13.56
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004171, dtype: object

(9,)

tconst                    tt11823424
titleType                  tvEpisode
primaryTitle          Episode #13.60
originalTitle         Episode #13.60
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004172, dtype: object

(9,)

tconst                    tt11823426
titleType                  tvEpisode
primaryTitle          Episode #13.59
originalTitle         Episode #13.59
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004173, dtype: object

(9,)

tconst                    tt11823428
titleType                  tvEpisode
primaryTitle          Episode #13.63
originalTitle         Episode #13.63
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004174, dtype: object

(9,)

tconst                            tt1182342
titleType                         videoGame
primaryTitle      Major League Baseball 2K8
originalTitle     Major League Baseball 2K8
isAdult                                   0
startYear                              2008
endYear                                  \N
runtimeMinutes                           \N
genres                                Sport
Name: 2004175, dtype: object

(9,)

tconst                    tt11823430
titleType                  tvEpisode
primaryTitle          Episode #13.62
originalTitle         Episode #13.62
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004176, dtype: object

(9,)

tconst                    tt11823432
titleType                  tvEpisode
primaryTitle          Episode #13.61
originalTitle         Episode #13.61
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004177, dtype: object

(9,)

tconst                    tt11823434
titleType                  tvEpisode
primaryTitle          Episode #13.64
originalTitle         Episode #13.64
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004178, dtype: object

(9,)

tconst                tt11823436
titleType              tvEpisode
primaryTitle      Dionne Warwick
originalTitle     Dionne Warwick
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2004179, dtype: object

(9,)

tconst              tt11823438
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004180, dtype: object

(9,)

tconst                    tt11823440
titleType                  tvEpisode
primaryTitle           Episode #14.2
originalTitle          Episode #14.2
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004181, dtype: object

(9,)

tconst              tt11823442
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004182, dtype: object

(9,)

tconst                    tt11823444
titleType                  tvEpisode
primaryTitle           Episode #14.4
originalTitle          Episode #14.4
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004183, dtype: object

(9,)

tconst              tt11823446
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004184, dtype: object

(9,)

tconst                    tt11823448
titleType                  tvEpisode
primaryTitle           Episode #14.3
originalTitle          Episode #14.3
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004185, dtype: object

(9,)

tconst                 tt1182344
titleType                  movie
primaryTitle      Melvyn's Clock
originalTitle     Melvyn's Clock
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004186, dtype: object

(9,)

tconst                    tt11823450
titleType                  tvEpisode
primaryTitle           Episode #14.6
originalTitle          Episode #14.6
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004187, dtype: object

(9,)

tconst                    tt11823452
titleType                  tvEpisode
primaryTitle           Episode #14.5
originalTitle          Episode #14.5
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004188, dtype: object

(9,)

tconst              tt11823454
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004189, dtype: object

(9,)

tconst                    tt11823456
titleType                  tvEpisode
primaryTitle           Episode #14.7
originalTitle          Episode #14.7
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004190, dtype: object

(9,)

tconst                    tt11823458
titleType                  tvEpisode
primaryTitle           Episode #14.8
originalTitle          Episode #14.8
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004191, dtype: object

(9,)

tconst                       tt1182345
titleType                        movie
primaryTitle                      Moon
originalTitle                     Moon
isAdult                              0
startYear                         2009
endYear                             \N
runtimeMinutes                      97
genres            Drama,Mystery,Sci-Fi
Name: 2004192, dtype: object

(9,)

tconst              tt11823460
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004193, dtype: object

(9,)

tconst                    tt11823462
titleType                  tvEpisode
primaryTitle           Episode #14.9
originalTitle          Episode #14.9
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004194, dtype: object

(9,)

tconst                    tt11823464
titleType                  tvEpisode
primaryTitle          Episode #14.10
originalTitle         Episode #14.10
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004195, dtype: object

(9,)

tconst                    tt11823466
titleType                  tvEpisode
primaryTitle          Episode #14.12
originalTitle         Episode #14.12
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004196, dtype: object

(9,)

tconst                    tt11823468
titleType                  tvEpisode
primaryTitle          Episode #14.11
originalTitle         Episode #14.11
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004197, dtype: object

(9,)

tconst                    tt11823470
titleType                  tvEpisode
primaryTitle          Episode #14.13
originalTitle         Episode #14.13
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004198, dtype: object

(9,)

tconst                    tt11823472
titleType                  tvEpisode
primaryTitle          Episode #14.16
originalTitle         Episode #14.16
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004199, dtype: object

(9,)

tconst                    tt11823474
titleType                  tvEpisode
primaryTitle          Episode #14.14
originalTitle         Episode #14.14
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004200, dtype: object

(9,)

tconst              tt11823476
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004201, dtype: object

(9,)

tconst              tt11823478
titleType            tvEpisode
primaryTitle      Ananda Lewis
originalTitle     Ananda Lewis
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2004202, dtype: object

(9,)

tconst            tt1182347
titleType             video
primaryTitle         Savage
originalTitle        Savage
isAdult                   1
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                Adult
Name: 2004203, dtype: object

(9,)

tconst                    tt11823480
titleType                  tvEpisode
primaryTitle          Episode #14.15
originalTitle         Episode #14.15
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004204, dtype: object

(9,)

tconst              tt11823482
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004205, dtype: object

(9,)

tconst                    tt11823484
titleType                  tvEpisode
primaryTitle          Episode #14.17
originalTitle         Episode #14.17
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004206, dtype: object

(9,)

tconst                    tt11823486
titleType                  tvEpisode
primaryTitle          Episode #14.19
originalTitle         Episode #14.19
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004207, dtype: object

(9,)

tconst                    tt11823488
titleType                  tvEpisode
primaryTitle          Episode #14.18
originalTitle         Episode #14.18
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004208, dtype: object

(9,)

tconst                         tt1182348
titleType                          video
primaryTitle      Start Singing with Boz
originalTitle     Start Singing with Boz
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        40
genres                      Family,Short
Name: 2004209, dtype: object

(9,)

tconst              tt11823490
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2010
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004210, dtype: object

(9,)

tconst                    tt11823492
titleType                  tvEpisode
primaryTitle          Episode #14.21
originalTitle         Episode #14.21
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004211, dtype: object

(9,)

tconst                    tt11823494
titleType                  tvEpisode
primaryTitle          Episode #14.20
originalTitle         Episode #14.20
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004212, dtype: object

(9,)

tconst                    tt11823496
titleType                  tvEpisode
primaryTitle          Episode #14.23
originalTitle         Episode #14.23
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004213, dtype: object

(9,)

tconst                    tt11823498
titleType                  tvEpisode
primaryTitle          Episode #14.24
originalTitle         Episode #14.24
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004214, dtype: object

(9,)

tconst                   tt1182349
titleType                tvEpisode
primaryTitle      The First Doctor
originalTitle     The First Doctor
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  14
genres                 Documentary
Name: 2004215, dtype: object

(9,)

tconst                    tt11823500
titleType                  tvEpisode
primaryTitle          Episode #14.22
originalTitle         Episode #14.22
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004216, dtype: object

(9,)

tconst                    tt11823502
titleType                  tvEpisode
primaryTitle          Episode #14.25
originalTitle         Episode #14.25
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004217, dtype: object

(9,)

tconst                    tt11823504
titleType                  tvEpisode
primaryTitle          Episode #14.26
originalTitle         Episode #14.26
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004218, dtype: object

(9,)

tconst                    tt11823506
titleType                  tvEpisode
primaryTitle          Episode #14.27
originalTitle         Episode #14.27
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004219, dtype: object

(9,)

tconst                    tt11823508
titleType                  tvEpisode
primaryTitle          Episode #14.28
originalTitle         Episode #14.28
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004220, dtype: object

(9,)

tconst                                     tt1182350
titleType                                      movie
primaryTitle      You Will Meet a Tall Dark Stranger
originalTitle     You Will Meet a Tall Dark Stranger
isAdult                                            0
startYear                                       2010
endYear                                           \N
runtimeMinutes                                    98
genres                          Comedy,Drama,Romance
Name: 2004221, dtype: object

(9,)

tconst                    tt11823510
titleType                  tvEpisode
primaryTitle          Episode #14.29
originalTitle         Episode #14.29
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004222, dtype: object

(9,)

tconst                    tt11823512
titleType                  tvEpisode
primaryTitle          Episode #14.30
originalTitle         Episode #14.30
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004223, dtype: object

(9,)

tconst             tt11823514
titleType               movie
primaryTitle      Wagenknecht
originalTitle     Wagenknecht
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             99
genres            Documentary
Name: 2004224, dtype: object

(9,)

tconst                    tt11823516
titleType                  tvEpisode
primaryTitle          Episode #14.32
originalTitle         Episode #14.32
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004225, dtype: object

(9,)

tconst                    tt11823518
titleType                  tvEpisode
primaryTitle          Episode #14.31
originalTitle         Episode #14.31
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004226, dtype: object

(9,)

tconst                              tt1182351
titleType                            tvSeries
primaryTitle      40 degrés à l'ombre de la 3
originalTitle     40 degrés à l'ombre de la 3
isAdult                                     0
startYear                                1987
endYear                                  1997
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2004227, dtype: object

(9,)

tconst                    tt11823520
titleType                  tvEpisode
primaryTitle          Episode #14.33
originalTitle         Episode #14.33
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004228, dtype: object

(9,)

tconst                    tt11823522
titleType                  tvEpisode
primaryTitle          Episode #14.35
originalTitle         Episode #14.35
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004229, dtype: object

(9,)

tconst                    tt11823524
titleType                  tvEpisode
primaryTitle          Episode #14.34
originalTitle         Episode #14.34
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004230, dtype: object

(9,)

tconst                    tt11823526
titleType                  tvEpisode
primaryTitle          Episode #14.38
originalTitle         Episode #14.38
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004231, dtype: object

(9,)

tconst                    tt11823528
titleType                  tvEpisode
primaryTitle          Episode #14.37
originalTitle         Episode #14.37
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004232, dtype: object

(9,)

tconst                  tt1182352
titleType               tvEpisode
primaryTitle      Finalmente soli
originalTitle     Finalmente soli
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2004233, dtype: object

(9,)

tconst                    tt11823530
titleType                  tvEpisode
primaryTitle          Episode #14.36
originalTitle         Episode #14.36
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004234, dtype: object

(9,)

tconst                    tt11823532
titleType                  tvEpisode
primaryTitle          Episode #14.39
originalTitle         Episode #14.39
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004235, dtype: object

(9,)

tconst                    tt11823534
titleType                  tvEpisode
primaryTitle          Episode #14.40
originalTitle         Episode #14.40
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004236, dtype: object

(9,)

tconst                    tt11823536
titleType                  tvEpisode
primaryTitle          Episode #14.42
originalTitle         Episode #14.42
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004237, dtype: object

(9,)

tconst               tt11823538
titleType             tvEpisode
primaryTitle      Amanda Seales
originalTitle     Amanda Seales
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2004238, dtype: object

(9,)

tconst                        tt1182353
titleType                     tvEpisode
primaryTitle      Il mio migliore amico
originalTitle     Il mio migliore amico
isAdult                               0
startYear                          2007
endYear                              \N
runtimeMinutes                       \N
genres                           Comedy
Name: 2004239, dtype: object

(9,)

tconst                    tt11823540
titleType                  tvEpisode
primaryTitle          Episode #14.41
originalTitle         Episode #14.41
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004240, dtype: object

(9,)

tconst                    tt11823542
titleType                  tvEpisode
primaryTitle          Episode #14.43
originalTitle         Episode #14.43
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2004241, dtype: object

(9,)

tconst              tt11823544
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004242, dtype: object

(9,)

tconst              tt11823546
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004243, dtype: object

(9,)

tconst              tt11823548
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004244, dtype: object

(9,)

tconst                      tt1182354
titleType                   tvEpisode
primaryTitle      Il nuovo che avanza
originalTitle     Il nuovo che avanza
isAdult                             0
startYear                        2007
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2004245, dtype: object

(9,)

tconst              tt11823550
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004246, dtype: object

(9,)

tconst              tt11823552
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004247, dtype: object

(9,)

tconst              tt11823554
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004248, dtype: object

(9,)

tconst              tt11823556
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004249, dtype: object

(9,)

tconst              tt11823558
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2011
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004250, dtype: object

(9,)

tconst                    tt1182355
titleType                 tvEpisode
primaryTitle      Il pelo nell'uovo
originalTitle     Il pelo nell'uovo
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2004251, dtype: object

(9,)

tconst              tt11823560
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004252, dtype: object

(9,)

tconst              tt11823562
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004253, dtype: object

(9,)

tconst              tt11823564
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004254, dtype: object

(9,)

tconst                                                   tt11823566
titleType                                                     video
primaryTitle      A Stepmom Finds Her Stepson Jerking Off to Her...
originalTitle     A Stepmom Finds Her Stepson Jerking Off to Her...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   97
genres                                                        Adult
Name: 2004255, dtype: object

(9,)

tconst              tt11823568
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004256, dtype: object

(9,)

tconst                tt1182356
titleType             tvEpisode
primaryTitle      Il vero amore
originalTitle     Il vero amore
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004257, dtype: object

(9,)

tconst              tt11823570
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004258, dtype: object

(9,)

tconst              tt11823572
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004259, dtype: object

(9,)

tconst              tt11823574
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004260, dtype: object

(9,)

tconst              tt11823576
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004261, dtype: object

(9,)

tconst               tt11823578
titleType             tvEpisode
primaryTitle      Episode #13.1
originalTitle     Episode #13.1
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2004262, dtype: object

(9,)

tconst                tt1182357
titleType             tvEpisode
primaryTitle      Io ti perdono
originalTitle     Io ti perdono
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004263, dtype: object

(9,)

tconst               tt11823580
titleType             tvEpisode
primaryTitle      Episode #2.32
originalTitle     Episode #2.32
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2004264, dtype: object

(9,)

tconst            tt11823582
titleType          tvEpisode
primaryTitle       Episode 1
originalTitle      Episode 1
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres               Fantasy
Name: 2004265, dtype: object

(9,)

tconst                              tt11823584
titleType                            tvEpisode
primaryTitle      Episode dated 8 October 1970
originalTitle     Episode dated 8 October 1970
isAdult                                      0
startYear                                 1970
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2004266, dtype: object

(9,)

tconst               tt11823586
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               40
genres                    Crime
Name: 2004267, dtype: object

(9,)

tconst               tt11823588
titleType             tvEpisode
primaryTitle      Episode #21.5
originalTitle     Episode #21.5
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres             Drama,Family
Name: 2004268, dtype: object

(9,)

tconst              tt1182358
titleType           tvEpisode
primaryTitle      L'incidente
originalTitle     L'incidente
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2004269, dtype: object

(9,)

tconst                  tt11823590
titleType                tvEpisode
primaryTitle      Woman in the Box
originalTitle     Woman in the Box
isAdult                          0
startYear                     1954
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2004270, dtype: object

(9,)

tconst               tt11823592
titleType             tvEpisode
primaryTitle      Episode #21.6
originalTitle     Episode #21.6
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres             Drama,Family
Name: 2004271, dtype: object

(9,)

tconst                                    tt11823596
titleType                                  tvEpisode
primaryTitle      Top 10 Best Movie Trailers of 2018
originalTitle     Top 10 Best Movie Trailers of 2018
isAdult                                            0
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                              Comedy,Talk-Show
Name: 2004272, dtype: object

(9,)

tconst                tt11823598
titleType              tvEpisode
primaryTitle      Episode #21.12
originalTitle     Episode #21.12
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres              Drama,Family
Name: 2004273, dtype: object

(9,)

tconst                       tt1182359
titleType                    tvEpisode
primaryTitle      La stanza del figlio
originalTitle     La stanza del figlio
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres                          Comedy
Name: 2004274, dtype: object

(9,)

tconst                tt11823600
titleType              tvEpisode
primaryTitle      Episode #21.13
originalTitle     Episode #21.13
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres              Drama,Family
Name: 2004275, dtype: object

(9,)

tconst                tt11823602
titleType              tvEpisode
primaryTitle      Episode #16.20
originalTitle     Episode #16.20
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2004276, dtype: object

(9,)

tconst                tt11823604
titleType              tvEpisode
primaryTitle      Episode #21.14
originalTitle     Episode #21.14
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres              Drama,Family
Name: 2004277, dtype: object

(9,)

tconst                tt11823606
titleType              tvEpisode
primaryTitle      Episode #21.15
originalTitle     Episode #21.15
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres              Drama,Family
Name: 2004278, dtype: object

(9,)

tconst                        tt11823608
titleType                      tvEpisode
primaryTitle      The Lovers Out of Time
originalTitle     The Lovers Out of Time
isAdult                                0
startYear                           1954
endYear                               \N
runtimeMinutes                        \N
genres                             Drama
Name: 2004279, dtype: object

(9,)

tconst                            tt1182360
titleType                         tvEpisode
primaryTitle      Mia nonna è un'autarchica
originalTitle     Mia nonna è un'autarchica
isAdult                                   0
startYear                              2007
endYear                                  \N
runtimeMinutes                           \N
genres                               Comedy
Name: 2004280, dtype: object

(9,)

tconst                tt11823610
titleType              tvEpisode
primaryTitle      Episode #21.19
originalTitle     Episode #21.19
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres              Drama,Family
Name: 2004281, dtype: object

(9,)

tconst                                 tt11823612
titleType                                   video
primaryTitle      Ray Parker Jr.: The Other Woman
originalTitle     Ray Parker Jr.: The Other Woman
isAdult                                         0
startYear                                    1982
endYear                                        \N
runtimeMinutes                                  4
genres                                Music,Short
Name: 2004282, dtype: object

(9,)

tconst                              tt11823614
titleType                                movie
primaryTitle      Russkie gruziny. Film pervyy
originalTitle     Russkie gruziny. Film pervyy
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                             115
genres                             Documentary
Name: 2004283, dtype: object

(9,)

tconst                     tt11823616
titleType                   tvEpisode
primaryTitle      The Pulse of Murder
originalTitle     The Pulse of Murder
isAdult                             0
startYear                        1954
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2004284, dtype: object

(9,)

tconst               tt11823618
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               40
genres                    Crime
Name: 2004285, dtype: object

(9,)

tconst                        tt1182361
titleType                     tvEpisode
primaryTitle            Episode #1.9810
originalTitle           Episode #1.9810
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2004286, dtype: object

(9,)

tconst            tt11823620
titleType          tvEpisode
primaryTitle       Episode 2
originalTitle      Episode 2
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres               Fantasy
Name: 2004287, dtype: object

(9,)

tconst                                                   tt11823622
titleType                                                     video
primaryTitle      Ray Parker Jr.: I Still Can't Get Over Loving You
originalTitle     Ray Parker Jr.: I Still Can't Get Over Loving You
isAdult                                                           0
startYear                                                      1983
endYear                                                          \N
runtimeMinutes                                                    5
genres                                                  Music,Short
Name: 2004288, dtype: object

(9,)

tconst                     tt11823624
titleType                       short
primaryTitle          Autumn Nocturne
originalTitle         Autumn Nocturne
isAdult                             0
startYear                        2021
endYear                            \N
runtimeMinutes                      5
genres            Drama,History,Short
Name: 2004289, dtype: object

(9,)

tconst                           tt11823626
titleType                             video
primaryTitle      Ray Parker Jr.: Let Me Go
originalTitle     Ray Parker Jr.: Let Me Go
isAdult                                   0
startYear                              1982
endYear                                  \N
runtimeMinutes                            4
genres                          Music,Short
Name: 2004290, dtype: object

(9,)

tconst                         tt11823628
titleType                       tvEpisode
primaryTitle      Mr. Krosneck Disappears
originalTitle     Mr. Krosneck Disappears
isAdult                                 0
startYear                            1954
endYear                                \N
runtimeMinutes                         \N
genres                              Drama
Name: 2004291, dtype: object

(9,)

tconst                        tt1182362
titleType                     tvEpisode
primaryTitle            Episode #1.9811
originalTitle           Episode #1.9811
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Mystery,Romance
Name: 2004292, dtype: object

(9,)

tconst            tt11823630
titleType          tvEpisode
primaryTitle       Episode 3
originalTitle      Episode 3
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres               Fantasy
Name: 2004293, dtype: object

(9,)

tconst                     tt11823634
titleType                   tvEpisode
primaryTitle      The Tell-Tale Heart
originalTitle     The Tell-Tale Heart
isAdult                             0
startYear                        1954
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2004294, dtype: object

(9,)

tconst                                    tt11823636
titleType                                      video
primaryTitle      Ray Parker Jr.: Girls Are More Fun
originalTitle     Ray Parker Jr.: Girls Are More Fun
isAdult                                            0
startYear                                       1985
endYear                                           \N
runtimeMinutes                                     5
genres                                   Music,Short
Name: 2004295, dtype: object

(9,)

tconst            tt11823638
titleType          tvEpisode
primaryTitle       Episode 4
originalTitle      Episode 4
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres               Fantasy
Name: 2004296, dtype: object

(9,)

tconst                tt1182363
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004297, dtype: object

(9,)

tconst                                                   tt11823640
titleType                                                     video
primaryTitle      Ray Parker Jr.: I Don't Think That Man Should ...
originalTitle     Ray Parker Jr.: I Don't Think That Man Should ...
isAdult                                                           0
startYear                                                      1987
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2004298, dtype: object

(9,)

tconst                       tt11823642
titleType                     tvEpisode
primaryTitle      The Last Man on Earth
originalTitle     The Last Man on Earth
isAdult                               0
startYear                          1954
endYear                              \N
runtimeMinutes                       \N
genres                            Drama
Name: 2004299, dtype: object

(9,)

tconst            tt11823644
titleType          tvEpisode
primaryTitle       Episode 5
originalTitle      Episode 5
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres               Fantasy
Name: 2004300, dtype: object

(9,)

tconst                   tt11823646
titleType                 tvEpisode
primaryTitle      I Dream of Murder
originalTitle     I Dream of Murder
isAdult                           0
startYear                      1954
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2004301, dtype: object

(9,)

tconst              tt11823648
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2004302, dtype: object

(9,)

tconst                tt1182364
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004303, dtype: object

(9,)

tconst                          tt11823650
titleType                        tvEpisode
primaryTitle      Episode dated 8 May 2017
originalTitle     Episode dated 8 May 2017
isAdult                                  0
startYear                             2017
endYear                                 \N
runtimeMinutes                          \N
genres                                  \N
Name: 2004304, dtype: object

(9,)

tconst                           tt11823652
titleType                         tvEpisode
primaryTitle      Episode dated 15 May 2017
originalTitle     Episode dated 15 May 2017
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2004305, dtype: object

(9,)

tconst                           tt11823654
titleType                         tvEpisode
primaryTitle      Episode dated 22 May 2017
originalTitle     Episode dated 22 May 2017
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2004306, dtype: object

(9,)

tconst                           tt11823656
titleType                         tvEpisode
primaryTitle      Episode dated 26 May 2017
originalTitle     Episode dated 26 May 2017
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2004307, dtype: object

(9,)

tconst                tt11823658
titleType              tvEpisode
primaryTitle      The Third Rose
originalTitle     The Third Rose
isAdult                        0
startYear                   1954
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004308, dtype: object

(9,)

tconst                tt1182365
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004309, dtype: object

(9,)

tconst                                                   tt11823660
titleType                                                     video
primaryTitle      Ray Parker Jr. Feat. Helen Terry: One Sunny Da...
originalTitle     Ray Parker Jr. Feat. Helen Terry: One Sunny Da...
isAdult                                                           0
startYear                                                      1986
endYear                                                          \N
runtimeMinutes                                                    3
genres                                                  Music,Short
Name: 2004310, dtype: object

(9,)

tconst                            tt11823662
titleType                          tvEpisode
primaryTitle      Episode dated 23 June 1985
originalTitle     Episode dated 23 June 1985
isAdult                                    0
startYear                               1985
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2004311, dtype: object

(9,)

tconst               tt11823664
titleType             tvEpisode
primaryTitle      The Deadliest
originalTitle     The Deadliest
isAdult                       0
startYear                  1954
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004312, dtype: object

(9,)

tconst                tt11823666
titleType              tvEpisode
primaryTitle      Episode #1.221
originalTitle     Episode #1.221
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004313, dtype: object

(9,)

tconst                tt11823668
titleType              tvEpisode
primaryTitle      Episode #1.222
originalTitle     Episode #1.222
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004314, dtype: object

(9,)

tconst                tt1182366
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004315, dtype: object

(9,)

tconst                tt11823670
titleType              tvEpisode
primaryTitle      Episode #1.224
originalTitle     Episode #1.224
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004316, dtype: object

(9,)

tconst                tt11823672
titleType              tvEpisode
primaryTitle      Episode #1.223
originalTitle     Episode #1.223
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004317, dtype: object

(9,)

tconst                tt11823674
titleType              tvEpisode
primaryTitle      Episode #1.225
originalTitle     Episode #1.225
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004318, dtype: object

(9,)

tconst                tt11823676
titleType              tvEpisode
primaryTitle      Episode #1.227
originalTitle     Episode #1.227
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004319, dtype: object

(9,)

tconst                tt11823678
titleType              tvEpisode
primaryTitle      Episode #1.226
originalTitle     Episode #1.226
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004320, dtype: object

(9,)

tconst                tt1182367
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004321, dtype: object

(9,)

tconst                tt11823680
titleType              tvEpisode
primaryTitle      Episode #1.228
originalTitle     Episode #1.228
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004322, dtype: object

(9,)

tconst                tt11823682
titleType              tvEpisode
primaryTitle      Episode #1.229
originalTitle     Episode #1.229
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004323, dtype: object

(9,)

tconst                tt11823684
titleType              tvEpisode
primaryTitle      Episode #1.230
originalTitle     Episode #1.230
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004324, dtype: object

(9,)

tconst                tt11823686
titleType              tvEpisode
primaryTitle      Episode #1.231
originalTitle     Episode #1.231
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004325, dtype: object

(9,)

tconst                tt11823688
titleType              tvEpisode
primaryTitle      Episode #1.232
originalTitle     Episode #1.232
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004326, dtype: object

(9,)

tconst                tt1182368
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004327, dtype: object

(9,)

tconst                tt11823690
titleType              tvEpisode
primaryTitle      Episode #1.233
originalTitle     Episode #1.233
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004328, dtype: object

(9,)

tconst                            tt11823692
titleType                          tvEpisode
primaryTitle      Episode dated 28 July 1985
originalTitle     Episode dated 28 July 1985
isAdult                                    0
startYear                               1985
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2004329, dtype: object

(9,)

tconst                tt11823694
titleType              tvEpisode
primaryTitle      Episode #1.234
originalTitle     Episode #1.234
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004330, dtype: object

(9,)

tconst                tt11823696
titleType              tvEpisode
primaryTitle      Episode #1.235
originalTitle     Episode #1.235
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004331, dtype: object

(9,)

tconst                                                   tt11823698
titleType                                                     video
primaryTitle      Ray Parker Jr. & Raydio: A Woman Needs Love (J...
originalTitle     Ray Parker Jr. & Raydio: A Woman Needs Love (J...
isAdult                                                           0
startYear                                                      1981
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2004332, dtype: object

(9,)

tconst                tt1182369
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004333, dtype: object

(9,)

tconst                tt11823700
titleType              tvEpisode
primaryTitle      Episode #1.236
originalTitle     Episode #1.236
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004334, dtype: object

(9,)

tconst                tt11823702
titleType              tvEpisode
primaryTitle      Episode #1.237
originalTitle     Episode #1.237
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004335, dtype: object

(9,)

tconst                tt11823704
titleType              tvEpisode
primaryTitle      Episode #1.238
originalTitle     Episode #1.238
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004336, dtype: object

(9,)

tconst                tt11823706
titleType              tvEpisode
primaryTitle      Episode #1.239
originalTitle     Episode #1.239
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004337, dtype: object

(9,)

tconst                tt11823708
titleType              tvEpisode
primaryTitle      Episode #1.240
originalTitle     Episode #1.240
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004338, dtype: object

(9,)

tconst                tt1182370
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004339, dtype: object

(9,)

tconst               tt11823710
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004340, dtype: object

(9,)

tconst            tt11823712
titleType              movie
primaryTitle       Kisô jowa
originalTitle      Kisô jowa
isAdult                    0
startYear               1935
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2004341, dtype: object

(9,)

tconst               tt11823714
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004342, dtype: object

(9,)

tconst               tt11823716
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004343, dtype: object

(9,)

tconst               tt11823718
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004344, dtype: object

(9,)

tconst                tt1182371
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004345, dtype: object

(9,)

tconst                            tt11823720
titleType                          tvEpisode
primaryTitle      Episode dated 11 June 1994
originalTitle     Episode dated 11 June 1994
isAdult                                    0
startYear                               1994
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2004346, dtype: object

(9,)

tconst               tt11823722
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004347, dtype: object

(9,)

tconst               tt11823724
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004348, dtype: object

(9,)

tconst                              tt11823726
titleType                            tvEpisode
primaryTitle      Episode dated 21 August 2018
originalTitle     Episode dated 21 August 2018
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2004349, dtype: object

(9,)

tconst                              tt11823728
titleType                            tvEpisode
primaryTitle      Episode dated 22 August 2018
originalTitle     Episode dated 22 August 2018
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2004350, dtype: object

(9,)

tconst                tt1182372
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004351, dtype: object

(9,)

tconst                                                   tt11823730
titleType                                                     video
primaryTitle      Ray Parker Jr. Feat Father MC: She Needs to Ge...
originalTitle     Ray Parker Jr. Feat Father MC: She Needs to Ge...
isAdult                                                           0
startYear                                                      1991
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2004352, dtype: object

(9,)

tconst            tt11823732
titleType          tvEpisode
primaryTitle        Turnover
originalTitle       Turnover
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres               Fantasy
Name: 2004353, dtype: object

(9,)

tconst                                tt11823734
titleType                              tvEpisode
primaryTitle      Episode dated 4 September 2018
originalTitle     Episode dated 4 September 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2004354, dtype: object

(9,)

tconst                                tt11823736
titleType                              tvEpisode
primaryTitle      Episode dated 5 September 2018
originalTitle     Episode dated 5 September 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2004355, dtype: object

(9,)

tconst                                 tt11823738
titleType                               tvEpisode
primaryTitle      Episode dated 11 September 2018
originalTitle     Episode dated 11 September 2018
isAdult                                         0
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2004356, dtype: object

(9,)

tconst                tt1182373
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004357, dtype: object

(9,)

tconst                             tt11823740
titleType                           tvEpisode
primaryTitle      Episode dated 4 August 1985
originalTitle     Episode dated 4 August 1985
isAdult                                     0
startYear                                1985
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2004358, dtype: object

(9,)

tconst               tt11823742
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004359, dtype: object

(9,)

tconst               tt11823744
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004360, dtype: object

(9,)

tconst               tt11823746
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004361, dtype: object

(9,)

tconst                                                   tt11823748
titleType                                                     video
primaryTitle      A Stepson Makes His Stepmom Cum Under the Heat...
originalTitle     A Stepson Makes His Stepmom Cum Under the Heat...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   96
genres                                                        Adult
Name: 2004362, dtype: object

(9,)

tconst                tt1182374
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004363, dtype: object

(9,)

tconst               tt11823750
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004364, dtype: object

(9,)

tconst               tt11823752
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004365, dtype: object

(9,)

tconst               tt11823754
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004366, dtype: object

(9,)

tconst               tt11823756
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004367, dtype: object

(9,)

tconst               tt11823758
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004368, dtype: object

(9,)

tconst                tt1182375
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004369, dtype: object

(9,)

tconst               tt11823760
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004370, dtype: object

(9,)

tconst               tt11823762
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004371, dtype: object

(9,)

tconst               tt11823764
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004372, dtype: object

(9,)

tconst               tt11823766
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004373, dtype: object

(9,)

tconst               tt11823768
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004374, dtype: object

(9,)

tconst                tt1182376
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004375, dtype: object

(9,)

tconst               tt11823770
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004376, dtype: object

(9,)

tconst               tt11823772
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004377, dtype: object

(9,)

tconst               tt11823774
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004378, dtype: object

(9,)

tconst                                                   tt11823776
titleType                                                 tvEpisode
primaryTitle      Gmod: Frogger! (Garry's Mod Sandbox Funny Mome...
originalTitle     Gmod: Frogger! (Garry's Mod Sandbox Funny Mome...
isAdult                                                           0
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   10
genres                                                       Comedy
Name: 2004379, dtype: object

(9,)

tconst               tt11823778
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004380, dtype: object

(9,)

tconst                tt1182377
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004381, dtype: object

(9,)

tconst               tt11823780
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004382, dtype: object

(9,)

tconst               tt11823782
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004383, dtype: object

(9,)

tconst               tt11823784
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004384, dtype: object

(9,)

tconst               tt11823786
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004385, dtype: object

(9,)

tconst               tt11823788
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004386, dtype: object

(9,)

tconst                tt1182378
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004387, dtype: object

(9,)

tconst               tt11823790
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004388, dtype: object

(9,)

tconst               tt11823792
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004389, dtype: object

(9,)

tconst               tt11823794
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004390, dtype: object

(9,)

tconst               tt11823796
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004391, dtype: object

(9,)

tconst               tt11823798
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004392, dtype: object

(9,)

tconst                tt1182379
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004393, dtype: object

(9,)

tconst               tt11823800
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004394, dtype: object

(9,)

tconst               tt11823802
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004395, dtype: object

(9,)

tconst               tt11823804
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004396, dtype: object

(9,)

tconst               tt11823806
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004397, dtype: object

(9,)

tconst               tt11823808
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004398, dtype: object

(9,)

tconst                tt1182380
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004399, dtype: object

(9,)

tconst               tt11823810
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2004400, dtype: object

(9,)

tconst                     tt11823812
titleType                   tvEpisode
primaryTitle                     Fall
originalTitle                    Fall
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     25
genres            Crime,Drama,Romance
Name: 2004401, dtype: object

(9,)

tconst               tt11823814
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004402, dtype: object

(9,)

tconst                                                   tt11823816
titleType                                                 tvEpisode
primaryTitle      Gmod: Piggy Balboa - Super Weenie Fight Club (...
originalTitle     Gmod: Piggy Balboa - Super Weenie Fight Club (...
isAdult                                                           0
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   11
genres                                                       Comedy
Name: 2004403, dtype: object

(9,)

tconst                        tt11823818
titleType                      tvEpisode
primaryTitle      Exploring Dog Soldiers
originalTitle     Exploring Dog Soldiers
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                       Comedy,News
Name: 2004404, dtype: object

(9,)

tconst                tt1182381
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004405, dtype: object

(9,)

tconst               tt11823820
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004406, dtype: object

(9,)

tconst               tt11823822
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004407, dtype: object

(9,)

tconst                                           tt11823824
titleType                                             video
primaryTitle      Raydio: More Than One Way to Love a Woman
originalTitle     Raydio: More Than One Way to Love a Woman
isAdult                                                   0
startYear                                              1979
endYear                                                  \N
runtimeMinutes                                            5
genres                                          Music,Short
Name: 2004408, dtype: object

(9,)

tconst               tt11823826
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004409, dtype: object

(9,)

tconst               tt11823828
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004410, dtype: object

(9,)

tconst                tt1182382
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004411, dtype: object

(9,)

tconst               tt11823830
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004412, dtype: object

(9,)

tconst               tt11823832
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004413, dtype: object

(9,)

tconst               tt11823834
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004414, dtype: object

(9,)

tconst               tt11823836
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004415, dtype: object

(9,)

tconst               tt11823838
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004416, dtype: object

(9,)

tconst             tt1182383
titleType          tvEpisode
primaryTitle      Pullapojat
originalTitle     Pullapojat
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2004417, dtype: object

(9,)

tconst               tt11823840
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004418, dtype: object

(9,)

tconst               tt11823842
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004419, dtype: object

(9,)

tconst               tt11823844
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004420, dtype: object

(9,)

tconst                                                   tt11823846
titleType                                                 tvEpisode
primaryTitle      Gmod Deathrun Funny Moments: Gotcha Bitch! (Ga...
originalTitle     Gmod Deathrun Funny Moments: Gotcha Bitch! (Ga...
isAdult                                                           0
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   13
genres                                                       Comedy
Name: 2004421, dtype: object

(9,)

tconst               tt11823848
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004422, dtype: object

(9,)

tconst               tt1182384
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2004423, dtype: object

(9,)

tconst               tt11823850
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004424, dtype: object

(9,)

tconst                        tt11823852
titleType                          video
primaryTitle      Raydio: Honey I'm Rich
originalTitle     Raydio: Honey I'm Rich
isAdult                                0
startYear                           1978
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2004425, dtype: object

(9,)

tconst                        tt11823854
titleType                      tvEpisode
primaryTitle                  Dog Tricks
originalTitle                 Dog Tricks
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Short
Name: 2004426, dtype: object

(9,)

tconst                       tt11823856
titleType                     tvEpisode
primaryTitle      The Big Day Out Badge
originalTitle     The Big Day Out Badge
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                 Animation,Family
Name: 2004427, dtype: object

(9,)

tconst               tt11823858
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004428, dtype: object

(9,)

tconst                                                    tt1182385
titleType                                                 tvEpisode
primaryTitle      Bamse bestemmer selv, om han vil være gul med ...
originalTitle     Bamse bestemmer selv, om han vil være gul med ...
isAdult                                                           0
startYear                                                      1989
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Family
Name: 2004429, dtype: object

(9,)

tconst               tt11823860
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004430, dtype: object

(9,)

tconst               tt11823862
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004431, dtype: object

(9,)

tconst                              tt11823864
titleType                                video
primaryTitle      Raydio: Is This a Love Thing
originalTitle     Raydio: Is This a Love Thing
isAdult                                      0
startYear                                 1978
endYear                                     \N
runtimeMinutes                               6
genres                             Music,Short
Name: 2004432, dtype: object

(9,)

tconst               tt11823866
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004433, dtype: object

(9,)

tconst                   tt11823868
titleType                  tvSeries
primaryTitle      Rip Roarin Sports
originalTitle     Rip Roarin Sports
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                  Documentary
Name: 2004434, dtype: object

(9,)

tconst                                     tt1182386
titleType                                  tvEpisode
primaryTitle      Bamse og Kylling flytter hjem igen
originalTitle     Bamse og Kylling flytter hjem igen
isAdult                                            0
startYear                                       1989
endYear                                           \N
runtimeMinutes                                    \N
genres                                        Family
Name: 2004435, dtype: object

(9,)

tconst                                                   tt11823870
titleType                                                 tvEpisode
primaryTitle      Gmod Hide and Seek Funny Moments - Oooo Meter,...
originalTitle     Gmod Hide and Seek Funny Moments - Oooo Meter,...
isAdult                                                           0
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   10
genres                                                       Comedy
Name: 2004436, dtype: object

(9,)

tconst                    tt11823872
titleType                  tvEpisode
primaryTitle      Deadly Performance
originalTitle     Deadly Performance
isAdult                            0
startYear                       1983
endYear                           \N
runtimeMinutes                    \N
genres                     Adventure
Name: 2004437, dtype: object

(9,)

tconst               tt11823874
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2004438, dtype: object

(9,)

tconst                               tt11823876
titleType                             tvEpisode
primaryTitle      Episode dated 16 January 2017
originalTitle     Episode dated 16 January 2017
isAdult                                       0
startYear                                  2017
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2004439, dtype: object

(9,)

tconst                               tt11823878
titleType                             tvEpisode
primaryTitle      Episode dated 11 January 1954
originalTitle     Episode dated 11 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2004440, dtype: object

(9,)

tconst                                     tt1182387
titleType                                  tvEpisode
primaryTitle      Bamse og Kylling flytter hjemmefra
originalTitle     Bamse og Kylling flytter hjemmefra
isAdult                                            0
startYear                                       1989
endYear                                           \N
runtimeMinutes                                    \N
genres                                        Family
Name: 2004441, dtype: object

(9,)

tconst                               tt11823880
titleType                             tvEpisode
primaryTitle      Episode dated 17 January 2017
originalTitle     Episode dated 17 January 2017
isAdult                                       0
startYear                                  2017
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2004442, dtype: object

(9,)

tconst                                tt11823882
titleType                              tvEpisode
primaryTitle      Episode dated 10 February 2017
originalTitle     Episode dated 10 February 2017
isAdult                                        0
startYear                                   2017
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2004443, dtype: object

(9,)

tconst                       tt11823884
titleType                         video
primaryTitle      Raydio: Jack and Jill
originalTitle     Raydio: Jack and Jill
isAdult                               0
startYear                          1978
endYear                              \N
runtimeMinutes                        4
genres                      Music,Short
Name: 2004444, dtype: object

(9,)

tconst               tt11823886
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004445, dtype: object

(9,)

tconst                                tt11823888
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2017
originalTitle     Episode dated 20 February 2017
isAdult                                        0
startYear                                   2017
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2004446, dtype: object

(9,)

tconst                    tt1182388
titleType                 tvEpisode
primaryTitle      Bamses fødselsdag
originalTitle     Bamses fødselsdag
isAdult                           0
startYear                      1989
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2004447, dtype: object

(9,)

tconst                            tt11823890
titleType                          tvEpisode
primaryTitle      Episode dated 6 March 2017
originalTitle     Episode dated 6 March 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2004448, dtype: object

(9,)

tconst                               tt11823892
titleType                             tvEpisode
primaryTitle      Episode dated 13 January 1954
originalTitle     Episode dated 13 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2004449, dtype: object

(9,)

tconst                     tt11823894
titleType                   tvEpisode
primaryTitle          Kasalan no more
originalTitle         Kasalan no more
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     26
genres            Crime,Drama,Romance
Name: 2004450, dtype: object

(9,)

tconst                  tt11823896
titleType                tvEpisode
primaryTitle        Episode #1.874
originalTitle       Episode #1.874
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004451, dtype: object

(9,)

tconst               tt11823898
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004452, dtype: object

(9,)

tconst                          tt1182389
titleType                       tvEpisode
primaryTitle      Bamses huskebog: Part 1
originalTitle     Bamses huskebog: Part 1
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2004453, dtype: object

(9,)

tconst               tt11823900
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004454, dtype: object

(9,)

tconst               tt11823902
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004455, dtype: object

(9,)

tconst               tt11823904
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004456, dtype: object

(9,)

tconst                  tt11823906
titleType                tvEpisode
primaryTitle        Episode #1.875
originalTitle       Episode #1.875
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004457, dtype: object

(9,)

tconst               tt11823908
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004458, dtype: object

(9,)

tconst                          tt1182390
titleType                       tvEpisode
primaryTitle      Bamses huskebog: Part 2
originalTitle     Bamses huskebog: Part 2
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2004459, dtype: object

(9,)

tconst               tt11823910
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004460, dtype: object

(9,)

tconst               tt11823912
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004461, dtype: object

(9,)

tconst               tt11823914
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004462, dtype: object

(9,)

tconst               tt11823916
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004463, dtype: object

(9,)

tconst               tt11823918
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004464, dtype: object

(9,)

tconst                          tt1182391
titleType                       tvEpisode
primaryTitle      Bamses huskebog: Part 3
originalTitle     Bamses huskebog: Part 3
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2004465, dtype: object

(9,)

tconst               tt11823920
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004466, dtype: object

(9,)

tconst                                    tt11823922
titleType                                      movie
primaryTitle      Timeless: A National Parks Odyssey
originalTitle     Timeless: A National Parks Odyssey
isAdult                                            0
startYear                                       2006
endYear                                           \N
runtimeMinutes                                    51
genres                                   Documentary
Name: 2004467, dtype: object

(9,)

tconst               tt11823924
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004468, dtype: object

(9,)

tconst               tt11823926
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004469, dtype: object

(9,)

tconst               tt11823928
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004470, dtype: object

(9,)

tconst                          tt1182392
titleType                       tvEpisode
primaryTitle      Bamses huskebog: Part 4
originalTitle     Bamses huskebog: Part 4
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2004471, dtype: object

(9,)

tconst               tt11823930
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004472, dtype: object

(9,)

tconst               tt11823932
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004473, dtype: object

(9,)

tconst               tt11823934
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004474, dtype: object

(9,)

tconst               tt11823936
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004475, dtype: object

(9,)

tconst               tt11823938
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2004476, dtype: object

(9,)

tconst                          tt1182393
titleType                       tvEpisode
primaryTitle      Bamses huskebog: Part 5
originalTitle     Bamses huskebog: Part 5
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2004477, dtype: object

(9,)

tconst             tt11823940
titleType               movie
primaryTitle      Wax is love
originalTitle     Wax is love
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             88
genres                  Drama
Name: 2004478, dtype: object

(9,)

tconst                tt11823942
titleType              tvEpisode
primaryTitle      Episode #1.961
originalTitle     Episode #1.961
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004479, dtype: object

(9,)

tconst                              tt11823944
titleType                            tvEpisode
primaryTitle      Episode dated 9 October 1970
originalTitle     Episode dated 9 October 1970
isAdult                                      0
startYear                                 1970
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2004480, dtype: object

(9,)

tconst                tt11823946
titleType              tvEpisode
primaryTitle      Episode #1.962
originalTitle     Episode #1.962
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004481, dtype: object

(9,)

tconst                tt11823948
titleType              tvEpisode
primaryTitle      Episode #1.964
originalTitle     Episode #1.964
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004482, dtype: object

(9,)

tconst                          tt1182394
titleType                       tvEpisode
primaryTitle      Bamses huskebog: Part 6
originalTitle     Bamses huskebog: Part 6
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2004483, dtype: object

(9,)

tconst                tt11823950
titleType              tvEpisode
primaryTitle      Episode #1.963
originalTitle     Episode #1.963
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004484, dtype: object

(9,)

tconst                tt11823952
titleType              tvEpisode
primaryTitle      Episode #1.965
originalTitle     Episode #1.965
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004485, dtype: object

(9,)

tconst                  tt11823954
titleType                tvEpisode
primaryTitle        Episode #1.876
originalTitle       Episode #1.876
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004486, dtype: object

(9,)

tconst                tt11823956
titleType              tvEpisode
primaryTitle      Episode #1.968
originalTitle     Episode #1.968
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004487, dtype: object

(9,)

tconst                tt11823958
titleType              tvEpisode
primaryTitle      Episode #1.966
originalTitle     Episode #1.966
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004488, dtype: object

(9,)

tconst                          tt1182395
titleType                       tvEpisode
primaryTitle      Bamses huskebog: Part 7
originalTitle     Bamses huskebog: Part 7
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2004489, dtype: object

(9,)

tconst                tt11823960
titleType              tvEpisode
primaryTitle      Episode #1.967
originalTitle     Episode #1.967
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004490, dtype: object

(9,)

tconst                tt11823962
titleType              tvEpisode
primaryTitle      Episode #1.969
originalTitle     Episode #1.969
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004491, dtype: object

(9,)

tconst                tt11823964
titleType              tvEpisode
primaryTitle      Episode #1.970
originalTitle     Episode #1.970
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004492, dtype: object

(9,)

tconst                tt11823966
titleType              tvEpisode
primaryTitle      Episode #1.971
originalTitle     Episode #1.971
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004493, dtype: object

(9,)

tconst                  tt11823968
titleType                tvEpisode
primaryTitle        Episode #1.877
originalTitle       Episode #1.877
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004494, dtype: object

(9,)

tconst                          tt1182396
titleType                       tvEpisode
primaryTitle      Bamses huskebog: Part 8
originalTitle     Bamses huskebog: Part 8
isAdult                                 0
startYear                            1989
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2004495, dtype: object

(9,)

tconst                tt11823970
titleType              tvEpisode
primaryTitle      Episode #1.973
originalTitle     Episode #1.973
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004496, dtype: object

(9,)

tconst                tt11823972
titleType              tvEpisode
primaryTitle      Episode #1.972
originalTitle     Episode #1.972
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004497, dtype: object

(9,)

tconst                tt11823974
titleType              tvEpisode
primaryTitle      Episode #1.975
originalTitle     Episode #1.975
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004498, dtype: object

(9,)

tconst                tt11823976
titleType              tvEpisode
primaryTitle      Episode #1.974
originalTitle     Episode #1.974
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004499, dtype: object

(9,)

tconst                tt11823978
titleType              tvEpisode
primaryTitle      Episode #1.977
originalTitle     Episode #1.977
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004500, dtype: object

(9,)

tconst               tt1182397
titleType            tvEpisode
primaryTitle      Sommerdansen
originalTitle     Sommerdansen
isAdult                      0
startYear                 1989
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2004501, dtype: object

(9,)

tconst                tt11823980
titleType              tvEpisode
primaryTitle      Episode #1.976
originalTitle     Episode #1.976
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004502, dtype: object

(9,)

tconst                  tt11823982
titleType                tvEpisode
primaryTitle        Episode #1.878
originalTitle       Episode #1.878
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004503, dtype: object

(9,)

tconst                             tt11823984
titleType                           tvEpisode
primaryTitle      Librarian - Clueless Expert
originalTitle     Librarian - Clueless Expert
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres                    Comedy,Drama,Sci-Fi
Name: 2004504, dtype: object

(9,)

tconst                tt11823986
titleType              tvEpisode
primaryTitle      Episode #1.978
originalTitle     Episode #1.978
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004505, dtype: object

(9,)

tconst                tt11823988
titleType              tvEpisode
primaryTitle      Episode #1.979
originalTitle     Episode #1.979
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004506, dtype: object

(9,)

tconst                                               tt1182398
titleType                                            tvEpisode
primaryTitle      Tænk hvis der kom nogen og boede i ens hytte
originalTitle     Tænk hvis der kom nogen og boede i ens hytte
isAdult                                                      0
startYear                                                 1989
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                  Family
Name: 2004507, dtype: object

(9,)

tconst                tt11823990
titleType              tvEpisode
primaryTitle      Episode #1.980
originalTitle     Episode #1.980
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004508, dtype: object

(9,)

tconst                  tt11823992
titleType                tvEpisode
primaryTitle        Episode #1.879
originalTitle       Episode #1.879
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004509, dtype: object

(9,)

tconst                tt11823994
titleType              tvEpisode
primaryTitle      Episode #1.742
originalTitle     Episode #1.742
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004510, dtype: object

(9,)

tconst                tt11823996
titleType              tvEpisode
primaryTitle      Episode #1.741
originalTitle     Episode #1.741
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004511, dtype: object

(9,)

tconst                tt11823998
titleType              tvEpisode
primaryTitle      Episode #1.744
originalTitle     Episode #1.744
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004512, dtype: object

(9,)

tconst                  tt1182399
titleType               tvEpisode
primaryTitle      Episode #1.4169
originalTitle     Episode #1.4169
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2004513, dtype: object

(9,)

tconst                tt11824000
titleType              tvEpisode
primaryTitle      Episode #1.743
originalTitle     Episode #1.743
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004514, dtype: object

(9,)

tconst                tt11824002
titleType              tvEpisode
primaryTitle      Episode #1.745
originalTitle     Episode #1.745
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004515, dtype: object

(9,)

tconst                tt11824004
titleType              tvEpisode
primaryTitle      Episode #1.747
originalTitle     Episode #1.747
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004516, dtype: object

(9,)

tconst                  tt11824006
titleType                tvEpisode
primaryTitle        Episode #1.880
originalTitle       Episode #1.880
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004517, dtype: object

(9,)

tconst                tt11824008
titleType              tvEpisode
primaryTitle      Episode #1.746
originalTitle     Episode #1.746
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004518, dtype: object

(9,)

tconst                  tt1182400
titleType               tvEpisode
primaryTitle      Episode #1.4170
originalTitle     Episode #1.4170
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2004519, dtype: object

(9,)

tconst                tt11824010
titleType              tvEpisode
primaryTitle      Episode #1.748
originalTitle     Episode #1.748
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004520, dtype: object

(9,)

tconst                tt11824012
titleType              tvEpisode
primaryTitle      Episode #1.749
originalTitle     Episode #1.749
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004521, dtype: object

(9,)

tconst                  tt11824014
titleType                tvEpisode
primaryTitle        Episode #1.881
originalTitle       Episode #1.881
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004522, dtype: object

(9,)

tconst                tt11824016
titleType              tvEpisode
primaryTitle      Episode #1.750
originalTitle     Episode #1.750
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004523, dtype: object

(9,)

tconst                  tt11824018
titleType                tvEpisode
primaryTitle        Episode #1.882
originalTitle       Episode #1.882
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004524, dtype: object

(9,)

tconst                  tt1182401
titleType               tvEpisode
primaryTitle      Episode #1.4171
originalTitle     Episode #1.4171
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2004525, dtype: object

(9,)

tconst                tt11824020
titleType              tvEpisode
primaryTitle      Episode #1.751
originalTitle     Episode #1.751
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004526, dtype: object

(9,)

tconst                tt11824022
titleType              tvEpisode
primaryTitle      Episode #1.752
originalTitle     Episode #1.752
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004527, dtype: object

(9,)

tconst                tt11824024
titleType              tvEpisode
primaryTitle      Episode #1.753
originalTitle     Episode #1.753
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004528, dtype: object

(9,)

tconst                tt11824026
titleType              tvEpisode
primaryTitle      Episode #1.754
originalTitle     Episode #1.754
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004529, dtype: object

(9,)

tconst                tt11824028
titleType              tvEpisode
primaryTitle      Episode #1.756
originalTitle     Episode #1.756
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004530, dtype: object

(9,)

tconst                  tt1182402
titleType               tvEpisode
primaryTitle      Episode #1.4172
originalTitle     Episode #1.4172
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2004531, dtype: object

(9,)

tconst                tt11824030
titleType              tvEpisode
primaryTitle      Episode #1.755
originalTitle     Episode #1.755
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004532, dtype: object

(9,)

tconst                tt11824032
titleType              tvEpisode
primaryTitle      Episode #1.757
originalTitle     Episode #1.757
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004533, dtype: object

(9,)

tconst                tt11824034
titleType              tvEpisode
primaryTitle      Episode #1.758
originalTitle     Episode #1.758
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004534, dtype: object

(9,)

tconst                tt11824036
titleType              tvEpisode
primaryTitle      Episode #1.759
originalTitle     Episode #1.759
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004535, dtype: object

(9,)

tconst                tt11824038
titleType              tvEpisode
primaryTitle      Episode #1.760
originalTitle     Episode #1.760
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004536, dtype: object

(9,)

tconst                tt1182403
titleType             tvEpisode
primaryTitle      Episode #34.2
originalTitle     Episode #34.2
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes              120
genres                Game-Show
Name: 2004537, dtype: object

(9,)

tconst                tt11824040
titleType              tvEpisode
primaryTitle      Episode #1.581
originalTitle     Episode #1.581
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004538, dtype: object

(9,)

tconst                tt11824042
titleType              tvEpisode
primaryTitle      Episode #1.583
originalTitle     Episode #1.583
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004539, dtype: object

(9,)

tconst              tt11824044
titleType            tvEpisode
primaryTitle      Final Battle
originalTitle     Final Battle
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              21
genres                   Drama
Name: 2004540, dtype: object

(9,)

tconst                tt11824046
titleType              tvEpisode
primaryTitle      Episode #1.582
originalTitle     Episode #1.582
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004541, dtype: object

(9,)

tconst                tt11824048
titleType              tvEpisode
primaryTitle      Episode #1.584
originalTitle     Episode #1.584
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004542, dtype: object

(9,)

tconst                tt1182404
titleType             tvEpisode
primaryTitle      Episode #34.3
originalTitle     Episode #34.3
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes              120
genres                Game-Show
Name: 2004543, dtype: object

(9,)

tconst                tt11824050
titleType              tvEpisode
primaryTitle      Episode #1.585
originalTitle     Episode #1.585
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004544, dtype: object

(9,)

tconst                     tt11824052
titleType                       short
primaryTitle               Gloop Girl
originalTitle              Gloop Girl
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Horror,Short
Name: 2004545, dtype: object

(9,)

tconst                tt11824054
titleType              tvEpisode
primaryTitle      Episode #1.586
originalTitle     Episode #1.586
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004546, dtype: object

(9,)

tconst                tt11824056
titleType              tvEpisode
primaryTitle      Episode #1.587
originalTitle     Episode #1.587
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004547, dtype: object

(9,)

tconst                     tt11824058
titleType                   tvEpisode
primaryTitle      Kang Yi Shi Lu Pt.1
originalTitle     Kang Yi Shi Lu Pt.1
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     59
genres                    Documentary
Name: 2004548, dtype: object

(9,)

tconst                tt1182405
titleType             tvEpisode
primaryTitle      Episode #34.4
originalTitle     Episode #34.4
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes              120
genres                Game-Show
Name: 2004549, dtype: object

(9,)

tconst                tt11824060
titleType              tvEpisode
primaryTitle      Episode #1.588
originalTitle     Episode #1.588
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004550, dtype: object

(9,)

tconst                tt11824062
titleType              tvEpisode
primaryTitle      Episode #1.589
originalTitle     Episode #1.589
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004551, dtype: object

(9,)

tconst                             tt11824064
titleType                               short
primaryTitle      Man, I Feel Like a Wrangler
originalTitle     Man, I Feel Like a Wrangler
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                              4
genres                                  Short
Name: 2004552, dtype: object

(9,)

tconst                tt11824066
titleType              tvEpisode
primaryTitle      Episode #1.590
originalTitle     Episode #1.590
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004553, dtype: object

(9,)

tconst                tt11824068
titleType              tvEpisode
primaryTitle      Episode #1.591
originalTitle     Episode #1.591
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004554, dtype: object

(9,)

tconst                tt1182406
titleType             tvEpisode
primaryTitle      Episode #34.5
originalTitle     Episode #34.5
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes              120
genres                Game-Show
Name: 2004555, dtype: object

(9,)

tconst                tt11824070
titleType              tvEpisode
primaryTitle      Episode #1.592
originalTitle     Episode #1.592
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004556, dtype: object

(9,)

tconst                tt11824072
titleType              tvEpisode
primaryTitle      Episode #1.593
originalTitle     Episode #1.593
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004557, dtype: object

(9,)

tconst                tt11824074
titleType              tvEpisode
primaryTitle      Episode #1.594
originalTitle     Episode #1.594
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004558, dtype: object

(9,)

tconst                tt11824076
titleType              tvEpisode
primaryTitle      Episode #1.596
originalTitle     Episode #1.596
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004559, dtype: object

(9,)

tconst                tt11824078
titleType              tvEpisode
primaryTitle      Episode #1.595
originalTitle     Episode #1.595
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004560, dtype: object

(9,)

tconst                tt1182407
titleType             tvEpisode
primaryTitle      Episode #34.6
originalTitle     Episode #34.6
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes              120
genres                Game-Show
Name: 2004561, dtype: object

(9,)

tconst                tt11824080
titleType              tvEpisode
primaryTitle      Episode #1.598
originalTitle     Episode #1.598
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004562, dtype: object

(9,)

tconst                tt11824082
titleType              tvEpisode
primaryTitle      Episode #1.597
originalTitle     Episode #1.597
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004563, dtype: object

(9,)

tconst                            tt11824084
titleType                          tvEpisode
primaryTitle                       Zacchaeus
originalTitle                      Zacchaeus
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Adventure,Animation,Family
Name: 2004564, dtype: object

(9,)

tconst                tt11824086
titleType              tvEpisode
primaryTitle      Episode #1.599
originalTitle     Episode #1.599
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004565, dtype: object

(9,)

tconst                tt11824088
titleType              tvEpisode
primaryTitle      Episode #1.600
originalTitle     Episode #1.600
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004566, dtype: object

(9,)

tconst                  tt1182408
titleType               tvEpisode
primaryTitle      Episode #1.1602
originalTitle     Episode #1.1602
isAdult                         0
startYear                    1993
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004567, dtype: object

(9,)

tconst                tt11824090
titleType              tvEpisode
primaryTitle      Episode #1.301
originalTitle     Episode #1.301
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004568, dtype: object

(9,)

tconst                tt11824092
titleType              tvEpisode
primaryTitle      Episode #1.302
originalTitle     Episode #1.302
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004569, dtype: object

(9,)

tconst                                         tt11824094
titleType                                       tvEpisode
primaryTitle      Antichronicles - Chronologies: The Omen
originalTitle     Antichronicles - Chronologies: The Omen
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                             Comedy
Name: 2004570, dtype: object

(9,)

tconst                tt11824096
titleType              tvEpisode
primaryTitle      Episode #1.304
originalTitle     Episode #1.304
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004571, dtype: object

(9,)

tconst                tt11824098
titleType              tvEpisode
primaryTitle      Episode #1.303
originalTitle     Episode #1.303
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004572, dtype: object

(9,)

tconst                  tt1182409
titleType               tvEpisode
primaryTitle      Episode #1.2448
originalTitle     Episode #1.2448
isAdult                         0
startYear                    1996
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004573, dtype: object

(9,)

tconst                tt11824100
titleType              tvEpisode
primaryTitle      Episode #1.305
originalTitle     Episode #1.305
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004574, dtype: object

(9,)

tconst                tt11824102
titleType              tvEpisode
primaryTitle      Episode #1.306
originalTitle     Episode #1.306
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004575, dtype: object

(9,)

tconst                tt11824104
titleType              tvEpisode
primaryTitle      Episode #1.307
originalTitle     Episode #1.307
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004576, dtype: object

(9,)

tconst                tt11824106
titleType              tvEpisode
primaryTitle      Episode #1.308
originalTitle     Episode #1.308
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004577, dtype: object

(9,)

tconst                tt11824108
titleType              tvEpisode
primaryTitle      Episode #1.309
originalTitle     Episode #1.309
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004578, dtype: object

(9,)

tconst                  tt1182410
titleType               tvEpisode
primaryTitle      Episode #1.2449
originalTitle     Episode #1.2449
isAdult                         0
startYear                    1996
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004579, dtype: object

(9,)

tconst               tt11824110
titleType             tvEpisode
primaryTitle      Episode #4.89
originalTitle     Episode #4.89
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2004580, dtype: object

(9,)

tconst                tt11824112
titleType              tvEpisode
primaryTitle      Episode #1.310
originalTitle     Episode #1.310
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004581, dtype: object

(9,)

tconst                tt11824114
titleType              tvEpisode
primaryTitle      Episode #1.311
originalTitle     Episode #1.311
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004582, dtype: object

(9,)

tconst                tt11824116
titleType              tvEpisode
primaryTitle      Episode #1.312
originalTitle     Episode #1.312
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004583, dtype: object

(9,)

tconst                tt11824118
titleType              tvEpisode
primaryTitle      Episode #1.313
originalTitle     Episode #1.313
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004584, dtype: object

(9,)

tconst                  tt1182411
titleType               tvEpisode
primaryTitle      Episode #1.2454
originalTitle     Episode #1.2454
isAdult                         0
startYear                    1997
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004585, dtype: object

(9,)

tconst                tt11824120
titleType              tvEpisode
primaryTitle      Episode #1.314
originalTitle     Episode #1.314
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004586, dtype: object

(9,)

tconst                tt11824122
titleType              tvEpisode
primaryTitle      Episode #1.315
originalTitle     Episode #1.315
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004587, dtype: object

(9,)

tconst                tt11824124
titleType              tvEpisode
primaryTitle      Episode #1.316
originalTitle     Episode #1.316
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004588, dtype: object

(9,)

tconst                tt11824126
titleType              tvEpisode
primaryTitle      Episode #1.317
originalTitle     Episode #1.317
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004589, dtype: object

(9,)

tconst            tt11824128
titleType              movie
primaryTitle           Tribe
originalTitle          Tribe
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2004590, dtype: object

(9,)

tconst                  tt1182412
titleType               tvEpisode
primaryTitle      Episode #1.2456
originalTitle     Episode #1.2456
isAdult                         0
startYear                    1997
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004591, dtype: object

(9,)

tconst                tt11824130
titleType              tvEpisode
primaryTitle      Episode #1.318
originalTitle     Episode #1.318
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004592, dtype: object

(9,)

tconst                tt11824132
titleType              tvEpisode
primaryTitle      Episode #1.319
originalTitle     Episode #1.319
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004593, dtype: object

(9,)

tconst            tt11824134
titleType              movie
primaryTitle        Seishojo
originalTitle       Seishojo
isAdult                    0
startYear               1936
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2004594, dtype: object

(9,)

tconst                tt11824136
titleType              tvEpisode
primaryTitle      Episode #1.320
originalTitle     Episode #1.320
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004595, dtype: object

(9,)

tconst                tt11824138
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004596, dtype: object

(9,)

tconst                  tt1182413
titleType               tvEpisode
primaryTitle      Episode #1.2458
originalTitle     Episode #1.2458
isAdult                         0
startYear                    1997
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004597, dtype: object

(9,)

tconst                tt11824140
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004598, dtype: object

(9,)

tconst                tt11824142
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004599, dtype: object

(9,)

tconst                tt11824144
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004600, dtype: object

(9,)

tconst                tt11824146
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004601, dtype: object

(9,)

tconst                tt11824148
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004602, dtype: object

(9,)

tconst                                tt1182414
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                    Family,News,Talk-Show
Name: 2004603, dtype: object

(9,)

tconst                tt11824150
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004604, dtype: object

(9,)

tconst                tt11824152
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004605, dtype: object

(9,)

tconst                tt11824154
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004606, dtype: object

(9,)

tconst                tt11824156
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004607, dtype: object

(9,)

tconst                tt11824158
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004608, dtype: object

(9,)

tconst                                tt1182415
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                    Family,News,Talk-Show
Name: 2004609, dtype: object

(9,)

tconst                tt11824160
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004610, dtype: object

(9,)

tconst                tt11824162
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004611, dtype: object

(9,)

tconst                tt11824164
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004612, dtype: object

(9,)

tconst                tt11824166
titleType              tvEpisode
primaryTitle      Episode #1.115
originalTitle     Episode #1.115
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004613, dtype: object

(9,)

tconst                tt11824168
titleType              tvEpisode
primaryTitle      Episode #1.116
originalTitle     Episode #1.116
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004614, dtype: object

(9,)

tconst                                tt1182416
titleType                             tvEpisode
primaryTitle      Episode dated 23 January 2008
originalTitle     Episode dated 23 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                        Comedy,Music,News
Name: 2004615, dtype: object

(9,)

tconst                tt11824170
titleType              tvEpisode
primaryTitle      Episode #1.117
originalTitle     Episode #1.117
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004616, dtype: object

(9,)

tconst                tt11824172
titleType              tvEpisode
primaryTitle      Episode #1.118
originalTitle     Episode #1.118
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004617, dtype: object

(9,)

tconst                tt11824174
titleType              tvEpisode
primaryTitle      Episode #1.119
originalTitle     Episode #1.119
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004618, dtype: object

(9,)

tconst                tt11824176
titleType              tvEpisode
primaryTitle      Episode #1.120
originalTitle     Episode #1.120
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004619, dtype: object

(9,)

tconst               tt1182417
titleType            tvEpisode
primaryTitle      Baile mortal
originalTitle     Baile mortal
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2004620, dtype: object

(9,)

tconst                tt11824180
titleType              tvEpisode
primaryTitle      Episode #1.141
originalTitle     Episode #1.141
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004621, dtype: object

(9,)

tconst                              tt11824182
titleType                                video
primaryTitle      Fleetwood Mac: Seven Wonders
originalTitle     Fleetwood Mac: Seven Wonders
isAdult                                      0
startYear                                 1987
endYear                                     \N
runtimeMinutes                               4
genres                             Music,Short
Name: 2004622, dtype: object

(9,)

tconst                               tt11824184
titleType                             tvEpisode
primaryTitle      Episode dated 14 January 1954
originalTitle     Episode dated 14 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2004623, dtype: object

(9,)

tconst                                                   tt11824186
titleType                                                     short
primaryTitle      People Are Only Interesting When You Get to Kn...
originalTitle     People Are Only Interesting When You Get to Kn...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    9
genres                                                 Comedy,Short
Name: 2004624, dtype: object

(9,)

tconst                   tt11824188
titleType                 tvEpisode
primaryTitle      Festival of India
originalTitle     Festival of India
isAdult                           0
startYear                        \N
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2004625, dtype: object

(9,)

tconst                     tt1182418
titleType                  tvEpisode
primaryTitle      Buscando problemas
originalTitle     Buscando problemas
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres                    Reality-TV
Name: 2004626, dtype: object

(9,)

tconst                tt11824190
titleType              tvEpisode
primaryTitle      Episode #1.143
originalTitle     Episode #1.143
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004627, dtype: object

(9,)

tconst                tt11824192
titleType              tvEpisode
primaryTitle      Episode #1.142
originalTitle     Episode #1.142
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004628, dtype: object

(9,)

tconst                tt11824194
titleType              tvEpisode
primaryTitle      Episode #1.144
originalTitle     Episode #1.144
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004629, dtype: object

(9,)

tconst                               tt11824196
titleType                             tvEpisode
primaryTitle      Episode dated 15 January 1954
originalTitle     Episode dated 15 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2004630, dtype: object

(9,)

tconst                tt11824198
titleType              tvEpisode
primaryTitle      Episode #1.145
originalTitle     Episode #1.145
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004631, dtype: object

(9,)

tconst                         tt1182419
titleType                      tvEpisode
primaryTitle      El nombre se llama sky
originalTitle     El nombre se llama sky
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres                        Reality-TV
Name: 2004632, dtype: object

(9,)

tconst                tt11824200
titleType              tvEpisode
primaryTitle      Episode #1.146
originalTitle     Episode #1.146
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004633, dtype: object

(9,)

tconst                tt11824202
titleType              tvEpisode
primaryTitle      Episode #1.147
originalTitle     Episode #1.147
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004634, dtype: object

(9,)

tconst            tt11824204
titleType          tvEpisode
primaryTitle          Onward
originalTitle         Onward
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2004635, dtype: object

(9,)

tconst                tt11824206
titleType              tvEpisode
primaryTitle      Episode #1.148
originalTitle     Episode #1.148
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004636, dtype: object

(9,)

tconst                tt11824208
titleType              tvEpisode
primaryTitle      Episode #1.150
originalTitle     Episode #1.150
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004637, dtype: object

(9,)

tconst                               tt1182420
titleType                            tvEpisode
primaryTitle      Episode dated 7 January 2008
originalTitle     Episode dated 7 January 2008
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                    News
Name: 2004638, dtype: object

(9,)

tconst                         tt11824210
titleType                           video
primaryTitle      Fleetwood Mac: Oh Diane
originalTitle     Fleetwood Mac: Oh Diane
isAdult                                 0
startYear                            1982
endYear                                \N
runtimeMinutes                          3
genres                        Music,Short
Name: 2004639, dtype: object

(9,)

tconst                tt11824212
titleType              tvEpisode
primaryTitle      Episode #1.149
originalTitle     Episode #1.149
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004640, dtype: object

(9,)

tconst                tt11824214
titleType              tvEpisode
primaryTitle      Episode #1.152
originalTitle     Episode #1.152
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004641, dtype: object

(9,)

tconst                tt11824216
titleType              tvEpisode
primaryTitle      Episode #1.151
originalTitle     Episode #1.151
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004642, dtype: object

(9,)

tconst                      tt11824218
titleType                     tvSeries
primaryTitle      Meet the Richardsons
originalTitle     Meet the Richardsons
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      40
genres                          Comedy
Name: 2004643, dtype: object

(9,)

tconst                 tt1182421
titleType              tvEpisode
primaryTitle      Episode #1.209
originalTitle     Episode #1.209
isAdult                        0
startYear                   2001
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004644, dtype: object

(9,)

tconst                tt11824220
titleType              tvEpisode
primaryTitle      Episode #1.153
originalTitle     Episode #1.153
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004645, dtype: object

(9,)

tconst                      tt11824222
titleType                        short
primaryTitle             Second Chance
originalTitle            Second Chance
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Romance,Short
Name: 2004646, dtype: object

(9,)

tconst                tt11824224
titleType              tvEpisode
primaryTitle      Episode #1.154
originalTitle     Episode #1.154
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004647, dtype: object

(9,)

tconst                tt11824226
titleType              tvEpisode
primaryTitle      Episode #1.155
originalTitle     Episode #1.155
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004648, dtype: object

(9,)

tconst                tt11824228
titleType              tvEpisode
primaryTitle      Episode #1.156
originalTitle     Episode #1.156
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004649, dtype: object

(9,)

tconst                        tt1182422
titleType                     tvEpisode
primaryTitle              Chris Wallace
originalTitle             Chris Wallace
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       21
genres            Comedy,News,Talk-Show
Name: 2004650, dtype: object

(9,)

tconst                tt11824230
titleType              tvEpisode
primaryTitle      Episode #1.157
originalTitle     Episode #1.157
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004651, dtype: object

(9,)

tconst                tt11824232
titleType              tvEpisode
primaryTitle      Episode #1.158
originalTitle     Episode #1.158
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004652, dtype: object

(9,)

tconst                tt11824234
titleType              tvEpisode
primaryTitle      Episode #1.160
originalTitle     Episode #1.160
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004653, dtype: object

(9,)

tconst                                 tt11824236
titleType                               tvEpisode
primaryTitle      Meteorologist - Clueless Expert
originalTitle     Meteorologist - Clueless Expert
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 \N
genres                        Comedy,Drama,Sci-Fi
Name: 2004654, dtype: object

(9,)

tconst                tt11824238
titleType              tvEpisode
primaryTitle      Episode #1.159
originalTitle     Episode #1.159
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2004655, dtype: object

(9,)

tconst                         tt1182423
titleType                      tvEpisode
primaryTitle                Episode #7.7
originalTitle               Episode #7.7
isAdult                                0
startYear                           2007
endYear                               \N
runtimeMinutes                        \N
genres            Family,Game-Show,Music
Name: 2004656, dtype: object

(9,)

tconst                              tt11824240
titleType                            tvEpisode
primaryTitle      The Lighthouse - Enchantment
originalTitle     The Lighthouse - Enchantment
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                               3
genres                  Action,Adventure,Drama
Name: 2004657, dtype: object

(9,)

tconst                      tt11824242
titleType                        video
primaryTitle      Fleetwood Mac: Gypsy
originalTitle     Fleetwood Mac: Gypsy
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                       5
genres                     Music,Short
Name: 2004658, dtype: object

(9,)

tconst                tt11824244
titleType              tvEpisode
primaryTitle      Episode #1.341
originalTitle     Episode #1.341
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004659, dtype: object

(9,)

tconst                tt11824246
titleType              tvEpisode
primaryTitle      Episode #1.342
originalTitle     Episode #1.342
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004660, dtype: object

(9,)

tconst                tt11824248
titleType              tvEpisode
primaryTitle      Episode #1.343
originalTitle     Episode #1.343
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004661, dtype: object

(9,)

tconst                         tt1182424
titleType                      tvEpisode
primaryTitle                Episode #7.8
originalTitle               Episode #7.8
isAdult                                0
startYear                           2007
endYear                               \N
runtimeMinutes                        \N
genres            Family,Game-Show,Music
Name: 2004662, dtype: object

(9,)

tconst                tt11824250
titleType              tvEpisode
primaryTitle      Episode #1.344
originalTitle     Episode #1.344
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004663, dtype: object

(9,)

tconst                tt11824252
titleType              tvEpisode
primaryTitle      Episode #1.346
originalTitle     Episode #1.346
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004664, dtype: object

(9,)

tconst                tt11824254
titleType              tvEpisode
primaryTitle      Episode #1.345
originalTitle     Episode #1.345
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004665, dtype: object

(9,)

tconst                        tt11824256
titleType                          video
primaryTitle      Fleetwood Mac: Hold Me
originalTitle     Fleetwood Mac: Hold Me
isAdult                                0
startYear                           1981
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2004666, dtype: object

(9,)

tconst                tt11824258
titleType              tvEpisode
primaryTitle      Episode #1.348
originalTitle     Episode #1.348
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004667, dtype: object

(9,)

tconst                  tt1182425
titleType               tvEpisode
primaryTitle      Episode #1.9601
originalTitle     Episode #1.9601
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004668, dtype: object

(9,)

tconst                tt11824260
titleType              tvEpisode
primaryTitle      Episode #1.349
originalTitle     Episode #1.349
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004669, dtype: object

(9,)

tconst                tt11824262
titleType              tvEpisode
primaryTitle      Episode #1.347
originalTitle     Episode #1.347
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004670, dtype: object

(9,)

tconst                  tt11824264
titleType                tvEpisode
primaryTitle        Episode #1.883
originalTitle       Episode #1.883
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004671, dtype: object

(9,)

tconst                tt11824266
titleType              tvEpisode
primaryTitle      Episode #1.350
originalTitle     Episode #1.350
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004672, dtype: object

(9,)

tconst                tt11824268
titleType              tvEpisode
primaryTitle      Episode #1.351
originalTitle     Episode #1.351
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004673, dtype: object

(9,)

tconst                                tt1182426
titleType                             tvEpisode
primaryTitle      Episode dated 27 January 2006
originalTitle     Episode dated 27 January 2006
isAdult                                       0
startYear                                  2006
endYear                                      \N
runtimeMinutes                               \N
genres                      Crime,Drama,Romance
Name: 2004674, dtype: object

(9,)

tconst                tt11824270
titleType              tvEpisode
primaryTitle      Episode #1.352
originalTitle     Episode #1.352
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004675, dtype: object

(9,)

tconst                tt11824272
titleType              tvEpisode
primaryTitle      Episode #1.353
originalTitle     Episode #1.353
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004676, dtype: object

(9,)

tconst                  tt11824274
titleType                tvEpisode
primaryTitle        Episode #1.884
originalTitle       Episode #1.884
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004677, dtype: object

(9,)

tconst                  tt11824276
titleType                tvEpisode
primaryTitle        Episode #1.885
originalTitle       Episode #1.885
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004678, dtype: object

(9,)

tconst                     tt11824278
titleType                       video
primaryTitle      Fleetwood Mac: Tusk
originalTitle     Fleetwood Mac: Tusk
isAdult                             0
startYear                        1978
endYear                            \N
runtimeMinutes                      3
genres                    Music,Short
Name: 2004679, dtype: object

(9,)

tconst                                tt1182427
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2004680, dtype: object

(9,)

tconst                tt11824280
titleType              tvEpisode
primaryTitle      Episode #1.355
originalTitle     Episode #1.355
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004681, dtype: object

(9,)

tconst                tt11824282
titleType              tvEpisode
primaryTitle      Episode #1.354
originalTitle     Episode #1.354
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004682, dtype: object

(9,)

tconst                tt11824284
titleType              tvEpisode
primaryTitle      Episode #1.356
originalTitle     Episode #1.356
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004683, dtype: object

(9,)

tconst                tt11824286
titleType              tvEpisode
primaryTitle      Episode #1.357
originalTitle     Episode #1.357
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004684, dtype: object

(9,)

tconst                    tt11824288
titleType                      short
primaryTitle      Razas, primer acto
originalTitle     Razas, primer acto
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    15
genres             Documentary,Short
Name: 2004685, dtype: object

(9,)

tconst                                tt1182428
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2004686, dtype: object

(9,)

tconst                     tt11824290
titleType                       video
primaryTitle      Fleetwood Mac: Sara
originalTitle     Fleetwood Mac: Sara
isAdult                             0
startYear                        1979
endYear                            \N
runtimeMinutes                      4
genres                    Music,Short
Name: 2004687, dtype: object

(9,)

tconst                  tt11824292
titleType                tvEpisode
primaryTitle        Episode #1.886
originalTitle       Episode #1.886
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004688, dtype: object

(9,)

tconst                tt11824294
titleType              tvEpisode
primaryTitle      Episode #1.359
originalTitle     Episode #1.359
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004689, dtype: object

(9,)

tconst                tt11824296
titleType              tvEpisode
primaryTitle      Episode #1.358
originalTitle     Episode #1.358
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004690, dtype: object

(9,)

tconst                tt11824298
titleType              tvEpisode
primaryTitle      Episode #1.360
originalTitle     Episode #1.360
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004691, dtype: object

(9,)

tconst                  tt1182429
titleType               tvEpisode
primaryTitle      Episode #1.3703
originalTitle     Episode #1.3703
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2004692, dtype: object

(9,)

tconst                  tt11824300
titleType                tvEpisode
primaryTitle        Episode #1.887
originalTitle       Episode #1.887
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004693, dtype: object

(9,)

tconst            tt11824302
titleType          tvEpisode
primaryTitle      Invitation
originalTitle     Invitation
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            30
genres                 Drama
Name: 2004694, dtype: object

(9,)

tconst                  tt11824304
titleType                tvEpisode
primaryTitle        Episode #1.888
originalTitle       Episode #1.888
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004695, dtype: object

(9,)

tconst             tt11824306
titleType               short
primaryTitle          Celaine
originalTitle         Celaine
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2004696, dtype: object

(9,)

tconst                                tt11824308
titleType                                  video
primaryTitle      Fleetwood Mac: Go Your Own Way
originalTitle     Fleetwood Mac: Go Your Own Way
isAdult                                        0
startYear                                   1977
endYear                                       \N
runtimeMinutes                                 4
genres                               Music,Short
Name: 2004697, dtype: object

(9,)

tconst                  tt1182430
titleType               tvEpisode
primaryTitle      Episode #1.3704
originalTitle     Episode #1.3704
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2004698, dtype: object

(9,)

tconst                  tt11824310
titleType                tvEpisode
primaryTitle        Episode #1.889
originalTitle       Episode #1.889
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004699, dtype: object

(9,)

tconst                  tt11824312
titleType                tvEpisode
primaryTitle        Episode #1.890
originalTitle       Episode #1.890
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004700, dtype: object

(9,)

tconst                  tt11824314
titleType                tvEpisode
primaryTitle        Episode #1.891
originalTitle       Episode #1.891
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004701, dtype: object

(9,)

tconst                 tt11824316
titleType                   short
primaryTitle      Northern Malady
originalTitle     Northern Malady
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 28
genres              Mystery,Short
Name: 2004702, dtype: object

(9,)

tconst                  tt11824318
titleType                tvEpisode
primaryTitle        Episode #1.892
originalTitle       Episode #1.892
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004703, dtype: object

(9,)

tconst                 tt1182431
titleType              tvEpisode
primaryTitle       Episode #1.13
originalTitle      Episode #1.13
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2004704, dtype: object

(9,)

tconst                          tt11824320
titleType                            video
primaryTitle      Fleetwood Mac: Dragonfly
originalTitle     Fleetwood Mac: Dragonfly
isAdult                                  0
startYear                             1971
endYear                                 \N
runtimeMinutes                           3
genres                         Music,Short
Name: 2004705, dtype: object

(9,)

tconst                  tt11824322
titleType                tvEpisode
primaryTitle        Episode #1.893
originalTitle       Episode #1.893
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004706, dtype: object

(9,)

tconst              tt11824324
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004707, dtype: object

(9,)

tconst                tt11824326
titleType              tvEpisode
primaryTitle      Episode #1.141
originalTitle     Episode #1.141
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004708, dtype: object

(9,)

tconst                                 tt11824328
titleType                                   video
primaryTitle      Fleetwood Mac: Man of the World
originalTitle     Fleetwood Mac: Man of the World
isAdult                                         0
startYear                                    1969
endYear                                        \N
runtimeMinutes                                  3
genres                                Music,Short
Name: 2004709, dtype: object

(9,)

tconst                      tt1182432
titleType                   tvEpisode
primaryTitle         Episode #1.10551
originalTitle        Episode #1.10551
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004710, dtype: object

(9,)

tconst                  tt11824330
titleType                tvEpisode
primaryTitle        Episode #1.894
originalTitle       Episode #1.894
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004711, dtype: object

(9,)

tconst                tt11824332
titleType              tvEpisode
primaryTitle      Episode #1.142
originalTitle     Episode #1.142
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004712, dtype: object

(9,)

tconst                tt11824334
titleType              tvEpisode
primaryTitle      Episode #1.143
originalTitle     Episode #1.143
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004713, dtype: object

(9,)

tconst                tt11824336
titleType              tvEpisode
primaryTitle      Episode #1.144
originalTitle     Episode #1.144
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004714, dtype: object

(9,)

tconst                  tt11824338
titleType                tvEpisode
primaryTitle        Episode #1.895
originalTitle       Episode #1.895
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004715, dtype: object

(9,)

tconst                      tt1182433
titleType                   tvEpisode
primaryTitle         Episode #1.10552
originalTitle        Episode #1.10552
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004716, dtype: object

(9,)

tconst              tt11824340
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004717, dtype: object

(9,)

tconst                tt11824342
titleType              tvEpisode
primaryTitle      Episode #1.146
originalTitle     Episode #1.146
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004718, dtype: object

(9,)

tconst                tt11824344
titleType              tvEpisode
primaryTitle      Episode #1.145
originalTitle     Episode #1.145
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004719, dtype: object

(9,)

tconst                tt11824346
titleType              tvEpisode
primaryTitle      Episode #1.147
originalTitle     Episode #1.147
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004720, dtype: object

(9,)

tconst                tt11824348
titleType              tvEpisode
primaryTitle      Episode #1.148
originalTitle     Episode #1.148
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004721, dtype: object

(9,)

tconst                      tt1182434
titleType                   tvEpisode
primaryTitle         Episode #1.10555
originalTitle        Episode #1.10555
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004722, dtype: object

(9,)

tconst                tt11824350
titleType              tvEpisode
primaryTitle      Episode #1.149
originalTitle     Episode #1.149
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004723, dtype: object

(9,)

tconst                  tt11824352
titleType                tvEpisode
primaryTitle      Invasion: Part 2
originalTitle     Invasion: Part 2
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2004724, dtype: object

(9,)

tconst              tt11824354
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004725, dtype: object

(9,)

tconst                tt11824356
titleType              tvEpisode
primaryTitle      Episode #1.150
originalTitle     Episode #1.150
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004726, dtype: object

(9,)

tconst                  tt11824358
titleType                    short
primaryTitle      The Bandaged Man
originalTitle     The Bandaged Man
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                   2
genres                Horror,Short
Name: 2004727, dtype: object

(9,)

tconst                      tt1182435
titleType                   tvEpisode
primaryTitle         Episode #1.10557
originalTitle        Episode #1.10557
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004728, dtype: object

(9,)

tconst                tt11824360
titleType              tvEpisode
primaryTitle      Episode #1.151
originalTitle     Episode #1.151
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004729, dtype: object

(9,)

tconst                tt11824362
titleType              tvEpisode
primaryTitle      Episode #1.152
originalTitle     Episode #1.152
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004730, dtype: object

(9,)

tconst                  tt11824364
titleType                tvEpisode
primaryTitle        Episode #1.896
originalTitle       Episode #1.896
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004731, dtype: object

(9,)

tconst                tt11824366
titleType              tvEpisode
primaryTitle      Episode #1.153
originalTitle     Episode #1.153
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004732, dtype: object

(9,)

tconst              tt11824368
titleType                short
primaryTitle      Couple Exigé
originalTitle     Couple Exigé
isAdult                      0
startYear                 2014
endYear                     \N
runtimeMinutes              \N
genres                   Short
Name: 2004733, dtype: object

(9,)

tconst                      tt1182436
titleType                   tvEpisode
primaryTitle         Episode #1.10558
originalTitle        Episode #1.10558
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004734, dtype: object

(9,)

tconst                tt11824370
titleType              tvEpisode
primaryTitle      Episode #1.154
originalTitle     Episode #1.154
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004735, dtype: object

(9,)

tconst                tt11824372
titleType              tvEpisode
primaryTitle      Episode #1.155
originalTitle     Episode #1.155
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004736, dtype: object

(9,)

tconst            tt11824374
titleType              short
primaryTitle      Separation
originalTitle     Separation
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes             7
genres                 Short
Name: 2004737, dtype: object

(9,)

tconst              tt11824376
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004738, dtype: object

(9,)

tconst                tt11824378
titleType              tvEpisode
primaryTitle      Episode #1.156
originalTitle     Episode #1.156
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004739, dtype: object

(9,)

tconst                      tt1182437
titleType                   tvEpisode
primaryTitle         Episode #1.10559
originalTitle        Episode #1.10559
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004740, dtype: object

(9,)

tconst                  tt11824380
titleType                tvEpisode
primaryTitle        Episode #1.897
originalTitle       Episode #1.897
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004741, dtype: object

(9,)

tconst                tt11824382
titleType              tvEpisode
primaryTitle      Episode #1.157
originalTitle     Episode #1.157
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004742, dtype: object

(9,)

tconst                tt11824384
titleType              tvEpisode
primaryTitle      Episode #1.158
originalTitle     Episode #1.158
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004743, dtype: object

(9,)

tconst                  tt11824386
titleType                tvEpisode
primaryTitle        Episode #1.898
originalTitle       Episode #1.898
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2004744, dtype: object

(9,)

tconst                tt11824388
titleType              tvEpisode
primaryTitle      Episode #1.159
originalTitle     Episode #1.159
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004745, dtype: object

(9,)

tconst                      tt1182438
titleType                   tvEpisode
primaryTitle         Episode #1.10560
originalTitle        Episode #1.10560
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004746, dtype: object

(9,)

tconst                tt11824390
titleType              tvEpisode
primaryTitle      Episode #1.160
originalTitle     Episode #1.160
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004747, dtype: object

(9,)

tconst                     tt11824392
titleType                   tvEpisode
primaryTitle          Episode #1.1921
originalTitle         Episode #1.1921
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004748, dtype: object

(9,)

tconst                   tt11824394
titleType                 tvEpisode
primaryTitle      A Girly Night Out
originalTitle     A Girly Night Out
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2004749, dtype: object

(9,)

tconst                                      tt11824396
titleType                                        video
primaryTitle      Quik Academy Palindrome Preview 2020
originalTitle     Quik Academy Palindrome Preview 2020
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      \N
genres                                 Short,Talk-Show
Name: 2004750, dtype: object

(9,)

tconst                         tt11824398
titleType                       tvEpisode
primaryTitle      Super Mario Maker 2 #34
originalTitle     Super Mario Maker 2 #34
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         45
genres                                 \N
Name: 2004751, dtype: object

(9,)

tconst                      tt1182439
titleType                   tvEpisode
primaryTitle         Episode #1.10563
originalTitle        Episode #1.10563
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004752, dtype: object

(9,)

tconst                     tt11824400
titleType                   tvEpisode
primaryTitle                  Milonov
originalTitle                 Milonov
isAdult                             0
startYear                        2017
endYear                            \N
runtimeMinutes                     22
genres            Game-Show,Talk-Show
Name: 2004753, dtype: object

(9,)

tconst                     tt11824402
titleType                   tvEpisode
primaryTitle          Episode #1.1923
originalTitle         Episode #1.1923
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004754, dtype: object

(9,)

tconst                     tt11824404
titleType                   tvEpisode
primaryTitle          Episode #1.1922
originalTitle         Episode #1.1922
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004755, dtype: object

(9,)

tconst                     tt11824406
titleType                   tvEpisode
primaryTitle          Episode #1.1924
originalTitle         Episode #1.1924
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004756, dtype: object

(9,)

tconst                                tt11824408
titleType                                  video
primaryTitle      Fleetwood Mac: Gold Dust Woman
originalTitle     Fleetwood Mac: Gold Dust Woman
isAdult                                        0
startYear                                   1988
endYear                                       \N
runtimeMinutes                                 6
genres                               Music,Short
Name: 2004757, dtype: object

(9,)

tconst                      tt1182440
titleType                   tvEpisode
primaryTitle         Episode #1.10565
originalTitle        Episode #1.10565
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2004758, dtype: object

(9,)

tconst                     tt11824410
titleType                   tvEpisode
primaryTitle          Episode #1.1925
originalTitle         Episode #1.1925
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004759, dtype: object

(9,)

tconst                     tt11824412
titleType                   tvEpisode
primaryTitle          Episode #1.1927
originalTitle         Episode #1.1927
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004760, dtype: object

(9,)

tconst                     tt11824414
titleType                   tvEpisode
primaryTitle          Episode #1.1926
originalTitle         Episode #1.1926
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004761, dtype: object

(9,)

tconst                     tt11824416
titleType                   tvEpisode
primaryTitle      A Teacher Named War
originalTitle     A Teacher Named War
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2004762, dtype: object

(9,)

tconst                     tt11824418
titleType                   tvEpisode
primaryTitle          Episode #1.1928
originalTitle         Episode #1.1928
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004763, dtype: object

(9,)

tconst                   tt1182441
titleType                tvEpisode
primaryTitle         Episode #17.1
originalTitle        Episode #17.1
isAdult                          0
startYear                     1995
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2004764, dtype: object

(9,)

tconst                     tt11824420
titleType                   tvEpisode
primaryTitle          Episode #1.1929
originalTitle         Episode #1.1929
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004765, dtype: object

(9,)

tconst                     tt11824422
titleType                   tvEpisode
primaryTitle          Episode #1.1930
originalTitle         Episode #1.1930
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004766, dtype: object

(9,)

tconst                     tt11824424
titleType                   tvEpisode
primaryTitle          Episode #1.1931
originalTitle         Episode #1.1931
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004767, dtype: object

(9,)

tconst                     tt11824426
titleType                   tvEpisode
primaryTitle          Episode #1.1932
originalTitle         Episode #1.1932
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004768, dtype: object

(9,)

tconst                                                   tt11824428
titleType                                                 tvEpisode
primaryTitle      Tiago Brandão Rodrigues, Carolina Patrocínio e...
originalTitle     Tiago Brandão Rodrigues, Carolina Patrocínio e...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                             Comedy,Talk-Show
Name: 2004769, dtype: object

(9,)

tconst                      tt1182442
titleType                   tvEpisode
primaryTitle           Episode #22.11
originalTitle          Episode #22.11
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2004770, dtype: object

(9,)

tconst                     tt11824430
titleType                   tvEpisode
primaryTitle          Episode #1.1933
originalTitle         Episode #1.1933
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004771, dtype: object

(9,)

tconst                     tt11824432
titleType                   tvEpisode
primaryTitle          Episode #1.1934
originalTitle         Episode #1.1934
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004772, dtype: object

(9,)

tconst                     tt11824434
titleType                   tvEpisode
primaryTitle          Episode #1.1935
originalTitle         Episode #1.1935
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004773, dtype: object

(9,)

tconst                     tt11824436
titleType                   tvEpisode
primaryTitle          Episode #1.1936
originalTitle         Episode #1.1936
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004774, dtype: object

(9,)

tconst                     tt11824438
titleType                   tvEpisode
primaryTitle          Episode #1.1937
originalTitle         Episode #1.1937
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004775, dtype: object

(9,)

tconst                      tt1182443
titleType                   tvEpisode
primaryTitle           Episode #22.12
originalTitle          Episode #22.12
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2004776, dtype: object

(9,)

tconst                     tt11824440
titleType                   tvEpisode
primaryTitle          Episode #1.1938
originalTitle         Episode #1.1938
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004777, dtype: object

(9,)

tconst                     tt11824442
titleType                   tvEpisode
primaryTitle          Episode #1.1939
originalTitle         Episode #1.1939
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004778, dtype: object

(9,)

tconst                                  tt11824444
titleType                                    video
primaryTitle      Fleetwood Mac: Isn't It Midnight
originalTitle     Fleetwood Mac: Isn't It Midnight
isAdult                                          0
startYear                                     1988
endYear                                         \N
runtimeMinutes                                   5
genres                                 Music,Short
Name: 2004779, dtype: object

(9,)

tconst                             tt11824446
titleType                               video
primaryTitle      Chalna hai teri Rahoon Main
originalTitle     Chalna hai teri Rahoon Main
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres                          Romance,Short
Name: 2004780, dtype: object

(9,)

tconst                           tt11824448
titleType                         tvEpisode
primaryTitle      Le Kangourou en Australie
originalTitle     Le Kangourou en Australie
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2004781, dtype: object

(9,)

tconst                             tt1182444
titleType                           tvSeries
primaryTitle      Healthy Body, Healthy Mind
originalTitle     Healthy Body, Healthy Mind
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            \N
genres                      Documentary,News
Name: 2004782, dtype: object

(9,)

tconst                     tt11824450
titleType                   tvEpisode
primaryTitle          Episode #1.1940
originalTitle         Episode #1.1940
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004783, dtype: object

(9,)

tconst                tt11824452
titleType                  movie
primaryTitle      Violência S.A.
originalTitle     Violência S.A.
isAdult                        0
startYear                   2005
endYear                       \N
runtimeMinutes                52
genres               Documentary
Name: 2004784, dtype: object

(9,)

tconst                               tt11824456
titleType                             tvEpisode
primaryTitle      New Super Mario Bros. Wii #01
originalTitle     New Super Mario Bros. Wii #01
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               26
genres                                       \N
Name: 2004785, dtype: object

(9,)

tconst                     tt11824458
titleType                   tvEpisode
primaryTitle          Episode #1.1681
originalTitle         Episode #1.1681
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004786, dtype: object

(9,)

tconst               tt1182445
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004787, dtype: object

(9,)

tconst                                      tt11824460
titleType                                        video
primaryTitle      Fleetwood Mac: As Long As You Follow
originalTitle     Fleetwood Mac: As Long As You Follow
isAdult                                              0
startYear                                         1988
endYear                                             \N
runtimeMinutes                                       4
genres                                     Music,Short
Name: 2004788, dtype: object

(9,)

tconst                     tt11824462
titleType                   tvEpisode
primaryTitle          Episode #1.1682
originalTitle         Episode #1.1682
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004789, dtype: object

(9,)

tconst                     tt11824464
titleType                   tvEpisode
primaryTitle          Episode #1.1683
originalTitle         Episode #1.1683
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004790, dtype: object

(9,)

tconst            tt11824466
titleType           tvSeries
primaryTitle       Lightning
originalTitle      Lightning
isAdult                    0
startYear               2021
endYear                   \N
runtimeMinutes            30
genres             Game-Show
Name: 2004791, dtype: object

(9,)

tconst                     tt11824468
titleType                   tvEpisode
primaryTitle          Episode #1.1685
originalTitle         Episode #1.1685
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004792, dtype: object

(9,)

tconst               tt1182446
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004793, dtype: object

(9,)

tconst                     tt11824470
titleType                   tvEpisode
primaryTitle          Episode #1.1684
originalTitle         Episode #1.1684
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004794, dtype: object

(9,)

tconst                     tt11824472
titleType                   tvEpisode
primaryTitle          Episode #1.1686
originalTitle         Episode #1.1686
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004795, dtype: object

(9,)

tconst                     tt11824474
titleType                   tvEpisode
primaryTitle          Episode #1.1687
originalTitle         Episode #1.1687
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004796, dtype: object

(9,)

tconst                     tt11824476
titleType                   tvEpisode
primaryTitle          Episode #1.1688
originalTitle         Episode #1.1688
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004797, dtype: object

(9,)

tconst                     tt11824478
titleType                   tvEpisode
primaryTitle          Episode #1.1689
originalTitle         Episode #1.1689
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004798, dtype: object

(9,)

tconst                  tt1182447
titleType               tvEpisode
primaryTitle      Episode #1.1007
originalTitle     Episode #1.1007
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004799, dtype: object

(9,)

tconst                     tt11824480
titleType                   tvEpisode
primaryTitle          Episode #1.1690
originalTitle         Episode #1.1690
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004800, dtype: object

(9,)

tconst                     tt11824482
titleType                   tvEpisode
primaryTitle          Episode #1.1691
originalTitle         Episode #1.1691
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004801, dtype: object

(9,)

tconst                     tt11824484
titleType                   tvEpisode
primaryTitle          Episode #1.1693
originalTitle         Episode #1.1693
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004802, dtype: object

(9,)

tconst                     tt11824486
titleType                   tvEpisode
primaryTitle          Episode #1.1692
originalTitle         Episode #1.1692
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004803, dtype: object

(9,)

tconst                     tt11824488
titleType                   tvEpisode
primaryTitle          Episode #1.1694
originalTitle         Episode #1.1694
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004804, dtype: object

(9,)

tconst                  tt1182448
titleType               tvEpisode
primaryTitle      Episode #1.1017
originalTitle     Episode #1.1017
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004805, dtype: object

(9,)

tconst                     tt11824490
titleType                   tvEpisode
primaryTitle          Episode #1.1695
originalTitle         Episode #1.1695
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004806, dtype: object

(9,)

tconst                     tt11824492
titleType                   tvEpisode
primaryTitle          Episode #1.1696
originalTitle         Episode #1.1696
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004807, dtype: object

(9,)

tconst                     tt11824494
titleType                   tvEpisode
primaryTitle          Episode #1.1697
originalTitle         Episode #1.1697
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004808, dtype: object

(9,)

tconst                     tt11824496
titleType                   tvEpisode
primaryTitle          Episode #1.1699
originalTitle         Episode #1.1699
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004809, dtype: object

(9,)

tconst                   tt11824498
titleType                 tvEpisode
primaryTitle      Drippin' in Sauce
originalTitle     Drippin' in Sauce
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2004810, dtype: object

(9,)

tconst                  tt1182449
titleType               tvEpisode
primaryTitle      Episode #1.1030
originalTitle     Episode #1.1030
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004811, dtype: object

(9,)

tconst                     tt11824500
titleType                   tvEpisode
primaryTitle          Episode #1.1698
originalTitle         Episode #1.1698
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004812, dtype: object

(9,)

tconst                     tt11824502
titleType                   tvEpisode
primaryTitle          Episode #1.1700
originalTitle         Episode #1.1700
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004813, dtype: object

(9,)

tconst                     tt11824504
titleType                   tvEpisode
primaryTitle          Episode #1.1421
originalTitle         Episode #1.1421
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004814, dtype: object

(9,)

tconst                                                   tt11824506
titleType                                                 tvEpisode
primaryTitle      WHY DOES THIS GAME EXIST!?? (Donkey Kong: Barr...
originalTitle     WHY DOES THIS GAME EXIST!?? (Donkey Kong: Barr...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   19
genres                                                       Comedy
Name: 2004815, dtype: object

(9,)

tconst                     tt11824508
titleType                   tvEpisode
primaryTitle          Episode #1.1422
originalTitle         Episode #1.1422
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004816, dtype: object

(9,)

tconst                  tt1182450
titleType               tvEpisode
primaryTitle      Episode #1.1056
originalTitle     Episode #1.1056
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004817, dtype: object

(9,)

tconst              tt11824510
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004818, dtype: object

(9,)

tconst                     tt11824512
titleType                   tvEpisode
primaryTitle          Episode #1.1424
originalTitle         Episode #1.1424
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004819, dtype: object

(9,)

tconst                     tt11824514
titleType                   tvEpisode
primaryTitle          Episode #1.1423
originalTitle         Episode #1.1423
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004820, dtype: object

(9,)

tconst                     tt11824516
titleType                   tvEpisode
primaryTitle          Episode #1.1426
originalTitle         Episode #1.1426
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004821, dtype: object

(9,)

tconst                     tt11824518
titleType                   tvEpisode
primaryTitle          Episode #1.1425
originalTitle         Episode #1.1425
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004822, dtype: object

(9,)

tconst                  tt1182451
titleType               tvEpisode
primaryTitle      Episode #1.1059
originalTitle     Episode #1.1059
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004823, dtype: object

(9,)

tconst                     tt11824520
titleType                   tvEpisode
primaryTitle          Episode #1.1427
originalTitle         Episode #1.1427
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004824, dtype: object

(9,)

tconst                     tt11824522
titleType                   tvEpisode
primaryTitle          Episode #1.1429
originalTitle         Episode #1.1429
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004825, dtype: object

(9,)

tconst                     tt11824524
titleType                   tvEpisode
primaryTitle          Episode #1.1428
originalTitle         Episode #1.1428
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004826, dtype: object

(9,)

tconst                     tt11824526
titleType                   tvEpisode
primaryTitle          Episode #1.1430
originalTitle         Episode #1.1430
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004827, dtype: object

(9,)

tconst                     tt11824528
titleType                   tvEpisode
primaryTitle          Episode #1.1431
originalTitle         Episode #1.1431
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004828, dtype: object

(9,)

tconst                  tt1182452
titleType               tvEpisode
primaryTitle      Episode #1.1060
originalTitle     Episode #1.1060
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004829, dtype: object

(9,)

tconst                     tt11824530
titleType                   tvEpisode
primaryTitle          Episode #1.1432
originalTitle         Episode #1.1432
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004830, dtype: object

(9,)

tconst                     tt11824532
titleType                   tvEpisode
primaryTitle          Episode #1.1433
originalTitle         Episode #1.1433
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004831, dtype: object

(9,)

tconst                     tt11824534
titleType                   tvEpisode
primaryTitle          Episode #1.1434
originalTitle         Episode #1.1434
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004832, dtype: object

(9,)

tconst                     tt11824536
titleType                   tvEpisode
primaryTitle          Episode #1.1435
originalTitle         Episode #1.1435
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004833, dtype: object

(9,)

tconst                     tt11824538
titleType                   tvEpisode
primaryTitle          Episode #1.1436
originalTitle         Episode #1.1436
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004834, dtype: object

(9,)

tconst                  tt1182453
titleType               tvEpisode
primaryTitle      Episode #1.1091
originalTitle     Episode #1.1091
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004835, dtype: object

(9,)

tconst                           tt11824540
titleType                             video
primaryTitle      Fleetwood Mac: Family Man
originalTitle     Fleetwood Mac: Family Man
isAdult                                   0
startYear                              1987
endYear                                  \N
runtimeMinutes                            4
genres                          Music,Short
Name: 2004836, dtype: object

(9,)

tconst                     tt11824542
titleType                   tvEpisode
primaryTitle          Episode #1.1438
originalTitle         Episode #1.1438
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004837, dtype: object

(9,)

tconst                     tt11824544
titleType                   tvEpisode
primaryTitle          Episode #1.1437
originalTitle         Episode #1.1437
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004838, dtype: object

(9,)

tconst                     tt11824546
titleType                   tvEpisode
primaryTitle          Episode #1.1440
originalTitle         Episode #1.1440
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004839, dtype: object

(9,)

tconst                     tt11824548
titleType                   tvEpisode
primaryTitle          Episode #1.1439
originalTitle         Episode #1.1439
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004840, dtype: object

(9,)

tconst                  tt1182454
titleType               tvEpisode
primaryTitle      Episode #1.1092
originalTitle     Episode #1.1092
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004841, dtype: object

(9,)

tconst                        tt11824550
titleType                          video
primaryTitle      Fleetwood Mac: Save Me
originalTitle     Fleetwood Mac: Save Me
isAdult                                0
startYear                           1990
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2004842, dtype: object

(9,)

tconst            tt11824552
titleType              video
primaryTitle        WaVR-093
originalTitle       WaVR-093
isAdult                    1
startYear               2020
endYear                   \N
runtimeMinutes            66
genres                 Adult
Name: 2004843, dtype: object

(9,)

tconst                     tt11824554
titleType                   tvEpisode
primaryTitle          Episode #1.1181
originalTitle         Episode #1.1181
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004844, dtype: object

(9,)

tconst                     tt11824556
titleType                   tvEpisode
primaryTitle          Episode #1.1182
originalTitle         Episode #1.1182
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004845, dtype: object

(9,)

tconst                     tt11824558
titleType                   tvEpisode
primaryTitle          Episode #1.1183
originalTitle         Episode #1.1183
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004846, dtype: object

(9,)

tconst                  tt1182455
titleType               tvEpisode
primaryTitle      Episode #1.1108
originalTitle     Episode #1.1108
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004847, dtype: object

(9,)

tconst                     tt11824560
titleType                   tvEpisode
primaryTitle          Episode #1.1184
originalTitle         Episode #1.1184
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004848, dtype: object

(9,)

tconst                     tt11824562
titleType                   tvEpisode
primaryTitle          Episode #1.1186
originalTitle         Episode #1.1186
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004849, dtype: object

(9,)

tconst                     tt11824564
titleType                   tvEpisode
primaryTitle          Episode #1.1185
originalTitle         Episode #1.1185
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004850, dtype: object

(9,)

tconst                     tt11824566
titleType                   tvEpisode
primaryTitle          Episode #1.1187
originalTitle         Episode #1.1187
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004851, dtype: object

(9,)

tconst                  tt1182456
titleType               tvEpisode
primaryTitle      Episode #1.1126
originalTitle     Episode #1.1126
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004852, dtype: object

(9,)

tconst                     tt11824572
titleType                   tvEpisode
primaryTitle          Episode #1.1188
originalTitle         Episode #1.1188
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004853, dtype: object

(9,)

tconst                     tt11824574
titleType                   tvEpisode
primaryTitle          Episode #1.1189
originalTitle         Episode #1.1189
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004854, dtype: object

(9,)

tconst                     tt11824576
titleType                   tvEpisode
primaryTitle          Episode #1.1190
originalTitle         Episode #1.1190
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004855, dtype: object

(9,)

tconst                     tt11824578
titleType                   tvEpisode
primaryTitle          Episode #1.1192
originalTitle         Episode #1.1192
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004856, dtype: object

(9,)

tconst                  tt1182457
titleType               tvEpisode
primaryTitle      Episode #1.1127
originalTitle     Episode #1.1127
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004857, dtype: object

(9,)

tconst                     tt11824580
titleType                   tvEpisode
primaryTitle          Episode #1.1191
originalTitle         Episode #1.1191
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004858, dtype: object

(9,)

tconst                     tt11824582
titleType                   tvEpisode
primaryTitle          Episode #1.1193
originalTitle         Episode #1.1193
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004859, dtype: object

(9,)

tconst                     tt11824584
titleType                   tvEpisode
primaryTitle          Episode #1.1194
originalTitle         Episode #1.1194
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004860, dtype: object

(9,)

tconst                     tt11824586
titleType                   tvEpisode
primaryTitle          Episode #1.1195
originalTitle         Episode #1.1195
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004861, dtype: object

(9,)

tconst                     tt11824588
titleType                   tvEpisode
primaryTitle          Episode #1.1196
originalTitle         Episode #1.1196
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004862, dtype: object

(9,)

tconst                     tt11824590
titleType                   tvEpisode
primaryTitle          Episode #1.1197
originalTitle         Episode #1.1197
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004863, dtype: object

(9,)

tconst                     tt11824592
titleType                   tvEpisode
primaryTitle          Episode #1.1199
originalTitle         Episode #1.1199
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004864, dtype: object

(9,)

tconst                     tt11824594
titleType                   tvEpisode
primaryTitle          Episode #1.1198
originalTitle         Episode #1.1198
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004865, dtype: object

(9,)

tconst                            tt11824596
titleType                          tvEpisode
primaryTitle        SMG4: Mario's Magical TV
originalTitle       SMG4: Mario's Magical TV
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            12
genres            Adventure,Animation,Comedy
Name: 2004866, dtype: object

(9,)

tconst                     tt11824598
titleType                   tvEpisode
primaryTitle          Episode #1.1200
originalTitle         Episode #1.1200
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004867, dtype: object

(9,)

tconst                  tt1182459
titleType               tvEpisode
primaryTitle      Episode #1.1143
originalTitle     Episode #1.1143
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004868, dtype: object

(9,)

tconst                             tt11824600
titleType                           tvEpisode
primaryTitle                  Episode #21.138
originalTitle                 Episode #21.138
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Comedy,Game-Show,Reality-TV
Name: 2004869, dtype: object

(9,)

tconst                     tt11824602
titleType                   tvEpisode
primaryTitle           Episode #1.961
originalTitle          Episode #1.961
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004870, dtype: object

(9,)

tconst                             tt11824604
titleType                           tvEpisode
primaryTitle                  Episode #21.139
originalTitle                 Episode #21.139
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Comedy,Game-Show,Reality-TV
Name: 2004871, dtype: object

(9,)

tconst                                tt11824606
titleType                                  video
primaryTitle      Fleetwood Mac: Skies the Limit
originalTitle     Fleetwood Mac: Skies the Limit
isAdult                                        0
startYear                                   1990
endYear                                       \N
runtimeMinutes                                 4
genres                               Music,Short
Name: 2004872, dtype: object

(9,)

tconst                     tt11824608
titleType                   tvEpisode
primaryTitle           Episode #1.962
originalTitle          Episode #1.962
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004873, dtype: object

(9,)

tconst                  tt1182460
titleType               tvEpisode
primaryTitle      Episode #1.1166
originalTitle     Episode #1.1166
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004874, dtype: object

(9,)

tconst                     tt11824610
titleType                   tvEpisode
primaryTitle           Episode #1.963
originalTitle          Episode #1.963
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004875, dtype: object

(9,)

tconst                     tt11824612
titleType                   tvEpisode
primaryTitle           Episode #1.965
originalTitle          Episode #1.965
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004876, dtype: object

(9,)

tconst                     tt11824614
titleType                   tvEpisode
primaryTitle           Episode #1.964
originalTitle          Episode #1.964
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004877, dtype: object

(9,)

tconst                     tt11824616
titleType                   tvEpisode
primaryTitle           Episode #1.966
originalTitle          Episode #1.966
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004878, dtype: object

(9,)

tconst                     tt11824618
titleType                   tvEpisode
primaryTitle           Episode #1.967
originalTitle          Episode #1.967
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004879, dtype: object

(9,)

tconst                  tt1182461
titleType               tvEpisode
primaryTitle      Episode #1.1191
originalTitle     Episode #1.1191
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004880, dtype: object

(9,)

tconst                     tt11824620
titleType                   tvEpisode
primaryTitle           Episode #1.969
originalTitle          Episode #1.969
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004881, dtype: object

(9,)

tconst                     tt11824622
titleType                   tvEpisode
primaryTitle           Episode #1.968
originalTitle          Episode #1.968
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004882, dtype: object

(9,)

tconst                     tt11824624
titleType                   tvEpisode
primaryTitle           Episode #1.971
originalTitle          Episode #1.971
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004883, dtype: object

(9,)

tconst                     tt11824626
titleType                   tvEpisode
primaryTitle           Episode #1.970
originalTitle          Episode #1.970
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004884, dtype: object

(9,)

tconst                     tt11824628
titleType                   tvEpisode
primaryTitle           Episode #1.972
originalTitle          Episode #1.972
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004885, dtype: object

(9,)

tconst                  tt1182462
titleType               tvEpisode
primaryTitle      Episode #1.1235
originalTitle     Episode #1.1235
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004886, dtype: object

(9,)

tconst                     tt11824630
titleType                   tvEpisode
primaryTitle           Episode #1.973
originalTitle          Episode #1.973
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004887, dtype: object

(9,)

tconst                     tt11824632
titleType                   tvEpisode
primaryTitle           Episode #1.974
originalTitle          Episode #1.974
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004888, dtype: object

(9,)

tconst                     tt11824634
titleType                   tvEpisode
primaryTitle           Episode #1.975
originalTitle          Episode #1.975
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004889, dtype: object

(9,)

tconst                     tt11824636
titleType                   tvEpisode
primaryTitle           Episode #1.976
originalTitle          Episode #1.976
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004890, dtype: object

(9,)

tconst                     tt11824638
titleType                   tvEpisode
primaryTitle           Episode #1.977
originalTitle          Episode #1.977
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004891, dtype: object

(9,)

tconst                     tt11824640
titleType                   tvEpisode
primaryTitle           Episode #1.978
originalTitle          Episode #1.978
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004892, dtype: object

(9,)

tconst                     tt11824642
titleType                   tvEpisode
primaryTitle           Episode #1.979
originalTitle          Episode #1.979
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004893, dtype: object

(9,)

tconst                      tt11824644
titleType                        short
primaryTitle           Daniel & Maggie
originalTitle          Daniel & Maggie
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Sci-Fi,Short,Western
Name: 2004894, dtype: object

(9,)

tconst                     tt11824646
titleType                   tvEpisode
primaryTitle           Episode #1.980
originalTitle          Episode #1.980
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004895, dtype: object

(9,)

tconst                            tt11824648
titleType                           tvSeries
primaryTitle                         Courier
originalTitle                        Courier
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            34
genres            Adventure,Animation,Comedy
Name: 2004896, dtype: object

(9,)

tconst                     tt11824650
titleType                   tvEpisode
primaryTitle           Episode #1.721
originalTitle          Episode #1.721
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004897, dtype: object

(9,)

tconst                     tt11824652
titleType                   tvEpisode
primaryTitle           Episode #1.722
originalTitle          Episode #1.722
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004898, dtype: object

(9,)

tconst                                       tt11824654
titleType                                         video
primaryTitle      Fleetwood Mac: In the Back of My Mind
originalTitle     Fleetwood Mac: In the Back of My Mind
isAdult                                               0
startYear                                          1990
endYear                                              \N
runtimeMinutes                                        5
genres                                      Music,Short
Name: 2004899, dtype: object

(9,)

tconst                     tt11824656
titleType                   tvEpisode
primaryTitle           Episode #1.723
originalTitle          Episode #1.723
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004900, dtype: object

(9,)

tconst                     tt11824658
titleType                   tvEpisode
primaryTitle           Episode #1.724
originalTitle          Episode #1.724
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004901, dtype: object

(9,)

tconst                  tt1182465
titleType               tvEpisode
primaryTitle      Episode #1.1281
originalTitle     Episode #1.1281
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004902, dtype: object

(9,)

tconst                     tt11824660
titleType                   tvEpisode
primaryTitle           Episode #1.725
originalTitle          Episode #1.725
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004903, dtype: object

(9,)

tconst                     tt11824662
titleType                   tvEpisode
primaryTitle           Episode #1.727
originalTitle          Episode #1.727
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004904, dtype: object

(9,)

tconst                     tt11824664
titleType                   tvEpisode
primaryTitle           Episode #1.726
originalTitle          Episode #1.726
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004905, dtype: object

(9,)

tconst                     tt11824666
titleType                   tvEpisode
primaryTitle           Episode #1.728
originalTitle          Episode #1.728
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004906, dtype: object

(9,)

tconst                     tt11824668
titleType                   tvEpisode
primaryTitle           Episode #1.729
originalTitle          Episode #1.729
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004907, dtype: object

(9,)

tconst                  tt1182466
titleType               tvEpisode
primaryTitle      Episode #1.1282
originalTitle     Episode #1.1282
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004908, dtype: object

(9,)

tconst                     tt11824670
titleType                   tvEpisode
primaryTitle           Episode #1.730
originalTitle          Episode #1.730
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004909, dtype: object

(9,)

tconst                     tt11824672
titleType                   tvEpisode
primaryTitle           Episode #1.731
originalTitle          Episode #1.731
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004910, dtype: object

(9,)

tconst                     tt11824674
titleType                   tvEpisode
primaryTitle           Episode #1.732
originalTitle          Episode #1.732
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004911, dtype: object

(9,)

tconst                             tt11824676
titleType                           tvEpisode
primaryTitle      Cooking Up with Melody Lane
originalTitle     Cooking Up with Melody Lane
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres                    Comedy,Drama,Sci-Fi
Name: 2004912, dtype: object

(9,)

tconst                     tt11824678
titleType                   tvEpisode
primaryTitle           Episode #1.735
originalTitle          Episode #1.735
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004913, dtype: object

(9,)

tconst                  tt1182467
titleType               tvEpisode
primaryTitle      Episode #1.1316
originalTitle     Episode #1.1316
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004914, dtype: object

(9,)

tconst                     tt11824680
titleType                   tvEpisode
primaryTitle           Episode #1.734
originalTitle          Episode #1.734
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004915, dtype: object

(9,)

tconst                     tt11824682
titleType                   tvEpisode
primaryTitle           Episode #1.733
originalTitle          Episode #1.733
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004916, dtype: object

(9,)

tconst                     tt11824684
titleType                   tvEpisode
primaryTitle           Episode #1.736
originalTitle          Episode #1.736
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004917, dtype: object

(9,)

tconst               tt11824686
titleType             tvEpisode
primaryTitle      Episode #2.33
originalTitle     Episode #2.33
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2004918, dtype: object

(9,)

tconst                     tt11824688
titleType                   tvEpisode
primaryTitle           Episode #1.737
originalTitle          Episode #1.737
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004919, dtype: object

(9,)

tconst                  tt1182468
titleType               tvEpisode
primaryTitle      Episode #1.1317
originalTitle     Episode #1.1317
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004920, dtype: object

(9,)

tconst               tt11824690
titleType             tvEpisode
primaryTitle      We Are Family
originalTitle     We Are Family
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               27
genres                    Drama
Name: 2004921, dtype: object

(9,)

tconst                     tt11824692
titleType                   tvEpisode
primaryTitle           Episode #1.738
originalTitle          Episode #1.738
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004922, dtype: object

(9,)

tconst                     tt11824694
titleType                   tvEpisode
primaryTitle           Episode #1.739
originalTitle          Episode #1.739
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004923, dtype: object

(9,)

tconst                     tt11824696
titleType                   tvEpisode
primaryTitle           Episode #1.740
originalTitle          Episode #1.740
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004924, dtype: object

(9,)

tconst                     tt11824698
titleType                   tvEpisode
primaryTitle           Episode #1.461
originalTitle          Episode #1.461
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004925, dtype: object

(9,)

tconst                  tt1182469
titleType               tvEpisode
primaryTitle      Episode #1.1332
originalTitle     Episode #1.1332
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004926, dtype: object

(9,)

tconst                     tt11824700
titleType                   tvEpisode
primaryTitle           Episode #1.462
originalTitle          Episode #1.462
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004927, dtype: object

(9,)

tconst                     tt11824702
titleType                   tvEpisode
primaryTitle           Episode #1.463
originalTitle          Episode #1.463
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004928, dtype: object

(9,)

tconst                     tt11824704
titleType                   tvEpisode
primaryTitle           Episode #1.464
originalTitle          Episode #1.464
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004929, dtype: object

(9,)

tconst                     tt11824706
titleType                   tvEpisode
primaryTitle           Episode #1.465
originalTitle          Episode #1.465
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004930, dtype: object

(9,)

tconst                     tt11824708
titleType                   tvEpisode
primaryTitle           Episode #1.466
originalTitle          Episode #1.466
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004931, dtype: object

(9,)

tconst                  tt1182470
titleType               tvEpisode
primaryTitle      Episode #1.1333
originalTitle     Episode #1.1333
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004932, dtype: object

(9,)

tconst                     tt11824710
titleType                   tvEpisode
primaryTitle           Episode #1.467
originalTitle          Episode #1.467
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004933, dtype: object

(9,)

tconst                     tt11824712
titleType                   tvEpisode
primaryTitle           Episode #1.468
originalTitle          Episode #1.468
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004934, dtype: object

(9,)

tconst                     tt11824714
titleType                   tvEpisode
primaryTitle           Episode #1.469
originalTitle          Episode #1.469
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004935, dtype: object

(9,)

tconst                     tt11824716
titleType                   tvEpisode
primaryTitle           Episode #1.471
originalTitle          Episode #1.471
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004936, dtype: object

(9,)

tconst                     tt11824718
titleType                   tvEpisode
primaryTitle           Episode #1.470
originalTitle          Episode #1.470
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004937, dtype: object

(9,)

tconst                  tt1182471
titleType               tvEpisode
primaryTitle      Episode #1.1349
originalTitle     Episode #1.1349
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004938, dtype: object

(9,)

tconst                     tt11824720
titleType                   tvEpisode
primaryTitle           Episode #1.473
originalTitle          Episode #1.473
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004939, dtype: object

(9,)

tconst                     tt11824722
titleType                   tvEpisode
primaryTitle           Episode #1.472
originalTitle          Episode #1.472
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004940, dtype: object

(9,)

tconst                     tt11824724
titleType                   tvEpisode
primaryTitle           Episode #1.474
originalTitle          Episode #1.474
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004941, dtype: object

(9,)

tconst                     tt11824726
titleType                   tvEpisode
primaryTitle           Episode #1.475
originalTitle          Episode #1.475
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004942, dtype: object

(9,)

tconst                     tt11824728
titleType                   tvEpisode
primaryTitle           Episode #1.476
originalTitle          Episode #1.476
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004943, dtype: object

(9,)

tconst                  tt1182472
titleType               tvEpisode
primaryTitle      Episode #1.1350
originalTitle     Episode #1.1350
isAdult                         0
startYear                    2004
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004944, dtype: object

(9,)

tconst                     tt11824730
titleType                   tvEpisode
primaryTitle           Episode #1.477
originalTitle          Episode #1.477
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004945, dtype: object

(9,)

tconst                     tt11824732
titleType                   tvEpisode
primaryTitle           Episode #1.478
originalTitle          Episode #1.478
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004946, dtype: object

(9,)

tconst                     tt11824734
titleType                   tvEpisode
primaryTitle           Episode #1.479
originalTitle          Episode #1.479
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004947, dtype: object

(9,)

tconst                     tt11824736
titleType                   tvEpisode
primaryTitle           Episode #1.480
originalTitle          Episode #1.480
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004948, dtype: object

(9,)

tconst                     tt11824738
titleType                   tvEpisode
primaryTitle           Episode #1.221
originalTitle          Episode #1.221
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004949, dtype: object

(9,)

tconst                     tt11824740
titleType                   tvEpisode
primaryTitle           Episode #1.222
originalTitle          Episode #1.222
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004950, dtype: object

(9,)

tconst                     tt11824742
titleType                   tvEpisode
primaryTitle           Episode #1.223
originalTitle          Episode #1.223
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004951, dtype: object

(9,)

tconst                     tt11824744
titleType                   tvEpisode
primaryTitle           Episode #1.225
originalTitle          Episode #1.225
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004952, dtype: object

(9,)

tconst                     tt11824746
titleType                   tvEpisode
primaryTitle           Episode #1.224
originalTitle          Episode #1.224
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004953, dtype: object

(9,)

tconst                     tt11824748
titleType                   tvEpisode
primaryTitle           Episode #1.226
originalTitle          Episode #1.226
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004954, dtype: object

(9,)

tconst                  tt1182474
titleType               tvEpisode
primaryTitle      Episode #1.1619
originalTitle     Episode #1.1619
isAdult                         0
startYear                    2005
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004955, dtype: object

(9,)

tconst                     tt11824750
titleType                   tvEpisode
primaryTitle           Episode #1.227
originalTitle          Episode #1.227
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004956, dtype: object

(9,)

tconst                     tt11824752
titleType                   tvEpisode
primaryTitle           Episode #1.229
originalTitle          Episode #1.229
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004957, dtype: object

(9,)

tconst                     tt11824754
titleType                   tvEpisode
primaryTitle           Episode #1.228
originalTitle          Episode #1.228
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004958, dtype: object

(9,)

tconst                     tt11824756
titleType                   tvEpisode
primaryTitle           Episode #1.230
originalTitle          Episode #1.230
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004959, dtype: object

(9,)

tconst                     tt11824758
titleType                   tvEpisode
primaryTitle           Episode #1.231
originalTitle          Episode #1.231
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004960, dtype: object

(9,)

tconst                  tt1182475
titleType               tvEpisode
primaryTitle      Episode #1.1632
originalTitle     Episode #1.1632
isAdult                         0
startYear                    2005
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004961, dtype: object

(9,)

tconst                     tt11824760
titleType                   tvEpisode
primaryTitle           Episode #1.232
originalTitle          Episode #1.232
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004962, dtype: object

(9,)

tconst                     tt11824762
titleType                   tvEpisode
primaryTitle           Episode #1.233
originalTitle          Episode #1.233
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004963, dtype: object

(9,)

tconst                     tt11824764
titleType                   tvEpisode
primaryTitle           Episode #1.234
originalTitle          Episode #1.234
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004964, dtype: object

(9,)

tconst                     tt11824766
titleType                   tvEpisode
primaryTitle           Episode #1.235
originalTitle          Episode #1.235
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004965, dtype: object

(9,)

tconst                     tt11824768
titleType                   tvEpisode
primaryTitle           Episode #1.237
originalTitle          Episode #1.237
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004966, dtype: object

(9,)

tconst                  tt1182476
titleType               tvEpisode
primaryTitle      Episode #1.1678
originalTitle     Episode #1.1678
isAdult                         0
startYear                    2005
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004967, dtype: object

(9,)

tconst                     tt11824770
titleType                   tvEpisode
primaryTitle           Episode #1.236
originalTitle          Episode #1.236
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004968, dtype: object

(9,)

tconst                     tt11824772
titleType                   tvEpisode
primaryTitle           Episode #1.238
originalTitle          Episode #1.238
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004969, dtype: object

(9,)

tconst                             tt11824774
titleType                           tvEpisode
primaryTitle                    Episode #15.6
originalTitle                   Episode #15.6
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres            Family,Game-Show,Reality-TV
Name: 2004970, dtype: object

(9,)

tconst                     tt11824776
titleType                   tvEpisode
primaryTitle           Episode #1.239
originalTitle          Episode #1.239
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004971, dtype: object

(9,)

tconst                     tt11824778
titleType                   tvEpisode
primaryTitle           Episode #1.240
originalTitle          Episode #1.240
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2004972, dtype: object

(9,)

tconst                  tt1182477
titleType               tvEpisode
primaryTitle      Episode #1.1692
originalTitle     Episode #1.1692
isAdult                         0
startYear                    2006
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004973, dtype: object

(9,)

tconst                        tt11824780
titleType                      tvEpisode
primaryTitle               Episode #1.21
originalTitle              Episode #1.21
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Adventure,Comedy,Drama
Name: 2004974, dtype: object

(9,)

tconst                           tt11824782
titleType                             video
primaryTitle      Fleetwood Mac: Paper Doll
originalTitle     Fleetwood Mac: Paper Doll
isAdult                                   0
startYear                              1992
endYear                                  \N
runtimeMinutes                            4
genres                          Music,Short
Name: 2004975, dtype: object

(9,)

tconst                tt11824784
titleType              tvEpisode
primaryTitle      Episode #1.261
originalTitle     Episode #1.261
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004976, dtype: object

(9,)

tconst                            tt11824786
titleType                              movie
primaryTitle      Byen hvor børn forsivinder
originalTitle     Byen hvor børn forsivinder
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                           Documentary
Name: 2004977, dtype: object

(9,)

tconst                tt11824788
titleType              tvEpisode
primaryTitle      Episode #1.262
originalTitle     Episode #1.262
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004978, dtype: object

(9,)

tconst                  tt1182478
titleType               tvEpisode
primaryTitle      Episode #1.1714
originalTitle     Episode #1.1714
isAdult                         0
startYear                    2006
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004979, dtype: object

(9,)

tconst                            tt11824790
titleType                              video
primaryTitle      Fleetwood Mac: Love Shines
originalTitle     Fleetwood Mac: Love Shines
isAdult                                    0
startYear                               1992
endYear                                   \N
runtimeMinutes                             4
genres                           Music,Short
Name: 2004980, dtype: object

(9,)

tconst                tt11824792
titleType              tvEpisode
primaryTitle      Episode #1.263
originalTitle     Episode #1.263
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004981, dtype: object

(9,)

tconst                tt11824794
titleType              tvEpisode
primaryTitle      Episode #1.264
originalTitle     Episode #1.264
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004982, dtype: object

(9,)

tconst                tt11824796
titleType              tvEpisode
primaryTitle      Episode #1.266
originalTitle     Episode #1.266
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004983, dtype: object

(9,)

tconst                tt11824798
titleType              tvEpisode
primaryTitle      Episode #1.265
originalTitle     Episode #1.265
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004984, dtype: object

(9,)

tconst                  tt1182479
titleType               tvEpisode
primaryTitle      Episode #1.1732
originalTitle     Episode #1.1732
isAdult                         0
startYear                    2006
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004985, dtype: object

(9,)

tconst                tt11824800
titleType              tvEpisode
primaryTitle      Episode #1.267
originalTitle     Episode #1.267
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004986, dtype: object

(9,)

tconst                tt11824802
titleType              tvEpisode
primaryTitle      Episode #1.268
originalTitle     Episode #1.268
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004987, dtype: object

(9,)

tconst                tt11824804
titleType              tvEpisode
primaryTitle      Episode #1.269
originalTitle     Episode #1.269
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004988, dtype: object

(9,)

tconst              tt11824806
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2004989, dtype: object

(9,)

tconst                  tt1182480
titleType               tvEpisode
primaryTitle      Episode #1.1756
originalTitle     Episode #1.1756
isAdult                         0
startYear                    2006
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004990, dtype: object

(9,)

tconst                tt11824810
titleType              tvEpisode
primaryTitle      Episode #1.270
originalTitle     Episode #1.270
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004991, dtype: object

(9,)

tconst                tt11824812
titleType              tvEpisode
primaryTitle      Episode #1.271
originalTitle     Episode #1.271
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004992, dtype: object

(9,)

tconst                tt11824814
titleType              tvEpisode
primaryTitle      Episode #1.272
originalTitle     Episode #1.272
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004993, dtype: object

(9,)

tconst                tt11824816
titleType              tvEpisode
primaryTitle      Episode #1.273
originalTitle     Episode #1.273
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004994, dtype: object

(9,)

tconst                 tt11824818
titleType               videoGame
primaryTitle      Just Dance 2015
originalTitle     Just Dance 2015
isAdult                         0
startYear                    2014
endYear                        \N
runtimeMinutes                 \N
genres                      Music
Name: 2004995, dtype: object

(9,)

tconst                  tt1182481
titleType               tvEpisode
primaryTitle      Episode #1.2228
originalTitle     Episode #1.2228
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2004996, dtype: object

(9,)

tconst                tt11824820
titleType              tvEpisode
primaryTitle      Episode #1.276
originalTitle     Episode #1.276
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004997, dtype: object

(9,)

tconst                tt11824822
titleType              tvEpisode
primaryTitle      Episode #1.274
originalTitle     Episode #1.274
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004998, dtype: object

(9,)

tconst                tt11824824
titleType              tvEpisode
primaryTitle      Episode #1.275
originalTitle     Episode #1.275
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2004999, dtype: object

(9,)

tconst                tt11824826
titleType              tvEpisode
primaryTitle      Episode #1.277
originalTitle     Episode #1.277
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005000, dtype: object

(9,)

tconst              tt11824828
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2005001, dtype: object

(9,)

tconst                 tt1182482
titleType              tvEpisode
primaryTitle      Episode #1.879
originalTitle     Episode #1.879
isAdult                        0
startYear                   2002
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2005002, dtype: object

(9,)

tconst                  tt11824830
titleType                tvEpisode
primaryTitle        Episode #1.899
originalTitle       Episode #1.899
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005003, dtype: object

(9,)

tconst                tt11824832
titleType              tvEpisode
primaryTitle      Episode #1.278
originalTitle     Episode #1.278
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005004, dtype: object

(9,)

tconst                tt11824834
titleType              tvEpisode
primaryTitle      Episode #1.279
originalTitle     Episode #1.279
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005005, dtype: object

(9,)

tconst                tt11824836
titleType              tvEpisode
primaryTitle      Episode #1.280
originalTitle     Episode #1.280
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005006, dtype: object

(9,)

tconst                  tt11824838
titleType                tvEpisode
primaryTitle        Episode #1.900
originalTitle       Episode #1.900
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005007, dtype: object

(9,)

tconst                 tt1182483
titleType              tvEpisode
primaryTitle      Episode #1.929
originalTitle     Episode #1.929
isAdult                        0
startYear                   2002
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2005008, dtype: object

(9,)

tconst              tt11824840
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2005009, dtype: object

(9,)

tconst                tt11824842
titleType              tvEpisode
primaryTitle      Episode #1.241
originalTitle     Episode #1.241
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005010, dtype: object

(9,)

tconst                  tt11824844
titleType                tvEpisode
primaryTitle        Episode #1.901
originalTitle       Episode #1.901
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005011, dtype: object

(9,)

tconst                tt11824846
titleType              tvEpisode
primaryTitle      Episode #1.242
originalTitle     Episode #1.242
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005012, dtype: object

(9,)

tconst                     tt11824848
titleType                    tvSeries
primaryTitle                  Addicts
originalTitle                 Addicts
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Crime
Name: 2005013, dtype: object

(9,)

tconst                 tt1182484
titleType              tvEpisode
primaryTitle      Episode #1.942
originalTitle     Episode #1.942
isAdult                        0
startYear                   2003
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2005014, dtype: object

(9,)

tconst                tt11824850
titleType              tvEpisode
primaryTitle      Episode #1.243
originalTitle     Episode #1.243
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005015, dtype: object

(9,)

tconst                tt11824852
titleType                  movie
primaryTitle      Late in Summer
originalTitle     Late in Summer
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005016, dtype: object

(9,)

tconst                                 tt11824854
titleType                                   video
primaryTitle      Fleetwood Mac: Landslide (Live)
originalTitle     Fleetwood Mac: Landslide (Live)
isAdult                                         0
startYear                                    1998
endYear                                        \N
runtimeMinutes                                  4
genres                                Music,Short
Name: 2005017, dtype: object

(9,)

tconst             tt11824856
titleType           tvEpisode
primaryTitle       Capítulo 1
originalTitle      Capítulo 1
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2005018, dtype: object

(9,)

tconst                tt11824858
titleType              tvEpisode
primaryTitle      Episode #1.244
originalTitle     Episode #1.244
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005019, dtype: object

(9,)

tconst                 tt1182485
titleType              tvEpisode
primaryTitle      Episode #1.960
originalTitle     Episode #1.960
isAdult                        0
startYear                   2003
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2005020, dtype: object

(9,)

tconst                tt11824860
titleType              tvEpisode
primaryTitle      Episode #1.245
originalTitle     Episode #1.245
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005021, dtype: object

(9,)

tconst                tt11824862
titleType              tvEpisode
primaryTitle      Episode #1.246
originalTitle     Episode #1.246
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005022, dtype: object

(9,)

tconst                tt11824864
titleType              tvEpisode
primaryTitle      Episode #1.248
originalTitle     Episode #1.248
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005023, dtype: object

(9,)

tconst                tt11824866
titleType              tvEpisode
primaryTitle      Episode #1.247
originalTitle     Episode #1.247
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005024, dtype: object

(9,)

tconst                tt11824868
titleType              tvEpisode
primaryTitle      Episode #1.249
originalTitle     Episode #1.249
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005025, dtype: object

(9,)

tconst                 tt1182486
titleType              tvEpisode
primaryTitle      Episode #1.983
originalTitle     Episode #1.983
isAdult                        0
startYear                   2003
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2005026, dtype: object

(9,)

tconst                tt11824870
titleType              tvEpisode
primaryTitle      Episode #1.251
originalTitle     Episode #1.251
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005027, dtype: object

(9,)

tconst                tt11824872
titleType              tvEpisode
primaryTitle      Episode #1.250
originalTitle     Episode #1.250
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005028, dtype: object

(9,)

tconst                tt11824874
titleType                  short
primaryTitle      Wandering Mind
originalTitle     Wandering Mind
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                13
genres               Drama,Short
Name: 2005029, dtype: object

(9,)

tconst                tt11824876
titleType              tvEpisode
primaryTitle      Episode #1.252
originalTitle     Episode #1.252
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005030, dtype: object

(9,)

tconst                tt11824878
titleType              tvEpisode
primaryTitle      Episode #1.253
originalTitle     Episode #1.253
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005031, dtype: object

(9,)

tconst                          tt1182487
titleType                       tvEpisode
primaryTitle       La noche del comisario
originalTitle      La noche del comisario
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres            Action,Adventure,Comedy
Name: 2005032, dtype: object

(9,)

tconst                tt11824880
titleType              tvEpisode
primaryTitle      Episode #1.254
originalTitle     Episode #1.254
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005033, dtype: object

(9,)

tconst                tt11824882
titleType              tvEpisode
primaryTitle      Episode #1.255
originalTitle     Episode #1.255
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005034, dtype: object

(9,)

tconst                tt11824884
titleType              tvEpisode
primaryTitle      Episode #1.256
originalTitle     Episode #1.256
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005035, dtype: object

(9,)

tconst                tt11824886
titleType              tvEpisode
primaryTitle      Episode #1.257
originalTitle     Episode #1.257
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005036, dtype: object

(9,)

tconst                tt11824888
titleType              tvEpisode
primaryTitle      Episode #1.258
originalTitle     Episode #1.258
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005037, dtype: object

(9,)

tconst                         tt1182488
titleType                      tvEpisode
primaryTitle               No retornable
originalTitle              No retornable
isAdult                                0
startYear                           1990
endYear                               \N
runtimeMinutes                        \N
genres            Fantasy,Horror,Mystery
Name: 2005038, dtype: object

(9,)

tconst                tt11824890
titleType              tvEpisode
primaryTitle      Episode #1.259
originalTitle     Episode #1.259
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005039, dtype: object

(9,)

tconst                tt11824892
titleType              tvEpisode
primaryTitle      Episode #1.260
originalTitle     Episode #1.260
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005040, dtype: object

(9,)

tconst                              tt11824894
titleType                                video
primaryTitle      Fleetwood Mac: Dreams (Live)
originalTitle     Fleetwood Mac: Dreams (Live)
isAdult                                      0
startYear                                 1977
endYear                                     \N
runtimeMinutes                               4
genres                             Music,Short
Name: 2005041, dtype: object

(9,)

tconst                      tt11824896
titleType                    tvEpisode
primaryTitle            Episode #1.201
originalTitle           Episode #1.201
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005042, dtype: object

(9,)

tconst             tt11824898
titleType           tvEpisode
primaryTitle       Capítulo 2
originalTitle      Capítulo 2
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2005043, dtype: object

(9,)

tconst                                  tt11824900
titleType                                    video
primaryTitle      Fleetwood Mac: Don't Stop (Live)
originalTitle     Fleetwood Mac: Don't Stop (Live)
isAdult                                          0
startYear                                     1977
endYear                                         \N
runtimeMinutes                                   4
genres                                 Music,Short
Name: 2005044, dtype: object

(9,)

tconst             tt11824902
titleType               short
primaryTitle         Raw Deal
originalTitle        Raw Deal
isAdult                     0
startYear                2011
endYear                    \N
runtimeMinutes              3
genres            Drama,Short
Name: 2005045, dtype: object

(9,)

tconst                      tt11824904
titleType                    tvEpisode
primaryTitle            Episode #1.202
originalTitle           Episode #1.202
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005046, dtype: object

(9,)

tconst                      tt11824906
titleType                    tvEpisode
primaryTitle            Episode #1.203
originalTitle           Episode #1.203
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005047, dtype: object

(9,)

tconst                      tt11824908
titleType                    tvEpisode
primaryTitle            Episode #1.205
originalTitle           Episode #1.205
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005048, dtype: object

(9,)

tconst                                tt1182490
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2005049, dtype: object

(9,)

tconst                      tt11824910
titleType                    tvEpisode
primaryTitle            Episode #1.204
originalTitle           Episode #1.204
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005050, dtype: object

(9,)

tconst                      tt11824912
titleType                    tvEpisode
primaryTitle            Episode #1.206
originalTitle           Episode #1.206
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005051, dtype: object

(9,)

tconst                      tt11824914
titleType                    tvEpisode
primaryTitle            Episode #1.208
originalTitle           Episode #1.208
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005052, dtype: object

(9,)

tconst                      tt11824916
titleType                    tvEpisode
primaryTitle            Episode #1.207
originalTitle           Episode #1.207
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005053, dtype: object

(9,)

tconst                      tt11824918
titleType                    tvEpisode
primaryTitle            Episode #1.209
originalTitle           Episode #1.209
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005054, dtype: object

(9,)

tconst                                tt1182491
titleType                             tvEpisode
primaryTitle      Episode dated 8 February 2008
originalTitle     Episode dated 8 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2005055, dtype: object

(9,)

tconst              tt11824920
titleType                short
primaryTitle       Car Trouble
originalTitle      Car Trouble
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes               5
genres            Comedy,Short
Name: 2005056, dtype: object

(9,)

tconst                      tt11824922
titleType                    tvEpisode
primaryTitle            Episode #1.210
originalTitle           Episode #1.210
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005057, dtype: object

(9,)

tconst                      tt11824924
titleType                    tvEpisode
primaryTitle            Episode #1.211
originalTitle           Episode #1.211
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005058, dtype: object

(9,)

tconst                      tt11824926
titleType                    tvEpisode
primaryTitle            Episode #1.212
originalTitle           Episode #1.212
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005059, dtype: object

(9,)

tconst                         tt11824928
titleType                           video
primaryTitle      Fleetwood Mac: Rhiannon
originalTitle     Fleetwood Mac: Rhiannon
isAdult                                 0
startYear                            1976
endYear                                \N
runtimeMinutes                          7
genres                        Music,Short
Name: 2005060, dtype: object

(9,)

tconst                     tt1182492
titleType                  tvEpisode
primaryTitle      Gyilkos játszma I.
originalTitle     Gyilkos játszma I.
isAdult                            0
startYear                       2000
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2005061, dtype: object

(9,)

tconst                      tt11824930
titleType                    tvEpisode
primaryTitle            Episode #1.213
originalTitle           Episode #1.213
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005062, dtype: object

(9,)

tconst                      tt11824932
titleType                    tvEpisode
primaryTitle            Episode #1.214
originalTitle           Episode #1.214
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005063, dtype: object

(9,)

tconst                      tt11824934
titleType                    tvEpisode
primaryTitle            Episode #1.215
originalTitle           Episode #1.215
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005064, dtype: object

(9,)

tconst                      tt11824936
titleType                    tvEpisode
primaryTitle            Episode #1.217
originalTitle           Episode #1.217
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005065, dtype: object

(9,)

tconst                      tt11824938
titleType                    tvEpisode
primaryTitle            Episode #1.216
originalTitle           Episode #1.216
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005066, dtype: object

(9,)

tconst                      tt1182493
titleType                   tvEpisode
primaryTitle      Gyilkos játszma II.
originalTitle     Gyilkos játszma II.
isAdult                             0
startYear                        2000
endYear                            \N
runtimeMinutes                     \N
genres             Comedy,Crime,Drama
Name: 2005067, dtype: object

(9,)

tconst                      tt11824940
titleType                    tvEpisode
primaryTitle            Episode #1.218
originalTitle           Episode #1.218
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005068, dtype: object

(9,)

tconst                      tt11824942
titleType                    tvEpisode
primaryTitle            Episode #1.219
originalTitle           Episode #1.219
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005069, dtype: object

(9,)

tconst                      tt11824944
titleType                    tvEpisode
primaryTitle            Episode #1.220
originalTitle           Episode #1.220
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005070, dtype: object

(9,)

tconst              tt11824946
titleType            tvEpisode
primaryTitle      La Sauvagine
originalTitle     La Sauvagine
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              22
genres             Documentary
Name: 2005071, dtype: object

(9,)

tconst                      tt11824948
titleType                    tvEpisode
primaryTitle            Episode #1.221
originalTitle           Episode #1.221
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005072, dtype: object

(9,)

tconst                     tt1182494
titleType                  tvEpisode
primaryTitle      Gyilkos játszma II
originalTitle     Gyilkos játszma II
isAdult                            0
startYear                       2000
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2005073, dtype: object

(9,)

tconst                      tt11824950
titleType                    tvEpisode
primaryTitle            Episode #1.222
originalTitle           Episode #1.222
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005074, dtype: object

(9,)

tconst                      tt11824952
titleType                    tvEpisode
primaryTitle            Episode #1.223
originalTitle           Episode #1.223
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005075, dtype: object

(9,)

tconst                             tt11824954
titleType                               video
primaryTitle      Fleetwood Mac: Say You Will
originalTitle     Fleetwood Mac: Say You Will
isAdult                                     0
startYear                                2003
endYear                                    \N
runtimeMinutes                              4
genres                            Music,Short
Name: 2005076, dtype: object

(9,)

tconst                      tt11824956
titleType                    tvEpisode
primaryTitle            Episode #1.225
originalTitle           Episode #1.225
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005077, dtype: object

(9,)

tconst                      tt11824958
titleType                    tvEpisode
primaryTitle            Episode #1.224
originalTitle           Episode #1.224
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005078, dtype: object

(9,)

tconst                        tt1182495
titleType                     tvEpisode
primaryTitle      Kriszta születésnapja
originalTitle     Kriszta születésnapja
isAdult                               0
startYear                          1977
endYear                              \N
runtimeMinutes                       \N
genres                        Animation
Name: 2005079, dtype: object

(9,)

tconst                      tt11824960
titleType                    tvEpisode
primaryTitle            Episode #1.226
originalTitle           Episode #1.226
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005080, dtype: object

(9,)

tconst                      tt11824962
titleType                    tvEpisode
primaryTitle            Episode #1.227
originalTitle           Episode #1.227
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005081, dtype: object

(9,)

tconst                      tt11824964
titleType                    tvEpisode
primaryTitle            Episode #1.228
originalTitle           Episode #1.228
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005082, dtype: object

(9,)

tconst                      tt11824966
titleType                    tvEpisode
primaryTitle            Episode #1.229
originalTitle           Episode #1.229
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005083, dtype: object

(9,)

tconst                               tt11824968
titleType                                 movie
primaryTitle      The Legendary Marion Williams
originalTitle     The Legendary Marion Williams
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                              Documentary
Name: 2005084, dtype: object

(9,)

tconst                tt1182496
titleType             tvEpisode
primaryTitle       Episode #1.5
originalTitle      Episode #1.5
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               53
genres            Drama,Romance
Name: 2005085, dtype: object

(9,)

tconst                      tt11824972
titleType                    tvEpisode
primaryTitle            Episode #1.230
originalTitle           Episode #1.230
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005086, dtype: object

(9,)

tconst                            tt11824974
titleType                              video
primaryTitle      Fleetwood Mac: Peacekeeper
originalTitle     Fleetwood Mac: Peacekeeper
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                             4
genres                           Music,Short
Name: 2005087, dtype: object

(9,)

tconst                      tt11824976
titleType                    tvEpisode
primaryTitle            Episode #1.601
originalTitle           Episode #1.601
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005088, dtype: object

(9,)

tconst                      tt11824978
titleType                    tvEpisode
primaryTitle            Episode #1.602
originalTitle           Episode #1.602
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005089, dtype: object

(9,)

tconst                tt1182497
titleType             tvEpisode
primaryTitle       Episode #1.6
originalTitle      Episode #1.6
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               53
genres            Drama,Romance
Name: 2005090, dtype: object

(9,)

tconst                      tt11824980
titleType                    tvEpisode
primaryTitle            Episode #1.604
originalTitle           Episode #1.604
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005091, dtype: object

(9,)

tconst                      tt11824982
titleType                    tvEpisode
primaryTitle            Episode #1.603
originalTitle           Episode #1.603
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005092, dtype: object

(9,)

tconst                      tt11824984
titleType                    tvEpisode
primaryTitle            Episode #1.605
originalTitle           Episode #1.605
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005093, dtype: object

(9,)

tconst                      tt11824986
titleType                    tvEpisode
primaryTitle            Episode #1.606
originalTitle           Episode #1.606
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005094, dtype: object

(9,)

tconst                      tt11824988
titleType                    tvEpisode
primaryTitle            Episode #1.607
originalTitle           Episode #1.607
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005095, dtype: object

(9,)

tconst                      tt11824990
titleType                    tvEpisode
primaryTitle            Episode #1.608
originalTitle           Episode #1.608
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005096, dtype: object

(9,)

tconst                      tt11824992
titleType                    tvEpisode
primaryTitle            Episode #1.610
originalTitle           Episode #1.610
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005097, dtype: object

(9,)

tconst                  tt11824994
titleType                    short
primaryTitle      An Indian Abroad
originalTitle     An Indian Abroad
isAdult                          0
startYear                       \N
endYear                         \N
runtimeMinutes                  \N
genres                Comedy,Short
Name: 2005098, dtype: object

(9,)

tconst                      tt11824996
titleType                    tvEpisode
primaryTitle            Episode #1.609
originalTitle           Episode #1.609
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005099, dtype: object

(9,)

tconst                      tt11824998
titleType                    tvEpisode
primaryTitle            Episode #1.611
originalTitle           Episode #1.611
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005100, dtype: object

(9,)

tconst                      tt11825000
titleType                    tvEpisode
primaryTitle            Episode #1.612
originalTitle           Episode #1.612
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005101, dtype: object

(9,)

tconst                                                   tt11825002
titleType                                                 tvEpisode
primaryTitle      Manchester City'ye Ceza, Spurs & Sakatliklar, ...
originalTitle     Manchester City'ye Ceza, Spurs & Sakatliklar, ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   47
genres                                                 Comedy,Sport
Name: 2005102, dtype: object

(9,)

tconst                      tt11825004
titleType                    tvEpisode
primaryTitle            Episode #1.613
originalTitle           Episode #1.613
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005103, dtype: object

(9,)

tconst                      tt11825006
titleType                    tvEpisode
primaryTitle            Episode #1.614
originalTitle           Episode #1.614
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005104, dtype: object

(9,)

tconst                      tt11825008
titleType                    tvEpisode
primaryTitle            Episode #1.615
originalTitle           Episode #1.615
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005105, dtype: object

(9,)

tconst                                tt1182500
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               60
genres                                     News
Name: 2005106, dtype: object

(9,)

tconst                      tt11825010
titleType                    tvEpisode
primaryTitle            Episode #1.616
originalTitle           Episode #1.616
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005107, dtype: object

(9,)

tconst                      tt11825012
titleType                    tvEpisode
primaryTitle            Episode #1.617
originalTitle           Episode #1.617
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005108, dtype: object

(9,)

tconst                      tt11825014
titleType                    tvEpisode
primaryTitle            Episode #1.618
originalTitle           Episode #1.618
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005109, dtype: object

(9,)

tconst                                     tt11825018
titleType                                       video
primaryTitle      Fleetwood Mac: Temporary One (Live)
originalTitle     Fleetwood Mac: Temporary One (Live)
isAdult                                             0
startYear                                        1997
endYear                                            \N
runtimeMinutes                                      3
genres                                    Music,Short
Name: 2005110, dtype: object

(9,)

tconst                                tt1182501
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Music
Name: 2005111, dtype: object

(9,)

tconst                      tt11825020
titleType                    tvEpisode
primaryTitle            Episode #1.620
originalTitle           Episode #1.620
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005112, dtype: object

(9,)

tconst                      tt11825022
titleType                    tvEpisode
primaryTitle            Episode #1.619
originalTitle           Episode #1.619
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005113, dtype: object

(9,)

tconst               tt11825024
titleType             tvEpisode
primaryTitle      Episode #2.20
originalTitle     Episode #2.20
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005114, dtype: object

(9,)

tconst                      tt11825026
titleType                    tvEpisode
primaryTitle            Episode #1.841
originalTitle           Episode #1.841
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005115, dtype: object

(9,)

tconst                      tt11825028
titleType                    tvEpisode
primaryTitle            Episode #1.843
originalTitle           Episode #1.843
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005116, dtype: object

(9,)

tconst                  tt1182502
titleType               tvEpisode
primaryTitle      Episode #12.106
originalTitle     Episode #12.106
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2005117, dtype: object

(9,)

tconst                      tt11825030
titleType                    tvEpisode
primaryTitle            Episode #1.842
originalTitle           Episode #1.842
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005118, dtype: object

(9,)

tconst                 tt11825032
titleType               videoGame
primaryTitle      Just Dance 2016
originalTitle     Just Dance 2016
isAdult                         0
startYear                    2015
endYear                        \N
runtimeMinutes                 \N
genres                      Music
Name: 2005119, dtype: object

(9,)

tconst                      tt11825034
titleType                    tvEpisode
primaryTitle            Episode #1.844
originalTitle           Episode #1.844
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005120, dtype: object

(9,)

tconst                      tt11825036
titleType                    tvEpisode
primaryTitle            Episode #1.846
originalTitle           Episode #1.846
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005121, dtype: object

(9,)

tconst                      tt11825038
titleType                    tvEpisode
primaryTitle            Episode #1.845
originalTitle           Episode #1.845
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005122, dtype: object

(9,)

tconst              tt1182503
titleType           tvEpisode
primaryTitle      Kratki spoj
originalTitle     Kratki spoj
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2005123, dtype: object

(9,)

tconst                      tt11825040
titleType                    tvEpisode
primaryTitle            Episode #1.847
originalTitle           Episode #1.847
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005124, dtype: object

(9,)

tconst                      tt11825042
titleType                    tvEpisode
primaryTitle            Episode #1.848
originalTitle           Episode #1.848
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005125, dtype: object

(9,)

tconst                      tt11825044
titleType                    tvEpisode
primaryTitle            Episode #1.849
originalTitle           Episode #1.849
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005126, dtype: object

(9,)

tconst                      tt11825046
titleType                    tvEpisode
primaryTitle            Episode #1.850
originalTitle           Episode #1.850
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005127, dtype: object

(9,)

tconst                      tt11825048
titleType                    tvEpisode
primaryTitle            Episode #1.851
originalTitle           Episode #1.851
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005128, dtype: object

(9,)

tconst                 tt1182504
titleType              tvEpisode
primaryTitle      Na rubu zakona
originalTitle     Na rubu zakona
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005129, dtype: object

(9,)

tconst              tt11825050
titleType                short
primaryTitle           Matilde
originalTitle          Matilde
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes               8
genres            Comedy,Short
Name: 2005130, dtype: object

(9,)

tconst                      tt11825052
titleType                    tvEpisode
primaryTitle            Episode #1.852
originalTitle           Episode #1.852
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005131, dtype: object

(9,)

tconst                      tt11825054
titleType                    tvEpisode
primaryTitle            Episode #1.853
originalTitle           Episode #1.853
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005132, dtype: object

(9,)

tconst                      tt11825056
titleType                    tvEpisode
primaryTitle            Episode #1.854
originalTitle           Episode #1.854
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005133, dtype: object

(9,)

tconst                      tt11825058
titleType                    tvEpisode
primaryTitle            Episode #1.855
originalTitle           Episode #1.855
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005134, dtype: object

(9,)

tconst                                              tt1182505
titleType                                           tvEpisode
primaryTitle      Eleni Vlahou: Mia dimosiografos thymatai...
originalTitle     Eleni Vlahou: Mia dimosiografos thymatai...
isAdult                                                     0
startYear                                                1991
endYear                                                    \N
runtimeMinutes                                             \N
genres                          Documentary,History,Talk-Show
Name: 2005135, dtype: object

(9,)

tconst                      tt11825060
titleType                    tvEpisode
primaryTitle            Episode #1.857
originalTitle           Episode #1.857
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005136, dtype: object

(9,)

tconst                      tt11825062
titleType                    tvEpisode
primaryTitle            Episode #1.856
originalTitle           Episode #1.856
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005137, dtype: object

(9,)

tconst                               tt11825064
titleType                                 video
primaryTitle      Fleetwood Mac: Not That Funny
originalTitle     Fleetwood Mac: Not That Funny
isAdult                                       0
startYear                                  1979
endYear                                      \N
runtimeMinutes                                4
genres                              Music,Short
Name: 2005138, dtype: object

(9,)

tconst                      tt11825066
titleType                    tvEpisode
primaryTitle            Episode #1.858
originalTitle           Episode #1.858
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005139, dtype: object

(9,)

tconst                 tt11825068
titleType               tvEpisode
primaryTitle        Gastón Gaudio
originalTitle       Gastón Gaudio
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2005140, dtype: object

(9,)

tconst                                tt1182506
titleType                             tvEpisode
primaryTitle                I diki tou Naftikou
originalTitle               I diki tou Naftikou
isAdult                                       0
startYear                                  1994
endYear                                      \N
runtimeMinutes                               \N
genres            Documentary,History,Talk-Show
Name: 2005141, dtype: object

(9,)

tconst                      tt11825070
titleType                    tvEpisode
primaryTitle            Episode #1.860
originalTitle           Episode #1.860
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005142, dtype: object

(9,)

tconst                      tt11825072
titleType                    tvEpisode
primaryTitle            Episode #1.859
originalTitle           Episode #1.859
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005143, dtype: object

(9,)

tconst                                tt11825074
titleType                              tvEpisode
primaryTitle      Episode dated 26 February 2020
originalTitle     Episode dated 26 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005144, dtype: object

(9,)

tconst                           tt11825076
titleType                             short
primaryTitle      The Weight of Forgiveness
originalTitle     The Weight of Forgiveness
isAdult                                   0
startYear                              2016
endYear                                  \N
runtimeMinutes                           \N
genres                        Fantasy,Short
Name: 2005145, dtype: object

(9,)

tconst                 tt11825078
titleType               tvEpisode
primaryTitle         José Chatruc
originalTitle        José Chatruc
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2005146, dtype: object

(9,)

tconst                     tt1182507
titleType                  tvEpisode
primaryTitle            Episode #1.6
originalTitle           Episode #1.6
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2005147, dtype: object

(9,)

tconst                                tt11825080
titleType                              tvEpisode
primaryTitle      Episode dated 27 February 2020
originalTitle     Episode dated 27 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005148, dtype: object

(9,)

tconst                               tt11825082
titleType                                 short
primaryTitle      An evening about Alan Smithee
originalTitle     An evening about Alan Smithee
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                             Comedy,Short
Name: 2005149, dtype: object

(9,)

tconst                      tt11825084
titleType                    tvEpisode
primaryTitle           Episode #1.1061
originalTitle          Episode #1.1061
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005150, dtype: object

(9,)

tconst                      tt11825086
titleType                    tvEpisode
primaryTitle           Episode #1.1063
originalTitle          Episode #1.1063
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005151, dtype: object

(9,)

tconst                      tt11825088
titleType                    tvEpisode
primaryTitle           Episode #1.1062
originalTitle          Episode #1.1062
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005152, dtype: object

(9,)

tconst                              tt1182508
titleType                           tvEpisode
primaryTitle      The Late Captain Binghamton
originalTitle     The Late Captain Binghamton
isAdult                                     0
startYear                                1965
endYear                                    \N
runtimeMinutes                             30
genres                             Comedy,War
Name: 2005153, dtype: object

(9,)

tconst                      tt11825090
titleType                    tvEpisode
primaryTitle           Episode #1.1065
originalTitle          Episode #1.1065
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005154, dtype: object

(9,)

tconst                      tt11825092
titleType                    tvEpisode
primaryTitle           Episode #1.1064
originalTitle          Episode #1.1064
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005155, dtype: object

(9,)

tconst                      tt11825094
titleType                    tvEpisode
primaryTitle           Episode #1.1066
originalTitle          Episode #1.1066
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005156, dtype: object

(9,)

tconst                      tt11825096
titleType                    tvEpisode
primaryTitle           Episode #1.1067
originalTitle          Episode #1.1067
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005157, dtype: object

(9,)

tconst                      tt11825098
titleType                    tvEpisode
primaryTitle           Episode #1.1068
originalTitle          Episode #1.1068
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005158, dtype: object

(9,)

tconst                               tt1182509
titleType                            tvEpisode
primaryTitle      McHale's Floating Laundromat
originalTitle     McHale's Floating Laundromat
isAdult                                      0
startYear                                 1965
endYear                                     \N
runtimeMinutes                              30
genres                              Comedy,War
Name: 2005159, dtype: object

(9,)

tconst                      tt11825100
titleType                    tvEpisode
primaryTitle           Episode #1.1069
originalTitle          Episode #1.1069
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005160, dtype: object

(9,)

tconst                      tt11825102
titleType                    tvEpisode
primaryTitle           Episode #1.1070
originalTitle          Episode #1.1070
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005161, dtype: object

(9,)

tconst                      tt11825104
titleType                    tvEpisode
primaryTitle           Episode #1.1071
originalTitle          Episode #1.1071
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005162, dtype: object

(9,)

tconst              tt11825106
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              80
genres               Talk-Show
Name: 2005163, dtype: object

(9,)

tconst                            tt1182510
titleType                         tvEpisode
primaryTitle      All Chiefs and No Indians
originalTitle     All Chiefs and No Indians
isAdult                                   0
startYear                              1965
endYear                                  \N
runtimeMinutes                           30
genres                           Comedy,War
Name: 2005164, dtype: object

(9,)

tconst                      tt11825110
titleType                    tvEpisode
primaryTitle           Episode #1.1072
originalTitle          Episode #1.1072
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005165, dtype: object

(9,)

tconst                      tt11825112
titleType                    tvEpisode
primaryTitle           Episode #1.1074
originalTitle          Episode #1.1074
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005166, dtype: object

(9,)

tconst                      tt11825114
titleType                    tvEpisode
primaryTitle           Episode #1.1073
originalTitle          Episode #1.1073
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005167, dtype: object

(9,)

tconst                      tt11825116
titleType                    tvEpisode
primaryTitle           Episode #1.1075
originalTitle          Episode #1.1075
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005168, dtype: object

(9,)

tconst                      tt11825118
titleType                    tvEpisode
primaryTitle           Episode #1.1076
originalTitle          Episode #1.1076
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005169, dtype: object

(9,)

tconst                                   tt1182511
titleType                                tvEpisode
primaryTitle      The Seven Faces of Ensign Parker
originalTitle     The Seven Faces of Ensign Parker
isAdult                                          0
startYear                                     1965
endYear                                         \N
runtimeMinutes                                  30
genres                                  Comedy,War
Name: 2005170, dtype: object

(9,)

tconst                      tt11825120
titleType                    tvEpisode
primaryTitle           Episode #1.1077
originalTitle          Episode #1.1077
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005171, dtype: object

(9,)

tconst                      tt11825122
titleType                    tvEpisode
primaryTitle           Episode #1.1078
originalTitle          Episode #1.1078
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005172, dtype: object

(9,)

tconst                      tt11825124
titleType                    tvEpisode
primaryTitle           Episode #1.1079
originalTitle          Episode #1.1079
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005173, dtype: object

(9,)

tconst                      tt11825126
titleType                    tvEpisode
primaryTitle           Episode #1.1080
originalTitle          Episode #1.1080
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005174, dtype: object

(9,)

tconst                 tt11825128
titleType               tvEpisode
primaryTitle       Bernardo Romeo
originalTitle      Bernardo Romeo
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2005175, dtype: object

(9,)

tconst                       tt1182512
titleType                    tvEpisode
primaryTitle      The Return of Maggie
originalTitle     The Return of Maggie
isAdult                              0
startYear                         1965
endYear                             \N
runtimeMinutes                      30
genres                      Comedy,War
Name: 2005176, dtype: object

(9,)

tconst                      tt11825130
titleType                    tvEpisode
primaryTitle           Episode #1.1301
originalTitle          Episode #1.1301
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005177, dtype: object

(9,)

tconst                      tt11825132
titleType                    tvEpisode
primaryTitle           Episode #1.1303
originalTitle          Episode #1.1303
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005178, dtype: object

(9,)

tconst                      tt11825134
titleType                    tvEpisode
primaryTitle           Episode #1.1302
originalTitle          Episode #1.1302
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005179, dtype: object

(9,)

tconst                      tt11825136
titleType                    tvEpisode
primaryTitle           Episode #1.1304
originalTitle          Episode #1.1304
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005180, dtype: object

(9,)

tconst                      tt11825138
titleType                    tvEpisode
primaryTitle           Episode #1.1306
originalTitle          Episode #1.1306
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005181, dtype: object

(9,)

tconst                           tt1182513
titleType                        tvEpisode
primaryTitle      Send This Ensign to Camp
originalTitle     Send This Ensign to Camp
isAdult                                  0
startYear                             1965
endYear                                 \N
runtimeMinutes                          30
genres                          Comedy,War
Name: 2005182, dtype: object

(9,)

tconst                      tt11825140
titleType                    tvEpisode
primaryTitle           Episode #1.1305
originalTitle          Episode #1.1305
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005183, dtype: object

(9,)

tconst                                             tt11825142
titleType                                               video
primaryTitle      Stevie Nicks: Stop Draggin' My Heart Around
originalTitle     Stevie Nicks: Stop Draggin' My Heart Around
isAdult                                                     0
startYear                                                1981
endYear                                                    \N
runtimeMinutes                                              4
genres                                            Music,Short
Name: 2005184, dtype: object

(9,)

tconst                      tt11825144
titleType                    tvEpisode
primaryTitle           Episode #1.1307
originalTitle          Episode #1.1307
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005185, dtype: object

(9,)

tconst                      tt11825146
titleType                    tvEpisode
primaryTitle           Episode #1.1309
originalTitle          Episode #1.1309
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005186, dtype: object

(9,)

tconst                      tt11825148
titleType                    tvEpisode
primaryTitle           Episode #1.1308
originalTitle          Episode #1.1308
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005187, dtype: object

(9,)

tconst                        tt1182514
titleType                     tvEpisode
primaryTitle      By the Numbers, Paint
originalTitle     By the Numbers, Paint
isAdult                               0
startYear                          1965
endYear                              \N
runtimeMinutes                       30
genres                       Comedy,War
Name: 2005188, dtype: object

(9,)

tconst                      tt11825150
titleType                    tvEpisode
primaryTitle           Episode #1.1310
originalTitle          Episode #1.1310
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005189, dtype: object

(9,)

tconst                      tt11825152
titleType                    tvEpisode
primaryTitle           Episode #1.1311
originalTitle          Episode #1.1311
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005190, dtype: object

(9,)

tconst                      tt11825154
titleType                    tvEpisode
primaryTitle           Episode #1.1313
originalTitle          Episode #1.1313
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005191, dtype: object

(9,)

tconst                      tt11825156
titleType                    tvEpisode
primaryTitle           Episode #1.1312
originalTitle          Episode #1.1312
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005192, dtype: object

(9,)

tconst                     tt1182515
titleType                  tvEpisode
primaryTitle      Chuckie Cottontail
originalTitle     Chuckie Cottontail
isAdult                            0
startYear                       1965
endYear                           \N
runtimeMinutes                    30
genres                    Comedy,War
Name: 2005193, dtype: object

(9,)

tconst                     tt11825160
titleType                   tvEpisode
primaryTitle      Gustavo Campagnuolo
originalTitle     Gustavo Campagnuolo
isAdult                             0
startYear                        2018
endYear                            \N
runtimeMinutes                     \N
genres                Sport,Talk-Show
Name: 2005194, dtype: object

(9,)

tconst                     tt11825162
titleType                       short
primaryTitle                Rage Club
originalTitle               Rage Club
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Short
Name: 2005195, dtype: object

(9,)

tconst                      tt11825166
titleType                    tvEpisode
primaryTitle           Episode #1.1315
originalTitle          Episode #1.1315
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005196, dtype: object

(9,)

tconst                      tt11825168
titleType                    tvEpisode
primaryTitle           Episode #1.1314
originalTitle          Episode #1.1314
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005197, dtype: object

(9,)

tconst                           tt1182516
titleType                        tvEpisode
primaryTitle      The Great Necklace Caper
originalTitle     The Great Necklace Caper
isAdult                                  0
startYear                             1965
endYear                                 \N
runtimeMinutes                          30
genres                          Comedy,War
Name: 2005198, dtype: object

(9,)

tconst                      tt11825170
titleType                    tvEpisode
primaryTitle           Episode #1.1316
originalTitle          Episode #1.1316
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005199, dtype: object

(9,)

tconst                      tt11825172
titleType                    tvEpisode
primaryTitle           Episode #1.1317
originalTitle          Episode #1.1317
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005200, dtype: object

(9,)

tconst                 tt11825174
titleType               tvEpisode
primaryTitle       Horacio Agulla
originalTitle      Horacio Agulla
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2005201, dtype: object

(9,)

tconst                      tt11825176
titleType                    tvEpisode
primaryTitle           Episode #1.1319
originalTitle          Episode #1.1319
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005202, dtype: object

(9,)

tconst                      tt11825178
titleType                    tvEpisode
primaryTitle           Episode #1.1318
originalTitle          Episode #1.1318
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005203, dtype: object

(9,)

tconst               tt1182517
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2005204, dtype: object

(9,)

tconst                      tt11825180
titleType                    tvEpisode
primaryTitle           Episode #1.1320
originalTitle          Episode #1.1320
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005205, dtype: object

(9,)

tconst                                                   tt11825182
titleType                                                     video
primaryTitle      Tom Petty and the Heartbreakers Feat. Stevie N...
originalTitle     Tom Petty and the Heartbreakers Feat. Stevie N...
isAdult                                                           0
startYear                                                      1981
endYear                                                          \N
runtimeMinutes                                                    5
genres                                                  Music,Short
Name: 2005206, dtype: object

(9,)

tconst                tt11825184
titleType              tvEpisode
primaryTitle      Episode #1.161
originalTitle     Episode #1.161
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005207, dtype: object

(9,)

tconst                 tt11825186
titleType               tvEpisode
primaryTitle            Luis Lobo
originalTitle           Luis Lobo
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2005208, dtype: object

(9,)

tconst                tt11825188
titleType              tvEpisode
primaryTitle      Episode #1.121
originalTitle     Episode #1.121
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Action
Name: 2005209, dtype: object

(9,)

tconst                               tt1182518
titleType                            tvEpisode
primaryTitle      Besoin urgent de changements
originalTitle     Besoin urgent de changements
isAdult                                      0
startYear                                 2003
endYear                                     \N
runtimeMinutes                              \N
genres                           Drama,Romance
Name: 2005210, dtype: object

(9,)

tconst                       tt11825190
titleType                     tvEpisode
primaryTitle      Red, White, and Ewwww
originalTitle     Red, White, and Ewwww
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       44
genres                       Reality-TV
Name: 2005211, dtype: object

(9,)

tconst                 tt11825194
titleType               videoGame
primaryTitle      Just Dance 2017
originalTitle     Just Dance 2017
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Music
Name: 2005212, dtype: object

(9,)

tconst                tt11825196
titleType              tvEpisode
primaryTitle      Episode #1.162
originalTitle     Episode #1.162
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005213, dtype: object

(9,)

tconst                tt11825198
titleType              tvEpisode
primaryTitle      Episode #1.163
originalTitle     Episode #1.163
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005214, dtype: object

(9,)

tconst                   tt1182519
titleType                tvEpisode
primaryTitle      L'homme sandwich
originalTitle     L'homme sandwich
isAdult                          0
startYear                     2003
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2005215, dtype: object

(9,)

tconst                tt11825200
titleType              tvEpisode
primaryTitle      Episode #1.164
originalTitle     Episode #1.164
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005216, dtype: object

(9,)

tconst                tt11825202
titleType              tvEpisode
primaryTitle      Episode #1.165
originalTitle     Episode #1.165
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005217, dtype: object

(9,)

tconst                tt11825204
titleType              tvEpisode
primaryTitle      Episode #1.166
originalTitle     Episode #1.166
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005218, dtype: object

(9,)

tconst              tt11825206
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2005219, dtype: object

(9,)

tconst                           tt1182520
titleType                        tvEpisode
primaryTitle      Le monstre de l'intimité
originalTitle     Le monstre de l'intimité
isAdult                                  0
startYear                             2003
endYear                                 \N
runtimeMinutes                          \N
genres                       Drama,Romance
Name: 2005220, dtype: object

(9,)

tconst                tt11825210
titleType                  short
primaryTitle                Vows
originalTitle               Vows
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                 5
genres            Short,Thriller
Name: 2005221, dtype: object

(9,)

tconst                tt11825212
titleType              tvEpisode
primaryTitle      Episode #1.167
originalTitle     Episode #1.167
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005222, dtype: object

(9,)

tconst                tt11825214
titleType              tvEpisode
primaryTitle      Episode #1.168
originalTitle     Episode #1.168
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005223, dtype: object

(9,)

tconst                tt11825216
titleType              tvEpisode
primaryTitle      Episode #1.169
originalTitle     Episode #1.169
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005224, dtype: object

(9,)

tconst                tt11825218
titleType              tvEpisode
primaryTitle      Episode #1.171
originalTitle     Episode #1.171
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005225, dtype: object

(9,)

tconst                                tt1182521
titleType                             tvEpisode
primaryTitle      Les griffes de l'intelligence
originalTitle     Les griffes de l'intelligence
isAdult                                       0
startYear                                  2003
endYear                                      \N
runtimeMinutes                               \N
genres                            Drama,Romance
Name: 2005226, dtype: object

(9,)

tconst                   tt11825220
titleType                     short
primaryTitle             Low Season
originalTitle            Low Season
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2005227, dtype: object

(9,)

tconst                tt11825222
titleType              tvEpisode
primaryTitle      Episode #1.172
originalTitle     Episode #1.172
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005228, dtype: object

(9,)

tconst                tt11825224
titleType              tvEpisode
primaryTitle      Episode #1.170
originalTitle     Episode #1.170
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005229, dtype: object

(9,)

tconst                tt11825228
titleType              tvEpisode
primaryTitle      Episode #1.173
originalTitle     Episode #1.173
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005230, dtype: object

(9,)

tconst                  tt1182522
titleType               tvEpisode
primaryTitle      Pozar w klinice
originalTitle     Pozar w klinice
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 49
genres              Drama,Romance
Name: 2005231, dtype: object

(9,)

tconst                tt11825230
titleType              tvEpisode
primaryTitle      Episode #1.174
originalTitle     Episode #1.174
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005232, dtype: object

(9,)

tconst                tt11825232
titleType              tvEpisode
primaryTitle      Episode #1.175
originalTitle     Episode #1.175
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005233, dtype: object

(9,)

tconst                        tt11825234
titleType                      tvEpisode
primaryTitle      Merkwürdiges Verhalten
originalTitle     Merkwürdiges Verhalten
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                           Romance
Name: 2005234, dtype: object

(9,)

tconst                tt11825236
titleType              tvEpisode
primaryTitle      Episode #1.176
originalTitle     Episode #1.176
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005235, dtype: object

(9,)

tconst                tt11825238
titleType              tvEpisode
primaryTitle      Episode #1.177
originalTitle     Episode #1.177
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005236, dtype: object

(9,)

tconst                     tt1182523
titleType                  tvEpisode
primaryTitle      A Fork in the Toad
originalTitle     A Fork in the Toad
isAdult                            0
startYear                       2006
endYear                           \N
runtimeMinutes                    \N
genres                 Drama,Romance
Name: 2005237, dtype: object

(9,)

tconst                tt11825240
titleType              tvEpisode
primaryTitle      Episode #1.178
originalTitle     Episode #1.178
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005238, dtype: object

(9,)

tconst                tt11825242
titleType              tvEpisode
primaryTitle      Episode #1.179
originalTitle     Episode #1.179
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005239, dtype: object

(9,)

tconst                tt11825244
titleType              tvEpisode
primaryTitle      Episode #1.180
originalTitle     Episode #1.180
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005240, dtype: object

(9,)

tconst                tt11825246
titleType              tvEpisode
primaryTitle      Episode #1.401
originalTitle     Episode #1.401
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005241, dtype: object

(9,)

tconst              tt11825248
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2005242, dtype: object

(9,)

tconst                                tt1182524
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2005243, dtype: object

(9,)

tconst                tt11825250
titleType              tvEpisode
primaryTitle      Episode #1.402
originalTitle     Episode #1.402
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005244, dtype: object

(9,)

tconst                tt11825252
titleType              tvEpisode
primaryTitle      Episode #1.403
originalTitle     Episode #1.403
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005245, dtype: object

(9,)

tconst                tt11825254
titleType              tvEpisode
primaryTitle      Episode #1.404
originalTitle     Episode #1.404
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005246, dtype: object

(9,)

tconst                tt11825256
titleType              tvEpisode
primaryTitle      Meet Matt Shep
originalTitle     Meet Matt Shep
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Short
Name: 2005247, dtype: object

(9,)

tconst                tt11825258
titleType              tvEpisode
primaryTitle      Episode #1.406
originalTitle     Episode #1.406
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005248, dtype: object

(9,)

tconst                tt1182525
titleType             tvEpisode
primaryTitle      Episode #2.15
originalTitle     Episode #2.15
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005249, dtype: object

(9,)

tconst                tt11825260
titleType              tvEpisode
primaryTitle      Episode #1.405
originalTitle     Episode #1.405
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005250, dtype: object

(9,)

tconst                     tt11825262
titleType                   tvEpisode
primaryTitle        Roanoke (No. 139)
originalTitle       Roanoke (No. 139)
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     43
genres            Crime,Drama,Mystery
Name: 2005251, dtype: object

(9,)

tconst                tt11825264
titleType              tvEpisode
primaryTitle      Episode #1.407
originalTitle     Episode #1.407
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005252, dtype: object

(9,)

tconst                tt11825266
titleType              tvEpisode
primaryTitle      Episode #1.408
originalTitle     Episode #1.408
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005253, dtype: object

(9,)

tconst                tt11825268
titleType              tvEpisode
primaryTitle      Episode #1.409
originalTitle     Episode #1.409
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005254, dtype: object

(9,)

tconst               tt1182526
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              \N
genres               Adventure
Name: 2005255, dtype: object

(9,)

tconst                tt11825270
titleType              tvEpisode
primaryTitle      Episode #1.410
originalTitle     Episode #1.410
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005256, dtype: object

(9,)

tconst                tt11825272
titleType              tvEpisode
primaryTitle      Episode #1.411
originalTitle     Episode #1.411
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005257, dtype: object

(9,)

tconst                tt11825276
titleType              tvEpisode
primaryTitle      Episode #1.413
originalTitle     Episode #1.413
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005258, dtype: object

(9,)

tconst                tt11825278
titleType              tvEpisode
primaryTitle      Episode #1.414
originalTitle     Episode #1.414
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005259, dtype: object

(9,)

tconst                                tt1182527
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                     News,Sport,Talk-Show
Name: 2005260, dtype: object

(9,)

tconst                tt11825280
titleType              tvEpisode
primaryTitle      Episode #1.415
originalTitle     Episode #1.415
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005261, dtype: object

(9,)

tconst                     tt11825282
titleType                   tvEpisode
primaryTitle      How to Make Friends
originalTitle     How to Make Friends
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                   Comedy,Short
Name: 2005262, dtype: object

(9,)

tconst                tt11825284
titleType              tvEpisode
primaryTitle      Episode #1.416
originalTitle     Episode #1.416
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005263, dtype: object

(9,)

tconst                tt11825286
titleType              tvEpisode
primaryTitle      Episode #1.417
originalTitle     Episode #1.417
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005264, dtype: object

(9,)

tconst                tt11825288
titleType              tvEpisode
primaryTitle      Episode #1.418
originalTitle     Episode #1.418
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005265, dtype: object

(9,)

tconst                 tt1182528
titleType              tvEpisode
primaryTitle      Episode #1.184
originalTitle     Episode #1.184
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2005266, dtype: object

(9,)

tconst                  tt11825290
titleType                    short
primaryTitle      The Side Effects
originalTitle     The Side Effects
isAdult                          0
startYear                       \N
endYear                         \N
runtimeMinutes                  \N
genres                Comedy,Short
Name: 2005267, dtype: object

(9,)

tconst                tt11825292
titleType              tvEpisode
primaryTitle      Episode #1.419
originalTitle     Episode #1.419
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005268, dtype: object

(9,)

tconst                tt11825294
titleType              tvEpisode
primaryTitle      Episode #1.420
originalTitle     Episode #1.420
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005269, dtype: object

(9,)

tconst                tt11825296
titleType              tvEpisode
primaryTitle      Episode #1.661
originalTitle     Episode #1.661
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005270, dtype: object

(9,)

tconst                       tt1182529
titleType                    tvEpisode
primaryTitle             Episode #1.12
originalTitle            Episode #1.12
isAdult                              0
startYear                         2004
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005271, dtype: object

(9,)

tconst                tt11825300
titleType              tvEpisode
primaryTitle      Episode #1.662
originalTitle     Episode #1.662
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005272, dtype: object

(9,)

tconst                      tt11825302
titleType                    tvEpisode
primaryTitle      How to Process Grief
originalTitle     How to Process Grief
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                    Comedy,Short
Name: 2005273, dtype: object

(9,)

tconst                tt11825304
titleType              tvEpisode
primaryTitle      Episode #1.663
originalTitle     Episode #1.663
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005274, dtype: object

(9,)

tconst                                   tt11825306
titleType                                 tvEpisode
primaryTitle      Adhiraj Cursed To Die In 48 Hours
originalTitle     Adhiraj Cursed To Die In 48 Hours
isAdult                                           0
startYear                                        \N
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Crime
Name: 2005275, dtype: object

(9,)

tconst                tt11825308
titleType              tvEpisode
primaryTitle      Episode #1.666
originalTitle     Episode #1.666
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005276, dtype: object

(9,)

tconst                       tt1182530
titleType                    tvEpisode
primaryTitle             Episode #1.13
originalTitle            Episode #1.13
isAdult                              0
startYear                         2004
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2005277, dtype: object

(9,)

tconst                        tt11825310
titleType                      tvEpisode
primaryTitle      Honeymoon With A Ghost
originalTitle     Honeymoon With A Ghost
isAdult                                0
startYear                             \N
endYear                               \N
runtimeMinutes                        \N
genres                             Crime
Name: 2005278, dtype: object

(9,)

tconst                              tt11825312
titleType                            tvEpisode
primaryTitle      How to get through a Breakup
originalTitle     How to get through a Breakup
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                            Comedy,Short
Name: 2005279, dtype: object

(9,)

tconst                tt11825314
titleType              tvEpisode
primaryTitle      Episode #1.667
originalTitle     Episode #1.667
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005280, dtype: object

(9,)

tconst                tt11825316
titleType              tvEpisode
primaryTitle      Episode #1.668
originalTitle     Episode #1.668
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005281, dtype: object

(9,)

tconst                                       tt11825318
titleType                                         video
primaryTitle      Stevie Nicks: Leather and Lace (Live)
originalTitle     Stevie Nicks: Leather and Lace (Live)
isAdult                                               0
startYear                                          1981
endYear                                              \N
runtimeMinutes                                        4
genres                                      Music,Short
Name: 2005282, dtype: object

(9,)

tconst                tt1182531
titleType             tvEpisode
primaryTitle      Episode #2.20
originalTitle     Episode #2.20
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2005283, dtype: object

(9,)

tconst                tt11825320
titleType              tvEpisode
primaryTitle      Episode #1.669
originalTitle     Episode #1.669
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005284, dtype: object

(9,)

tconst                tt11825322
titleType              tvEpisode
primaryTitle      Episode #1.670
originalTitle     Episode #1.670
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005285, dtype: object

(9,)

tconst              tt11825324
titleType                short
primaryTitle               Gum
originalTitle              Gum
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes               9
genres            Comedy,Short
Name: 2005286, dtype: object

(9,)

tconst                            tt11825326
titleType                              video
primaryTitle      Do you mind coming with me
originalTitle     Do you mind coming with me
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                           Music,Short
Name: 2005287, dtype: object

(9,)

tconst                                    tt11825328
titleType                                  tvEpisode
primaryTitle      Star Wars 9: L'ascension Du Sketch
originalTitle     Star Wars 9: L'ascension Du Sketch
isAdult                                            0
startYear                                       2019
endYear                                           \N
runtimeMinutes                                    \N
genres                                            \N
Name: 2005288, dtype: object

(9,)

tconst                 tt1182532
titleType              tvEpisode
primaryTitle      Eaux profondes
originalTitle     Eaux profondes
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005289, dtype: object

(9,)

tconst                                                   tt11825330
titleType                                                 tvEpisode
primaryTitle      How to be honest about your Eating Disorder (S...
originalTitle     How to be honest about your Eating Disorder (S...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                 Comedy,Short
Name: 2005290, dtype: object

(9,)

tconst                           tt11825332
titleType                         tvEpisode
primaryTitle      How to Date like an Adult
originalTitle     How to Date like an Adult
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                         Comedy,Short
Name: 2005291, dtype: object

(9,)

tconst                tt11825334
titleType              tvEpisode
primaryTitle      Episode #1.671
originalTitle     Episode #1.671
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005292, dtype: object

(9,)

tconst                tt11825336
titleType              tvEpisode
primaryTitle      Episode #1.672
originalTitle     Episode #1.672
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005293, dtype: object

(9,)

tconst                     tt11825338
titleType                       short
primaryTitle      Delusion: Long Rope
originalTitle     Delusion: Long Rope
isAdult                             0
startYear                        2015
endYear                            \N
runtimeMinutes                     \N
genres                    Music,Short
Name: 2005294, dtype: object

(9,)

tconst               tt1182533
titleType            tvEpisode
primaryTitle      Tirs croisés
originalTitle     Tirs croisés
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                   Crime
Name: 2005295, dtype: object

(9,)

tconst                tt11825340
titleType              tvEpisode
primaryTitle      Episode #1.673
originalTitle     Episode #1.673
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005296, dtype: object

(9,)

tconst                tt11825342
titleType              tvEpisode
primaryTitle      Episode #1.674
originalTitle     Episode #1.674
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005297, dtype: object

(9,)

tconst                tt11825346
titleType              tvEpisode
primaryTitle      Episode #1.675
originalTitle     Episode #1.675
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005298, dtype: object

(9,)

tconst               tt11825348
titleType                 video
primaryTitle              Pryme
originalTitle             Pryme
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Musical,Short
Name: 2005299, dtype: object

(9,)

tconst                                tt1182534
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2005300, dtype: object

(9,)

tconst                                   tt11825350
titleType                                 tvEpisode
primaryTitle      How to Find Therapy (on a budget)
originalTitle     How to Find Therapy (on a budget)
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                 Comedy,Short
Name: 2005301, dtype: object

(9,)

tconst                tt11825352
titleType              tvEpisode
primaryTitle      Episode #1.677
originalTitle     Episode #1.677
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005302, dtype: object

(9,)

tconst                tt11825354
titleType              tvEpisode
primaryTitle      Episode #1.676
originalTitle     Episode #1.676
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005303, dtype: object

(9,)

tconst                tt11825356
titleType              tvEpisode
primaryTitle      Episode #1.678
originalTitle     Episode #1.678
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005304, dtype: object

(9,)

tconst                tt11825358
titleType              tvEpisode
primaryTitle      Episode #1.679
originalTitle     Episode #1.679
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005305, dtype: object

(9,)

tconst                       tt1182535
titleType                    tvEpisode
primaryTitle               Confidences
originalTitle              Confidences
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005306, dtype: object

(9,)

tconst                tt11825360
titleType              tvEpisode
primaryTitle      Episode #1.680
originalTitle     Episode #1.680
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005307, dtype: object

(9,)

tconst                tt11825362
titleType              tvEpisode
primaryTitle      Episode #1.882
originalTitle     Episode #1.882
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005308, dtype: object

(9,)

tconst                tt11825364
titleType              tvEpisode
primaryTitle      Episode #1.881
originalTitle     Episode #1.881
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005309, dtype: object

(9,)

tconst                tt11825366
titleType              tvEpisode
primaryTitle      Episode #1.883
originalTitle     Episode #1.883
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005310, dtype: object

(9,)

tconst               tt11825368
titleType             tvEpisode
primaryTitle      Episode #13.3
originalTitle     Episode #13.3
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005311, dtype: object

(9,)

tconst                       tt1182536
titleType                    tvEpisode
primaryTitle             Confrontation
originalTitle            Confrontation
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005312, dtype: object

(9,)

tconst                       tt11825370
titleType                     tvEpisode
primaryTitle      A Mother's Conviction
originalTitle     A Mother's Conviction
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres                            Crime
Name: 2005313, dtype: object

(9,)

tconst                tt11825372
titleType              tvEpisode
primaryTitle      Episode #1.885
originalTitle     Episode #1.885
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005314, dtype: object

(9,)

tconst                tt11825374
titleType              tvEpisode
primaryTitle      Episode #1.886
originalTitle     Episode #1.886
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005315, dtype: object

(9,)

tconst                tt11825376
titleType              tvEpisode
primaryTitle      Episode #1.887
originalTitle     Episode #1.887
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005316, dtype: object

(9,)

tconst                tt11825378
titleType              tvEpisode
primaryTitle      Episode #1.888
originalTitle     Episode #1.888
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005317, dtype: object

(9,)

tconst                       tt1182537
titleType                    tvEpisode
primaryTitle                Confusions
originalTitle               Confusions
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005318, dtype: object

(9,)

tconst                tt11825380
titleType              tvEpisode
primaryTitle      Episode #1.890
originalTitle     Episode #1.890
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005319, dtype: object

(9,)

tconst                tt11825382
titleType              tvEpisode
primaryTitle      Episode #1.889
originalTitle     Episode #1.889
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005320, dtype: object

(9,)

tconst                tt11825384
titleType              tvEpisode
primaryTitle      Episode #1.891
originalTitle     Episode #1.891
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005321, dtype: object

(9,)

tconst                tt11825386
titleType              tvEpisode
primaryTitle      Episode #1.894
originalTitle     Episode #1.894
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005322, dtype: object

(9,)

tconst                tt11825388
titleType              tvEpisode
primaryTitle      Episode #1.893
originalTitle     Episode #1.893
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005323, dtype: object

(9,)

tconst                       tt1182538
titleType                    tvEpisode
primaryTitle            Coup de foudre
originalTitle           Coup de foudre
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005324, dtype: object

(9,)

tconst                tt11825390
titleType              tvEpisode
primaryTitle      Episode #1.892
originalTitle     Episode #1.892
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005325, dtype: object

(9,)

tconst                tt11825392
titleType              tvEpisode
primaryTitle      Episode #1.895
originalTitle     Episode #1.895
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005326, dtype: object

(9,)

tconst            tt11825394
titleType              movie
primaryTitle      The Dragon
originalTitle     The Dragon
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2005327, dtype: object

(9,)

tconst                tt11825396
titleType              tvEpisode
primaryTitle      Episode #1.896
originalTitle     Episode #1.896
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005328, dtype: object

(9,)

tconst                tt11825398
titleType              tvEpisode
primaryTitle      Episode #1.897
originalTitle     Episode #1.897
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005329, dtype: object

(9,)

tconst                       tt1182539
titleType                    tvEpisode
primaryTitle             Coup de fouet
originalTitle            Coup de fouet
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005330, dtype: object

(9,)

tconst                tt11825400
titleType              tvEpisode
primaryTitle      Episode #1.898
originalTitle     Episode #1.898
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005331, dtype: object

(9,)

tconst                tt11825402
titleType              tvEpisode
primaryTitle      Episode #1.899
originalTitle     Episode #1.899
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005332, dtype: object

(9,)

tconst                tt11825404
titleType              tvEpisode
primaryTitle      Episode #1.900
originalTitle     Episode #1.900
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2005333, dtype: object

(9,)

tconst                 tt11825406
titleType               tvEpisode
primaryTitle      Episode #1.1122
originalTitle     Episode #1.1122
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005334, dtype: object

(9,)

tconst                 tt11825408
titleType               tvEpisode
primaryTitle      Episode #1.1121
originalTitle     Episode #1.1121
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005335, dtype: object

(9,)

tconst                       tt1182540
titleType                    tvEpisode
primaryTitle         Courage... fuyons
originalTitle        Courage... fuyons
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005336, dtype: object

(9,)

tconst                 tt11825410
titleType               tvEpisode
primaryTitle      Episode #1.1123
originalTitle     Episode #1.1123
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005337, dtype: object

(9,)

tconst                 tt11825412
titleType               tvEpisode
primaryTitle      Episode #1.1124
originalTitle     Episode #1.1124
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005338, dtype: object

(9,)

tconst                 tt11825414
titleType               tvEpisode
primaryTitle      Episode #1.1125
originalTitle     Episode #1.1125
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005339, dtype: object

(9,)

tconst                 tt11825416
titleType               tvEpisode
primaryTitle      Episode #1.1126
originalTitle     Episode #1.1126
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005340, dtype: object

(9,)

tconst                 tt11825418
titleType               tvEpisode
primaryTitle      Episode #1.1127
originalTitle     Episode #1.1127
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005341, dtype: object

(9,)

tconst                       tt1182541
titleType                    tvEpisode
primaryTitle             Fausses notes
originalTitle            Fausses notes
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005342, dtype: object

(9,)

tconst                 tt11825420
titleType               tvEpisode
primaryTitle      Episode #1.1128
originalTitle     Episode #1.1128
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005343, dtype: object

(9,)

tconst                 tt11825422
titleType               tvEpisode
primaryTitle      Episode #1.1129
originalTitle     Episode #1.1129
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005344, dtype: object

(9,)

tconst                 tt11825424
titleType               tvEpisode
primaryTitle      Episode #1.1130
originalTitle     Episode #1.1130
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005345, dtype: object

(9,)

tconst                 tt11825426
titleType               tvEpisode
primaryTitle      Episode #1.1131
originalTitle     Episode #1.1131
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005346, dtype: object

(9,)

tconst                       tt1182542
titleType                    tvEpisode
primaryTitle              Image de soi
originalTitle             Image de soi
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005347, dtype: object

(9,)

tconst                 tt11825432
titleType               tvEpisode
primaryTitle      Episode #1.1134
originalTitle     Episode #1.1134
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005348, dtype: object

(9,)

tconst                 tt11825434
titleType               tvEpisode
primaryTitle      Episode #1.1135
originalTitle     Episode #1.1135
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005349, dtype: object

(9,)

tconst                 tt11825436
titleType               tvEpisode
primaryTitle      Episode #1.1137
originalTitle     Episode #1.1137
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005350, dtype: object

(9,)

tconst                 tt11825438
titleType               tvEpisode
primaryTitle      Episode #1.1136
originalTitle     Episode #1.1136
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005351, dtype: object

(9,)

tconst                       tt1182543
titleType                    tvEpisode
primaryTitle       Joyeux anniversaire
originalTitle      Joyeux anniversaire
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005352, dtype: object

(9,)

tconst                 tt11825440
titleType               tvEpisode
primaryTitle      Episode #1.1138
originalTitle     Episode #1.1138
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005353, dtype: object

(9,)

tconst                 tt11825442
titleType               tvEpisode
primaryTitle      Episode #1.1139
originalTitle     Episode #1.1139
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005354, dtype: object

(9,)

tconst                 tt11825444
titleType               tvEpisode
primaryTitle      Episode #1.1140
originalTitle     Episode #1.1140
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005355, dtype: object

(9,)

tconst                 tt11825446
titleType               tvEpisode
primaryTitle      Episode #1.1321
originalTitle     Episode #1.1321
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005356, dtype: object

(9,)

tconst                 tt11825448
titleType               tvEpisode
primaryTitle      Episode #1.1322
originalTitle     Episode #1.1322
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005357, dtype: object

(9,)

tconst                         tt1182544
titleType                      tvEpisode
primaryTitle      L'humour a ses limites
originalTitle     L'humour a ses limites
isAdult                                0
startYear                           2007
endYear                               \N
runtimeMinutes                        \N
genres              Comedy,Drama,Musical
Name: 2005358, dtype: object

(9,)

tconst                 tt11825450
titleType               tvEpisode
primaryTitle      Episode #1.1323
originalTitle     Episode #1.1323
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005359, dtype: object

(9,)

tconst                 tt11825452
titleType               tvEpisode
primaryTitle      Episode #1.1325
originalTitle     Episode #1.1325
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005360, dtype: object

(9,)

tconst                 tt11825454
titleType               tvEpisode
primaryTitle      Episode #1.1324
originalTitle     Episode #1.1324
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005361, dtype: object

(9,)

tconst                 tt11825456
titleType               tvEpisode
primaryTitle      Episode #1.1326
originalTitle     Episode #1.1326
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005362, dtype: object

(9,)

tconst                 tt11825458
titleType               tvEpisode
primaryTitle      Episode #1.1328
originalTitle     Episode #1.1328
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005363, dtype: object

(9,)

tconst                       tt1182545
titleType                    tvEpisode
primaryTitle                  La cible
originalTitle                 La cible
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005364, dtype: object

(9,)

tconst                 tt11825460
titleType               tvEpisode
primaryTitle      Episode #1.1327
originalTitle     Episode #1.1327
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005365, dtype: object

(9,)

tconst                 tt11825462
titleType               tvEpisode
primaryTitle      Episode #1.1329
originalTitle     Episode #1.1329
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005366, dtype: object

(9,)

tconst                 tt11825464
titleType               tvEpisode
primaryTitle      Episode #1.1330
originalTitle     Episode #1.1330
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005367, dtype: object

(9,)

tconst                 tt11825466
titleType               tvEpisode
primaryTitle      Episode #1.1332
originalTitle     Episode #1.1332
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005368, dtype: object

(9,)

tconst                 tt11825468
titleType               tvEpisode
primaryTitle      Episode #1.1331
originalTitle     Episode #1.1331
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005369, dtype: object

(9,)

tconst                       tt1182546
titleType                    tvEpisode
primaryTitle          La fausse rivale
originalTitle         La fausse rivale
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005370, dtype: object

(9,)

tconst                 tt11825470
titleType               tvEpisode
primaryTitle      Episode #1.1333
originalTitle     Episode #1.1333
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005371, dtype: object

(9,)

tconst                 tt11825472
titleType               tvEpisode
primaryTitle      Episode #1.1334
originalTitle     Episode #1.1334
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005372, dtype: object

(9,)

tconst                 tt11825474
titleType               tvEpisode
primaryTitle      Episode #1.1335
originalTitle     Episode #1.1335
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005373, dtype: object

(9,)

tconst                 tt11825476
titleType               tvEpisode
primaryTitle      Episode #1.1338
originalTitle     Episode #1.1338
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005374, dtype: object

(9,)

tconst                 tt11825478
titleType               tvEpisode
primaryTitle      Episode #1.1337
originalTitle     Episode #1.1337
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005375, dtype: object

(9,)

tconst                       tt1182547
titleType                    tvEpisode
primaryTitle                Le concert
originalTitle               Le concert
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005376, dtype: object

(9,)

tconst                 tt11825480
titleType               tvEpisode
primaryTitle      Episode #1.1336
originalTitle     Episode #1.1336
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005377, dtype: object

(9,)

tconst                 tt11825482
titleType               tvEpisode
primaryTitle      Episode #1.1339
originalTitle     Episode #1.1339
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005378, dtype: object

(9,)

tconst                 tt11825484
titleType               tvEpisode
primaryTitle      Episode #1.1340
originalTitle     Episode #1.1340
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005379, dtype: object

(9,)

tconst                 tt11825486
titleType               tvEpisode
primaryTitle      Episode #1.1621
originalTitle     Episode #1.1621
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005380, dtype: object

(9,)

tconst                 tt11825488
titleType               tvEpisode
primaryTitle      Episode #1.1622
originalTitle     Episode #1.1622
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005381, dtype: object

(9,)

tconst                        tt1182548
titleType                     tvEpisode
primaryTitle      Le goût de la liberté
originalTitle     Le goût de la liberté
isAdult                               0
startYear                          2007
endYear                              \N
runtimeMinutes                       \N
genres             Comedy,Drama,Musical
Name: 2005382, dtype: object

(9,)

tconst                 tt11825490
titleType               tvEpisode
primaryTitle      Episode #1.1623
originalTitle     Episode #1.1623
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005383, dtype: object

(9,)

tconst                 tt11825494
titleType               tvEpisode
primaryTitle      Episode #1.1624
originalTitle     Episode #1.1624
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005384, dtype: object

(9,)

tconst                 tt11825496
titleType               tvEpisode
primaryTitle      Episode #1.1625
originalTitle     Episode #1.1625
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005385, dtype: object

(9,)

tconst                 tt11825498
titleType               tvEpisode
primaryTitle      Episode #1.1626
originalTitle     Episode #1.1626
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005386, dtype: object

(9,)

tconst                              tt1182549
titleType                           tvEpisode
primaryTitle      Petits mensonges entre amis
originalTitle     Petits mensonges entre amis
isAdult                                     0
startYear                                2007
endYear                                    \N
runtimeMinutes                             \N
genres                   Comedy,Drama,Musical
Name: 2005387, dtype: object

(9,)

tconst                 tt11825500
titleType               tvEpisode
primaryTitle      Episode #1.1627
originalTitle     Episode #1.1627
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005388, dtype: object

(9,)

tconst                 tt11825502
titleType               tvEpisode
primaryTitle      Episode #1.1628
originalTitle     Episode #1.1628
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005389, dtype: object

(9,)

tconst                 tt11825504
titleType               tvEpisode
primaryTitle      Episode #1.1629
originalTitle     Episode #1.1629
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005390, dtype: object

(9,)

tconst                    tt11825506
titleType                  tvEpisode
primaryTitle             Épisode 389
originalTitle            Épisode 389
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    22
genres            Comedy,Crime,Drama
Name: 2005391, dtype: object

(9,)

tconst                 tt11825508
titleType               tvEpisode
primaryTitle      Episode #1.1630
originalTitle     Episode #1.1630
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005392, dtype: object

(9,)

tconst                       tt1182550
titleType                    tvEpisode
primaryTitle            Petits secrets
originalTitle           Petits secrets
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005393, dtype: object

(9,)

tconst                 tt11825510
titleType               tvEpisode
primaryTitle      Episode #1.1631
originalTitle     Episode #1.1631
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005394, dtype: object

(9,)

tconst                 tt11825512
titleType               tvEpisode
primaryTitle      Episode #1.1632
originalTitle     Episode #1.1632
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005395, dtype: object

(9,)

tconst                 tt11825514
titleType               tvEpisode
primaryTitle      Episode #1.1633
originalTitle     Episode #1.1633
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005396, dtype: object

(9,)

tconst                 tt11825516
titleType               tvEpisode
primaryTitle      Episode #1.1634
originalTitle     Episode #1.1634
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005397, dtype: object

(9,)

tconst                 tt11825518
titleType               tvEpisode
primaryTitle      Episode #1.1635
originalTitle     Episode #1.1635
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005398, dtype: object

(9,)

tconst                       tt1182551
titleType                    tvEpisode
primaryTitle                   Soupçon
originalTitle                  Soupçon
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005399, dtype: object

(9,)

tconst                 tt11825520
titleType               tvEpisode
primaryTitle      Episode #1.1636
originalTitle     Episode #1.1636
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005400, dtype: object

(9,)

tconst                 tt11825522
titleType               tvEpisode
primaryTitle      Episode #1.1637
originalTitle     Episode #1.1637
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005401, dtype: object

(9,)

tconst                 tt11825524
titleType               tvEpisode
primaryTitle      Episode #1.1639
originalTitle     Episode #1.1639
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005402, dtype: object

(9,)

tconst                 tt11825526
titleType               tvEpisode
primaryTitle      Episode #1.1638
originalTitle     Episode #1.1638
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005403, dtype: object

(9,)

tconst                  tt11825528
titleType                    short
primaryTitle      Dire 03: Retiens
originalTitle     Dire 03: Retiens
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                       Short
Name: 2005404, dtype: object

(9,)

tconst                        tt1182552
titleType                     tvEpisode
primaryTitle      Sous une bonne étoile
originalTitle     Sous une bonne étoile
isAdult                               0
startYear                          2007
endYear                              \N
runtimeMinutes                       \N
genres             Comedy,Drama,Musical
Name: 2005405, dtype: object

(9,)

tconst                 tt11825530
titleType               tvEpisode
primaryTitle      Episode #1.1640
originalTitle     Episode #1.1640
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005406, dtype: object

(9,)

tconst               tt11825532
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005407, dtype: object

(9,)

tconst                               tt11825534
titleType                                 video
primaryTitle      Caught in the Act 3: Real Sex
originalTitle     Caught in the Act 3: Real Sex
isAdult                                       1
startYear                                  2015
endYear                                      \N
runtimeMinutes                              136
genres                                    Adult
Name: 2005408, dtype: object

(9,)

tconst                                tt11825536
titleType                              tvEpisode
primaryTitle      Cuidaos de los falsos profetas
originalTitle     Cuidaos de los falsos profetas
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                               Documentary
Name: 2005409, dtype: object

(9,)

tconst                     tt11825538
titleType                       short
primaryTitle        Suburban Shanghai
originalTitle       Suburban Shanghai
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     14
genres            Action,Comedy,Short
Name: 2005410, dtype: object

(9,)

tconst                       tt1182553
titleType                    tvEpisode
primaryTitle        Tous pour la frime
originalTitle       Tous pour la frime
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005411, dtype: object

(9,)

tconst               tt11825540
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005412, dtype: object

(9,)

tconst               tt11825542
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005413, dtype: object

(9,)

tconst               tt11825544
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005414, dtype: object

(9,)

tconst               tt11825546
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005415, dtype: object

(9,)

tconst               tt11825548
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005416, dtype: object

(9,)

tconst                       tt1182554
titleType                    tvEpisode
primaryTitle      Tous pour la musique
originalTitle     Tous pour la musique
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005417, dtype: object

(9,)

tconst               tt11825550
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005418, dtype: object

(9,)

tconst               tt11825552
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005419, dtype: object

(9,)

tconst               tt11825554
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005420, dtype: object

(9,)

tconst               tt11825556
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005421, dtype: object

(9,)

tconst               tt11825558
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005422, dtype: object

(9,)

tconst                       tt1182555
titleType                    tvEpisode
primaryTitle             Tous pour une
originalTitle            Tous pour une
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005423, dtype: object

(9,)

tconst               tt11825560
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005424, dtype: object

(9,)

tconst               tt11825562
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005425, dtype: object

(9,)

tconst                                 tt11825564
titleType                                   video
primaryTitle      Stevie Nicks: Edge of Seventeen
originalTitle     Stevie Nicks: Edge of Seventeen
isAdult                                         0
startYear                                    1982
endYear                                        \N
runtimeMinutes                                  9
genres                                Music,Short
Name: 2005426, dtype: object

(9,)

tconst                           tt11825566
titleType                         tvEpisode
primaryTitle      Lobos con piel de cordero
originalTitle     Lobos con piel de cordero
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                          Documentary
Name: 2005427, dtype: object

(9,)

tconst               tt11825568
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005428, dtype: object

(9,)

tconst                       tt1182556
titleType                    tvEpisode
primaryTitle              Tout ou rien
originalTitle             Tout ou rien
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005429, dtype: object

(9,)

tconst               tt11825570
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005430, dtype: object

(9,)

tconst               tt11825572
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005431, dtype: object

(9,)

tconst               tt11825574
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005432, dtype: object

(9,)

tconst               tt11825576
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005433, dtype: object

(9,)

tconst               tt11825578
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005434, dtype: object

(9,)

tconst                       tt1182557
titleType                    tvEpisode
primaryTitle            Tout sauf amis
originalTitle           Tout sauf amis
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005435, dtype: object

(9,)

tconst                tt11825580
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005436, dtype: object

(9,)

tconst               tt11825582
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005437, dtype: object

(9,)

tconst                    tt11825584
titleType                      short
primaryTitle         The Book of Job
originalTitle        The Book of Job
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres            Action,Drama,Short
Name: 2005438, dtype: object

(9,)

tconst                          tt11825586
titleType                            short
primaryTitle      Vous L'avez Bien Cherché
originalTitle     Vous L'avez Bien Cherché
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                               Short
Name: 2005439, dtype: object

(9,)

tconst                         tt11825588
titleType                       tvEpisode
primaryTitle      Take 5 With Jay Pharoah
originalTitle     Take 5 With Jay Pharoah
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2005440, dtype: object

(9,)

tconst                       tt1182558
titleType                    tvEpisode
primaryTitle              Tout sauf ça
originalTitle             Tout sauf ça
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005441, dtype: object

(9,)

tconst                        tt11825590
titleType                      tvEpisode
primaryTitle             Episode #13.135
originalTitle            Episode #13.135
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Comedy,Drama,Game-Show
Name: 2005442, dtype: object

(9,)

tconst                                   tt11825594
titleType                                 tvEpisode
primaryTitle      Nail Technician - Clueless Expert
originalTitle     Nail Technician - Clueless Expert
isAdult                                           0
startYear                                      2019
endYear                                          \N
runtimeMinutes                                   \N
genres                          Comedy,Drama,Sci-Fi
Name: 2005443, dtype: object

(9,)

tconst                                  tt11825596
titleType                                    video
primaryTitle      Parapan Am Games: Are You Ready?
originalTitle     Parapan Am Games: Are You Ready?
isAdult                                          0
startYear                                     2015
endYear                                         \N
runtimeMinutes                                  \N
genres                                 Short,Sport
Name: 2005444, dtype: object

(9,)

tconst             tt11825598
titleType           tvEpisode
primaryTitle        David Dye
originalTitle       David Dye
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2005445, dtype: object

(9,)

tconst                       tt1182559
titleType                    tvEpisode
primaryTitle      Trio versus quinquet
originalTitle     Trio versus quinquet
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005446, dtype: object

(9,)

tconst               tt11825600
titleType                 movie
primaryTitle      Sale histoire
originalTitle     Sale histoire
isAdult                       0
startYear                  1997
endYear                      \N
runtimeMinutes               62
genres                    Drama
Name: 2005447, dtype: object

(9,)

tconst                               tt11825602
titleType                                 video
primaryTitle      Stevie Nicks: If Anyone Falls
originalTitle     Stevie Nicks: If Anyone Falls
isAdult                                       0
startYear                                  1983
endYear                                      \N
runtimeMinutes                                4
genres                              Music,Short
Name: 2005448, dtype: object

(9,)

tconst               tt11825606
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005449, dtype: object

(9,)

tconst               tt11825608
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005450, dtype: object

(9,)

tconst                       tt1182560
titleType                    tvEpisode
primaryTitle                 Trop loin
originalTitle                Trop loin
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Musical
Name: 2005451, dtype: object

(9,)

tconst               tt11825610
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005452, dtype: object

(9,)

tconst               tt11825612
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005453, dtype: object

(9,)

tconst               tt11825614
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005454, dtype: object

(9,)

tconst               tt11825616
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005455, dtype: object

(9,)

tconst               tt11825618
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005456, dtype: object

(9,)

tconst                 tt1182561
titleType              tvEpisode
primaryTitle      Episode #1.765
originalTitle     Episode #1.765
isAdult                        0
startYear                   1987
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2005457, dtype: object

(9,)

tconst               tt11825620
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005458, dtype: object

(9,)

tconst               tt11825622
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005459, dtype: object

(9,)

tconst               tt11825624
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005460, dtype: object

(9,)

tconst                                          tt11825626
titleType                                            video
primaryTitle      22-Pistepirkko: (Just a) Little Bit More
originalTitle     22-Pistepirkko: (Just a) Little Bit More
isAdult                                                  0
startYear                                             1994
endYear                                                 \N
runtimeMinutes                                           5
genres                                         Music,Short
Name: 2005461, dtype: object

(9,)

tconst               tt11825628
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005462, dtype: object

(9,)

tconst                tt1182562
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2005463, dtype: object

(9,)

tconst               tt11825630
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005464, dtype: object

(9,)

tconst               tt11825632
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005465, dtype: object

(9,)

tconst               tt11825634
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005466, dtype: object

(9,)

tconst               tt11825636
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005467, dtype: object

(9,)

tconst               tt11825638
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005468, dtype: object

(9,)

tconst                               tt1182563
titleType                            tvEpisode
primaryTitle      Episode dated 5 October 2007
originalTitle     Episode dated 5 October 2007
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                    Comedy,Drama,Romance
Name: 2005469, dtype: object

(9,)

tconst               tt11825640
titleType                 video
primaryTitle          Mr Clever
originalTitle         Mr Clever
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes                3
genres            Musical,Short
Name: 2005470, dtype: object

(9,)

tconst               tt11825642
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005471, dtype: object

(9,)

tconst               tt11825644
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005472, dtype: object

(9,)

tconst                tt11825646
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005473, dtype: object

(9,)

tconst                   tt11825648
titleType                   tvMovie
primaryTitle          Fatboy Racing
originalTitle         Fatboy Racing
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   28
genres            Documentary,Sport
Name: 2005474, dtype: object

(9,)

tconst                               tt1182564
titleType                            tvEpisode
primaryTitle      Episode dated 6 October 2007
originalTitle     Episode dated 6 October 2007
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                    Comedy,Drama,Romance
Name: 2005475, dtype: object

(9,)

tconst                  tt11825650
titleType                tvEpisode
primaryTitle        Episode #1.902
originalTitle       Episode #1.902
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005476, dtype: object

(9,)

tconst               tt11825652
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005477, dtype: object

(9,)

tconst               tt11825654
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005478, dtype: object

(9,)

tconst                            tt11825656
titleType                          tvEpisode
primaryTitle                    Episode #1.1
originalTitle                   Episode #1.1
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            34
genres            Adventure,Animation,Comedy
Name: 2005479, dtype: object

(9,)

tconst               tt11825658
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005480, dtype: object

(9,)

tconst                                 tt1182565
titleType                              tvEpisode
primaryTitle      Episode dated 15 November 2007
originalTitle     Episode dated 15 November 2007
isAdult                                        0
startYear                                   2007
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2005481, dtype: object

(9,)

tconst               tt11825660
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005482, dtype: object

(9,)

tconst               tt11825662
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005483, dtype: object

(9,)

tconst               tt11825664
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005484, dtype: object

(9,)

tconst            tt11825666
titleType              short
primaryTitle       Rude Boys
originalTitle      Rude Boys
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes             9
genres                 Short
Name: 2005485, dtype: object

(9,)

tconst               tt11825668
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005486, dtype: object

(9,)

tconst                tt1182566
titleType             tvEpisode
primaryTitle      Episode #7.17
originalTitle     Episode #7.17
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005487, dtype: object

(9,)

tconst               tt11825672
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005488, dtype: object

(9,)

tconst               tt11825674
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005489, dtype: object

(9,)

tconst               tt11825676
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005490, dtype: object

(9,)

tconst               tt11825678
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005491, dtype: object

(9,)

tconst                                tt1182567
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Game-Show
Name: 2005492, dtype: object

(9,)

tconst               tt11825680
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005493, dtype: object

(9,)

tconst               tt11825682
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005494, dtype: object

(9,)

tconst               tt11825684
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005495, dtype: object

(9,)

tconst               tt11825686
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005496, dtype: object

(9,)

tconst               tt11825688
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005497, dtype: object

(9,)

tconst                                 tt1182568
titleType                              tvEpisode
primaryTitle      Episode dated 25 November 2006
originalTitle     Episode dated 25 November 2006
isAdult                                        0
startYear                                   2006
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2005498, dtype: object

(9,)

tconst               tt11825690
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005499, dtype: object

(9,)

tconst               tt11825692
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005500, dtype: object

(9,)

tconst               tt11825694
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005501, dtype: object

(9,)

tconst                tt11825696
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005502, dtype: object

(9,)

tconst                tt11825698
titleType              tvEpisode
primaryTitle      Episode #1.281
originalTitle     Episode #1.281
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005503, dtype: object

(9,)

tconst                                 tt1182569
titleType                              tvEpisode
primaryTitle      Episode dated 29 November 2006
originalTitle     Episode dated 29 November 2006
isAdult                                        0
startYear                                   2006
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2005504, dtype: object

(9,)

tconst                tt11825700
titleType              tvEpisode
primaryTitle      Episode #1.282
originalTitle     Episode #1.282
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005505, dtype: object

(9,)

tconst                                                   tt11825702
titleType                                                 tvEpisode
primaryTitle      Round of 32, 1st leg 2019/2020: Sporting CP vs...
originalTitle     Round of 32, 1st leg 2019/2020: Sporting CP vs...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Sport
Name: 2005506, dtype: object

(9,)

tconst                tt11825706
titleType              tvEpisode
primaryTitle      Episode #1.283
originalTitle     Episode #1.283
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005507, dtype: object

(9,)

tconst                tt11825708
titleType              tvEpisode
primaryTitle      Episode #1.284
originalTitle     Episode #1.284
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005508, dtype: object

(9,)

tconst                                tt1182570
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                   Comedy,Music,Talk-Show
Name: 2005509, dtype: object

(9,)

tconst            tt11825710
titleType              movie
primaryTitle           Black
originalTitle          Black
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Sci-Fi
Name: 2005510, dtype: object

(9,)

tconst                tt11825712
titleType              tvEpisode
primaryTitle      Episode #1.285
originalTitle     Episode #1.285
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005511, dtype: object

(9,)

tconst                tt11825714
titleType              tvEpisode
primaryTitle      Episode #1.286
originalTitle     Episode #1.286
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005512, dtype: object

(9,)

tconst              tt11825716
titleType         tvMiniSeries
primaryTitle       Lengalongas
originalTitle      Lengalongas
isAdult                      0
startYear                 2019
endYear                   2019
runtimeMinutes              \N
genres               Animation
Name: 2005513, dtype: object

(9,)

tconst                tt11825718
titleType              tvEpisode
primaryTitle      Episode #1.288
originalTitle     Episode #1.288
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005514, dtype: object

(9,)

tconst                                tt1182571
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                   Comedy,Music,Talk-Show
Name: 2005515, dtype: object

(9,)

tconst                tt11825720
titleType              tvEpisode
primaryTitle      Episode #1.287
originalTitle     Episode #1.287
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005516, dtype: object

(9,)

tconst                tt11825722
titleType              tvEpisode
primaryTitle      Episode #1.289
originalTitle     Episode #1.289
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005517, dtype: object

(9,)

tconst                tt11825724
titleType              tvEpisode
primaryTitle      Episode #1.291
originalTitle     Episode #1.291
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005518, dtype: object

(9,)

tconst                tt11825726
titleType              tvEpisode
primaryTitle      Episode #1.292
originalTitle     Episode #1.292
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005519, dtype: object

(9,)

tconst                tt11825728
titleType              tvEpisode
primaryTitle      Episode #1.290
originalTitle     Episode #1.290
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005520, dtype: object

(9,)

tconst                                tt1182572
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                   Comedy,Music,Talk-Show
Name: 2005521, dtype: object

(9,)

tconst                tt11825730
titleType              tvEpisode
primaryTitle      Episode #1.294
originalTitle     Episode #1.294
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005522, dtype: object

(9,)

tconst                tt11825732
titleType              tvEpisode
primaryTitle      Episode #1.293
originalTitle     Episode #1.293
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005523, dtype: object

(9,)

tconst                tt11825734
titleType              tvEpisode
primaryTitle      Episode #1.297
originalTitle     Episode #1.297
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005524, dtype: object

(9,)

tconst                tt11825736
titleType              tvEpisode
primaryTitle      Episode #1.296
originalTitle     Episode #1.296
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005525, dtype: object

(9,)

tconst                tt11825738
titleType              tvEpisode
primaryTitle      Episode #1.295
originalTitle     Episode #1.295
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005526, dtype: object

(9,)

tconst                                tt1182573
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2005527, dtype: object

(9,)

tconst                tt11825740
titleType              tvEpisode
primaryTitle      Episode #1.299
originalTitle     Episode #1.299
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005528, dtype: object

(9,)

tconst                tt11825742
titleType              tvEpisode
primaryTitle      Episode #1.298
originalTitle     Episode #1.298
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005529, dtype: object

(9,)

tconst                tt11825744
titleType              tvEpisode
primaryTitle      Episode #1.300
originalTitle     Episode #1.300
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2005530, dtype: object

(9,)

tconst                                            tt11825746
titleType                                          tvEpisode
primaryTitle      I Recalled the Memories of My Past Life...
originalTitle     I Recalled the Memories of My Past Life...
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                Animation,Comedy,Drama
Name: 2005531, dtype: object

(9,)

tconst               tt11825748
titleType             tvEpisode
primaryTitle      Episode #2.41
originalTitle     Episode #2.41
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005532, dtype: object

(9,)

tconst               tt11825750
titleType             tvEpisode
primaryTitle      Episode #2.42
originalTitle     Episode #2.42
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005533, dtype: object

(9,)

tconst               tt11825752
titleType             tvEpisode
primaryTitle      Episode #2.43
originalTitle     Episode #2.43
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005534, dtype: object

(9,)

tconst               tt11825754
titleType             tvEpisode
primaryTitle      Episode #2.44
originalTitle     Episode #2.44
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005535, dtype: object

(9,)

tconst               tt11825756
titleType             tvEpisode
primaryTitle      Episode #2.46
originalTitle     Episode #2.46
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005536, dtype: object

(9,)

tconst               tt11825758
titleType             tvEpisode
primaryTitle      Episode #2.45
originalTitle     Episode #2.45
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005537, dtype: object

(9,)

tconst                                tt1182575
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2005538, dtype: object

(9,)

tconst               tt11825760
titleType             tvEpisode
primaryTitle      Episode #2.47
originalTitle     Episode #2.47
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005539, dtype: object

(9,)

tconst               tt11825762
titleType             tvEpisode
primaryTitle      Episode #2.48
originalTitle     Episode #2.48
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005540, dtype: object

(9,)

tconst               tt11825764
titleType             tvEpisode
primaryTitle      Episode #2.49
originalTitle     Episode #2.49
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005541, dtype: object

(9,)

tconst               tt11825766
titleType             tvEpisode
primaryTitle      Episode #2.50
originalTitle     Episode #2.50
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005542, dtype: object

(9,)

tconst               tt11825768
titleType             tvEpisode
primaryTitle      Episode #2.51
originalTitle     Episode #2.51
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005543, dtype: object

(9,)

tconst                tt1182576
titleType             tvEpisode
primaryTitle      Episode #3.15
originalTitle     Episode #3.15
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               58
genres            Drama,Romance
Name: 2005544, dtype: object

(9,)

tconst                                             tt11825770
titleType                                               video
primaryTitle      Stevie Nicks: Stand Back (Scarlett Version)
originalTitle     Stevie Nicks: Stand Back (Scarlett Version)
isAdult                                                     0
startYear                                                1983
endYear                                                    \N
runtimeMinutes                                              4
genres                                            Music,Short
Name: 2005545, dtype: object

(9,)

tconst              tt11825772
titleType            tvEpisode
primaryTitle      Episode #3.2
originalTitle     Episode #3.2
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres               Animation
Name: 2005546, dtype: object

(9,)

tconst              tt11825774
titleType            tvEpisode
primaryTitle      Episode #3.3
originalTitle     Episode #3.3
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres               Animation
Name: 2005547, dtype: object

(9,)

tconst              tt11825776
titleType            tvEpisode
primaryTitle      Episode #3.4
originalTitle     Episode #3.4
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres               Animation
Name: 2005548, dtype: object

(9,)

tconst              tt11825778
titleType            tvEpisode
primaryTitle      Episode #3.5
originalTitle     Episode #3.5
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres               Animation
Name: 2005549, dtype: object

(9,)

tconst                 tt1182577
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2005550, dtype: object

(9,)

tconst              tt11825780
titleType            tvEpisode
primaryTitle      Episode #3.6
originalTitle     Episode #3.6
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres               Animation
Name: 2005551, dtype: object

(9,)

tconst              tt11825782
titleType            tvEpisode
primaryTitle      Episode #3.8
originalTitle     Episode #3.8
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres               Animation
Name: 2005552, dtype: object

(9,)

tconst              tt11825784
titleType            tvEpisode
primaryTitle      Episode #3.7
originalTitle     Episode #3.7
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres               Animation
Name: 2005553, dtype: object

(9,)

tconst               tt11825786
titleType             tvEpisode
primaryTitle      Episode #3.10
originalTitle     Episode #3.10
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005554, dtype: object

(9,)

tconst              tt11825788
titleType            tvEpisode
primaryTitle      Episode #3.9
originalTitle     Episode #3.9
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres               Animation
Name: 2005555, dtype: object

(9,)

tconst                 tt1182578
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2005556, dtype: object

(9,)

tconst               tt11825790
titleType             tvEpisode
primaryTitle      Episode #3.11
originalTitle     Episode #3.11
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005557, dtype: object

(9,)

tconst               tt11825792
titleType             tvEpisode
primaryTitle      Episode #3.12
originalTitle     Episode #3.12
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005558, dtype: object

(9,)

tconst               tt11825794
titleType             tvEpisode
primaryTitle      Episode #3.13
originalTitle     Episode #3.13
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005559, dtype: object

(9,)

tconst               tt11825796
titleType             tvEpisode
primaryTitle      Episode #3.14
originalTitle     Episode #3.14
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005560, dtype: object

(9,)

tconst                   tt11825798
titleType                 tvEpisode
primaryTitle      The Biggest Loser
originalTitle     The Biggest Loser
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2005561, dtype: object

(9,)

tconst                 tt1182579
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2005562, dtype: object

(9,)

tconst               tt11825800
titleType             tvEpisode
primaryTitle      Episode #3.15
originalTitle     Episode #3.15
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005563, dtype: object

(9,)

tconst               tt11825802
titleType             tvEpisode
primaryTitle      Episode #3.16
originalTitle     Episode #3.16
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005564, dtype: object

(9,)

tconst                          tt11825804
titleType                            video
primaryTitle      Stevie Nicks: Talk to Me
originalTitle     Stevie Nicks: Talk to Me
isAdult                                  0
startYear                             1985
endYear                                 \N
runtimeMinutes                           4
genres                         Music,Short
Name: 2005565, dtype: object

(9,)

tconst               tt11825806
titleType             tvEpisode
primaryTitle      Episode #3.17
originalTitle     Episode #3.17
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005566, dtype: object

(9,)

tconst               tt11825808
titleType             tvEpisode
primaryTitle      Episode #3.18
originalTitle     Episode #3.18
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005567, dtype: object

(9,)

tconst                tt1182580
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005568, dtype: object

(9,)

tconst               tt11825810
titleType             tvEpisode
primaryTitle      Episode #3.19
originalTitle     Episode #3.19
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005569, dtype: object

(9,)

tconst               tt11825812
titleType             tvEpisode
primaryTitle      Episode #3.20
originalTitle     Episode #3.20
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2005570, dtype: object

(9,)

tconst                                 tt11825814
titleType                                   short
primaryTitle      World War Three: The Good Fight
originalTitle     World War Three: The Good Fight
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 15
genres                               Comedy,Short
Name: 2005571, dtype: object

(9,)

tconst               tt11825816
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005572, dtype: object

(9,)

tconst               tt11825818
titleType             tvEpisode
primaryTitle      Episode #1.42
originalTitle     Episode #1.42
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005573, dtype: object

(9,)

tconst                tt1182581
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005574, dtype: object

(9,)

tconst               tt11825820
titleType             tvEpisode
primaryTitle      Episode #1.43
originalTitle     Episode #1.43
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005575, dtype: object

(9,)

tconst               tt11825822
titleType             tvEpisode
primaryTitle      Episode #1.44
originalTitle     Episode #1.44
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005576, dtype: object

(9,)

tconst                                      tt11825824
titleType                                        video
primaryTitle      Stevie Nicks: Sometimes It's A Bitch
originalTitle     Stevie Nicks: Sometimes It's A Bitch
isAdult                                              0
startYear                                         1991
endYear                                             \N
runtimeMinutes                                       5
genres                                     Music,Short
Name: 2005577, dtype: object

(9,)

tconst               tt11825826
titleType             tvEpisode
primaryTitle      Episode #1.45
originalTitle     Episode #1.45
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005578, dtype: object

(9,)

tconst                tt1182582
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005579, dtype: object

(9,)

tconst               tt11825830
titleType             tvEpisode
primaryTitle      Episode #1.47
originalTitle     Episode #1.47
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005580, dtype: object

(9,)

tconst               tt11825832
titleType             tvEpisode
primaryTitle      Episode #1.46
originalTitle     Episode #1.46
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005581, dtype: object

(9,)

tconst               tt11825834
titleType             tvEpisode
primaryTitle      Episode #1.48
originalTitle     Episode #1.48
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005582, dtype: object

(9,)

tconst               tt11825836
titleType             tvEpisode
primaryTitle      Episode #1.49
originalTitle     Episode #1.49
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005583, dtype: object

(9,)

tconst               tt11825838
titleType             tvEpisode
primaryTitle      Episode #1.50
originalTitle     Episode #1.50
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005584, dtype: object

(9,)

tconst                tt1182583
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005585, dtype: object

(9,)

tconst               tt11825840
titleType             tvEpisode
primaryTitle      Episode #1.51
originalTitle     Episode #1.51
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005586, dtype: object

(9,)

tconst                     tt11825842
titleType                   tvEpisode
primaryTitle      Deutsche Neue Welle
originalTitle     Deutsche Neue Welle
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2005587, dtype: object

(9,)

tconst               tt11825844
titleType             tvEpisode
primaryTitle      Episode #1.52
originalTitle     Episode #1.52
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005588, dtype: object

(9,)

tconst               tt11825846
titleType             tvEpisode
primaryTitle      Episode #1.54
originalTitle     Episode #1.54
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005589, dtype: object

(9,)

tconst                tt11825848
titleType                  short
primaryTitle      Pale Blue Eyes
originalTitle     Pale Blue Eyes
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres               Drama,Short
Name: 2005590, dtype: object

(9,)

tconst                tt1182584
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005591, dtype: object

(9,)

tconst               tt11825850
titleType             tvEpisode
primaryTitle      Episode #1.53
originalTitle     Episode #1.53
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005592, dtype: object

(9,)

tconst               tt11825852
titleType             tvEpisode
primaryTitle      Episode #1.55
originalTitle     Episode #1.55
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005593, dtype: object

(9,)

tconst               tt11825854
titleType             tvEpisode
primaryTitle      Episode #1.56
originalTitle     Episode #1.56
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005594, dtype: object

(9,)

tconst               tt11825856
titleType             tvEpisode
primaryTitle      Episode #1.57
originalTitle     Episode #1.57
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005595, dtype: object

(9,)

tconst                              tt11825858
titleType                            tvEpisode
primaryTitle      Folge 41: Christian Solmecke
originalTitle     Folge 41: Christian Solmecke
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2005596, dtype: object

(9,)

tconst                tt1182585
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005597, dtype: object

(9,)

tconst               tt11825860
titleType             tvEpisode
primaryTitle      Episode #1.59
originalTitle     Episode #1.59
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005598, dtype: object

(9,)

tconst               tt11825862
titleType             tvEpisode
primaryTitle      Episode #1.58
originalTitle     Episode #1.58
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005599, dtype: object

(9,)

tconst                             tt11825864
titleType                           tvEpisode
primaryTitle      Couchsurfing in Kisbekistan
originalTitle     Couchsurfing in Kisbekistan
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres                                 Comedy
Name: 2005600, dtype: object

(9,)

tconst               tt11825866
titleType             tvEpisode
primaryTitle      Episode #2.41
originalTitle     Episode #2.41
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005601, dtype: object

(9,)

tconst               tt11825868
titleType             tvEpisode
primaryTitle      Episode #1.60
originalTitle     Episode #1.60
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005602, dtype: object

(9,)

tconst                tt1182586
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005603, dtype: object

(9,)

tconst               tt11825870
titleType             tvEpisode
primaryTitle      Episode #2.42
originalTitle     Episode #2.42
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005604, dtype: object

(9,)

tconst               tt11825872
titleType             tvEpisode
primaryTitle      Episode #2.43
originalTitle     Episode #2.43
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005605, dtype: object

(9,)

tconst               tt11825874
titleType             tvEpisode
primaryTitle      Episode #2.44
originalTitle     Episode #2.44
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005606, dtype: object

(9,)

tconst               tt11825876
titleType             tvEpisode
primaryTitle      Episode #2.45
originalTitle     Episode #2.45
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005607, dtype: object

(9,)

tconst                                 tt11825878
titleType                               tvEpisode
primaryTitle      Der Exorzismus der Anneliese E.
originalTitle     Der Exorzismus der Anneliese E.
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Comedy
Name: 2005608, dtype: object

(9,)

tconst                tt1182587
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005609, dtype: object

(9,)

tconst               tt11825880
titleType             tvEpisode
primaryTitle      Episode #2.46
originalTitle     Episode #2.46
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005610, dtype: object

(9,)

tconst               tt11825882
titleType             tvEpisode
primaryTitle      Episode #2.48
originalTitle     Episode #2.48
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005611, dtype: object

(9,)

tconst               tt11825884
titleType             tvEpisode
primaryTitle      Episode #2.47
originalTitle     Episode #2.47
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005612, dtype: object

(9,)

tconst               tt11825886
titleType             tvEpisode
primaryTitle      Episode #2.49
originalTitle     Episode #2.49
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005613, dtype: object

(9,)

tconst               tt11825888
titleType             tvEpisode
primaryTitle      Episode #2.50
originalTitle     Episode #2.50
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005614, dtype: object

(9,)

tconst                tt1182588
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005615, dtype: object

(9,)

tconst               tt11825890
titleType             tvEpisode
primaryTitle      Episode #2.51
originalTitle     Episode #2.51
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005616, dtype: object

(9,)

tconst               tt11825892
titleType             tvEpisode
primaryTitle      Episode #2.52
originalTitle     Episode #2.52
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005617, dtype: object

(9,)

tconst               tt11825894
titleType             tvEpisode
primaryTitle      Episode #2.53
originalTitle     Episode #2.53
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005618, dtype: object

(9,)

tconst               tt11825896
titleType             tvEpisode
primaryTitle      Episode #2.54
originalTitle     Episode #2.54
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005619, dtype: object

(9,)

tconst               tt11825898
titleType             tvEpisode
primaryTitle      Episode #2.55
originalTitle     Episode #2.55
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005620, dtype: object

(9,)

tconst                tt1182589
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005621, dtype: object

(9,)

tconst                  tt11825900
titleType                tvEpisode
primaryTitle      Ritt der Walküre
originalTitle     Ritt der Walküre
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2005622, dtype: object

(9,)

tconst               tt11825902
titleType             tvEpisode
primaryTitle      Episode #2.56
originalTitle     Episode #2.56
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005623, dtype: object

(9,)

tconst               tt11825904
titleType             tvEpisode
primaryTitle      Episode #2.57
originalTitle     Episode #2.57
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005624, dtype: object

(9,)

tconst               tt11825908
titleType             tvEpisode
primaryTitle      Episode #2.58
originalTitle     Episode #2.58
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005625, dtype: object

(9,)

tconst                tt1182590
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005626, dtype: object

(9,)

tconst                  tt11825910
titleType                tvEpisode
primaryTitle      Der letzte Wille
originalTitle     Der letzte Wille
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2005627, dtype: object

(9,)

tconst               tt11825912
titleType             tvEpisode
primaryTitle      Episode #2.59
originalTitle     Episode #2.59
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005628, dtype: object

(9,)

tconst               tt11825914
titleType             tvEpisode
primaryTitle      Episode #2.60
originalTitle     Episode #2.60
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2005629, dtype: object

(9,)

tconst                         tt11825916
titleType                       tvEpisode
primaryTitle      Der fliehende Holländer
originalTitle     Der fliehende Holländer
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                             Comedy
Name: 2005630, dtype: object

(9,)

tconst                                              tt11825918
titleType                                                movie
primaryTitle      Who has the Most Grudge Cast the First Stone
originalTitle     Who has the Most Grudge Cast the First Stone
isAdult                                                      0
startYear                                                   \N
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                  Family
Name: 2005631, dtype: object

(9,)

tconst                tt1182591
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005632, dtype: object

(9,)

tconst                          tt11825920
titleType                            video
primaryTitle      Stevie Nicks: Blue Denim
originalTitle     Stevie Nicks: Blue Denim
isAdult                                  0
startYear                             1994
endYear                                 \N
runtimeMinutes                           4
genres                         Music,Short
Name: 2005633, dtype: object

(9,)

tconst                tt11825922
titleType              tvEpisode
primaryTitle      Episode #2.241
originalTitle     Episode #2.241
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005634, dtype: object

(9,)

tconst                tt11825924
titleType              tvEpisode
primaryTitle      Episode #2.242
originalTitle     Episode #2.242
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005635, dtype: object

(9,)

tconst                tt11825926
titleType              tvEpisode
primaryTitle      Episode #2.243
originalTitle     Episode #2.243
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005636, dtype: object

(9,)

tconst                tt11825928
titleType              tvEpisode
primaryTitle      Episode #2.244
originalTitle     Episode #2.244
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005637, dtype: object

(9,)

tconst               tt1182592
titleType            tvEpisode
primaryTitle      Episode #3.3
originalTitle     Episode #3.3
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              46
genres                   Drama
Name: 2005638, dtype: object

(9,)

tconst                tt11825930
titleType              tvEpisode
primaryTitle      Episode #2.245
originalTitle     Episode #2.245
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005639, dtype: object

(9,)

tconst                tt11825932
titleType              tvEpisode
primaryTitle      Episode #2.246
originalTitle     Episode #2.246
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005640, dtype: object

(9,)

tconst                tt11825934
titleType              tvEpisode
primaryTitle      Episode #2.247
originalTitle     Episode #2.247
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005641, dtype: object

(9,)

tconst                tt11825936
titleType              tvEpisode
primaryTitle      Episode #2.248
originalTitle     Episode #2.248
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005642, dtype: object

(9,)

tconst                tt11825938
titleType              tvEpisode
primaryTitle      Episode #2.249
originalTitle     Episode #2.249
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005643, dtype: object

(9,)

tconst                 tt1182593
titleType              tvEpisode
primaryTitle      Episode #15.12
originalTitle     Episode #15.12
isAdult                        0
startYear                   2007
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2005644, dtype: object

(9,)

tconst                tt11825940
titleType              tvEpisode
primaryTitle      Episode #2.250
originalTitle     Episode #2.250
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005645, dtype: object

(9,)

tconst                tt11825942
titleType              tvEpisode
primaryTitle      Episode #2.251
originalTitle     Episode #2.251
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005646, dtype: object

(9,)

tconst                tt11825944
titleType              tvEpisode
primaryTitle      Episode #2.252
originalTitle     Episode #2.252
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005647, dtype: object

(9,)

tconst                tt11825946
titleType              tvEpisode
primaryTitle      Episode #2.253
originalTitle     Episode #2.253
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005648, dtype: object

(9,)

tconst                tt11825948
titleType              tvEpisode
primaryTitle      Episode #2.254
originalTitle     Episode #2.254
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005649, dtype: object

(9,)

tconst                tt1182594
titleType             tvEpisode
primaryTitle      Episode #9.23
originalTitle     Episode #9.23
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005650, dtype: object

(9,)

tconst                tt11825950
titleType              tvEpisode
primaryTitle      Episode #2.255
originalTitle     Episode #2.255
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005651, dtype: object

(9,)

tconst                tt11825952
titleType              tvEpisode
primaryTitle      Episode #2.256
originalTitle     Episode #2.256
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005652, dtype: object

(9,)

tconst                tt11825954
titleType              tvEpisode
primaryTitle      Episode #2.257
originalTitle     Episode #2.257
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005653, dtype: object

(9,)

tconst                tt11825956
titleType              tvEpisode
primaryTitle      Episode #2.258
originalTitle     Episode #2.258
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005654, dtype: object

(9,)

tconst                tt11825958
titleType              tvEpisode
primaryTitle      Episode #2.259
originalTitle     Episode #2.259
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005655, dtype: object

(9,)

tconst                             tt1182595
titleType                          tvEpisode
primaryTitle                       Awakening
originalTitle                      Awakening
isAdult                                    0
startYear                               2005
endYear                                   \N
runtimeMinutes                            23
genres            Action,Adventure,Animation
Name: 2005656, dtype: object

(9,)

tconst                tt11825960
titleType              tvEpisode
primaryTitle      Episode #2.260
originalTitle     Episode #2.260
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2005657, dtype: object

(9,)

tconst               tt11825962
titleType                 short
primaryTitle           No Drugs
originalTitle          No Drugs
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Musical,Short
Name: 2005658, dtype: object

(9,)

tconst                tt11825964
titleType              tvEpisode
primaryTitle       Episode #1.41
originalTitle      Episode #1.41
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005659, dtype: object

(9,)

tconst                tt11825966
titleType              tvEpisode
primaryTitle       Episode #1.42
originalTitle      Episode #1.42
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005660, dtype: object

(9,)

tconst                tt11825968
titleType              tvEpisode
primaryTitle       Episode #1.43
originalTitle      Episode #1.43
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005661, dtype: object

(9,)

tconst                  tt1182596
titleType               tvEpisode
primaryTitle      Episode #1.8825
originalTitle     Episode #1.8825
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2005662, dtype: object

(9,)

tconst                tt11825970
titleType              tvEpisode
primaryTitle       Episode #1.44
originalTitle      Episode #1.44
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005663, dtype: object

(9,)

tconst                tt11825972
titleType              tvEpisode
primaryTitle       Episode #1.46
originalTitle      Episode #1.46
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005664, dtype: object

(9,)

tconst                tt11825974
titleType              tvEpisode
primaryTitle       Episode #1.45
originalTitle      Episode #1.45
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005665, dtype: object

(9,)

tconst                tt11825976
titleType              tvEpisode
primaryTitle       Episode #1.47
originalTitle      Episode #1.47
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005666, dtype: object

(9,)

tconst                tt11825978
titleType              tvEpisode
primaryTitle       Episode #1.48
originalTitle      Episode #1.48
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005667, dtype: object

(9,)

tconst                  tt1182597
titleType               tvEpisode
primaryTitle      Episode #1.8838
originalTitle     Episode #1.8838
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2005668, dtype: object

(9,)

tconst                tt11825982
titleType              tvEpisode
primaryTitle       Episode #1.49
originalTitle      Episode #1.49
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005669, dtype: object

(9,)

tconst                tt11825984
titleType              tvEpisode
primaryTitle       Episode #1.50
originalTitle      Episode #1.50
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005670, dtype: object

(9,)

tconst                  tt11825986
titleType                tvEpisode
primaryTitle         The spaceship
originalTitle        The spaceship
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2005671, dtype: object

(9,)

tconst                tt11825988
titleType              tvEpisode
primaryTitle       Episode #1.52
originalTitle      Episode #1.52
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005672, dtype: object

(9,)

tconst               tt1182598
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2005673, dtype: object

(9,)

tconst                tt11825990
titleType              tvEpisode
primaryTitle       Episode #1.51
originalTitle      Episode #1.51
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005674, dtype: object

(9,)

tconst                tt11825992
titleType              tvEpisode
primaryTitle       Episode #1.53
originalTitle      Episode #1.53
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005675, dtype: object

(9,)

tconst                           tt11825994
titleType                             movie
primaryTitle      Yasuke: Soul of a Samurai
originalTitle     Yasuke: Soul of a Samurai
isAdult                                   0
startYear                                \N
endYear                                  \N
runtimeMinutes                           \N
genres               Action,Biography,Drama
Name: 2005676, dtype: object

(9,)

tconst                tt11825996
titleType              tvEpisode
primaryTitle       Episode #1.55
originalTitle      Episode #1.55
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005677, dtype: object

(9,)

tconst                tt11825998
titleType              tvEpisode
primaryTitle       Episode #1.54
originalTitle      Episode #1.54
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005678, dtype: object

(9,)

tconst                                tt1182599
titleType                             tvEpisode
primaryTitle      Episode dated 2 February 2008
originalTitle     Episode dated 2 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Game-Show
Name: 2005679, dtype: object

(9,)

tconst                tt11826000
titleType              tvEpisode
primaryTitle       Episode #1.56
originalTitle      Episode #1.56
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005680, dtype: object

(9,)

tconst                tt11826002
titleType              tvEpisode
primaryTitle       Episode #1.57
originalTitle      Episode #1.57
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005681, dtype: object

(9,)

tconst                tt11826004
titleType              tvEpisode
primaryTitle       Episode #1.58
originalTitle      Episode #1.58
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005682, dtype: object

(9,)

tconst                tt11826006
titleType              tvEpisode
primaryTitle       Episode #1.59
originalTitle      Episode #1.59
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005683, dtype: object

(9,)

tconst                tt11826008
titleType              tvEpisode
primaryTitle       Episode #1.60
originalTitle      Episode #1.60
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2005684, dtype: object

(9,)

tconst                                                    tt1182600
titleType                                                     video
primaryTitle      'White Christmas': A Look Back with Rosemary C...
originalTitle     'White Christmas': A Look Back with Rosemary C...
isAdult                                                           0
startYear                                                      2000
endYear                                                          \N
runtimeMinutes                                                   17
genres                                            Documentary,Short
Name: 2005685, dtype: object

(9,)

tconst                   tt11826010
titleType                  tvSeries
primaryTitle             Flashpoint
originalTitle     Goryachaya tochka
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                Drama,Mystery
Name: 2005686, dtype: object

(9,)

tconst                    tt11826012
titleType                      movie
primaryTitle      Daphne Grows Roots
originalTitle     Daphne Grows Roots
isAdult                            0
startYear                         \N
endYear                           \N
runtimeMinutes                    \N
genres                         Drama
Name: 2005687, dtype: object

(9,)

tconst                        tt11826014
titleType                      tvEpisode
primaryTitle                   Arazaramu
originalTitle                  Arazaramu
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Drama
Name: 2005688, dtype: object

(9,)

tconst                        tt11826018
titleType                      tvEpisode
primaryTitle         Mi wo tsukushite ya
originalTitle        Mi wo tsukushite ya
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Drama
Name: 2005689, dtype: object

(9,)

tconst                                  tt1182601
titleType                               tvSpecial
primaryTitle      10th Anniversary Essence Awards
originalTitle     10th Anniversary Essence Awards
isAdult                                         0
startYear                                    1997
endYear                                        \N
runtimeMinutes                                120
genres                                     Family
Name: 2005690, dtype: object

(9,)

tconst                  tt11826020
titleType                tvEpisode
primaryTitle          Snowy search
originalTitle         Snowy search
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2005691, dtype: object

(9,)

tconst                         tt11826022
titleType                           video
primaryTitle      Stevie Nicks: Every Day
originalTitle     Stevie Nicks: Every Day
isAdult                                 0
startYear                            2001
endYear                                \N
runtimeMinutes                          4
genres                        Music,Short
Name: 2005692, dtype: object

(9,)

tconst                               tt11826024
titleType                             tvEpisode
primaryTitle      Episode dated 12 October 2014
originalTitle     Episode dated 12 October 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2005693, dtype: object

(9,)

tconst                                      tt11826026
titleType                                        video
primaryTitle      Stevie Nicks & Sheryl Crow: Sorcerer
originalTitle     Stevie Nicks & Sheryl Crow: Sorcerer
isAdult                                              0
startYear                                         2001
endYear                                             \N
runtimeMinutes                                       4
genres                                     Music,Short
Name: 2005694, dtype: object

(9,)

tconst                                tt11826028
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005695, dtype: object

(9,)

tconst                      tt1182602
titleType                   tvSpecial
primaryTitle      1996 Essence Awards
originalTitle     1996 Essence Awards
isAdult                             0
startYear                        1996
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2005696, dtype: object

(9,)

tconst                tt11826030
titleType                  short
primaryTitle      The Last Straw
originalTitle     The Last Straw
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Sci-Fi,Short
Name: 2005697, dtype: object

(9,)

tconst                       tt11826032
titleType                         short
primaryTitle      To Die Like a Peacock
originalTitle     To Die Like a Peacock
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                      Drama,Short
Name: 2005698, dtype: object

(9,)

tconst                 tt11826034
titleType               tvEpisode
primaryTitle      Episode #1.1752
originalTitle     Episode #1.1752
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005699, dtype: object

(9,)

tconst                 tt11826036
titleType               tvEpisode
primaryTitle      Episode #1.1753
originalTitle     Episode #1.1753
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005700, dtype: object

(9,)

tconst                  tt11826038
titleType                tvEpisode
primaryTitle            Marisphinx
originalTitle           Marisphinx
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2005701, dtype: object

(9,)

tconst                      tt1182603
titleType                   tvEpisode
primaryTitle      The 2008 SAG Awards
originalTitle     The 2008 SAG Awards
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     60
genres               Comedy,Talk-Show
Name: 2005702, dtype: object

(9,)

tconst                 tt11826040
titleType               tvEpisode
primaryTitle      Episode #1.1754
originalTitle     Episode #1.1754
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005703, dtype: object

(9,)

tconst                 tt11826042
titleType               tvEpisode
primaryTitle      Episode #1.1755
originalTitle     Episode #1.1755
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005704, dtype: object

(9,)

tconst                 tt11826044
titleType               tvEpisode
primaryTitle      Episode #1.1756
originalTitle     Episode #1.1756
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005705, dtype: object

(9,)

tconst                 tt11826046
titleType               tvEpisode
primaryTitle      Episode #1.1757
originalTitle     Episode #1.1757
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005706, dtype: object

(9,)

tconst                 tt11826048
titleType               tvEpisode
primaryTitle      Episode #1.1758
originalTitle     Episode #1.1758
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005707, dtype: object

(9,)

tconst                                  tt1182604
titleType                               tvSpecial
primaryTitle      25th Anniversary Essence Awards
originalTitle     25th Anniversary Essence Awards
isAdult                                         0
startYear                                    1995
endYear                                        \N
runtimeMinutes                                120
genres                                     Family
Name: 2005708, dtype: object

(9,)

tconst                 tt11826052
titleType                   short
primaryTitle      Donnie Mountain
originalTitle     Donnie Mountain
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 22
genres                Drama,Short
Name: 2005709, dtype: object

(9,)

tconst                 tt11826054
titleType               tvEpisode
primaryTitle      Episode #1.1760
originalTitle     Episode #1.1760
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005710, dtype: object

(9,)

tconst                                tt11826056
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005711, dtype: object

(9,)

tconst                 tt11826058
titleType               tvEpisode
primaryTitle      Episode #1.2001
originalTitle     Episode #1.2001
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005712, dtype: object

(9,)

tconst                                tt1182605
titleType                               tvMovie
primaryTitle      Adult Entertainment Expo 2008
originalTitle     Adult Entertainment Expo 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                              Documentary
Name: 2005713, dtype: object

(9,)

tconst            tt11826060
titleType          tvEpisode
primaryTitle           Pilot
originalTitle          Pilot
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2005714, dtype: object

(9,)

tconst                 tt11826062
titleType               tvEpisode
primaryTitle      Episode #1.2002
originalTitle     Episode #1.2002
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005715, dtype: object

(9,)

tconst                 tt11826064
titleType               tvEpisode
primaryTitle      Episode #1.2004
originalTitle     Episode #1.2004
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005716, dtype: object

(9,)

tconst                 tt11826066
titleType               tvEpisode
primaryTitle      Episode #1.2003
originalTitle     Episode #1.2003
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005717, dtype: object

(9,)

tconst                                tt11826068
titleType                              tvEpisode
primaryTitle      Episode dated 28 November 2014
originalTitle     Episode dated 28 November 2014
isAdult                                        0
startYear                                   2014
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005718, dtype: object

(9,)

tconst                        tt1182606
titleType                       tvMovie
primaryTitle           Bad Cop, Bad Cop
originalTitle          Bad Cop, Bad Cop
isAdult                               0
startYear                          1998
endYear                              \N
runtimeMinutes                       \N
genres            Comedy,Crime,Thriller
Name: 2005719, dtype: object

(9,)

tconst                      tt11826070
titleType                        movie
primaryTitle      Til Death Do Us Part
originalTitle     Til Death Do Us Part
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres                  Comedy,Romance
Name: 2005720, dtype: object

(9,)

tconst                                      tt11826072
titleType                                    videoGame
primaryTitle      The Monkey King the Adventure Begins
originalTitle     The Monkey King the Adventure Begins
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      \N
genres                                       Animation
Name: 2005721, dtype: object

(9,)

tconst                 tt11826074
titleType               tvEpisode
primaryTitle      Episode #1.2005
originalTitle     Episode #1.2005
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005722, dtype: object

(9,)

tconst                 tt11826076
titleType               tvEpisode
primaryTitle      Episode #1.2006
originalTitle     Episode #1.2006
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005723, dtype: object

(9,)

tconst                 tt11826078
titleType               tvEpisode
primaryTitle      Episode #1.2007
originalTitle     Episode #1.2007
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005724, dtype: object

(9,)

tconst                                          tt1182607
titleType                                           video
primaryTitle      Billie Holiday: The Ultimate Collection
originalTitle     Billie Holiday: The Ultimate Collection
isAdult                                                 0
startYear                                            2005
endYear                                                \N
runtimeMinutes                                         \N
genres                                              Music
Name: 2005725, dtype: object

(9,)

tconst                 tt11826080
titleType               tvEpisode
primaryTitle      Episode #1.2008
originalTitle     Episode #1.2008
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005726, dtype: object

(9,)

tconst                                             tt11826082
titleType                                               video
primaryTitle      Stevie Nicks: Moonlight (A Vampire's Dream)
originalTitle     Stevie Nicks: Moonlight (A Vampire's Dream)
isAdult                                                     0
startYear                                                2011
endYear                                                    \N
runtimeMinutes                                              6
genres                                            Music,Short
Name: 2005727, dtype: object

(9,)

tconst                 tt11826084
titleType               tvEpisode
primaryTitle      Episode #1.2009
originalTitle     Episode #1.2009
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005728, dtype: object

(9,)

tconst                               tt11826086
titleType                             tvEpisode
primaryTitle      Episode dated 5 December 2014
originalTitle     Episode dated 5 December 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2005729, dtype: object

(9,)

tconst                 tt11826088
titleType               tvEpisode
primaryTitle      Episode #1.2010
originalTitle     Episode #1.2010
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005730, dtype: object

(9,)

tconst                    tt1182608
titleType                     short
primaryTitle      The Dipsy Doodler
originalTitle     The Dipsy Doodler
isAdult                           0
startYear                      1940
endYear                          \N
runtimeMinutes                   11
genres                  Music,Short
Name: 2005731, dtype: object

(9,)

tconst                 tt11826090
titleType               tvEpisode
primaryTitle      Episode #1.2011
originalTitle     Episode #1.2011
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005732, dtype: object

(9,)

tconst                               tt11826092
titleType                             tvEpisode
primaryTitle      Episode dated 8 December 2014
originalTitle     Episode dated 8 December 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2005733, dtype: object

(9,)

tconst                   tt11826094
titleType                 tvEpisode
primaryTitle      Schlangen im Büro
originalTitle     Schlangen im Büro
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2005734, dtype: object

(9,)

tconst                 tt11826096
titleType               tvEpisode
primaryTitle      Episode #1.2012
originalTitle     Episode #1.2012
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005735, dtype: object

(9,)

tconst                 tt11826098
titleType               tvEpisode
primaryTitle      Episode #1.2013
originalTitle     Episode #1.2013
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005736, dtype: object

(9,)

tconst                  tt1182609
titleType                   movie
primaryTitle       Direct Contact
originalTitle      Direct Contact
isAdult                         0
startYear                    2009
endYear                        \N
runtimeMinutes                 90
genres            Action,Thriller
Name: 2005737, dtype: object

(9,)

tconst                                tt11826100
titleType                              tvEpisode
primaryTitle      Episode dated 12 December 2014
originalTitle     Episode dated 12 December 2014
isAdult                                        0
startYear                                   2014
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005738, dtype: object

(9,)

tconst                                tt11826102
titleType                              tvEpisode
primaryTitle      Episode dated 15 December 2014
originalTitle     Episode dated 15 December 2014
isAdult                                        0
startYear                                   2014
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005739, dtype: object

(9,)

tconst                 tt11826104
titleType               tvEpisode
primaryTitle      Episode #1.2014
originalTitle     Episode #1.2014
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005740, dtype: object

(9,)

tconst                 tt11826106
titleType               tvEpisode
primaryTitle      Episode #1.2016
originalTitle     Episode #1.2016
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005741, dtype: object

(9,)

tconst                 tt11826108
titleType               tvEpisode
primaryTitle      Episode #1.2015
originalTitle     Episode #1.2015
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005742, dtype: object

(9,)

tconst                  tt1182610
titleType                   video
primaryTitle      Dressed for Sex
originalTitle     Dressed for Sex
isAdult                         1
startYear                    2006
endYear                        \N
runtimeMinutes                115
genres                      Adult
Name: 2005743, dtype: object

(9,)

tconst                 tt11826110
titleType               tvEpisode
primaryTitle      Durch die Wüste
originalTitle     Durch die Wüste
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2005744, dtype: object

(9,)

tconst                 tt11826112
titleType               tvEpisode
primaryTitle      Episode #1.2017
originalTitle     Episode #1.2017
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005745, dtype: object

(9,)

tconst                 tt11826114
titleType               tvEpisode
primaryTitle      Episode #1.2018
originalTitle     Episode #1.2018
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005746, dtype: object

(9,)

tconst                 tt11826116
titleType               tvEpisode
primaryTitle      Episode #1.2019
originalTitle     Episode #1.2019
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005747, dtype: object

(9,)

tconst                                tt11826118
titleType                              tvEpisode
primaryTitle      Episode dated 29 December 2014
originalTitle     Episode dated 29 December 2014
isAdult                                        0
startYear                                   2014
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005748, dtype: object

(9,)

tconst                                       tt1182611
titleType                                    tvEpisode
primaryTitle      The 2008 British Academy Film Awards
originalTitle     The 2008 British Academy Film Awards
isAdult                                              0
startYear                                         2008
endYear                                             \N
runtimeMinutes                                      \N
genres                                            News
Name: 2005749, dtype: object

(9,)

tconst                   tt11826120
titleType                 tvEpisode
primaryTitle      Dahoam ist dahoam
originalTitle     Dahoam ist dahoam
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2005750, dtype: object

(9,)

tconst                 tt11826122
titleType               tvEpisode
primaryTitle      Episode #1.2020
originalTitle     Episode #1.2020
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005751, dtype: object

(9,)

tconst                 tt11826124
titleType               tvEpisode
primaryTitle      Episode #1.2301
originalTitle     Episode #1.2301
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005752, dtype: object

(9,)

tconst                 tt11826126
titleType               tvEpisode
primaryTitle      Episode #1.2302
originalTitle     Episode #1.2302
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005753, dtype: object

(9,)

tconst                 tt11826128
titleType               tvEpisode
primaryTitle      Episode #1.2304
originalTitle     Episode #1.2304
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005754, dtype: object

(9,)

tconst                tt1182612
titleType             tvSpecial
primaryTitle      Farewell Vera
originalTitle     Farewell Vera
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               25
genres              Documentary
Name: 2005755, dtype: object

(9,)

tconst                         tt11826130
titleType                       tvEpisode
primaryTitle      Married To A Psychopath
originalTitle     Married To A Psychopath
isAdult                                 0
startYear                              \N
endYear                                \N
runtimeMinutes                         \N
genres                              Crime
Name: 2005756, dtype: object

(9,)

tconst                 tt11826132
titleType               tvEpisode
primaryTitle      Episode #1.2305
originalTitle     Episode #1.2305
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005757, dtype: object

(9,)

tconst                                                   tt11826134
titleType                                                     video
primaryTitle      Stevie Nicks Feat. Dave Stewart: Cheaper Than ...
originalTitle     Stevie Nicks Feat. Dave Stewart: Cheaper Than ...
isAdult                                                           0
startYear                                                      2011
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2005758, dtype: object

(9,)

tconst                               tt11826136
titleType                             tvEpisode
primaryTitle      Episode dated 12 October 1970
originalTitle     Episode dated 12 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2005759, dtype: object

(9,)

tconst                 tt11826138
titleType               tvEpisode
primaryTitle      Episode #1.2307
originalTitle     Episode #1.2307
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005760, dtype: object

(9,)

tconst                                                 tt1182613
titleType                                                tvMovie
primaryTitle      Garasu no shiro: Shuzenji onsen satsujin jiken
originalTitle     Garasu no shiro: Shuzenji onsen satsujin jiken
isAdult                                                        0
startYear                                                   2001
endYear                                                       \N
runtimeMinutes                                                90
genres                                                        \N
Name: 2005761, dtype: object

(9,)

tconst                 tt11826140
titleType               tvEpisode
primaryTitle      Episode #1.2306
originalTitle     Episode #1.2306
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005762, dtype: object

(9,)

tconst                 tt11826142
titleType               tvEpisode
primaryTitle      Episode #1.2308
originalTitle     Episode #1.2308
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005763, dtype: object

(9,)

tconst                      tt11826144
titleType                    tvEpisode
primaryTitle      Father Or A Monster?
originalTitle     Father Or A Monster?
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres                           Crime
Name: 2005764, dtype: object

(9,)

tconst                 tt11826146
titleType               tvEpisode
primaryTitle      Episode #1.2310
originalTitle     Episode #1.2310
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005765, dtype: object

(9,)

tconst                 tt11826148
titleType               tvEpisode
primaryTitle      Episode #1.2311
originalTitle     Episode #1.2311
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005766, dtype: object

(9,)

tconst                     tt1182614
titleType                    tvShort
primaryTitle      I Was That Monster
originalTitle     I Was That Monster
isAdult                            0
startYear                       1993
endYear                           \N
runtimeMinutes                     5
genres             Documentary,Short
Name: 2005767, dtype: object

(9,)

tconst                  tt11826150
titleType                tvEpisode
primaryTitle               The egg
originalTitle              The egg
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2005768, dtype: object

(9,)

tconst                 tt11826152
titleType               tvEpisode
primaryTitle      Episode #1.2312
originalTitle     Episode #1.2312
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005769, dtype: object

(9,)

tconst                  tt11826154
titleType                tvEpisode
primaryTitle        Episode #1.903
originalTitle       Episode #1.903
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005770, dtype: object

(9,)

tconst                 tt11826156
titleType               tvEpisode
primaryTitle      Episode #1.2313
originalTitle     Episode #1.2313
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005771, dtype: object

(9,)

tconst                     tt1182615
titleType                      movie
primaryTitle         Ah Long Pte Ltd
originalTitle     Lao shi jia lao da
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                   158
genres                        Comedy
Name: 2005772, dtype: object

(9,)

tconst                 tt11826160
titleType               tvEpisode
primaryTitle      Episode #1.2315
originalTitle     Episode #1.2315
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005773, dtype: object

(9,)

tconst                 tt11826162
titleType               tvEpisode
primaryTitle      Episode #1.2316
originalTitle     Episode #1.2316
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005774, dtype: object

(9,)

tconst                  tt11826164
titleType                tvEpisode
primaryTitle        Episode #1.904
originalTitle       Episode #1.904
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005775, dtype: object

(9,)

tconst                 tt11826166
titleType               tvEpisode
primaryTitle      Episode #1.2317
originalTitle     Episode #1.2317
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005776, dtype: object

(9,)

tconst                 tt11826168
titleType               tvEpisode
primaryTitle      Episode #1.2318
originalTitle     Episode #1.2318
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005777, dtype: object

(9,)

tconst                        tt1182616
titleType                       tvMovie
primaryTitle      Once Upon a Time Lord
originalTitle     Once Upon a Time Lord
isAdult                               0
startYear                          1983
endYear                              \N
runtimeMinutes                       24
genres                      Documentary
Name: 2005778, dtype: object

(9,)

tconst                 tt11826170
titleType               tvEpisode
primaryTitle      Episode #1.2319
originalTitle     Episode #1.2319
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005779, dtype: object

(9,)

tconst                 tt11826172
titleType               tvEpisode
primaryTitle      Episode #1.2320
originalTitle     Episode #1.2320
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005780, dtype: object

(9,)

tconst                           tt11826174
titleType                             video
primaryTitle      Stevie Nicks: Secret Love
originalTitle     Stevie Nicks: Secret Love
isAdult                                   0
startYear                              2011
endYear                                  \N
runtimeMinutes                            3
genres                          Music,Short
Name: 2005781, dtype: object

(9,)

tconst                  tt11826176
titleType                tvEpisode
primaryTitle        Episode #1.905
originalTitle       Episode #1.905
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005782, dtype: object

(9,)

tconst                 tt11826178
titleType               tvEpisode
primaryTitle      Episode #1.2561
originalTitle     Episode #1.2561
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2005783, dtype: object

(9,)

tconst                                                    tt1182617
titleType                                                     video
primaryTitle      One Summer in Austin: The Story of Filming 'A ...
originalTitle     One Summer in Austin: The Story of Filming 'A ...
isAdult                                                           0
startYear                                                      2006
endYear                                                          \N
runtimeMinutes                                                   26
genres                                            Documentary,Short
Name: 2005784, dtype: object

(9,)

tconst                                  tt11826180
titleType                                tvEpisode
primaryTitle      Urbain - Je n'aime plus internet
originalTitle     Urbain - Je n'aime plus internet
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                      Comedy
Name: 2005785, dtype: object

(9,)

tconst                  tt11826182
titleType                tvEpisode
primaryTitle        Episode #1.906
originalTitle       Episode #1.906
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005786, dtype: object

(9,)

tconst                  tt11826184
titleType                tvEpisode
primaryTitle        Episode #1.907
originalTitle       Episode #1.907
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005787, dtype: object

(9,)

tconst              tt11826186
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              45
genres             Crime,Drama
Name: 2005788, dtype: object

(9,)

tconst                          tt11826188
titleType                            video
primaryTitle      The Rising Mixtape Vol 1
originalTitle     The Rising Mixtape Vol 1
isAdult                                  0
startYear                             2017
endYear                                 \N
runtimeMinutes                          \N
genres                         Music,Short
Name: 2005789, dtype: object

(9,)

tconst                             tt1182618
titleType                              movie
primaryTitle      The Other Side of Istanbul
originalTitle            Das andere Istanbul
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            80
genres                           Documentary
Name: 2005790, dtype: object

(9,)

tconst                  tt11826190
titleType                tvEpisode
primaryTitle        Episode #1.908
originalTitle       Episode #1.908
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005791, dtype: object

(9,)

tconst              tt11826194
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2005792, dtype: object

(9,)

tconst                  tt11826196
titleType                tvEpisode
primaryTitle        Episode #1.909
originalTitle       Episode #1.909
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005793, dtype: object

(9,)

tconst              tt11826198
titleType              tvShort
primaryTitle        Nontourage
originalTitle       Nontourage
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              10
genres            Comedy,Short
Name: 2005794, dtype: object

(9,)

tconst                                               tt1182619
titleType                                                video
primaryTitle      The Parody Video Tom Cruise Wants You to See
originalTitle     The Parody Video Tom Cruise Wants You to See
isAdult                                                      0
startYear                                                 2008
endYear                                                     \N
runtimeMinutes                                               3
genres                                            Comedy,Short
Name: 2005795, dtype: object

(9,)

tconst              tt11826200
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2005796, dtype: object

(9,)

tconst                             tt11826202
titleType                           tvEpisode
primaryTitle                  Rebel Commander
originalTitle                 Rebel Commander
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             83
genres            Biography,Documentary,Drama
Name: 2005797, dtype: object

(9,)

tconst                  tt11826204
titleType                tvEpisode
primaryTitle        Episode #1.910
originalTitle       Episode #1.910
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005798, dtype: object

(9,)

tconst                  tt11826206
titleType                tvEpisode
primaryTitle        Episode #1.911
originalTitle       Episode #1.911
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005799, dtype: object

(9,)

tconst              tt11826208
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              44
genres             Crime,Drama
Name: 2005800, dtype: object

(9,)

tconst                                        tt1182620
titleType                                         short
primaryTitle      Screen Snapshots: Salute to Hollywood
originalTitle     Screen Snapshots: Salute to Hollywood
isAdult                                               0
startYear                                          1958
endYear                                              \N
runtimeMinutes                                       11
genres                                Documentary,Short
Name: 2005801, dtype: object

(9,)

tconst                                   tt11826210
titleType                                     video
primaryTitle      Stevie Nicks: For What It's Worth
originalTitle     Stevie Nicks: For What It's Worth
isAdult                                           0
startYear                                      2011
endYear                                          \N
runtimeMinutes                                    5
genres                                  Music,Short
Name: 2005802, dtype: object

(9,)

tconst              tt11826212
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2005803, dtype: object

(9,)

tconst               tt11826214
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2005804, dtype: object

(9,)

tconst              tt11826216
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2005805, dtype: object

(9,)

tconst                  tt11826218
titleType                tvEpisode
primaryTitle        The video game
originalTitle       The video game
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2005806, dtype: object

(9,)

tconst                         tt1182621
titleType                          short
primaryTitle      Around the World Revue
originalTitle     Around the World Revue
isAdult                                0
startYear                           1956
endYear                               \N
runtimeMinutes                        16
genres                       Music,Short
Name: 2005807, dtype: object

(9,)

tconst              tt11826220
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2005808, dtype: object

(9,)

tconst                             tt11826222
titleType                           tvEpisode
primaryTitle            Father of His Country
originalTitle           Father of His Country
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             86
genres            Biography,Documentary,Drama
Name: 2005809, dtype: object

(9,)

tconst                    tt11826224
titleType                      video
primaryTitle      Stevie Nicks: Lady
originalTitle     Stevie Nicks: Lady
isAdult                            0
startYear                       2014
endYear                           \N
runtimeMinutes                     5
genres                   Music,Short
Name: 2005810, dtype: object

(9,)

tconst                         tt11826226
titleType                       tvEpisode
primaryTitle      Sæsonens sidste budkrig
originalTitle     Sæsonens sidste budkrig
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         58
genres                         Reality-TV
Name: 2005811, dtype: object

(9,)

tconst                   tt1182622
titleType                 tvSeries
primaryTitle      Shop Like a Star
originalTitle     Shop Like a Star
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                          \N
Name: 2005812, dtype: object

(9,)

tconst              tt11826230
titleType                short
primaryTitle        Condom Wah
originalTitle       Condom Wah
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2005813, dtype: object

(9,)

tconst                           tt11826232
titleType                             short
primaryTitle      Ellos nos llaman artistas
originalTitle     Ellos nos llaman artistas
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           15
genres                    Documentary,Short
Name: 2005814, dtype: object

(9,)

tconst                         tt11826234
titleType                    tvMiniSeries
primaryTitle      La dama de las camelias
originalTitle     La dama de las camelias
isAdult                                 0
startYear                            1983
endYear                                \N
runtimeMinutes                         \N
genres                      Drama,Romance
Name: 2005815, dtype: object

(9,)

tconst                           tt11826236
titleType                         tvEpisode
primaryTitle      Être étudiant sans argent
originalTitle     Être étudiant sans argent
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                               Comedy
Name: 2005816, dtype: object

(9,)

tconst             tt11826238
titleType               short
primaryTitle             Love
originalTitle            Love
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             15
genres            Drama,Short
Name: 2005817, dtype: object

(9,)

tconst                   tt1182623
titleType                tvEpisode
primaryTitle      Belated Birthday
originalTitle     Belated Birthday
isAdult                          0
startYear                     2001
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2005818, dtype: object

(9,)

tconst                     tt11826240
titleType                       movie
primaryTitle       Lalitham Sundharam
originalTitle      Lalitham Sundharam
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2005819, dtype: object

(9,)

tconst                                                   tt11826242
titleType                                                 tvEpisode
primaryTitle      Cherchez l'intrus: Sonic, Birds of Prey, Jojo ...
originalTitle     Cherchez l'intrus: Sonic, Birds of Prey, Jojo ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2005820, dtype: object

(9,)

tconst                       tt11826246
titleType                     tvEpisode
primaryTitle      Heaux's Deconstructed
originalTitle     Heaux's Deconstructed
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                           Comedy
Name: 2005821, dtype: object

(9,)

tconst                                      tt11826248
titleType                                        video
primaryTitle      Deep Dish Feat. Stevie Nicks: Dreams
originalTitle     Deep Dish Feat. Stevie Nicks: Dreams
isAdult                                              0
startYear                                         2006
endYear                                             \N
runtimeMinutes                                       4
genres                                     Music,Short
Name: 2005822, dtype: object

(9,)

tconst                        tt1182624
titleType                     tvEpisode
primaryTitle      Caitlin's First Dance
originalTitle     Caitlin's First Dance
isAdult                               0
startYear                          2000
endYear                              \N
runtimeMinutes                       \N
genres                            Drama
Name: 2005823, dtype: object

(9,)

tconst            tt11826250
titleType              movie
primaryTitle      Feito Pipa
originalTitle     Feito Pipa
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2005824, dtype: object

(9,)

tconst                 tt11826252
titleType            tvMiniSeries
primaryTitle      Inseln Italiens
originalTitle     Inseln Italiens
isAdult                         0
startYear                    2020
endYear                      2020
runtimeMinutes                 \N
genres                Documentary
Name: 2005825, dtype: object

(9,)

tconst                  tt11826254
titleType                tvEpisode
primaryTitle          Goals on ice
originalTitle         Goals on ice
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2005826, dtype: object

(9,)

tconst                  tt11826256
titleType                tvEpisode
primaryTitle        Episode #1.912
originalTitle       Episode #1.912
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2005827, dtype: object

(9,)

tconst                                     tt11826258
titleType                                    tvSeries
primaryTitle      Frontline - Terror in Little Saigon
originalTitle     Frontline - Terror in Little Saigon
isAdult                                             0
startYear                                        2015
endYear                                          2015
runtimeMinutes                                     54
genres                                    Documentary
Name: 2005828, dtype: object

(9,)

tconst                              tt1182625
titleType                           tvEpisode
primaryTitle      Fear and Falling in Montana
originalTitle     Fear and Falling in Montana
isAdult                                     0
startYear                                2000
endYear                                    \N
runtimeMinutes                             \N
genres                                  Drama
Name: 2005829, dtype: object

(9,)

tconst                tt11826260
titleType                  movie
primaryTitle      O Melhor Amigo
originalTitle     O Melhor Amigo
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                   Romance
Name: 2005830, dtype: object

(9,)

tconst                      tt11826262
titleType                        short
primaryTitle          Shattered Visage
originalTitle         Shattered Visage
isAdult                              0
startYear                         2017
endYear                             \N
runtimeMinutes                      13
genres            Drama,Short,Thriller
Name: 2005831, dtype: object

(9,)

tconst              tt11826264
titleType                movie
primaryTitle      Teen Tilange
originalTitle     Teen Tilange
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2005832, dtype: object

(9,)

tconst                                   tt11826266
titleType                                     movie
primaryTitle      With - A Journey to the Slow Life
originalTitle                                  With
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   75
genres                                  Documentary
Name: 2005833, dtype: object

(9,)

tconst              tt1182626
titleType           tvEpisode
primaryTitle      Horror Show
originalTitle     Horror Show
isAdult                     0
startYear                2000
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2005834, dtype: object

(9,)

tconst                     tt11826270
titleType                   tvEpisode
primaryTitle      Arctic architecture
originalTitle     Arctic architecture
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres               Animation,Family
Name: 2005835, dtype: object

(9,)

tconst                                                   tt11826272
titleType                                                 tvEpisode
primaryTitle      Chisugate - tekijänoikeusjärjestöjen painajainen?
originalTitle     Chisugate - tekijänoikeusjärjestöjen painajainen?
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2005836, dtype: object

(9,)

tconst                      tt11826274
titleType                     tvSeries
primaryTitle      Faster with Finnegan
originalTitle     Faster with Finnegan
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                      Reality-TV
Name: 2005837, dtype: object

(9,)

tconst                                      tt11826276
titleType                                    tvEpisode
primaryTitle      Le courrier de janvier... en février
originalTitle     Le courrier de janvier... en février
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      \N
genres                                          Sci-Fi
Name: 2005838, dtype: object

(9,)

tconst              tt11826278
titleType                short
primaryTitle      Found Family
originalTitle     Found Family
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              12
genres             Drama,Short
Name: 2005839, dtype: object

(9,)

tconst                    tt1182627
titleType                 tvEpisode
primaryTitle      Making Allowances
originalTitle     Making Allowances
isAdult                           0
startYear                      2000
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2005840, dtype: object

(9,)

tconst                                     tt11826280
titleType                                   tvEpisode
primaryTitle      Can't Turn a Heaux into a Housewife
originalTitle     Can't Turn a Heaux into a Housewife
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                         Comedy
Name: 2005841, dtype: object

(9,)

tconst              tt11826282
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2005842, dtype: object

(9,)

tconst                           tt11826284
titleType                         tvEpisode
primaryTitle                  Episode #1.36
originalTitle                 Episode #1.36
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres            Comedy,Reality-TV,Romance
Name: 2005843, dtype: object

(9,)

tconst            tt11826286
titleType              movie
primaryTitle            CODA
originalTitle           CODA
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2005844, dtype: object

(9,)

tconst                           tt11826288
titleType                         tvEpisode
primaryTitle                  Episode #1.37
originalTitle                 Episode #1.37
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres            Comedy,Reality-TV,Romance
Name: 2005845, dtype: object

(9,)

tconst              tt1182628
titleType           tvEpisode
primaryTitle      Money Walks
originalTitle     Money Walks
isAdult                     0
startYear                2000
endYear                    \N
runtimeMinutes             30
genres                  Drama
Name: 2005846, dtype: object

(9,)

tconst                  tt11826290
titleType                tvEpisode
primaryTitle      Live Your Legacy
originalTitle     Live Your Legacy
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2005847, dtype: object

(9,)

tconst                           tt11826292
titleType                         tvEpisode
primaryTitle                  Episode #1.38
originalTitle                 Episode #1.38
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres            Comedy,Reality-TV,Romance
Name: 2005848, dtype: object

(9,)

tconst                           tt11826294
titleType                         tvEpisode
primaryTitle                  Episode #1.39
originalTitle                 Episode #1.39
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres            Comedy,Reality-TV,Romance
Name: 2005849, dtype: object

(9,)

tconst               tt11826296
titleType              tvSeries
primaryTitle      A Diner Story
originalTitle     A Diner Story
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               30
genres                    Drama
Name: 2005850, dtype: object

(9,)

tconst             tt1182629
titleType          tvEpisode
primaryTitle      Puppy Love
originalTitle     Puppy Love
isAdult                    0
startYear               2000
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2005851, dtype: object

(9,)

tconst            tt11826300
titleType              movie
primaryTitle      Honey Moon
originalTitle     Honey Moon
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            51
genres                    \N
Name: 2005852, dtype: object

(9,)

tconst             tt11826302
titleType               movie
primaryTitle       Golden Age
originalTitle      Golden Age
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             85
genres            Documentary
Name: 2005853, dtype: object

(9,)

tconst                  tt11826304
titleType                tvEpisode
primaryTitle         Cleo's circus
originalTitle        Cleo's circus
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2005854, dtype: object

(9,)

tconst             tt11826306
titleType               short
primaryTitle         Buttball
originalTitle        Buttball
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             13
genres            Drama,Short
Name: 2005855, dtype: object

(9,)

tconst                          tt11826308
titleType                        tvEpisode
primaryTitle      Trabajar para el enemigo
originalTitle     Trabajar para el enemigo
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                              Action
Name: 2005856, dtype: object

(9,)

tconst              tt1182630
titleType           tvEpisode
primaryTitle      Solar Mates
originalTitle     Solar Mates
isAdult                     0
startYear                2000
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2005857, dtype: object

(9,)

tconst                      tt11826310
titleType                 tvMiniSeries
primaryTitle      Krabbé zoekt Chagall
originalTitle     Krabbé zoekt Chagall
isAdult                              0
startYear                         2020
endYear                           2020
runtimeMinutes                      \N
genres                     Documentary
Name: 2005858, dtype: object

(9,)

tconst                       tt11826312
titleType                         short
primaryTitle      Cross the River Twice
originalTitle     Cross the River Twice
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres                      Drama,Short
Name: 2005859, dtype: object

(9,)

tconst                             tt11826314
titleType                               movie
primaryTitle      Passager, plyds og panorama
originalTitle     Passager, plyds og panorama
isAdult                                     0
startYear                                  \N
endYear                                    \N
runtimeMinutes                             \N
genres                            Documentary
Name: 2005860, dtype: object

(9,)

tconst                               tt11826316
titleType                             tvEpisode
primaryTitle      Episode dated 11 October 2019
originalTitle     Episode dated 11 October 2019
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2005861, dtype: object

(9,)

tconst                               tt11826318
titleType                             tvEpisode
primaryTitle      Episode dated 16 October 2019
originalTitle     Episode dated 16 October 2019
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2005862, dtype: object

(9,)

tconst            tt1182631
titleType         tvEpisode
primaryTitle           Solo
originalTitle          Solo
isAdult                   0
startYear              2002
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2005863, dtype: object

(9,)

tconst                  tt11826320
titleType                tvEpisode
primaryTitle         Vacation time
originalTitle        Vacation time
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2005864, dtype: object

(9,)

tconst                               tt11826322
titleType                             tvEpisode
primaryTitle      Episode dated 22 October 2019
originalTitle     Episode dated 22 October 2019
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2005865, dtype: object

(9,)

tconst                               tt11826324
titleType                             tvEpisode
primaryTitle      Episode dated 5 November 2019
originalTitle     Episode dated 5 November 2019
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2005866, dtype: object

(9,)

tconst              tt11826326
titleType            tvEpisode
primaryTitle      The Precinct
originalTitle     The Precinct
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Crime
Name: 2005867, dtype: object

(9,)

tconst                               tt11826328
titleType                             tvEpisode
primaryTitle      Episode dated 8 November 2019
originalTitle     Episode dated 8 November 2019
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2005868, dtype: object

(9,)

tconst                tt1182632
titleType             tvEpisode
primaryTitle      The Candidate
originalTitle     The Candidate
isAdult                       0
startYear                  2000
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2005869, dtype: object

(9,)

tconst                               tt11826330
titleType                             tvEpisode
primaryTitle      Episode dated 3 December 2019
originalTitle     Episode dated 3 December 2019
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2005870, dtype: object

(9,)

tconst             tt11826332
titleType               video
primaryTitle           Poison
originalTitle          Poison
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Music,Short
Name: 2005871, dtype: object

(9,)

tconst               tt11826334
titleType             tvEpisode
primaryTitle       Episode #1.2
originalTitle      Episode #1.2
isAdult                       0
startYear                  1998
endYear                      \N
runtimeMinutes               \N
genres            Action,Horror
Name: 2005872, dtype: object

(9,)

tconst                                       tt11826338
titleType                                         short
primaryTitle      ACA Dreams Being Young Gifted & Black
originalTitle     ACA Dreams Being Young Gifted & Black
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                Documentary,Short
Name: 2005873, dtype: object

(9,)

tconst                      tt1182633
titleType                   tvEpisode
primaryTitle      Under Western Skies
originalTitle     Under Western Skies
isAdult                             0
startYear                        2000
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2005874, dtype: object

(9,)

tconst                               tt11826340
titleType                             tvEpisode
primaryTitle      Episode dated 13 October 1970
originalTitle     Episode dated 13 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2005875, dtype: object

(9,)

tconst            tt11826342
titleType            tvMovie
primaryTitle         Gastone
originalTitle        Gastone
isAdult                    0
startYear               1977
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2005876, dtype: object

(9,)

tconst                 tt11826344
titleType               tvSpecial
primaryTitle      Hometown Heroes
originalTitle     Hometown Heroes
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                      Music
Name: 2005877, dtype: object

(9,)

tconst             tt11826346
titleType           tvEpisode
primaryTitle         Sizilien
originalTitle        Sizilien
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             43
genres            Documentary
Name: 2005878, dtype: object

(9,)

tconst             tt11826348
titleType               video
primaryTitle           Jhumka
originalTitle          Jhumka
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Music,Short
Name: 2005879, dtype: object

(9,)

tconst                    tt1182634
titleType                 tvEpisode
primaryTitle      Misty Witherspoon
originalTitle     Misty Witherspoon
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   44
genres            Crime,Documentary
Name: 2005880, dtype: object

(9,)

tconst                                                   tt11826350
titleType                                                 tvEpisode
primaryTitle      Groundbreaking Anti-Aging Drug Trial!/Baby Ste...
originalTitle     Groundbreaking Anti-Aging Drug Trial!/Baby Ste...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                    News,Reality-TV,Talk-Show
Name: 2005881, dtype: object

(9,)

tconst                   tt11826352
titleType                 tvEpisode
primaryTitle      Liparische Inseln
originalTitle     Liparische Inseln
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   43
genres                  Documentary
Name: 2005882, dtype: object

(9,)

tconst               tt11826356
titleType             tvEpisode
primaryTitle      Isole Tremiti
originalTitle     Isole Tremiti
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               43
genres              Documentary
Name: 2005883, dtype: object

(9,)

tconst                                                   tt11826358
titleType                                                 tvEpisode
primaryTitle      Shaman Durek's Guide to Love!/Why Am I Single?...
originalTitle     Shaman Durek's Guide to Love!/Why Am I Single?...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                    News,Reality-TV,Talk-Show
Name: 2005884, dtype: object

(9,)

tconst                    tt1182635
titleType                 tvEpisode
primaryTitle         Sharon Daniels
originalTitle        Sharon Daniels
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   22
genres            Crime,Documentary
Name: 2005885, dtype: object

(9,)

tconst                             tt11826360
titleType                               movie
primaryTitle      Mai Khoi and the Dissidents
originalTitle     Mai Khoi and the Dissidents
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             70
genres                            Documentary
Name: 2005886, dtype: object

(9,)

tconst                                    tt11826362
titleType                                  tvEpisode
primaryTitle      After the Hunt - Unknown Ancestors
originalTitle     After the Hunt - Unknown Ancestors
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    42
genres                  Adventure,Mystery,Reality-TV
Name: 2005887, dtype: object

(9,)

tconst                tt11826364
titleType              tvEpisode
primaryTitle      The Good Fight
originalTitle     The Good Fight
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2005888, dtype: object

(9,)

tconst                        tt11826366
titleType                      tvEpisode
primaryTitle      Seven Three Distilling
originalTitle     Seven Three Distilling
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                        Reality-TV
Name: 2005889, dtype: object

(9,)

tconst                 tt11826368
titleType               tvEpisode
primaryTitle      Episode #1.5370
originalTitle     Episode #1.5370
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2005890, dtype: object

(9,)

tconst                    tt1182636
titleType                 tvEpisode
primaryTitle      And All That Jazz
originalTitle     And All That Jazz
isAdult                           0
startYear                      1974
endYear                          \N
runtimeMinutes                   \N
genres                        Music
Name: 2005891, dtype: object

(9,)

tconst                                                   tt11826370
titleType                                                 tvEpisode
primaryTitle      Nurses under Attack!/Misdiagnosed Post-Pregnan...
originalTitle     Nurses under Attack!/Misdiagnosed Post-Pregnan...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                    News,Reality-TV,Talk-Show
Name: 2005892, dtype: object

(9,)

tconst              tt11826372
titleType                short
primaryTitle             12/14
originalTitle            12/14
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              10
genres            Sci-Fi,Short
Name: 2005893, dtype: object

(9,)

tconst                                                tt11826374
titleType                                              tvEpisode
primaryTitle      Will Ferrell Deeply Regrets Eating Spicy Wings
originalTitle     Will Ferrell Deeply Regrets Eating Spicy Wings
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                \N
genres                                          Comedy,Talk-Show
Name: 2005894, dtype: object

(9,)

tconst             tt11826376
titleType               short
primaryTitle         I'm Fine
originalTitle        I'm Fine
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes             10
genres            Drama,Short
Name: 2005895, dtype: object

(9,)

tconst                              tt1182637
titleType                           tvEpisode
primaryTitle      Dancing on a Saturday Night
originalTitle     Dancing on a Saturday Night
isAdult                                     0
startYear                                1974
endYear                                    \N
runtimeMinutes                             \N
genres                                  Music
Name: 2005896, dtype: object

(9,)

tconst                          tt11826380
titleType                        tvEpisode
primaryTitle                  Episode #1.1
originalTitle                 Episode #1.1
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          51
genres            Action,Comedy,Reality-TV
Name: 2005897, dtype: object

(9,)

tconst              tt11826382
titleType         tvMiniSeries
primaryTitle      O Meu Sangue
originalTitle     O Meu Sangue
isAdult                      0
startYear                 2020
endYear                   2020
runtimeMinutes              \N
genres             Documentary
Name: 2005898, dtype: object

(9,)

tconst                          tt11826384
titleType                        tvEpisode
primaryTitle                  Episode #1.2
originalTitle                 Episode #1.2
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          51
genres            Action,Comedy,Reality-TV
Name: 2005899, dtype: object

(9,)

tconst                          tt11826386
titleType                        tvEpisode
primaryTitle                  Episode #1.3
originalTitle                 Episode #1.3
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          52
genres            Action,Comedy,Reality-TV
Name: 2005900, dtype: object

(9,)

tconst                          tt11826388
titleType                        tvEpisode
primaryTitle                  Episode #1.4
originalTitle                 Episode #1.4
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          48
genres            Action,Comedy,Reality-TV
Name: 2005901, dtype: object

(9,)

tconst               tt1182638
titleType            tvEpisode
primaryTitle      His and Hers
originalTitle     His and Hers
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2005902, dtype: object

(9,)

tconst                          tt11826390
titleType                        tvEpisode
primaryTitle                  Episode #1.5
originalTitle                 Episode #1.5
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          49
genres            Action,Comedy,Reality-TV
Name: 2005903, dtype: object

(9,)

tconst                         tt11826392
titleType                       tvEpisode
primaryTitle      NJoy Spirits Distillery
originalTitle     NJoy Spirits Distillery
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                         Reality-TV
Name: 2005904, dtype: object

(9,)

tconst              tt11826394
titleType                movie
primaryTitle      Broken Souls
originalTitle      Almas Rotas
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2005905, dtype: object

(9,)

tconst                                tt11826396
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005906, dtype: object

(9,)

tconst                          tt11826398
titleType                        tvEpisode
primaryTitle                  Episode #1.6
originalTitle                 Episode #1.6
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          52
genres            Action,Comedy,Reality-TV
Name: 2005907, dtype: object

(9,)

tconst                    tt1182639
titleType                 tvEpisode
primaryTitle      Off to the Movies
originalTitle     Off to the Movies
isAdult                           0
startYear                      1974
endYear                          \N
runtimeMinutes                   \N
genres                        Music
Name: 2005908, dtype: object

(9,)

tconst            tt11826400
titleType          tvEpisode
primaryTitle      Mean Girls
originalTitle     Mean Girls
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2005909, dtype: object

(9,)

tconst                tt11826404
titleType              tvEpisode
primaryTitle      Episode #20.22
originalTitle     Episode #20.22
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2005910, dtype: object

(9,)

tconst                        tt11826408
titleType                      tvEpisode
primaryTitle      La Chasse Au Chevreuil
originalTitle     La Chasse Au Chevreuil
isAdult                                0
startYear                           2017
endYear                               \N
runtimeMinutes                        22
genres                       Documentary
Name: 2005911, dtype: object

(9,)

tconst                                  tt1182640
titleType                               tvEpisode
primaryTitle      The Bacharach & David Song Book
originalTitle     The Bacharach & David Song Book
isAdult                                         0
startYear                                    1973
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Music
Name: 2005912, dtype: object

(9,)

tconst                                                tt11826410
titleType                                                  video
primaryTitle      Sex with Grandpa Ed Powers: Featuring Lulu Chu
originalTitle     Sex with Grandpa Ed Powers: Featuring Lulu Chu
isAdult                                                        1
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                50
genres                                                     Adult
Name: 2005913, dtype: object

(9,)

tconst                       tt11826412
titleType                      tvSeries
primaryTitle      Inhotim Arte Presente
originalTitle     Inhotim Arte Presente
isAdult                               0
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2005914, dtype: object

(9,)

tconst                     tt11826414
titleType                    tvSeries
primaryTitle      The Bruce Gold Show
originalTitle     The Bruce Gold Show
isAdult                             0
startYear                        2018
endYear                            \N
runtimeMinutes                     30
genres                      Talk-Show
Name: 2005915, dtype: object

(9,)

tconst                               tt11826416
titleType                             tvEpisode
primaryTitle      Episode dated 14 October 1970
originalTitle     Episode dated 14 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2005916, dtype: object

(9,)

tconst                                             tt11826418
titleType                                           tvEpisode
primaryTitle      Chattanooga Experimental Whiskey Distillery
originalTitle     Chattanooga Experimental Whiskey Distillery
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             \N
genres                                             Reality-TV
Name: 2005917, dtype: object

(9,)

tconst                        tt1182641
titleType                     tvEpisode
primaryTitle      The French Connection
originalTitle     The French Connection
isAdult                               0
startYear                          1973
endYear                              \N
runtimeMinutes                       \N
genres                            Music
Name: 2005918, dtype: object

(9,)

tconst             tt11826420
titleType               short
primaryTitle      Blue, Diane
originalTitle     Blue, Diane
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes              7
genres                  Short
Name: 2005919, dtype: object

(9,)

tconst                                 tt11826422
titleType                               tvEpisode
primaryTitle      Top 10 Guilty Pleasure TV Shows
originalTitle     Top 10 Guilty Pleasure TV Shows
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Talk-Show
Name: 2005920, dtype: object

(9,)

tconst             tt11826424
titleType               short
primaryTitle        Esmeralda
originalTitle       Esmeralda
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2005921, dtype: object

(9,)

tconst                tt11826426
titleType                  short
primaryTitle       The Candidate
originalTitle      The Candidate
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            Short,Thriller
Name: 2005922, dtype: object

(9,)

tconst                                           tt11826428
titleType                                         tvSpecial
primaryTitle      The 18th Annual Americana Honors & Awards
originalTitle     The 18th Annual Americana Honors & Awards
isAdult                                                   0
startYear                                              2019
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Music
Name: 2005923, dtype: object

(9,)

tconst                   tt1182642
titleType                tvEpisode
primaryTitle      The One Man Band
originalTitle     The One Man Band
isAdult                          0
startYear                     1974
endYear                         \N
runtimeMinutes                  \N
genres                       Music
Name: 2005924, dtype: object

(9,)

tconst                                                   tt11826430
titleType                                                     video
primaryTitle      Cathy Lee Crosby's 20 Minute Beautiful Body Wo...
originalTitle     Cathy Lee Crosby's 20 Minute Beautiful Body Wo...
isAdult                                                           0
startYear                                                      1989
endYear                                                          \N
runtimeMinutes                                                   26
genres                                                        Short
Name: 2005925, dtype: object

(9,)

tconst                       tt11826432
titleType                       tvMovie
primaryTitle      Gyilkosság aknatüzben
originalTitle     Gyilkosság aknatüzben
isAdult                               0
startYear                          1965
endYear                              \N
runtimeMinutes                       \N
genres                            Crime
Name: 2005926, dtype: object

(9,)

tconst                                                   tt11826434
titleType                                                 tvEpisode
primaryTitle      Riittääkö ymmärrystä protestoiville kreikkalai...
originalTitle     Riittääkö ymmärrystä protestoiville kreikkalai...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2005927, dtype: object

(9,)

tconst                                                   tt11826436
titleType                                                 tvEpisode
primaryTitle      Miksi julkinen tieto on niin vaikeasti saatavi...
originalTitle     Miksi julkinen tieto on niin vaikeasti saatavi...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2005928, dtype: object

(9,)

tconst                      tt1182643
titleType                   tvEpisode
primaryTitle      The Roaring Forties
originalTitle     The Roaring Forties
isAdult                             0
startYear                        1974
endYear                            \N
runtimeMinutes                     \N
genres                          Music
Name: 2005929, dtype: object

(9,)

tconst                                      tt11826440
titleType                                    tvEpisode
primaryTitle      Miksi paskaduuni ei kelpaa köyhälle?
originalTitle     Miksi paskaduuni ei kelpaa köyhälle?
isAdult                                              0
startYear                                         2012
endYear                                             \N
runtimeMinutes                                      \N
genres                                       Talk-Show
Name: 2005930, dtype: object

(9,)

tconst                tt11826442
titleType                  short
primaryTitle      Brutal Neglect
originalTitle     Brutal Neglect
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Short
Name: 2005931, dtype: object

(9,)

tconst                  tt11826444
titleType                tvEpisode
primaryTitle      Asuntokeskustelu
originalTitle     Asuntokeskustelu
isAdult                          0
startYear                     2012
endYear                         \N
runtimeMinutes                  \N
genres                          \N
Name: 2005932, dtype: object

(9,)

tconst                         tt11826446
titleType                           video
primaryTitle      Womack & Womack: Uptown
originalTitle     Womack & Womack: Uptown
isAdult                                 0
startYear                            1991
endYear                                \N
runtimeMinutes                          5
genres                        Music,Short
Name: 2005933, dtype: object

(9,)

tconst                                                   tt11826448
titleType                                                 tvEpisode
primaryTitle      Är det ok att pissa på finlandssvenskarna? Mik...
originalTitle     Är det ok att pissa på finlandssvenskarna? Mik...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2005934, dtype: object

(9,)

tconst                        tt1182644
titleType                     tvEpisode
primaryTitle      The Tale of a Scorpio
originalTitle     The Tale of a Scorpio
isAdult                               0
startYear                          1974
endYear                              \N
runtimeMinutes                       \N
genres                            Music
Name: 2005935, dtype: object

(9,)

tconst                   tt11826450
titleType                     movie
primaryTitle      Lady of the Manor
originalTitle     Lady of the Manor
isAdult                           0
startYear                      2021
endYear                          \N
runtimeMinutes                   96
genres                       Comedy
Name: 2005936, dtype: object

(9,)

tconst                                                   tt11826452
titleType                                                 tvEpisode
primaryTitle      Onko helpompi myöntää tavoittelevansa terveytt...
originalTitle     Onko helpompi myöntää tavoittelevansa terveytt...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2005937, dtype: object

(9,)

tconst                                                   tt11826454
titleType                                                 tvEpisode
primaryTitle      Mitä me tehdään kerjäläisille? Miksi ne tulee ...
originalTitle     Mitä me tehdään kerjäläisille? Miksi ne tulee ...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2005938, dtype: object

(9,)

tconst                                             tt11826456
titleType                                           tvEpisode
primaryTitle      Mitä voi kirjoittaa poliittisessa blogissa?
originalTitle     Mitä voi kirjoittaa poliittisessa blogissa?
isAdult                                                     0
startYear                                                2012
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                     \N
Name: 2005939, dtype: object

(9,)

tconst                                                   tt11826458
titleType                                                 tvEpisode
primaryTitle      Miten sosiaalinen media voi haastaa perinteise...
originalTitle     Miten sosiaalinen media voi haastaa perinteise...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2005940, dtype: object

(9,)

tconst                     tt1182645
titleType                  tvEpisode
primaryTitle      The Young at Heart
originalTitle     The Young at Heart
isAdult                            0
startYear                       1974
endYear                           \N
runtimeMinutes                    \N
genres                         Music
Name: 2005941, dtype: object

(9,)

tconst            tt11826460
titleType              video
primaryTitle       Hot Water
originalTitle      Hot Water
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2005942, dtype: object

(9,)

tconst                    tt11826462
titleType                  tvEpisode
primaryTitle      Kaivos tuli kylään
originalTitle     Kaivos tuli kylään
isAdult                            0
startYear                       2012
endYear                           \N
runtimeMinutes                    \N
genres                            \N
Name: 2005943, dtype: object

(9,)

tconst                          tt11826464
titleType                            movie
primaryTitle      Superman: Mortal Menaces
originalTitle     Superman: Mortal Menaces
isAdult                                  0
startYear                             2021
endYear                                 \N
runtimeMinutes                          \N
genres                              Action
Name: 2005944, dtype: object

(9,)

tconst                                                   tt11826466
titleType                                                 tvEpisode
primaryTitle      Onko suomalainen peruskoulu hanurista? Vai onk...
originalTitle     Onko suomalainen peruskoulu hanurista? Vai onk...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2005945, dtype: object

(9,)

tconst                          tt11826468
titleType                            movie
primaryTitle      T.U.C. Stories the Movie
originalTitle     T.U.C. Stories the Movie
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                         Crime,Drama
Name: 2005946, dtype: object

(9,)

tconst              tt1182646
titleType           tvEpisode
primaryTitle      What's New?
originalTitle     What's New?
isAdult                     0
startYear                1974
endYear                    \N
runtimeMinutes             \N
genres                  Music
Name: 2005947, dtype: object

(9,)

tconst                                                   tt11826470
titleType                                                 tvEpisode
primaryTitle      Pitäisikö Euroviisut järjestää Bakussa vaikka ...
originalTitle     Pitäisikö Euroviisut järjestää Bakussa vaikka ...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2005948, dtype: object

(9,)

tconst               tt11826472
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2012
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2005949, dtype: object

(9,)

tconst                tt11826474
titleType              tvEpisode
primaryTitle      La Grande Bête
originalTitle     La Grande Bête
isAdult                        0
startYear                   2017
endYear                       \N
runtimeMinutes                22
genres               Documentary
Name: 2005950, dtype: object

(9,)

tconst                                tt11826476
titleType                              tvEpisode
primaryTitle      Sausage, Shawarma & Scaloppini
originalTitle     Sausage, Shawarma & Scaloppini
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                Reality-TV
Name: 2005951, dtype: object

(9,)

tconst                              tt11826478
titleType                            tvEpisode
primaryTitle      Episode dated 31 August 2012
originalTitle     Episode dated 31 August 2012
isAdult                                      0
startYear                                 2012
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2005952, dtype: object

(9,)

tconst               tt1182647
titleType            tvEpisode
primaryTitle      Abortion War
originalTitle     Abortion War
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2005953, dtype: object

(9,)

tconst                                              tt11826480
titleType                                            tvEpisode
primaryTitle      Käskevätkö jääkiekkovalmentajat väkivaltaan?
originalTitle     Käskevätkö jääkiekkovalmentajat väkivaltaan?
isAdult                                                      0
startYear                                                 2012
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                      \N
Name: 2005954, dtype: object

(9,)

tconst                                                   tt11826482
titleType                                                 tvEpisode
primaryTitle      Ninistö tarjoaa halia, pusia ja pullaa syrjäyt...
originalTitle     Ninistö tarjoaa halia, pusia ja pullaa syrjäyt...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2005955, dtype: object

(9,)

tconst                                                tt11826484
titleType                                              tvEpisode
primaryTitle      Onko läskistä hyötyä vai haittaa politiikassa?
originalTitle     Onko läskistä hyötyä vai haittaa politiikassa?
isAdult                                                        0
startYear                                                   2012
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                        \N
Name: 2005956, dtype: object

(9,)

tconst                                 tt11826486
titleType                               tvEpisode
primaryTitle      Episode dated 28 September 2012
originalTitle     Episode dated 28 September 2012
isAdult                                         0
startYear                                    2012
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2005957, dtype: object

(9,)

tconst                tt11826488
titleType                  movie
primaryTitle      Wildest Arctic
originalTitle     Wildest Arctic
isAdult                        0
startYear                   1999
endYear                       \N
runtimeMinutes                50
genres               Documentary
Name: 2005958, dtype: object

(9,)

tconst                  tt1182648
titleType               tvEpisode
primaryTitle      Anger Advantage
originalTitle     Anger Advantage
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2005959, dtype: object

(9,)

tconst                                                   tt11826490
titleType                                                 tvEpisode
primaryTitle      Romney haastaa tosissaan Obaman. Mihin katosi ...
originalTitle     Romney haastaa tosissaan Obaman. Mihin katosi ...
isAdult                                                           0
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2005960, dtype: object

(9,)

tconst                               tt11826492
titleType                             tvEpisode
primaryTitle      Episode dated 9 November 2012
originalTitle     Episode dated 9 November 2012
isAdult                                       0
startYear                                  2012
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2005961, dtype: object

(9,)

tconst                                                  tt11826494
titleType                                                tvEpisode
primaryTitle      Mitä työelämässä mättää kun jengi palaa loppuun?
originalTitle     Mitä työelämässä mättää kun jengi palaa loppuun?
isAdult                                                          0
startYear                                                     2012
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                          \N
Name: 2005962, dtype: object

(9,)

tconst                        tt11826496
titleType                      tvEpisode
primaryTitle      Systemkritik, nej tak!
originalTitle     Systemkritik, nej tak!
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        25
genres             Comedy,News,Talk-Show
Name: 2005963, dtype: object

(9,)

tconst                          tt1182649
titleType                       tvEpisode
primaryTitle      Black History Month III
originalTitle     Black History Month III
isAdult                                 0
startYear                            2003
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2005964, dtype: object

(9,)

tconst                                tt11826500
titleType                              tvEpisode
primaryTitle      Episode dated 23 November 2012
originalTitle     Episode dated 23 November 2012
isAdult                                        0
startYear                                   2012
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2005965, dtype: object

(9,)

tconst            tt11826502
titleType          tvEpisode
primaryTitle         Charade
originalTitle        Charade
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2005966, dtype: object

(9,)

tconst              tt11826504
titleType            tvEpisode
primaryTitle      The Selftape
originalTitle     The Selftape
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2005967, dtype: object

(9,)

tconst                 tt11826506
titleType               tvEpisode
primaryTitle      Dont talk to me
originalTitle     Dont talk to me
isAdult                         0
startYear                    2022
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Sci-Fi
Name: 2005968, dtype: object

(9,)

tconst                       tt11826508
titleType                      tvSeries
primaryTitle      UNPOLITICALLY CORRECT
originalTitle     UNPOLITICALLY CORRECT
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                           Comedy
Name: 2005969, dtype: object

(9,)

tconst            tt1182650
titleType         tvEpisode
primaryTitle          Brag!
originalTitle         Brag!
isAdult                   0
startYear              2003
endYear                  \N
runtimeMinutes           \N
genres            Talk-Show
Name: 2005970, dtype: object

(9,)

tconst                        tt11826510
titleType                      tvEpisode
primaryTitle      An Intro to Sangiovese
originalTitle     An Intro to Sangiovese
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2005971, dtype: object

(9,)

tconst                    tt11826512
titleType                      movie
primaryTitle      Wildest Antarctica
originalTitle     Wildest Antarctica
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    56
genres                   Documentary
Name: 2005972, dtype: object

(9,)

tconst                     tt11826516
titleType                   tvEpisode
primaryTitle      An Intro to Acidity
originalTitle     An Intro to Acidity
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2005973, dtype: object

(9,)

tconst              tt11826518
titleType            tvEpisode
primaryTitle      The Callback
originalTitle     The Callback
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2005974, dtype: object

(9,)

tconst                      tt1182651
titleType                   tvEpisode
primaryTitle      Carol Moseley Braun
originalTitle     Carol Moseley Braun
isAdult                             0
startYear                        2003
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2005975, dtype: object

(9,)

tconst              tt11826520
titleType                movie
primaryTitle      Mystery Spot
originalTitle     Mystery Spot
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes             111
genres                  Horror
Name: 2005976, dtype: object

(9,)

tconst                  tt11826522
titleType                tvEpisode
primaryTitle      Heaux Technology
originalTitle     Heaux Technology
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2005977, dtype: object

(9,)

tconst                   tt11826524
titleType                 tvEpisode
primaryTitle      Wednesday, Feb 19
originalTitle     Wednesday, Feb 19
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2005978, dtype: object

(9,)

tconst                                                tt11826526
titleType                                              tvEpisode
primaryTitle      Mitä itsenäisyyspäivän vietossa oikein mättää?
originalTitle     Mitä itsenäisyyspäivän vietossa oikein mättää?
isAdult                                                        0
startYear                                                   2012
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                 Talk-Show
Name: 2005979, dtype: object

(9,)

tconst                                                   tt11826528
titleType                                                     video
primaryTitle      Ash King & Jyotica Tangri ft. Kangna Sharma: Y...
originalTitle     Ash King & Jyotica Tangri ft. Kangna Sharma: Y...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2005980, dtype: object

(9,)

tconst                      tt1182652
titleType                   tvEpisode
primaryTitle      Cheating in Schools
originalTitle     Cheating in Schools
isAdult                             0
startYear                        2003
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2005981, dtype: object

(9,)

tconst                     tt11826532
titleType                   tvEpisode
primaryTitle      Das "perfekte" Paar
originalTitle     Das "perfekte" Paar
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                  Drama,Romance
Name: 2005982, dtype: object

(9,)

tconst                                tt11826534
titleType                              tvEpisode
primaryTitle      Episode dated 14 December 2012
originalTitle     Episode dated 14 December 2012
isAdult                                        0
startYear                                   2012
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2005983, dtype: object

(9,)

tconst                           tt11826536
titleType                         tvEpisode
primaryTitle      Four Heaux's and a Doctor
originalTitle     Four Heaux's and a Doctor
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                               Comedy
Name: 2005984, dtype: object

(9,)

tconst                    tt1182653
titleType                 tvEpisode
primaryTitle      Cult of Celebrity
originalTitle     Cult of Celebrity
isAdult                           0
startYear                      2003
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2005985, dtype: object

(9,)

tconst                            tt11826540
titleType                          tvEpisode
primaryTitle      Episode dated 24 June 2019
originalTitle     Episode dated 24 June 2019
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2005986, dtype: object

(9,)

tconst                             tt11826542
titleType                           tvEpisode
primaryTitle      Episode dated 31 March 2016
originalTitle     Episode dated 31 March 2016
isAdult                                     0
startYear                                2016
endYear                                    \N
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2005987, dtype: object

(9,)

tconst                                  tt11826544
titleType                                tvEpisode
primaryTitle      Jasper - Attacked the wrong gal!
originalTitle     Jasper - Attacked the wrong gal!
isAdult                                          1
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2005988, dtype: object

(9,)

tconst                             tt11826546
titleType                           tvEpisode
primaryTitle      Episode dated 5 August 2011
originalTitle     Episode dated 5 August 2011
isAdult                                     0
startYear                                2011
endYear                                    \N
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2005989, dtype: object

(9,)

tconst               tt1182654
titleType            tvEpisode
primaryTitle      Dance Injury
originalTitle     Dance Injury
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2005990, dtype: object

(9,)

tconst                                 tt11826550
titleType                               tvEpisode
primaryTitle      Episode dated 22 September 2011
originalTitle     Episode dated 22 September 2011
isAdult                                         0
startYear                                    2011
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2005991, dtype: object

(9,)

tconst                  tt11826552
titleType                tvEpisode
primaryTitle         Episode #2.52
originalTitle        Episode #2.52
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2005992, dtype: object

(9,)

tconst                               tt11826554
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2013
originalTitle     Episode dated 5 February 2013
isAdult                                       0
startYear                                  2013
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2005993, dtype: object

(9,)

tconst                                            tt11826556
titleType                                              video
primaryTitle      Ankit Tiwari & Jyotica Tangri: Taake Naina
originalTitle     Ankit Tiwari & Jyotica Tangri: Taake Naina
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                             5
genres                                           Music,Short
Name: 2005994, dtype: object

(9,)

tconst                  tt11826558
titleType                tvEpisode
primaryTitle      But Her Mom Will
originalTitle     But Her Mom Will
isAdult                          1
startYear                     2020
endYear                         \N
runtimeMinutes                  32
genres                       Adult
Name: 2005995, dtype: object

(9,)

tconst                             tt1182655
titleType                          tvEpisode
primaryTitle      Denver Pay for Performance
originalTitle     Denver Pay for Performance
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2005996, dtype: object

(9,)

tconst                  tt11826560
titleType                  tvMovie
primaryTitle      American Luthier
originalTitle     American Luthier
isAdult                          0
startYear                       \N
endYear                         \N
runtimeMinutes                  \N
genres                  Reality-TV
Name: 2005997, dtype: object

(9,)

tconst             tt11826562
titleType               movie
primaryTitle      Tell Me Why
originalTitle     Tell Me Why
isAdult                     0
startYear                2022
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2005998, dtype: object

(9,)

tconst                            tt11826564
titleType                          tvEpisode
primaryTitle                        Training
originalTitle                       Training
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2005999, dtype: object

(9,)

tconst             tt11826566
titleType           tvEpisode
primaryTitle      The Manager
originalTitle     The Manager
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2006000, dtype: object

(9,)

tconst                         tt11826568
titleType                       tvEpisode
primaryTitle      Belly, Beef & Bratwurst
originalTitle     Belly, Beef & Bratwurst
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         21
genres                         Reality-TV
Name: 2006001, dtype: object

(9,)

tconst               tt1182656
titleType            tvEpisode
primaryTitle      Diesel Fumes
originalTitle     Diesel Fumes
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2006002, dtype: object

(9,)

tconst               tt11826570
titleType                 short
primaryTitle      Truth Be Told
originalTitle     Truth Be Told
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres             Comedy,Short
Name: 2006003, dtype: object

(9,)

tconst                             tt11826572
titleType                               video
primaryTitle      Making of Fleming dvd extra
originalTitle     Making of Fleming dvd extra
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             20
genres                      Documentary,Short
Name: 2006004, dtype: object

(9,)

tconst                      tt11826574
titleType                    tvEpisode
primaryTitle      Burger and Breakfast
originalTitle     Burger and Breakfast
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                      Reality-TV
Name: 2006005, dtype: object

(9,)

tconst                             tt11826576
titleType                           tvEpisode
primaryTitle      British, Hawaiian & Mexican
originalTitle     British, Hawaiian & Mexican
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres                             Reality-TV
Name: 2006006, dtype: object

(9,)

tconst                     tt1182657
titleType                  tvEpisode
primaryTitle      Diversity Pipeline
originalTitle     Diversity Pipeline
isAdult                            0
startYear                       2003
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2006007, dtype: object

(9,)

tconst                    tt11826580
titleType                  tvEpisode
primaryTitle      Ghosts of the Past
originalTitle     Ghosts of the Past
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    42
genres                            \N
Name: 2006008, dtype: object

(9,)

tconst                                   tt11826582
titleType                                 tvEpisode
primaryTitle      Crazy Chicken and Twisted Burgers
originalTitle     Crazy Chicken and Twisted Burgers
isAdult                                           0
startYear                                      2019
endYear                                          \N
runtimeMinutes                                   21
genres                                   Reality-TV
Name: 2006009, dtype: object

(9,)

tconst                      tt11826584
titleType                    tvEpisode
primaryTitle                      4001
originalTitle                     4001
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006010, dtype: object

(9,)

tconst                   tt11826586
titleType                 tvEpisode
primaryTitle      Evening adventure
originalTitle     Evening adventure
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres             Animation,Family
Name: 2006011, dtype: object

(9,)

tconst            tt11826588
titleType          tvEpisode
primaryTitle        Lovesick
originalTitle       Lovesick
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006012, dtype: object

(9,)

tconst                    tt1182658
titleType                 tvEpisode
primaryTitle      Dr. Sandra Headen
originalTitle     Dr. Sandra Headen
isAdult                           0
startYear                      2003
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2006013, dtype: object

(9,)

tconst                    tt11826590
titleType                  tvEpisode
primaryTitle      Spinning the Globe
originalTitle     Spinning the Globe
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                    Reality-TV
Name: 2006014, dtype: object

(9,)

tconst            tt11826592
titleType          tvEpisode
primaryTitle       The Girls
originalTitle      The Girls
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006015, dtype: object

(9,)

tconst                                     tt11826594
titleType                                       video
primaryTitle      Badass Bandito: Tokin On Cigarettes
originalTitle     Badass Bandito: Tokin On Cigarettes
isAdult                                             0
startYear                                        2019
endYear                                            \N
runtimeMinutes                                      4
genres                                    Music,Short
Name: 2006016, dtype: object

(9,)

tconst              tt11826596
titleType            tvEpisode
primaryTitle      Family Meals
originalTitle     Family Meals
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              21
genres              Reality-TV
Name: 2006017, dtype: object

(9,)

tconst                                        tt11826598
titleType                                      tvEpisode
primaryTitle      Best Little Heaux House in the Complex
originalTitle     Best Little Heaux House in the Complex
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        \N
genres                                            Comedy
Name: 2006018, dtype: object

(9,)

tconst            tt1182659
titleType         tvEpisode
primaryTitle            ERA
originalTitle           ERA
isAdult                   0
startYear              2003
endYear                  \N
runtimeMinutes           \N
genres            Talk-Show
Name: 2006019, dtype: object

(9,)

tconst                     tt11826600
titleType                   tvEpisode
primaryTitle      Heavily Ever After?
originalTitle     Heavily Ever After?
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     42
genres                             \N
Name: 2006020, dtype: object

(9,)

tconst              tt11826602
titleType            tvEpisode
primaryTitle      Meat Sampler
originalTitle     Meat Sampler
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              21
genres              Reality-TV
Name: 2006021, dtype: object

(9,)

tconst                   tt11826604
titleType                 tvEpisode
primaryTitle      Traumfrau gesucht
originalTitle     Traumfrau gesucht
isAdult                           0
startYear                      2012
endYear                          \N
runtimeMinutes                   \N
genres                        Crime
Name: 2006022, dtype: object

(9,)

tconst            tt11826606
titleType          tvEpisode
primaryTitle        The Love
originalTitle       The Love
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006023, dtype: object

(9,)

tconst                                     tt11826608
titleType                                   tvEpisode
primaryTitle      Zhi yi: Wo xin chang dan - Di wu ji
originalTitle     Zhi yi: Wo xin chang dan - Di wu ji
isAdult                                             0
startYear                                        2000
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Drama
Name: 2006024, dtype: object

(9,)

tconst            tt1182660
titleType         tvEpisode
primaryTitle      Education
originalTitle     Education
isAdult                   0
startYear              2003
endYear                  \N
runtimeMinutes           \N
genres            Talk-Show
Name: 2006025, dtype: object

(9,)

tconst            tt11826610
titleType          tvEpisode
primaryTitle         The End
originalTitle        The End
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006026, dtype: object

(9,)

tconst                            tt11826612
titleType                          tvEpisode
primaryTitle      Professionelle Verabredung
originalTitle     Professionelle Verabredung
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                  Drama,Family,Romance
Name: 2006027, dtype: object

(9,)

tconst               tt11826614
titleType             tvEpisode
primaryTitle      The Avon Lady
originalTitle     The Avon Lady
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Crime
Name: 2006028, dtype: object

(9,)

tconst               tt11826616
titleType                 short
primaryTitle               Mine
originalTitle              Mine
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Romance,Short
Name: 2006029, dtype: object

(9,)

tconst                          tt11826618
titleType                            movie
primaryTitle      Buenos Aires al Pacífico
originalTitle     Buenos Aires al Pacífico
isAdult                                  0
startYear                             2018
endYear                                 \N
runtimeMinutes                          98
genres                         Documentary
Name: 2006030, dtype: object

(9,)

tconst              tt1182661
titleType           tvEpisode
primaryTitle      Elder Abuse
originalTitle     Elder Abuse
isAdult                     0
startYear                2003
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2006031, dtype: object

(9,)

tconst                  tt11826620
titleType                tvEpisode
primaryTitle        Tree house TLC
originalTitle       Tree house TLC
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006032, dtype: object

(9,)

tconst                                  tt11826622
titleType                                tvEpisode
primaryTitle      Der Arzt mit den goldenen Händen
originalTitle     Der Arzt mit den goldenen Händen
isAdult                                          0
startYear                                     2012
endYear                                         \N
runtimeMinutes                                  \N
genres                            Crime,Reality-TV
Name: 2006033, dtype: object

(9,)

tconst              tt11826624
titleType                short
primaryTitle      Boy in Bloom
originalTitle     Boy in Bloom
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              18
genres             Drama,Short
Name: 2006034, dtype: object

(9,)

tconst               tt11826626
titleType                 short
primaryTitle              Veins
originalTitle             Veins
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Mystery,Short
Name: 2006035, dtype: object

(9,)

tconst                 tt11826628
titleType               tvEpisode
primaryTitle      Modniy pregovor
originalTitle     Modniy pregovor
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres               Comedy,Drama
Name: 2006036, dtype: object

(9,)

tconst                             tt1182662
titleType                          tvEpisode
primaryTitle      Emergency Contraception II
originalTitle     Emergency Contraception II
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2006037, dtype: object

(9,)

tconst                   tt11826630
titleType                 tvEpisode
primaryTitle      Davay pozhenimsya
originalTitle     Davay pozhenimsya
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                 Comedy,Drama
Name: 2006038, dtype: object

(9,)

tconst                                        tt11826632
titleType                                   tvMiniSeries
primaryTitle      Maximum Danger Top 10 Wingsuit Flights
originalTitle     Maximum Danger Top 10 Wingsuit Flights
isAdult                                                0
startYear                                           2020
endYear                                             2020
runtimeMinutes                                        \N
genres                                            Action
Name: 2006039, dtype: object

(9,)

tconst               tt11826634
titleType             tvEpisode
primaryTitle      Zhit' zdorovo
originalTitle     Zhit' zdorovo
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres             Comedy,Drama
Name: 2006040, dtype: object

(9,)

tconst                      tt11826636
titleType                        short
primaryTitle      Dead, White, or Blue
originalTitle     Dead, White, or Blue
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                  Short,Thriller
Name: 2006041, dtype: object

(9,)

tconst                     tt11826638
titleType                   tvEpisode
primaryTitle      Muzhskoye/zhenskoye
originalTitle     Muzhskoye/zhenskoye
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                   Comedy,Drama
Name: 2006042, dtype: object

(9,)

tconst                        tt1182663
titleType                     tvEpisode
primaryTitle      Environmental Justice
originalTitle     Environmental Justice
isAdult                               0
startYear                          2003
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2006043, dtype: object

(9,)

tconst                    tt11826640
titleType                      short
primaryTitle      The Veil of Solace
originalTitle     The Veil of Solace
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                   Drama,Short
Name: 2006044, dtype: object

(9,)

tconst                        tt11826644
titleType                      tvEpisode
primaryTitle      A spacetastic birthday
originalTitle     A spacetastic birthday
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                  Animation,Family
Name: 2006045, dtype: object

(9,)

tconst                                tt11826646
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006046, dtype: object

(9,)

tconst               tt11826648
titleType             tvEpisode
primaryTitle           Pagdamay
originalTitle          Pagdamay
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006047, dtype: object

(9,)

tconst               tt1182664
titleType            tvEpisode
primaryTitle      Ethnic Media
originalTitle     Ethnic Media
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2006048, dtype: object

(9,)

tconst              tt11826650
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2006049, dtype: object

(9,)

tconst                           tt11826652
titleType                         tvEpisode
primaryTitle      Episode dated 30 May 2017
originalTitle     Episode dated 30 May 2017
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2006050, dtype: object

(9,)

tconst                           tt11826654
titleType                         tvEpisode
primaryTitle      Episode dated 1 June 2017
originalTitle     Episode dated 1 June 2017
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2006051, dtype: object

(9,)

tconst                           tt11826656
titleType                         tvEpisode
primaryTitle      Episode dated 7 June 2017
originalTitle     Episode dated 7 June 2017
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2006052, dtype: object

(9,)

tconst                           tt11826658
titleType                         tvEpisode
primaryTitle      Episode dated 9 June 2017
originalTitle     Episode dated 9 June 2017
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2006053, dtype: object

(9,)

tconst                tt1182665
titleType             tvEpisode
primaryTitle      Eve's Revenge
originalTitle     Eve's Revenge
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2006054, dtype: object

(9,)

tconst                            tt11826660
titleType                          tvEpisode
primaryTitle      Episode dated 12 June 2017
originalTitle     Episode dated 12 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2006055, dtype: object

(9,)

tconst                                  tt11826662
titleType                                    movie
primaryTitle      Het geheim van een goed huwelijk
originalTitle     Het geheim van een goed huwelijk
isAdult                                          0
startYear                                       \N
endYear                                         \N
runtimeMinutes                                  \N
genres                                          \N
Name: 2006056, dtype: object

(9,)

tconst            tt11826664
titleType          videoGame
primaryTitle      Just Dance
originalTitle     Just Dance
isAdult                    0
startYear               2009
endYear                   \N
runtimeMinutes            \N
genres                 Music
Name: 2006057, dtype: object

(9,)

tconst                  tt11826666
titleType                tvEpisode
primaryTitle        Tete's glasses
originalTitle       Tete's glasses
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006058, dtype: object

(9,)

tconst              tt11826668
titleType                short
primaryTitle      The Yoga Off
originalTitle     The Yoga Off
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2006059, dtype: object

(9,)

tconst                  tt1182666
titleType               tvEpisode
primaryTitle      Family Recovery
originalTitle     Family Recovery
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2006060, dtype: object

(9,)

tconst                   tt11826670
titleType                     short
primaryTitle          Sweet Sorghum
originalTitle         Sweet Sorghum
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                    9
genres            Documentary,Short
Name: 2006061, dtype: object

(9,)

tconst                                           tt11826672
titleType                                             video
primaryTitle      Otsuka Mari mi/kaikin! Mashima ro jikappu
originalTitle     Otsuka Mari mi/kaikin! Mashima ro jikappu
isAdult                                                   0
startYear                                              2016
endYear                                                  \N
runtimeMinutes                                           95
genres                                            Adventure
Name: 2006062, dtype: object

(9,)

tconst               tt11826674
titleType                 short
primaryTitle      The Red Paint
originalTitle     The Red Paint
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               16
genres             Horror,Short
Name: 2006063, dtype: object

(9,)

tconst                          tt11826676
titleType                        tvEpisode
primaryTitle      Brasil 2014: 09/07/14 #2
originalTitle     Brasil 2014: 09/07/14 #2
isAdult                                  0
startYear                             2014
endYear                                 \N
runtimeMinutes                          \N
genres                                  \N
Name: 2006064, dtype: object

(9,)

tconst                                                   tt11826678
titleType                                                     video
primaryTitle      A Married Woman with A Meaty Body Is Hungry fo...
originalTitle     A Married Woman with A Meaty Body Is Hungry fo...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                  126
genres                                                        Adult
Name: 2006065, dtype: object

(9,)

tconst                  tt1182667
titleType               tvEpisode
primaryTitle      Guerrilla Girls
originalTitle     Guerrilla Girls
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2006066, dtype: object

(9,)

tconst             tt11826680
titleType               video
primaryTitle        Win River
originalTitle       Win River
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2006067, dtype: object

(9,)

tconst              tt11826682
titleType                short
primaryTitle            Utopia
originalTitle           Utopia
isAdult                      0
startYear                 1997
endYear                     \N
runtimeMinutes              40
genres            Comedy,Short
Name: 2006068, dtype: object

(9,)

tconst                    tt11826684
titleType                  tvEpisode
primaryTitle      A Shot in the Dark
originalTitle     A Shot in the Dark
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    43
genres                       Mystery
Name: 2006069, dtype: object

(9,)

tconst                  tt11826686
titleType                tvEpisode
primaryTitle      Odin's giant egg
originalTitle     Odin's giant egg
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006070, dtype: object

(9,)

tconst                      tt1182668
titleType                   tvEpisode
primaryTitle      Home Rehabilitation
originalTitle     Home Rehabilitation
isAdult                             0
startYear                        2003
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2006071, dtype: object

(9,)

tconst                            tt11826690
titleType                          tvEpisode
primaryTitle      Episode dated 2 April 2013
originalTitle     Episode dated 2 April 2013
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2006072, dtype: object

(9,)

tconst                            tt11826692
titleType                          tvEpisode
primaryTitle      Episode dated 3 April 2013
originalTitle     Episode dated 3 April 2013
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2006073, dtype: object

(9,)

tconst                            tt11826694
titleType                          tvEpisode
primaryTitle      Episode dated 4 April 2013
originalTitle     Episode dated 4 April 2013
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2006074, dtype: object

(9,)

tconst                            tt11826696
titleType                          tvEpisode
primaryTitle      Episode dated 9 April 2013
originalTitle     Episode dated 9 April 2013
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2006075, dtype: object

(9,)

tconst                             tt11826698
titleType                           tvEpisode
primaryTitle      Episode dated 11 April 2013
originalTitle     Episode dated 11 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2006076, dtype: object

(9,)

tconst                             tt1182669
titleType                          tvEpisode
primaryTitle      Iraq/Women in the Military
originalTitle     Iraq/Women in the Military
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2006077, dtype: object

(9,)

tconst                      tt11826700
titleType                    tvEpisode
primaryTitle                      2702
originalTitle                     2702
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006078, dtype: object

(9,)

tconst              tt11826702
titleType                short
primaryTitle         El Tejano
originalTitle        El Tejano
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes               9
genres            Comedy,Short
Name: 2006079, dtype: object

(9,)

tconst                   tt11826706
titleType                 tvEpisode
primaryTitle      The Morning After
originalTitle     The Morning After
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2006080, dtype: object

(9,)

tconst                             tt11826708
titleType                           tvEpisode
primaryTitle      Gloved Masturbation Therapy
originalTitle     Gloved Masturbation Therapy
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2006081, dtype: object

(9,)

tconst                             tt1182670
titleType                          tvEpisode
primaryTitle      LGBT Community and Smoking
originalTitle     LGBT Community and Smoking
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2006082, dtype: object

(9,)

tconst                tt11826710
titleType              tvEpisode
primaryTitle         Épisode 665
originalTitle        Épisode 665
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                29
genres            Crime,Thriller
Name: 2006083, dtype: object

(9,)

tconst                               tt11826712
titleType                             tvEpisode
primaryTitle      Episode dated 30 October 2018
originalTitle     Episode dated 30 October 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2006084, dtype: object

(9,)

tconst                                tt11826714
titleType                              tvEpisode
primaryTitle      Episode dated 13 November 2018
originalTitle     Episode dated 13 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                           Sport,Talk-Show
Name: 2006085, dtype: object

(9,)

tconst                  tt11826716
titleType                tvEpisode
primaryTitle          Fishy Things
originalTitle         Fishy Things
isAdult                          0
startYear                     1981
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006086, dtype: object

(9,)

tconst                                tt11826718
titleType                              tvEpisode
primaryTitle      Episode dated 14 November 2018
originalTitle     Episode dated 14 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                           Sport,Talk-Show
Name: 2006087, dtype: object

(9,)

tconst                      tt1182671
titleType                   tvEpisode
primaryTitle      Latinas and Smoking
originalTitle     Latinas and Smoking
isAdult                             0
startYear                        2003
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2006088, dtype: object

(9,)

tconst                      tt11826720
titleType                    tvEpisode
primaryTitle                      2705
originalTitle                     2705
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006089, dtype: object

(9,)

tconst                                tt11826722
titleType                              tvEpisode
primaryTitle      Episode dated 15 November 2018
originalTitle     Episode dated 15 November 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                           Sport,Talk-Show
Name: 2006090, dtype: object

(9,)

tconst                                tt11826724
titleType                              tvEpisode
primaryTitle      Episode dated 11 December 2018
originalTitle     Episode dated 11 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                           Sport,Talk-Show
Name: 2006091, dtype: object

(9,)

tconst                       tt11826726
titleType                     tvEpisode
primaryTitle      The Disappearing Peas
originalTitle     The Disappearing Peas
isAdult                               0
startYear                          1981
endYear                              \N
runtimeMinutes                       \N
genres                 Animation,Family
Name: 2006092, dtype: object

(9,)

tconst                                tt11826728
titleType                              tvEpisode
primaryTitle      Episode dated 20 December 2018
originalTitle     Episode dated 20 December 2018
isAdult                                        0
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                           Sport,Talk-Show
Name: 2006093, dtype: object

(9,)

tconst                   tt1182672
titleType                tvEpisode
primaryTitle      Low Wage America
originalTitle     Low Wage America
isAdult                          0
startYear                     2003
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2006094, dtype: object

(9,)

tconst            tt11826730
titleType              movie
primaryTitle           Kosto
originalTitle          Kosto
isAdult                    0
startYear               2000
endYear                   \N
runtimeMinutes           136
genres                Action
Name: 2006095, dtype: object

(9,)

tconst                            tt11826732
titleType                          tvEpisode
primaryTitle      Something Beginning with P
originalTitle     Something Beginning with P
isAdult                                    0
startYear                               1981
endYear                                   \N
runtimeMinutes                            \N
genres                      Animation,Family
Name: 2006096, dtype: object

(9,)

tconst               tt11826734
titleType             tvEpisode
primaryTitle             Kidnap
originalTitle            Kidnap
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006097, dtype: object

(9,)

tconst              tt11826736
titleType                short
primaryTitle      Happy Hannah
originalTitle     Happy Hannah
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Drama,Short
Name: 2006098, dtype: object

(9,)

tconst                        tt11826738
titleType                      tvEpisode
primaryTitle      Footprints in the Sand
originalTitle     Footprints in the Sand
isAdult                                0
startYear                           1981
endYear                               \N
runtimeMinutes                        \N
genres                  Animation,Family
Name: 2006099, dtype: object

(9,)

tconst                    tt1182673
titleType                 tvEpisode
primaryTitle      Men Can Stop Rape
originalTitle     Men Can Stop Rape
isAdult                           0
startYear                      2003
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2006100, dtype: object

(9,)

tconst                  tt11826740
titleType                tvEpisode
primaryTitle          Ghoul school
originalTitle         Ghoul school
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006101, dtype: object

(9,)

tconst                     tt11826742
titleType                       movie
primaryTitle      The Crowe's Landing
originalTitle     The Crowe's Landing
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                         Horror
Name: 2006102, dtype: object

(9,)

tconst              tt11826744
titleType         tvMiniSeries
primaryTitle      Gorod nevest
originalTitle     Gorod nevest
isAdult                      0
startYear                 2020
endYear                   2020
runtimeMinutes              \N
genres                 Romance
Name: 2006103, dtype: object

(9,)

tconst                    tt11826746
titleType                  tvEpisode
primaryTitle      Bumps and Twangles
originalTitle     Bumps and Twangles
isAdult                            0
startYear                       1981
endYear                           \N
runtimeMinutes                    \N
genres              Animation,Family
Name: 2006104, dtype: object

(9,)

tconst                 tt11826748
titleType               tvEpisode
primaryTitle         Uppvaknandet
originalTitle        Uppvaknandet
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 18
genres            Sci-Fi,Thriller
Name: 2006105, dtype: object

(9,)

tconst               tt1182674
titleType            tvEpisode
primaryTitle      Microbicides
originalTitle     Microbicides
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2006106, dtype: object

(9,)

tconst                        tt11826750
titleType                      tvEpisode
primaryTitle      Tack för ert samarbete
originalTitle     Tack för ert samarbete
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        16
genres                   Sci-Fi,Thriller
Name: 2006107, dtype: object

(9,)

tconst                      tt11826752
titleType                    tvEpisode
primaryTitle      Krossa allt motstånd
originalTitle     Krossa allt motstånd
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      18
genres                 Sci-Fi,Thriller
Name: 2006108, dtype: object

(9,)

tconst                  tt11826754
titleType                tvEpisode
primaryTitle        Episode #1.913
originalTitle       Episode #1.913
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006109, dtype: object

(9,)

tconst                  tt11826756
titleType                tvEpisode
primaryTitle        Episode #1.914
originalTitle       Episode #1.914
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006110, dtype: object

(9,)

tconst                  tt11826758
titleType                tvEpisode
primaryTitle        Episode #1.916
originalTitle       Episode #1.916
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006111, dtype: object

(9,)

tconst                      tt1182675
titleType                   tvEpisode
primaryTitle      Price of Motherhood
originalTitle     Price of Motherhood
isAdult                             0
startYear                        2003
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2006112, dtype: object

(9,)

tconst            tt11826760
titleType           tvSeries
primaryTitle           Hangs
originalTitle          Hangs
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006113, dtype: object

(9,)

tconst                                tt11826762
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006114, dtype: object

(9,)

tconst                      tt11826764
titleType                    tvEpisode
primaryTitle      Jag vill inte dö här
originalTitle     Jag vill inte dö här
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      17
genres                 Sci-Fi,Thriller
Name: 2006115, dtype: object

(9,)

tconst                  tt11826766
titleType                tvEpisode
primaryTitle      Är vi De Utvalda
originalTitle     Är vi De Utvalda
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  18
genres             Sci-Fi,Thriller
Name: 2006116, dtype: object

(9,)

tconst                  tt11826768
titleType                tvEpisode
primaryTitle        Episode #1.917
originalTitle       Episode #1.917
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006117, dtype: object

(9,)

tconst                               tt1182676
titleType                            tvEpisode
primaryTitle      Republican Women in Congress
originalTitle     Republican Women in Congress
isAdult                                      0
startYear                                 2003
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2006118, dtype: object

(9,)

tconst                  tt11826770
titleType                tvEpisode
primaryTitle      A gigantic world
originalTitle     A gigantic world
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006119, dtype: object

(9,)

tconst                  tt11826772
titleType                tvEpisode
primaryTitle        Episode #1.918
originalTitle       Episode #1.918
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006120, dtype: object

(9,)

tconst                           tt11826774
titleType                         tvEpisode
primaryTitle      Offra 11 för att rädda 1?
originalTitle     Offra 11 för att rädda 1?
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           17
genres                      Sci-Fi,Thriller
Name: 2006121, dtype: object

(9,)

tconst                  tt11826776
titleType                tvEpisode
primaryTitle        Episode #1.919
originalTitle       Episode #1.919
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006122, dtype: object

(9,)

tconst                       tt11826778
titleType                     tvEpisode
primaryTitle      A Shock to the System
originalTitle     A Shock to the System
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       47
genres                Crime,Documentary
Name: 2006123, dtype: object

(9,)

tconst                tt1182677
titleType             tvEpisode
primaryTitle      School Boards
originalTitle     School Boards
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2006124, dtype: object

(9,)

tconst                        tt11826780
titleType                      tvEpisode
primaryTitle      Evil in this Courtroom
originalTitle     Evil in this Courtroom
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        52
genres                 Crime,Documentary
Name: 2006125, dtype: object

(9,)

tconst                  tt11826782
titleType                tvEpisode
primaryTitle        Episode #1.920
originalTitle       Episode #1.920
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006126, dtype: object

(9,)

tconst                  tt11826784
titleType                tvEpisode
primaryTitle        Episode #1.921
originalTitle       Episode #1.921
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006127, dtype: object

(9,)

tconst                       tt11826786
titleType                     tvEpisode
primaryTitle      Failure at All Levels
originalTitle     Failure at All Levels
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       63
genres                Crime,Documentary
Name: 2006128, dtype: object

(9,)

tconst               tt11826788
titleType             tvEpisode
primaryTitle            Pagluha
originalTitle           Pagluha
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006129, dtype: object

(9,)

tconst                tt1182678
titleType             tvEpisode
primaryTitle      Security Moms
originalTitle     Security Moms
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2006130, dtype: object

(9,)

tconst                               tt11826790
titleType                             tvEpisode
primaryTitle      Death Has Got Him by the Hand
originalTitle     Death Has Got Him by the Hand
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               55
genres                        Crime,Documentary
Name: 2006131, dtype: object

(9,)

tconst                             tt11826792
titleType                           tvEpisode
primaryTitle      How To Date Satan And Santa
originalTitle     How To Date Satan And Santa
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                 Comedy
Name: 2006132, dtype: object

(9,)

tconst                                 tt11826794
titleType                               tvEpisode
primaryTitle      Improper Regard or Indifference
originalTitle     Improper Regard or Indifference
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 50
genres                          Crime,Documentary
Name: 2006133, dtype: object

(9,)

tconst                  tt11826796
titleType             tvMiniSeries
primaryTitle      Cyberintimidé(e)
originalTitle     Cyberintimidé(e)
isAdult                          0
startYear                     2014
endYear                       2014
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2006134, dtype: object

(9,)

tconst                      tt11826798
titleType                    tvEpisode
primaryTitle                      2712
originalTitle                     2712
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006135, dtype: object

(9,)

tconst                             tt1182679
titleType                          tvEpisode
primaryTitle      Sen. Lisa Murkowski (R-AK)
originalTitle     Sen. Lisa Murkowski (R-AK)
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2006136, dtype: object

(9,)

tconst                 tt11826800
titleType                   short
primaryTitle      Fight or Flight
originalTitle     Fight or Flight
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                  5
genres                Drama,Short
Name: 2006137, dtype: object

(9,)

tconst                  tt11826802
titleType                tvEpisode
primaryTitle        Episode #1.922
originalTitle       Episode #1.922
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006138, dtype: object

(9,)

tconst                   tt11826804
titleType                 tvEpisode
primaryTitle        Gabriel's Voice
originalTitle       Gabriel's Voice
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   61
genres            Crime,Documentary
Name: 2006139, dtype: object

(9,)

tconst                  tt11826806
titleType                tvEpisode
primaryTitle        Episode #1.923
originalTitle       Episode #1.923
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006140, dtype: object

(9,)

tconst                  tt11826808
titleType                tvEpisode
primaryTitle        Episode #1.924
originalTitle       Episode #1.924
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006141, dtype: object

(9,)

tconst              tt1182680
titleType           tvEpisode
primaryTitle      Senate Moms
originalTitle     Senate Moms
isAdult                     0
startYear                2003
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2006142, dtype: object

(9,)

tconst                  tt11826810
titleType                tvEpisode
primaryTitle          A new friend
originalTitle         A new friend
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006143, dtype: object

(9,)

tconst                  tt11826812
titleType                tvEpisode
primaryTitle        Episode #1.925
originalTitle       Episode #1.925
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006144, dtype: object

(9,)

tconst                    tt11826814
titleType                  tvEpisode
primaryTitle      How To Date Medusa
originalTitle     How To Date Medusa
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                        Comedy
Name: 2006145, dtype: object

(9,)

tconst                  tt11826816
titleType                tvEpisode
primaryTitle        Episode #1.926
originalTitle       Episode #1.926
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006146, dtype: object

(9,)

tconst                  tt11826818
titleType                tvEpisode
primaryTitle        Episode #1.927
originalTitle       Episode #1.927
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006147, dtype: object

(9,)

tconst                       tt1182681
titleType                    tvEpisode
primaryTitle      Teen Substance Abuse
originalTitle     Teen Substance Abuse
isAdult                              0
startYear                         2003
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2006148, dtype: object

(9,)

tconst                  tt11826820
titleType                tvEpisode
primaryTitle        Episode #1.928
originalTitle       Episode #1.928
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006149, dtype: object

(9,)

tconst                  tt11826822
titleType                tvEpisode
primaryTitle        Episode #1.933
originalTitle       Episode #1.933
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006150, dtype: object

(9,)

tconst             tt11826824
titleType               movie
primaryTitle      La Voz Fría
originalTitle     La Voz Fría
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres                 Horror
Name: 2006151, dtype: object

(9,)

tconst                  tt11826826
titleType                tvEpisode
primaryTitle        Episode #1.934
originalTitle       Episode #1.934
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006152, dtype: object

(9,)

tconst                  tt11826828
titleType                tvEpisode
primaryTitle        Episode #1.935
originalTitle       Episode #1.935
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006153, dtype: object

(9,)

tconst                          tt1182682
titleType                       tvEpisode
primaryTitle      Teen Substance Abuse II
originalTitle     Teen Substance Abuse II
isAdult                                 0
startYear                            2003
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2006154, dtype: object

(9,)

tconst                  tt11826830
titleType                tvEpisode
primaryTitle        Episode #1.936
originalTitle       Episode #1.936
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006155, dtype: object

(9,)

tconst                                               tt11826832
titleType                                              tvSeries
primaryTitle      Kioku sosa - Shinjuku higashi-sho jiken fairu
originalTitle     Kioku sosa - Shinjuku higashi-sho jiken fairu
isAdult                                                       0
startYear                                                  2019
endYear                                                    2020
runtimeMinutes                                               \N
genres                                                  Mystery
Name: 2006156, dtype: object

(9,)

tconst                      tt11826834
titleType                    tvEpisode
primaryTitle                      2721
originalTitle                     2721
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006157, dtype: object

(9,)

tconst                  tt11826836
titleType                tvEpisode
primaryTitle        Episode #1.937
originalTitle       Episode #1.937
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006158, dtype: object

(9,)

tconst                  tt11826838
titleType                tvEpisode
primaryTitle        Episode #1.938
originalTitle       Episode #1.938
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006159, dtype: object

(9,)

tconst                               tt1182683
titleType                            tvEpisode
primaryTitle      The Death of Right and Wrong
originalTitle     The Death of Right and Wrong
isAdult                                      0
startYear                                 2003
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2006160, dtype: object

(9,)

tconst            tt11826840
titleType           tvSeries
primaryTitle         Assinie
originalTitle        Assinie
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2006161, dtype: object

(9,)

tconst                  tt11826842
titleType                tvEpisode
primaryTitle        Episode #1.939
originalTitle       Episode #1.939
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006162, dtype: object

(9,)

tconst                              tt11826844
titleType                              tvMovie
primaryTitle      Good Help Is So Hard to Find
originalTitle     Good Help Is So Hard to Find
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                               8
genres                                  Comedy
Name: 2006163, dtype: object

(9,)

tconst               tt11826846
titleType             tvEpisode
primaryTitle          Promotion
originalTitle         Promotion
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006164, dtype: object

(9,)

tconst                      tt11826848
titleType                    tvEpisode
primaryTitle                      2722
originalTitle                     2722
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006165, dtype: object

(9,)

tconst                     tt1182684
titleType                  tvEpisode
primaryTitle      The New Gender Gap
originalTitle     The New Gender Gap
isAdult                            0
startYear                       2003
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2006166, dtype: object

(9,)

tconst                  tt11826850
titleType                tvEpisode
primaryTitle        Episode #1.940
originalTitle       Episode #1.940
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006167, dtype: object

(9,)

tconst                  tt11826852
titleType                tvEpisode
primaryTitle        Episode #1.941
originalTitle       Episode #1.941
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006168, dtype: object

(9,)

tconst            tt11826854
titleType              movie
primaryTitle        The Pack
originalTitle       The Pack
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2006169, dtype: object

(9,)

tconst                  tt11826856
titleType                tvEpisode
primaryTitle        Episode #1.942
originalTitle       Episode #1.942
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006170, dtype: object

(9,)

tconst                  tt11826858
titleType                tvEpisode
primaryTitle        Episode #1.943
originalTitle       Episode #1.943
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006171, dtype: object

(9,)

tconst                  tt1182685
titleType               tvEpisode
primaryTitle      Two Income Trap
originalTitle     Two Income Trap
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2006172, dtype: object

(9,)

tconst                  tt11826860
titleType                tvEpisode
primaryTitle        Episode #1.944
originalTitle       Episode #1.944
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006173, dtype: object

(9,)

tconst                         tt11826862
titleType                           movie
primaryTitle                Gold for Dogs
originalTitle     De l'or pour les chiens
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         99
genres                              Drama
Name: 2006174, dtype: object

(9,)

tconst               tt11826864
titleType                 movie
primaryTitle      Family Jewels
originalTitle     Family Jewels
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2006175, dtype: object

(9,)

tconst                  tt11826866
titleType                tvEpisode
primaryTitle        Episode #1.945
originalTitle       Episode #1.945
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006176, dtype: object

(9,)

tconst             tt11826868
titleType            tvSeries
primaryTitle      Nome de Rua
originalTitle     Nome de Rua
isAdult                     0
startYear                1991
endYear                  1991
runtimeMinutes             \N
genres            Documentary
Name: 2006177, dtype: object

(9,)

tconst                     tt1182686
titleType                  tvEpisode
primaryTitle      Unsung Heroines VI
originalTitle     Unsung Heroines VI
isAdult                            0
startYear                       2003
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2006178, dtype: object

(9,)

tconst                  tt11826870
titleType                tvEpisode
primaryTitle        Episode #1.946
originalTitle       Episode #1.946
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006179, dtype: object

(9,)

tconst                                   tt11826872
titleType                                 tvEpisode
primaryTitle      Trust the Process?/Trade for Tua?
originalTitle     Trust the Process?/Trade for Tua?
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   30
genres                                           \N
Name: 2006180, dtype: object

(9,)

tconst                  tt11826874
titleType                tvEpisode
primaryTitle      Hidden treasures
originalTitle     Hidden treasures
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006181, dtype: object

(9,)

tconst                  tt11826876
titleType                tvEpisode
primaryTitle        Episode #1.947
originalTitle       Episode #1.947
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006182, dtype: object

(9,)

tconst                  tt11826878
titleType                tvEpisode
primaryTitle        Episode #1.948
originalTitle       Episode #1.948
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006183, dtype: object

(9,)

tconst                         tt1182687
titleType                      tvEpisode
primaryTitle      Why I Love Black Women
originalTitle     Why I Love Black Women
isAdult                                0
startYear                           2003
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2006184, dtype: object

(9,)

tconst                  tt11826882
titleType                tvEpisode
primaryTitle        Episode #1.949
originalTitle       Episode #1.949
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006185, dtype: object

(9,)

tconst                                tt11826884
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                      News,Sport,Talk-Show
Name: 2006186, dtype: object

(9,)

tconst                  tt11826886
titleType                tvEpisode
primaryTitle        Episode #1.950
originalTitle       Episode #1.950
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006187, dtype: object

(9,)

tconst                  tt11826888
titleType                tvEpisode
primaryTitle        Episode #1.951
originalTitle       Episode #1.951
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006188, dtype: object

(9,)

tconst                        tt1182688
titleType                     tvEpisode
primaryTitle      Women Business Voters
originalTitle     Women Business Voters
isAdult                               0
startYear                          2003
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2006189, dtype: object

(9,)

tconst                                tt11826890
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006190, dtype: object

(9,)

tconst                  tt11826892
titleType                tvEpisode
primaryTitle        Episode #1.952
originalTitle       Episode #1.952
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006191, dtype: object

(9,)

tconst                      tt11826894
titleType                    tvEpisode
primaryTitle                      2651
originalTitle                     2651
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006192, dtype: object

(9,)

tconst                  tt11826896
titleType                tvEpisode
primaryTitle        Episode #1.953
originalTitle       Episode #1.953
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006193, dtype: object

(9,)

tconst                  tt11826898
titleType                tvEpisode
primaryTitle        Episode #1.954
originalTitle       Episode #1.954
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006194, dtype: object

(9,)

tconst                  tt1182689
titleType               tvEpisode
primaryTitle      Women Governors
originalTitle     Women Governors
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2006195, dtype: object

(9,)

tconst                                tt11826900
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006196, dtype: object

(9,)

tconst                  tt11826902
titleType                tvEpisode
primaryTitle        Episode #1.955
originalTitle       Episode #1.955
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006197, dtype: object

(9,)

tconst                  tt11826904
titleType                tvEpisode
primaryTitle        Episode #1.956
originalTitle       Episode #1.956
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006198, dtype: object

(9,)

tconst                      tt11826906
titleType                    tvEpisode
primaryTitle                      2652
originalTitle                     2652
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006199, dtype: object

(9,)

tconst                  tt11826908
titleType                tvEpisode
primaryTitle        Episode #1.957
originalTitle       Episode #1.957
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006200, dtype: object

(9,)

tconst                        tt1182690
titleType                     tvEpisode
primaryTitle      Women Suicide Bombers
originalTitle     Women Suicide Bombers
isAdult                               0
startYear                          2003
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2006201, dtype: object

(9,)

tconst                  tt11826910
titleType                tvEpisode
primaryTitle        Episode #1.958
originalTitle       Episode #1.958
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006202, dtype: object

(9,)

tconst                  tt11826912
titleType                tvEpisode
primaryTitle        Episode #1.959
originalTitle       Episode #1.959
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006203, dtype: object

(9,)

tconst                                tt11826914
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006204, dtype: object

(9,)

tconst            tt11826916
titleType          tvEpisode
primaryTitle       High Tech
originalTitle      High Tech
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006205, dtype: object

(9,)

tconst                      tt11826918
titleType                    tvEpisode
primaryTitle                      2655
originalTitle                     2655
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006206, dtype: object

(9,)

tconst                  tt1182691
titleType               tvEpisode
primaryTitle      Women and Media
originalTitle     Women and Media
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2006207, dtype: object

(9,)

tconst                                  tt11826920
titleType                                tvEpisode
primaryTitle      O policistih, vojakih in sklecah
originalTitle     O policistih, vojakih in sklecah
isAdult                                          0
startYear                                     2015
endYear                                         \N
runtimeMinutes                                  \N
genres                               Comedy,Family
Name: 2006208, dtype: object

(9,)

tconst                           tt11826922
titleType                         tvEpisode
primaryTitle      Episode dated 10 May 2016
originalTitle     Episode dated 10 May 2016
isAdult                                   0
startYear                              2016
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2006209, dtype: object

(9,)

tconst                  tt11826924
titleType                tvEpisode
primaryTitle          Winter games
originalTitle         Winter games
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006210, dtype: object

(9,)

tconst                                tt11826926
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006211, dtype: object

(9,)

tconst              tt11826928
titleType                short
primaryTitle             Gholü
originalTitle            Gholü
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes               2
genres            Horror,Short
Name: 2006212, dtype: object

(9,)

tconst                          tt1182692
titleType                       tvEpisode
primaryTitle      Women and Retirement II
originalTitle     Women and Retirement II
isAdult                                 0
startYear                            2003
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2006213, dtype: object

(9,)

tconst            tt11826930
titleType              video
primaryTitle       Dandy-703
originalTitle      Dandy-703
isAdult                    1
startYear               2020
endYear                   \N
runtimeMinutes           142
genres                 Adult
Name: 2006214, dtype: object

(9,)

tconst                      tt11826932
titleType                    tvEpisode
primaryTitle                      2657
originalTitle                     2657
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006215, dtype: object

(9,)

tconst                                         tt11826934
titleType                                       tvEpisode
primaryTitle      O karlingu, pleskanju in peni na pretek
originalTitle     O karlingu, pleskanju in peni na pretek
isAdult                                                 0
startYear                                            2015
endYear                                                \N
runtimeMinutes                                         \N
genres                                      Comedy,Family
Name: 2006216, dtype: object

(9,)

tconst                     tt11826936
titleType                    tvSeries
primaryTitle      Plant Power Stories
originalTitle     Plant Power Stories
isAdult                             0
startYear                        2018
endYear                          2020
runtimeMinutes                     \N
genres                          Short
Name: 2006217, dtype: object

(9,)

tconst                                tt11826938
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                 News,Reality-TV,Talk-Show
Name: 2006218, dtype: object

(9,)

tconst                       tt1182693
titleType                    tvEpisode
primaryTitle      Women in Engineering
originalTitle     Women in Engineering
isAdult                              0
startYear                         2003
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2006219, dtype: object

(9,)

tconst                         tt11826940
titleType                        tvSeries
primaryTitle      Great Minds Drink Alike
originalTitle     Great Minds Drink Alike
isAdult                                 0
startYear                            2018
endYear                                \N
runtimeMinutes                         45
genres                          Talk-Show
Name: 2006220, dtype: object

(9,)

tconst                                                   tt11826942
titleType                                                     movie
primaryTitle      Fiverr Presents: Myke Metzger - How to Grow Yo...
originalTitle     Fiverr Presents: Myke Metzger - How to Grow Yo...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   79
genres                                                  Documentary
Name: 2006221, dtype: object

(9,)

tconst                                                   tt11826944
titleType                                                 tvEpisode
primaryTitle      Anschlag in Hanau - Wie kann man den rechten T...
originalTitle     Anschlag in Hanau - Wie kann man den rechten T...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006222, dtype: object

(9,)

tconst                      tt11826946
titleType                    tvEpisode
primaryTitle                      2660
originalTitle                     2660
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006223, dtype: object

(9,)

tconst                                       tt11826948
titleType                                     tvEpisode
primaryTitle      O akrobacijah, rudniku in malih lazeh
originalTitle     O akrobacijah, rudniku in malih lazeh
isAdult                                               0
startYear                                          2015
endYear                                              \N
runtimeMinutes                                       \N
genres                                    Comedy,Family
Name: 2006224, dtype: object

(9,)

tconst                       tt1182694
titleType                    tvEpisode
primaryTitle      Women in Wall Street
originalTitle     Women in Wall Street
isAdult                              0
startYear                         2003
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2006225, dtype: object

(9,)

tconst            tt11826950
titleType          tvEpisode
primaryTitle            Stan
originalTitle           Stan
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006226, dtype: object

(9,)

tconst                       tt11826952
titleType                     tvEpisode
primaryTitle      Coronavirus Latest #5
originalTitle     Coronavirus Latest #5
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                 Documentary,News
Name: 2006227, dtype: object

(9,)

tconst                  tt11826954
titleType                tvEpisode
primaryTitle         The Last Meal
originalTitle        The Last Meal
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Documentary,News
Name: 2006228, dtype: object

(9,)

tconst                      tt11826958
titleType                    tvEpisode
primaryTitle      Kobe Bryant Memorial
originalTitle     Kobe Bryant Memorial
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                              \N
Name: 2006229, dtype: object

(9,)

tconst                 tt1182695
titleType              tvEpisode
primaryTitle      Women's Groups
originalTitle     Women's Groups
isAdult                        0
startYear                   2003
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2006230, dtype: object

(9,)

tconst                                                   tt11826960
titleType                                                 tvEpisode
primaryTitle      O izpadu elektricnega toka, vzpenjaci in deska...
originalTitle     O izpadu elektricnega toka, vzpenjaci in deska...
isAdult                                                           0
startYear                                                      2015
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2006231, dtype: object

(9,)

tconst                            tt11826962
titleType                          tvEpisode
primaryTitle      Trump's Vegetarian Banquet
originalTitle     Trump's Vegetarian Banquet
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                      Documentary,News
Name: 2006232, dtype: object

(9,)

tconst              tt11826964
titleType            tvEpisode
primaryTitle      Hello Sydney
originalTitle     Hello Sydney
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2006233, dtype: object

(9,)

tconst                                  tt11826966
titleType                                tvEpisode
primaryTitle      South Carolina Democratic Debate
originalTitle     South Carolina Democratic Debate
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                            Documentary,News
Name: 2006234, dtype: object

(9,)

tconst                   tt11826968
titleType                 tvEpisode
primaryTitle      Coronavirus Panic
originalTitle     Coronavirus Panic
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres             Documentary,News
Name: 2006235, dtype: object

(9,)

tconst                  tt1182696
titleType               tvEpisode
primaryTitle      Women's History
originalTitle     Women's History
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2006236, dtype: object

(9,)

tconst                    tt11826970
titleType                  tvEpisode
primaryTitle      Coronavirus Latest
originalTitle     Coronavirus Latest
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres              Documentary,News
Name: 2006237, dtype: object

(9,)

tconst                                tt11826972
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                      News,Sport,Talk-Show
Name: 2006238, dtype: object

(9,)

tconst                         tt11826974
titleType                       tvEpisode
primaryTitle      The mistery of the shed
originalTitle     The mistery of the shed
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                   Animation,Family
Name: 2006239, dtype: object

(9,)

tconst             tt11826978
titleType           tvEpisode
primaryTitle      Hotel China
originalTitle     Hotel China
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2006240, dtype: object

(9,)

tconst               tt1182697
titleType            tvEpisode
primaryTitle      Work Modules
originalTitle     Work Modules
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2006241, dtype: object

(9,)

tconst                                tt11826980
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006242, dtype: object

(9,)

tconst                            tt11826982
titleType                          tvEpisode
primaryTitle      The Talking Christmas Tree
originalTitle     The Talking Christmas Tree
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                             9
genres                      Animation,Family
Name: 2006243, dtype: object

(9,)

tconst                                        tt11826984
titleType                                      tvEpisode
primaryTitle      O kurentih, krofih in pustnih norostih
originalTitle     O kurentih, krofih in pustnih norostih
isAdult                                                0
startYear                                           2015
endYear                                               \N
runtimeMinutes                                        \N
genres                                     Comedy,Family
Name: 2006244, dtype: object

(9,)

tconst               tt11826986
titleType                 short
primaryTitle      Fortuneteller
originalTitle     Fortuneteller
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes                3
genres              Drama,Short
Name: 2006245, dtype: object

(9,)

tconst                tt11826988
titleType              tvEpisode
primaryTitle      Playing Hookie
originalTitle     Playing Hookie
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2006246, dtype: object

(9,)

tconst                    tt1182698
titleType                 tvEpisode
primaryTitle         Cynthia George
originalTitle        Cynthia George
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   44
genres            Crime,Documentary
Name: 2006247, dtype: object

(9,)

tconst                                           tt11826990
titleType                                         tvEpisode
primaryTitle      DNA Dysfunction: Are You My Father? Pt. 1
originalTitle     DNA Dysfunction: Are You My Father? Pt. 1
isAdult                                                   0
startYear                                              2019
endYear                                                  \N
runtimeMinutes                                           \N
genres                                            Talk-Show
Name: 2006248, dtype: object

(9,)

tconst                                tt11826992
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006249, dtype: object

(9,)

tconst                                      tt11826994
titleType                                    tvEpisode
primaryTitle      O zlatem kipcu, alpakah in opeklinah
originalTitle     O zlatem kipcu, alpakah in opeklinah
isAdult                                              0
startYear                                         2015
endYear                                             \N
runtimeMinutes                                      \N
genres                                   Comedy,Family
Name: 2006250, dtype: object

(9,)

tconst                  tt11826996
titleType                tvEpisode
primaryTitle      Save the forest!
originalTitle     Save the forest!
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006251, dtype: object

(9,)

tconst                tt11826998
titleType              tvEpisode
primaryTitle      Leo Montero #1
originalTitle     Leo Montero #1
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2006252, dtype: object

(9,)

tconst                    tt1182699
titleType                 tvEpisode
primaryTitle           Erika Sifrit
originalTitle          Erika Sifrit
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   44
genres            Crime,Documentary
Name: 2006253, dtype: object

(9,)

tconst                tt11827000
titleType              tvEpisode
primaryTitle      Leo Montero #2
originalTitle     Leo Montero #2
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2006254, dtype: object

(9,)

tconst                                           tt11827004
titleType                                         tvEpisode
primaryTitle      DNA Dysfunction: Are You My Father? Pt. 2
originalTitle     DNA Dysfunction: Are You My Father? Pt. 2
isAdult                                                   0
startYear                                              2019
endYear                                                  \N
runtimeMinutes                                           \N
genres                                            Talk-Show
Name: 2006255, dtype: object

(9,)

tconst                  tt11827006
titleType                 tvSeries
primaryTitle      Send for Dithers
originalTitle     Send for Dithers
isAdult                          0
startYear                     1966
endYear                       1966
runtimeMinutes                  14
genres                      Family
Name: 2006256, dtype: object

(9,)

tconst                 tt11827008
titleType               tvEpisode
primaryTitle      Lisandro Borges
originalTitle     Lisandro Borges
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2006257, dtype: object

(9,)

tconst                    tt1182700
titleType                 tvEpisode
primaryTitle           Lisa Whedbee
originalTitle          Lisa Whedbee
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   44
genres            Crime,Documentary
Name: 2006258, dtype: object

(9,)

tconst                 tt11827010
titleType               tvEpisode
primaryTitle      Sanyo Gutiérrez
originalTitle     Sanyo Gutiérrez
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2006259, dtype: object

(9,)

tconst                                           tt11827012
titleType                                         tvEpisode
primaryTitle      O vrocem poletju, karikaturi in lubenicah
originalTitle     O vrocem poletju, karikaturi in lubenicah
isAdult                                                   0
startYear                                              2015
endYear                                                  \N
runtimeMinutes                                           \N
genres                                        Comedy,Family
Name: 2006260, dtype: object

(9,)

tconst                 tt11827014
titleType               tvEpisode
primaryTitle          Juan Lebrón
originalTitle         Juan Lebrón
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2006261, dtype: object

(9,)

tconst                                          tt11827016
titleType                                          tvMovie
primaryTitle      Waddup YouTube: An AndrusTV Feature Film
originalTitle     Waddup YouTube: An AndrusTV Feature Film
isAdult                                                  0
startYear                                               \N
endYear                                                 \N
runtimeMinutes                                          \N
genres                                              Comedy
Name: 2006262, dtype: object

(9,)

tconst                    tt11827018
titleType               tvMiniSeries
primaryTitle      American Valkyries
originalTitle     American Valkyries
isAdult                            0
startYear                         \N
endYear                           \N
runtimeMinutes                    \N
genres                         Drama
Name: 2006263, dtype: object

(9,)

tconst                                      tt1182701
titleType                                   tvEpisode
primaryTitle      Ida B. Wells: A Passion for Justice
originalTitle     Ida B. Wells: A Passion for Justice
isAdult                                             0
startYear                                        1989
endYear                                            \N
runtimeMinutes                                     \N
genres                  Biography,Documentary,History
Name: 2006264, dtype: object

(9,)

tconst                                tt11827020
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006265, dtype: object

(9,)

tconst                                tt11827022
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006266, dtype: object

(9,)

tconst                    tt11827024
titleType                  tvEpisode
primaryTitle      DJ Hernán Cattáneo
originalTitle     DJ Hernán Cattáneo
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres               Sport,Talk-Show
Name: 2006267, dtype: object

(9,)

tconst                                tt11827026
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006268, dtype: object

(9,)

tconst                                  tt11827028
titleType                                tvEpisode
primaryTitle      O grafitih, kajaku in domu cebel
originalTitle     O grafitih, kajaku in domu cebel
isAdult                                          0
startYear                                     2015
endYear                                         \N
runtimeMinutes                                  \N
genres                               Comedy,Family
Name: 2006269, dtype: object

(9,)

tconst                                 tt1182702
titleType                              tvEpisode
primaryTitle      Episode dated 12 December 2006
originalTitle     Episode dated 12 December 2006
isAdult                                        0
startYear                                   2006
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2006270, dtype: object

(9,)

tconst                 tt11827030
titleType               tvEpisode
primaryTitle      D Anthony Evans
originalTitle     D Anthony Evans
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres                      Short
Name: 2006271, dtype: object

(9,)

tconst                 tt11827034
titleType               tvEpisode
primaryTitle        Ricky Sarkany
originalTitle       Ricky Sarkany
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2006272, dtype: object

(9,)

tconst                  tt11827036
titleType                tvEpisode
primaryTitle             The dance
originalTitle            The dance
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006273, dtype: object

(9,)

tconst                                                   tt11827038
titleType                                                 tvEpisode
primaryTitle      Die 454. Sendung: Klaus Albrecht Schröder & Me...
originalTitle     Die 454. Sendung: Klaus Albrecht Schröder & Me...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                             Comedy,Talk-Show
Name: 2006274, dtype: object

(9,)

tconst                    tt1182703
titleType                 tvEpisode
primaryTitle      All About Caitlin
originalTitle     All About Caitlin
isAdult                           0
startYear                      2002
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2006275, dtype: object

(9,)

tconst                 tt11827040
titleType                   short
primaryTitle      Old Man Forever
originalTitle     Old Man Forever
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres               Horror,Short
Name: 2006276, dtype: object

(9,)

tconst             tt11827042
titleType           tvEpisode
primaryTitle      Linda Lavin
originalTitle     Linda Lavin
isAdult                     0
startYear                2000
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2006277, dtype: object

(9,)

tconst                 tt11827044
titleType               tvEpisode
primaryTitle        Less Is More?
originalTitle       Less Is More?
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                150
genres            Sport,Talk-Show
Name: 2006278, dtype: object

(9,)

tconst                      tt11827046
titleType                    tvEpisode
primaryTitle      A picnic by the lake
originalTitle     A picnic by the lake
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                Animation,Family
Name: 2006279, dtype: object

(9,)

tconst                    tt1182704
titleType                 tvEpisode
primaryTitle      Duh Truth, Uh-Huh
originalTitle     Duh Truth, Uh-Huh
isAdult                           0
startYear                      2002
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2006280, dtype: object

(9,)

tconst              tt11827050
titleType            tvEpisode
primaryTitle      Back In Town
originalTitle     Back In Town
isAdult                      1
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2006281, dtype: object

(9,)

tconst                                tt11827052
titleType                              tvEpisode
primaryTitle      Episode dated 18 February 2020
originalTitle     Episode dated 18 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006282, dtype: object

(9,)

tconst                     tt11827056
titleType                   tvEpisode
primaryTitle      An Intro to Terroir
originalTitle     An Intro to Terroir
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2006283, dtype: object

(9,)

tconst              tt11827058
titleType         tvMiniSeries
primaryTitle       Mollys Vice
originalTitle      Mollys Vice
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Crime
Name: 2006284, dtype: object

(9,)

tconst                  tt1182705
titleType               tvEpisode
primaryTitle      Playing Caitlin
originalTitle     Playing Caitlin
isAdult                         0
startYear                    2000
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2006285, dtype: object

(9,)

tconst                       tt11827060
titleType                     tvEpisode
primaryTitle      An Intro to Decanting
originalTitle     An Intro to Decanting
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2006286, dtype: object

(9,)

tconst              tt11827062
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2006287, dtype: object

(9,)

tconst                     tt11827064
titleType                   tvEpisode
primaryTitle      An Intro to Tannins
originalTitle     An Intro to Tannins
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2006288, dtype: object

(9,)

tconst                                                   tt11827066
titleType                                                   tvShort
primaryTitle      Shaken and Stirred: A Brief History of James Bond
originalTitle     Shaken and Stirred: A Brief History of James Bond
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   12
genres                                            Documentary,Short
Name: 2006289, dtype: object

(9,)

tconst                      tt11827068
titleType                    tvEpisode
primaryTitle            Episode #42.50
originalTitle           Episode #42.50
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            News,Sport,Talk-Show
Name: 2006290, dtype: object

(9,)

tconst                      tt11827070
titleType                    tvEpisode
primaryTitle      An Intro to Sulfites
originalTitle     An Intro to Sulfites
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2006291, dtype: object

(9,)

tconst                        tt11827072
titleType                          movie
primaryTitle         Fire on the Marmara
originalTitle     Fuego sobre el Marmara
isAdult                                0
startYear                           2011
endYear                               \N
runtimeMinutes                        69
genres                       Documentary
Name: 2006292, dtype: object

(9,)

tconst                   tt11827074
titleType                 tvEpisode
primaryTitle      An Intro to Corks
originalTitle     An Intro to Corks
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                  Documentary
Name: 2006293, dtype: object

(9,)

tconst                                tt11827076
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006294, dtype: object

(9,)

tconst                       tt11827078
titleType                     tvEpisode
primaryTitle      An Intro to Glassware
originalTitle     An Intro to Glassware
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2006295, dtype: object

(9,)

tconst                     tt1182707
titleType                  tvEpisode
primaryTitle      The Angel of Death
originalTitle     The Angel of Death
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres             Crime,Documentary
Name: 2006296, dtype: object

(9,)

tconst                      tt11827080
titleType                    tvEpisode
primaryTitle      An Intro to Frascati
originalTitle     An Intro to Frascati
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2006297, dtype: object

(9,)

tconst                                 tt11827082
titleType                               tvEpisode
primaryTitle      An Intro to Parmigiano Reggiano
originalTitle     An Intro to Parmigiano Reggiano
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                Documentary
Name: 2006298, dtype: object

(9,)

tconst                  tt11827084
titleType                tvEpisode
primaryTitle            Say cheese
originalTitle           Say cheese
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006299, dtype: object

(9,)

tconst                      tt11827086
titleType                    tvEpisode
primaryTitle      An Intro to Albariño
originalTitle     An Intro to Albariño
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2006300, dtype: object

(9,)

tconst                            tt11827088
titleType                          videoGame
primaryTitle      Ourliaxta apo to Parelthon
originalTitle     Ourliaxta apo to Parelthon
isAdult                                    0
startYear                               2005
endYear                                   \N
runtimeMinutes                            \N
genres              Adventure,Horror,Mystery
Name: 2006301, dtype: object

(9,)

tconst              tt1182708
titleType           tvEpisode
primaryTitle      Perfect Fit
originalTitle     Perfect Fit
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2006302, dtype: object

(9,)

tconst                  tt11827090
titleType                tvEpisode
primaryTitle        Episode #1.960
originalTitle       Episode #1.960
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006303, dtype: object

(9,)

tconst                      tt11827092
titleType                        video
primaryTitle      Wolo: Hideaway Blast
originalTitle     Wolo: Hideaway Blast
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       1
genres                           Short
Name: 2006304, dtype: object

(9,)

tconst                                                   tt11827094
titleType                                                 tvEpisode
primaryTitle      14 Years Old, Out of Control, and Desperate fo...
originalTitle     14 Years Old, Out of Control, and Desperate fo...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                   Drama,Reality-TV,Talk-Show
Name: 2006305, dtype: object

(9,)

tconst                  tt11827096
titleType                tvEpisode
primaryTitle        Episode #1.961
originalTitle       Episode #1.961
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006306, dtype: object

(9,)

tconst                                                   tt11827098
titleType                                                 tvEpisode
primaryTitle      Exclusive: Man Accused of Murdering Wife Freed...
originalTitle     Exclusive: Man Accused of Murdering Wife Freed...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                   Drama,Reality-TV,Talk-Show
Name: 2006307, dtype: object

(9,)

tconst                                tt1182709
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2006308, dtype: object

(9,)

tconst                  tt11827100
titleType                tvEpisode
primaryTitle        Episode #1.962
originalTitle       Episode #1.962
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006309, dtype: object

(9,)

tconst                            tt11827102
titleType                           tvSeries
primaryTitle      Africas Greatest Mysteries
originalTitle     Africas Greatest Mysteries
isAdult                                    0
startYear                                 \N
endYear                                   \N
runtimeMinutes                            \N
genres                           Documentary
Name: 2006310, dtype: object

(9,)

tconst                          tt11827104
titleType                            short
primaryTitle      Sveriges Sista Samurajer
originalTitle     Sveriges Sista Samurajer
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          12
genres                        Comedy,Short
Name: 2006311, dtype: object

(9,)

tconst                  tt11827106
titleType                tvEpisode
primaryTitle        Episode #1.963
originalTitle       Episode #1.963
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006312, dtype: object

(9,)

tconst                  tt11827108
titleType                tvEpisode
primaryTitle        Episode #1.964
originalTitle       Episode #1.964
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006313, dtype: object

(9,)

tconst                              tt1182710
titleType                           tvEpisode
primaryTitle      A Living Room for Living In
originalTitle     A Living Room for Living In
isAdult                                     0
startYear                                2008
endYear                                    \N
runtimeMinutes                             \N
genres                             Reality-TV
Name: 2006314, dtype: object

(9,)

tconst                  tt11827110
titleType                tvEpisode
primaryTitle        Episode #1.965
originalTitle       Episode #1.965
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006315, dtype: object

(9,)

tconst                     tt11827112
titleType                   tvEpisode
primaryTitle      Big foot's big itch
originalTitle     Big foot's big itch
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres               Animation,Family
Name: 2006316, dtype: object

(9,)

tconst                  tt11827114
titleType                tvEpisode
primaryTitle        Episode #1.966
originalTitle       Episode #1.966
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2006317, dtype: object

(9,)

tconst                                                   tt11827116
titleType                                                 tvEpisode
primaryTitle      Our Device-Addicted, Violent Teen Controls the...
originalTitle     Our Device-Addicted, Violent Teen Controls the...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                   Drama,Reality-TV,Talk-Show
Name: 2006318, dtype: object

(9,)

tconst                                            tt11827118
titleType                                          tvEpisode
primaryTitle      My Mooching Mom Has 6 Months to Get a Life
originalTitle     My Mooching Mom Has 6 Months to Get a Life
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                            Drama,Reality-TV,Talk-Show
Name: 2006319, dtype: object

(9,)

tconst               tt1182711
titleType            tvEpisode
primaryTitle      Boring Beige
originalTitle     Boring Beige
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2006320, dtype: object

(9,)

tconst                                                   tt11827120
titleType                                                 tvEpisode
primaryTitle      A Blown Inheritance and Threats with a Loaded ...
originalTitle     A Blown Inheritance and Threats with a Loaded ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                   Drama,Reality-TV,Talk-Show
Name: 2006321, dtype: object

(9,)

tconst                                                   tt11827122
titleType                                                 tvEpisode
primaryTitle      Doomsday Couple Found in Hawaii/Family of Miss...
originalTitle     Doomsday Couple Found in Hawaii/Family of Miss...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                   Drama,Reality-TV,Talk-Show
Name: 2006322, dtype: object

(9,)

tconst                                                 tt11827124
titleType                                               tvEpisode
primaryTitle      Real Life Pretty Woman... Not So Pretty Ending!
originalTitle     Real Life Pretty Woman... Not So Pretty Ending!
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                 Drama,Reality-TV,Talk-Show
Name: 2006323, dtype: object

(9,)

tconst                                  tt11827126
titleType                                tvEpisode
primaryTitle      Jessae Rossea First Time Fucking
originalTitle     Jessae Rossea First Time Fucking
isAdult                                          1
startYear                                     2019
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006324, dtype: object

(9,)

tconst                     tt11827128
titleType                       short
primaryTitle      From Heaven Is Cali
originalTitle     From Heaven Is Cali
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                          Short
Name: 2006325, dtype: object

(9,)

tconst                              tt1182712
titleType                           tvEpisode
primaryTitle      Family-Friendly Living Room
originalTitle     Family-Friendly Living Room
isAdult                                     0
startYear                                2007
endYear                                    \N
runtimeMinutes                             \N
genres                             Reality-TV
Name: 2006326, dtype: object

(9,)

tconst                      tt11827130
titleType                     tvSeries
primaryTitle      Wonder Boy and Tiger
originalTitle     Wonder Boy and Tiger
isAdult                              0
startYear                         1967
endYear                           1967
runtimeMinutes                      14
genres                          Family
Name: 2006327, dtype: object

(9,)

tconst            tt11827132
titleType          tvEpisode
primaryTitle      Sami Beigi
originalTitle     Sami Beigi
isAdult                    0
startYear               2014
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2006328, dtype: object

(9,)

tconst            tt11827134
titleType              short
primaryTitle          Lacuna
originalTitle         Lacuna
isAdult                    0
startYear               2018
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2006329, dtype: object

(9,)

tconst                  tt11827136
titleType                tvEpisode
primaryTitle          The blackout
originalTitle         The blackout
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006330, dtype: object

(9,)

tconst                                       tt11827138
titleType                                     tvEpisode
primaryTitle      He's Convinced That I'm in a Sex Tape
originalTitle     He's Convinced That I'm in a Sex Tape
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                               \N
Name: 2006331, dtype: object

(9,)

tconst                            tt1182713
titleType                         tvEpisode
primaryTitle      Old Furniture New Purpose
originalTitle     Old Furniture New Purpose
isAdult                                   0
startYear                              2008
endYear                                  \N
runtimeMinutes                           \N
genres                           Reality-TV
Name: 2006332, dtype: object

(9,)

tconst                                                tt11827140
titleType                                              tvEpisode
primaryTitle      I Caught Him on a Dating App, So I Tracked Him
originalTitle     I Caught Him on a Dating App, So I Tracked Him
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                        \N
Name: 2006333, dtype: object

(9,)

tconst             tt11827142
titleType               movie
primaryTitle      Indomitable
originalTitle     Indomitable
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres              Adventure
Name: 2006334, dtype: object

(9,)

tconst                tt11827144
titleType              tvEpisode
primaryTitle      Wilkos' 2000th
originalTitle     Wilkos' 2000th
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2006335, dtype: object

(9,)

tconst                                                   tt11827146
titleType                                                 tvEpisode
primaryTitle      Why Haven't You Seen Your Daughter Since She W...
originalTitle     Why Haven't You Seen Your Daughter Since She W...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2006336, dtype: object

(9,)

tconst                       tt11827148
titleType                     tvEpisode
primaryTitle      This Story Sickens Me
originalTitle     This Story Sickens Me
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                               \N
Name: 2006337, dtype: object

(9,)

tconst                          tt1182714
titleType                       tvEpisode
primaryTitle      Great Male Vocal Groups
originalTitle     Great Male Vocal Groups
isAdult                                 0
startYear                            1991
endYear                                \N
runtimeMinutes                         \N
genres                  Documentary,Music
Name: 2006338, dtype: object

(9,)

tconst                                     tt11827150
titleType                                   tvEpisode
primaryTitle      Accused of Murdering My Best Friend
originalTitle     Accused of Murdering My Best Friend
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                             \N
Name: 2006339, dtype: object

(9,)

tconst                                tt11827152
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006340, dtype: object

(9,)

tconst                   tt11827154
titleType                 tvEpisode
primaryTitle          Episode #4.13
originalTitle         Episode #4.13
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Comedy,Music,News
Name: 2006341, dtype: object

(9,)

tconst              tt11827158
titleType                short
primaryTitle        Money Shot
originalTitle       Money Shot
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2006342, dtype: object

(9,)

tconst                     tt1182715
titleType                  tvEpisode
primaryTitle      Great Performances
originalTitle     Great Performances
isAdult                            0
startYear                       1991
endYear                           \N
runtimeMinutes                    \N
genres             Documentary,Music
Name: 2006343, dtype: object

(9,)

tconst             tt11827160
titleType           tvEpisode
primaryTitle       Frankreich
originalTitle      Frankreich
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006344, dtype: object

(9,)

tconst                   tt11827162
titleType                     short
primaryTitle           Free Falling
originalTitle          Free Falling
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2006345, dtype: object

(9,)

tconst             tt11827164
titleType               short
primaryTitle      Death Comes
originalTitle     Death Comes
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2006346, dtype: object

(9,)

tconst                       tt11827166
titleType                         movie
primaryTitle                     Aurora
originalTitle                    Aurora
isAdult                               0
startYear                          2022
endYear                              \N
runtimeMinutes                       \N
genres            Drama,Sci-Fi,Thriller
Name: 2006347, dtype: object

(9,)

tconst             tt11827168
titleType           tvEpisode
primaryTitle       Österreich
originalTitle      Österreich
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006348, dtype: object

(9,)

tconst                    tt1182716
titleType                 tvEpisode
primaryTitle              Hard Rock
originalTitle             Hard Rock
isAdult                           0
startYear                      1991
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Music
Name: 2006349, dtype: object

(9,)

tconst             tt11827170
titleType           tvEpisode
primaryTitle           Ungarn
originalTitle          Ungarn
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006350, dtype: object

(9,)

tconst                         tt11827172
titleType                       tvEpisode
primaryTitle      Oregon at Arizona State
originalTitle     Oregon at Arizona State
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                              Sport
Name: 2006351, dtype: object

(9,)

tconst              tt11827174
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2022
endYear                     \N
runtimeMinutes              \N
genres            Drama,Sci-Fi
Name: 2006352, dtype: object

(9,)

tconst             tt11827176
titleType           tvEpisode
primaryTitle        Serbien I
originalTitle       Serbien I
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006353, dtype: object

(9,)

tconst             tt11827178
titleType           tvEpisode
primaryTitle       Serbien II
originalTitle      Serbien II
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006354, dtype: object

(9,)

tconst                    tt1182717
titleType                 tvEpisode
primaryTitle       Legendary Ladies
originalTitle      Legendary Ladies
isAdult                           0
startYear                      1991
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Music
Name: 2006355, dtype: object

(9,)

tconst              tt11827180
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2022
endYear                     \N
runtimeMinutes              \N
genres            Drama,Sci-Fi
Name: 2006356, dtype: object

(9,)

tconst                tt11827182
titleType              tvEpisode
primaryTitle      Nordmazedonien
originalTitle     Nordmazedonien
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2006357, dtype: object

(9,)

tconst            tt11827184
titleType          tvEpisode
primaryTitle       Episode 1
originalTitle      Episode 1
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006358, dtype: object

(9,)

tconst                tt11827186
titleType                  short
primaryTitle      Gflip - Stupid
originalTitle     Gflip - Stupid
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres               Music,Short
Name: 2006359, dtype: object

(9,)

tconst              tt11827188
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2022
endYear                     \N
runtimeMinutes              \N
genres            Drama,Sci-Fi
Name: 2006360, dtype: object

(9,)

tconst                    tt1182718
titleType                 tvEpisode
primaryTitle            Party Songs
originalTitle           Party Songs
isAdult                           0
startYear                      1991
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Music
Name: 2006361, dtype: object

(9,)

tconst              tt11827190
titleType            tvEpisode
primaryTitle      Griechenland
originalTitle     Griechenland
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2006362, dtype: object

(9,)

tconst            tt11827192
titleType          tvEpisode
primaryTitle         25 Band
originalTitle        25 Band
isAdult                    0
startYear               2014
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2006363, dtype: object

(9,)

tconst              tt11827194
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2022
endYear                     \N
runtimeMinutes              \N
genres            Drama,Sci-Fi
Name: 2006364, dtype: object

(9,)

tconst                tt11827196
titleType                  short
primaryTitle       There You Are
originalTitle      There You Are
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Short,Thriller
Name: 2006365, dtype: object

(9,)

tconst              tt11827198
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2022
endYear                     \N
runtimeMinutes              \N
genres            Drama,Sci-Fi
Name: 2006366, dtype: object

(9,)

tconst                       tt1182719
titleType                    tvEpisode
primaryTitle      Rock's Guitar Heroes
originalTitle     Rock's Guitar Heroes
isAdult                              0
startYear                         1991
endYear                             \N
runtimeMinutes                      \N
genres               Documentary,Music
Name: 2006367, dtype: object

(9,)

tconst                 tt11827200
titleType                 tvMovie
primaryTitle      Kate Kapuralica
originalTitle     Kate Kapuralica
isAdult                         0
startYear                    1967
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2006368, dtype: object

(9,)

tconst            tt11827202
titleType          tvEpisode
primaryTitle            1763
originalTitle           1763
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2006369, dtype: object

(9,)

tconst             tt11827204
titleType           tvEpisode
primaryTitle           Lesbos
originalTitle          Lesbos
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006370, dtype: object

(9,)

tconst             tt11827206
titleType           tvEpisode
primaryTitle       Episódio 1
originalTitle      Episódio 1
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006371, dtype: object

(9,)

tconst             tt11827208
titleType           tvEpisode
primaryTitle       Episódio 2
originalTitle      Episódio 2
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006372, dtype: object

(9,)

tconst                    tt1182720
titleType                 tvEpisode
primaryTitle       Sweet Soul Music
originalTitle      Sweet Soul Music
isAdult                           0
startYear                      1991
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Music
Name: 2006373, dtype: object

(9,)

tconst             tt11827210
titleType           tvEpisode
primaryTitle       Episódio 3
originalTitle      Episódio 3
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2006374, dtype: object

(9,)

tconst                   tt11827212
titleType                     short
primaryTitle      Forgive Thy Angel
originalTitle     Forgive Thy Angel
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                  Drama,Short
Name: 2006375, dtype: object

(9,)

tconst              tt11827214
titleType                short
primaryTitle              Clap
originalTitle             Clap
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes               9
genres            Comedy,Short
Name: 2006376, dtype: object

(9,)

tconst                              tt11827216
titleType                            tvEpisode
primaryTitle      Super Model Solos scene #463
originalTitle     Super Model Solos scene #463
isAdult                                      1
startYear                                 2012
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2006377, dtype: object

(9,)

tconst             tt11827218
titleType               short
primaryTitle            Bound
originalTitle           Bound
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2006378, dtype: object

(9,)

tconst                      tt1182721
titleType                   tvEpisode
primaryTitle      The Rockabilly Beat
originalTitle     The Rockabilly Beat
isAdult                             0
startYear                        1991
endYear                            \N
runtimeMinutes                     \N
genres              Documentary,Music
Name: 2006379, dtype: object

(9,)

tconst              tt11827220
titleType                short
primaryTitle            Vlenka
originalTitle           Vlenka
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2006380, dtype: object

(9,)

tconst                            tt11827222
titleType                          tvEpisode
primaryTitle      Episode dated 10 June 2007
originalTitle     Episode dated 10 June 2007
isAdult                                    1
startYear                               2007
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2006381, dtype: object

(9,)

tconst                        tt11827224
titleType                          short
primaryTitle      Don't Go in the Garden
originalTitle     Don't Go in the Garden
isAdult                                0
startYear                             \N
endYear                               \N
runtimeMinutes                        \N
genres                      Horror,Short
Name: 2006382, dtype: object

(9,)

tconst                 tt11827228
titleType                tvSeries
primaryTitle      Perfect Partner
originalTitle     Perfect Partner
isAdult                         0
startYear                    2020
endYear                      2020
runtimeMinutes                 45
genres                    Romance
Name: 2006383, dtype: object

(9,)

tconst                  tt1182722
titleType               tvEpisode
primaryTitle      Making a Splash
originalTitle     Making a Splash
isAdult                         0
startYear                    2005
endYear                        \N
runtimeMinutes                 \N
genres                 Drama,News
Name: 2006384, dtype: object

(9,)

tconst                                                   tt11827236
titleType                                                 tvEpisode
primaryTitle      Frank Stallone and Peter Sherayko Talk 25th An...
originalTitle     Frank Stallone and Peter Sherayko Talk 25th An...
isAdult                                                           0
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006385, dtype: object

(9,)

tconst                                            tt11827238
titleType                                          tvEpisode
primaryTitle      Matt J. Doyle, Kathleen Kinmont Interview.
originalTitle     Matt J. Doyle, Kathleen Kinmont Interview.
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                            Reality-TV
Name: 2006386, dtype: object

(9,)

tconst            tt1182723
titleType         tvEpisode
primaryTitle      Final Cut
originalTitle     Final Cut
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           62
genres                Drama
Name: 2006387, dtype: object

(9,)

tconst                   tt11827240
titleType                 tvEpisode
primaryTitle      Kamran and Hooman
originalTitle     Kamran and Hooman
isAdult                           0
startYear                      2014
endYear                          \N
runtimeMinutes                   \N
genres                   Reality-TV
Name: 2006388, dtype: object

(9,)

tconst                        tt11827242
titleType                      tvEpisode
primaryTitle               Episode #1.22
originalTitle              Episode #1.22
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Adventure,Comedy,Drama
Name: 2006389, dtype: object

(9,)

tconst                    tt11827244
titleType                  tvEpisode
primaryTitle      Dead and Breakfast
originalTitle     Dead and Breakfast
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    42
genres                    Reality-TV
Name: 2006390, dtype: object

(9,)

tconst              tt11827246
titleType                short
primaryTitle         Das Kleid
originalTitle        Das Kleid
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes               7
genres            Family,Short
Name: 2006391, dtype: object

(9,)

tconst            tt11827248
titleType          tvEpisode
primaryTitle         Hunters
originalTitle        Hunters
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2006392, dtype: object

(9,)

tconst              tt1182724
titleType           tvEpisode
primaryTitle       Torn Apart
originalTitle      Torn Apart
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes             43
genres            Documentary
Name: 2006393, dtype: object

(9,)

tconst                   tt11827250
titleType                 tvEpisode
primaryTitle      The Invisible Man
originalTitle     The Invisible Man
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2006394, dtype: object

(9,)

tconst                                   tt11827252
titleType                                     video
primaryTitle      t.A.B.u. Kinpatsu on'na gakuen II
originalTitle     t.A.B.u. Kinpatsu on'na gakuen II
isAdult                                           0
startYear                                      2003
endYear                                          \N
runtimeMinutes                                   \N
genres                                           \N
Name: 2006395, dtype: object

(9,)

tconst                   tt11827254
titleType                     short
primaryTitle              Vote Neil
originalTitle             Vote Neil
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2006396, dtype: object

(9,)

tconst                                      tt11827256
titleType                                        movie
primaryTitle      David Parker Ray: The Toy Box Killer
originalTitle     David Parker Ray: The Toy Box Killer
isAdult                                              0
startYear                                         2019
endYear                                             \N
runtimeMinutes                                      50
genres                                     Documentary
Name: 2006397, dtype: object

(9,)

tconst                         tt11827258
titleType                       tvEpisode
primaryTitle      Harold's Christmas Deed
originalTitle     Harold's Christmas Deed
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                          9
genres                   Animation,Family
Name: 2006398, dtype: object

(9,)

tconst                tt1182725
titleType             tvEpisode
primaryTitle      Episode #3.13
originalTitle     Episode #3.13
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2006399, dtype: object

(9,)

tconst                                                   tt11827260
titleType                                                 tvEpisode
primaryTitle      Every Dem Candidate but Bernie Comes Out Again...
originalTitle     Every Dem Candidate but Bernie Comes Out Again...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2006400, dtype: object

(9,)

tconst                                tt11827262
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006401, dtype: object

(9,)

tconst                                         tt11827264
titleType                                       tvEpisode
primaryTitle      Is 'The Batman' Logo a Deadly Reminder?
originalTitle     Is 'The Batman' Logo a Deadly Reminder?
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                          4
genres                                         News,Short
Name: 2006402, dtype: object

(9,)

tconst                                                   tt11827266
titleType                                                 tvEpisode
primaryTitle      The Beautiful Destruction of Bloomberg by Bernie!
originalTitle     The Beautiful Destruction of Bloomberg by Bernie!
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2006403, dtype: object

(9,)

tconst                             tt1182726
titleType                          tvEpisode
primaryTitle      SuperMADE: Family Makeover
originalTitle     SuperMADE: Family Makeover
isAdult                                    0
startYear                               2007
endYear                                   \N
runtimeMinutes                            \N
genres                            Reality-TV
Name: 2006404, dtype: object

(9,)

tconst                      tt11827272
titleType                        short
primaryTitle       Love's Labours Lost
originalTitle      Love's Labours Lost
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Fantasy
Name: 2006405, dtype: object

(9,)

tconst             tt11827274
titleType           tvEpisode
primaryTitle        Gift Bag!
originalTitle       Gift Bag!
isAdult                     1
startYear                2017
endYear                    \N
runtimeMinutes             \N
genres            Adult,Short
Name: 2006406, dtype: object

(9,)

tconst                        tt11827276
titleType                      tvEpisode
primaryTitle      The Death of Bon Scott
originalTitle     The Death of Bon Scott
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                            Horror
Name: 2006407, dtype: object

(9,)

tconst             tt11827278
titleType           tvEpisode
primaryTitle      Sasy Mankan
originalTitle     Sasy Mankan
isAdult                     0
startYear                2014
endYear                    \N
runtimeMinutes             \N
genres             Reality-TV
Name: 2006408, dtype: object

(9,)

tconst                      tt1182727
titleType                   tvEpisode
primaryTitle        The Glass Ceiling
originalTitle       The Glass Ceiling
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     48
genres            Crime,Drama,Mystery
Name: 2006409, dtype: object

(9,)

tconst                   tt11827280
titleType                     short
primaryTitle           Divine Women
originalTitle          Divine Women
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                    6
genres            Documentary,Short
Name: 2006410, dtype: object

(9,)

tconst                tt11827282
titleType                  movie
primaryTitle      Even in Dreams
originalTitle     Even in Dreams
isAdult                        0
startYear                   2021
endYear                       \N
runtimeMinutes               120
genres                    Family
Name: 2006411, dtype: object

(9,)

tconst                       tt11827284
titleType                     tvEpisode
primaryTitle                The Captive
originalTitle               The Captive
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres            Action,Drama,Thriller
Name: 2006412, dtype: object

(9,)

tconst                       tt11827286
titleType                     tvEpisode
primaryTitle                   The Plan
originalTitle                  The Plan
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres            Action,Drama,Thriller
Name: 2006413, dtype: object

(9,)

tconst                       tt11827288
titleType                     tvEpisode
primaryTitle                  The Price
originalTitle                 The Price
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres            Action,Drama,Thriller
Name: 2006414, dtype: object

(9,)

tconst                    tt1182728
titleType                 tvEpisode
primaryTitle       Brookey Lee West
originalTitle      Brookey Lee West
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   22
genres            Crime,Documentary
Name: 2006415, dtype: object

(9,)

tconst                                tt11827290
titleType                              tvEpisode
primaryTitle      Episode dated 22 February 2020
originalTitle     Episode dated 22 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006416, dtype: object

(9,)

tconst                      tt11827292
titleType                     tvSeries
primaryTitle      Videodrome Dialogues
originalTitle     Videodrome Dialogues
isAdult                              0
startYear                         2017
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2006417, dtype: object

(9,)

tconst                                tt11827294
titleType                              tvEpisode
primaryTitle      Episode dated 23 February 2020
originalTitle     Episode dated 23 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006418, dtype: object

(9,)

tconst                                tt11827296
titleType                              tvEpisode
primaryTitle      Episode dated 24 February 2020
originalTitle     Episode dated 24 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006419, dtype: object

(9,)

tconst                                tt11827298
titleType                              tvEpisode
primaryTitle      Episode dated 25 February 2020
originalTitle     Episode dated 25 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006420, dtype: object

(9,)

tconst                    tt1182729
titleType                 tvEpisode
primaryTitle           Claire Welsh
originalTitle          Claire Welsh
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres            Crime,Documentary
Name: 2006421, dtype: object

(9,)

tconst                                                   tt11827300
titleType                                                 tvEpisode
primaryTitle      Teen Internet Fame... the Good, the Bad, and t...
originalTitle     Teen Internet Fame... the Good, the Bad, and t...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2006422, dtype: object

(9,)

tconst                      tt11827302
titleType                     tvSeries
primaryTitle      Entertainment Hacker
originalTitle     Entertainment Hacker
isAdult                              0
startYear                         2018
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2006423, dtype: object

(9,)

tconst                                                   tt11827304
titleType                                                 tvEpisode
primaryTitle      Are My Best Friends Sleeping with My Man? Test...
originalTitle     Are My Best Friends Sleeping with My Man? Test...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2006424, dtype: object

(9,)

tconst                                                   tt11827306
titleType                                                 tvEpisode
primaryTitle      Read the Results! Did This Man Have a Baby wit...
originalTitle     Read the Results! Did This Man Have a Baby wit...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2006425, dtype: object

(9,)

tconst                             tt11827308
titleType                               video
primaryTitle      Barebacking Fuck Buddies 20
originalTitle     Barebacking Fuck Buddies 20
isAdult                                     1
startYear                                2016
endYear                                    \N
runtimeMinutes                            105
genres                                  Adult
Name: 2006426, dtype: object

(9,)

tconst                    tt1182730
titleType                 tvEpisode
primaryTitle          Daphne Wright
originalTitle         Daphne Wright
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   22
genres            Crime,Documentary
Name: 2006427, dtype: object

(9,)

tconst                             tt11827310
titleType                               short
primaryTitle      Cut Copy - Lights and Music
originalTitle     Cut Copy - Lights and Music
isAdult                                     0
startYear                                2009
endYear                                    \N
runtimeMinutes                             \N
genres                            Music,Short
Name: 2006428, dtype: object

(9,)

tconst                               tt11827312
titleType                             tvEpisode
primaryTitle      The Stubborn Christmas Diesel
originalTitle     The Stubborn Christmas Diesel
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                                9
genres                         Animation,Family
Name: 2006429, dtype: object

(9,)

tconst                                   tt11827314
titleType                                 tvEpisode
primaryTitle      Resúmenes diarios / Últimas horas
originalTitle     Resúmenes diarios / Últimas horas
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres               Adventure,Game-Show,Reality-TV
Name: 2006430, dtype: object

(9,)

tconst                   tt11827318
titleType                 tvEpisode
primaryTitle      Blame it on jorge
originalTitle     Blame it on jorge
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2006431, dtype: object

(9,)

tconst                    tt1182731
titleType                 tvEpisode
primaryTitle           Mary Krueger
originalTitle          Mary Krueger
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   22
genres            Crime,Documentary
Name: 2006432, dtype: object

(9,)

tconst                        tt11827320
titleType                      tvEpisode
primaryTitle      xxxInsanityxxx escapes
originalTitle     xxxInsanityxxx escapes
isAdult                                1
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres                                \N
Name: 2006433, dtype: object

(9,)

tconst                                                   tt11827322
titleType                                                 tvEpisode
primaryTitle      True Crime: Deadly Collision: Jealous Wife Cha...
originalTitle     True Crime: Deadly Collision: Jealous Wife Cha...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006434, dtype: object

(9,)

tconst                           tt11827324
titleType                         tvEpisode
primaryTitle      Christina Carter stuggles
originalTitle     Christina Carter stuggles
isAdult                                   1
startYear                              2008
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2006435, dtype: object

(9,)

tconst                                                 tt11827326
titleType                                               tvEpisode
primaryTitle      Surprisingly Common Accidental Ways You Can Die
originalTitle     Surprisingly Common Accidental Ways You Can Die
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                  Talk-Show
Name: 2006436, dtype: object

(9,)

tconst                                                   tt11827328
titleType                                                 tvEpisode
primaryTitle      Corey Feldman: What is the Truth About the All...
originalTitle     Corey Feldman: What is the Truth About the All...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006437, dtype: object

(9,)

tconst                    tt1182732
titleType                 tvEpisode
primaryTitle           Vicki Monroe
originalTitle          Vicki Monroe
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   22
genres            Crime,Documentary
Name: 2006438, dtype: object

(9,)

tconst                                                   tt11827330
titleType                                                 tvEpisode
primaryTitle      True Crime: What Happened to the Girls on the ...
originalTitle     True Crime: What Happened to the Girls on the ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006439, dtype: object

(9,)

tconst                                                   tt11827332
titleType                                                 tvEpisode
primaryTitle      Flying the Unfriendly Skies: Outrageous Passen...
originalTitle     Flying the Unfriendly Skies: Outrageous Passen...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006440, dtype: object

(9,)

tconst                                                   tt11827334
titleType                                                 tvEpisode
primaryTitle      The Underground Group Fighting Sex Slavery in ...
originalTitle     The Underground Group Fighting Sex Slavery in ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006441, dtype: object

(9,)

tconst                                                   tt11827338
titleType                                                 tvEpisode
primaryTitle      Shocking Tales From People Who Died and Came B...
originalTitle     Shocking Tales From People Who Died and Came B...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006442, dtype: object

(9,)

tconst                 tt1182733
titleType              tvEpisode
primaryTitle      Episode #1.590
originalTitle     Episode #1.590
isAdult                        0
startYear                   1999
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2006443, dtype: object

(9,)

tconst                tt11827340
titleType                  short
primaryTitle      Cane Toad Road
originalTitle     Cane Toad Road
isAdult                        0
startYear                   2012
endYear                       \N
runtimeMinutes                \N
genres                     Short
Name: 2006444, dtype: object

(9,)

tconst                                       tt11827342
titleType                                     tvEpisode
primaryTitle      Week 18 - Vikings vs Saints Wild Card
originalTitle     Week 18 - Vikings vs Saints Wild Card
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                  Sport,Talk-Show
Name: 2006445, dtype: object

(9,)

tconst                           tt11827344
titleType                         tvEpisode
primaryTitle      Pandora and Cherish in MN
originalTitle     Pandora and Cherish in MN
isAdult                                   1
startYear                              2008
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2006446, dtype: object

(9,)

tconst                         tt11827346
titleType                       tvEpisode
primaryTitle      Elaine Hersey in 3 ties
originalTitle     Elaine Hersey in 3 ties
isAdult                                 1
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2006447, dtype: object

(9,)

tconst                 tt1182734
titleType              tvEpisode
primaryTitle      Episode #1.625
originalTitle     Episode #1.625
isAdult                        0
startYear                   1999
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2006448, dtype: object

(9,)

tconst                     tt11827350
titleType                       movie
primaryTitle      Far East Deep South
originalTitle     Far East Deep South
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     76
genres                    Documentary
Name: 2006449, dtype: object

(9,)

tconst                       tt11827352
titleType                      tvSeries
primaryTitle              TheQuartering
originalTitle             TheQuartering
isAdult                               0
startYear                          2017
endYear                              \N
runtimeMinutes                       \N
genres            Comedy,News,Talk-Show
Name: 2006450, dtype: object

(9,)

tconst                   tt11827354
titleType                 tvEpisode
primaryTitle      Pandora in 4 ties
originalTitle     Pandora in 4 ties
isAdult                           1
startYear                      2008
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2006451, dtype: object

(9,)

tconst            tt11827356
titleType          tvEpisode
primaryTitle       Mountains
originalTitle      Mountains
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2006452, dtype: object

(9,)

tconst                      tt11827358
titleType                    tvEpisode
primaryTitle                      2604
originalTitle                     2604
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2006453, dtype: object

(9,)

tconst                 tt1182735
titleType              tvEpisode
primaryTitle      Episode #1.630
originalTitle     Episode #1.630
isAdult                        0
startYear                   1999
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2006454, dtype: object

(9,)

tconst                  tt11827360
titleType                tvEpisode
primaryTitle      Gypsy chair tied
originalTitle     Gypsy chair tied
isAdult                          1
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                       Adult
Name: 2006455, dtype: object

(9,)

tconst                         tt11827362
titleType                           movie
primaryTitle      I Am Raymond Washington
originalTitle     I Am Raymond Washington
isAdult                                 0
startYear                              \N
endYear                                \N
runtimeMinutes                         \N
genres                              Drama
Name: 2006456, dtype: object

(9,)

tconst                          tt11827364
titleType                        tvEpisode
primaryTitle                  Lost & Found
originalTitle                 Lost & Found
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          24
genres            Animation,Family,Fantasy
Name: 2006457, dtype: object

(9,)

tconst                           tt11827366
titleType                         tvEpisode
primaryTitle      Samantha Grace's daydream
originalTitle     Samantha Grace's daydream
isAdult                                   1
startYear                              2008
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2006458, dtype: object

(9,)

tconst                                  tt11827368
titleType                                tvEpisode
primaryTitle      Pandora on the bed and frog tied
originalTitle     Pandora on the bed and frog tied
isAdult                                          1
startYear                                     2008
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006459, dtype: object

(9,)

tconst                 tt1182736
titleType              tvEpisode
primaryTitle      Episode #1.607
originalTitle     Episode #1.607
isAdult                        0
startYear                   1999
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2006460, dtype: object

(9,)

tconst                                  tt11827370
titleType                                tvEpisode
primaryTitle      Christina Carter and the burglar
originalTitle     Christina Carter and the burglar
isAdult                                          1
startYear                                     2008
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006461, dtype: object

(9,)

tconst                                                   tt11827372
titleType                                                 tvEpisode
primaryTitle      Week 20 - Conference Championship - Saints vs ...
originalTitle     Week 20 - Conference Championship - Saints vs ...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                              Sport,Talk-Show
Name: 2006462, dtype: object

(9,)

tconst                          tt11827374
titleType                        tvEpisode
primaryTitle      DFP Academy: Tat for Tit
originalTitle     DFP Academy: Tat for Tit
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2006463, dtype: object

(9,)

tconst                                            tt11827376
titleType                                          tvEpisode
primaryTitle      DFP Academy: A New Sheriff in Town Round 7
originalTitle     DFP Academy: A New Sheriff in Town Round 7
isAdult                                                    1
startYear                                               2018
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                 Adult
Name: 2006464, dtype: object

(9,)

tconst                                                   tt11827378
titleType                                                 tvEpisode
primaryTitle      Bloomberg Is Cancelled & Biden Continues To Rank!
originalTitle     Bloomberg Is Cancelled & Biden Continues To Rank!
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2006465, dtype: object

(9,)

tconst                 tt1182737
titleType              tvEpisode
primaryTitle      Episode #1.623
originalTitle     Episode #1.623
isAdult                        0
startYear                   1999
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2006466, dtype: object

(9,)

tconst                                tt11827380
titleType                              tvEpisode
primaryTitle      Episode dated 11 February 2020
originalTitle     Episode dated 11 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006467, dtype: object

(9,)

tconst                               tt11827382
titleType                             tvEpisode
primaryTitle      DFP Academy: Shirts vs. Skins
originalTitle     DFP Academy: Shirts vs. Skins
isAdult                                       1
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2006468, dtype: object

(9,)

tconst                              tt11827384
titleType                            tvEpisode
primaryTitle      Mesmerism Mayhem: Afterparty
originalTitle     Mesmerism Mayhem: Afterparty
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2006469, dtype: object

(9,)

tconst            tt11827386
titleType          tvEpisode
primaryTitle         No. 729
originalTitle        No. 729
isAdult                    0
startYear               2012
endYear                   \N
runtimeMinutes            \N
genres                 Music
Name: 2006470, dtype: object

(9,)

tconst                              tt11827388
titleType                            tvEpisode
primaryTitle      DFP Academy: The Next Lesson
originalTitle     DFP Academy: The Next Lesson
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2006471, dtype: object

(9,)

tconst                                                 tt1182738
titleType                                              tvEpisode
primaryTitle      I Should Be Carried on the Chariot-Type Thing!
originalTitle     I Should Be Carried on the Chariot-Type Thing!
isAdult                                                        0
startYear                                                   2008
endYear                                                       \N
runtimeMinutes                                                43
genres                            Adventure,Game-Show,Reality-TV
Name: 2006472, dtype: object

(9,)

tconst                          tt11827390
titleType                        tvEpisode
primaryTitle      DFP Academy: Makeup Test
originalTitle     DFP Academy: Makeup Test
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2006473, dtype: object

(9,)

tconst                 tt11827392
titleType               tvEpisode
primaryTitle              Week 13
originalTitle             Week 13
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2006474, dtype: object

(9,)

tconst                                tt11827394
titleType                              tvEpisode
primaryTitle      DFP Academy: Hiring a Henchman
originalTitle     DFP Academy: Hiring a Henchman
isAdult                                        1
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2006475, dtype: object

(9,)

tconst                            tt11827396
titleType                              movie
primaryTitle      Burapa: Bikers of the East
originalTitle     Burapa: Bikers of the East
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            51
genres                           Documentary
Name: 2006476, dtype: object

(9,)

tconst                  tt11827398
titleType                tvEpisode
primaryTitle      2019/20: 15/2/20
originalTitle     2019/20: 15/2/20
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                  News,Sport
Name: 2006477, dtype: object

(9,)

tconst                                  tt1182739
titleType                               tvEpisode
primaryTitle      5 Ways to Get Over Being Dumped
originalTitle     5 Ways to Get Over Being Dumped
isAdult                                         0
startYear                                    2008
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Talk-Show
Name: 2006478, dtype: object

(9,)

tconst                                tt11827400
titleType                                  movie
primaryTitle      My Friend Max: Friends Forever
originalTitle     My Friend Max: Friends Forever
isAdult                                        0
startYear                                   2022
endYear                                       \N
runtimeMinutes                                \N
genres                          Animation,Family
Name: 2006479, dtype: object

(9,)

tconst                                  tt11827402
titleType                                tvEpisode
primaryTitle      DFP Academy: Hiring a Henchman 2
originalTitle     DFP Academy: Hiring a Henchman 2
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006480, dtype: object

(9,)

tconst                 tt11827404
titleType               tvEpisode
primaryTitle      Change of Heart
originalTitle     Change of Heart
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2006481, dtype: object

(9,)

tconst                                             tt11827406
titleType                                           tvEpisode
primaryTitle      Week 19 - Divisional Round - Rams vs Saints
originalTitle     Week 19 - Divisional Round - Rams vs Saints
isAdult                                                     0
startYear                                                2019
endYear                                                    \N
runtimeMinutes                                             \N
genres                                        Sport,Talk-Show
Name: 2006482, dtype: object

(9,)

tconst                                       tt11827408
titleType                                     tvEpisode
primaryTitle      DFP Academy: Sharing with the Teacher
originalTitle     DFP Academy: Sharing with the Teacher
isAdult                                               1
startYear                                          2018
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Adult
Name: 2006483, dtype: object

(9,)

tconst                                                tt1182740
titleType                                             tvEpisode
primaryTitle      Back to Basic Beauty Secrets Finally Revealed
originalTitle     Back to Basic Beauty Secrets Finally Revealed
isAdult                                                       0
startYear                                                  2008
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                Talk-Show
Name: 2006484, dtype: object

(9,)

tconst                tt11827410
titleType                  short
primaryTitle      After the Rain
originalTitle     After the Rain
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                 6
genres               Drama,Short
Name: 2006485, dtype: object

(9,)

tconst                                                 tt11827412
titleType                                               tvEpisode
primaryTitle      Beer Review: Greenbrier Valley Brewing: Mothman
originalTitle     Beer Review: Greenbrier Valley Brewing: Mothman
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                     Comedy
Name: 2006486, dtype: object

(9,)

tconst                                tt11827414
titleType                              tvEpisode
primaryTitle      DFP Academy: Itching for Lunch
originalTitle     DFP Academy: Itching for Lunch
isAdult                                        1
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2006487, dtype: object

(9,)

tconst            tt11827416
titleType          tvEpisode
primaryTitle       Episode 2
originalTitle      Episode 2
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006488, dtype: object

(9,)

tconst                 tt11827418
titleType               tvEpisode
primaryTitle      2019/20: 9/2/20
originalTitle     2019/20: 9/2/20
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                      Sport
Name: 2006489, dtype: object

(9,)

tconst                                    tt1182741
titleType                                 tvEpisode
primaryTitle      New Year's Weight Loss Resolution
originalTitle     New Year's Weight Loss Resolution
isAdult                                           0
startYear                                      2008
endYear                                          \N
runtimeMinutes                                   \N
genres                                    Talk-Show
Name: 2006490, dtype: object

(9,)

tconst                                         tt11827420
titleType                                       tvEpisode
primaryTitle      DFP Academy: You Backed the Wrong Horse
originalTitle     DFP Academy: You Backed the Wrong Horse
isAdult                                                 1
startYear                                            2018
endYear                                                \N
runtimeMinutes                                         \N
genres                                              Adult
Name: 2006491, dtype: object

(9,)

tconst            tt11827422
titleType          tvEpisode
primaryTitle       Episode 3
originalTitle      Episode 3
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006492, dtype: object

(9,)

tconst                                 tt11827424
titleType                               tvEpisode
primaryTitle      DFP Academy: The Queen's Dreams
originalTitle     DFP Academy: The Queen's Dreams
isAdult                                         1
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2006493, dtype: object

(9,)

tconst               tt11827426
titleType             tvEpisode
primaryTitle      Conakry: Emma
originalTitle     Conakry: Emma
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2006494, dtype: object

(9,)

tconst                             tt11827428
titleType                               movie
primaryTitle      Grand Theft Auto: Vice City
originalTitle     Grand Theft Auto: Vice City
isAdult                                     0
startYear                                  \N
endYear                                    \N
runtimeMinutes                            124
genres                                 Action
Name: 2006495, dtype: object

(9,)

tconst                       tt1182742
titleType                    tvEpisode
primaryTitle      What Men Really Want
originalTitle     What Men Really Want
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2006496, dtype: object

(9,)

tconst                                                   tt11827430
titleType                                                 tvEpisode
primaryTitle      Beer Review: Greenbrier Valley Brewing: Wild T...
originalTitle     Beer Review: Greenbrier Valley Brewing: Wild T...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2006497, dtype: object

(9,)

tconst                       tt11827432
titleType                     tvEpisode
primaryTitle      Welcome to Prank Talk
originalTitle     Welcome to Prank Talk
isAdult                               1
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2006498, dtype: object

(9,)

tconst            tt11827434
titleType          tvEpisode
primaryTitle       Episode 4
originalTitle      Episode 4
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006499, dtype: object

(9,)

tconst               tt11827440
titleType                 video
primaryTitle      Raw Roommates
originalTitle     Raw Roommates
isAdult                       1
startYear                  2016
endYear                      \N
runtimeMinutes              104
genres                    Adult
Name: 2006500, dtype: object

(9,)

tconst                                  tt11827442
titleType                                tvEpisode
primaryTitle      DFP Academy: What's That? Part 1
originalTitle     DFP Academy: What's That? Part 1
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006501, dtype: object

(9,)

tconst                    tt11827444
titleType                      short
primaryTitle      The Guy on my Roof
originalTitle     The Guy on my Roof
isAdult                            0
startYear                       2022
endYear                           \N
runtimeMinutes                    \N
genres                  Comedy,Short
Name: 2006502, dtype: object

(9,)

tconst                                                   tt11827446
titleType                                                 tvEpisode
primaryTitle      Beer Review: Greenbrier Valley Brewing: Devil ...
originalTitle     Beer Review: Greenbrier Valley Brewing: Devil ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2006503, dtype: object

(9,)

tconst            tt11827448
titleType          tvEpisode
primaryTitle       Episode 5
originalTitle      Episode 5
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006504, dtype: object

(9,)

tconst                  tt1182744
titleType               tvEpisode
primaryTitle      Fight or Flight
originalTitle     Fight or Flight
isAdult                         0
startYear                    2006
endYear                        \N
runtimeMinutes                 \N
genres                 Reality-TV
Name: 2006505, dtype: object

(9,)

tconst                               tt11827450
titleType                                 short
primaryTitle      Tech N9ne - Nobody Want None.
originalTitle     Tech N9ne - Nobody Want None.
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                    Short
Name: 2006506, dtype: object

(9,)

tconst                       tt11827452
titleType                     tvEpisode
primaryTitle      DFP Academy: Lockdown
originalTitle     DFP Academy: Lockdown
isAdult                               1
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2006507, dtype: object

(9,)

tconst            tt11827454
titleType          tvEpisode
primaryTitle       Episode 6
originalTitle      Episode 6
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006508, dtype: object

(9,)

tconst              tt11827456
titleType            tvEpisode
primaryTitle      Gold Diggers
originalTitle     Gold Diggers
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              42
genres              Reality-TV
Name: 2006509, dtype: object

(9,)

tconst                                tt11827458
titleType                              tvEpisode
primaryTitle                 Conexión Honduras 1
originalTitle                Conexión Honduras 1
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres            Adventure,Game-Show,Reality-TV
Name: 2006510, dtype: object

(9,)

tconst                   tt1182745
titleType                tvEpisode
primaryTitle         Sweet William
originalTitle        Sweet William
isAdult                          0
startYear                     1994
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2006511, dtype: object

(9,)

tconst                                              tt11827460
titleType                                            tvEpisode
primaryTitle      DFP Academy: Where Everybody Knows Your Name
originalTitle     DFP Academy: Where Everybody Knows Your Name
isAdult                                                      1
startYear                                                 2018
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                   Adult
Name: 2006512, dtype: object

(9,)

tconst                              tt11827462
titleType                                video
primaryTitle      Agnes Obel: Camera's Rolling
originalTitle     Agnes Obel: Camera's Rolling
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                               5
genres                             Music,Short
Name: 2006513, dtype: object

(9,)

tconst            tt11827464
titleType          tvEpisode
primaryTitle       Episode 7
originalTitle      Episode 7
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006514, dtype: object

(9,)

tconst                                tt11827466
titleType                              tvEpisode
primaryTitle                   Tierra de nadie 1
originalTitle                  Tierra de nadie 1
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres            Adventure,Game-Show,Reality-TV
Name: 2006515, dtype: object

(9,)

tconst              tt11827468
titleType                short
primaryTitle        Night Hike
originalTitle       Night Hike
isAdult                      0
startYear                 2016
endYear                     \N
runtimeMinutes              15
genres            Horror,Short
Name: 2006516, dtype: object

(9,)

tconst                           tt1182746
titleType                        tvEpisode
primaryTitle      Wogan: Licence To Thrill
originalTitle     Wogan: Licence To Thrill
isAdult                                  0
startYear                             1989
endYear                                 \N
runtimeMinutes                          42
genres                           Talk-Show
Name: 2006517, dtype: object

(9,)

tconst                   tt11827470
titleType                 tvEpisode
primaryTitle      Intimate Surprise
originalTitle     Intimate Surprise
isAdult                           1
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2006518, dtype: object

(9,)

tconst                            tt11827472
titleType                              movie
primaryTitle      Legendary Set Photographer
originalTitle     Legendary Set Photographer
isAdult                                    0
startYear                               2021
endYear                                   \N
runtimeMinutes                            \N
genres                           Documentary
Name: 2006519, dtype: object

(9,)

tconst                                                 tt11827474
titleType                                               tvEpisode
primaryTitle      Remove Amber Heard From L'Oreal Petition Begins
originalTitle     Remove Amber Heard From L'Oreal Petition Begins
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                         \N
Name: 2006520, dtype: object

(9,)

tconst                 tt11827476
titleType                   short
primaryTitle        My Friend Max
originalTitle       My Friend Max
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 29
genres            Animation,Short
Name: 2006521, dtype: object

(9,)

tconst            tt11827478
titleType          tvEpisode
primaryTitle       Episode 8
originalTitle      Episode 8
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006522, dtype: object

(9,)

tconst              tt1182747
titleType           tvEpisode
primaryTitle      Car Trouble
originalTitle     Car Trouble
isAdult                     0
startYear                1995
endYear                    \N
runtimeMinutes             \N
genres                 Family
Name: 2006523, dtype: object

(9,)

tconst               tt11827480
titleType                 short
primaryTitle       Sada AlMadhi
originalTitle      Sada AlMadhi
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres            History,Short
Name: 2006524, dtype: object

(9,)

tconst                       tt11827482
titleType                     tvEpisode
primaryTitle      Uncle Petey in Prison
originalTitle     Uncle Petey in Prison
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                           Comedy
Name: 2006525, dtype: object

(9,)

tconst                          tt11827484
titleType                        tvEpisode
primaryTitle      Mother Knows Best Part 1
originalTitle     Mother Knows Best Part 1
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2006526, dtype: object

(9,)

tconst                  tt11827486
titleType                tvEpisode
primaryTitle      Secret Slaughter
originalTitle     Secret Slaughter
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  42
genres                  Reality-TV
Name: 2006527, dtype: object

(9,)

tconst            tt11827488
titleType          tvEpisode
primaryTitle       Episode 9
originalTitle      Episode 9
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006528, dtype: object

(9,)

tconst             tt1182748
titleType          tvEpisode
primaryTitle      Angekommen
originalTitle     Angekommen
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006529, dtype: object

(9,)

tconst                                  tt11827490
titleType                                tvEpisode
primaryTitle      DFP Academy: What's That? Part 2
originalTitle     DFP Academy: What's That? Part 2
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006530, dtype: object

(9,)

tconst            tt11827492
titleType          tvEpisode
primaryTitle      Demon Mine
originalTitle     Demon Mine
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            42
genres            Reality-TV
Name: 2006531, dtype: object

(9,)

tconst            tt11827494
titleType          tvEpisode
primaryTitle      Episode 10
originalTitle     Episode 10
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006532, dtype: object

(9,)

tconst                          tt11827496
titleType                        tvEpisode
primaryTitle      Mother Knows Best Part 2
originalTitle     Mother Knows Best Part 2
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2006533, dtype: object

(9,)

tconst                                                   tt11827498
titleType                                                 tvEpisode
primaryTitle      STAR WARS toys in TOKYO (feat. one huge Kylo R...
originalTitle     STAR WARS toys in TOKYO (feat. one huge Kylo R...
isAdult                                                           0
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006534, dtype: object

(9,)

tconst            tt1182749
titleType         tvEpisode
primaryTitle      Aphrodite
originalTitle     Aphrodite
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2006535, dtype: object

(9,)

tconst                      tt11827500
titleType                    tvEpisode
primaryTitle      Uncle Petey on Blast
originalTitle     Uncle Petey on Blast
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                          Comedy
Name: 2006536, dtype: object

(9,)

tconst                 tt11827502
titleType               tvEpisode
primaryTitle      Conakry: Mariam
originalTitle     Conakry: Mariam
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                Documentary
Name: 2006537, dtype: object

(9,)

tconst                                  tt11827504
titleType                                tvEpisode
primaryTitle      DFP Academy: What's That? Part 3
originalTitle     DFP Academy: What's That? Part 3
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006538, dtype: object

(9,)

tconst            tt11827506
titleType          tvEpisode
primaryTitle      Episode 11
originalTitle     Episode 11
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006539, dtype: object

(9,)

tconst             tt11827508
titleType               short
primaryTitle           Voyeur
originalTitle          Voyeur
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2006540, dtype: object

(9,)

tconst            tt1182750
titleType         tvEpisode
primaryTitle       Einbruch
originalTitle      Einbruch
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2006541, dtype: object

(9,)

tconst                          tt11827510
titleType                        tvEpisode
primaryTitle      Mother Knows Best Part 3
originalTitle     Mother Knows Best Part 3
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2006542, dtype: object

(9,)

tconst            tt11827512
titleType          tvEpisode
primaryTitle      Episode 12
originalTitle     Episode 12
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006543, dtype: object

(9,)

tconst                                      tt11827514
titleType                                    tvEpisode
primaryTitle      Uncle Petey Condoms & Water Balloons
originalTitle     Uncle Petey Condoms & Water Balloons
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      \N
genres                                          Comedy
Name: 2006544, dtype: object

(9,)

tconst                                                   tt11827516
titleType                                                 tvEpisode
primaryTitle      DFP Academy: Where Everbody Knows Your Name La...
originalTitle     DFP Academy: Where Everbody Knows Your Name La...
isAdult                                                           1
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2006545, dtype: object

(9,)

tconst            tt11827518
titleType          tvEpisode
primaryTitle      Episode 13
originalTitle     Episode 13
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006546, dtype: object

(9,)

tconst               tt1182751
titleType            tvEpisode
primaryTitle      Einbürgerung
originalTitle     Einbürgerung
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2006547, dtype: object

(9,)

tconst            tt11827520
titleType          tvEpisode
primaryTitle      I Dare You
originalTitle     I Dare You
isAdult                    1
startYear               2018
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2006548, dtype: object

(9,)

tconst                 tt11827522
titleType               tvEpisode
primaryTitle       Week 11 - 2019
originalTitle      Week 11 - 2019
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2006549, dtype: object

(9,)

tconst                       tt11827524
titleType                     tvEpisode
primaryTitle      The Latest Technology
originalTitle     The Latest Technology
isAdult                               1
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2006550, dtype: object

(9,)

tconst                tt11827526
titleType                  video
primaryTitle      Mai Kino: Swim
originalTitle     Mai Kino: Swim
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                 3
genres               Music,Short
Name: 2006551, dtype: object

(9,)

tconst                                       tt11827528
titleType                                     tvEpisode
primaryTitle      DFP Academy: Tit for Tat, Ass to Pass
originalTitle     DFP Academy: Tit for Tat, Ass to Pass
isAdult                                               1
startYear                                          2018
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Adult
Name: 2006552, dtype: object

(9,)

tconst              tt1182752
titleType           tvEpisode
primaryTitle      Fight Night
originalTitle     Fight Night
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2006553, dtype: object

(9,)

tconst                         tt11827530
titleType                       tvEpisode
primaryTitle      Tension Headache Relief
originalTitle     Tension Headache Relief
isAdult                                 1
startYear                            2018
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2006554, dtype: object

(9,)

tconst                                            tt11827532
titleType                                          tvEpisode
primaryTitle      Remove Amber Heard Petition Almost 300,000
originalTitle     Remove Amber Heard Petition Almost 300,000
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                    \N
Name: 2006555, dtype: object

(9,)

tconst                tt11827534
titleType              tvEpisode
primaryTitle      Conakry: Aïssa
originalTitle     Conakry: Aïssa
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2006556, dtype: object

(9,)

tconst                                           tt11827536
titleType                                         tvEpisode
primaryTitle      DFP Academy: You Backed the Wrong Horse 2
originalTitle     DFP Academy: You Backed the Wrong Horse 2
isAdult                                                   1
startYear                                              2018
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Adult
Name: 2006557, dtype: object

(9,)

tconst                 tt11827538
titleType               tvEpisode
primaryTitle       Week 14 - 2018
originalTitle      Week 14 - 2018
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2006558, dtype: object

(9,)

tconst             tt1182753
titleType          tvEpisode
primaryTitle      Kaspretien
originalTitle     Kaspretien
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006559, dtype: object

(9,)

tconst               tt11827540
titleType              tvSeries
primaryTitle        Bommalattam
originalTitle       Bommalattam
isAdult                       0
startYear                  2012
endYear                    2016
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006560, dtype: object

(9,)

tconst                       tt11827544
titleType                     tvEpisode
primaryTitle      The First Time: Dacey
originalTitle     The First Time: Dacey
isAdult                               1
startYear                          2018
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2006561, dtype: object

(9,)

tconst               tt11827546
titleType                 short
primaryTitle        Sem Janelas
originalTitle       Sem Janelas
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               12
genres            Mystery,Short
Name: 2006562, dtype: object

(9,)

tconst                                tt11827548
titleType                              tvEpisode
primaryTitle      DFP Academy: Vigilante Justice
originalTitle     DFP Academy: Vigilante Justice
isAdult                                        1
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2006563, dtype: object

(9,)

tconst             tt1182754
titleType          tvEpisode
primaryTitle      Konkurrenz
originalTitle     Konkurrenz
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006564, dtype: object

(9,)

tconst                   tt11827550
titleType                 tvEpisode
primaryTitle      I Double Dare You
originalTitle     I Double Dare You
isAdult                           1
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2006565, dtype: object

(9,)

tconst                tt11827552
titleType                  short
primaryTitle      The Classmates
originalTitle     The Classmates
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                 6
genres              Horror,Short
Name: 2006566, dtype: object

(9,)

tconst                         tt11827554
titleType                       tvEpisode
primaryTitle      DFP Academy: Variations
originalTitle     DFP Academy: Variations
isAdult                                 1
startYear                            2018
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2006567, dtype: object

(9,)

tconst                                    tt11827556
titleType                                  tvEpisode
primaryTitle      DFP Academy: Buck Up Little Camper
originalTitle     DFP Academy: Buck Up Little Camper
isAdult                                            1
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2006568, dtype: object

(9,)

tconst                                           tt11827558
titleType                                             video
primaryTitle      Clint Black & Wynonna Judd: A Bad Goodbye
originalTitle     Clint Black & Wynonna Judd: A Bad Goodbye
isAdult                                                   0
startYear                                              1993
endYear                                                  \N
runtimeMinutes                                           \N
genres                                          Music,Short
Name: 2006569, dtype: object

(9,)

tconst            tt1182755
titleType         tvEpisode
primaryTitle          Liebe
originalTitle         Liebe
isAdult                   0
startYear                \N
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2006570, dtype: object

(9,)

tconst                                       tt11827560
titleType                                     tvEpisode
primaryTitle      Flashback!!! You Can't Be Too Careful
originalTitle     Flashback!!! You Can't Be Too Careful
isAdult                                               1
startYear                                          2018
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Adult
Name: 2006571, dtype: object

(9,)

tconst                                       tt11827562
titleType                                     tvSpecial
primaryTitle      The Guild of Music Supervisors Awards
originalTitle     The Guild of Music Supervisors Awards
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                               \N
Name: 2006572, dtype: object

(9,)

tconst                                        tt11827564
titleType                                      tvEpisode
primaryTitle      FLASHBACK!!! DFP Academy: New Uniforms
originalTitle     FLASHBACK!!! DFP Academy: New Uniforms
isAdult                                                1
startYear                                           2018
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Adult
Name: 2006573, dtype: object

(9,)

tconst                          tt11827566
titleType                        tvEpisode
primaryTitle      Her First Time Here: Ivy
originalTitle     Her First Time Here: Ivy
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2006574, dtype: object

(9,)

tconst                          tt11827568
titleType                        tvEpisode
primaryTitle      Flashback!!! Old Grudges
originalTitle     Flashback!!! Old Grudges
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2006575, dtype: object

(9,)

tconst             tt1182756
titleType          tvEpisode
primaryTitle      Nachtleben
originalTitle     Nachtleben
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006576, dtype: object

(9,)

tconst                   tt11827570
titleType                 tvEpisode
primaryTitle      I Triple Dare You
originalTitle     I Triple Dare You
isAdult                           1
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2006577, dtype: object

(9,)

tconst                            tt11827572
titleType                          tvEpisode
primaryTitle      DFP Academy: Getting Dicey
originalTitle     DFP Academy: Getting Dicey
isAdult                                    1
startYear                               2018
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2006578, dtype: object

(9,)

tconst                           tt11827576
titleType                         tvEpisode
primaryTitle      DFP Academy: Eco-Friendly
originalTitle     DFP Academy: Eco-Friendly
isAdult                                   1
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2006579, dtype: object

(9,)

tconst            tt1182757
titleType         tvEpisode
primaryTitle           Null
originalTitle          Null
isAdult                   0
startYear                \N
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2006580, dtype: object

(9,)

tconst                             tt11827580
titleType                           tvEpisode
primaryTitle      DFP Academy: Party of Three
originalTitle     DFP Academy: Party of Three
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2006581, dtype: object

(9,)

tconst                                                   tt11827582
titleType                                                 tvEpisode
primaryTitle      Cecil Says Wednesday Night EJAC Show Extravaga...
originalTitle     Cecil Says Wednesday Night EJAC Show Extravaga...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2006582, dtype: object

(9,)

tconst                                                 tt11827584
titleType                                               tvEpisode
primaryTitle      DFP Academy: Whatever Happened to Sadie? Part 1
originalTitle     DFP Academy: Whatever Happened to Sadie? Part 1
isAdult                                                         1
startYear                                                    2018
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                      Adult
Name: 2006583, dtype: object

(9,)

tconst                                      tt11827586
titleType                                    tvEpisode
primaryTitle      Sophia Deluxe fucks her son's friend
originalTitle     Sophia Deluxe fucks her son's friend
isAdult                                              1
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      38
genres                                           Adult
Name: 2006584, dtype: object

(9,)

tconst            tt1182758
titleType         tvEpisode
primaryTitle         Streit
originalTitle        Streit
isAdult                   0
startYear                \N
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2006585, dtype: object

(9,)

tconst                                  tt11827590
titleType                                tvEpisode
primaryTitle      DFP Academy: Bullies: The Victim
originalTitle     DFP Academy: Bullies: The Victim
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006586, dtype: object

(9,)

tconst                                    tt11827592
titleType                                  tvEpisode
primaryTitle      DFP Academy: Happy Birthday Bellah
originalTitle     DFP Academy: Happy Birthday Bellah
isAdult                                            1
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2006587, dtype: object

(9,)

tconst             tt11827594
titleType               short
primaryTitle           Viagra
originalTitle          Viagra
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2006588, dtype: object

(9,)

tconst                     tt11827596
titleType                   tvEpisode
primaryTitle      Medical Necessity 2
originalTitle     Medical Necessity 2
isAdult                             1
startYear                        2018
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2006589, dtype: object

(9,)

tconst            tt1182759
titleType         tvEpisode
primaryTitle        Wahltag
originalTitle       Wahltag
isAdult                   0
startYear                \N
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2006590, dtype: object

(9,)

tconst                                   tt11827600
titleType                                 tvEpisode
primaryTitle      DFP Academy: Bullies: The Revenge
originalTitle     DFP Academy: Bullies: The Revenge
isAdult                                           1
startYear                                      2018
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2006591, dtype: object

(9,)

tconst                                                  tt11827602
titleType                                                tvEpisode
primaryTitle      JACK Show Keeps Touching People Part 3 1/30/2020
originalTitle     JACK Show Keeps Touching People Part 3 1/30/2020
isAdult                                                          0
startYear                                                     2020
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                          \N
Name: 2006592, dtype: object

(9,)

tconst                     tt11827604
titleType                       short
primaryTitle      Shotgun Witchdoctor
originalTitle     Shotgun Witchdoctor
isAdult                             0
startYear                        2014
endYear                            \N
runtimeMinutes                     26
genres                   Comedy,Short
Name: 2006593, dtype: object

(9,)

tconst                                                 tt11827606
titleType                                               tvEpisode
primaryTitle      DFP Academy: Whatever Happened to Sadie? Part 2
originalTitle     DFP Academy: Whatever Happened to Sadie? Part 2
isAdult                                                         1
startYear                                                    2018
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                      Adult
Name: 2006594, dtype: object

(9,)

tconst              tt11827608
titleType             tvSeries
primaryTitle       Friend Zone
originalTitle      Friend Zone
isAdult                      0
startYear                 2019
endYear                   2020
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2006595, dtype: object

(9,)

tconst                           tt1182760
titleType                        tvEpisode
primaryTitle                       Honesty
originalTitle                      Honesty
isAdult                                  0
startYear                             2000
endYear                                 \N
runtimeMinutes                          \N
genres            Animation,Family,Fantasy
Name: 2006596, dtype: object

(9,)

tconst                              tt11827610
titleType                            tvEpisode
primaryTitle      DFP Academy: Sister Pranks 1
originalTitle     DFP Academy: Sister Pranks 1
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2006597, dtype: object

(9,)

tconst             tt11827612
titleType               video
primaryTitle       Opeth: Era
originalTitle      Opeth: Era
isAdult                     0
startYear                2017
endYear                    \N
runtimeMinutes              6
genres            Music,Short
Name: 2006598, dtype: object

(9,)

tconst                                                   tt11827614
titleType                                                 tvEpisode
primaryTitle      Sonic The Hedgehog DESTROYS Birds of Prey in i...
originalTitle     Sonic The Hedgehog DESTROYS Birds of Prey in i...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2006599, dtype: object

(9,)

tconst             tt11827616
titleType               short
primaryTitle      Fire Escape
originalTitle     Fire Escape
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes              3
genres            Drama,Short
Name: 2006600, dtype: object

(9,)

tconst                              tt11827618
titleType                            tvEpisode
primaryTitle      Sara and Hoppity Bake a Cake
originalTitle     Sara and Hoppity Bake a Cake
isAdult                                      0
startYear                                 1962
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2006601, dtype: object

(9,)

tconst                                tt1182761
titleType                             tvEpisode
primaryTitle              Battle for Wilderness
originalTitle             Battle for Wilderness
isAdult                                       0
startYear                                  1989
endYear                                      \N
runtimeMinutes                               \N
genres            Biography,Documentary,History
Name: 2006602, dtype: object

(9,)

tconst                          tt11827620
titleType                            short
primaryTitle      Untitled Netflix Project
originalTitle     Untitled Netflix Project
isAdult                                  0
startYear                               \N
endYear                                 \N
runtimeMinutes                          \N
genres                               Short
Name: 2006603, dtype: object

(9,)

tconst                     tt11827622
titleType                   tvEpisode
primaryTitle      Surviving the Storm
originalTitle     Surviving the Storm
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2006604, dtype: object

(9,)

tconst              tt11827624
titleType                short
primaryTitle         You're So
originalTitle        You're So
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2006605, dtype: object

(9,)

tconst            tt11827626
titleType          tvEpisode
primaryTitle       Rob Nagle
originalTitle      Rob Nagle
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2006606, dtype: object

(9,)

tconst                 tt11827628
titleType                   movie
primaryTitle               Memory
originalTitle              Memory
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres            Action,Thriller
Name: 2006607, dtype: object

(9,)

tconst                                          tt1182762
titleType                                       tvEpisode
primaryTitle      The Life and Times of Rosie the Riveter
originalTitle     The Life and Times of Rosie the Riveter
isAdult                                                 0
startYear                                            1988
endYear                                                \N
runtimeMinutes                                         \N
genres                      Biography,Documentary,History
Name: 2006608, dtype: object

(9,)

tconst             tt11827630
titleType               video
primaryTitle         Flatline
originalTitle        Flatline
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              3
genres            Music,Short
Name: 2006609, dtype: object

(9,)

tconst                  tt11827634
titleType                 tvSeries
primaryTitle      La Edad Versátil
originalTitle     La Edad Versátil
isAdult                          0
startYear                     2018
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2006610, dtype: object

(9,)

tconst              tt11827636
titleType                short
primaryTitle      Dream Chaser
originalTitle     Dream Chaser
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Drama,Short
Name: 2006611, dtype: object

(9,)

tconst                         tt11827638
titleType                           short
primaryTitle      Bag Raiders - Lightning
originalTitle     Bag Raiders - Lightning
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                        Music,Short
Name: 2006612, dtype: object

(9,)

tconst                                           tt1182763
titleType                                        tvEpisode
primaryTitle      Bamse og Kylling har fat i hver sin ende
originalTitle     Bamse og Kylling har fat i hver sin ende
isAdult                                                  0
startYear                                             1989
endYear                                                 \N
runtimeMinutes                                          \N
genres                                              Family
Name: 2006613, dtype: object

(9,)

tconst                  tt11827640
titleType                    video
primaryTitle      Santana: Winning
originalTitle     Santana: Winning
isAdult                          0
startYear                     1981
endYear                         \N
runtimeMinutes                  \N
genres                 Music,Short
Name: 2006614, dtype: object

(9,)

tconst                tt1182764
titleType             tvEpisode
primaryTitle      Episode #7.12
originalTitle     Episode #7.12
isAdult                       0
startYear                  1989
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2006615, dtype: object

(9,)

tconst                    tt11827650
titleType                      video
primaryTitle      Santana: E Papa Re
originalTitle     Santana: E Papa Re
isAdult                            0
startYear                       1981
endYear                           \N
runtimeMinutes                    \N
genres                   Music,Short
Name: 2006616, dtype: object

(9,)

tconst              tt11827652
titleType                movie
primaryTitle      Porter's Way
originalTitle     Porter's Way
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2006617, dtype: object

(9,)

tconst                  tt11827654
titleType                tvEpisode
primaryTitle      A Sheppard's Pie
originalTitle     A Sheppard's Pie
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2006618, dtype: object

(9,)

tconst                tt11827656
titleType              tvEpisode
primaryTitle      Cameras of LBZ
originalTitle     Cameras of LBZ
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2006619, dtype: object

(9,)

tconst                                   tt11827658
titleType                                     video
primaryTitle      Santana: I Love You Much Too Much
originalTitle     Santana: I Love You Much Too Much
isAdult                                           0
startYear                                      1981
endYear                                          \N
runtimeMinutes                                   \N
genres                                  Music,Short
Name: 2006620, dtype: object

(9,)

tconst                tt1182765
titleType             tvEpisode
primaryTitle      Episode #7.13
originalTitle     Episode #7.13
isAdult                       0
startYear                  1989
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2006621, dtype: object

(9,)

tconst              tt11827660
titleType                short
primaryTitle             Manic
originalTitle            Manic
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Horror,Short
Name: 2006622, dtype: object

(9,)

tconst                                                   tt11827662
titleType                                                 tvEpisode
primaryTitle      Carr-Greer Family Cemetery - Albemarle County, VA
originalTitle     Carr-Greer Family Cemetery - Albemarle County, VA
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    2
genres                                                  Documentary
Name: 2006623, dtype: object

(9,)

tconst                  tt11827664
titleType                    video
primaryTitle      Santana: Changes
originalTitle     Santana: Changes
isAdult                          0
startYear                     1981
endYear                         \N
runtimeMinutes                  \N
genres                 Music,Short
Name: 2006624, dtype: object

(9,)

tconst                                                   tt11827666
titleType                                                 tvEpisode
primaryTitle      Another Top 10 Cringiest Celebrity Interview W...
originalTitle     Another Top 10 Cringiest Celebrity Interview W...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                             Comedy,Talk-Show
Name: 2006625, dtype: object

(9,)

tconst                                     tt1182766
titleType                                  tvEpisode
primaryTitle      Bytte bytte roller - bytte om igen
originalTitle     Bytte bytte roller - bytte om igen
isAdult                                            0
startYear                                       1989
endYear                                           \N
runtimeMinutes                                    \N
genres                                        Family
Name: 2006626, dtype: object

(9,)

tconst                                   tt11827670
titleType                                 tvEpisode
primaryTitle      We Cryogenically Freeze Ourselves
originalTitle     We Cryogenically Freeze Ourselves
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   11
genres                            Comedy,Reality-TV
Name: 2006627, dtype: object

(9,)

tconst                                                   tt11827672
titleType                                                     short
primaryTitle      Midnight Juggernauts: Into the Galaxy (Version 1)
originalTitle     Midnight Juggernauts: Into the Galaxy (Version 1)
isAdult                                                           0
startYear                                                      2007
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                  Music,Short
Name: 2006628, dtype: object

(9,)

tconst                                                   tt11827674
titleType                                                 tvEpisode
primaryTitle      Next Gen Xbox Leak, Kojima on Phantom Pains, S...
originalTitle     Next Gen Xbox Leak, Kojima on Phantom Pains, S...
isAdult                                                           0
startYear                                                      2013
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2006629, dtype: object

(9,)

tconst                                             tt11827676
titleType                                           tvEpisode
primaryTitle      Top 10 Most Powerful Characters in Yu-Gi-Oh
originalTitle     Top 10 Most Powerful Characters in Yu-Gi-Oh
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             \N
genres                                       Comedy,Talk-Show
Name: 2006630, dtype: object

(9,)

tconst                    tt11827678
titleType                      video
primaryTitle      Santana: Searchin'
originalTitle     Santana: Searchin'
isAdult                            0
startYear                       1981
endYear                           \N
runtimeMinutes                    \N
genres                   Music,Short
Name: 2006631, dtype: object

(9,)

tconst                      tt1182767
titleType                   tvEpisode
primaryTitle      Anschnallen, bitte!
originalTitle     Anschnallen, bitte!
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2006632, dtype: object

(9,)

tconst                                           tt11827680
titleType                                             video
primaryTitle      Tim & Phil's Special Half Baked Christmas
originalTitle     Tim & Phil's Special Half Baked Christmas
isAdult                                                   0
startYear                                              2019
endYear                                                  \N
runtimeMinutes                                            9
genres                              Documentary,Short,Sport
Name: 2006633, dtype: object

(9,)

tconst                 tt11827682
titleType               tvEpisode
primaryTitle               FOX 45
originalTitle              FOX 45
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2006634, dtype: object

(9,)

tconst                                     tt11827684
titleType                                       video
primaryTitle      The Young of Certain Animals: Theme
originalTitle     The Young of Certain Animals: Theme
isAdult                                             0
startYear                                        2019
endYear                                            \N
runtimeMinutes                                      4
genres                                    Music,Short
Name: 2006635, dtype: object

(9,)

tconst            tt11827686
titleType          tvEpisode
primaryTitle      Endangered
originalTitle     Endangered
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Animation
Name: 2006636, dtype: object

(9,)

tconst                 tt11827688
titleType               tvEpisode
primaryTitle      Death By Manson
originalTitle     Death By Manson
isAdult                         0
startYear                    2021
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2006637, dtype: object

(9,)

tconst                      tt1182768
titleType                   tvEpisode
primaryTitle      Böse Überraschungen
originalTitle     Böse Überraschungen
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2006638, dtype: object

(9,)

tconst               tt11827690
titleType             tvEpisode
primaryTitle      Extended Stay
originalTitle     Extended Stay
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2006639, dtype: object

(9,)

tconst             tt11827692
titleType           tvEpisode
primaryTitle      CL Franklin
originalTitle     CL Franklin
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             \N
genres                  Crime
Name: 2006640, dtype: object

(9,)

tconst                        tt11827694
titleType                       tvSeries
primaryTitle                       Train
originalTitle                      Train
isAdult                                0
startYear                           2020
endYear                             2020
runtimeMinutes                        60
genres            Fantasy,Mystery,Sci-Fi
Name: 2006641, dtype: object

(9,)

tconst                                           tt11827696
titleType                                         tvEpisode
primaryTitle      What Happens When A Youtube Channel Dies?
originalTitle     What Happens When A Youtube Channel Dies?
isAdult                                                   0
startYear                                              2020
endYear                                                  \N
runtimeMinutes                                           19
genres                                    Comedy,Reality-TV
Name: 2006642, dtype: object

(9,)

tconst                   tt11827698
titleType                 tvEpisode
primaryTitle          Bad Bad Beans
originalTitle         Bad Bad Beans
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   13
genres            Comedy,Reality-TV
Name: 2006643, dtype: object

(9,)

tconst               tt1182769
titleType            tvEpisode
primaryTitle      Die Invasion
originalTitle     Die Invasion
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2006644, dtype: object

(9,)

tconst                                                   tt11827700
titleType                                                 tvEpisode
primaryTitle      PAX East, Blizzard Card Game, CD Projekt Red, ...
originalTitle     PAX East, Blizzard Card Game, CD Projekt Red, ...
isAdult                                                           0
startYear                                                      2013
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2006645, dtype: object

(9,)

tconst                                             tt11827702
titleType                                           tvEpisode
primaryTitle      Learning the Ancient Art of Chinese Archery
originalTitle     Learning the Ancient Art of Chinese Archery
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             24
genres                                      Comedy,Reality-TV
Name: 2006646, dtype: object

(9,)

tconst                tt11827704
titleType                  video
primaryTitle      Opeth: Harvest
originalTitle     Opeth: Harvest
isAdult                        0
startYear                   2001
endYear                       \N
runtimeMinutes                 6
genres               Music,Short
Name: 2006647, dtype: object

(9,)

tconst                                                   tt11827706
titleType                                                 tvEpisode
primaryTitle      Double Fine's Broken Age, XCOM goes mobile, Bo...
originalTitle     Double Fine's Broken Age, XCOM goes mobile, Bo...
isAdult                                                           0
startYear                                                      2013
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2006648, dtype: object

(9,)

tconst                                    tt11827708
titleType                                  tvEpisode
primaryTitle      Arrow 4x9 REACTION!! "Dark Waters"
originalTitle     Arrow 4x9 REACTION!! "Dark Waters"
isAdult                                            0
startYear                                       2015
endYear                                           \N
runtimeMinutes                                    27
genres                                     Talk-Show
Name: 2006649, dtype: object

(9,)

tconst                          tt1182770
titleType                       tvEpisode
primaryTitle      Die leichtesten Übungen
originalTitle     Die leichtesten Übungen
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                              Drama
Name: 2006650, dtype: object

(9,)

tconst                                            tt11827710
titleType                                          tvEpisode
primaryTitle      Arrow Viewer Questions Week 9 DISCUSSION!!
originalTitle     Arrow Viewer Questions Week 9 DISCUSSION!!
isAdult                                                    0
startYear                                               2016
endYear                                                   \N
runtimeMinutes                                            30
genres                                             Talk-Show
Name: 2006651, dtype: object

(9,)

tconst                                     tt11827712
titleType                                   tvEpisode
primaryTitle      Arrow 4x10 REACTION!! "Blood Debts"
originalTitle     Arrow 4x10 REACTION!! "Blood Debts"
isAdult                                             0
startYear                                        2016
endYear                                            \N
runtimeMinutes                                     25
genres                                      Talk-Show
Name: 2006652, dtype: object

(9,)

tconst                                                   tt11827714
titleType                                                 tvEpisode
primaryTitle      We Hired a Real Hypnotherapist to Analyze Our ...
originalTitle     We Hired a Real Hypnotherapist to Analyze Our ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   26
genres                                            Comedy,Reality-TV
Name: 2006653, dtype: object

(9,)

tconst                               tt11827716
titleType                             tvEpisode
primaryTitle      We Turned Our Bodies Into Art
originalTitle     We Turned Our Bodies Into Art
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               16
genres                        Comedy,Reality-TV
Name: 2006654, dtype: object

(9,)

tconst              tt11827718
titleType                short
primaryTitle      The Profiler
originalTitle     The Profiler
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes               5
genres            Sci-Fi,Short
Name: 2006655, dtype: object

(9,)

tconst            tt1182771
titleType         tvEpisode
primaryTitle           Föhn
originalTitle          Föhn
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2006656, dtype: object

(9,)

tconst                              tt11827720
titleType                                video
primaryTitle      Opeth: The Grand Conjuration
originalTitle     Opeth: The Grand Conjuration
isAdult                                      0
startYear                                 2005
endYear                                     \N
runtimeMinutes                               5
genres                             Music,Short
Name: 2006657, dtype: object

(9,)

tconst               tt11827722
titleType             tvEpisode
primaryTitle      Play Anything
originalTitle     Play Anything
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes                3
genres                   Comedy
Name: 2006658, dtype: object

(9,)

tconst                                           tt11827724
titleType                                         tvEpisode
primaryTitle      Mark and Ethan Learn About The Human Body
originalTitle     Mark and Ethan Learn About The Human Body
isAdult                                                   0
startYear                                              2020
endYear                                                  \N
runtimeMinutes                                           20
genres                                    Comedy,Reality-TV
Name: 2006659, dtype: object

(9,)

tconst                                                   tt11827728
titleType                                                 tvEpisode
primaryTitle      Square Enix CEO resigns, New Assassin's Creed ...
originalTitle     Square Enix CEO resigns, New Assassin's Creed ...
isAdult                                                           0
startYear                                                      2013
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2006660, dtype: object

(9,)

tconst                        tt1182772
titleType                     tvEpisode
primaryTitle      Lügen und Geheimnisse
originalTitle     Lügen und Geheimnisse
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres                            Drama
Name: 2006661, dtype: object

(9,)

tconst                  tt11827730
titleType                tvEpisode
primaryTitle      Special Delivery
originalTitle     Special Delivery
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                   3
genres                      Comedy
Name: 2006662, dtype: object

(9,)

tconst                   tt11827732
titleType                 tvEpisode
primaryTitle      ASMR You Serious?
originalTitle     ASMR You Serious?
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                    4
genres                       Comedy
Name: 2006663, dtype: object

(9,)

tconst                       tt11827734
titleType                     tvEpisode
primaryTitle             Michelle Obama
originalTitle            Michelle Obama
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       40
genres            Biography,Documentary
Name: 2006664, dtype: object

(9,)

tconst                            tt11827736
titleType                          tvEpisode
primaryTitle      Desperately Seeking Signal
originalTitle     Desperately Seeking Signal
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                             4
genres                                Comedy
Name: 2006665, dtype: object

(9,)

tconst                       tt11827738
titleType                     tvEpisode
primaryTitle             Jackie Kennedy
originalTitle            Jackie Kennedy
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       40
genres            Biography,Documentary
Name: 2006666, dtype: object

(9,)

tconst                   tt1182773
titleType                tvEpisode
primaryTitle      Ruhm und Glauben
originalTitle     Ruhm und Glauben
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2006667, dtype: object

(9,)

tconst            tt11827740
titleType          tvEpisode
primaryTitle          Timber
originalTitle         Timber
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes             4
genres                Comedy
Name: 2006668, dtype: object

(9,)

tconst             tt11827742
titleType           tvEpisode
primaryTitle      Block Party
originalTitle     Block Party
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              3
genres                 Comedy
Name: 2006669, dtype: object

(9,)

tconst                                                   tt11827744
titleType                                                 tvEpisode
primaryTitle      Battlefield 4, Metal Gear Solid V, and Mojang ...
originalTitle     Battlefield 4, Metal Gear Solid V, and Mojang ...
isAdult                                                           0
startYear                                                      2013
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2006670, dtype: object

(9,)

tconst             tt11827746
titleType           tvEpisode
primaryTitle      G.O.T. Cup?
originalTitle     G.O.T. Cup?
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              3
genres                 Comedy
Name: 2006671, dtype: object

(9,)

tconst                        tt11827748
titleType                          video
primaryTitle      Opeth: Porcelain Heart
originalTitle     Opeth: Porcelain Heart
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                         5
genres                       Music,Short
Name: 2006672, dtype: object

(9,)

tconst              tt1182774
titleType           tvEpisode
primaryTitle      Spurensuche
originalTitle     Spurensuche
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2006673, dtype: object

(9,)

tconst             tt11827750
titleType           tvEpisode
primaryTitle      All Is Calm
originalTitle     All Is Calm
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              2
genres                 Comedy
Name: 2006674, dtype: object

(9,)

tconst                         tt11827754
titleType                       tvEpisode
primaryTitle      Oregon State at Arizona
originalTitle     Oregon State at Arizona
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                              Sport
Name: 2006675, dtype: object

(9,)

tconst                            tt11827756
titleType                          tvEpisode
primaryTitle      The Return of Nick Fuentes
originalTitle     The Return of Nick Fuentes
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                        News,Talk-Show
Name: 2006676, dtype: object

(9,)

tconst                    tt11827758
titleType                  tvEpisode
primaryTitle      The Shame of Water
originalTitle     The Shame of Water
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    25
genres             Comedy,Reality-TV
Name: 2006677, dtype: object

(9,)

tconst                      tt1182775
titleType                   tvEpisode
primaryTitle      Stunde der Wahrheit
originalTitle     Stunde der Wahrheit
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2006678, dtype: object

(9,)

tconst                                                   tt11827760
titleType                                                 tvEpisode
primaryTitle      No David Hayter in Metal Gear, Journey Sweeps ...
originalTitle     No David Hayter in Metal Gear, Journey Sweeps ...
isAdult                                                           0
startYear                                                      2013
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2006679, dtype: object

(9,)

tconst                     tt11827762
titleType                       movie
primaryTitle      Infiltrator project
originalTitle     Infiltrator project
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres                  Action,Sci-Fi
Name: 2006680, dtype: object

(9,)

tconst                                     tt11827764
titleType                                       short
primaryTitle      Architecture in Helsinki: That Beep
originalTitle     Architecture in Helsinki: That Beep
isAdult                                             0
startYear                                        2009
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Short
Name: 2006681, dtype: object

(9,)

tconst                 tt11827766
titleType               tvEpisode
primaryTitle      Milfs Grab Back
originalTitle     Milfs Grab Back
isAdult                         1
startYear                    2018
endYear                        \N
runtimeMinutes                 32
genres                      Adult
Name: 2006682, dtype: object

(9,)

tconst               tt11827768
titleType                 video
primaryTitle      Opeth: Burden
originalTitle     Opeth: Burden
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes                4
genres              Music,Short
Name: 2006683, dtype: object

(9,)

tconst                             tt1182776
titleType                          tvEpisode
primaryTitle      Suche Vater, biete Tochter
originalTitle     Suche Vater, biete Tochter
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            \N
genres                                 Drama
Name: 2006684, dtype: object

(9,)

tconst                  tt11827772
titleType                tvEpisode
primaryTitle      Introducing Azul
originalTitle     Introducing Azul
isAdult                          1
startYear                     2020
endYear                         \N
runtimeMinutes                  34
genres                       Adult
Name: 2006685, dtype: object

(9,)

tconst                                                   tt11827774
titleType                                                 tvEpisode
primaryTitle      Diablo 3 Auction House regret, Activision's ne...
originalTitle     Diablo 3 Auction House regret, Activision's ne...
isAdult                                                           0
startYear                                                      2013
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2006686, dtype: object

(9,)

tconst            tt11827776
titleType          tvEpisode
primaryTitle      Date Night
originalTitle     Date Night
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006687, dtype: object

(9,)

tconst                  tt11827778
titleType                 tvSeries
primaryTitle      Picture the Word
originalTitle     Picture the Word
isAdult                          0
startYear                     1965
endYear                       1966
runtimeMinutes                  15
genres                      Family
Name: 2006688, dtype: object

(9,)

tconst                   tt1182777
titleType                tvEpisode
primaryTitle      Verborgene Väter
originalTitle     Verborgene Väter
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2006689, dtype: object

(9,)

tconst                                                   tt11827780
titleType                                                 tvEpisode
primaryTitle      Tisha Campbell, Julie Warner, Dave Foley, Beth...
originalTitle     Tisha Campbell, Julie Warner, Dave Foley, Beth...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                         Game-Show,Reality-TV
Name: 2006690, dtype: object

(9,)

tconst                      tt11827782
titleType                        short
primaryTitle                     Tarde
originalTitle                    Tarde
isAdult                              0
startYear                         2016
endYear                             \N
runtimeMinutes                      10
genres            Comedy,Romance,Short
Name: 2006691, dtype: object

(9,)

tconst                                 tt11827784
titleType                                   short
primaryTitle      The Best Orchestra in the World
originalTitle     The Best Orchestra in the World
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 14
genres                       Comedy,Fantasy,Short
Name: 2006692, dtype: object

(9,)

tconst                        tt11827786
titleType                          video
primaryTitle      Opeth: Universal Truth
originalTitle     Opeth: Universal Truth
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                         8
genres                       Music,Short
Name: 2006693, dtype: object

(9,)

tconst                                tt11827788
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2006694, dtype: object

(9,)

tconst                                 tt1182778
titleType                              tvEpisode
primaryTitle      Verräter in den eigenen Reihen
originalTitle     Verräter in den eigenen Reihen
isAdult                                        0
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres                                     Drama
Name: 2006695, dtype: object

(9,)

tconst                tt11827790
titleType                  movie
primaryTitle      Beyond Ed Buck
originalTitle     Beyond Ed Buck
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2006696, dtype: object

(9,)

tconst             tt11827792
titleType               short
primaryTitle         I'm Fine
originalTitle        I'm Fine
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2006697, dtype: object

(9,)

tconst                tt11827794
titleType              tvEpisode
primaryTitle      Boats & Clocks
originalTitle     Boats & Clocks
isAdult                        0
startYear                   1965
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2006698, dtype: object

(9,)

tconst                               tt11827796
titleType                                 short
primaryTitle      Harmful or Fatal If Swallowed
originalTitle     Harmful or Fatal If Swallowed
isAdult                                       0
startYear                                  1982
endYear                                      \N
runtimeMinutes                               12
genres                                    Short
Name: 2006699, dtype: object

(9,)

tconst              tt11827798
titleType            tvEpisode
primaryTitle      Cats & Baths
originalTitle     Cats & Baths
isAdult                      0
startYear                 1965
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2006700, dtype: object

(9,)

tconst              tt1182779
titleType           tvEpisode
primaryTitle      Verzeih mir
originalTitle     Verzeih mir
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2006701, dtype: object

(9,)

tconst                          tt11827800
titleType                            video
primaryTitle      Miya Folick: Stock Image
originalTitle     Miya Folick: Stock Image
isAdult                                  0
startYear                             2018
endYear                                 \N
runtimeMinutes                           4
genres                         Music,Short
Name: 2006702, dtype: object

(9,)

tconst              tt11827802
titleType         tvMiniSeries
primaryTitle          COVID-19
originalTitle         COVID-19
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2006703, dtype: object

(9,)

tconst                      tt11827804
titleType                    tvEpisode
primaryTitle      Flying & the Seaside
originalTitle     Flying & the Seaside
isAdult                              0
startYear                         1965
endYear                             \N
runtimeMinutes                      \N
genres                          Family
Name: 2006704, dtype: object

(9,)

tconst                      tt11827806
titleType                        movie
primaryTitle      So Much Love to Give
originalTitle             Corazón loco
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                     108
genres                          Comedy
Name: 2006705, dtype: object

(9,)

tconst                tt11827808
titleType              tvEpisode
primaryTitle      Beds & Writing
originalTitle     Beds & Writing
isAdult                        0
startYear                   1965
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2006706, dtype: object

(9,)

tconst                     tt1182780
titleType                  tvEpisode
primaryTitle      Väter und Verräter
originalTitle     Väter und Verräter
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres                         Drama
Name: 2006707, dtype: object

(9,)

tconst                               tt11827810
titleType                                 short
primaryTitle      Ghost Legends: Bonnie & Clyde
originalTitle     Ghost Legends: Bonnie & Clyde
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               43
genres                            Mystery,Short
Name: 2006708, dtype: object

(9,)

tconst              tt11827812
titleType            tvEpisode
primaryTitle      Ponds & Pets
originalTitle     Ponds & Pets
isAdult                      0
startYear                 1965
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2006709, dtype: object

(9,)

tconst                tt11827814
titleType              tvEpisode
primaryTitle      Dogs & Schools
originalTitle     Dogs & Schools
isAdult                        0
startYear                   1965
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2006710, dtype: object

(9,)

tconst               tt11827816
titleType             tvEpisode
primaryTitle       Episode #1.1
originalTitle      Episode #1.1
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006711, dtype: object

(9,)

tconst               tt11827818
titleType             tvEpisode
primaryTitle      Shoes & Shops
originalTitle     Shoes & Shops
isAdult                       0
startYear                  1965
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2006712, dtype: object

(9,)

tconst                   tt1182781
titleType                tvEpisode
primaryTitle      Wahlkampf-Folgen
originalTitle     Wahlkampf-Folgen
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2006713, dtype: object

(9,)

tconst               tt11827820
titleType             tvEpisode
primaryTitle      Episode #3.35
originalTitle     Episode #3.35
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2006714, dtype: object

(9,)

tconst               tt11827822
titleType             tvEpisode
primaryTitle       Episode #1.2
originalTitle      Episode #1.2
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006715, dtype: object

(9,)

tconst               tt11827824
titleType             tvEpisode
primaryTitle       Episode #1.3
originalTitle      Episode #1.3
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006716, dtype: object

(9,)

tconst               tt11827826
titleType             tvEpisode
primaryTitle      Horses & Fish
originalTitle     Horses & Fish
isAdult                       0
startYear                  1965
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2006717, dtype: object

(9,)

tconst               tt11827828
titleType             tvEpisode
primaryTitle       Episode #1.4
originalTitle      Episode #1.4
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006718, dtype: object

(9,)

tconst                          tt1182782
titleType                       tvEpisode
primaryTitle      Ärger liegt in der Luft
originalTitle     Ärger liegt in der Luft
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                              Drama
Name: 2006719, dtype: object

(9,)

tconst                    tt11827830
titleType                  tvEpisode
primaryTitle      Uniforms & Schools
originalTitle     Uniforms & Schools
isAdult                            0
startYear                       1965
endYear                           \N
runtimeMinutes                    \N
genres                        Family
Name: 2006720, dtype: object

(9,)

tconst               tt11827832
titleType             tvEpisode
primaryTitle       Episode #1.5
originalTitle      Episode #1.5
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006721, dtype: object

(9,)

tconst               tt11827834
titleType             tvEpisode
primaryTitle       Episode #1.6
originalTitle      Episode #1.6
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006722, dtype: object

(9,)

tconst               tt11827838
titleType             tvEpisode
primaryTitle       Episode #1.7
originalTitle      Episode #1.7
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006723, dtype: object

(9,)

tconst               tt1182783
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2006724, dtype: object

(9,)

tconst              tt11827840
titleType            tvEpisode
primaryTitle      Birds & Toys
originalTitle     Birds & Toys
isAdult                      0
startYear                 1965
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2006725, dtype: object

(9,)

tconst               tt11827842
titleType             tvEpisode
primaryTitle       Episode #1.8
originalTitle      Episode #1.8
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006726, dtype: object

(9,)

tconst               tt11827844
titleType             tvEpisode
primaryTitle       Episode #1.9
originalTitle      Episode #1.9
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006727, dtype: object

(9,)

tconst                                             tt11827846
titleType                                               short
primaryTitle      Matthew McNeal: All for Nothing/Be Yourself
originalTitle     Matthew McNeal: All for Nothing/Be Yourself
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             \N
genres                                            Music,Short
Name: 2006728, dtype: object

(9,)

tconst              tt11827848
titleType                short
primaryTitle      Take It Back
originalTitle     Take It Back
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres             Drama,Short
Name: 2006729, dtype: object

(9,)

tconst               tt1182784
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2006730, dtype: object

(9,)

tconst              tt11827850
titleType            tvEpisode
primaryTitle      Hair & Bread
originalTitle     Hair & Bread
isAdult                      0
startYear                 1965
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2006731, dtype: object

(9,)

tconst               tt11827852
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006732, dtype: object

(9,)

tconst               tt11827854
titleType             tvEpisode
primaryTitle      Episode #3.34
originalTitle     Episode #3.34
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2006733, dtype: object

(9,)

tconst             tt11827856
titleType           tvEpisode
primaryTitle      Dogs & Hats
originalTitle     Dogs & Hats
isAdult                     0
startYear                1965
endYear                    \N
runtimeMinutes             \N
genres                 Family
Name: 2006734, dtype: object

(9,)

tconst                  tt11827858
titleType                tvEpisode
primaryTitle      Cutlery & Chairs
originalTitle     Cutlery & Chairs
isAdult                          0
startYear                     1965
endYear                         \N
runtimeMinutes                  \N
genres                      Family
Name: 2006735, dtype: object

(9,)

tconst                             tt1182785
titleType                          tvEpisode
primaryTitle      Das Wolgadelta in Russland
originalTitle     Das Wolgadelta in Russland
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            \N
genres                           Documentary
Name: 2006736, dtype: object

(9,)

tconst               tt11827860
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006737, dtype: object

(9,)

tconst               tt11827864
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006738, dtype: object

(9,)

tconst               tt11827866
titleType                 short
primaryTitle      Lizzo McGuire
originalTitle     Lizzo McGuire
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes                4
genres             Comedy,Short
Name: 2006739, dtype: object

(9,)

tconst               tt11827868
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006740, dtype: object

(9,)

tconst                                    tt1182786
titleType                                 tvEpisode
primaryTitle      Der Nationalpark Biebrza in Polen
originalTitle     Der Nationalpark Biebrza in Polen
isAdult                                           0
startYear                                      2002
endYear                                          \N
runtimeMinutes                                   \N
genres                                  Documentary
Name: 2006741, dtype: object

(9,)

tconst               tt11827870
titleType             tvEpisode
primaryTitle      Babies & Zoos
originalTitle     Babies & Zoos
isAdult                       0
startYear                  1965
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2006742, dtype: object

(9,)

tconst               tt11827872
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006743, dtype: object

(9,)

tconst               tt11827874
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006744, dtype: object

(9,)

tconst               tt11827876
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  1965
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2006745, dtype: object

(9,)

tconst               tt11827878
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006746, dtype: object

(9,)

tconst                                       tt1182787
titleType                                    tvEpisode
primaryTitle      Der Nationalpark Kiskunság in Ungarn
originalTitle     Der Nationalpark Kiskunság in Ungarn
isAdult                                              0
startYear                                         2001
endYear                                             \N
runtimeMinutes                                      \N
genres                                     Documentary
Name: 2006747, dtype: object

(9,)

tconst               tt11827880
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006748, dtype: object

(9,)

tconst                  tt11827882
titleType                tvEpisode
primaryTitle      Funfair & Pillow
originalTitle     Funfair & Pillow
isAdult                          0
startYear                     1965
endYear                         \N
runtimeMinutes                  \N
genres                      Family
Name: 2006749, dtype: object

(9,)

tconst               tt11827884
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006750, dtype: object

(9,)

tconst                                tt11827886
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006751, dtype: object

(9,)

tconst               tt11827888
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006752, dtype: object

(9,)

tconst                                       tt1182788
titleType                                    tvEpisode
primaryTitle      Der Nationalpark Kornati in Kroatien
originalTitle     Der Nationalpark Kornati in Kroatien
isAdult                                              0
startYear                                         2003
endYear                                             \N
runtimeMinutes                                      51
genres                                     Documentary
Name: 2006753, dtype: object

(9,)

tconst                     tt11827890
titleType                   tvEpisode
primaryTitle      Trains & the Circus
originalTitle     Trains & the Circus
isAdult                             0
startYear                        1965
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2006754, dtype: object

(9,)

tconst               tt11827892
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006755, dtype: object

(9,)

tconst                     tt11827894
titleType                   tvEpisode
primaryTitle      Battleships & Water
originalTitle     Battleships & Water
isAdult                             0
startYear                        1965
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2006756, dtype: object

(9,)

tconst                tt11827896
titleType                  short
primaryTitle       The Good Maid
originalTitle      The Good Maid
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            Short,Thriller
Name: 2006757, dtype: object

(9,)

tconst              tt11827898
titleType            tvEpisode
primaryTitle      Wool & Farms
originalTitle     Wool & Farms
isAdult                      0
startYear                 1966
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2006758, dtype: object

(9,)

tconst                                      tt1182789
titleType                                   tvEpisode
primaryTitle      Der Nationalpark Pirin in Bulgarien
originalTitle     Der Nationalpark Pirin in Bulgarien
isAdult                                             0
startYear                                        2005
endYear                                            \N
runtimeMinutes                                     \N
genres                                    Documentary
Name: 2006759, dtype: object

(9,)

tconst            tt11827900
titleType           tvSeries
primaryTitle          Vlenka
originalTitle         Vlenka
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2006760, dtype: object

(9,)

tconst                   tt11827902
titleType                 tvEpisode
primaryTitle      Singing & Weapons
originalTitle     Singing & Weapons
isAdult                           0
startYear                      1966
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2006761, dtype: object

(9,)

tconst              tt11827904
titleType                short
primaryTitle      Lil Gardener
originalTitle     Lil Gardener
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              10
genres             Music,Short
Name: 2006762, dtype: object

(9,)

tconst                     tt11827906
titleType                   tvEpisode
primaryTitle      The Year & Crockery
originalTitle     The Year & Crockery
isAdult                             0
startYear                        1966
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2006763, dtype: object

(9,)

tconst               tt11827908
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006764, dtype: object

(9,)

tconst                                       tt1182790
titleType                                    tvEpisode
primaryTitle      Der Nationalpark Vilsandi in Estland
originalTitle     Der Nationalpark Vilsandi in Estland
isAdult                                              0
startYear                                         2001
endYear                                             \N
runtimeMinutes                                      \N
genres                                     Documentary
Name: 2006765, dtype: object

(9,)

tconst               tt11827910
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006766, dtype: object

(9,)

tconst               tt11827912
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006767, dtype: object

(9,)

tconst               tt11827914
titleType             tvEpisode
primaryTitle      Trees & Sport
originalTitle     Trees & Sport
isAdult                       0
startYear                  1966
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2006768, dtype: object

(9,)

tconst               tt11827916
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006769, dtype: object

(9,)

tconst              tt11827918
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2006770, dtype: object

(9,)

tconst                                        tt1182791
titleType                                     tvEpisode
primaryTitle      Der Nationalpark Zemaitija in Litauen
originalTitle     Der Nationalpark Zemaitija in Litauen
isAdult                                               0
startYear                                          2004
endYear                                              \N
runtimeMinutes                                       \N
genres                                      Documentary
Name: 2006771, dtype: object

(9,)

tconst                  tt11827920
titleType                tvEpisode
primaryTitle      Sweets & Flavour
originalTitle     Sweets & Flavour
isAdult                          0
startYear                     1966
endYear                         \N
runtimeMinutes                  \N
genres                      Family
Name: 2006772, dtype: object

(9,)

tconst               tt11827922
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006773, dtype: object

(9,)

tconst               tt11827924
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006774, dtype: object

(9,)

tconst                          tt11827926
titleType                        tvEpisode
primaryTitle                  Fateful Date
originalTitle                 Fateful Date
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres            Crime,Mystery,Reality-TV
Name: 2006775, dtype: object

(9,)

tconst               tt11827928
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006776, dtype: object

(9,)

tconst                                         tt1182792
titleType                                      tvEpisode
primaryTitle      Der Tatra-Nationalpark in der Slowakei
originalTitle     Der Tatra-Nationalpark in der Slowakei
isAdult                                                0
startYear                                           2001
endYear                                               \N
runtimeMinutes                                        \N
genres                                       Documentary
Name: 2006777, dtype: object

(9,)

tconst                    tt11827930
titleType                  tvEpisode
primaryTitle      Utensils & Bottles
originalTitle     Utensils & Bottles
isAdult                            0
startYear                       1966
endYear                           \N
runtimeMinutes                    \N
genres                        Family
Name: 2006778, dtype: object

(9,)

tconst               tt11827932
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006779, dtype: object

(9,)

tconst               tt11827934
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006780, dtype: object

(9,)

tconst                    tt11827936
titleType                  tvEpisode
primaryTitle      Soldiers & Weather
originalTitle     Soldiers & Weather
isAdult                            0
startYear                       1966
endYear                           \N
runtimeMinutes                    \N
genres                        Family
Name: 2006781, dtype: object

(9,)

tconst               tt11827938
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006782, dtype: object

(9,)

tconst                         tt1182793
titleType                      tvEpisode
primaryTitle      Eine unheimliche Nacht
originalTitle     Eine unheimliche Nacht
isAdult                                0
startYear                           1989
endYear                               \N
runtimeMinutes                        45
genres                      Drama,Family
Name: 2006783, dtype: object

(9,)

tconst                 tt11827940
titleType               tvEpisode
primaryTitle      Fruit & Hygiene
originalTitle     Fruit & Hygiene
isAdult                         0
startYear                    1966
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2006784, dtype: object

(9,)

tconst               tt11827942
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006785, dtype: object

(9,)

tconst               tt11827944
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006786, dtype: object

(9,)

tconst               tt11827946
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006787, dtype: object

(9,)

tconst               tt11827948
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006788, dtype: object

(9,)

tconst                                tt1182794
titleType                             tvEpisode
primaryTitle      Completely Private Livingroom
originalTitle     Completely Private Livingroom
isAdult                                       0
startYear                                  2007
endYear                                      \N
runtimeMinutes                               \N
genres                               Reality-TV
Name: 2006789, dtype: object

(9,)

tconst               tt11827950
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006790, dtype: object

(9,)

tconst               tt11827952
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006791, dtype: object

(9,)

tconst               tt11827954
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006792, dtype: object

(9,)

tconst               tt11827956
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006793, dtype: object

(9,)

tconst               tt11827958
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006794, dtype: object

(9,)

tconst                          tt1182795
titleType                       tvEpisode
primaryTitle      Schlaf Kindlein, schlaf
originalTitle     Schlaf Kindlein, schlaf
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                                 \N
Name: 2006795, dtype: object

(9,)

tconst               tt11827960
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006796, dtype: object

(9,)

tconst               tt11827962
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006797, dtype: object

(9,)

tconst            tt11827964
titleType           tvSeries
primaryTitle       Decrypted
originalTitle      Decrypted
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Sci-Fi
Name: 2006798, dtype: object

(9,)

tconst                 tt11827966
titleType                tvSeries
primaryTitle      UnREAL (Brazil)
originalTitle     UnREAL (Brazil)
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                         \N
Name: 2006799, dtype: object

(9,)

tconst               tt11827968
titleType             tvEpisode
primaryTitle      Episode #1.42
originalTitle     Episode #1.42
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006800, dtype: object

(9,)

tconst                      tt1182796
titleType                   tvEpisode
primaryTitle      Laugharne Boathouse
originalTitle     Laugharne Boathouse
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2006801, dtype: object

(9,)

tconst               tt11827970
titleType             tvEpisode
primaryTitle      Episode #1.43
originalTitle     Episode #1.43
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006802, dtype: object

(9,)

tconst               tt11827972
titleType             tvEpisode
primaryTitle      Episode #1.44
originalTitle     Episode #1.44
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006803, dtype: object

(9,)

tconst               tt11827974
titleType             tvEpisode
primaryTitle      Episode #1.45
originalTitle     Episode #1.45
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006804, dtype: object

(9,)

tconst               tt11827976
titleType             tvEpisode
primaryTitle      Episode #1.46
originalTitle     Episode #1.46
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006805, dtype: object

(9,)

tconst               tt11827978
titleType             tvEpisode
primaryTitle      Episode #1.47
originalTitle     Episode #1.47
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006806, dtype: object

(9,)

tconst                          tt1182797
titleType                       tvEpisode
primaryTitle      Newbridge Memorial Hall
originalTitle     Newbridge Memorial Hall
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                                 \N
Name: 2006807, dtype: object

(9,)

tconst               tt11827982
titleType             tvEpisode
primaryTitle      Episode #1.48
originalTitle     Episode #1.48
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2006808, dtype: object

(9,)

tconst               tt11827984
titleType             tvEpisode
primaryTitle      My First Time
originalTitle     My First Time
isAdult                       1
startYear                  2017
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2006809, dtype: object

(9,)

tconst            tt11827986
titleType          tvEpisode
primaryTitle        Gangbang
originalTitle       Gangbang
isAdult                    1
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2006810, dtype: object

(9,)

tconst            tt1182798
titleType         tvEpisode
primaryTitle       Plas Teg
originalTitle      Plas Teg
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                   \N
Name: 2006811, dtype: object

(9,)

tconst                                                  tt11827990
titleType                                                tvEpisode
primaryTitle      Gorgeous lesbian roommates masturbate each other
originalTitle     Gorgeous lesbian roommates masturbate each other
isAdult                                                          1
startYear                                                     2018
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                       Adult
Name: 2006812, dtype: object

(9,)

tconst                 tt11827994
titleType                   short
primaryTitle                 Food
originalTitle                Food
isAdult                         0
startYear                    2014
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2006813, dtype: object

(9,)

tconst                                                   tt11827996
titleType                                                     video
primaryTitle      Final Destination 5: Visual Effects of Death -...
originalTitle     Final Destination 5: Visual Effects of Death -...
isAdult                                                           0
startYear                                                      2011
endYear                                                          \N
runtimeMinutes                                                    9
genres                                                        Short
Name: 2006814, dtype: object

(9,)

tconst                tt1182799
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2006815, dtype: object

(9,)

tconst               tt11828004
titleType                 movie
primaryTitle      Rondo and Bob
originalTitle     Rondo and Bob
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes              100
genres              Documentary
Name: 2006816, dtype: object

(9,)

tconst                  tt11828006
titleType                tvEpisode
primaryTitle              02.21.20
originalTitle             02.21.20
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Crime,Reality-TV
Name: 2006817, dtype: object

(9,)

tconst                       tt1182800
titleType                    tvEpisode
primaryTitle           Episode #1.1207
originalTitle          Episode #1.1207
isAdult                              0
startYear                         1997
endYear                             \N
runtimeMinutes                      \N
genres            Drama,Family,Romance
Name: 2006818, dtype: object

(9,)

tconst              tt11828010
titleType                short
primaryTitle       The Mansion
originalTitle      The Mansion
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              \N
genres            Horror,Short
Name: 2006819, dtype: object

(9,)

tconst                     tt11828012
titleType                   tvEpisode
primaryTitle      Mirroring her pussy
originalTitle     Mirroring her pussy
isAdult                             1
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2006820, dtype: object

(9,)

tconst                           tt11828016
titleType                         tvEpisode
primaryTitle      Teen fucking a skater boy
originalTitle     Teen fucking a skater boy
isAdult                                   1
startYear                              2020
endYear                                  \N
runtimeMinutes                           20
genres                                Adult
Name: 2006821, dtype: object

(9,)

tconst                 tt11828018
titleType               tvEpisode
primaryTitle      Study My Stiffy
originalTitle     Study My Stiffy
isAdult                         1
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2006822, dtype: object

(9,)

tconst                                                  tt1182801
titleType                                               tvEpisode
primaryTitle      Voller Tatendrang renoviert Vanessa den "Fasan"
originalTitle     Voller Tatendrang renoviert Vanessa den "Fasan"
isAdult                                                         0
startYear                                                    1997
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                       Drama,Family,Romance
Name: 2006823, dtype: object

(9,)

tconst                         tt11828020
titleType                       tvEpisode
primaryTitle                   F for Fake
originalTitle                  F for Fake
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                          5
genres            Action,Adventure,Comedy
Name: 2006824, dtype: object

(9,)

tconst                                tt11828022
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2006825, dtype: object

(9,)

tconst                                                   tt11828024
titleType                                                     short
primaryTitle      The Sum of Several Sticky Situations involving...
originalTitle     The Sum of Several Sticky Situations involving...
isAdult                                                           0
startYear                                                      2021
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Short
Name: 2006826, dtype: object

(9,)

tconst                           tt11828026
titleType                         tvEpisode
primaryTitle      Oscar Red Carpet Coverage
originalTitle     Oscar Red Carpet Coverage
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                                 News
Name: 2006827, dtype: object

(9,)

tconst                                                   tt11828028
titleType                                                     movie
primaryTitle      Incident at Devils Den: A True Story, by Terry...
originalTitle     Incident at Devils Den: A True Story, by Terry...
isAdult                                                           0
startYear                                                        \N
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Sci-Fi
Name: 2006828, dtype: object

(9,)

tconst                                                    tt1182802
titleType                                                 tvEpisode
primaryTitle      Nataly überredet Philip, einen HIV-Test zu machen
originalTitle     Nataly überredet Philip, einen HIV-Test zu machen
isAdult                                                           0
startYear                                                      1997
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                         Drama,Family,Romance
Name: 2006829, dtype: object

(9,)

tconst                                                 tt1182803
titleType                                              tvEpisode
primaryTitle      Iris konfrontiert ihre Kinder mit ihren Plänen
originalTitle     Iris konfrontiert ihre Kinder mit ihren Plänen
isAdult                                                        0
startYear                                                   2008
endYear                                                       \N
runtimeMinutes                                                \N
genres                                      Drama,Family,Romance
Name: 2006830, dtype: object

(9,)

tconst                             tt11828042
titleType                           tvEpisode
primaryTitle      From Stockings to Strap-ons
originalTitle     From Stockings to Strap-ons
isAdult                                     1
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2006831, dtype: object

(9,)

tconst                    tt11828046
titleType                  tvEpisode
primaryTitle      Drop of Excitement
originalTitle     Drop of Excitement
isAdult                            1
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2006832, dtype: object

(9,)

tconst                       tt11828048
titleType                         video
primaryTitle      Snail Mail: Heat Wave
originalTitle     Snail Mail: Heat Wave
isAdult                               0
startYear                          2018
endYear                              \N
runtimeMinutes                        5
genres                      Music,Short
Name: 2006833, dtype: object

(9,)

tconst                            tt1182804
titleType                         tvEpisode
primaryTitle      Denise steht vor der Wahl
originalTitle     Denise steht vor der Wahl
isAdult                                   0
startYear                              1992
endYear                                  \N
runtimeMinutes                           \N
genres                 Drama,Family,Romance
Name: 2006834, dtype: object

(9,)

tconst                tt11828050
titleType              tvEpisode
primaryTitle       Episode #5.21
originalTitle      Episode #5.21
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006835, dtype: object

(9,)

tconst                tt11828052
titleType              tvEpisode
primaryTitle       Episode #5.22
originalTitle      Episode #5.22
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006836, dtype: object

(9,)

tconst                tt11828054
titleType              tvEpisode
primaryTitle       Episode #5.23
originalTitle      Episode #5.23
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006837, dtype: object

(9,)

tconst                tt11828056
titleType              tvEpisode
primaryTitle       Episode #5.24
originalTitle      Episode #5.24
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006838, dtype: object

(9,)

tconst                tt11828058
titleType              tvEpisode
primaryTitle       Episode #5.25
originalTitle      Episode #5.25
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006839, dtype: object

(9,)

tconst                                tt1182805
titleType                             tvEpisode
primaryTitle      Heiko verschwindet für immer!
originalTitle     Heiko verschwindet für immer!
isAdult                                       0
startYear                                  1996
endYear                                      \N
runtimeMinutes                               \N
genres                     Drama,Family,Romance
Name: 2006840, dtype: object

(9,)

tconst                tt11828060
titleType              tvEpisode
primaryTitle       Episode #5.26
originalTitle      Episode #5.26
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006841, dtype: object

(9,)

tconst                   tt11828062
titleType                     short
primaryTitle        Take It Forward
originalTitle       Take It Forward
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   17
genres            Documentary,Short
Name: 2006842, dtype: object

(9,)

tconst                      tt11828064
titleType                    tvEpisode
primaryTitle      Oldje Shower Routine
originalTitle     Oldje Shower Routine
isAdult                              1
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2006843, dtype: object

(9,)

tconst                tt11828066
titleType              tvEpisode
primaryTitle       Episode #5.27
originalTitle      Episode #5.27
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006844, dtype: object

(9,)

tconst                tt11828068
titleType              tvEpisode
primaryTitle       Episode #5.28
originalTitle      Episode #5.28
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006845, dtype: object

(9,)

tconst                                    tt1182806
titleType                                 tvEpisode
primaryTitle      The Six Billion Dollar Experiment
originalTitle     The Six Billion Dollar Experiment
isAdult                                           0
startYear                                      2007
endYear                                          \N
runtimeMinutes                                   \N
genres                                  Documentary
Name: 2006846, dtype: object

(9,)

tconst                tt11828070
titleType              tvEpisode
primaryTitle       Episode #5.29
originalTitle      Episode #5.29
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006847, dtype: object

(9,)

tconst                tt11828072
titleType              tvEpisode
primaryTitle       Episode #5.30
originalTitle      Episode #5.30
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006848, dtype: object

(9,)

tconst                tt11828074
titleType              tvEpisode
primaryTitle       Episode #5.31
originalTitle      Episode #5.31
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006849, dtype: object

(9,)

tconst                tt11828076
titleType              tvEpisode
primaryTitle       Episode #5.32
originalTitle      Episode #5.32
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006850, dtype: object

(9,)

tconst                      tt11828078
titleType                    tvEpisode
primaryTitle      Flames of Attraction
originalTitle     Flames of Attraction
isAdult                              1
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2006851, dtype: object

(9,)

tconst                   tt1182807
titleType                tvEpisode
primaryTitle      Gegen jede Regel
originalTitle     Gegen jede Regel
isAdult                          0
startYear                     2005
endYear                         \N
runtimeMinutes                  \N
genres                 Crime,Drama
Name: 2006852, dtype: object

(9,)

tconst                tt11828080
titleType              tvEpisode
primaryTitle       Episode #5.34
originalTitle      Episode #5.34
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006853, dtype: object

(9,)

tconst                tt11828082
titleType              tvEpisode
primaryTitle       Episode #5.33
originalTitle      Episode #5.33
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006854, dtype: object

(9,)

tconst                             tt11828084
titleType                           tvEpisode
primaryTitle                    Mickey Walker
originalTitle                   Mickey Walker
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2006855, dtype: object

(9,)

tconst                tt11828086
titleType              tvEpisode
primaryTitle       Episode #5.35
originalTitle      Episode #5.35
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006856, dtype: object

(9,)

tconst                tt11828088
titleType              tvEpisode
primaryTitle       Episode #5.36
originalTitle      Episode #5.36
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006857, dtype: object

(9,)

tconst                          tt1182808
titleType                       tvEpisode
primaryTitle      Tod auf dem Tonnenleger
originalTitle     Tod auf dem Tonnenleger
isAdult                                 0
startYear                            2005
endYear                                \N
runtimeMinutes                         \N
genres                        Crime,Drama
Name: 2006858, dtype: object

(9,)

tconst                tt11828090
titleType              tvEpisode
primaryTitle       Episode #5.37
originalTitle      Episode #5.37
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006859, dtype: object

(9,)

tconst                tt11828092
titleType              tvEpisode
primaryTitle       Episode #5.38
originalTitle      Episode #5.38
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006860, dtype: object

(9,)

tconst                    tt11828094
titleType                  tvEpisode
primaryTitle      Masseuse Gone Wild
originalTitle     Masseuse Gone Wild
isAdult                            1
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2006861, dtype: object

(9,)

tconst                             tt11828096
titleType                           tvEpisode
primaryTitle                Wayman R. Presley
originalTitle               Wayman R. Presley
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2006862, dtype: object

(9,)

tconst                        tt11828098
titleType                      tvEpisode
primaryTitle      Blondie Wants His Cock
originalTitle     Blondie Wants His Cock
isAdult                                1
startYear                           2019
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2006863, dtype: object

(9,)

tconst               tt1182809
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2006864, dtype: object

(9,)

tconst                tt11828100
titleType              tvEpisode
primaryTitle       Episode #5.39
originalTitle      Episode #5.39
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006865, dtype: object

(9,)

tconst                tt11828102
titleType              tvEpisode
primaryTitle       Episode #5.40
originalTitle      Episode #5.40
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006866, dtype: object

(9,)

tconst              tt11828104
titleType                movie
primaryTitle          Iraniyan
originalTitle         Iraniyan
isAdult                      0
startYear                 1999
endYear                     \N
runtimeMinutes             163
genres            Action,Drama
Name: 2006867, dtype: object

(9,)

tconst                             tt11828106
titleType                           tvEpisode
primaryTitle                  Mrs. Viola Ruth
originalTitle                 Mrs. Viola Ruth
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2006868, dtype: object

(9,)

tconst                tt11828108
titleType              tvEpisode
primaryTitle       Episode #5.41
originalTitle      Episode #5.41
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006869, dtype: object

(9,)

tconst                  tt1182810
titleType               tvEpisode
primaryTitle      Never Back Down
originalTitle     Never Back Down
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                  Adventure
Name: 2006870, dtype: object

(9,)

tconst                tt11828110
titleType              tvEpisode
primaryTitle       Episode #5.42
originalTitle      Episode #5.42
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006871, dtype: object

(9,)

tconst                tt11828112
titleType              tvEpisode
primaryTitle       Episode #5.45
originalTitle      Episode #5.45
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006872, dtype: object

(9,)

tconst                tt11828114
titleType              tvEpisode
primaryTitle       Episode #5.43
originalTitle      Episode #5.43
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006873, dtype: object

(9,)

tconst                tt11828116
titleType              tvEpisode
primaryTitle       Episode #5.44
originalTitle      Episode #5.44
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006874, dtype: object

(9,)

tconst                tt11828118
titleType              tvEpisode
primaryTitle       Episode #5.46
originalTitle      Episode #5.46
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006875, dtype: object

(9,)

tconst                         tt1182811
titleType                      tvEpisode
primaryTitle      The Accidental Husband
originalTitle     The Accidental Husband
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres                         Adventure
Name: 2006876, dtype: object

(9,)

tconst             tt11828120
titleType           tvEpisode
primaryTitle      Morning Sex
originalTitle     Morning Sex
isAdult                     1
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2006877, dtype: object

(9,)

tconst                tt11828122
titleType              tvEpisode
primaryTitle       Episode #5.47
originalTitle      Episode #5.47
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006878, dtype: object

(9,)

tconst                tt11828124
titleType              tvEpisode
primaryTitle       Episode #5.48
originalTitle      Episode #5.48
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006879, dtype: object

(9,)

tconst                tt11828126
titleType              tvEpisode
primaryTitle       Episode #5.49
originalTitle      Episode #5.49
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006880, dtype: object

(9,)

tconst                tt11828128
titleType              tvEpisode
primaryTitle       Episode #5.50
originalTitle      Episode #5.50
isAdult                        0
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres            Family,Musical
Name: 2006881, dtype: object

(9,)

tconst            tt11828130
titleType           tvSeries
primaryTitle         Someone
originalTitle        Someone
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2006882, dtype: object

(9,)

tconst                   tt11828132
titleType                 tvEpisode
primaryTitle      Admirateur secret
originalTitle     Admirateur secret
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2006883, dtype: object

(9,)

tconst                tt11828136
titleType              tvEpisode
primaryTitle      Alors heureux?
originalTitle     Alors heureux?
isAdult                        0
startYear                   2017
endYear                       \N
runtimeMinutes                \N
genres                    Family
Name: 2006884, dtype: object

(9,)

tconst                   tt11828138
titleType                 tvEpisode
primaryTitle      Ambition relative
originalTitle     Ambition relative
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2006885, dtype: object

(9,)

tconst             tt1182813
titleType          tvEpisode
primaryTitle      Das Brettl
originalTitle     Das Brettl
isAdult                    0
startYear               1974
endYear                   \N
runtimeMinutes            48
genres                Comedy
Name: 2006886, dtype: object

(9,)

tconst                   tt11828140
titleType                 tvEpisode
primaryTitle      Tight Tender Trio
originalTitle     Tight Tender Trio
isAdult                           1
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2006887, dtype: object

(9,)

tconst            tt11828142
titleType          tvEpisode
primaryTitle           Aware
originalTitle          Aware
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006888, dtype: object

(9,)

tconst            tt11828144
titleType          tvEpisode
primaryTitle      Belle mifa
originalTitle     Belle mifa
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006889, dtype: object

(9,)

tconst            tt11828146
titleType          tvEpisode
primaryTitle       Bol d'air
originalTitle      Bol d'air
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2006890, dtype: object

(9,)

tconst                 tt11828148
titleType               tvEpisode
primaryTitle      Change my World
originalTitle     Change my World
isAdult                         0
startYear                    2017
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2006891, dtype: object

(9,)

tconst                                tt1182814
titleType                             tvEpisode
primaryTitle      Der lange Weg nach Sacramento
originalTitle     Der lange Weg nach Sacramento
isAdult                                       0
startYear                                  1975
endYear                                      \N
runtimeMinutes                               51
genres                                   Comedy
Name: 2006892, dtype: object

(9,)

tconst                 tt11828150
titleType               tvEpisode
primaryTitle      Charlie's Angel
originalTitle     Charlie's Angel
isAdult                         0
startYear                    2017
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2006893, dtype: object

(9,)

tconst              tt11828152
titleType            tvEpisode
primaryTitle      Conspiration
originalTitle     Conspiration
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2006894, dtype: object

(9,)

tconst                               tt11828154
titleType                             tvEpisode
primaryTitle      De la complexité des rapports
originalTitle     De la complexité des rapports
isAdult                                       0
startYear                                  2017
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2006895, dtype: object

(9,)

tconst                   tt11828156
titleType                 tvEpisode
primaryTitle      Des gènes gênants
originalTitle     Des gènes gênants
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2006896, dtype: object

(9,)

tconst                  tt11828158
titleType                    video
primaryTitle      645AR: 4 Da Trap
originalTitle     645AR: 4 Da Trap
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                   2
genres                 Music,Short
Name: 2006897, dtype: object

(9,)

tconst                   tt1182815
titleType                tvEpisode
primaryTitle      Dreiviertelreife
originalTitle     Dreiviertelreife
isAdult                          0
startYear                     1974
endYear                         \N
runtimeMinutes                  51
genres                      Comedy
Name: 2006898, dtype: object

(9,)

tconst               tt11828160
titleType              tvSeries
primaryTitle      Irish Pickers
originalTitle     Irish Pickers
isAdult                       0
startYear                  2021
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2006899, dtype: object

(9,)

tconst                                  tt11828162
titleType                                tvEpisode
primaryTitle      Two hot blondes in threesome sex
originalTitle     Two hot blondes in threesome sex
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006900, dtype: object

(9,)

tconst                           tt11828164
titleType                         tvEpisode
primaryTitle      Ep 2: Shannon Baker Davis
originalTitle     Ep 2: Shannon Baker Davis
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2006901, dtype: object

(9,)

tconst                                              tt11828168
titleType                                            tvEpisode
primaryTitle      Beautiful lesbian seduces and bangs waitress
originalTitle     Beautiful lesbian seduces and bangs waitress
isAdult                                                      1
startYear                                                 2018
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                   Adult
Name: 2006902, dtype: object

(9,)

tconst                    tt1182816
titleType                 tvEpisode
primaryTitle      Ein Ziel im Leben
originalTitle     Ein Ziel im Leben
isAdult                           0
startYear                      1975
endYear                          \N
runtimeMinutes                   51
genres                       Comedy
Name: 2006903, dtype: object

(9,)

tconst                             tt11828170
titleType                           tvEpisode
primaryTitle               General Mark Clark
originalTitle              General Mark Clark
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2006904, dtype: object

(9,)

tconst                      tt11828172
titleType                    tvEpisode
primaryTitle      Blonde And Beautiful
originalTitle     Blonde And Beautiful
isAdult                              1
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2006905, dtype: object

(9,)

tconst              tt11828174
titleType            tvEpisode
primaryTitle      More To Give
originalTitle     More To Give
isAdult                      1
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2006906, dtype: object

(9,)

tconst                                   tt11828176
titleType                                 tvEpisode
primaryTitle      Sara and Hoppity and a Shaggy Dog
originalTitle     Sara and Hoppity and a Shaggy Dog
isAdult                                           0
startYear                                      1962
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Family
Name: 2006907, dtype: object

(9,)

tconst                 tt11828178
titleType               tvEpisode
primaryTitle      The Right Touch
originalTitle     The Right Touch
isAdult                         1
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2006908, dtype: object

(9,)

tconst                        tt1182817
titleType                     tvEpisode
primaryTitle      Geschäft ist Geschäft
originalTitle     Geschäft ist Geschäft
isAdult                               0
startYear                          1975
endYear                              \N
runtimeMinutes                       49
genres                           Comedy
Name: 2006909, dtype: object

(9,)

tconst             tt11828180
titleType           tvEpisode
primaryTitle      Make Me Cum
originalTitle     Make Me Cum
isAdult                     1
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2006910, dtype: object

(9,)

tconst                               tt11828184
titleType                             tvEpisode
primaryTitle      Sara's Friend Has an Accident
originalTitle     Sara's Friend Has an Accident
isAdult                                       0
startYear                                  1962
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2006911, dtype: object

(9,)

tconst                tt11828186
titleType              tvEpisode
primaryTitle      Playing To Win
originalTitle     Playing To Win
isAdult                        1
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2006912, dtype: object

(9,)

tconst            tt1182818
titleType         tvEpisode
primaryTitle      Glücksach
originalTitle     Glücksach
isAdult                   0
startYear              1974
endYear                  \N
runtimeMinutes           52
genres               Comedy
Name: 2006913, dtype: object

(9,)

tconst                    tt11828190
titleType                  tvEpisode
primaryTitle      Pedicure threesome
originalTitle     Pedicure threesome
isAdult                            1
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2006914, dtype: object

(9,)

tconst                   tt11828192
titleType                 tvEpisode
primaryTitle      Rainy sapphic day
originalTitle     Rainy sapphic day
isAdult                           1
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2006915, dtype: object

(9,)

tconst                     tt11828194
titleType                       short
primaryTitle      By Appointment Only
originalTitle     By Appointment Only
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                      4
genres                   Comedy,Short
Name: 2006916, dtype: object

(9,)

tconst                              tt11828196
titleType                            tvEpisode
primaryTitle      Shaggy is Taught Some Tricks
originalTitle     Shaggy is Taught Some Tricks
isAdult                                      0
startYear                                 1962
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2006917, dtype: object

(9,)

tconst                                                   tt11828198
titleType                                                     short
primaryTitle      Dr. Spylove or: How I Learned to Stop Worrying...
originalTitle     Dr. Spylove or: How I Learned to Stop Worrying...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    7
genres                                                 Comedy,Short
Name: 2006918, dtype: object

(9,)

tconst             tt1182819
titleType          tvEpisode
primaryTitle      Maulhelden
originalTitle     Maulhelden
isAdult                    0
startYear               1975
endYear                   \N
runtimeMinutes            47
genres                Comedy
Name: 2006919, dtype: object

(9,)

tconst                             tt11828202
titleType                           tvEpisode
primaryTitle      Sara and Hoppity Go Skating
originalTitle     Sara and Hoppity Go Skating
isAdult                                     0
startYear                                1962
endYear                                    \N
runtimeMinutes                             \N
genres                                 Family
Name: 2006920, dtype: object

(9,)

tconst                          tt11828204
titleType                         tvSeries
primaryTitle                    FIA Xpress
originalTitle                   FIA Xpress
isAdult                                  0
startYear                               \N
endYear                                 \N
runtimeMinutes                          \N
genres            Fantasy,Sci-Fi,Talk-Show
Name: 2006921, dtype: object

(9,)

tconst                                   tt11828208
titleType                                     video
primaryTitle      Asking Alexandria: Anti-Socialist
originalTitle     Asking Alexandria: Anti-Socialist
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Short
Name: 2006922, dtype: object

(9,)

tconst             tt1182820
titleType          tvEpisode
primaryTitle      Ois anders
originalTitle     Ois anders
isAdult                    0
startYear               1975
endYear                   \N
runtimeMinutes            49
genres                Comedy
Name: 2006923, dtype: object

(9,)

tconst                                        tt11828210
titleType                                      tvEpisode
primaryTitle      Super cute teen banged by her neighbor
originalTitle     Super cute teen banged by her neighbor
isAdult                                                1
startYear                                           2018
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Adult
Name: 2006924, dtype: object

(9,)

tconst                        tt11828212
titleType                      tvEpisode
primaryTitle      Fresh new talent Casey
originalTitle     Fresh new talent Casey
isAdult                                1
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2006925, dtype: object

(9,)

tconst                             tt11828214
titleType                           tvEpisode
primaryTitle      Hot Casey loves riding cock
originalTitle     Hot Casey loves riding cock
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2006926, dtype: object

(9,)

tconst                                   tt11828216
titleType                                 tvEpisode
primaryTitle      Cute teen masturbating in her bed
originalTitle     Cute teen masturbating in her bed
isAdult                                           1
startYear                                      2018
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Adult
Name: 2006927, dtype: object

(9,)

tconst                                  tt11828218
titleType                                tvEpisode
primaryTitle      Lesbians making out on the beach
originalTitle     Lesbians making out on the beach
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2006928, dtype: object

(9,)

tconst              tt1182821
titleType           tvEpisode
primaryTitle      Rosenzauber
originalTitle     Rosenzauber
isAdult                     0
startYear                1974
endYear                    \N
runtimeMinutes             50
genres                 Comedy
Name: 2006929, dtype: object

(9,)

tconst                            tt11828220
titleType                          tvEpisode
primaryTitle      Casey gets fucked outdoors
originalTitle     Casey gets fucked outdoors
isAdult                                    1
startYear                               2018
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2006930, dtype: object

(9,)

tconst                                               tt11828222
titleType                                             tvEpisode
primaryTitle      Beautiful blonde student masturbating at home
originalTitle     Beautiful blonde student masturbating at home
isAdult                                                       1
startYear                                                  2019
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                    Adult
Name: 2006931, dtype: object

(9,)

tconst                                        tt11828226
titleType                                      tvEpisode
primaryTitle      Gorgeous babes making out on the beach
originalTitle     Gorgeous babes making out on the beach
isAdult                                                1
startYear                                           2019
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Adult
Name: 2006932, dtype: object

(9,)

tconst                               tt11828228
titleType                             tvEpisode
primaryTitle      Blonde student banged at home
originalTitle     Blonde student banged at home
isAdult                                       1
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2006933, dtype: object

(9,)

tconst               tt1182822
titleType            tvEpisode
primaryTitle      Episode #3.3
originalTitle     Episode #3.3
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2006934, dtype: object

(9,)

tconst                                      tt11828230
titleType                                    tvEpisode
primaryTitle      A finger a day keeps the doctor away
originalTitle     A finger a day keeps the doctor away
isAdult                                              1
startYear                                         2019
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Adult
Name: 2006935, dtype: object

(9,)

tconst             tt11828232
titleType           tvEpisode
primaryTitle      Working Out
originalTitle     Working Out
isAdult                     1
startYear                2016
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2006936, dtype: object

(9,)

tconst              tt11828234
titleType            tvEpisode
primaryTitle      Upskirt Peek
originalTitle     Upskirt Peek
isAdult                      1
startYear                 2016
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2006937, dtype: object

(9,)

tconst                  tt11828236
titleType                tvSpecial
primaryTitle      Motorama of 1954
originalTitle     Motorama of 1954
isAdult                          0
startYear                     1954
endYear                         \N
runtimeMinutes                  45
genres                      Family
Name: 2006938, dtype: object

(9,)

tconst            tt11828238
titleType          tvEpisode
primaryTitle        Show Off
originalTitle       Show Off
isAdult                    1
startYear               2016
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2006939, dtype: object

(9,)

tconst                       tt1182823
titleType                    tvEpisode
primaryTitle      Man liebt nur einmal
originalTitle     Man liebt nur einmal
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      43
genres                           Crime
Name: 2006940, dtype: object

(9,)

tconst            tt11828240
titleType          tvEpisode
primaryTitle       Cutie Pie
originalTitle      Cutie Pie
isAdult                    1
startYear               2016
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2006941, dtype: object

(9,)

tconst                   tt11828242
titleType                     short
primaryTitle            In Alliance
originalTitle           In Alliance
isAdult                           0
startYear                      2015
endYear                          \N
runtimeMinutes                   16
genres            Documentary,Short
Name: 2006942, dtype: object

(9,)

tconst                          tt11828244
titleType                        tvEpisode
primaryTitle      Sara and the Broken Toys
originalTitle     Sara and the Broken Toys
isAdult                                  0
startYear                             1962
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2006943, dtype: object

(9,)

tconst                                 tt11828246
titleType                               tvEpisode
primaryTitle      The Academy Awards Big Surprise
originalTitle     The Academy Awards Big Surprise
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Talk-Show
Name: 2006944, dtype: object

(9,)

tconst                       tt11828248
titleType                         short
primaryTitle      Mayday - Better Place
originalTitle     Mayday - Better Place
isAdult                               0
startYear                          2017
endYear                              \N
runtimeMinutes                       \N
genres                            Short
Name: 2006945, dtype: object

(9,)

tconst                  tt1182824
titleType               tvEpisode
primaryTitle      Tony and Maxxie
originalTitle     Tony and Maxxie
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 45
genres                      Drama
Name: 2006946, dtype: object

(9,)

tconst                      tt11828250
titleType                    tvEpisode
primaryTitle      Edge of the Universe
originalTitle     Edge of the Universe
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      42
genres                     Documentary
Name: 2006947, dtype: object

(9,)

tconst                         tt11828256
titleType                       tvEpisode
primaryTitle      Valentine's Day Special
originalTitle     Valentine's Day Special
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2006948, dtype: object

(9,)

tconst                   tt11828258
titleType                 tvEpisode
primaryTitle      Shaggy in Trouble
originalTitle     Shaggy in Trouble
isAdult                           0
startYear                      1962
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2006949, dtype: object

(9,)

tconst                   tt1182825
titleType                tvEpisode
primaryTitle           Auditions 1
originalTitle          Auditions 1
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Music,Reality-TV
Name: 2006950, dtype: object

(9,)

tconst                              tt11828260
titleType                            tvEpisode
primaryTitle      Phantom of the Opera on Tour
originalTitle     Phantom of the Opera on Tour
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2006951, dtype: object

(9,)

tconst                 tt11828262
titleType                   short
primaryTitle      Chocolate Child
originalTitle     Chocolate Child
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                Music,Short
Name: 2006952, dtype: object

(9,)

tconst                                  tt11828264
titleType                                    short
primaryTitle      Snow Globe: A Breaking Bad Short
originalTitle     Snow Globe: A Breaking Bad Short
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Short
Name: 2006953, dtype: object

(9,)

tconst            tt11828266
titleType          tvEpisode
primaryTitle        CES 2020
originalTitle       CES 2020
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2006954, dtype: object

(9,)

tconst                                    tt11828268
titleType                                  tvEpisode
primaryTitle      Palm Springs Film Festival Special
originalTitle     Palm Springs Film Festival Special
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                     Talk-Show
Name: 2006955, dtype: object

(9,)

tconst                   tt1182826
titleType                tvEpisode
primaryTitle           Auditions 2
originalTitle          Auditions 2
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Music,Reality-TV
Name: 2006956, dtype: object

(9,)

tconst                           tt11828270
titleType                         tvEpisode
primaryTitle      Monsters of the Milky Way
originalTitle     Monsters of the Milky Way
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           42
genres                          Documentary
Name: 2006957, dtype: object

(9,)

tconst                               tt11828272
titleType                                 short
primaryTitle      Eden: The Only One Left to Us
originalTitle     Eden: The Only One Left to Us
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                    Short
Name: 2006958, dtype: object

(9,)

tconst                                      tt11828274
titleType                                        video
primaryTitle      Meli Deluxe: Knallhart im Fickrausch
originalTitle     Meli Deluxe: Knallhart im Fickrausch
isAdult                                              1
startYear                                         2012
endYear                                             \N
runtimeMinutes                                     119
genres                                           Adult
Name: 2006959, dtype: object

(9,)

tconst                   tt1182827
titleType                tvEpisode
primaryTitle           Auditions 3
originalTitle          Auditions 3
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Music,Reality-TV
Name: 2006960, dtype: object

(9,)

tconst                 tt11828280
titleType               tvEpisode
primaryTitle      Holiday Special
originalTitle     Holiday Special
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2006961, dtype: object

(9,)

tconst                        tt11828282
titleType                          movie
primaryTitle          The Truffle Hunter
originalTitle         The Truffle Hunter
isAdult                                0
startYear                             \N
endYear                               \N
runtimeMinutes                        \N
genres            Adventure,Comedy,Drama
Name: 2006962, dtype: object

(9,)

tconst               tt11828284
titleType                 movie
primaryTitle      Dope Is Death
originalTitle     Dope Is Death
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               78
genres              Documentary
Name: 2006963, dtype: object

(9,)

tconst               tt11828286
titleType                 short
primaryTitle      A Third Party
originalTitle             Jomun
isAdult                       0
startYear                  2014
endYear                      \N
runtimeMinutes               20
genres              Drama,Short
Name: 2006964, dtype: object

(9,)

tconst                                                   tt11828288
titleType                                                     video
primaryTitle      Riaru jokyôshi kokujin kaikin!! Hitodzuma joky...
originalTitle     Riaru jokyôshi kokujin kaikin!! Hitodzuma joky...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                  115
genres                                                        Drama
Name: 2006965, dtype: object

(9,)

tconst                   tt1182828
titleType                tvEpisode
primaryTitle      Songs of My Life
originalTitle     Songs of My Life
isAdult                          0
startYear                     1973
endYear                         \N
runtimeMinutes                  \N
genres                       Music
Name: 2006966, dtype: object

(9,)

tconst                          tt11828290
titleType                        tvEpisode
primaryTitle      The Baja Andrenalin Rush
originalTitle     The Baja Andrenalin Rush
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          \N
genres                           Talk-Show
Name: 2006967, dtype: object

(9,)

tconst               tt11828294
titleType             tvEpisode
primaryTitle      Mammoth Lakes
originalTitle     Mammoth Lakes
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2006968, dtype: object

(9,)

tconst                       tt11828296
titleType                         short
primaryTitle      The Gray and The Blue
originalTitle     The Gray and The Blue
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                        9
genres                  Animation,Short
Name: 2006969, dtype: object

(9,)

tconst                       tt11828298
titleType                         short
primaryTitle      Happy Birthday, Marty
originalTitle     Happy Birthday, Marty
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                            Short
Name: 2006970, dtype: object

(9,)

tconst                       tt1182829
titleType                    tvEpisode
primaryTitle      Songs of The Beatles
originalTitle     Songs of The Beatles
isAdult                              0
startYear                         1973
endYear                             \N
runtimeMinutes                      \N
genres                           Music
Name: 2006971, dtype: object

(9,)

tconst                      tt11828300
titleType                    tvEpisode
primaryTitle      Thanksgiving Special
originalTitle     Thanksgiving Special
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2006972, dtype: object

(9,)

tconst                                tt11828302
titleType                              tvEpisode
primaryTitle      Have you met all the Regulars?
originalTitle     Have you met all the Regulars?
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                     Crime
Name: 2006973, dtype: object

(9,)

tconst                             tt11828304
titleType                        tvMiniSeries
primaryTitle                         Skandal!
originalTitle                        Skandal!
isAdult                                     0
startYear                                2014
endYear                                  2014
runtimeMinutes                             30
genres            Documentary,Drama,Talk-Show
Name: 2006974, dtype: object

(9,)

tconst                    tt11828306
titleType                  tvEpisode
primaryTitle      The Best College's
originalTitle     The Best College's
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2006975, dtype: object

(9,)

tconst                                tt11828308
titleType                              tvEpisode
primaryTitle      Everyone's talking about Benji
originalTitle     Everyone's talking about Benji
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                     Crime
Name: 2006976, dtype: object

(9,)

tconst                      tt1182830
titleType                   tvEpisode
primaryTitle      Familienaufstellung
originalTitle     Familienaufstellung
isAdult                             0
startYear                        2009
endYear                            \N
runtimeMinutes                     90
genres            Crime,Drama,Mystery
Name: 2006977, dtype: object

(9,)

tconst                        tt11828310
titleType                      tvEpisode
primaryTitle      California News Update
originalTitle     California News Update
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2006978, dtype: object

(9,)

tconst                                  tt11828312
titleType                                tvEpisode
primaryTitle      You wanna tell me the punchline?
originalTitle     You wanna tell me the punchline?
isAdult                                          0
startYear                                     2019
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Crime
Name: 2006979, dtype: object

(9,)

tconst                  tt11828314
titleType                    short
primaryTitle      Black Eyed Susan
originalTitle     Black Eyed Susan
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                       Short
Name: 2006980, dtype: object

(9,)

tconst            tt11828316
titleType              movie
primaryTitle          Kondor
originalTitle         Kondor
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            81
genres                 Crime
Name: 2006981, dtype: object

(9,)

tconst            tt11828318
titleType          tvEpisode
primaryTitle      Cockbuster
originalTitle     Cockbuster
isAdult                    1
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2006982, dtype: object

(9,)

tconst                                           tt1182831
titleType                                        tvEpisode
primaryTitle      Orson Bean & Sid Caesar and Imogene Coca
originalTitle     Orson Bean & Sid Caesar and Imogene Coca
isAdult                                                  0
startYear                                             1967
endYear                                                 \N
runtimeMinutes                                          \N
genres                                    Family,Game-Show
Name: 2006983, dtype: object

(9,)

tconst                   tt11828320
titleType                 tvEpisode
primaryTitle      I took care of it
originalTitle     I took care of it
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                        Crime
Name: 2006984, dtype: object

(9,)

tconst                 tt11828322
titleType               tvEpisode
primaryTitle      San Luis Obispo
originalTitle     San Luis Obispo
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2006985, dtype: object

(9,)

tconst                   tt11828324
titleType                 tvEpisode
primaryTitle      Halloween Special
originalTitle     Halloween Special
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2006986, dtype: object

(9,)

tconst                     tt11828326
titleType                   tvEpisode
primaryTitle      It's Never Too Late
originalTitle     It's Never Too Late
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2006987, dtype: object

(9,)

tconst                        tt11828328
titleType                      tvEpisode
primaryTitle      Taking it for the Team
originalTitle     Taking it for the Team
isAdult                                1
startYear                           2011
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2006988, dtype: object

(9,)

tconst                   tt1182832
titleType                tvEpisode
primaryTitle        Candice Bergen
originalTitle       Candice Bergen
isAdult                          0
startYear                     1967
endYear                         \N
runtimeMinutes                  \N
genres            Family,Game-Show
Name: 2006989, dtype: object

(9,)

tconst                         tt11828330
titleType                       tvEpisode
primaryTitle      Halloween at Disneyland
originalTitle     Halloween at Disneyland
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2006990, dtype: object

(9,)

tconst                   tt11828334
titleType                     video
primaryTitle         Rata bañandose
originalTitle        Rata bañandose
isAdult                           0
startYear                      2018
endYear                          \N
runtimeMinutes                    1
genres            Documentary,Short
Name: 2006991, dtype: object

(9,)

tconst                       tt11828336
titleType                     tvEpisode
primaryTitle      Veteran's Fishing Day
originalTitle     Veteran's Fishing Day
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2006992, dtype: object

(9,)

tconst                       tt1182833
titleType                    tvEpisode
primaryTitle              Episode #9.1
originalTitle             Episode #9.1
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      44
genres            Game-Show,Reality-TV
Name: 2006993, dtype: object

(9,)

tconst            tt11828342
titleType          tvEpisode
primaryTitle      Mark Munoz
originalTitle     Mark Munoz
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2006994, dtype: object

(9,)

tconst                      tt11828344
titleType                        short
primaryTitle      Allting är en fördel
originalTitle     Allting är en fördel
isAdult                              0
startYear                         2009
endYear                             \N
runtimeMinutes                      25
genres               Documentary,Short
Name: 2006995, dtype: object

(9,)

tconst                               tt11828346
titleType                              tvSeries
primaryTitle      The Dark Corners of the Night
originalTitle     The Dark Corners of the Night
isAdult                                       0
startYear                                    \N
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2006996, dtype: object

(9,)

tconst                              tt11828348
titleType                            tvSpecial
primaryTitle          Are You Next Talent Show
originalTitle     Love and Happiness Talk Show
isAdult                                      0
startYear                                 2021
endYear                                     \N
runtimeMinutes                              30
genres                               Talk-Show
Name: 2006997, dtype: object

(9,)

tconst                       tt1182834
titleType                    tvEpisode
primaryTitle             Episode #9.10
originalTitle            Episode #9.10
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      44
genres            Game-Show,Reality-TV
Name: 2006998, dtype: object

(9,)

tconst                                 tt11828350
titleType                                   movie
primaryTitle      Tottenham Hotspur vs RB Leipzig
originalTitle     Tottenham Hotspur vs RB Leipzig
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 95
genres                                     Action
Name: 2006999, dtype: object

(9,)

tconst                             tt11828352
titleType                           tvEpisode
primaryTitle         Okänd kvinna 2009-349701
originalTitle        Okänd kvinna 2009-349701
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres            Documentary,Drama,Talk-Show
Name: 2007000, dtype: object

(9,)

tconst                             tt11828356
titleType                           tvEpisode
primaryTitle           Makode Linde/Rastårtan
originalTitle          Makode Linde/Rastårtan
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres            Documentary,Drama,Talk-Show
Name: 2007001, dtype: object

(9,)

tconst                  tt11828358
titleType                tvEpisode
primaryTitle      The Missing Link
originalTitle     The Missing Link
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2007002, dtype: object

(9,)

tconst                       tt1182835
titleType                    tvEpisode
primaryTitle             Episode #9.11
originalTitle            Episode #9.11
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      43
genres            Game-Show,Reality-TV
Name: 2007003, dtype: object

(9,)

tconst                tt11828360
titleType              tvEpisode
primaryTitle        Episode #6.5
originalTitle       Episode #6.5
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes               180
genres            News,Talk-Show
Name: 2007004, dtype: object

(9,)

tconst                                   tt11828362
titleType                                     movie
primaryTitle      Manchester City vs Leicester City
originalTitle     Manchester City vs Leicester City
isAdult                                           0
startYear                                      2019
endYear                                          \N
runtimeMinutes                                   94
genres                                       Action
Name: 2007005, dtype: object

(9,)

tconst                             tt11828364
titleType                           tvEpisode
primaryTitle                Den högsta kasten
originalTitle               Den högsta kasten
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres            Documentary,Drama,Talk-Show
Name: 2007006, dtype: object

(9,)

tconst                                   tt11828366
titleType                                 tvEpisode
primaryTitle      It's Floofy and Everything's Fine
originalTitle     It's Floofy and Everything's Fine
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                    Talk-Show
Name: 2007007, dtype: object

(9,)

tconst                            tt11828368
titleType                          tvEpisode
primaryTitle      The Opposite of a Hot Mess
originalTitle     The Opposite of a Hot Mess
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            22
genres                             Talk-Show
Name: 2007008, dtype: object

(9,)

tconst                       tt1182836
titleType                    tvEpisode
primaryTitle             Episode #9.12
originalTitle            Episode #9.12
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007009, dtype: object

(9,)

tconst                        tt11828370
titleType                      tvEpisode
primaryTitle      Bundt and Roll With It
originalTitle     Bundt and Roll With It
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        22
genres                         Talk-Show
Name: 2007010, dtype: object

(9,)

tconst                             tt11828372
titleType                           tvEpisode
primaryTitle                  Horkarlsmyntet.
originalTitle                 Horkarlsmyntet.
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres            Documentary,Drama,Talk-Show
Name: 2007011, dtype: object

(9,)

tconst                            tt11828374
titleType                          tvEpisode
primaryTitle                    Episode #1.2
originalTitle                   Episode #1.2
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007012, dtype: object

(9,)

tconst                    tt11828376
titleType                  tvEpisode
primaryTitle      Thursday, Feb 20th
originalTitle     Thursday, Feb 20th
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                          News
Name: 2007013, dtype: object

(9,)

tconst                            tt11828378
titleType                          tvEpisode
primaryTitle                    Episode #1.3
originalTitle                   Episode #1.3
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007014, dtype: object

(9,)

tconst                       tt1182837
titleType                    tvEpisode
primaryTitle             Episode #9.13
originalTitle            Episode #9.13
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      44
genres            Game-Show,Reality-TV
Name: 2007015, dtype: object

(9,)

tconst                            tt11828380
titleType                          tvEpisode
primaryTitle                    Episode #1.4
originalTitle                   Episode #1.4
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007016, dtype: object

(9,)

tconst                            tt11828382
titleType                          tvEpisode
primaryTitle                    Episode #1.5
originalTitle                   Episode #1.5
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007017, dtype: object

(9,)

tconst                            tt11828384
titleType                          tvEpisode
primaryTitle                    Episode #1.6
originalTitle                   Episode #1.6
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007018, dtype: object

(9,)

tconst                            tt11828386
titleType                           tvSeries
primaryTitle                    The Hospital
originalTitle                   The Hospital
isAdult                                    0
startYear                                 \N
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2007019, dtype: object

(9,)

tconst                            tt11828388
titleType                          tvEpisode
primaryTitle                    Episode #1.7
originalTitle                   Episode #1.7
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007020, dtype: object

(9,)

tconst                       tt1182838
titleType                    tvEpisode
primaryTitle             Episode #9.14
originalTitle            Episode #9.14
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      43
genres            Game-Show,Reality-TV
Name: 2007021, dtype: object

(9,)

tconst             tt11828390
titleType               short
primaryTitle            Peter
originalTitle           Peter
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              6
genres            Drama,Short
Name: 2007022, dtype: object

(9,)

tconst                            tt11828392
titleType                          tvEpisode
primaryTitle                    Episode #1.8
originalTitle                   Episode #1.8
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007023, dtype: object

(9,)

tconst                         tt11828394
titleType                           video
primaryTitle      Nilüfer Yanya: Baby Blu
originalTitle     Nilüfer Yanya: Baby Blu
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                          5
genres                        Music,Short
Name: 2007024, dtype: object

(9,)

tconst                            tt11828396
titleType                          tvEpisode
primaryTitle                    Episode #1.9
originalTitle                   Episode #1.9
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007025, dtype: object

(9,)

tconst                       tt1182839
titleType                    tvEpisode
primaryTitle             Episode #9.15
originalTitle            Episode #9.15
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007026, dtype: object

(9,)

tconst                            tt11828400
titleType                          tvEpisode
primaryTitle                   Episode #1.10
originalTitle                  Episode #1.10
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007027, dtype: object

(9,)

tconst              tt11828402
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 1967
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2007028, dtype: object

(9,)

tconst                                                   tt11828404
titleType                                                 tvEpisode
primaryTitle      WAR Series 3 - John 'Camouflage by Spray Paint...
originalTitle     WAR Series 3 - John 'Camouflage by Spray Paint...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2007029, dtype: object

(9,)

tconst            tt11828406
titleType              movie
primaryTitle         Forever
originalTitle        Forever
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres               Romance
Name: 2007030, dtype: object

(9,)

tconst                       tt1182840
titleType                    tvEpisode
primaryTitle             Episode #9.16
originalTitle            Episode #9.16
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      44
genres            Game-Show,Reality-TV
Name: 2007031, dtype: object

(9,)

tconst                                     tt11828410
titleType                                   tvEpisode
primaryTitle      Bloomberg Eaten Alive at Dem Debate
originalTitle     Bloomberg Eaten Alive at Dem Debate
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                      Talk-Show
Name: 2007032, dtype: object

(9,)

tconst                          tt11828412
titleType                            video
primaryTitle      Celeste: Stop This Flame
originalTitle     Celeste: Stop This Flame
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                           5
genres                         Music,Short
Name: 2007033, dtype: object

(9,)

tconst                      tt11828414
titleType                    tvEpisode
primaryTitle                  Tinnitus
originalTitle                 Tinnitus
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      45
genres            Crime,Drama,Thriller
Name: 2007034, dtype: object

(9,)

tconst                                      tt11828416
titleType                                        movie
primaryTitle      West Ham United vs Manchester United
originalTitle     West Ham United vs Manchester United
isAdult                                              0
startYear                                         2011
endYear                                             \N
runtimeMinutes                                      90
genres                                      Reality-TV
Name: 2007035, dtype: object

(9,)

tconst                tt11828418
titleType              tvEpisode
primaryTitle       Episode #2.25
originalTitle      Episode #2.25
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2007036, dtype: object

(9,)

tconst                       tt1182841
titleType                    tvEpisode
primaryTitle             Episode #9.17
originalTitle            Episode #9.17
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      43
genres            Game-Show,Reality-TV
Name: 2007037, dtype: object

(9,)

tconst                       tt11828420
titleType                       tvMovie
primaryTitle      Christmas on the Vine
originalTitle     Christmas on the Vine
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       87
genres                    Drama,Romance
Name: 2007038, dtype: object

(9,)

tconst                      tt11828422
titleType                    tvSpecial
primaryTitle      The BRIT Awards 2020
originalTitle     The BRIT Awards 2020
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                     109
genres                           Music
Name: 2007039, dtype: object

(9,)

tconst               tt11828424
titleType                 short
primaryTitle        Coming Home
originalTitle       Coming Home
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes                6
genres            Fantasy,Short
Name: 2007040, dtype: object

(9,)

tconst                                                   tt11828426
titleType                                                 tvEpisode
primaryTitle      Buttigieg Fabricating African American Support...
originalTitle     Buttigieg Fabricating African American Support...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2007041, dtype: object

(9,)

tconst                                                   tt11828428
titleType                                                 tvSpecial
primaryTitle      Women's Olympic football qualifier China vs Au...
originalTitle     Women's Olympic football qualifier China vs Au...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   95
genres                                                        Sport
Name: 2007042, dtype: object

(9,)

tconst                       tt1182842
titleType                    tvEpisode
primaryTitle             Episode #9.18
originalTitle            Episode #9.18
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007043, dtype: object

(9,)

tconst                            tt11828432
titleType                          tvEpisode
primaryTitle                      Castingy 2
originalTitle                     Castingy 2
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007044, dtype: object

(9,)

tconst                                               tt11828434
titleType                                             tvEpisode
primaryTitle      FINALLY: The Bloodiest Democratic Debate Ever
originalTitle     FINALLY: The Bloodiest Democratic Debate Ever
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               \N
genres                                           News,Talk-Show
Name: 2007045, dtype: object

(9,)

tconst                                     tt11828438
titleType                                   tvEpisode
primaryTitle      Serie A TIM 2000-01: Roma vs. Parma
originalTitle     Serie A TIM 2000-01: Roma vs. Parma
isAdult                                             0
startYear                                        2001
endYear                                            \N
runtimeMinutes                                     90
genres                                          Sport
Name: 2007046, dtype: object

(9,)

tconst                       tt1182843
titleType                    tvEpisode
primaryTitle             Episode #9.19
originalTitle            Episode #9.19
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007047, dtype: object

(9,)

tconst                                                   tt11828442
titleType                                                 tvEpisode
primaryTitle      Richard Turner: The Magical Phenom Who Will Bl...
originalTitle     Richard Turner: The Magical Phenom Who Will Bl...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                               News,Talk-Show
Name: 2007048, dtype: object

(9,)

tconst                                                   tt11828446
titleType                                                 tvSpecial
primaryTitle      FIBA Olympic qualifier China women vs South Ko...
originalTitle     FIBA Olympic qualifier China women vs South Ko...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Action
Name: 2007049, dtype: object

(9,)

tconst                       tt1182844
titleType                    tvEpisode
primaryTitle              Episode #9.2
originalTitle             Episode #9.2
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      43
genres            Game-Show,Reality-TV
Name: 2007050, dtype: object

(9,)

tconst                tt11828450
titleType                  short
primaryTitle          Paralipsis
originalTitle         Paralipsis
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres            Short,Thriller
Name: 2007051, dtype: object

(9,)

tconst                             tt11828452
titleType                           tvEpisode
primaryTitle         Docklands/Frihetsfronten
originalTitle        Docklands/Frihetsfronten
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres            Documentary,Drama,Talk-Show
Name: 2007052, dtype: object

(9,)

tconst                     tt11828454
titleType                       movie
primaryTitle      Liverpool vs Napoli
originalTitle     Liverpool vs Napoli
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     96
genres                         Action
Name: 2007053, dtype: object

(9,)

tconst                              tt11828456
titleType                                movie
primaryTitle      Molulo 2: Jodohku yang Mana?
originalTitle     Molulo 2: Jodohku yang Mana?
isAdult                                      0
startYear                                   \N
endYear                                     \N
runtimeMinutes                              \N
genres                            Comedy,Drama
Name: 2007054, dtype: object

(9,)

tconst                             tt11828458
titleType                           tvEpisode
primaryTitle                    Rondellhunden
originalTitle                   Rondellhunden
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres            Documentary,Drama,Talk-Show
Name: 2007055, dtype: object

(9,)

tconst                       tt1182845
titleType                    tvEpisode
primaryTitle             Episode #9.20
originalTitle            Episode #9.20
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007056, dtype: object

(9,)

tconst                                tt11828460
titleType                                  movie
primaryTitle      Barcelona vs Borussia Dortmund
originalTitle     Barcelona vs Borussia Dortmund
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                92
genres                                Reality-TV
Name: 2007057, dtype: object

(9,)

tconst             tt11828462
titleType               short
primaryTitle         Good Bye
originalTitle          Dohaga
isAdult                     0
startYear                2014
endYear                    \N
runtimeMinutes             21
genres            Drama,Short
Name: 2007058, dtype: object

(9,)

tconst                                                   tt11828464
titleType                                                     video
primaryTitle      Animal Sacrifices Continue at the Gadhimai Temple
originalTitle     Animal Sacrifices Continue at the Gadhimai Temple
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    3
genres                                            Documentary,Short
Name: 2007059, dtype: object

(9,)

tconst                             tt11828468
titleType                           tvSpecial
primaryTitle      Wigan Athletic vs Liverpool
originalTitle     Wigan Athletic vs Liverpool
isAdult                                     0
startYear                                2017
endYear                                    \N
runtimeMinutes                             93
genres                                 Action
Name: 2007060, dtype: object

(9,)

tconst                       tt1182846
titleType                    tvEpisode
primaryTitle              Episode #9.3
originalTitle             Episode #9.3
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      43
genres            Game-Show,Reality-TV
Name: 2007061, dtype: object

(9,)

tconst                           tt11828470
titleType                             movie
primaryTitle      Genk vs Red Bull Salzburg
originalTitle     Genk vs Red Bull Salzburg
isAdult                                   0
startYear                              2019
endYear                                  \N
runtimeMinutes                           91
genres                               Action
Name: 2007062, dtype: object

(9,)

tconst                tt11828474
titleType              tvEpisode
primaryTitle       Episode #4.25
originalTitle      Episode #4.25
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2007063, dtype: object

(9,)

tconst             tt11828476
titleType               movie
primaryTitle      Zulüm Treni
originalTitle     Zulüm Treni
isAdult                     0
startYear                1989
endYear                    \N
runtimeMinutes             68
genres                  Drama
Name: 2007064, dtype: object

(9,)

tconst            tt11828478
titleType              movie
primaryTitle        Magamról
originalTitle       Magamról
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Biography
Name: 2007065, dtype: object

(9,)

tconst                       tt1182847
titleType                    tvEpisode
primaryTitle              Episode #9.4
originalTitle             Episode #9.4
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007066, dtype: object

(9,)

tconst                                   tt11828480
titleType                                 tvEpisode
primaryTitle      Do You Believe in Life After Suds
originalTitle     Do You Believe in Life After Suds
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                    Game-Show
Name: 2007067, dtype: object

(9,)

tconst                        tt11828482
titleType                      tvEpisode
primaryTitle                      Rivals
originalTitle                     Rivals
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        24
genres            Animation,Comedy,Drama
Name: 2007068, dtype: object

(9,)

tconst                                        tt11828486
titleType                                          short
primaryTitle           It's Nothing, Only a Film Shot...
originalTitle     Den einai tipota, ena gyrisma einai...
isAdult                                                0
startYear                                           1991
endYear                                               \N
runtimeMinutes                                        11
genres                                 Documentary,Short
Name: 2007069, dtype: object

(9,)

tconst                            tt11828488
titleType                          tvEpisode
primaryTitle      Gender with Yulia Romanova
originalTitle     Gender with Yulia Romanova
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2007070, dtype: object

(9,)

tconst                       tt1182848
titleType                    tvEpisode
primaryTitle              Episode #9.5
originalTitle             Episode #9.5
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007071, dtype: object

(9,)

tconst                                                   tt11828490
titleType                                                     video
primaryTitle      100 Man Fuck, and 30 Cum Swallows Too! Miki Su...
originalTitle     100 nin kiri tsuide ni 30 hatsu mo tairyô gokk...
isAdult                                                           1
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                  150
genres                                                        Adult
Name: 2007072, dtype: object

(9,)

tconst              tt11828492
titleType             tvSeries
primaryTitle          Physical
originalTitle         Physical
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              30
genres            Comedy,Drama
Name: 2007073, dtype: object

(9,)

tconst                            tt11828494
titleType                          tvEpisode
primaryTitle      L'Age D'or with Jenna Suru
originalTitle     L'Age D'or with Jenna Suru
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2007074, dtype: object

(9,)

tconst             tt11828496
titleType               short
primaryTitle          Un père
originalTitle         Un père
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             22
genres            Drama,Short
Name: 2007075, dtype: object

(9,)

tconst                      tt11828498
titleType                    tvEpisode
primaryTitle      Milan AC vs AC Parma
originalTitle     Milan AC vs AC Parma
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      91
genres                           Sport
Name: 2007076, dtype: object

(9,)

tconst                       tt1182849
titleType                    tvEpisode
primaryTitle              Episode #9.6
originalTitle             Episode #9.6
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007077, dtype: object

(9,)

tconst              tt11828500
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1964
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2007078, dtype: object

(9,)

tconst             tt11828502
titleType           tvEpisode
primaryTitle             Love
originalTitle            Love
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2007079, dtype: object

(9,)

tconst                                tt11828504
titleType                              tvEpisode
primaryTitle      Daddy Issues with Andrew Pifko
originalTitle     Daddy Issues with Andrew Pifko
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2007080, dtype: object

(9,)

tconst                                 tt11828506
titleType                               tvEpisode
primaryTitle      Grand Hotel with Justina Adorno
originalTitle     Grand Hotel with Justina Adorno
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Talk-Show
Name: 2007081, dtype: object

(9,)

tconst                       tt1182850
titleType                    tvEpisode
primaryTitle              Episode #9.7
originalTitle             Episode #9.7
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      44
genres            Game-Show,Reality-TV
Name: 2007082, dtype: object

(9,)

tconst                        tt11828510
titleType                      tvEpisode
primaryTitle      Como están las mujeres
originalTitle     Como están las mujeres
isAdult                                0
startYear                           1996
endYear                               \N
runtimeMinutes                        \N
genres                                \N
Name: 2007083, dtype: object

(9,)

tconst                             tt11828512
titleType                               video
primaryTitle      Slow Loris Having Teeth Cut
originalTitle     Slow Loris Having Teeth Cut
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                              1
genres                      Documentary,Short
Name: 2007084, dtype: object

(9,)

tconst            tt11828514
titleType              movie
primaryTitle          Violet
originalTitle         Violet
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres              Thriller
Name: 2007085, dtype: object

(9,)

tconst                                      tt11828516
titleType                                    tvEpisode
primaryTitle      Temptation Island with Brittney Rose
originalTitle     Temptation Island with Brittney Rose
isAdult                                              0
startYear                                         2019
endYear                                             \N
runtimeMinutes                                      \N
genres                                       Talk-Show
Name: 2007086, dtype: object

(9,)

tconst                                tt11828518
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007087, dtype: object

(9,)

tconst                       tt1182851
titleType                    tvEpisode
primaryTitle              Episode #9.8
originalTitle             Episode #9.8
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      43
genres            Game-Show,Reality-TV
Name: 2007088, dtype: object

(9,)

tconst                tt11828522
titleType              tvEpisode
primaryTitle      John P Logsdon
originalTitle     John P Logsdon
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2007089, dtype: object

(9,)

tconst                                                   tt11828526
titleType                                                 tvEpisode
primaryTitle      I Love my Mum with Dom Lenoir, Tatjana Anders ...
originalTitle     I Love my Mum with Dom Lenoir, Tatjana Anders ...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2007090, dtype: object

(9,)

tconst                                                   tt11828528
titleType                                                 tvEpisode
primaryTitle      Just a Girl with Claudia McKell, Michael McKel...
originalTitle     Just a Girl with Claudia McKell, Michael McKel...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2007091, dtype: object

(9,)

tconst                       tt1182852
titleType                    tvEpisode
primaryTitle              Episode #9.9
originalTitle             Episode #9.9
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      42
genres            Game-Show,Reality-TV
Name: 2007092, dtype: object

(9,)

tconst                 tt11828530
titleType                   movie
primaryTitle      Yagmurlu Gecede
originalTitle     Yagmurlu Gecede
isAdult                         0
startYear                    2015
endYear                        \N
runtimeMinutes                 85
genres                      Drama
Name: 2007093, dtype: object

(9,)

tconst                  tt11828532
titleType                  tvMovie
primaryTitle      Jeden Donnerstag
originalTitle     Jeden Donnerstag
isAdult                          0
startYear                     1963
endYear                         \N
runtimeMinutes                  23
genres                          \N
Name: 2007094, dtype: object

(9,)

tconst                            tt11828538
titleType                          tvEpisode
primaryTitle      Ononokin with Jus Sargeant
originalTitle     Ononokin with Jus Sargeant
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2007095, dtype: object

(9,)

tconst            tt1182853
titleType          tvSeries
primaryTitle       JÅ-NE-TV
originalTitle      JÅ-NE-TV
isAdult                   0
startYear              2007
endYear                  \N
runtimeMinutes           \N
genres            Animation
Name: 2007096, dtype: object

(9,)

tconst                tt11828540
titleType                  short
primaryTitle               Flesh
originalTitle              Flesh
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                13
genres            Short,Thriller
Name: 2007097, dtype: object

(9,)

tconst                          tt11828542
titleType                        tvEpisode
primaryTitle      Deadly Circle of Friends
originalTitle     Deadly Circle of Friends
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                               Crime
Name: 2007098, dtype: object

(9,)

tconst                                    tt11828544
titleType                                  tvEpisode
primaryTitle      The Whistler with Fernando Gaviria
originalTitle     The Whistler with Fernando Gaviria
isAdult                                            0
startYear                                       2019
endYear                                           \N
runtimeMinutes                                    \N
genres                                     Talk-Show
Name: 2007099, dtype: object

(9,)

tconst                      tt11828546
titleType                    tvEpisode
primaryTitle      Choritrer Chalchitro
originalTitle     Choritrer Chalchitro
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                        Thriller
Name: 2007100, dtype: object

(9,)

tconst                                tt11828548
titleType                              tvEpisode
primaryTitle      The Creatress with Luke Guldan
originalTitle     The Creatress with Luke Guldan
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2007101, dtype: object

(9,)

tconst                    tt1182854
titleType                  tvSeries
primaryTitle          Kosketuksessa
originalTitle         Kosketuksessa
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Music
Name: 2007102, dtype: object

(9,)

tconst                 tt11828550
titleType               tvEpisode
primaryTitle      Jibito na Mrito
originalTitle     Jibito na Mrito
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                   Thriller
Name: 2007103, dtype: object

(9,)

tconst                                        tt11828552
titleType                                      tvEpisode
primaryTitle      The Creatress with Francis Lloyd Corby
originalTitle     The Creatress with Francis Lloyd Corby
isAdult                                                0
startYear                                           2019
endYear                                               \N
runtimeMinutes                                        \N
genres                                         Talk-Show
Name: 2007104, dtype: object

(9,)

tconst                tt11828554
titleType              tvEpisode
primaryTitle      Black Room III
originalTitle     Black Room III
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            Horror,Mystery
Name: 2007105, dtype: object

(9,)

tconst                                tt11828556
titleType                              tvEpisode
primaryTitle      The Creatress with Lindy Booth
originalTitle     The Creatress with Lindy Booth
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2007106, dtype: object

(9,)

tconst             tt11828558
titleType               short
primaryTitle            Yawp!
originalTitle           Yawp!
isAdult                     0
startYear                2010
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2007107, dtype: object

(9,)

tconst                tt1182855
titleType              tvSeries
primaryTitle      Leijonan kita
originalTitle     Leijonan kita
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2007108, dtype: object

(9,)

tconst                                tt11828560
titleType                                  video
primaryTitle      And Now... at Last - Sonya!!!!
originalTitle     And Now... at Last - Sonya!!!!
isAdult                                        0
startYear                                   2009
endYear                                       \N
runtimeMinutes                                 1
genres                         Documentary,Short
Name: 2007109, dtype: object

(9,)

tconst                tt11828562
titleType              tvEpisode
primaryTitle      Episode #1.160
originalTitle     Episode #1.160
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2007110, dtype: object

(9,)

tconst                                    tt11828564
titleType                                  tvEpisode
primaryTitle      The Mandalorian with Emily Swallow
originalTitle     The Mandalorian with Emily Swallow
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                     Talk-Show
Name: 2007111, dtype: object

(9,)

tconst                           tt11828566
titleType                         tvEpisode
primaryTitle      68 Whiskey with Linc Hand
originalTitle     68 Whiskey with Linc Hand
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2007112, dtype: object

(9,)

tconst                         tt11828568
titleType                       tvEpisode
primaryTitle              Jay Leno & Seal
originalTitle             Jay Leno & Seal
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres            Comedy,Music,Reality-TV
Name: 2007113, dtype: object

(9,)

tconst                      tt1182856
titleType                    tvSeries
primaryTitle      Maajussille morsian
originalTitle     Maajussille morsian
isAdult                             0
startYear                        2006
endYear                            \N
runtimeMinutes                     \N
genres                     Reality-TV
Name: 2007114, dtype: object

(9,)

tconst                      tt11828570
titleType                    tvEpisode
primaryTitle      Jiboner Shobdo Jobdo
originalTitle     Jiboner Shobdo Jobdo
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                        Thriller
Name: 2007115, dtype: object

(9,)

tconst                       tt11828572
titleType                     tvEpisode
primaryTitle      Ana with Olivia Dudek
originalTitle     Ana with Olivia Dudek
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2007116, dtype: object

(9,)

tconst                         tt11828574
titleType                       tvEpisode
primaryTitle      Ami ki khun korte pari?
originalTitle     Ami ki khun korte pari?
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                           Thriller
Name: 2007117, dtype: object

(9,)

tconst                tt11828576
titleType              tvEpisode
primaryTitle      Episode #1.279
originalTitle     Episode #1.279
isAdult                        0
startYear                   2003
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2007118, dtype: object

(9,)

tconst                      tt11828578
titleType                    tvEpisode
primaryTitle               Jasná výzva
originalTitle              Jasná výzva
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007119, dtype: object

(9,)

tconst               tt1182857
titleType             tvSeries
primaryTitle      Maria, Maria
originalTitle     Maria, Maria
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2007120, dtype: object

(9,)

tconst              tt11828580
titleType            tvEpisode
primaryTitle      Notun Otithi
originalTitle     Notun Otithi
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2007121, dtype: object

(9,)

tconst                      tt11828582
titleType                    tvEpisode
primaryTitle                      2723
originalTitle                     2723
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007122, dtype: object

(9,)

tconst                       tt11828584
titleType                     tvEpisode
primaryTitle      Boka Pahar Jaane Shob
originalTitle     Boka Pahar Jaane Shob
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                         Thriller
Name: 2007123, dtype: object

(9,)

tconst                   tt11828586
titleType                 tvEpisode
primaryTitle      Iti Sougata Sinha
originalTitle     Iti Sougata Sinha
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                     Thriller
Name: 2007124, dtype: object

(9,)

tconst             tt11828588
titleType               short
primaryTitle       Be with Me
originalTitle          Gyeote
isAdult                     0
startYear                2014
endYear                    \N
runtimeMinutes             19
genres            Drama,Short
Name: 2007125, dtype: object

(9,)

tconst                        tt1182858
titleType                      tvSeries
primaryTitle      Moderne Luftschlösser
originalTitle     Moderne Luftschlösser
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       26
genres                      Documentary
Name: 2007126, dtype: object

(9,)

tconst                      tt11828590
titleType                    tvEpisode
primaryTitle                      2724
originalTitle                     2724
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007127, dtype: object

(9,)

tconst                    tt11828592
titleType                  tvEpisode
primaryTitle             Épisode 390
originalTitle            Épisode 390
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    23
genres            Comedy,Crime,Drama
Name: 2007128, dtype: object

(9,)

tconst                      tt11828594
titleType                    tvEpisode
primaryTitle                      2726
originalTitle                     2726
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007129, dtype: object

(9,)

tconst              tt11828596
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              13
genres                   Drama
Name: 2007130, dtype: object

(9,)

tconst                       tt11828598
titleType                  tvMiniSeries
primaryTitle      The Faith Tucker Show
originalTitle     The Faith Tucker Show
isAdult                               0
startYear                          2017
endYear                              \N
runtimeMinutes                       \N
genres                           Comedy
Name: 2007131, dtype: object

(9,)

tconst               tt1182859
titleType             tvSeries
primaryTitle      Ota tai jätä
originalTitle     Ota tai jätä
isAdult                      0
startYear                 2007
endYear                   2007
runtimeMinutes              \N
genres               Game-Show
Name: 2007132, dtype: object

(9,)

tconst              tt11828600
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              16
genres                   Drama
Name: 2007133, dtype: object

(9,)

tconst                            tt11828602
titleType                          tvEpisode
primaryTitle                      Castingy 2
originalTitle                     Castingy 2
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007134, dtype: object

(9,)

tconst                      tt11828604
titleType                        short
primaryTitle      Once a Broken Cowboy
originalTitle     Once a Broken Cowboy
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres               Documentary,Short
Name: 2007135, dtype: object

(9,)

tconst                      tt11828606
titleType                    tvEpisode
primaryTitle                      2732
originalTitle                     2732
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007136, dtype: object

(9,)

tconst                       tt11828608
titleType                     tvEpisode
primaryTitle      Takze me tam nechces?
originalTitle     Takze me tam nechces?
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres             Comedy,Drama,Romance
Name: 2007137, dtype: object

(9,)

tconst                 tt1182860
titleType               tvSeries
primaryTitle      Under One Roof
originalTitle     Under One Roof
isAdult                        0
startYear                   2008
endYear                     2009
runtimeMinutes                \N
genres                    Comedy
Name: 2007138, dtype: object

(9,)

tconst             tt11828610
titleType           tvEpisode
primaryTitle      Nov lastnik
originalTitle     Nov lastnik
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                  Music
Name: 2007139, dtype: object

(9,)

tconst                tt11828614
titleType              tvEpisode
primaryTitle       Episode #1.20
originalTitle      Episode #1.20
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2007140, dtype: object

(9,)

tconst              tt11828616
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              17
genres                   Drama
Name: 2007141, dtype: object

(9,)

tconst               tt11828618
titleType              tvSeries
primaryTitle         De Hoppers
originalTitle        De Hoppers
isAdult                       0
startYear                  2019
endYear                    2020
runtimeMinutes               15
genres            Comedy,Family
Name: 2007142, dtype: object

(9,)

tconst                                                tt1182861
titleType                                             tvSpecial
primaryTitle      'Dat matscht so schön' - Eine Legende wird 30
originalTitle     'Dat matscht so schön' - Eine Legende wird 30
isAdult                                                       0
startYear                                                  2006
endYear                                                      \N
runtimeMinutes                                               60
genres                                        Documentary,Music
Name: 2007143, dtype: object

(9,)

tconst                          tt11828620
titleType                            short
primaryTitle      Human Resources of Ugago
originalTitle     Human Resources of Ugago
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          14
genres                        Comedy,Short
Name: 2007144, dtype: object

(9,)

tconst                            tt11828622
titleType                          tvEpisode
primaryTitle                     GrandFinále
originalTitle                    GrandFinále
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2007145, dtype: object

(9,)

tconst                    tt11828624
titleType                      short
primaryTitle      La Vie de Mastorna
originalTitle     La Vie de Mastorna
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                     5
genres                   Drama,Short
Name: 2007146, dtype: object

(9,)

tconst                      tt11828626
titleType                    tvEpisode
primaryTitle                      2733
originalTitle                     2733
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007147, dtype: object

(9,)

tconst              tt11828628
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              10
genres                   Drama
Name: 2007148, dtype: object

(9,)

tconst              tt1182862
titleType               short
primaryTitle      Amerigo Tot
originalTitle     Amerigo Tot
isAdult                     0
startYear                1970
endYear                    \N
runtimeMinutes             18
genres                  Short
Name: 2007149, dtype: object

(9,)

tconst                    tt11828630
titleType                      short
primaryTitle      Did You Hear That?
originalTitle     Did You Hear That?
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                  Horror,Short
Name: 2007150, dtype: object

(9,)

tconst             tt11828632
titleType               movie
primaryTitle           Engato
originalTitle          Engato
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             60
genres            Drama,Sport
Name: 2007151, dtype: object

(9,)

tconst                            tt11828634
titleType                              movie
primaryTitle      The Last Fortress: Hacibey
originalTitle               Son Kale Hacibey
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                           100
genres                               History
Name: 2007152, dtype: object

(9,)

tconst                 tt11828636
titleType                   movie
primaryTitle      A Space in Time
originalTitle     A Space in Time
isAdult                         0
startYear                    2021
endYear                        \N
runtimeMinutes                 88
genres                Documentary
Name: 2007153, dtype: object

(9,)

tconst                      tt11828638
titleType                    tvEpisode
primaryTitle                 Delivered
originalTitle                Delivered
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      79
genres            Drama,Fantasy,Horror
Name: 2007154, dtype: object

(9,)

tconst                      tt1182863
titleType                       short
primaryTitle      L'amico dello sposo
originalTitle     L'amico dello sposo
isAdult                             0
startYear                        1912
endYear                            \N
runtimeMinutes                     \N
genres                          Short
Name: 2007155, dtype: object

(9,)

tconst                      tt11828640
titleType                    tvEpisode
primaryTitle                  Good Boy
originalTitle                 Good Boy
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      88
genres            Drama,Fantasy,Horror
Name: 2007156, dtype: object

(9,)

tconst                      tt11828642
titleType                    tvEpisode
primaryTitle              Pooka Lives!
originalTitle             Pooka Lives!
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      80
genres            Drama,Fantasy,Horror
Name: 2007157, dtype: object

(9,)

tconst                      tt11828644
titleType                    tvEpisode
primaryTitle                 Tentacles
originalTitle                Tentacles
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      84
genres            Drama,Fantasy,Horror
Name: 2007158, dtype: object

(9,)

tconst                tt11828646
titleType              tvEpisode
primaryTitle      Episode #8.141
originalTitle     Episode #8.141
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007159, dtype: object

(9,)

tconst                      tt11828648
titleType                    tvEpisode
primaryTitle                Blood Moon
originalTitle               Blood Moon
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      82
genres            Drama,Fantasy,Horror
Name: 2007160, dtype: object

(9,)

tconst                       tt1182864
titleType                        short
primaryTitle      The Apple of His Eye
originalTitle     The Apple of His Eye
isAdult                              0
startYear                         1911
endYear                             \N
runtimeMinutes                      \N
genres                     Drama,Short
Name: 2007161, dtype: object

(9,)

tconst                tt11828650
titleType              tvEpisode
primaryTitle      Episode #8.142
originalTitle     Episode #8.142
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007162, dtype: object

(9,)

tconst                      tt11828652
titleType                    tvEpisode
primaryTitle                      2741
originalTitle                     2741
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007163, dtype: object

(9,)

tconst                tt11828654
titleType              tvEpisode
primaryTitle      Episode #8.126
originalTitle     Episode #8.126
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007164, dtype: object

(9,)

tconst                tt11828656
titleType              tvEpisode
primaryTitle      Episode #8.127
originalTitle     Episode #8.127
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007165, dtype: object

(9,)

tconst                tt11828658
titleType              tvEpisode
primaryTitle      Episode #8.128
originalTitle     Episode #8.128
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007166, dtype: object

(9,)

tconst            tt1182865
titleType             movie
primaryTitle        Autodoc
originalTitle       Autodoc
isAdult                   0
startYear              2009
endYear                  \N
runtimeMinutes           98
genres                Drama
Name: 2007167, dtype: object

(9,)

tconst                tt11828660
titleType              tvEpisode
primaryTitle      Episode #8.129
originalTitle     Episode #8.129
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007168, dtype: object

(9,)

tconst                tt11828662
titleType              tvEpisode
primaryTitle      Episode #8.130
originalTitle     Episode #8.130
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007169, dtype: object

(9,)

tconst              tt11828664
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes               8
genres                   Drama
Name: 2007170, dtype: object

(9,)

tconst              tt11828668
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              10
genres                   Drama
Name: 2007171, dtype: object

(9,)

tconst                                      tt1182866
titleType                                     tvMovie
primaryTitle      Baltijsk - Letzte Trophäe Russlands
originalTitle     Baltijsk - Letzte Trophäe Russlands
isAdult                                             0
startYear                                        2004
endYear                                            \N
runtimeMinutes                                     45
genres                                    Documentary
Name: 2007172, dtype: object

(9,)

tconst                           tt11828670
titleType                             movie
primaryTitle         The End of an Eternity
originalTitle     To telos mias aioniotitas
isAdult                                   0
startYear                              1998
endYear                                  \N
runtimeMinutes                           58
genres                          Documentary
Name: 2007173, dtype: object

(9,)

tconst                                   tt11828672
titleType                                     short
primaryTitle      Wah-Tah! Breve storia di un amore
originalTitle     Wah-Tah! Breve storia di un amore
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                 Comedy,Short
Name: 2007174, dtype: object

(9,)

tconst                      tt11828674
titleType                    tvEpisode
primaryTitle                      4002
originalTitle                     4002
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007175, dtype: object

(9,)

tconst                     tt11828676
titleType                       short
primaryTitle             Hand in Hand
originalTitle            Hand in Hand
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                      4
genres            Comedy,Horror,Short
Name: 2007176, dtype: object

(9,)

tconst                   tt11828678
titleType                     short
primaryTitle      Silent But Deadly
originalTitle     Silent But Deadly
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                 Comedy,Short
Name: 2007177, dtype: object

(9,)

tconst                                                    tt1182867
titleType                                                   tvMovie
primaryTitle      Baltischer Cocktail - Kaliningrader Umweltprob...
originalTitle     Baltischer Cocktail - Kaliningrader Umweltprob...
isAdult                                                           0
startYear                                                      2004
endYear                                                          \N
runtimeMinutes                                                   30
genres                                                  Documentary
Name: 2007178, dtype: object

(9,)

tconst                         tt11828680
titleType                           video
primaryTitle      Waco Texas: apocalipsis
originalTitle     Waco Texas: apocalipsis
isAdult                                 0
startYear                            1993
endYear                                \N
runtimeMinutes                         \N
genres                      Action,Horror
Name: 2007179, dtype: object

(9,)

tconst              tt11828682
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              12
genres                   Drama
Name: 2007180, dtype: object

(9,)

tconst             tt11828684
titleType               video
primaryTitle         Girasoli
originalTitle        Girasoli
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes             \N
genres            Music,Short
Name: 2007181, dtype: object

(9,)

tconst              tt11828686
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              12
genres                   Drama
Name: 2007182, dtype: object

(9,)

tconst                               tt11828688
titleType                                 video
primaryTitle      Lost in Paradise: Oggi nevica
originalTitle     Lost in Paradise: Oggi nevica
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                              Music,Short
Name: 2007183, dtype: object

(9,)

tconst                   tt1182868
titleType                    video
primaryTitle      A Better Place 2
originalTitle     A Better Place 2
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2007184, dtype: object

(9,)

tconst            tt11828690
titleType              short
primaryTitle              02
originalTitle             02
isAdult                    0
startYear               2006
endYear                   \N
runtimeMinutes             4
genres                 Short
Name: 2007185, dtype: object

(9,)

tconst               tt11828692
titleType                 movie
primaryTitle      Child Machine
originalTitle     Child Machine
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Sci-Fi
Name: 2007186, dtype: object

(9,)

tconst            tt11828694
titleType              short
primaryTitle              01
originalTitle             01
isAdult                    0
startYear               2006
endYear                   \N
runtimeMinutes             5
genres                 Short
Name: 2007187, dtype: object

(9,)

tconst                tt11828696
titleType                  short
primaryTitle      A/Spring/Today
originalTitle     A/Spring/Today
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                 8
genres                     Short
Name: 2007188, dtype: object

(9,)

tconst            tt11828698
titleType              short
primaryTitle         Neither
originalTitle        Neither
isAdult                    0
startYear               2013
endYear                   \N
runtimeMinutes            10
genres                 Short
Name: 2007189, dtype: object

(9,)

tconst                 tt1182869
titleType                  video
primaryTitle      A Better Place
originalTitle     A Better Place
isAdult                        0
startYear                   2007
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2007190, dtype: object

(9,)

tconst               tt11828700
titleType                 video
primaryTitle      Ti proteggerò
originalTitle     Ti proteggerò
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes               \N
genres              Music,Short
Name: 2007191, dtype: object

(9,)

tconst                            tt11828702
titleType                          tvEpisode
primaryTitle      Episode dated 9 March 2006
originalTitle     Episode dated 9 March 2006
isAdult                                    0
startYear                               2006
endYear                                   \N
runtimeMinutes                            \N
genres                  Game-Show,Reality-TV
Name: 2007192, dtype: object

(9,)

tconst            tt11828706
titleType              short
primaryTitle      Skyscraper
originalTitle     Skyscraper
isAdult                    0
startYear               2001
endYear                   \N
runtimeMinutes             8
genres                 Short
Name: 2007193, dtype: object

(9,)

tconst                                                   tt11828708
titleType                                                 tvEpisode
primaryTitle      EXTRAIT DU FILM "DES HOMMES D'HONNEUR" de ROB ...
originalTitle     EXTRAIT DU FILM "DES HOMMES D'HONNEUR" de ROB ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2007194, dtype: object

(9,)

tconst             tt1182870
titleType              video
primaryTitle      Black Star
originalTitle     Black Star
isAdult                    0
startYear               2006
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2007195, dtype: object

(9,)

tconst              tt11828712
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2007196, dtype: object

(9,)

tconst              tt11828714
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2007197, dtype: object

(9,)

tconst              tt11828716
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2007198, dtype: object

(9,)

tconst               tt1182871
titleType                video
primaryTitle      Black Star 2
originalTitle     Black Star 2
isAdult                      0
startYear                 2006
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2007199, dtype: object

(9,)

tconst              tt11828720
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2007200, dtype: object

(9,)

tconst            tt11828722
titleType              movie
primaryTitle           Shiyû
originalTitle          Shiyû
isAdult                    0
startYear               1936
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2007201, dtype: object

(9,)

tconst              tt11828724
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2007202, dtype: object

(9,)

tconst              tt11828728
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2007203, dtype: object

(9,)

tconst                    tt1182872
titleType                     short
primaryTitle        Boil Your Water
originalTitle       Boil Your Water
isAdult                           0
startYear                      1911
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2007204, dtype: object

(9,)

tconst            tt11828730
titleType           tvSeries
primaryTitle      Forceclash
originalTitle     Forceclash
isAdult                    0
startYear               2012
endYear                   \N
runtimeMinutes            \N
genres               Fantasy
Name: 2007205, dtype: object

(9,)

tconst               tt11828732
titleType             tvEpisode
primaryTitle      Episode #2.36
originalTitle     Episode #2.36
isAdult                       0
startYear                  1989
endYear                      \N
runtimeMinutes               \N
genres               Crime,News
Name: 2007206, dtype: object

(9,)

tconst                        tt11828736
titleType                        tvMovie
primaryTitle      Seht mich verschwinden
originalTitle     Seht mich verschwinden
isAdult                                0
startYear                           2014
endYear                               \N
runtimeMinutes                        52
genres             Biography,Documentary
Name: 2007207, dtype: object

(9,)

tconst                   tt11828738
titleType                     short
primaryTitle       Finding My Tirbe
originalTitle      Finding My Tirbe
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2007208, dtype: object

(9,)

tconst               tt1182873
titleType                video
primaryTitle      Campus Girls
originalTitle     Campus Girls
isAdult                      0
startYear                 2004
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2007209, dtype: object

(9,)

tconst                                                   tt11828740
titleType                                                 tvEpisode
primaryTitle      EXTRAIT DU FILM "LE PROFESSIONNEL" DE GEORGES ...
originalTitle     EXTRAIT DU FILM "LE PROFESSIONNEL" DE GEORGES ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2007210, dtype: object

(9,)

tconst            tt11828742
titleType              movie
primaryTitle      Vlad I Mir
originalTitle     Vlad I Mir
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2007211, dtype: object

(9,)

tconst                      tt11828744
titleType                        short
primaryTitle                      SC 4
originalTitle                     SC 4
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       8
genres            Drama,Short,Thriller
Name: 2007212, dtype: object

(9,)

tconst               tt11828746
titleType             tvEpisode
primaryTitle      Sweet Sixteen
originalTitle     Sweet Sixteen
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres            Comedy,Family
Name: 2007213, dtype: object

(9,)

tconst                   tt11828748
titleType                     movie
primaryTitle      Daigaku no shishî
originalTitle     Daigaku no shishî
isAdult                           0
startYear                      1935
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2007214, dtype: object

(9,)

tconst              tt1182874
titleType               video
primaryTitle      Campus Love
originalTitle     Campus Love
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2007215, dtype: object

(9,)

tconst                                                 tt11828750
titleType                                               tvEpisode
primaryTitle      EXTRAIT DU FILM "TOP GUN" DE TONY SCOTT... 1986
originalTitle     EXTRAIT DU FILM "TOP GUN" DE TONY SCOTT... 1986
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                  Talk-Show
Name: 2007216, dtype: object

(9,)

tconst              tt11828752
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              10
genres                   Drama
Name: 2007217, dtype: object

(9,)

tconst              tt11828758
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres                   Drama
Name: 2007218, dtype: object

(9,)

tconst                tt1182875
titleType                 video
primaryTitle      Campus Love 2
originalTitle     Campus Love 2
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2007219, dtype: object

(9,)

tconst            tt11828760
titleType              movie
primaryTitle         Curtido
originalTitle        Curtido
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2007220, dtype: object

(9,)

tconst                                          tt11828762
titleType                                          tvMovie
primaryTitle      Brücken zum Menschen: Rundfunk Fernsehen
originalTitle     Brücken zum Menschen: Rundfunk Fernsehen
isAdult                                                  0
startYear                                             1966
endYear                                                 \N
runtimeMinutes                                          24
genres                                         Documentary
Name: 2007221, dtype: object

(9,)

tconst            tt11828764
titleType          tvEpisode
primaryTitle      Girl crush
originalTitle     Girl crush
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes             9
genres                Family
Name: 2007222, dtype: object

(9,)

tconst              tt11828766
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              13
genres                   Drama
Name: 2007223, dtype: object

(9,)

tconst                   tt11828768
titleType                     short
primaryTitle                Liberty
originalTitle               Liberty
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                    8
genres            Documentary,Short
Name: 2007224, dtype: object

(9,)

tconst            tt1182876
titleType             short
primaryTitle      Capriccio
originalTitle     Capriccio
isAdult                   0
startYear              1970
endYear                  \N
runtimeMinutes           18
genres                Short
Name: 2007225, dtype: object

(9,)

tconst               tt11828770
titleType                 video
primaryTitle          Lipstick+
originalTitle         Lipstick+
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Mystery,Short
Name: 2007226, dtype: object

(9,)

tconst              tt11828772
titleType            tvEpisode
primaryTitle      Episode #2.9
originalTitle     Episode #2.9
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              11
genres                   Drama
Name: 2007227, dtype: object

(9,)

tconst               tt11828774
titleType             tvEpisode
primaryTitle      Episode #2.38
originalTitle     Episode #2.38
isAdult                       0
startYear                  1989
endYear                      \N
runtimeMinutes               \N
genres               Crime,News
Name: 2007228, dtype: object

(9,)

tconst                      tt11828778
titleType                        video
primaryTitle      A. Australis Feeding
originalTitle     A. Australis Feeding
isAdult                              0
startYear                         2012
endYear                             \N
runtimeMinutes                       2
genres               Documentary,Short
Name: 2007229, dtype: object

(9,)

tconst                            tt1182877
titleType                             movie
primaryTitle      Il castello delle tenebre
originalTitle     Il castello delle tenebre
isAdult                                   0
startYear                              1921
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2007230, dtype: object

(9,)

tconst                              tt11828780
titleType                            tvEpisode
primaryTitle      Episode dated 3 October 2017
originalTitle     Episode dated 3 October 2017
isAdult                                      0
startYear                                 2017
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2007231, dtype: object

(9,)

tconst               tt11828782
titleType             tvEpisode
primaryTitle      Naina's Visit
originalTitle     Naina's Visit
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007232, dtype: object

(9,)

tconst               tt11828784
titleType             tvEpisode
primaryTitle      Episode #2.10
originalTitle     Episode #2.10
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               17
genres                    Drama
Name: 2007233, dtype: object

(9,)

tconst                                               tt11828786
titleType                                                 video
primaryTitle      Male Baby Desert Horned Viper Assist Feeding!
originalTitle     Male Baby Desert Horned Viper Assist Feeding!
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               22
genres                                        Documentary,Short
Name: 2007234, dtype: object

(9,)

tconst               tt11828788
titleType                 movie
primaryTitle         Les pedres
originalTitle        Les pedres
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007235, dtype: object

(9,)

tconst                             tt1182878
titleType                              movie
primaryTitle      La cavalcata del capriccio
originalTitle     La cavalcata del capriccio
isAdult                                    0
startYear                               1921
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2007236, dtype: object

(9,)

tconst                 tt11828790
titleType                   movie
primaryTitle      Tokai no kanshô
originalTitle     Tokai no kanshô
isAdult                         0
startYear                    1934
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2007237, dtype: object

(9,)

tconst                      tt11828792
titleType                        short
primaryTitle      Seven Days of Winter
originalTitle     Sete Dias de Inverno
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      15
genres                           Short
Name: 2007238, dtype: object

(9,)

tconst                     tt11828794
titleType                       short
primaryTitle                The Loner
originalTitle               The Loner
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                      6
genres            Drama,Romance,Short
Name: 2007239, dtype: object

(9,)

tconst                                                 tt11828796
titleType                                                   video
primaryTitle      Female Baby Desert Horned Viper Assist Feeding!
originalTitle     Female Baby Desert Horned Viper Assist Feeding!
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 10
genres                                          Documentary,Short
Name: 2007240, dtype: object

(9,)

tconst                                                   tt11828798
titleType                                                 tvEpisode
primaryTitle      EXTRAIT DU FILM "THE DARK KNIGHT" DE CHRISTOPH...
originalTitle     EXTRAIT DU FILM "THE DARK KNIGHT" DE CHRISTOPH...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2007241, dtype: object

(9,)

tconst                                   tt1182879
titleType                                    movie
primaryTitle      Il delitto della villa solitaria
originalTitle     Il delitto della villa solitaria
isAdult                                          0
startYear                                     1916
endYear                                         \N
runtimeMinutes                                  \N
genres                                          \N
Name: 2007242, dtype: object

(9,)

tconst                     tt11828800
titleType                       short
primaryTitle          Gute Träume.mp3
originalTitle         Gute Träume.mp3
isAdult                             0
startYear                        2013
endYear                            \N
runtimeMinutes                     17
genres            Comedy,Sci-Fi,Short
Name: 2007243, dtype: object

(9,)

tconst                             tt11828804
titleType                               video
primaryTitle      Green Tree Frogs and Anoles
originalTitle     Green Tree Frogs and Anoles
isAdult                                     0
startYear                                2012
endYear                                    \N
runtimeMinutes                              2
genres                      Documentary,Short
Name: 2007244, dtype: object

(9,)

tconst                                                   tt11828806
titleType                                                 tvEpisode
primaryTitle      EXTRAIT DU FILM "AU DELA DE NOS REVES" DE VINC...
originalTitle     EXTRAIT DU FILM "AU DELA DE NOS REVES" DE VINC...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2007245, dtype: object

(9,)

tconst                                           tt1182880
titleType                                            video
primaryTitle      Devo: Live in the Land of the Rising Sun
originalTitle     Devo: Live in the Land of the Rising Sun
isAdult                                                  0
startYear                                             2007
endYear                                                 \N
runtimeMinutes                                          75
genres                                   Documentary,Music
Name: 2007246, dtype: object

(9,)

tconst                      tt11828810
titleType                        short
primaryTitle                Study Date
originalTitle               Study Date
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       3
genres            Comedy,Romance,Short
Name: 2007247, dtype: object

(9,)

tconst                                tt11828812
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2007248, dtype: object

(9,)

tconst                                                   tt11828814
titleType                                                 tvEpisode
primaryTitle      EXTRAIT DU FILM "L'OMBRE BLANCHE" DE JOHN GRAY...
originalTitle     EXTRAIT DU FILM "L'OMBRE BLANCHE" DE JOHN GRAY...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2007249, dtype: object

(9,)

tconst                                       tt11828816
titleType                                         video
primaryTitle      What Happens After You Hunt a Coyote?
originalTitle     What Happens After You Hunt a Coyote?
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                        8
genres                                Documentary,Short
Name: 2007250, dtype: object

(9,)

tconst                                                    tt1182881
titleType                                                   tvMovie
primaryTitle      Diese Lust sich zu verbeugen - Pressefreiheit ...
originalTitle     Diese Lust sich zu verbeugen - Pressefreiheit ...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   30
genres                                                  Documentary
Name: 2007251, dtype: object

(9,)

tconst               tt11828820
titleType             tvEpisode
primaryTitle       Episode #1.1
originalTitle      Episode #1.1
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007252, dtype: object

(9,)

tconst            tt11828822
titleType          tvEpisode
primaryTitle          Racism
originalTitle         Racism
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            60
genres             Talk-Show
Name: 2007253, dtype: object

(9,)

tconst               tt11828824
titleType             tvEpisode
primaryTitle       Episode #1.2
originalTitle      Episode #1.2
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007254, dtype: object

(9,)

tconst               tt11828826
titleType             tvEpisode
primaryTitle       Episode #1.3
originalTitle      Episode #1.3
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007255, dtype: object

(9,)

tconst               tt11828828
titleType             tvEpisode
primaryTitle       Episode #1.4
originalTitle      Episode #1.4
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007256, dtype: object

(9,)

tconst                          tt1182882
titleType                           movie
primaryTitle      Un dramma in wagon-lits
originalTitle     Un dramma in wagon-lits
isAdult                                 0
startYear                            1919
endYear                                \N
runtimeMinutes                         \N
genres                                 \N
Name: 2007257, dtype: object

(9,)

tconst                         tt11828832
titleType                       tvEpisode
primaryTitle      Un tranquillo filippino
originalTitle     Un tranquillo filippino
isAdult                                 0
startYear                            2016
endYear                                \N
runtimeMinutes                         \N
genres                         Crime,News
Name: 2007258, dtype: object

(9,)

tconst               tt11828834
titleType             tvEpisode
primaryTitle       Episode #1.5
originalTitle      Episode #1.5
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007259, dtype: object

(9,)

tconst                      tt1182883
titleType                       movie
primaryTitle      La duchessa di Nala
originalTitle     La duchessa di Nala
isAdult                             0
startYear                        1920
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2007260, dtype: object

(9,)

tconst                                                   tt11828840
titleType                                                     movie
primaryTitle      Diana Grace Needs to Get Fucked by New Dick to...
originalTitle     Diana Grace Needs to Get Fucked by New Dick to...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2007261, dtype: object

(9,)

tconst               tt11828842
titleType             tvEpisode
primaryTitle       Episode #1.6
originalTitle      Episode #1.6
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007262, dtype: object

(9,)

tconst               tt11828844
titleType             tvEpisode
primaryTitle       Episode #1.7
originalTitle      Episode #1.7
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007263, dtype: object

(9,)

tconst               tt11828846
titleType             tvEpisode
primaryTitle       Episode #1.8
originalTitle      Episode #1.8
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007264, dtype: object

(9,)

tconst                          tt11828848
titleType                        tvEpisode
primaryTitle      Una difficile convivenza
originalTitle     Una difficile convivenza
isAdult                                  0
startYear                             2016
endYear                                 \N
runtimeMinutes                          \N
genres                          Crime,News
Name: 2007265, dtype: object

(9,)

tconst                       tt1182884
titleType                        movie
primaryTitle            Dulha Mil Gaya
originalTitle           Dulha Mil Gaya
isAdult                              0
startYear                         2010
endYear                             \N
runtimeMinutes                     152
genres            Comedy,Drama,Romance
Name: 2007266, dtype: object

(9,)

tconst               tt11828850
titleType                 short
primaryTitle      Une antiquité
originalTitle     Une antiquité
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes                2
genres              Drama,Short
Name: 2007267, dtype: object

(9,)

tconst               tt11828852
titleType             tvEpisode
primaryTitle       Episode #1.9
originalTitle      Episode #1.9
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007268, dtype: object

(9,)

tconst               tt11828856
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007269, dtype: object

(9,)

tconst                                  tt11828858
titleType                                tvEpisode
primaryTitle      Luxury Home in Pacific Palisades
originalTitle     Luxury Home in Pacific Palisades
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                  Reality-TV
Name: 2007270, dtype: object

(9,)

tconst              tt1182885
titleType               short
primaryTitle          Enemies
originalTitle         Enemies
isAdult                     0
startYear                1911
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2007271, dtype: object

(9,)

tconst               tt11828860
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007272, dtype: object

(9,)

tconst               tt11828862
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007273, dtype: object

(9,)

tconst                             tt11828864
titleType                           tvEpisode
primaryTitle      Tarantini. Un anno da leone
originalTitle     Tarantini. Un anno da leone
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                             Crime,News
Name: 2007274, dtype: object

(9,)

tconst               tt11828866
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007275, dtype: object

(9,)

tconst                             tt11828868
titleType                               movie
primaryTitle      Juan Goytisolo (medineando)
originalTitle     Juan Goytisolo (medineando)
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                            Documentary
Name: 2007276, dtype: object

(9,)

tconst                      tt1182886
titleType                       movie
primaryTitle             The Superman
originalTitle     I figli di Sansonia
isAdult                             0
startYear                        1919
endYear                            \N
runtimeMinutes                     \N
genres                   Comedy,Drama
Name: 2007277, dtype: object

(9,)

tconst               tt11828872
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007278, dtype: object

(9,)

tconst               tt11828874
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007279, dtype: object

(9,)

tconst               tt11828876
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007280, dtype: object

(9,)

tconst               tt11828878
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007281, dtype: object

(9,)

tconst                       tt1182887
titleType                      tvMovie
primaryTitle       Flirting with Forty
originalTitle      Flirting with Forty
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      87
genres            Comedy,Drama,Romance
Name: 2007282, dtype: object

(9,)

tconst               tt11828880
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007283, dtype: object

(9,)

tconst               tt11828882
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007284, dtype: object

(9,)

tconst               tt11828884
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007285, dtype: object

(9,)

tconst                      tt11828886
titleType                        video
primaryTitle         VIXX: Voodoo Doll
originalTitle     VIXX: Jeoju Inhyeong
isAdult                              0
startYear                         2013
endYear                             \N
runtimeMinutes                       4
genres            Fantasy,Horror,Music
Name: 2007286, dtype: object

(9,)

tconst               tt11828888
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007287, dtype: object

(9,)

tconst                         tt1182888
titleType                          movie
primaryTitle      La forza di un ricordo
originalTitle     La forza di un ricordo
isAdult                                0
startYear                           1920
endYear                               \N
runtimeMinutes                        \N
genres                                \N
Name: 2007288, dtype: object

(9,)

tconst               tt11828890
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007289, dtype: object

(9,)

tconst               tt11828892
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007290, dtype: object

(9,)

tconst               tt11828894
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007291, dtype: object

(9,)

tconst               tt11828896
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007292, dtype: object

(9,)

tconst                       tt11828898
titleType                         short
primaryTitle                 Salon Styx
originalTitle                Salon Styx
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                        6
genres            Comedy,Short,Thriller
Name: 2007293, dtype: object

(9,)

tconst                 tt1182889
titleType                  video
primaryTitle      Friend of Mine
originalTitle     Friend of Mine
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2007294, dtype: object

(9,)

tconst             tt11828900
titleType           tvEpisode
primaryTitle       First Food
originalTitle      First Food
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2007295, dtype: object

(9,)

tconst                  tt11828902
titleType                tvEpisode
primaryTitle      Hårløs og håbløs
originalTitle     Hårløs og håbløs
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  10
genres                      Family
Name: 2007296, dtype: object

(9,)

tconst             tt11828904
titleType           tvEpisode
primaryTitle         Crawling
originalTitle        Crawling
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2007297, dtype: object

(9,)

tconst             tt11828906
titleType           tvEpisode
primaryTitle            Sleep
originalTitle           Sleep
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2007298, dtype: object

(9,)

tconst                    tt11828908
titleType                      short
primaryTitle                  Reboot
originalTitle                 Reboot
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    15
genres            Drama,Sci-Fi,Short
Name: 2007299, dtype: object

(9,)

tconst                   tt1182890
titleType                    video
primaryTitle      Friend of Mine 2
originalTitle     Friend of Mine 2
isAdult                          0
startYear                     2004
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2007300, dtype: object

(9,)

tconst                                        tt11828910
titleType                                   tvMiniSeries
primaryTitle      Rap Trip: Underground Scenes Uncovered
originalTitle     Rap Trip: Underground Scenes Uncovered
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        \N
genres                                       Documentary
Name: 2007301, dtype: object

(9,)

tconst             tt11828912
titleType           tvEpisode
primaryTitle      First Steps
originalTitle     First Steps
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2007302, dtype: object

(9,)

tconst                       tt11828914
titleType                     tvEpisode
primaryTitle      Bisnestä pettämisellä
originalTitle     Bisnestä pettämisellä
isAdult                               0
startYear                          2013
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2007303, dtype: object

(9,)

tconst                                      tt11828916
titleType                                        video
primaryTitle      Got Questions Ask Away. Short Stream
originalTitle     Got Questions Ask Away. Short Stream
isAdult                                              0
startYear                                         2019
endYear                                             \N
runtimeMinutes                                      87
genres                                              \N
Name: 2007304, dtype: object

(9,)

tconst                   tt11828918
titleType                 tvEpisode
primaryTitle      Kaljahanat kiinni
originalTitle     Kaljahanat kiinni
isAdult                           0
startYear                      2013
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2007305, dtype: object

(9,)

tconst                         tt1182891
titleType                          movie
primaryTitle      Il fu signor me stesso
originalTitle     Il fu signor me stesso
isAdult                                0
startYear                           1921
endYear                               \N
runtimeMinutes                        \N
genres                                \N
Name: 2007306, dtype: object

(9,)

tconst               tt11828920
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007307, dtype: object

(9,)

tconst               tt11828922
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007308, dtype: object

(9,)

tconst                             tt11828924
titleType                           tvEpisode
primaryTitle                   Rene Belbenoit
originalTitle                  Rene Belbenoit
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2007309, dtype: object

(9,)

tconst                      tt11828926
titleType                    tvEpisode
primaryTitle      Kannabista kansalle!
originalTitle     Kannabista kansalle!
isAdult                              0
startYear                         2013
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2007310, dtype: object

(9,)

tconst               tt11828928
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007311, dtype: object

(9,)

tconst                 tt1182892
titleType                  movie
primaryTitle      Grappolo d'oro
originalTitle     Grappolo d'oro
isAdult                        0
startYear                   1922
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007312, dtype: object

(9,)

tconst                                tt11828930
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007313, dtype: object

(9,)

tconst               tt11828932
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007314, dtype: object

(9,)

tconst                                tt11828934
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007315, dtype: object

(9,)

tconst               tt11828936
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007316, dtype: object

(9,)

tconst                    tt11828938
titleType                  tvEpisode
primaryTitle      Paavin paikka auki
originalTitle     Paavin paikka auki
isAdult                            0
startYear                       2013
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2007317, dtype: object

(9,)

tconst            tt1182893
titleType             short
primaryTitle       Groteszk
originalTitle      Groteszk
isAdult                   0
startYear              1963
endYear                  \N
runtimeMinutes           11
genres                Short
Name: 2007318, dtype: object

(9,)

tconst                        tt11828940
titleType                          video
primaryTitle      Columbian Tegu Feeding
originalTitle     Columbian Tegu Feeding
isAdult                                0
startYear                           2014
endYear                               \N
runtimeMinutes                         1
genres                 Documentary,Short
Name: 2007319, dtype: object

(9,)

tconst                           tt11828942
titleType                         tvEpisode
primaryTitle      Liivijengit levittäytyvät
originalTitle     Liivijengit levittäytyvät
isAdult                                   0
startYear                              2013
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2007320, dtype: object

(9,)

tconst                                tt11828944
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007321, dtype: object

(9,)

tconst              tt11828946
titleType                short
primaryTitle         Sanctorum
originalTitle        Sanctorum
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Sci-Fi,Short
Name: 2007322, dtype: object

(9,)

tconst               tt11828948
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007323, dtype: object

(9,)

tconst                tt1182894
titleType               tvMovie
primaryTitle      The Great Tom
originalTitle     Der große Tom
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               90
genres                    Drama
Name: 2007324, dtype: object

(9,)

tconst                            tt11828950
titleType                          tvEpisode
primaryTitle      Kotimaisen ruoan metsästys
originalTitle     Kotimaisen ruoan metsästys
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2007325, dtype: object

(9,)

tconst               tt11828952
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007326, dtype: object

(9,)

tconst                                               tt11828954
titleType                                             tvEpisode
primaryTitle      Opintolaina - kiristämistä vai kannustamista?
originalTitle     Opintolaina - kiristämistä vai kannustamista?
isAdult                                                       0
startYear                                                  2013
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                Talk-Show
Name: 2007327, dtype: object

(9,)

tconst               tt11828956
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007328, dtype: object

(9,)

tconst               tt11828958
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007329, dtype: object

(9,)

tconst             tt1182895
titleType              movie
primaryTitle      A Harmadik
originalTitle     A Harmadik
isAdult                    0
startYear               1971
endYear                   \N
runtimeMinutes            50
genres                    \N
Name: 2007330, dtype: object

(9,)

tconst                              tt11828960
titleType                            tvEpisode
primaryTitle      Taistelu kalastuskiintiöistä
originalTitle     Taistelu kalastuskiintiöistä
isAdult                                      0
startYear                                 2013
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2007331, dtype: object

(9,)

tconst               tt11828962
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007332, dtype: object

(9,)

tconst                   tt11828964
titleType                     video
primaryTitle        Snake Feedings!
originalTitle       Snake Feedings!
isAdult                           0
startYear                      2014
endYear                          \N
runtimeMinutes                    1
genres            Documentary,Short
Name: 2007333, dtype: object

(9,)

tconst               tt11828966
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007334, dtype: object

(9,)

tconst               tt11828968
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007335, dtype: object

(9,)

tconst                tt1182896
titleType                 movie
primaryTitle            Harvest
originalTitle           Harvest
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               73
genres            Drama,Musical
Name: 2007336, dtype: object

(9,)

tconst               tt11828970
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007337, dtype: object

(9,)

tconst                             tt11828972
titleType                           tvEpisode
primaryTitle      Episode dated 12 April 2013
originalTitle     Episode dated 12 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2007338, dtype: object

(9,)

tconst               tt11828974
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007339, dtype: object

(9,)

tconst               tt11828976
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007340, dtype: object

(9,)

tconst                        tt11828978
titleType                      tvEpisode
primaryTitle      Kamppailu Saamenmaasta
originalTitle     Kamppailu Saamenmaasta
isAdult                                0
startYear                           2013
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2007341, dtype: object

(9,)

tconst                      tt1182897
titleType                       short
primaryTitle      The Hazard of Youth
originalTitle     The Hazard of Youth
isAdult                             0
startYear                        1913
endYear                            \N
runtimeMinutes                     11
genres                    Drama,Short
Name: 2007342, dtype: object

(9,)

tconst               tt11828980
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007343, dtype: object

(9,)

tconst                   tt11828982
titleType                 tvEpisode
primaryTitle      Flamingos a Go-Go
originalTitle     Flamingos a Go-Go
isAdult                           0
startYear                      2015
endYear                          \N
runtimeMinutes                   11
genres                    Animation
Name: 2007344, dtype: object

(9,)

tconst               tt11828984
titleType             tvEpisode
primaryTitle      Episode #1.42
originalTitle     Episode #1.42
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007345, dtype: object

(9,)

tconst               tt11828986
titleType             tvEpisode
primaryTitle      Episode #1.43
originalTitle     Episode #1.43
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007346, dtype: object

(9,)

tconst               tt11828988
titleType             tvEpisode
primaryTitle      Episode #1.44
originalTitle     Episode #1.44
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007347, dtype: object

(9,)

tconst                     tt1182898
titleType                    tvMovie
primaryTitle      Hela världens Arja
originalTitle     Hela världens Arja
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres             Documentary,Music
Name: 2007348, dtype: object

(9,)

tconst                tt11828990
titleType                  movie
primaryTitle      Kaishain kakka
originalTitle     Kaishain kakka
isAdult                        0
startYear                   1934
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2007349, dtype: object

(9,)

tconst               tt11828992
titleType             tvEpisode
primaryTitle      Episode #1.45
originalTitle     Episode #1.45
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007350, dtype: object

(9,)

tconst                                 tt11828994
titleType                               tvSpecial
primaryTitle      Dynamo: Every trick in the book
originalTitle     Dynamo: Every trick in the book
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2007351, dtype: object

(9,)

tconst                       tt11828996
titleType                     tvEpisode
primaryTitle      Verkossa vaaniva viha
originalTitle     Verkossa vaaniva viha
isAdult                               0
startYear                          2013
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2007352, dtype: object

(9,)

tconst                  tt11828998
titleType                    short
primaryTitle      Sub-subconscious
originalTitle     Sub-subconscious
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  31
genres                 Drama,Short
Name: 2007353, dtype: object

(9,)

tconst              tt1182899
titleType             tvMovie
primaryTitle      Hopeanuolet
originalTitle     Hopeanuolet
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes            140
genres                  Drama
Name: 2007354, dtype: object

(9,)

tconst                                                tt11829000
titleType                                                  video
primaryTitle      Mojave Rattlesnake First Meal After Brumation!
originalTitle     Mojave Rattlesnake First Meal After Brumation!
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                 6
genres                                         Documentary,Short
Name: 2007355, dtype: object

(9,)

tconst                      tt11829002
titleType                    tvEpisode
primaryTitle              Episode #1.2
originalTitle             Episode #1.2
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      43
genres            Crime,Drama,Thriller
Name: 2007356, dtype: object

(9,)

tconst                              tt11829004
titleType                            tvEpisode
primaryTitle      Koulussa ei saa epäonnistua!
originalTitle     Koulussa ei saa epäonnistua!
isAdult                                      0
startYear                                 2013
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2007357, dtype: object

(9,)

tconst                               tt11829006
titleType                             tvEpisode
primaryTitle      Episode dated 1 February 1977
originalTitle     Episode dated 1 February 1977
isAdult                                       0
startYear                                  1977
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2007358, dtype: object

(9,)

tconst                           tt11829008
titleType                         tvEpisode
primaryTitle      Episode dated 10 May 2013
originalTitle     Episode dated 10 May 2013
isAdult                                   0
startYear                              2013
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2007359, dtype: object

(9,)

tconst                          tt1182900
titleType                           short
primaryTitle      How Edam Cheese Is Made
originalTitle     How Edam Cheese Is Made
isAdult                                 0
startYear                            1911
endYear                                \N
runtimeMinutes                         \N
genres                  Documentary,Short
Name: 2007360, dtype: object

(9,)

tconst                     tt11829010
titleType                   tvEpisode
primaryTitle      Sairaan ihana koira
originalTitle     Sairaan ihana koira
isAdult                             0
startYear                        2013
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2007361, dtype: object

(9,)

tconst                      tt11829012
titleType                    tvEpisode
primaryTitle              Episode #1.3
originalTitle             Episode #1.3
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      43
genres            Crime,Drama,Thriller
Name: 2007362, dtype: object

(9,)

tconst                               tt11829014
titleType                             tvEpisode
primaryTitle      Kilpailu uhkapelimarkkinoista
originalTitle     Kilpailu uhkapelimarkkinoista
isAdult                                       0
startYear                                  2013
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2007363, dtype: object

(9,)

tconst                             tt11829016
titleType                           tvEpisode
primaryTitle                Marjorie Lawrence
originalTitle               Marjorie Lawrence
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2007364, dtype: object

(9,)

tconst                           tt11829018
titleType                         tvEpisode
primaryTitle      Lakiin kahlittu sukupuoli
originalTitle     Lakiin kahlittu sukupuoli
isAdult                                   0
startYear                              2013
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2007365, dtype: object

(9,)

tconst                                  tt1182901
titleType                               tvSpecial
primaryTitle      Immer wieder geht die Sonne auf
originalTitle     Immer wieder geht die Sonne auf
isAdult                                         0
startYear                                    1999
endYear                                        \N
runtimeMinutes                                 60
genres                 Comedy,Documentary,History
Name: 2007366, dtype: object

(9,)

tconst                      tt11829020
titleType                    tvEpisode
primaryTitle      Isänmaa ilman inttiä
originalTitle     Isänmaa ilman inttiä
isAdult                              0
startYear                         2013
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2007367, dtype: object

(9,)

tconst                                             tt11829022
titleType                                               video
primaryTitle      Billiam Eats a Chicks and Rat Combo Platter
originalTitle     Billiam Eats a Chicks and Rat Combo Platter
isAdult                                                     0
startYear                                                2013
endYear                                                    \N
runtimeMinutes                                             14
genres                                      Documentary,Short
Name: 2007368, dtype: object

(9,)

tconst                     tt11829026
titleType                   tvEpisode
primaryTitle      Unelmien Guggenheim
originalTitle     Unelmien Guggenheim
isAdult                             0
startYear                        2013
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2007369, dtype: object

(9,)

tconst                      tt11829028
titleType                    tvEpisode
primaryTitle             Episode #1.33
originalTitle            Episode #1.33
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007370, dtype: object

(9,)

tconst                        tt1182902
titleType                         short
primaryTitle      Indian Army Exercises
originalTitle     Indian Army Exercises
isAdult                               0
startYear                          1910
endYear                              \N
runtimeMinutes                       \N
genres                Documentary,Short
Name: 2007371, dtype: object

(9,)

tconst            tt11829030
titleType              movie
primaryTitle        Crede-Mi
originalTitle       Crede-Mi
isAdult                    0
startYear               1996
endYear                   \N
runtimeMinutes            75
genres                 Drama
Name: 2007372, dtype: object

(9,)

tconst                      tt11829032
titleType                    tvEpisode
primaryTitle      Liha pois lautaselta
originalTitle     Liha pois lautaselta
isAdult                              0
startYear                         2013
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2007373, dtype: object

(9,)

tconst                      tt11829034
titleType                    tvEpisode
primaryTitle              Episode #1.4
originalTitle             Episode #1.4
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      43
genres            Crime,Drama,Thriller
Name: 2007374, dtype: object

(9,)

tconst                      tt11829036
titleType                    tvEpisode
primaryTitle             Episode #1.34
originalTitle            Episode #1.34
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007375, dtype: object

(9,)

tconst                               tt11829038
titleType                             tvEpisode
primaryTitle      Episode dated 11 October 2013
originalTitle     Episode dated 11 October 2013
isAdult                                       0
startYear                                  2013
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2007376, dtype: object

(9,)

tconst                    tt1182903
titleType                     short
primaryTitle      Insects That Sing
originalTitle     Insects That Sing
isAdult                           0
startYear                      1913
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2007377, dtype: object

(9,)

tconst                      tt11829040
titleType                    tvEpisode
primaryTitle             Episode #1.35
originalTitle            Episode #1.35
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007378, dtype: object

(9,)

tconst                  tt11829042
titleType                tvEpisode
primaryTitle      Veriset vaatteet
originalTitle     Veriset vaatteet
isAdult                          0
startYear                     2013
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2007379, dtype: object

(9,)

tconst                      tt11829044
titleType                    tvEpisode
primaryTitle             Episode #1.36
originalTitle            Episode #1.36
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007380, dtype: object

(9,)

tconst                         tt11829046
titleType                       tvEpisode
primaryTitle          Booba in the Future
originalTitle         Booba in the Future
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres            Animation,Comedy,Family
Name: 2007381, dtype: object

(9,)

tconst                    tt11829048
titleType                      short
primaryTitle                Fabulous
originalTitle               Fabulous
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                     1
genres            Comedy,Drama,Short
Name: 2007382, dtype: object

(9,)

tconst                                                    tt1182904
titleType                                                     short
primaryTitle      The Joining of the Oceans, the Panama Canal, O...
originalTitle     The Joining of the Oceans, the Panama Canal, O...
isAdult                                                           0
startYear                                                      1913
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Documentary,Short
Name: 2007383, dtype: object

(9,)

tconst                      tt11829050
titleType                    tvEpisode
primaryTitle              Episode #1.6
originalTitle             Episode #1.6
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      45
genres            Crime,Drama,Thriller
Name: 2007384, dtype: object

(9,)

tconst                      tt11829052
titleType                    tvEpisode
primaryTitle             Episode #1.37
originalTitle            Episode #1.37
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007385, dtype: object

(9,)

tconst                tt11829054
titleType                  movie
primaryTitle      Minakmî shinjû
originalTitle     Minakmî shinjû
isAdult                        0
startYear                   1934
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2007386, dtype: object

(9,)

tconst                                                 tt11829056
titleType                                                   video
primaryTitle      Blue Speckled Rattlesnake Venomous Live Feeding
originalTitle     Blue Speckled Rattlesnake Venomous Live Feeding
isAdult                                                         0
startYear                                                    2019
endYear                                                        \N
runtimeMinutes                                                 15
genres                                          Documentary,Short
Name: 2007387, dtype: object

(9,)

tconst                      tt11829058
titleType                    tvEpisode
primaryTitle             Episode #1.38
originalTitle            Episode #1.38
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007388, dtype: object

(9,)

tconst                          tt1182905
titleType                           short
primaryTitle      The Justice of Claudius
originalTitle     The Justice of Claudius
isAdult                                 0
startYear                            1911
endYear                                \N
runtimeMinutes                         \N
genres                        Drama,Short
Name: 2007389, dtype: object

(9,)

tconst                      tt11829060
titleType                    tvEpisode
primaryTitle             Episode #1.39
originalTitle            Episode #1.39
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007390, dtype: object

(9,)

tconst                      tt11829062
titleType                    tvEpisode
primaryTitle              Episode #1.7
originalTitle             Episode #1.7
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      44
genres            Crime,Drama,Thriller
Name: 2007391, dtype: object

(9,)

tconst                             tt11829064
titleType                           tvEpisode
primaryTitle                      Belle Baker
originalTitle                     Belle Baker
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2007392, dtype: object

(9,)

tconst                      tt11829066
titleType                    tvEpisode
primaryTitle             Episode #1.40
originalTitle            Episode #1.40
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007393, dtype: object

(9,)

tconst                                tt11829068
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2007394, dtype: object

(9,)

tconst               tt1182906
titleType              tvMovie
primaryTitle             Katve
originalTitle            Katve
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              70
genres            Comedy,Drama
Name: 2007395, dtype: object

(9,)

tconst                                tt11829072
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007396, dtype: object

(9,)

tconst                                     tt11829074
titleType                                       movie
primaryTitle      Like a Dog or a Boat, you tether it
originalTitle     Like a Dog or a Boat, you tether it
isAdult                                             0
startYear                                        2018
endYear                                            \N
runtimeMinutes                                     85
genres                                    Documentary
Name: 2007397, dtype: object

(9,)

tconst                      tt11829076
titleType                    tvEpisode
primaryTitle             Episode #1.41
originalTitle            Episode #1.41
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007398, dtype: object

(9,)

tconst                                tt11829078
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2007399, dtype: object

(9,)

tconst                       tt1182907
titleType                        movie
primaryTitle              The Kind One
originalTitle             The Kind One
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2007400, dtype: object

(9,)

tconst                      tt11829080
titleType                    tvEpisode
primaryTitle              Episode #1.8
originalTitle             Episode #1.8
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      44
genres            Crime,Drama,Thriller
Name: 2007401, dtype: object

(9,)

tconst               tt11829082
titleType             tvEpisode
primaryTitle       Episode #1.1
originalTitle      Episode #1.1
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               45
genres            Drama,Romance
Name: 2007402, dtype: object

(9,)

tconst                      tt11829084
titleType                    tvEpisode
primaryTitle             Episode #1.42
originalTitle            Episode #1.42
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007403, dtype: object

(9,)

tconst               tt11829086
titleType             tvEpisode
primaryTitle       Episode #1.2
originalTitle      Episode #1.2
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               47
genres            Drama,Romance
Name: 2007404, dtype: object

(9,)

tconst               tt11829088
titleType             tvEpisode
primaryTitle       Episode #1.3
originalTitle      Episode #1.3
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               46
genres            Drama,Romance
Name: 2007405, dtype: object

(9,)

tconst                     tt1182908
titleType                      movie
primaryTitle                Krazzy 4
originalTitle               Krazzy 4
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                   110
genres            Comedy,Crime,Drama
Name: 2007406, dtype: object

(9,)

tconst                      tt11829090
titleType                    tvEpisode
primaryTitle             Episode #1.43
originalTitle            Episode #1.43
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007407, dtype: object

(9,)

tconst                tt11829092
titleType              tvEpisode
primaryTitle      Episode #2.121
originalTitle     Episode #2.121
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2007408, dtype: object

(9,)

tconst               tt11829094
titleType             tvEpisode
primaryTitle       Episode #1.4
originalTitle      Episode #1.4
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               47
genres            Drama,Romance
Name: 2007409, dtype: object

(9,)

tconst                      tt11829096
titleType                    tvEpisode
primaryTitle             Episode #1.44
originalTitle            Episode #1.44
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007410, dtype: object

(9,)

tconst               tt11829098
titleType             tvEpisode
primaryTitle       Episode #1.5
originalTitle      Episode #1.5
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007411, dtype: object

(9,)

tconst                                                    tt1182909
titleType                                                   tvMovie
primaryTitle      Kreuzzug durch Sibirien - Mit orthodoxen Pries...
originalTitle     Kreuzzug durch Sibirien - Mit orthodoxen Pries...
isAdult                                                           0
startYear                                                      2007
endYear                                                          \N
runtimeMinutes                                                   30
genres                                                  Documentary
Name: 2007412, dtype: object

(9,)

tconst                         tt11829100
titleType                       tvEpisode
primaryTitle      Kova kisa korkeakouluun
originalTitle     Kova kisa korkeakouluun
isAdult                                 0
startYear                            2013
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2007413, dtype: object

(9,)

tconst               tt11829102
titleType             tvEpisode
primaryTitle       Episode #1.6
originalTitle      Episode #1.6
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007414, dtype: object

(9,)

tconst               tt11829104
titleType             tvEpisode
primaryTitle       Episode #1.7
originalTitle      Episode #1.7
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007415, dtype: object

(9,)

tconst                      tt11829106
titleType                    tvEpisode
primaryTitle             Episode #1.45
originalTitle            Episode #1.45
isAdult                              0
startYear                         1983
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007416, dtype: object

(9,)

tconst                      tt11829108
titleType                    tvEpisode
primaryTitle             Episode #2.26
originalTitle            Episode #2.26
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007417, dtype: object

(9,)

tconst                         tt1182910
titleType                          short
primaryTitle      Lai Chyeim (Good Luck)
originalTitle     Lai Chyeim (Good Luck)
isAdult                                0
startYear                           1911
endYear                               \N
runtimeMinutes                        \N
genres                       Drama,Short
Name: 2007418, dtype: object

(9,)

tconst               tt11829110
titleType             tvEpisode
primaryTitle       Episode #1.8
originalTitle      Episode #1.8
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007419, dtype: object

(9,)

tconst               tt11829112
titleType             tvEpisode
primaryTitle       Episode #1.9
originalTitle      Episode #1.9
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007420, dtype: object

(9,)

tconst                      tt11829114
titleType                    tvEpisode
primaryTitle             Episode #1.46
originalTitle            Episode #1.46
isAdult                              0
startYear                         1984
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007421, dtype: object

(9,)

tconst                      tt11829116
titleType                    tvEpisode
primaryTitle             Episode #2.27
originalTitle            Episode #2.27
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007422, dtype: object

(9,)

tconst                                tt11829118
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2007423, dtype: object

(9,)

tconst             tt1182911
titleType            tvMovie
primaryTitle       Liliova 4
originalTitle      Liliova 4
isAdult                    0
startYear               1996
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2007424, dtype: object

(9,)

tconst               tt11829120
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007425, dtype: object

(9,)

tconst                                tt11829122
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2007426, dtype: object

(9,)

tconst                      tt11829124
titleType                    tvEpisode
primaryTitle             Episode #2.28
originalTitle            Episode #2.28
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007427, dtype: object

(9,)

tconst                        tt11829126
titleType                      tvEpisode
primaryTitle      Ruoka pois roskiksesta
originalTitle     Ruoka pois roskiksesta
isAdult                                0
startYear                           2013
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2007428, dtype: object

(9,)

tconst                      tt11829128
titleType                    tvEpisode
primaryTitle             Episode #1.47
originalTitle            Episode #1.47
isAdult                              0
startYear                         1984
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007429, dtype: object

(9,)

tconst                      tt1182912
titleType                       short
primaryTitle                     Lisa
originalTitle                    Lisa
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     18
genres            Drama,Fantasy,Short
Name: 2007430, dtype: object

(9,)

tconst                      tt11829130
titleType                    tvEpisode
primaryTitle             Episode #2.29
originalTitle            Episode #2.29
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007431, dtype: object

(9,)

tconst                      tt11829132
titleType                    tvEpisode
primaryTitle             Episode #1.48
originalTitle            Episode #1.48
isAdult                              0
startYear                         1984
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007432, dtype: object

(9,)

tconst                      tt11829134
titleType                    tvEpisode
primaryTitle             Episode #2.30
originalTitle            Episode #2.30
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007433, dtype: object

(9,)

tconst                    tt11829136
titleType                      short
primaryTitle      Jump into the wild
originalTitle     Jump into the wild
isAdult                            0
startYear                       2012
endYear                           \N
runtimeMinutes                    \N
genres                  Comedy,Short
Name: 2007434, dtype: object

(9,)

tconst                             tt11829138
titleType                           tvEpisode
primaryTitle               George Gregory Jr.
originalTitle              George Gregory Jr.
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2007435, dtype: object

(9,)

tconst                        tt1182913
titleType                         short
primaryTitle      Little Miss Bountiful
originalTitle     Little Miss Bountiful
isAdult                               0
startYear                          1914
endYear                              \N
runtimeMinutes                       \N
genres                     Comedy,Short
Name: 2007436, dtype: object

(9,)

tconst               tt11829140
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007437, dtype: object

(9,)

tconst              tt11829142
titleType                movie
primaryTitle            Not Me
originalTitle           Not Me
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes             105
genres            Comedy,Drama
Name: 2007438, dtype: object

(9,)

tconst                      tt11829144
titleType                    tvEpisode
primaryTitle             Episode #1.49
originalTitle            Episode #1.49
isAdult                              0
startYear                         1984
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007439, dtype: object

(9,)

tconst               tt11829146
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007440, dtype: object

(9,)

tconst                                       tt11829148
titleType                                     tvEpisode
primaryTitle      Poliiseja vai rosvoja - tapaus Aarnio
originalTitle     Poliiseja vai rosvoja - tapaus Aarnio
isAdult                                               0
startYear                                          2013
endYear                                              \N
runtimeMinutes                                       \N
genres                                        Talk-Show
Name: 2007441, dtype: object

(9,)

tconst                  tt1182914
titleType                   short
primaryTitle      Love's Oblivion
originalTitle     Love's Oblivion
isAdult                         0
startYear                    1914
endYear                        \N
runtimeMinutes                 \N
genres               Comedy,Short
Name: 2007442, dtype: object

(9,)

tconst               tt11829150
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007443, dtype: object

(9,)

tconst               tt11829152
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2007444, dtype: object

(9,)

tconst                      tt11829154
titleType                    tvEpisode
primaryTitle             Episode #1.50
originalTitle            Episode #1.50
isAdult                              0
startYear                         1984
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007445, dtype: object

(9,)

tconst               tt11829156
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007446, dtype: object

(9,)

tconst               tt11829158
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007447, dtype: object

(9,)

tconst                            tt1182915
titleType                             short
primaryTitle      Mary Long and Sammy Short
originalTitle      Tom Pouce suit une femme
isAdult                                   0
startYear                              1910
endYear                                  \N
runtimeMinutes                            3
genres                         Comedy,Short
Name: 2007448, dtype: object

(9,)

tconst                      tt11829160
titleType                    tvEpisode
primaryTitle      Suomi säästökuurilla
originalTitle     Suomi säästökuurilla
isAdult                              0
startYear                         2013
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2007449, dtype: object

(9,)

tconst               tt11829162
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007450, dtype: object

(9,)

tconst               tt11829164
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007451, dtype: object

(9,)

tconst               tt11829166
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007452, dtype: object

(9,)

tconst                             tt11829168
titleType                           tvEpisode
primaryTitle                    Frankie Laine
originalTitle                   Frankie Laine
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2007453, dtype: object

(9,)

tconst                      tt1182916
titleType                       movie
primaryTitle      I milioni di Saetta
originalTitle     I milioni di Saetta
isAdult                             0
startYear                        1923
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2007454, dtype: object

(9,)

tconst               tt11829170
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007455, dtype: object

(9,)

tconst                        tt11829172
titleType                      tvEpisode
primaryTitle      Uskonnonopetus uusiksi
originalTitle     Uskonnonopetus uusiksi
isAdult                                0
startYear                           2013
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2007456, dtype: object

(9,)

tconst               tt11829174
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007457, dtype: object

(9,)

tconst                             tt11829176
titleType                           tvEpisode
primaryTitle            Dr. George Foote Bond
originalTitle           Dr. George Foote Bond
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2007458, dtype: object

(9,)

tconst                                             tt11829178
titleType                                           tvEpisode
primaryTitle      Nick Fuentes Banned from YT for Wrong Think
originalTitle     Nick Fuentes Banned from YT for Wrong Think
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             \N
genres                                         News,Talk-Show
Name: 2007459, dtype: object

(9,)

tconst                                 tt1182917
titleType                                  movie
primaryTitle      Il mistero dell'auto in fiamme
originalTitle     Il mistero dell'auto in fiamme
isAdult                                        0
startYear                                   1921
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007460, dtype: object

(9,)

tconst                               tt11829182
titleType                             tvEpisode
primaryTitle      Episode dated 1 February 2020
originalTitle     Episode dated 1 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2007461, dtype: object

(9,)

tconst             tt11829186
titleType               short
primaryTitle              Why
originalTitle             Why
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             14
genres            Drama,Short
Name: 2007462, dtype: object

(9,)

tconst                                                   tt11829188
titleType                                                 tvEpisode
primaryTitle      En ville ou à la campagne: les maires sur tous...
originalTitle     En ville ou à la campagne: les maires sur tous...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                  Documentary
Name: 2007463, dtype: object

(9,)

tconst                        tt1182918
titleType                         movie
primaryTitle      Il mistero della mano
originalTitle     Il mistero della mano
isAdult                               0
startYear                          1921
endYear                              \N
runtimeMinutes                       \N
genres                               \N
Name: 2007464, dtype: object

(9,)

tconst                                tt11829190
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007465, dtype: object

(9,)

tconst                     tt11829192
titleType                   tvEpisode
primaryTitle      Squeetie Pie Stream
originalTitle     Squeetie Pie Stream
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                 News,Talk-Show
Name: 2007466, dtype: object

(9,)

tconst              tt11829194
titleType                short
primaryTitle      Disconnected
originalTitle     Disconnected
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              16
genres             Drama,Short
Name: 2007467, dtype: object

(9,)

tconst            tt11829196
titleType          tvEpisode
primaryTitle         Spa Day
originalTitle        Spa Day
isAdult                    1
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2007468, dtype: object

(9,)

tconst                                        tt11829198
titleType                                      tvEpisode
primaryTitle      Las Vegas Dem Debate WINNERS & LOSERS!
originalTitle     Las Vegas Dem Debate WINNERS & LOSERS!
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        \N
genres                                              News
Name: 2007469, dtype: object

(9,)

tconst                                                    tt1182919
titleType                                                     short
primaryTitle                     Native Industries in Cochin, China
originalTitle     La Cochinchine et les petites industries indig...
isAdult                                                           0
startYear                                                      1910
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Documentary,Short
Name: 2007470, dtype: object

(9,)

tconst                                             tt11829200
titleType                                           tvSpecial
primaryTitle      The FA Cup Third Round Liverpool vs Everton
originalTitle     The FA Cup Third Round Liverpool vs Everton
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             95
genres                                                 Action
Name: 2007471, dtype: object

(9,)

tconst                               tt11829202
titleType                             tvEpisode
primaryTitle         Le goût de la Haute-Savoie
originalTitle        Le goût de la Haute-Savoie
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres            Adventure,Documentary,History
Name: 2007472, dtype: object

(9,)

tconst               tt11829204
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007473, dtype: object

(9,)

tconst                tt11829206
titleType              tvEpisode
primaryTitle      Sterling Times
originalTitle     Sterling Times
isAdult                        1
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2007474, dtype: object

(9,)

tconst               tt11829208
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007475, dtype: object

(9,)

tconst                        tt1182920
titleType                         short
primaryTitle      Nice and Its Environs
originalTitle     Nice and Its Environs
isAdult                               0
startYear                          1913
endYear                              \N
runtimeMinutes                       \N
genres                Documentary,Short
Name: 2007476, dtype: object

(9,)

tconst                tt11829210
titleType              tvEpisode
primaryTitle      Episode #22.21
originalTitle     Episode #22.21
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            News,Talk-Show
Name: 2007477, dtype: object

(9,)

tconst              tt11829212
titleType            tvEpisode
primaryTitle      Episode #3.1
originalTitle     Episode #3.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Sport
Name: 2007478, dtype: object

(9,)

tconst               tt11829214
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007479, dtype: object

(9,)

tconst                       tt11829216
titleType                     tvEpisode
primaryTitle      She Speaks Fluent Cum
originalTitle     She Speaks Fluent Cum
isAdult                               1
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                            Adult
Name: 2007480, dtype: object

(9,)

tconst               tt11829218
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007481, dtype: object

(9,)

tconst                  tt1182921
titleType                   movie
primaryTitle                Ninja
originalTitle               Ninja
isAdult                         0
startYear                    2009
endYear                        \N
runtimeMinutes                 86
genres            Action,Thriller
Name: 2007482, dtype: object

(9,)

tconst             tt11829220
titleType           tvEpisode
primaryTitle      Jojo Rabbit
originalTitle     Jojo Rabbit
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                     \N
Name: 2007483, dtype: object

(9,)

tconst               tt11829222
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007484, dtype: object

(9,)

tconst               tt11829224
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007485, dtype: object

(9,)

tconst               tt11829226
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007486, dtype: object

(9,)

tconst                    tt11829228
titleType                  tvEpisode
primaryTitle      Talking to Dr Duke
originalTitle     Talking to Dr Duke
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                News,Talk-Show
Name: 2007487, dtype: object

(9,)

tconst                tt1182922
titleType                 movie
primaryTitle      Occhi dipinti
originalTitle     Occhi dipinti
isAdult                       0
startYear                  1920
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2007488, dtype: object

(9,)

tconst               tt11829230
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007489, dtype: object

(9,)

tconst               tt11829232
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007490, dtype: object

(9,)

tconst                  tt11829234
titleType                tvEpisode
primaryTitle               Game On
originalTitle              Game On
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                   7
genres            Animation,Comedy
Name: 2007491, dtype: object

(9,)

tconst               tt11829236
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007492, dtype: object

(9,)

tconst               tt11829238
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007493, dtype: object

(9,)

tconst                 tt11829240
titleType                   movie
primaryTitle      Qualcosa rimane
originalTitle     Qualcosa rimane
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 70
genres                Documentary
Name: 2007494, dtype: object

(9,)

tconst               tt11829242
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007495, dtype: object

(9,)

tconst               tt11829244
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007496, dtype: object

(9,)

tconst               tt11829246
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007497, dtype: object

(9,)

tconst               tt11829248
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007498, dtype: object

(9,)

tconst                    tt1182924
titleType                     movie
primaryTitle      A Pain in the Ass
originalTitle           L'emmerdeur
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   86
genres                       Comedy
Name: 2007499, dtype: object

(9,)

tconst                                                   tt11829250
titleType                                                 tvEpisode
primaryTitle      Elizabeth Warren Knocks Out Bloomberg with One...
originalTitle     Elizabeth Warren Knocks Out Bloomberg with One...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2007500, dtype: object

(9,)

tconst               tt11829252
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007501, dtype: object

(9,)

tconst               tt11829254
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007502, dtype: object

(9,)

tconst               tt11829256
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007503, dtype: object

(9,)

tconst                                             tt11829258
titleType                                           tvEpisode
primaryTitle      Måste Kalle swisha Kakan för missade poäng?
originalTitle     Måste Kalle swisha Kakan för missade poäng?
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             \N
genres                                              Game-Show
Name: 2007504, dtype: object

(9,)

tconst                 tt1182925
titleType                  movie
primaryTitle      París Marsella
originalTitle     París Marsella
isAdult                        0
startYear                   2005
endYear                       \N
runtimeMinutes                70
genres               Documentary
Name: 2007505, dtype: object

(9,)

tconst                                  tt11829260
titleType                                tvEpisode
primaryTitle      Varför tröttnar Karin på Anders?
originalTitle     Varför tröttnar Karin på Anders?
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                   Game-Show
Name: 2007506, dtype: object

(9,)

tconst               tt11829262
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007507, dtype: object

(9,)

tconst                                            tt11829264
titleType                                          tvEpisode
primaryTitle      Rebusar, hologram-kändisar och kända bögar
originalTitle     Rebusar, hologram-kändisar och kända bögar
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                             Game-Show
Name: 2007508, dtype: object

(9,)

tconst                                  tt11829266
titleType                                tvEpisode
primaryTitle      Rafflande match om semifinalspel
originalTitle     Rafflande match om semifinalspel
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                   Game-Show
Name: 2007509, dtype: object

(9,)

tconst               tt11829268
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007510, dtype: object

(9,)

tconst                    tt1182926
titleType                     short
primaryTitle       Pastime in Chile
originalTitle      Pastime in Chile
isAdult                           0
startYear                      1911
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2007511, dtype: object

(9,)

tconst                                    tt11829270
titleType                                      video
primaryTitle      Giant White Knee Tarantula Feeding
originalTitle     Giant White Knee Tarantula Feeding
isAdult                                            0
startYear                                       2014
endYear                                           \N
runtimeMinutes                                     1
genres                             Documentary,Short
Name: 2007512, dtype: object

(9,)

tconst            tt11829272
titleType            tvMovie
primaryTitle        Falstaff
originalTitle       Falstaff
isAdult                    0
startYear               1963
endYear                   \N
runtimeMinutes           130
genres                 Music
Name: 2007513, dtype: object

(9,)

tconst                tt11829276
titleType                  short
primaryTitle      Light & Motion
originalTitle     Light & Motion
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Short
Name: 2007514, dtype: object

(9,)

tconst                              tt11829278
titleType                                video
primaryTitle      Northern Pacific Rattlesnake
originalTitle     Northern Pacific Rattlesnake
isAdult                                      0
startYear                                 2014
endYear                                     \N
runtimeMinutes                               1
genres                       Documentary,Short
Name: 2007515, dtype: object

(9,)

tconst               tt1182927
titleType                movie
primaryTitle      Per un bacio
originalTitle     Per un bacio
isAdult                      0
startYear                 1923
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2007516, dtype: object

(9,)

tconst                          tt11829280
titleType                            video
primaryTitle      Mojave Green Rattlesnake
originalTitle     Mojave Green Rattlesnake
isAdult                                  0
startYear                             2014
endYear                                 \N
runtimeMinutes                           1
genres                   Documentary,Short
Name: 2007517, dtype: object

(9,)

tconst                                             tt11829282
titleType                                           tvEpisode
primaryTitle      Dane Clark, Pat Englund, Florence Pritchett
originalTitle     Dane Clark, Pat Englund, Florence Pritchett
isAdult                                                     0
startYear                                                1954
endYear                                                    \N
runtimeMinutes                                             \N
genres                                       Family,Talk-Show
Name: 2007518, dtype: object

(9,)

tconst              tt11829284
titleType            tvEpisode
primaryTitle      Caradepiedra
originalTitle     Caradepiedra
isAdult                      0
startYear                 1982
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2007519, dtype: object

(9,)

tconst              tt11829286
titleType                movie
primaryTitle         Dear Ones
originalTitle           Bliscy
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              74
genres            Comedy,Drama
Name: 2007520, dtype: object

(9,)

tconst                                                   tt11829288
titleType                                                 tvEpisode
primaryTitle      MASSIVE Numbers of Democrats Are Quitting the ...
originalTitle     MASSIVE Numbers of Democrats Are Quitting the ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2007521, dtype: object

(9,)

tconst                        tt1182928
titleType                         movie
primaryTitle      La perla insanguinata
originalTitle     La perla insanguinata
isAdult                               0
startYear                          1920
endYear                              \N
runtimeMinutes                       \N
genres                               \N
Name: 2007522, dtype: object

(9,)

tconst                          tt11829290
titleType                         tvSeries
primaryTitle      Lafazkan Kalimah Cintamu
originalTitle     Lafazkan Kalimah Cintamu
isAdult                                  0
startYear                             2018
endYear                               2018
runtimeMinutes                          48
genres                       Drama,Romance
Name: 2007523, dtype: object

(9,)

tconst                                         tt11829292
titleType                                        tvSeries
primaryTitle      China's Mega Projects 3: China Revealed
originalTitle     China's Mega Projects 3: China Revealed
isAdult                                                 0
startYear                                            2017
endYear                                                \N
runtimeMinutes                                         \N
genres                                        Documentary
Name: 2007524, dtype: object

(9,)

tconst                               tt11829294
titleType                                 video
primaryTitle      New California Kingsnakes!!!!
originalTitle     New California Kingsnakes!!!!
isAdult                                       0
startYear                                  2012
endYear                                      \N
runtimeMinutes                                2
genres                        Documentary,Short
Name: 2007525, dtype: object

(9,)

tconst                   tt11829296
titleType                     video
primaryTitle              My Snakes
originalTitle             My Snakes
isAdult                           0
startYear                      2013
endYear                          \N
runtimeMinutes                    4
genres            Documentary,Short
Name: 2007526, dtype: object

(9,)

tconst                               tt1182929
titleType                                short
primaryTitle      Pilio, mnimes kai paradoseis
originalTitle     Pilio, mnimes kai paradoseis
isAdult                                      0
startYear                                 1978
endYear                                     \N
runtimeMinutes                              20
genres                       Documentary,Short
Name: 2007527, dtype: object

(9,)

tconst             tt11829300
titleType           tvEpisode
primaryTitle      Sommer 1963
originalTitle     Sommer 1963
isAdult                     0
startYear                1963
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2007528, dtype: object

(9,)

tconst            tt11829304
titleType          tvEpisode
primaryTitle      Ugly Truth
originalTitle     Ugly Truth
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            29
genres                 Drama
Name: 2007529, dtype: object

(9,)

tconst                              tt11829306
titleType                            tvEpisode
primaryTitle      La guerre c'est Ark! Et Wow!
originalTitle     La guerre c'est Ark! Et Wow!
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2007530, dtype: object

(9,)

tconst                                          tt11829308
titleType                                            movie
primaryTitle      Manchester United vs Queens Park Rangers
originalTitle     Manchester United vs Queens Park Rangers
isAdult                                                  0
startYear                                             2012
endYear                                                 \N
runtimeMinutes                                          92
genres                                               Sport
Name: 2007531, dtype: object

(9,)

tconst                                              tt1182930
titleType                                             tvMovie
primaryTitle      Podivuhodny pribeh profesora J. a slecny H.
originalTitle     Podivuhodny pribeh profesora J. a slecny H.
isAdult                                                     0
startYear                                                1995
endYear                                                    \N
runtimeMinutes                                             \N
genres                                          Comedy,Sci-Fi
Name: 2007532, dtype: object

(9,)

tconst               tt11829310
titleType             tvEpisode
primaryTitle      Frühling 1963
originalTitle     Frühling 1963
isAdult                       0
startYear                  1963
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007533, dtype: object

(9,)

tconst                                  tt11829312
titleType                                tvEpisode
primaryTitle      Les poètes qui riment c'est Ark!
originalTitle     Les poètes qui riment c'est Ark!
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                   Talk-Show
Name: 2007534, dtype: object

(9,)

tconst                      tt11829316
titleType                     tvSeries
primaryTitle                  Vampires
originalTitle                 Vampires
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Drama,Fantasy,Horror
Name: 2007535, dtype: object

(9,)

tconst                                       tt11829318
titleType                                     tvEpisode
primaryTitle      Des cours de civisme pour les enfants
originalTitle     Des cours de civisme pour les enfants
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                        Talk-Show
Name: 2007536, dtype: object

(9,)

tconst                                                    tt1182931
titleType                                                 tvSpecial
primaryTitle      Polizeistund' ade - Das Abschiedskonzert von K...
originalTitle     Polizeistund' ade - Das Abschiedskonzert von K...
isAdult                                                           0
startYear                                                      2007
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Documentary,Music
Name: 2007537, dtype: object

(9,)

tconst                                    tt11829320
titleType                                  tvEpisode
primaryTitle      Les States eux ils l'ont l'affaire
originalTitle     Les States eux ils l'ont l'affaire
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                     Talk-Show
Name: 2007538, dtype: object

(9,)

tconst                                   tt11829322
titleType                                 tvEpisode
primaryTitle      Shots, Shots, Shots, Shots, Shots
originalTitle     Shots, Shots, Shots, Shots, Shots
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                    Talk-Show
Name: 2007539, dtype: object

(9,)

tconst             tt11829324
titleType           tvSpecial
primaryTitle       Porrkungen
originalTitle      Porrkungen
isAdult                     0
startYear                2004
endYear                    \N
runtimeMinutes             43
genres            Documentary
Name: 2007540, dtype: object

(9,)

tconst                                   tt11829326
titleType                                     movie
primaryTitle      Manchester United vs Norwich City
originalTitle     Manchester United vs Norwich City
isAdult                                           0
startYear                                      2013
endYear                                          \N
runtimeMinutes                                   90
genres                                       Action
Name: 2007541, dtype: object

(9,)

tconst                        tt11829328
titleType                      tvEpisode
primaryTitle      On parlera pas de O.D.
originalTitle     On parlera pas de O.D.
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2007542, dtype: object

(9,)

tconst             tt1182932
titleType              short
primaryTitle      O pontikos
originalTitle     O pontikos
isAdult                    0
startYear               1978
endYear                   \N
runtimeMinutes             8
genres                 Short
Name: 2007543, dtype: object

(9,)

tconst                            tt11829332
titleType                          tvEpisode
primaryTitle      The Sainte-Fondue chinoise
originalTitle     The Sainte-Fondue chinoise
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2007544, dtype: object

(9,)

tconst               tt11829334
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2007545, dtype: object

(9,)

tconst                             tt11829336
titleType                           tvEpisode
primaryTitle      Le CEGEP voulait pas de moé
originalTitle     Le CEGEP voulait pas de moé
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2007546, dtype: object

(9,)

tconst                    tt11829338
titleType                  tvEpisode
primaryTitle      Only Crypto: Day 3
originalTitle     Only Crypto: Day 3
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2007547, dtype: object

(9,)

tconst                            tt1182933
titleType                             movie
primaryTitle      La prigione sotto la neve
originalTitle     La prigione sotto la neve
isAdult                                   0
startYear                              1923
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2007548, dtype: object

(9,)

tconst                            tt11829340
titleType                           tvSeries
primaryTitle                           Buddi
originalTitle                          Buddi
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            12
genres            Adventure,Animation,Comedy
Name: 2007549, dtype: object

(9,)

tconst                   tt11829342
titleType                 tvEpisode
primaryTitle      Victoria Charlton
originalTitle     Victoria Charlton
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2007550, dtype: object

(9,)

tconst                        tt11829344
titleType                       tvSeries
primaryTitle      Vadelmakallion iltamat
originalTitle     Vadelmakallion iltamat
isAdult                                0
startYear                           1996
endYear                             1998
runtimeMinutes                        \N
genres                             Music
Name: 2007551, dtype: object

(9,)

tconst                           tt11829346
titleType                         tvEpisode
primaryTitle      Pierre-Yves Roy-Desmarais
originalTitle     Pierre-Yves Roy-Desmarais
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2007552, dtype: object

(9,)

tconst              tt11829348
titleType            tvEpisode
primaryTitle      War and Love
originalTitle     War and Love
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              27
genres                   Drama
Name: 2007553, dtype: object

(9,)

tconst                      tt1182934
titleType                       movie
primaryTitle      La principessa nera
originalTitle     La principessa nera
isAdult                             0
startYear                        1920
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2007554, dtype: object

(9,)

tconst                tt11829350
titleType              tvEpisode
primaryTitle      Colin Boudrias
originalTitle     Colin Boudrias
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2007555, dtype: object

(9,)

tconst                                        tt11829352
titleType                                      tvEpisode
primaryTitle      Office Administrator - Clueless Expert
originalTitle     Office Administrator - Clueless Expert
isAdult                                                0
startYear                                           2019
endYear                                               \N
runtimeMinutes                                        \N
genres                               Comedy,Drama,Sci-Fi
Name: 2007556, dtype: object

(9,)

tconst                   tt11829354
titleType                     short
primaryTitle      Gibber Graf Night
originalTitle     Gibber Graf Night
isAdult                           0
startYear                      1997
endYear                          \N
runtimeMinutes                    3
genres                        Short
Name: 2007557, dtype: object

(9,)

tconst              tt11829356
titleType            tvEpisode
primaryTitle      Martin Petit
originalTitle     Martin Petit
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2007558, dtype: object

(9,)

tconst                tt11829358
titleType                  short
primaryTitle      Money Addicted
originalTitle     Money Addicted
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres               Crime,Short
Name: 2007559, dtype: object

(9,)

tconst                   tt1182935
titleType                    short
primaryTitle      Pszichokozmoszok
originalTitle     Pszichokozmoszok
isAdult                          0
startYear                     1976
endYear                         \N
runtimeMinutes                  12
genres                       Short
Name: 2007560, dtype: object

(9,)

tconst             tt11829360
titleType           tvEpisode
primaryTitle      Korine Côté
originalTitle     Korine Côté
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2007561, dtype: object

(9,)

tconst                tt11829364
titleType              tvEpisode
primaryTitle        Episode #3.4
originalTitle       Episode #3.4
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes               150
genres            News,Talk-Show
Name: 2007562, dtype: object

(9,)

tconst                tt11829366
titleType              tvEpisode
primaryTitle      Dominic Tardif
originalTitle     Dominic Tardif
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2007563, dtype: object

(9,)

tconst                    tt11829368
titleType                  tvEpisode
primaryTitle      Jean-Philippe Dion
originalTitle     Jean-Philippe Dion
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2007564, dtype: object

(9,)

tconst                         tt1182936
titleType                          movie
primaryTitle      I quattro moschettieri
originalTitle     I quattro moschettieri
isAdult                                0
startYear                           1919
endYear                               \N
runtimeMinutes                        \N
genres                                \N
Name: 2007565, dtype: object

(9,)

tconst               tt11829370
titleType             videoGame
primaryTitle      Land of glory
originalTitle     Land of glory
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               \N
genres                   Action
Name: 2007566, dtype: object

(9,)

tconst             tt11829372
titleType           tvEpisode
primaryTitle      Arnaud Soly
originalTitle     Arnaud Soly
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2007567, dtype: object

(9,)

tconst                                       tt11829374
titleType                                     tvSpecial
primaryTitle      Gabrielle - porrdrottning eller offer
originalTitle     Gabrielle - porrdrottning eller offer
isAdult                                               0
startYear                                          1999
endYear                                              \N
runtimeMinutes                                       45
genres                                      Documentary
Name: 2007568, dtype: object

(9,)

tconst                              tt11829376
titleType                            tvEpisode
primaryTitle      Episode dated 6 January 2020
originalTitle     Episode dated 6 January 2020
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2007569, dtype: object

(9,)

tconst                               tt11829378
titleType                             tvEpisode
primaryTitle      Episode dated 13 January 2020
originalTitle     Episode dated 13 January 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2007570, dtype: object

(9,)

tconst                      tt1182937
titleType                       movie
primaryTitle      Rab Ne Bana Di Jodi
originalTitle     Rab Ne Bana Di Jodi
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                    167
genres             Comedy,Drama,Music
Name: 2007571, dtype: object

(9,)

tconst                      tt11829380
titleType                        movie
primaryTitle      Venezuela: the truth
originalTitle     Venezuela: the truth
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      62
genres                     Documentary
Name: 2007572, dtype: object

(9,)

tconst                               tt11829382
titleType                             tvEpisode
primaryTitle      Episode dated 20 January 2020
originalTitle     Episode dated 20 January 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2007573, dtype: object

(9,)

tconst              tt11829384
titleType            tvEpisode
primaryTitle      Episode #4.7
originalTitle     Episode #4.7
isAdult                      0
startYear                 1999
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2007574, dtype: object

(9,)

tconst                               tt11829386
titleType                             tvEpisode
primaryTitle      Episode dated 27 January 2020
originalTitle     Episode dated 27 January 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2007575, dtype: object

(9,)

tconst                               tt11829388
titleType                             tvEpisode
primaryTitle      Episode dated 3 February 2020
originalTitle     Episode dated 3 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2007576, dtype: object

(9,)

tconst                    tt1182938
titleType                     short
primaryTitle      Robert the Silent
originalTitle     Robert the Silent
isAdult                           0
startYear                      1911
endYear                          \N
runtimeMinutes                   \N
genres                  Drama,Short
Name: 2007577, dtype: object

(9,)

tconst                       tt11829390
titleType                         video
primaryTitle               A SOAP OPERA
originalTitle              A SOAP OPERA
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                      132
genres            Comedy,Drama,Thriller
Name: 2007578, dtype: object

(9,)

tconst                                tt11829392
titleType                              tvEpisode
primaryTitle      Episode dated 17 February 2020
originalTitle     Episode dated 17 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007579, dtype: object

(9,)

tconst                      tt11829394
titleType                    tvEpisode
primaryTitle              Episode #1.1
originalTitle             Episode #1.1
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007580, dtype: object

(9,)

tconst                     tt11829396
titleType                   tvEpisode
primaryTitle           Episode #1.108
originalTitle          Episode #1.108
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2007581, dtype: object

(9,)

tconst                      tt11829398
titleType                    tvEpisode
primaryTitle              Episode #1.2
originalTitle             Episode #1.2
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007582, dtype: object

(9,)

tconst                     tt1182939
titleType                      short
primaryTitle      Robinet, Robinette
originalTitle     Robinet, Robinette
isAdult                            0
startYear                       1913
endYear                           \N
runtimeMinutes                    \N
genres                  Comedy,Short
Name: 2007583, dtype: object

(9,)

tconst                tt11829400
titleType              tvEpisode
primaryTitle      Burger Premier
originalTitle     Burger Premier
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2007584, dtype: object

(9,)

tconst              tt11829402
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007585, dtype: object

(9,)

tconst              tt11829404
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007586, dtype: object

(9,)

tconst              tt11829406
titleType            tvEpisode
primaryTitle      Hot-Dog Fier
originalTitle     Hot-Dog Fier
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2007587, dtype: object

(9,)

tconst              tt11829408
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007588, dtype: object

(9,)

tconst                         tt1182940
titleType                          movie
primaryTitle      Il romanzo del diavolo
originalTitle     Il romanzo del diavolo
isAdult                                0
startYear                           1922
endYear                               \N
runtimeMinutes                        \N
genres                                \N
Name: 2007589, dtype: object

(9,)

tconst                             tt11829410
titleType                           tvEpisode
primaryTitle      The Border Blocking Brexit?
originalTitle     The Border Blocking Brexit?
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             \N
genres                            Documentary
Name: 2007590, dtype: object

(9,)

tconst              tt11829412
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007591, dtype: object

(9,)

tconst              tt11829414
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007592, dtype: object

(9,)

tconst            tt11829416
titleType          tvEpisode
primaryTitle       Complots?
originalTitle      Complots?
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2007593, dtype: object

(9,)

tconst              tt11829418
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 1997
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007594, dtype: object

(9,)

tconst                          tt1182941
titleType                         tvMovie
primaryTitle      Russlands wilde Dichter
originalTitle     Russlands wilde Dichter
isAdult                                 0
startYear                            2003
endYear                                \N
runtimeMinutes                         60
genres                        Documentary
Name: 2007595, dtype: object

(9,)

tconst              tt11829420
titleType                video
primaryTitle      Lies in Blue
originalTitle     Lies in Blue
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes               5
genres             Music,Short
Name: 2007596, dtype: object

(9,)

tconst                   tt11829422
titleType                 tvEpisode
primaryTitle      Pennitön uneksija
originalTitle     Pennitön uneksija
isAdult                           0
startYear                      1998
endYear                          \N
runtimeMinutes                   \N
genres                        Music
Name: 2007597, dtype: object

(9,)

tconst                 tt11829424
titleType               tvEpisode
primaryTitle      Pikku Midinetti
originalTitle     Pikku Midinetti
isAdult                         0
startYear                    1998
endYear                        \N
runtimeMinutes                 \N
genres                      Music
Name: 2007598, dtype: object

(9,)

tconst                   tt11829426
titleType                 tvEpisode
primaryTitle      Avec Ariel Rebel!
originalTitle     Avec Ariel Rebel!
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2007599, dtype: object

(9,)

tconst                      tt11829428
titleType                    tvEpisode
primaryTitle      Alla venäläisen kuun
originalTitle     Alla venäläisen kuun
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres                           Music
Name: 2007600, dtype: object

(9,)

tconst                  tt1182942
titleType                   movie
primaryTitle             S.N.U.B!
originalTitle            S.N.U.B!
isAdult                         0
startYear                    2010
endYear                        \N
runtimeMinutes                 74
genres            Horror,Thriller
Name: 2007601, dtype: object

(9,)

tconst                    tt11829430
titleType                  tvEpisode
primaryTitle      Muistan sua Elaine
originalTitle     Muistan sua Elaine
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres                         Music
Name: 2007602, dtype: object

(9,)

tconst             tt11829432
titleType           tvEpisode
primaryTitle      Tulenliekki
originalTitle     Tulenliekki
isAdult                     0
startYear                1998
endYear                    \N
runtimeMinutes             \N
genres                  Music
Name: 2007603, dtype: object

(9,)

tconst                    tt11829434
titleType                  tvEpisode
primaryTitle      Ranskalaiset korot
originalTitle     Ranskalaiset korot
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres                         Music
Name: 2007604, dtype: object

(9,)

tconst                tt11829436
titleType              tvEpisode
primaryTitle       Episode #2.40
originalTitle      Episode #2.40
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2007605, dtype: object

(9,)

tconst                      tt11829438
titleType                    tvEpisode
primaryTitle      Gratitude vs Bazooka
originalTitle     Gratitude vs Bazooka
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2007606, dtype: object

(9,)

tconst                      tt1182943
titleType                       movie
primaryTitle      Saetta contro Golia
originalTitle     Saetta contro Golia
isAdult                             0
startYear                        1920
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2007607, dtype: object

(9,)

tconst                   tt11829440
titleType                 tvEpisode
primaryTitle      Excellent Timing!
originalTitle     Excellent Timing!
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2007608, dtype: object

(9,)

tconst                        tt11829442
titleType                          short
primaryTitle      Deathstination (A POC)
originalTitle     Deathstination (A POC)
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                         1
genres                     Mystery,Short
Name: 2007609, dtype: object

(9,)

tconst                                                   tt11829444
titleType                                                 tvEpisode
primaryTitle      Demon Slayer 1x16 REACTION!! "Letting Someone ...
originalTitle     Demon Slayer 1x16 REACTION!! "Letting Someone ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   25
genres                                                    Talk-Show
Name: 2007610, dtype: object

(9,)

tconst                    tt11829446
titleType                  tvEpisode
primaryTitle      Le Jeune Paresseux
originalTitle     Le Jeune Paresseux
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2007611, dtype: object

(9,)

tconst                                  tt1182944
titleType                                   movie
primaryTitle      Saetta contro l'orco di Marcouf
originalTitle     Saetta contro l'orco di Marcouf
isAdult                                         0
startYear                                    1921
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2007612, dtype: object

(9,)

tconst                  tt11829452
titleType                tvEpisode
primaryTitle      Sylvain Larocque
originalTitle     Sylvain Larocque
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2007613, dtype: object

(9,)

tconst              tt11829454
titleType            tvEpisode
primaryTitle      Stefie Shock
originalTitle     Stefie Shock
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2007614, dtype: object

(9,)

tconst             tt11829456
titleType           tvEpisode
primaryTitle      José Gaudet
originalTitle     José Gaudet
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2007615, dtype: object

(9,)

tconst                    tt11829458
titleType                  tvEpisode
primaryTitle      Jonathan Painchaud
originalTitle     Jonathan Painchaud
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2007616, dtype: object

(9,)

tconst                              tt1182945
titleType                               movie
primaryTitle      Saetta e il club dei Ciuffi
originalTitle     Saetta e il club dei Ciuffi
isAdult                                     0
startYear                                1921
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2007617, dtype: object

(9,)

tconst                tt11829460
titleType              tvEpisode
primaryTitle      Etienne Boulay
originalTitle     Etienne Boulay
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2007618, dtype: object

(9,)

tconst            tt11829462
titleType          tvEpisode
primaryTitle      Gab Joncas
originalTitle     Gab Joncas
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2007619, dtype: object

(9,)

tconst                         tt11829464
titleType                        tvSeries
primaryTitle      The Too Late Night Show
originalTitle     The Too Late Night Show
isAdult                                 0
startYear                            2019
endYear                              2019
runtimeMinutes                         \N
genres                             Comedy
Name: 2007620, dtype: object

(9,)

tconst                     tt11829466
titleType                   tvEpisode
primaryTitle      François Létourneau
originalTitle     François Létourneau
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2007621, dtype: object

(9,)

tconst            tt11829468
titleType          tvEpisode
primaryTitle      Hugo Mudie
originalTitle     Hugo Mudie
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2007622, dtype: object

(9,)

tconst                                      tt1182946
titleType                                       movie
primaryTitle      Saetta più forte di Sherlock Holmes
originalTitle     Saetta più forte di Sherlock Holmes
isAdult                                             0
startYear                                        1921
endYear                                            \N
runtimeMinutes                                     \N
genres                                             \N
Name: 2007623, dtype: object

(9,)

tconst               tt11829470
titleType             tvEpisode
primaryTitle      Episode #9.51
originalTitle     Episode #9.51
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007624, dtype: object

(9,)

tconst               tt11829472
titleType             tvEpisode
primaryTitle      Episode #9.52
originalTitle     Episode #9.52
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007625, dtype: object

(9,)

tconst            tt11829474
titleType          tvEpisode
primaryTitle       Miesluola
originalTitle      Miesluola
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            22
genres                Comedy
Name: 2007626, dtype: object

(9,)

tconst                                   tt11829476
titleType                                 tvEpisode
primaryTitle      Dong Bei Suan Cai Bai Rou Huo Guo
originalTitle     Dong Bei Suan Cai Bai Rou Huo Guo
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   14
genres                                  Documentary
Name: 2007627, dtype: object

(9,)

tconst               tt11829478
titleType             tvEpisode
primaryTitle      Episode #9.53
originalTitle     Episode #9.53
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007628, dtype: object

(9,)

tconst                            tt1182947
titleType                             short
primaryTitle      The Schooling of Mary Ann
originalTitle     The Schooling of Mary Ann
isAdult                                   0
startYear                              1914
endYear                                  \N
runtimeMinutes                           \N
genres                          Drama,Short
Name: 2007629, dtype: object

(9,)

tconst                                       tt11829480
titleType                                     tvEpisode
primaryTitle      Serge Bouchard et Jean-Philippe Pleau
originalTitle     Serge Bouchard et Jean-Philippe Pleau
isAdult                                               0
startYear                                          2019
endYear                                              \N
runtimeMinutes                                       \N
genres                                        Talk-Show
Name: 2007630, dtype: object

(9,)

tconst               tt11829482
titleType             tvEpisode
primaryTitle      Episode #9.54
originalTitle     Episode #9.54
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007631, dtype: object

(9,)

tconst              tt11829484
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007632, dtype: object

(9,)

tconst              tt11829486
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007633, dtype: object

(9,)

tconst               tt11829488
titleType             tvEpisode
primaryTitle      Episode #9.55
originalTitle     Episode #9.55
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007634, dtype: object

(9,)

tconst               tt1182948
titleType                video
primaryTitle      The Search 2
originalTitle     The Search 2
isAdult                      0
startYear                 2006
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2007635, dtype: object

(9,)

tconst             tt11829490
titleType           tvEpisode
primaryTitle      Marc Séguin
originalTitle     Marc Séguin
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2007636, dtype: object

(9,)

tconst              tt11829492
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007637, dtype: object

(9,)

tconst              tt11829494
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007638, dtype: object

(9,)

tconst               tt11829496
titleType             tvEpisode
primaryTitle      Episode #9.56
originalTitle     Episode #9.56
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007639, dtype: object

(9,)

tconst               tt11829498
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  1996
endYear                      \N
runtimeMinutes               \N
genres                    Music
Name: 2007640, dtype: object

(9,)

tconst               tt1182949
titleType                video
primaryTitle      The Search 3
originalTitle     The Search 3
isAdult                      0
startYear                 2006
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2007641, dtype: object

(9,)

tconst                  tt11829502
titleType                tvEpisode
primaryTitle      Stéphan Larouche
originalTitle     Stéphan Larouche
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2007642, dtype: object

(9,)

tconst              tt11829504
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 1997
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007643, dtype: object

(9,)

tconst                tt11829506
titleType              tvEpisode
primaryTitle      The Human Bond
originalTitle     The Human Bond
isAdult                        0
startYear                   1954
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2007644, dtype: object

(9,)

tconst              tt11829508
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 1997
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007645, dtype: object

(9,)

tconst             tt1182950
titleType              video
primaryTitle      The Search
originalTitle     The Search
isAdult                    0
startYear               2006
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2007646, dtype: object

(9,)

tconst              tt11829510
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2016
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2007647, dtype: object

(9,)

tconst              tt11829512
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 1997
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007648, dtype: object

(9,)

tconst                     tt11829514
titleType                   tvEpisode
primaryTitle      Claude Vaillancourt
originalTitle     Claude Vaillancourt
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2007649, dtype: object

(9,)

tconst              tt11829516
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 1997
endYear                     \N
runtimeMinutes              \N
genres                   Music
Name: 2007650, dtype: object

(9,)

tconst               tt11829518
titleType             tvEpisode
primaryTitle      Episode #9.57
originalTitle     Episode #9.57
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007651, dtype: object

(9,)

tconst                 tt1182951
titleType                  video
primaryTitle      Secret Affairs
originalTitle     Secret Affairs
isAdult                        0
startYear                   2005
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007652, dtype: object

(9,)

tconst                    tt11829520
titleType                  tvEpisode
primaryTitle      Yves-Marie Abraham
originalTitle     Yves-Marie Abraham
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2007653, dtype: object

(9,)

tconst                   tt11829522
titleType                     short
primaryTitle                 Scapes
originalTitle                Scapes
isAdult                           0
startYear                      2006
endYear                          \N
runtimeMinutes                   15
genres            Documentary,Short
Name: 2007654, dtype: object

(9,)

tconst                     tt11829524
titleType                       short
primaryTitle                 Bad News
originalTitle                Bad News
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     14
genres            Comedy,Horror,Short
Name: 2007655, dtype: object

(9,)

tconst               tt11829526
titleType             tvEpisode
primaryTitle      Episode #9.58
originalTitle     Episode #9.58
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007656, dtype: object

(9,)

tconst                 tt11829528
titleType               tvEpisode
primaryTitle      Episode #1.2693
originalTitle     Episode #1.2693
isAdult                         0
startYear                    1985
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2007657, dtype: object

(9,)

tconst                              tt1182952
titleType                             tvMovie
primaryTitle      La signora Morlì, una e due
originalTitle     La signora Morlì, una e due
isAdult                                     0
startYear                                1991
endYear                                    \N
runtimeMinutes                             90
genres                                 Comedy
Name: 2007658, dtype: object

(9,)

tconst               tt11829530
titleType             tvEpisode
primaryTitle      Episode #9.59
originalTitle     Episode #9.59
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007659, dtype: object

(9,)

tconst               tt11829532
titleType             tvEpisode
primaryTitle      Episode #9.60
originalTitle     Episode #9.60
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007660, dtype: object

(9,)

tconst                 tt11829534
titleType               tvEpisode
primaryTitle        Episode #1.91
originalTitle       Episode #1.91
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2007661, dtype: object

(9,)

tconst                                                   tt11829536
titleType                                                 tvEpisode
primaryTitle      Bèlivo, Daniel Boucher, Jeff Smallwood, Martin...
originalTitle     Bèlivo, Daniel Boucher, Jeff Smallwood, Martin...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007662, dtype: object

(9,)

tconst             tt11829538
titleType           tvEpisode
primaryTitle      No Conflict
originalTitle     No Conflict
isAdult                     0
startYear                1954
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2007663, dtype: object

(9,)

tconst                      tt1182953
titleType                       short
primaryTitle      Il signore metodico
originalTitle     Il signore metodico
isAdult                             0
startYear                        1909
endYear                            \N
runtimeMinutes                     \N
genres                          Short
Name: 2007664, dtype: object

(9,)

tconst                 tt11829540
titleType               tvEpisode
primaryTitle        Episode #1.92
originalTitle       Episode #1.92
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2007665, dtype: object

(9,)

tconst            tt11829542
titleType              movie
primaryTitle         Jakkoaî
originalTitle        Jakkoaî
isAdult                    0
startYear               1936
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2007666, dtype: object

(9,)

tconst                          tt11829544
titleType                        tvEpisode
primaryTitle      Hainan Zao Po Cu Huo Guo
originalTitle     Hainan Zao Po Cu Huo Guo
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          12
genres                         Documentary
Name: 2007667, dtype: object

(9,)

tconst                   tt11829546
titleType                  tvSeries
primaryTitle      The Peach Blossom
originalTitle     The Peach Blossom
isAdult                           0
startYear                      2017
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2007668, dtype: object

(9,)

tconst                 tt11829548
titleType               tvEpisode
primaryTitle        Episode #1.93
originalTitle       Episode #1.93
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2007669, dtype: object

(9,)

tconst                       tt1182954
titleType                        short
primaryTitle      La signorina Robinet
originalTitle     La signorina Robinet
isAdult                              0
startYear                         1912
endYear                             \N
runtimeMinutes                       3
genres                    Comedy,Short
Name: 2007670, dtype: object

(9,)

tconst                 tt11829550
titleType               tvEpisode
primaryTitle        Episode #1.94
originalTitle       Episode #1.94
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2007671, dtype: object

(9,)

tconst                               tt11829552
titleType                             tvEpisode
primaryTitle      Episode dated 15 October 1970
originalTitle     Episode dated 15 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2007672, dtype: object

(9,)

tconst                 tt11829556
titleType               tvEpisode
primaryTitle        Episode #1.95
originalTitle       Episode #1.95
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2007673, dtype: object

(9,)

tconst                 tt11829558
titleType               tvEpisode
primaryTitle        Episode #1.96
originalTitle       Episode #1.96
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2007674, dtype: object

(9,)

tconst                            tt1182955
titleType                             movie
primaryTitle      Una signorina in lotteria
originalTitle     Una signorina in lotteria
isAdult                                   0
startYear                              1921
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2007675, dtype: object

(9,)

tconst              tt11829560
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2016
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2007676, dtype: object

(9,)

tconst                 tt11829562
titleType               tvEpisode
primaryTitle        Episode #1.97
originalTitle       Episode #1.97
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Sport,Talk-Show
Name: 2007677, dtype: object

(9,)

tconst                               tt11829564
titleType                             tvEpisode
primaryTitle      Episode dated 24 January 1966
originalTitle     Episode dated 24 January 1966
isAdult                                       0
startYear                                  1966
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2007678, dtype: object

(9,)

tconst                           tt11829566
titleType                         tvEpisode
primaryTitle         Jane Pickens, Al Hodge
originalTitle        Jane Pickens, Al Hodge
isAdult                                   0
startYear                              1954
endYear                                  \N
runtimeMinutes                           \N
genres            Documentary,Drama,Musical
Name: 2007679, dtype: object

(9,)

tconst                                  tt1182956
titleType                                 tvMovie
primaryTitle      Le signorine dai cappelli verdi
originalTitle     Le signorine dai cappelli verdi
isAdult                                         0
startYear                                    1960
endYear                                        \N
runtimeMinutes                                 90
genres                                         \N
Name: 2007680, dtype: object

(9,)

tconst                             tt11829570
titleType                           tvEpisode
primaryTitle                  Episode #21.140
originalTitle                 Episode #21.140
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Comedy,Game-Show,Reality-TV
Name: 2007681, dtype: object

(9,)

tconst                             tt11829572
titleType                           tvEpisode
primaryTitle                  Episode #21.141
originalTitle                 Episode #21.141
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Comedy,Game-Show,Reality-TV
Name: 2007682, dtype: object

(9,)

tconst                           tt11829574
titleType                         tvEpisode
primaryTitle      Episode dated 24 May 1966
originalTitle     Episode dated 24 May 1966
isAdult                                   0
startYear                              1966
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2007683, dtype: object

(9,)

tconst              tt11829576
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2007684, dtype: object

(9,)

tconst                 tt11829578
titleType               tvEpisode
primaryTitle      Episode #1.2695
originalTitle     Episode #1.2695
isAdult                         0
startYear                    1985
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2007685, dtype: object

(9,)

tconst                    tt1182957
titleType                     short
primaryTitle      Smiles of Fortune
originalTitle     Smiles of Fortune
isAdult                           0
startYear                      1914
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2007686, dtype: object

(9,)

tconst                 tt11829580
titleType               tvEpisode
primaryTitle      Episode #1.2321
originalTitle     Episode #1.2321
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007687, dtype: object

(9,)

tconst                 tt11829582
titleType               tvEpisode
primaryTitle      Episode #1.2322
originalTitle     Episode #1.2322
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007688, dtype: object

(9,)

tconst                      tt11829584
titleType                        short
primaryTitle      L'appel de Stockholm
originalTitle     L'appel de Stockholm
isAdult                              0
startYear                         2011
endYear                             \N
runtimeMinutes                      \N
genres                    Comedy,Short
Name: 2007689, dtype: object

(9,)

tconst                 tt11829586
titleType               tvEpisode
primaryTitle      Episode #1.2323
originalTitle     Episode #1.2323
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007690, dtype: object

(9,)

tconst                 tt11829588
titleType                   movie
primaryTitle      Wakodo no sekai
originalTitle     Wakodo no sekai
isAdult                         0
startYear                    1935
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2007691, dtype: object

(9,)

tconst                          tt1182958
titleType                           short
primaryTitle      The Smuggler's Daughter
originalTitle     The Smuggler's Daughter
isAdult                                 0
startYear                            1913
endYear                                \N
runtimeMinutes                         \N
genres                        Drama,Short
Name: 2007692, dtype: object

(9,)

tconst                 tt11829590
titleType               tvEpisode
primaryTitle      Episode #1.2325
originalTitle     Episode #1.2325
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007693, dtype: object

(9,)

tconst                 tt11829592
titleType               tvEpisode
primaryTitle      Episode #1.2324
originalTitle     Episode #1.2324
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007694, dtype: object

(9,)

tconst                 tt11829594
titleType               tvEpisode
primaryTitle      Episode #1.2327
originalTitle     Episode #1.2327
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007695, dtype: object

(9,)

tconst                    tt11829596
titleType                  tvEpisode
primaryTitle      A Despotic Husband
originalTitle     A Despotic Husband
isAdult                            0
startYear                         \N
endYear                           \N
runtimeMinutes                    \N
genres                         Crime
Name: 2007696, dtype: object

(9,)

tconst            tt11829598
titleType              movie
primaryTitle          Reboot
originalTitle         Reboot
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Action
Name: 2007697, dtype: object

(9,)

tconst               tt1182959
titleType                short
primaryTitle      Some Elopers
originalTitle     Some Elopers
isAdult                      0
startYear                 1913
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2007698, dtype: object

(9,)

tconst                 tt11829600
titleType               tvEpisode
primaryTitle      Episode #1.2328
originalTitle     Episode #1.2328
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007699, dtype: object

(9,)

tconst                 tt11829602
titleType               tvEpisode
primaryTitle      Episode #1.2329
originalTitle     Episode #1.2329
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007700, dtype: object

(9,)

tconst                 tt11829604
titleType               tvEpisode
primaryTitle      Episode #1.2330
originalTitle     Episode #1.2330
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007701, dtype: object

(9,)

tconst                 tt11829606
titleType               tvEpisode
primaryTitle      Episode #1.2331
originalTitle     Episode #1.2331
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007702, dtype: object

(9,)

tconst                        tt1182960
titleType                         short
primaryTitle      Stagone mes sto hrono
originalTitle     Stagone mes sto hrono
isAdult                               0
startYear                          1978
endYear                              \N
runtimeMinutes                        6
genres                            Short
Name: 2007703, dtype: object

(9,)

tconst                   tt11829610
titleType                     short
primaryTitle      Fingertip Dream 4
originalTitle     Fingertip Dream 4
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2007704, dtype: object

(9,)

tconst                 tt11829612
titleType               tvEpisode
primaryTitle      Episode #1.2333
originalTitle     Episode #1.2333
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007705, dtype: object

(9,)

tconst                 tt11829614
titleType               tvEpisode
primaryTitle      Episode #1.2334
originalTitle     Episode #1.2334
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007706, dtype: object

(9,)

tconst                 tt11829616
titleType               tvEpisode
primaryTitle      Episode #1.2335
originalTitle     Episode #1.2335
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007707, dtype: object

(9,)

tconst                 tt11829618
titleType               tvEpisode
primaryTitle      Episode #1.2336
originalTitle     Episode #1.2336
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007708, dtype: object

(9,)

tconst                 tt11829620
titleType               tvEpisode
primaryTitle      Episode #1.2337
originalTitle     Episode #1.2337
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007709, dtype: object

(9,)

tconst                 tt11829622
titleType               tvEpisode
primaryTitle      Episode #1.2338
originalTitle     Episode #1.2338
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007710, dtype: object

(9,)

tconst                 tt11829624
titleType               tvEpisode
primaryTitle      Episode #1.2339
originalTitle     Episode #1.2339
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007711, dtype: object

(9,)

tconst                 tt11829626
titleType               tvEpisode
primaryTitle      Episode #1.2340
originalTitle     Episode #1.2340
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007712, dtype: object

(9,)

tconst              tt11829628
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2007713, dtype: object

(9,)

tconst                           tt1182962
titleType                            short
primaryTitle      Tha borouse na 'he ginei
originalTitle     Tha borouse na 'he ginei
isAdult                                  0
startYear                             1978
endYear                                 \N
runtimeMinutes                          10
genres                               Short
Name: 2007714, dtype: object

(9,)

tconst                        tt11829630
titleType                      tvEpisode
primaryTitle      Protect the Laser Gun!
originalTitle     Protect the Laser Gun!
isAdult                                0
startYear                           1998
endYear                               \N
runtimeMinutes                        \N
genres                            Sci-Fi
Name: 2007715, dtype: object

(9,)

tconst                         tt11829632
titleType                       tvEpisode
primaryTitle      Passion Out Of Control!
originalTitle     Passion Out Of Control!
isAdult                                 0
startYear                            2017
endYear                                \N
runtimeMinutes                         \N
genres                              Crime
Name: 2007716, dtype: object

(9,)

tconst                 tt11829634
titleType               tvEpisode
primaryTitle      Episode #1.2022
originalTitle     Episode #1.2022
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007717, dtype: object

(9,)

tconst                 tt11829636
titleType               tvEpisode
primaryTitle      Episode #1.2023
originalTitle     Episode #1.2023
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007718, dtype: object

(9,)

tconst                 tt11829638
titleType               tvEpisode
primaryTitle      Episode #1.2024
originalTitle     Episode #1.2024
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007719, dtype: object

(9,)

tconst                     tt1182963
titleType                      short
primaryTitle      The Three Whiffles
originalTitle     The Three Whiffles
isAdult                            0
startYear                       1911
endYear                           \N
runtimeMinutes                    \N
genres                  Comedy,Short
Name: 2007720, dtype: object

(9,)

tconst                 tt11829640
titleType               tvEpisode
primaryTitle      Episode #1.2025
originalTitle     Episode #1.2025
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007721, dtype: object

(9,)

tconst                 tt11829642
titleType               tvEpisode
primaryTitle      Episode #1.2026
originalTitle     Episode #1.2026
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007722, dtype: object

(9,)

tconst                 tt11829644
titleType               tvEpisode
primaryTitle      Episode #1.2027
originalTitle     Episode #1.2027
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007723, dtype: object

(9,)

tconst                 tt11829646
titleType               tvEpisode
primaryTitle      Episode #1.2028
originalTitle     Episode #1.2028
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007724, dtype: object

(9,)

tconst                           tt11829648
titleType                             video
primaryTitle      Clara Luciani: La grenade
originalTitle     Clara Luciani: La grenade
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                            3
genres                          Music,Short
Name: 2007725, dtype: object

(9,)

tconst                      tt1182964
titleType                       short
primaryTitle      The Thrifty Janitor
originalTitle     The Thrifty Janitor
isAdult                             0
startYear                        1913
endYear                            \N
runtimeMinutes                     \N
genres                   Comedy,Short
Name: 2007726, dtype: object

(9,)

tconst                 tt11829650
titleType               tvEpisode
primaryTitle      Episode #1.2029
originalTitle     Episode #1.2029
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007727, dtype: object

(9,)

tconst                 tt11829652
titleType               tvEpisode
primaryTitle      Episode #1.2030
originalTitle     Episode #1.2030
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007728, dtype: object

(9,)

tconst                 tt11829654
titleType               tvEpisode
primaryTitle      Episode #1.2031
originalTitle     Episode #1.2031
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007729, dtype: object

(9,)

tconst               tt11829656
titleType             tvEpisode
primaryTitle      Shoot! Torema
originalTitle     Shoot! Torema
isAdult                       0
startYear                  1998
endYear                      \N
runtimeMinutes               \N
genres                   Sci-Fi
Name: 2007730, dtype: object

(9,)

tconst                 tt11829658
titleType               tvEpisode
primaryTitle      Episode #1.2032
originalTitle     Episode #1.2032
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007731, dtype: object

(9,)

tconst                    tt1182965
titleType                     short
primaryTitle       Tobacco Industry
originalTitle      Tobacco Industry
isAdult                           0
startYear                      1914
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2007732, dtype: object

(9,)

tconst                 tt11829660
titleType               tvEpisode
primaryTitle      Episode #1.2033
originalTitle     Episode #1.2033
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007733, dtype: object

(9,)

tconst                 tt11829662
titleType               tvEpisode
primaryTitle      Episode #1.2034
originalTitle     Episode #1.2034
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007734, dtype: object

(9,)

tconst                 tt11829664
titleType               tvEpisode
primaryTitle      Episode #1.2035
originalTitle     Episode #1.2035
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007735, dtype: object

(9,)

tconst                 tt11829666
titleType               tvEpisode
primaryTitle      Episode #1.2036
originalTitle     Episode #1.2036
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007736, dtype: object

(9,)

tconst                 tt11829668
titleType               tvEpisode
primaryTitle      Episode #1.2037
originalTitle     Episode #1.2037
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007737, dtype: object

(9,)

tconst                          tt1182966
titleType                           movie
primaryTitle      La tortura del silenzio
originalTitle     La tortura del silenzio
isAdult                                 0
startYear                            1921
endYear                                \N
runtimeMinutes                         \N
genres                                 \N
Name: 2007738, dtype: object

(9,)

tconst                                    tt11829670
titleType                                  tvEpisode
primaryTitle      Regina corre a David del instituto
originalTitle     Regina corre a David del instituto
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    44
genres                        Adventure,Drama,Family
Name: 2007739, dtype: object

(9,)

tconst                 tt11829672
titleType               tvEpisode
primaryTitle      Episode #1.2038
originalTitle     Episode #1.2038
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007740, dtype: object

(9,)

tconst                 tt11829674
titleType               tvEpisode
primaryTitle      Episode #1.2039
originalTitle     Episode #1.2039
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007741, dtype: object

(9,)

tconst                                                   tt11829676
titleType                                                 tvEpisode
primaryTitle      Shirley Albert, Johanne Provencher, Louis Béru...
originalTitle     Shirley Albert, Johanne Provencher, Louis Béru...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007742, dtype: object

(9,)

tconst                 tt11829678
titleType               tvEpisode
primaryTitle      Episode #1.2040
originalTitle     Episode #1.2040
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007743, dtype: object

(9,)

tconst                 tt1182967
titleType                  movie
primaryTitle      Tragica fiamma
originalTitle     Tragica fiamma
isAdult                        0
startYear                   1920
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007744, dtype: object

(9,)

tconst              tt11829680
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2007745, dtype: object

(9,)

tconst                        tt11829682
titleType                          video
primaryTitle      Clara Luciani: La baie
originalTitle     Clara Luciani: La baie
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2007746, dtype: object

(9,)

tconst                 tt11829684
titleType               tvEpisode
primaryTitle      Episode #1.1761
originalTitle     Episode #1.1761
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007747, dtype: object

(9,)

tconst                             tt11829686
titleType                           tvEpisode
primaryTitle      Episode dated 13 March 1990
originalTitle     Episode dated 13 March 1990
isAdult                                     0
startYear                                1990
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2007748, dtype: object

(9,)

tconst                 tt11829688
titleType               tvEpisode
primaryTitle      Episode #1.1762
originalTitle     Episode #1.1762
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007749, dtype: object

(9,)

tconst                      tt1182968
titleType                       short
primaryTitle      Trohaia dystyhimata
originalTitle     Trohaia dystyhimata
isAdult                             0
startYear                        1978
endYear                            \N
runtimeMinutes                     20
genres              Documentary,Short
Name: 2007750, dtype: object

(9,)

tconst                   tt11829690
titleType                 tvEpisode
primaryTitle      A Critical Moment
originalTitle     A Critical Moment
isAdult                           0
startYear                      1998
endYear                          \N
runtimeMinutes                   \N
genres                       Sci-Fi
Name: 2007751, dtype: object

(9,)

tconst                 tt11829692
titleType               tvEpisode
primaryTitle      Episode #1.1763
originalTitle     Episode #1.1763
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007752, dtype: object

(9,)

tconst                 tt11829694
titleType               tvEpisode
primaryTitle      Episode #1.1764
originalTitle     Episode #1.1764
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007753, dtype: object

(9,)

tconst                 tt11829696
titleType               tvEpisode
primaryTitle      Episode #1.1765
originalTitle     Episode #1.1765
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007754, dtype: object

(9,)

tconst                 tt11829698
titleType               tvEpisode
primaryTitle      Episode #1.1766
originalTitle     Episode #1.1766
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007755, dtype: object

(9,)

tconst                                 tt1182969
titleType                                  movie
primaryTitle      La tua vita è in questo scudo!
originalTitle     La tua vita è in questo scudo!
isAdult                                        0
startYear                                   1923
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2007756, dtype: object

(9,)

tconst                 tt11829700
titleType               tvEpisode
primaryTitle      Episode #1.1767
originalTitle     Episode #1.1767
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007757, dtype: object

(9,)

tconst                 tt11829702
titleType               tvEpisode
primaryTitle      Episode #1.1768
originalTitle     Episode #1.1768
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007758, dtype: object

(9,)

tconst                 tt11829704
titleType               tvEpisode
primaryTitle      Episode #1.1769
originalTitle     Episode #1.1769
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007759, dtype: object

(9,)

tconst                 tt11829706
titleType               tvEpisode
primaryTitle      Episode #1.1770
originalTitle     Episode #1.1770
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007760, dtype: object

(9,)

tconst                                                   tt11829708
titleType                                                 tvEpisode
primaryTitle      Vikings, Karaoke Og Farlig Kørsel Med Alex Høg...
originalTitle     Vikings, Karaoke Og Farlig Kørsel Med Alex Høg...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2007761, dtype: object

(9,)

tconst                                      tt1182970
titleType                                       movie
primaryTitle      L'ultima serata dei diavoli volanti
originalTitle     L'ultima serata dei diavoli volanti
isAdult                                             0
startYear                                        1920
endYear                                            \N
runtimeMinutes                                     \N
genres                                             \N
Name: 2007762, dtype: object

(9,)

tconst             tt11829710
titleType               movie
primaryTitle           Retiro
originalTitle          Retiro
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             70
genres            Documentary
Name: 2007763, dtype: object

(9,)

tconst                 tt11829712
titleType               tvEpisode
primaryTitle      Episode #1.1771
originalTitle     Episode #1.1771
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007764, dtype: object

(9,)

tconst                 tt11829714
titleType               tvEpisode
primaryTitle      Episode #1.1772
originalTitle     Episode #1.1772
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007765, dtype: object

(9,)

tconst                 tt11829716
titleType               tvEpisode
primaryTitle      Episode #1.1774
originalTitle     Episode #1.1774
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007766, dtype: object

(9,)

tconst                 tt11829718
titleType               tvEpisode
primaryTitle      Episode #1.1773
originalTitle     Episode #1.1773
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007767, dtype: object

(9,)

tconst                  tt1182971
titleType                   short
primaryTitle            Uninvited
originalTitle     Elskovs Gækkeri
isAdult                         0
startYear                    1913
endYear                        \N
runtimeMinutes                 \N
genres               Comedy,Short
Name: 2007768, dtype: object

(9,)

tconst                 tt11829720
titleType               tvEpisode
primaryTitle      Episode #1.1775
originalTitle     Episode #1.1775
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007769, dtype: object

(9,)

tconst                                                   tt11829722
titleType                                                 tvEpisode
primaryTitle      Danny Boudreau, Jesse Farrell, Kevin Parent, L...
originalTitle     Danny Boudreau, Jesse Farrell, Kevin Parent, L...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007770, dtype: object

(9,)

tconst                        tt11829724
titleType                      tvEpisode
primaryTitle      Regina y Mireya pelean
originalTitle     Regina y Mireya pelean
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        44
genres            Adventure,Drama,Family
Name: 2007771, dtype: object

(9,)

tconst                 tt11829726
titleType               tvEpisode
primaryTitle      Episode #1.1776
originalTitle     Episode #1.1776
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007772, dtype: object

(9,)

tconst                 tt11829728
titleType               tvEpisode
primaryTitle      Episode #1.1777
originalTitle     Episode #1.1777
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007773, dtype: object

(9,)

tconst                       tt1182972
titleType                        movie
primaryTitle         Bachna Ae Haseeno
originalTitle        Bachna Ae Haseeno
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                     152
genres            Comedy,Drama,Romance
Name: 2007774, dtype: object

(9,)

tconst                 tt11829730
titleType               tvEpisode
primaryTitle      Episode #1.1778
originalTitle     Episode #1.1778
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007775, dtype: object

(9,)

tconst                 tt11829734
titleType               tvEpisode
primaryTitle      Episode #1.1779
originalTitle     Episode #1.1779
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007776, dtype: object

(9,)

tconst                 tt11829736
titleType               tvEpisode
primaryTitle      Episode #1.1780
originalTitle     Episode #1.1780
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2007777, dtype: object

(9,)

tconst                          tt11829738
titleType                            video
primaryTitle      Clara Luciani: Comme toi
originalTitle     Clara Luciani: Comme toi
isAdult                                  0
startYear                             2017
endYear                                 \N
runtimeMinutes                           2
genres                         Music,Short
Name: 2007778, dtype: object

(9,)

tconst                            tt1182973
titleType                             movie
primaryTitle      L'uomo che dormì 130 anni
originalTitle     L'uomo che dormì 130 anni
isAdult                                   0
startYear                              1922
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2007779, dtype: object

(9,)

tconst              tt11829740
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2007780, dtype: object

(9,)

tconst              tt11829742
titleType                movie
primaryTitle      Têkikan miyû
originalTitle     Têkikan miyû
isAdult                      0
startYear                 1934
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2007781, dtype: object

(9,)

tconst                                   tt11829744
titleType                                 tvEpisode
primaryTitle      El nuevo jefe de Consulta Externa
originalTitle     El nuevo jefe de Consulta Externa
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   44
genres                       Adventure,Drama,Family
Name: 2007782, dtype: object

(9,)

tconst                            tt11829746
titleType                          tvEpisode
primaryTitle      Episode dated 30 July 1990
originalTitle     Episode dated 30 July 1990
isAdult                                    0
startYear                               1990
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2007783, dtype: object

(9,)

tconst                                                   tt11829748
titleType                                                 tvEpisode
primaryTitle      Dennis Côté, Gord Bamford, Jean and Christiane...
originalTitle     Dennis Côté, Gord Bamford, Jean and Christiane...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007784, dtype: object

(9,)

tconst                 tt1182974
titleType                  movie
primaryTitle      Wanda Saraceto
originalTitle     Wanda Saraceto
isAdult                        0
startYear                   1919
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2007785, dtype: object

(9,)

tconst                    tt11829750
titleType                  tvEpisode
primaryTitle      Shoot the Fake Sun
originalTitle     Shoot the Fake Sun
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres                        Sci-Fi
Name: 2007786, dtype: object

(9,)

tconst                tt11829752
titleType              tvEpisode
primaryTitle       Episode #1.61
originalTitle      Episode #1.61
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007787, dtype: object

(9,)

tconst                                                   tt11829754
titleType                                                 tvEpisode
primaryTitle      Debbie Myers, Jamie Warren, Jean-François Brea...
originalTitle     Debbie Myers, Jamie Warren, Jean-François Brea...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007788, dtype: object

(9,)

tconst                                tt11829756
titleType                              tvEpisode
primaryTitle      Carlos Ibarra amenaza a Regina
originalTitle     Carlos Ibarra amenaza a Regina
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                44
genres                    Adventure,Drama,Family
Name: 2007789, dtype: object

(9,)

tconst              tt11829758
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2007790, dtype: object

(9,)

tconst                    tt1182975
titleType                     video
primaryTitle      Ways of the Heart
originalTitle     Ways of the Heart
isAdult                           0
startYear                      2005
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2007791, dtype: object

(9,)

tconst                tt11829760
titleType              tvEpisode
primaryTitle       Episode #1.62
originalTitle      Episode #1.62
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007792, dtype: object

(9,)

tconst                                                   tt11829762
titleType                                                 tvEpisode
primaryTitle      Claude Cormier, France D'Amour, Ronald Bourgeo...
originalTitle     Claude Cormier, France D'Amour, Ronald Bourgeo...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007793, dtype: object

(9,)

tconst                tt11829764
titleType              tvEpisode
primaryTitle       Episode #1.64
originalTitle      Episode #1.64
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007794, dtype: object

(9,)

tconst                                     tt11829766
titleType                                       video
primaryTitle      Clara Luciani: Pleure Clara, pleure
originalTitle     Clara Luciani: Pleure Clara, pleure
isAdult                                             0
startYear                                        2017
endYear                                            \N
runtimeMinutes                                      3
genres                                    Music,Short
Name: 2007795, dtype: object

(9,)

tconst                tt11829768
titleType              tvEpisode
primaryTitle       Episode #1.63
originalTitle      Episode #1.63
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007796, dtype: object

(9,)

tconst                      tt1182976
titleType                       video
primaryTitle      Ways of the Heart 2
originalTitle     Ways of the Heart 2
isAdult                             0
startYear                        2005
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2007797, dtype: object

(9,)

tconst                                                   tt11829770
titleType                                                 tvEpisode
primaryTitle      MacTavish's, Better Valu, and Kraft Deluxe Var...
originalTitle     MacTavish's, Better Valu, and Kraft Deluxe Var...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2007798, dtype: object

(9,)

tconst                tt11829774
titleType              tvEpisode
primaryTitle       Episode #1.65
originalTitle      Episode #1.65
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007799, dtype: object

(9,)

tconst                tt11829776
titleType              tvEpisode
primaryTitle       Episode #1.66
originalTitle      Episode #1.66
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007800, dtype: object

(9,)

tconst                tt11829778
titleType              tvEpisode
primaryTitle       Episode #1.67
originalTitle      Episode #1.67
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007801, dtype: object

(9,)

tconst                          tt1182977
titleType                           short
primaryTitle      Whiffle's Home Troubles
originalTitle     Whiffle's Home Troubles
isAdult                                 0
startYear                            1911
endYear                                \N
runtimeMinutes                         \N
genres                       Comedy,Short
Name: 2007802, dtype: object

(9,)

tconst                tt11829780
titleType              tvEpisode
primaryTitle       Episode #1.68
originalTitle      Episode #1.68
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007803, dtype: object

(9,)

tconst                tt11829782
titleType              tvEpisode
primaryTitle       Episode #1.69
originalTitle      Episode #1.69
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007804, dtype: object

(9,)

tconst                                                   tt11829784
titleType                                                 tvEpisode
primaryTitle      Bertrand Déraspe, Châkidor, Claude Martel, Joë...
originalTitle     Bertrand Déraspe, Châkidor, Claude Martel, Joë...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007805, dtype: object

(9,)

tconst              tt11829786
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                  Sci-Fi
Name: 2007806, dtype: object

(9,)

tconst                tt11829788
titleType              tvEpisode
primaryTitle       Episode #1.70
originalTitle      Episode #1.70
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007807, dtype: object

(9,)

tconst                  tt1182978
titleType                   short
primaryTitle      Who Was Guilty?
originalTitle         L'innocente
isAdult                         0
startYear                    1913
endYear                        \N
runtimeMinutes                 \N
genres                Drama,Short
Name: 2007808, dtype: object

(9,)

tconst                tt11829790
titleType              tvEpisode
primaryTitle       Episode #1.71
originalTitle      Episode #1.71
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007809, dtype: object

(9,)

tconst                tt11829792
titleType              tvEpisode
primaryTitle       Episode #1.72
originalTitle      Episode #1.72
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007810, dtype: object

(9,)

tconst                                           tt11829794
titleType                                         tvEpisode
primaryTitle      What We Want in a Star Wars Movie: Part 2
originalTitle     What We Want in a Star Wars Movie: Part 2
isAdult                                                   0
startYear                                              2020
endYear                                                  \N
runtimeMinutes                                           \N
genres                                          Documentary
Name: 2007811, dtype: object

(9,)

tconst                tt11829796
titleType              tvEpisode
primaryTitle       Episode #1.73
originalTitle      Episode #1.73
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007812, dtype: object

(9,)

tconst                tt11829798
titleType              tvEpisode
primaryTitle       Episode #1.74
originalTitle      Episode #1.74
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007813, dtype: object

(9,)

tconst                tt11829800
titleType              tvEpisode
primaryTitle       Episode #1.75
originalTitle      Episode #1.75
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007814, dtype: object

(9,)

tconst                tt11829802
titleType              tvEpisode
primaryTitle       Episode #1.76
originalTitle      Episode #1.76
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007815, dtype: object

(9,)

tconst                tt11829804
titleType              tvEpisode
primaryTitle       Episode #1.77
originalTitle      Episode #1.77
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007816, dtype: object

(9,)

tconst                tt11829806
titleType              tvEpisode
primaryTitle       Episode #1.78
originalTitle      Episode #1.78
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007817, dtype: object

(9,)

tconst                                          tt11829808
titleType                                        tvEpisode
primaryTitle      Vegan Pastabilities and liveGfree Deluxe
originalTitle     Vegan Pastabilities and liveGfree Deluxe
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                              Comedy
Name: 2007818, dtype: object

(9,)

tconst                    tt1182980
titleType                     short
primaryTitle      The Wrath of CAAA
originalTitle     The Wrath of CAAA
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                    4
genres                 Comedy,Short
Name: 2007819, dtype: object

(9,)

tconst                tt11829810
titleType              tvEpisode
primaryTitle       Episode #1.79
originalTitle      Episode #1.79
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007820, dtype: object

(9,)

tconst                tt11829812
titleType              tvEpisode
primaryTitle       Episode #1.80
originalTitle      Episode #1.80
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2007821, dtype: object

(9,)

tconst                                tt11829814
titleType                                  video
primaryTitle      Clara Luciani: Monstre d'Amour
originalTitle     Clara Luciani: Monstre d'Amour
isAdult                                        0
startYear                                   2017
endYear                                       \N
runtimeMinutes                                 3
genres                               Music,Short
Name: 2007822, dtype: object

(9,)

tconst                                tt11829816
titleType                              tvEpisode
primaryTitle      La gran maestra Masha Simonova
originalTitle     La gran maestra Masha Simonova
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                44
genres                                     Drama
Name: 2007823, dtype: object

(9,)

tconst                tt11829818
titleType              tvEpisode
primaryTitle      Episode #2.261
originalTitle     Episode #2.261
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007824, dtype: object

(9,)

tconst                     tt1182981
titleType                      short
primaryTitle      Wrecked in Mid-Air
originalTitle     Wrecked in Mid-Air
isAdult                            0
startYear                       1914
endYear                           \N
runtimeMinutes                    \N
genres                   Drama,Short
Name: 2007825, dtype: object

(9,)

tconst                                                 tt11829820
titleType                                               tvEpisode
primaryTitle      How to Succeed in Business Without Really Dying
originalTitle     How to Succeed in Business Without Really Dying
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                        Action,Crime,Horror
Name: 2007826, dtype: object

(9,)

tconst                      tt11829822
titleType                    tvEpisode
primaryTitle              Episode #1.3
originalTitle             Episode #1.3
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007827, dtype: object

(9,)

tconst                                            tt11829824
titleType                                          tvEpisode
primaryTitle      Costco, Kraft White Bean, and Kraft Frozen
originalTitle     Costco, Kraft White Bean, and Kraft Frozen
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                Comedy
Name: 2007828, dtype: object

(9,)

tconst                      tt11829826
titleType                    tvEpisode
primaryTitle              Episode #1.4
originalTitle             Episode #1.4
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007829, dtype: object

(9,)

tconst                     tt11829828
titleType                   tvEpisode
primaryTitle           The Last Dance
originalTitle          The Last Dance
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Action,Crime,Horror
Name: 2007830, dtype: object

(9,)

tconst                                tt1182982
titleType                             tvEpisode
primaryTitle      Episode dated 8 February 2008
originalTitle     Episode dated 8 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                         Documentary,News
Name: 2007831, dtype: object

(9,)

tconst                      tt11829830
titleType                    tvEpisode
primaryTitle              Episode #1.5
originalTitle             Episode #1.5
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007832, dtype: object

(9,)

tconst                      tt11829834
titleType                    tvEpisode
primaryTitle              Episode #1.6
originalTitle             Episode #1.6
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007833, dtype: object

(9,)

tconst                tt11829836
titleType              tvEpisode
primaryTitle      Episode #2.262
originalTitle     Episode #2.262
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007834, dtype: object

(9,)

tconst                           tt1182983
titleType                        tvEpisode
primaryTitle                       Courage
originalTitle                      Courage
isAdult                                  0
startYear                             2000
endYear                                 \N
runtimeMinutes                          \N
genres            Animation,Family,Fantasy
Name: 2007835, dtype: object

(9,)

tconst                      tt11829840
titleType                    tvEpisode
primaryTitle              Episode #1.7
originalTitle             Episode #1.7
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007836, dtype: object

(9,)

tconst                      tt11829842
titleType                    tvEpisode
primaryTitle      Zaguresu's Dismissal
originalTitle     Zaguresu's Dismissal
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres                          Sci-Fi
Name: 2007837, dtype: object

(9,)

tconst                      tt11829844
titleType                    tvEpisode
primaryTitle              Episode #1.8
originalTitle             Episode #1.8
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007838, dtype: object

(9,)

tconst                      tt11829846
titleType                    tvEpisode
primaryTitle              Episode #1.9
originalTitle             Episode #1.9
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007839, dtype: object

(9,)

tconst                    tt11829848
titleType                  tvEpisode
primaryTitle      Ocho meses después
originalTitle     Ocho meses después
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    44
genres                         Drama
Name: 2007840, dtype: object

(9,)

tconst                                tt1182984
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2007841, dtype: object

(9,)

tconst                      tt11829850
titleType                    tvEpisode
primaryTitle             Episode #1.10
originalTitle            Episode #1.10
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007842, dtype: object

(9,)

tconst                                              tt11829852
titleType                                            tvEpisode
primaryTitle      Victoria y los bebés corren riesgo de muerte
originalTitle     Victoria y los bebés corren riesgo de muerte
isAdult                                                      0
startYear                                                 2020
endYear                                                     \N
runtimeMinutes                                              44
genres                                                   Drama
Name: 2007843, dtype: object

(9,)

tconst                 tt11829854
titleType                   short
primaryTitle      Monsieur Madame
originalTitle     Monsieur Madame
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres               Comedy,Short
Name: 2007844, dtype: object

(9,)

tconst                      tt11829856
titleType                        short
primaryTitle      Death and the Knight
originalTitle     Death and the Knight
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      34
genres                 Animation,Short
Name: 2007845, dtype: object

(9,)

tconst                         tt11829858
titleType                       tvEpisode
primaryTitle      Citizens in Development
originalTitle     Citizens in Development
isAdult                                 0
startYear                            2017
endYear                                \N
runtimeMinutes                         \N
genres                        Documentary
Name: 2007846, dtype: object

(9,)

tconst                tt1182985
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007847, dtype: object

(9,)

tconst                                            tt11829860
titleType                                          tvEpisode
primaryTitle      Masha secuestra al bebé de Nico y Victoria
originalTitle     Masha secuestra al bebé de Nico y Victoria
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            44
genres                                                 Drama
Name: 2007848, dtype: object

(9,)

tconst                tt11829862
titleType              tvEpisode
primaryTitle      Episode #2.263
originalTitle     Episode #2.263
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007849, dtype: object

(9,)

tconst                tt11829864
titleType              tvEpisode
primaryTitle      Episode #2.265
originalTitle     Episode #2.265
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007850, dtype: object

(9,)

tconst                tt11829866
titleType              tvEpisode
primaryTitle      Episode #2.264
originalTitle     Episode #2.264
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007851, dtype: object

(9,)

tconst                     tt11829868
titleType                   tvEpisode
primaryTitle                Desperado
originalTitle               Desperado
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     25
genres            Crime,Drama,Romance
Name: 2007852, dtype: object

(9,)

tconst                tt1182986
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007853, dtype: object

(9,)

tconst                tt11829870
titleType              tvEpisode
primaryTitle      Episode #2.267
originalTitle     Episode #2.267
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007854, dtype: object

(9,)

tconst                      tt11829872
titleType                    tvEpisode
primaryTitle              Episode #1.1
originalTitle             Episode #1.1
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007855, dtype: object

(9,)

tconst                tt11829874
titleType              tvEpisode
primaryTitle      Episode #2.266
originalTitle     Episode #2.266
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007856, dtype: object

(9,)

tconst                tt11829876
titleType              tvEpisode
primaryTitle      Episode #2.268
originalTitle     Episode #2.268
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007857, dtype: object

(9,)

tconst                tt11829878
titleType              tvEpisode
primaryTitle      Episode #2.269
originalTitle     Episode #2.269
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007858, dtype: object

(9,)

tconst                tt1182987
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007859, dtype: object

(9,)

tconst                tt11829880
titleType              tvEpisode
primaryTitle      Episode #2.270
originalTitle     Episode #2.270
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007860, dtype: object

(9,)

tconst                tt11829882
titleType              tvEpisode
primaryTitle      Episode #2.271
originalTitle     Episode #2.271
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007861, dtype: object

(9,)

tconst                 tt11829884
titleType                   movie
primaryTitle      Fate of Alakada
originalTitle     Fate of Alakada
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                114
genres                     Comedy
Name: 2007862, dtype: object

(9,)

tconst                      tt11829886
titleType                    tvEpisode
primaryTitle              Episode #1.2
originalTitle             Episode #1.2
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007863, dtype: object

(9,)

tconst                tt11829888
titleType              tvEpisode
primaryTitle      Episode #2.272
originalTitle     Episode #2.272
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007864, dtype: object

(9,)

tconst                tt1182988
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007865, dtype: object

(9,)

tconst             tt11829890
titleType           tvEpisode
primaryTitle       Technology
originalTitle      Technology
isAdult                     0
startYear                2017
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2007866, dtype: object

(9,)

tconst                         tt11829892
titleType                           video
primaryTitle      Sébastien Tellier: Love
originalTitle     Sébastien Tellier: Love
isAdult                                 0
startYear                            2014
endYear                                \N
runtimeMinutes                          3
genres              Animation,Music,Short
Name: 2007867, dtype: object

(9,)

tconst                tt11829894
titleType              tvEpisode
primaryTitle      Episode #2.273
originalTitle     Episode #2.273
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007868, dtype: object

(9,)

tconst                tt11829896
titleType              tvEpisode
primaryTitle      Episode #2.274
originalTitle     Episode #2.274
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007869, dtype: object

(9,)

tconst                tt11829898
titleType              tvEpisode
primaryTitle      Episode #2.275
originalTitle     Episode #2.275
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007870, dtype: object

(9,)

tconst                tt1182989
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2007871, dtype: object

(9,)

tconst                      tt11829900
titleType                    tvEpisode
primaryTitle              Episode #1.3
originalTitle             Episode #1.3
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007872, dtype: object

(9,)

tconst                tt11829902
titleType              tvEpisode
primaryTitle      Episode #2.276
originalTitle     Episode #2.276
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007873, dtype: object

(9,)

tconst                tt11829904
titleType              tvEpisode
primaryTitle      Episode #2.277
originalTitle     Episode #2.277
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007874, dtype: object

(9,)

tconst                      tt11829906
titleType                    tvEpisode
primaryTitle              Episode #1.4
originalTitle             Episode #1.4
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007875, dtype: object

(9,)

tconst                tt11829908
titleType              tvEpisode
primaryTitle      Episode #2.279
originalTitle     Episode #2.279
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007876, dtype: object

(9,)

tconst                 tt1182990
titleType              tvEpisode
primaryTitle      Episode #5.147
originalTitle     Episode #5.147
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007877, dtype: object

(9,)

tconst                tt11829910
titleType              tvEpisode
primaryTitle      Episode #2.278
originalTitle     Episode #2.278
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007878, dtype: object

(9,)

tconst                tt11829912
titleType              tvEpisode
primaryTitle      Episode #2.280
originalTitle     Episode #2.280
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007879, dtype: object

(9,)

tconst                      tt11829914
titleType                    tvEpisode
primaryTitle              Episode #1.5
originalTitle             Episode #1.5
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007880, dtype: object

(9,)

tconst                    tt11829916
titleType                  tvEpisode
primaryTitle      Public Authorities
originalTitle     Public Authorities
isAdult                            0
startYear                       2017
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2007881, dtype: object

(9,)

tconst                      tt11829918
titleType                    tvEpisode
primaryTitle              Episode #1.6
originalTitle             Episode #1.6
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007882, dtype: object

(9,)

tconst                 tt1182991
titleType              tvEpisode
primaryTitle      Episode #5.148
originalTitle     Episode #5.148
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2007883, dtype: object

(9,)

tconst               tt11829920
titleType             tvEpisode
primaryTitle      Episode #2.61
originalTitle     Episode #2.61
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007884, dtype: object

(9,)

tconst               tt11829922
titleType             tvEpisode
primaryTitle      Episode #2.63
originalTitle     Episode #2.63
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007885, dtype: object

(9,)

tconst               tt11829924
titleType             tvEpisode
primaryTitle      Episode #2.62
originalTitle     Episode #2.62
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007886, dtype: object

(9,)

tconst                      tt11829926
titleType                    tvEpisode
primaryTitle              Episode #1.7
originalTitle             Episode #1.7
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007887, dtype: object

(9,)

tconst               tt11829928
titleType             tvEpisode
primaryTitle      Episode #2.64
originalTitle     Episode #2.64
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007888, dtype: object

(9,)

tconst                  tt1182992
titleType               tvEpisode
primaryTitle        Episode #13.3
originalTitle       Episode #13.3
isAdult                         0
startYear                    1969
endYear                        \N
runtimeMinutes                 60
genres            Music,Talk-Show
Name: 2007889, dtype: object

(9,)

tconst               tt11829930
titleType             tvEpisode
primaryTitle      Episode #2.65
originalTitle     Episode #2.65
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007890, dtype: object

(9,)

tconst               tt11829932
titleType             tvEpisode
primaryTitle      Episode #2.66
originalTitle     Episode #2.66
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007891, dtype: object

(9,)

tconst                      tt11829934
titleType                    tvEpisode
primaryTitle              Episode #1.8
originalTitle             Episode #1.8
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007892, dtype: object

(9,)

tconst                  tt11829938
titleType                    short
primaryTitle      Just Let Me Know
originalTitle     Just Let Me Know
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres               Romance,Short
Name: 2007893, dtype: object

(9,)

tconst                tt1182993
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2007894, dtype: object

(9,)

tconst               tt11829940
titleType             tvEpisode
primaryTitle      Episode #2.68
originalTitle     Episode #2.68
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007895, dtype: object

(9,)

tconst               tt11829942
titleType             tvEpisode
primaryTitle      Episode #2.67
originalTitle     Episode #2.67
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007896, dtype: object

(9,)

tconst               tt11829944
titleType             tvEpisode
primaryTitle      Episode #2.69
originalTitle     Episode #2.69
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007897, dtype: object

(9,)

tconst               tt11829946
titleType             tvEpisode
primaryTitle      Episode #2.70
originalTitle     Episode #2.70
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007898, dtype: object

(9,)

tconst                      tt11829948
titleType                    tvEpisode
primaryTitle              Episode #1.9
originalTitle             Episode #1.9
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007899, dtype: object

(9,)

tconst                                tt1182994
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                    Family,News,Talk-Show
Name: 2007900, dtype: object

(9,)

tconst               tt11829950
titleType             tvEpisode
primaryTitle      Episode #2.71
originalTitle     Episode #2.71
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007901, dtype: object

(9,)

tconst                                         tt11829952
titleType                                           video
primaryTitle      Sébastien Tellier: Aller vers le soleil
originalTitle     Sébastien Tellier: Aller vers le soleil
isAdult                                                 0
startYear                                            2014
endYear                                                \N
runtimeMinutes                                          4
genres                                        Music,Short
Name: 2007902, dtype: object

(9,)

tconst                      tt11829954
titleType                    tvEpisode
primaryTitle             Episode #1.10
originalTitle            Episode #1.10
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2007903, dtype: object

(9,)

tconst               tt11829956
titleType             tvEpisode
primaryTitle      Episode #2.72
originalTitle     Episode #2.72
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007904, dtype: object

(9,)

tconst               tt11829958
titleType             tvEpisode
primaryTitle      Episode #2.74
originalTitle     Episode #2.74
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007905, dtype: object

(9,)

tconst                                tt1182995
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                   Comedy,Music,Talk-Show
Name: 2007906, dtype: object

(9,)

tconst               tt11829960
titleType             tvEpisode
primaryTitle      Episode #2.73
originalTitle     Episode #2.73
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007907, dtype: object

(9,)

tconst               tt11829962
titleType             tvEpisode
primaryTitle      Episode #2.76
originalTitle     Episode #2.76
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007908, dtype: object

(9,)

tconst               tt11829964
titleType             tvEpisode
primaryTitle      Episode #2.75
originalTitle     Episode #2.75
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007909, dtype: object

(9,)

tconst                                 tt11829966
titleType                               tvEpisode
primaryTitle      What Do I Have to Do With That?
originalTitle     What Do I Have to Do With That?
isAdult                                         0
startYear                                    2017
endYear                                        \N
runtimeMinutes                                 \N
genres                                Documentary
Name: 2007910, dtype: object

(9,)

tconst               tt11829968
titleType             tvEpisode
primaryTitle      Episode #2.78
originalTitle     Episode #2.78
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007911, dtype: object

(9,)

tconst                                tt1182996
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2007912, dtype: object

(9,)

tconst               tt11829970
titleType             tvEpisode
primaryTitle      Episode #2.77
originalTitle     Episode #2.77
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007913, dtype: object

(9,)

tconst                 tt11829972
titleType                   video
primaryTitle      Slut Meat Slave
originalTitle     Slut Meat Slave
isAdult                         1
startYear                    2010
endYear                        \N
runtimeMinutes                104
genres                      Adult
Name: 2007914, dtype: object

(9,)

tconst                                                   tt11829974
titleType                                                 tvEpisode
primaryTitle      Fodbold & Piger med DAVID MANDEL & JONATHAN FR...
originalTitle     Fodbold & Piger med DAVID MANDEL & JONATHAN FR...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2007915, dtype: object

(9,)

tconst               tt11829976
titleType             tvEpisode
primaryTitle      Episode #2.79
originalTitle     Episode #2.79
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007916, dtype: object

(9,)

tconst               tt11829978
titleType             tvEpisode
primaryTitle      Episode #2.80
originalTitle     Episode #2.80
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007917, dtype: object

(9,)

tconst                    tt1182997
titleType                 tvEpisode
primaryTitle      Wrongly Convicted
originalTitle     Wrongly Convicted
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   \N
genres            Crime,Documentary
Name: 2007918, dtype: object

(9,)

tconst               tt11829980
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007919, dtype: object

(9,)

tconst               tt11829984
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007920, dtype: object

(9,)

tconst               tt11829986
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007921, dtype: object

(9,)

tconst               tt11829988
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007922, dtype: object

(9,)

tconst                  tt1182998
titleType               tvEpisode
primaryTitle      Episode #1.6745
originalTitle     Episode #1.6745
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 23
genres              Drama,Romance
Name: 2007923, dtype: object

(9,)

tconst               tt11829990
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007924, dtype: object

(9,)

tconst               tt11829992
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007925, dtype: object

(9,)

tconst                      tt11829994
titleType                    tvEpisode
primaryTitle              Episode #1.1
originalTitle             Episode #1.1
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007926, dtype: object

(9,)

tconst               tt11829996
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007927, dtype: object

(9,)

tconst               tt11829998
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007928, dtype: object

(9,)

tconst                                               tt1182999
titleType                                             tvSeries
primaryTitle      Discovery Kids Ultimate Guide to the Awesome
originalTitle     Discovery Kids Ultimate Guide to the Awesome
isAdult                                                      0
startYear                                                 2002
endYear                                                     \N
runtimeMinutes                                              \N
genres                                             Documentary
Name: 2007929, dtype: object

(9,)

tconst               tt11830004
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007930, dtype: object

(9,)

tconst               tt11830006
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007931, dtype: object

(9,)

tconst                      tt11830008
titleType                    tvEpisode
primaryTitle              Episode #1.2
originalTitle             Episode #1.2
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007932, dtype: object

(9,)

tconst                tt1183000
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres              Crime,Drama
Name: 2007933, dtype: object

(9,)

tconst               tt11830010
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007934, dtype: object

(9,)

tconst               tt11830012
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007935, dtype: object

(9,)

tconst               tt11830014
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007936, dtype: object

(9,)

tconst               tt11830016
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007937, dtype: object

(9,)

tconst                      tt11830018
titleType                    tvEpisode
primaryTitle              Episode #1.3
originalTitle             Episode #1.3
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007938, dtype: object

(9,)

tconst                tt1183001
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres              Crime,Drama
Name: 2007939, dtype: object

(9,)

tconst               tt11830020
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007940, dtype: object

(9,)

tconst                      tt11830022
titleType                    tvEpisode
primaryTitle              Episode #1.4
originalTitle             Episode #1.4
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007941, dtype: object

(9,)

tconst               tt11830024
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007942, dtype: object

(9,)

tconst               tt11830026
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007943, dtype: object

(9,)

tconst               tt11830028
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007944, dtype: object

(9,)

tconst                                tt1183002
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2007945, dtype: object

(9,)

tconst               tt11830030
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007946, dtype: object

(9,)

tconst                     tt11830032
titleType                   tvEpisode
primaryTitle      Joker and Daydreams
originalTitle     Joker and Daydreams
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2007947, dtype: object

(9,)

tconst               tt11830034
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2007948, dtype: object

(9,)

tconst                      tt11830036
titleType                    tvEpisode
primaryTitle              Episode #1.5
originalTitle             Episode #1.5
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007949, dtype: object

(9,)

tconst                      tt11830038
titleType                    tvEpisode
primaryTitle              Episode #1.6
originalTitle             Episode #1.6
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007950, dtype: object

(9,)

tconst                                tt1183003
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2008
originalTitle     Episode dated 4 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                               Reality-TV
Name: 2007951, dtype: object

(9,)

tconst               tt11830040
titleType             tvEpisode
primaryTitle      Episode #3.21
originalTitle     Episode #3.21
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007952, dtype: object

(9,)

tconst                      tt11830042
titleType                    tvEpisode
primaryTitle              Episode #1.7
originalTitle             Episode #1.7
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007953, dtype: object

(9,)

tconst                                   tt11830044
titleType                                     short
primaryTitle      Noah, 18 ans (Noah, 18 years old)
originalTitle     Noah, 18 ans (Noah, 18 years old)
isAdult                                           0
startYear                                      2018
endYear                                          \N
runtimeMinutes                                   10
genres                                        Short
Name: 2007954, dtype: object

(9,)

tconst                      tt11830046
titleType                    tvEpisode
primaryTitle              Episode #1.8
originalTitle             Episode #1.8
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007955, dtype: object

(9,)

tconst                             tt11830048
titleType                               video
primaryTitle      Sébastien Tellier: L'adulte
originalTitle     Sébastien Tellier: L'adulte
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                              3
genres                            Music,Short
Name: 2007956, dtype: object

(9,)

tconst                       tt1183004
titleType                    tvEpisode
primaryTitle             Episode #1.59
originalTitle            Episode #1.59
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007957, dtype: object

(9,)

tconst                      tt11830050
titleType                    tvEpisode
primaryTitle              Episode #1.9
originalTitle             Episode #1.9
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007958, dtype: object

(9,)

tconst                tt11830052
titleType                  short
primaryTitle              Renard
originalTitle             Renard
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                10
genres            Short,Thriller
Name: 2007959, dtype: object

(9,)

tconst            tt11830054
titleType          tvEpisode
primaryTitle        Burn Out
originalTitle       Burn Out
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2007960, dtype: object

(9,)

tconst                                   tt11830056
titleType                                 tvEpisode
primaryTitle      MADS MIKKELSEN kommer på besøg!!!
originalTitle     MADS MIKKELSEN kommer på besøg!!!
isAdult                                           0
startYear                                      2019
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Comedy
Name: 2007961, dtype: object

(9,)

tconst                      tt11830058
titleType                    tvEpisode
primaryTitle             Episode #1.10
originalTitle            Episode #1.10
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007962, dtype: object

(9,)

tconst                       tt1183005
titleType                    tvEpisode
primaryTitle             Episode #1.60
originalTitle            Episode #1.60
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2007963, dtype: object

(9,)

tconst               tt11830060
titleType             tvEpisode
primaryTitle      Episode #3.22
originalTitle     Episode #3.22
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007964, dtype: object

(9,)

tconst               tt11830062
titleType             tvEpisode
primaryTitle      Episode #3.24
originalTitle     Episode #3.24
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007965, dtype: object

(9,)

tconst               tt11830064
titleType             tvEpisode
primaryTitle      Episode #3.23
originalTitle     Episode #3.23
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007966, dtype: object

(9,)

tconst               tt11830066
titleType             tvEpisode
primaryTitle      Episode #3.25
originalTitle     Episode #3.25
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007967, dtype: object

(9,)

tconst               tt11830068
titleType             tvEpisode
primaryTitle      Episode #3.27
originalTitle     Episode #3.27
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007968, dtype: object

(9,)

tconst                   tt1183006
titleType                tvEpisode
primaryTitle         Episode #2.15
originalTitle        Episode #2.15
isAdult                          0
startYear                     1982
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2007969, dtype: object

(9,)

tconst               tt11830070
titleType             tvEpisode
primaryTitle      Episode #3.26
originalTitle     Episode #3.26
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007970, dtype: object

(9,)

tconst               tt11830072
titleType             tvEpisode
primaryTitle      Episode #3.28
originalTitle     Episode #3.28
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007971, dtype: object

(9,)

tconst               tt11830074
titleType             tvEpisode
primaryTitle      Episode #3.29
originalTitle     Episode #3.29
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007972, dtype: object

(9,)

tconst                               tt11830076
titleType                             tvEpisode
primaryTitle      Episode dated 17 January 1954
originalTitle     Episode dated 17 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres               Documentary,Family,History
Name: 2007973, dtype: object

(9,)

tconst                                                   tt11830078
titleType                                                 tvEpisode
primaryTitle      Bourbon Gautier, Jeff Smallwood, Renée Martel,...
originalTitle     Bourbon Gautier, Jeff Smallwood, Renée Martel,...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007974, dtype: object

(9,)

tconst                   tt1183007
titleType                tvEpisode
primaryTitle          Episode #3.1
originalTitle         Episode #3.1
isAdult                          0
startYear                     1983
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2007975, dtype: object

(9,)

tconst               tt11830080
titleType             tvEpisode
primaryTitle      Episode #3.30
originalTitle     Episode #3.30
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007976, dtype: object

(9,)

tconst               tt11830082
titleType             tvEpisode
primaryTitle      Episode #3.32
originalTitle     Episode #3.32
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007977, dtype: object

(9,)

tconst               tt11830084
titleType             tvEpisode
primaryTitle      Episode #3.31
originalTitle     Episode #3.31
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007978, dtype: object

(9,)

tconst               tt11830086
titleType             tvEpisode
primaryTitle      Episode #3.33
originalTitle     Episode #3.33
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007979, dtype: object

(9,)

tconst              tt11830088
titleType                short
primaryTitle      Union County
originalTitle     Union County
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              14
genres             Drama,Short
Name: 2007980, dtype: object

(9,)

tconst                   tt1183008
titleType                tvEpisode
primaryTitle         Episode #3.12
originalTitle        Episode #3.12
isAdult                          0
startYear                     1983
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2007981, dtype: object

(9,)

tconst               tt11830090
titleType             tvEpisode
primaryTitle      Episode #3.34
originalTitle     Episode #3.34
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007982, dtype: object

(9,)

tconst               tt11830092
titleType             tvEpisode
primaryTitle      Episode #3.36
originalTitle     Episode #3.36
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007983, dtype: object

(9,)

tconst               tt11830094
titleType             tvEpisode
primaryTitle      Episode #3.35
originalTitle     Episode #3.35
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007984, dtype: object

(9,)

tconst               tt11830096
titleType             tvEpisode
primaryTitle      Episode #3.37
originalTitle     Episode #3.37
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007985, dtype: object

(9,)

tconst               tt11830098
titleType             tvEpisode
primaryTitle      Episode #3.38
originalTitle     Episode #3.38
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007986, dtype: object

(9,)

tconst                      tt1183009
titleType                   tvEpisode
primaryTitle      Llanerchaeron House
originalTitle     Llanerchaeron House
isAdult                             0
startYear                        2007
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2007987, dtype: object

(9,)

tconst                              tt11830100
titleType                            tvEpisode
primaryTitle      Politician - Clueless Expert
originalTitle     Politician - Clueless Expert
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                     Comedy,Drama,Sci-Fi
Name: 2007988, dtype: object

(9,)

tconst               tt11830102
titleType             tvEpisode
primaryTitle      Episode #3.39
originalTitle     Episode #3.39
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007989, dtype: object

(9,)

tconst               tt11830104
titleType             tvEpisode
primaryTitle      Episode #3.40
originalTitle     Episode #3.40
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007990, dtype: object

(9,)

tconst                                                   tt11830106
titleType                                                 tvEpisode
primaryTitle      André Proulx, Bourbon Gautier, Bruce Daigrepon...
originalTitle     André Proulx, Bourbon Gautier, Bruce Daigrepon...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2007991, dtype: object

(9,)

tconst               tt11830108
titleType             tvEpisode
primaryTitle      Episode #3.41
originalTitle     Episode #3.41
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007992, dtype: object

(9,)

tconst                                tt1183010
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2007993, dtype: object

(9,)

tconst               tt11830110
titleType             tvEpisode
primaryTitle      Episode #3.43
originalTitle     Episode #3.43
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007994, dtype: object

(9,)

tconst               tt11830112
titleType             tvEpisode
primaryTitle      Episode #3.42
originalTitle     Episode #3.42
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007995, dtype: object

(9,)

tconst               tt11830114
titleType             tvEpisode
primaryTitle      Episode #3.44
originalTitle     Episode #3.44
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007996, dtype: object

(9,)

tconst               tt11830116
titleType             tvEpisode
primaryTitle      Episode #3.45
originalTitle     Episode #3.45
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007997, dtype: object

(9,)

tconst               tt11830118
titleType             tvEpisode
primaryTitle      Episode #3.46
originalTitle     Episode #3.46
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2007998, dtype: object

(9,)

tconst                  tt1183011
titleType               tvEpisode
primaryTitle      Aflevering 3567
originalTitle     Aflevering 3567
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2007999, dtype: object

(9,)

tconst               tt11830120
titleType             tvEpisode
primaryTitle      Episode #3.47
originalTitle     Episode #3.47
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2008000, dtype: object

(9,)

tconst               tt11830122
titleType             tvEpisode
primaryTitle      Episode #3.48
originalTitle     Episode #3.48
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2008001, dtype: object

(9,)

tconst               tt11830124
titleType             tvEpisode
primaryTitle      Episode #3.50
originalTitle     Episode #3.50
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2008002, dtype: object

(9,)

tconst               tt11830126
titleType             tvEpisode
primaryTitle      Episode #3.49
originalTitle     Episode #3.49
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2008003, dtype: object

(9,)

tconst               tt11830128
titleType             tvEpisode
primaryTitle      Episode #3.51
originalTitle     Episode #3.51
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                Animation
Name: 2008004, dtype: object

(9,)

tconst                  tt1183012
titleType               tvEpisode
primaryTitle      Aflevering 3568
originalTitle     Aflevering 3568
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2008005, dtype: object

(9,)

tconst                                    tt11830130
titleType                                  tvEpisode
primaryTitle      The Trip to Greece: Troy to Kavala
originalTitle     The Trip to Greece: Troy to Kavala
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                        Comedy
Name: 2008006, dtype: object

(9,)

tconst              tt11830132
titleType            tvEpisode
primaryTitle      Episode #3.2
originalTitle     Episode #3.2
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2008007, dtype: object

(9,)

tconst              tt11830134
titleType            tvEpisode
primaryTitle      Episode #3.3
originalTitle     Episode #3.3
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2008008, dtype: object

(9,)

tconst            tt11830136
titleType          tvEpisode
primaryTitle        07162019
originalTitle       07162019
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres             Talk-Show
Name: 2008009, dtype: object

(9,)

tconst                                 tt11830138
titleType                                   video
primaryTitle      Sébastien Tellier: Cochon Ville
originalTitle     Sébastien Tellier: Cochon Ville
isAdult                                         0
startYear                                    2012
endYear                                        \N
runtimeMinutes                                  3
genres                                Music,Short
Name: 2008010, dtype: object

(9,)

tconst                  tt1183013
titleType               tvEpisode
primaryTitle      Aflevering 3569
originalTitle     Aflevering 3569
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2008011, dtype: object

(9,)

tconst                tt11830140
titleType              tvEpisode
primaryTitle      Episode #1.301
originalTitle     Episode #1.301
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008012, dtype: object

(9,)

tconst              tt11830142
titleType            tvEpisode
primaryTitle      Episode #3.4
originalTitle     Episode #3.4
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2008013, dtype: object

(9,)

tconst                  tt11830144
titleType                tvEpisode
primaryTitle      Kavala to Pelion
originalTitle     Kavala to Pelion
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2008014, dtype: object

(9,)

tconst                  tt11830146
titleType                tvEpisode
primaryTitle      Pelion to Athens
originalTitle     Pelion to Athens
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2008015, dtype: object

(9,)

tconst                 tt11830148
titleType               tvEpisode
primaryTitle      Athens to Hydra
originalTitle     Athens to Hydra
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2008016, dtype: object

(9,)

tconst                      tt1183014
titleType                   tvEpisode
primaryTitle           Episode #22.13
originalTitle          Episode #22.13
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2008017, dtype: object

(9,)

tconst              tt11830150
titleType            tvEpisode
primaryTitle      Episode #3.5
originalTitle     Episode #3.5
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2008018, dtype: object

(9,)

tconst                                tt11830152
titleType                              tvEpisode
primaryTitle      Episode dated 18 February 2020
originalTitle     Episode dated 18 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2008019, dtype: object

(9,)

tconst                tt11830154
titleType              tvEpisode
primaryTitle      Episode #1.302
originalTitle     Episode #1.302
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008020, dtype: object

(9,)

tconst                   tt11830156
titleType                 tvEpisode
primaryTitle      Hydra to the Mani
originalTitle     Hydra to the Mani
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2008021, dtype: object

(9,)

tconst                tt11830158
titleType              tvEpisode
primaryTitle      Episode #1.303
originalTitle     Episode #1.303
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008022, dtype: object

(9,)

tconst                      tt1183015
titleType                   tvEpisode
primaryTitle           Episode #22.14
originalTitle          Episode #22.14
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2008023, dtype: object

(9,)

tconst                tt11830160
titleType              tvEpisode
primaryTitle      Episode #1.304
originalTitle     Episode #1.304
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008024, dtype: object

(9,)

tconst                     tt11830162
titleType                   tvEpisode
primaryTitle        Bawal na pag-ibig
originalTitle       Bawal na pag-ibig
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     26
genres            Crime,Drama,Romance
Name: 2008025, dtype: object

(9,)

tconst                tt11830164
titleType              tvEpisode
primaryTitle      Episode #1.305
originalTitle     Episode #1.305
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008026, dtype: object

(9,)

tconst                    tt11830166
titleType                  tvEpisode
primaryTitle      The Mani to Ithaca
originalTitle     The Mani to Ithaca
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                        Comedy
Name: 2008027, dtype: object

(9,)

tconst                                         tt11830168
titleType                                       tvEpisode
primaryTitle      Eltoria and The Tailless WHIP SCORPION!
originalTitle     Eltoria and The Tailless WHIP SCORPION!
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                          Game-Show
Name: 2008028, dtype: object

(9,)

tconst                      tt1183016
titleType                   tvEpisode
primaryTitle           Episode #22.15
originalTitle          Episode #22.15
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2008029, dtype: object

(9,)

tconst                tt11830170
titleType              tvEpisode
primaryTitle      Episode #1.308
originalTitle     Episode #1.308
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008030, dtype: object

(9,)

tconst                            tt11830172
titleType                          tvEpisode
primaryTitle      Episode dated 13 June 2017
originalTitle     Episode dated 13 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                       Sport,Talk-Show
Name: 2008031, dtype: object

(9,)

tconst                tt11830174
titleType              tvEpisode
primaryTitle      Episode #1.307
originalTitle     Episode #1.307
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008032, dtype: object

(9,)

tconst                          tt11830176
titleType                        tvEpisode
primaryTitle      På date med NADJA HANSEN
originalTitle     På date med NADJA HANSEN
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          \N
genres                              Comedy
Name: 2008033, dtype: object

(9,)

tconst                tt11830178
titleType              tvEpisode
primaryTitle      Episode #1.306
originalTitle     Episode #1.306
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008034, dtype: object

(9,)

tconst                      tt1183017
titleType                   tvEpisode
primaryTitle           Episode #22.16
originalTitle          Episode #22.16
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2008035, dtype: object

(9,)

tconst                tt11830180
titleType              tvEpisode
primaryTitle      Episode #1.309
originalTitle     Episode #1.309
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008036, dtype: object

(9,)

tconst                tt11830182
titleType              tvEpisode
primaryTitle      Episode #1.310
originalTitle     Episode #1.310
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008037, dtype: object

(9,)

tconst                                                   tt11830184
titleType                                                     video
primaryTitle      Sébastien Tellier & Caroline Polachek: In the ...
originalTitle     Sébastien Tellier & Caroline Polachek: In the ...
isAdult                                                           0
startYear                                                      2013
endYear                                                          \N
runtimeMinutes                                                    3
genres                                                  Music,Short
Name: 2008038, dtype: object

(9,)

tconst                              tt11830186
titleType                            tvEpisode
primaryTitle      Episode dated 16 August 2017
originalTitle     Episode dated 16 August 2017
isAdult                                      0
startYear                                 2017
endYear                                     \N
runtimeMinutes                              \N
genres                         Sport,Talk-Show
Name: 2008039, dtype: object

(9,)

tconst                tt11830188
titleType              tvEpisode
primaryTitle      Episode #1.311
originalTitle     Episode #1.311
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008040, dtype: object

(9,)

tconst                      tt1183018
titleType                   tvEpisode
primaryTitle           Episode #22.17
originalTitle          Episode #22.17
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2008041, dtype: object

(9,)

tconst                tt11830190
titleType              tvEpisode
primaryTitle      Episode #1.313
originalTitle     Episode #1.313
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008042, dtype: object

(9,)

tconst                tt11830192
titleType              tvEpisode
primaryTitle      Episode #1.312
originalTitle     Episode #1.312
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008043, dtype: object

(9,)

tconst                                tt11830194
titleType                              tvEpisode
primaryTitle      Episode dated 7 September 2017
originalTitle     Episode dated 7 September 2017
isAdult                                        0
startYear                                   2017
endYear                                       \N
runtimeMinutes                                \N
genres                           Sport,Talk-Show
Name: 2008044, dtype: object

(9,)

tconst                tt11830196
titleType              tvEpisode
primaryTitle      Episode #1.314
originalTitle     Episode #1.314
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008045, dtype: object

(9,)

tconst                tt11830198
titleType              tvEpisode
primaryTitle      Episode #1.315
originalTitle     Episode #1.315
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008046, dtype: object

(9,)

tconst                      tt1183019
titleType                   tvEpisode
primaryTitle           Episode #22.18
originalTitle          Episode #22.18
isAdult                             0
startYear                        1999
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2008047, dtype: object

(9,)

tconst                tt11830200
titleType              tvEpisode
primaryTitle      Episode #1.316
originalTitle     Episode #1.316
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008048, dtype: object

(9,)

tconst                tt11830202
titleType              tvEpisode
primaryTitle      Episode #1.318
originalTitle     Episode #1.318
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008049, dtype: object

(9,)

tconst              tt11830204
titleType            tvEpisode
primaryTitle      Episode #3.6
originalTitle     Episode #3.6
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2008050, dtype: object

(9,)

tconst                tt11830206
titleType              tvEpisode
primaryTitle      Episode #1.317
originalTitle     Episode #1.317
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008051, dtype: object

(9,)

tconst                                 tt11830208
titleType                               tvEpisode
primaryTitle      Episode dated 19 September 2017
originalTitle     Episode dated 19 September 2017
isAdult                                         0
startYear                                    2017
endYear                                        \N
runtimeMinutes                                 \N
genres                            Sport,Talk-Show
Name: 2008052, dtype: object

(9,)

tconst               tt1183020
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008053, dtype: object

(9,)

tconst                tt11830210
titleType              tvEpisode
primaryTitle      Episode #1.320
originalTitle     Episode #1.320
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008054, dtype: object

(9,)

tconst                tt11830212
titleType              tvEpisode
primaryTitle      Episode #1.319
originalTitle     Episode #1.319
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008055, dtype: object

(9,)

tconst                               tt11830214
titleType                             tvEpisode
primaryTitle      Episode dated 18 October 2017
originalTitle     Episode dated 18 October 2017
isAdult                                       0
startYear                                  2017
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2008056, dtype: object

(9,)

tconst                               tt11830216
titleType                             tvEpisode
primaryTitle      Episode dated 16 October 1970
originalTitle     Episode dated 16 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2008057, dtype: object

(9,)

tconst                tt11830218
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008058, dtype: object

(9,)

tconst               tt1183021
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008059, dtype: object

(9,)

tconst                tt11830220
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008060, dtype: object

(9,)

tconst                tt11830222
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008061, dtype: object

(9,)

tconst                tt11830224
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008062, dtype: object

(9,)

tconst                tt11830226
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008063, dtype: object

(9,)

tconst                                tt1183022
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2008064, dtype: object

(9,)

tconst                tt11830230
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008065, dtype: object

(9,)

tconst                tt11830232
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008066, dtype: object

(9,)

tconst                tt11830234
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008067, dtype: object

(9,)

tconst              tt11830236
titleType            tvEpisode
primaryTitle      Episode #3.7
originalTitle     Episode #3.7
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2008068, dtype: object

(9,)

tconst                tt11830238
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008069, dtype: object

(9,)

tconst                tt1183023
titleType             tvEpisode
primaryTitle      Episode #2.20
originalTitle     Episode #2.20
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2008070, dtype: object

(9,)

tconst                tt11830240
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008071, dtype: object

(9,)

tconst                tt11830242
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008072, dtype: object

(9,)

tconst                tt11830244
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008073, dtype: object

(9,)

tconst                                           tt11830246
titleType                                         tvEpisode
primaryTitle      Kærester og Guldtuben med RASMUS BROHAVE!
originalTitle     Kærester og Guldtuben med RASMUS BROHAVE!
isAdult                                                   0
startYear                                              2019
endYear                                                  \N
runtimeMinutes                                           \N
genres                                               Comedy
Name: 2008074, dtype: object

(9,)

tconst                tt11830248
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008075, dtype: object

(9,)

tconst                        tt1183024
titleType                      tvSeries
primaryTitle      Inside This Old House
originalTitle     Inside This Old House
isAdult                               0
startYear                          2003
endYear                            2004
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2008076, dtype: object

(9,)

tconst                tt11830250
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008077, dtype: object

(9,)

tconst                tt11830252
titleType              tvEpisode
primaryTitle      Episode #1.116
originalTitle     Episode #1.116
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008078, dtype: object

(9,)

tconst                tt11830254
titleType              tvEpisode
primaryTitle      Episode #1.115
originalTitle     Episode #1.115
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008079, dtype: object

(9,)

tconst                tt11830256
titleType              tvEpisode
primaryTitle      Episode #1.117
originalTitle     Episode #1.117
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008080, dtype: object

(9,)

tconst              tt11830258
titleType            tvEpisode
primaryTitle      Episode #3.8
originalTitle     Episode #3.8
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2008081, dtype: object

(9,)

tconst                tt11830260
titleType              tvEpisode
primaryTitle      Episode #1.118
originalTitle     Episode #1.118
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008082, dtype: object

(9,)

tconst                 tt11830262
titleType                   movie
primaryTitle      Dassen sanjushi
originalTitle     Dassen sanjushi
isAdult                         0
startYear                    1935
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2008083, dtype: object

(9,)

tconst                tt11830264
titleType              tvEpisode
primaryTitle      Episode #1.119
originalTitle     Episode #1.119
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008084, dtype: object

(9,)

tconst                tt11830266
titleType              tvEpisode
primaryTitle      Episode #1.120
originalTitle     Episode #1.120
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008085, dtype: object

(9,)

tconst                tt11830268
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008086, dtype: object

(9,)

tconst                  tt1183026
titleType               tvEpisode
primaryTitle      Episode #12.107
originalTitle     Episode #12.107
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2008087, dtype: object

(9,)

tconst                                                   tt11830270
titleType                                                 tvEpisode
primaryTitle      André Proulx, Bruce Daigrepont, Gary Boudreaul...
originalTitle     André Proulx, Bruce Daigrepont, Gary Boudreaul...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008088, dtype: object

(9,)

tconst                tt11830272
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008089, dtype: object

(9,)

tconst                                         tt11830274
titleType                                       tvEpisode
primaryTitle      Gran final parte 1: Cada segundo cuenta
originalTitle     Gran final parte 1: Cada segundo cuenta
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         44
genres                                              Drama
Name: 2008090, dtype: object

(9,)

tconst                tt11830276
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008091, dtype: object

(9,)

tconst                tt11830278
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008092, dtype: object

(9,)

tconst            tt11830280
titleType          tvEpisode
primaryTitle       Kliimaksi
originalTitle      Kliimaksi
isAdult                    0
startYear               2012
endYear                   \N
runtimeMinutes            23
genres                Comedy
Name: 2008093, dtype: object

(9,)

tconst                tt11830282
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008094, dtype: object

(9,)

tconst              tt11830284
titleType            tvEpisode
primaryTitle      Episode #3.9
originalTitle     Episode #3.9
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2008095, dtype: object

(9,)

tconst                tt11830286
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008096, dtype: object

(9,)

tconst                tt11830288
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008097, dtype: object

(9,)

tconst                       tt1183028
titleType                    tvEpisode
primaryTitle             Episode #4.21
originalTitle            Episode #4.21
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2008098, dtype: object

(9,)

tconst                               tt11830290
titleType                             tvEpisode
primaryTitle      NICKLAS BENDTNER i studiet!!!
originalTitle     NICKLAS BENDTNER i studiet!!!
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               \N
genres                                   Comedy
Name: 2008099, dtype: object

(9,)

tconst                tt11830292
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008100, dtype: object

(9,)

tconst                tt11830296
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008101, dtype: object

(9,)

tconst                tt11830298
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008102, dtype: object

(9,)

tconst                       tt1183029
titleType                    tvEpisode
primaryTitle             Episode #4.22
originalTitle            Episode #4.22
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2008103, dtype: object

(9,)

tconst               tt11830300
titleType             tvEpisode
primaryTitle      Episode #3.10
originalTitle     Episode #3.10
isAdult                       0
startYear                  2013
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2008104, dtype: object

(9,)

tconst                tt11830302
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008105, dtype: object

(9,)

tconst                tt11830304
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008106, dtype: object

(9,)

tconst                tt11830306
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008107, dtype: object

(9,)

tconst                                tt11830308
titleType                                  video
primaryTitle      Sébastien Tellier: Pépito Bleu
originalTitle     Sébastien Tellier: Pépito Bleu
isAdult                                        0
startYear                                   2012
endYear                                       \N
runtimeMinutes                                 3
genres                               Music,Short
Name: 2008108, dtype: object

(9,)

tconst                  tt1183030
titleType               tvEpisode
primaryTitle      Au nom de toi 1
originalTitle     Au nom de toi 1
isAdult                         0
startYear                    2002
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2008109, dtype: object

(9,)

tconst                tt11830310
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                   2010
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008110, dtype: object

(9,)

tconst                    tt11830312
titleType                  tvEpisode
primaryTitle      Yhtä vuoristorataa
originalTitle     Yhtä vuoristorataa
isAdult                            0
startYear                       2012
endYear                           \N
runtimeMinutes                    21
genres                        Comedy
Name: 2008111, dtype: object

(9,)

tconst               tt11830314
titleType             tvEpisode
primaryTitle      Episode #3.11
originalTitle     Episode #3.11
isAdult                       0
startYear                  2013
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2008112, dtype: object

(9,)

tconst              tt11830316
titleType            tvEpisode
primaryTitle      Spooktacular
originalTitle     Spooktacular
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2008113, dtype: object

(9,)

tconst                tt11830318
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008114, dtype: object

(9,)

tconst                        tt1183031
titleType                     tvEpisode
primaryTitle      'Til Death Do Us Part
originalTitle     'Til Death Do Us Part
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       48
genres              Crime,Drama,Mystery
Name: 2008115, dtype: object

(9,)

tconst                    tt11830320
titleType                      short
primaryTitle      Huntsville Station
originalTitle     Huntsville Station
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    14
genres             Documentary,Short
Name: 2008116, dtype: object

(9,)

tconst               tt11830324
titleType          tvMiniSeries
primaryTitle      My Friend Max
originalTitle     My Friend Max
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Animation
Name: 2008117, dtype: object

(9,)

tconst                tt11830326
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008118, dtype: object

(9,)

tconst                tt11830328
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008119, dtype: object

(9,)

tconst                      tt1183032
titleType                   tvEpisode
primaryTitle       Let Loose the Dogs
originalTitle      Let Loose the Dogs
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     48
genres            Crime,Drama,Mystery
Name: 2008120, dtype: object

(9,)

tconst                                                   tt11830330
titleType                                                 tvEpisode
primaryTitle      Dani Daraîche, David Bernatchez, Émilie Daraîc...
originalTitle     Dani Daraîche, David Bernatchez, Émilie Daraîc...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008121, dtype: object

(9,)

tconst                                 tt11830332
titleType                               tvEpisode
primaryTitle      Episode dated 29 September 1990
originalTitle     Episode dated 29 September 1990
isAdult                                         0
startYear                                    1990
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2008122, dtype: object

(9,)

tconst                tt11830334
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008123, dtype: object

(9,)

tconst                tt11830336
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008124, dtype: object

(9,)

tconst                tt11830338
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008125, dtype: object

(9,)

tconst                         tt1183033
titleType                      tvEpisode
primaryTitle              Episode #21.12
originalTitle             Episode #21.12
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres            Comedy,Game-Show,Music
Name: 2008126, dtype: object

(9,)

tconst                tt11830340
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008127, dtype: object

(9,)

tconst                tt11830342
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008128, dtype: object

(9,)

tconst                tt11830344
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008129, dtype: object

(9,)

tconst               tt11830346
titleType             tvEpisode
primaryTitle      Episode #3.12
originalTitle     Episode #3.12
isAdult                       0
startYear                  2013
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2008130, dtype: object

(9,)

tconst                tt11830348
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008131, dtype: object

(9,)

tconst                tt1183034
titleType             tvEpisode
primaryTitle      Episode #6.80
originalTitle     Episode #6.80
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2008132, dtype: object

(9,)

tconst                tt11830350
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008133, dtype: object

(9,)

tconst                tt11830352
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008134, dtype: object

(9,)

tconst                tt11830354
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008135, dtype: object

(9,)

tconst                tt11830356
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008136, dtype: object

(9,)

tconst                                tt1183035
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               30
genres                           News,Talk-Show
Name: 2008137, dtype: object

(9,)

tconst                tt11830360
titleType              tvEpisode
primaryTitle      Episode #1.115
originalTitle     Episode #1.115
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008138, dtype: object

(9,)

tconst                tt11830362
titleType              tvEpisode
primaryTitle      Episode #1.116
originalTitle     Episode #1.116
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008139, dtype: object

(9,)

tconst                                                   tt11830364
titleType                                                 tvEpisode
primaryTitle      Cayouche, Chuck Labelle, Josée Truchon, Stephe...
originalTitle     Cayouche, Chuck Labelle, Josée Truchon, Stephe...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008140, dtype: object

(9,)

tconst                tt11830366
titleType              tvEpisode
primaryTitle      Episode #1.117
originalTitle     Episode #1.117
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008141, dtype: object

(9,)

tconst                tt11830368
titleType              tvEpisode
primaryTitle      Episode #1.118
originalTitle     Episode #1.118
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008142, dtype: object

(9,)

tconst                                tt1183036
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               60
genres                           News,Talk-Show
Name: 2008143, dtype: object

(9,)

tconst              tt11830370
titleType                movie
primaryTitle      Yubi wa akai
originalTitle     Yubi wa akai
isAdult                      0
startYear                 1936
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008144, dtype: object

(9,)

tconst                tt11830372
titleType              tvEpisode
primaryTitle      Episode #1.119
originalTitle     Episode #1.119
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008145, dtype: object

(9,)

tconst                tt11830374
titleType              tvEpisode
primaryTitle      Episode #1.120
originalTitle     Episode #1.120
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008146, dtype: object

(9,)

tconst                          tt11830376
titleType                            video
primaryTitle      Sébastien Tellier: Roche
originalTitle     Sébastien Tellier: Roche
isAdult                                  0
startYear                             2009
endYear                                 \N
runtimeMinutes                           3
genres                         Music,Short
Name: 2008147, dtype: object

(9,)

tconst                 tt11830378
titleType               tvEpisode
primaryTitle      Episode #1.1641
originalTitle     Episode #1.1641
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008148, dtype: object

(9,)

tconst                                tt1183037
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2008
originalTitle     Episode dated 4 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Drama
Name: 2008149, dtype: object

(9,)

tconst                           tt11830380
titleType                             movie
primaryTitle      Rien ne se perd (Rolling)
originalTitle     Rien ne se perd (Rolling)
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                               Comedy
Name: 2008150, dtype: object

(9,)

tconst                 tt11830382
titleType               tvEpisode
primaryTitle      Anthony Hopkins
originalTitle     Anthony Hopkins
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2008151, dtype: object

(9,)

tconst                 tt11830384
titleType               tvEpisode
primaryTitle      Episode #1.1642
originalTitle     Episode #1.1642
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008152, dtype: object

(9,)

tconst                 tt11830386
titleType               tvEpisode
primaryTitle      Episode #1.1643
originalTitle     Episode #1.1643
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008153, dtype: object

(9,)

tconst                 tt11830388
titleType               tvEpisode
primaryTitle      Episode #1.1644
originalTitle     Episode #1.1644
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008154, dtype: object

(9,)

tconst                                tt1183038
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2008
originalTitle     Episode dated 5 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Drama
Name: 2008155, dtype: object

(9,)

tconst                          tt11830390
titleType                        tvEpisode
primaryTitle      El que persevera alcanza
originalTitle     El que persevera alcanza
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          44
genres                               Drama
Name: 2008156, dtype: object

(9,)

tconst                 tt11830392
titleType               tvEpisode
primaryTitle      Episode #1.1645
originalTitle     Episode #1.1645
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008157, dtype: object

(9,)

tconst                     tt11830394
titleType                   tvEpisode
primaryTitle      Jeg har fødselsdag!
originalTitle     Jeg har fødselsdag!
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2008158, dtype: object

(9,)

tconst                 tt11830396
titleType               tvEpisode
primaryTitle      Episode #1.1646
originalTitle     Episode #1.1646
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008159, dtype: object

(9,)

tconst            tt11830398
titleType          tvEpisode
primaryTitle        Premiere
originalTitle       Premiere
isAdult                    0
startYear               2005
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2008160, dtype: object

(9,)

tconst                                tt1183039
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Drama
Name: 2008161, dtype: object

(9,)

tconst                 tt11830400
titleType               tvEpisode
primaryTitle      Episode #1.1647
originalTitle     Episode #1.1647
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008162, dtype: object

(9,)

tconst                 tt11830404
titleType               tvEpisode
primaryTitle      Episode #1.1649
originalTitle     Episode #1.1649
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008163, dtype: object

(9,)

tconst            tt11830406
titleType          tvEpisode
primaryTitle        Premiere
originalTitle       Premiere
isAdult                    0
startYear               2006
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2008164, dtype: object

(9,)

tconst                 tt11830408
titleType               tvEpisode
primaryTitle      Episode #1.1650
originalTitle     Episode #1.1650
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008165, dtype: object

(9,)

tconst                                tt1183040
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Drama
Name: 2008166, dtype: object

(9,)

tconst                 tt11830410
titleType               tvEpisode
primaryTitle      Episode #1.1651
originalTitle     Episode #1.1651
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008167, dtype: object

(9,)

tconst               tt11830412
titleType                 short
primaryTitle      The Evil Doll
originalTitle     The Evil Doll
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres             Horror,Short
Name: 2008168, dtype: object

(9,)

tconst                 tt11830414
titleType               tvEpisode
primaryTitle      Episode #1.1652
originalTitle     Episode #1.1652
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008169, dtype: object

(9,)

tconst                 tt11830416
titleType               tvEpisode
primaryTitle      Episode #1.1653
originalTitle     Episode #1.1653
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008170, dtype: object

(9,)

tconst            tt11830418
titleType          tvEpisode
primaryTitle        Premiere
originalTitle       Premiere
isAdult                    0
startYear               2007
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2008171, dtype: object

(9,)

tconst                                tt1183041
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                     News,Sport,Talk-Show
Name: 2008172, dtype: object

(9,)

tconst                 tt11830420
titleType               tvEpisode
primaryTitle      Episode #1.1654
originalTitle     Episode #1.1654
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008173, dtype: object

(9,)

tconst                                                   tt11830422
titleType                                                 tvEpisode
primaryTitle      Florian Gagné, Gaétane Beaubien, Marco Dorval,...
originalTitle     Florian Gagné, Gaétane Beaubien, Marco Dorval,...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008174, dtype: object

(9,)

tconst                 tt11830424
titleType               tvEpisode
primaryTitle      Episode #1.1655
originalTitle     Episode #1.1655
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008175, dtype: object

(9,)

tconst                 tt11830426
titleType               tvEpisode
primaryTitle      Episode #1.2704
originalTitle     Episode #1.2704
isAdult                         0
startYear                    1985
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2008176, dtype: object

(9,)

tconst                 tt1183042
titleType              tvEpisode
primaryTitle      Episode #2.103
originalTitle     Episode #2.103
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008177, dtype: object

(9,)

tconst                 tt11830430
titleType               tvEpisode
primaryTitle      Episode #1.1656
originalTitle     Episode #1.1656
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008178, dtype: object

(9,)

tconst                         tt11830432
titleType                           video
primaryTitle      Sébastien Tellier: Look
originalTitle     Sébastien Tellier: Look
isAdult                                 0
startYear                            2011
endYear                                \N
runtimeMinutes                          4
genres              Animation,Music,Short
Name: 2008179, dtype: object

(9,)

tconst                     tt11830434
titleType                       short
primaryTitle      Portrait of Pockets
originalTitle     Portrait of Pockets
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     12
genres              Documentary,Short
Name: 2008180, dtype: object

(9,)

tconst                 tt11830436
titleType               tvEpisode
primaryTitle      Episode #1.1657
originalTitle     Episode #1.1657
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008181, dtype: object

(9,)

tconst                    tt11830438
titleType                  tvEpisode
primaryTitle      Vencer el silencio
originalTitle     Vencer el silencio
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    44
genres                         Drama
Name: 2008182, dtype: object

(9,)

tconst                   tt1183043
titleType                 tvSeries
primaryTitle                   Paz
originalTitle                  Paz
isAdult                          0
startYear                     2005
endYear                       2006
runtimeMinutes                  \N
genres            Animation,Family
Name: 2008183, dtype: object

(9,)

tconst                 tt11830440
titleType               tvEpisode
primaryTitle      Episode #1.1658
originalTitle     Episode #1.1658
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008184, dtype: object

(9,)

tconst                 tt11830442
titleType               tvEpisode
primaryTitle      Episode #1.1659
originalTitle     Episode #1.1659
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008185, dtype: object

(9,)

tconst                 tt11830444
titleType               tvEpisode
primaryTitle      Episode #1.1660
originalTitle     Episode #1.1660
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008186, dtype: object

(9,)

tconst            tt11830446
titleType          tvEpisode
primaryTitle          Finale
originalTitle         Finale
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            23
genres                 Drama
Name: 2008187, dtype: object

(9,)

tconst                             tt11830448
titleType                           tvEpisode
primaryTitle      El fin justifica los medios
originalTitle     El fin justifica los medios
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             44
genres                                  Drama
Name: 2008188, dtype: object

(9,)

tconst                 tt11830452
titleType               tvEpisode
primaryTitle      Episode #1.1341
originalTitle     Episode #1.1341
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008189, dtype: object

(9,)

tconst                 tt11830454
titleType               tvEpisode
primaryTitle      Episode #1.1342
originalTitle     Episode #1.1342
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008190, dtype: object

(9,)

tconst             tt11830456
titleType               short
primaryTitle      Not so fast
originalTitle     Not so fast
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              2
genres            Crime,Short
Name: 2008191, dtype: object

(9,)

tconst                 tt11830458
titleType               tvEpisode
primaryTitle      Episode #1.1343
originalTitle     Episode #1.1343
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008192, dtype: object

(9,)

tconst                 tt11830460
titleType               tvEpisode
primaryTitle      Episode #1.1344
originalTitle     Episode #1.1344
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008193, dtype: object

(9,)

tconst                 tt11830462
titleType               tvEpisode
primaryTitle      Episode #1.1346
originalTitle     Episode #1.1346
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008194, dtype: object

(9,)

tconst                 tt11830464
titleType               tvEpisode
primaryTitle      Episode #1.1345
originalTitle     Episode #1.1345
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008195, dtype: object

(9,)

tconst                 tt11830466
titleType               tvEpisode
primaryTitle      Episode #1.1347
originalTitle     Episode #1.1347
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008196, dtype: object

(9,)

tconst                                     tt11830468
titleType                                   tvEpisode
primaryTitle      Inés rechaza divorciarse de Vicente
originalTitle     Inés rechaza divorciarse de Vicente
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     44
genres                                          Drama
Name: 2008197, dtype: object

(9,)

tconst                 tt11830470
titleType               tvEpisode
primaryTitle      Episode #1.1348
originalTitle     Episode #1.1348
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008198, dtype: object

(9,)

tconst                 tt11830472
titleType               tvEpisode
primaryTitle      Episode #1.1349
originalTitle     Episode #1.1349
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008199, dtype: object

(9,)

tconst                 tt11830474
titleType               tvEpisode
primaryTitle      Episode #1.1350
originalTitle     Episode #1.1350
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008200, dtype: object

(9,)

tconst                              tt11830476
titleType                                video
primaryTitle      Sébastien Tellier: Kilometer
originalTitle     Sébastien Tellier: Kilometer
isAdult                                      0
startYear                                 2011
endYear                                     \N
runtimeMinutes                               3
genres                             Music,Short
Name: 2008201, dtype: object

(9,)

tconst                 tt11830478
titleType               tvEpisode
primaryTitle      Episode #1.1351
originalTitle     Episode #1.1351
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008202, dtype: object

(9,)

tconst                                tt1183047
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2008203, dtype: object

(9,)

tconst              tt11830480
titleType            tvEpisode
primaryTitle      HJÆLP MIG!!!
originalTitle     HJÆLP MIG!!!
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008204, dtype: object

(9,)

tconst                 tt11830482
titleType               tvEpisode
primaryTitle      Episode #1.1353
originalTitle     Episode #1.1353
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008205, dtype: object

(9,)

tconst                 tt11830484
titleType               tvEpisode
primaryTitle      Episode #1.1352
originalTitle     Episode #1.1352
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008206, dtype: object

(9,)

tconst                 tt11830486
titleType               tvEpisode
primaryTitle      Episode #1.1355
originalTitle     Episode #1.1355
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008207, dtype: object

(9,)

tconst                 tt11830488
titleType               tvEpisode
primaryTitle      Episode #1.1354
originalTitle     Episode #1.1354
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008208, dtype: object

(9,)

tconst                                tt1183048
titleType                             tvEpisode
primaryTitle      Episode dated 9 February 2008
originalTitle     Episode dated 9 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Game-Show
Name: 2008209, dtype: object

(9,)

tconst                 tt11830490
titleType               tvEpisode
primaryTitle      Episode #1.1357
originalTitle     Episode #1.1357
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008210, dtype: object

(9,)

tconst                 tt11830492
titleType               tvEpisode
primaryTitle      Episode #1.1356
originalTitle     Episode #1.1356
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008211, dtype: object

(9,)

tconst                 tt11830494
titleType               tvEpisode
primaryTitle      Episode #1.1358
originalTitle     Episode #1.1358
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008212, dtype: object

(9,)

tconst                 tt11830496
titleType               tvEpisode
primaryTitle      Episode #1.1359
originalTitle     Episode #1.1359
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008213, dtype: object

(9,)

tconst                 tt11830498
titleType               tvEpisode
primaryTitle      Episode #1.1360
originalTitle     Episode #1.1360
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008214, dtype: object

(9,)

tconst                                tt1183049
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2008215, dtype: object

(9,)

tconst                 tt11830500
titleType               tvEpisode
primaryTitle      Episode #1.1141
originalTitle     Episode #1.1141
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008216, dtype: object

(9,)

tconst                 tt11830502
titleType               tvEpisode
primaryTitle      Episode #1.1143
originalTitle     Episode #1.1143
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008217, dtype: object

(9,)

tconst                 tt11830504
titleType               tvEpisode
primaryTitle      Episode #1.1144
originalTitle     Episode #1.1144
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008218, dtype: object

(9,)

tconst                 tt11830506
titleType               tvEpisode
primaryTitle      Episode #1.1142
originalTitle     Episode #1.1142
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008219, dtype: object

(9,)

tconst                 tt11830508
titleType               tvEpisode
primaryTitle      Episode #1.1145
originalTitle     Episode #1.1145
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008220, dtype: object

(9,)

tconst               tt1183050
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008221, dtype: object

(9,)

tconst                 tt11830510
titleType               tvEpisode
primaryTitle      Episode #1.1147
originalTitle     Episode #1.1147
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008222, dtype: object

(9,)

tconst                 tt11830512
titleType               tvEpisode
primaryTitle      Episode #1.1146
originalTitle     Episode #1.1146
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008223, dtype: object

(9,)

tconst                 tt11830514
titleType               tvEpisode
primaryTitle      Episode #1.1149
originalTitle     Episode #1.1149
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008224, dtype: object

(9,)

tconst                 tt11830516
titleType               tvEpisode
primaryTitle      Episode #1.1148
originalTitle     Episode #1.1148
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008225, dtype: object

(9,)

tconst                                                   tt11830518
titleType                                                 tvEpisode
primaryTitle      Annie Blanchard, Damien Robitaille, Florent Vo...
originalTitle     Annie Blanchard, Damien Robitaille, Florent Vo...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008226, dtype: object

(9,)

tconst               tt1183051
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008227, dtype: object

(9,)

tconst                 tt11830520
titleType               tvEpisode
primaryTitle      Episode #1.1150
originalTitle     Episode #1.1150
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008228, dtype: object

(9,)

tconst                           tt11830522
titleType                         tvEpisode
primaryTitle      ¿Existe el justo castigo?
originalTitle     ¿Existe el justo castigo?
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           44
genres                                Drama
Name: 2008229, dtype: object

(9,)

tconst                 tt11830524
titleType               tvEpisode
primaryTitle      Episode #1.1151
originalTitle     Episode #1.1151
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008230, dtype: object

(9,)

tconst                             tt11830526
titleType                           tvEpisode
primaryTitle      Episode dated 13 March 2015
originalTitle     Episode dated 13 March 2015
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2008231, dtype: object

(9,)

tconst                 tt11830528
titleType               tvEpisode
primaryTitle      Episode #1.1153
originalTitle     Episode #1.1153
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008232, dtype: object

(9,)

tconst               tt1183052
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008233, dtype: object

(9,)

tconst                 tt11830530
titleType               tvEpisode
primaryTitle      Episode #1.1152
originalTitle     Episode #1.1152
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008234, dtype: object

(9,)

tconst                 tt11830532
titleType               tvEpisode
primaryTitle      Episode #1.1154
originalTitle     Episode #1.1154
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008235, dtype: object

(9,)

tconst                           tt11830534
titleType                             video
primaryTitle      Sébastien Tellier: Divine
originalTitle     Sébastien Tellier: Divine
isAdult                                   0
startYear                              2008
endYear                                  \N
runtimeMinutes                            3
genres                          Music,Short
Name: 2008236, dtype: object

(9,)

tconst                             tt11830536
titleType                           tvEpisode
primaryTitle      Episode dated 23 March 2015
originalTitle     Episode dated 23 March 2015
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2008237, dtype: object

(9,)

tconst                 tt11830538
titleType               tvEpisode
primaryTitle      Episode #1.1156
originalTitle     Episode #1.1156
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008238, dtype: object

(9,)

tconst               tt1183053
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008239, dtype: object

(9,)

tconst                 tt11830540
titleType               tvEpisode
primaryTitle      Episode #1.1155
originalTitle     Episode #1.1155
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008240, dtype: object

(9,)

tconst                 tt11830542
titleType               tvEpisode
primaryTitle      Episode #1.1157
originalTitle     Episode #1.1157
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008241, dtype: object

(9,)

tconst                             tt11830544
titleType                           tvEpisode
primaryTitle      Episode dated 27 March 2015
originalTitle     Episode dated 27 March 2015
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2008242, dtype: object

(9,)

tconst                 tt11830546
titleType               tvEpisode
primaryTitle      Episode #1.1158
originalTitle     Episode #1.1158
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008243, dtype: object

(9,)

tconst                 tt11830548
titleType               tvEpisode
primaryTitle      Episode #1.1159
originalTitle     Episode #1.1159
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008244, dtype: object

(9,)

tconst               tt1183054
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008245, dtype: object

(9,)

tconst                             tt11830550
titleType                           tvEpisode
primaryTitle      Episode dated 13 April 2015
originalTitle     Episode dated 13 April 2015
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2008246, dtype: object

(9,)

tconst                 tt11830552
titleType               tvEpisode
primaryTitle      Episode #1.1160
originalTitle     Episode #1.1160
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2008247, dtype: object

(9,)

tconst                tt11830554
titleType              tvEpisode
primaryTitle      Episode #1.901
originalTitle     Episode #1.901
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008248, dtype: object

(9,)

tconst                tt11830556
titleType              tvEpisode
primaryTitle      Episode #1.902
originalTitle     Episode #1.902
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008249, dtype: object

(9,)

tconst                tt11830558
titleType              tvEpisode
primaryTitle      Episode #1.903
originalTitle     Episode #1.903
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008250, dtype: object

(9,)

tconst               tt1183055
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008251, dtype: object

(9,)

tconst                             tt11830560
titleType                           tvEpisode
primaryTitle      Episode dated 17 April 2015
originalTitle     Episode dated 17 April 2015
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2008252, dtype: object

(9,)

tconst                tt11830562
titleType              tvEpisode
primaryTitle      Episode #1.904
originalTitle     Episode #1.904
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008253, dtype: object

(9,)

tconst                tt11830564
titleType              tvEpisode
primaryTitle      Episode #1.905
originalTitle     Episode #1.905
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008254, dtype: object

(9,)

tconst                tt11830566
titleType              tvEpisode
primaryTitle      Episode #1.906
originalTitle     Episode #1.906
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008255, dtype: object

(9,)

tconst                tt11830568
titleType              tvEpisode
primaryTitle      Episode #1.907
originalTitle     Episode #1.907
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008256, dtype: object

(9,)

tconst               tt1183056
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008257, dtype: object

(9,)

tconst                tt11830570
titleType              tvEpisode
primaryTitle      Episode #1.909
originalTitle     Episode #1.909
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008258, dtype: object

(9,)

tconst                tt11830572
titleType              tvEpisode
primaryTitle      Episode #1.908
originalTitle     Episode #1.908
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008259, dtype: object

(9,)

tconst                tt11830574
titleType              tvEpisode
primaryTitle      Episode #1.911
originalTitle     Episode #1.911
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008260, dtype: object

(9,)

tconst                tt11830576
titleType              tvEpisode
primaryTitle      Episode #1.910
originalTitle     Episode #1.910
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008261, dtype: object

(9,)

tconst                           tt11830578
titleType                         tvEpisode
primaryTitle      ¿Huir es la mejor salida?
originalTitle     ¿Huir es la mejor salida?
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           44
genres                                Drama
Name: 2008262, dtype: object

(9,)

tconst               tt1183057
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008263, dtype: object

(9,)

tconst                tt11830580
titleType              tvEpisode
primaryTitle      Episode #1.912
originalTitle     Episode #1.912
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008264, dtype: object

(9,)

tconst                tt11830582
titleType              tvEpisode
primaryTitle      Episode #1.913
originalTitle     Episode #1.913
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008265, dtype: object

(9,)

tconst                tt11830584
titleType              tvEpisode
primaryTitle      Episode #1.914
originalTitle     Episode #1.914
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008266, dtype: object

(9,)

tconst                tt11830586
titleType              tvEpisode
primaryTitle      Episode #1.915
originalTitle     Episode #1.915
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008267, dtype: object

(9,)

tconst                tt11830588
titleType              tvEpisode
primaryTitle      Episode #1.916
originalTitle     Episode #1.916
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008268, dtype: object

(9,)

tconst               tt1183058
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008269, dtype: object

(9,)

tconst            tt11830590
titleType              movie
primaryTitle      Short Ends
originalTitle     Short Ends
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres               Mystery
Name: 2008270, dtype: object

(9,)

tconst                                           tt11830592
titleType                                             video
primaryTitle      Sébastien Tellier: L'amour et la violence
originalTitle     Sébastien Tellier: L'amour et la violence
isAdult                                                   0
startYear                                              2009
endYear                                                  \N
runtimeMinutes                                            5
genres                                          Music,Short
Name: 2008271, dtype: object

(9,)

tconst                tt11830594
titleType              tvEpisode
primaryTitle      Episode #1.917
originalTitle     Episode #1.917
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008272, dtype: object

(9,)

tconst                tt11830596
titleType              tvEpisode
primaryTitle      Episode #1.919
originalTitle     Episode #1.919
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008273, dtype: object

(9,)

tconst                tt11830598
titleType              tvEpisode
primaryTitle      Episode #1.918
originalTitle     Episode #1.918
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008274, dtype: object

(9,)

tconst               tt1183059
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008275, dtype: object

(9,)

tconst                tt11830600
titleType              tvEpisode
primaryTitle      Episode #1.920
originalTitle     Episode #1.920
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008276, dtype: object

(9,)

tconst                      tt11830602
titleType                    tvEpisode
primaryTitle             Episode #1.11
originalTitle            Episode #1.11
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008277, dtype: object

(9,)

tconst                               tt11830604
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2020
originalTitle     Episode dated 7 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2008278, dtype: object

(9,)

tconst                      tt11830606
titleType                    tvEpisode
primaryTitle             Episode #1.12
originalTitle            Episode #1.12
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008279, dtype: object

(9,)

tconst                                                   tt11830608
titleType                                                 tvEpisode
primaryTitle      Los pequeños detalles revelan los secretos más...
originalTitle     Los pequeños detalles revelan los secretos más...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   44
genres                                                        Drama
Name: 2008280, dtype: object

(9,)

tconst               tt1183060
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008281, dtype: object

(9,)

tconst                      tt11830610
titleType                    tvEpisode
primaryTitle             Episode #1.13
originalTitle            Episode #1.13
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008282, dtype: object

(9,)

tconst                tt11830612
titleType              tvEpisode
primaryTitle      Episode #1.681
originalTitle     Episode #1.681
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008283, dtype: object

(9,)

tconst                tt11830614
titleType              tvEpisode
primaryTitle      Episode #1.682
originalTitle     Episode #1.682
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008284, dtype: object

(9,)

tconst                tt11830616
titleType              tvEpisode
primaryTitle      Episode #1.683
originalTitle     Episode #1.683
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008285, dtype: object

(9,)

tconst                tt11830618
titleType              tvEpisode
primaryTitle      Episode #1.684
originalTitle     Episode #1.684
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008286, dtype: object

(9,)

tconst               tt1183061
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008287, dtype: object

(9,)

tconst                tt11830620
titleType              tvEpisode
primaryTitle      Episode #1.685
originalTitle     Episode #1.685
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008288, dtype: object

(9,)

tconst                tt11830622
titleType              tvEpisode
primaryTitle      Episode #1.686
originalTitle     Episode #1.686
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008289, dtype: object

(9,)

tconst                      tt11830624
titleType                    tvEpisode
primaryTitle             Episode #1.14
originalTitle            Episode #1.14
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008290, dtype: object

(9,)

tconst                tt11830626
titleType              tvEpisode
primaryTitle      Episode #1.687
originalTitle     Episode #1.687
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008291, dtype: object

(9,)

tconst                   tt11830628
titleType                     short
primaryTitle       Nourishing Japan
originalTitle      Nourishing Japan
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   24
genres            Documentary,Short
Name: 2008292, dtype: object

(9,)

tconst               tt1183062
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008293, dtype: object

(9,)

tconst                tt11830632
titleType              tvEpisode
primaryTitle      Episode #1.689
originalTitle     Episode #1.689
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008294, dtype: object

(9,)

tconst                 tt11830634
titleType                tvSeries
primaryTitle               ESC NL
originalTitle              ESC NL
isAdult                         0
startYear                    2017
endYear                        \N
runtimeMinutes                 10
genres            Music,Talk-Show
Name: 2008295, dtype: object

(9,)

tconst                tt11830636
titleType              tvEpisode
primaryTitle      Episode #1.688
originalTitle     Episode #1.688
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008296, dtype: object

(9,)

tconst                tt11830638
titleType              tvEpisode
primaryTitle      Episode #1.690
originalTitle     Episode #1.690
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008297, dtype: object

(9,)

tconst               tt1183063
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008298, dtype: object

(9,)

tconst                      tt11830640
titleType                    tvEpisode
primaryTitle             Episode #1.15
originalTitle            Episode #1.15
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008299, dtype: object

(9,)

tconst                      tt11830642
titleType                    tvEpisode
primaryTitle      Love Leads To Murder
originalTitle     Love Leads To Murder
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres                           Crime
Name: 2008300, dtype: object

(9,)

tconst                tt11830644
titleType              tvEpisode
primaryTitle      Episode #1.691
originalTitle     Episode #1.691
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008301, dtype: object

(9,)

tconst                      tt11830646
titleType                    tvEpisode
primaryTitle             Episode #1.16
originalTitle            Episode #1.16
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008302, dtype: object

(9,)

tconst                tt11830648
titleType              tvEpisode
primaryTitle      Episode #1.694
originalTitle     Episode #1.694
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008303, dtype: object

(9,)

tconst               tt1183064
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1993
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008304, dtype: object

(9,)

tconst                tt11830650
titleType              tvEpisode
primaryTitle      Episode #1.693
originalTitle     Episode #1.693
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008305, dtype: object

(9,)

tconst                tt11830652
titleType              tvEpisode
primaryTitle      Episode #1.695
originalTitle     Episode #1.695
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008306, dtype: object

(9,)

tconst                      tt11830656
titleType                    tvEpisode
primaryTitle             Episode #1.17
originalTitle            Episode #1.17
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008307, dtype: object

(9,)

tconst                tt11830658
titleType              tvEpisode
primaryTitle      Episode #1.696
originalTitle     Episode #1.696
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008308, dtype: object

(9,)

tconst               tt1183065
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1993
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008309, dtype: object

(9,)

tconst                tt11830660
titleType              tvEpisode
primaryTitle      Episode #1.697
originalTitle     Episode #1.697
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008310, dtype: object

(9,)

tconst             tt11830662
titleType           tvEpisode
primaryTitle      Dar la cara
originalTitle     Dar la cara
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             44
genres                  Drama
Name: 2008311, dtype: object

(9,)

tconst                tt11830664
titleType              tvEpisode
primaryTitle      Episode #1.698
originalTitle     Episode #1.698
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008312, dtype: object

(9,)

tconst                      tt11830666
titleType                    tvEpisode
primaryTitle             Episode #1.18
originalTitle            Episode #1.18
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008313, dtype: object

(9,)

tconst                tt11830668
titleType              tvEpisode
primaryTitle      Episode #1.699
originalTitle     Episode #1.699
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008314, dtype: object

(9,)

tconst               tt1183066
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 1993
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008315, dtype: object

(9,)

tconst                      tt11830670
titleType                    tvEpisode
primaryTitle             Episode #1.19
originalTitle            Episode #1.19
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008316, dtype: object

(9,)

tconst                tt11830672
titleType              tvEpisode
primaryTitle      Episode #1.700
originalTitle     Episode #1.700
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008317, dtype: object

(9,)

tconst                      tt11830674
titleType                    tvEpisode
primaryTitle             Episode #1.20
originalTitle            Episode #1.20
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008318, dtype: object

(9,)

tconst            tt11830676
titleType          tvEpisode
primaryTitle      Negocjator
originalTitle     Negocjator
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            79
genres                 Drama
Name: 2008319, dtype: object

(9,)

tconst                      tt11830678
titleType                    tvEpisode
primaryTitle             Episode #1.21
originalTitle            Episode #1.21
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008320, dtype: object

(9,)

tconst               tt1183067
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 1993
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008321, dtype: object

(9,)

tconst                      tt11830680
titleType                    tvEpisode
primaryTitle             Episode #1.22
originalTitle            Episode #1.22
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008322, dtype: object

(9,)

tconst                      tt11830682
titleType                    tvEpisode
primaryTitle             Episode #1.23
originalTitle            Episode #1.23
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008323, dtype: object

(9,)

tconst                                                   tt11830684
titleType                                                 tvEpisode
primaryTitle      Daniel Langlois, Diane Morin, Marie-Chantal Ca...
originalTitle     Daniel Langlois, Diane Morin, Marie-Chantal Ca...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008324, dtype: object

(9,)

tconst                      tt11830686
titleType                    tvEpisode
primaryTitle             Episode #1.24
originalTitle            Episode #1.24
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008325, dtype: object

(9,)

tconst                      tt11830688
titleType                    tvEpisode
primaryTitle             Episode #1.25
originalTitle            Episode #1.25
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008326, dtype: object

(9,)

tconst               tt1183068
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008327, dtype: object

(9,)

tconst               tt11830690
titleType             tvEpisode
primaryTitle      Episode #3.19
originalTitle     Episode #3.19
isAdult                       0
startYear                  1954
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2008328, dtype: object

(9,)

tconst                                tt11830692
titleType                              tvEpisode
primaryTitle      Episode dated 10 February 2020
originalTitle     Episode dated 10 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008329, dtype: object

(9,)

tconst                tt11830694
titleType              tvEpisode
primaryTitle      Episode #1.421
originalTitle     Episode #1.421
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008330, dtype: object

(9,)

tconst                      tt11830696
titleType                    tvEpisode
primaryTitle             Episode #1.26
originalTitle            Episode #1.26
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008331, dtype: object

(9,)

tconst                                                   tt11830698
titleType                                                     video
primaryTitle      Sébastien Tellier: L'amour et la violence (Boy...
originalTitle     Sébastien Tellier: L'amour et la violence (Boy...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                    5
genres                                                  Music,Short
Name: 2008332, dtype: object

(9,)

tconst               tt1183069
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008333, dtype: object

(9,)

tconst                tt11830700
titleType              tvEpisode
primaryTitle      Episode #1.422
originalTitle     Episode #1.422
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008334, dtype: object

(9,)

tconst                      tt11830702
titleType                    tvEpisode
primaryTitle             Episode #1.27
originalTitle            Episode #1.27
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008335, dtype: object

(9,)

tconst                tt11830704
titleType              tvEpisode
primaryTitle      Episode #1.424
originalTitle     Episode #1.424
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008336, dtype: object

(9,)

tconst                tt11830706
titleType              tvEpisode
primaryTitle      Episode #1.423
originalTitle     Episode #1.423
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008337, dtype: object

(9,)

tconst                tt11830708
titleType              tvEpisode
primaryTitle      Episode #1.426
originalTitle     Episode #1.426
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008338, dtype: object

(9,)

tconst               tt1183070
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008339, dtype: object

(9,)

tconst                tt11830710
titleType              tvEpisode
primaryTitle      Episode #1.425
originalTitle     Episode #1.425
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008340, dtype: object

(9,)

tconst                      tt11830712
titleType                    tvEpisode
primaryTitle             Episode #1.28
originalTitle            Episode #1.28
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008341, dtype: object

(9,)

tconst                tt11830714
titleType              tvEpisode
primaryTitle      Episode #1.428
originalTitle     Episode #1.428
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008342, dtype: object

(9,)

tconst                tt11830716
titleType              tvEpisode
primaryTitle      Episode #1.427
originalTitle     Episode #1.427
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008343, dtype: object

(9,)

tconst                tt11830718
titleType              tvEpisode
primaryTitle      Episode #1.429
originalTitle     Episode #1.429
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008344, dtype: object

(9,)

tconst               tt1183071
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008345, dtype: object

(9,)

tconst                      tt11830720
titleType                    tvEpisode
primaryTitle             Episode #1.29
originalTitle            Episode #1.29
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008346, dtype: object

(9,)

tconst                tt11830722
titleType              tvEpisode
primaryTitle      Episode #1.430
originalTitle     Episode #1.430
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008347, dtype: object

(9,)

tconst                tt11830724
titleType              tvEpisode
primaryTitle      Episode #1.431
originalTitle     Episode #1.431
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008348, dtype: object

(9,)

tconst                      tt11830726
titleType                    tvEpisode
primaryTitle             Episode #1.30
originalTitle            Episode #1.30
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008349, dtype: object

(9,)

tconst                tt11830728
titleType              tvEpisode
primaryTitle      Episode #1.432
originalTitle     Episode #1.432
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008350, dtype: object

(9,)

tconst               tt1183072
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008351, dtype: object

(9,)

tconst                tt11830730
titleType              tvEpisode
primaryTitle      Episode #1.433
originalTitle     Episode #1.433
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008352, dtype: object

(9,)

tconst                tt11830732
titleType              tvEpisode
primaryTitle      Episode #1.434
originalTitle     Episode #1.434
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008353, dtype: object

(9,)

tconst                                                   tt11830734
titleType                                                 tvEpisode
primaryTitle      Bobby Hachey, Mara Tremblay, Paul Dwayne, Rona...
originalTitle     Bobby Hachey, Mara Tremblay, Paul Dwayne, Rona...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008354, dtype: object

(9,)

tconst                tt11830736
titleType              tvEpisode
primaryTitle      Episode #1.436
originalTitle     Episode #1.436
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008355, dtype: object

(9,)

tconst                tt11830738
titleType              tvEpisode
primaryTitle      Episode #1.435
originalTitle     Episode #1.435
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008356, dtype: object

(9,)

tconst               tt1183073
titleType            tvEpisode
primaryTitle      Episode #3.2
originalTitle     Episode #3.2
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008357, dtype: object

(9,)

tconst                tt11830742
titleType              tvEpisode
primaryTitle      Episode #1.439
originalTitle     Episode #1.439
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008358, dtype: object

(9,)

tconst                tt11830744
titleType              tvEpisode
primaryTitle      Episode #1.438
originalTitle     Episode #1.438
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008359, dtype: object

(9,)

tconst                tt11830746
titleType              tvEpisode
primaryTitle      Episode #1.440
originalTitle     Episode #1.440
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008360, dtype: object

(9,)

tconst                tt11830748
titleType              tvEpisode
primaryTitle      Episode #1.181
originalTitle     Episode #1.181
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008361, dtype: object

(9,)

tconst               tt1183074
titleType            tvEpisode
primaryTitle      Episode #3.3
originalTitle     Episode #3.3
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008362, dtype: object

(9,)

tconst                tt11830750
titleType              tvEpisode
primaryTitle      Episode #1.183
originalTitle     Episode #1.183
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008363, dtype: object

(9,)

tconst                tt11830752
titleType              tvEpisode
primaryTitle      Episode #1.182
originalTitle     Episode #1.182
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008364, dtype: object

(9,)

tconst                              tt11830754
titleType                            tvEpisode
primaryTitle      1: Betty and Becky Se La Vie
originalTitle     1: Betty and Becky Se La Vie
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2008365, dtype: object

(9,)

tconst                tt11830756
titleType              tvEpisode
primaryTitle      Episode #1.184
originalTitle     Episode #1.184
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008366, dtype: object

(9,)

tconst                tt11830758
titleType              tvEpisode
primaryTitle      Episode #1.185
originalTitle     Episode #1.185
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008367, dtype: object

(9,)

tconst               tt1183075
titleType            tvEpisode
primaryTitle      Episode #3.4
originalTitle     Episode #3.4
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008368, dtype: object

(9,)

tconst                tt11830760
titleType              tvEpisode
primaryTitle      Episode #1.186
originalTitle     Episode #1.186
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008369, dtype: object

(9,)

tconst                tt11830762
titleType              tvEpisode
primaryTitle      Episode #1.187
originalTitle     Episode #1.187
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008370, dtype: object

(9,)

tconst                                   tt11830764
titleType                                     video
primaryTitle      Sébastien Tellier: La Ritournelle
originalTitle     Sébastien Tellier: La Ritournelle
isAdult                                           0
startYear                                      2010
endYear                                          \N
runtimeMinutes                                    4
genres                                  Music,Short
Name: 2008371, dtype: object

(9,)

tconst                tt11830766
titleType              tvEpisode
primaryTitle      Episode #1.188
originalTitle     Episode #1.188
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008372, dtype: object

(9,)

tconst                tt11830768
titleType              tvEpisode
primaryTitle      Episode #1.189
originalTitle     Episode #1.189
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008373, dtype: object

(9,)

tconst               tt1183076
titleType            tvEpisode
primaryTitle      Episode #3.5
originalTitle     Episode #3.5
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008374, dtype: object

(9,)

tconst                tt11830770
titleType              tvEpisode
primaryTitle      Episode #1.190
originalTitle     Episode #1.190
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008375, dtype: object

(9,)

tconst                tt11830772
titleType              tvEpisode
primaryTitle      Episode #1.191
originalTitle     Episode #1.191
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008376, dtype: object

(9,)

tconst                tt11830774
titleType              tvEpisode
primaryTitle      Episode #1.192
originalTitle     Episode #1.192
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008377, dtype: object

(9,)

tconst                tt11830776
titleType              tvEpisode
primaryTitle      Episode #1.193
originalTitle     Episode #1.193
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008378, dtype: object

(9,)

tconst                tt11830778
titleType              tvEpisode
primaryTitle      Episode #1.194
originalTitle     Episode #1.194
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008379, dtype: object

(9,)

tconst               tt1183077
titleType            tvEpisode
primaryTitle      Episode #3.6
originalTitle     Episode #3.6
isAdult                      0
startYear                 1995
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2008380, dtype: object

(9,)

tconst                tt11830780
titleType              tvEpisode
primaryTitle      Episode #1.195
originalTitle     Episode #1.195
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008381, dtype: object

(9,)

tconst                tt11830782
titleType              tvEpisode
primaryTitle      Episode #1.196
originalTitle     Episode #1.196
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008382, dtype: object

(9,)

tconst                tt11830784
titleType              tvEpisode
primaryTitle      Episode #1.197
originalTitle     Episode #1.197
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008383, dtype: object

(9,)

tconst                tt11830786
titleType              tvEpisode
primaryTitle      Episode #1.199
originalTitle     Episode #1.199
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008384, dtype: object

(9,)

tconst                tt11830788
titleType              tvEpisode
primaryTitle      Episode #1.198
originalTitle     Episode #1.198
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008385, dtype: object

(9,)

tconst                      tt1183078
titleType                   tvEpisode
primaryTitle      All in a Day's Work
originalTitle     All in a Day's Work
isAdult                             0
startYear                        1987
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2008386, dtype: object

(9,)

tconst                tt11830790
titleType              tvEpisode
primaryTitle      Episode #1.200
originalTitle     Episode #1.200
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2008387, dtype: object

(9,)

tconst                                tt11830792
titleType                              tvEpisode
primaryTitle      Episode dated 11 February 2020
originalTitle     Episode dated 11 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008388, dtype: object

(9,)

tconst            tt11830794
titleType              movie
primaryTitle        Fortress
originalTitle       Fortezza
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            72
genres                 Drama
Name: 2008389, dtype: object

(9,)

tconst                      tt11830796
titleType                    tvEpisode
primaryTitle           Episode #1.1321
originalTitle          Episode #1.1321
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008390, dtype: object

(9,)

tconst                 tt11830798
titleType               tvEpisode
primaryTitle      Episode #1.2705
originalTitle     Episode #1.2705
isAdult                         0
startYear                    1985
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2008391, dtype: object

(9,)

tconst                    tt1183079
titleType                 tvEpisode
primaryTitle        Malaika Griffin
originalTitle       Malaika Griffin
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   44
genres            Crime,Documentary
Name: 2008392, dtype: object

(9,)

tconst                  tt11830800
titleType                tvEpisode
primaryTitle         Episode #2.17
originalTitle        Episode #2.17
isAdult                          0
startYear                     1987
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2008393, dtype: object

(9,)

tconst                            tt11830802
titleType                          tvEpisode
primaryTitle      Episode dated 13 June 2017
originalTitle     Episode dated 13 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2008394, dtype: object

(9,)

tconst                      tt11830804
titleType                    tvEpisode
primaryTitle           Episode #1.1323
originalTitle          Episode #1.1323
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008395, dtype: object

(9,)

tconst                      tt11830806
titleType                    tvEpisode
primaryTitle           Episode #1.1324
originalTitle          Episode #1.1324
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008396, dtype: object

(9,)

tconst                    tt11830808
titleType                  tvEpisode
primaryTitle      2: Tis' the Season
originalTitle     2: Tis' the Season
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                            \N
Name: 2008397, dtype: object

(9,)

tconst                      tt11830810
titleType                    tvEpisode
primaryTitle           Episode #1.1326
originalTitle          Episode #1.1326
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008398, dtype: object

(9,)

tconst                      tt11830812
titleType                    tvEpisode
primaryTitle           Episode #1.1325
originalTitle          Episode #1.1325
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008399, dtype: object

(9,)

tconst                      tt11830814
titleType                    tvEpisode
primaryTitle           Episode #1.1328
originalTitle          Episode #1.1328
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008400, dtype: object

(9,)

tconst                      tt11830816
titleType                    tvEpisode
primaryTitle           Episode #1.1327
originalTitle          Episode #1.1327
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008401, dtype: object

(9,)

tconst                                             tt11830818
titleType                                               video
primaryTitle      Sébastien Tellier: Oh malheur chez O'Malley
originalTitle     Sébastien Tellier: Oh malheur chez O'Malley
isAdult                                                     0
startYear                                                2001
endYear                                                    \N
runtimeMinutes                                              5
genres                                            Music,Short
Name: 2008402, dtype: object

(9,)

tconst                      tt1183081
titleType                   tvEpisode
primaryTitle      Single White Female
originalTitle     Single White Female
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2008403, dtype: object

(9,)

tconst                                tt11830820
titleType                              tvEpisode
primaryTitle      Episode dated 12 February 2020
originalTitle     Episode dated 12 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008404, dtype: object

(9,)

tconst                      tt11830822
titleType                    tvEpisode
primaryTitle           Episode #1.1329
originalTitle          Episode #1.1329
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008405, dtype: object

(9,)

tconst                                tt11830824
titleType                              tvEpisode
primaryTitle      Queue Doctor - Clueless Expert
originalTitle     Queue Doctor - Clueless Expert
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                       Comedy,Drama,Sci-Fi
Name: 2008406, dtype: object

(9,)

tconst                            tt11830826
titleType                          tvEpisode
primaryTitle      Episode dated 14 June 2017
originalTitle     Episode dated 14 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2008407, dtype: object

(9,)

tconst                      tt11830828
titleType                    tvEpisode
primaryTitle           Episode #1.1331
originalTitle          Episode #1.1331
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008408, dtype: object

(9,)

tconst                tt1183082
titleType             tvEpisode
primaryTitle      Door Number 2
originalTitle     Door Number 2
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2008409, dtype: object

(9,)

tconst                      tt11830830
titleType                    tvEpisode
primaryTitle           Episode #1.1330
originalTitle          Episode #1.1330
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008410, dtype: object

(9,)

tconst                            tt11830832
titleType                          tvEpisode
primaryTitle      Episode dated 19 June 2017
originalTitle     Episode dated 19 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2008411, dtype: object

(9,)

tconst                            tt11830834
titleType                          tvEpisode
primaryTitle      Episode dated 22 June 2017
originalTitle     Episode dated 22 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2008412, dtype: object

(9,)

tconst                      tt11830836
titleType                    tvEpisode
primaryTitle           Episode #1.1081
originalTitle          Episode #1.1081
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008413, dtype: object

(9,)

tconst                            tt11830838
titleType                          tvEpisode
primaryTitle      Episode dated 23 June 2017
originalTitle     Episode dated 23 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2008414, dtype: object

(9,)

tconst                 tt1183083
titleType              tvEpisode
primaryTitle      Read the Signs
originalTitle     Read the Signs
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2008415, dtype: object

(9,)

tconst                      tt11830840
titleType                    tvEpisode
primaryTitle           Episode #1.1082
originalTitle          Episode #1.1082
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008416, dtype: object

(9,)

tconst                      tt11830842
titleType                    tvEpisode
primaryTitle           Episode #1.1083
originalTitle          Episode #1.1083
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008417, dtype: object

(9,)

tconst                      tt11830844
titleType                    tvEpisode
primaryTitle           Episode #1.1084
originalTitle          Episode #1.1084
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008418, dtype: object

(9,)

tconst                      tt11830846
titleType                    tvEpisode
primaryTitle           Episode #1.1085
originalTitle          Episode #1.1085
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008419, dtype: object

(9,)

tconst                      tt11830848
titleType                    tvEpisode
primaryTitle           Episode #1.1086
originalTitle          Episode #1.1086
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008420, dtype: object

(9,)

tconst                tt1183084
titleType             tvEpisode
primaryTitle      Business, Man
originalTitle     Business, Man
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2008421, dtype: object

(9,)

tconst                      tt11830850
titleType                    tvEpisode
primaryTitle           Episode #1.1087
originalTitle          Episode #1.1087
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008422, dtype: object

(9,)

tconst                      tt11830852
titleType                    tvEpisode
primaryTitle           Episode #1.1088
originalTitle          Episode #1.1088
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008423, dtype: object

(9,)

tconst                      tt11830854
titleType                    tvEpisode
primaryTitle           Episode #1.1089
originalTitle          Episode #1.1089
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008424, dtype: object

(9,)

tconst                      tt11830856
titleType                    tvEpisode
primaryTitle           Episode #1.1090
originalTitle          Episode #1.1090
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008425, dtype: object

(9,)

tconst                      tt11830858
titleType                    tvEpisode
primaryTitle           Episode #1.1091
originalTitle          Episode #1.1091
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008426, dtype: object

(9,)

tconst                                tt1183085
titleType                             tvEpisode
primaryTitle      Guess Who's Coming to Dinner?
originalTitle     Guess Who's Coming to Dinner?
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                   Comedy
Name: 2008427, dtype: object

(9,)

tconst                      tt11830860
titleType                    tvEpisode
primaryTitle           Episode #1.1092
originalTitle          Episode #1.1092
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008428, dtype: object

(9,)

tconst                      tt11830862
titleType                    tvEpisode
primaryTitle           Episode #1.1093
originalTitle          Episode #1.1093
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008429, dtype: object

(9,)

tconst                      tt11830864
titleType                    tvEpisode
primaryTitle           Episode #1.1094
originalTitle          Episode #1.1094
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008430, dtype: object

(9,)

tconst                      tt11830866
titleType                    tvEpisode
primaryTitle           Episode #1.1095
originalTitle          Episode #1.1095
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008431, dtype: object

(9,)

tconst                      tt11830868
titleType                    tvEpisode
primaryTitle           Episode #1.1096
originalTitle          Episode #1.1096
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008432, dtype: object

(9,)

tconst                      tt1183086
titleType                   tvEpisode
primaryTitle      Checking Sophie Out
originalTitle     Checking Sophie Out
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2008433, dtype: object

(9,)

tconst                      tt11830870
titleType                    tvEpisode
primaryTitle           Episode #1.1097
originalTitle          Episode #1.1097
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008434, dtype: object

(9,)

tconst                      tt11830872
titleType                    tvEpisode
primaryTitle           Episode #1.1099
originalTitle          Episode #1.1099
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008435, dtype: object

(9,)

tconst                      tt11830874
titleType                    tvEpisode
primaryTitle           Episode #1.1098
originalTitle          Episode #1.1098
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008436, dtype: object

(9,)

tconst                                tt11830876
titleType                              tvEpisode
primaryTitle      Episode dated 13 February 2020
originalTitle     Episode dated 13 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008437, dtype: object

(9,)

tconst                      tt11830878
titleType                    tvEpisode
primaryTitle           Episode #1.1100
originalTitle          Episode #1.1100
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008438, dtype: object

(9,)

tconst                   tt1183087
titleType                tvEpisode
primaryTitle      Ze Boy Next Door
originalTitle     Ze Boy Next Door
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2008439, dtype: object

(9,)

tconst                                  tt11830880
titleType                                    video
primaryTitle      Sébastien Tellier: La Dolce Vita
originalTitle     Sébastien Tellier: La Dolce Vita
isAdult                                          0
startYear                                     2007
endYear                                         \N
runtimeMinutes                                   4
genres                                 Music,Short
Name: 2008440, dtype: object

(9,)

tconst                tt11830882
titleType              tvEpisode
primaryTitle      Father and Son
originalTitle     Father and Son
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                25
genres                     Drama
Name: 2008441, dtype: object

(9,)

tconst                      tt11830884
titleType                    tvEpisode
primaryTitle            Episode #1.862
originalTitle           Episode #1.862
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008442, dtype: object

(9,)

tconst                      tt11830886
titleType                    tvEpisode
primaryTitle            Episode #1.861
originalTitle           Episode #1.861
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008443, dtype: object

(9,)

tconst                      tt11830888
titleType                    tvEpisode
primaryTitle            Episode #1.863
originalTitle           Episode #1.863
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008444, dtype: object

(9,)

tconst                tt1183088
titleType             tvEpisode
primaryTitle      Mommy Dearest
originalTitle     Mommy Dearest
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2008445, dtype: object

(9,)

tconst                      tt11830890
titleType                    tvEpisode
primaryTitle            Episode #1.864
originalTitle           Episode #1.864
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008446, dtype: object

(9,)

tconst                      tt11830892
titleType                    tvEpisode
primaryTitle            Episode #1.865
originalTitle           Episode #1.865
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008447, dtype: object

(9,)

tconst                      tt11830894
titleType                    tvEpisode
primaryTitle            Episode #1.866
originalTitle           Episode #1.866
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008448, dtype: object

(9,)

tconst                      tt11830896
titleType                    tvEpisode
primaryTitle            Episode #1.867
originalTitle           Episode #1.867
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008449, dtype: object

(9,)

tconst                      tt11830898
titleType                    tvEpisode
primaryTitle            Episode #1.868
originalTitle           Episode #1.868
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008450, dtype: object

(9,)

tconst               tt1183089
titleType            tvEpisode
primaryTitle      Episode #6.3
originalTitle     Episode #6.3
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2008451, dtype: object

(9,)

tconst                      tt11830900
titleType                    tvEpisode
primaryTitle            Episode #1.869
originalTitle           Episode #1.869
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008452, dtype: object

(9,)

tconst                      tt11830902
titleType                    tvEpisode
primaryTitle            Episode #1.870
originalTitle           Episode #1.870
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008453, dtype: object

(9,)

tconst                      tt11830904
titleType                    tvEpisode
primaryTitle            Episode #1.871
originalTitle           Episode #1.871
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008454, dtype: object

(9,)

tconst            tt11830906
titleType          tvSpecial
primaryTitle      2 AM Girls
originalTitle     2 AM Girls
isAdult                    0
startYear               2018
endYear                   \N
runtimeMinutes            \N
genres                  News
Name: 2008455, dtype: object

(9,)

tconst                      tt11830908
titleType                    tvEpisode
primaryTitle            Episode #1.872
originalTitle           Episode #1.872
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008456, dtype: object

(9,)

tconst                 tt1183090
titleType              tvEpisode
primaryTitle      Episode #3.100
originalTitle     Episode #3.100
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2008457, dtype: object

(9,)

tconst                      tt11830910
titleType                    tvEpisode
primaryTitle            Episode #1.873
originalTitle           Episode #1.873
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008458, dtype: object

(9,)

tconst                      tt11830912
titleType                    tvEpisode
primaryTitle            Episode #1.874
originalTitle           Episode #1.874
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008459, dtype: object

(9,)

tconst                      tt11830914
titleType                    tvEpisode
primaryTitle            Episode #1.875
originalTitle           Episode #1.875
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008460, dtype: object

(9,)

tconst                      tt11830916
titleType                    tvEpisode
primaryTitle            Episode #1.876
originalTitle           Episode #1.876
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008461, dtype: object

(9,)

tconst                      tt11830918
titleType                    tvEpisode
primaryTitle            Episode #1.878
originalTitle           Episode #1.878
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008462, dtype: object

(9,)

tconst                      tt1183091
titleType                   tvEpisode
primaryTitle       Der frühe Abschied
originalTitle      Der frühe Abschied
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     90
genres            Crime,Drama,Mystery
Name: 2008463, dtype: object

(9,)

tconst                      tt11830920
titleType                    tvEpisode
primaryTitle            Episode #1.877
originalTitle           Episode #1.877
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008464, dtype: object

(9,)

tconst                                tt11830922
titleType                              tvEpisode
primaryTitle      Episode dated 14 February 2020
originalTitle     Episode dated 14 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2008465, dtype: object

(9,)

tconst                      tt11830924
titleType                    tvEpisode
primaryTitle            Episode #1.879
originalTitle           Episode #1.879
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008466, dtype: object

(9,)

tconst                      tt11830926
titleType                    tvEpisode
primaryTitle            Episode #1.880
originalTitle           Episode #1.880
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008467, dtype: object

(9,)

tconst                    tt11830928
titleType                      short
primaryTitle      Ward's Henna Party
originalTitle             Henet Ward
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    23
genres                   Drama,Short
Name: 2008468, dtype: object

(9,)

tconst                      tt1183092
titleType                   tvEpisode
primaryTitle          Episode #13.110
originalTitle         Episode #13.110
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2008469, dtype: object

(9,)

tconst                      tt11830930
titleType                    tvEpisode
primaryTitle            Episode #1.881
originalTitle           Episode #1.881
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008470, dtype: object

(9,)

tconst                      tt11830932
titleType                    tvEpisode
primaryTitle            Episode #1.882
originalTitle           Episode #1.882
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008471, dtype: object

(9,)

tconst                      tt11830934
titleType                    tvEpisode
primaryTitle            Episode #1.883
originalTitle           Episode #1.883
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008472, dtype: object

(9,)

tconst                          tt11830936
titleType                        tvEpisode
primaryTitle      3: What are you haulin'?
originalTitle     3: What are you haulin'?
isAdult                                  0
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                           Talk-Show
Name: 2008473, dtype: object

(9,)

tconst                      tt11830938
titleType                    tvEpisode
primaryTitle            Episode #1.884
originalTitle           Episode #1.884
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008474, dtype: object

(9,)

tconst                      tt1183093
titleType                   tvEpisode
primaryTitle          Episode #13.114
originalTitle         Episode #13.114
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2008475, dtype: object

(9,)

tconst                      tt11830940
titleType                    tvEpisode
primaryTitle            Episode #1.885
originalTitle           Episode #1.885
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008476, dtype: object

(9,)

tconst                      tt11830942
titleType                    tvEpisode
primaryTitle            Episode #1.887
originalTitle           Episode #1.887
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008477, dtype: object

(9,)

tconst                      tt11830944
titleType                    tvEpisode
primaryTitle            Episode #1.886
originalTitle           Episode #1.886
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008478, dtype: object

(9,)

tconst                      tt11830946
titleType                    tvEpisode
primaryTitle            Episode #1.888
originalTitle           Episode #1.888
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008479, dtype: object

(9,)

tconst                                                   tt11830948
titleType                                                 tvEpisode
primaryTitle      Enemy In The Vietnam War: Tim O'Brien & Karl M...
originalTitle     Enemy In The Vietnam War: Tim O'Brien & Karl M...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            History,Talk-Show
Name: 2008480, dtype: object

(9,)

tconst                tt1183094
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2008481, dtype: object

(9,)

tconst                      tt11830950
titleType                    tvEpisode
primaryTitle            Episode #1.889
originalTitle           Episode #1.889
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008482, dtype: object

(9,)

tconst                      tt11830952
titleType                    tvEpisode
primaryTitle            Episode #1.890
originalTitle           Episode #1.890
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008483, dtype: object

(9,)

tconst                      tt11830954
titleType                    tvEpisode
primaryTitle            Episode #1.891
originalTitle           Episode #1.891
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008484, dtype: object

(9,)

tconst                                                   tt11830956
titleType                                                 tvEpisode
primaryTitle      Caroline Laurendeau, Geneviéve Grenier, Gilles...
originalTitle     Caroline Laurendeau, Geneviéve Grenier, Gilles...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008485, dtype: object

(9,)

tconst                      tt11830958
titleType                    tvEpisode
primaryTitle            Episode #1.892
originalTitle           Episode #1.892
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008486, dtype: object

(9,)

tconst                            tt1183095
titleType                         tvEpisode
primaryTitle      Episode dated 16 May 1986
originalTitle     Episode dated 16 May 1986
isAdult                                   0
startYear                              1986
endYear                                  \N
runtimeMinutes                           \N
genres                       News,Talk-Show
Name: 2008487, dtype: object

(9,)

tconst                      tt11830960
titleType                    tvEpisode
primaryTitle            Episode #1.893
originalTitle           Episode #1.893
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008488, dtype: object

(9,)

tconst                      tt11830962
titleType                    tvEpisode
primaryTitle            Episode #1.894
originalTitle           Episode #1.894
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008489, dtype: object

(9,)

tconst                      tt11830964
titleType                    tvEpisode
primaryTitle            Episode #1.895
originalTitle           Episode #1.895
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008490, dtype: object

(9,)

tconst                             tt11830966
titleType                               video
primaryTitle      Sébastien Tellier: Universe
originalTitle     Sébastien Tellier: Universe
isAdult                                     0
startYear                                2008
endYear                                    \N
runtimeMinutes                              5
genres                            Music,Short
Name: 2008491, dtype: object

(9,)

tconst                      tt11830968
titleType                    tvEpisode
primaryTitle            Episode #1.897
originalTitle           Episode #1.897
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008492, dtype: object

(9,)

tconst                              tt1183096
titleType                           tvEpisode
primaryTitle      Episode dated 9 August 1989
originalTitle     Episode dated 9 August 1989
isAdult                                     0
startYear                                1989
endYear                                    \N
runtimeMinutes                             \N
genres                         News,Talk-Show
Name: 2008493, dtype: object

(9,)

tconst                      tt11830970
titleType                    tvEpisode
primaryTitle            Episode #1.896
originalTitle           Episode #1.896
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008494, dtype: object

(9,)

tconst                      tt11830972
titleType                    tvEpisode
primaryTitle            Episode #1.898
originalTitle           Episode #1.898
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008495, dtype: object

(9,)

tconst                      tt11830974
titleType                    tvEpisode
primaryTitle            Episode #1.899
originalTitle           Episode #1.899
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008496, dtype: object

(9,)

tconst                      tt11830976
titleType                    tvEpisode
primaryTitle      Casting d'Elie Bloom
originalTitle     Casting d'Elie Bloom
isAdult                              1
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2008497, dtype: object

(9,)

tconst                      tt11830978
titleType                    tvEpisode
primaryTitle            Episode #1.900
originalTitle           Episode #1.900
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008498, dtype: object

(9,)

tconst                                tt1183097
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2008499, dtype: object

(9,)

tconst                      tt11830980
titleType                    tvEpisode
primaryTitle            Episode #1.621
originalTitle           Episode #1.621
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008500, dtype: object

(9,)

tconst                      tt11830982
titleType                    tvEpisode
primaryTitle            Episode #1.622
originalTitle           Episode #1.622
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008501, dtype: object

(9,)

tconst                      tt11830984
titleType                    tvEpisode
primaryTitle            Episode #1.623
originalTitle           Episode #1.623
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008502, dtype: object

(9,)

tconst                      tt11830986
titleType                    tvEpisode
primaryTitle            Episode #1.624
originalTitle           Episode #1.624
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008503, dtype: object

(9,)

tconst                      tt11830988
titleType                    tvEpisode
primaryTitle            Episode #1.625
originalTitle           Episode #1.625
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008504, dtype: object

(9,)

tconst                tt1183098
titleType             tvEpisode
primaryTitle      Episode #3.13
originalTitle     Episode #3.13
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               58
genres            Drama,Romance
Name: 2008505, dtype: object

(9,)

tconst                      tt11830990
titleType                    tvEpisode
primaryTitle            Episode #1.628
originalTitle           Episode #1.628
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008506, dtype: object

(9,)

tconst                      tt11830992
titleType                    tvEpisode
primaryTitle            Episode #1.626
originalTitle           Episode #1.626
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008507, dtype: object

(9,)

tconst                      tt11830994
titleType                    tvEpisode
primaryTitle            Episode #1.627
originalTitle           Episode #1.627
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008508, dtype: object

(9,)

tconst                      tt11830996
titleType                    tvEpisode
primaryTitle            Episode #1.629
originalTitle           Episode #1.629
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008509, dtype: object

(9,)

tconst                tt11830998
titleType              tvEpisode
primaryTitle      Episode #1.527
originalTitle     Episode #1.527
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008510, dtype: object

(9,)

tconst                tt1183099
titleType             tvEpisode
primaryTitle      Episode #3.14
originalTitle     Episode #3.14
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               58
genres            Drama,Romance
Name: 2008511, dtype: object

(9,)

tconst                      tt11831000
titleType                    tvEpisode
primaryTitle            Episode #1.630
originalTitle           Episode #1.630
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008512, dtype: object

(9,)

tconst                                     tt11831002
titleType                                       video
primaryTitle      Sébastien Tellier - League Chicanos
originalTitle     Sébastien Tellier - League Chicanos
isAdult                                             0
startYear                                        2007
endYear                                            \N
runtimeMinutes                                      2
genres                             Comedy,Music,Short
Name: 2008513, dtype: object

(9,)

tconst                      tt11831004
titleType                    tvEpisode
primaryTitle            Episode #1.631
originalTitle           Episode #1.631
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008514, dtype: object

(9,)

tconst                      tt11831006
titleType                    tvEpisode
primaryTitle            Episode #1.632
originalTitle           Episode #1.632
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008515, dtype: object

(9,)

tconst                      tt11831008
titleType                    tvEpisode
primaryTitle            Episode #1.633
originalTitle           Episode #1.633
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008516, dtype: object

(9,)

tconst                 tt1183100
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008517, dtype: object

(9,)

tconst                     tt11831010
titleType                       short
primaryTitle      What the Sea Forget
originalTitle     What the Sea Forget
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres              Documentary,Short
Name: 2008518, dtype: object

(9,)

tconst                      tt11831012
titleType                    tvEpisode
primaryTitle            Episode #1.635
originalTitle           Episode #1.635
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008519, dtype: object

(9,)

tconst                      tt11831014
titleType                    tvEpisode
primaryTitle            Episode #1.634
originalTitle           Episode #1.634
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008520, dtype: object

(9,)

tconst                      tt11831016
titleType                    tvEpisode
primaryTitle            Episode #1.636
originalTitle           Episode #1.636
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008521, dtype: object

(9,)

tconst                      tt11831018
titleType                    tvEpisode
primaryTitle            Episode #1.637
originalTitle           Episode #1.637
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008522, dtype: object

(9,)

tconst                 tt1183101
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008523, dtype: object

(9,)

tconst                      tt11831020
titleType                    tvEpisode
primaryTitle            Episode #1.638
originalTitle           Episode #1.638
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008524, dtype: object

(9,)

tconst                      tt11831022
titleType                    tvEpisode
primaryTitle            Episode #1.639
originalTitle           Episode #1.639
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008525, dtype: object

(9,)

tconst                      tt11831024
titleType                    tvEpisode
primaryTitle            Episode #1.640
originalTitle           Episode #1.640
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008526, dtype: object

(9,)

tconst                      tt11831026
titleType                    tvEpisode
primaryTitle            Episode #1.641
originalTitle           Episode #1.641
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008527, dtype: object

(9,)

tconst                      tt11831028
titleType                    tvEpisode
primaryTitle            Episode #1.642
originalTitle           Episode #1.642
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008528, dtype: object

(9,)

tconst                 tt1183102
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008529, dtype: object

(9,)

tconst                      tt11831030
titleType                    tvEpisode
primaryTitle            Episode #1.643
originalTitle           Episode #1.643
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008530, dtype: object

(9,)

tconst                      tt11831032
titleType                    tvEpisode
primaryTitle            Episode #1.645
originalTitle           Episode #1.645
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008531, dtype: object

(9,)

tconst                      tt11831034
titleType                    tvEpisode
primaryTitle            Episode #1.644
originalTitle           Episode #1.644
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008532, dtype: object

(9,)

tconst                      tt11831036
titleType                    tvEpisode
primaryTitle            Episode #1.646
originalTitle           Episode #1.646
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008533, dtype: object

(9,)

tconst                      tt11831038
titleType                    tvEpisode
primaryTitle            Episode #1.647
originalTitle           Episode #1.647
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008534, dtype: object

(9,)

tconst                 tt1183103
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008535, dtype: object

(9,)

tconst                    tt11831040
titleType                  tvEpisode
primaryTitle       The Mighty Weasel
originalTitle      The Mighty Weasel
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    53
genres            Documentary,Family
Name: 2008536, dtype: object

(9,)

tconst                      tt11831042
titleType                    tvEpisode
primaryTitle            Episode #1.648
originalTitle           Episode #1.648
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008537, dtype: object

(9,)

tconst                      tt11831044
titleType                    tvEpisode
primaryTitle            Episode #1.649
originalTitle           Episode #1.649
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008538, dtype: object

(9,)

tconst                      tt11831046
titleType                    tvEpisode
primaryTitle            Episode #1.650
originalTitle           Episode #1.650
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008539, dtype: object

(9,)

tconst                      tt11831048
titleType                    tvEpisode
primaryTitle            Episode #1.231
originalTitle           Episode #1.231
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008540, dtype: object

(9,)

tconst                 tt1183104
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008541, dtype: object

(9,)

tconst                      tt11831050
titleType                    tvEpisode
primaryTitle            Episode #1.232
originalTitle           Episode #1.232
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008542, dtype: object

(9,)

tconst                      tt11831052
titleType                    tvEpisode
primaryTitle            Episode #1.233
originalTitle           Episode #1.233
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008543, dtype: object

(9,)

tconst                      tt11831054
titleType                    tvEpisode
primaryTitle            Episode #1.234
originalTitle           Episode #1.234
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008544, dtype: object

(9,)

tconst                      tt11831056
titleType                    tvEpisode
primaryTitle            Episode #1.235
originalTitle           Episode #1.235
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008545, dtype: object

(9,)

tconst                      tt11831058
titleType                    tvEpisode
primaryTitle            Episode #1.236
originalTitle           Episode #1.236
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008546, dtype: object

(9,)

tconst                 tt1183105
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008547, dtype: object

(9,)

tconst                      tt11831060
titleType                    tvEpisode
primaryTitle            Episode #1.237
originalTitle           Episode #1.237
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008548, dtype: object

(9,)

tconst                      tt11831062
titleType                    tvEpisode
primaryTitle            Episode #1.238
originalTitle           Episode #1.238
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008549, dtype: object

(9,)

tconst                                    tt11831064
titleType                                  tvEpisode
primaryTitle      Stoppi venäläisten tonttikaupoille
originalTitle     Stoppi venäläisten tonttikaupoille
isAdult                                            0
startYear                                       2014
endYear                                           \N
runtimeMinutes                                    \N
genres                                     Talk-Show
Name: 2008550, dtype: object

(9,)

tconst                      tt11831066
titleType                    tvEpisode
primaryTitle            Episode #1.240
originalTitle           Episode #1.240
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008551, dtype: object

(9,)

tconst                      tt11831068
titleType                    tvEpisode
primaryTitle            Episode #1.241
originalTitle           Episode #1.241
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008552, dtype: object

(9,)

tconst                 tt1183106
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008553, dtype: object

(9,)

tconst                  tt11831070
titleType                tvEpisode
primaryTitle      Duunit uhattuina
originalTitle     Duunit uhattuina
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2008554, dtype: object

(9,)

tconst                      tt11831072
titleType                    tvEpisode
primaryTitle            Episode #1.242
originalTitle           Episode #1.242
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008555, dtype: object

(9,)

tconst                      tt11831074
titleType                    tvEpisode
primaryTitle            Episode #1.243
originalTitle           Episode #1.243
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008556, dtype: object

(9,)

tconst                             tt11831076
titleType                           tvEpisode
primaryTitle      4: Pizza Skiing for the Win
originalTitle     4: Pizza Skiing for the Win
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2008557, dtype: object

(9,)

tconst                      tt11831078
titleType                    tvEpisode
primaryTitle            Episode #1.244
originalTitle           Episode #1.244
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008558, dtype: object

(9,)

tconst                 tt1183107
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008559, dtype: object

(9,)

tconst                      tt11831080
titleType                    tvEpisode
primaryTitle            Episode #1.246
originalTitle           Episode #1.246
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008560, dtype: object

(9,)

tconst                      tt11831082
titleType                    tvEpisode
primaryTitle            Episode #1.245
originalTitle           Episode #1.245
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008561, dtype: object

(9,)

tconst                             tt11831084
titleType                               movie
primaryTitle      Kambili: The Whole 30 Yards
originalTitle     Kambili: The Whole 30 Yards
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                            119
genres                                Romance
Name: 2008562, dtype: object

(9,)

tconst                      tt11831086
titleType                    tvEpisode
primaryTitle            Episode #1.247
originalTitle           Episode #1.247
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008563, dtype: object

(9,)

tconst                      tt11831088
titleType                    tvEpisode
primaryTitle            Episode #1.248
originalTitle           Episode #1.248
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008564, dtype: object

(9,)

tconst                 tt1183108
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008565, dtype: object

(9,)

tconst                      tt11831090
titleType                    tvEpisode
primaryTitle            Episode #1.250
originalTitle           Episode #1.250
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008566, dtype: object

(9,)

tconst                      tt11831092
titleType                    tvEpisode
primaryTitle            Episode #1.249
originalTitle           Episode #1.249
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2008567, dtype: object

(9,)

tconst                    tt11831094
titleType                  tvEpisode
primaryTitle      Kunnat pakkoraossa
originalTitle     Kunnat pakkoraossa
isAdult                            0
startYear                       2014
endYear                           \N
runtimeMinutes                    \N
genres                            \N
Name: 2008568, dtype: object

(9,)

tconst                      tt11831098
titleType                    tvEpisode
primaryTitle      Ruutitynnyri Ukraina
originalTitle     Ruutitynnyri Ukraina
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2008569, dtype: object

(9,)

tconst                 tt1183109
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008570, dtype: object

(9,)

tconst                tt11831100
titleType              tvEpisode
primaryTitle      Episode #1.261
originalTitle     Episode #1.261
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008571, dtype: object

(9,)

tconst                               tt11831102
titleType                             tvEpisode
primaryTitle      Velka vie ja hallitus vikisee
originalTitle     Velka vie ja hallitus vikisee
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2008572, dtype: object

(9,)

tconst                tt11831104
titleType              tvEpisode
primaryTitle      Episode #1.262
originalTitle     Episode #1.262
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008573, dtype: object

(9,)

tconst                tt11831106
titleType              tvEpisode
primaryTitle      Episode #1.263
originalTitle     Episode #1.263
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008574, dtype: object

(9,)

tconst                tt11831108
titleType              tvEpisode
primaryTitle      Episode #1.265
originalTitle     Episode #1.265
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008575, dtype: object

(9,)

tconst                 tt1183110
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008576, dtype: object

(9,)

tconst                tt11831110
titleType              tvEpisode
primaryTitle      Episode #1.264
originalTitle     Episode #1.264
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008577, dtype: object

(9,)

tconst                tt11831112
titleType              tvEpisode
primaryTitle      Episode #1.266
originalTitle     Episode #1.266
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008578, dtype: object

(9,)

tconst                tt11831114
titleType              tvEpisode
primaryTitle      Episode #1.267
originalTitle     Episode #1.267
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008579, dtype: object

(9,)

tconst                tt11831116
titleType              tvEpisode
primaryTitle      Episode #1.268
originalTitle     Episode #1.268
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008580, dtype: object

(9,)

tconst                tt11831118
titleType              tvEpisode
primaryTitle      Episode #1.269
originalTitle     Episode #1.269
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008581, dtype: object

(9,)

tconst                 tt1183111
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008582, dtype: object

(9,)

tconst                tt11831120
titleType              tvEpisode
primaryTitle      Episode #1.271
originalTitle     Episode #1.271
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008583, dtype: object

(9,)

tconst                tt11831122
titleType              tvEpisode
primaryTitle      Episode #1.270
originalTitle     Episode #1.270
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008584, dtype: object

(9,)

tconst                tt11831124
titleType              tvEpisode
primaryTitle      Episode #1.272
originalTitle     Episode #1.272
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008585, dtype: object

(9,)

tconst                tt11831126
titleType              tvEpisode
primaryTitle      Episode #1.273
originalTitle     Episode #1.273
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008586, dtype: object

(9,)

tconst                     tt11831128
titleType                   tvEpisode
primaryTitle      Töissä tappiin asti
originalTitle     Töissä tappiin asti
isAdult                             0
startYear                        2013
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2008587, dtype: object

(9,)

tconst                 tt1183112
titleType              tvEpisode
primaryTitle      Episode #1.115
originalTitle     Episode #1.115
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2008588, dtype: object

(9,)

tconst                tt11831130
titleType              tvEpisode
primaryTitle      Episode #1.274
originalTitle     Episode #1.274
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008589, dtype: object

(9,)

tconst                tt11831132
titleType              tvEpisode
primaryTitle      Episode #1.275
originalTitle     Episode #1.275
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008590, dtype: object

(9,)

tconst                tt11831134
titleType              tvEpisode
primaryTitle      Episode #1.276
originalTitle     Episode #1.276
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008591, dtype: object

(9,)

tconst                tt11831136
titleType              tvEpisode
primaryTitle      Episode #1.277
originalTitle     Episode #1.277
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008592, dtype: object

(9,)

tconst                tt11831138
titleType              tvEpisode
primaryTitle      Episode #1.278
originalTitle     Episode #1.278
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008593, dtype: object

(9,)

tconst               tt1183113
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008594, dtype: object

(9,)

tconst                                tt11831140
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2014
originalTitle     Episode dated 20 February 2014
isAdult                                        0
startYear                                   2014
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008595, dtype: object

(9,)

tconst                tt11831142
titleType              tvEpisode
primaryTitle      Episode #1.279
originalTitle     Episode #1.279
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008596, dtype: object

(9,)

tconst                tt11831144
titleType              tvEpisode
primaryTitle      Episode #1.280
originalTitle     Episode #1.280
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008597, dtype: object

(9,)

tconst                tt11831146
titleType              tvEpisode
primaryTitle      Episode #1.523
originalTitle     Episode #1.523
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008598, dtype: object

(9,)

tconst                tt11831148
titleType              tvEpisode
primaryTitle      Episode #1.281
originalTitle     Episode #1.281
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008599, dtype: object

(9,)

tconst               tt1183114
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008600, dtype: object

(9,)

tconst                                tt11831150
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008601, dtype: object

(9,)

tconst                                 tt11831152
titleType                                tvSeries
primaryTitle      Loranga, Masarin och Dartanjang
originalTitle     Loranga, Masarin och Dartanjang
isAdult                                         0
startYear                                    1975
endYear                                      1975
runtimeMinutes                                 \N
genres                                  Animation
Name: 2008602, dtype: object

(9,)

tconst                tt11831154
titleType              tvEpisode
primaryTitle      Episode #1.282
originalTitle     Episode #1.282
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008603, dtype: object

(9,)

tconst                    tt11831156
titleType                  tvEpisode
primaryTitle      Poliisit pinteessä
originalTitle     Poliisit pinteessä
isAdult                            0
startYear                       2014
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2008604, dtype: object

(9,)

tconst                tt11831158
titleType              tvEpisode
primaryTitle      Episode #1.285
originalTitle     Episode #1.285
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008605, dtype: object

(9,)

tconst                          tt1183115
titleType                       tvEpisode
primaryTitle      Coach Trip to Blackpool
originalTitle     Coach Trip to Blackpool
isAdult                                 0
startYear                            1974
endYear                                \N
runtimeMinutes                         \N
genres                       Comedy,Music
Name: 2008606, dtype: object

(9,)

tconst                tt11831160
titleType              tvEpisode
primaryTitle      Episode #1.283
originalTitle     Episode #1.283
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008607, dtype: object

(9,)

tconst                tt11831162
titleType              tvEpisode
primaryTitle      Episode #1.284
originalTitle     Episode #1.284
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008608, dtype: object

(9,)

tconst                tt11831164
titleType              tvEpisode
primaryTitle      Episode #1.286
originalTitle     Episode #1.286
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008609, dtype: object

(9,)

tconst                tt11831166
titleType              tvEpisode
primaryTitle      Episode #1.287
originalTitle     Episode #1.287
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008610, dtype: object

(9,)

tconst                tt11831168
titleType              tvEpisode
primaryTitle      Episode #1.288
originalTitle     Episode #1.288
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008611, dtype: object

(9,)

tconst               tt1183116
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008612, dtype: object

(9,)

tconst                            tt11831170
titleType                          tvEpisode
primaryTitle      Elättäkää itse vanhempanne
originalTitle     Elättäkää itse vanhempanne
isAdult                                    0
startYear                               2014
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2008613, dtype: object

(9,)

tconst                tt11831172
titleType              tvEpisode
primaryTitle      Episode #1.289
originalTitle     Episode #1.289
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008614, dtype: object

(9,)

tconst                                tt11831174
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                 News,Reality-TV,Talk-Show
Name: 2008615, dtype: object

(9,)

tconst                tt11831176
titleType              tvEpisode
primaryTitle      Episode #1.291
originalTitle     Episode #1.291
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008616, dtype: object

(9,)

tconst                tt11831178
titleType              tvEpisode
primaryTitle      Episode #1.290
originalTitle     Episode #1.290
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008617, dtype: object

(9,)

tconst                tt1183117
titleType             tvEpisode
primaryTitle      New Years Eve
originalTitle     New Years Eve
isAdult                       0
startYear                  1974
endYear                      \N
runtimeMinutes               \N
genres             Comedy,Music
Name: 2008618, dtype: object

(9,)

tconst                tt11831180
titleType              tvEpisode
primaryTitle      Episode #1.293
originalTitle     Episode #1.293
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008619, dtype: object

(9,)

tconst                tt11831182
titleType              tvEpisode
primaryTitle      Episode #1.294
originalTitle     Episode #1.294
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008620, dtype: object

(9,)

tconst                tt11831184
titleType              tvEpisode
primaryTitle      Episode #1.292
originalTitle     Episode #1.292
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008621, dtype: object

(9,)

tconst                     tt11831186
titleType                   tvEpisode
primaryTitle      Minne menet Venäjä?
originalTitle     Minne menet Venäjä?
isAdult                             0
startYear                        2014
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2008622, dtype: object

(9,)

tconst                tt11831188
titleType              tvEpisode
primaryTitle      Episode #1.296
originalTitle     Episode #1.296
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008623, dtype: object

(9,)

tconst               tt1183118
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008624, dtype: object

(9,)

tconst                tt11831190
titleType              tvEpisode
primaryTitle      Episode #1.295
originalTitle     Episode #1.295
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008625, dtype: object

(9,)

tconst                tt11831192
titleType              tvEpisode
primaryTitle      Episode #1.297
originalTitle     Episode #1.297
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008626, dtype: object

(9,)

tconst                           tt11831194
titleType                         tvEpisode
primaryTitle      Ydinvoimala venäläisiltä?
originalTitle     Ydinvoimala venäläisiltä?
isAdult                                   0
startYear                              2014
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2008627, dtype: object

(9,)

tconst                  tt11831196
titleType                tvEpisode
primaryTitle      Hallitus hajalla
originalTitle     Hallitus hajalla
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2008628, dtype: object

(9,)

tconst                                tt11831198
titleType                              tvEpisode
primaryTitle      Episode dated 10 February 2020
originalTitle     Episode dated 10 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2008629, dtype: object

(9,)

tconst               tt1183119
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008630, dtype: object

(9,)

tconst                        tt11831200
titleType                      tvEpisode
primaryTitle      Finnair turbulenssissa
originalTitle     Finnair turbulenssissa
isAdult                                0
startYear                           2014
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2008631, dtype: object

(9,)

tconst                                tt11831202
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008632, dtype: object

(9,)

tconst                                                   tt11831204
titleType                                                 tvEpisode
primaryTitle      If You're Not Seeing Sonic The Hedgehog Becaus...
originalTitle     If You're Not Seeing Sonic The Hedgehog Becaus...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2008633, dtype: object

(9,)

tconst                         tt11831206
titleType                       tvEpisode
primaryTitle      Työttömille tiukat ajat
originalTitle     Työttömille tiukat ajat
isAdult                                 0
startYear                            2014
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2008634, dtype: object

(9,)

tconst                     tt11831208
titleType                   tvEpisode
primaryTitle           Episode #1.481
originalTitle          Episode #1.481
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008635, dtype: object

(9,)

tconst               tt1183120
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008636, dtype: object

(9,)

tconst                     tt11831210
titleType                   tvEpisode
primaryTitle           Episode #1.482
originalTitle          Episode #1.482
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008637, dtype: object

(9,)

tconst                     tt11831212
titleType                   tvEpisode
primaryTitle           Episode #1.483
originalTitle          Episode #1.483
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008638, dtype: object

(9,)

tconst                     tt11831214
titleType                   tvEpisode
primaryTitle           Episode #1.484
originalTitle          Episode #1.484
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008639, dtype: object

(9,)

tconst                     tt11831216
titleType                   tvEpisode
primaryTitle           Episode #1.485
originalTitle          Episode #1.485
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008640, dtype: object

(9,)

tconst                     tt11831218
titleType                   tvEpisode
primaryTitle           Episode #1.486
originalTitle          Episode #1.486
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008641, dtype: object

(9,)

tconst               tt1183121
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008642, dtype: object

(9,)

tconst                     tt11831220
titleType                   tvEpisode
primaryTitle           Episode #1.488
originalTitle          Episode #1.488
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008643, dtype: object

(9,)

tconst                     tt11831222
titleType                   tvEpisode
primaryTitle           Episode #1.487
originalTitle          Episode #1.487
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008644, dtype: object

(9,)

tconst                     tt11831224
titleType                   tvEpisode
primaryTitle      Nato-kortti hihassa
originalTitle     Nato-kortti hihassa
isAdult                             0
startYear                        2014
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2008645, dtype: object

(9,)

tconst                     tt11831226
titleType                   tvEpisode
primaryTitle           Episode #1.489
originalTitle          Episode #1.489
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008646, dtype: object

(9,)

tconst                     tt11831228
titleType                   tvEpisode
primaryTitle           Episode #1.490
originalTitle          Episode #1.490
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008647, dtype: object

(9,)

tconst               tt1183122
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008648, dtype: object

(9,)

tconst                     tt11831230
titleType                   tvEpisode
primaryTitle           Episode #1.491
originalTitle          Episode #1.491
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008649, dtype: object

(9,)

tconst                 tt11831232
titleType               tvEpisode
primaryTitle      Ilmailun vaarat
originalTitle     Ilmailun vaarat
isAdult                         0
startYear                    2014
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2008650, dtype: object

(9,)

tconst                     tt11831234
titleType                   tvEpisode
primaryTitle           Episode #1.492
originalTitle          Episode #1.492
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008651, dtype: object

(9,)

tconst                     tt11831236
titleType                   tvEpisode
primaryTitle           Episode #1.493
originalTitle          Episode #1.493
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008652, dtype: object

(9,)

tconst                     tt11831238
titleType                   tvEpisode
primaryTitle           Episode #1.495
originalTitle          Episode #1.495
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008653, dtype: object

(9,)

tconst               tt1183123
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008654, dtype: object

(9,)

tconst                     tt11831240
titleType                   tvEpisode
primaryTitle           Episode #1.494
originalTitle          Episode #1.494
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008655, dtype: object

(9,)

tconst                     tt11831242
titleType                   tvEpisode
primaryTitle           Episode #1.496
originalTitle          Episode #1.496
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008656, dtype: object

(9,)

tconst                     tt11831244
titleType                   tvEpisode
primaryTitle           Episode #1.497
originalTitle          Episode #1.497
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008657, dtype: object

(9,)

tconst                                tt11831246
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008658, dtype: object

(9,)

tconst                     tt11831248
titleType                   tvEpisode
primaryTitle           Episode #1.498
originalTitle          Episode #1.498
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008659, dtype: object

(9,)

tconst               tt1183124
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008660, dtype: object

(9,)

tconst                     tt11831250
titleType                   tvEpisode
primaryTitle           Episode #1.499
originalTitle          Episode #1.499
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008661, dtype: object

(9,)

tconst                     tt11831252
titleType                   tvEpisode
primaryTitle           Episode #1.500
originalTitle          Episode #1.500
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008662, dtype: object

(9,)

tconst                                tt11831254
titleType                              tvEpisode
primaryTitle      Episode dated 11 February 2020
originalTitle     Episode dated 11 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2008663, dtype: object

(9,)

tconst                     tt11831256
titleType                   tvEpisode
primaryTitle           Episode #1.981
originalTitle          Episode #1.981
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008664, dtype: object

(9,)

tconst                     tt11831258
titleType                   tvEpisode
primaryTitle           Episode #1.982
originalTitle          Episode #1.982
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008665, dtype: object

(9,)

tconst               tt1183125
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 1974
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2008666, dtype: object

(9,)

tconst                                tt11831260
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008667, dtype: object

(9,)

tconst                     tt11831262
titleType                   tvEpisode
primaryTitle           Episode #1.983
originalTitle          Episode #1.983
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008668, dtype: object

(9,)

tconst                            tt11831264
titleType                          tvEpisode
primaryTitle      Pudokkaat pakolla kouluun?
originalTitle     Pudokkaat pakolla kouluun?
isAdult                                    0
startYear                               2014
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2008669, dtype: object

(9,)

tconst                                                   tt11831266
titleType                                                 tvEpisode
primaryTitle      We Need To Save Snake Eyes From Identity Politics
originalTitle     We Need To Save Snake Eyes From Identity Politics
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2008670, dtype: object

(9,)

tconst             tt11831268
titleType               short
primaryTitle             Prom
originalTitle            Prom
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2008671, dtype: object

(9,)

tconst                tt1183126
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2003
endYear                      \N
runtimeMinutes               \N
genres              Crime,Drama
Name: 2008672, dtype: object

(9,)

tconst                        tt11831270
titleType                      tvEpisode
primaryTitle      Jokerit loikkasi itään
originalTitle     Jokerit loikkasi itään
isAdult                                0
startYear                           2014
endYear                               \N
runtimeMinutes                        \N
genres                         Talk-Show
Name: 2008673, dtype: object

(9,)

tconst                     tt11831272
titleType                   tvEpisode
primaryTitle           Episode #1.985
originalTitle          Episode #1.985
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008674, dtype: object

(9,)

tconst                     tt11831274
titleType                   tvEpisode
primaryTitle           Episode #1.984
originalTitle          Episode #1.984
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008675, dtype: object

(9,)

tconst                               tt11831276
titleType                             tvEpisode
primaryTitle      Eläkeikä ylös, eläkkeet alas?
originalTitle     Eläkeikä ylös, eläkkeet alas?
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2008676, dtype: object

(9,)

tconst                     tt11831278
titleType                   tvEpisode
primaryTitle           Episode #1.986
originalTitle          Episode #1.986
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008677, dtype: object

(9,)

tconst               tt1183127
titleType            tvEpisode
primaryTitle      Episode #3.1
originalTitle     Episode #3.1
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              47
genres                   Drama
Name: 2008678, dtype: object

(9,)

tconst                     tt11831280
titleType                   tvEpisode
primaryTitle           Episode #1.987
originalTitle          Episode #1.987
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008679, dtype: object

(9,)

tconst                                  tt11831282
titleType                                tvEpisode
primaryTitle      More Cooking Up with Melody Lane
originalTitle     More Cooking Up with Melody Lane
isAdult                                          0
startYear                                     2019
endYear                                         \N
runtimeMinutes                                  \N
genres                         Comedy,Drama,Sci-Fi
Name: 2008680, dtype: object

(9,)

tconst                     tt11831284
titleType                   tvEpisode
primaryTitle           Episode #1.988
originalTitle          Episode #1.988
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008681, dtype: object

(9,)

tconst                     tt11831286
titleType                   tvEpisode
primaryTitle      Tomorrow World 2015
originalTitle     Tomorrow World 2015
isAdult                             0
startYear                        2015
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2008682, dtype: object

(9,)

tconst                     tt11831288
titleType                   tvEpisode
primaryTitle           Episode #1.989
originalTitle          Episode #1.989
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008683, dtype: object

(9,)

tconst               tt1183128
titleType            tvEpisode
primaryTitle      Episode #3.5
originalTitle     Episode #3.5
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              47
genres                   Drama
Name: 2008684, dtype: object

(9,)

tconst                     tt11831290
titleType                   tvEpisode
primaryTitle           Episode #1.990
originalTitle          Episode #1.990
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008685, dtype: object

(9,)

tconst              tt11831292
titleType            tvEpisode
primaryTitle          Adelante
originalTitle         Adelante
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              31
genres            Comedy,Drama
Name: 2008686, dtype: object

(9,)

tconst                     tt11831294
titleType                   tvEpisode
primaryTitle           Episode #1.991
originalTitle          Episode #1.991
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008687, dtype: object

(9,)

tconst                     tt11831296
titleType                   tvEpisode
primaryTitle           Episode #1.992
originalTitle          Episode #1.992
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008688, dtype: object

(9,)

tconst                     tt11831298
titleType                   tvEpisode
primaryTitle           Episode #1.994
originalTitle          Episode #1.994
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008689, dtype: object

(9,)

tconst                tt1183129
titleType             tvEpisode
primaryTitle      Episode #9.24
originalTitle     Episode #9.24
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2008690, dtype: object

(9,)

tconst                     tt11831300
titleType                   tvEpisode
primaryTitle           Episode #1.993
originalTitle          Episode #1.993
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008691, dtype: object

(9,)

tconst                               tt11831302
titleType                             tvEpisode
primaryTitle      5: They better be a knockin'!
originalTitle     5: They better be a knockin'!
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2008692, dtype: object

(9,)

tconst                           tt11831304
titleType                         tvEpisode
primaryTitle      Säröjä ulkopoliitiikassa?
originalTitle     Säröjä ulkopoliitiikassa?
isAdult                                   0
startYear                              2014
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2008693, dtype: object

(9,)

tconst                     tt11831306
titleType                   tvEpisode
primaryTitle           Episode #1.998
originalTitle          Episode #1.998
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008694, dtype: object

(9,)

tconst                     tt11831308
titleType                   tvEpisode
primaryTitle           Episode #1.995
originalTitle          Episode #1.995
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008695, dtype: object

(9,)

tconst                                tt1183130
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2008
originalTitle     Episode dated 6 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2008696, dtype: object

(9,)

tconst                     tt11831310
titleType                   tvEpisode
primaryTitle           Episode #1.996
originalTitle          Episode #1.996
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008697, dtype: object

(9,)

tconst                     tt11831312
titleType                   tvEpisode
primaryTitle           Episode #1.997
originalTitle          Episode #1.997
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008698, dtype: object

(9,)

tconst                     tt11831314
titleType                   tvEpisode
primaryTitle           Episode #1.999
originalTitle          Episode #1.999
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008699, dtype: object

(9,)

tconst                         tt11831316
titleType                       tvEpisode
primaryTitle      Paperinpyörittäjien maa
originalTitle     Paperinpyörittäjien maa
isAdult                                 0
startYear                            2014
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2008700, dtype: object

(9,)

tconst                     tt11831318
titleType                   tvEpisode
primaryTitle          Episode #1.1000
originalTitle         Episode #1.1000
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008701, dtype: object

(9,)

tconst                                                    tt1183131
titleType                                                     video
primaryTitle      'Ach, die Sissi!' - Wie Romy lernte, nein zu s...
originalTitle     'Ach, die Sissi!' - Wie Romy lernte, nein zu s...
isAdult                                                           0
startYear                                                      2007
endYear                                                          \N
runtimeMinutes                                                   10
genres                                            Documentary,Short
Name: 2008702, dtype: object

(9,)

tconst                            tt11831320
titleType                          tvEpisode
primaryTitle      Asuntomarkkinat krapulassa
originalTitle     Asuntomarkkinat krapulassa
isAdult                                    0
startYear                               2014
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2008703, dtype: object

(9,)

tconst                  tt11831322
titleType                videoGame
primaryTitle      Just Dance Wii U
originalTitle     Just Dance Wii U
isAdult                          0
startYear                     2014
endYear                         \N
runtimeMinutes                  \N
genres                       Music
Name: 2008704, dtype: object

(9,)

tconst                                tt11831324
titleType                              tvEpisode
primaryTitle      Episode dated 28 December 2019
originalTitle     Episode dated 28 December 2019
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008705, dtype: object

(9,)

tconst                       tt11831326
titleType                     tvEpisode
primaryTitle      Ebola ehti Eurooppaan
originalTitle     Ebola ehti Eurooppaan
isAdult                               0
startYear                          2014
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2008706, dtype: object

(9,)

tconst              tt11831328
titleType            tvEpisode
primaryTitle              Solo
originalTitle             Solo
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              31
genres            Comedy,Drama
Name: 2008707, dtype: object

(9,)

tconst                       tt1183132
titleType                        movie
primaryTitle      Animales de compañía
originalTitle     Animales de compañía
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres                          Comedy
Name: 2008708, dtype: object

(9,)

tconst                      tt11831330
titleType                    tvEpisode
primaryTitle      Ozark Mountain Lodge
originalTitle     Ozark Mountain Lodge
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      39
genres                     Documentary
Name: 2008709, dtype: object

(9,)

tconst            tt11831332
titleType          tvEpisode
primaryTitle       Episode 3
originalTitle      Episode 3
isAdult                    0
startYear               2015
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2008710, dtype: object

(9,)

tconst                                tt11831334
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008711, dtype: object

(9,)

tconst                     tt11831336
titleType                   tvEpisode
primaryTitle          Episode #1.1201
originalTitle         Episode #1.1201
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008712, dtype: object

(9,)

tconst                     tt11831338
titleType                   tvEpisode
primaryTitle          Episode #1.1202
originalTitle         Episode #1.1202
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008713, dtype: object

(9,)

tconst                      tt1183133
titleType                       short
primaryTitle                 Das Baby
originalTitle                Das Baby
isAdult                             0
startYear                        2007
endYear                            \N
runtimeMinutes                     30
genres            Drama,Mystery,Short
Name: 2008714, dtype: object

(9,)

tconst                     tt11831340
titleType                   tvEpisode
primaryTitle          Episode #1.1203
originalTitle         Episode #1.1203
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008715, dtype: object

(9,)

tconst                     tt11831342
titleType                   tvEpisode
primaryTitle          Episode #1.1204
originalTitle         Episode #1.1204
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008716, dtype: object

(9,)

tconst                                  tt11831344
titleType                                tvEpisode
primaryTitle      Kokoomus ja SDP tukkanuottasilla
originalTitle     Kokoomus ja SDP tukkanuottasilla
isAdult                                          0
startYear                                     2014
endYear                                         \N
runtimeMinutes                                  \N
genres                                   Talk-Show
Name: 2008717, dtype: object

(9,)

tconst                     tt11831346
titleType                   tvEpisode
primaryTitle          Episode #1.1206
originalTitle         Episode #1.1206
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008718, dtype: object

(9,)

tconst                     tt11831348
titleType                   tvEpisode
primaryTitle          Episode #1.1205
originalTitle         Episode #1.1205
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008719, dtype: object

(9,)

tconst                                      tt1183134
titleType                                     tvMovie
primaryTitle      Behind the Scenes of This Old House
originalTitle     Behind the Scenes of This Old House
isAdult                                             0
startYear                                        2002
endYear                                            \N
runtimeMinutes                                     \N
genres                                    Documentary
Name: 2008720, dtype: object

(9,)

tconst                     tt11831350
titleType                   tvEpisode
primaryTitle          Episode #1.1207
originalTitle         Episode #1.1207
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008721, dtype: object

(9,)

tconst              tt11831352
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2013
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2008722, dtype: object

(9,)

tconst                     tt11831354
titleType                   tvEpisode
primaryTitle          Episode #1.1208
originalTitle         Episode #1.1208
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008723, dtype: object

(9,)

tconst                    tt11831356
titleType                      video
primaryTitle      Flawes: Ghost Town
originalTitle     Flawes: Ghost Town
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                     3
genres                   Music,Short
Name: 2008724, dtype: object

(9,)

tconst                     tt11831358
titleType                   tvEpisode
primaryTitle          Episode #1.1209
originalTitle         Episode #1.1209
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008725, dtype: object

(9,)

tconst                                                    tt1183135
titleType                                                     video
primaryTitle      Christina Aguilera: Back to Basics - Live and ...
originalTitle     Christina Aguilera: Back to Basics - Live and ...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                  130
genres                                            Documentary,Music
Name: 2008726, dtype: object

(9,)

tconst                     tt11831360
titleType                   tvEpisode
primaryTitle          Episode #1.1210
originalTitle         Episode #1.1210
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008727, dtype: object

(9,)

tconst                     tt11831362
titleType                   tvEpisode
primaryTitle          Episode #1.1211
originalTitle         Episode #1.1211
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008728, dtype: object

(9,)

tconst                   tt11831364
titleType                 tvEpisode
primaryTitle      Itämerellä kuohuu
originalTitle     Itämerellä kuohuu
isAdult                           0
startYear                      2014
endYear                          \N
runtimeMinutes                   \N
genres                    Talk-Show
Name: 2008729, dtype: object

(9,)

tconst                     tt11831366
titleType                   tvEpisode
primaryTitle          Episode #1.1213
originalTitle         Episode #1.1213
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008730, dtype: object

(9,)

tconst                     tt11831368
titleType                   tvEpisode
primaryTitle          Episode #1.1212
originalTitle         Episode #1.1212
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008731, dtype: object

(9,)

tconst              tt1183136
titleType               movie
primaryTitle       Cold Waves
originalTitle      Cold Waves
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes            108
genres            Documentary
Name: 2008732, dtype: object

(9,)

tconst                     tt11831370
titleType                   tvEpisode
primaryTitle          Episode #1.1214
originalTitle         Episode #1.1214
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008733, dtype: object

(9,)

tconst                     tt11831372
titleType                   tvEpisode
primaryTitle          Episode #1.1216
originalTitle         Episode #1.1216
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008734, dtype: object

(9,)

tconst                     tt11831374
titleType                   tvEpisode
primaryTitle          Episode #1.1215
originalTitle         Episode #1.1215
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008735, dtype: object

(9,)

tconst                     tt11831376
titleType                   tvEpisode
primaryTitle      Lihas on uusi laiha
originalTitle     Lihas on uusi laiha
isAdult                             0
startYear                        2014
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2008736, dtype: object

(9,)

tconst                         tt11831378
titleType                           short
primaryTitle            The Stocky Broker
originalTitle           The Stocky Broker
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         16
genres            Documentary,Short,Sport
Name: 2008737, dtype: object

(9,)

tconst                tt1183137
titleType                 short
primaryTitle      Datura Sophia
originalTitle     Datura Sophia
isAdult                       0
startYear                  2005
endYear                      \N
runtimeMinutes               23
genres                    Short
Name: 2008738, dtype: object

(9,)

tconst                     tt11831380
titleType                   tvEpisode
primaryTitle          Episode #1.1217
originalTitle         Episode #1.1217
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008739, dtype: object

(9,)

tconst                     tt11831382
titleType                   tvEpisode
primaryTitle          Episode #1.1218
originalTitle         Episode #1.1218
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008740, dtype: object

(9,)

tconst                     tt11831384
titleType                   tvEpisode
primaryTitle          Episode #1.1219
originalTitle         Episode #1.1219
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008741, dtype: object

(9,)

tconst                     tt11831386
titleType                   tvEpisode
primaryTitle          Episode #1.1220
originalTitle         Episode #1.1220
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008742, dtype: object

(9,)

tconst                               tt11831388
titleType                             tvEpisode
primaryTitle      Episode dated 6 November 2014
originalTitle     Episode dated 6 November 2014
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2008743, dtype: object

(9,)

tconst               tt1183138
titleType                short
primaryTitle       Death Trike
originalTitle      Death Trike
isAdult                      0
startYear                 2006
endYear                     \N
runtimeMinutes               7
genres            Horror,Short
Name: 2008744, dtype: object

(9,)

tconst                     tt11831390
titleType                   tvEpisode
primaryTitle          Episode #1.1441
originalTitle         Episode #1.1441
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008745, dtype: object

(9,)

tconst                     tt11831392
titleType                   tvEpisode
primaryTitle          Episode #1.1443
originalTitle         Episode #1.1443
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008746, dtype: object

(9,)

tconst                     tt11831394
titleType                   tvEpisode
primaryTitle          Episode #1.1442
originalTitle         Episode #1.1442
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008747, dtype: object

(9,)

tconst                     tt11831396
titleType                   tvEpisode
primaryTitle          Episode #1.1444
originalTitle         Episode #1.1444
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008748, dtype: object

(9,)

tconst                     tt11831398
titleType                   tvEpisode
primaryTitle          Episode #1.1445
originalTitle         Episode #1.1445
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008749, dtype: object

(9,)

tconst                                  tt1183139
titleType                                   movie
primaryTitle      Déculottez-vous, les starlettes
originalTitle     Déculottez-vous, les starlettes
isAdult                                         1
startYear                                    1977
endYear                                        \N
runtimeMinutes                                 80
genres                                      Adult
Name: 2008750, dtype: object

(9,)

tconst                     tt11831400
titleType                   tvEpisode
primaryTitle          Episode #1.1446
originalTitle         Episode #1.1446
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008751, dtype: object

(9,)

tconst                     tt11831402
titleType                   tvEpisode
primaryTitle          Episode #1.1447
originalTitle         Episode #1.1447
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008752, dtype: object

(9,)

tconst                     tt11831404
titleType                   tvEpisode
primaryTitle          Episode #1.1448
originalTitle         Episode #1.1448
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008753, dtype: object

(9,)

tconst                     tt11831406
titleType                   tvEpisode
primaryTitle          Episode #1.1449
originalTitle         Episode #1.1449
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008754, dtype: object

(9,)

tconst                     tt11831408
titleType                   tvEpisode
primaryTitle          Episode #1.1450
originalTitle         Episode #1.1450
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008755, dtype: object

(9,)

tconst                  tt1183140
titleType                   movie
primaryTitle      Etwas ist immer
originalTitle     Etwas ist immer
isAdult                         0
startYear                    1994
endYear                        \N
runtimeMinutes                 87
genres                     Comedy
Name: 2008756, dtype: object

(9,)

tconst                     tt11831410
titleType                   tvEpisode
primaryTitle          Episode #1.1452
originalTitle         Episode #1.1452
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008757, dtype: object

(9,)

tconst                     tt11831412
titleType                   tvEpisode
primaryTitle          Episode #1.1451
originalTitle         Episode #1.1451
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008758, dtype: object

(9,)

tconst                     tt11831414
titleType                   tvEpisode
primaryTitle          Episode #1.1453
originalTitle         Episode #1.1453
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008759, dtype: object

(9,)

tconst                     tt11831416
titleType                   tvEpisode
primaryTitle          Episode #1.1454
originalTitle         Episode #1.1454
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008760, dtype: object

(9,)

tconst                     tt11831418
titleType                   tvEpisode
primaryTitle          Episode #1.1455
originalTitle         Episode #1.1455
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008761, dtype: object

(9,)

tconst                                                    tt1183141
titleType                                                     video
primaryTitle      Exploring the Hills: The Making of 'The Hills ...
originalTitle     Exploring the Hills: The Making of 'The Hills ...
isAdult                                                           0
startYear                                                      2007
endYear                                                          \N
runtimeMinutes                                                   13
genres                                            Documentary,Short
Name: 2008762, dtype: object

(9,)

tconst                                tt11831420
titleType                              tvEpisode
primaryTitle      Poliisi puun ja kuoren välissä
originalTitle     Poliisi puun ja kuoren välissä
isAdult                                        0
startYear                                   2014
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2008763, dtype: object

(9,)

tconst                     tt11831422
titleType                   tvEpisode
primaryTitle          Episode #1.1456
originalTitle         Episode #1.1456
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008764, dtype: object

(9,)

tconst                     tt11831424
titleType                   tvEpisode
primaryTitle          Episode #1.1457
originalTitle         Episode #1.1457
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008765, dtype: object

(9,)

tconst                     tt11831426
titleType                   tvEpisode
primaryTitle          Episode #1.1459
originalTitle         Episode #1.1459
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008766, dtype: object

(9,)

tconst                     tt11831428
titleType                   tvEpisode
primaryTitle          Episode #1.1458
originalTitle         Episode #1.1458
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008767, dtype: object

(9,)

tconst                                                    tt1183142
titleType                                                     movie
primaryTitle      If One Thing Matters: A Film About Wolfgang Ti...
originalTitle     If One Thing Matters: A Film About Wolfgang Ti...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   72
genres                                                  Documentary
Name: 2008768, dtype: object

(9,)

tconst                     tt11831430
titleType                   tvEpisode
primaryTitle          Episode #1.1460
originalTitle         Episode #1.1460
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008769, dtype: object

(9,)

tconst                     tt11831432
titleType                   tvEpisode
primaryTitle          Episode #1.1701
originalTitle         Episode #1.1701
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008770, dtype: object

(9,)

tconst                       tt11831434
titleType                     tvEpisode
primaryTitle      Eikö lasikatto murru?
originalTitle     Eikö lasikatto murru?
isAdult                               0
startYear                          2014
endYear                              \N
runtimeMinutes                       \N
genres                        Talk-Show
Name: 2008771, dtype: object

(9,)

tconst               tt11831436
titleType             tvEpisode
primaryTitle              Pilot
originalTitle             Pilot
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres            Drama,Mystery
Name: 2008772, dtype: object

(9,)

tconst                     tt11831438
titleType                   tvEpisode
primaryTitle          Episode #1.1703
originalTitle         Episode #1.1703
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008773, dtype: object

(9,)

tconst                         tt1183143
titleType                          movie
primaryTitle      Jesus Christus Erlöser
originalTitle     Jesus Christus Erlöser
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        84
genres                       Documentary
Name: 2008774, dtype: object

(9,)

tconst                     tt11831440
titleType                   tvEpisode
primaryTitle          Episode #1.1702
originalTitle         Episode #1.1702
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008775, dtype: object

(9,)

tconst                tt11831442
titleType              tvEpisode
primaryTitle      Laughing Skull
originalTitle     Laughing Skull
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2008776, dtype: object

(9,)

tconst                     tt11831444
titleType                   tvEpisode
primaryTitle          Episode #1.1704
originalTitle         Episode #1.1704
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008777, dtype: object

(9,)

tconst                      tt11831446
titleType                    tvEpisode
primaryTitle      The Misuse of "Simp"
originalTitle     The Misuse of "Simp"
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                       Talk-Show
Name: 2008778, dtype: object

(9,)

tconst                     tt11831448
titleType                   tvEpisode
primaryTitle          Episode #1.1705
originalTitle         Episode #1.1705
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008779, dtype: object

(9,)

tconst                                  tt1183144
titleType                                 tvMovie
primaryTitle      Kenpô dai 39 jô: Furasshu bakku
originalTitle     Kenpô dai 39 jô: Furasshu bakku
isAdult                                         0
startYear                                    2001
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2008780, dtype: object

(9,)

tconst                     tt11831450
titleType                   tvEpisode
primaryTitle          Episode #1.1707
originalTitle         Episode #1.1707
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008781, dtype: object

(9,)

tconst                     tt11831452
titleType                   tvEpisode
primaryTitle          Episode #1.1706
originalTitle         Episode #1.1706
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008782, dtype: object

(9,)

tconst                     tt11831454
titleType                   tvEpisode
primaryTitle          Episode #1.1708
originalTitle         Episode #1.1708
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008783, dtype: object

(9,)

tconst                         tt11831456
titleType                       tvEpisode
primaryTitle      Fennovoiman naimakaupat
originalTitle     Fennovoiman naimakaupat
isAdult                                 0
startYear                            2014
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2008784, dtype: object

(9,)

tconst                     tt11831458
titleType                   tvEpisode
primaryTitle          Episode #1.1709
originalTitle         Episode #1.1709
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008785, dtype: object

(9,)

tconst                           tt1183145
titleType                          tvMovie
primaryTitle      Das Kino bittet zu Tisch
originalTitle     Das Kino bittet zu Tisch
isAdult                                  0
startYear                             1995
endYear                                 \N
runtimeMinutes                          30
genres                         Documentary
Name: 2008786, dtype: object

(9,)

tconst                   tt11831460
titleType                 tvEpisode
primaryTitle      Elefante de Papel
originalTitle     Elefante de Papel
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                    Biography
Name: 2008787, dtype: object

(9,)

tconst                     tt11831462
titleType                   tvEpisode
primaryTitle          Episode #1.1710
originalTitle         Episode #1.1710
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008788, dtype: object

(9,)

tconst                     tt11831464
titleType                   tvEpisode
primaryTitle          Episode #1.1711
originalTitle         Episode #1.1711
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008789, dtype: object

(9,)

tconst                     tt11831466
titleType                   tvEpisode
primaryTitle          Episode #1.1712
originalTitle         Episode #1.1712
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008790, dtype: object

(9,)

tconst                     tt11831468
titleType                   tvEpisode
primaryTitle          Episode #1.1713
originalTitle         Episode #1.1713
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008791, dtype: object

(9,)

tconst                                  tt1183146
titleType                                   video
primaryTitle      Legends of Country Blues Guitar
originalTitle     Legends of Country Blues Guitar
isAdult                                         0
startYear                                    1994
endYear                                        \N
runtimeMinutes                                 59
genres                                      Music
Name: 2008792, dtype: object

(9,)

tconst                     tt11831470
titleType                   tvEpisode
primaryTitle          Episode #1.1714
originalTitle         Episode #1.1714
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008793, dtype: object

(9,)

tconst                   tt11831472
titleType                 tvEpisode
primaryTitle      Stuck in the SNOW
originalTitle     Stuck in the SNOW
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                    9
genres             Animation,Family
Name: 2008794, dtype: object

(9,)

tconst                     tt11831474
titleType                   tvEpisode
primaryTitle          Episode #1.1717
originalTitle         Episode #1.1717
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008795, dtype: object

(9,)

tconst                     tt11831476
titleType                   tvEpisode
primaryTitle          Episode #1.1715
originalTitle         Episode #1.1715
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008796, dtype: object

(9,)

tconst                     tt11831478
titleType                   tvEpisode
primaryTitle          Episode #1.1716
originalTitle         Episode #1.1716
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008797, dtype: object

(9,)

tconst                     tt1183147
titleType                      movie
primaryTitle      Lights Camera Dead
originalTitle     Lights Camera Dead
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    77
genres                 Comedy,Horror
Name: 2008798, dtype: object

(9,)

tconst                                            tt11831480
titleType                                          tvEpisode
primaryTitle      Duunarit kyykkyyn yhteiskuntasopimuksella?
originalTitle     Duunarit kyykkyyn yhteiskuntasopimuksella?
isAdult                                                    0
startYear                                               2014
endYear                                                   \N
runtimeMinutes                                            \N
genres                                             Talk-Show
Name: 2008799, dtype: object

(9,)

tconst                     tt11831482
titleType                   tvEpisode
primaryTitle          Episode #1.1718
originalTitle         Episode #1.1718
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008800, dtype: object

(9,)

tconst                     tt11831484
titleType                   tvEpisode
primaryTitle          Episode #1.1719
originalTitle         Episode #1.1719
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008801, dtype: object

(9,)

tconst                     tt11831486
titleType                   tvEpisode
primaryTitle          Episode #1.1720
originalTitle         Episode #1.1720
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008802, dtype: object

(9,)

tconst               tt11831488
titleType             tvEpisode
primaryTitle      Maluco Beleza
originalTitle     Maluco Beleza
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Biography
Name: 2008803, dtype: object

(9,)

tconst                                                tt1183148
titleType                                                 movie
primaryTitle      Mein Traum oder Die Einsamkeit ist nie allein
originalTitle     Mein Traum oder Die Einsamkeit ist nie allein
isAdult                                                       0
startYear                                                  2008
endYear                                                      \N
runtimeMinutes                                              100
genres                                                    Drama
Name: 2008804, dtype: object

(9,)

tconst                     tt11831490
titleType                   tvEpisode
primaryTitle          Episode #1.1941
originalTitle         Episode #1.1941
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008805, dtype: object

(9,)

tconst                  tt11831492
titleType                tvEpisode
primaryTitle        Episode #1.967
originalTitle       Episode #1.967
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2008806, dtype: object

(9,)

tconst                     tt11831494
titleType                   tvEpisode
primaryTitle          Episode #1.1943
originalTitle         Episode #1.1943
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008807, dtype: object

(9,)

tconst                     tt11831496
titleType                   tvEpisode
primaryTitle          Episode #1.1942
originalTitle         Episode #1.1942
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008808, dtype: object

(9,)

tconst                     tt11831498
titleType                   tvEpisode
primaryTitle          Episode #1.1944
originalTitle         Episode #1.1944
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008809, dtype: object

(9,)

tconst                                    tt1183149
titleType                                   tvMovie
primaryTitle      Oscar, que empiece el espectáculo
originalTitle     Oscar, que empiece el espectáculo
isAdult                                           0
startYear                                      2008
endYear                                          \N
runtimeMinutes                                   26
genres                                  Documentary
Name: 2008810, dtype: object

(9,)

tconst                  tt11831500
titleType                tvEpisode
primaryTitle        Episode #1.968
originalTitle       Episode #1.968
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2008811, dtype: object

(9,)

tconst                     tt11831502
titleType                   tvEpisode
primaryTitle          Episode #1.1946
originalTitle         Episode #1.1946
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008812, dtype: object

(9,)

tconst                     tt11831504
titleType                   tvEpisode
primaryTitle          Episode #1.1945
originalTitle         Episode #1.1945
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008813, dtype: object

(9,)

tconst                     tt11831506
titleType                   tvEpisode
primaryTitle          Episode #1.1947
originalTitle         Episode #1.1947
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008814, dtype: object

(9,)

tconst                  tt11831508
titleType                tvEpisode
primaryTitle        Episode #1.969
originalTitle       Episode #1.969
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2008815, dtype: object

(9,)

tconst            tt1183150
titleType             short
primaryTitle       Picknick
originalTitle      Picknick
isAdult                   0
startYear              2004
endYear                  \N
runtimeMinutes           14
genres                Short
Name: 2008816, dtype: object

(9,)

tconst                               tt11831510
titleType                             tvEpisode
primaryTitle      Mitä nyt, herra pääministeri?
originalTitle     Mitä nyt, herra pääministeri?
isAdult                                       0
startYear                                  2014
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2008817, dtype: object

(9,)

tconst                     tt11831512
titleType                   tvEpisode
primaryTitle          Episode #1.1948
originalTitle         Episode #1.1948
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008818, dtype: object

(9,)

tconst                     tt11831514
titleType                   tvEpisode
primaryTitle          Episode #1.1949
originalTitle         Episode #1.1949
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008819, dtype: object

(9,)

tconst                     tt11831516
titleType                   tvEpisode
primaryTitle          Episode #1.1950
originalTitle         Episode #1.1950
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008820, dtype: object

(9,)

tconst                                      tt11831518
titleType                                    tvEpisode
primaryTitle      Louis Bérubé, Marie-Denise Pelletier
originalTitle     Louis Bérubé, Marie-Denise Pelletier
isAdult                                              0
startYear                                         2009
endYear                                             \N
runtimeMinutes                                      \N
genres                                         Musical
Name: 2008821, dtype: object

(9,)

tconst                tt1183151
titleType               tvMovie
primaryTitle      Red and Blues
originalTitle     Red and Blues
isAdult                       0
startYear                  2005
endYear                      \N
runtimeMinutes               65
genres                       \N
Name: 2008822, dtype: object

(9,)

tconst                     tt11831520
titleType                   tvEpisode
primaryTitle          Episode #1.1951
originalTitle         Episode #1.1951
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008823, dtype: object

(9,)

tconst                     tt11831522
titleType                   tvEpisode
primaryTitle          Episode #1.1952
originalTitle         Episode #1.1952
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008824, dtype: object

(9,)

tconst                     tt11831524
titleType                   tvEpisode
primaryTitle          Episode #1.1953
originalTitle         Episode #1.1953
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008825, dtype: object

(9,)

tconst                     tt11831526
titleType                   tvEpisode
primaryTitle          Episode #1.1954
originalTitle         Episode #1.1954
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008826, dtype: object

(9,)

tconst                     tt11831528
titleType                   tvEpisode
primaryTitle          Episode #1.1955
originalTitle         Episode #1.1955
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008827, dtype: object

(9,)

tconst                                                    tt1183152
titleType                                                     video
primaryTitle      Reise in die Vergangenheit - Ulli Lommel über ...
originalTitle     Reise in die Vergangenheit - Ulli Lommel über ...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   21
genres                                            Documentary,Short
Name: 2008828, dtype: object

(9,)

tconst                     tt11831530
titleType                   tvEpisode
primaryTitle          Episode #1.1956
originalTitle         Episode #1.1956
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008829, dtype: object

(9,)

tconst                     tt11831532
titleType                   tvEpisode
primaryTitle          Episode #1.1958
originalTitle         Episode #1.1958
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008830, dtype: object

(9,)

tconst                     tt11831534
titleType                   tvEpisode
primaryTitle          Episode #1.1957
originalTitle         Episode #1.1957
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008831, dtype: object

(9,)

tconst                     tt11831536
titleType                   tvEpisode
primaryTitle          Episode #1.1959
originalTitle         Episode #1.1959
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008832, dtype: object

(9,)

tconst                     tt11831538
titleType                   tvEpisode
primaryTitle          Episode #1.1960
originalTitle         Episode #1.1960
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2008833, dtype: object

(9,)

tconst                                              tt1183153
titleType                                             tvMovie
primaryTitle      Seitensprünge - Deutsch-deutsche Scheinehen
originalTitle     Seitensprünge - Deutsch-deutsche Scheinehen
isAdult                                                     0
startYear                                                1999
endYear                                                    \N
runtimeMinutes                                             45
genres                                            Documentary
Name: 2008834, dtype: object

(9,)

tconst                tt11831540
titleType              tvEpisode
primaryTitle      Episode #1.161
originalTitle     Episode #1.161
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008835, dtype: object

(9,)

tconst                tt11831544
titleType              tvEpisode
primaryTitle      Episode #1.163
originalTitle     Episode #1.163
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008836, dtype: object

(9,)

tconst                tt11831546
titleType              tvEpisode
primaryTitle      Episode #1.162
originalTitle     Episode #1.162
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008837, dtype: object

(9,)

tconst                tt11831548
titleType              tvEpisode
primaryTitle      Episode #1.164
originalTitle     Episode #1.164
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008838, dtype: object

(9,)

tconst                                                  tt1183154
titleType                                                   short
primaryTitle      Shaw vs. Shakespeare I: The Character of Caesar
originalTitle     Shaw vs. Shakespeare I: The Character of Caesar
isAdult                                                         0
startYear                                                    1970
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                          Documentary,Short
Name: 2008839, dtype: object

(9,)

tconst                tt11831550
titleType              tvEpisode
primaryTitle      Episode #1.165
originalTitle     Episode #1.165
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008840, dtype: object

(9,)

tconst                               tt11831552
titleType                             tvEpisode
primaryTitle      Tim Mälzer vs. Christoph Kunz
originalTitle     Tim Mälzer vs. Christoph Kunz
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                              168
genres                               Reality-TV
Name: 2008841, dtype: object

(9,)

tconst                                                   tt11831554
titleType                                                 tvEpisode
primaryTitle      (REACTION) ESC 2020 - Szansa na Sukces - Kasia...
originalTitle     (REACTION) ESC 2020 - Szansa na Sukces - Kasia...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   11
genres                                                           \N
Name: 2008842, dtype: object

(9,)

tconst                             tt11831556
titleType                           tvEpisode
primaryTitle      Tim Mälzer vs. Franz Keller
originalTitle     Tim Mälzer vs. Franz Keller
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                            162
genres                             Reality-TV
Name: 2008843, dtype: object

(9,)

tconst                                                   tt11831558
titleType                                                 tvEpisode
primaryTitle      Denis Côté, La Famille Daraîche, Les Cowboys F...
originalTitle     Denis Côté, La Famille Daraîche, Les Cowboys F...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008844, dtype: object

(9,)

tconst                                tt1183155
titleType                                 video
primaryTitle      Sperma Beauty schluckt alles!
originalTitle     Sperma Beauty schluckt alles!
isAdult                                       1
startYear                                  2006
endYear                                      \N
runtimeMinutes                               83
genres                                    Adult
Name: 2008845, dtype: object

(9,)

tconst                tt11831560
titleType              tvEpisode
primaryTitle      Episode #1.166
originalTitle     Episode #1.166
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008846, dtype: object

(9,)

tconst                      tt11831562
titleType                    tvEpisode
primaryTitle             Episode #1.11
originalTitle            Episode #1.11
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008847, dtype: object

(9,)

tconst                tt11831564
titleType              tvEpisode
primaryTitle      Episode #1.167
originalTitle     Episode #1.167
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008848, dtype: object

(9,)

tconst                            tt11831566
titleType                          tvEpisode
primaryTitle      Tim Mälzer vs. Haya Molcho
originalTitle     Tim Mälzer vs. Haya Molcho
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                            Reality-TV
Name: 2008849, dtype: object

(9,)

tconst                tt11831568
titleType              tvEpisode
primaryTitle      Episode #1.168
originalTitle     Episode #1.168
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008850, dtype: object

(9,)

tconst                  tt1183156
titleType                   video
primaryTitle      Sperma überall!
originalTitle     Sperma überall!
isAdult                         1
startYear                    2005
endYear                        \N
runtimeMinutes                 74
genres                         \N
Name: 2008851, dtype: object

(9,)

tconst                tt11831570
titleType              tvEpisode
primaryTitle      Episode #1.169
originalTitle     Episode #1.169
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008852, dtype: object

(9,)

tconst                      tt11831572
titleType                    tvEpisode
primaryTitle             Episode #1.12
originalTitle            Episode #1.12
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008853, dtype: object

(9,)

tconst                tt11831574
titleType              tvEpisode
primaryTitle      Episode #1.170
originalTitle     Episode #1.170
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008854, dtype: object

(9,)

tconst               tt11831576
titleType             tvEpisode
primaryTitle      6: We're Back
originalTitle     6: We're Back
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2008855, dtype: object

(9,)

tconst                tt11831578
titleType              tvEpisode
primaryTitle      Episode #1.171
originalTitle     Episode #1.171
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008856, dtype: object

(9,)

tconst                       tt1183157
titleType                        movie
primaryTitle      Sportsfreund Lötzsch
originalTitle     Sportsfreund Lötzsch
isAdult                              0
startYear                         2007
endYear                             \N
runtimeMinutes                      85
genres                     Documentary
Name: 2008857, dtype: object

(9,)

tconst                tt11831580
titleType              tvEpisode
primaryTitle      Episode #1.172
originalTitle     Episode #1.172
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008858, dtype: object

(9,)

tconst                tt11831582
titleType              tvEpisode
primaryTitle      Episode #1.173
originalTitle     Episode #1.173
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008859, dtype: object

(9,)

tconst                tt11831584
titleType              tvEpisode
primaryTitle      Episode #1.175
originalTitle     Episode #1.175
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008860, dtype: object

(9,)

tconst                      tt11831586
titleType                    tvEpisode
primaryTitle             Episode #1.13
originalTitle            Episode #1.13
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008861, dtype: object

(9,)

tconst                tt11831588
titleType              tvEpisode
primaryTitle      Episode #1.174
originalTitle     Episode #1.174
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008862, dtype: object

(9,)

tconst              tt1183158
titleType               short
primaryTitle             Tabu
originalTitle            Tabu
isAdult                     0
startYear                2003
endYear                    \N
runtimeMinutes              7
genres            Drama,Short
Name: 2008863, dtype: object

(9,)

tconst                tt11831590
titleType              tvEpisode
primaryTitle      Episode #1.176
originalTitle     Episode #1.176
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008864, dtype: object

(9,)

tconst                tt11831592
titleType              tvEpisode
primaryTitle      Episode #1.178
originalTitle     Episode #1.178
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008865, dtype: object

(9,)

tconst                tt11831594
titleType              tvEpisode
primaryTitle      Episode #1.177
originalTitle     Episode #1.177
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008866, dtype: object

(9,)

tconst                tt11831596
titleType              tvEpisode
primaryTitle      Episode #1.179
originalTitle     Episode #1.179
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008867, dtype: object

(9,)

tconst                     tt1183159
titleType                    tvMovie
primaryTitle      Te no hira no yami
originalTitle     Te no hira no yami
isAdult                            0
startYear                       2001
endYear                           \N
runtimeMinutes                    \N
genres                            \N
Name: 2008868, dtype: object

(9,)

tconst                tt11831600
titleType              tvEpisode
primaryTitle      Episode #1.180
originalTitle     Episode #1.180
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008869, dtype: object

(9,)

tconst                      tt11831602
titleType                    tvEpisode
primaryTitle             Episode #1.14
originalTitle            Episode #1.14
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008870, dtype: object

(9,)

tconst                tt11831604
titleType              tvEpisode
primaryTitle      Episode #1.361
originalTitle     Episode #1.361
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008871, dtype: object

(9,)

tconst                      tt11831606
titleType                    tvEpisode
primaryTitle             Episode #1.15
originalTitle            Episode #1.15
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008872, dtype: object

(9,)

tconst                                 tt11831608
titleType                               tvEpisode
primaryTitle      La face cachée de l'ufologie...
originalTitle     La face cachée de l'ufologie...
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Sci-Fi
Name: 2008873, dtype: object

(9,)

tconst                             tt1183160
titleType                              video
primaryTitle      Thorsten Hitschfel - Live!
originalTitle     Thorsten Hitschfel - Live!
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            50
genres                    Comedy,Documentary
Name: 2008874, dtype: object

(9,)

tconst                tt11831610
titleType              tvEpisode
primaryTitle      Episode #1.362
originalTitle     Episode #1.362
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008875, dtype: object

(9,)

tconst                tt11831612
titleType              tvEpisode
primaryTitle      Episode #1.364
originalTitle     Episode #1.364
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008876, dtype: object

(9,)

tconst                tt11831614
titleType              tvEpisode
primaryTitle      Episode #1.363
originalTitle     Episode #1.363
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008877, dtype: object

(9,)

tconst                tt11831616
titleType              tvEpisode
primaryTitle      Episode #1.366
originalTitle     Episode #1.366
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008878, dtype: object

(9,)

tconst                tt11831618
titleType              tvEpisode
primaryTitle      Episode #1.365
originalTitle     Episode #1.365
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008879, dtype: object

(9,)

tconst                        tt1183161
titleType                         short
primaryTitle      Winter in Weiterstadt
originalTitle     Winter in Weiterstadt
isAdult                               0
startYear                          2004
endYear                              \N
runtimeMinutes                        5
genres               Comedy,Music,Short
Name: 2008880, dtype: object

(9,)

tconst                tt11831620
titleType              tvEpisode
primaryTitle      Episode #1.367
originalTitle     Episode #1.367
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008881, dtype: object

(9,)

tconst                tt11831622
titleType              tvEpisode
primaryTitle      Episode #1.368
originalTitle     Episode #1.368
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008882, dtype: object

(9,)

tconst                tt11831624
titleType              tvEpisode
primaryTitle      Episode #1.369
originalTitle     Episode #1.369
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008883, dtype: object

(9,)

tconst                      tt11831626
titleType                    tvEpisode
primaryTitle             Episode #1.16
originalTitle            Episode #1.16
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008884, dtype: object

(9,)

tconst                tt11831628
titleType              tvEpisode
primaryTitle      Episode #1.370
originalTitle     Episode #1.370
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008885, dtype: object

(9,)

tconst                  tt1183162
titleType               tvEpisode
primaryTitle      No em deixis!!!
originalTitle     No em deixis!!!
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2008886, dtype: object

(9,)

tconst                tt11831630
titleType              tvEpisode
primaryTitle      Episode #1.371
originalTitle     Episode #1.371
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008887, dtype: object

(9,)

tconst                tt11831632
titleType              tvEpisode
primaryTitle      Episode #1.372
originalTitle     Episode #1.372
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008888, dtype: object

(9,)

tconst                tt11831634
titleType              tvEpisode
primaryTitle      Episode #1.373
originalTitle     Episode #1.373
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008889, dtype: object

(9,)

tconst                      tt11831636
titleType                    tvEpisode
primaryTitle             Episode #1.17
originalTitle            Episode #1.17
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008890, dtype: object

(9,)

tconst                tt11831638
titleType              tvEpisode
primaryTitle      Episode #1.375
originalTitle     Episode #1.375
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008891, dtype: object

(9,)

tconst                     tt1183163
titleType                  tvEpisode
primaryTitle      Die gute Bewirtung
originalTitle     Die gute Bewirtung
isAdult                            0
startYear                       1974
endYear                           \N
runtimeMinutes                    \N
genres                       Musical
Name: 2008892, dtype: object

(9,)

tconst                tt11831640
titleType              tvEpisode
primaryTitle      Episode #1.374
originalTitle     Episode #1.374
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008893, dtype: object

(9,)

tconst                tt11831642
titleType              tvEpisode
primaryTitle      Episode #1.376
originalTitle     Episode #1.376
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008894, dtype: object

(9,)

tconst                tt11831644
titleType              tvEpisode
primaryTitle      Episode #11.14
originalTitle     Episode #11.14
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2008895, dtype: object

(9,)

tconst                tt11831646
titleType              tvEpisode
primaryTitle      Episode #1.377
originalTitle     Episode #1.377
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008896, dtype: object

(9,)

tconst                         tt11831648
titleType                       tvEpisode
primaryTitle      7: Archived Shenanigans
originalTitle     7: Archived Shenanigans
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                          Talk-Show
Name: 2008897, dtype: object

(9,)

tconst                     tt1183164
titleType                  tvEpisode
primaryTitle      An Grá Faoi Bhláth
originalTitle     An Grá Faoi Bhláth
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    \N
genres                        Family
Name: 2008898, dtype: object

(9,)

tconst                tt11831650
titleType              tvEpisode
primaryTitle      Episode #1.378
originalTitle     Episode #1.378
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008899, dtype: object

(9,)

tconst                      tt11831652
titleType                    tvEpisode
primaryTitle             Episode #1.18
originalTitle            Episode #1.18
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008900, dtype: object

(9,)

tconst                tt11831654
titleType              tvEpisode
primaryTitle      Episode #1.379
originalTitle     Episode #1.379
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008901, dtype: object

(9,)

tconst                tt11831656
titleType              tvEpisode
primaryTitle      Episode #1.380
originalTitle     Episode #1.380
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008902, dtype: object

(9,)

tconst                      tt11831658
titleType                    tvEpisode
primaryTitle             Episode #1.19
originalTitle            Episode #1.19
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008903, dtype: object

(9,)

tconst               tt1183165
titleType            tvEpisode
primaryTitle      An tÉalú Mór
originalTitle     An tÉalú Mór
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2008904, dtype: object

(9,)

tconst                tt11831660
titleType              tvEpisode
primaryTitle      Episode #1.161
originalTitle     Episode #1.161
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres              Comedy,Drama
Name: 2008905, dtype: object

(9,)

tconst               tt11831662
titleType                 movie
primaryTitle      Jacob A. Riis
originalTitle     Jacob A. Riis
isAdult                       0
startYear                  2021
endYear                      \N
runtimeMinutes               \N
genres                Biography
Name: 2008906, dtype: object

(9,)

tconst                      tt11831664
titleType                    tvEpisode
primaryTitle             Episode #1.20
originalTitle            Episode #1.20
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008907, dtype: object

(9,)

tconst                              tt11831666
titleType                                short
primaryTitle      Among Us (The Final Chapter)
originalTitle     Among Us (The Final Chapter)
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              10
genres                                   Short
Name: 2008908, dtype: object

(9,)

tconst                                tt11831668
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008909, dtype: object

(9,)

tconst                    tt1183166
titleType                 tvEpisode
primaryTitle      Bróna an Kling-on
originalTitle     Bróna an Kling-on
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2008910, dtype: object

(9,)

tconst                                                 tt11831670
titleType                                               tvEpisode
primaryTitle      Michèle O, Paul Daraîche, Wilfred LeBouthillier
originalTitle     Michèle O, Paul Daraîche, Wilfred LeBouthillier
isAdult                                                         0
startYear                                                    2009
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                    Musical
Name: 2008911, dtype: object

(9,)

tconst                                tt11831672
titleType                              tvEpisode
primaryTitle      Episode dated 14 February 2017
originalTitle     Episode dated 14 February 2017
isAdult                                        0
startYear                                   2017
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2008912, dtype: object

(9,)

tconst                tt11831674
titleType              tvEpisode
primaryTitle      Episode #1.121
originalTitle     Episode #1.121
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008913, dtype: object

(9,)

tconst                                 tt11831676
titleType                               tvEpisode
primaryTitle      8: Grandma's Guide to Halloween
originalTitle     8: Grandma's Guide to Halloween
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Talk-Show
Name: 2008914, dtype: object

(9,)

tconst                  tt11831678
titleType                videoGame
primaryTitle      Just Dance Wii 2
originalTitle     Just Dance Wii 2
isAdult                          0
startYear                     2012
endYear                         \N
runtimeMinutes                  \N
genres                       Music
Name: 2008915, dtype: object

(9,)

tconst              tt1183167
titleType           tvEpisode
primaryTitle      Cinder Eile
originalTitle     Cinder Eile
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes             \N
genres                 Family
Name: 2008916, dtype: object

(9,)

tconst                tt11831680
titleType              tvEpisode
primaryTitle      Episode #1.122
originalTitle     Episode #1.122
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008917, dtype: object

(9,)

tconst                tt11831682
titleType              tvEpisode
primaryTitle      Episode #1.123
originalTitle     Episode #1.123
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008918, dtype: object

(9,)

tconst                tt11831684
titleType              tvEpisode
primaryTitle      Episode #1.124
originalTitle     Episode #1.124
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008919, dtype: object

(9,)

tconst                tt11831686
titleType              tvEpisode
primaryTitle      Episode #1.126
originalTitle     Episode #1.126
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008920, dtype: object

(9,)

tconst                tt11831688
titleType                  movie
primaryTitle      Machki w'Âoued
originalTitle     Machki w'Âoued
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes               120
genres                    Comedy
Name: 2008921, dtype: object

(9,)

tconst               tt1183168
titleType            tvEpisode
primaryTitle      Gafa le Mata
originalTitle     Gafa le Mata
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2008922, dtype: object

(9,)

tconst                tt11831690
titleType              tvEpisode
primaryTitle      Episode #1.125
originalTitle     Episode #1.125
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008923, dtype: object

(9,)

tconst                tt11831692
titleType              tvEpisode
primaryTitle      Episode #1.128
originalTitle     Episode #1.128
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008924, dtype: object

(9,)

tconst                tt11831694
titleType              tvEpisode
primaryTitle      Episode #1.127
originalTitle     Episode #1.127
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008925, dtype: object

(9,)

tconst                tt11831696
titleType              tvEpisode
primaryTitle      Episode #1.129
originalTitle     Episode #1.129
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008926, dtype: object

(9,)

tconst                      tt11831698
titleType                    tvEpisode
primaryTitle             Episode #1.21
originalTitle            Episode #1.21
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008927, dtype: object

(9,)

tconst                           tt1183169
titleType                        tvEpisode
primaryTitle      To xseno einai pio glyko
originalTitle     To xseno einai pio glyko
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres                       Drama,Romance
Name: 2008928, dtype: object

(9,)

tconst                tt11831700
titleType              tvEpisode
primaryTitle      Episode #1.130
originalTitle     Episode #1.130
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008929, dtype: object

(9,)

tconst                tt11831702
titleType              tvEpisode
primaryTitle      Episode #1.131
originalTitle     Episode #1.131
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008930, dtype: object

(9,)

tconst                tt11831704
titleType              tvEpisode
primaryTitle      Episode #1.132
originalTitle     Episode #1.132
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008931, dtype: object

(9,)

tconst                tt11831706
titleType              tvEpisode
primaryTitle      Episode #1.134
originalTitle     Episode #1.134
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008932, dtype: object

(9,)

tconst                tt11831708
titleType              tvEpisode
primaryTitle      Episode #1.133
originalTitle     Episode #1.133
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008933, dtype: object

(9,)

tconst                                             tt1183170
titleType                                          tvEpisode
primaryTitle      La primera foto familiar de Sole y Juanito
originalTitle     La primera foto familiar de Sole y Juanito
isAdult                                                    0
startYear                                               2008
endYear                                                   \N
runtimeMinutes                                            \N
genres                                Action,Adventure,Drama
Name: 2008934, dtype: object

(9,)

tconst                tt11831710
titleType              tvEpisode
primaryTitle      Episode #1.135
originalTitle     Episode #1.135
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008935, dtype: object

(9,)

tconst                    tt11831712
titleType                  tvEpisode
primaryTitle      Castles in the Air
originalTitle     Castles in the Air
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                         Drama
Name: 2008936, dtype: object

(9,)

tconst                      tt11831714
titleType                    tvEpisode
primaryTitle             Episode #1.22
originalTitle            Episode #1.22
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008937, dtype: object

(9,)

tconst                tt11831716
titleType              tvEpisode
primaryTitle      Episode #1.136
originalTitle     Episode #1.136
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008938, dtype: object

(9,)

tconst                tt11831718
titleType              tvEpisode
primaryTitle      Episode #1.137
originalTitle     Episode #1.137
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008939, dtype: object

(9,)

tconst                         tt1183171
titleType                      tvEpisode
primaryTitle          Llega Doña Paquita
originalTitle         Llega Doña Paquita
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres            Action,Adventure,Drama
Name: 2008940, dtype: object

(9,)

tconst                                  tt11831720
titleType                                tvEpisode
primaryTitle      9: I Always Knew I Was a Mistake
originalTitle     9: I Always Knew I Was a Mistake
isAdult                                          0
startYear                                     2019
endYear                                         \N
runtimeMinutes                                  \N
genres                                   Talk-Show
Name: 2008941, dtype: object

(9,)

tconst                tt11831722
titleType              tvEpisode
primaryTitle      Episode #1.138
originalTitle     Episode #1.138
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008942, dtype: object

(9,)

tconst                      tt11831724
titleType                    tvEpisode
primaryTitle             Episode #1.23
originalTitle            Episode #1.23
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008943, dtype: object

(9,)

tconst                tt11831726
titleType              tvEpisode
primaryTitle      Episode #1.140
originalTitle     Episode #1.140
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008944, dtype: object

(9,)

tconst                tt11831728
titleType              tvEpisode
primaryTitle      Episode #1.139
originalTitle     Episode #1.139
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008945, dtype: object

(9,)

tconst                         tt1183172
titleType                      tvEpisode
primaryTitle                       Ratas
originalTitle                      Ratas
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres            Action,Adventure,Drama
Name: 2008946, dtype: object

(9,)

tconst                tt11831730
titleType              tvEpisode
primaryTitle      Episode #1.321
originalTitle     Episode #1.321
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008947, dtype: object

(9,)

tconst                      tt11831732
titleType                    tvEpisode
primaryTitle             Episode #1.24
originalTitle            Episode #1.24
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008948, dtype: object

(9,)

tconst                tt11831734
titleType              tvEpisode
primaryTitle      Episode #1.322
originalTitle     Episode #1.322
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008949, dtype: object

(9,)

tconst                tt11831736
titleType              tvEpisode
primaryTitle      Episode #1.324
originalTitle     Episode #1.324
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008950, dtype: object

(9,)

tconst                tt11831738
titleType              tvEpisode
primaryTitle      Episode #1.323
originalTitle     Episode #1.323
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008951, dtype: object

(9,)

tconst                                                    tt1183173
titleType                                                 tvEpisode
primaryTitle      Leistungsdruck und lasche Lehrer - Macht die S...
originalTitle     Leistungsdruck und lasche Lehrer - Macht die S...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2008952, dtype: object

(9,)

tconst                                tt11831740
titleType                              tvEpisode
primaryTitle      Episode dated 24 February 2020
originalTitle     Episode dated 24 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2008953, dtype: object

(9,)

tconst                      tt11831742
titleType                    tvEpisode
primaryTitle             Episode #1.25
originalTitle            Episode #1.25
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008954, dtype: object

(9,)

tconst                tt11831744
titleType              tvEpisode
primaryTitle      Episode #1.326
originalTitle     Episode #1.326
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008955, dtype: object

(9,)

tconst                tt11831746
titleType              tvEpisode
primaryTitle      Episode #1.325
originalTitle     Episode #1.325
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008956, dtype: object

(9,)

tconst                tt11831748
titleType              tvEpisode
primaryTitle      Episode #1.327
originalTitle     Episode #1.327
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008957, dtype: object

(9,)

tconst                       tt1183174
titleType                     tvSeries
primaryTitle             Bad Housewife
originalTitle        Bul lyang joo boo
isAdult                              0
startYear                         2005
endYear                             \N
runtimeMinutes                      30
genres            Comedy,Drama,Romance
Name: 2008958, dtype: object

(9,)

tconst                     tt11831750
titleType                   tvEpisode
primaryTitle               Cloistered
originalTitle              Cloistered
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2008959, dtype: object

(9,)

tconst                                tt11831752
titleType                              tvEpisode
primaryTitle      Episode dated 25 February 2020
originalTitle     Episode dated 25 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2008960, dtype: object

(9,)

tconst                tt11831754
titleType              tvEpisode
primaryTitle      Episode #1.328
originalTitle     Episode #1.328
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008961, dtype: object

(9,)

tconst                                                   tt11831756
titleType                                                 tvEpisode
primaryTitle      Denis Champoux, Denis Richard, Gaye Delorme, M...
originalTitle     Denis Champoux, Denis Richard, Gaye Delorme, M...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2008962, dtype: object

(9,)

tconst                tt11831758
titleType              tvEpisode
primaryTitle      Episode #1.329
originalTitle     Episode #1.329
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008963, dtype: object

(9,)

tconst                   tt1183175
titleType                tvEpisode
primaryTitle      Balders - Er Cof
originalTitle     Balders - Er Cof
isAdult                          0
startYear                       \N
endYear                         \N
runtimeMinutes                  \N
genres                Comedy,Drama
Name: 2008964, dtype: object

(9,)

tconst                    tt11831760
titleType                  tvEpisode
primaryTitle      10: Holy Matrimony
originalTitle     10: Holy Matrimony
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                     Talk-Show
Name: 2008965, dtype: object

(9,)

tconst                      tt11831762
titleType                    tvEpisode
primaryTitle             Episode #1.26
originalTitle            Episode #1.26
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008966, dtype: object

(9,)

tconst                tt11831764
titleType              tvEpisode
primaryTitle      Episode #1.330
originalTitle     Episode #1.330
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008967, dtype: object

(9,)

tconst                tt11831766
titleType              tvEpisode
primaryTitle      Episode #1.331
originalTitle     Episode #1.331
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008968, dtype: object

(9,)

tconst                tt11831768
titleType              tvEpisode
primaryTitle      Episode #1.332
originalTitle     Episode #1.332
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008969, dtype: object

(9,)

tconst               tt1183176
titleType            tvEpisode
primaryTitle           Y Craic
originalTitle          Y Craic
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2008970, dtype: object

(9,)

tconst                      tt11831770
titleType                    tvEpisode
primaryTitle             Episode #1.27
originalTitle            Episode #1.27
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008971, dtype: object

(9,)

tconst                tt11831772
titleType              tvEpisode
primaryTitle      Episode #1.333
originalTitle     Episode #1.333
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008972, dtype: object

(9,)

tconst                                tt11831774
titleType                              tvEpisode
primaryTitle      Episode dated 26 February 2020
originalTitle     Episode dated 26 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2008973, dtype: object

(9,)

tconst                tt11831776
titleType              tvEpisode
primaryTitle      Episode #1.334
originalTitle     Episode #1.334
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008974, dtype: object

(9,)

tconst                tt11831778
titleType              tvEpisode
primaryTitle      Episode #1.335
originalTitle     Episode #1.335
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008975, dtype: object

(9,)

tconst                             tt1183177
titleType                          tvEpisode
primaryTitle            Unhappily Ever After
originalTitle           Unhappily Ever After
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            23
genres            Adventure,Animation,Comedy
Name: 2008976, dtype: object

(9,)

tconst                      tt11831780
titleType                    tvEpisode
primaryTitle             Episode #1.28
originalTitle            Episode #1.28
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008977, dtype: object

(9,)

tconst                tt11831782
titleType              tvEpisode
primaryTitle      Episode #1.337
originalTitle     Episode #1.337
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008978, dtype: object

(9,)

tconst                                tt11831784
titleType                              tvEpisode
primaryTitle      Episode dated 27 February 2020
originalTitle     Episode dated 27 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2008979, dtype: object

(9,)

tconst                tt11831786
titleType              tvEpisode
primaryTitle      Episode #1.336
originalTitle     Episode #1.336
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008980, dtype: object

(9,)

tconst                                tt11831788
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2008981, dtype: object

(9,)

tconst                             tt1183178
titleType                          tvEpisode
primaryTitle      Filiation: Première partie
originalTitle     Filiation: Première partie
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            51
genres                                 Crime
Name: 2008982, dtype: object

(9,)

tconst                tt11831790
titleType              tvEpisode
primaryTitle      Episode #1.338
originalTitle     Episode #1.338
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008983, dtype: object

(9,)

tconst                tt11831792
titleType              tvEpisode
primaryTitle      Episode #1.340
originalTitle     Episode #1.340
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008984, dtype: object

(9,)

tconst                tt11831794
titleType              tvEpisode
primaryTitle      Episode #1.339
originalTitle     Episode #1.339
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008985, dtype: object

(9,)

tconst                           tt11831796
titleType                         tvEpisode
primaryTitle      The Challenge of Zaguresu
originalTitle     The Challenge of Zaguresu
isAdult                                   0
startYear                              1998
endYear                                  \N
runtimeMinutes                           \N
genres                               Sci-Fi
Name: 2008986, dtype: object

(9,)

tconst                      tt11831798
titleType                    tvEpisode
primaryTitle             Episode #1.29
originalTitle            Episode #1.29
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008987, dtype: object

(9,)

tconst                       tt1183179
titleType                    tvEpisode
primaryTitle                 Part Five
originalTitle                Part Five
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2008988, dtype: object

(9,)

tconst                tt11831800
titleType              tvEpisode
primaryTitle      Episode #1.601
originalTitle     Episode #1.601
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008989, dtype: object

(9,)

tconst                                tt11831802
titleType                              tvEpisode
primaryTitle      Episode dated 22 February 2020
originalTitle     Episode dated 22 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2008990, dtype: object

(9,)

tconst                      tt11831804
titleType                    tvEpisode
primaryTitle             Episode #1.30
originalTitle            Episode #1.30
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008991, dtype: object

(9,)

tconst                tt11831806
titleType              tvEpisode
primaryTitle      Episode #1.604
originalTitle     Episode #1.604
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008992, dtype: object

(9,)

tconst                tt11831808
titleType              tvEpisode
primaryTitle      Episode #1.602
originalTitle     Episode #1.602
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008993, dtype: object

(9,)

tconst                       tt1183180
titleType                    tvEpisode
primaryTitle                 Part Four
originalTitle                Part Four
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2008994, dtype: object

(9,)

tconst                                tt11831810
titleType                              tvEpisode
primaryTitle      Episode dated 23 February 2020
originalTitle     Episode dated 23 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                      News
Name: 2008995, dtype: object

(9,)

tconst                tt11831812
titleType              tvEpisode
primaryTitle      Episode #1.603
originalTitle     Episode #1.603
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008996, dtype: object

(9,)

tconst                      tt11831814
titleType                    tvEpisode
primaryTitle             Episode #1.31
originalTitle            Episode #1.31
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2008997, dtype: object

(9,)

tconst                tt11831816
titleType              tvEpisode
primaryTitle      Episode #1.605
originalTitle     Episode #1.605
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008998, dtype: object

(9,)

tconst                tt11831818
titleType              tvEpisode
primaryTitle      Episode #1.606
originalTitle     Episode #1.606
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2008999, dtype: object

(9,)

tconst                       tt1183181
titleType                    tvEpisode
primaryTitle                  Part One
originalTitle                 Part One
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2009000, dtype: object

(9,)

tconst                tt11831820
titleType              tvEpisode
primaryTitle      Episode #1.607
originalTitle     Episode #1.607
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009001, dtype: object

(9,)

tconst                tt11831822
titleType              tvEpisode
primaryTitle      Episode #1.609
originalTitle     Episode #1.609
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009002, dtype: object

(9,)

tconst                tt11831824
titleType              tvEpisode
primaryTitle      Episode #1.608
originalTitle     Episode #1.608
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009003, dtype: object

(9,)

tconst                               tt11831826
titleType                             tvEpisode
primaryTitle      Take Off Black MechaGodzilla!
originalTitle     Take Off Black MechaGodzilla!
isAdult                                       0
startYear                                  1998
endYear                                      \N
runtimeMinutes                               \N
genres                                   Sci-Fi
Name: 2009004, dtype: object

(9,)

tconst                      tt11831828
titleType                    tvEpisode
primaryTitle             Episode #1.32
originalTitle            Episode #1.32
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009005, dtype: object

(9,)

tconst                       tt1183182
titleType                    tvEpisode
primaryTitle                Part Seven
originalTitle               Part Seven
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2009006, dtype: object

(9,)

tconst                tt11831830
titleType              tvEpisode
primaryTitle      Episode #1.610
originalTitle     Episode #1.610
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009007, dtype: object

(9,)

tconst                tt11831832
titleType              tvEpisode
primaryTitle      Episode #1.612
originalTitle     Episode #1.612
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009008, dtype: object

(9,)

tconst                tt11831834
titleType              tvEpisode
primaryTitle      Episode #1.611
originalTitle     Episode #1.611
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009009, dtype: object

(9,)

tconst                      tt11831836
titleType                    tvEpisode
primaryTitle             Episode #1.33
originalTitle            Episode #1.33
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009010, dtype: object

(9,)

tconst                tt11831838
titleType              tvEpisode
primaryTitle      Episode #1.613
originalTitle     Episode #1.613
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009011, dtype: object

(9,)

tconst                       tt1183183
titleType                    tvEpisode
primaryTitle                  Part Six
originalTitle                 Part Six
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2009012, dtype: object

(9,)

tconst                tt11831840
titleType              tvEpisode
primaryTitle      Episode #1.614
originalTitle     Episode #1.614
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009013, dtype: object

(9,)

tconst                tt11831842
titleType              tvEpisode
primaryTitle      Episode #1.615
originalTitle     Episode #1.615
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009014, dtype: object

(9,)

tconst                                          tt11831844
titleType                                        tvEpisode
primaryTitle      Nobody Cares About The Rise Of Skywalker
originalTitle     Nobody Cares About The Rise Of Skywalker
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                           Talk-Show
Name: 2009015, dtype: object

(9,)

tconst                      tt11831846
titleType                    tvEpisode
primaryTitle             Episode #1.34
originalTitle            Episode #1.34
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009016, dtype: object

(9,)

tconst                tt11831848
titleType              tvEpisode
primaryTitle      Episode #1.617
originalTitle     Episode #1.617
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009017, dtype: object

(9,)

tconst                       tt1183184
titleType                    tvEpisode
primaryTitle                Part Three
originalTitle               Part Three
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2009018, dtype: object

(9,)

tconst                tt11831850
titleType              tvEpisode
primaryTitle      Episode #1.616
originalTitle     Episode #1.616
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009019, dtype: object

(9,)

tconst                tt11831852
titleType              tvEpisode
primaryTitle      Episode #1.618
originalTitle     Episode #1.618
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009020, dtype: object

(9,)

tconst                tt11831854
titleType              tvEpisode
primaryTitle      Episode #1.619
originalTitle     Episode #1.619
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009021, dtype: object

(9,)

tconst                tt11831858
titleType              tvEpisode
primaryTitle      Episode #1.620
originalTitle     Episode #1.620
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009022, dtype: object

(9,)

tconst                       tt1183185
titleType                    tvEpisode
primaryTitle                  Part Two
originalTitle                 Part Two
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2009023, dtype: object

(9,)

tconst                  tt11831860
titleType                tvEpisode
primaryTitle      The Duel at Dawn
originalTitle     The Duel at Dawn
isAdult                          0
startYear                     1998
endYear                         \N
runtimeMinutes                  \N
genres                      Sci-Fi
Name: 2009024, dtype: object

(9,)

tconst                      tt11831862
titleType                    tvEpisode
primaryTitle             Episode #1.35
originalTitle            Episode #1.35
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009025, dtype: object

(9,)

tconst                tt11831864
titleType              tvEpisode
primaryTitle      Episode #1.761
originalTitle     Episode #1.761
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009026, dtype: object

(9,)

tconst                tt11831866
titleType              tvEpisode
primaryTitle      Episode #1.763
originalTitle     Episode #1.763
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009027, dtype: object

(9,)

tconst                             tt11831868
titleType                           tvEpisode
primaryTitle      Who Took the Christmas Car?
originalTitle     Who Took the Christmas Car?
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                              7
genres                       Animation,Family
Name: 2009028, dtype: object

(9,)

tconst                       tt1183186
titleType                    tvEpisode
primaryTitle                  Prologue
originalTitle                 Prologue
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Mystery
Name: 2009029, dtype: object

(9,)

tconst                tt11831870
titleType              tvEpisode
primaryTitle      Episode #1.762
originalTitle     Episode #1.762
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009030, dtype: object

(9,)

tconst                tt11831872
titleType              tvEpisode
primaryTitle      Episode #1.764
originalTitle     Episode #1.764
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009031, dtype: object

(9,)

tconst                tt11831874
titleType              tvEpisode
primaryTitle      Episode #1.765
originalTitle     Episode #1.765
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009032, dtype: object

(9,)

tconst                tt11831878
titleType              tvEpisode
primaryTitle      Episode #1.766
originalTitle     Episode #1.766
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009033, dtype: object

(9,)

tconst                tt1183187
titleType             tvEpisode
primaryTitle      Der Jagdkönig
originalTitle     Der Jagdkönig
isAdult                       0
startYear                  1989
endYear                      \N
runtimeMinutes               51
genres             Drama,Family
Name: 2009034, dtype: object

(9,)

tconst                tt11831880
titleType              tvEpisode
primaryTitle      Episode #1.768
originalTitle     Episode #1.768
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009035, dtype: object

(9,)

tconst                tt11831882
titleType              tvEpisode
primaryTitle      Episode #1.767
originalTitle     Episode #1.767
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009036, dtype: object

(9,)

tconst                tt11831886
titleType              tvEpisode
primaryTitle      Episode #1.769
originalTitle     Episode #1.769
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009037, dtype: object

(9,)

tconst                tt11831888
titleType              tvEpisode
primaryTitle      Episode #1.770
originalTitle     Episode #1.770
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009038, dtype: object

(9,)

tconst                      tt1183188
titleType                   tvEpisode
primaryTitle      Fließender Übergang
originalTitle     Fließender Übergang
isAdult                             0
startYear                        1989
endYear                            \N
runtimeMinutes                     44
genres                   Drama,Family
Name: 2009039, dtype: object

(9,)

tconst                tt11831892
titleType              tvEpisode
primaryTitle      Episode #1.771
originalTitle     Episode #1.771
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009040, dtype: object

(9,)

tconst                tt11831894
titleType              tvEpisode
primaryTitle      Episode #1.772
originalTitle     Episode #1.772
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009041, dtype: object

(9,)

tconst                     tt11831896
titleType                   tvEpisode
primaryTitle      Zaguresu, a Coward!
originalTitle     Zaguresu, a Coward!
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres                         Sci-Fi
Name: 2009042, dtype: object

(9,)

tconst                      tt11831898
titleType                    tvEpisode
primaryTitle             Episode #1.36
originalTitle            Episode #1.36
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009043, dtype: object

(9,)

tconst                       tt1183189
titleType                    tvEpisode
primaryTitle           Episode #1.3323
originalTitle          Episode #1.3323
isAdult                              0
startYear                         2005
endYear                             \N
runtimeMinutes                      \N
genres            Drama,Family,Romance
Name: 2009044, dtype: object

(9,)

tconst                      tt11831900
titleType                    tvEpisode
primaryTitle             Episode #1.37
originalTitle            Episode #1.37
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009045, dtype: object

(9,)

tconst                tt11831902
titleType              tvEpisode
primaryTitle      Episode #1.773
originalTitle     Episode #1.773
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009046, dtype: object

(9,)

tconst                tt11831904
titleType              tvEpisode
primaryTitle      Episode #1.774
originalTitle     Episode #1.774
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009047, dtype: object

(9,)

tconst                                                   tt11831906
titleType                                                 tvEpisode
primaryTitle      How To Draw A Bull... SMASHING UP A COMPUTER S...
originalTitle     How To Draw A Bull... SMASHING UP A COMPUTER S...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Short
Name: 2009048, dtype: object

(9,)

tconst                tt11831908
titleType              tvEpisode
primaryTitle      Episode #1.775
originalTitle     Episode #1.775
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009049, dtype: object

(9,)

tconst               tt1183190
titleType            tvEpisode
primaryTitle      Episode #7.5
originalTitle     Episode #7.5
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2009050, dtype: object

(9,)

tconst                tt11831910
titleType              tvEpisode
primaryTitle      Episode #1.776
originalTitle     Episode #1.776
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009051, dtype: object

(9,)

tconst                      tt11831912
titleType                    tvEpisode
primaryTitle             Episode #1.38
originalTitle            Episode #1.38
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009052, dtype: object

(9,)

tconst                tt11831914
titleType              tvEpisode
primaryTitle      Episode #1.777
originalTitle     Episode #1.777
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009053, dtype: object

(9,)

tconst                        tt11831916
titleType                      tvEpisode
primaryTitle             Episode #13.136
originalTitle            Episode #13.136
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Comedy,Drama,Game-Show
Name: 2009054, dtype: object

(9,)

tconst                tt11831918
titleType              tvEpisode
primaryTitle      Episode #1.778
originalTitle     Episode #1.778
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009055, dtype: object

(9,)

tconst                            tt1183191
titleType                         tvEpisode
primaryTitle      Merénylet a színpadon II.
originalTitle     Merénylet a színpadon II.
isAdult                                   0
startYear                              1999
endYear                                  \N
runtimeMinutes                           \N
genres                   Comedy,Crime,Drama
Name: 2009056, dtype: object

(9,)

tconst                tt11831920
titleType              tvEpisode
primaryTitle      Episode #1.779
originalTitle     Episode #1.779
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009057, dtype: object

(9,)

tconst                tt11831922
titleType              tvEpisode
primaryTitle      Episode #1.780
originalTitle     Episode #1.780
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009058, dtype: object

(9,)

tconst                      tt11831924
titleType                    tvEpisode
primaryTitle             Episode #1.39
originalTitle            Episode #1.39
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009059, dtype: object

(9,)

tconst                tt11831926
titleType              tvEpisode
primaryTitle      Episode #1.981
originalTitle     Episode #1.981
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009060, dtype: object

(9,)

tconst                tt11831928
titleType              tvEpisode
primaryTitle      Episode #1.982
originalTitle     Episode #1.982
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009061, dtype: object

(9,)

tconst                             tt1183192
titleType                          tvEpisode
primaryTitle      Merénylet a színpadon III.
originalTitle     Merénylet a színpadon III.
isAdult                                    0
startYear                               1999
endYear                                   \N
runtimeMinutes                            \N
genres                    Comedy,Crime,Drama
Name: 2009062, dtype: object

(9,)

tconst                tt11831930
titleType              tvEpisode
primaryTitle      Episode #1.983
originalTitle     Episode #1.983
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009063, dtype: object

(9,)

tconst                             tt11831932
titleType                               video
primaryTitle      Flying Lotus: Ready Err Not
originalTitle     Flying Lotus: Ready Err Not
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                              3
genres               Animation,Fantasy,Horror
Name: 2009064, dtype: object

(9,)

tconst                tt11831934
titleType              tvEpisode
primaryTitle      Episode #1.984
originalTitle     Episode #1.984
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009065, dtype: object

(9,)

tconst                                                tt11831936
titleType                                              videoGame
primaryTitle      Yo-kai Watch Dance: Just Dance Special Version
originalTitle     Yo-kai Watch Dance: Just Dance Special Version
isAdult                                                        0
startYear                                                   2015
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                     Music
Name: 2009066, dtype: object

(9,)

tconst                      tt11831938
titleType                    tvEpisode
primaryTitle             Episode #1.40
originalTitle            Episode #1.40
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009067, dtype: object

(9,)

tconst                   tt1183193
titleType                tvEpisode
primaryTitle          Valami repül
originalTitle         Valami repül
isAdult                          0
startYear                     1972
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Family
Name: 2009068, dtype: object

(9,)

tconst                tt11831940
titleType              tvEpisode
primaryTitle      Episode #1.985
originalTitle     Episode #1.985
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009069, dtype: object

(9,)

tconst                     tt11831942
titleType                   tvEpisode
primaryTitle      Captive of Zaguresu
originalTitle     Captive of Zaguresu
isAdult                             0
startYear                        1998
endYear                            \N
runtimeMinutes                     \N
genres                         Sci-Fi
Name: 2009070, dtype: object

(9,)

tconst                tt11831944
titleType              tvEpisode
primaryTitle      Episode #1.986
originalTitle     Episode #1.986
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009071, dtype: object

(9,)

tconst                tt11831946
titleType              tvEpisode
primaryTitle      Episode #1.987
originalTitle     Episode #1.987
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009072, dtype: object

(9,)

tconst                      tt11831948
titleType                    tvEpisode
primaryTitle             Episode #1.41
originalTitle            Episode #1.41
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009073, dtype: object

(9,)

tconst            tt1183194
titleType          tvSeries
primaryTitle          Lukio
originalTitle         Lukio
isAdult                   0
startYear              2008
endYear                2008
runtimeMinutes           \N
genres                   \N
Name: 2009074, dtype: object

(9,)

tconst                tt11831950
titleType              tvEpisode
primaryTitle      Episode #1.988
originalTitle     Episode #1.988
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009075, dtype: object

(9,)

tconst                tt11831952
titleType              tvEpisode
primaryTitle      Episode #1.989
originalTitle     Episode #1.989
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009076, dtype: object

(9,)

tconst                tt11831954
titleType              tvEpisode
primaryTitle      Episode #1.990
originalTitle     Episode #1.990
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009077, dtype: object

(9,)

tconst                tt11831956
titleType              tvEpisode
primaryTitle      Episode #1.991
originalTitle     Episode #1.991
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009078, dtype: object

(9,)

tconst                tt11831958
titleType              tvEpisode
primaryTitle      Episode #1.992
originalTitle     Episode #1.992
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009079, dtype: object

(9,)

tconst                 tt1183195
titleType           tvMiniSeries
primaryTitle        Midnight Man
originalTitle       Midnight Man
isAdult                        0
startYear                   2008
endYear                     2008
runtimeMinutes                \N
genres            Drama,Thriller
Name: 2009080, dtype: object

(9,)

tconst                      tt11831960
titleType                    tvEpisode
primaryTitle             Episode #1.42
originalTitle            Episode #1.42
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009081, dtype: object

(9,)

tconst                tt11831962
titleType              tvEpisode
primaryTitle      Episode #1.993
originalTitle     Episode #1.993
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009082, dtype: object

(9,)

tconst                tt11831964
titleType              tvEpisode
primaryTitle      Episode #1.995
originalTitle     Episode #1.995
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009083, dtype: object

(9,)

tconst                tt11831966
titleType              tvEpisode
primaryTitle      Episode #1.994
originalTitle     Episode #1.994
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009084, dtype: object

(9,)

tconst                                                   tt11831968
titleType                                                     video
primaryTitle      Back to Back Creampie S********l School Festiv...
originalTitle     Back to Back Creampie S********l School Festiv...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                  223
genres                                                        Adult
Name: 2009085, dtype: object

(9,)

tconst                             tt1183196
titleType                          tvEpisode
primaryTitle      La face cachée d'une reine
originalTitle     La face cachée d'une reine
isAdult                                    0
startYear                               2001
endYear                                   \N
runtimeMinutes                            \N
genres                         Drama,Romance
Name: 2009086, dtype: object

(9,)

tconst                tt11831970
titleType              tvEpisode
primaryTitle      Episode #1.997
originalTitle     Episode #1.997
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009087, dtype: object

(9,)

tconst                tt11831972
titleType              tvEpisode
primaryTitle      Episode #1.996
originalTitle     Episode #1.996
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009088, dtype: object

(9,)

tconst                      tt11831974
titleType                    tvEpisode
primaryTitle             Episode #1.43
originalTitle            Episode #1.43
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009089, dtype: object

(9,)

tconst                tt11831976
titleType              tvEpisode
primaryTitle      Episode #1.999
originalTitle     Episode #1.999
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009090, dtype: object

(9,)

tconst                tt11831978
titleType              tvEpisode
primaryTitle      Episode #1.998
originalTitle     Episode #1.998
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009091, dtype: object

(9,)

tconst                         tt1183197
titleType                      tvEpisode
primaryTitle           All That Glitters
originalTitle          All That Glitters
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009092, dtype: object

(9,)

tconst                      tt11831980
titleType                    tvEpisode
primaryTitle             Episode #1.44
originalTitle            Episode #1.44
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009093, dtype: object

(9,)

tconst                                                   tt11831982
titleType                                                     short
primaryTitle      Documenting Donald: A Peoples' History of the ...
originalTitle     Documenting Donald: A Peoples' History of the ...
isAdult                                                           0
startYear                                                      2017
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Documentary,Short
Name: 2009094, dtype: object

(9,)

tconst                      tt11831984
titleType                    tvEpisode
primaryTitle             Episode #1.45
originalTitle            Episode #1.45
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009095, dtype: object

(9,)

tconst                      tt11831986
titleType                    tvEpisode
primaryTitle        The Atheist Papers
originalTitle       The Atheist Papers
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      43
genres            Comedy,Drama,Fantasy
Name: 2009096, dtype: object

(9,)

tconst                tt11831988
titleType              tvEpisode
primaryTitle      Death Together
originalTitle     Death Together
isAdult                        0
startYear                   1998
endYear                       \N
runtimeMinutes                \N
genres                    Sci-Fi
Name: 2009097, dtype: object

(9,)

tconst                                  tt1183198
titleType                               tvEpisode
primaryTitle      First Impressions Are Skin Deep
originalTitle     First Impressions Are Skin Deep
isAdult                                         0
startYear                                    1995
endYear                                        \N
runtimeMinutes                                 43
genres                     Adventure,Drama,Sci-Fi
Name: 2009098, dtype: object

(9,)

tconst              tt11831990
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              83
genres               Talk-Show
Name: 2009099, dtype: object

(9,)

tconst                 tt11831992
titleType               tvEpisode
primaryTitle      The True Intent
originalTitle     The True Intent
isAdult                         0
startYear                    1998
endYear                        \N
runtimeMinutes                 \N
genres                     Sci-Fi
Name: 2009100, dtype: object

(9,)

tconst              tt11831994
titleType            tvEpisode
primaryTitle      Ostari-blues
originalTitle     Ostari-blues
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2009101, dtype: object

(9,)

tconst               tt11831996
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009102, dtype: object

(9,)

tconst                       tt11831998
titleType                     tvEpisode
primaryTitle      A Desperate Situation
originalTitle     A Desperate Situation
isAdult                               0
startYear                          1998
endYear                              \N
runtimeMinutes                       \N
genres                           Sci-Fi
Name: 2009103, dtype: object

(9,)

tconst                  tt11832000
titleType                tvEpisode
primaryTitle      Kuolema Alpeilla
originalTitle     Kuolema Alpeilla
isAdult                          0
startYear                     2009
endYear                         \N
runtimeMinutes                  \N
genres                 Documentary
Name: 2009104, dtype: object

(9,)

tconst               tt11832002
titleType             tvEpisode
primaryTitle      Köyhät jonoon
originalTitle     Köyhät jonoon
isAdult                       0
startYear                  2009
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2009105, dtype: object

(9,)

tconst               tt11832004
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009106, dtype: object

(9,)

tconst               tt11832006
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009107, dtype: object

(9,)

tconst               tt11832008
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009108, dtype: object

(9,)

tconst                         tt1183200
titleType                      tvEpisode
primaryTitle               Gideon's Tale
originalTitle              Gideon's Tale
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009109, dtype: object

(9,)

tconst               tt11832010
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009110, dtype: object

(9,)

tconst               tt11832012
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009111, dtype: object

(9,)

tconst               tt11832014
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009112, dtype: object

(9,)

tconst               tt11832016
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009113, dtype: object

(9,)

tconst               tt11832018
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009114, dtype: object

(9,)

tconst                         tt1183201
titleType                      tvEpisode
primaryTitle             Going, Going...
originalTitle            Going, Going...
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009115, dtype: object

(9,)

tconst                  tt11832020
titleType                tvEpisode
primaryTitle      Zaguresu Praised
originalTitle     Zaguresu Praised
isAdult                          0
startYear                     1998
endYear                         \N
runtimeMinutes                  \N
genres                      Sci-Fi
Name: 2009116, dtype: object

(9,)

tconst                       tt11832022
titleType                     tvEpisode
primaryTitle      Merirosvojen rannikko
originalTitle     Merirosvojen rannikko
isAdult                               0
startYear                          2009
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2009117, dtype: object

(9,)

tconst               tt11832024
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009118, dtype: object

(9,)

tconst               tt11832026
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009119, dtype: object

(9,)

tconst               tt11832028
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009120, dtype: object

(9,)

tconst                         tt1183202
titleType                      tvEpisode
primaryTitle              He's Not Heavy
originalTitle             He's Not Heavy
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009121, dtype: object

(9,)

tconst                        tt11832030
titleType                      tvEpisode
primaryTitle      Työttömien kierrätystä
originalTitle     Työttömien kierrätystä
isAdult                                0
startYear                           2009
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2009122, dtype: object

(9,)

tconst            tt11832032
titleType              short
primaryTitle            Slow
originalTitle           Slow
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes             3
genres                 Short
Name: 2009123, dtype: object

(9,)

tconst                  tt11832034
titleType                tvEpisode
primaryTitle       The Water Wheel
originalTitle      The Water Wheel
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                   3
genres            Animation,Family
Name: 2009124, dtype: object

(9,)

tconst                     tt11832036
titleType                   tvEpisode
primaryTitle      11. We are Official
originalTitle     11. We are Official
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2009125, dtype: object

(9,)

tconst               tt11832038
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009126, dtype: object

(9,)

tconst                             tt1183203
titleType                          tvEpisode
primaryTitle      It Should Be an Englishman
originalTitle     It Should Be an Englishman
isAdult                                    0
startYear                               1995
endYear                                   \N
runtimeMinutes                            43
genres                Adventure,Drama,Sci-Fi
Name: 2009127, dtype: object

(9,)

tconst             tt11832040
titleType           tvEpisode
primaryTitle      S-etuparkki
originalTitle     S-etuparkki
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2009128, dtype: object

(9,)

tconst               tt11832042
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009129, dtype: object

(9,)

tconst               tt11832044
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009130, dtype: object

(9,)

tconst                            tt11832046
titleType                              movie
primaryTitle           PAW Patrol: The Movie
originalTitle          PAW Patrol: The Movie
isAdult                                    0
startYear                               2021
endYear                                   \N
runtimeMinutes                            86
genres            Adventure,Animation,Comedy
Name: 2009131, dtype: object

(9,)

tconst               tt11832048
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009132, dtype: object

(9,)

tconst                         tt1183204
titleType                      tvEpisode
primaryTitle                Labours Lost
originalTitle               Labours Lost
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009133, dtype: object

(9,)

tconst               tt11832050
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009134, dtype: object

(9,)

tconst               tt11832052
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009135, dtype: object

(9,)

tconst               tt11832054
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009136, dtype: object

(9,)

tconst                    tt11832056
titleType                  tvEpisode
primaryTitle      Kunnon Kela-kylvyt
originalTitle     Kunnon Kela-kylvyt
isAdult                            0
startYear                       2009
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2009137, dtype: object

(9,)

tconst                tt11832058
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2009138, dtype: object

(9,)

tconst                         tt1183205
titleType                      tvEpisode
primaryTitle        Last Rites of Spring
originalTitle       Last Rites of Spring
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009139, dtype: object

(9,)

tconst             tt11832060
titleType           tvEpisode
primaryTitle        Turha tie
originalTitle       Turha tie
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2009140, dtype: object

(9,)

tconst               tt11832062
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009141, dtype: object

(9,)

tconst              tt11832066
titleType                video
primaryTitle        Quiproquos
originalTitle       Quiproquos
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2009142, dtype: object

(9,)

tconst                                                   tt11832068
titleType                                                 tvEpisode
primaryTitle      Adam Gregory, Diane and Synthia, Loup Noir, Ma...
originalTitle     Adam Gregory, Diane and Synthia, Loup Noir, Ma...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009143, dtype: object

(9,)

tconst                         tt1183206
titleType                      tvEpisode
primaryTitle          Love Thy Neighbour
originalTitle         Love Thy Neighbour
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009144, dtype: object

(9,)

tconst                            tt11832070
titleType                          tvEpisode
primaryTitle      Maailman paras lentokenttä
originalTitle     Maailman paras lentokenttä
isAdult                                    0
startYear                               2009
endYear                                   \N
runtimeMinutes                            \N
genres                           Documentary
Name: 2009145, dtype: object

(9,)

tconst               tt11832072
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009146, dtype: object

(9,)

tconst               tt11832074
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009147, dtype: object

(9,)

tconst               tt11832076
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009148, dtype: object

(9,)

tconst                     tt11832078
titleType                   tvEpisode
primaryTitle      Sur Une Glace Mince
originalTitle     Sur Une Glace Mince
isAdult                             0
startYear                        2017
endYear                            \N
runtimeMinutes                     22
genres                    Documentary
Name: 2009149, dtype: object

(9,)

tconst                         tt1183207
titleType                      tvEpisode
primaryTitle             No One Rules Me
originalTitle            No One Rules Me
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009150, dtype: object

(9,)

tconst               tt11832080
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009151, dtype: object

(9,)

tconst               tt11832082
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009152, dtype: object

(9,)

tconst               tt11832084
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009153, dtype: object

(9,)

tconst               tt11832086
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009154, dtype: object

(9,)

tconst               tt11832088
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009155, dtype: object

(9,)

tconst                         tt1183208
titleType                      tvEpisode
primaryTitle          The Phantom's Lair
originalTitle         The Phantom's Lair
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009156, dtype: object

(9,)

tconst               tt11832090
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009157, dtype: object

(9,)

tconst                tt11832092
titleType              tvEpisode
primaryTitle      Potkujen hinta
originalTitle     Potkujen hinta
isAdult                        0
startYear                   2009
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2009158, dtype: object

(9,)

tconst              tt11832094
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              51
genres               Game-Show
Name: 2009159, dtype: object

(9,)

tconst               tt11832096
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009160, dtype: object

(9,)

tconst               tt11832098
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009161, dtype: object

(9,)

tconst                         tt1183209
titleType                      tvEpisode
primaryTitle      The Price of Vengeance
originalTitle     The Price of Vengeance
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009162, dtype: object

(9,)

tconst               tt11832100
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009163, dtype: object

(9,)

tconst               tt11832102
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009164, dtype: object

(9,)

tconst               tt11832104
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009165, dtype: object

(9,)

tconst               tt11832106
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009166, dtype: object

(9,)

tconst               tt11832108
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009167, dtype: object

(9,)

tconst                         tt1183210
titleType                      tvEpisode
primaryTitle                 The Visitor
originalTitle                The Visitor
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009168, dtype: object

(9,)

tconst               tt11832110
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009169, dtype: object

(9,)

tconst               tt11832112
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2009170, dtype: object

(9,)

tconst                tt11832114
titleType              tvEpisode
primaryTitle      Syntinen lääke
originalTitle     Syntinen lääke
isAdult                        0
startYear                   2009
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2009171, dtype: object

(9,)

tconst                tt11832116
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2009172, dtype: object

(9,)

tconst              tt11832118
titleType            tvEpisode
primaryTitle      Näkymättömät
originalTitle     Näkymättömät
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2009173, dtype: object

(9,)

tconst                         tt1183211
titleType                      tvEpisode
primaryTitle       A Pact with the Devil
originalTitle      A Pact with the Devil
isAdult                                0
startYear                           1995
endYear                               \N
runtimeMinutes                        43
genres            Adventure,Drama,Sci-Fi
Name: 2009174, dtype: object

(9,)

tconst               tt11832120
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009175, dtype: object

(9,)

tconst                        tt11832124
titleType                      tvEpisode
primaryTitle      Piilotetut puoluerahat
originalTitle     Piilotetut puoluerahat
isAdult                                0
startYear                           2009
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2009176, dtype: object

(9,)

tconst               tt11832126
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009177, dtype: object

(9,)

tconst               tt11832128
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009178, dtype: object

(9,)

tconst                          tt1183212
titleType                       tvEpisode
primaryTitle      What Are You Afraid Of?
originalTitle     What Are You Afraid Of?
isAdult                                 0
startYear                            1995
endYear                                \N
runtimeMinutes                         43
genres             Adventure,Drama,Sci-Fi
Name: 2009179, dtype: object

(9,)

tconst               tt11832130
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009180, dtype: object

(9,)

tconst               tt11832132
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009181, dtype: object

(9,)

tconst               tt11832134
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009182, dtype: object

(9,)

tconst               tt11832136
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009183, dtype: object

(9,)

tconst               tt11832138
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009184, dtype: object

(9,)

tconst              tt1183213
titleType           tvEpisode
primaryTitle       Vollrausch
originalTitle      Vollrausch
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             43
genres            Crime,Drama
Name: 2009185, dtype: object

(9,)

tconst                                   tt11832140
titleType                                 tvEpisode
primaryTitle      Haamukoulutusta ja orjakauppaa II
originalTitle     Haamukoulutusta ja orjakauppaa II
isAdult                                           0
startYear                                      2009
endYear                                          \N
runtimeMinutes                                   \N
genres                                  Documentary
Name: 2009186, dtype: object

(9,)

tconst                       tt11832142
titleType                         video
primaryTitle      Monos Moy Tin Palepsa
originalTitle     Monos Moy Tin Palepsa
isAdult                               0
startYear                          2010
endYear                              \N
runtimeMinutes                       \N
genres                            Short
Name: 2009187, dtype: object

(9,)

tconst               tt11832144
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009188, dtype: object

(9,)

tconst               tt11832146
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009189, dtype: object

(9,)

tconst               tt11832148
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009190, dtype: object

(9,)

tconst            tt1183214
titleType         tvEpisode
primaryTitle         Donald
originalTitle        Donald
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                Crime
Name: 2009191, dtype: object

(9,)

tconst               tt11832150
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009192, dtype: object

(9,)

tconst                 tt11832152
titleType               tvEpisode
primaryTitle      Ruotsin Karjala
originalTitle     Ruotsin Karjala
isAdult                         0
startYear                    2009
endYear                        \N
runtimeMinutes                 \N
genres                Documentary
Name: 2009193, dtype: object

(9,)

tconst                                                   tt11832154
titleType                                                 tvEpisode
primaryTitle      Franklyne, George Langford, Madame Moustache, ...
originalTitle     Franklyne, George Langford, Madame Moustache, ...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009194, dtype: object

(9,)

tconst               tt11832156
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009195, dtype: object

(9,)

tconst               tt11832158
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009196, dtype: object

(9,)

tconst                 tt1183215
titleType              tvEpisode
primaryTitle      Das Liebesnest
originalTitle     Das Liebesnest
isAdult                        0
startYear                   1984
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2009197, dtype: object

(9,)

tconst                tt11832160
titleType                  short
primaryTitle      Scorched Earth
originalTitle     Scorched Earth
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                15
genres                 Short,War
Name: 2009198, dtype: object

(9,)

tconst               tt11832162
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009199, dtype: object

(9,)

tconst               tt11832164
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009200, dtype: object

(9,)

tconst               tt11832166
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009201, dtype: object

(9,)

tconst               tt11832168
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009202, dtype: object

(9,)

tconst                 tt1183216
titleType              tvEpisode
primaryTitle      Die Ungekrönte
originalTitle     Die Ungekrönte
isAdult                        0
startYear                   1984
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2009203, dtype: object

(9,)

tconst               tt11832170
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009204, dtype: object

(9,)

tconst                                tt11832172
titleType                              tvEpisode
primaryTitle      Lisää rahaa Amerikan rikkaille
originalTitle     Lisää rahaa Amerikan rikkaille
isAdult                                        0
startYear                                   2009
endYear                                       \N
runtimeMinutes                                \N
genres                               Documentary
Name: 2009205, dtype: object

(9,)

tconst                tt11832174
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009206, dtype: object

(9,)

tconst                              tt11832176
titleType                            tvEpisode
primaryTitle      Lisää rahaa Suomen rikkaille
originalTitle     Lisää rahaa Suomen rikkaille
isAdult                                      0
startYear                                 2009
endYear                                     \N
runtimeMinutes                              \N
genres                             Documentary
Name: 2009207, dtype: object

(9,)

tconst               tt11832178
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009208, dtype: object

(9,)

tconst              tt1183217
titleType           tvEpisode
primaryTitle      Ewige Treue
originalTitle     Ewige Treue
isAdult                     0
startYear                1984
endYear                    \N
runtimeMinutes             \N
genres                     \N
Name: 2009209, dtype: object

(9,)

tconst                           tt11832180
titleType                         tvEpisode
primaryTitle      Koivuniemen herran kultti
originalTitle     Koivuniemen herran kultti
isAdult                                   0
startYear                              2009
endYear                                  \N
runtimeMinutes                           \N
genres                          Documentary
Name: 2009210, dtype: object

(9,)

tconst               tt11832184
titleType             tvEpisode
primaryTitle      Episode #1.42
originalTitle     Episode #1.42
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009211, dtype: object

(9,)

tconst                   tt11832186
titleType                 tvEpisode
primaryTitle      Jonotuslautakunta
originalTitle     Jonotuslautakunta
isAdult                           0
startYear                      2009
endYear                          \N
runtimeMinutes                   \N
genres                  Documentary
Name: 2009212, dtype: object

(9,)

tconst               tt11832188
titleType             tvEpisode
primaryTitle      Episode #1.44
originalTitle     Episode #1.44
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009213, dtype: object

(9,)

tconst                tt1183218
titleType             tvEpisode
primaryTitle      Heimsuchungen
originalTitle     Heimsuchungen
isAdult                       0
startYear                  1984
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2009214, dtype: object

(9,)

tconst               tt11832190
titleType             tvEpisode
primaryTitle      Episode #1.43
originalTitle     Episode #1.43
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009215, dtype: object

(9,)

tconst               tt11832192
titleType             tvEpisode
primaryTitle      Episode #1.45
originalTitle     Episode #1.45
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009216, dtype: object

(9,)

tconst               tt11832194
titleType             tvEpisode
primaryTitle      Episode #1.47
originalTitle     Episode #1.47
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009217, dtype: object

(9,)

tconst               tt11832196
titleType             tvEpisode
primaryTitle      Episode #1.46
originalTitle     Episode #1.46
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009218, dtype: object

(9,)

tconst                               tt11832198
titleType                             tvEpisode
primaryTitle      Ihmissalakuljettajan matkassa
originalTitle     Ihmissalakuljettajan matkassa
isAdult                                       0
startYear                                  2009
endYear                                      \N
runtimeMinutes                               \N
genres                              Documentary
Name: 2009219, dtype: object

(9,)

tconst                  tt1183219
titleType               tvEpisode
primaryTitle      Hutmistr - 1914
originalTitle     Hutmistr - 1914
isAdult                         0
startYear                    1986
endYear                        \N
runtimeMinutes                 \N
genres              Drama,History
Name: 2009220, dtype: object

(9,)

tconst               tt11832200
titleType             tvEpisode
primaryTitle      Episode #1.49
originalTitle     Episode #1.49
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009221, dtype: object

(9,)

tconst               tt11832202
titleType             tvEpisode
primaryTitle      Episode #1.48
originalTitle     Episode #1.48
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009222, dtype: object

(9,)

tconst             tt11832204
titleType           tvEpisode
primaryTitle        Paskalaki
originalTitle       Paskalaki
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2009223, dtype: object

(9,)

tconst               tt11832206
titleType             tvEpisode
primaryTitle      Episode #1.50
originalTitle     Episode #1.50
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009224, dtype: object

(9,)

tconst               tt11832208
titleType             tvEpisode
primaryTitle      Episode #1.51
originalTitle     Episode #1.51
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009225, dtype: object

(9,)

tconst                tt1183220
titleType             tvEpisode
primaryTitle        Jaro - 1945
originalTitle       Jaro - 1945
isAdult                       0
startYear                  1986
endYear                      \N
runtimeMinutes               \N
genres            Drama,History
Name: 2009226, dtype: object

(9,)

tconst               tt11832212
titleType             tvEpisode
primaryTitle      Episode #1.52
originalTitle     Episode #1.52
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009227, dtype: object

(9,)

tconst               tt11832214
titleType             tvEpisode
primaryTitle      Episode #1.53
originalTitle     Episode #1.53
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009228, dtype: object

(9,)

tconst               tt11832216
titleType             tvEpisode
primaryTitle      Episode #1.54
originalTitle     Episode #1.54
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009229, dtype: object

(9,)

tconst               tt11832218
titleType             tvEpisode
primaryTitle      Episode #1.55
originalTitle     Episode #1.55
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009230, dtype: object

(9,)

tconst                  tt1183221
titleType               tvEpisode
primaryTitle      Jubileum - 1957
originalTitle     Jubileum - 1957
isAdult                         0
startYear                    1986
endYear                        \N
runtimeMinutes                 \N
genres              Drama,History
Name: 2009231, dtype: object

(9,)

tconst                          tt11832220
titleType                        tvEpisode
primaryTitle      Tantrakultin pimeä puoli
originalTitle     Tantrakultin pimeä puoli
isAdult                                  0
startYear                             2009
endYear                                 \N
runtimeMinutes                          \N
genres                         Documentary
Name: 2009232, dtype: object

(9,)

tconst               tt11832222
titleType             tvEpisode
primaryTitle      Episode #1.56
originalTitle     Episode #1.56
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009233, dtype: object

(9,)

tconst               tt11832224
titleType             tvEpisode
primaryTitle      Tweede plaats
originalTitle     Tweede plaats
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres            Comedy,Family
Name: 2009234, dtype: object

(9,)

tconst               tt11832226
titleType             tvEpisode
primaryTitle      Episode #1.58
originalTitle     Episode #1.58
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009235, dtype: object

(9,)

tconst               tt11832228
titleType             tvEpisode
primaryTitle      Episode #1.57
originalTitle     Episode #1.57
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009236, dtype: object

(9,)

tconst                          tt1183222
titleType                       tvEpisode
primaryTitle      Krahulíkova vila - 1949
originalTitle     Krahulíkova vila - 1949
isAdult                                 0
startYear                            1986
endYear                                \N
runtimeMinutes                         \N
genres                      Drama,History
Name: 2009237, dtype: object

(9,)

tconst                             tt11832230
titleType                           tvEpisode
primaryTitle      Merenneito ja Nordean pojat
originalTitle     Merenneito ja Nordean pojat
isAdult                                     0
startYear                                2009
endYear                                    \N
runtimeMinutes                             \N
genres                            Documentary
Name: 2009238, dtype: object

(9,)

tconst               tt11832232
titleType             tvEpisode
primaryTitle      Episode #1.60
originalTitle     Episode #1.60
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009239, dtype: object

(9,)

tconst               tt11832234
titleType             tvEpisode
primaryTitle      Episode #1.59
originalTitle     Episode #1.59
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009240, dtype: object

(9,)

tconst                                            tt11832236
titleType                                              video
primaryTitle      Banana Moon Fall/Winter 2012-13 Collection
originalTitle     Banana Moon Fall/Winter 2012-13 Collection
isAdult                                                    0
startYear                                               2012
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                 Short
Name: 2009241, dtype: object

(9,)

tconst                      tt11832238
titleType                    tvEpisode
primaryTitle      Mikä maidossa maksaa
originalTitle     Mikä maidossa maksaa
isAdult                              0
startYear                         2009
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2009242, dtype: object

(9,)

tconst                tt1183223
titleType             tvEpisode
primaryTitle       Krize - 1931
originalTitle      Krize - 1931
isAdult                       0
startYear                  1986
endYear                      \N
runtimeMinutes               \N
genres            Drama,History
Name: 2009243, dtype: object

(9,)

tconst                tt11832240
titleType              tvEpisode
primaryTitle      Episode #1.241
originalTitle     Episode #1.241
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009244, dtype: object

(9,)

tconst                tt11832242
titleType              tvEpisode
primaryTitle      Episode #1.243
originalTitle     Episode #1.243
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009245, dtype: object

(9,)

tconst                tt11832244
titleType              tvEpisode
primaryTitle      Episode #1.242
originalTitle     Episode #1.242
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009246, dtype: object

(9,)

tconst                tt11832246
titleType              tvEpisode
primaryTitle      Episode #1.245
originalTitle     Episode #1.245
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009247, dtype: object

(9,)

tconst                tt11832248
titleType              tvEpisode
primaryTitle      Episode #1.244
originalTitle     Episode #1.244
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009248, dtype: object

(9,)

tconst                       tt1183224
titleType                    tvEpisode
primaryTitle      Nedelní smena - 1954
originalTitle     Nedelní smena - 1954
isAdult                              0
startYear                         1986
endYear                             \N
runtimeMinutes                      \N
genres                   Drama,History
Name: 2009249, dtype: object

(9,)

tconst                         tt11832250
titleType                           video
primaryTitle      PV Nova: Down the Ocean
originalTitle     PV Nova: Down the Ocean
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                          5
genres                        Music,Short
Name: 2009250, dtype: object

(9,)

tconst                         tt11832252
titleType                       tvEpisode
primaryTitle      Hehkulampun hautajaiset
originalTitle     Hehkulampun hautajaiset
isAdult                                 0
startYear                            2009
endYear                                \N
runtimeMinutes                         \N
genres                        Documentary
Name: 2009251, dtype: object

(9,)

tconst                tt11832254
titleType              tvEpisode
primaryTitle      Episode #1.246
originalTitle     Episode #1.246
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009252, dtype: object

(9,)

tconst                tt11832256
titleType              tvEpisode
primaryTitle      Episode #1.247
originalTitle     Episode #1.247
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009253, dtype: object

(9,)

tconst                tt11832258
titleType              tvEpisode
primaryTitle      Episode #1.248
originalTitle     Episode #1.248
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009254, dtype: object

(9,)

tconst                tt1183225
titleType             tvEpisode
primaryTitle      Návrat - 1918
originalTitle     Návrat - 1918
isAdult                       0
startYear                  1986
endYear                      \N
runtimeMinutes               \N
genres            Drama,History
Name: 2009255, dtype: object

(9,)

tconst                tt11832260
titleType              tvEpisode
primaryTitle      Episode #1.249
originalTitle     Episode #1.249
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009256, dtype: object

(9,)

tconst                        tt11832262
titleType                      tvEpisode
primaryTitle      Op zoek naar connectie
originalTitle     Op zoek naar connectie
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                        \N
genres                     Comedy,Family
Name: 2009257, dtype: object

(9,)

tconst             tt11832264
titleType           tvEpisode
primaryTitle      Palkattomat
originalTitle     Palkattomat
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2009258, dtype: object

(9,)

tconst                tt11832266
titleType              tvEpisode
primaryTitle      Episode #1.250
originalTitle     Episode #1.250
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009259, dtype: object

(9,)

tconst                tt11832268
titleType              tvEpisode
primaryTitle      Episode #1.251
originalTitle     Episode #1.251
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009260, dtype: object

(9,)

tconst                         tt1183226
titleType                      tvEpisode
primaryTitle      Ochranná znacka - 1952
originalTitle     Ochranná znacka - 1952
isAdult                                0
startYear                           1986
endYear                               \N
runtimeMinutes                        \N
genres                     Drama,History
Name: 2009261, dtype: object

(9,)

tconst                tt11832270
titleType              tvEpisode
primaryTitle      Episode #1.254
originalTitle     Episode #1.254
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009262, dtype: object

(9,)

tconst                tt11832272
titleType              tvEpisode
primaryTitle      Episode #1.253
originalTitle     Episode #1.253
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009263, dtype: object

(9,)

tconst                tt11832274
titleType              tvEpisode
primaryTitle      Episode #1.252
originalTitle     Episode #1.252
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009264, dtype: object

(9,)

tconst                              tt11832276
titleType                            tvEpisode
primaryTitle      Ilmastokatastrofi peruutettu
originalTitle     Ilmastokatastrofi peruutettu
isAdult                                      0
startYear                                 2009
endYear                                     \N
runtimeMinutes                              \N
genres                             Documentary
Name: 2009265, dtype: object

(9,)

tconst                tt11832278
titleType              tvEpisode
primaryTitle      Episode #1.255
originalTitle     Episode #1.255
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009266, dtype: object

(9,)

tconst                tt11832280
titleType              tvEpisode
primaryTitle      Episode #1.256
originalTitle     Episode #1.256
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009267, dtype: object

(9,)

tconst               tt11832282
titleType             tvEpisode
primaryTitle      Maantierosvot
originalTitle     Maantierosvot
isAdult                       0
startYear                  2009
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2009268, dtype: object

(9,)

tconst                      tt11832284
titleType                        short
primaryTitle               Left on Red
originalTitle              Left on Red
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                       5
genres            Comedy,Romance,Short
Name: 2009269, dtype: object

(9,)

tconst                tt11832286
titleType              tvEpisode
primaryTitle      Episode #1.257
originalTitle     Episode #1.257
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009270, dtype: object

(9,)

tconst                tt11832288
titleType              tvEpisode
primaryTitle      Episode #1.258
originalTitle     Episode #1.258
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009271, dtype: object

(9,)

tconst                tt1183228
titleType             tvEpisode
primaryTitle       Skrýs - 1942
originalTitle      Skrýs - 1942
isAdult                       0
startYear                  1986
endYear                      \N
runtimeMinutes               \N
genres            Drama,History
Name: 2009272, dtype: object

(9,)

tconst                     tt11832290
titleType                   tvEpisode
primaryTitle      Attraktives Angebot
originalTitle     Attraktives Angebot
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                  Drama,Romance
Name: 2009273, dtype: object

(9,)

tconst            tt11832292
titleType              video
primaryTitle             Sen
originalTitle            Sen
isAdult                    0
startYear               2016
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2009274, dtype: object

(9,)

tconst                                   tt11832294
titleType                                 tvEpisode
primaryTitle      Finanssivalvonta ja Nordean pojat
originalTitle     Finanssivalvonta ja Nordean pojat
isAdult                                           0
startYear                                      2009
endYear                                          \N
runtimeMinutes                                   \N
genres                                  Documentary
Name: 2009275, dtype: object

(9,)

tconst                tt11832296
titleType              tvEpisode
primaryTitle      Episode #1.260
originalTitle     Episode #1.260
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009276, dtype: object

(9,)

tconst                tt11832298
titleType              tvEpisode
primaryTitle      Episode #1.259
originalTitle     Episode #1.259
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009277, dtype: object

(9,)

tconst                   tt1183229
titleType                tvEpisode
primaryTitle      Stehování - 1938
originalTitle     Stehování - 1938
isAdult                          0
startYear                     1986
endYear                         \N
runtimeMinutes                  \N
genres               Drama,History
Name: 2009278, dtype: object

(9,)

tconst                              tt11832300
titleType                            tvEpisode
primaryTitle      Työpaikkojen kierrätyskeskus
originalTitle     Työpaikkojen kierrätyskeskus
isAdult                                      0
startYear                                 2009
endYear                                     \N
runtimeMinutes                              \N
genres                             Documentary
Name: 2009279, dtype: object

(9,)

tconst               tt11832302
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               40
genres                    Crime
Name: 2009280, dtype: object

(9,)

tconst             tt11832304
titleType           tvEpisode
primaryTitle      Ilmastogate
originalTitle     Ilmastogate
isAdult                     0
startYear                2009
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2009281, dtype: object

(9,)

tconst                      tt11832306
titleType                    tvEpisode
primaryTitle              Episode #1.1
originalTitle             Episode #1.1
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2009282, dtype: object

(9,)

tconst              tt11832308
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009283, dtype: object

(9,)

tconst                      tt1183230
titleType                   tvEpisode
primaryTitle      V novém dome - 1924
originalTitle     V novém dome - 1924
isAdult                             0
startYear                        1986
endYear                            \N
runtimeMinutes                     \N
genres                  Drama,History
Name: 2009284, dtype: object

(9,)

tconst              tt11832310
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009285, dtype: object

(9,)

tconst                      tt11832312
titleType                    tvEpisode
primaryTitle      Likaista jätehuoltoa
originalTitle     Likaista jätehuoltoa
isAdult                              0
startYear                         2009
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2009286, dtype: object

(9,)

tconst              tt11832314
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009287, dtype: object

(9,)

tconst              tt11832316
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009288, dtype: object

(9,)

tconst              tt11832318
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009289, dtype: object

(9,)

tconst                    tt1183231
titleType                 tvEpisode
primaryTitle      Vandrovník - 1899
originalTitle     Vandrovník - 1899
isAdult                           0
startYear                      1986
endYear                          \N
runtimeMinutes                   \N
genres                Drama,History
Name: 2009290, dtype: object

(9,)

tconst              tt11832320
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009291, dtype: object

(9,)

tconst              tt11832322
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009292, dtype: object

(9,)

tconst              tt11832324
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009293, dtype: object

(9,)

tconst               tt11832326
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009294, dtype: object

(9,)

tconst               tt11832328
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009295, dtype: object

(9,)

tconst                tt1183232
titleType             tvEpisode
primaryTitle        Voda - 1947
originalTitle       Voda - 1947
isAdult                       0
startYear                  1986
endYear                      \N
runtimeMinutes               \N
genres            Drama,History
Name: 2009296, dtype: object

(9,)

tconst                                                   tt11832330
titleType                                                 tvEpisode
primaryTitle      Antoine Gratton, Kenneth Saulnier, Mara Trembl...
originalTitle     Antoine Gratton, Kenneth Saulnier, Mara Trembl...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009297, dtype: object

(9,)

tconst               tt11832332
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009298, dtype: object

(9,)

tconst                         tt11832334
titleType                       tvEpisode
primaryTitle      La Grande Pêche D'Hiver
originalTitle     La Grande Pêche D'Hiver
isAdult                                 0
startYear                            2017
endYear                                \N
runtimeMinutes                         22
genres                        Documentary
Name: 2009299, dtype: object

(9,)

tconst               tt11832336
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009300, dtype: object

(9,)

tconst                 tt11832338
titleType               tvEpisode
primaryTitle      Les algorithmes
originalTitle     Les algorithmes
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2009301, dtype: object

(9,)

tconst                   tt1183233
titleType                tvEpisode
primaryTitle      Janette des bois
originalTitle     Janette des bois
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                      Comedy
Name: 2009302, dtype: object

(9,)

tconst               tt11832340
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009303, dtype: object

(9,)

tconst               tt11832342
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009304, dtype: object

(9,)

tconst               tt11832344
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009305, dtype: object

(9,)

tconst                     tt11832346
titleType                       movie
primaryTitle      La bataille du rail
originalTitle     La bataille du rail
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     82
genres                         Comedy
Name: 2009306, dtype: object

(9,)

tconst               tt11832348
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009307, dtype: object

(9,)

tconst                             tt1183234
titleType                          tvEpisode
primaryTitle      A Bridge Too Close: Part I
originalTitle     A Bridge Too Close: Part I
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            22
genres               Action,Animation,Family
Name: 2009308, dtype: object

(9,)

tconst               tt11832350
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009309, dtype: object

(9,)

tconst               tt11832352
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009310, dtype: object

(9,)

tconst               tt11832354
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009311, dtype: object

(9,)

tconst                                       tt11832356
titleType                                      tvSeries
primaryTitle      Instant Influencer with James Charles
originalTitle     Instant Influencer with James Charles
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                       Reality-TV
Name: 2009312, dtype: object

(9,)

tconst              tt11832358
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009313, dtype: object

(9,)

tconst                              tt1183235
titleType                           tvEpisode
primaryTitle      A Bridge Too Close: Part II
originalTitle     A Bridge Too Close: Part II
isAdult                                     0
startYear                                2008
endYear                                    \N
runtimeMinutes                             22
genres                Action,Animation,Family
Name: 2009314, dtype: object

(9,)

tconst              tt11832360
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009315, dtype: object

(9,)

tconst               tt11832362
titleType                 movie
primaryTitle       Tulip moyang
originalTitle      Tulip moyang
isAdult                       0
startYear                  2021
endYear                      \N
runtimeMinutes              118
genres            Drama,Romance
Name: 2009316, dtype: object

(9,)

tconst              tt11832364
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2009317, dtype: object

(9,)

tconst               tt11832366
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009318, dtype: object

(9,)

tconst               tt11832368
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009319, dtype: object

(9,)

tconst                          tt1183236
titleType                       tvEpisode
primaryTitle          Sari, No One's Home
originalTitle         Sari, No One's Home
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         22
genres            Action,Animation,Family
Name: 2009320, dtype: object

(9,)

tconst               tt11832370
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009321, dtype: object

(9,)

tconst               tt11832372
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009322, dtype: object

(9,)

tconst               tt11832374
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009323, dtype: object

(9,)

tconst                                                   tt11832376
titleType                                                 tvEpisode
primaryTitle      Francis Audet, Georges Hamel, Michael Pucci, P...
originalTitle     Francis Audet, Georges Hamel, Michael Pucci, P...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009324, dtype: object

(9,)

tconst                                 tt11832378
titleType                               tvEpisode
primaryTitle      Episode dated 30 September 1966
originalTitle     Episode dated 30 September 1966
isAdult                                         0
startYear                                    1966
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2009325, dtype: object

(9,)

tconst                 tt1183237
titleType           tvMiniSeries
primaryTitle      Troubleshooter
originalTitle     Troubleshooter
isAdult                        0
startYear                   1990
endYear                     2000
runtimeMinutes                \N
genres               Documentary
Name: 2009326, dtype: object

(9,)

tconst               tt11832380
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009327, dtype: object

(9,)

tconst               tt11832382
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009328, dtype: object

(9,)

tconst              tt11832384
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009329, dtype: object

(9,)

tconst              tt11832386
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009330, dtype: object

(9,)

tconst              tt11832388
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009331, dtype: object

(9,)

tconst                     tt1183238
titleType               tvMiniSeries
primaryTitle      Viimeinen koukkaus
originalTitle     Viimeinen koukkaus
isAdult                            0
startYear                       1990
endYear                         1990
runtimeMinutes                    30
genres                            \N
Name: 2009332, dtype: object

(9,)

tconst              tt11832390
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009333, dtype: object

(9,)

tconst              tt11832392
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009334, dtype: object

(9,)

tconst              tt11832396
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009335, dtype: object

(9,)

tconst               tt11832398
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009336, dtype: object

(9,)

tconst              tt1183239
titleType           tvEpisode
primaryTitle      Böses Spiel
originalTitle     Böses Spiel
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             45
genres                  Drama
Name: 2009337, dtype: object

(9,)

tconst               tt11832400
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009338, dtype: object

(9,)

tconst               tt11832402
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               40
genres                    Crime
Name: 2009339, dtype: object

(9,)

tconst                tt11832404
titleType              tvEpisode
primaryTitle      Episode #1.160
originalTitle     Episode #1.160
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009340, dtype: object

(9,)

tconst                                                   tt11832406
titleType                                                 tvEpisode
primaryTitle      Sebastian Maniscalco/Saoise Ronan/Caitriola Ba...
originalTitle     Sebastian Maniscalco/Saoise Ronan/Caitriola Ba...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2009341, dtype: object

(9,)

tconst                tt11832408
titleType              tvEpisode
primaryTitle      Episode #1.161
originalTitle     Episode #1.161
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009342, dtype: object

(9,)

tconst                       tt1183240
titleType                    tvEpisode
primaryTitle      Der Scheidungsantrag
originalTitle     Der Scheidungsantrag
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      44
genres                           Drama
Name: 2009343, dtype: object

(9,)

tconst                                tt11832410
titleType                              tvEpisode
primaryTitle      Selena Gomez/RuPaul/Matt Bomer
originalTitle     Selena Gomez/RuPaul/Matt Bomer
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009344, dtype: object

(9,)

tconst                tt11832412
titleType              tvEpisode
primaryTitle      Episode #1.162
originalTitle     Episode #1.162
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009345, dtype: object

(9,)

tconst                                            tt11832416
titleType                                          tvEpisode
primaryTitle      Tyra Banks/Christopher Jackson/Yumna Jawad
originalTitle     Tyra Banks/Christopher Jackson/Yumna Jawad
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                    \N
Name: 2009346, dtype: object

(9,)

tconst                tt11832418
titleType              tvEpisode
primaryTitle      Episode #1.163
originalTitle     Episode #1.163
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009347, dtype: object

(9,)

tconst                  tt1183241
titleType               tvEpisode
primaryTitle      Die Eisheiligen
originalTitle     Die Eisheiligen
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 47
genres                      Drama
Name: 2009348, dtype: object

(9,)

tconst                tt11832420
titleType              tvEpisode
primaryTitle      Episode #1.164
originalTitle     Episode #1.164
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009349, dtype: object

(9,)

tconst                                          tt11832422
titleType                                        tvEpisode
primaryTitle      InstaFoodie: Winter Cooking Week - Day 1
originalTitle     InstaFoodie: Winter Cooking Week - Day 1
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                                  \N
Name: 2009350, dtype: object

(9,)

tconst                tt11832424
titleType              tvEpisode
primaryTitle      Episode #1.165
originalTitle     Episode #1.165
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009351, dtype: object

(9,)

tconst                                          tt11832426
titleType                                        tvEpisode
primaryTitle      InstaFoodie: Winter Cooking Week - Day 2
originalTitle     InstaFoodie: Winter Cooking Week - Day 2
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                                  \N
Name: 2009352, dtype: object

(9,)

tconst                tt11832428
titleType              tvEpisode
primaryTitle      Episode #1.167
originalTitle     Episode #1.167
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009353, dtype: object

(9,)

tconst                  tt1183242
titleType               tvEpisode
primaryTitle      Über die Grenze
originalTitle     Über die Grenze
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 42
genres                      Drama
Name: 2009354, dtype: object

(9,)

tconst                                          tt11832430
titleType                                        tvEpisode
primaryTitle      InstaFoodie: Winter Cooking Week - Day 3
originalTitle     InstaFoodie: Winter Cooking Week - Day 3
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                                  \N
Name: 2009355, dtype: object

(9,)

tconst                tt11832432
titleType              tvEpisode
primaryTitle      Episode #1.166
originalTitle     Episode #1.166
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009356, dtype: object

(9,)

tconst                tt11832434
titleType              tvEpisode
primaryTitle      Episode #1.168
originalTitle     Episode #1.168
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009357, dtype: object

(9,)

tconst                             tt11832436
titleType                           tvEpisode
primaryTitle      Juliette Lewis/Nik Wallenda
originalTitle     Juliette Lewis/Nik Wallenda
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2009358, dtype: object

(9,)

tconst                tt11832438
titleType              tvEpisode
primaryTitle      Episode #1.170
originalTitle     Episode #1.170
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009359, dtype: object

(9,)

tconst                tt11832440
titleType              tvEpisode
primaryTitle      Episode #1.169
originalTitle     Episode #1.169
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009360, dtype: object

(9,)

tconst                tt11832442
titleType              tvEpisode
primaryTitle      Episode #1.171
originalTitle     Episode #1.171
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009361, dtype: object

(9,)

tconst                tt11832444
titleType              tvEpisode
primaryTitle      Episode #1.172
originalTitle     Episode #1.172
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009362, dtype: object

(9,)

tconst                tt11832446
titleType              tvEpisode
primaryTitle      Episode #1.174
originalTitle     Episode #1.174
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009363, dtype: object

(9,)

tconst                tt11832448
titleType              tvEpisode
primaryTitle      Episode #1.173
originalTitle     Episode #1.173
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009364, dtype: object

(9,)

tconst                                    tt1183244
titleType                                     short
primaryTitle      The Adventures of Sandy MacGregor
originalTitle     The Adventures of Sandy MacGregor
isAdult                                           0
startYear                                      1904
endYear                                          \N
runtimeMinutes                                   \N
genres                                 Comedy,Short
Name: 2009365, dtype: object

(9,)

tconst                tt11832450
titleType              tvEpisode
primaryTitle      Episode #1.175
originalTitle     Episode #1.175
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009366, dtype: object

(9,)

tconst                tt11832452
titleType              tvEpisode
primaryTitle      Episode #1.176
originalTitle     Episode #1.176
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009367, dtype: object

(9,)

tconst                tt11832454
titleType              tvEpisode
primaryTitle      Episode #1.179
originalTitle     Episode #1.179
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009368, dtype: object

(9,)

tconst                tt11832456
titleType              tvEpisode
primaryTitle      Episode #1.177
originalTitle     Episode #1.177
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009369, dtype: object

(9,)

tconst                tt11832458
titleType              tvEpisode
primaryTitle      Episode #1.178
originalTitle     Episode #1.178
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009370, dtype: object

(9,)

tconst                                        tt1183245
titleType                                     videoGame
primaryTitle      Aria the Natural: Tôi kioku no mirâju
originalTitle     Aria the Natural: Tôi kioku no mirâju
isAdult                                               0
startYear                                          2006
endYear                                              \N
runtimeMinutes                                       \N
genres                                               \N
Name: 2009371, dtype: object

(9,)

tconst                tt11832460
titleType              tvEpisode
primaryTitle      Episode #1.180
originalTitle     Episode #1.180
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009372, dtype: object

(9,)

tconst                      tt11832462
titleType                    tvEpisode
primaryTitle      Scouthouse Adventure
originalTitle     Scouthouse Adventure
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      27
genres                           Sport
Name: 2009373, dtype: object

(9,)

tconst                                                   tt11832464
titleType                                                 tvEpisode
primaryTitle      Jean and Christiane, Marie-Éve Janvier, Jean-F...
originalTitle     Jean and Christiane, Marie-Éve Janvier, Jean-F...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009374, dtype: object

(9,)

tconst              tt11832466
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009375, dtype: object

(9,)

tconst                                 tt11832468
titleType                               tvEpisode
primaryTitle      Episode dated 15 September 1966
originalTitle     Episode dated 15 September 1966
isAdult                                         0
startYear                                    1966
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2009376, dtype: object

(9,)

tconst                          tt1183246
titleType                           short
primaryTitle      At Phnom Penh, Cambodia
originalTitle     At Phnom Penh, Cambodia
isAdult                                 0
startYear                            1913
endYear                                \N
runtimeMinutes                         \N
genres                  Documentary,Short
Name: 2009377, dtype: object

(9,)

tconst              tt11832470
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009378, dtype: object

(9,)

tconst                tt11832472
titleType              tvEpisode
primaryTitle      Episode #1.380
originalTitle     Episode #1.380
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009379, dtype: object

(9,)

tconst                                 tt11832474
titleType                               tvEpisode
primaryTitle      Episode dated 22 September 1966
originalTitle     Episode dated 22 September 1966
isAdult                                         0
startYear                                    1966
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2009380, dtype: object

(9,)

tconst              tt11832476
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009381, dtype: object

(9,)

tconst                        tt11832478
titleType                          movie
primaryTitle               Shape of Fate
originalTitle              Shape of Fate
isAdult                                0
startYear                             \N
endYear                               \N
runtimeMinutes                        \N
genres            Drama,Mystery,Thriller
Name: 2009382, dtype: object

(9,)

tconst               tt1183247
titleType                short
primaryTitle         Banty Tim
originalTitle        Banty Tim
isAdult                      0
startYear                 1913
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2009383, dtype: object

(9,)

tconst              tt11832480
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009384, dtype: object

(9,)

tconst              tt11832482
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009385, dtype: object

(9,)

tconst              tt11832484
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009386, dtype: object

(9,)

tconst              tt11832486
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2009387, dtype: object

(9,)

tconst              tt11832488
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009388, dtype: object

(9,)

tconst              tt11832490
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009389, dtype: object

(9,)

tconst               tt11832494
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009390, dtype: object

(9,)

tconst               tt11832496
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009391, dtype: object

(9,)

tconst               tt11832498
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009392, dtype: object

(9,)

tconst                                 tt1183249
titleType                                  short
primaryTitle      Beautiful Angkor-Wat, Cambodia
originalTitle     Beautiful Angkor-Wat, Cambodia
isAdult                                        0
startYear                                   1913
endYear                                       \N
runtimeMinutes                                \N
genres                         Documentary,Short
Name: 2009393, dtype: object

(9,)

tconst               tt11832500
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009394, dtype: object

(9,)

tconst                tt11832502
titleType              tvEpisode
primaryTitle      Episode #1.122
originalTitle     Episode #1.122
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                   Romance
Name: 2009395, dtype: object

(9,)

tconst               tt11832504
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009396, dtype: object

(9,)

tconst               tt11832506
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009397, dtype: object

(9,)

tconst               tt11832508
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009398, dtype: object

(9,)

tconst                 tt1183250
titleType                  short
primaryTitle      Between Dances
originalTitle     Between Dances
isAdult                        0
startYear                   1913
endYear                       \N
runtimeMinutes                 6
genres              Comedy,Short
Name: 2009399, dtype: object

(9,)

tconst               tt11832510
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009400, dtype: object

(9,)

tconst              tt11832512
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009401, dtype: object

(9,)

tconst                                                   tt11832514
titleType                                                 tvEpisode
primaryTitle      Bourbon Gautier, Les Fabuleux Élégants, Mario ...
originalTitle     Bourbon Gautier, Les Fabuleux Élégants, Mario ...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009402, dtype: object

(9,)

tconst                      tt11832516
titleType                    tvEpisode
primaryTitle                      2605
originalTitle                     2605
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2009403, dtype: object

(9,)

tconst               tt11832518
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009404, dtype: object

(9,)

tconst                            tt1183251
titleType                             movie
primaryTitle      Beyond a Reasonable Doubt
originalTitle     Beyond a Reasonable Doubt
isAdult                                   0
startYear                              2009
endYear                                  \N
runtimeMinutes                          106
genres                  Crime,Drama,Mystery
Name: 2009405, dtype: object

(9,)

tconst               tt11832520
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009406, dtype: object

(9,)

tconst               tt11832522
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009407, dtype: object

(9,)

tconst                                tt11832524
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009408, dtype: object

(9,)

tconst              tt11832526
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009409, dtype: object

(9,)

tconst              tt11832528
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009410, dtype: object

(9,)

tconst               tt1183252
titleType                movie
primaryTitle         Chocolate
originalTitle        Chocolate
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes             110
genres            Action,Drama
Name: 2009411, dtype: object

(9,)

tconst              tt11832530
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009412, dtype: object

(9,)

tconst              tt11832532
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009413, dtype: object

(9,)

tconst             tt11832534
titleType               short
primaryTitle          Patrick
originalTitle         Patrick
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             22
genres            Drama,Short
Name: 2009414, dtype: object

(9,)

tconst                   tt11832536
titleType                     short
primaryTitle      Emily at the Park
originalTitle     Emily at the Park
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                    7
genres                  Drama,Short
Name: 2009415, dtype: object

(9,)

tconst                            tt11832538
titleType                          tvEpisode
primaryTitle      Episode dated 4 April 2017
originalTitle     Episode dated 4 April 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2009416, dtype: object

(9,)

tconst                  tt1183253
titleType                   short
primaryTitle      A College Cupid
originalTitle     A College Cupid
isAdult                         0
startYear                    1913
endYear                        \N
runtimeMinutes                 \N
genres               Comedy,Short
Name: 2009417, dtype: object

(9,)

tconst                            tt11832540
titleType                          tvEpisode
primaryTitle      Episode dated 5 April 2017
originalTitle     Episode dated 5 April 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2009418, dtype: object

(9,)

tconst                                tt11832542
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009419, dtype: object

(9,)

tconst                                tt11832544
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009420, dtype: object

(9,)

tconst                                tt11832546
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009421, dtype: object

(9,)

tconst                             tt11832548
titleType                           tvEpisode
primaryTitle      Episode dated 25 April 2017
originalTitle     Episode dated 25 April 2017
isAdult                                     0
startYear                                2017
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2009422, dtype: object

(9,)

tconst                 tt1183254
titleType                  short
primaryTitle      The Death Trap
originalTitle     The Death Trap
isAdult                        0
startYear                   1913
endYear                       \N
runtimeMinutes                11
genres               Drama,Short
Name: 2009423, dtype: object

(9,)

tconst                          tt11832550
titleType                        tvEpisode
primaryTitle      Episode dated 1 May 2017
originalTitle     Episode dated 1 May 2017
isAdult                                  0
startYear                             2017
endYear                                 \N
runtimeMinutes                          \N
genres                                  \N
Name: 2009424, dtype: object

(9,)

tconst                                                   tt11832552
titleType                                                 tvEpisode
primaryTitle      Catherine Durand, Denis Richard, Etienne Drape...
originalTitle     Catherine Durand, Denis Richard, Etienne Drape...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009425, dtype: object

(9,)

tconst                            tt11832554
titleType                          tvEpisode
primaryTitle      Episode dated 31 July 2017
originalTitle     Episode dated 31 July 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2009426, dtype: object

(9,)

tconst                               tt11832556
titleType                             tvEpisode
primaryTitle      Duet, czyli recepta na milosc
originalTitle     Duet, czyli recepta na milosc
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               63
genres                                    Drama
Name: 2009427, dtype: object

(9,)

tconst                     tt1183255
titleType                      short
primaryTitle      A Desperate Chance
originalTitle     A Desperate Chance
isAdult                            0
startYear                       1914
endYear                           \N
runtimeMinutes                    11
genres                   Drama,Short
Name: 2009428, dtype: object

(9,)

tconst                                tt11832560
titleType                              tvEpisode
primaryTitle      Finesse Mitchell/Manslation #2
originalTitle     Finesse Mitchell/Manslation #2
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                        History,Music,News
Name: 2009429, dtype: object

(9,)

tconst                          tt11832562
titleType                        tvEpisode
primaryTitle      Jeff Friday/Keyshia Cole
originalTitle     Jeff Friday/Keyshia Cole
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                  History,Music,News
Name: 2009430, dtype: object

(9,)

tconst            tt11832564
titleType          tvEpisode
primaryTitle           1 - 6
originalTitle          1 - 6
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                 Crime
Name: 2009431, dtype: object

(9,)

tconst                                            tt11832566
titleType                                          tvEpisode
primaryTitle      Mike Colter/Man Crush Monday/Hotline Bling
originalTitle     Mike Colter/Man Crush Monday/Hotline Bling
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                    History,Music,News
Name: 2009432, dtype: object

(9,)

tconst                                                   tt11832568
titleType                                                 tvEpisode
primaryTitle      Jerrika Hinton/Drugstore Dupes/As a Matter of ...
originalTitle     Jerrika Hinton/Drugstore Dupes/As a Matter of ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                           History,Music,News
Name: 2009433, dtype: object

(9,)

tconst                            tt1183256
titleType                             video
primaryTitle      Durchgefickt & vollgewixt
originalTitle     Durchgefickt & vollgewixt
isAdult                                   1
startYear                              2004
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2009434, dtype: object

(9,)

tconst                  tt11832570
titleType                    short
primaryTitle      La Chambre Noire
originalTitle     La Chambre Noire
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                       Short
Name: 2009435, dtype: object

(9,)

tconst                                                   tt11832572
titleType                                                 tvEpisode
primaryTitle      Bow Wow/As a Matter of Black/Steals on The Rea...
originalTitle     Bow Wow/As a Matter of Black/Steals on The Rea...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                           History,Music,News
Name: 2009436, dtype: object

(9,)

tconst                              tt11832574
titleType                            tvEpisode
primaryTitle      Tisha Campbell/Hotline Bling
originalTitle     Tisha Campbell/Hotline Bling
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                      History,Music,News
Name: 2009437, dtype: object

(9,)

tconst                          tt11832576
titleType                        tvEpisode
primaryTitle      Storm Reid/Hotline Bling
originalTitle     Storm Reid/Hotline Bling
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                  History,Music,News
Name: 2009438, dtype: object

(9,)

tconst                  tt11832578
titleType                tvEpisode
primaryTitle      What is Tic Tock
originalTitle     What is Tic Tock
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                   Talk-Show
Name: 2009439, dtype: object

(9,)

tconst                          tt1183257
titleType                           short
primaryTitle      Eikosi dyo Protohronies
originalTitle     Eikosi dyo Protohronies
isAdult                                 0
startYear                            1978
endYear                                \N
runtimeMinutes                         11
genres                              Short
Name: 2009440, dtype: object

(9,)

tconst                    tt11832580
titleType                  tvEpisode
primaryTitle      Perilous Turquoise
originalTitle     Perilous Turquoise
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres             Animation,Mystery
Name: 2009441, dtype: object

(9,)

tconst            tt11832582
titleType              video
primaryTitle           Prand
originalTitle          Prand
isAdult                    0
startYear               2011
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2009442, dtype: object

(9,)

tconst                        tt11832584
titleType                      tvEpisode
primaryTitle      The Jade of Succession
originalTitle     The Jade of Succession
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                 Animation,Mystery
Name: 2009443, dtype: object

(9,)

tconst                tt11832586
titleType               tvSeries
primaryTitle      Brain Stormers
originalTitle     Script Masters
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2009444, dtype: object

(9,)

tconst                    tt11832588
titleType                  tvEpisode
primaryTitle            Episode #5.2
originalTitle           Episode #5.2
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009445, dtype: object

(9,)

tconst                    tt1183258
titleType                     short
primaryTitle      Elephants at Work
originalTitle     Elephants at Work
isAdult                           0
startYear                      1913
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2009446, dtype: object

(9,)

tconst                    tt11832590
titleType                  tvEpisode
primaryTitle            Episode #5.3
originalTitle           Episode #5.3
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009447, dtype: object

(9,)

tconst                    tt11832592
titleType                  tvEpisode
primaryTitle            Episode #5.5
originalTitle           Episode #5.5
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009448, dtype: object

(9,)

tconst                    tt11832594
titleType                  tvEpisode
primaryTitle            Episode #5.4
originalTitle           Episode #5.4
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009449, dtype: object

(9,)

tconst                    tt11832596
titleType                  tvEpisode
primaryTitle            Episode #5.6
originalTitle           Episode #5.6
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009450, dtype: object

(9,)

tconst                    tt11832598
titleType                  tvEpisode
primaryTitle            Episode #5.7
originalTitle           Episode #5.7
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009451, dtype: object

(9,)

tconst                         tt1183259
titleType                          short
primaryTitle      The Enemy in Our Midst
originalTitle     The Enemy in Our Midst
isAdult                                0
startYear                           1914
endYear                               \N
runtimeMinutes                        \N
genres                 Crime,Drama,Short
Name: 2009452, dtype: object

(9,)

tconst                      tt11832600
titleType                    tvEpisode
primaryTitle              Episode #1.5
originalTitle             Episode #1.5
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2009453, dtype: object

(9,)

tconst                    tt11832602
titleType                  tvEpisode
primaryTitle            Episode #5.9
originalTitle           Episode #5.9
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009454, dtype: object

(9,)

tconst                    tt11832604
titleType                  tvEpisode
primaryTitle            Episode #5.8
originalTitle           Episode #5.8
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009455, dtype: object

(9,)

tconst                    tt11832606
titleType                  tvEpisode
primaryTitle           Episode #5.10
originalTitle          Episode #5.10
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009456, dtype: object

(9,)

tconst                               tt11832608
titleType                             tvEpisode
primaryTitle      Corona - Das politische Virus
originalTitle     Corona - Das politische Virus
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                Biography
Name: 2009457, dtype: object

(9,)

tconst                 tt1183260
titleType                  short
primaryTitle      An Enemy's Aid
originalTitle     An Enemy's Aid
isAdult                        0
startYear                   1913
endYear                       \N
runtimeMinutes                11
genres               Drama,Short
Name: 2009458, dtype: object

(9,)

tconst                             tt11832610
titleType                               short
primaryTitle      First Contact Worst Contact
originalTitle     First Contact Worst Contact
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                              5
genres                           Sci-Fi,Short
Name: 2009459, dtype: object

(9,)

tconst                    tt11832612
titleType                  tvEpisode
primaryTitle           Episode #5.12
originalTitle          Episode #5.12
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009460, dtype: object

(9,)

tconst                    tt11832614
titleType                  tvEpisode
primaryTitle           Episode #5.11
originalTitle          Episode #5.11
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009461, dtype: object

(9,)

tconst                    tt11832616
titleType                  tvEpisode
primaryTitle           Episode #5.13
originalTitle          Episode #5.13
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009462, dtype: object

(9,)

tconst                    tt11832618
titleType                  tvEpisode
primaryTitle           Episode #5.14
originalTitle          Episode #5.14
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009463, dtype: object

(9,)

tconst                    tt1183261
titleType                     short
primaryTitle      The Family Record
originalTitle     The Family Record
isAdult                           0
startYear                      1914
endYear                          \N
runtimeMinutes                   \N
genres                  Drama,Short
Name: 2009464, dtype: object

(9,)

tconst                    tt11832620
titleType                  tvEpisode
primaryTitle           Episode #5.16
originalTitle          Episode #5.16
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009465, dtype: object

(9,)

tconst                    tt11832622
titleType                  tvEpisode
primaryTitle           Episode #5.15
originalTitle          Episode #5.15
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009466, dtype: object

(9,)

tconst                                tt11832624
titleType                                  movie
primaryTitle      Mark, Mary & Some Other People
originalTitle     Mark, Mary & Some Other People
isAdult                                        0
startYear                                   2021
endYear                                       \N
runtimeMinutes                                90
genres                                    Comedy
Name: 2009467, dtype: object

(9,)

tconst                    tt11832626
titleType                  tvEpisode
primaryTitle           Episode #5.18
originalTitle          Episode #5.18
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009468, dtype: object

(9,)

tconst                    tt11832628
titleType                  tvEpisode
primaryTitle           Episode #5.17
originalTitle          Episode #5.17
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009469, dtype: object

(9,)

tconst                  tt1183262
titleType                   short
primaryTitle      Father's Temper
originalTitle     Father's Temper
isAdult                         0
startYear                    1914
endYear                        \N
runtimeMinutes                  6
genres               Comedy,Short
Name: 2009470, dtype: object

(9,)

tconst                    tt11832630
titleType                  tvEpisode
primaryTitle           Episode #5.19
originalTitle          Episode #5.19
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009471, dtype: object

(9,)

tconst                     tt11832632
titleType                   tvEpisode
primaryTitle                 Wylsacom
originalTitle                Wylsacom
isAdult                             0
startYear                        2017
endYear                            \N
runtimeMinutes                     24
genres            Game-Show,Talk-Show
Name: 2009472, dtype: object

(9,)

tconst                    tt11832634
titleType                  tvEpisode
primaryTitle           Episode #5.20
originalTitle          Episode #5.20
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2009473, dtype: object

(9,)

tconst              tt11832636
titleType                short
primaryTitle       Word Choice
originalTitle      Word Choice
isAdult                      0
startYear                 2009
endYear                     \N
runtimeMinutes               5
genres            Comedy,Short
Name: 2009474, dtype: object

(9,)

tconst                tt11832638
titleType                  short
primaryTitle           Following
originalTitle          Following
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            Short,Thriller
Name: 2009475, dtype: object

(9,)

tconst            tt1183263
titleType           tvMovie
primaryTitle       Fatty 69
originalTitle      Fatty 69
isAdult                   0
startYear              1969
endYear                  \N
runtimeMinutes           50
genres            Biography
Name: 2009476, dtype: object

(9,)

tconst                tt11832640
titleType              tvEpisode
primaryTitle      Episode #1.271
originalTitle     Episode #1.271
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2009477, dtype: object

(9,)

tconst                         tt11832642
titleType                           short
primaryTitle      Christian's Second Shot
originalTitle     Christian's Second Shot
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                          8
genres                              Short
Name: 2009478, dtype: object

(9,)

tconst                          tt11832644
titleType                            video
primaryTitle      Tommy Tiernan - Bovinity
originalTitle     Tommy Tiernan - Bovinity
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres                              Comedy
Name: 2009479, dtype: object

(9,)

tconst                                                   tt11832646
titleType                                                 tvEpisode
primaryTitle      Luc de LaRochellière, Mélanie Grenier, Michel ...
originalTitle     Luc de LaRochellière, Mélanie Grenier, Michel ...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009480, dtype: object

(9,)

tconst                             tt11832648
titleType                           tvEpisode
primaryTitle      Maruti Arrives At Sutal Lok
originalTitle     Maruti Arrives At Sutal Lok
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                Fantasy
Name: 2009481, dtype: object

(9,)

tconst                                           tt1183264
titleType                                            video
primaryTitle      Fetish-Zone - Latex: Rassige Gummistuten
originalTitle     Fetish-Zone - Latex: Rassige Gummistuten
isAdult                                                  1
startYear                                             2004
endYear                                                 \N
runtimeMinutes                                          \N
genres                                               Adult
Name: 2009482, dtype: object

(9,)

tconst                           tt11832650
titleType                         tvEpisode
primaryTitle      Episode dated 29 May 2018
originalTitle     Episode dated 29 May 2018
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                 News
Name: 2009483, dtype: object

(9,)

tconst              tt11832652
titleType                short
primaryTitle          SNOWBALL
originalTitle         SNOWBALL
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2009484, dtype: object

(9,)

tconst               tt11832654
titleType             tvEpisode
primaryTitle      Dunkin' Dodge
originalTitle     Dunkin' Dodge
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Sport
Name: 2009485, dtype: object

(9,)

tconst                tt11832656
titleType              tvEpisode
primaryTitle      Episode #1.272
originalTitle     Episode #1.272
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2009486, dtype: object

(9,)

tconst                  tt11832658
titleType                tvEpisode
primaryTitle        Episode #1.970
originalTitle       Episode #1.970
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009487, dtype: object

(9,)

tconst                                 tt1183265
titleType                                  video
primaryTitle      Fetish-Zone - Latex: Toy Girls
originalTitle     Fetish-Zone - Latex: Toy Girls
isAdult                                        1
startYear                                   2005
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2009488, dtype: object

(9,)

tconst                                                   tt11832660
titleType                                                 tvEpisode
primaryTitle      Chloé Sainte-Marie, Danny Boudreau, Jim Corcor...
originalTitle     Chloé Sainte-Marie, Danny Boudreau, Jim Corcor...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009489, dtype: object

(9,)

tconst                                                   tt11832662
titleType                                                 tvEpisode
primaryTitle      Luc de LaRochellière, Mélanie Grenier, Michel ...
originalTitle     Luc de LaRochellière, Mélanie Grenier, Michel ...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009490, dtype: object

(9,)

tconst                  tt11832664
titleType                tvEpisode
primaryTitle        Episode #1.971
originalTitle       Episode #1.971
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009491, dtype: object

(9,)

tconst                   tt11832666
titleType                  tvSeries
primaryTitle      Let Go Pf My Baby
originalTitle     Let Go Pf My Baby
isAdult                           0
startYear                      2018
endYear                          \N
runtimeMinutes                   70
genres                   Reality-TV
Name: 2009492, dtype: object

(9,)

tconst                  tt11832668
titleType                tvEpisode
primaryTitle        Episode #1.972
originalTitle       Episode #1.972
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009493, dtype: object

(9,)

tconst                                   tt1183266
titleType                                    video
primaryTitle      Private Movies 30: Freestyle Sex
originalTitle     Private Movies 30: Freestyle Sex
isAdult                                          1
startYear                                     2006
endYear                                         \N
runtimeMinutes                                 115
genres                                       Adult
Name: 2009494, dtype: object

(9,)

tconst                  tt11832670
titleType                tvEpisode
primaryTitle        Episode #1.973
originalTitle       Episode #1.973
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009495, dtype: object

(9,)

tconst                  tt11832672
titleType                    video
primaryTitle      Football Focus 2
originalTitle     Football Focus 2
isAdult                          1
startYear                     2016
endYear                         \N
runtimeMinutes                 108
genres                       Adult
Name: 2009496, dtype: object

(9,)

tconst                  tt11832674
titleType                tvEpisode
primaryTitle        Episode #1.974
originalTitle       Episode #1.974
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009497, dtype: object

(9,)

tconst                  tt11832676
titleType                tvEpisode
primaryTitle        Episode #1.975
originalTitle       Episode #1.975
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009498, dtype: object

(9,)

tconst                  tt11832678
titleType                tvEpisode
primaryTitle        Episode #1.976
originalTitle       Episode #1.976
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009499, dtype: object

(9,)

tconst                                                    tt1183267
titleType                                                   tvMovie
primaryTitle      Furin chôsain Katayama Yumi: Kyôto hônô matsur...
originalTitle     Furin chôsain Katayama Yumi: Kyôto hônô matsur...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2009500, dtype: object

(9,)

tconst                  tt11832680
titleType                tvEpisode
primaryTitle        Episode #1.977
originalTitle       Episode #1.977
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009501, dtype: object

(9,)

tconst                  tt11832682
titleType                tvEpisode
primaryTitle        Episode #1.978
originalTitle       Episode #1.978
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009502, dtype: object

(9,)

tconst                  tt11832684
titleType                tvEpisode
primaryTitle        Episode #1.979
originalTitle       Episode #1.979
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009503, dtype: object

(9,)

tconst                  tt11832688
titleType                tvEpisode
primaryTitle        Episode #1.980
originalTitle       Episode #1.980
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009504, dtype: object

(9,)

tconst                        tt1183268
titleType                         short
primaryTitle      The Girl in the Middy
originalTitle     The Girl in the Middy
isAdult                               0
startYear                          1914
endYear                              \N
runtimeMinutes                       11
genres                     Comedy,Short
Name: 2009505, dtype: object

(9,)

tconst                  tt11832690
titleType                tvEpisode
primaryTitle        Episode #1.981
originalTitle       Episode #1.981
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009506, dtype: object

(9,)

tconst            tt11832692
titleType              movie
primaryTitle       Roomates!
originalTitle      Roomates!
isAdult                    0
startYear               2021
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2009507, dtype: object

(9,)

tconst                  tt11832694
titleType                tvEpisode
primaryTitle        Episode #1.982
originalTitle       Episode #1.982
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009508, dtype: object

(9,)

tconst                                            tt11832698
titleType                                              video
primaryTitle      BIG RUSSIAN BOSS feat MOLLY: Mne Nravitsya
originalTitle     BIG RUSSIAN BOSS feat MOLLY: Mne Nravitsya
isAdult                                                    0
startYear                                               2017
endYear                                                   \N
runtimeMinutes                                             2
genres                                           Music,Short
Name: 2009509, dtype: object

(9,)

tconst                                    tt1183269
titleType                                     short
primaryTitle      Growing and Gathering Cocoa Beans
originalTitle     Growing and Gathering Cocoa Beans
isAdult                                           0
startYear                                      1913
endYear                                          \N
runtimeMinutes                                    2
genres                            Documentary,Short
Name: 2009510, dtype: object

(9,)

tconst                                                 tt11832702
titleType                                                   movie
primaryTitle      They Come to America IV: Immigration & Politics
originalTitle     They Come to America IV: Immigration & Politics
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                115
genres                                                Documentary
Name: 2009511, dtype: object

(9,)

tconst                  tt11832704
titleType                tvEpisode
primaryTitle        Episode #1.983
originalTitle       Episode #1.983
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009512, dtype: object

(9,)

tconst                                                   tt11832706
titleType                                                 tvEpisode
primaryTitle      Bruce Daigrepont, Carolyne Jomphe, Danny Boudr...
originalTitle     Bruce Daigrepont, Carolyne Jomphe, Danny Boudr...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009513, dtype: object

(9,)

tconst                  tt11832708
titleType                tvEpisode
primaryTitle        Episode #1.984
originalTitle       Episode #1.984
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009514, dtype: object

(9,)

tconst                                  tt1183270
titleType                                   video
primaryTitle      Grüezi! Spritz mir in den Mund!
originalTitle     Grüezi! Spritz mir in den Mund!
isAdult                                         1
startYear                                    2008
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2009515, dtype: object

(9,)

tconst                      tt11832710
titleType                    tvEpisode
primaryTitle                      2606
originalTitle                     2606
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2009516, dtype: object

(9,)

tconst                  tt11832712
titleType                tvEpisode
primaryTitle        Episode #1.985
originalTitle       Episode #1.985
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009517, dtype: object

(9,)

tconst                  tt11832714
titleType                tvEpisode
primaryTitle        Episode #1.986
originalTitle       Episode #1.986
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009518, dtype: object

(9,)

tconst                  tt11832716
titleType                tvEpisode
primaryTitle        Episode #1.987
originalTitle       Episode #1.987
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009519, dtype: object

(9,)

tconst               tt1183271
titleType                video
primaryTitle      O gyftorokas
originalTitle     O gyftorokas
isAdult                      0
startYear                 1987
endYear                     \N
runtimeMinutes              90
genres                  Comedy
Name: 2009520, dtype: object

(9,)

tconst                  tt11832720
titleType                tvEpisode
primaryTitle        Episode #1.988
originalTitle       Episode #1.988
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009521, dtype: object

(9,)

tconst                   tt11832722
titleType                  tvSeries
primaryTitle      Let Go of My Baby
originalTitle     Let Go of My Baby
isAdult                           0
startYear                      2018
endYear                          \N
runtimeMinutes                   70
genres                   Reality-TV
Name: 2009522, dtype: object

(9,)

tconst                  tt11832724
titleType                tvEpisode
primaryTitle        Episode #1.989
originalTitle       Episode #1.989
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009523, dtype: object

(9,)

tconst                 tt11832726
titleType               tvEpisode
primaryTitle      Judge Wendy! #2
originalTitle     Judge Wendy! #2
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                         \N
Name: 2009524, dtype: object

(9,)

tconst             tt11832728
titleType           tvEpisode
primaryTitle      Luenell! #2
originalTitle     Luenell! #2
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                     \N
Name: 2009525, dtype: object

(9,)

tconst                           tt1183272
titleType                            short
primaryTitle      Her Face Was Her Fortune
originalTitle     Her Face Was Her Fortune
isAdult                                  0
startYear                             1913
endYear                                 \N
runtimeMinutes                          12
genres                        Comedy,Short
Name: 2009526, dtype: object

(9,)

tconst                     tt11832730
titleType                   tvEpisode
primaryTitle      Trendy @ Wendy! #11
originalTitle     Trendy @ Wendy! #11
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2009527, dtype: object

(9,)

tconst                  tt11832732
titleType                tvEpisode
primaryTitle        Episode #1.990
originalTitle       Episode #1.990
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009528, dtype: object

(9,)

tconst                 tt11832734
titleType               tvEpisode
primaryTitle      Tommy Davidson!
originalTitle     Tommy Davidson!
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                         \N
Name: 2009529, dtype: object

(9,)

tconst                  tt11832736
titleType                    video
primaryTitle      Spanking Vol. 58
originalTitle     Spanking Vol. 58
isAdult                          1
startYear                     2017
endYear                         \N
runtimeMinutes                  71
genres                       Adult
Name: 2009530, dtype: object

(9,)

tconst                   tt11832738
titleType                 tvEpisode
primaryTitle      Finesse Mitchell!
originalTitle     Finesse Mitchell!
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                           \N
Name: 2009531, dtype: object

(9,)

tconst                              tt1183273
titleType                           tvEpisode
primaryTitle                           Shogun
originalTitle                          Shogun
isAdult                                     0
startYear                                2008
endYear                                    \N
runtimeMinutes                             60
genres            Biography,Documentary,Drama
Name: 2009532, dtype: object

(9,)

tconst               tt11832740
titleType                 movie
primaryTitle       Mot de passe
originalTitle      Mot de passe
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres            Action,Comedy
Name: 2009533, dtype: object

(9,)

tconst                  tt11832742
titleType                tvEpisode
primaryTitle        Episode #1.991
originalTitle       Episode #1.991
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009534, dtype: object

(9,)

tconst               tt11832744
titleType             tvEpisode
primaryTitle      Eva Marcille!
originalTitle     Eva Marcille!
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2009535, dtype: object

(9,)

tconst            tt11832746
titleType          tvEpisode
primaryTitle       Hot 5! #5
originalTitle      Hot 5! #5
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2009536, dtype: object

(9,)

tconst                  tt1183274
titleType                   short
primaryTitle      His Best Friend
originalTitle     His Best Friend
isAdult                         0
startYear                    1913
endYear                        \N
runtimeMinutes                 18
genres                Drama,Short
Name: 2009537, dtype: object

(9,)

tconst                         tt11832750
titleType                           movie
primaryTitle                       Pharma
originalTitle                      Pharma
isAdult                                 0
startYear                              \N
endYear                                \N
runtimeMinutes                         \N
genres            Biography,Drama,History
Name: 2009538, dtype: object

(9,)

tconst                  tt11832752
titleType                tvEpisode
primaryTitle        Episode #1.992
originalTitle       Episode #1.992
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009539, dtype: object

(9,)

tconst                                                   tt11832754
titleType                                                 tvEpisode
primaryTitle      Claude Martel, Gervaise Cloutier, Guy Marcoux,...
originalTitle     Claude Martel, Gervaise Cloutier, Guy Marcoux,...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009540, dtype: object

(9,)

tconst                  tt11832756
titleType                tvEpisode
primaryTitle        Episode #1.993
originalTitle       Episode #1.993
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009541, dtype: object

(9,)

tconst                                tt11832758
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009542, dtype: object

(9,)

tconst                    tt1183275
titleType                     movie
primaryTitle          The Lucky Guy
originalTitle     Hong yun dang tou
isAdult                           0
startYear                      1972
endYear                          \N
runtimeMinutes                   \N
genres               Comedy,Musical
Name: 2009543, dtype: object

(9,)

tconst                  tt11832760
titleType                tvEpisode
primaryTitle        Episode #1.994
originalTitle       Episode #1.994
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009544, dtype: object

(9,)

tconst                  tt11832762
titleType                tvEpisode
primaryTitle        Episode #1.995
originalTitle       Episode #1.995
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009545, dtype: object

(9,)

tconst                 tt11832764
titleType               tvEpisode
primaryTitle      Lesley Manville
originalTitle     Lesley Manville
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 74
genres                  Talk-Show
Name: 2009546, dtype: object

(9,)

tconst                      tt11832766
titleType                        short
primaryTitle      Get Out of My Shower
originalTitle     Get Out of My Shower
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       3
genres                 Animation,Short
Name: 2009547, dtype: object

(9,)

tconst                  tt11832768
titleType                tvEpisode
primaryTitle        Episode #1.996
originalTitle       Episode #1.996
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009548, dtype: object

(9,)

tconst                tt1183276
titleType                 movie
primaryTitle          The Horde
originalTitle          La horde
isAdult                       0
startYear                  2009
endYear                      \N
runtimeMinutes               90
genres            Action,Horror
Name: 2009549, dtype: object

(9,)

tconst                   tt11832770
titleType                  tvSeries
primaryTitle      Charli Knows Best
originalTitle     Charli Knows Best
isAdult                           0
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres                   Reality-TV
Name: 2009550, dtype: object

(9,)

tconst                  tt11832774
titleType                tvEpisode
primaryTitle        Episode #1.997
originalTitle       Episode #1.997
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009551, dtype: object

(9,)

tconst                  tt11832776
titleType                tvEpisode
primaryTitle        Episode #1.998
originalTitle       Episode #1.998
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009552, dtype: object

(9,)

tconst                             tt11832778
titleType                               video
primaryTitle      Cherry Busting by WH Vol. 8
originalTitle     Cherry Busting by WH Vol. 8
isAdult                                     1
startYear                                2019
endYear                                    \N
runtimeMinutes                             66
genres                                  Adult
Name: 2009553, dtype: object

(9,)

tconst                              tt1183277
titleType                               short
primaryTitle      Hydraulic Works on the Adda
originalTitle     Hydraulic Works on the Adda
isAdult                                     0
startYear                                1913
endYear                                    \N
runtimeMinutes                              6
genres                      Documentary,Short
Name: 2009554, dtype: object

(9,)

tconst                  tt11832780
titleType                tvEpisode
primaryTitle        Episode #1.999
originalTitle       Episode #1.999
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009555, dtype: object

(9,)

tconst              tt11832782
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2016
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2009556, dtype: object

(9,)

tconst             tt11832784
titleType               short
primaryTitle        Katabasis
originalTitle       Katabasis
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2009557, dtype: object

(9,)

tconst                            tt11832786
titleType                              video
primaryTitle      Jaliet Caprana: Heartbreak
originalTitle     Jaliet Caprana: Heartbreak
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                           Music,Short
Name: 2009558, dtype: object

(9,)

tconst                                               tt11832788
titleType                                             tvEpisode
primaryTitle      S2 Episode 1 Featuring Pastor Emmanuel Barlow
originalTitle     S2 Episode 1 Featuring Pastor Emmanuel Barlow
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                Talk-Show
Name: 2009559, dtype: object

(9,)

tconst            tt1183278
titleType           tvMovie
primaryTitle           Häät
originalTitle          Häät
isAdult                   0
startYear              1969
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2009560, dtype: object

(9,)

tconst                             tt11832790
titleType                           tvEpisode
primaryTitle               Llewellyn J. Scott
originalTitle              Llewellyn J. Scott
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2009561, dtype: object

(9,)

tconst                                           tt11832792
titleType                                             movie
primaryTitle      Echoes of the Empire: Beyond Genghis Khan
originalTitle     Echoes of the Empire: Beyond Genghis Khan
isAdult                                                   0
startYear                                              2021
endYear                                                  \N
runtimeMinutes                                           \N
genres                                          Documentary
Name: 2009562, dtype: object

(9,)

tconst                            tt11832794
titleType                              video
primaryTitle      Dirty Blond: Temporary Fix
originalTitle     Dirty Blond: Temporary Fix
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                             3
genres                           Music,Short
Name: 2009563, dtype: object

(9,)

tconst                    tt11832798
titleType                  tvEpisode
primaryTitle      Party in the Salon
originalTitle     Party in the Salon
isAdult                            1
startYear                       2011
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2009564, dtype: object

(9,)

tconst                       tt1183279
titleType                        short
primaryTitle      The Jungle Samaritan
originalTitle     The Jungle Samaritan
isAdult                              0
startYear                         1914
endYear                             \N
runtimeMinutes                      \N
genres                     Drama,Short
Name: 2009565, dtype: object

(9,)

tconst                             tt11832800
titleType                           tvEpisode
primaryTitle                  Kathleen Norris
originalTitle                 Kathleen Norris
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2009566, dtype: object

(9,)

tconst                   tt11832802
titleType                 tvEpisode
primaryTitle      NFL Improvements?
originalTitle     NFL Improvements?
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   30
genres            Comedy,News,Sport
Name: 2009567, dtype: object

(9,)

tconst                         tt11832804
titleType                           movie
primaryTitle      Sainte-Croix-Les-Vaches
originalTitle     Sainte-Croix-Les-Vaches
isAdult                                 0
startYear                              \N
endYear                                \N
runtimeMinutes                         \N
genres                             Comedy
Name: 2009568, dtype: object

(9,)

tconst                   tt11832806
titleType                     short
primaryTitle           A Great Line
originalTitle          A Great Line
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   19
genres            Documentary,Short
Name: 2009569, dtype: object

(9,)

tconst                                                   tt11832808
titleType                                                 tvEpisode
primaryTitle      Bob White, Johanne Provencher, Marie-Chantal C...
originalTitle     Bob White, Johanne Provencher, Marie-Chantal C...
isAdult                                                           0
startYear                                                      2009
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009570, dtype: object

(9,)

tconst             tt1183280
titleType            tvMovie
primaryTitle      Kake 40 v.
originalTitle     Kake 40 v.
isAdult                    0
startYear               1994
endYear                   \N
runtimeMinutes            54
genres                Comedy
Name: 2009571, dtype: object

(9,)

tconst                             tt11832810
titleType                           tvEpisode
primaryTitle                    John Weber Jr
originalTitle                   John Weber Jr
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2009572, dtype: object

(9,)

tconst              tt11832812
titleType            tvEpisode
primaryTitle      Noc s háckem
originalTitle     Noc s háckem
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              57
genres            Comedy,Crime
Name: 2009573, dtype: object

(9,)

tconst                       tt11832816
titleType                     tvEpisode
primaryTitle      Atlanta Jazz Festival
originalTitle     Atlanta Jazz Festival
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2009574, dtype: object

(9,)

tconst                   tt11832818
titleType                     short
primaryTitle         The Great Line
originalTitle           Dobrá lajna
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   19
genres            Documentary,Short
Name: 2009575, dtype: object

(9,)

tconst                       tt1183281
titleType                      tvMovie
primaryTitle      Kaukana tähtien tiet
originalTitle     Kaukana tähtien tiet
isAdult                              0
startYear                         1992
endYear                             \N
runtimeMinutes                      \N
genres                          Comedy
Name: 2009576, dtype: object

(9,)

tconst                            tt11832820
titleType                          tvEpisode
primaryTitle      Looks are Deceiving Part 2
originalTitle     Looks are Deceiving Part 2
isAdult                                    0
startYear                                 \N
endYear                                   \N
runtimeMinutes                            \N
genres                            Reality-TV
Name: 2009577, dtype: object

(9,)

tconst            tt11832822
titleType          tvEpisode
primaryTitle       Elizabeth
originalTitle      Elizabeth
isAdult                    1
startYear               2003
endYear                   \N
runtimeMinutes            48
genres                 Adult
Name: 2009578, dtype: object

(9,)

tconst            tt11832824
titleType              video
primaryTitle        Bi 3Ways
originalTitle       Bi 3Ways
isAdult                    1
startYear               2019
endYear                   \N
runtimeMinutes           114
genres                 Adult
Name: 2009579, dtype: object

(9,)

tconst                          tt11832826
titleType                        tvEpisode
primaryTitle      Pin the Junk on the Hunk
originalTitle     Pin the Junk on the Hunk
isAdult                                  1
startYear                             2011
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2009580, dtype: object

(9,)

tconst                    tt11832828
titleType                  tvEpisode
primaryTitle      Fire in the Desert
originalTitle     Fire in the Desert
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    42
genres                         Crime
Name: 2009581, dtype: object

(9,)

tconst                            tt1183282
titleType                             movie
primaryTitle      Ki i Athina diamantopetra
originalTitle     Ki i Athina diamantopetra
isAdult                                   0
startYear                              1978
endYear                                  \N
runtimeMinutes                           48
genres                          Documentary
Name: 2009582, dtype: object

(9,)

tconst                                   tt11832830
titleType                                     short
primaryTitle      Stalingrad: The Commissar's House
originalTitle     Stalingrad: The Commissar's House
isAdult                                           0
startYear                                      2018
endYear                                          \N
runtimeMinutes                                   40
genres                            Documentary,Short
Name: 2009583, dtype: object

(9,)

tconst                        tt11832832
titleType                      tvEpisode
primaryTitle      Capturing the Iditarod
originalTitle     Capturing the Iditarod
isAdult                                0
startYear                           2019
endYear                               \N
runtimeMinutes                        \N
genres                       Documentary
Name: 2009584, dtype: object

(9,)

tconst                        tt11832834
titleType                          short
primaryTitle      2 Cars/1 Parking Space
originalTitle     2 Cars/1 Parking Space
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                         7
genres                       Drama,Short
Name: 2009585, dtype: object

(9,)

tconst                 tt11832836
titleType               tvEpisode
primaryTitle      Episode #1.2770
originalTitle     Episode #1.2770
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2009586, dtype: object

(9,)

tconst             tt11832838
titleType               short
primaryTitle             Ciro
originalTitle            Ciro
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2009587, dtype: object

(9,)

tconst                              tt1183283
titleType                               short
primaryTitle      The King's Move in the City
originalTitle     The King's Move in the City
isAdult                                     0
startYear                                1914
endYear                                    \N
runtimeMinutes                             \N
genres                            Drama,Short
Name: 2009588, dtype: object

(9,)

tconst                 tt11832840
titleType               tvEpisode
primaryTitle      Episode #1.2771
originalTitle     Episode #1.2771
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2009589, dtype: object

(9,)

tconst                 tt11832842
titleType               tvEpisode
primaryTitle      Episode #1.2772
originalTitle     Episode #1.2772
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2009590, dtype: object

(9,)

tconst              tt11832844
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2009591, dtype: object

(9,)

tconst                 tt11832846
titleType               tvEpisode
primaryTitle      Episode #1.2773
originalTitle     Episode #1.2773
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2009592, dtype: object

(9,)

tconst                 tt11832848
titleType               tvEpisode
primaryTitle      Episode #1.2774
originalTitle     Episode #1.2774
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2009593, dtype: object

(9,)

tconst                                           tt1183284
titleType                                          tvMovie
primaryTitle      Kita arupusu hotaka renbô satsujin jiken
originalTitle     Kita arupusu hotaka renbô satsujin jiken
isAdult                                                  0
startYear                                             2001
endYear                                                 \N
runtimeMinutes                                          \N
genres                                                  \N
Name: 2009594, dtype: object

(9,)

tconst             tt11832850
titleType               short
primaryTitle        Katabasis
originalTitle       Katabasis
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2009595, dtype: object

(9,)

tconst                                     tt11832852
titleType                                       video
primaryTitle      YoungBoy Never Broke Again: Bad Bad
originalTitle     YoungBoy Never Broke Again: Bad Bad
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                      2
genres                                    Music,Short
Name: 2009596, dtype: object

(9,)

tconst                            tt11832854
titleType                          tvEpisode
primaryTitle      Ashley's Bachlorette Party
originalTitle     Ashley's Bachlorette Party
isAdult                                    1
startYear                               2011
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2009597, dtype: object

(9,)

tconst                  tt11832856
titleType                 tvSeries
primaryTitle              Chase Me
originalTitle             Chase Me
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                 100
genres            Reality-TV,Sport
Name: 2009598, dtype: object

(9,)

tconst                            tt11832858
titleType                          tvEpisode
primaryTitle      Lauren's Bacherlorette Day
originalTitle     Lauren's Bacherlorette Day
isAdult                                    1
startYear                               2011
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2009599, dtype: object

(9,)

tconst                 tt1183285
titleType                tvMovie
primaryTitle      Die Lederköpfe
originalTitle     Die Lederköpfe
isAdult                        0
startYear                   1970
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2009600, dtype: object

(9,)

tconst                                               tt11832860
titleType                                             tvEpisode
primaryTitle      Deeper Analysis of the Grievance Studies Hoax
originalTitle     Deeper Analysis of the Grievance Studies Hoax
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                Talk-Show
Name: 2009601, dtype: object

(9,)

tconst                                         tt11832862
titleType                                       tvEpisode
primaryTitle      O brajici, sportnikih in mnjammnjamladi
originalTitle     O brajici, sportnikih in mnjammnjamladi
isAdult                                                 0
startYear                                            2015
endYear                                                \N
runtimeMinutes                                         \N
genres                                      Comedy,Family
Name: 2009602, dtype: object

(9,)

tconst            tt11832864
titleType          tvSpecial
primaryTitle      BETX Live!
originalTitle     BETX Live!
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2009603, dtype: object

(9,)

tconst                              tt11832866
titleType                            tvEpisode
primaryTitle      There is Sex in the VIP Room
originalTitle     There is Sex in the VIP Room
isAdult                                      1
startYear                                 2011
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2009604, dtype: object

(9,)

tconst                                               tt11832868
titleType                                             tvEpisode
primaryTitle      Overlooked Aspects of the Battle of the Bulge
originalTitle     Overlooked Aspects of the Battle of the Bulge
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               \N
genres                                        History,Talk-Show
Name: 2009605, dtype: object

(9,)

tconst                      tt1183286
titleType                       video
primaryTitle      Leonie - Kaliber 39
originalTitle     Leonie - Kaliber 39
isAdult                             1
startYear                        2007
endYear                            \N
runtimeMinutes                     97
genres                          Adult
Name: 2009606, dtype: object

(9,)

tconst                                           tt11832870
titleType                                         tvEpisode
primaryTitle      O ribji minljivosti, poletih in animaciji
originalTitle     O ribji minljivosti, poletih in animaciji
isAdult                                                   0
startYear                                              2015
endYear                                                  \N
runtimeMinutes                                           \N
genres                                        Comedy,Family
Name: 2009607, dtype: object

(9,)

tconst                                tt11832874
titleType                              tvEpisode
primaryTitle      Episode dated 22 February 2020
originalTitle     Episode dated 22 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009608, dtype: object

(9,)

tconst                  tt11832876
titleType                tvEpisode
primaryTitle      Art & Expression
originalTitle     Art & Expression
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                 Documentary
Name: 2009609, dtype: object

(9,)

tconst                                tt11832878
titleType                              tvEpisode
primaryTitle      Episode dated 23 February 2020
originalTitle     Episode dated 23 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009610, dtype: object

(9,)

tconst            tt1183287
titleType           tvMovie
primaryTitle      Literatur
originalTitle     Literatur
isAdult                   0
startYear              1970
endYear                  \N
runtimeMinutes           50
genres               Comedy
Name: 2009611, dtype: object

(9,)

tconst                                tt11832880
titleType                              tvEpisode
primaryTitle      Episode dated 24 February 2020
originalTitle     Episode dated 24 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009612, dtype: object

(9,)

tconst                                                tt11832884
titleType                                              tvEpisode
primaryTitle      Blou, Cayouche, Mélanie Durand, Ray Bonneville
originalTitle     Blou, Cayouche, Mélanie Durand, Ray Bonneville
isAdult                                                        0
startYear                                                   2010
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                   Musical
Name: 2009613, dtype: object

(9,)

tconst                            tt11832886
titleType                          tvEpisode
primaryTitle      9th January 2020 Late News
originalTitle     9th January 2020 Late News
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                                  News
Name: 2009614, dtype: object

(9,)

tconst                      tt11832888
titleType                        video
primaryTitle      Bi Sexual Experience
originalTitle     Bi Sexual Experience
isAdult                              1
startYear                         2019
endYear                             \N
runtimeMinutes                     123
genres                           Adult
Name: 2009615, dtype: object

(9,)

tconst                tt1183288
titleType                 short
primaryTitle      A Love of '64
originalTitle     A Love of '64
isAdult                       0
startYear                  1913
endYear                      \N
runtimeMinutes               \N
genres              Drama,Short
Name: 2009616, dtype: object

(9,)

tconst                      tt11832890
titleType                    tvEpisode
primaryTitle      On the Receiving End
originalTitle     On the Receiving End
isAdult                              1
startYear                         2020
endYear                             \N
runtimeMinutes                      35
genres                           Adult
Name: 2009617, dtype: object

(9,)

tconst                     tt11832892
titleType                tvMiniSeries
primaryTitle      Double Trouble Inc.
originalTitle     Double Trouble Inc.
isAdult                             0
startYear                        2018
endYear                            \N
runtimeMinutes                     \N
genres                         Action
Name: 2009618, dtype: object

(9,)

tconst                   tt11832894
titleType                 tvEpisode
primaryTitle            USS Olympia
originalTitle           USS Olympia
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            History,Talk-Show
Name: 2009619, dtype: object

(9,)

tconst                                tt11832896
titleType                              tvEpisode
primaryTitle      Episode dated 25 February 2020
originalTitle     Episode dated 25 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009620, dtype: object

(9,)

tconst                  tt11832898
titleType                    short
primaryTitle      Cranberry Nights
originalTitle     Cranberry Nights
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  15
genres                 Drama,Short
Name: 2009621, dtype: object

(9,)

tconst                     tt1183289
titleType                    tvMovie
primaryTitle      Lähtö ennen joulua
originalTitle     Lähtö ennen joulua
isAdult                            0
startYear                       1979
endYear                           \N
runtimeMinutes                    65
genres                         Drama
Name: 2009622, dtype: object

(9,)

tconst                     tt11832900
titleType                   tvEpisode
primaryTitle                  Species
originalTitle                 Species
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2009623, dtype: object

(9,)

tconst                                tt11832902
titleType                              tvEpisode
primaryTitle      Episode dated 26 February 2020
originalTitle     Episode dated 26 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009624, dtype: object

(9,)

tconst                                tt11832904
titleType                              tvEpisode
primaryTitle      Episode dated 27 February 2020
originalTitle     Episode dated 27 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009625, dtype: object

(9,)

tconst                      tt11832906
titleType                    tvEpisode
primaryTitle      Through the Gauntlet
originalTitle     Through the Gauntlet
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2009626, dtype: object

(9,)

tconst                                tt11832908
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                 News,Reality-TV,Talk-Show
Name: 2009627, dtype: object

(9,)

tconst                        tt1183290
titleType                         short
primaryTitle      Making of 'Mabudachi'
originalTitle     Making of 'Mabudachi'
isAdult                               0
startYear                          2002
endYear                              \N
runtimeMinutes                       \N
genres                            Short
Name: 2009628, dtype: object

(9,)

tconst                                                   tt11832910
titleType                                                 tvEpisode
primaryTitle      O crepinjah, lovljenju mack in slavnih nogomet...
originalTitle     O crepinjah, lovljenju mack in slavnih nogomet...
isAdult                                                           0
startYear                                                      2015
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2009629, dtype: object

(9,)

tconst             tt11832912
titleType           tvEpisode
primaryTitle         The Mill
originalTitle        The Mill
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             63
genres            Crime,Drama
Name: 2009630, dtype: object

(9,)

tconst                                                   tt11832914
titleType                                                 tvEpisode
primaryTitle      Irvin Blais, Manon Bédard, Nicole Dumont, Paul...
originalTitle     Irvin Blais, Manon Bédard, Nicole Dumont, Paul...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009631, dtype: object

(9,)

tconst            tt11832916
titleType              movie
primaryTitle         The Cut
originalTitle        The Cut
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                 Crime
Name: 2009632, dtype: object

(9,)

tconst               tt11832918
titleType             tvEpisode
primaryTitle      Happy Returns
originalTitle     Happy Returns
isAdult                       0
startYear                  2021
endYear                      \N
runtimeMinutes               57
genres              Crime,Drama
Name: 2009633, dtype: object

(9,)

tconst                                                    tt1183291
titleType                                                   tvMovie
primaryTitle      Manekarezaru kyaku: Fujisanroku renzoku satsuj...
originalTitle     Manekarezaru kyaku: Fujisanroku renzoku satsuj...
isAdult                                                           0
startYear                                                      2001
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2009634, dtype: object

(9,)

tconst                       tt11832920
titleType                     tvEpisode
primaryTitle      La llamada inesperada
originalTitle     La llamada inesperada
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                           Action
Name: 2009635, dtype: object

(9,)

tconst               tt11832922
titleType             tvEpisode
primaryTitle       Episode #1.1
originalTitle      Episode #1.1
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009636, dtype: object

(9,)

tconst               tt11832924
titleType             tvEpisode
primaryTitle       Episode #1.2
originalTitle      Episode #1.2
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009637, dtype: object

(9,)

tconst                                                   tt11832926
titleType                                                 tvEpisode
primaryTitle      9. The American Revolution with David Hackett ...
originalTitle     9. The American Revolution with David Hackett ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            History,Talk-Show
Name: 2009638, dtype: object

(9,)

tconst               tt11832928
titleType             tvEpisode
primaryTitle       Episode #1.3
originalTitle      Episode #1.3
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009639, dtype: object

(9,)

tconst                       tt11832930
titleType                     tvEpisode
primaryTitle      From Russia with Love
originalTitle     From Russia with Love
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                   News,Talk-Show
Name: 2009640, dtype: object

(9,)

tconst               tt11832932
titleType             tvEpisode
primaryTitle       Episode #1.4
originalTitle      Episode #1.4
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009641, dtype: object

(9,)

tconst               tt11832934
titleType             tvEpisode
primaryTitle       Episode #1.5
originalTitle      Episode #1.5
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009642, dtype: object

(9,)

tconst               tt11832936
titleType             tvEpisode
primaryTitle       Episode #1.6
originalTitle      Episode #1.6
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009643, dtype: object

(9,)

tconst                               tt11832938
titleType                             tvEpisode
primaryTitle      Episode dated 19 October 1970
originalTitle     Episode dated 19 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2009644, dtype: object

(9,)

tconst                               tt1183293
titleType                              tvMovie
primaryTitle      Mokugeki: Aru ai no hajimari
originalTitle     Mokugeki: Aru ai no hajimari
isAdult                                      0
startYear                                 2001
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2009645, dtype: object

(9,)

tconst               tt11832940
titleType             tvEpisode
primaryTitle       Episode #1.7
originalTitle      Episode #1.7
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009646, dtype: object

(9,)

tconst                                         tt11832942
titleType                                       tvEpisode
primaryTitle      O grozi, elektriki in zlomljenih kosteh
originalTitle     O grozi, elektriki in zlomljenih kosteh
isAdult                                                 0
startYear                                            2015
endYear                                                \N
runtimeMinutes                                         \N
genres                                      Comedy,Family
Name: 2009647, dtype: object

(9,)

tconst               tt11832944
titleType             tvEpisode
primaryTitle       Episode #1.8
originalTitle      Episode #1.8
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009648, dtype: object

(9,)

tconst                             tt11832946
titleType                           tvEpisode
primaryTitle      21st January 2020 Late News
originalTitle     21st January 2020 Late News
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                   News
Name: 2009649, dtype: object

(9,)

tconst               tt11832948
titleType             tvEpisode
primaryTitle       Episode #1.9
originalTitle      Episode #1.9
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009650, dtype: object

(9,)

tconst              tt1183294
titleType               short
primaryTitle       Not Wanted
originalTitle      Not Wanted
isAdult                     0
startYear                1915
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2009651, dtype: object

(9,)

tconst             tt11832950
titleType               short
primaryTitle       Just Right
originalTitle      Just Right
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2009652, dtype: object

(9,)

tconst               tt11832952
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009653, dtype: object

(9,)

tconst               tt11832954
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009654, dtype: object

(9,)

tconst               tt11832956
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009655, dtype: object

(9,)

tconst               tt11832958
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009656, dtype: object

(9,)

tconst                          tt1183295
titleType                           short
primaryTitle      On the Great Steel Beam
originalTitle     On the Great Steel Beam
isAdult                                 0
startYear                            1914
endYear                                \N
runtimeMinutes                         \N
genres                        Drama,Short
Name: 2009657, dtype: object

(9,)

tconst               tt11832960
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009658, dtype: object

(9,)

tconst               tt11832964
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009659, dtype: object

(9,)

tconst                                tt11832966
titleType                              tvEpisode
primaryTitle      Episode dated 12 February 2020
originalTitle     Episode dated 12 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2009660, dtype: object

(9,)

tconst               tt11832968
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2009661, dtype: object

(9,)

tconst                    tt1183296
titleType                     short
primaryTitle       Paigniotherapeia
originalTitle      Paigniotherapeia
isAdult                           0
startYear                      1978
endYear                          \N
runtimeMinutes                   20
genres            Documentary,Short
Name: 2009662, dtype: object

(9,)

tconst                                 tt11832970
titleType                               tvEpisode
primaryTitle      O bradlji, valcku in pitju krvi
originalTitle     O bradlji, valcku in pitju krvi
isAdult                                         0
startYear                                    2015
endYear                                        \N
runtimeMinutes                                 \N
genres                              Comedy,Family
Name: 2009663, dtype: object

(9,)

tconst                     tt11832972
titleType                       short
primaryTitle      Great Asphyxiations
originalTitle     Great Asphyxiations
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                      9
genres                   Comedy,Short
Name: 2009664, dtype: object

(9,)

tconst                  tt11832974
titleType                    movie
primaryTitle      Sisyphus at Work
originalTitle     Sisyphus at Work
isAdult                          0
startYear                     2021
endYear                         \N
runtimeMinutes                 128
genres                       Drama
Name: 2009665, dtype: object

(9,)

tconst               tt11832976
titleType                 video
primaryTitle      Bi Swingers 3
originalTitle     Bi Swingers 3
isAdult                       1
startYear                  2018
endYear                      \N
runtimeMinutes              118
genres                    Adult
Name: 2009666, dtype: object

(9,)

tconst                       tt11832978
titleType                         short
primaryTitle                    Diluted
originalTitle                   Diluted
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                        3
genres            Animation,Music,Short
Name: 2009667, dtype: object

(9,)

tconst                                  tt1183297
titleType                                   movie
primaryTitle      Pano se ena mikro elliniko nisi
originalTitle     Pano se ena mikro elliniko nisi
isAdult                                         0
startYear                                    1978
endYear                                        \N
runtimeMinutes                                 55
genres                                         \N
Name: 2009668, dtype: object

(9,)

tconst                                                   tt11832980
titleType                                                     video
primaryTitle      Arjun Kanungo, Prakriti Kakar & M Ajay Vaas: T...
originalTitle     Arjun Kanungo, Prakriti Kakar & M Ajay Vaas: T...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2009669, dtype: object

(9,)

tconst                      tt11832982
titleType                    tvEpisode
primaryTitle      PDK Peachtree Dekalb
originalTitle     PDK Peachtree Dekalb
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2009670, dtype: object

(9,)

tconst             tt11832984
titleType               video
primaryTitle            Crazy
originalTitle           Crazy
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Music,Short
Name: 2009671, dtype: object

(9,)

tconst                                       tt11832986
titleType                                     tvEpisode
primaryTitle      O tankistih, pastetkah in zivem pesku
originalTitle     O tankistih, pastetkah in zivem pesku
isAdult                                               0
startYear                                          2015
endYear                                              \N
runtimeMinutes                                       \N
genres                                    Comedy,Family
Name: 2009672, dtype: object

(9,)

tconst                  tt11832988
titleType                tvEpisode
primaryTitle             The Lodge
originalTitle            The Lodge
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  27
genres            Comedy,Talk-Show
Name: 2009673, dtype: object

(9,)

tconst                                                    tt1183298
titleType                                                     short
primaryTitle      Paul Sleuth Crime Investigator: The Burglary S...
originalTitle     Paul Sleuth Crime Investigator: The Burglary S...
isAdult                                                           0
startYear                                                      1913
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Crime,Drama,Short
Name: 2009674, dtype: object

(9,)

tconst                                  tt11832990
titleType                                    video
primaryTitle      Neil Cicierega: Wallspin (Audio)
originalTitle     Neil Cicierega: Wallspin (Audio)
isAdult                                          0
startYear                                     2017
endYear                                         \N
runtimeMinutes                                   3
genres                          Comedy,Music,Short
Name: 2009675, dtype: object

(9,)

tconst                               tt11832992
titleType                              tvSeries
primaryTitle      Bilangin ang bituin sa langit
originalTitle     Bilangin ang bituin sa langit
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                      Crime,Drama,Romance
Name: 2009676, dtype: object

(9,)

tconst                       tt11832994
titleType                         video
primaryTitle      Lil Baby: Sum 2 Prove
originalTitle     Lil Baby: Sum 2 Prove
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                        3
genres                      Music,Short
Name: 2009677, dtype: object

(9,)

tconst                     tt11832996
titleType                       short
primaryTitle      Government Shutdown
originalTitle     Government Shutdown
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                      7
genres             Comedy,Crime,Drama
Name: 2009678, dtype: object

(9,)

tconst                 tt11832998
titleType               tvEpisode
primaryTitle      Episode #1.5371
originalTitle     Episode #1.5371
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2009679, dtype: object

(9,)

tconst                                                    tt1183299
titleType                                                     short
primaryTitle      Paul Sleuth: The Mystery of the Astorian Crown...
originalTitle     Paul Sleuth: The Mystery of the Astorian Crown...
isAdult                                                           0
startYear                                                      1912
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Crime,Drama,Short
Name: 2009680, dtype: object

(9,)

tconst                                  tt11833000
titleType                                tvEpisode
primaryTitle      O smrkljih, puskah in tovornjaku
originalTitle     O smrkljih, puskah in tovornjaku
isAdult                                          0
startYear                                     2015
endYear                                         \N
runtimeMinutes                                  \N
genres                               Comedy,Family
Name: 2009681, dtype: object

(9,)

tconst                        tt11833004
titleType                          video
primaryTitle      Clara Luzia: Sinnerman
originalTitle     Clara Luzia: Sinnerman
isAdult                                0
startYear                           2014
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2009682, dtype: object

(9,)

tconst                                tt11833006
titleType                              tvEpisode
primaryTitle      Episode dated 12 February 2020
originalTitle     Episode dated 12 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009683, dtype: object

(9,)

tconst                                                   tt11833008
titleType                                                 tvEpisode
primaryTitle      Chantal Cliche, Denis Lepage, Michel Canapé, P...
originalTitle     Chantal Cliche, Denis Lepage, Michel Canapé, P...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009684, dtype: object

(9,)

tconst                   tt1183300
titleType                    short
primaryTitle      A Pill Box Cupid
originalTitle     A Pill Box Cupid
isAdult                          0
startYear                     1913
endYear                         \N
runtimeMinutes                  \N
genres                Comedy,Short
Name: 2009685, dtype: object

(9,)

tconst            tt11833010
titleType           tvSeries
primaryTitle         Blossom
originalTitle        Blossom
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2009686, dtype: object

(9,)

tconst                        tt11833012
titleType                          short
primaryTitle      Mayday - Airplane Mode
originalTitle     Mayday - Airplane Mode
isAdult                                0
startYear                           2017
endYear                               \N
runtimeMinutes                        \N
genres                             Short
Name: 2009687, dtype: object

(9,)

tconst                   tt11833014
titleType                     short
primaryTitle              Pas à pas
originalTitle             Pas à pas
isAdult                           0
startYear                      1983
endYear                          \N
runtimeMinutes                    5
genres            Documentary,Short
Name: 2009688, dtype: object

(9,)

tconst                                            tt11833018
titleType                                          tvEpisode
primaryTitle      O (ne)pravem Bozicku, venckih in drevescih
originalTitle     O (ne)pravem Bozicku, venckih in drevescih
isAdult                                                    0
startYear                                               2015
endYear                                                   \N
runtimeMinutes                                            \N
genres                                         Comedy,Family
Name: 2009689, dtype: object

(9,)

tconst                       tt1183301
titleType                        movie
primaryTitle                      Pink
originalTitle                     Pink
isAdult                              0
startYear                         2009
endYear                             \N
runtimeMinutes                      82
genres            Comedy,Drama,Romance
Name: 2009690, dtype: object

(9,)

tconst                tt11833020
titleType                  movie
primaryTitle           The Abbey
originalTitle          The Abbey
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres            History,Horror
Name: 2009691, dtype: object

(9,)

tconst                                                   tt11833022
titleType                                                     video
primaryTitle      Chandler Kinney & Pearce Joza & Baby Ariel: We...
originalTitle     Chandler Kinney & Pearce Joza & Baby Ariel: We...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    3
genres                                                  Music,Short
Name: 2009692, dtype: object

(9,)

tconst            tt11833024
titleType          tvEpisode
primaryTitle        Going In
originalTitle       Going In
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2009693, dtype: object

(9,)

tconst                   tt11833026
titleType                 tvEpisode
primaryTitle      Packing the House
originalTitle     Packing the House
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                       Comedy
Name: 2009694, dtype: object

(9,)

tconst                tt11833028
titleType                  short
primaryTitle      Bennie & Mason
originalTitle     Bennie & Mason
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres               Drama,Short
Name: 2009695, dtype: object

(9,)

tconst                  tt1183302
titleType                   video
primaryTitle      Sexy Temptation
originalTitle     Sexy Temptation
isAdult                         1
startYear                    2001
endYear                        \N
runtimeMinutes                 86
genres                      Adult
Name: 2009696, dtype: object

(9,)

tconst                                       tt11833030
titleType                                     tvEpisode
primaryTitle      O mavcu, caju in silvestrskem poljubu
originalTitle     O mavcu, caju in silvestrskem poljubu
isAdult                                               0
startYear                                          2015
endYear                                              \N
runtimeMinutes                                       \N
genres                                    Comedy,Family
Name: 2009697, dtype: object

(9,)

tconst                        tt11833032
titleType                      tvEpisode
primaryTitle      The Bear in the House!
originalTitle     The Bear in the House!
isAdult                                1
startYear                           2011
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2009698, dtype: object

(9,)

tconst                 tt11833036
titleType               tvEpisode
primaryTitle      The Baby Naming
originalTitle     The Baby Naming
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2009699, dtype: object

(9,)

tconst                                     tt11833038
titleType                                       video
primaryTitle      Zombies 2 Cast: Like the Zombies Do
originalTitle     Zombies 2 Cast: Like the Zombies Do
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                      2
genres                                    Music,Short
Name: 2009700, dtype: object

(9,)

tconst              tt1183303
titleType               video
primaryTitle      Summer Love
originalTitle     Summer Love
isAdult                     1
startYear                2002
endYear                    \N
runtimeMinutes             80
genres                  Adult
Name: 2009701, dtype: object

(9,)

tconst                         tt11833040
titleType                       tvEpisode
primaryTitle      O prdcih, ledu in ognju
originalTitle     O prdcih, ledu in ognju
isAdult                                 0
startYear                            2016
endYear                                \N
runtimeMinutes                         \N
genres                      Comedy,Family
Name: 2009702, dtype: object

(9,)

tconst                                                   tt11833042
titleType                                                 tvEpisode
primaryTitle      Claude Cormier, Etienne and Mélanie Bessette, ...
originalTitle     Claude Cormier, Etienne and Mélanie Bessette, ...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009703, dtype: object

(9,)

tconst                tt11833044
titleType              tvEpisode
primaryTitle      The Matchmaker
originalTitle     The Matchmaker
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2009704, dtype: object

(9,)

tconst             tt11833046
titleType               short
primaryTitle             Hera
originalTitle            Hera
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2009705, dtype: object

(9,)

tconst              tt11833048
titleType              tvMovie
primaryTitle      Nenä lasissa
originalTitle     Nenä lasissa
isAdult                      0
startYear                 1992
endYear                     \N
runtimeMinutes              46
genres             Documentary
Name: 2009706, dtype: object

(9,)

tconst                 tt1183304
titleType                  movie
primaryTitle      Qing chun meng
originalTitle     Qing chun meng
isAdult                        0
startYear                   1967
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Romance
Name: 2009707, dtype: object

(9,)

tconst                              tt11833050
titleType                                video
primaryTitle      Zombies 2 Cast: Flesh & Bone
originalTitle     Zombies 2 Cast: Flesh & Bone
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                               4
genres                             Music,Short
Name: 2009708, dtype: object

(9,)

tconst                       tt11833052
titleType                     tvEpisode
primaryTitle      Meeting Conan Colbert
originalTitle     Meeting Conan Colbert
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                           Comedy
Name: 2009709, dtype: object

(9,)

tconst                        tt11833054
titleType                          short
primaryTitle      Rittz - I'm Only Human
originalTitle     Rittz - I'm Only Human
isAdult                                0
startYear                           2017
endYear                               \N
runtimeMinutes                        \N
genres                             Short
Name: 2009710, dtype: object

(9,)

tconst                                                   tt11833056
titleType                                                 tvEpisode
primaryTitle      Socially Liberal and Fiscally Conservative Mak...
originalTitle     Socially Liberal and Fiscally Conservative Mak...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2009711, dtype: object

(9,)

tconst                     tt11833058
titleType                       short
primaryTitle      The Meaning of Work
originalTitle     The Meaning of Work
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     18
genres                   Comedy,Short
Name: 2009712, dtype: object

(9,)

tconst                    tt1183305
titleType                     short
primaryTitle      The Real Impostor
originalTitle     The Real Impostor
isAdult                           0
startYear                      1913
endYear                          \N
runtimeMinutes                   14
genres                  Drama,Short
Name: 2009713, dtype: object

(9,)

tconst                                                   tt11833060
titleType                                                     short
primaryTitle      Behind the Curtain: The Masters of Horror on P...
originalTitle     Behind the Curtain: The Masters of Horror on P...
isAdult                                                           0
startYear                                                      2017
endYear                                                          \N
runtimeMinutes                                                   42
genres                                            Documentary,Short
Name: 2009714, dtype: object

(9,)

tconst                                                   tt11833062
titleType                                                 tvEpisode
primaryTitle      O Firbcologih v tezavah, detektorju lazi in ek...
originalTitle     O Firbcologih v tezavah, detektorju lazi in ek...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2009715, dtype: object

(9,)

tconst                                  tt11833064
titleType                                tvEpisode
primaryTitle      10th January 2020 Lunchtime News
originalTitle     10th January 2020 Lunchtime News
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                        News
Name: 2009716, dtype: object

(9,)

tconst                             tt11833066
titleType                               video
primaryTitle      Zombies 2 Cast: We Got This
originalTitle     Zombies 2 Cast: We Got This
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                              3
genres                            Music,Short
Name: 2009717, dtype: object

(9,)

tconst                 tt11833068
titleType               tvEpisode
primaryTitle      Lie or Be Fired
originalTitle     Lie or Be Fired
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                       News
Name: 2009718, dtype: object

(9,)

tconst                           tt1183306
titleType                          tvMovie
primaryTitle      Der Rowdy auf der Treppe
originalTitle     Der Rowdy auf der Treppe
isAdult                                  0
startYear                             1970
endYear                                 \N
runtimeMinutes                          90
genres                               Drama
Name: 2009719, dtype: object

(9,)

tconst                            tt11833070
titleType                              movie
primaryTitle      Havana Dreams-Snovi Havane
originalTitle     Havana Dreams-Snovi Havane
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            52
genres                           Documentary
Name: 2009720, dtype: object

(9,)

tconst                                  tt11833072
titleType                                    video
primaryTitle      Zombies 2 Cast: Call to the Wild
originalTitle     Zombies 2 Cast: Call to the Wild
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                   3
genres                                 Music,Short
Name: 2009721, dtype: object

(9,)

tconst                                                   tt11833074
titleType                                                 tvEpisode
primaryTitle      Karo Laurendeau, Hert Leblanc, Renée Martel, S...
originalTitle     Karo Laurendeau, Hert Leblanc, Renée Martel, S...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009722, dtype: object

(9,)

tconst                    tt11833076
titleType                  tvEpisode
primaryTitle      Mom's Helping Hand
originalTitle     Mom's Helping Hand
isAdult                            1
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2009723, dtype: object

(9,)

tconst                                          tt11833078
titleType                                        tvEpisode
primaryTitle      O macjih mladicih, saltah in carodejstvu
originalTitle     O macjih mladicih, saltah in carodejstvu
isAdult                                                  0
startYear                                             2016
endYear                                                 \N
runtimeMinutes                                          \N
genres                                       Comedy,Family
Name: 2009724, dtype: object

(9,)

tconst                          tt1183307
titleType                           movie
primaryTitle       The Village of Shadows
originalTitle       Le village des ombres
isAdult                                 0
startYear                            2010
endYear                                \N
runtimeMinutes                        103
genres            Horror,Mystery,Thriller
Name: 2009725, dtype: object

(9,)

tconst                             tt11833080
titleType                               video
primaryTitle      Zombies 2 Cast: One for All
originalTitle     Zombies 2 Cast: One for All
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                              3
genres                            Music,Short
Name: 2009726, dtype: object

(9,)

tconst              tt11833082
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009727, dtype: object

(9,)

tconst                             tt11833084
titleType                               video
primaryTitle      Zombies 2 Cast: I'm Winning
originalTitle     Zombies 2 Cast: I'm Winning
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                              3
genres                            Music,Short
Name: 2009728, dtype: object

(9,)

tconst                                             tt11833086
titleType                                           tvEpisode
primaryTitle      Les gens de culture en Colombie-Britannique
originalTitle     Les gens de culture en Colombie-Britannique
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             22
genres                                            Documentary
Name: 2009729, dtype: object

(9,)

tconst              tt11833088
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009730, dtype: object

(9,)

tconst                  tt1183308
titleType                   video
primaryTitle      Schluck Empfang
originalTitle     Schluck Empfang
isAdult                         1
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2009731, dtype: object

(9,)

tconst                                  tt11833090
titleType                                tvEpisode
primaryTitle      22nd January 2020 Afternoon News
originalTitle     22nd January 2020 Afternoon News
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                        News
Name: 2009732, dtype: object

(9,)

tconst             tt11833092
titleType               short
primaryTitle      Before I Go
originalTitle     Before I Go
isAdult                     0
startYear                  \N
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2009733, dtype: object

(9,)

tconst              tt11833094
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009734, dtype: object

(9,)

tconst                                                   tt11833096
titleType                                                     video
primaryTitle      Milo Manheim & Meg Donnelly: Gotta Find Where ...
originalTitle     Milo Manheim & Meg Donnelly: Gotta Find Where ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    3
genres                                                  Music,Short
Name: 2009735, dtype: object

(9,)

tconst                                                   tt11833098
titleType                                                 tvEpisode
primaryTitle      Bourbon Gautier, Louis Bérubé, Guylaine Tangua...
originalTitle     Bourbon Gautier, Louis Bérubé, Guylaine Tangua...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009736, dtype: object

(9,)

tconst                      tt1183309
titleType                       short
primaryTitle      A Son of His Father
originalTitle     A Son of His Father
isAdult                             0
startYear                        1913
endYear                            \N
runtimeMinutes                     \N
genres                    Drama,Short
Name: 2009737, dtype: object

(9,)

tconst                                  tt11833100
titleType                                tvEpisode
primaryTitle      O sneznih gradovih, peni in useh
originalTitle     O sneznih gradovih, peni in useh
isAdult                                          0
startYear                                     2016
endYear                                         \N
runtimeMinutes                                  \N
genres                               Comedy,Family
Name: 2009738, dtype: object

(9,)

tconst              tt11833102
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009739, dtype: object

(9,)

tconst                           tt11833104
titleType                             short
primaryTitle      The Art of Moving Forward
originalTitle     The Art of Moving Forward
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                            7
genres                          Drama,Short
Name: 2009740, dtype: object

(9,)

tconst               tt11833106
titleType             tvEpisode
primaryTitle      Made to Serve
originalTitle     Made to Serve
isAdult                       1
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2009741, dtype: object

(9,)

tconst              tt11833108
titleType            tvSpecial
primaryTitle       Mardocienta
originalTitle      Mardocienta
isAdult                      0
startYear                 2015
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2009742, dtype: object

(9,)

tconst                                     tt1183310
titleType                                      short
primaryTitle      Spata, to stifado tou Agiou Petrou
originalTitle     Spata, to stifado tou Agiou Petrou
isAdult                                            0
startYear                                       1978
endYear                                           \N
runtimeMinutes                                    25
genres                             Documentary,Short
Name: 2009743, dtype: object

(9,)

tconst                                                   tt11833110
titleType                                                     short
primaryTitle      Creating a Tiny Erdös-Bacon-Sabbath Number for...
originalTitle     Creating a Tiny Erdös-Bacon-Sabbath Number for...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    9
genres                                            Documentary,Short
Name: 2009744, dtype: object

(9,)

tconst              tt11833112
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009745, dtype: object

(9,)

tconst                                 tt11833114
titleType                                   movie
primaryTitle      Ghost Island - A Spherical Film
originalTitle     Ghost Island - A Spherical Film
isAdult                                         0
startYear                                      \N
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Horror
Name: 2009746, dtype: object

(9,)

tconst                                tt11833116
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2009747, dtype: object

(9,)

tconst                     tt11833118
titleType                   tvEpisode
primaryTitle      Getting to Location
originalTitle     Getting to Location
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                    Documentary
Name: 2009748, dtype: object

(9,)

tconst                tt1183311
titleType                 video
primaryTitle      Sperma ahoi!!
originalTitle     Sperma ahoi!!
isAdult                       1
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2009749, dtype: object

(9,)

tconst                                                   tt11833120
titleType                                                 tvEpisode
primaryTitle      Sperm Junkie #1, Lina Love swallows 15 cumshot...
originalTitle     Sperm Junkie #1, Lina Love swallows 15 cumshot...
isAdult                                                           1
startYear                                                      2015
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2009750, dtype: object

(9,)

tconst                             tt11833122
titleType                           tvEpisode
primaryTitle          Colonel John Paul Stapp
originalTitle         Colonel John Paul Stapp
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2009751, dtype: object

(9,)

tconst                                         tt11833124
titleType                                       tvEpisode
primaryTitle      O sodobni tehnologiji, roladah in pakih
originalTitle     O sodobni tehnologiji, roladah in pakih
isAdult                                                 0
startYear                                            2016
endYear                                                \N
runtimeMinutes                                         \N
genres                                      Comedy,Family
Name: 2009752, dtype: object

(9,)

tconst                      tt11833126
titleType                    tvEpisode
primaryTitle      Kriminelle Geschäfte
originalTitle     Kriminelle Geschäfte
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                   Drama,Romance
Name: 2009753, dtype: object

(9,)

tconst                                      tt11833128
titleType                                        video
primaryTitle      Milo Manheim & Meg Donnelly: Someday
originalTitle     Milo Manheim & Meg Donnelly: Someday
isAdult                                              0
startYear                                         2018
endYear                                             \N
runtimeMinutes                                       3
genres                                     Music,Short
Name: 2009754, dtype: object

(9,)

tconst                         tt1183312
titleType                          video
primaryTitle      Sperma... s'isch geil!
originalTitle     Sperma... s'isch geil!
isAdult                                1
startYear                           2007
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2009755, dtype: object

(9,)

tconst              tt11833130
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009756, dtype: object

(9,)

tconst                                                   tt11833132
titleType                                                 tvEpisode
primaryTitle      Steve Veilleux, Nathalie Carbonneau, Jerry Cor...
originalTitle     Steve Veilleux, Nathalie Carbonneau, Jerry Cor...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009757, dtype: object

(9,)

tconst                        tt11833134
titleType                      tvEpisode
primaryTitle       Mit Geduld und Spucke
originalTitle      Mit Geduld und Spucke
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Documentary,Reality-TV
Name: 2009758, dtype: object

(9,)

tconst              tt11833138
titleType            tvEpisode
primaryTitle      Sex Preacher
originalTitle     Sex Preacher
isAdult                      1
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2009759, dtype: object

(9,)

tconst                               tt1183313
titleType                                video
primaryTitle      Suzumiya Hiharu no Shôshitsu
originalTitle     Suzumiya Hiharu no Shôshitsu
isAdult                                      1
startYear                                 2007
endYear                                     \N
runtimeMinutes                             120
genres                                   Adult
Name: 2009760, dtype: object

(9,)

tconst                                         tt11833140
titleType                                       tvEpisode
primaryTitle      Quaden Bayles - Little Person, BIG LIE?
originalTitle     Quaden Bayles - Little Person, BIG LIE?
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                             Comedy
Name: 2009761, dtype: object

(9,)

tconst              tt11833142
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009762, dtype: object

(9,)

tconst                         tt11833144
titleType                           movie
primaryTitle      Kyôen kobanzame: Zenpen
originalTitle     Kyôen kobanzame: Zenpen
isAdult                                 0
startYear                            1958
endYear                                \N
runtimeMinutes                         70
genres                                 \N
Name: 2009763, dtype: object

(9,)

tconst                        tt11833146
titleType                          movie
primaryTitle      Kyôen kobanzame: Kôhen
originalTitle     Kyôen kobanzame: Kôhen
isAdult                                0
startYear                           1958
endYear                               \N
runtimeMinutes                        73
genres                                \N
Name: 2009764, dtype: object

(9,)

tconst                                                   tt11833148
titleType                                                 tvEpisode
primaryTitle      Lina Love 3on1 BBC DP & intense anal fucking RS52
originalTitle     Lina Love 3on1 BBC DP & intense anal fucking RS52
isAdult                                                           1
startYear                                                      2015
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2009765, dtype: object

(9,)

tconst                        tt1183314
titleType                         short
primaryTitle      Through Flaming Paths
originalTitle     Through Flaming Paths
isAdult                               0
startYear                          1913
endYear                              \N
runtimeMinutes                       \N
genres                      Drama,Short
Name: 2009766, dtype: object

(9,)

tconst                  tt11833150
titleType                    movie
primaryTitle      DNA 2: Bloodline
originalTitle     DNA 2: Bloodline
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                 110
genres                      Action
Name: 2009767, dtype: object

(9,)

tconst                      tt11833152
titleType                    tvEpisode
primaryTitle             Episode #1.11
originalTitle            Episode #1.11
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009768, dtype: object

(9,)

tconst                                              tt11833154
titleType                                            tvEpisode
primaryTitle      O vrtecih se kroznikih, kravlu in parlamentu
originalTitle     O vrtecih se kroznikih, kravlu in parlamentu
isAdult                                                      0
startYear                                                 2016
endYear                                                     \N
runtimeMinutes                                              \N
genres                                           Comedy,Family
Name: 2009769, dtype: object

(9,)

tconst                        tt11833156
titleType                          video
primaryTitle      Cast Zombies: Fired Up
originalTitle     Cast Zombies: Fired Up
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2009770, dtype: object

(9,)

tconst              tt11833158
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2009771, dtype: object

(9,)

tconst                tt1183315
titleType                 short
primaryTitle      Tides of Time
originalTitle     Tides of Time
isAdult                       0
startYear                  1915
endYear                      \N
runtimeMinutes               \N
genres              Drama,Short
Name: 2009772, dtype: object

(9,)

tconst                      tt11833160
titleType                    tvEpisode
primaryTitle             Episode #1.12
originalTitle            Episode #1.12
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009773, dtype: object

(9,)

tconst                      tt11833162
titleType                    tvEpisode
primaryTitle             Episode #1.13
originalTitle            Episode #1.13
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009774, dtype: object

(9,)

tconst                      tt11833166
titleType                    tvEpisode
primaryTitle             Episode #1.14
originalTitle            Episode #1.14
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009775, dtype: object

(9,)

tconst                      tt11833168
titleType                    tvEpisode
primaryTitle             Episode #1.15
originalTitle            Episode #1.15
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009776, dtype: object

(9,)

tconst                    tt1183316
titleType                     movie
primaryTitle      Tie dan shen long
originalTitle     Tie dan shen long
isAdult                           0
startYear                      1970
endYear                          \N
runtimeMinutes                   \N
genres             Action,Adventure
Name: 2009777, dtype: object

(9,)

tconst                      tt11833170
titleType                    tvEpisode
primaryTitle             Episode #1.16
originalTitle            Episode #1.16
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009778, dtype: object

(9,)

tconst                                              tt11833172
titleType                                                video
primaryTitle      Cast Zombies: Fired Up (Competition Version)
originalTitle     Cast Zombies: Fired Up (Competition Version)
isAdult                                                      0
startYear                                                 2018
endYear                                                     \N
runtimeMinutes                                               3
genres                                             Music,Short
Name: 2009779, dtype: object

(9,)

tconst                           tt11833174
titleType                         tvEpisode
primaryTitle      Office Party Cock Blowout
originalTitle     Office Party Cock Blowout
isAdult                                   1
startYear                              2011
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2009780, dtype: object

(9,)

tconst                      tt11833176
titleType                    tvEpisode
primaryTitle             Episode #1.17
originalTitle            Episode #1.17
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009781, dtype: object

(9,)

tconst                      tt11833178
titleType                    tvEpisode
primaryTitle             Episode #1.18
originalTitle            Episode #1.18
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009782, dtype: object

(9,)

tconst                        tt1183317
titleType                         short
primaryTitle      An Unintentional Hero
originalTitle     An Unintentional Hero
isAdult                               0
startYear                          1914
endYear                              \N
runtimeMinutes                        4
genres                     Comedy,Short
Name: 2009783, dtype: object

(9,)

tconst                      tt11833180
titleType                    tvEpisode
primaryTitle             Episode #1.19
originalTitle            Episode #1.19
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009784, dtype: object

(9,)

tconst                      tt11833182
titleType                    tvEpisode
primaryTitle             Episode #1.20
originalTitle            Episode #1.20
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009785, dtype: object

(9,)

tconst                                  tt11833184
titleType                                tvEpisode
primaryTitle      O cokoladi, cvetju in poljubckih
originalTitle     O cokoladi, cvetju in poljubckih
isAdult                                          0
startYear                                     2016
endYear                                         \N
runtimeMinutes                                  \N
genres                               Comedy,Family
Name: 2009786, dtype: object

(9,)

tconst              tt11833186
titleType            tvEpisode
primaryTitle      Pretty Woman
originalTitle     Pretty Woman
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Biography
Name: 2009787, dtype: object

(9,)

tconst                      tt11833188
titleType                        short
primaryTitle      Giving Bloch His Due
originalTitle     Giving Bloch His Due
isAdult                              0
startYear                         2017
endYear                             \N
runtimeMinutes                      10
genres               Documentary,Short
Name: 2009788, dtype: object

(9,)

tconst                                      tt1183318
titleType                                       video
primaryTitle      Vollgewichste Gangbang Schlampen 15
originalTitle     Vollgewichste Gangbang Schlampen 15
isAdult                                             1
startYear                                        2007
endYear                                            \N
runtimeMinutes                                    122
genres                                          Adult
Name: 2009789, dtype: object

(9,)

tconst                                           tt11833190
titleType                                             video
primaryTitle      Orient Jewellers TVC: Sonay Thakuk Sansar
originalTitle     Orient Jewellers TVC: Sonay Thakuk Sansar
isAdult                                                   0
startYear                                              2018
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Short
Name: 2009790, dtype: object

(9,)

tconst                                                 tt11833192
titleType                                               tvEpisode
primaryTitle      Christie's Bachelorette Party from Dancing Bear
originalTitle     Christie's Bachelorette Party from Dancing Bear
isAdult                                                         1
startYear                                                    2012
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                      Adult
Name: 2009791, dtype: object

(9,)

tconst                                                   tt11833194
titleType                                                 tvEpisode
primaryTitle      Nina Heaven, Lina Love & Susie Q interracial m...
originalTitle     Nina Heaven, Lina Love & Susie Q interracial m...
isAdult                                                           1
startYear                                                      2015
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2009792, dtype: object

(9,)

tconst                tt11833196
titleType                tvMovie
primaryTitle      Kieli poskessa
originalTitle     Kieli poskessa
isAdult                        0
startYear                   1987
endYear                       \N
runtimeMinutes                47
genres               Documentary
Name: 2009793, dtype: object

(9,)

tconst                                                   tt11833198
titleType                                                 tvEpisode
primaryTitle      André Barriault, Annette Campagne, Denis Landr...
originalTitle     André Barriault, Annette Campagne, Denis Landr...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009794, dtype: object

(9,)

tconst                                      tt1183319
titleType                                       video
primaryTitle      Vollgewichste Gangbang Schlampen 19
originalTitle     Vollgewichste Gangbang Schlampen 19
isAdult                                             1
startYear                                        2007
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2009795, dtype: object

(9,)

tconst                                       tt11833200
titleType                                         video
primaryTitle      Meg Donnelly & Trevor Tordjman: Stand
originalTitle     Meg Donnelly & Trevor Tordjman: Stand
isAdult                                               0
startYear                                          2018
endYear                                              \N
runtimeMinutes                                        3
genres                                      Music,Short
Name: 2009796, dtype: object

(9,)

tconst                                                   tt11833202
titleType                                                 tvEpisode
primaryTitle      O pokakanih plenicah, sofiranju in rjuhah z me...
originalTitle     O pokakanih plenicah, sofiranju in rjuhah z me...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2009797, dtype: object

(9,)

tconst               tt11833204
titleType                 movie
primaryTitle       Double Bluff
originalTitle      Double Bluff
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres            Action,Comedy
Name: 2009798, dtype: object

(9,)

tconst                                                   tt11833206
titleType                                                 tvEpisode
primaryTitle      DAP Reload. Lina Love intense DAP with huge ga...
originalTitle     DAP Reload. Lina Love intense DAP with huge ga...
isAdult                                                           1
startYear                                                      2015
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2009799, dtype: object

(9,)

tconst            tt11833208
titleType          tvEpisode
primaryTitle           Death
originalTitle          Death
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            38
genres                 Drama
Name: 2009800, dtype: object

(9,)

tconst                     tt1183320
titleType                      movie
primaryTitle      Wan Zai si tiao nu
originalTitle     Wan Zai si tiao nu
isAdult                            0
startYear                       1979
endYear                           \N
runtimeMinutes                    \N
genres                         Drama
Name: 2009801, dtype: object

(9,)

tconst                                tt11833210
titleType                              tvEpisode
primaryTitle      Expérience autochtone à Ottawa
originalTitle     Expérience autochtone à Ottawa
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                22
genres                               Documentary
Name: 2009802, dtype: object

(9,)

tconst                                                   tt11833212
titleType                                                 tvEpisode
primaryTitle      Crystal Plamondon, Dani Daraîche, Julie Daraîc...
originalTitle     Crystal Plamondon, Dani Daraîche, Julie Daraîc...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009803, dtype: object

(9,)

tconst                     tt11833214
titleType                   tvEpisode
primaryTitle      Types of Gym People
originalTitle     Types of Gym People
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2009804, dtype: object

(9,)

tconst                                               tt11833216
titleType                                             tvEpisode
primaryTitle      Lina Love ass banged (anal gaping slut) GG418
originalTitle     Lina Love ass banged (anal gaping slut) GG418
isAdult                                                       1
startYear                                                  2015
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                    Adult
Name: 2009805, dtype: object

(9,)

tconst                   tt11833218
titleType                     video
primaryTitle          Walking Dog!!
originalTitle         Walking Dog!!
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                    1
genres            Documentary,Short
Name: 2009806, dtype: object

(9,)

tconst                          tt1183321
titleType                           short
primaryTitle      What Happened to Lizzie
originalTitle     What Happened to Lizzie
isAdult                                 0
startYear                            1913
endYear                                \N
runtimeMinutes                         \N
genres                       Comedy,Short
Name: 2009807, dtype: object

(9,)

tconst                            tt11833220
titleType                          tvEpisode
primaryTitle      Episode dated 1 March 2018
originalTitle     Episode dated 1 March 2018
isAdult                                    0
startYear                               2018
endYear                                   \N
runtimeMinutes                            \N
genres                       Sport,Talk-Show
Name: 2009808, dtype: object

(9,)

tconst                                         tt11833222
titleType                                       tvEpisode
primaryTitle      GG Exclusive Anal #467 Lina double anal
originalTitle     GG Exclusive Anal #467 Lina double anal
isAdult                                                 1
startYear                                            2014
endYear                                                \N
runtimeMinutes                                         \N
genres                                                 \N
Name: 2009809, dtype: object

(9,)

tconst                            tt11833224
titleType                          tvEpisode
primaryTitle      Episode dated 5 March 2018
originalTitle     Episode dated 5 March 2018
isAdult                                    0
startYear                               2018
endYear                                   \N
runtimeMinutes                            \N
genres                       Sport,Talk-Show
Name: 2009810, dtype: object

(9,)

tconst                                               tt11833226
titleType                                             tvEpisode
primaryTitle      O izginotju, laku za nohte in orjaskih udavih
originalTitle     O izginotju, laku za nohte in orjaskih udavih
isAdult                                                       0
startYear                                                  2016
endYear                                                      \N
runtimeMinutes                                               \N
genres                                            Comedy,Family
Name: 2009811, dtype: object

(9,)

tconst                             tt11833228
titleType                           tvEpisode
primaryTitle      Episode dated 27 March 2018
originalTitle     Episode dated 27 March 2018
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                        Sport,Talk-Show
Name: 2009812, dtype: object

(9,)

tconst                         tt1183322
titleType                          short
primaryTitle      When the Well Went Dry
originalTitle     When the Well Went Dry
isAdult                                0
startYear                           1913
endYear                               \N
runtimeMinutes                        \N
genres                      Comedy,Short
Name: 2009813, dtype: object

(9,)

tconst                                              tt11833230
titleType                                            tvEpisode
primaryTitle      GG Exclusive Lina Love Fucked by Marcus #427
originalTitle     GG Exclusive Lina Love Fucked by Marcus #427
isAdult                                                      1
startYear                                                 2014
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                      \N
Name: 2009814, dtype: object

(9,)

tconst                           tt11833232
titleType                         tvEpisode
primaryTitle      Episode dated 4 July 2018
originalTitle     Episode dated 4 July 2018
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                      Sport,Talk-Show
Name: 2009815, dtype: object

(9,)

tconst                          tt11833234
titleType                            movie
primaryTitle      Do observatório me viram
originalTitle     Do observatório me viram
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                              Sci-Fi
Name: 2009816, dtype: object

(9,)

tconst                                 tt11833236
titleType                               tvEpisode
primaryTitle      Episode dated 17 September 2018
originalTitle     Episode dated 17 September 2018
isAdult                                         0
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                            Sport,Talk-Show
Name: 2009817, dtype: object

(9,)

tconst                               tt11833238
titleType                             tvEpisode
primaryTitle      Episode dated 6 December 2018
originalTitle     Episode dated 6 December 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2009818, dtype: object

(9,)

tconst               tt1183323
titleType                short
primaryTitle      The Windfall
originalTitle     The Windfall
isAdult                      0
startYear                 1914
endYear                     \N
runtimeMinutes              \N
genres             Drama,Short
Name: 2009819, dtype: object

(9,)

tconst                            tt11833240
titleType                          tvEpisode
primaryTitle      Remy's Dancing Bear Fiesta
originalTitle     Remy's Dancing Bear Fiesta
isAdult                                    1
startYear                               2012
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2009820, dtype: object

(9,)

tconst                          tt11833242
titleType                        tvEpisode
primaryTitle      Sivasspor vs. Alanyaspor
originalTitle     Sivasspor vs. Alanyaspor
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                               Sport
Name: 2009821, dtype: object

(9,)

tconst                         tt11833244
titleType                       tvEpisode
primaryTitle      Los rostros de Agustina
originalTitle     Los rostros de Agustina
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                              Drama
Name: 2009822, dtype: object

(9,)

tconst                                                   tt11833246
titleType                                                 tvEpisode
primaryTitle      O postavljanju pravil, delfinih in mavricnih r...
originalTitle     O postavljanju pravil, delfinih in mavricnih r...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2009823, dtype: object

(9,)

tconst                                                   tt11833248
titleType                                                 tvEpisode
primaryTitle      GG Exclusive #431 Lina Love & Stephanie Anal V...
originalTitle     GG Exclusive #431 Lina Love & Stephanie Anal V...
isAdult                                                           1
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2009824, dtype: object

(9,)

tconst                tt1183324
titleType                 movie
primaryTitle      Xie dou chuan
originalTitle     Xie dou chuan
isAdult                       0
startYear                  1980
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2009825, dtype: object

(9,)

tconst               tt11833250
titleType              tvSeries
primaryTitle      Struggle City
originalTitle     Struggle City
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres             Comedy,Short
Name: 2009826, dtype: object

(9,)

tconst                             tt11833252
titleType                           tvEpisode
primaryTitle                      Julia Judge
originalTitle                     Julia Judge
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2009827, dtype: object

(9,)

tconst                                                   tt11833254
titleType                                                 tvEpisode
primaryTitle      GG Exclusive #461 Eva Zan & Lina Love nasty Ru...
originalTitle     GG Exclusive #461 Eva Zan & Lina Love nasty Ru...
isAdult                                                           1
startYear                                                      2014
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2009828, dtype: object

(9,)

tconst                       tt11833256
titleType                         video
primaryTitle      Cast Zombies: My Year
originalTitle     Cast Zombies: My Year
isAdult                               0
startYear                          2018
endYear                              \N
runtimeMinutes                        4
genres                      Music,Short
Name: 2009829, dtype: object

(9,)

tconst                 tt11833258
titleType               tvEpisode
primaryTitle      Alaina's Fiesta
originalTitle     Alaina's Fiesta
isAdult                         1
startYear                    2012
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2009830, dtype: object

(9,)

tconst                   tt1183325
titleType                 tvSeries
primaryTitle      Against All Odds
originalTitle     Against All Odds
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  60
genres                 Documentary
Name: 2009831, dtype: object

(9,)

tconst                                                   tt11833260
titleType                                                 tvEpisode
primaryTitle      Joëlle Bizier, Guy Marcoux, Pascal Lejeune, Ré...
originalTitle     Joëlle Bizier, Guy Marcoux, Pascal Lejeune, Ré...
isAdult                                                           0
startYear                                                      2010
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                      Musical
Name: 2009832, dtype: object

(9,)

tconst                                                  tt11833262
titleType                                                tvEpisode
primaryTitle      O krekerjih, neandertalcih in spretnih jadralcih
originalTitle     O krekerjih, neandertalcih in spretnih jadralcih
isAdult                                                          0
startYear                                                     2016
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                               Comedy,Family
Name: 2009833, dtype: object

(9,)

tconst                                      tt11833264
titleType                                    tvEpisode
primaryTitle      GG Exclusive #449 Lina Love anal POV
originalTitle     GG Exclusive #449 Lina Love anal POV
isAdult                                              1
startYear                                         2014
endYear                                             \N
runtimeMinutes                                      \N
genres                                              \N
Name: 2009834, dtype: object

(9,)

tconst             tt11833266
titleType               movie
primaryTitle       Finding Us
originalTitle      Finding Us
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2009835, dtype: object

(9,)

tconst                      tt11833268
titleType                    tvEpisode
primaryTitle         Furioser Auftritt
originalTitle        Furioser Auftritt
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Drama,Family,Romance
Name: 2009836, dtype: object

(9,)

tconst                       tt1183326
titleType                     tvSeries
primaryTitle      La botica de Txumari
originalTitle     La botica de Txumari
isAdult                              0
startYear                         2000
endYear                             \N
runtimeMinutes                      25
genres                              \N
Name: 2009837, dtype: object

(9,)

tconst                             tt11833270
titleType                           tvEpisode
primaryTitle      Episode dated 27 April 2015
originalTitle     Episode dated 27 April 2015
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                              Talk-Show
Name: 2009838, dtype: object

(9,)

tconst                          tt11833272
titleType                        tvEpisode
primaryTitle      Episode dated 8 May 2015
originalTitle     Episode dated 8 May 2015
isAdult                                  0
startYear                             2015
endYear                                 \N
runtimeMinutes                          \N
genres                           Talk-Show
Name: 2009839, dtype: object

(9,)

tconst                           tt11833274
titleType                         tvEpisode
primaryTitle      Episode dated 15 May 2015
originalTitle     Episode dated 15 May 2015
isAdult                                   0
startYear                              2015
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2009840, dtype: object

(9,)

tconst                                    tt11833276
titleType                                  tvEpisode
primaryTitle      G/G Sexy Bath Time with Gaberiella
originalTitle     G/G Sexy Bath Time with Gaberiella
isAdult                                            1
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2009841, dtype: object

(9,)

tconst                     tt11833278
titleType                   tvEpisode
primaryTitle           Episode #1.109
originalTitle          Episode #1.109
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2009842, dtype: object

(9,)

tconst                             tt1183327
titleType                          tvEpisode
primaryTitle             Enter the Commandos
originalTitle            Enter the Commandos
isAdult                                    0
startYear                               1988
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2009843, dtype: object

(9,)

tconst                           tt11833280
titleType                         tvEpisode
primaryTitle      Episode dated 22 May 2015
originalTitle     Episode dated 22 May 2015
isAdult                                   0
startYear                              2015
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2009844, dtype: object

(9,)

tconst                           tt11833282
titleType                         tvEpisode
primaryTitle      Episode dated 25 May 2015
originalTitle     Episode dated 25 May 2015
isAdult                                   0
startYear                              2015
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2009845, dtype: object

(9,)

tconst              tt11833284
titleType                movie
primaryTitle      The Knocking
originalTitle     The Knocking
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                  Horror
Name: 2009846, dtype: object

(9,)

tconst                                         tt11833288
titleType                                           video
primaryTitle      Cast Zombies: BAMM (Zombie Block Party)
originalTitle     Cast Zombies: BAMM (Zombie Block Party)
isAdult                                                 0
startYear                                            2018
endYear                                                \N
runtimeMinutes                                          1
genres                                        Music,Short
Name: 2009847, dtype: object

(9,)

tconst                             tt1183328
titleType                          tvEpisode
primaryTitle                           T-Rex
originalTitle                          T-Rex
isAdult                                    0
startYear                               1988
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2009848, dtype: object

(9,)

tconst             tt11833290
titleType           tvEpisode
primaryTitle      Èpisode 113
originalTitle     Èpisode 113
isAdult                     0
startYear                2010
endYear                    \N
runtimeMinutes             \N
genres                Musical
Name: 2009849, dtype: object

(9,)

tconst                                       tt11833292
titleType                                     tvEpisode
primaryTitle      First Gape Lina Love Nasty Anal #5041
originalTitle     First Gape Lina Love Nasty Anal #5041
isAdult                                               1
startYear                                          2014
endYear                                              \N
runtimeMinutes                                       \N
genres                                               \N
Name: 2009850, dtype: object

(9,)

tconst                                                   tt11833294
titleType                                                 tvEpisode
primaryTitle      O bruhajocih bucah, gledaliscu in junaskem lajezu
originalTitle     O bruhajocih bucah, gledaliscu in junaskem lajezu
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                Comedy,Family
Name: 2009851, dtype: object

(9,)

tconst                                                 tt11833296
titleType                                                   video
primaryTitle      Milo Manheim, Meg Donnelly, Kylee Russell: BAMM
originalTitle     Milo Manheim, Meg Donnelly, Kylee Russell: BAMM
isAdult                                                         0
startYear                                                    2017
endYear                                                        \N
runtimeMinutes                                                  3
genres                                                Music,Short
Name: 2009852, dtype: object

(9,)

tconst                                        tt11833298
titleType                                          video
primaryTitle      How Fast Does Venom Work Against Mice?
originalTitle     How Fast Does Venom Work Against Mice?
isAdult                                                0
startYear                                           2019
endYear                                               \N
runtimeMinutes                                        15
genres                                 Documentary,Short
Name: 2009853, dtype: object

(9,)

tconst                             tt1183329
titleType                          tvEpisode
primaryTitle            The Adventure Begins
originalTitle           The Adventure Begins
isAdult                                    0
startYear                               1988
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2009854, dtype: object

(9,)

tconst                                  tt11833302
titleType                                tvEpisode
primaryTitle      A View 2 Lina's Gaping Ass #1816
originalTitle     A View 2 Lina's Gaping Ass #1816
isAdult                                          1
startYear                                     2014
endYear                                         \N
runtimeMinutes                                  \N
genres                                          \N
Name: 2009855, dtype: object

(9,)

tconst                                       tt11833304
titleType                                     tvEpisode
primaryTitle      Top 10 Worst Movie Monster Weaknesses
originalTitle     Top 10 Worst Movie Monster Weaknesses
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                               \N
Name: 2009856, dtype: object

(9,)

tconst                      tt11833306
titleType                    tvEpisode
primaryTitle            One Year Later
originalTitle           One Year Later
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      42
genres            Comedy,Drama,Romance
Name: 2009857, dtype: object

(9,)

tconst                                       tt11833308
titleType                                     tvEpisode
primaryTitle      First Gape Lina Love Anal Porno #5013
originalTitle     First Gape Lina Love Anal Porno #5013
isAdult                                               1
startYear                                          2014
endYear                                              \N
runtimeMinutes                                       \N
genres                                               \N
Name: 2009858, dtype: object

(9,)

tconst                             tt1183330
titleType                          tvEpisode
primaryTitle              The Rulon Stampede
originalTitle             The Rulon Stampede
isAdult                                    0
startYear                               1988
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2009859, dtype: object

(9,)

tconst                       tt11833310
titleType                     tvEpisode
primaryTitle      Mothers and Daughters
originalTitle     Mothers and Daughters
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       41
genres             Comedy,Drama,Romance
Name: 2009860, dtype: object

(9,)

tconst                                                tt11833312
titleType                                              tvEpisode
primaryTitle      Ashley Lane- UltraGirl Vs The Black Cat Part 2
originalTitle     Ashley Lane- UltraGirl Vs The Black Cat Part 2
isAdult                                                        1
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                     Adult
Name: 2009861, dtype: object

(9,)

tconst                       tt11833314
titleType                     tvEpisode
primaryTitle      'Til Death Do Us Part
originalTitle     'Til Death Do Us Part
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       42
genres             Comedy,Drama,Romance
Name: 2009862, dtype: object

(9,)

tconst                               tt11833318
titleType                             tvEpisode
primaryTitle      Indica Fetish- Swimsuit Bound
originalTitle     Indica Fetish- Swimsuit Bound
isAdult                                       1
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2009863, dtype: object

(9,)

tconst                             tt1183331
titleType                          tvEpisode
primaryTitle            Toro Toro Torosaurus
originalTitle           Toro Toro Torosaurus
isAdult                                    0
startYear                               1988
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2009864, dtype: object

(9,)

tconst                            tt11833322
titleType                          tvEpisode
primaryTitle      Alex Coal- The Game Part 1
originalTitle     Alex Coal- The Game Part 1
isAdult                                    1
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2009865, dtype: object

(9,)

tconst                            tt11833324
titleType                          tvEpisode
primaryTitle      Anal Training of Lena Love
originalTitle     Anal Training of Lena Love
isAdult                                    0
startYear                               2013
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2009866, dtype: object

(9,)

tconst                                                   tt11833326
titleType                                                 tvEpisode
primaryTitle      G.I. Joe - Hasbro 6" Snake Eyes Figure Leaks O...
originalTitle     G.I. Joe - Hasbro 6" Snake Eyes Figure Leaks O...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2009867, dtype: object

(9,)

tconst                                             tt11833328
titleType                                           tvEpisode
primaryTitle      Lydia Helpless In Arm Binder Bondage Sleeve
originalTitle     Lydia Helpless In Arm Binder Bondage Sleeve
isAdult                                                     1
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                  Adult
Name: 2009868, dtype: object

(9,)

tconst                             tt1183332
titleType                       tvMiniSeries
primaryTitle      Fine Gael: A Family at War
originalTitle     Fine Gael: A Family at War
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            52
genres                           Documentary
Name: 2009869, dtype: object

(9,)

tconst               tt11833330
titleType             tvSpecial
primaryTitle      MR WORLD 2019
originalTitle     MR WORLD 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009870, dtype: object

(9,)

tconst                 tt11833332
titleType               tvEpisode
primaryTitle      A New Challenge
originalTitle     A New Challenge
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 23
genres            Animation,Music
Name: 2009871, dtype: object

(9,)

tconst                                                   tt11833336
titleType                                                 tvEpisode
primaryTitle      Anal Toying Girl Loses Her Virgin Ass to a Big...
originalTitle     Anal Toying Girl Loses Her Virgin Ass to a Big...
isAdult                                                           1
startYear                                                      2012
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2009872, dtype: object

(9,)

tconst                      tt11833338
titleType                    tvEpisode
primaryTitle             Episode #1.21
originalTitle            Episode #1.21
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009873, dtype: object

(9,)

tconst                     tt1183333
titleType                   tvSeries
primaryTitle      The Growing Summer
originalTitle     The Growing Summer
isAdult                            0
startYear                       1968
endYear                           \N
runtimeMinutes                    \N
genres                        Family
Name: 2009874, dtype: object

(9,)

tconst                     tt11833340
titleType                       short
primaryTitle      Arman Licina - Moët
originalTitle     Arman Licina - Moët
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                    Music,Short
Name: 2009875, dtype: object

(9,)

tconst                                                   tt11833342
titleType                                                 tvEpisode
primaryTitle      First Anal Fucking for an Inexperienced Teen V...
originalTitle     First Anal Fucking for an Inexperienced Teen V...
isAdult                                                           1
startYear                                                      2015
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2009876, dtype: object

(9,)

tconst                      tt11833344
titleType                    tvEpisode
primaryTitle             Episode #1.22
originalTitle            Episode #1.22
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009877, dtype: object

(9,)

tconst                   tt11833346
titleType                 tvEpisode
primaryTitle      Celeb Look-a-like
originalTitle     Celeb Look-a-like
isAdult                           1
startYear                      2011
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2009878, dtype: object

(9,)

tconst                      tt11833348
titleType                    tvEpisode
primaryTitle             Episode #1.23
originalTitle            Episode #1.23
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009879, dtype: object

(9,)

tconst               tt1183334
titleType         tvMiniSeries
primaryTitle           Haughey
originalTitle          Haughey
isAdult                      0
startYear                 2005
endYear                     \N
runtimeMinutes              52
genres             Documentary
Name: 2009880, dtype: object

(9,)

tconst                tt11833350
titleType              tvEpisode
primaryTitle         Épisode 666
originalTitle        Épisode 666
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                28
genres            Crime,Thriller
Name: 2009881, dtype: object

(9,)

tconst                      tt11833352
titleType                    tvEpisode
primaryTitle             Episode #1.24
originalTitle            Episode #1.24
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009882, dtype: object

(9,)

tconst                      tt11833354
titleType                    tvEpisode
primaryTitle             Episode #1.25
originalTitle            Episode #1.25
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009883, dtype: object

(9,)

tconst                                                   tt11833356
titleType                                                 tvEpisode
primaryTitle      Sexy student gets fucked hard in casting inter...
originalTitle     Sexy student gets fucked hard in casting inter...
isAdult                                                           1
startYear                                                      2015
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2009884, dtype: object

(9,)

tconst                      tt11833358
titleType                    tvEpisode
primaryTitle             Episode #1.26
originalTitle            Episode #1.26
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009885, dtype: object

(9,)

tconst                      tt1183335
titleType                    tvSeries
primaryTitle      The Hotel Inspector
originalTitle     The Hotel Inspector
isAdult                             0
startYear                        2005
endYear                            \N
runtimeMinutes                     60
genres                    Documentary
Name: 2009886, dtype: object

(9,)

tconst                      tt11833360
titleType                    tvEpisode
primaryTitle             Episode #1.27
originalTitle            Episode #1.27
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009887, dtype: object

(9,)

tconst                   tt11833362
titleType                 tvEpisode
primaryTitle      Casting Call (II)
originalTitle     Casting Call (II)
isAdult                           1
startYear                      2012
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2009888, dtype: object

(9,)

tconst                      tt11833364
titleType                    tvEpisode
primaryTitle             Episode #1.28
originalTitle            Episode #1.28
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009889, dtype: object

(9,)

tconst            tt11833366
titleType          tvEpisode
primaryTitle       Lina Love
originalTitle      Lina Love
isAdult                    1
startYear               2016
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2009890, dtype: object

(9,)

tconst                                  tt11833368
titleType                                tvEpisode
primaryTitle      Why do people hate THE I-LAND???
originalTitle     Why do people hate THE I-LAND???
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                      Comedy
Name: 2009891, dtype: object

(9,)

tconst                 tt1183336
titleType           tvMiniSeries
primaryTitle      Junior Doctors
originalTitle     Junior Doctors
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                40
genres               Documentary
Name: 2009892, dtype: object

(9,)

tconst                      tt11833370
titleType                    tvEpisode
primaryTitle             Episode #1.29
originalTitle            Episode #1.29
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009893, dtype: object

(9,)

tconst                     tt11833372
titleType                   tvEpisode
primaryTitle      Haunted House Tease
originalTitle     Haunted House Tease
isAdult                             1
startYear                        2012
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2009894, dtype: object

(9,)

tconst                      tt11833374
titleType                    tvEpisode
primaryTitle             Episode #1.30
originalTitle            Episode #1.30
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009895, dtype: object

(9,)

tconst                                     tt11833376
titleType                                   tvSpecial
primaryTitle      106 & Park Live from the BET Awards
originalTitle     106 & Park Live from the BET Awards
isAdult                                             0
startYear                                        2016
endYear                                            \N
runtimeMinutes                                     \N
genres                                             \N
Name: 2009896, dtype: object

(9,)

tconst                      tt11833378
titleType                    tvEpisode
primaryTitle             Episode #1.31
originalTitle            Episode #1.31
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009897, dtype: object

(9,)

tconst                          tt1183337
titleType                       tvEpisode
primaryTitle               Double Trouble
originalTitle              Double Trouble
isAdult                                 0
startYear                            2006
endYear                                \N
runtimeMinutes                         23
genres            Adventure,Comedy,Family
Name: 2009898, dtype: object

(9,)

tconst                      tt11833380
titleType                    tvEpisode
primaryTitle             Episode #1.32
originalTitle            Episode #1.32
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009899, dtype: object

(9,)

tconst            tt11833382
titleType          tvEpisode
primaryTitle      Booty Call
originalTitle     Booty Call
isAdult                    1
startYear               2012
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2009900, dtype: object

(9,)

tconst                      tt11833384
titleType                    tvEpisode
primaryTitle             Episode #1.33
originalTitle            Episode #1.33
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009901, dtype: object

(9,)

tconst               tt11833386
titleType             tvEpisode
primaryTitle      Episode #3.91
originalTitle     Episode #3.91
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009902, dtype: object

(9,)

tconst              tt11833388
titleType             tvSeries
primaryTitle      Danger Force
originalTitle     Danger Force
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              30
genres                  Comedy
Name: 2009903, dtype: object

(9,)

tconst                          tt1183338
titleType                       tvEpisode
primaryTitle             Once Upon a Time
originalTitle            Once Upon a Time
isAdult                                 0
startYear                            2007
endYear                                \N
runtimeMinutes                         23
genres            Adventure,Comedy,Family
Name: 2009904, dtype: object

(9,)

tconst               tt11833390
titleType             tvEpisode
primaryTitle      Episode #3.92
originalTitle     Episode #3.92
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009905, dtype: object

(9,)

tconst                      tt11833392
titleType                    tvEpisode
primaryTitle             Episode #1.34
originalTitle            Episode #1.34
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009906, dtype: object

(9,)

tconst               tt11833394
titleType             tvEpisode
primaryTitle      Episode #3.93
originalTitle     Episode #3.93
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009907, dtype: object

(9,)

tconst                      tt11833396
titleType                    tvEpisode
primaryTitle             Episode #1.35
originalTitle            Episode #1.35
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2009908, dtype: object

(9,)

tconst               tt11833398
titleType             tvEpisode
primaryTitle      Episode #3.94
originalTitle     Episode #3.94
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009909, dtype: object

(9,)

tconst                          tt1183339
titleType                       tvEpisode
primaryTitle                     Pixel TV
originalTitle                    Pixel TV
isAdult                                 0
startYear                            2007
endYear                                \N
runtimeMinutes                         23
genres            Adventure,Comedy,Family
Name: 2009910, dtype: object

(9,)

tconst                    tt11833400
titleType                  tvEpisode
primaryTitle      Fucking the Police
originalTitle     Fucking the Police
isAdult                            1
startYear                       2012
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2009911, dtype: object

(9,)

tconst                          tt11833402
titleType                         tvSeries
primaryTitle      Paranormal Psycho Chicks
originalTitle     Paranormal Psycho Chicks
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          30
genres                              Comedy
Name: 2009912, dtype: object

(9,)

tconst               tt11833404
titleType             tvEpisode
primaryTitle      Episode #3.95
originalTitle     Episode #3.95
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009913, dtype: object

(9,)

tconst                    tt11833406
titleType                  tvEpisode
primaryTitle      First Time Jitters
originalTitle     First Time Jitters
isAdult                            1
startYear                       2012
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2009914, dtype: object

(9,)

tconst                             tt11833408
titleType                               movie
primaryTitle      The Minute You Wake Up Dead
originalTitle     The Minute You Wake Up Dead
isAdult                                     0
startYear                                  \N
endYear                                    \N
runtimeMinutes                             \N
genres                               Thriller
Name: 2009915, dtype: object

(9,)

tconst                           tt1183340
titleType                        tvEpisode
primaryTitle      Sportacus Saves the Toys
originalTitle     Sportacus Saves the Toys
isAdult                                  0
startYear                             2007
endYear                                 \N
runtimeMinutes                          23
genres             Adventure,Comedy,Family
Name: 2009916, dtype: object

(9,)

tconst                tt11833410
titleType              tvEpisode
primaryTitle      Posterior Play
originalTitle     Posterior Play
isAdult                        1
startYear                   2015
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2009917, dtype: object

(9,)

tconst                   tt11833412
titleType                 tvEpisode
primaryTitle      Sneaky Sneak Milf
originalTitle     Sneaky Sneak Milf
isAdult                           1
startYear                      2012
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2009918, dtype: object

(9,)

tconst                              tt11833414
titleType                            tvEpisode
primaryTitle      Kenya Moore & Mercedes Javid
originalTitle     Kenya Moore & Mercedes Javid
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2009919, dtype: object

(9,)

tconst            tt11833416
titleType          tvEpisode
primaryTitle        Premiere
originalTitle       Premiere
isAdult                    0
startYear               2004
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2009920, dtype: object

(9,)

tconst            tt11833418
titleType          tvEpisode
primaryTitle            Lina
originalTitle           Lina
isAdult                    1
startYear               2012
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2009921, dtype: object

(9,)

tconst                          tt1183341
titleType                       tvEpisode
primaryTitle               The Lazy Genie
originalTitle              The Lazy Genie
isAdult                                 0
startYear                            2007
endYear                                \N
runtimeMinutes                         23
genres            Adventure,Comedy,Family
Name: 2009922, dtype: object

(9,)

tconst                  tt11833420
titleType                tvEpisode
primaryTitle          Episode #7.5
originalTitle         Episode #7.5
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2009923, dtype: object

(9,)

tconst                   tt11833422
titleType                 tvEpisode
primaryTitle      Hot Anal Brunette
originalTitle     Hot Anal Brunette
isAdult                           1
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2009924, dtype: object

(9,)

tconst                  tt11833424
titleType                tvEpisode
primaryTitle      Kinky Tour Guide
originalTitle     Kinky Tour Guide
isAdult                          1
startYear                     2012
endYear                         \N
runtimeMinutes                  \N
genres                       Adult
Name: 2009925, dtype: object

(9,)

tconst            tt11833426
titleType          tvEpisode
primaryTitle            Lina
originalTitle           Lina
isAdult                    1
startYear               2012
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2009926, dtype: object

(9,)

tconst                         tt11833428
titleType                       tvEpisode
primaryTitle      High Class Working Girl
originalTitle     High Class Working Girl
isAdult                                 1
startYear                            2012
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2009927, dtype: object

(9,)

tconst                          tt1183342
titleType                       tvEpisode
primaryTitle                Trash Trouble
originalTitle               Trash Trouble
isAdult                                 0
startYear                            2006
endYear                                \N
runtimeMinutes                         23
genres            Adventure,Comedy,Family
Name: 2009928, dtype: object

(9,)

tconst                   tt11833430
titleType                     video
primaryTitle       The Walking Dog!
originalTitle      The Walking Dog!
isAdult                           0
startYear                      2016
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2009929, dtype: object

(9,)

tconst                              tt11833432
titleType                            tvEpisode
primaryTitle      Issa Rae & LaKeith Stanfield
originalTitle     Issa Rae & LaKeith Stanfield
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              21
genres                               Talk-Show
Name: 2009930, dtype: object

(9,)

tconst                   tt11833434
titleType                 tvEpisode
primaryTitle      Let's Make a Deal
originalTitle     Let's Make a Deal
isAdult                           1
startYear                      2012
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2009931, dtype: object

(9,)

tconst                                               tt11833436
titleType                                                 movie
primaryTitle      Shi da qiangji yaofan zhi shasheng zhuangyuan
originalTitle     Shi da qiangji yaofan zhi shasheng zhuangyuan
isAdult                                                       0
startYear                                                  1993
endYear                                                      \N
runtimeMinutes                                               94
genres                                                 Thriller
Name: 2009932, dtype: object

(9,)

tconst                tt11833438
titleType              tvEpisode
primaryTitle      Lina X Casting
originalTitle     Lina X Casting
isAdult                        1
startYear                   2013
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2009933, dtype: object

(9,)

tconst               tt1183343
titleType             tvSeries
primaryTitle      Llama y gana
originalTitle     Llama y gana
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              30
genres               Game-Show
Name: 2009934, dtype: object

(9,)

tconst                                  tt11833440
titleType                                tvEpisode
primaryTitle      MORAL DILEMMAS!! (RDR2 Gameplay)
originalTitle     MORAL DILEMMAS!! (RDR2 Gameplay)
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                   9
genres                                      Comedy
Name: 2009935, dtype: object

(9,)

tconst                  tt11833442
titleType                tvEpisode
primaryTitle       Episode #1.1000
originalTitle      Episode #1.1000
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009936, dtype: object

(9,)

tconst                 tt11833444
titleType               tvEpisode
primaryTitle      Episode #1.2498
originalTitle     Episode #1.2498
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                 60
genres                         \N
Name: 2009937, dtype: object

(9,)

tconst                   tt11833446
titleType              tvMiniSeries
primaryTitle            Murder 24/7
originalTitle           Murder 24/7
isAdult                           0
startYear                      2020
endYear                        2020
runtimeMinutes                   \N
genres            Crime,Documentary
Name: 2009938, dtype: object

(9,)

tconst              tt11833448
titleType            tvEpisode
primaryTitle      Paid in Full
originalTitle     Paid in Full
isAdult                      1
startYear                 2012
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2009939, dtype: object

(9,)

tconst                      tt1183344
titleType                    tvSeries
primaryTitle      The People Watchers
originalTitle     The People Watchers
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2009940, dtype: object

(9,)

tconst                  tt11833450
titleType                tvEpisode
primaryTitle       Episode #1.1001
originalTitle      Episode #1.1001
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009941, dtype: object

(9,)

tconst                          tt11833452
titleType                        tvEpisode
primaryTitle      A Present for Miss Julie
originalTitle     A Present for Miss Julie
isAdult                                  0
startYear                             1962
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2009942, dtype: object

(9,)

tconst                  tt11833454
titleType                tvEpisode
primaryTitle       Episode #1.1002
originalTitle      Episode #1.1002
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009943, dtype: object

(9,)

tconst               tt11833456
titleType             tvEpisode
primaryTitle      Episode #4.90
originalTitle     Episode #4.90
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2009944, dtype: object

(9,)

tconst                      tt11833458
titleType                    tvEpisode
primaryTitle      Schließe deine Augen
originalTitle     Schließe deine Augen
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      90
genres                           Crime
Name: 2009945, dtype: object

(9,)

tconst                                 tt1183345
titleType                              tvEpisode
primaryTitle      A Pretty Girl Is Like a Malady
originalTitle     A Pretty Girl Is Like a Malady
isAdult                                        0
startYear                                   1998
endYear                                       \N
runtimeMinutes                                \N
genres                    Action,Animation,Crime
Name: 2009946, dtype: object

(9,)

tconst                  tt11833460
titleType                tvEpisode
primaryTitle       Episode #1.1003
originalTitle      Episode #1.1003
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009947, dtype: object

(9,)

tconst                  tt11833462
titleType                tvEpisode
primaryTitle       Episode #1.1004
originalTitle      Episode #1.1004
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009948, dtype: object

(9,)

tconst               tt11833464
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009949, dtype: object

(9,)

tconst                                                 tt11833466
titleType                                               tvEpisode
primaryTitle      Adventurous girl goes for real wild outdoor sex
originalTitle     Adventurous girl goes for real wild outdoor sex
isAdult                                                         1
startYear                                                    2015
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                      Adult
Name: 2009950, dtype: object

(9,)

tconst                   tt11833468
titleType                 tvEpisode
primaryTitle      Let's Add a Third
originalTitle     Let's Add a Third
isAdult                           1
startYear                      2012
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2009951, dtype: object

(9,)

tconst                          tt1183346
titleType                       tvEpisode
primaryTitle      Really, Really Big Shoo
originalTitle     Really, Really Big Shoo
isAdult                                 0
startYear                            1998
endYear                                \N
runtimeMinutes                         \N
genres             Action,Animation,Crime
Name: 2009952, dtype: object

(9,)

tconst               tt11833470
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009953, dtype: object

(9,)

tconst                  tt11833474
titleType                tvEpisode
primaryTitle       Episode #1.1005
originalTitle      Episode #1.1005
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009954, dtype: object

(9,)

tconst               tt11833476
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009955, dtype: object

(9,)

tconst                       tt1183347
titleType                     tvSeries
primaryTitle      Shimokita Glory Days
originalTitle     Shimokita Glory Days
isAdult                              0
startYear                         2006
endYear                             \N
runtimeMinutes                      30
genres                    Comedy,Drama
Name: 2009956, dtype: object

(9,)

tconst                                                   tt11833480
titleType                                                 tvEpisode
primaryTitle      LGR Oddware - DOS PC Action Replay: The Ultima...
originalTitle     LGR Oddware - DOS PC Action Replay: The Ultima...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                   Reality-TV
Name: 2009957, dtype: object

(9,)

tconst                              tt11833482
titleType                            tvEpisode
primaryTitle      Gorgey Georgie Comes to Stay
originalTitle     Gorgey Georgie Comes to Stay
isAdult                                      0
startYear                                 1962
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2009958, dtype: object

(9,)

tconst               tt11833484
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009959, dtype: object

(9,)

tconst                  tt11833486
titleType                tvEpisode
primaryTitle       Episode #1.1006
originalTitle      Episode #1.1006
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009960, dtype: object

(9,)

tconst                  tt11833488
titleType                tvEpisode
primaryTitle       Episode #1.1007
originalTitle      Episode #1.1007
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009961, dtype: object

(9,)

tconst                            tt11833490
titleType                              short
primaryTitle      Untitled Fairy tale Horror
originalTitle     Untitled Fairy tale Horror
isAdult                                    0
startYear                                 \N
endYear                                   \N
runtimeMinutes                            \N
genres                          Horror,Short
Name: 2009962, dtype: object

(9,)

tconst                  tt11833492
titleType                tvEpisode
primaryTitle       Episode #1.1008
originalTitle      Episode #1.1008
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009963, dtype: object

(9,)

tconst                             tt11833494
titleType                        tvMiniSeries
primaryTitle      Unabomber: In His Own Words
originalTitle     Unabomber: In His Own Words
isAdult                                     0
startYear                                2020
endYear                                  2020
runtimeMinutes                            175
genres            Biography,Crime,Documentary
Name: 2009964, dtype: object

(9,)

tconst                  tt11833496
titleType                tvEpisode
primaryTitle       Episode #1.1009
originalTitle      Episode #1.1009
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009965, dtype: object

(9,)

tconst                  tt11833498
titleType                tvEpisode
primaryTitle       Episode #1.1010
originalTitle      Episode #1.1010
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009966, dtype: object

(9,)

tconst                               tt1183349
titleType                            tvEpisode
primaryTitle      Music for When We Feel Bored
originalTitle     Music for When We Feel Bored
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                                  Comedy
Name: 2009967, dtype: object

(9,)

tconst                                        tt11833500
titleType                                      tvEpisode
primaryTitle      11-Year-Old Makes Your Car Smell Fresh
originalTitle     11-Year-Old Makes Your Car Smell Fresh
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        \N
genres                                       Documentary
Name: 2009968, dtype: object

(9,)

tconst            tt11833502
titleType          tvEpisode
primaryTitle      Two on One
originalTitle     Two on One
isAdult                    1
startYear               2012
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2009969, dtype: object

(9,)

tconst                  tt11833504
titleType                tvEpisode
primaryTitle       Episode #1.1011
originalTitle      Episode #1.1011
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009970, dtype: object

(9,)

tconst               tt11833506
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009971, dtype: object

(9,)

tconst                          tt1183350
titleType                       tvEpisode
primaryTitle      Music to Spin Around To
originalTitle     Music to Spin Around To
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                             Comedy
Name: 2009972, dtype: object

(9,)

tconst                             tt11833510
titleType                               video
primaryTitle      Yolo Aventuras: Por un beso
originalTitle     Yolo Aventuras: Por un beso
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                              3
genres                            Music,Short
Name: 2009973, dtype: object

(9,)

tconst                  tt11833512
titleType                tvEpisode
primaryTitle       Episode #1.1012
originalTitle      Episode #1.1012
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009974, dtype: object

(9,)

tconst               tt11833514
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009975, dtype: object

(9,)

tconst                   tt11833516
titleType                     short
primaryTitle       A Dream Deferred
originalTitle      A Dream Deferred
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   17
genres            Documentary,Short
Name: 2009976, dtype: object

(9,)

tconst                                  tt11833518
titleType                                tvEpisode
primaryTitle      La drástica decisión de Agustina
originalTitle     La drástica decisión de Agustina
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Drama
Name: 2009977, dtype: object

(9,)

tconst                tt1183351
titleType              tvSeries
primaryTitle      El ventilador
originalTitle     El ventilador
isAdult                       0
startYear                  2007
endYear                    2008
runtimeMinutes              120
genres                Talk-Show
Name: 2009978, dtype: object

(9,)

tconst                    tt11833520
titleType                      short
primaryTitle      Den gode samariten
originalTitle     Den gode samariten
isAdult                            0
startYear                       2021
endYear                           \N
runtimeMinutes                    \N
genres                Short,Thriller
Name: 2009979, dtype: object

(9,)

tconst                  tt11833522
titleType                tvEpisode
primaryTitle       Episode #1.1013
originalTitle      Episode #1.1013
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009980, dtype: object

(9,)

tconst                        tt11833524
titleType                      tvEpisode
primaryTitle      I'm Not Going to Class
originalTitle     I'm Not Going to Class
isAdult                                1
startYear                           2012
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2009981, dtype: object

(9,)

tconst                                                   tt11833526
titleType                                                 tvEpisode
primaryTitle      Science-types Fell in Love, So They Tried Atte...
originalTitle     Science-types Fell in Love, So They Tried Atte...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                     Animation,Comedy,Romance
Name: 2009982, dtype: object

(9,)

tconst               tt11833528
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009983, dtype: object

(9,)

tconst                             tt1183352
titleType                              movie
primaryTitle                     Ana y Bruno
originalTitle                    Ana y Bruno
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            96
genres            Action,Adventure,Animation
Name: 2009984, dtype: object

(9,)

tconst                                                   tt11833530
titleType                                                 tvEpisode
primaryTitle      Science-types Fell in Love, So They Tried Givi...
originalTitle     Science-types Fell in Love, So They Tried Givi...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                     Animation,Comedy,Romance
Name: 2009985, dtype: object

(9,)

tconst                                        tt11833532
titleType                                      tvEpisode
primaryTitle      Frodo Calls Out The Rise Of Skywalker!
originalTitle     Frodo Calls Out The Rise Of Skywalker!
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        \N
genres                                         Talk-Show
Name: 2009986, dtype: object

(9,)

tconst                  tt11833534
titleType                tvEpisode
primaryTitle       Episode #1.1014
originalTitle      Episode #1.1014
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009987, dtype: object

(9,)

tconst                                                   tt11833536
titleType                                                 tvEpisode
primaryTitle      Science-types Fell in Love, So They Tried Havi...
originalTitle     Science-types Fell in Love, So They Tried Havi...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                     Animation,Comedy,Romance
Name: 2009988, dtype: object

(9,)

tconst                                                tt11833538
titleType                                                  movie
primaryTitle      Triumph & tragedy on the World's Greatest Reef
originalTitle     Triumph & tragedy on the World's Greatest Reef
isAdult                                                        0
startYear                                                   1998
endYear                                                       \N
runtimeMinutes                                                49
genres                                               Documentary
Name: 2009989, dtype: object

(9,)

tconst                                tt1183353
titleType                               tvShort
primaryTitle      The Antique 'Doctor Who' Show
originalTitle     The Antique 'Doctor Who' Show
isAdult                                       0
startYear                                  1993
endYear                                      \N
runtimeMinutes                                5
genres                        Documentary,Short
Name: 2009990, dtype: object

(9,)

tconst               tt11833540
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009991, dtype: object

(9,)

tconst                           tt11833542
titleType                         tvEpisode
primaryTitle      Sara and Father Christmas
originalTitle     Sara and Father Christmas
isAdult                                   0
startYear                              1962
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2009992, dtype: object

(9,)

tconst                                                   tt11833544
titleType                                                 tvEpisode
primaryTitle      I Knew I Could Fall in Love with You, So I Tri...
originalTitle     I Knew I Could Fall in Love with You, So I Tri...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                     Animation,Comedy,Romance
Name: 2009993, dtype: object

(9,)

tconst                                tt11833546
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                52
genres                                        \N
Name: 2009994, dtype: object

(9,)

tconst                    tt1183354
titleType                     movie
primaryTitle      Bang! You're Dead
originalTitle     Bang! You're Dead
isAdult                           0
startYear                      2002
endYear                          \N
runtimeMinutes                   52
genres                  Documentary
Name: 2009995, dtype: object

(9,)

tconst                  tt11833550
titleType                tvEpisode
primaryTitle       Episode #1.1015
originalTitle      Episode #1.1015
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2009996, dtype: object

(9,)

tconst               tt11833552
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2009997, dtype: object

(9,)

tconst                      tt11833554
titleType                    tvEpisode
primaryTitle      Freshman Orientation
originalTitle     Freshman Orientation
isAdult                              1
startYear                         2012
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2009998, dtype: object

(9,)

tconst                            tt11833556
titleType                          tvEpisode
primaryTitle      Episode dated 6 March 2020
originalTitle     Episode dated 6 March 2020
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            52
genres                                    \N
Name: 2009999, dtype: object

(9,)

tconst                                          tt11833558
titleType                                        tvEpisode
primaryTitle      Top 10 Times Robots Beat Humans at Games
originalTitle     Top 10 Times Robots Beat Humans at Games
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                    Comedy,Talk-Show
Name: 2010000, dtype: object

(9,)

tconst                         tt1183355
titleType                        tvShort
primaryTitle      Bigger Inside Than Out
originalTitle     Bigger Inside Than Out
isAdult                                0
startYear                           1993
endYear                               \N
runtimeMinutes                         4
genres                 Documentary,Short
Name: 2010001, dtype: object

(9,)

tconst                  tt11833560
titleType                tvEpisode
primaryTitle       Episode #1.1016
originalTitle      Episode #1.1016
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010002, dtype: object

(9,)

tconst                              tt11833562
titleType                            tvEpisode
primaryTitle      Jenni & Skarlet - Meal TIME!
originalTitle     Jenni & Skarlet - Meal TIME!
isAdult                                      1
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010003, dtype: object

(9,)

tconst                  tt11833564
titleType                tvEpisode
primaryTitle       Episode #1.1017
originalTitle      Episode #1.1017
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010004, dtype: object

(9,)

tconst               tt11833566
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2010005, dtype: object

(9,)

tconst                      tt11833568
titleType                    tvEpisode
primaryTitle        Poor Wandering One
originalTitle       Poor Wandering One
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      42
genres            Action,Drama,Romance
Name: 2010006, dtype: object

(9,)

tconst                      tt1183356
titleType                       movie
primaryTitle      The White She-Camel
originalTitle     La chamelle blanche
isAdult                             0
startYear                        2006
endYear                            \N
runtimeMinutes                     52
genres                    Documentary
Name: 2010007, dtype: object

(9,)

tconst                  tt11833570
titleType                tvEpisode
primaryTitle       Episode #1.1018
originalTitle      Episode #1.1018
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010008, dtype: object

(9,)

tconst               tt11833572
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2010009, dtype: object

(9,)

tconst                  tt11833574
titleType                tvEpisode
primaryTitle       Episode #1.1019
originalTitle      Episode #1.1019
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010010, dtype: object

(9,)

tconst                              tt11833576
titleType                            tvEpisode
primaryTitle                   Daylight (1996)
originalTitle                  Daylight (1996)
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres            Action,Animation,Documentary
Name: 2010011, dtype: object

(9,)

tconst                  tt11833578
titleType                tvEpisode
primaryTitle       Episode #1.1020
originalTitle      Episode #1.1020
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010012, dtype: object

(9,)

tconst                     tt1183357
titleType                      movie
primaryTitle      An Charraig Stoite
originalTitle     An Charraig Stoite
isAdult                            0
startYear                       2003
endYear                           \N
runtimeMinutes                    54
genres                   Documentary
Name: 2010013, dtype: object

(9,)

tconst                  tt11833580
titleType                tvEpisode
primaryTitle       Episode #1.1021
originalTitle      Episode #1.1021
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010014, dtype: object

(9,)

tconst               tt11833582
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2010015, dtype: object

(9,)

tconst                 tt11833584
titleType               tvEpisode
primaryTitle      The Awful Truth
originalTitle     The Awful Truth
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2010016, dtype: object

(9,)

tconst                                  tt11833586
titleType                                    video
primaryTitle      Jesse & Joy: Lo nuestro vale más
originalTitle     Jesse & Joy: Lo nuestro vale más
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                   4
genres                                 Music,Short
Name: 2010017, dtype: object

(9,)

tconst                  tt11833588
titleType                tvEpisode
primaryTitle       Episode #1.1022
originalTitle      Episode #1.1022
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010018, dtype: object

(9,)

tconst                       tt1183358
titleType                      tvMovie
primaryTitle      Christine's Children
originalTitle     Christine's Children
isAdult                              0
startYear                         2003
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2010019, dtype: object

(9,)

tconst               tt11833590
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2010020, dtype: object

(9,)

tconst               tt11833592
titleType                 movie
primaryTitle      Hai Tang Hong
originalTitle     Hai Tang Hong
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               90
genres                       \N
Name: 2010021, dtype: object

(9,)

tconst                           tt11833594
titleType                         tvEpisode
primaryTitle      Aunt Mathilda's New Dress
originalTitle     Aunt Mathilda's New Dress
isAdult                                   0
startYear                              1962
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2010022, dtype: object

(9,)

tconst                     tt11833596
titleType                       movie
primaryTitle      Murder by Deception
originalTitle     Murder by Deception
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres                          Crime
Name: 2010023, dtype: object

(9,)

tconst                  tt11833598
titleType                tvEpisode
primaryTitle       Episode #1.1023
originalTitle      Episode #1.1023
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010024, dtype: object

(9,)

tconst              tt1183359
titleType             tvMovie
primaryTitle            Crash
originalTitle           Crash
isAdult                     0
startYear                2003
endYear                    \N
runtimeMinutes             52
genres            Documentary
Name: 2010025, dtype: object

(9,)

tconst               tt11833600
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                  1985
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2010026, dtype: object

(9,)

tconst                  tt11833602
titleType                tvEpisode
primaryTitle       Episode #1.1024
originalTitle      Episode #1.1024
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010027, dtype: object

(9,)

tconst                                     tt11833604
titleType                                   tvEpisode
primaryTitle      Jim Carrey is SSSSMOKIN' The Mask!!
originalTitle     Jim Carrey is SSSSMOKIN' The Mask!!
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                      Talk-Show
Name: 2010028, dtype: object

(9,)

tconst                 tt11833606
titleType                   video
primaryTitle      Myke Towers: Tú
originalTitle     Myke Towers: Tú
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                  3
genres                Music,Short
Name: 2010029, dtype: object

(9,)

tconst                         tt11833608
titleType                           movie
primaryTitle      Living with Polar Bears
originalTitle     Living with Polar Bears
isAdult                                 0
startYear                            2008
endYear                                \N
runtimeMinutes                         51
genres                        Documentary
Name: 2010030, dtype: object

(9,)

tconst                        tt1183360
titleType                       tvShort
primaryTitle      Crimefile: The Master
originalTitle     Crimefile: The Master
isAdult                               0
startYear                          1993
endYear                              \N
runtimeMinutes                        6
genres                Documentary,Short
Name: 2010031, dtype: object

(9,)

tconst                         tt11833610
titleType                       tvEpisode
primaryTitle              Episode #11.112
originalTitle             Episode #11.112
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         37
genres            Comedy,Family,Game-Show
Name: 2010032, dtype: object

(9,)

tconst                         tt11833612
titleType                       tvEpisode
primaryTitle              Episode #11.113
originalTitle             Episode #11.113
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres            Comedy,Family,Game-Show
Name: 2010033, dtype: object

(9,)

tconst                  tt11833614
titleType                tvEpisode
primaryTitle       Episode #1.1025
originalTitle      Episode #1.1025
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010034, dtype: object

(9,)

tconst                         tt11833616
titleType                       tvEpisode
primaryTitle               Episode #11.97
originalTitle              Episode #11.97
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         37
genres            Comedy,Family,Game-Show
Name: 2010035, dtype: object

(9,)

tconst                         tt11833618
titleType                       tvEpisode
primaryTitle               Episode #11.98
originalTitle              Episode #11.98
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres            Comedy,Family,Game-Show
Name: 2010036, dtype: object

(9,)

tconst               tt1183361
titleType                video
primaryTitle      Demon's Trap
originalTitle     Demon's Trap
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              97
genres                  Horror
Name: 2010037, dtype: object

(9,)

tconst                         tt11833620
titleType                       tvEpisode
primaryTitle               Episode #11.99
originalTitle              Episode #11.99
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         37
genres            Comedy,Family,Game-Show
Name: 2010038, dtype: object

(9,)

tconst                  tt11833622
titleType                tvEpisode
primaryTitle       Episode #1.1026
originalTitle      Episode #1.1026
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010039, dtype: object

(9,)

tconst                         tt11833624
titleType                       tvEpisode
primaryTitle              Episode #11.100
originalTitle             Episode #11.100
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         37
genres            Comedy,Family,Game-Show
Name: 2010040, dtype: object

(9,)

tconst                         tt11833626
titleType                       tvEpisode
primaryTitle              Episode #11.101
originalTitle             Episode #11.101
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         37
genres            Comedy,Family,Game-Show
Name: 2010041, dtype: object

(9,)

tconst               tt11833628
titleType              tvSeries
primaryTitle      Filthy Femdom
originalTitle     Filthy Femdom
isAdult                       1
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2010042, dtype: object

(9,)

tconst                             tt1183362
titleType                            tvMovie
primaryTitle      The Edwardian Family Album
originalTitle     The Edwardian Family Album
isAdult                                    0
startYear                               2007
endYear                                   \N
runtimeMinutes                            60
genres                           Documentary
Name: 2010043, dtype: object

(9,)

tconst                                 tt11833630
titleType                                   video
primaryTitle      Ashley Cordelia: All Join Hands
originalTitle     Ashley Cordelia: All Join Hands
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                  3
genres                                Music,Short
Name: 2010044, dtype: object

(9,)

tconst              tt11833632
titleType            tvEpisode
primaryTitle      Episode #2.1
originalTitle     Episode #2.1
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010045, dtype: object

(9,)

tconst                                  tt11833634
titleType                                    video
primaryTitle      Stephanie Poetri: Do You Love Me
originalTitle     Stephanie Poetri: Do You Love Me
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                   3
genres                                 Music,Short
Name: 2010046, dtype: object

(9,)

tconst                  tt11833636
titleType                tvEpisode
primaryTitle       Episode #1.1027
originalTitle      Episode #1.1027
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010047, dtype: object

(9,)

tconst                  tt11833638
titleType                tvEpisode
primaryTitle       Episode #1.1028
originalTitle      Episode #1.1028
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010048, dtype: object

(9,)

tconst                             tt1183363
titleType                          tvEpisode
primaryTitle      La guerre contre le cancer
originalTitle     La guerre contre le cancer
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            72
genres                           Documentary
Name: 2010049, dtype: object

(9,)

tconst              tt11833640
titleType            tvEpisode
primaryTitle      Episode #2.2
originalTitle     Episode #2.2
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010050, dtype: object

(9,)

tconst                                     tt11833642
titleType                                       movie
primaryTitle      A Million Dollars and A Machine Gun
originalTitle     A Million Dollars and A Machine Gun
isAdult                                             0
startYear                                          \N
endYear                                            \N
runtimeMinutes                                     \N
genres                                         Action
Name: 2010051, dtype: object

(9,)

tconst              tt11833644
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010052, dtype: object

(9,)

tconst              tt11833646
titleType            tvEpisode
primaryTitle      Episode #2.4
originalTitle     Episode #2.4
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010053, dtype: object

(9,)

tconst                   tt11833648
titleType                     movie
primaryTitle      The Sun of Gnosis
originalTitle      Shams Al-Ma'arif
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                  120
genres                       Comedy
Name: 2010054, dtype: object

(9,)

tconst                  tt1183364
titleType                 tvMovie
primaryTitle      A House Divided
originalTitle     A House Divided
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 75
genres                Documentary
Name: 2010055, dtype: object

(9,)

tconst                tt11833650
titleType                  movie
primaryTitle      Fabulous Foals
originalTitle     Fabulous Foals
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                52
genres               Documentary
Name: 2010056, dtype: object

(9,)

tconst              tt11833652
titleType            tvEpisode
primaryTitle      Episode #2.5
originalTitle     Episode #2.5
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010057, dtype: object

(9,)

tconst                  tt11833654
titleType                tvEpisode
primaryTitle       Episode #1.1029
originalTitle      Episode #1.1029
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010058, dtype: object

(9,)

tconst                  tt11833656
titleType                tvEpisode
primaryTitle       Episode #1.1030
originalTitle      Episode #1.1030
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010059, dtype: object

(9,)

tconst                        tt11833658
titleType                          video
primaryTitle      Saif Nabeel: Ma Dareit
originalTitle     Saif Nabeel: Ma Dareit
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                         4
genres                       Music,Short
Name: 2010060, dtype: object

(9,)

tconst                                                    tt1183365
titleType                                                     movie
primaryTitle      Islandman: The Story of the Last Trading Skipp...
originalTitle     Islandman: The Story of the Last Trading Skipp...
isAdult                                                           0
startYear                                                      2003
endYear                                                          \N
runtimeMinutes                                                   52
genres                                                  Documentary
Name: 2010061, dtype: object

(9,)

tconst              tt11833660
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010062, dtype: object

(9,)

tconst              tt11833662
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010063, dtype: object

(9,)

tconst              tt11833664
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010064, dtype: object

(9,)

tconst                                            tt11833666
titleType                                          tvEpisode
primaryTitle      Sonic The Hedgehog Proves The Fans Matter!
originalTitle     Sonic The Hedgehog Proves The Fans Matter!
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                             Talk-Show
Name: 2010065, dtype: object

(9,)

tconst              tt11833668
titleType            tvEpisode
primaryTitle      Episode #2.9
originalTitle     Episode #2.9
isAdult                      0
startYear                 1985
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010066, dtype: object

(9,)

tconst                           tt1183366
titleType                     tvMiniSeries
primaryTitle                      My Santa
originalTitle           Itsudatte my Santa
isAdult                                  0
startYear                             2005
endYear                                 \N
runtimeMinutes                          55
genres            Animation,Comedy,Romance
Name: 2010067, dtype: object

(9,)

tconst                tt11833670
titleType                  movie
primaryTitle      Last Shoot Out
originalTitle     Last Shoot Out
isAdult                        0
startYear                   2021
endYear                       \N
runtimeMinutes                \N
genres                   Western
Name: 2010068, dtype: object

(9,)

tconst                              tt11833672
titleType                                short
primaryTitle      Australia's Greatest Islands
originalTitle     Australia's Greatest Islands
isAdult                                      0
startYear                                 2006
endYear                                     \N
runtimeMinutes                              44
genres                       Documentary,Short
Name: 2010069, dtype: object

(9,)

tconst                                                tt11833674
titleType                                                  short
primaryTitle      Tech N9ne, Big Scoob, Darrien Saffron - LET GO
originalTitle     Tech N9ne, Big Scoob, Darrien Saffron - LET GO
isAdult                                                        0
startYear                                                   2017
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                     Short
Name: 2010070, dtype: object

(9,)

tconst                             tt11833676
titleType                           tvEpisode
primaryTitle      Episode dated 12 April 2013
originalTitle     Episode dated 12 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2010071, dtype: object

(9,)

tconst                             tt11833678
titleType                           tvEpisode
primaryTitle      Episode dated 16 April 2013
originalTitle     Episode dated 16 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2010072, dtype: object

(9,)

tconst                tt1183367
titleType               tvMovie
primaryTitle      King of Clubs
originalTitle     King of Clubs
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2010073, dtype: object

(9,)

tconst                             tt11833680
titleType                           tvEpisode
primaryTitle      Episode dated 17 April 2013
originalTitle     Episode dated 17 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2010074, dtype: object

(9,)

tconst                             tt11833682
titleType                           tvEpisode
primaryTitle      Episode dated 18 April 2013
originalTitle     Episode dated 18 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2010075, dtype: object

(9,)

tconst                             tt11833684
titleType                           tvEpisode
primaryTitle      Episode dated 19 April 2013
originalTitle     Episode dated 19 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2010076, dtype: object

(9,)

tconst                      tt11833686
titleType                        video
primaryTitle      Lyanno: En tu cuerpo
originalTitle     Lyanno: En tu cuerpo
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       4
genres                     Music,Short
Name: 2010077, dtype: object

(9,)

tconst                              tt11833688
titleType                            tvEpisode
primaryTitle      Episode dated 27 August 1985
originalTitle     Episode dated 27 August 1985
isAdult                                      0
startYear                                 1985
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2010078, dtype: object

(9,)

tconst                                                  tt1183368
titleType                                                   video
primaryTitle      The Ladies of the Evil Dead Meet Bruce Campbell
originalTitle     The Ladies of the Evil Dead Meet Bruce Campbell
isAdult                                                         0
startYear                                                    2007
endYear                                                        \N
runtimeMinutes                                                 29
genres                                                      Short
Name: 2010079, dtype: object

(9,)

tconst                  tt11833690
titleType                tvEpisode
primaryTitle       Episode #1.1031
originalTitle      Episode #1.1031
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010080, dtype: object

(9,)

tconst                      tt11833692
titleType                        movie
primaryTitle      The Desperate Riders
originalTitle     The Desperate Riders
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres                         Western
Name: 2010081, dtype: object

(9,)

tconst             tt11833694
titleType           tvEpisode
primaryTitle      revenge 1.1
originalTitle     revenge 1.1
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes             \N
genres                 Action
Name: 2010082, dtype: object

(9,)

tconst             tt11833696
titleType               movie
primaryTitle      On Thin Ice
originalTitle     On Thin Ice
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes             53
genres            Documentary
Name: 2010083, dtype: object

(9,)

tconst                             tt11833698
titleType                               video
primaryTitle      Kodak Black: Because of You
originalTitle     Kodak Black: Because of You
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                              3
genres                            Music,Short
Name: 2010084, dtype: object

(9,)

tconst                                               tt1183369
titleType                                                video
primaryTitle      Life After Dead: The Ladies of the Evil Dead
originalTitle     Life After Dead: The Ladies of the Evil Dead
isAdult                                                      0
startYear                                                 2007
endYear                                                     \N
runtimeMinutes                                              15
genres                                                   Short
Name: 2010085, dtype: object

(9,)

tconst                            tt11833700
titleType                          tvEpisode
primaryTitle      Below Deck Reunion Part II
originalTitle     Below Deck Reunion Part II
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2010086, dtype: object

(9,)

tconst                  tt11833702
titleType                tvEpisode
primaryTitle      Episode #1.10010
originalTitle     Episode #1.10010
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  22
genres               Drama,Romance
Name: 2010087, dtype: object

(9,)

tconst                 tt11833704
titleType               tvEpisode
primaryTitle             Ice Trae
originalTitle            Ice Trae
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                150
genres            Sport,Talk-Show
Name: 2010088, dtype: object

(9,)

tconst               tt11833706
titleType             tvEpisode
primaryTitle      Episode #2.34
originalTitle     Episode #2.34
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010089, dtype: object

(9,)

tconst                                     tt11833708
titleType                                       video
primaryTitle      YoungBoy Never Broke Again: Lil Top
originalTitle     YoungBoy Never Broke Again: Lil Top
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                      3
genres                                    Music,Short
Name: 2010090, dtype: object

(9,)

tconst                        tt1183370
titleType                         movie
primaryTitle      Living the Revolution
originalTitle     Living the Revolution
isAdult                               0
startYear                          2002
endYear                              \N
runtimeMinutes                       52
genres                      Documentary
Name: 2010091, dtype: object

(9,)

tconst                  tt11833710
titleType                    movie
primaryTitle      Catch the Bullet
originalTitle     Catch the Bullet
isAdult                          0
startYear                     2021
endYear                         \N
runtimeMinutes                  88
genres                     Western
Name: 2010092, dtype: object

(9,)

tconst                            tt11833712
titleType                          tvEpisode
primaryTitle      Episode dated 27 July 1989
originalTitle     Episode dated 27 July 1989
isAdult                                    0
startYear                               1989
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2010093, dtype: object

(9,)

tconst                                 tt11833714
titleType                               tvEpisode
primaryTitle      Episode dated 24 September 1985
originalTitle     Episode dated 24 September 1985
isAdult                                         0
startYear                                    1985
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2010094, dtype: object

(9,)

tconst                         tt11833716
titleType                           video
primaryTitle      Stephanie Poetri: Touch
originalTitle     Stephanie Poetri: Touch
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                          3
genres                        Music,Short
Name: 2010095, dtype: object

(9,)

tconst                               tt11833718
titleType                             tvEpisode
primaryTitle      Episode dated 22 October 1985
originalTitle     Episode dated 22 October 1985
isAdult                                       0
startYear                                  1985
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2010096, dtype: object

(9,)

tconst                                   tt1183371
titleType                                  tvMovie
primaryTitle      Mairtín Ó Cadhain: King of Words
originalTitle     Maírtín Ó Cadhain: Rí an Fhocail
isAdult                                          0
startYear                                     2006
endYear                                         \N
runtimeMinutes                                  52
genres                                 Documentary
Name: 2010097, dtype: object

(9,)

tconst                                                   tt11833720
titleType                                                 tvEpisode
primaryTitle      Shakedown: Chanel Preston Helps Daisy Ducati B...
originalTitle     Shakedown: Chanel Preston Helps Daisy Ducati B...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010098, dtype: object

(9,)

tconst                          tt11833722
titleType                        tvEpisode
primaryTitle      Melancholy Monday Part 1
originalTitle     Melancholy Monday Part 1
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                              Comedy
Name: 2010099, dtype: object

(9,)

tconst                      tt11833724
titleType                    tvEpisode
primaryTitle              Episode #1.1
originalTitle             Episode #1.1
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      48
genres            Crime,Drama,Thriller
Name: 2010100, dtype: object

(9,)

tconst                  tt11833726
titleType                tvEpisode
primaryTitle      The Jolly Diesel
originalTitle     The Jolly Diesel
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                   9
genres            Animation,Family
Name: 2010101, dtype: object

(9,)

tconst               tt11833728
titleType                 video
primaryTitle      Singga: Oscar
originalTitle     Singga: Oscar
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes                3
genres              Music,Short
Name: 2010102, dtype: object

(9,)

tconst                    tt1183372
titleType                   tvShort
primaryTitle      Missing in Action
originalTitle     Missing in Action
isAdult                           0
startYear                      1993
endYear                          \N
runtimeMinutes                    7
genres            Documentary,Short
Name: 2010103, dtype: object

(9,)

tconst                   tt11833730
titleType                     movie
primaryTitle      The Green Stadium
originalTitle     The Green Stadium
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   51
genres                  Documentary
Name: 2010104, dtype: object

(9,)

tconst                        tt11833732
titleType                          movie
primaryTitle      40 Years and One Night
originalTitle     40 Years and One Night
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                       125
genres                             Drama
Name: 2010105, dtype: object

(9,)

tconst                   tt11833734
titleType                     video
primaryTitle      Do as You're Told
originalTitle     Do as You're Told
isAdult                           1
startYear                      2018
endYear                          \N
runtimeMinutes                   60
genres                        Adult
Name: 2010106, dtype: object

(9,)

tconst                      tt11833736
titleType                    tvEpisode
primaryTitle              Episode #1.2
originalTitle             Episode #1.2
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010107, dtype: object

(9,)

tconst                   tt11833738
titleType                     movie
primaryTitle      Blood and Loyalty
originalTitle     Blood and Loyalty
isAdult                           0
startYear                        \N
endYear                          \N
runtimeMinutes                   \N
genres                        Crime
Name: 2010108, dtype: object

(9,)

tconst                tt1183373
titleType                 movie
primaryTitle        Tory Island
originalTitle     Oileán Thoraí
isAdult                       0
startYear                  2002
endYear                      \N
runtimeMinutes               52
genres              Documentary
Name: 2010109, dtype: object

(9,)

tconst                      tt11833740
titleType                    tvEpisode
primaryTitle              Episode #1.3
originalTitle             Episode #1.3
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010110, dtype: object

(9,)

tconst                      tt11833742
titleType                    tvEpisode
primaryTitle              Episode #1.4
originalTitle             Episode #1.4
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010111, dtype: object

(9,)

tconst                      tt11833744
titleType                    tvEpisode
primaryTitle              Episode #1.5
originalTitle             Episode #1.5
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010112, dtype: object

(9,)

tconst                  tt11833748
titleType                tvEpisode
primaryTitle       Episode #1.1032
originalTitle      Episode #1.1032
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010113, dtype: object

(9,)

tconst                  tt1183374
titleType                   movie
primaryTitle                  Pet
originalTitle                 Pet
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 94
genres            Horror,Thriller
Name: 2010114, dtype: object

(9,)

tconst                  tt11833750
titleType                tvEpisode
primaryTitle       Episode #1.1033
originalTitle      Episode #1.1033
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010115, dtype: object

(9,)

tconst                               tt11833752
titleType                             tvEpisode
primaryTitle      Episode dated 28 January 2020
originalTitle     Episode dated 28 January 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2010116, dtype: object

(9,)

tconst                  tt11833754
titleType                tvEpisode
primaryTitle       Episode #1.1034
originalTitle      Episode #1.1034
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010117, dtype: object

(9,)

tconst             tt11833756
titleType               short
primaryTitle      Out da Hood
originalTitle     Out da Hood
isAdult                     0
startYear                2017
endYear                    \N
runtimeMinutes             \N
genres                  Short
Name: 2010118, dtype: object

(9,)

tconst                  tt11833758
titleType                tvEpisode
primaryTitle       Episode #1.1035
originalTitle      Episode #1.1035
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010119, dtype: object

(9,)

tconst                    tt1183375
titleType                   tvMovie
primaryTitle      The Queen by Rolf
originalTitle     The Queen by Rolf
isAdult                           0
startYear                      2006
endYear                          \N
runtimeMinutes                   60
genres                  Documentary
Name: 2010120, dtype: object

(9,)

tconst                      tt11833760
titleType                    tvEpisode
primaryTitle              Episode #1.7
originalTitle             Episode #1.7
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010121, dtype: object

(9,)

tconst                  tt11833762
titleType                tvEpisode
primaryTitle       Episode #1.1036
originalTitle      Episode #1.1036
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010122, dtype: object

(9,)

tconst                                                   tt11833764
titleType                                                 tvEpisode
primaryTitle      Ninja Speaks The Truth About Gaming - SJWs Get...
originalTitle     Ninja Speaks The Truth About Gaming - SJWs Get...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2010123, dtype: object

(9,)

tconst                      tt11833766
titleType                        video
primaryTitle      Jhonny Rivera: Bella
originalTitle     Jhonny Rivera: Bella
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       3
genres                     Music,Short
Name: 2010124, dtype: object

(9,)

tconst                                 tt11833768
titleType                                   video
primaryTitle      Neil Cicierega: Wow Wow (Audio)
originalTitle     Neil Cicierega: Wow Wow (Audio)
isAdult                                         0
startYear                                    2017
endYear                                        \N
runtimeMinutes                                  3
genres                                Music,Short
Name: 2010125, dtype: object

(9,)

tconst                tt1183376
titleType               tvMovie
primaryTitle      Retour à Alep
originalTitle     Retour à Alep
isAdult                       0
startYear                  1998
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2010126, dtype: object

(9,)

tconst                      tt11833770
titleType                    tvEpisode
primaryTitle              Episode #1.8
originalTitle             Episode #1.8
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010127, dtype: object

(9,)

tconst                      tt11833772
titleType                    tvEpisode
primaryTitle             Episode #1.36
originalTitle            Episode #1.36
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010128, dtype: object

(9,)

tconst                      tt11833774
titleType                    tvEpisode
primaryTitle              Episode #1.9
originalTitle             Episode #1.9
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010129, dtype: object

(9,)

tconst                      tt11833776
titleType                    tvEpisode
primaryTitle             Episode #1.37
originalTitle            Episode #1.37
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010130, dtype: object

(9,)

tconst                      tt11833778
titleType                    tvEpisode
primaryTitle             Episode #1.38
originalTitle            Episode #1.38
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010131, dtype: object

(9,)

tconst                            tt1183377
titleType                           tvMovie
primaryTitle      Sex, Lies & Michael Aspel
originalTitle     Sex, Lies & Michael Aspel
isAdult                                   0
startYear                              2004
endYear                                  \N
runtimeMinutes                           60
genres                               Comedy
Name: 2010132, dtype: object

(9,)

tconst                      tt11833780
titleType                    tvEpisode
primaryTitle             Episode #1.39
originalTitle            Episode #1.39
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010133, dtype: object

(9,)

tconst                                                   tt11833782
titleType                                                     video
primaryTitle      Sebastián Yatra & Rauw Alejandro & Manuel Turi...
originalTitle     Sebastián Yatra & Rauw Alejandro & Manuel Turi...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2010134, dtype: object

(9,)

tconst                       tt11833784
titleType                     tvEpisode
primaryTitle            The News At Six
originalTitle           The News At Six
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres            Comedy,News,Talk-Show
Name: 2010135, dtype: object

(9,)

tconst                      tt11833786
titleType                    tvEpisode
primaryTitle             Episode #1.40
originalTitle            Episode #1.40
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010136, dtype: object

(9,)

tconst                      tt11833788
titleType                    tvEpisode
primaryTitle             Episode #1.41
originalTitle            Episode #1.41
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010137, dtype: object

(9,)

tconst                                                   tt1183378
titleType                                                    movie
primaryTitle      Shutdown: The Story of the Ulster Workers Strike
originalTitle     Shutdown: The Story of the Ulster Workers Strike
isAdult                                                          0
startYear                                                     2004
endYear                                                         \N
runtimeMinutes                                                  50
genres                                                 Documentary
Name: 2010138, dtype: object

(9,)

tconst                  tt11833790
titleType                tvEpisode
primaryTitle       Episode #1.1037
originalTitle      Episode #1.1037
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010139, dtype: object

(9,)

tconst                      tt11833792
titleType                    tvEpisode
primaryTitle             Episode #1.42
originalTitle            Episode #1.42
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010140, dtype: object

(9,)

tconst                      tt11833794
titleType                    tvEpisode
primaryTitle             Episode #1.43
originalTitle            Episode #1.43
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010141, dtype: object

(9,)

tconst                  tt11833796
titleType                tvEpisode
primaryTitle       Episode #1.1038
originalTitle      Episode #1.1038
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010142, dtype: object

(9,)

tconst                      tt11833798
titleType                    tvEpisode
primaryTitle             Episode #1.44
originalTitle            Episode #1.44
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010143, dtype: object

(9,)

tconst                  tt1183379
titleType                 tvMovie
primaryTitle      Sing on Forever
originalTitle     Sing on Forever
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 54
genres                Documentary
Name: 2010144, dtype: object

(9,)

tconst                       tt11833800
titleType                         movie
primaryTitle                     Circle
originalTitle                    Circle
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                      112
genres            Drama,Horror,Thriller
Name: 2010145, dtype: object

(9,)

tconst                  tt11833802
titleType                tvEpisode
primaryTitle       Episode #1.1039
originalTitle      Episode #1.1039
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010146, dtype: object

(9,)

tconst                      tt11833804
titleType                    tvEpisode
primaryTitle             Episode #1.45
originalTitle            Episode #1.45
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Romance
Name: 2010147, dtype: object

(9,)

tconst                  tt11833806
titleType                tvEpisode
primaryTitle       Episode #1.1040
originalTitle      Episode #1.1040
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010148, dtype: object

(9,)

tconst                                 tt11833808
titleType                                   video
primaryTitle      Natti Natasha: Me estás matando
originalTitle     Natti Natasha: Me estás matando
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                  3
genres                                Music,Short
Name: 2010149, dtype: object

(9,)

tconst                     tt1183380
titleType                    tvMovie
primaryTitle      Le système Poutine
originalTitle     Le système Poutine
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    98
genres                   Documentary
Name: 2010150, dtype: object

(9,)

tconst                  tt11833810
titleType                tvEpisode
primaryTitle       Episode #1.1041
originalTitle      Episode #1.1041
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010151, dtype: object

(9,)

tconst                      tt11833812
titleType                        short
primaryTitle      Just a Few Questions
originalTitle     Just a Few Questions
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                      15
genres                     Drama,Short
Name: 2010152, dtype: object

(9,)

tconst                                           tt11833814
titleType                                         tvEpisode
primaryTitle      Alec Baldwin/Maya Rudolph/Hilaria Baldwin
originalTitle     Alec Baldwin/Maya Rudolph/Hilaria Baldwin
isAdult                                                   0
startYear                                              2020
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                   \N
Name: 2010153, dtype: object

(9,)

tconst                      tt11833816
titleType                    tvEpisode
primaryTitle             Episode #1.11
originalTitle            Episode #1.11
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010154, dtype: object

(9,)

tconst                            tt11833818
titleType                          tvEpisode
primaryTitle      Sean Hayes/Chelsea Handler
originalTitle     Sean Hayes/Chelsea Handler
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2010155, dtype: object

(9,)

tconst                tt1183381
titleType               tvMovie
primaryTitle      Tango Maestro
originalTitle     Tango Maestro
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres                Biography
Name: 2010156, dtype: object

(9,)

tconst                    tt11833820
titleType                  tvEpisode
primaryTitle      Les arts à Moncton
originalTitle     Les arts à Moncton
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    22
genres                   Documentary
Name: 2010157, dtype: object

(9,)

tconst             tt11833822
titleType           tvEpisode
primaryTitle      Trevor Noah
originalTitle     Trevor Noah
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                     \N
Name: 2010158, dtype: object

(9,)

tconst                  tt11833824
titleType                tvEpisode
primaryTitle       Episode #1.1042
originalTitle      Episode #1.1042
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010159, dtype: object

(9,)

tconst                             tt11833826
titleType                           tvEpisode
primaryTitle      Kristen Bell and Ajani Huff
originalTitle     Kristen Bell and Ajani Huff
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2010160, dtype: object

(9,)

tconst                      tt11833828
titleType                    tvEpisode
primaryTitle             Episode #1.12
originalTitle            Episode #1.12
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010161, dtype: object

(9,)

tconst              tt1183382
titleType             tvMovie
primaryTitle      Tower Opera
originalTitle     Tower Opera
isAdult                     0
startYear                2002
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2010162, dtype: object

(9,)

tconst               tt11833830
titleType             tvEpisode
primaryTitle      Mark Wahlberg
originalTitle     Mark Wahlberg
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2010163, dtype: object

(9,)

tconst                   tt11833832
titleType                 tvEpisode
primaryTitle      Duncan the Grouch
originalTitle     Duncan the Grouch
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                    9
genres             Animation,Family
Name: 2010164, dtype: object

(9,)

tconst                tt11833834
titleType              tvEpisode
primaryTitle      X-Rated Tackle
originalTitle     X-Rated Tackle
isAdult                        1
startYear                   2018
endYear                       \N
runtimeMinutes                35
genres                     Adult
Name: 2010165, dtype: object

(9,)

tconst                tt11833836
titleType              tvEpisode
primaryTitle      Kris Jenner #2
originalTitle     Kris Jenner #2
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2010166, dtype: object

(9,)

tconst                  tt11833838
titleType                tvEpisode
primaryTitle       Episode #1.1043
originalTitle      Episode #1.1043
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010167, dtype: object

(9,)

tconst                       tt1183383
titleType                        movie
primaryTitle      Waiting for Houlihan
originalTitle     Waiting for Houlihan
isAdult                              0
startYear                         2004
endYear                             \N
runtimeMinutes                      52
genres                     Documentary
Name: 2010168, dtype: object

(9,)

tconst                  tt11833840
titleType                tvEpisode
primaryTitle       Episode #1.1044
originalTitle      Episode #1.1044
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010169, dtype: object

(9,)

tconst                                     tt11833842
titleType                                   tvEpisode
primaryTitle      Sean Hayes and Jesse Tyler Ferguson
originalTitle     Sean Hayes and Jesse Tyler Ferguson
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                             \N
Name: 2010170, dtype: object

(9,)

tconst                  tt11833844
titleType                tvEpisode
primaryTitle       Episode #1.1045
originalTitle      Episode #1.1045
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010171, dtype: object

(9,)

tconst                                                tt11833848
titleType                                              tvEpisode
primaryTitle      Proença-a-Velha - Festa do Azeite e do Fumeiro
originalTitle     Proença-a-Velha - Festa do Azeite e do Fumeiro
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                     Music
Name: 2010172, dtype: object

(9,)

tconst               tt1183384
titleType                video
primaryTitle      Warlock Moon
originalTitle     Warlock Moon
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              80
genres                  Horror
Name: 2010173, dtype: object

(9,)

tconst                  tt11833850
titleType                tvEpisode
primaryTitle       Episode #1.1046
originalTitle      Episode #1.1046
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010174, dtype: object

(9,)

tconst                  tt11833852
titleType                tvEpisode
primaryTitle       Episode #1.1047
originalTitle      Episode #1.1047
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010175, dtype: object

(9,)

tconst                                   tt11833854
titleType                                 tvEpisode
primaryTitle      Torres Vedras - Festa de Carnaval
originalTitle     Torres Vedras - Festa de Carnaval
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Music
Name: 2010176, dtype: object

(9,)

tconst                      tt11833856
titleType                    tvEpisode
primaryTitle              Episode #2.1
originalTitle             Episode #2.1
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010177, dtype: object

(9,)

tconst             tt11833858
titleType           tvEpisode
primaryTitle      Regina Hall
originalTitle     Regina Hall
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                     \N
Name: 2010178, dtype: object

(9,)

tconst                    tt1183385
titleType                     short
primaryTitle      Seven Indian Boys
originalTitle     Yot hndik tghaner
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                    7
genres            Documentary,Short
Name: 2010179, dtype: object

(9,)

tconst                                tt11833860
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010180, dtype: object

(9,)

tconst                                 tt11833862
titleType                               tvEpisode
primaryTitle      Martha MacCallum/View Your Deal
originalTitle     Martha MacCallum/View Your Deal
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2010181, dtype: object

(9,)

tconst                                            tt11833864
titleType                                          tvEpisode
primaryTitle      Rahm Emanuel/View Your Deal: Oprah Edition
originalTitle     Rahm Emanuel/View Your Deal: Oprah Edition
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                    \N
Name: 2010182, dtype: object

(9,)

tconst                          tt11833866
titleType                        tvEpisode
primaryTitle      Mark Cuban/Kevin O'Leary
originalTitle     Mark Cuban/Kevin O'Leary
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                                  \N
Name: 2010183, dtype: object

(9,)

tconst                              tt11833868
titleType                                video
primaryTitle      Young M.A: She Like I'm Like
originalTitle     Young M.A: She Like I'm Like
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                               3
genres                             Music,Short
Name: 2010184, dtype: object

(9,)

tconst                tt1183386
titleType             tvEpisode
primaryTitle      Crystal Clear
originalTitle     Crystal Clear
isAdult                       0
startYear                  2005
endYear                      \N
runtimeMinutes               \N
genres               Reality-TV
Name: 2010185, dtype: object

(9,)

tconst                             tt11833870
titleType                           tvEpisode
primaryTitle      Eddie Holland/Brian Holland
originalTitle     Eddie Holland/Brian Holland
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2010186, dtype: object

(9,)

tconst                      tt11833872
titleType                    tvEpisode
primaryTitle              Episode #2.3
originalTitle             Episode #2.3
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010187, dtype: object

(9,)

tconst            tt11833874
titleType          tvEpisode
primaryTitle      Edie Falco
originalTitle     Edie Falco
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                    \N
Name: 2010188, dtype: object

(9,)

tconst                                                 tt11833876
titleType                                               tvEpisode
primaryTitle      Hot Topics/View Your Deal: Oprah Edition - 2020
originalTitle     Hot Topics/View Your Deal: Oprah Edition - 2020
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                         \N
Name: 2010189, dtype: object

(9,)

tconst                tt11833878
titleType              tvEpisode
primaryTitle      Episode #16.45
originalTitle     Episode #16.45
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2010190, dtype: object

(9,)

tconst                                 tt1183387
titleType                              tvEpisode
primaryTitle      From Backstage to Center Stage
originalTitle     From Backstage to Center Stage
isAdult                                        0
startYear                                   2005
endYear                                       \N
runtimeMinutes                                \N
genres                                Reality-TV
Name: 2010191, dtype: object

(9,)

tconst                                tt11833880
titleType                              tvEpisode
primaryTitle      Episode dated 24 February 2020
originalTitle     Episode dated 24 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                          Comedy,Talk-Show
Name: 2010192, dtype: object

(9,)

tconst                      tt11833882
titleType                    tvEpisode
primaryTitle              Episode #2.4
originalTitle             Episode #2.4
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010193, dtype: object

(9,)

tconst                  tt11833884
titleType                tvEpisode
primaryTitle               Goodbye
originalTitle              Goodbye
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2010194, dtype: object

(9,)

tconst                                tt11833886
titleType                              tvEpisode
primaryTitle      Episode dated 25 February 2020
originalTitle     Episode dated 25 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                          Comedy,Talk-Show
Name: 2010195, dtype: object

(9,)

tconst                      tt11833888
titleType                    tvEpisode
primaryTitle              Episode #2.5
originalTitle             Episode #2.5
isAdult                              0
startYear                         1985
endYear                             \N
runtimeMinutes                      \N
genres            Game-Show,Reality-TV
Name: 2010196, dtype: object

(9,)

tconst             tt1183388
titleType          tvEpisode
primaryTitle      Funny Girl
originalTitle     Funny Girl
isAdult                    0
startYear               2005
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2010197, dtype: object

(9,)

tconst                                tt11833890
titleType                              tvEpisode
primaryTitle      Episode dated 26 February 2020
originalTitle     Episode dated 26 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                          Comedy,Talk-Show
Name: 2010198, dtype: object

(9,)

tconst                                tt11833892
titleType                              tvEpisode
primaryTitle      Episode dated 27 February 2020
originalTitle     Episode dated 27 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                          Comedy,Talk-Show
Name: 2010199, dtype: object

(9,)

tconst                                tt11833894
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                          Comedy,Talk-Show
Name: 2010200, dtype: object

(9,)

tconst                      tt11833896
titleType                    tvEpisode
primaryTitle      Behalte es für dich!
originalTitle     Behalte es für dich!
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                Drama,Reality-TV
Name: 2010201, dtype: object

(9,)

tconst                                tt11833898
titleType                              tvEpisode
primaryTitle      Episode dated 24 February 2020
originalTitle     Episode dated 24 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010202, dtype: object

(9,)

tconst                           tt1183389
titleType                        tvEpisode
primaryTitle      So I Had This Great Idea
originalTitle     So I Had This Great Idea
isAdult                                  0
startYear                             2005
endYear                                 \N
runtimeMinutes                          \N
genres                          Reality-TV
Name: 2010203, dtype: object

(9,)

tconst                                tt11833900
titleType                              tvEpisode
primaryTitle      Episode dated 26 February 2020
originalTitle     Episode dated 26 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010204, dtype: object

(9,)

tconst                                tt11833902
titleType                              tvEpisode
primaryTitle      Episode dated 27 February 2020
originalTitle     Episode dated 27 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010205, dtype: object

(9,)

tconst                                tt11833904
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010206, dtype: object

(9,)

tconst                 tt11833906
titleType               tvEpisode
primaryTitle      Episode #1.7329
originalTitle     Episode #1.7329
isAdult                         0
startYear                    2002
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010207, dtype: object

(9,)

tconst                                              tt11833908
titleType                                            tvEpisode
primaryTitle      Valentine's Day - How It All Began and Stuff
originalTitle     Valentine's Day - How It All Began and Stuff
isAdult                                                      0
startYear                                                 2020
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                  Comedy
Name: 2010208, dtype: object

(9,)

tconst                       tt1183390
titleType                    tvEpisode
primaryTitle               New Orleans
originalTitle              New Orleans
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      44
genres            Adventure,Reality-TV
Name: 2010209, dtype: object

(9,)

tconst                tt11833910
titleType              tvEpisode
primaryTitle      Episode #16.46
originalTitle     Episode #16.46
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2010210, dtype: object

(9,)

tconst                                    tt11833912
titleType                                  tvEpisode
primaryTitle      Nia Long/Paris Hilton/Nicky Hilton
originalTitle     Nia Long/Paris Hilton/Nicky Hilton
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    38
genres                                            \N
Name: 2010211, dtype: object

(9,)

tconst                                                   tt11833914
titleType                                                 tvEpisode
primaryTitle      Max Greenfield/Tarek El Moussa/Rumer Willis/Ta...
originalTitle     Max Greenfield/Tarek El Moussa/Rumer Willis/Ta...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   38
genres                                                           \N
Name: 2010212, dtype: object

(9,)

tconst                               tt11833916
titleType                             tvEpisode
primaryTitle      Raven Symone/Issac Ryan Brown
originalTitle     Raven Symone/Issac Ryan Brown
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               38
genres                                Talk-Show
Name: 2010213, dtype: object

(9,)

tconst               tt11833918
titleType             tvEpisode
primaryTitle      Dr. Mehmet Oz
originalTitle     Dr. Mehmet Oz
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               38
genres                Talk-Show
Name: 2010214, dtype: object

(9,)

tconst            tt1183391
titleType         tvEpisode
primaryTitle          Dance
originalTitle         Dance
isAdult                   0
startYear                \N
endYear                  \N
runtimeMinutes           \N
genres               Family
Name: 2010215, dtype: object

(9,)

tconst                 tt11833920
titleType               tvEpisode
primaryTitle      William Shatner
originalTitle     William Shatner
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 38
genres                  Talk-Show
Name: 2010216, dtype: object

(9,)

tconst                  tt11833922
titleType                tvEpisode
primaryTitle      Episode #1.10011
originalTitle     Episode #1.10011
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  22
genres               Drama,Romance
Name: 2010217, dtype: object

(9,)

tconst                                               tt11833924
titleType                                                 movie
primaryTitle                                           Ice Cold
originalTitle     Ice Cold: The Untold Story of Hip Hop Jewelry
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               \N
genres                                              Documentary
Name: 2010218, dtype: object

(9,)

tconst                  tt11833926
titleType                tvEpisode
primaryTitle      Oprah Winfrey #2
originalTitle     Oprah Winfrey #2
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  38
genres                   Talk-Show
Name: 2010219, dtype: object

(9,)

tconst             tt11833928
titleType           tvEpisode
primaryTitle      Hilary Duff
originalTitle     Hilary Duff
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             38
genres              Talk-Show
Name: 2010220, dtype: object

(9,)

tconst            tt1183392
titleType         tvEpisode
primaryTitle         Health
originalTitle        Health
isAdult                   0
startYear                \N
endYear                  \N
runtimeMinutes           \N
genres               Family
Name: 2010221, dtype: object

(9,)

tconst                               tt11833930
titleType                             tvEpisode
primaryTitle      La communauté de Petit-Rocher
originalTitle     La communauté de Petit-Rocher
isAdult                                       0
startYear                                  2019
endYear                                      \N
runtimeMinutes                               22
genres                              Documentary
Name: 2010222, dtype: object

(9,)

tconst                                   tt11833932
titleType                                     video
primaryTitle      Jaylann Feat. Beathoven: Chi Wqat
originalTitle     Jaylann Feat. Beathoven: Chi Wqat
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                    4
genres                                  Music,Short
Name: 2010223, dtype: object

(9,)

tconst                 tt11833934
titleType               tvEpisode
primaryTitle      Episode #1.7334
originalTitle     Episode #1.7334
isAdult                         0
startYear                    2002
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010224, dtype: object

(9,)

tconst               tt11833936
titleType              tvSeries
primaryTitle      Sky News at 9
originalTitle     Sky News at 9
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010225, dtype: object

(9,)

tconst                                            tt11833938
titleType                                              short
primaryTitle      The Big Iain Lee Signing at Balcony Shirts
originalTitle     The Big Iain Lee Signing at Balcony Shirts
isAdult                                                    0
startYear                                               2012
endYear                                                   \N
runtimeMinutes                                             9
genres                                          Comedy,Short
Name: 2010226, dtype: object

(9,)

tconst                  tt1183393
titleType               tvEpisode
primaryTitle      Protect & Serve
originalTitle     Protect & Serve
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2010227, dtype: object

(9,)

tconst                  tt11833940
titleType                    short
primaryTitle      Bottled Emotions
originalTitle     Bottled Emotions
isAdult                          0
startYear                     2018
endYear                         \N
runtimeMinutes                  \N
genres                 Drama,Short
Name: 2010228, dtype: object

(9,)

tconst                    tt11833942
titleType                      video
primaryTitle      Jaylann: Allo Allo
originalTitle     Jaylann: Allo Allo
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                     4
genres                   Music,Short
Name: 2010229, dtype: object

(9,)

tconst                          tt11833944
titleType                            movie
primaryTitle      Kipinöitä Unelan Takasta
originalTitle     Kipinöitä Unelan Takasta
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          46
genres                                  \N
Name: 2010230, dtype: object

(9,)

tconst                                 tt11833946
titleType                               tvEpisode
primaryTitle      Gorgey Georgie is Naughty Again
originalTitle     Gorgey Georgie is Naughty Again
isAdult                                         0
startYear                                    1962
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Family
Name: 2010231, dtype: object

(9,)

tconst                    tt11833948
titleType                      video
primaryTitle      Jaylann: Je t'aime
originalTitle     Jaylann: Je t'aime
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                     4
genres                   Music,Short
Name: 2010232, dtype: object

(9,)

tconst            tt1183394
titleType         tvEpisode
primaryTitle        Science
originalTitle       Science
isAdult                   0
startYear                \N
endYear                  \N
runtimeMinutes           \N
genres               Family
Name: 2010233, dtype: object

(9,)

tconst                                                   tt11833950
titleType                                                 tvEpisode
primaryTitle      Sonic The Hedgehog Destroys Birds of Prey at t...
originalTitle     Sonic The Hedgehog Destroys Birds of Prey at t...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2010234, dtype: object

(9,)

tconst                           tt11833954
titleType                         tvEpisode
primaryTitle      Sara and Hoppity Get Lost
originalTitle     Sara and Hoppity Get Lost
isAdult                                   0
startYear                              1962
endYear                                  \N
runtimeMinutes                           \N
genres                               Family
Name: 2010235, dtype: object

(9,)

tconst                                       tt11833956
titleType                                     tvEpisode
primaryTitle      Histoire de pêche et passion au Yukon
originalTitle     Histoire de pêche et passion au Yukon
isAdult                                               0
startYear                                          2019
endYear                                              \N
runtimeMinutes                                       22
genres                                      Documentary
Name: 2010236, dtype: object

(9,)

tconst             tt1183395
titleType          tvEpisode
primaryTitle            Avon
originalTitle           Avon
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2010237, dtype: object

(9,)

tconst               tt11833960
titleType                 video
primaryTitle      Khaoula: Mama
originalTitle     Khaoula: Mama
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes                4
genres              Music,Short
Name: 2010238, dtype: object

(9,)

tconst                              tt11833962
titleType                            tvEpisode
primaryTitle                      Daily Raptor
originalTitle                     Daily Raptor
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              36
genres            Documentary,Reality-TV,Sport
Name: 2010239, dtype: object

(9,)

tconst                       tt11833964
titleType                      tvSeries
primaryTitle      Kay Burley @Breakfast
originalTitle     Kay Burley @Breakfast
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       \N
genres                             News
Name: 2010240, dtype: object

(9,)

tconst                 tt11833966
titleType               tvEpisode
primaryTitle      Sara's Birthday
originalTitle     Sara's Birthday
isAdult                         0
startYear                    1962
endYear                        \N
runtimeMinutes                 \N
genres                     Family
Name: 2010241, dtype: object

(9,)

tconst              tt11833968
titleType                short
primaryTitle      Daddy Issues
originalTitle     Daddy Issues
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes               7
genres            Comedy,Short
Name: 2010242, dtype: object

(9,)

tconst                               tt1183396
titleType                            tvEpisode
primaryTitle      Episode dated 4 January 2008
originalTitle     Episode dated 4 January 2008
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                    News
Name: 2010243, dtype: object

(9,)

tconst                      tt11833970
titleType                    tvEpisode
primaryTitle              Episode #3.1
originalTitle             Episode #3.1
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Fantasy
Name: 2010244, dtype: object

(9,)

tconst                               tt11833972
titleType                             tvEpisode
primaryTitle      Episode dated 17 January 1954
originalTitle     Episode dated 17 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2010245, dtype: object

(9,)

tconst                               tt11833974
titleType                             tvEpisode
primaryTitle      Sara Does the Spring Cleaning
originalTitle     Sara Does the Spring Cleaning
isAdult                                       0
startYear                                  1962
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2010246, dtype: object

(9,)

tconst                  tt11833976
titleType                tvEpisode
primaryTitle      Living the Dream
originalTitle     Living the Dream
isAdult                          0
startYear                     2021
endYear                         \N
runtimeMinutes                  44
genres                Comedy,Drama
Name: 2010247, dtype: object

(9,)

tconst                tt11833978
titleType              tvEpisode
primaryTitle           Dream job
originalTitle          Dream job
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres            Comedy,Fantasy
Name: 2010248, dtype: object

(9,)

tconst                  tt1183397
titleType               tvEpisode
primaryTitle      Episode #1.9602
originalTitle     Episode #1.9602
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010249, dtype: object

(9,)

tconst                         tt11833980
titleType                        tvSeries
primaryTitle      The Sarah-Jane Mee Show
originalTitle     The Sarah-Jane Mee Show
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres                               News
Name: 2010250, dtype: object

(9,)

tconst                                                   tt11833982
titleType                                                     video
primaryTitle      Khaoula Feat. Muslim & Issam Kamal & Foulane B...
originalTitle     Khaoula Feat. Muslim & Issam Kamal & Foulane B...
isAdult                                                           0
startYear                                                      2017
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2010251, dtype: object

(9,)

tconst                             tt11833984
titleType                           tvEpisode
primaryTitle      Gorgey Georgie Comes to Tea
originalTitle     Gorgey Georgie Comes to Tea
isAdult                                     0
startYear                                1962
endYear                                    \N
runtimeMinutes                             \N
genres                                 Family
Name: 2010252, dtype: object

(9,)

tconst                      tt11833986
titleType                        short
primaryTitle      Water Meditation One
originalTitle     Water Meditation One
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                           Short
Name: 2010253, dtype: object

(9,)

tconst                  tt11833988
titleType                tvEpisode
primaryTitle          Episode #1.1
originalTitle         Episode #1.1
isAdult                          0
startYear                     1984
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010254, dtype: object

(9,)

tconst                              tt1183398
titleType                           tvEpisode
primaryTitle      Battle for the Brontosaurus
originalTitle     Battle for the Brontosaurus
isAdult                                     0
startYear                                1988
endYear                                    \N
runtimeMinutes                             \N
genres             Action,Adventure,Animation
Name: 2010255, dtype: object

(9,)

tconst                   tt11833990
titleType                 tvEpisode
primaryTitle           Episode #1.1
originalTitle          Episode #1.1
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010256, dtype: object

(9,)

tconst                       tt11833992
titleType                     tvEpisode
primaryTitle      Sara and the Junk Man
originalTitle     Sara and the Junk Man
isAdult                               0
startYear                          1962
endYear                              \N
runtimeMinutes                       \N
genres                           Family
Name: 2010257, dtype: object

(9,)

tconst                                      tt11833994
titleType                                        video
primaryTitle      H-Kayne & Khaoula: Do What You Can't
originalTitle     H-Kayne & Khaoula: Do What You Can't
isAdult                                              0
startYear                                         2018
endYear                                             \N
runtimeMinutes                                       4
genres                                     Music,Short
Name: 2010258, dtype: object

(9,)

tconst                   tt11833996
titleType                 tvEpisode
primaryTitle           Episode #1.2
originalTitle          Episode #1.2
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010259, dtype: object

(9,)

tconst                   tt11833998
titleType                 tvEpisode
primaryTitle           Episode #1.3
originalTitle          Episode #1.3
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010260, dtype: object

(9,)

tconst                         tt1183399
titleType                      tvEpisode
primaryTitle      Something's Gotta Give
originalTitle     Something's Gotta Give
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres                             Drama
Name: 2010261, dtype: object

(9,)

tconst                   tt11834000
titleType                 tvEpisode
primaryTitle           Episode #1.4
originalTitle          Episode #1.4
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010262, dtype: object

(9,)

tconst                   tt11834002
titleType                 tvEpisode
primaryTitle           Episode #1.5
originalTitle          Episode #1.5
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010263, dtype: object

(9,)

tconst                      tt11834004
titleType                        short
primaryTitle      Water Meditation Two
originalTitle     Water Meditation Two
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                           Short
Name: 2010264, dtype: object

(9,)

tconst                   tt11834006
titleType                  tvSeries
primaryTitle      The Early Rundown
originalTitle     The Early Rundown
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2010265, dtype: object

(9,)

tconst                   tt11834008
titleType                 tvEpisode
primaryTitle           Episode #1.6
originalTitle          Episode #1.6
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010266, dtype: object

(9,)

tconst                                tt1183400
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                      Crime,Drama,Romance
Name: 2010267, dtype: object

(9,)

tconst                  tt11834010
titleType                tvEpisode
primaryTitle          Episode #1.2
originalTitle         Episode #1.2
isAdult                          0
startYear                     1984
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010268, dtype: object

(9,)

tconst                   tt11834012
titleType                 tvEpisode
primaryTitle           Episode #1.7
originalTitle          Episode #1.7
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010269, dtype: object

(9,)

tconst                  tt11834014
titleType                tvEpisode
primaryTitle          Episode #1.3
originalTitle         Episode #1.3
isAdult                          0
startYear                     1984
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010270, dtype: object

(9,)

tconst                   tt11834016
titleType                 tvEpisode
primaryTitle           Episode #1.8
originalTitle          Episode #1.8
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010271, dtype: object

(9,)

tconst                   tt11834018
titleType                 tvEpisode
primaryTitle           Episode #1.9
originalTitle          Episode #1.9
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010272, dtype: object

(9,)

tconst                             tt1183401
titleType                          tvEpisode
primaryTitle      Christmas Day 2007: Part 2
originalTitle     Christmas Day 2007: Part 2
isAdult                                    0
startYear                               2007
endYear                                   \N
runtimeMinutes                            \N
genres                   Crime,Drama,Romance
Name: 2010273, dtype: object

(9,)

tconst             tt11834020
titleType               short
primaryTitle      Life Lesson
originalTitle     Life Lesson
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              5
genres            Drama,Short
Name: 2010274, dtype: object

(9,)

tconst                   tt11834022
titleType                 tvEpisode
primaryTitle          Episode #1.10
originalTitle         Episode #1.10
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Adventure,Romance
Name: 2010275, dtype: object

(9,)

tconst                        tt11834024
titleType                          short
primaryTitle      Water Meditation Three
originalTitle     Water Meditation Three
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres                             Short
Name: 2010276, dtype: object

(9,)

tconst                  tt11834026
titleType                tvEpisode
primaryTitle          Episode #1.4
originalTitle         Episode #1.4
isAdult                          0
startYear                     1984
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010277, dtype: object

(9,)

tconst                  tt11834028
titleType                tvEpisode
primaryTitle          Episode #1.5
originalTitle         Episode #1.5
isAdult                          0
startYear                     1984
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010278, dtype: object

(9,)

tconst                              tt1183402
titleType                           tvEpisode
primaryTitle                   Temple of Fear
originalTitle                  Temple of Fear
isAdult                                     0
startYear                                2001
endYear                                    \N
runtimeMinutes                             50
genres            Biography,Crime,Documentary
Name: 2010279, dtype: object

(9,)

tconst                                tt11834030
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010280, dtype: object

(9,)

tconst                                tt11834032
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010281, dtype: object

(9,)

tconst                                tt11834034
titleType                              tvEpisode
primaryTitle      Une communauté active au Yukon
originalTitle     Une communauté active au Yukon
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                22
genres                               Documentary
Name: 2010282, dtype: object

(9,)

tconst                                tt11834036
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010283, dtype: object

(9,)

tconst                 tt11834038
titleType               tvEpisode
primaryTitle      Episode #1.4548
originalTitle     Episode #1.4548
isAdult                         0
startYear                    1986
endYear                        \N
runtimeMinutes                 60
genres                         \N
Name: 2010284, dtype: object

(9,)

tconst                   tt1183403
titleType                tvEpisode
primaryTitle          Episode #1.1
originalTitle         Episode #1.1
isAdult                          0
startYear                     1981
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2010285, dtype: object

(9,)

tconst                                tt11834040
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010286, dtype: object

(9,)

tconst                                tt11834042
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010287, dtype: object

(9,)

tconst                                              tt11834044
titleType                                                video
primaryTitle      H-Kayne Feat. Youness & Dj Soul-A: Ça va pas
originalTitle     H-Kayne Feat. Youness & Dj Soul-A: Ça va pas
isAdult                                                      0
startYear                                                 2018
endYear                                                     \N
runtimeMinutes                                               4
genres                                             Music,Short
Name: 2010288, dtype: object

(9,)

tconst                                         tt11834048
titleType                                       tvEpisode
primaryTitle      Birthday Heroes for Hero/Maple Cheer up
originalTitle     Birthday Heroes for Hero/Maple Cheer up
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                         Adventure,Animation,Comedy
Name: 2010289, dtype: object

(9,)

tconst                   tt1183404
titleType                tvEpisode
primaryTitle         Episode #1.14
originalTitle        Episode #1.14
isAdult                          0
startYear                     1981
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2010290, dtype: object

(9,)

tconst            tt11834050
titleType          tvEpisode
primaryTitle          Lørdag
originalTitle         Lørdag
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2010291, dtype: object

(9,)

tconst            tt11834052
titleType              short
primaryTitle      Chad's PSA
originalTitle     Chad's PSA
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes             2
genres                 Short
Name: 2010292, dtype: object

(9,)

tconst                                tt11834054
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010293, dtype: object

(9,)

tconst                  tt11834056
titleType                tvEpisode
primaryTitle      Melanotan II (2)
originalTitle     Melanotan II (2)
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                  Reality-TV
Name: 2010294, dtype: object

(9,)

tconst                   tt1183405
titleType                tvEpisode
primaryTitle          Episode #4.1
originalTitle         Episode #4.1
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2010295, dtype: object

(9,)

tconst               tt11834060
titleType             tvEpisode
primaryTitle      Episode #10.1
originalTitle     Episode #10.1
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Game-Show
Name: 2010296, dtype: object

(9,)

tconst                tt11834062
titleType                  movie
primaryTitle      The Sacrificed
originalTitle     The Sacrificed
isAdult                        0
startYear                   2023
endYear                       \N
runtimeMinutes                \N
genres                    Horror
Name: 2010297, dtype: object

(9,)

tconst                            tt11834064
titleType                              video
primaryTitle      Khaoula: Ana Machi Perfect
originalTitle     Khaoula: Ana Machi Perfect
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                             4
genres                           Music,Short
Name: 2010298, dtype: object

(9,)

tconst                 tt11834066
titleType                   short
primaryTitle      The Canard Line
originalTitle     The Canard Line
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                      Short
Name: 2010299, dtype: object

(9,)

tconst                 tt11834068
titleType               tvEpisode
primaryTitle      Ennemis intimes
originalTitle     Ennemis intimes
isAdult                         0
startYear                    2012
endYear                        \N
runtimeMinutes                 25
genres                      Drama
Name: 2010300, dtype: object

(9,)

tconst                   tt1183406
titleType                tvEpisode
primaryTitle         Episode #4.11
originalTitle        Episode #4.11
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2010301, dtype: object

(9,)

tconst                      tt11834070
titleType                    tvEpisode
primaryTitle       Me with Punctuation
originalTitle      Me with Punctuation
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Music,Musical
Name: 2010302, dtype: object

(9,)

tconst                  tt11834072
titleType                tvEpisode
primaryTitle          Episode #1.6
originalTitle         Episode #1.6
isAdult                          0
startYear                     1984
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010303, dtype: object

(9,)

tconst                           tt11834074
titleType                         tvEpisode
primaryTitle      Miriam Bryant/Lasse Åberg
originalTitle     Miriam Bryant/Lasse Åberg
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                            Talk-Show
Name: 2010304, dtype: object

(9,)

tconst                tt11834076
titleType                  video
primaryTitle      Khaoula: Toren
originalTitle     Khaoula: Toren
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                 5
genres               Music,Short
Name: 2010305, dtype: object

(9,)

tconst             tt11834078
titleType               short
primaryTitle      I Knew Him!
originalTitle     I Knew Him!
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                  Short
Name: 2010306, dtype: object

(9,)

tconst                   tt1183407
titleType                tvEpisode
primaryTitle          Episode #5.1
originalTitle         Episode #5.1
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2010307, dtype: object

(9,)

tconst                     tt11834082
titleType                       short
primaryTitle      For the Barren King
originalTitle     For the Barren King
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                    Drama,Short
Name: 2010308, dtype: object

(9,)

tconst              tt11834084
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2010309, dtype: object

(9,)

tconst              tt11834086
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2010310, dtype: object

(9,)

tconst              tt11834088
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2010311, dtype: object

(9,)

tconst                   tt1183408
titleType                tvEpisode
primaryTitle          Episode #5.7
originalTitle         Episode #5.7
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2010312, dtype: object

(9,)

tconst             tt11834090
titleType               short
primaryTitle       Highwaymen
originalTitle      Highwaymen
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             15
genres            Drama,Short
Name: 2010313, dtype: object

(9,)

tconst                 tt11834092
titleType               tvEpisode
primaryTitle      Episode #1.8748
originalTitle     Episode #1.8748
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 22
genres              Drama,Romance
Name: 2010314, dtype: object

(9,)

tconst                  tt11834094
titleType                tvEpisode
primaryTitle      Episode #1.10012
originalTitle     Episode #1.10012
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  46
genres               Drama,Romance
Name: 2010315, dtype: object

(9,)

tconst                 tt11834096
titleType               tvEpisode
primaryTitle      Episode #1.8749
originalTitle     Episode #1.8749
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 22
genres              Drama,Romance
Name: 2010316, dtype: object

(9,)

tconst                 tt11834098
titleType               tvEpisode
primaryTitle      Episode #1.8750
originalTitle     Episode #1.8750
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010317, dtype: object

(9,)

tconst                      tt1183409
titleType                   tvEpisode
primaryTitle         Episode #1.11487
originalTitle        Episode #1.11487
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2010318, dtype: object

(9,)

tconst                 tt11834100
titleType               tvEpisode
primaryTitle      Episode #1.8751
originalTitle     Episode #1.8751
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 22
genres              Drama,Romance
Name: 2010319, dtype: object

(9,)

tconst                        tt11834102
titleType                       tvSeries
primaryTitle                    IDOLiSH7
originalTitle                   IDOLiSH7
isAdult                                0
startYear                           2017
endYear                               \N
runtimeMinutes                        \N
genres            Animation,Comedy,Drama
Name: 2010320, dtype: object

(9,)

tconst            tt11834104
titleType          tvEpisode
primaryTitle         Kitty 1
originalTitle        Kitty 1
isAdult                    1
startYear               2007
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2010321, dtype: object

(9,)

tconst            tt11834106
titleType          tvEpisode
primaryTitle         Kitty 2
originalTitle        Kitty 2
isAdult                    1
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2010322, dtype: object

(9,)

tconst                             tt11834108
titleType                           tvEpisode
primaryTitle                      Ralph Veady
originalTitle                     Ralph Veady
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2010323, dtype: object

(9,)

tconst                      tt1183410
titleType                   tvEpisode
primaryTitle          Episode #1.9925
originalTitle         Episode #1.9925
isAdult                             0
startYear                        2002
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2010324, dtype: object

(9,)

tconst                               tt11834110
titleType                             tvEpisode
primaryTitle      Deepthroatfrenzy With Olimpia
originalTitle     Deepthroatfrenzy With Olimpia
isAdult                                       1
startYear                                  2007
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2010325, dtype: object

(9,)

tconst                                     tt11834112
titleType                                   tvEpisode
primaryTitle      Beach bunny loves to suck and fuck!
originalTitle     Beach bunny loves to suck and fuck!
isAdult                                             1
startYear                                        2008
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2010326, dtype: object

(9,)

tconst                  tt11834114
titleType                tvEpisode
primaryTitle          Episode #1.7
originalTitle         Episode #1.7
isAdult                          0
startYear                     1984
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010327, dtype: object

(9,)

tconst            tt11834116
titleType              short
primaryTitle      Smartmouth
originalTitle     Smartmouth
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2010328, dtype: object

(9,)

tconst                   tt11834118
titleType                     movie
primaryTitle      Molly Bling Bling
originalTitle     Molly Bling Bling
isAdult                           0
startYear                      2022
endYear                          \N
runtimeMinutes                   \N
genres               Comedy,Romance
Name: 2010329, dtype: object

(9,)

tconst                      tt1183411
titleType                   tvEpisode
primaryTitle          Episode #1.9926
originalTitle         Episode #1.9926
isAdult                             0
startYear                        2002
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2010330, dtype: object

(9,)

tconst                              tt11834120
titleType                            tvEpisode
primaryTitle      A mouthful of his gooey cum!
originalTitle     A mouthful of his gooey cum!
isAdult                                      1
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010331, dtype: object

(9,)

tconst                        tt11834122
titleType                          video
primaryTitle      African Crew: La Magie
originalTitle     African Crew: La Magie
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                         5
genres                       Music,Short
Name: 2010332, dtype: object

(9,)

tconst            tt11834124
titleType              movie
primaryTitle            Drvr
originalTitle           Drvr
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres              Thriller
Name: 2010333, dtype: object

(9,)

tconst                                 tt11834126
titleType                               tvEpisode
primaryTitle      Rasoplichtster door heel Europa
originalTitle     Rasoplichtster door heel Europa
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                 Reality-TV
Name: 2010334, dtype: object

(9,)

tconst                 tt11834128
titleType                   movie
primaryTitle           Hack/Slash
originalTitle          Hack/Slash
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres            Horror,Thriller
Name: 2010335, dtype: object

(9,)

tconst                      tt1183412
titleType                   tvEpisode
primaryTitle          Episode #1.9928
originalTitle         Episode #1.9928
isAdult                             0
startYear                        2002
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2010336, dtype: object

(9,)

tconst                                 tt11834130
titleType                                   short
primaryTitle      Edith, die Tochter seines Chefs
originalTitle     Edith, die Tochter seines Chefs
isAdult                                         0
startYear                                    1912
endYear                                        \N
runtimeMinutes                                 \N
genres                               Comedy,Short
Name: 2010337, dtype: object

(9,)

tconst                    tt11834132
titleType                  tvEpisode
primaryTitle          Episode #14.44
originalTitle         Episode #14.44
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010338, dtype: object

(9,)

tconst                    tt11834134
titleType                  tvEpisode
primaryTitle          Episode #14.45
originalTitle         Episode #14.45
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010339, dtype: object

(9,)

tconst                    tt11834136
titleType                  tvEpisode
primaryTitle          Episode #14.46
originalTitle         Episode #14.46
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010340, dtype: object

(9,)

tconst                    tt11834138
titleType                  tvEpisode
primaryTitle          Episode #14.47
originalTitle         Episode #14.47
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010341, dtype: object

(9,)

tconst                      tt1183413
titleType                   tvEpisode
primaryTitle          Episode #1.9930
originalTitle         Episode #1.9930
isAdult                             0
startYear                        2002
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2010342, dtype: object

(9,)

tconst                    tt11834140
titleType                  tvEpisode
primaryTitle          Episode #14.48
originalTitle         Episode #14.48
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010343, dtype: object

(9,)

tconst            tt11834142
titleType              short
primaryTitle            PTSD
originalTitle           PTSD
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2010344, dtype: object

(9,)

tconst                    tt11834144
titleType                  tvEpisode
primaryTitle          Episode #14.49
originalTitle         Episode #14.49
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010345, dtype: object

(9,)

tconst                             tt11834146
titleType                           tvEpisode
primaryTitle      Sara and Hoppity Help Mummy
originalTitle     Sara and Hoppity Help Mummy
isAdult                                     0
startYear                                1962
endYear                                    \N
runtimeMinutes                             \N
genres                                 Family
Name: 2010346, dtype: object

(9,)

tconst                      tt11834148
titleType                     tvSeries
primaryTitle      Ice Fishing Hardcore
originalTitle     Ice Fishing Hardcore
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      23
genres                       Adventure
Name: 2010347, dtype: object

(9,)

tconst                             tt1183414
titleType                          tvEpisode
primaryTitle      Episode dated 8 April 1996
originalTitle     Episode dated 8 April 1996
isAdult                                    0
startYear                               1996
endYear                                   \N
runtimeMinutes                            19
genres                   Crime,Drama,Romance
Name: 2010348, dtype: object

(9,)

tconst              tt11834150
titleType             tvSeries
primaryTitle         The Chair
originalTitle        The Chair
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              30
genres            Comedy,Drama
Name: 2010349, dtype: object

(9,)

tconst                    tt11834152
titleType                  tvEpisode
primaryTitle          Episode #14.51
originalTitle         Episode #14.51
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010350, dtype: object

(9,)

tconst                    tt11834154
titleType                  tvEpisode
primaryTitle          Episode #14.50
originalTitle         Episode #14.50
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010351, dtype: object

(9,)

tconst                                 tt11834156
titleType                               tvEpisode
primaryTitle      Lauren Blake & Samantha Siclari
originalTitle     Lauren Blake & Samantha Siclari
isAdult                                         0
startYear                                    2012
endYear                                        \N
runtimeMinutes                                 \N
genres                                  Talk-Show
Name: 2010352, dtype: object

(9,)

tconst                    tt11834158
titleType                  tvEpisode
primaryTitle          Episode #14.52
originalTitle         Episode #14.52
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010353, dtype: object

(9,)

tconst                              tt1183415
titleType                           tvEpisode
primaryTitle      Episode dated 23 April 2001
originalTitle     Episode dated 23 April 2001
isAdult                                     0
startYear                                2001
endYear                                    \N
runtimeMinutes                             \N
genres                    Crime,Drama,Romance
Name: 2010354, dtype: object

(9,)

tconst                    tt11834160
titleType                  tvEpisode
primaryTitle          Episode #14.54
originalTitle         Episode #14.54
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010355, dtype: object

(9,)

tconst                    tt11834162
titleType                  tvEpisode
primaryTitle          Episode #14.55
originalTitle         Episode #14.55
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010356, dtype: object

(9,)

tconst                    tt11834164
titleType                  tvEpisode
primaryTitle          Episode #14.53
originalTitle         Episode #14.53
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010357, dtype: object

(9,)

tconst                   tt11834166
titleType                 tvEpisode
primaryTitle      Brilliant Mistake
originalTitle     Brilliant Mistake
isAdult                           0
startYear                      2021
endYear                          \N
runtimeMinutes                   30
genres                 Comedy,Drama
Name: 2010358, dtype: object

(9,)

tconst                    tt11834168
titleType                  tvEpisode
primaryTitle          Episode #14.56
originalTitle         Episode #14.56
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010359, dtype: object

(9,)

tconst                           tt1183416
titleType                        tvEpisode
primaryTitle      Episode dated 2 May 2001
originalTitle     Episode dated 2 May 2001
isAdult                                  0
startYear                             2001
endYear                                 \N
runtimeMinutes                          \N
genres                 Crime,Drama,Romance
Name: 2010360, dtype: object

(9,)

tconst                    tt11834170
titleType                  tvEpisode
primaryTitle          Episode #14.57
originalTitle         Episode #14.57
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010361, dtype: object

(9,)

tconst                    tt11834172
titleType                  tvEpisode
primaryTitle          Episode #14.58
originalTitle         Episode #14.58
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010362, dtype: object

(9,)

tconst                   tt11834174
titleType                 tvEpisode
primaryTitle      The Faculty Party
originalTitle     The Faculty Party
isAdult                           0
startYear                      2021
endYear                          \N
runtimeMinutes                   30
genres                 Comedy,Drama
Name: 2010363, dtype: object

(9,)

tconst               tt11834176
titleType             tvEpisode
primaryTitle      The Town Hall
originalTitle     The Town Hall
isAdult                       0
startYear                  2021
endYear                      \N
runtimeMinutes               30
genres             Comedy,Drama
Name: 2010364, dtype: object

(9,)

tconst                 tt11834178
titleType               tvEpisode
primaryTitle      Don't Kill Bill
originalTitle     Don't Kill Bill
isAdult                         0
startYear                    2021
endYear                        \N
runtimeMinutes                 30
genres               Comedy,Drama
Name: 2010365, dtype: object

(9,)

tconst                  tt1183417
titleType               tvEpisode
primaryTitle      Episode #1.2229
originalTitle     Episode #1.2229
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010366, dtype: object

(9,)

tconst                    tt11834180
titleType                  tvEpisode
primaryTitle          Episode #14.59
originalTitle         Episode #14.59
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010367, dtype: object

(9,)

tconst                      tt11834182
titleType                    tvEpisode
primaryTitle      The Last Bus in Town
originalTitle     The Last Bus in Town
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      30
genres                    Comedy,Drama
Name: 2010368, dtype: object

(9,)

tconst              tt11834184
titleType            tvEpisode
primaryTitle         The Chair
originalTitle        The Chair
isAdult                      0
startYear                 2021
endYear                     \N
runtimeMinutes              30
genres            Comedy,Drama
Name: 2010369, dtype: object

(9,)

tconst                    tt11834186
titleType                  tvEpisode
primaryTitle          Episode #14.63
originalTitle         Episode #14.63
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010370, dtype: object

(9,)

tconst                    tt11834188
titleType                  tvEpisode
primaryTitle          Episode #14.60
originalTitle         Episode #14.60
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010371, dtype: object

(9,)

tconst                                            tt1183418
titleType                                         tvEpisode
primaryTitle      A Shakeup of the House of Representatives
originalTitle     A Shakeup of the House of Representatives
isAdult                                                   0
startYear                                              1962
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                   \N
Name: 2010372, dtype: object

(9,)

tconst                    tt11834190
titleType                  tvEpisode
primaryTitle          Episode #14.62
originalTitle         Episode #14.62
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010373, dtype: object

(9,)

tconst                    tt11834192
titleType                  tvEpisode
primaryTitle          Episode #14.61
originalTitle         Episode #14.61
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010374, dtype: object

(9,)

tconst                    tt11834194
titleType                  tvEpisode
primaryTitle          Episode #14.64
originalTitle         Episode #14.64
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Crime,Drama
Name: 2010375, dtype: object

(9,)

tconst                                                tt11834196
titleType                                              tvEpisode
primaryTitle      Random Arma 3 Antistasi Bullshittery: Part 3/5
originalTitle     Random Arma 3 Antistasi Bullshittery: Part 3/5
isAdult                                                        0
startYear                                                   2019
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                    Comedy
Name: 2010376, dtype: object

(9,)

tconst                                                 tt11834198
titleType                                               tvEpisode
primaryTitle      El dia en que se resolveran todos sus problemas
originalTitle     El dia en que se resolveran todos sus problemas
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                      Drama
Name: 2010377, dtype: object

(9,)

tconst                  tt1183419
titleType               tvEpisode
primaryTitle      Communist China
originalTitle     Communist China
isAdult                         0
startYear                    1962
endYear                        \N
runtimeMinutes                 \N
genres                         \N
Name: 2010378, dtype: object

(9,)

tconst                                   tt11834200
titleType                                 tvEpisode
primaryTitle      Random Rocket League Bullshittery
originalTitle     Random Rocket League Bullshittery
isAdult                                           0
startYear                                      2019
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Comedy
Name: 2010379, dtype: object

(9,)

tconst                  tt11834202
titleType                tvEpisode
primaryTitle          Episode #1.8
originalTitle         Episode #1.8
isAdult                          0
startYear                     1984
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010380, dtype: object

(9,)

tconst                              tt11834204
titleType                            tvEpisode
primaryTitle      Hoppity Does Something Wrong
originalTitle     Hoppity Does Something Wrong
isAdult                                      0
startYear                                 1962
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2010381, dtype: object

(9,)

tconst                                         tt11834206
titleType                                       tvEpisode
primaryTitle      Feet fucking my boyfriend's best friend
originalTitle     Feet fucking my boyfriend's best friend
isAdult                                                 1
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                              Adult
Name: 2010382, dtype: object

(9,)

tconst                                      tt11834208
titleType                                    tvEpisode
primaryTitle      Noviy god, tvoyu divisiyu! special 1
originalTitle     Noviy god, tvoyu divisiyu! special 1
isAdult                                              0
startYear                                         2008
endYear                                             \N
runtimeMinutes                                      \N
genres                              Comedy,Crime,Drama
Name: 2010383, dtype: object

(9,)

tconst              tt1183420
titleType           tvEpisode
primaryTitle      Disarmament
originalTitle     Disarmament
isAdult                     0
startYear                1962
endYear                    \N
runtimeMinutes             \N
genres                     \N
Name: 2010384, dtype: object

(9,)

tconst                                             tt11834210
titleType                                           tvEpisode
primaryTitle      Random Space Engineers Bullshittery: Part 3
originalTitle     Random Space Engineers Bullshittery: Part 3
isAdult                                                     0
startYear                                                2019
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                 Comedy
Name: 2010385, dtype: object

(9,)

tconst                   tt11834212
titleType                 tvEpisode
primaryTitle      La bague au doigt
originalTitle     La bague au doigt
isAdult                           0
startYear                      2012
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2010386, dtype: object

(9,)

tconst                                      tt11834214
titleType                                    tvEpisode
primaryTitle      Noviy god, tvoyu divisiyu! special 2
originalTitle     Noviy god, tvoyu divisiyu! special 2
isAdult                                              0
startYear                                         2008
endYear                                             \N
runtimeMinutes                                      \N
genres                              Comedy,Crime,Drama
Name: 2010387, dtype: object

(9,)

tconst                  tt11834216
titleType                tvEpisode
primaryTitle          Episode #1.9
originalTitle         Episode #1.9
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010388, dtype: object

(9,)

tconst                                                tt11834218
titleType                                              tvEpisode
primaryTitle      Random Arma 3 Antistasi Bullshittery: Part 4/5
originalTitle     Random Arma 3 Antistasi Bullshittery: Part 4/5
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                    Comedy
Name: 2010389, dtype: object

(9,)

tconst                                          tt1183421
titleType                                       tvEpisode
primaryTitle      Does Congress Represent Public Opinion?
originalTitle     Does Congress Represent Public Opinion?
isAdult                                                 0
startYear                                            1962
endYear                                                \N
runtimeMinutes                                         \N
genres                                                 \N
Name: 2010390, dtype: object

(9,)

tconst                              tt11834220
titleType                            tvEpisode
primaryTitle      Take my pussy for a discount
originalTitle     Take my pussy for a discount
isAdult                                      1
startYear                                 2020
endYear                                     \N
runtimeMinutes                              28
genres                                   Adult
Name: 2010391, dtype: object

(9,)

tconst                                                   tt11834222
titleType                                                 tvEpisode
primaryTitle      Drew Pinsky, Lisa Ann Walter, Roselyn Sanchez,...
originalTitle     Drew Pinsky, Lisa Ann Walter, Roselyn Sanchez,...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                         Game-Show,Reality-TV
Name: 2010392, dtype: object

(9,)

tconst                  tt11834224
titleType                tvEpisode
primaryTitle         Episode #1.10
originalTitle        Episode #1.10
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010393, dtype: object

(9,)

tconst                     tt11834226
titleType                   tvEpisode
primaryTitle      A New Hat for Mummy
originalTitle     A New Hat for Mummy
isAdult                             0
startYear                        1962
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2010394, dtype: object

(9,)

tconst            tt11834228
titleType          tvEpisode
primaryTitle           Pilot
originalTitle          Pilot
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            40
genres                 Drama
Name: 2010395, dtype: object

(9,)

tconst                                                    tt1183422
titleType                                                 tvEpisode
primaryTitle      Guerilla Warfare: The Challenge in Southeast Asia
originalTitle     Guerilla Warfare: The Challenge in Southeast Asia
isAdult                                                           0
startYear                                                      1962
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2010396, dtype: object

(9,)

tconst                  tt11834230
titleType                tvEpisode
primaryTitle         Episode #1.12
originalTitle        Episode #1.12
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010397, dtype: object

(9,)

tconst               tt11834232
titleType             tvEpisode
primaryTitle      March 7, 2019
originalTitle     March 7, 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010398, dtype: object

(9,)

tconst                  tt11834234
titleType                tvEpisode
primaryTitle         Episode #1.13
originalTitle        Episode #1.13
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010399, dtype: object

(9,)

tconst                                                   tt11834236
titleType                                                 tvEpisode
primaryTitle      Robin's Anal Casting with Ariel Adams Balls De...
originalTitle     Robin's Anal Casting with Ariel Adams Balls De...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010400, dtype: object

(9,)

tconst                      tt11834238
titleType                        short
primaryTitle      A Man Called Imafuku
originalTitle     A Man Called Imafuku
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                       3
genres                    Comedy,Short
Name: 2010401, dtype: object

(9,)

tconst                                                 tt1183423
titleType                                              tvEpisode
primaryTitle      Is the Kennedy Administration Spending Enough?
originalTitle     Is the Kennedy Administration Spending Enough?
isAdult                                                        0
startYear                                                   1962
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                        \N
Name: 2010402, dtype: object

(9,)

tconst                  tt11834240
titleType                tvEpisode
primaryTitle         Episode #1.14
originalTitle        Episode #1.14
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010403, dtype: object

(9,)

tconst                tt11834242
titleType              tvEpisode
primaryTitle      March 14, 2019
originalTitle     March 14, 2019
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010404, dtype: object

(9,)

tconst                  tt11834244
titleType                tvEpisode
primaryTitle         Episode #1.15
originalTitle        Episode #1.15
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010405, dtype: object

(9,)

tconst                tt11834246
titleType              tvEpisode
primaryTitle      March 21, 2019
originalTitle     March 21, 2019
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010406, dtype: object

(9,)

tconst            tt11834248
titleType          tvEpisode
primaryTitle      A New Kite
originalTitle     A New Kite
isAdult                    0
startYear               1962
endYear                   \N
runtimeMinutes            \N
genres                Family
Name: 2010407, dtype: object

(9,)

tconst                                         tt1183424
titleType                                      tvEpisode
primaryTitle      Is the Western Alliance Falling Apart?
originalTitle     Is the Western Alliance Falling Apart?
isAdult                                                0
startYear                                           1962
endYear                                               \N
runtimeMinutes                                        \N
genres                                                \N
Name: 2010408, dtype: object

(9,)

tconst                tt11834250
titleType              tvEpisode
primaryTitle      March 28, 2019
originalTitle     March 28, 2019
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010409, dtype: object

(9,)

tconst               tt11834252
titleType             tvEpisode
primaryTitle      April 4, 2019
originalTitle     April 4, 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010410, dtype: object

(9,)

tconst                  tt11834254
titleType                tvEpisode
primaryTitle         Episode #1.16
originalTitle        Episode #1.16
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010411, dtype: object

(9,)

tconst                  tt11834256
titleType                tvEpisode
primaryTitle         Episode #1.17
originalTitle        Episode #1.17
isAdult                          0
startYear                     1985
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2010412, dtype: object

(9,)

tconst                                                   tt11834258
titleType                                                 tvEpisode
primaryTitle      Petite teen slut Scarlet Domingo assfucked by ...
originalTitle     Petite teen slut Scarlet Domingo assfucked by ...
isAdult                                                           1
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010413, dtype: object

(9,)

tconst                     tt1183425
titleType                  tvEpisode
primaryTitle      Study of a Paradox
originalTitle     Study of a Paradox
isAdult                            0
startYear                       1962
endYear                           \N
runtimeMinutes                    \N
genres                            \N
Name: 2010414, dtype: object

(9,)

tconst            tt11834262
titleType          tvEpisode
primaryTitle      Double vie
originalTitle     Double vie
isAdult                    0
startYear               2012
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2010415, dtype: object

(9,)

tconst                                                 tt11834264
titleType                                               tvEpisode
primaryTitle      Scarlet Domingo first double penetration SZ2246
originalTitle     Scarlet Domingo first double penetration SZ2246
isAdult                                                         1
startYear                                                    2019
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                      Adult
Name: 2010416, dtype: object

(9,)

tconst                tt11834266
titleType              tvEpisode
primaryTitle      Episode #10.38
originalTitle     Episode #10.38
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2010417, dtype: object

(9,)

tconst                tt11834268
titleType              tvEpisode
primaryTitle      April 11, 2019
originalTitle     April 11, 2019
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010418, dtype: object

(9,)

tconst                      tt1183426
titleType                   tvEpisode
primaryTitle      The Integrated City
originalTitle     The Integrated City
isAdult                             0
startYear                        1962
endYear                            \N
runtimeMinutes                     \N
genres                             \N
Name: 2010419, dtype: object

(9,)

tconst                tt11834270
titleType              tvEpisode
primaryTitle      April 18, 2019
originalTitle     April 18, 2019
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010420, dtype: object

(9,)

tconst            tt11834272
titleType              short
primaryTitle           Drama
originalTitle          Drama
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2010421, dtype: object

(9,)

tconst                tt11834274
titleType              tvEpisode
primaryTitle      Nishmant Group
originalTitle     Nishmant Group
isAdult                        0
startYear                   2014
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2010422, dtype: object

(9,)

tconst                                                   tt11834278
titleType                                                 tvEpisode
primaryTitle      Hot latina Scarlet Domingo assfucked balls dee...
originalTitle     Hot latina Scarlet Domingo assfucked balls dee...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010423, dtype: object

(9,)

tconst                                       tt1183427
titleType                                    tvEpisode
primaryTitle      The Short, Hectic Life of Television
originalTitle     The Short, Hectic Life of Television
isAdult                                              0
startYear                                         1962
endYear                                             \N
runtimeMinutes                                      \N
genres                                              \N
Name: 2010424, dtype: object

(9,)

tconst                           tt11834280
titleType                             movie
primaryTitle      Untitled Brig Owens Story
originalTitle     Untitled Brig Owens Story
isAdult                                   0
startYear                                \N
endYear                                  \N
runtimeMinutes                           \N
genres                                Drama
Name: 2010425, dtype: object

(9,)

tconst              tt11834282
titleType                short
primaryTitle          ARTIFICE
originalTitle         ARTIFICE
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes               5
genres            Sci-Fi,Short
Name: 2010426, dtype: object

(9,)

tconst                  tt11834284
titleType                tvEpisode
primaryTitle      The Trojan Horse
originalTitle     The Trojan Horse
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  42
genres                      Comedy
Name: 2010427, dtype: object

(9,)

tconst                                                  tt11834286
titleType                                                tvEpisode
primaryTitle      Skinny Latina Scarlet Domingo gets her ass gaped
originalTitle     Skinny Latina Scarlet Domingo gets her ass gaped
isAdult                                                          1
startYear                                                     2018
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                       Adult
Name: 2010428, dtype: object

(9,)

tconst                       tt11834288
titleType                         short
primaryTitle      FTY: Failure to Yield
originalTitle     FTY: Failure to Yield
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       19
genres                     Sci-Fi,Short
Name: 2010429, dtype: object

(9,)

tconst                        tt1183428
titleType                     tvEpisode
primaryTitle      The World of Baseball
originalTitle     The World of Baseball
isAdult                               0
startYear                          1962
endYear                              \N
runtimeMinutes                       \N
genres                               \N
Name: 2010430, dtype: object

(9,)

tconst              tt11834290
titleType            tvEpisode
primaryTitle      Episode #5.1
originalTitle     Episode #5.1
isAdult                      0
startYear                 1990
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010431, dtype: object

(9,)

tconst                     tt11834292
titleType                       short
primaryTitle            Eyes of Anger
originalTitle           Eyes of Anger
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                      5
genres            Action,Comedy,Drama
Name: 2010432, dtype: object

(9,)

tconst                    tt11834296
titleType                  tvEpisode
primaryTitle      Two Ponies at Play
originalTitle     Two Ponies at Play
isAdult                            1
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2010433, dtype: object

(9,)

tconst                     tt11834298
titleType                   tvEpisode
primaryTitle      Pandora at her Desk
originalTitle     Pandora at her Desk
isAdult                             1
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2010434, dtype: object

(9,)

tconst                            tt1183429
titleType                         tvEpisode
primaryTitle      UN Financial Difficulties
originalTitle     UN Financial Difficulties
isAdult                                   0
startYear                              1962
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2010435, dtype: object

(9,)

tconst                     tt11834300
titleType                   tvEpisode
primaryTitle      Pandora and Cherish
originalTitle     Pandora and Cherish
isAdult                             1
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2010436, dtype: object

(9,)

tconst                                  tt11834302
titleType                                tvEpisode
primaryTitle      O Sinal da Cruz - Lendas da Vovó
originalTitle     O Sinal da Cruz - Lendas da Vovó
isAdult                                          0
startYear                                     2019
endYear                                         \N
runtimeMinutes                                  \N
genres                                      Horror
Name: 2010437, dtype: object

(9,)

tconst                             tt11834304
titleType                           tvEpisode
primaryTitle      Elaine Hershey tops Pandora
originalTitle     Elaine Hershey tops Pandora
isAdult                                     1
startYear                                2008
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2010438, dtype: object

(9,)

tconst                     tt11834306
titleType                   tvEpisode
primaryTitle      Pandora chair bound
originalTitle     Pandora chair bound
isAdult                             1
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2010439, dtype: object

(9,)

tconst                           tt11834308
titleType                         tvEpisode
primaryTitle      Brittney Brooks in 2 ties
originalTitle     Brittney Brooks in 2 ties
isAdult                                   1
startYear                              2008
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2010440, dtype: object

(9,)

tconst               tt1183430
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 1983
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2010441, dtype: object

(9,)

tconst                                     tt11834310
titleType                                   tvEpisode
primaryTitle      Samantha Grace stuggles in pokadots
originalTitle     Samantha Grace stuggles in pokadots
isAdult                                             1
startYear                                        2008
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2010442, dtype: object

(9,)

tconst               tt11834312
titleType                 short
primaryTitle      Nebeneinander
originalTitle     Nebeneinander
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes                4
genres                    Short
Name: 2010443, dtype: object

(9,)

tconst                              tt11834314
titleType                            tvEpisode
primaryTitle      Gypsy bound on the love seat
originalTitle     Gypsy bound on the love seat
isAdult                                      1
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010444, dtype: object

(9,)

tconst                           tt11834316
titleType                         tvEpisode
primaryTitle      Episode dated 1 June 2015
originalTitle     Episode dated 1 June 2015
isAdult                                   0
startYear                              2015
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2010445, dtype: object

(9,)

tconst                            tt11834318
titleType                          tvEpisode
primaryTitle      Pandora tied to the stairs
originalTitle     Pandora tied to the stairs
isAdult                                    1
startYear                               2008
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2010446, dtype: object

(9,)

tconst               tt1183431
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1983
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2010447, dtype: object

(9,)

tconst              tt11834320
titleType                movie
primaryTitle      Dotty & Soul
originalTitle     Dotty & Soul
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2010448, dtype: object

(9,)

tconst                           tt11834322
titleType                         tvEpisode
primaryTitle      Episode dated 8 June 2015
originalTitle     Episode dated 8 June 2015
isAdult                                   0
startYear                              2015
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2010449, dtype: object

(9,)

tconst                              tt11834324
titleType                            tvEpisode
primaryTitle      Pandora in a straight jacket
originalTitle     Pandora in a straight jacket
isAdult                                      1
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010450, dtype: object

(9,)

tconst                            tt11834326
titleType                          tvEpisode
primaryTitle      Episode dated 15 June 2015
originalTitle     Episode dated 15 June 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2010451, dtype: object

(9,)

tconst                            tt11834328
titleType                          tvEpisode
primaryTitle      Episode dated 19 June 2015
originalTitle     Episode dated 19 June 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2010452, dtype: object

(9,)

tconst               tt1183432
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1983
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2010453, dtype: object

(9,)

tconst                            tt11834330
titleType                          tvEpisode
primaryTitle      Episode dated 22 June 2015
originalTitle     Episode dated 22 June 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2010454, dtype: object

(9,)

tconst             tt11834332
titleType           tvEpisode
primaryTitle      Mae Escapes
originalTitle     Mae Escapes
isAdult                     1
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2010455, dtype: object

(9,)

tconst                     tt11834334
titleType                       movie
primaryTitle      Evil Daisy Carnival
originalTitle     Evil Daisy Carnival
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres                         Horror
Name: 2010456, dtype: object

(9,)

tconst              tt11834336
titleType                short
primaryTitle           El Leon
originalTitle          El Leon
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres            Action,Short
Name: 2010457, dtype: object

(9,)

tconst                      tt11834338
titleType                    tvEpisode
primaryTitle      Ireland can't escape
originalTitle     Ireland can't escape
isAdult                              1
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2010458, dtype: object

(9,)

tconst                          tt1183433
titleType                       tvEpisode
primaryTitle        LazyTown Goes Digital
originalTitle       LazyTown Goes Digital
isAdult                                 0
startYear                            2007
endYear                                \N
runtimeMinutes                         23
genres            Adventure,Comedy,Family
Name: 2010459, dtype: object

(9,)

tconst                                             tt11834340
titleType                                           tvEpisode
primaryTitle      Gorgeous Latina teen masturbating in public
originalTitle     Gorgeous Latina teen masturbating in public
isAdult                                                     1
startYear                                                2017
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                  Adult
Name: 2010460, dtype: object

(9,)

tconst                 tt11834342
titleType               tvEpisode
primaryTitle      What is Tic Toc
originalTitle     What is Tic Toc
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2010461, dtype: object

(9,)

tconst                             tt11834344
titleType                               video
primaryTitle      Utsukushiki gokudô no on'na
originalTitle     Utsukushiki gokudô no on'na
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                            163
genres                                  Crime
Name: 2010462, dtype: object

(9,)

tconst                                     tt11834346
titleType                                   tvEpisode
primaryTitle      Latina teen rubs her pussy outdoors
originalTitle     Latina teen rubs her pussy outdoors
isAdult                                             1
startYear                                        2018
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2010463, dtype: object

(9,)

tconst                                             tt11834348
titleType                                           tvEpisode
primaryTitle      Latina gets her pussy pounded by black cock
originalTitle     Latina gets her pussy pounded by black cock
isAdult                                                     1
startYear                                                2018
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                  Adult
Name: 2010464, dtype: object

(9,)

tconst                          tt1183434
titleType                       tvEpisode
primaryTitle          The LazyTown Circus
originalTitle         The LazyTown Circus
isAdult                                 0
startYear                            2007
endYear                                \N
runtimeMinutes                         23
genres            Adventure,Comedy,Family
Name: 2010465, dtype: object

(9,)

tconst                               tt11834350
titleType                             tvEpisode
primaryTitle      DFP Academy: Cassandra Cuffed
originalTitle     DFP Academy: Cassandra Cuffed
isAdult                                       1
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2010466, dtype: object

(9,)

tconst                           tt11834352
titleType                         tvEpisode
primaryTitle      Saeed Shayesteh-Stockholm
originalTitle     Saeed Shayesteh-Stockholm
isAdult                                   0
startYear                              2014
endYear                                  \N
runtimeMinutes                           \N
genres                           Reality-TV
Name: 2010467, dtype: object

(9,)

tconst                                     tt11834354
titleType                                   tvEpisode
primaryTitle      Hot latina gets fucked by boyfriend
originalTitle     Hot latina gets fucked by boyfriend
isAdult                                             1
startYear                                        2019
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Adult
Name: 2010468, dtype: object

(9,)

tconst                              tt11834356
titleType                            tvEpisode
primaryTitle      DFP Academy: Sister Pranks 2
originalTitle     DFP Academy: Sister Pranks 2
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010469, dtype: object

(9,)

tconst                tt11834358
titleType              tvEpisode
primaryTitle      April 25, 2019
originalTitle     April 25, 2019
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010470, dtype: object

(9,)

tconst               tt1183435
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 1991
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2010471, dtype: object

(9,)

tconst                     tt11834360
titleType                   tvEpisode
primaryTitle      A Criança da Parede
originalTitle     A Criança da Parede
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                         Horror
Name: 2010472, dtype: object

(9,)

tconst                                                 tt11834362
titleType                                               tvEpisode
primaryTitle      DFP Academy: Whatever Happened to Sadie? Part 3
originalTitle     DFP Academy: Whatever Happened to Sadie? Part 3
isAdult                                                         1
startYear                                                    2018
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                      Adult
Name: 2010473, dtype: object

(9,)

tconst             tt11834364
titleType           tvEpisode
primaryTitle      May 2, 2019
originalTitle     May 2, 2019
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                   News
Name: 2010474, dtype: object

(9,)

tconst             tt11834366
titleType           tvEpisode
primaryTitle      May 9, 2019
originalTitle     May 9, 2019
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                   News
Name: 2010475, dtype: object

(9,)

tconst                              tt11834368
titleType                            tvEpisode
primaryTitle      DFP Academy: Stop Bugging Me
originalTitle     DFP Academy: Stop Bugging Me
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010476, dtype: object

(9,)

tconst               tt1183436
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1991
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2010477, dtype: object

(9,)

tconst              tt11834372
titleType            tvEpisode
primaryTitle      May 16, 2019
originalTitle     May 16, 2019
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2010478, dtype: object

(9,)

tconst                         tt11834374
titleType                       tvEpisode
primaryTitle      DFP Academy: Fire Alarm
originalTitle     DFP Academy: Fire Alarm
isAdult                                 1
startYear                            2018
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2010479, dtype: object

(9,)

tconst                                tt11834376
titleType                              tvEpisode
primaryTitle      DFP Academy: New Tit, Same Tat
originalTitle     DFP Academy: New Tit, Same Tat
isAdult                                        1
startYear                                   2018
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2010480, dtype: object

(9,)

tconst              tt11834378
titleType            tvEpisode
primaryTitle      May 23, 2019
originalTitle     May 23, 2019
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2010481, dtype: object

(9,)

tconst               tt1183437
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1991
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2010482, dtype: object

(9,)

tconst             tt11834380
titleType           tvEpisode
primaryTitle      Laundry Day
originalTitle     Laundry Day
isAdult                     1
startYear                2018
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2010483, dtype: object

(9,)

tconst                                         tt11834382
titleType                                        tvSeries
primaryTitle      American Tourist: Nightmare in Thailand
originalTitle     American Tourist: Nightmare in Thailand
isAdult                                                 0
startYear                                            2020
endYear                                              2020
runtimeMinutes                                         \N
genres                                           Thriller
Name: 2010484, dtype: object

(9,)

tconst              tt11834384
titleType            tvEpisode
primaryTitle      May 30, 2019
originalTitle     May 30, 2019
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2010485, dtype: object

(9,)

tconst                             tt11834386
titleType                           tvEpisode
primaryTitle      DFP Academy: Love Potion #8
originalTitle     DFP Academy: Love Potion #8
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2010486, dtype: object

(9,)

tconst              tt11834388
titleType            tvEpisode
primaryTitle      June 6, 2019
originalTitle     June 6, 2019
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2010487, dtype: object

(9,)

tconst               tt1183438
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 1991
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2010488, dtype: object

(9,)

tconst                           tt11834390
titleType                         tvEpisode
primaryTitle      A New Problem to Work Out
originalTitle     A New Problem to Work Out
isAdult                                   1
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2010489, dtype: object

(9,)

tconst               tt11834392
titleType             tvEpisode
primaryTitle      June 13, 2019
originalTitle     June 13, 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010490, dtype: object

(9,)

tconst               tt11834394
titleType             tvEpisode
primaryTitle      June 20, 2019
originalTitle     June 20, 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010491, dtype: object

(9,)

tconst                                       tt11834396
titleType                                     tvEpisode
primaryTitle      DFP Academy After Dark: Maria Resting
originalTitle     DFP Academy After Dark: Maria Resting
isAdult                                               1
startYear                                          2018
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Adult
Name: 2010492, dtype: object

(9,)

tconst               tt11834398
titleType             tvEpisode
primaryTitle      June 27, 2019
originalTitle     June 27, 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010493, dtype: object

(9,)

tconst                         tt1183439
titleType                      tvEpisode
primaryTitle      The Cold Blooded Truth
originalTitle     The Cold Blooded Truth
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        58
genres                       Documentary
Name: 2010494, dtype: object

(9,)

tconst            tt11834400
titleType          tvEpisode
primaryTitle        Hot Dare
originalTitle       Hot Dare
isAdult                    1
startYear               2018
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2010495, dtype: object

(9,)

tconst              tt11834402
titleType            tvEpisode
primaryTitle      July 4, 2019
originalTitle     July 4, 2019
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2010496, dtype: object

(9,)

tconst                              tt11834404
titleType                            tvEpisode
primaryTitle      The Meek, The Mild, The Maid
originalTitle     The Meek, The Mild, The Maid
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010497, dtype: object

(9,)

tconst                        tt11834406
titleType                      tvEpisode
primaryTitle      Sure Beats a Bake Sale
originalTitle     Sure Beats a Bake Sale
isAdult                                1
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2010498, dtype: object

(9,)

tconst                tt11834408
titleType              tvEpisode
primaryTitle      Ghostly Gloves
originalTitle     Ghostly Gloves
isAdult                        1
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2010499, dtype: object

(9,)

tconst              tt1183440
titleType           tvEpisode
primaryTitle      Eye Witness
originalTitle     Eye Witness
isAdult                     0
startYear                1959
endYear                    \N
runtimeMinutes             30
genres            Crime,Drama
Name: 2010500, dtype: object

(9,)

tconst                                         tt11834410
titleType                                       tvEpisode
primaryTitle      DFP Academy After Dark: Bailey's Karma?
originalTitle     DFP Academy After Dark: Bailey's Karma?
isAdult                                                 1
startYear                                            2018
endYear                                                \N
runtimeMinutes                                         \N
genres                                              Adult
Name: 2010501, dtype: object

(9,)

tconst             tt11834412
titleType               short
primaryTitle      No Palm Oil
originalTitle     No Palm Oil
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              5
genres                  Short
Name: 2010502, dtype: object

(9,)

tconst               tt11834414
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010503, dtype: object

(9,)

tconst                 tt11834416
titleType               tvEpisode
primaryTitle      View at the Top
originalTitle     View at the Top
isAdult                         1
startYear                    2018
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2010504, dtype: object

(9,)

tconst                                  tt11834418
titleType                                tvEpisode
primaryTitle      DFP Academy: Not Much of a Break
originalTitle     DFP Academy: Not Much of a Break
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2010505, dtype: object

(9,)

tconst             tt1183441
titleType          tvEpisode
primaryTitle      Get a Grip
originalTitle     Get a Grip
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                  News
Name: 2010506, dtype: object

(9,)

tconst               tt11834420
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010507, dtype: object

(9,)

tconst               tt11834422
titleType             tvEpisode
primaryTitle      The Kink Test
originalTitle     The Kink Test
isAdult                       1
startYear                  2018
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2010508, dtype: object

(9,)

tconst               tt11834424
titleType             tvEpisode
primaryTitle      Episode #2.23
originalTitle     Episode #2.23
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010509, dtype: object

(9,)

tconst                        tt11834426
titleType                      tvEpisode
primaryTitle      The Empress' New Codes
originalTitle     The Empress' New Codes
isAdult                                1
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2010510, dtype: object

(9,)

tconst                   tt11834428
titleType                 tvEpisode
primaryTitle      DFP Academy: SSDD
originalTitle     DFP Academy: SSDD
isAdult                           1
startYear                      2018
endYear                          \N
runtimeMinutes                   \N
genres                        Adult
Name: 2010511, dtype: object

(9,)

tconst                      tt1183442
titleType                   tvEpisode
primaryTitle      First Week Euphoria
originalTitle     First Week Euphoria
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2010512, dtype: object

(9,)

tconst                                   tt11834430
titleType                                     movie
primaryTitle      Untitled Star Wars/Exegol Project
originalTitle     Untitled Star Wars/Exegol Project
isAdult                                           0
startYear                                        \N
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Sci-Fi
Name: 2010513, dtype: object

(9,)

tconst                     tt11834432
titleType                   tvEpisode
primaryTitle      The Factory: Part 2
originalTitle     The Factory: Part 2
isAdult                             1
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2010514, dtype: object

(9,)

tconst                  tt11834434
titleType                tvEpisode
primaryTitle      Locked Out redux
originalTitle     Locked Out redux
isAdult                          1
startYear                     2018
endYear                         \N
runtimeMinutes                  \N
genres                       Adult
Name: 2010515, dtype: object

(9,)

tconst                     tt11834436
titleType                   tvEpisode
primaryTitle      The Factory: Part 4
originalTitle     The Factory: Part 4
isAdult                             1
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                          Adult
Name: 2010516, dtype: object

(9,)

tconst                          tt11834438
titleType                        tvEpisode
primaryTitle      DFP Acadmey: Sweet Break
originalTitle     DFP Acadmey: Sweet Break
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2010517, dtype: object

(9,)

tconst              tt11834440
titleType            tvEpisode
primaryTitle      Acting Coach
originalTitle     Acting Coach
isAdult                      1
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2010518, dtype: object

(9,)

tconst              tt11834442
titleType            tvEpisode
primaryTitle      The Baroness
originalTitle     The Baroness
isAdult                      1
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2010519, dtype: object

(9,)

tconst              tt11834444
titleType            tvEpisode
primaryTitle      New Neighbor
originalTitle     New Neighbor
isAdult                      1
startYear                 2020
endYear                     \N
runtimeMinutes              31
genres                   Adult
Name: 2010520, dtype: object

(9,)

tconst                                    tt11834448
titleType                                  tvEpisode
primaryTitle      DFP Academy: Back to School Part 1
originalTitle     DFP Academy: Back to School Part 1
isAdult                                            1
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2010521, dtype: object

(9,)

tconst                        tt11834452
titleType                      tvEpisode
primaryTitle      Anastasia's Directions
originalTitle     Anastasia's Directions
isAdult                                1
startYear                           2018
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2010522, dtype: object

(9,)

tconst                             tt11834454
titleType                           tvEpisode
primaryTitle      Teaching the Girls the Game
originalTitle     Teaching the Girls the Game
isAdult                                     1
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2010523, dtype: object

(9,)

tconst                                    tt11834456
titleType                                  tvEpisode
primaryTitle      DFP Academy: Back to School Part 2
originalTitle     DFP Academy: Back to School Part 2
isAdult                                            1
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2010524, dtype: object

(9,)

tconst            tt11834458
titleType          tvEpisode
primaryTitle      Sera Ryder
originalTitle     Sera Ryder
isAdult                    1
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2010525, dtype: object

(9,)

tconst                          tt1183445
titleType                       tvEpisode
primaryTitle         The Nutcracker Scoob
originalTitle        The Nutcracker Scoob
isAdult                                 0
startYear                            1984
endYear                                \N
runtimeMinutes                         12
genres            Animation,Comedy,Family
Name: 2010526, dtype: object

(9,)

tconst             tt11834460
titleType           tvEpisode
primaryTitle      No Means No
originalTitle     No Means No
isAdult                     1
startYear                2018
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2010527, dtype: object

(9,)

tconst              tt11834462
titleType                short
primaryTitle        Nine Lives
originalTitle       Nine Lives
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres            Horror,Short
Name: 2010528, dtype: object

(9,)

tconst                                    tt11834464
titleType                                  tvEpisode
primaryTitle      DFP Academy: Back to School Part 3
originalTitle     DFP Academy: Back to School Part 3
isAdult                                            1
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2010529, dtype: object

(9,)

tconst             tt11834466
titleType           tvEpisode
primaryTitle      Marked Deck
originalTitle     Marked Deck
isAdult                     1
startYear                2018
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2010530, dtype: object

(9,)

tconst                       tt11834468
titleType                     tvEpisode
primaryTitle      Salar Biria-Stockholm
originalTitle     Salar Biria-Stockholm
isAdult                               0
startYear                          2014
endYear                              \N
runtimeMinutes                       \N
genres                       Reality-TV
Name: 2010531, dtype: object

(9,)

tconst               tt1183446
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2010532, dtype: object

(9,)

tconst                                    tt11834470
titleType                                  tvEpisode
primaryTitle      DFP Academy: Back to School Part 4
originalTitle     DFP Academy: Back to School Part 4
isAdult                                            1
startYear                                       2018
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2010533, dtype: object

(9,)

tconst                         tt11834472
titleType                       tvEpisode
primaryTitle      DFP Academy: Blind Date
originalTitle     DFP Academy: Blind Date
isAdult                                 1
startYear                            2018
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2010534, dtype: object

(9,)

tconst              tt11834474
titleType            tvEpisode
primaryTitle      Bailey's Bet
originalTitle     Bailey's Bet
isAdult                      1
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2010535, dtype: object

(9,)

tconst                       tt11834476
titleType                     tvEpisode
primaryTitle      Bring in the Big Guns
originalTitle     Bring in the Big Guns
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       44
genres                       Reality-TV
Name: 2010536, dtype: object

(9,)

tconst                              tt11834478
titleType                            tvEpisode
primaryTitle      DFP Academy: Hit the Showers
originalTitle     DFP Academy: Hit the Showers
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010537, dtype: object

(9,)

tconst               tt1183447
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2010538, dtype: object

(9,)

tconst                           tt11834480
titleType                         tvEpisode
primaryTitle      Sucked By The Soccer Milf
originalTitle     Sucked By The Soccer Milf
isAdult                                   1
startYear                              2018
endYear                                  \N
runtimeMinutes                           34
genres                                Adult
Name: 2010539, dtype: object

(9,)

tconst                              tt11834482
titleType                            tvEpisode
primaryTitle      DFP Academy: Bye Bye Suckers
originalTitle     DFP Academy: Bye Bye Suckers
isAdult                                      1
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010540, dtype: object

(9,)

tconst               tt11834484
titleType             tvEpisode
primaryTitle      July 11, 2019
originalTitle     July 11, 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010541, dtype: object

(9,)

tconst                                 tt11834486
titleType                               tvEpisode
primaryTitle      DFP Academy: Bye Bye Suckers II
originalTitle     DFP Academy: Bye Bye Suckers II
isAdult                                         1
startYear                                    2018
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2010542, dtype: object

(9,)

tconst                           tt11834488
titleType                          tvSeries
primaryTitle      Inside Bedford-Stuyvesant
originalTitle     Inside Bedford-Stuyvesant
isAdult                                   0
startYear                              1968
endYear                                1971
runtimeMinutes                           \N
genres                          Documentary
Name: 2010543, dtype: object

(9,)

tconst               tt1183448
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2010544, dtype: object

(9,)

tconst                                  tt11834490
titleType                                tvEpisode
primaryTitle      DFP Academy: Unexpected Swelling
originalTitle     DFP Academy: Unexpected Swelling
isAdult                                          1
startYear                                     2018
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2010545, dtype: object

(9,)

tconst               tt11834492
titleType             tvEpisode
primaryTitle      July 18, 2019
originalTitle     July 18, 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010546, dtype: object

(9,)

tconst               tt11834494
titleType             tvEpisode
primaryTitle      July 25, 2019
originalTitle     July 25, 2019
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2010547, dtype: object

(9,)

tconst                tt11834498
titleType              tvEpisode
primaryTitle      August 1, 2019
originalTitle     August 1, 2019
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010548, dtype: object

(9,)

tconst            tt1183449
titleType         tvEpisode
primaryTitle       Aardvark
originalTitle      Aardvark
isAdult                   0
startYear              1989
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2010549, dtype: object

(9,)

tconst              tt11834500
titleType            tvEpisode
primaryTitle      Fuck My Wife
originalTitle     Fuck My Wife
isAdult                      1
startYear                 2014
endYear                     \N
runtimeMinutes              23
genres                   Adult
Name: 2010550, dtype: object

(9,)

tconst                tt11834502
titleType              tvEpisode
primaryTitle      August 8, 2019
originalTitle     August 8, 2019
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010551, dtype: object

(9,)

tconst            tt11834504
titleType              movie
primaryTitle       Deep Fake
originalTitle      Deep Fake
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            \N
genres              Thriller
Name: 2010552, dtype: object

(9,)

tconst                         tt11834506
titleType                           video
primaryTitle      Alex Anwandter: Tatuaje
originalTitle     Alex Anwandter: Tatuaje
isAdult                                 0
startYear                            2012
endYear                                \N
runtimeMinutes                          4
genres                        Music,Short
Name: 2010553, dtype: object

(9,)

tconst                              tt11834508
titleType                            tvEpisode
primaryTitle             Italy & Mediterranean
originalTitle            Italy & Mediterranean
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres            Biography,History,Reality-TV
Name: 2010554, dtype: object

(9,)

tconst            tt1183450
titleType         tvEpisode
primaryTitle          Bison
originalTitle         Bison
isAdult                   0
startYear              1989
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2010555, dtype: object

(9,)

tconst                 tt11834510
titleType               tvEpisode
primaryTitle      August 15, 2019
originalTitle     August 15, 2019
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                       News
Name: 2010556, dtype: object

(9,)

tconst                                                  tt11834512
titleType                                                tvEpisode
primaryTitle      Very First Painful Anal Fuck for Sweet Butterfly
originalTitle     Very First Painful Anal Fuck for Sweet Butterfly
isAdult                                                          1
startYear                                                     2019
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                       Adult
Name: 2010557, dtype: object

(9,)

tconst                 tt11834514
titleType               tvEpisode
primaryTitle      August 22, 2019
originalTitle     August 22, 2019
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                       News
Name: 2010558, dtype: object

(9,)

tconst                                  tt11834516
titleType                                    short
primaryTitle      Si no, viene el Cuco y te comerá
originalTitle     Si no, viene el Cuco y te comerá
isAdult                                          0
startYear                                     2018
endYear                                         \N
runtimeMinutes                                   3
genres                    Animation,Fantasy,Horror
Name: 2010559, dtype: object

(9,)

tconst                   tt11834518
titleType                 tvEpisode
primaryTitle      Mommy Understands
originalTitle     Mommy Understands
isAdult                           1
startYear                      2020
endYear                          \N
runtimeMinutes                   18
genres                        Adult
Name: 2010560, dtype: object

(9,)

tconst               tt1183451
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2010561, dtype: object

(9,)

tconst                                                   tt11834520
titleType                                                 tvEpisode
primaryTitle      Sweetie Plum First Time DP with Rough Action, ...
originalTitle     Sweetie Plum First Time DP with Rough Action, ...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010562, dtype: object

(9,)

tconst             tt11834522
titleType           tvEpisode
primaryTitle          Bananas
originalTitle         Bananas
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             \N
genres            Crime,Drama
Name: 2010563, dtype: object

(9,)

tconst                   tt11834524
titleType                     short
primaryTitle           Ypsi's Emoni
originalTitle          Ypsi's Emoni
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   20
genres            Documentary,Short
Name: 2010564, dtype: object

(9,)

tconst                                                   tt11834526
titleType                                                 tvEpisode
primaryTitle      Young teen Sweetie Plum comes to test black bu...
originalTitle     Young teen Sweetie Plum comes to test black bu...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010565, dtype: object

(9,)

tconst                                             tt11834528
titleType                                           tvEpisode
primaryTitle      On the Road: Las Vegas - "Tale of the Tape"
originalTitle     On the Road: Las Vegas - "Tale of the Tape"
isAdult                                                     0
startYear                                                2020
endYear                                                    \N
runtimeMinutes                                            120
genres                                   News,Sport,Talk-Show
Name: 2010566, dtype: object

(9,)

tconst               tt1183452
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2010567, dtype: object

(9,)

tconst             tt11834530
titleType               short
primaryTitle        Night Cab
originalTitle       Night Cab
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             16
genres            Drama,Short
Name: 2010568, dtype: object

(9,)

tconst                     tt11834532
titleType                       short
primaryTitle           Your Best Shot
originalTitle          Your Best Shot
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Short
Name: 2010569, dtype: object

(9,)

tconst                tt11834534
titleType              tvEpisode
primaryTitle      Kiss My Booboo
originalTitle     Kiss My Booboo
isAdult                        1
startYear                   2018
endYear                       \N
runtimeMinutes                19
genres                     Adult
Name: 2010570, dtype: object

(9,)

tconst                                     tt11834536
titleType                                    tvSeries
primaryTitle      The Killing of Three Thousand Crows
originalTitle     The Killing of Three Thousand Crows
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                      Adventure,Fantasy,History
Name: 2010571, dtype: object

(9,)

tconst                 tt11834538
titleType               tvEpisode
primaryTitle      Holiday Swagger
originalTitle     Holiday Swagger
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2010572, dtype: object

(9,)

tconst               tt1183453
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2010573, dtype: object

(9,)

tconst                  tt11834540
titleType                 tvSeries
primaryTitle      The Great Debate
originalTitle     The Great Debate
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  22
genres            Comedy,Talk-Show
Name: 2010574, dtype: object

(9,)

tconst                              tt11834542
titleType                            tvEpisode
primaryTitle      Why Do People Like Exercise?
originalTitle     Why Do People Like Exercise?
isAdult                                      0
startYear                                 2018
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2010575, dtype: object

(9,)

tconst                                tt11834544
titleType                              tvEpisode
primaryTitle      Kendra's Thanksgiving Stuffing
originalTitle     Kendra's Thanksgiving Stuffing
isAdult                                        1
startYear                                   2016
endYear                                       \N
runtimeMinutes                                32
genres                                     Adult
Name: 2010576, dtype: object

(9,)

tconst                      tt11834546
titleType                    tvEpisode
primaryTitle              Episode #1.7
originalTitle             Episode #1.7
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010577, dtype: object

(9,)

tconst                      tt11834548
titleType                    tvEpisode
primaryTitle              Episode #1.2
originalTitle             Episode #1.2
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010578, dtype: object

(9,)

tconst                  tt1183454
titleType               tvEpisode
primaryTitle      Episode #1.1264
originalTitle     Episode #1.1264
isAdult                         0
startYear                    1989
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010579, dtype: object

(9,)

tconst                                                   tt11834550
titleType                                                 tvEpisode
primaryTitle      Holiday Episode w/ Ladee Danger & Jumbo Commander
originalTitle     Holiday Episode w/ Ladee Danger & Jumbo Commander
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Game-Show
Name: 2010580, dtype: object

(9,)

tconst                      tt11834552
titleType                    tvEpisode
primaryTitle              Episode #1.3
originalTitle             Episode #1.3
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010581, dtype: object

(9,)

tconst                      tt11834554
titleType                    tvEpisode
primaryTitle              Episode #1.8
originalTitle             Episode #1.8
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010582, dtype: object

(9,)

tconst                      tt11834556
titleType                    tvEpisode
primaryTitle              Episode #1.5
originalTitle             Episode #1.5
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010583, dtype: object

(9,)

tconst                      tt11834558
titleType                    tvEpisode
primaryTitle              Episode #1.4
originalTitle             Episode #1.4
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010584, dtype: object

(9,)

tconst                                     tt1183455
titleType                                  tvEpisode
primaryTitle      When You Wish Upon a Star Creature
originalTitle     When You Wish Upon a Star Creature
isAdult                                            0
startYear                                       1979
endYear                                           \N
runtimeMinutes                                    24
genres                    Adventure,Animation,Comedy
Name: 2010585, dtype: object

(9,)

tconst                      tt11834560
titleType                    tvEpisode
primaryTitle              Episode #1.6
originalTitle             Episode #1.6
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010586, dtype: object

(9,)

tconst                              tt11834562
titleType                                movie
primaryTitle      Labordeta, un hombre sin más
originalTitle     Labordeta, un hombre sin más
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                             Documentary
Name: 2010587, dtype: object

(9,)

tconst                      tt11834564
titleType                    tvEpisode
primaryTitle           Infierno blanco
originalTitle          Infierno blanco
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010588, dtype: object

(9,)

tconst            tt11834566
titleType          tvEpisode
primaryTitle          No. 06
originalTitle         No. 06
isAdult                    0
startYear               1959
endYear                   \N
runtimeMinutes            \N
genres                 Music
Name: 2010589, dtype: object

(9,)

tconst                 tt11834568
titleType               tvEpisode
primaryTitle      August 29, 2019
originalTitle     August 29, 2019
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                       News
Name: 2010590, dtype: object

(9,)

tconst                      tt1183456
titleType                   tvEpisode
primaryTitle      Unsafe at Any Speed
originalTitle     Unsafe at Any Speed
isAdult                             0
startYear                        1987
endYear                            \N
runtimeMinutes                     \N
genres                         Comedy
Name: 2010591, dtype: object

(9,)

tconst                   tt11834570
titleType                 tvEpisode
primaryTitle      September 5, 2019
originalTitle     September 5, 2019
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2010592, dtype: object

(9,)

tconst                    tt11834572
titleType                  tvEpisode
primaryTitle      September 12, 2019
originalTitle     September 12, 2019
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                          News
Name: 2010593, dtype: object

(9,)

tconst                    tt11834574
titleType                  tvEpisode
primaryTitle      September 19, 2019
originalTitle     September 19, 2019
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                          News
Name: 2010594, dtype: object

(9,)

tconst                                    tt11834576
titleType                                  tvEpisode
primaryTitle      Mae proves she is an escape artist
originalTitle     Mae proves she is an escape artist
isAdult                                            1
startYear                                       2008
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2010595, dtype: object

(9,)

tconst            tt11834578
titleType          tvEpisode
primaryTitle          No. 07
originalTitle         No. 07
isAdult                    0
startYear               1959
endYear                   \N
runtimeMinutes            \N
genres                 Music
Name: 2010596, dtype: object

(9,)

tconst               tt1183457
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2010597, dtype: object

(9,)

tconst                   tt11834580
titleType                     short
primaryTitle               El Tunel
originalTitle              El Tunel
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2010598, dtype: object

(9,)

tconst                      tt11834582
titleType                    tvEpisode
primaryTitle              Soy inocente
originalTitle             Soy inocente
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010599, dtype: object

(9,)

tconst                                tt11834584
titleType                              tvEpisode
primaryTitle      Gypsy in cold medievel bondage
originalTitle     Gypsy in cold medievel bondage
isAdult                                        1
startYear                                   2008
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2010600, dtype: object

(9,)

tconst                             tt11834586
titleType                           tvEpisode
primaryTitle      Ireland in thigh high boots
originalTitle     Ireland in thigh high boots
isAdult                                     1
startYear                                2008
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2010601, dtype: object

(9,)

tconst                        tt11834588
titleType                      tvEpisode
primaryTitle      Gypsy in the armbinder
originalTitle     Gypsy in the armbinder
isAdult                                1
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2010602, dtype: object

(9,)

tconst               tt1183458
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2010603, dtype: object

(9,)

tconst                               tt11834590
titleType                             tvEpisode
primaryTitle      Pandora bound in a hotel room
originalTitle     Pandora bound in a hotel room
isAdult                                       1
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                    Adult
Name: 2010604, dtype: object

(9,)

tconst            tt11834592
titleType           tvSeries
primaryTitle          Gaslit
originalTitle         Gaslit
isAdult                    0
startYear               2021
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2010605, dtype: object

(9,)

tconst                              tt11834594
titleType                            tvEpisode
primaryTitle      Ireland on the massage table
originalTitle     Ireland on the massage table
isAdult                                      1
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010606, dtype: object

(9,)

tconst                             tt11834596
titleType                           tvEpisode
primaryTitle      Zar Music Festival-Part one
originalTitle     Zar Music Festival-Part one
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres                             Reality-TV
Name: 2010607, dtype: object

(9,)

tconst                      tt11834598
titleType                    tvEpisode
primaryTitle      Pandora over a table
originalTitle     Pandora over a table
isAdult                              1
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2010608, dtype: object

(9,)

tconst               tt1183459
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2010609, dtype: object

(9,)

tconst                          tt11834600
titleType                        tvEpisode
primaryTitle      Gypsy mummifed to a pole
originalTitle     Gypsy mummifed to a pole
isAdult                                  1
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2010610, dtype: object

(9,)

tconst                                    tt11834602
titleType                                  tvEpisode
primaryTitle      Mae in Ballet Boots and Arm Binder
originalTitle     Mae in Ballet Boots and Arm Binder
isAdult                                            1
startYear                                       2008
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Adult
Name: 2010611, dtype: object

(9,)

tconst                                 tt11834604
titleType                               tvEpisode
primaryTitle      Ireland escapes from a frog tie
originalTitle     Ireland escapes from a frog tie
isAdult                                         1
startYear                                    2008
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Adult
Name: 2010612, dtype: object

(9,)

tconst             tt11834606
titleType           tvEpisode
primaryTitle        Santuario
originalTitle       Santuario
isAdult                     1
startYear                2016
endYear                    \N
runtimeMinutes             \N
genres            Adult,Short
Name: 2010613, dtype: object

(9,)

tconst                          tt11834608
titleType                        tvEpisode
primaryTitle      Pandora on the hotel bed
originalTitle     Pandora on the hotel bed
isAdult                                  1
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2010614, dtype: object

(9,)

tconst               tt1183460
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2010615, dtype: object

(9,)

tconst                    tt11834610
titleType                  tvEpisode
primaryTitle      Gypsy on the couch
originalTitle     Gypsy on the couch
isAdult                            1
startYear                       2008
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2010616, dtype: object

(9,)

tconst                 tt11834612
titleType               tvEpisode
primaryTitle      Ireland escapes
originalTitle     Ireland escapes
isAdult                         1
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2010617, dtype: object

(9,)

tconst                                                   tt11834614
titleType                                                 tvEpisode
primaryTitle      The Fastest Thing Ever On Earth (Explosion Wed...
originalTitle     The Fastest Thing Ever On Earth (Explosion Wed...
isAdult                                                           0
startYear                                                      2017
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2010618, dtype: object

(9,)

tconst               tt11834616
titleType             tvEpisode
primaryTitle      Mae frog tied
originalTitle     Mae frog tied
isAdult                       1
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2010619, dtype: object

(9,)

tconst                  tt11834618
titleType                    video
primaryTitle      Chaozz: Televize
originalTitle     Chaozz: Televize
isAdult                          0
startYear                     1996
endYear                         \N
runtimeMinutes                   3
genres                 Music,Short
Name: 2010620, dtype: object

(9,)

tconst               tt1183461
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2010621, dtype: object

(9,)

tconst                   tt11834620
titleType                     movie
primaryTitle      Gobi Women's Song
originalTitle     Gobi Women's Song
isAdult                           0
startYear                      2006
endYear                          \N
runtimeMinutes                   72
genres                  Documentary
Name: 2010622, dtype: object

(9,)

tconst                          tt11834622
titleType                        tvEpisode
primaryTitle      Pandora by the fireplace
originalTitle     Pandora by the fireplace
isAdult                                  1
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2010623, dtype: object

(9,)

tconst                             tt11834624
titleType                           tvEpisode
primaryTitle      Christina Carter at the bar
originalTitle     Christina Carter at the bar
isAdult                                     1
startYear                                2008
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2010624, dtype: object

(9,)

tconst                              tt11834626
titleType                            tvEpisode
primaryTitle      Pandora in her new red dress
originalTitle     Pandora in her new red dress
isAdult                                      1
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010625, dtype: object

(9,)

tconst                                  tt11834628
titleType                                tvEpisode
primaryTitle      Pandora in pink thigh high boots
originalTitle     Pandora in pink thigh high boots
isAdult                                          1
startYear                                     2008
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Adult
Name: 2010626, dtype: object

(9,)

tconst            tt1183462
titleType         tvEpisode
primaryTitle       Dr. Who?
originalTitle      Dr. Who?
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2010627, dtype: object

(9,)

tconst                          tt11834630
titleType                        tvEpisode
primaryTitle      Pandora tied to the pole
originalTitle     Pandora tied to the pole
isAdult                                  1
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2010628, dtype: object

(9,)

tconst                             tt11834632
titleType                           tvEpisode
primaryTitle      Zar Music Festival-Part Two
originalTitle     Zar Music Festival-Part Two
isAdult                                     0
startYear                                2014
endYear                                    \N
runtimeMinutes                             \N
genres                             Reality-TV
Name: 2010629, dtype: object

(9,)

tconst                         tt11834634
titleType                       tvEpisode
primaryTitle      Pandora gets a spanking
originalTitle     Pandora gets a spanking
isAdult                                 1
startYear                            2008
endYear                                \N
runtimeMinutes                         \N
genres                              Adult
Name: 2010630, dtype: object

(9,)

tconst                                       tt11834636
titleType                                     tvEpisode
primaryTitle      Newt Struggles hard against the ropes
originalTitle     Newt Struggles hard against the ropes
isAdult                                               1
startYear                                          2008
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Adult
Name: 2010631, dtype: object

(9,)

tconst                                 tt11834638
titleType                               tvEpisode
primaryTitle      Boston College at Arizona State
originalTitle     Boston College at Arizona State
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                                      Sport
Name: 2010632, dtype: object

(9,)

tconst                   tt1183463
titleType                tvEpisode
primaryTitle        Nature's Child
originalTitle       Nature's Child
isAdult                          0
startYear                     1976
endYear                         \N
runtimeMinutes                  24
genres            Adventure,Family
Name: 2010633, dtype: object

(9,)

tconst                       tt11834640
titleType                         video
primaryTitle      Beautiful Handwriting
originalTitle     Beautiful Handwriting
isAdult                               0
startYear                          2019
endYear                              \N
runtimeMinutes                       15
genres                            Short
Name: 2010634, dtype: object

(9,)

tconst             tt11834642
titleType               movie
primaryTitle            Bytie
originalTitle           Bytie
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes             57
genres            Documentary
Name: 2010635, dtype: object

(9,)

tconst                    tt11834644
titleType                  tvEpisode
primaryTitle      September 26, 2019
originalTitle     September 26, 2019
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                          News
Name: 2010636, dtype: object

(9,)

tconst                  tt11834646
titleType                tvEpisode
primaryTitle      Nevada at Oregon
originalTitle     Nevada at Oregon
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                       Sport
Name: 2010637, dtype: object

(9,)

tconst                      tt11834648
titleType                    tvEpisode
primaryTitle           Sin vida propia
originalTitle          Sin vida propia
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010638, dtype: object

(9,)

tconst                       tt1183464
titleType                    tvEpisode
primaryTitle      Return from Paradise
originalTitle     Return from Paradise
isAdult                              0
startYear                         1976
endYear                             \N
runtimeMinutes                      24
genres                Adventure,Family
Name: 2010639, dtype: object

(9,)

tconst                 tt11834650
titleType               tvEpisode
primaryTitle      October 3, 2019
originalTitle     October 3, 2019
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                       News
Name: 2010640, dtype: object

(9,)

tconst                  tt11834652
titleType                tvEpisode
primaryTitle      October 10, 2019
originalTitle     October 10, 2019
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010641, dtype: object

(9,)

tconst                  tt11834654
titleType                tvEpisode
primaryTitle      October 17, 2019
originalTitle     October 17, 2019
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010642, dtype: object

(9,)

tconst              tt11834656
titleType                short
primaryTitle      Time to Kill
originalTitle     Time to Kill
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes               7
genres                   Short
Name: 2010643, dtype: object

(9,)

tconst                  tt1183465
titleType                tvSeries
primaryTitle      Three Wide Life
originalTitle     Three Wide Life
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 30
genres                      Sport
Name: 2010644, dtype: object

(9,)

tconst                  tt11834660
titleType                tvEpisode
primaryTitle      October 24, 2019
originalTitle     October 24, 2019
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010645, dtype: object

(9,)

tconst            tt11834662
titleType              short
primaryTitle       Old Young
originalTitle      Old Young
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            17
genres                 Short
Name: 2010646, dtype: object

(9,)

tconst                  tt11834668
titleType                tvEpisode
primaryTitle      October 31, 2019
originalTitle     October 31, 2019
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010647, dtype: object

(9,)

tconst                         tt1183466
titleType                      tvEpisode
primaryTitle                Scary Hoover
originalTitle               Scary Hoover
isAdult                                0
startYear                           2007
endYear                               \N
runtimeMinutes                        22
genres            Drama,Reality-TV,Sport
Name: 2010648, dtype: object

(9,)

tconst                  tt11834670
titleType                tvEpisode
primaryTitle      November 7, 2019
originalTitle     November 7, 2019
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010649, dtype: object

(9,)

tconst                   tt11834672
titleType                 tvEpisode
primaryTitle      November 14, 2019
originalTitle     November 14, 2019
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2010650, dtype: object

(9,)

tconst                   tt11834674
titleType                 tvEpisode
primaryTitle      November 21, 2019
originalTitle     November 21, 2019
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2010651, dtype: object

(9,)

tconst                   tt11834676
titleType                 tvEpisode
primaryTitle      November 28, 2019
originalTitle     November 28, 2019
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2010652, dtype: object

(9,)

tconst                                  tt11834678
titleType                                tvEpisode
primaryTitle      The Kamkars performance in Farsi
originalTitle     The Kamkars performance in Farsi
isAdult                                          0
startYear                                     2014
endYear                                         \N
runtimeMinutes                                  \N
genres                                  Reality-TV
Name: 2010653, dtype: object

(9,)

tconst                      tt1183467
titleType                   tvEpisode
primaryTitle      Backstabber: Part 1
originalTitle     Backstabber: Part 1
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                      Animation
Name: 2010654, dtype: object

(9,)

tconst                                                   tt11834682
titleType                                                 tvEpisode
primaryTitle      Mina manhandled to her first TRIPLE PENETRATIO...
originalTitle     Mina manhandled to her first TRIPLE PENETRATIO...
isAdult                                                           1
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010655, dtype: object

(9,)

tconst                   tt11834684
titleType                 tvEpisode
primaryTitle      December 12, 2019
originalTitle     December 12, 2019
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2010656, dtype: object

(9,)

tconst                                                   tt11834686
titleType                                                 tvEpisode
primaryTitle      Tiny teen slut Mina monster cock fuck session ...
originalTitle     Tiny teen slut Mina monster cock fuck session ...
isAdult                                                           1
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010657, dtype: object

(9,)

tconst                  tt11834688
titleType                tvEpisode
primaryTitle      December 5, 2019
originalTitle     December 5, 2019
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010658, dtype: object

(9,)

tconst                      tt1183468
titleType                   tvEpisode
primaryTitle      Backstabber: Part 2
originalTitle     Backstabber: Part 2
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres                      Animation
Name: 2010659, dtype: object

(9,)

tconst                                                   tt11834690
titleType                                                 tvEpisode
primaryTitle      Petite teen slut Mina first interracial (DP & ...
originalTitle     Petite teen slut Mina first interracial (DP & ...
isAdult                                                           1
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010660, dtype: object

(9,)

tconst                     tt11834692
titleType                   tvEpisode
primaryTitle      Directors' Cut 2019
originalTitle     Directors' Cut 2019
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                           News
Name: 2010661, dtype: object

(9,)

tconst                tt11834694
titleType               tvSeries
primaryTitle         Duty's Veil
originalTitle        Duty's Veil
isAdult                        0
startYear                   2019
endYear                     2019
runtimeMinutes                \N
genres            Crime,Thriller
Name: 2010662, dtype: object

(9,)

tconst                 tt11834696
titleType               tvEpisode
primaryTitle      January 9, 2020
originalTitle     January 9, 2020
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                       News
Name: 2010663, dtype: object

(9,)

tconst                  tt11834698
titleType                tvEpisode
primaryTitle      January 16, 2020
originalTitle     January 16, 2020
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010664, dtype: object

(9,)

tconst            tt1183469
titleType         tvEpisode
primaryTitle      Green Goo
originalTitle     Green Goo
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres            Animation
Name: 2010665, dtype: object

(9,)

tconst            tt11834700
titleType          tvEpisode
primaryTitle          No. 08
originalTitle         No. 08
isAdult                    0
startYear               1959
endYear                   \N
runtimeMinutes            \N
genres                 Music
Name: 2010666, dtype: object

(9,)

tconst                  tt11834702
titleType                tvEpisode
primaryTitle      January 23, 2020
originalTitle     January 23, 2020
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010667, dtype: object

(9,)

tconst                                                   tt11834704
titleType                                                 tvEpisode
primaryTitle      Waka Waka Blacks are coming Mina gets 5 BBC Ba...
originalTitle     Waka Waka Blacks are coming Mina gets 5 BBC Ba...
isAdult                                                           1
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2010668, dtype: object

(9,)

tconst                  tt11834706
titleType                tvEpisode
primaryTitle      January 30, 2020
originalTitle     January 30, 2020
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010669, dtype: object

(9,)

tconst              tt11834708
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010670, dtype: object

(9,)

tconst                        tt1183470
titleType                     tvEpisode
primaryTitle      William and the Whale
originalTitle     William and the Whale
isAdult                               0
startYear                          1994
endYear                              \N
runtimeMinutes                       \N
genres                 Animation,Family
Name: 2010671, dtype: object

(9,)

tconst                  tt11834710
titleType                tvEpisode
primaryTitle      February 6, 2020
originalTitle     February 6, 2020
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                        News
Name: 2010672, dtype: object

(9,)

tconst                   tt11834712
titleType                 tvEpisode
primaryTitle      February 13, 2020
originalTitle     February 13, 2020
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2010673, dtype: object

(9,)

tconst                   tt11834714
titleType                 tvEpisode
primaryTitle      February 20, 2020
originalTitle     February 20, 2020
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                         News
Name: 2010674, dtype: object

(9,)

tconst              tt11834716
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010675, dtype: object

(9,)

tconst                  tt1183471
titleType               tvEpisode
primaryTitle      Episode #1.8826
originalTitle     Episode #1.8826
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010676, dtype: object

(9,)

tconst                                          tt11834720
titleType                                        tvEpisode
primaryTitle      Mina assfucked 3on1 with DP & DAP SZ2404
originalTitle     Mina assfucked 3on1 with DP & DAP SZ2404
isAdult                                                  1
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                               Adult
Name: 2010677, dtype: object

(9,)

tconst              tt11834724
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010678, dtype: object

(9,)

tconst                       tt11834726
titleType                     tvEpisode
primaryTitle      I Met An Axe Murderer
originalTitle     I Met An Axe Murderer
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                        7
genres                 Adventure,Comedy
Name: 2010679, dtype: object

(9,)

tconst                                                   tt11834728
titleType                                                 tvEpisode
primaryTitle      Mina goes for a massage and gets fingered and ...
originalTitle     Mina goes for a massage and gets fingered and ...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010680, dtype: object

(9,)

tconst                  tt1183472
titleType               tvEpisode
primaryTitle      Episode #1.3377
originalTitle     Episode #1.3377
isAdult                         0
startYear                    1986
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010681, dtype: object

(9,)

tconst                                                   tt11834732
titleType                                                 tvEpisode
primaryTitle      Double penetration domination of patient Mina ...
originalTitle     Double penetration domination of patient Mina ...
isAdult                                                           1
startYear                                                      2018
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Adult
Name: 2010682, dtype: object

(9,)

tconst              tt11834734
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010683, dtype: object

(9,)

tconst               tt11834738
titleType             tvEpisode
primaryTitle      Food Delivery
originalTitle     Food Delivery
isAdult                       1
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2010684, dtype: object

(9,)

tconst                  tt1183473
titleType               tvEpisode
primaryTitle      Episode #1.3383
originalTitle     Episode #1.3383
isAdult                         0
startYear                    1986
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010685, dtype: object

(9,)

tconst                         tt11834740
titleType                       tvEpisode
primaryTitle      Soheil Shadloo-Brno Gun
originalTitle     Soheil Shadloo-Brno Gun
isAdult                                 0
startYear                            2014
endYear                                \N
runtimeMinutes                         \N
genres                         Reality-TV
Name: 2010686, dtype: object

(9,)

tconst                         tt11834742
titleType                       tvEpisode
primaryTitle      Unas paredes que gritan
originalTitle     Unas paredes que gritan
isAdult                                 0
startYear                            1999
endYear                                \N
runtimeMinutes                         \N
genres               Crime,Drama,Thriller
Name: 2010687, dtype: object

(9,)

tconst                        tt11834744
titleType                      tvEpisode
primaryTitle      Domination By The Lake
originalTitle     Domination By The Lake
isAdult                                1
startYear                           2019
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2010688, dtype: object

(9,)

tconst              tt11834746
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010689, dtype: object

(9,)

tconst                          tt11834748
titleType                        tvEpisode
primaryTitle      Tutorial in Hardcore Sex
originalTitle     Tutorial in Hardcore Sex
isAdult                                  1
startYear                             2018
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2010690, dtype: object

(9,)

tconst                  tt1183474
titleType               tvEpisode
primaryTitle      Episode #1.3390
originalTitle     Episode #1.3390
isAdult                         0
startYear                    1986
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010691, dtype: object

(9,)

tconst                                                  tt11834750
titleType                                                tvEpisode
primaryTitle      Horny Teen Fingered and Fucked in Massage Parlor
originalTitle     Horny Teen Fingered and Fucked in Massage Parlor
isAdult                                                          1
startYear                                                     2020
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                       Adult
Name: 2010692, dtype: object

(9,)

tconst             tt11834752
titleType            tvSeries
primaryTitle      View & Chew
originalTitle     View & Chew
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres             Reality-TV
Name: 2010693, dtype: object

(9,)

tconst                      tt11834754
titleType                        short
primaryTitle      The Contract Musical
originalTitle     The Contract Musical
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                       7
genres                   Musical,Short
Name: 2010694, dtype: object

(9,)

tconst              tt11834756
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010695, dtype: object

(9,)

tconst                                tt11834758
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2010696, dtype: object

(9,)

tconst               tt1183475
titleType                short
primaryTitle             $1.11
originalTitle            $1.11
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              15
genres            Family,Short
Name: 2010697, dtype: object

(9,)

tconst               tt11834760
titleType              tvSeries
primaryTitle      Battlegrounds
originalTitle     Battlegrounds
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                 Thriller
Name: 2010698, dtype: object

(9,)

tconst             tt11834762
titleType           tvEpisode
primaryTitle      Wild Beauty
originalTitle     Wild Beauty
isAdult                     1
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2010699, dtype: object

(9,)

tconst              tt11834764
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010700, dtype: object

(9,)

tconst             tt11834768
titleType           tvEpisode
primaryTitle      Mina Medina
originalTitle     Mina Medina
isAdult                     1
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2010701, dtype: object

(9,)

tconst                         tt1183476
titleType                      tvSpecial
primaryTitle      1971 MLB All-Star Game
originalTitle     1971 MLB All-Star Game
isAdult                                0
startYear                           1971
endYear                               \N
runtimeMinutes                       125
genres                             Sport
Name: 2010702, dtype: object

(9,)

tconst              tt11834770
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010703, dtype: object

(9,)

tconst                                tt11834772
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2010704, dtype: object

(9,)

tconst                                   tt11834774
titleType                                 tvEpisode
primaryTitle      Persian Metal Festival in Armenia
originalTitle     Persian Metal Festival in Armenia
isAdult                                           0
startYear                                      2014
endYear                                          \N
runtimeMinutes                                   \N
genres                                   Reality-TV
Name: 2010705, dtype: object

(9,)

tconst             tt11834776
titleType           tvEpisode
primaryTitle      Mina Medina
originalTitle     Mina Medina
isAdult                     1
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2010706, dtype: object

(9,)

tconst                                                   tt11834778
titleType                                                     video
primaryTitle      #InterntoInfluencer: How to Become a Mini-Bezo...
originalTitle     #InterntoInfluencer: How to Become a Mini-Bezo...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    3
genres                                                 Comedy,Short
Name: 2010707, dtype: object

(9,)

tconst               tt1183477
titleType                video
primaryTitle      Anal Dancing
originalTitle     Anal Dancing
isAdult                      1
startYear                 2006
endYear                     \N
runtimeMinutes             105
genres                   Adult
Name: 2010708, dtype: object

(9,)

tconst                 tt11834780
titleType               tvEpisode
primaryTitle      Tempting Cherry
originalTitle     Tempting Cherry
isAdult                         1
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2010709, dtype: object

(9,)

tconst                          tt11834782
titleType                        tvEpisode
primaryTitle      Tragedy Strikes Lorena's
originalTitle     Tragedy Strikes Lorena's
isAdult                                  0
startYear                               \N
endYear                                 \N
runtimeMinutes                          42
genres                               Crime
Name: 2010710, dtype: object

(9,)

tconst                              tt11834784
titleType                            tvEpisode
primaryTitle      All she needs is solo orgasm
originalTitle     All she needs is solo orgasm
isAdult                                      1
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                                   Adult
Name: 2010711, dtype: object

(9,)

tconst                                tt11834786
titleType                              tvEpisode
primaryTitle      Ruined plans end with hard sex
originalTitle     Ruined plans end with hard sex
isAdult                                        1
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                                     Adult
Name: 2010712, dtype: object

(9,)

tconst                                    tt11834788
titleType                               tvMiniSeries
primaryTitle      BanG Dream! Girls Band Party! PICO
originalTitle     BanG Dream! Girls Band Party! PICO
isAdult                                            0
startYear                                       2018
endYear                                         2021
runtimeMinutes                                    \N
genres                        Animation,Comedy,Music
Name: 2010713, dtype: object

(9,)

tconst                  tt1183478
titleType                   movie
primaryTitle      Basic Slaughter
originalTitle     Basic Slaughter
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 62
genres                     Horror
Name: 2010714, dtype: object

(9,)

tconst                    tt11834790
titleType                  tvEpisode
primaryTitle          Glasgow to Ayr
originalTitle         Glasgow to Ayr
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    24
genres            Comedy,Documentary
Name: 2010715, dtype: object

(9,)

tconst                      tt11834792
titleType                    tvEpisode
primaryTitle          Morir Por Dentro
originalTitle         Morir Por Dentro
isAdult                              0
startYear                         1999
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010716, dtype: object

(9,)

tconst              tt11834794
titleType            tvEpisode
primaryTitle      Razbar Group
originalTitle     Razbar Group
isAdult                      0
startYear                 2014
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2010717, dtype: object

(9,)

tconst                 tt11834796
titleType                   short
primaryTitle      Finders Keepers
originalTitle     Finders Keepers
isAdult                         0
startYear                    2018
endYear                        \N
runtimeMinutes                  5
genres               Comedy,Short
Name: 2010718, dtype: object

(9,)

tconst                 tt11834798
titleType                   short
primaryTitle      As He Lays Dead
originalTitle     As He Lays Dead
isAdult                         0
startYear                    2017
endYear                        \N
runtimeMinutes                  5
genres             Short,Thriller
Name: 2010719, dtype: object

(9,)

tconst                                tt1183479
titleType                             videoGame
primaryTitle      Cabela's Big Game Hunter 2008
originalTitle     Cabela's Big Game Hunter 2008
isAdult                                       0
startYear                                  2007
endYear                                      \N
runtimeMinutes                               \N
genres                                   Action
Name: 2010720, dtype: object

(9,)

tconst                                                   tt11834800
titleType                                                     video
primaryTitle      Slow Secret Sex in Bed with My Boss's Big Titt...
originalTitle     Slow Secret Sex in Bed with My Boss's Big Titt...
isAdult                                                           1
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                  173
genres                                                        Adult
Name: 2010721, dtype: object

(9,)

tconst              tt11834802
titleType                short
primaryTitle        Silhouette
originalTitle       Silhouette
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes               9
genres            Horror,Short
Name: 2010722, dtype: object

(9,)

tconst                                        tt11834806
titleType                                      tvEpisode
primaryTitle      Hot lesbian threesome by the fireplace
originalTitle     Hot lesbian threesome by the fireplace
isAdult                                                1
startYear                                           2019
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Adult
Name: 2010723, dtype: object

(9,)

tconst                   tt11834808
titleType                     short
primaryTitle           Not Just One
originalTitle          Not Just One
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   42
genres            Documentary,Short
Name: 2010724, dtype: object

(9,)

tconst                                              tt1183480
titleType                                               short
primaryTitle      The Chronicles of Curtis Tucker: Letting Go
originalTitle     The Chronicles of Curtis Tucker: Letting Go
isAdult                                                     0
startYear                                                2008
endYear                                                    \N
runtimeMinutes                                              7
genres                                           Family,Short
Name: 2010725, dtype: object

(9,)

tconst              tt11834812
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                Thriller
Name: 2010726, dtype: object

(9,)

tconst                      tt11834814
titleType                        video
primaryTitle                  Na Unhan
originalTitle                 Na Unhan
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      90
genres            Action,Drama,Mystery
Name: 2010727, dtype: object

(9,)

tconst                    tt11834816
titleType                      movie
primaryTitle      Bai niao zhao feng
originalTitle     Bai niao zhao feng
isAdult                            0
startYear                       1947
endYear                           \N
runtimeMinutes                    \N
genres                            \N
Name: 2010728, dtype: object

(9,)

tconst                tt11834818
titleType              tvEpisode
primaryTitle      Episode #3.183
originalTitle     Episode #3.183
isAdult                        0
startYear                   2002
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2010729, dtype: object

(9,)

tconst                     tt1183481
titleType                      short
primaryTitle      Clouded Billy Cuff
originalTitle     Clouded Billy Cuff
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    31
genres                   Drama,Short
Name: 2010730, dtype: object

(9,)

tconst                                           tt11834820
titleType                                         tvEpisode
primaryTitle      Adorably Sexy Katie Kush Fucks The Sybian
originalTitle     Adorably Sexy Katie Kush Fucks The Sybian
isAdult                                                   1
startYear                                              2020
endYear                                                  \N
runtimeMinutes                                           \N
genres                                                Adult
Name: 2010731, dtype: object

(9,)

tconst               tt11834822
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                 Thriller
Name: 2010732, dtype: object

(9,)

tconst                  tt11834824
titleType                tvEpisode
primaryTitle      La pena de Marco
originalTitle     La pena de Marco
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2010733, dtype: object

(9,)

tconst                              tt11834826
titleType                            tvEpisode
primaryTitle      Bag Talk Session with Marvin
originalTitle     Bag Talk Session with Marvin
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2010734, dtype: object

(9,)

tconst                  tt11834828
titleType                    short
primaryTitle      Guan dong da xia
originalTitle     Guan dong da xia
isAdult                          0
startYear                     1928
endYear                         \N
runtimeMinutes                  \N
genres                       Short
Name: 2010735, dtype: object

(9,)

tconst                tt1183482
titleType                 movie
primaryTitle      Ealing Comedy
originalTitle     Ealing Comedy
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               88
genres                   Comedy
Name: 2010736, dtype: object

(9,)

tconst                tt11834830
titleType                  short
primaryTitle          By Sunrise
originalTitle         By Sunrise
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                23
genres            Short,Thriller
Name: 2010737, dtype: object

(9,)

tconst                           tt11834832
titleType                         tvEpisode
primaryTitle      Parisa Arsalani in Turkey
originalTitle     Parisa Arsalani in Turkey
isAdult                                   0
startYear                              2014
endYear                                  \N
runtimeMinutes                           \N
genres                           Reality-TV
Name: 2010738, dtype: object

(9,)

tconst            tt11834834
titleType          tvEpisode
primaryTitle          Hubris
originalTitle         Hubris
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres               History
Name: 2010739, dtype: object

(9,)

tconst               tt11834836
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                 Thriller
Name: 2010740, dtype: object

(9,)

tconst            tt11834838
titleType          tvEpisode
primaryTitle         Nemesis
originalTitle        Nemesis
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres               History
Name: 2010741, dtype: object

(9,)

tconst               tt1183483
titleType                short
primaryTitle      Gunn Highway
originalTitle     Gunn Highway
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              17
genres             Crime,Short
Name: 2010742, dtype: object

(9,)

tconst                               tt11834840
titleType                             tvEpisode
primaryTitle      Episode dated 18 January 1954
originalTitle     Episode dated 18 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2010743, dtype: object

(9,)

tconst              tt11834842
titleType                short
primaryTitle      Nu da li shi
originalTitle     Nu da li shi
isAdult                      0
startYear                 1929
endYear                     \N
runtimeMinutes              \N
genres                   Short
Name: 2010744, dtype: object

(9,)

tconst               tt11834844
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                 Thriller
Name: 2010745, dtype: object

(9,)

tconst               tt11834846
titleType             tvEpisode
primaryTitle      With Samaiyah
originalTitle     With Samaiyah
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010746, dtype: object

(9,)

tconst                                         tt11834848
titleType                                       tvEpisode
primaryTitle      Agustina le contó sus recuerdos a Rocío
originalTitle     Agustina le contó sus recuerdos a Rocío
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                              Drama
Name: 2010747, dtype: object

(9,)

tconst              tt1183484
titleType               short
primaryTitle      The Honored
originalTitle     The Honored
isAdult                     0
startYear                2007
endYear                    \N
runtimeMinutes             10
genres            Drama,Short
Name: 2010748, dtype: object

(9,)

tconst                           tt11834850
titleType                         tvEpisode
primaryTitle      Arizona State at Colorado
originalTitle     Arizona State at Colorado
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                                Sport
Name: 2010749, dtype: object

(9,)

tconst                tt11834852
titleType                  movie
primaryTitle      Qi feng tu chu
originalTitle     Qi feng tu chu
isAdult                        0
startYear                   1926
endYear                       \N
runtimeMinutes                90
genres                     Drama
Name: 2010750, dtype: object

(9,)

tconst                                                   tt11834854
titleType                                                 tvEpisode
primaryTitle      yo, between you and me... this is because of s...
originalTitle     yo, between you and me... this is because of s...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   48
genres                                                       Comedy
Name: 2010751, dtype: object

(9,)

tconst                                         tt11834856
titleType                                       tvEpisode
primaryTitle      La desesperada llamada de Nancy a Rocío
originalTitle     La desesperada llamada de Nancy a Rocío
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         \N
genres                                              Drama
Name: 2010752, dtype: object

(9,)

tconst                 tt11834858
titleType                tvSeries
primaryTitle      Sing Me A Story
originalTitle     Sing Me A Story
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                      Music
Name: 2010753, dtype: object

(9,)

tconst              tt1183485
titleType               short
primaryTitle      The Milkman
originalTitle     The Milkman
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             16
genres            Drama,Short
Name: 2010754, dtype: object

(9,)

tconst             tt11834860
titleType           tvEpisode
primaryTitle      White Space
originalTitle     White Space
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2010755, dtype: object

(9,)

tconst                          tt11834862
titleType                        tvEpisode
primaryTitle      Payam Group in Amsterdam
originalTitle     Payam Group in Amsterdam
isAdult                                  0
startYear                             2014
endYear                                 \N
runtimeMinutes                          \N
genres                          Reality-TV
Name: 2010756, dtype: object

(9,)

tconst                        tt11834864
titleType                       tvSeries
primaryTitle               Lui Sei Leung
originalTitle              Lui Sei Leung
isAdult                                0
startYear                           1985
endYear                               \N
runtimeMinutes                        45
genres            Action,Adventure,Drama
Name: 2010757, dtype: object

(9,)

tconst                         tt11834866
titleType                           short
primaryTitle      Tell Me Why You're Here
originalTitle     Tell Me Why You're Here
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                        Drama,Short
Name: 2010758, dtype: object

(9,)

tconst                tt11834868
titleType              tvEpisode
primaryTitle      Sperminate-Her
originalTitle     Sperminate-Her
isAdult                        1
startYear                   2015
endYear                       \N
runtimeMinutes                31
genres                     Adult
Name: 2010759, dtype: object

(9,)

tconst                                     tt1183486
titleType                                    tvMovie
primaryTitle      The Night James Brown Saved Boston
originalTitle     The Night James Brown Saved Boston
isAdult                                            0
startYear                                       2008
endYear                                           \N
runtimeMinutes                                    66
genres                             Documentary,Music
Name: 2010760, dtype: object

(9,)

tconst                tt11834870
titleType               tvSeries
primaryTitle      Ah yee yat juk
originalTitle     Ah yee yat juk
isAdult                        0
startYear                   1990
endYear                     1990
runtimeMinutes                45
genres                     Drama
Name: 2010761, dtype: object

(9,)

tconst                      tt11834872
titleType                    tvEpisode
primaryTitle         Las malas lenguas
originalTitle        Las malas lenguas
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010762, dtype: object

(9,)

tconst                       tt11834874
titleType                     tvEpisode
primaryTitle      Kook in Malaga, Spain
originalTitle     Kook in Malaga, Spain
isAdult                               0
startYear                          2014
endYear                              \N
runtimeMinutes                       \N
genres                       Reality-TV
Name: 2010763, dtype: object

(9,)

tconst                       tt11834876
titleType                     tvEpisode
primaryTitle      La pesadilla de Diego
originalTitle     La pesadilla de Diego
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                            Drama
Name: 2010764, dtype: object

(9,)

tconst                tt11834878
titleType              tvEpisode
primaryTitle      Episode #1.161
originalTitle     Episode #1.161
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                      News
Name: 2010765, dtype: object

(9,)

tconst            tt1183487
titleType             movie
primaryTitle      Peacefire
originalTitle     Peacefire
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           87
genres                Drama
Name: 2010766, dtype: object

(9,)

tconst                      tt11834880
titleType                    tvEpisode
primaryTitle              Dinero fácil
originalTitle             Dinero fácil
isAdult                              0
startYear                         1998
endYear                             \N
runtimeMinutes                      \N
genres            Crime,Drama,Thriller
Name: 2010767, dtype: object

(9,)

tconst                                                   tt11834882
titleType                                                 tvEpisode
primaryTitle      Democrats EXPOSED Plotting to STEAL Election, ...
originalTitle     Democrats EXPOSED Plotting to STEAL Election, ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                         News
Name: 2010768, dtype: object

(9,)

tconst                        tt11834884
titleType                          video
primaryTitle      Honey Cunnies X-Cut 10
originalTitle     Honey Cunnies X-Cut 10
isAdult                                1
startYear                           2019
endYear                               \N
runtimeMinutes                       124
genres                             Adult
Name: 2010769, dtype: object

(9,)

tconst                   tt11834886
titleType                  tvSeries
primaryTitle      Faan ding yat juk
originalTitle     Faan ding yat juk
isAdult                           0
startYear                      2010
endYear                        2010
runtimeMinutes                   45
genres               Comedy,Romance
Name: 2010770, dtype: object

(9,)

tconst                            tt11834888
titleType                           tvSeries
primaryTitle                      HeroVoltsy
originalTitle                     HeroVoltsy
isAdult                                    0
startYear                               2012
endYear                                   \N
runtimeMinutes                            \N
genres            Adventure,Animation,Comedy
Name: 2010771, dtype: object

(9,)

tconst                              tt1183488
titleType                               movie
primaryTitle      The Sinking of Santa Isabel
originalTitle     The Sinking of Santa Isabel
isAdult                                     0
startYear                                2008
endYear                                    \N
runtimeMinutes                             88
genres                                 Comedy
Name: 2010772, dtype: object

(9,)

tconst                     tt11834890
titleType                       movie
primaryTitle      Welcome to the Show
originalTitle     Welcome to the Show
isAdult                             0
startYear                        2021
endYear                            \N
runtimeMinutes                     96
genres                          Drama
Name: 2010773, dtype: object

(9,)

tconst            tt11834892
titleType          tvEpisode
primaryTitle       Lois Hunt
originalTitle      Lois Hunt
isAdult                    0
startYear               1954
endYear                   \N
runtimeMinutes            \N
genres                 Music
Name: 2010774, dtype: object

(9,)

tconst                  tt11834896
titleType                tvEpisode
primaryTitle         Hale vs. Nash
originalTitle        Hale vs. Nash
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  22
genres            Comedy,Game-Show
Name: 2010775, dtype: object

(9,)

tconst                            tt11834898
titleType                          tvEpisode
primaryTitle      Pretty Pink Natural Orgasm
originalTitle     Pretty Pink Natural Orgasm
isAdult                                    1
startYear                               2020
endYear                                   \N
runtimeMinutes                            15
genres                                 Adult
Name: 2010776, dtype: object

(9,)

tconst                         tt1183489
titleType                          movie
primaryTitle      Stag Night of the Dead
originalTitle     Stag Night of the Dead
isAdult                                0
startYear                           2010
endYear                               \N
runtimeMinutes                        81
genres              Action,Comedy,Horror
Name: 2010777, dtype: object

(9,)

tconst                           tt11834900
titleType                         tvEpisode
primaryTitle      Episode dated 25 May 2018
originalTitle     Episode dated 25 May 2018
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2010778, dtype: object

(9,)

tconst            tt11834902
titleType              movie
primaryTitle         Engatto
originalTitle        Engatto
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            60
genres               Romance
Name: 2010779, dtype: object

(9,)

tconst                    tt11834904
titleType                      short
primaryTitle               War Movie
originalTitle     Jeonjaeng yeonghwa
isAdult                            0
startYear                       2005
endYear                           \N
runtimeMinutes                    23
genres                   Drama,Short
Name: 2010780, dtype: object

(9,)

tconst            tt11834906
titleType              video
primaryTitle        FcVR-008
originalTitle       FcVR-008
isAdult                    1
startYear               2019
endYear                   \N
runtimeMinutes           140
genres                 Adult
Name: 2010781, dtype: object

(9,)

tconst                      tt11834908
titleType                      tvShort
primaryTitle           Detective Carol
originalTitle          Detective Carol
isAdult                              0
startYear                         2019
endYear                             \N
runtimeMinutes                       5
genres            Comedy,Mystery,Short
Name: 2010782, dtype: object

(9,)

tconst                    tt1183490
titleType                     short
primaryTitle             Why We Wax
originalTitle            Why We Wax
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   20
genres            Documentary,Short
Name: 2010783, dtype: object

(9,)

tconst              tt11834910
titleType                short
primaryTitle           Cloud 9
originalTitle          Cloud 9
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2010784, dtype: object

(9,)

tconst               tt11834912
titleType                 short
primaryTitle      Heading South
originalTitle     Heading South
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               13
genres              Drama,Short
Name: 2010785, dtype: object

(9,)

tconst                               tt11834914
titleType                             tvEpisode
primaryTitle      Episode dated 18 January 1954
originalTitle     Episode dated 18 January 1954
isAdult                                       0
startYear                                  1954
endYear                                      \N
runtimeMinutes                               \N
genres                                   Comedy
Name: 2010786, dtype: object

(9,)

tconst                              tt11834916
titleType                             tvSeries
primaryTitle      Star Ocean First Departure R
originalTitle     Star Ocean First Departure R
isAdult                                      0
startYear                                 2019
endYear                                   2019
runtimeMinutes                              \N
genres                       Adventure,Fantasy
Name: 2010787, dtype: object

(9,)

tconst                        tt11834918
titleType                      tvEpisode
primaryTitle      Joining the Resistance
originalTitle     Joining the Resistance
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        60
genres                   Sport,Talk-Show
Name: 2010788, dtype: object

(9,)

tconst                         tt1183491
titleType                          short
primaryTitle                Wildlifeless
originalTitle               Wildlifeless
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                         8
genres            Action,Adventure,Drama
Name: 2010789, dtype: object

(9,)

tconst                                               tt11834920
titleType                                             tvEpisode
primaryTitle      You're So Vain, I'm a Big Girl, I Can Take It
originalTitle     You're So Vain, I'm a Big Girl, I Can Take It
isAdult                                                       0
startYear                                                  2020
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                   Comedy
Name: 2010790, dtype: object

(9,)

tconst                          tt11834922
titleType                         tvSeries
primaryTitle              Little Town Hero
originalTitle             Little Town Hero
isAdult                                  0
startYear                             2019
endYear                               2019
runtimeMinutes                          \N
genres            Action,Adventure,Fantasy
Name: 2010791, dtype: object

(9,)

tconst                                                 tt11834924
titleType                                                tvSeries
primaryTitle      Atelier Ryza Ever Darkness & The Secret Hideout
originalTitle     Atelier Ryza Ever Darkness & The Secret Hideout
isAdult                                                         0
startYear                                                    2019
endYear                                                      2019
runtimeMinutes                                                 \N
genres                                   Action,Adventure,Fantasy
Name: 2010792, dtype: object

(9,)

tconst               tt11834926
titleType              tvSeries
primaryTitle      Dragalia Lost
originalTitle     Dragalia Lost
isAdult                       0
startYear                  2018
endYear                    2018
runtimeMinutes               \N
genres                Adventure
Name: 2010793, dtype: object

(9,)

tconst                  tt11834928
titleType                tvEpisode
primaryTitle      Nash vs. Shoniwa
originalTitle     Nash vs. Shoniwa
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  22
genres            Comedy,Game-Show
Name: 2010794, dtype: object

(9,)

tconst                                tt1183492
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2010795, dtype: object

(9,)

tconst                   tt11834930
titleType                     short
primaryTitle      Rest in the Light
originalTitle       Bitsogui hyusik
isAdult                           0
startYear                      2002
endYear                          \N
runtimeMinutes                   30
genres                  Drama,Short
Name: 2010796, dtype: object

(9,)

tconst                           tt11834932
titleType                             video
primaryTitle      Slothrust: Horseshoe Crab
originalTitle     Slothrust: Horseshoe Crab
isAdult                                   0
startYear                              2016
endYear                                  \N
runtimeMinutes                            5
genres                          Music,Short
Name: 2010797, dtype: object

(9,)

tconst                              tt11834934
titleType                            tvEpisode
primaryTitle      New Mexico vs. Arizona State
originalTitle     New Mexico vs. Arizona State
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                                   Sport
Name: 2010798, dtype: object

(9,)

tconst                             tt11834936
titleType                           tvEpisode
primaryTitle      San Diego vs. Arizona State
originalTitle     San Diego vs. Arizona State
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                  Sport
Name: 2010799, dtype: object

(9,)

tconst                                 tt11834938
titleType                                   movie
primaryTitle      The First Lie I Told My Husband
originalTitle     The First Lie I Told My Husband
isAdult                                         1
startYear                                    2019
endYear                                        \N
runtimeMinutes                                102
genres                                      Adult
Name: 2010800, dtype: object

(9,)

tconst                                      tt1183493
titleType                                   tvEpisode
primaryTitle      The Fellowship of the License Plate
originalTitle     The Fellowship of the License Plate
isAdult                                             0
startYear                                        2005
endYear                                            \N
runtimeMinutes                                     \N
genres                                     Reality-TV
Name: 2010801, dtype: object

(9,)

tconst                              tt11834944
titleType                                video
primaryTitle      Suthri Si Chori: Niren Dabas
originalTitle     Suthri Si Chori: Niren Dabas
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              \N
genres                             Music,Short
Name: 2010802, dtype: object

(9,)

tconst                                              tt11834946
titleType                                            tvEpisode
primaryTitle      Mainstream Media Turns On Disney's Star Wars
originalTitle     Mainstream Media Turns On Disney's Star Wars
isAdult                                                      0
startYear                                                 2020
endYear                                                     \N
runtimeMinutes                                              \N
genres                                               Talk-Show
Name: 2010803, dtype: object

(9,)

tconst                     tt11834948
titleType                       short
primaryTitle      Faith and Firepower
originalTitle     Faith and Firepower
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     27
genres              Documentary,Short
Name: 2010804, dtype: object

(9,)

tconst                                     tt1183494
titleType                                  tvEpisode
primaryTitle      Solliciteren is een kunst - Deel 2
originalTitle     Solliciteren is een kunst - Deel 2
isAdult                                            0
startYear                                       2001
endYear                                           \N
runtimeMinutes                                    \N
genres                                        Comedy
Name: 2010805, dtype: object

(9,)

tconst                    tt11834950
titleType                      short
primaryTitle          Days of Sunhwa
originalTitle     Sunhwaui geunhwang
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    21
genres                   Drama,Short
Name: 2010806, dtype: object

(9,)

tconst              tt11834952
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2002
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2010807, dtype: object

(9,)

tconst                             tt11834954
titleType                               short
primaryTitle      MSA: The Ian Macindoe Story
originalTitle     MSA: The Ian Macindoe Story
isAdult                                     0
startYear                                2017
endYear                                    \N
runtimeMinutes                             41
genres                      Documentary,Short
Name: 2010808, dtype: object

(9,)

tconst                            tt11834956
titleType                          tvEpisode
primaryTitle      Threesome Caught on Camera
originalTitle     Threesome Caught on Camera
isAdult                                    1
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2010809, dtype: object

(9,)

tconst            tt11834958
titleType          tvEpisode
primaryTitle           Pilot
originalTitle          Pilot
isAdult                    0
startYear               2016
endYear                   \N
runtimeMinutes            \N
genres              Thriller
Name: 2010810, dtype: object

(9,)

tconst                            tt1183495
titleType                         tvEpisode
primaryTitle      Simone bangt aufzufliegen
originalTitle     Simone bangt aufzufliegen
isAdult                                   0
startYear                              2007
endYear                                  \N
runtimeMinutes                           \N
genres                        Drama,Romance
Name: 2010811, dtype: object

(9,)

tconst              tt11834960
titleType         tvMiniSeries
primaryTitle           Thirsty
originalTitle          Thirsty
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2010812, dtype: object

(9,)

tconst                    tt11834962
titleType                      short
primaryTitle      Alles Op Rolletjes
originalTitle     Alles Op Rolletjes
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                   Drama,Short
Name: 2010813, dtype: object

(9,)

tconst                                                   tt11834964
titleType                                                 tvEpisode
primaryTitle      Bob Iger Claimed Star Wars Fatigue - Baby Yoda...
originalTitle     Bob Iger Claimed Star Wars Fatigue - Baby Yoda...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2010814, dtype: object

(9,)

tconst                                   tt11834966
titleType                                     movie
primaryTitle      And You Call Yourself A Christian
originalTitle     And You Call Yourself A Christian
isAdult                                           0
startYear                                      2021
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Drama
Name: 2010815, dtype: object

(9,)

tconst                           tt11834968
titleType                         tvEpisode
primaryTitle      Dr. Wood Part 1: Bareback
originalTitle     Dr. Wood Part 1: Bareback
isAdult                                   1
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                                Adult
Name: 2010816, dtype: object

(9,)

tconst                tt1183496
titleType             tvEpisode
primaryTitle      Episode #1.51
originalTitle     Episode #1.51
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010817, dtype: object

(9,)

tconst                              tt11834970
titleType                             tvSeries
primaryTitle      Homeless Show TV Series 2020
originalTitle     Homeless Show TV Series 2020
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              60
genres                                  Comedy
Name: 2010818, dtype: object

(9,)

tconst                              tt11834972
titleType                             tvSeries
primaryTitle      The Lisa Oz & Kim Coles Show
originalTitle     The Lisa Oz & Kim Coles Show
isAdult                                      0
startYear                                 2010
endYear                                   2010
runtimeMinutes                              \N
genres                                      \N
Name: 2010819, dtype: object

(9,)

tconst                    tt11834974
titleType                      movie
primaryTitle      Toward Singularity
originalTitle     Toward Singularity
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    66
genres                   Documentary
Name: 2010820, dtype: object

(9,)

tconst                        tt11834976
titleType                      tvEpisode
primaryTitle      The All Inclusive Deal
originalTitle     The All Inclusive Deal
isAdult                                1
startYear                           2011
endYear                               \N
runtimeMinutes                        \N
genres                             Adult
Name: 2010821, dtype: object

(9,)

tconst                                                   tt11834978
titleType                                                     video
primaryTitle      Vicky Kajla Feat. Karishma Sharma & RB Gujjar:...
originalTitle     Vicky Kajla Feat. Karishma Sharma & RB Gujjar:...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                    4
genres                                                  Music,Short
Name: 2010822, dtype: object

(9,)

tconst                tt1183497
titleType             tvEpisode
primaryTitle      Episode #1.52
originalTitle     Episode #1.52
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010823, dtype: object

(9,)

tconst                 tt11834980
titleType               tvEpisode
primaryTitle      Swallow or Fail
originalTitle     Swallow or Fail
isAdult                         1
startYear                    2011
endYear                        \N
runtimeMinutes                 \N
genres                      Adult
Name: 2010824, dtype: object

(9,)

tconst                       tt11834982
titleType                         movie
primaryTitle      Jackie and the Ladies
originalTitle     Jackie and the Ladies
isAdult                               0
startYear                          2017
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2010825, dtype: object

(9,)

tconst             tt11834984
titleType           tvEpisode
primaryTitle      Shower Bait
originalTitle     Shower Bait
isAdult                     1
startYear                2011
endYear                    \N
runtimeMinutes             \N
genres                  Adult
Name: 2010826, dtype: object

(9,)

tconst             tt11834986
titleType           tvEpisode
primaryTitle      Autocorrect
originalTitle     Autocorrect
isAdult                     0
startYear                2014
endYear                    \N
runtimeMinutes             \N
genres                 Comedy
Name: 2010827, dtype: object

(9,)

tconst                              tt11834988
titleType                            tvEpisode
primaryTitle      Art Attack/Over My Shed Body
originalTitle     Art Attack/Over My Shed Body
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                 Animation,Comedy,Family
Name: 2010828, dtype: object

(9,)

tconst                tt1183498
titleType             tvEpisode
primaryTitle      Episode #1.56
originalTitle     Episode #1.56
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010829, dtype: object

(9,)

tconst                                         tt11834990
titleType                                       tvEpisode
primaryTitle      8 Moments That Made Us Go Eff This Game
originalTitle     8 Moments That Made Us Go Eff This Game
isAdult                                                 0
startYear                                            2018
endYear                                                \N
runtimeMinutes                                         \N
genres                                        Documentary
Name: 2010830, dtype: object

(9,)

tconst                      tt11834992
titleType                    tvEpisode
primaryTitle      Texting with Gosling
originalTitle     Texting with Gosling
isAdult                              0
startYear                         2014
endYear                             \N
runtimeMinutes                      \N
genres                          Comedy
Name: 2010831, dtype: object

(9,)

tconst                                              tt11834994
titleType                                            tvEpisode
primaryTitle      Goo-rillas in the Mist/Woman from the Future
originalTitle     Goo-rillas in the Mist/Woman from the Future
isAdult                                                      0
startYear                                                 2020
endYear                                                     \N
runtimeMinutes                                              \N
genres                                 Animation,Comedy,Family
Name: 2010832, dtype: object

(9,)

tconst            tt11834996
titleType          tvEpisode
primaryTitle          Finale
originalTitle         Finale
isAdult                    0
startYear               2014
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2010833, dtype: object

(9,)

tconst                      tt11834998
titleType                    tvEpisode
primaryTitle      Power Yoga: Bareback
originalTitle     Power Yoga: Bareback
isAdult                              1
startYear                         2019
endYear                             \N
runtimeMinutes                      \N
genres                           Adult
Name: 2010834, dtype: object

(9,)

tconst                tt1183499
titleType             tvEpisode
primaryTitle      Episode #1.57
originalTitle     Episode #1.57
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010835, dtype: object

(9,)

tconst                                                  tt11835000
titleType                                                tvEpisode
primaryTitle      Harley Quinn Looks Good In Suicide Squad 2 Leaks
originalTitle     Harley Quinn Looks Good In Suicide Squad 2 Leaks
isAdult                                                          0
startYear                                                     2020
endYear                                                         \N
runtimeMinutes                                                  \N
genres                                                   Talk-Show
Name: 2010836, dtype: object

(9,)

tconst                                                   tt11835002
titleType                                                 tvSpecial
primaryTitle      Live! Red! Ready: The Bet Awards Red Carpet Sp...
originalTitle     Live! Red! Ready: The Bet Awards Red Carpet Sp...
isAdult                                                           0
startYear                                                      2017
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                           \N
Name: 2010837, dtype: object

(9,)

tconst             tt11835004
titleType               short
primaryTitle             Eden
originalTitle            Eden
isAdult                     0
startYear                2013
endYear                    \N
runtimeMinutes             23
genres            Drama,Short
Name: 2010838, dtype: object

(9,)

tconst                tt11835006
titleType              tvEpisode
primaryTitle      Final Newscast
originalTitle     Final Newscast
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                87
genres                     Crime
Name: 2010839, dtype: object

(9,)

tconst               tt11835008
titleType             tvEpisode
primaryTitle      Surprise Dick
originalTitle     Surprise Dick
isAdult                       1
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                    Adult
Name: 2010840, dtype: object

(9,)

tconst                tt1183500
titleType             tvEpisode
primaryTitle      Episode #1.58
originalTitle     Episode #1.58
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010841, dtype: object

(9,)

tconst                 tt11835010
titleType               tvEpisode
primaryTitle         Episode #1.2
originalTitle        Episode #1.2
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres            Music,Talk-Show
Name: 2010842, dtype: object

(9,)

tconst                 tt11835012
titleType               tvEpisode
primaryTitle         Episode #1.3
originalTitle        Episode #1.3
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres            Music,Talk-Show
Name: 2010843, dtype: object

(9,)

tconst                 tt11835014
titleType               tvEpisode
primaryTitle         Episode #1.4
originalTitle        Episode #1.4
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres            Music,Talk-Show
Name: 2010844, dtype: object

(9,)

tconst                 tt11835016
titleType               tvEpisode
primaryTitle         Episode #1.6
originalTitle        Episode #1.6
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres            Music,Talk-Show
Name: 2010845, dtype: object

(9,)

tconst                 tt11835018
titleType               tvEpisode
primaryTitle         Episode #1.7
originalTitle        Episode #1.7
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres            Music,Talk-Show
Name: 2010846, dtype: object

(9,)

tconst                tt1183501
titleType             tvEpisode
primaryTitle      Episode #1.59
originalTitle     Episode #1.59
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010847, dtype: object

(9,)

tconst                 tt11835020
titleType               tvEpisode
primaryTitle         Episode #1.8
originalTitle        Episode #1.8
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres            Music,Talk-Show
Name: 2010848, dtype: object

(9,)

tconst                 tt11835022
titleType               tvEpisode
primaryTitle         Episode #1.9
originalTitle        Episode #1.9
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres            Music,Talk-Show
Name: 2010849, dtype: object

(9,)

tconst                     tt11835024
titleType                       video
primaryTitle      Angel Olsen: Sister
originalTitle     Angel Olsen: Sister
isAdult                             0
startYear                        2016
endYear                            \N
runtimeMinutes                      9
genres                    Music,Short
Name: 2010850, dtype: object

(9,)

tconst                                                   tt11835026
titleType                                                 tvEpisode
primaryTitle      Pascal Spalter vs. Dan Main - UKWA "War of Nat...
originalTitle     Pascal Spalter vs. Dan Main - UKWA "War of Nat...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Sport
Name: 2010851, dtype: object

(9,)

tconst                                   tt11835028
titleType                                 tvEpisode
primaryTitle      Born to Fight - MWA "Showstealer"
originalTitle     Born to Fight - MWA "Showstealer"
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Sport
Name: 2010852, dtype: object

(9,)

tconst                tt1183502
titleType             tvEpisode
primaryTitle      Episode #1.60
originalTitle     Episode #1.60
isAdult                       0
startYear                  2001
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010853, dtype: object

(9,)

tconst                      tt11835030
titleType                        short
primaryTitle      Sellainen on puhelin
originalTitle     Sellainen on puhelin
isAdult                              0
startYear                         1967
endYear                             \N
runtimeMinutes                      12
genres               Documentary,Short
Name: 2010854, dtype: object

(9,)

tconst                             tt11835032
titleType                           tvEpisode
primaryTitle      Tande-På programmet spesial
originalTitle     Tande-På programmet spesial
isAdult                                     0
startYear                                1992
endYear                                    \N
runtimeMinutes                             \N
genres                        Music,Talk-Show
Name: 2010855, dtype: object

(9,)

tconst                                     tt11835034
titleType                                   tvEpisode
primaryTitle      Marco le contó la verdad a Agustina
originalTitle     Marco le contó la verdad a Agustina
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Drama
Name: 2010856, dtype: object

(9,)

tconst              tt11835036
titleType            tvEpisode
primaryTitle      Watching You
originalTitle     Watching You
isAdult                      1
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2010857, dtype: object

(9,)

tconst                          tt11835038
titleType                        tvEpisode
primaryTitle      Art of Domination Part 1
originalTitle     Art of Domination Part 1
isAdult                                  1
startYear                             2019
endYear                                 \N
runtimeMinutes                          \N
genres                               Adult
Name: 2010858, dtype: object

(9,)

tconst                                tt1183503
titleType                             tvEpisode
primaryTitle      Episode dated 8 February 2008
originalTitle     Episode dated 8 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2010859, dtype: object

(9,)

tconst                                                   tt11835040
titleType                                                 tvEpisode
primaryTitle      Ben Affleck Finally Talks About Why He Left Th...
originalTitle     Ben Affleck Finally Talks About Why He Left Th...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2010860, dtype: object

(9,)

tconst                     tt11835042
titleType                   tvEpisode
primaryTitle             Episode #1.1
originalTitle            Episode #1.1
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010861, dtype: object

(9,)

tconst                     tt11835044
titleType                   tvEpisode
primaryTitle             Episode #1.2
originalTitle            Episode #1.2
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010862, dtype: object

(9,)

tconst            tt11835046
titleType          tvEpisode
primaryTitle      Puppy Love
originalTitle     Puppy Love
isAdult                    1
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2010863, dtype: object

(9,)

tconst                     tt11835048
titleType                   tvEpisode
primaryTitle             Episode #1.3
originalTitle            Episode #1.3
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010864, dtype: object

(9,)

tconst                            tt1183504
titleType                         tvEpisode
primaryTitle      Episode dated 16 May 1985
originalTitle     Episode dated 16 May 1985
isAdult                                   0
startYear                              1985
endYear                                  \N
runtimeMinutes                           \N
genres                        Drama,Romance
Name: 2010865, dtype: object

(9,)

tconst                     tt11835050
titleType                   tvEpisode
primaryTitle             Episode #1.4
originalTitle            Episode #1.4
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010866, dtype: object

(9,)

tconst                     tt11835052
titleType                   tvEpisode
primaryTitle             Episode #1.5
originalTitle            Episode #1.5
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010867, dtype: object

(9,)

tconst                     tt11835054
titleType                   tvEpisode
primaryTitle             Episode #1.6
originalTitle            Episode #1.6
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010868, dtype: object

(9,)

tconst                     tt11835056
titleType                   tvEpisode
primaryTitle             Episode #1.7
originalTitle            Episode #1.7
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010869, dtype: object

(9,)

tconst                     tt11835058
titleType                   tvEpisode
primaryTitle             Episode #1.8
originalTitle            Episode #1.8
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010870, dtype: object

(9,)

tconst                                tt1183505
titleType                             tvEpisode
primaryTitle      Episode dated 23 January 1989
originalTitle     Episode dated 23 January 1989
isAdult                                       0
startYear                                  1989
endYear                                      \N
runtimeMinutes                               \N
genres                            Drama,Romance
Name: 2010871, dtype: object

(9,)

tconst                     tt11835060
titleType                   tvEpisode
primaryTitle             Episode #1.9
originalTitle            Episode #1.9
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010872, dtype: object

(9,)

tconst                     tt11835062
titleType                   tvEpisode
primaryTitle            Episode #1.10
originalTitle           Episode #1.10
isAdult                             0
startYear                        1993
endYear                            \N
runtimeMinutes                     \N
genres            Game-Show,Talk-Show
Name: 2010873, dtype: object

(9,)

tconst             tt11835064
titleType               short
primaryTitle           Eunhee
originalTitle          Eunhee
isAdult                     0
startYear                2015
endYear                    \N
runtimeMinutes             18
genres            Drama,Short
Name: 2010874, dtype: object

(9,)

tconst                                               tt11835066
titleType                                             tvEpisode
primaryTitle      Marshal Hong accidentally releases the demons
originalTitle     Marshal Hong accidentally releases the demons
isAdult                                                       0
startYear                                                  2011
endYear                                                      \N
runtimeMinutes                                               \N
genres                                       Action,Crime,Drama
Name: 2010875, dtype: object

(9,)

tconst               tt11835068
titleType                 short
primaryTitle          Sondhayni
originalTitle         Sondhayni
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               25
genres            Fantasy,Short
Name: 2010876, dtype: object

(9,)

tconst                                tt1183506
titleType                             tvEpisode
primaryTitle      Episode dated 25 January 1989
originalTitle     Episode dated 25 January 1989
isAdult                                       0
startYear                                  1989
endYear                                      \N
runtimeMinutes                               \N
genres                            Drama,Romance
Name: 2010877, dtype: object

(9,)

tconst                           tt11835070
titleType                         tvEpisode
primaryTitle      Agustina enfrentó a Marco
originalTitle     Agustina enfrentó a Marco
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           \N
genres                                Drama
Name: 2010878, dtype: object

(9,)

tconst              tt11835072
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010879, dtype: object

(9,)

tconst              tt11835074
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010880, dtype: object

(9,)

tconst              tt11835076
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010881, dtype: object

(9,)

tconst                    tt11835078
titleType                  tvEpisode
primaryTitle      Girls Night Part 1
originalTitle     Girls Night Part 1
isAdult                            1
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2010882, dtype: object

(9,)

tconst                              tt1183507
titleType                           tvEpisode
primaryTitle      Episode dated 29 April 1993
originalTitle     Episode dated 29 April 1993
isAdult                                     0
startYear                                1993
endYear                                    \N
runtimeMinutes                             \N
genres                          Drama,Romance
Name: 2010883, dtype: object

(9,)

tconst              tt11835082
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010884, dtype: object

(9,)

tconst              tt11835084
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010885, dtype: object

(9,)

tconst              tt11835086
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010886, dtype: object

(9,)

tconst              tt11835088
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010887, dtype: object

(9,)

tconst                             tt1183508
titleType                          tvEpisode
primaryTitle      Episode dated 17 June 1994
originalTitle     Episode dated 17 June 1994
isAdult                                    0
startYear                               1994
endYear                                   \N
runtimeMinutes                            \N
genres                         Drama,Romance
Name: 2010888, dtype: object

(9,)

tconst              tt11835090
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010889, dtype: object

(9,)

tconst               tt11835092
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010890, dtype: object

(9,)

tconst               tt11835094
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010891, dtype: object

(9,)

tconst               tt11835096
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010892, dtype: object

(9,)

tconst               tt11835098
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010893, dtype: object

(9,)

tconst                               tt1183509
titleType                            tvEpisode
primaryTitle      Episode dated 29 August 1998
originalTitle     Episode dated 29 August 1998
isAdult                                      0
startYear                                 1998
endYear                                     \N
runtimeMinutes                              \N
genres                           Drama,Romance
Name: 2010894, dtype: object

(9,)

tconst               tt11835100
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010895, dtype: object

(9,)

tconst               tt11835102
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  1994
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010896, dtype: object

(9,)

tconst                         tt11835104
titleType                       tvEpisode
primaryTitle      Wholehearted Engagement
originalTitle     Wholehearted Engagement
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                        Documentary
Name: 2010897, dtype: object

(9,)

tconst                 tt11835106
titleType               tvEpisode
primaryTitle         Episode #1.5
originalTitle        Episode #1.5
isAdult                         0
startYear                    1992
endYear                        \N
runtimeMinutes                 \N
genres            Music,Talk-Show
Name: 2010898, dtype: object

(9,)

tconst                                 tt1183510
titleType                              tvEpisode
primaryTitle      Episode dated 10 November 1998
originalTitle     Episode dated 10 November 1998
isAdult                                        0
startYear                                   1998
endYear                                       \N
runtimeMinutes                                \N
genres                             Drama,Romance
Name: 2010899, dtype: object

(9,)

tconst                tt11835110
titleType              tvEpisode
primaryTitle      Wandering Eyes
originalTitle     Wandering Eyes
isAdult                        1
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Adult
Name: 2010900, dtype: object

(9,)

tconst            tt11835112
titleType          tvEpisode
primaryTitle          Lekcja
originalTitle         Lekcja
isAdult                    0
startYear               1991
endYear                   \N
runtimeMinutes            62
genres                 Drama
Name: 2010901, dtype: object

(9,)

tconst                  tt11835114
titleType                tvEpisode
primaryTitle              02.22.20
originalTitle             02.22.20
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Crime,Reality-TV
Name: 2010902, dtype: object

(9,)

tconst                   tt11835116
titleType                     short
primaryTitle                   I AM
originalTitle                  I AM
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   26
genres            Documentary,Short
Name: 2010903, dtype: object

(9,)

tconst                    tt11835118
titleType                  tvEpisode
primaryTitle      By Invitation Only
originalTitle     By Invitation Only
isAdult                            1
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                         Adult
Name: 2010904, dtype: object

(9,)

tconst                  tt1183511
titleType               tvEpisode
primaryTitle        Episode #15.2
originalTitle       Episode #15.2
isAdult                         0
startYear                    1971
endYear                        \N
runtimeMinutes                 60
genres            Music,Talk-Show
Name: 2010905, dtype: object

(9,)

tconst                                          tt11835120
titleType                                            movie
primaryTitle      There is Nothing So Strange as the Truth
originalTitle     There is Nothing So Strange as the Truth
isAdult                                                  0
startYear                                             2020
endYear                                                 \N
runtimeMinutes                                          \N
genres                                             History
Name: 2010906, dtype: object

(9,)

tconst                                                tt11835122
titleType                                              tvEpisode
primaryTitle      No Deleted Scenes on Rise of Skywalker Blu-Ray
originalTitle     No Deleted Scenes on Rise of Skywalker Blu-Ray
isAdult                                                        0
startYear                                                   2020
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                 Talk-Show
Name: 2010907, dtype: object

(9,)

tconst                                tt11835124
titleType                              tvEpisode
primaryTitle      Light at the End of the Tunnel
originalTitle     Light at the End of the Tunnel
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                             Drama,History
Name: 2010908, dtype: object

(9,)

tconst                               tt11835126
titleType                             tvEpisode
primaryTitle      Dwayne Wade & Michelle Buteau
originalTitle     Dwayne Wade & Michelle Buteau
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2010909, dtype: object

(9,)

tconst                            tt11835128
titleType                          tvEpisode
primaryTitle      Unbreakable Bond: Bareback
originalTitle     Unbreakable Bond: Bareback
isAdult                                    1
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                                 Adult
Name: 2010910, dtype: object

(9,)

tconst                tt1183512
titleType             tvEpisode
primaryTitle      Episode #5.13
originalTitle     Episode #5.13
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2010911, dtype: object

(9,)

tconst                         tt11835130
titleType                           movie
primaryTitle      Filmen som inte blev av
originalTitle     Filmen som inte blev av
isAdult                                 0
startYear                            2013
endYear                                \N
runtimeMinutes                         55
genres                        Documentary
Name: 2010912, dtype: object

(9,)

tconst                  tt11835132
titleType                    short
primaryTitle            Film Again
originalTitle     Bogangchwaryeong
isAdult                          0
startYear                     2018
endYear                         \N
runtimeMinutes                  30
genres                 Drama,Short
Name: 2010913, dtype: object

(9,)

tconst                                           tt11835134
titleType                                             short
primaryTitle      The Exceptional Life of Benjamin Banneker
originalTitle     The Exceptional Life of Benjamin Banneker
isAdult                                                   0
startYear                                              2017
endYear                                                  \N
runtimeMinutes                                            4
genres                            Animation,Biography,Short
Name: 2010914, dtype: object

(9,)

tconst             tt11835136
titleType               short
primaryTitle               O2
originalTitle              O2
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2010915, dtype: object

(9,)

tconst                              tt11835138
titleType                            tvEpisode
primaryTitle      Erika Jayne & Jennifer Aydin
originalTitle     Erika Jayne & Jennifer Aydin
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                               Talk-Show
Name: 2010916, dtype: object

(9,)

tconst                tt1183513
titleType             tvEpisode
primaryTitle      Episode #5.14
originalTitle     Episode #5.14
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2010917, dtype: object

(9,)

tconst                               tt11835140
titleType                             tvEpisode
primaryTitle      Lesley Manville & Liam Neeson
originalTitle     Lesley Manville & Liam Neeson
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2010918, dtype: object

(9,)

tconst                    tt11835142
titleType                      short
primaryTitle      The Lottery Ticket
originalTitle     The Lottery Ticket
isAdult                            0
startYear                         \N
endYear                           \N
runtimeMinutes                    \N
genres                   Drama,Short
Name: 2010919, dtype: object

(9,)

tconst            tt11835144
titleType          tvEpisode
primaryTitle      Real Stiff
originalTitle     Real Stiff
isAdult                    1
startYear               2019
endYear                   \N
runtimeMinutes            \N
genres                 Adult
Name: 2010920, dtype: object

(9,)

tconst                            tt11835146
titleType                              movie
primaryTitle      Atalanta BC vs Juventus FC
originalTitle     Atalanta BC vs Juventus FC
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            93
genres                                 Sport
Name: 2010921, dtype: object

(9,)

tconst                tt1183514
titleType             tvEpisode
primaryTitle      Episode #5.15
originalTitle     Episode #5.15
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2010922, dtype: object

(9,)

tconst                        tt11835150
titleType                          movie
primaryTitle      AC Perugia vs Milan AC
originalTitle     AC Perugia vs Milan AC
isAdult                                0
startYear                           2003
endYear                               \N
runtimeMinutes                        90
genres                        Reality-TV
Name: 2010923, dtype: object

(9,)

tconst            tt11835152
titleType          tvEpisode
primaryTitle          Cookie
originalTitle         Cookie
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2010924, dtype: object

(9,)

tconst                tt11835154
titleType              tvEpisode
primaryTitle      Red Sash Death
originalTitle     Red Sash Death
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                43
genres                   Mystery
Name: 2010925, dtype: object

(9,)

tconst            tt11835156
titleType          tvEpisode
primaryTitle          Mimosa
originalTitle         Mimosa
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2010926, dtype: object

(9,)

tconst            tt11835158
titleType          tvEpisode
primaryTitle         Bulleit
originalTitle        Bulleit
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2010927, dtype: object

(9,)

tconst                tt1183515
titleType             tvEpisode
primaryTitle      Episode #5.16
originalTitle     Episode #5.16
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres              Documentary
Name: 2010928, dtype: object

(9,)

tconst                      tt11835160
titleType                        movie
primaryTitle      The Manchester Derby
originalTitle     The Manchester Derby
isAdult                              0
startYear                         2003
endYear                             \N
runtimeMinutes                      94
genres                          Action
Name: 2010929, dtype: object

(9,)

tconst            tt11835162
titleType          tvEpisode
primaryTitle         Lobster
originalTitle        Lobster
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2010930, dtype: object

(9,)

tconst               tt11835164
titleType             tvEpisode
primaryTitle      Episode #9.61
originalTitle     Episode #9.61
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010931, dtype: object

(9,)

tconst               tt11835166
titleType             tvEpisode
primaryTitle      Episode #9.62
originalTitle     Episode #9.62
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010932, dtype: object

(9,)

tconst               tt11835168
titleType             tvEpisode
primaryTitle      Episode #9.63
originalTitle     Episode #9.63
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010933, dtype: object

(9,)

tconst                       tt1183516
titleType                    tvEpisode
primaryTitle             Episode #16.5
originalTitle            Episode #16.5
isAdult                              0
startYear                         2004
endYear                             \N
runtimeMinutes                      \N
genres            Drama,Family,Romance
Name: 2010934, dtype: object

(9,)

tconst               tt11835170
titleType             tvEpisode
primaryTitle      Episode #9.64
originalTitle     Episode #9.64
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010935, dtype: object

(9,)

tconst               tt11835172
titleType             tvEpisode
primaryTitle      Episode #9.65
originalTitle     Episode #9.65
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010936, dtype: object

(9,)

tconst                 tt11835174
titleType                tvSeries
primaryTitle         Micro Mayhem
originalTitle        Micro Mayhem
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2010937, dtype: object

(9,)

tconst               tt11835176
titleType             tvEpisode
primaryTitle      Episode #9.66
originalTitle     Episode #9.66
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010938, dtype: object

(9,)

tconst               tt11835178
titleType             tvEpisode
primaryTitle      Episode #9.67
originalTitle     Episode #9.67
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010939, dtype: object

(9,)

tconst                tt1183517
titleType             tvEpisode
primaryTitle      Episode #4.95
originalTitle     Episode #4.95
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2010940, dtype: object

(9,)

tconst               tt11835180
titleType             tvEpisode
primaryTitle      Episode #9.68
originalTitle     Episode #9.68
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010941, dtype: object

(9,)

tconst               tt11835182
titleType             tvEpisode
primaryTitle      Episode #9.69
originalTitle     Episode #9.69
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010942, dtype: object

(9,)

tconst               tt11835186
titleType             tvEpisode
primaryTitle      Episode #9.70
originalTitle     Episode #9.70
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2010943, dtype: object

(9,)

tconst                                      tt11835188
titleType                                        movie
primaryTitle      Bayern Munich vs Bayer 04 Leverkusen
originalTitle     Bayern Munich vs Bayer 04 Leverkusen
isAdult                                              0
startYear                                         2003
endYear                                             \N
runtimeMinutes                                      93
genres                                          Action
Name: 2010944, dtype: object

(9,)

tconst               tt1183518
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2010945, dtype: object

(9,)

tconst                                         tt11835190
titleType                                       tvEpisode
primaryTitle      The Call of the Wild/Brahms: The Boy II
originalTitle     The Call of the Wild/Brahms: The Boy II
isAdult                                                 0
startYear                                            2020
endYear                                                \N
runtimeMinutes                                         61
genres                                   Comedy,Talk-Show
Name: 2010946, dtype: object

(9,)

tconst                           tt11835192
titleType                         tvEpisode
primaryTitle      Duty's Veil Pilot Episode
originalTitle     Duty's Veil Pilot Episode
isAdult                                   0
startYear                              2019
endYear                                  \N
runtimeMinutes                           \N
genres                       Crime,Thriller
Name: 2010947, dtype: object

(9,)

tconst                                tt11835194
titleType                              tvEpisode
primaryTitle      G.I. Joe Toys Go Full Fortnite
originalTitle     G.I. Joe Toys Go Full Fortnite
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2010948, dtype: object

(9,)

tconst                                     tt11835196
titleType                                   tvEpisode
primaryTitle      New Star Wars Movie In Development?
originalTitle     New Star Wars Movie In Development?
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                      Talk-Show
Name: 2010949, dtype: object

(9,)

tconst                  tt1183519
titleType               tvEpisode
primaryTitle      Episode #1.1521
originalTitle     Episode #1.1521
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2010950, dtype: object

(9,)

tconst                      tt11835200
titleType                        movie
primaryTitle      SS Lazio vs AC Parma
originalTitle     SS Lazio vs AC Parma
isAdult                              0
startYear                         2003
endYear                             \N
runtimeMinutes                      93
genres                          Action
Name: 2010951, dtype: object

(9,)

tconst                                                   tt11835202
titleType                                                 tvEpisode
primaryTitle      Pixar Announces First Animated Alphabet Character
originalTitle     Pixar Announces First Animated Alphabet Character
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2010952, dtype: object

(9,)

tconst                                  tt11835204
titleType                                    movie
primaryTitle      TSV 1860 Munich vs VfB Stuttgart
originalTitle     TSV 1860 Munich vs VfB Stuttgart
isAdult                                          0
startYear                                     2003
endYear                                         \N
runtimeMinutes                                  92
genres                                       Sport
Name: 2010953, dtype: object

(9,)

tconst                         tt11835206
titleType                           video
primaryTitle      Epilogue: The Punchline
originalTitle     Epilogue: The Punchline
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         23
genres                       Comedy,Short
Name: 2010954, dtype: object

(9,)

tconst             tt11835208
titleType               short
primaryTitle         Good Day
originalTitle       Joeun nal
isAdult                     0
startYear                2017
endYear                    \N
runtimeMinutes             28
genres            Drama,Short
Name: 2010955, dtype: object

(9,)

tconst                  tt1183520
titleType               tvEpisode
primaryTitle      Episode #1.1778
originalTitle     Episode #1.1778
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010956, dtype: object

(9,)

tconst                       tt11835210
titleType                         video
primaryTitle      W utsukushiki asashin
originalTitle     W utsukushiki asashin
isAdult                               0
startYear                          2013
endYear                              \N
runtimeMinutes                      183
genres                           Action
Name: 2010957, dtype: object

(9,)

tconst             tt11835212
titleType               short
primaryTitle         With You
originalTitle        With You
isAdult                     0
startYear                2018
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2010958, dtype: object

(9,)

tconst                 tt11835214
titleType               tvEpisode
primaryTitle        Episode #9.10
originalTitle       Episode #9.10
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Game-Show,Music
Name: 2010959, dtype: object

(9,)

tconst                 tt11835216
titleType               tvEpisode
primaryTitle        Episode #9.11
originalTitle       Episode #9.11
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Game-Show,Music
Name: 2010960, dtype: object

(9,)

tconst                             tt11835218
titleType                           tvEpisode
primaryTitle      Austin Wolf & Grayson Lange
originalTitle     Austin Wolf & Grayson Lange
isAdult                                     1
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                  Adult
Name: 2010961, dtype: object

(9,)

tconst                  tt1183521
titleType               tvEpisode
primaryTitle      Episode #1.1780
originalTitle     Episode #1.1780
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010962, dtype: object

(9,)

tconst                 tt11835220
titleType               tvEpisode
primaryTitle        Episode #9.12
originalTitle       Episode #9.12
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Game-Show,Music
Name: 2010963, dtype: object

(9,)

tconst                               tt11835222
titleType                             tvEpisode
primaryTitle      Trump Approval Hits 46% Again
originalTitle     Trump Approval Hits 46% Again
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2010964, dtype: object

(9,)

tconst                                tt11835224
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010965, dtype: object

(9,)

tconst                                      tt11835226
titleType                                        movie
primaryTitle      Manchester City vs Tottenham Hotspur
originalTitle     Manchester City vs Tottenham Hotspur
isAdult                                              0
startYear                                         2003
endYear                                             \N
runtimeMinutes                                      94
genres                                          Action
Name: 2010966, dtype: object

(9,)

tconst              tt11835228
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 1994
endYear                     \N
runtimeMinutes              \N
genres               Talk-Show
Name: 2010967, dtype: object

(9,)

tconst                  tt1183522
titleType               tvEpisode
primaryTitle      Episode #1.1783
originalTitle     Episode #1.1783
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010968, dtype: object

(9,)

tconst                            tt11835230
titleType                          tvEpisode
primaryTitle                   Episode #1.93
originalTitle                  Episode #1.93
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2010969, dtype: object

(9,)

tconst                 tt11835232
titleType                   movie
primaryTitle      The Milan Derby
originalTitle     The Milan Derby
isAdult                         0
startYear                    2003
endYear                        \N
runtimeMinutes                 93
genres                     Action
Name: 2010970, dtype: object

(9,)

tconst                                tt11835234
titleType                                  movie
primaryTitle      SC Freiburg vs TSV 1860 Munich
originalTitle     SC Freiburg vs TSV 1860 Munich
isAdult                                        0
startYear                                   2003
endYear                                       \N
runtimeMinutes                                90
genres                                Reality-TV
Name: 2010971, dtype: object

(9,)

tconst                           tt11835236
titleType                             movie
primaryTitle      Generasi 90an: Melankolia
originalTitle     Generasi 90an: Melankolia
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           91
genres                                Drama
Name: 2010972, dtype: object

(9,)

tconst                             tt11835238
titleType                               movie
primaryTitle      VfB Stuttgart vs 1. FC Köln
originalTitle     VfB Stuttgart vs 1. FC Köln
isAdult                                     0
startYear                                2003
endYear                                    \N
runtimeMinutes                             92
genres                                 Action
Name: 2010973, dtype: object

(9,)

tconst                  tt1183523
titleType               tvEpisode
primaryTitle      Episode #1.1785
originalTitle     Episode #1.1785
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010974, dtype: object

(9,)

tconst                             tt11835242
titleType                               movie
primaryTitle      Bayern Munich vs Hertha BSC
originalTitle     Bayern Munich vs Hertha BSC
isAdult                                     0
startYear                                2003
endYear                                    \N
runtimeMinutes                             93
genres                                 Action
Name: 2010975, dtype: object

(9,)

tconst                      tt11835244
titleType                    tvEpisode
primaryTitle      Emotional Technology
originalTitle     Emotional Technology
isAdult                              0
startYear                         2016
endYear                             \N
runtimeMinutes                      \N
genres                     Documentary
Name: 2010976, dtype: object

(9,)

tconst                                tt11835246
titleType                                  movie
primaryTitle      Juventus FC vs Bologna FC 1909
originalTitle     Juventus FC vs Bologna FC 1909
isAdult                                        0
startYear                                   2003
endYear                                       \N
runtimeMinutes                                90
genres                                Reality-TV
Name: 2010977, dtype: object

(9,)

tconst                           tt11835248
titleType                         tvEpisode
primaryTitle      Carlton & Shantel's Story
originalTitle     Carlton & Shantel's Story
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           85
genres                           Reality-TV
Name: 2010978, dtype: object

(9,)

tconst                  tt1183524
titleType               tvEpisode
primaryTitle      Episode #1.1803
originalTitle     Episode #1.1803
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010979, dtype: object

(9,)

tconst                                tt11835250
titleType                              tvEpisode
primaryTitle      Episode dated 13 February 2020
originalTitle     Episode dated 13 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010980, dtype: object

(9,)

tconst                                   tt11835252
titleType                              tvMiniSeries
primaryTitle      Stromaufwärts! Europas Wasserwege
originalTitle     Stromaufwärts! Europas Wasserwege
isAdult                                           0
startYear                                      2019
endYear                                        2019
runtimeMinutes                                   \N
genres                                  Documentary
Name: 2010981, dtype: object

(9,)

tconst                                   tt11835254
titleType                                     movie
primaryTitle      Leeds United vs Manchester United
originalTitle     Leeds United vs Manchester United
isAdult                                           0
startYear                                      2003
endYear                                          \N
runtimeMinutes                                   94
genres                                   Reality-TV
Name: 2010982, dtype: object

(9,)

tconst                            tt11835256
titleType                          tvEpisode
primaryTitle      13. komnata Pavla Fischera
originalTitle     13. komnata Pavla Fischera
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                 Biography,Documentary
Name: 2010983, dtype: object

(9,)

tconst                         tt11835258
titleType                           video
primaryTitle      Travis Hayes: Teen Haze
originalTitle     Travis Hayes: Teen Haze
isAdult                                 0
startYear                            2014
endYear                                \N
runtimeMinutes                         \N
genres                        Music,Short
Name: 2010984, dtype: object

(9,)

tconst                  tt1183525
titleType               tvEpisode
primaryTitle      Episode #1.1809
originalTitle     Episode #1.1809
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010985, dtype: object

(9,)

tconst                            tt11835260
titleType                              movie
primaryTitle      Everton FC vs Liverpool FC
originalTitle     Everton FC vs Liverpool FC
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            93
genres                                Action
Name: 2010986, dtype: object

(9,)

tconst             tt11835262
titleType               short
primaryTitle           Cuckoo
originalTitle          Cuckoo
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2010987, dtype: object

(9,)

tconst                                tt11835264
titleType                              tvEpisode
primaryTitle      Episode dated 14 February 2020
originalTitle     Episode dated 14 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010988, dtype: object

(9,)

tconst                                tt11835266
titleType                              tvEpisode
primaryTitle      Episode dated 15 February 2020
originalTitle     Episode dated 15 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010989, dtype: object

(9,)

tconst                           tt11835268
titleType                             movie
primaryTitle      AS Roma vs Reggina Calcio
originalTitle     AS Roma vs Reggina Calcio
isAdult                                   0
startYear                              2003
endYear                                  \N
runtimeMinutes                           93
genres                                Sport
Name: 2010990, dtype: object

(9,)

tconst                  tt1183526
titleType               tvEpisode
primaryTitle      Episode #1.1814
originalTitle     Episode #1.1814
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010991, dtype: object

(9,)

tconst                                  tt11835270
titleType                                    movie
primaryTitle      My Truth: The Rape of Two Coreys
originalTitle                             My Truth
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  85
genres                                 Documentary
Name: 2010992, dtype: object

(9,)

tconst                                tt11835272
titleType                              tvEpisode
primaryTitle      Episode dated 16 February 2020
originalTitle     Episode dated 16 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010993, dtype: object

(9,)

tconst                                tt11835274
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010994, dtype: object

(9,)

tconst                     tt11835276
titleType                       short
primaryTitle                Retrieval
originalTitle               Retrieval
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Action,Drama,Sci-Fi
Name: 2010995, dtype: object

(9,)

tconst                                tt11835278
titleType                              tvEpisode
primaryTitle      Episode dated 17 February 2020
originalTitle     Episode dated 17 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010996, dtype: object

(9,)

tconst                  tt1183527
titleType               tvEpisode
primaryTitle      Episode #1.1816
originalTitle     Episode #1.1816
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2010997, dtype: object

(9,)

tconst                                tt11835280
titleType                              tvEpisode
primaryTitle      Episode dated 18 February 2020
originalTitle     Episode dated 18 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2010998, dtype: object

(9,)

tconst                                    tt11835282
titleType                                      movie
primaryTitle      Bayern Munich vs Borussia Dortmund
originalTitle     Bayern Munich vs Borussia Dortmund
isAdult                                            0
startYear                                       2003
endYear                                           \N
runtimeMinutes                                    94
genres                                        Action
Name: 2010999, dtype: object

(9,)

tconst                                tt11835284
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011000, dtype: object

(9,)

tconst                                tt11835286
titleType                              tvEpisode
primaryTitle      Episode dated 14 February 2020
originalTitle     Episode dated 14 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011001, dtype: object

(9,)

tconst                                tt11835288
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011002, dtype: object

(9,)

tconst                  tt1183528
titleType               tvEpisode
primaryTitle      Episode #1.1817
originalTitle     Episode #1.1817
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011003, dtype: object

(9,)

tconst                      tt11835290
titleType                        movie
primaryTitle      AC Parma vs Milan AC
originalTitle     AC Parma vs Milan AC
isAdult                              0
startYear                         2003
endYear                             \N
runtimeMinutes                      93
genres                          Action
Name: 2011004, dtype: object

(9,)

tconst                                tt11835292
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011005, dtype: object

(9,)

tconst                  tt11835296
titleType                    movie
primaryTitle      The Munich Derby
originalTitle     The Munich Derby
isAdult                          0
startYear                     2003
endYear                         \N
runtimeMinutes                  92
genres                      Action
Name: 2011006, dtype: object

(9,)

tconst                tt11835298
titleType              tvEpisode
primaryTitle      Episode #7.136
originalTitle     Episode #7.136
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2011007, dtype: object

(9,)

tconst                  tt1183529
titleType               tvEpisode
primaryTitle      Episode #1.1818
originalTitle     Episode #1.1818
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011008, dtype: object

(9,)

tconst                tt11835300
titleType              tvEpisode
primaryTitle      Episode #7.137
originalTitle     Episode #7.137
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2011009, dtype: object

(9,)

tconst                tt11835302
titleType              tvEpisode
primaryTitle      Episode #7.126
originalTitle     Episode #7.126
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2011010, dtype: object

(9,)

tconst                tt11835304
titleType              tvEpisode
primaryTitle      Episode #7.127
originalTitle     Episode #7.127
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2011011, dtype: object

(9,)

tconst                tt11835306
titleType              tvEpisode
primaryTitle      Episode #7.128
originalTitle     Episode #7.128
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2011012, dtype: object

(9,)

tconst                tt11835308
titleType              tvEpisode
primaryTitle      Episode #7.129
originalTitle     Episode #7.129
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2011013, dtype: object

(9,)

tconst                  tt1183530
titleType               tvEpisode
primaryTitle      Episode #1.1819
originalTitle     Episode #1.1819
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011014, dtype: object

(9,)

tconst                tt11835310
titleType              tvEpisode
primaryTitle      Episode #7.130
originalTitle     Episode #7.130
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2011015, dtype: object

(9,)

tconst                                 tt11835312
titleType                               tvEpisode
primaryTitle      Von der Camargue in die Ardèche
originalTitle     Von der Camargue in die Ardèche
isAdult                                         0
startYear                                    2019
endYear                                        \N
runtimeMinutes                                 43
genres                                Documentary
Name: 2011016, dtype: object

(9,)

tconst                                                 tt11835314
titleType                                               tvEpisode
primaryTitle      Von der Müritz über Berlin bis in die Spreeauen
originalTitle     Von der Müritz über Berlin bis in die Spreeauen
isAdult                                                         0
startYear                                                    2019
endYear                                                        \N
runtimeMinutes                                                 44
genres                                                Documentary
Name: 2011017, dtype: object

(9,)

tconst                            tt11835316
titleType                          tvEpisode
primaryTitle      Episode dated 20 July 2018
originalTitle     Episode dated 20 July 2018
isAdult                                    0
startYear                               2018
endYear                                   \N
runtimeMinutes                           210
genres                                    \N
Name: 2011018, dtype: object

(9,)

tconst                                                   tt11835318
titleType                                                 tvEpisode
primaryTitle      Von der Danziger Bucht bis zur Masurischen See...
originalTitle     Von der Danziger Bucht bis zur Masurischen See...
isAdult                                                           0
startYear                                                      2019
endYear                                                          \N
runtimeMinutes                                                   44
genres                                                  Documentary
Name: 2011019, dtype: object

(9,)

tconst                  tt1183531
titleType               tvEpisode
primaryTitle      Episode #1.1820
originalTitle     Episode #1.1820
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011020, dtype: object

(9,)

tconst                              tt11835320
titleType                            tvEpisode
primaryTitle      Auf dem Po durch Norditalien
originalTitle     Auf dem Po durch Norditalien
isAdult                                      0
startYear                                 2019
endYear                                     \N
runtimeMinutes                              44
genres                             Documentary
Name: 2011021, dtype: object

(9,)

tconst                                              tt11835322
titleType                                            tvEpisode
primaryTitle      Von Rotterdam bis in die belgischen Ardennen
originalTitle     Von Rotterdam bis in die belgischen Ardennen
isAdult                                                      0
startYear                                                 2019
endYear                                                     \N
runtimeMinutes                                              43
genres                                             Documentary
Name: 2011022, dtype: object

(9,)

tconst                       tt11835326
titleType                         movie
primaryTitle      Milan AC vs Modena FC
originalTitle     Milan AC vs Modena FC
isAdult                               0
startYear                          2003
endYear                              \N
runtimeMinutes                       93
genres                           Action
Name: 2011023, dtype: object

(9,)

tconst                                 tt11835328
titleType                                   movie
primaryTitle      FC Internazionale vs AC Perugia
originalTitle     FC Internazionale vs AC Perugia
isAdult                                         0
startYear                                    2003
endYear                                        \N
runtimeMinutes                                 93
genres                                     Action
Name: 2011024, dtype: object

(9,)

tconst                  tt1183532
titleType               tvEpisode
primaryTitle      Episode #1.1822
originalTitle     Episode #1.1822
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011025, dtype: object

(9,)

tconst            tt11835330
titleType              short
primaryTitle           Yusuf
originalTitle          Yusuf
isAdult                    0
startYear               2018
endYear                   \N
runtimeMinutes            \N
genres                 Short
Name: 2011026, dtype: object

(9,)

tconst                         tt11835332
titleType                           movie
primaryTitle      Juventus FC vs AC Parma
originalTitle     Juventus FC vs AC Parma
isAdult                                 0
startYear                            2003
endYear                                \N
runtimeMinutes                         92
genres                             Action
Name: 2011027, dtype: object

(9,)

tconst                                     tt11835334
titleType                                   tvEpisode
primaryTitle      Women in Horror: Staci Layne Wilson
originalTitle     Women in Horror: Staci Layne Wilson
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                         Horror
Name: 2011028, dtype: object

(9,)

tconst                                tt11835336
titleType                                  movie
primaryTitle      Bayern Munich vs VfB Stuttgart
originalTitle     Bayern Munich vs VfB Stuttgart
isAdult                                        0
startYear                                   2003
endYear                                       \N
runtimeMinutes                                95
genres                                    Action
Name: 2011029, dtype: object

(9,)

tconst              tt11835338
titleType                short
primaryTitle           Closure
originalTitle          Closure
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres            Horror,Short
Name: 2011030, dtype: object

(9,)

tconst                  tt1183533
titleType               tvEpisode
primaryTitle      Episode #1.1827
originalTitle     Episode #1.1827
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011031, dtype: object

(9,)

tconst                              tt11835340
titleType                                video
primaryTitle      Angel Olsen: Shut Up Kiss Me
originalTitle     Angel Olsen: Shut Up Kiss Me
isAdult                                      0
startYear                                 2016
endYear                                     \N
runtimeMinutes                               3
genres                             Music,Short
Name: 2011032, dtype: object

(9,)

tconst                   tt11835342
titleType                     short
primaryTitle                A Youth
originalTitle               A Youth
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2011033, dtype: object

(9,)

tconst               tt11835344
titleType                 movie
primaryTitle      Palyaço Recep
originalTitle     Palyaço Recep
isAdult                       0
startYear                  2010
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011034, dtype: object

(9,)

tconst               tt11835346
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               51
genres                Game-Show
Name: 2011035, dtype: object

(9,)

tconst                            tt11835348
titleType                              movie
primaryTitle      Milan AC vs Udinese Calcio
originalTitle     Milan AC vs Udinese Calcio
isAdult                                    0
startYear                               2003
endYear                                   \N
runtimeMinutes                            93
genres                                Action
Name: 2011036, dtype: object

(9,)

tconst                  tt1183534
titleType               tvEpisode
primaryTitle      Episode #1.1838
originalTitle     Episode #1.1838
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011037, dtype: object

(9,)

tconst                       tt11835350
titleType                         movie
primaryTitle      AC Perugia vs AS Roma
originalTitle     AC Perugia vs AS Roma
isAdult                               0
startYear                          2004
endYear                              \N
runtimeMinutes                       92
genres                           Action
Name: 2011038, dtype: object

(9,)

tconst                      tt11835352
titleType                    tvEpisode
primaryTitle      Goodbye to Our World
originalTitle     Goodbye to Our World
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                       Animation
Name: 2011039, dtype: object

(9,)

tconst                      tt11835354
titleType                    tvEpisode
primaryTitle      Lullaby of the Stars
originalTitle     Lullaby of the Stars
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      \N
genres                       Animation
Name: 2011040, dtype: object

(9,)

tconst                    tt11835356
titleType                  tvEpisode
primaryTitle      Chasing Our Dreams
originalTitle     Chasing Our Dreams
isAdult                            0
startYear                       2020
endYear                           \N
runtimeMinutes                    \N
genres                     Animation
Name: 2011041, dtype: object

(9,)

tconst                            tt11835358
titleType                          tvEpisode
primaryTitle      22/7 (nanabun no nijyuuni)
originalTitle     22/7 (nanabun no nijyuuni)
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                             Animation
Name: 2011042, dtype: object

(9,)

tconst                  tt1183535
titleType               tvEpisode
primaryTitle      Episode #1.1840
originalTitle     Episode #1.1840
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011043, dtype: object

(9,)

tconst                        tt11835360
titleType                          movie
primaryTitle      Milan AC vs AC Perugia
originalTitle     Milan AC vs AC Perugia
isAdult                                0
startYear                           2004
endYear                               \N
runtimeMinutes                        93
genres                            Action
Name: 2011044, dtype: object

(9,)

tconst                                              tt11835362
titleType                                                movie
primaryTitle      Borussia Mönchengladbach vs SV Werder Bremen
originalTitle     Borussia Mönchengladbach vs SV Werder Bremen
isAdult                                                      0
startYear                                                 2004
endYear                                                     \N
runtimeMinutes                                              95
genres                                                  Action
Name: 2011045, dtype: object

(9,)

tconst                         tt11835364
titleType                       tvEpisode
primaryTitle             Dueling Fictions
originalTitle            Dueling Fictions
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres            Action,Animation,Comedy
Name: 2011046, dtype: object

(9,)

tconst                         tt11835366
titleType                       tvEpisode
primaryTitle         The Ultimate Fiction
originalTitle        The Ultimate Fiction
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres            Action,Animation,Comedy
Name: 2011047, dtype: object

(9,)

tconst                      tt11835368
titleType                        movie
primaryTitle      US Lecce vs Milan AC
originalTitle     US Lecce vs Milan AC
isAdult                              0
startYear                         2004
endYear                             \N
runtimeMinutes                      92
genres                          Action
Name: 2011048, dtype: object

(9,)

tconst                  tt1183536
titleType               tvEpisode
primaryTitle      Episode #1.1841
originalTitle     Episode #1.1841
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011049, dtype: object

(9,)

tconst                         tt11835370
titleType                       tvEpisode
primaryTitle        She Who Defends Order
originalTitle       She Who Defends Order
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres            Action,Animation,Comedy
Name: 2011050, dtype: object

(9,)

tconst                     tt11835372
titleType                       movie
primaryTitle      AS Roma vs AC Siena
originalTitle     AS Roma vs AC Siena
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     92
genres                         Action
Name: 2011051, dtype: object

(9,)

tconst                                tt11835374
titleType                                  movie
primaryTitle      Bayern Munich vs VfL Wolfsburg
originalTitle     Bayern Munich vs VfL Wolfsburg
isAdult                                        0
startYear                                   2004
endYear                                       \N
runtimeMinutes                                92
genres                                    Action
Name: 2011052, dtype: object

(9,)

tconst                                tt11835376
titleType                                  movie
primaryTitle      VfB Stuttgart vs FC Schalke 04
originalTitle     VfB Stuttgart vs FC Schalke 04
isAdult                                        0
startYear                                   2004
endYear                                       \N
runtimeMinutes                                92
genres                                    Action
Name: 2011053, dtype: object

(9,)

tconst                     tt11835378
titleType                       movie
primaryTitle      AC Parma vs AS Roma
originalTitle     AC Parma vs AS Roma
isAdult                             0
startYear                        2004
endYear                            \N
runtimeMinutes                     93
genres                         Action
Name: 2011054, dtype: object

(9,)

tconst                  tt1183537
titleType               tvEpisode
primaryTitle      Episode #1.1845
originalTitle     Episode #1.1845
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011055, dtype: object

(9,)

tconst              tt11835380
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2011056, dtype: object

(9,)

tconst                     tt11835382
titleType                       short
primaryTitle      Soothing the Bruise
originalTitle     Soothing the Bruise
isAdult                             0
startYear                        1980
endYear                            \N
runtimeMinutes                     20
genres                          Short
Name: 2011057, dtype: object

(9,)

tconst                            tt11835384
titleType                              movie
primaryTitle      Hamburger SV vs Hertha BSC
originalTitle     Hamburger SV vs Hertha BSC
isAdult                                    0
startYear                               2004
endYear                                   \N
runtimeMinutes                            92
genres                                Action
Name: 2011058, dtype: object

(9,)

tconst              tt11835386
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2011059, dtype: object

(9,)

tconst                           tt11835388
titleType                             movie
primaryTitle      Reggina Calcio vs AS Roma
originalTitle     Reggina Calcio vs AS Roma
isAdult                                   0
startYear                              2004
endYear                                  \N
runtimeMinutes                           93
genres                               Action
Name: 2011060, dtype: object

(9,)

tconst                  tt1183538
titleType               tvEpisode
primaryTitle      Episode #1.1850
originalTitle     Episode #1.1850
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011061, dtype: object

(9,)

tconst                             tt11835390
titleType                               movie
primaryTitle      VfL Bochum vs FC Schalke 04
originalTitle     VfL Bochum vs FC Schalke 04
isAdult                                     0
startYear                                2004
endYear                                    \N
runtimeMinutes                             93
genres                                 Action
Name: 2011062, dtype: object

(9,)

tconst              tt11835392
titleType            tvEpisode
primaryTitle         Infection
originalTitle        Infection
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              31
genres            Comedy,Drama
Name: 2011063, dtype: object

(9,)

tconst                   tt11835394
titleType                 tvEpisode
primaryTitle      Pigen fra Italien
originalTitle     Pigen fra Italien
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   11
genres                       Family
Name: 2011064, dtype: object

(9,)

tconst                     tt11835396
titleType                   tvEpisode
primaryTitle      Friday, February 21
originalTitle     Friday, February 21
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                           News
Name: 2011065, dtype: object

(9,)

tconst                           tt11835398
titleType                             movie
primaryTitle      Milan AC vs Chievo Verona
originalTitle     Milan AC vs Chievo Verona
isAdult                                   0
startYear                              2004
endYear                                  \N
runtimeMinutes                           92
genres                               Action
Name: 2011066, dtype: object

(9,)

tconst                  tt1183539
titleType               tvEpisode
primaryTitle      Episode #1.1852
originalTitle     Episode #1.1852
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011067, dtype: object

(9,)

tconst                    tt11835400
titleType                  tvEpisode
primaryTitle      Il cuore di Orsola
originalTitle     Il cuore di Orsola
isAdult                            0
startYear                       2016
endYear                           \N
runtimeMinutes                    \N
genres                    Crime,News
Name: 2011068, dtype: object

(9,)

tconst                         tt11835404
titleType                           movie
primaryTitle      AC Parma vs Juventus FC
originalTitle     AC Parma vs Juventus FC
isAdult                                 0
startYear                            2004
endYear                                \N
runtimeMinutes                         93
genres                             Action
Name: 2011069, dtype: object

(9,)

tconst                                        tt11835406
titleType                                      tvEpisode
primaryTitle      Jordanie: la discrète du Proche-Orient
originalTitle     Jordanie: la discrète du Proche-Orient
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        13
genres                       Animation,Documentary,Short
Name: 2011070, dtype: object

(9,)

tconst                  tt1183540
titleType               tvEpisode
primaryTitle      Episode #1.1853
originalTitle     Episode #1.1853
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011071, dtype: object

(9,)

tconst                                        tt11835412
titleType                                      tvSpecial
primaryTitle      The Prince's Trust: We Are Most Amused
originalTitle     The Prince's Trust: We Are Most Amused
isAdult                                                0
startYear                                           2008
endYear                                               \N
runtimeMinutes                                        \N
genres                                            Comedy
Name: 2011072, dtype: object

(9,)

tconst                      tt11835416
titleType                    tvEpisode
primaryTitle              Episode #3.2
originalTitle             Episode #3.2
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Fantasy
Name: 2011073, dtype: object

(9,)

tconst                  tt1183541
titleType               tvEpisode
primaryTitle      Episode #1.1855
originalTitle     Episode #1.1855
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011074, dtype: object

(9,)

tconst                      tt11835420
titleType                    tvEpisode
primaryTitle              Episode #3.3
originalTitle             Episode #3.3
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Fantasy
Name: 2011075, dtype: object

(9,)

tconst                      tt11835422
titleType                    tvEpisode
primaryTitle              Episode #3.4
originalTitle             Episode #3.4
isAdult                              0
startYear                         2021
endYear                             \N
runtimeMinutes                      \N
genres            Action,Drama,Fantasy
Name: 2011076, dtype: object

(9,)

tconst                        tt11835424
titleType                        tvMovie
primaryTitle      The Story of a Recluse
originalTitle     The Story of a Recluse
isAdult                                0
startYear                           1987
endYear                               \N
runtimeMinutes                        50
genres                         Adventure
Name: 2011077, dtype: object

(9,)

tconst              tt11835426
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes             111
genres               Talk-Show
Name: 2011078, dtype: object

(9,)

tconst                                             tt11835428
titleType                                               movie
primaryTitle      La sentencia: Crónica de un día de justicia
originalTitle     La sentencia: Crónica de un día de justicia
isAdult                                                     0
startYear                                                2018
endYear                                                    \N
runtimeMinutes                                             72
genres                                            Documentary
Name: 2011079, dtype: object

(9,)

tconst                  tt1183542
titleType               tvEpisode
primaryTitle      Episode #1.1857
originalTitle     Episode #1.1857
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011080, dtype: object

(9,)

tconst                                tt11835430
titleType                              tvEpisode
primaryTitle      Brauchtum im Lungau und Pongau
originalTitle     Brauchtum im Lungau und Pongau
isAdult                                        0
startYear                                   1969
endYear                                       \N
runtimeMinutes                                \N
genres                               Documentary
Name: 2011081, dtype: object

(9,)

tconst               tt11835432
titleType                 short
primaryTitle            Forever
originalTitle           Forever
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes               10
genres            Musical,Short
Name: 2011082, dtype: object

(9,)

tconst               tt11835434
titleType             tvEpisode
primaryTitle      Episode #9.71
originalTitle     Episode #9.71
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011083, dtype: object

(9,)

tconst               tt11835436
titleType             tvEpisode
primaryTitle      Episode #9.72
originalTitle     Episode #9.72
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011084, dtype: object

(9,)

tconst               tt11835438
titleType             tvEpisode
primaryTitle      Episode #9.73
originalTitle     Episode #9.73
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011085, dtype: object

(9,)

tconst                  tt1183543
titleType               tvEpisode
primaryTitle      Episode #1.1858
originalTitle     Episode #1.1858
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011086, dtype: object

(9,)

tconst               tt11835440
titleType             tvEpisode
primaryTitle      Episode #9.74
originalTitle     Episode #9.74
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011087, dtype: object

(9,)

tconst               tt11835442
titleType             tvEpisode
primaryTitle      Episode #9.75
originalTitle     Episode #9.75
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011088, dtype: object

(9,)

tconst               tt11835444
titleType             tvEpisode
primaryTitle      Episode #9.76
originalTitle     Episode #9.76
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011089, dtype: object

(9,)

tconst               tt11835448
titleType             tvEpisode
primaryTitle      Episode #9.77
originalTitle     Episode #9.77
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011090, dtype: object

(9,)

tconst                  tt1183544
titleType               tvEpisode
primaryTitle      Episode #1.1859
originalTitle     Episode #1.1859
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011091, dtype: object

(9,)

tconst               tt11835450
titleType             tvEpisode
primaryTitle      Episode #9.78
originalTitle     Episode #9.78
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011092, dtype: object

(9,)

tconst               tt11835452
titleType             tvEpisode
primaryTitle      Episode #9.79
originalTitle     Episode #9.79
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011093, dtype: object

(9,)

tconst               tt11835454
titleType             tvEpisode
primaryTitle      Episode #9.80
originalTitle     Episode #9.80
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011094, dtype: object

(9,)

tconst            tt11835456
titleType              movie
primaryTitle       Agnidahan
originalTitle      Agnidahan
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes           118
genres                 Drama
Name: 2011095, dtype: object

(9,)

tconst                tt11835458
titleType              tvEpisode
primaryTitle      Jörgen Raymann
originalTitle     Jörgen Raymann
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                42
genres               Documentary
Name: 2011096, dtype: object

(9,)

tconst                  tt1183545
titleType               tvEpisode
primaryTitle      Episode #1.1860
originalTitle     Episode #1.1860
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011097, dtype: object

(9,)

tconst                                tt11835460
titleType                              tvEpisode
primaryTitle      Episode dated 23 February 2020
originalTitle     Episode dated 23 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011098, dtype: object

(9,)

tconst                     tt11835462
titleType                tvMiniSeries
primaryTitle      Courthill Squadcast
originalTitle     Courthill Squadcast
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres                      Talk-Show
Name: 2011099, dtype: object

(9,)

tconst                                       tt11835464
titleType                                      tvSeries
primaryTitle      Kozaky. Absolyutno brekhlyva istoriya
originalTitle     Kozaky. Absolyutno brekhlyva istoriya
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                        Adventure
Name: 2011100, dtype: object

(9,)

tconst                                tt11835468
titleType                              tvEpisode
primaryTitle      Episode dated 18 November 2016
originalTitle     Episode dated 18 November 2016
isAdult                                        0
startYear                                   2016
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2011101, dtype: object

(9,)

tconst                  tt1183546
titleType               tvEpisode
primaryTitle      Episode #1.1863
originalTitle     Episode #1.1863
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011102, dtype: object

(9,)

tconst            tt11835470
titleType           tvSeries
primaryTitle         Bedrock
originalTitle        Bedrock
isAdult                    0
startYear               1998
endYear                 2000
runtimeMinutes            \N
genres             Talk-Show
Name: 2011103, dtype: object

(9,)

tconst                       tt11835472
titleType                       tvMovie
primaryTitle              Billy the Kid
originalTitle             Billy the Kid
isAdult                               0
startYear                          2012
endYear                              \N
runtimeMinutes                       52
genres            Biography,Documentary
Name: 2011104, dtype: object

(9,)

tconst                tt11835474
titleType                  short
primaryTitle               Jewel
originalTitle              Jewel
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres            Short,Thriller
Name: 2011105, dtype: object

(9,)

tconst                      tt11835476
titleType                    videoGame
primaryTitle      Cube Escape: Paradox
originalTitle     Cube Escape: Paradox
isAdult                              0
startYear                         2018
endYear                             \N
runtimeMinutes                      \N
genres                         Mystery
Name: 2011106, dtype: object

(9,)

tconst                   tt11835478
titleType                 tvEpisode
primaryTitle      1st Test: Day One
originalTitle     1st Test: Day One
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                        Sport
Name: 2011107, dtype: object

(9,)

tconst                  tt1183547
titleType               tvEpisode
primaryTitle      Episode #1.1864
originalTitle     Episode #1.1864
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011108, dtype: object

(9,)

tconst                   tt11835480
titleType                 tvEpisode
primaryTitle      1st Test: Day Two
originalTitle     1st Test: Day Two
isAdult                           0
startYear                      2019
endYear                          \N
runtimeMinutes                   \N
genres                        Sport
Name: 2011109, dtype: object

(9,)

tconst                     tt11835482
titleType                   tvEpisode
primaryTitle      1st Test: Day Three
originalTitle     1st Test: Day Three
isAdult                             0
startYear                        2019
endYear                            \N
runtimeMinutes                     \N
genres                          Sport
Name: 2011110, dtype: object

(9,)

tconst                    tt11835484
titleType                  tvEpisode
primaryTitle      1st Test: Day Four
originalTitle     1st Test: Day Four
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                         Sport
Name: 2011111, dtype: object

(9,)

tconst                    tt11835486
titleType                  tvEpisode
primaryTitle      1st Test: Day Five
originalTitle     1st Test: Day Five
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres                         Sport
Name: 2011112, dtype: object

(9,)

tconst                     tt11835488
titleType                   tvEpisode
primaryTitle          Episode #1.4888
originalTitle         Episode #1.4888
isAdult                             0
startYear                        1982
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Romance
Name: 2011113, dtype: object

(9,)

tconst                  tt1183548
titleType               tvEpisode
primaryTitle      Episode #1.1865
originalTitle     Episode #1.1865
isAdult                         0
startYear                    1978
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011114, dtype: object

(9,)

tconst              tt11835490
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              12
genres                  Comedy
Name: 2011115, dtype: object

(9,)

tconst              tt11835492
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2002
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011116, dtype: object

(9,)

tconst                                                   tt11835494
titleType                                                  tvSeries
primaryTitle      Australian cricket team in South Africa in 201...
originalTitle     Australian cricket team in South Africa in 201...
isAdult                                                           0
startYear                                                      2020
endYear                                                        2020
runtimeMinutes                                                   \N
genres                                                        Sport
Name: 2011117, dtype: object

(9,)

tconst                         tt11835496
titleType                       tvEpisode
primaryTitle          Three Sick Brothers
originalTitle         Three Sick Brothers
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         27
genres            Horror,Mystery,Thriller
Name: 2011118, dtype: object

(9,)

tconst                         tt11835498
titleType                       tvEpisode
primaryTitle                   Bad Writer
originalTitle                  Bad Writer
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         27
genres            Horror,Mystery,Thriller
Name: 2011119, dtype: object

(9,)

tconst                  tt1183549
titleType               tvEpisode
primaryTitle      Episode #1.6746
originalTitle     Episode #1.6746
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 23
genres              Drama,Romance
Name: 2011120, dtype: object

(9,)

tconst                         tt11835500
titleType                       tvEpisode
primaryTitle                     Lab Rats
originalTitle                    Lab Rats
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         32
genres            Horror,Mystery,Thriller
Name: 2011121, dtype: object

(9,)

tconst                         tt11835502
titleType                       tvEpisode
primaryTitle               The Old School
originalTitle              The Old School
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         28
genres            Horror,Mystery,Thriller
Name: 2011122, dtype: object

(9,)

tconst                        tt11835504
titleType                   tvMiniSeries
primaryTitle      Franche-Comté und Jura
originalTitle     Franche-Comté und Jura
isAdult                                0
startYear                           2017
endYear                             2017
runtimeMinutes                        \N
genres                       Documentary
Name: 2011123, dtype: object

(9,)

tconst                          tt11835506
titleType                            short
primaryTitle      A Woman of a Certain Age
originalTitle     A Woman of a Certain Age
isAdult                                  0
startYear                               \N
endYear                                 \N
runtimeMinutes                          15
genres                         Drama,Short
Name: 2011124, dtype: object

(9,)

tconst              tt11835508
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              12
genres                  Comedy
Name: 2011125, dtype: object

(9,)

tconst                  tt1183550
titleType               tvEpisode
primaryTitle      Episode #1.6747
originalTitle     Episode #1.6747
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011126, dtype: object

(9,)

tconst                          tt11835510
titleType                        tvEpisode
primaryTitle      The Elephant in the Room
originalTitle     The Elephant in the Room
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          27
genres             Horror,Mystery,Thriller
Name: 2011127, dtype: object

(9,)

tconst              tt11835512
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              11
genres                  Comedy
Name: 2011128, dtype: object

(9,)

tconst              tt11835514
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              44
genres             Documentary
Name: 2011129, dtype: object

(9,)

tconst               tt11835516
titleType                 video
primaryTitle      The Romantics
originalTitle     The Romantics
isAdult                       0
startYear                  2015
endYear                      \N
runtimeMinutes               \N
genres                    Short
Name: 2011130, dtype: object

(9,)

tconst              tt11835518
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2017
endYear                     \N
runtimeMinutes              44
genres             Documentary
Name: 2011131, dtype: object

(9,)

tconst                 tt1183551
titleType              tvEpisode
primaryTitle      Episode #58.24
originalTitle     Episode #58.24
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                45
genres                 Game-Show
Name: 2011132, dtype: object

(9,)

tconst               tt11835524
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2011133, dtype: object

(9,)

tconst              tt11835526
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes               9
genres                  Comedy
Name: 2011134, dtype: object

(9,)

tconst                 tt11835528
titleType                   movie
primaryTitle      La corte de Ana
originalTitle     La corte de Ana
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                Documentary
Name: 2011135, dtype: object

(9,)

tconst                 tt1183552
titleType              tvEpisode
primaryTitle      Episode #58.25
originalTitle     Episode #58.25
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                45
genres                 Game-Show
Name: 2011136, dtype: object

(9,)

tconst              tt11835530
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              12
genres                  Comedy
Name: 2011137, dtype: object

(9,)

tconst              tt11835534
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              12
genres                  Comedy
Name: 2011138, dtype: object

(9,)

tconst                   tt11835536
titleType                  tvSeries
primaryTitle      Believe It or Not
originalTitle     Believe It or Not
isAdult                           0
startYear                      2015
endYear                        2016
runtimeMinutes                   \N
genres                    Game-Show
Name: 2011139, dtype: object

(9,)

tconst            tt11835538
titleType          tvEpisode
primaryTitle        Poquelin
originalTitle       Poquelin
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            88
genres                 Crime
Name: 2011140, dtype: object

(9,)

tconst                 tt1183553
titleType              tvEpisode
primaryTitle      Episode #58.26
originalTitle     Episode #58.26
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                45
genres                 Game-Show
Name: 2011141, dtype: object

(9,)

tconst              tt11835540
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes               9
genres                  Comedy
Name: 2011142, dtype: object

(9,)

tconst                                tt11835542
titleType                              tvEpisode
primaryTitle      Episode dated 22 February 2020
originalTitle     Episode dated 22 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011143, dtype: object

(9,)

tconst                      tt11835544
titleType                        short
primaryTitle      Utbränd och nydumpad
originalTitle     Utbränd och nydumpad
isAdult                              0
startYear                         2017
endYear                             \N
runtimeMinutes                      30
genres                    Horror,Short
Name: 2011144, dtype: object

(9,)

tconst                    tt11835546
titleType                      short
primaryTitle        La Dernière Note
originalTitle       La Dernière Note
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    30
genres            Drama,Horror,Short
Name: 2011145, dtype: object

(9,)

tconst                   tt11835548
titleType                 tvEpisode
primaryTitle      Looking - Through
originalTitle     Looking - Through
isAdult                           0
startYear                      1982
endYear                          \N
runtimeMinutes                   \N
genres                       Family
Name: 2011146, dtype: object

(9,)

tconst                 tt1183554
titleType              tvEpisode
primaryTitle      Episode #58.27
originalTitle     Episode #58.27
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                45
genres                 Game-Show
Name: 2011147, dtype: object

(9,)

tconst                                            tt11835550
titleType                                              short
primaryTitle      Förutsättningslöst möte (Open Discussions)
originalTitle     Förutsättningslöst möte (Open Discussions)
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                             8
genres                                           Drama,Short
Name: 2011148, dtype: object

(9,)

tconst              tt11835552
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              11
genres                  Comedy
Name: 2011149, dtype: object

(9,)

tconst              tt11835554
titleType            tvEpisode
primaryTitle      Looking - In
originalTitle     Looking - In
isAdult                      0
startYear                 1982
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2011150, dtype: object

(9,)

tconst                      tt11835556
titleType                    tvEpisode
primaryTitle      Looking - All Around
originalTitle     Looking - All Around
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres                          Family
Name: 2011151, dtype: object

(9,)

tconst             tt11835558
titleType               short
primaryTitle        Quasi ora
originalTitle       Quasi ora
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             13
genres            Drama,Short
Name: 2011152, dtype: object

(9,)

tconst                 tt1183555
titleType              tvEpisode
primaryTitle      Episode #58.28
originalTitle     Episode #58.28
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                45
genres                 Game-Show
Name: 2011153, dtype: object

(9,)

tconst              tt11835560
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              10
genres                  Comedy
Name: 2011154, dtype: object

(9,)

tconst              tt11835562
titleType            tvEpisode
primaryTitle      Looking - At
originalTitle     Looking - At
isAdult                      0
startYear                 1982
endYear                     \N
runtimeMinutes              \N
genres                  Family
Name: 2011155, dtype: object

(9,)

tconst               tt11835566
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2018
endYear                      \N
runtimeMinutes               15
genres                   Comedy
Name: 2011156, dtype: object

(9,)

tconst               tt11835568
titleType             tvEpisode
primaryTitle      Looking - For
originalTitle     Looking - For
isAdult                       0
startYear                  1982
endYear                      \N
runtimeMinutes               \N
genres                   Family
Name: 2011157, dtype: object

(9,)

tconst                           tt1183556
titleType                        tvEpisode
primaryTitle      Por la boca muere el pez
originalTitle     Por la boca muere el pez
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          \N
genres              Adventure,Comedy,Drama
Name: 2011158, dtype: object

(9,)

tconst                         tt11835572
titleType                       tvEpisode
primaryTitle      Liebe-Dein-Haustier-Tag
originalTitle     Liebe-Dein-Haustier-Tag
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                   Comedy,Game-Show
Name: 2011159, dtype: object

(9,)

tconst                                        tt11835576
titleType                                      tvEpisode
primaryTitle      Working with Natural Materials - Metal
originalTitle     Working with Natural Materials - Metal
isAdult                                                0
startYear                                           1982
endYear                                               \N
runtimeMinutes                                        \N
genres                                            Family
Name: 2011160, dtype: object

(9,)

tconst              tt11835578
titleType             tvSeries
primaryTitle      Calling Home
originalTitle     Calling Home
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Documentary
Name: 2011161, dtype: object

(9,)

tconst                             tt1183557
titleType                          tvEpisode
primaryTitle               When Penguins Fly
originalTitle              When Penguins Fly
isAdult                                    0
startYear                               2007
endYear                                   \N
runtimeMinutes                            23
genres            Adventure,Animation,Comedy
Name: 2011162, dtype: object

(9,)

tconst                                tt11835580
titleType                              tvEpisode
primaryTitle      Episode dated 23 February 2020
originalTitle     Episode dated 23 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011163, dtype: object

(9,)

tconst                                                   tt11835582
titleType                                                 tvEpisode
primaryTitle      Working with Natural Materials - Cement and Pl...
originalTitle     Working with Natural Materials - Cement and Pl...
isAdult                                                           0
startYear                                                      1982
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Family
Name: 2011164, dtype: object

(9,)

tconst                         tt11835584
titleType                       tvEpisode
primaryTitle      Ohne dich geht es nicht
originalTitle     Ohne dich geht es nicht
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                   Drama,Reality-TV
Name: 2011165, dtype: object

(9,)

tconst            tt11835586
titleType              movie
primaryTitle         On Hold
originalTitle        On Hold
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            60
genres                    \N
Name: 2011166, dtype: object

(9,)

tconst              tt11835588
titleType                movie
primaryTitle      Efsunlu Ayin
originalTitle     Efsunlu Ayin
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              92
genres                  Horror
Name: 2011167, dtype: object

(9,)

tconst                             tt1183558
titleType                          tvEpisode
primaryTitle                Tagg, You're It!
originalTitle               Tagg, You're It!
isAdult                                    0
startYear                               1988
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2011168, dtype: object

(9,)

tconst                                               tt11835590
titleType                                             tvEpisode
primaryTitle      Working with Natural Materials - Clay and Mud
originalTitle     Working with Natural Materials - Clay and Mud
isAdult                                                       0
startYear                                                  1982
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                   Family
Name: 2011169, dtype: object

(9,)

tconst                          tt11835594
titleType                            movie
primaryTitle      The Cunning Little Vixen
originalTitle     The Cunning Little Vixen
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                         101
genres                             Musical
Name: 2011170, dtype: object

(9,)

tconst                                                   tt11835596
titleType                                                 tvEpisode
primaryTitle      Working with Natural Materials - Wool, Cotton,...
originalTitle     Working with Natural Materials - Wool, Cotton,...
isAdult                                                           0
startYear                                                      1982
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Family
Name: 2011171, dtype: object

(9,)

tconst            tt11835598
titleType          tvEpisode
primaryTitle         Huddart
originalTitle        Huddart
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011172, dtype: object

(9,)

tconst                             tt1183559
titleType                          tvEpisode
primaryTitle                    Thanksgiving
originalTitle                   Thanksgiving
isAdult                                    0
startYear                               1988
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2011173, dtype: object

(9,)

tconst            tt11835600
titleType          tvEpisode
primaryTitle       Spenceley
originalTitle      Spenceley
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011174, dtype: object

(9,)

tconst              tt11835602
titleType            tvEpisode
primaryTitle      Rick & Morty
originalTitle     Rick & Morty
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              62
genres               Talk-Show
Name: 2011175, dtype: object

(9,)

tconst            tt11835604
titleType          tvEpisode
primaryTitle        McEleney
originalTitle       McEleney
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011176, dtype: object

(9,)

tconst                             tt11835606
titleType                           tvEpisode
primaryTitle                Mary Noyes Dunham
originalTitle               Mary Noyes Dunham
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2011177, dtype: object

(9,)

tconst                                       tt11835608
titleType                                     tvEpisode
primaryTitle      Working with Natural Materials - Wood
originalTitle     Working with Natural Materials - Wood
isAdult                                               0
startYear                                          1982
endYear                                              \N
runtimeMinutes                                       \N
genres                                           Family
Name: 2011178, dtype: object

(9,)

tconst                tt1183560
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres              Crime,Drama
Name: 2011179, dtype: object

(9,)

tconst            tt11835610
titleType          tvEpisode
primaryTitle         Walters
originalTitle        Walters
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres            Reality-TV
Name: 2011180, dtype: object

(9,)

tconst            tt11835612
titleType          tvEpisode
primaryTitle        Donnelly
originalTitle       Donnelly
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011181, dtype: object

(9,)

tconst                             tt11835614
titleType                           tvEpisode
primaryTitle                Marion Domenicali
originalTitle               Marion Domenicali
isAdult                                     0
startYear                                1955
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2011182, dtype: object

(9,)

tconst            tt11835616
titleType          tvEpisode
primaryTitle            Bone
originalTitle           Bone
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011183, dtype: object

(9,)

tconst                            tt11835618
titleType                          tvEpisode
primaryTitle      A Dash of L.A. Abracadabra
originalTitle     A Dash of L.A. Abracadabra
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            21
genres                            Reality-TV
Name: 2011184, dtype: object

(9,)

tconst                tt1183561
titleType             tvEpisode
primaryTitle       Episode #1.6
originalTitle      Episode #1.6
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres            Drama,Romance
Name: 2011185, dtype: object

(9,)

tconst            tt11835620
titleType          tvEpisode
primaryTitle           Evans
originalTitle          Evans
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011186, dtype: object

(9,)

tconst            tt11835622
titleType          tvEpisode
primaryTitle         Myburgh
originalTitle        Myburgh
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011187, dtype: object

(9,)

tconst                               tt11835624
titleType                             tvEpisode
primaryTitle      Transport - Boats and Bridges
originalTitle     Transport - Boats and Bridges
isAdult                                       0
startYear                                  1982
endYear                                      \N
runtimeMinutes                               \N
genres                                   Family
Name: 2011188, dtype: object

(9,)

tconst            tt11835626
titleType          tvEpisode
primaryTitle         Salaman
originalTitle        Salaman
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011189, dtype: object

(9,)

tconst            tt11835628
titleType          tvEpisode
primaryTitle          Mudhar
originalTitle         Mudhar
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            44
genres            Reality-TV
Name: 2011190, dtype: object

(9,)

tconst                  tt1183562
titleType               tvEpisode
primaryTitle      Episode #1.4846
originalTitle     Episode #1.4846
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011191, dtype: object

(9,)

tconst                         tt11835630
titleType                           short
primaryTitle      True Love Comes Quietly
originalTitle     True Love Comes Quietly
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                      Romance,Short
Name: 2011192, dtype: object

(9,)

tconst                                         tt11835632
titleType                                           short
primaryTitle      Posti- ja lennätinlaitos Keski-Suomessa
originalTitle     Posti- ja lennätinlaitos Keski-Suomessa
isAdult                                                 0
startYear                                            1968
endYear                                                \N
runtimeMinutes                                         14
genres                                  Documentary,Short
Name: 2011193, dtype: object

(9,)

tconst                                    tt11835634
titleType                                  tvEpisode
primaryTitle      Transport - Moving Vans and Babies
originalTitle     Transport - Moving Vans and Babies
isAdult                                            0
startYear                                       1982
endYear                                           \N
runtimeMinutes                                    \N
genres                                        Family
Name: 2011194, dtype: object

(9,)

tconst                              tt11835636
titleType                            tvEpisode
primaryTitle      Tiny with Two Teens in Texas
originalTitle     Tiny with Two Teens in Texas
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              21
genres                              Reality-TV
Name: 2011195, dtype: object

(9,)

tconst                                tt11835638
titleType                              tvEpisode
primaryTitle      Episode dated 22 February 2020
originalTitle     Episode dated 22 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011196, dtype: object

(9,)

tconst                                tt1183563
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011197, dtype: object

(9,)

tconst               tt11835640
titleType                 short
primaryTitle        Blind Faith
originalTitle       Blind Faith
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes                7
genres            Romance,Short
Name: 2011198, dtype: object

(9,)

tconst                     tt11835642
titleType                   tvEpisode
primaryTitle                Protected
originalTitle               Protected
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2011199, dtype: object

(9,)

tconst              tt11835644
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2022
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011200, dtype: object

(9,)

tconst              tt11835646
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011201, dtype: object

(9,)

tconst              tt11835648
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011202, dtype: object

(9,)

tconst                  tt1183564
titleType               tvEpisode
primaryTitle      Episode #1.3705
originalTitle     Episode #1.3705
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2011203, dtype: object

(9,)

tconst                          tt11835650
titleType                        tvEpisode
primaryTitle      A House with Dance Space
originalTitle     A House with Dance Space
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          \N
genres                          Reality-TV
Name: 2011204, dtype: object

(9,)

tconst              tt11835652
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011205, dtype: object

(9,)

tconst              tt11835654
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011206, dtype: object

(9,)

tconst              tt11835656
titleType                movie
primaryTitle      Boku no haru
originalTitle     Boku no haru
isAdult                      0
startYear                 1936
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011207, dtype: object

(9,)

tconst              tt11835658
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011208, dtype: object

(9,)

tconst                       tt1183565
titleType                    tvEpisode
primaryTitle             Episode #1.61
originalTitle            Episode #1.61
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2011209, dtype: object

(9,)

tconst                             tt11835660
titleType                           tvEpisode
primaryTitle      Episode dated 20 April 1956
originalTitle     Episode dated 20 April 1956
isAdult                                     0
startYear                                1956
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2011210, dtype: object

(9,)

tconst              tt11835662
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011211, dtype: object

(9,)

tconst                tt11835664
titleType              tvEpisode
primaryTitle      Episode #1.121
originalTitle     Episode #1.121
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011212, dtype: object

(9,)

tconst                tt11835666
titleType              tvEpisode
primaryTitle      Episode #1.122
originalTitle     Episode #1.122
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011213, dtype: object

(9,)

tconst                tt11835668
titleType              tvEpisode
primaryTitle      Episode #1.123
originalTitle     Episode #1.123
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011214, dtype: object

(9,)

tconst                tt1183566
titleType             tvEpisode
primaryTitle      Episode #9.21
originalTitle     Episode #9.21
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               86
genres             Action,Sport
Name: 2011215, dtype: object

(9,)

tconst                tt11835670
titleType              tvEpisode
primaryTitle      Episode #1.124
originalTitle     Episode #1.124
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011216, dtype: object

(9,)

tconst                tt11835672
titleType              tvEpisode
primaryTitle      Episode #1.125
originalTitle     Episode #1.125
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011217, dtype: object

(9,)

tconst                tt11835674
titleType              tvEpisode
primaryTitle       Episode #2.41
originalTitle      Episode #2.41
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                60
genres            News,Talk-Show
Name: 2011218, dtype: object

(9,)

tconst                  tt11835676
titleType                    short
primaryTitle      Moonlight Dreams
originalTitle     Moonlight Dreams
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  19
genres                 Drama,Short
Name: 2011219, dtype: object

(9,)

tconst                 tt11835678
titleType                 tvMovie
primaryTitle      Das Burgtheater
originalTitle     Das Burgtheater
isAdult                         0
startYear                    1963
endYear                        \N
runtimeMinutes                 50
genres                Documentary
Name: 2011220, dtype: object

(9,)

tconst                         tt1183567
titleType                      tvEpisode
primaryTitle               Episode #14.5
originalTitle              Episode #14.5
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres            Comedy,Music,Talk-Show
Name: 2011221, dtype: object

(9,)

tconst                                                   tt11835680
titleType                                                 tvEpisode
primaryTitle      Richard Jewell, Sonic, des films détestés (& d...
originalTitle     Richard Jewell, Sonic, des films détestés (& d...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2011222, dtype: object

(9,)

tconst                               tt11835682
titleType                                 video
primaryTitle      Anthrax: Kings Among Scotland
originalTitle     Anthrax: Kings Among Scotland
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                              129
genres                                    Music
Name: 2011223, dtype: object

(9,)

tconst                           tt11835684
titleType                         tvEpisode
primaryTitle      Episode dated 2 July 1956
originalTitle     Episode dated 2 July 1956
isAdult                                   0
startYear                              1956
endYear                                  \N
runtimeMinutes                           \N
genres                        Drama,Romance
Name: 2011224, dtype: object

(9,)

tconst                                             tt11835686
titleType                                           tvEpisode
primaryTitle      Top 10 Terminators from Each Movie: RANKED!
originalTitle     Top 10 Terminators from Each Movie: RANKED!
isAdult                                                     0
startYear                                                2019
endYear                                                    \N
runtimeMinutes                                             \N
genres                                       Comedy,Talk-Show
Name: 2011225, dtype: object

(9,)

tconst                   tt11835688
titleType                 tvEpisode
primaryTitle      The Dueling Cabos
originalTitle     The Dueling Cabos
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   21
genres                   Reality-TV
Name: 2011226, dtype: object

(9,)

tconst                  tt1183568
titleType               tvEpisode
primaryTitle      Aflevering 3570
originalTitle     Aflevering 3570
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2011227, dtype: object

(9,)

tconst                            tt11835690
titleType                          tvEpisode
primaryTitle      Episode dated 28 July 1967
originalTitle     Episode dated 28 July 1967
isAdult                                    0
startYear                               1967
endYear                                   \N
runtimeMinutes                            \N
genres                         Drama,Romance
Name: 2011228, dtype: object

(9,)

tconst                            tt11835692
titleType                          tvEpisode
primaryTitle      Episode dated 31 July 1967
originalTitle     Episode dated 31 July 1967
isAdult                                    0
startYear                               1967
endYear                                   \N
runtimeMinutes                            \N
genres                         Drama,Romance
Name: 2011229, dtype: object

(9,)

tconst                                tt11835694
titleType                              tvEpisode
primaryTitle      Episode dated 24 February 2020
originalTitle     Episode dated 24 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2011230, dtype: object

(9,)

tconst                                tt11835696
titleType                              tvEpisode
primaryTitle      Episode dated 25 February 2020
originalTitle     Episode dated 25 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2011231, dtype: object

(9,)

tconst                                tt11835698
titleType                              tvEpisode
primaryTitle      Episode dated 26 February 2020
originalTitle     Episode dated 26 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2011232, dtype: object

(9,)

tconst                   tt1183569
titleType                 tvSeries
primaryTitle      The Goode Family
originalTitle     The Goode Family
isAdult                          0
startYear                     2009
endYear                       2009
runtimeMinutes                  23
genres            Animation,Comedy
Name: 2011233, dtype: object

(9,)

tconst                                tt11835700
titleType                              tvEpisode
primaryTitle      Episode dated 27 February 2020
originalTitle     Episode dated 27 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2011234, dtype: object

(9,)

tconst                                tt11835702
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011235, dtype: object

(9,)

tconst              tt11835704
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011236, dtype: object

(9,)

tconst                   tt11835706
titleType                  tvSeries
primaryTitle           Extrablätter
originalTitle          Extrablätter
isAdult                           0
startYear                      1963
endYear                        1966
runtimeMinutes                   15
genres            Documentary,Short
Name: 2011237, dtype: object

(9,)

tconst             tt11835708
titleType               movie
primaryTitle          Mission
originalTitle         Mission
isAdult                     0
startYear                2021
endYear                    \N
runtimeMinutes             \N
genres            Documentary
Name: 2011238, dtype: object

(9,)

tconst                   tt1183570
titleType                tvEpisode
primaryTitle      Episode #1.15332
originalTitle     Episode #1.15332
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2011239, dtype: object

(9,)

tconst                      tt11835710
titleType                    tvEpisode
primaryTitle      Transport - Shopping
originalTitle     Transport - Shopping
isAdult                              0
startYear                         1982
endYear                             \N
runtimeMinutes                      \N
genres                          Family
Name: 2011240, dtype: object

(9,)

tconst                  tt11835712
titleType                tvEpisode
primaryTitle       Episode #1.1048
originalTitle      Episode #1.1048
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011241, dtype: object

(9,)

tconst                     tt11835714
titleType                       movie
primaryTitle             Dune Drifter
originalTitle            Dune Drifter
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     98
genres            Action,Drama,Sci-Fi
Name: 2011242, dtype: object

(9,)

tconst                  tt11835716
titleType                tvEpisode
primaryTitle       Episode #1.1049
originalTitle      Episode #1.1049
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011243, dtype: object

(9,)

tconst                  tt11835718
titleType                tvEpisode
primaryTitle       Episode #1.1050
originalTitle      Episode #1.1050
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011244, dtype: object

(9,)

tconst                   tt1183571
titleType                tvEpisode
primaryTitle      Episode #1.15333
originalTitle     Episode #1.15333
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2011245, dtype: object

(9,)

tconst                             tt11835720
titleType                           tvEpisode
primaryTitle                         Part One
originalTitle                        Part One
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Crime,Documentary
Name: 2011246, dtype: object

(9,)

tconst                                                tt11835722
titleType                                                tvMovie
primaryTitle      Krieg und Show: Die Schlacht am Little Bighorn
originalTitle     Krieg und Show: Die Schlacht am Little Bighorn
isAdult                                                        0
startYear                                                   2019
endYear                                                       \N
runtimeMinutes                                                52
genres                                               Documentary
Name: 2011247, dtype: object

(9,)

tconst                  tt11835724
titleType                tvEpisode
primaryTitle       Episode #1.1051
originalTitle      Episode #1.1051
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011248, dtype: object

(9,)

tconst                  tt11835726
titleType                tvEpisode
primaryTitle       Episode #1.1052
originalTitle      Episode #1.1052
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011249, dtype: object

(9,)

tconst                  tt11835728
titleType                tvEpisode
primaryTitle       Episode #1.1053
originalTitle      Episode #1.1053
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011250, dtype: object

(9,)

tconst                   tt1183572
titleType                tvEpisode
primaryTitle      Episode #1.15335
originalTitle     Episode #1.15335
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2011251, dtype: object

(9,)

tconst                  tt11835730
titleType                tvEpisode
primaryTitle       Episode #1.1054
originalTitle      Episode #1.1054
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011252, dtype: object

(9,)

tconst                  tt11835732
titleType                tvEpisode
primaryTitle       Episode #1.1055
originalTitle      Episode #1.1055
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011253, dtype: object

(9,)

tconst                                   tt11835734
titleType                                 tvEpisode
primaryTitle      Transport - Tractors and the Farm
originalTitle     Transport - Tractors and the Farm
isAdult                                           0
startYear                                      1982
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Family
Name: 2011254, dtype: object

(9,)

tconst                             tt11835736
titleType                           tvEpisode
primaryTitle                         Part Two
originalTitle                        Part Two
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Crime,Documentary
Name: 2011255, dtype: object

(9,)

tconst                            tt11835738
titleType                          tvEpisode
primaryTitle      Episode dated 26 June 2015
originalTitle     Episode dated 26 June 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2011256, dtype: object

(9,)

tconst                   tt1183573
titleType                tvEpisode
primaryTitle          Episode #2.5
originalTitle         Episode #2.5
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  60
genres            Comedy,Talk-Show
Name: 2011257, dtype: object

(9,)

tconst                            tt11835740
titleType                          tvEpisode
primaryTitle      Episode dated 29 June 2015
originalTitle     Episode dated 29 June 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2011258, dtype: object

(9,)

tconst                           tt11835742
titleType                         tvEpisode
primaryTitle      Episode dated 3 July 2015
originalTitle     Episode dated 3 July 2015
isAdult                                   0
startYear                              2015
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2011259, dtype: object

(9,)

tconst                           tt11835744
titleType                         tvEpisode
primaryTitle      Episode dated 6 July 2015
originalTitle     Episode dated 6 July 2015
isAdult                                   0
startYear                              2015
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2011260, dtype: object

(9,)

tconst                          tt11835746
titleType                            short
primaryTitle      Our children are burning
originalTitle     Our children are burning
isAdult                                  0
startYear                               \N
endYear                                 \N
runtimeMinutes                          \N
genres                         Drama,Short
Name: 2011261, dtype: object

(9,)

tconst                            tt11835748
titleType                          tvEpisode
primaryTitle      Episode dated 13 July 2015
originalTitle     Episode dated 13 July 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2011262, dtype: object

(9,)

tconst                                tt1183574
titleType                             tvEpisode
primaryTitle      Episode dated 8 February 2008
originalTitle     Episode dated 8 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                Talk-Show
Name: 2011263, dtype: object

(9,)

tconst                             tt11835750
titleType                           tvEpisode
primaryTitle                       Part Three
originalTitle                      Part Three
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Crime,Documentary
Name: 2011264, dtype: object

(9,)

tconst                         tt11835752
titleType                       tvEpisode
primaryTitle      Twenty Twenty: February
originalTitle     Twenty Twenty: February
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                        Documentary
Name: 2011265, dtype: object

(9,)

tconst                                tt11835754
titleType                              tvEpisode
primaryTitle      Transport - Cars and Balancing
originalTitle     Transport - Cars and Balancing
isAdult                                        0
startYear                                   1982
endYear                                       \N
runtimeMinutes                                \N
genres                                    Family
Name: 2011266, dtype: object

(9,)

tconst                             tt11835756
titleType                           tvEpisode
primaryTitle                        Part Four
originalTitle                       Part Four
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Crime,Documentary
Name: 2011267, dtype: object

(9,)

tconst            tt11835758
titleType          tvEpisode
primaryTitle         Squeeze
originalTitle        Squeeze
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            41
genres             Talk-Show
Name: 2011268, dtype: object

(9,)

tconst                tt1183575
titleType             tvEpisode
primaryTitle      Episode #4.18
originalTitle     Episode #4.18
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011269, dtype: object

(9,)

tconst             tt11835760
titleType             tvMovie
primaryTitle      I Am a Star
originalTitle     I Am a Star
isAdult                     0
startYear                2017
endYear                    \N
runtimeMinutes             \N
genres             Reality-TV
Name: 2011270, dtype: object

(9,)

tconst            tt11835762
titleType          tvEpisode
primaryTitle         Stalker
originalTitle        Stalker
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            41
genres             Talk-Show
Name: 2011271, dtype: object

(9,)

tconst                        tt11835764
titleType                      tvEpisode
primaryTitle           Live House CiRCLE
originalTitle          Live House CiRCLE
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                         3
genres            Animation,Comedy,Music
Name: 2011272, dtype: object

(9,)

tconst              tt11835766
titleType            tvEpisode
primaryTitle      Morning Star
originalTitle     Morning Star
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              41
genres               Talk-Show
Name: 2011273, dtype: object

(9,)

tconst                  tt11835768
titleType                tvEpisode
primaryTitle       Episode #1.1056
originalTitle      Episode #1.1056
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011274, dtype: object

(9,)

tconst                    tt1183576
titleType                 tvEpisode
primaryTitle           Episode #4.8
originalTitle          Episode #4.8
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres            Comedy,Reality-TV
Name: 2011275, dtype: object

(9,)

tconst                tt11835770
titleType              tvEpisode
primaryTitle      What We Become
originalTitle     What We Become
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                41
genres                 Talk-Show
Name: 2011276, dtype: object

(9,)

tconst                  tt11835772
titleType                tvEpisode
primaryTitle       Episode #1.1057
originalTitle      Episode #1.1057
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011277, dtype: object

(9,)

tconst                tt11835774
titleType              tvEpisode
primaryTitle      Fast Food Fuel
originalTitle     Fast Food Fuel
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                 Adventure
Name: 2011278, dtype: object

(9,)

tconst                  tt11835776
titleType                tvEpisode
primaryTitle       Episode #1.1058
originalTitle      Episode #1.1058
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011279, dtype: object

(9,)

tconst                        tt11835778
titleType                      tvEpisode
primaryTitle                  Think Tank
originalTitle                 Think Tank
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                         3
genres            Animation,Comedy,Music
Name: 2011280, dtype: object

(9,)

tconst                    tt1183577
titleType                 tvEpisode
primaryTitle           Episode #4.9
originalTitle          Episode #4.9
isAdult                           0
startYear                      2007
endYear                          \N
runtimeMinutes                   \N
genres            Comedy,Reality-TV
Name: 2011281, dtype: object

(9,)

tconst                         tt11835780
titleType                           short
primaryTitle      Submerge: Krag Conquest
originalTitle     Submerge: Krag Conquest
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                    Animation,Short
Name: 2011282, dtype: object

(9,)

tconst                  tt11835782
titleType                tvEpisode
primaryTitle       Episode #1.1059
originalTitle      Episode #1.1059
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011283, dtype: object

(9,)

tconst                  tt11835784
titleType                tvEpisode
primaryTitle       Episode #1.1060
originalTitle      Episode #1.1060
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011284, dtype: object

(9,)

tconst                  tt11835786
titleType                tvEpisode
primaryTitle       Episode #1.1061
originalTitle      Episode #1.1061
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011285, dtype: object

(9,)

tconst                  tt11835788
titleType                tvEpisode
primaryTitle       Episode #1.1062
originalTitle      Episode #1.1062
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011286, dtype: object

(9,)

tconst            tt1183578
titleType         tvEpisode
primaryTitle          Pilot
originalTitle         Pilot
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           22
genres               Comedy
Name: 2011287, dtype: object

(9,)

tconst                  tt11835790
titleType                tvEpisode
primaryTitle       Episode #1.1063
originalTitle      Episode #1.1063
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011288, dtype: object

(9,)

tconst                        tt11835792
titleType                      tvEpisode
primaryTitle                  Revolution
originalTitle                 Revolution
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                         3
genres            Animation,Comedy,Music
Name: 2011289, dtype: object

(9,)

tconst                  tt11835794
titleType                tvEpisode
primaryTitle       Episode #1.1064
originalTitle      Episode #1.1064
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011290, dtype: object

(9,)

tconst              tt11835796
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011291, dtype: object

(9,)

tconst                  tt11835798
titleType                tvEpisode
primaryTitle       Episode #1.1065
originalTitle      Episode #1.1065
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011292, dtype: object

(9,)

tconst            tt1183579
titleType         tvEpisode
primaryTitle            Old
originalTitle           Old
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           21
genres               Comedy
Name: 2011293, dtype: object

(9,)

tconst              tt11835800
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011294, dtype: object

(9,)

tconst              tt11835802
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011295, dtype: object

(9,)

tconst                             tt11835804
titleType                           tvEpisode
primaryTitle      Episode dated 23 April 2013
originalTitle     Episode dated 23 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2011296, dtype: object

(9,)

tconst                  tt11835806
titleType                tvEpisode
primaryTitle       Episode #1.1066
originalTitle      Episode #1.1066
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011297, dtype: object

(9,)

tconst              tt11835808
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011298, dtype: object

(9,)

tconst                             tt11835810
titleType                           tvEpisode
primaryTitle      Episode dated 24 April 2013
originalTitle     Episode dated 24 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2011299, dtype: object

(9,)

tconst                             tt11835812
titleType                           tvEpisode
primaryTitle      Episode dated 25 April 2013
originalTitle     Episode dated 25 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2011300, dtype: object

(9,)

tconst                               tt11835814
titleType                             tvEpisode
primaryTitle      Episode dated 26 October 1962
originalTitle     Episode dated 26 October 1962
isAdult                                       0
startYear                                  1962
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011301, dtype: object

(9,)

tconst                             tt11835816
titleType                           tvEpisode
primaryTitle      Episode dated 26 April 2013
originalTitle     Episode dated 26 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2011302, dtype: object

(9,)

tconst              tt11835818
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011303, dtype: object

(9,)

tconst            tt1183581
titleType         tvEpisode
primaryTitle        Respect
originalTitle       Respect
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           22
genres               Comedy
Name: 2011304, dtype: object

(9,)

tconst                  tt11835820
titleType                tvEpisode
primaryTitle       Episode #1.1067
originalTitle      Episode #1.1067
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011305, dtype: object

(9,)

tconst              tt11835822
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011306, dtype: object

(9,)

tconst                             tt11835824
titleType                           tvEpisode
primaryTitle      Episode dated 29 April 2013
originalTitle     Episode dated 29 April 2013
isAdult                                     0
startYear                                2013
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2011307, dtype: object

(9,)

tconst              tt11835826
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011308, dtype: object

(9,)

tconst              tt11835828
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2011309, dtype: object

(9,)

tconst            tt1183582
titleType         tvEpisode
primaryTitle         Dating
originalTitle        Dating
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           21
genres               Comedy
Name: 2011310, dtype: object

(9,)

tconst              tt11835830
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011311, dtype: object

(9,)

tconst              tt11835832
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2019
endYear                     \N
runtimeMinutes              \N
genres                    News
Name: 2011312, dtype: object

(9,)

tconst               tt11835834
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2011313, dtype: object

(9,)

tconst              tt11835836
titleType            tvEpisode
primaryTitle      Episode #1.1
originalTitle     Episode #1.1
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011314, dtype: object

(9,)

tconst               tt11835838
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2011315, dtype: object

(9,)

tconst            tt1183583
titleType         tvEpisode
primaryTitle          Money
originalTitle         Money
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           22
genres               Comedy
Name: 2011316, dtype: object

(9,)

tconst               tt11835840
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                     News
Name: 2011317, dtype: object

(9,)

tconst              tt11835842
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011318, dtype: object

(9,)

tconst                  tt11835844
titleType                tvEpisode
primaryTitle       Episode #1.1068
originalTitle      Episode #1.1068
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011319, dtype: object

(9,)

tconst                             tt11835846
titleType                           tvEpisode
primaryTitle                Henry Clay Conner
originalTitle               Henry Clay Conner
isAdult                                     0
startYear                                1956
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2011320, dtype: object

(9,)

tconst                             tt11835848
titleType                           tvEpisode
primaryTitle      Episode dated 14 April 2009
originalTitle     Episode dated 14 April 2009
isAdult                                     0
startYear                                2009
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2011321, dtype: object

(9,)

tconst                  tt1183584
titleType               tvEpisode
primaryTitle      Episode #12.108
originalTitle     Episode #12.108
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                  Talk-Show
Name: 2011322, dtype: object

(9,)

tconst              tt11835850
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011323, dtype: object

(9,)

tconst                tt11835852
titleType                  short
primaryTitle      Selbstportrait
originalTitle     Selbstportrait
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                17
genres                     Short
Name: 2011324, dtype: object

(9,)

tconst                  tt11835854
titleType                tvEpisode
primaryTitle       Episode #1.1069
originalTitle      Episode #1.1069
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011325, dtype: object

(9,)

tconst              tt11835856
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres             Crime,Drama
Name: 2011326, dtype: object

(9,)

tconst                            tt11835858
titleType                            tvMovie
primaryTitle      Seinerzeit in unserer Zeit
originalTitle     Seinerzeit in unserer Zeit
isAdult                                    0
startYear                               1963
endYear                                   \N
runtimeMinutes                            22
genres                                    \N
Name: 2011327, dtype: object

(9,)

tconst                            tt1183585
titleType                         tvEpisode
primaryTitle      Episode dated 4 June 1961
originalTitle     Episode dated 4 June 1961
isAdult                                   0
startYear                              1961
endYear                                  \N
runtimeMinutes                           \N
genres                       News,Talk-Show
Name: 2011328, dtype: object

(9,)

tconst                        tt11835860
titleType                      tvEpisode
primaryTitle           Rock n' Roll Baby
originalTitle          Rock n' Roll Baby
isAdult                                0
startYear                           2018
endYear                               \N
runtimeMinutes                         3
genres            Animation,Comedy,Music
Name: 2011329, dtype: object

(9,)

tconst                       tt11835862
titleType                     tvEpisode
primaryTitle      Nature's Cleanup Crew
originalTitle     Nature's Cleanup Crew
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres                      Documentary
Name: 2011330, dtype: object

(9,)

tconst                  tt11835864
titleType                tvEpisode
primaryTitle       Episode #1.1070
originalTitle      Episode #1.1070
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011331, dtype: object

(9,)

tconst                  tt11835866
titleType                tvEpisode
primaryTitle       Episode #1.1071
originalTitle      Episode #1.1071
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011332, dtype: object

(9,)

tconst                                    tt11835868
titleType                                      video
primaryTitle      Vaya Con Dios: Don't Cry for Louie
originalTitle     Vaya Con Dios: Don't Cry for Louie
isAdult                                            0
startYear                                       1988
endYear                                           \N
runtimeMinutes                                     3
genres                                   Music,Short
Name: 2011333, dtype: object

(9,)

tconst                    tt1183586
titleType                  tvSeries
primaryTitle            Meine Liebe
originalTitle           Meine Liebe
isAdult                           0
startYear                      2004
endYear                        2005
runtimeMinutes                   \N
genres            Animation,Fantasy
Name: 2011334, dtype: object

(9,)

tconst                                      tt11835870
titleType                                    tvEpisode
primaryTitle      Pastel*Palettes' Swimsuit Commercial
originalTitle     Pastel*Palettes' Swimsuit Commercial
isAdult                                              0
startYear                                         2018
endYear                                             \N
runtimeMinutes                                       3
genres                          Animation,Comedy,Music
Name: 2011335, dtype: object

(9,)

tconst                             tt11835872
titleType                           tvEpisode
primaryTitle                     Ruth Stromer
originalTitle                    Ruth Stromer
isAdult                                     0
startYear                                1956
endYear                                    \N
runtimeMinutes                             \N
genres            Biography,Family,Reality-TV
Name: 2011336, dtype: object

(9,)

tconst                  tt11835874
titleType                tvEpisode
primaryTitle       Episode #1.1072
originalTitle      Episode #1.1072
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011337, dtype: object

(9,)

tconst                  tt11835876
titleType                tvEpisode
primaryTitle       Episode #1.1073
originalTitle      Episode #1.1073
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011338, dtype: object

(9,)

tconst                                              tt11835878
titleType                                            tvEpisode
primaryTitle      Abominable Snowman and Other Holiday Stories
originalTitle     Abominable Snowman and Other Holiday Stories
isAdult                                                      0
startYear                                                 2019
endYear                                                     \N
runtimeMinutes                                              85
genres                                        Animation,Family
Name: 2011339, dtype: object

(9,)

tconst               tt1183587
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2011340, dtype: object

(9,)

tconst                  tt11835880
titleType                tvEpisode
primaryTitle       Episode #1.1074
originalTitle      Episode #1.1074
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011341, dtype: object

(9,)

tconst                                tt11835882
titleType                              tvEpisode
primaryTitle      Top 10 Comic-Con 2019 Trailers
originalTitle     Top 10 Comic-Con 2019 Trailers
isAdult                                        0
startYear                                   2019
endYear                                       \N
runtimeMinutes                                \N
genres                          Comedy,Talk-Show
Name: 2011342, dtype: object

(9,)

tconst                  tt11835884
titleType                tvEpisode
primaryTitle       Episode #1.1075
originalTitle      Episode #1.1075
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011343, dtype: object

(9,)

tconst                               tt11835886
titleType                             tvEpisode
primaryTitle      Episode dated 22 January 2018
originalTitle     Episode dated 22 January 2018
isAdult                                       0
startYear                                  2018
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011344, dtype: object

(9,)

tconst                                      tt11835888
titleType                                    tvEpisode
primaryTitle      Bangladesh v Zimbabwe: Test 1: Day 1
originalTitle     Bangladesh v Zimbabwe: Test 1: Day 1
isAdult                                              0
startYear                                         2020
endYear                                             \N
runtimeMinutes                                      \N
genres                                           Sport
Name: 2011345, dtype: object

(9,)

tconst                         tt1183588
titleType                      tvEpisode
primaryTitle      When a Child Is Bought
originalTitle     When a Child Is Bought
isAdult                                0
startYear                           2006
endYear                               \N
runtimeMinutes                        \N
genres                     Drama,Romance
Name: 2011346, dtype: object

(9,)

tconst                           tt11835890
titleType                         tvEpisode
primaryTitle      Welcome to Michelle Land!
originalTitle     Welcome to Michelle Land!
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                            3
genres               Animation,Comedy,Music
Name: 2011347, dtype: object

(9,)

tconst                         tt11835892
titleType                           video
primaryTitle      Rock N Roll Catastrophe
originalTitle     Rock N Roll Catastrophe
isAdult                                 0
startYear                            2010
endYear                                \N
runtimeMinutes                          3
genres                        Music,Short
Name: 2011348, dtype: object

(9,)

tconst                             tt11835894
titleType                           tvEpisode
primaryTitle      Episode dated 17 April 1970
originalTitle     Episode dated 17 April 1970
isAdult                                     0
startYear                                1970
endYear                                    \N
runtimeMinutes                             \N
genres                          Drama,Romance
Name: 2011349, dtype: object

(9,)

tconst                     tt11835896
titleType                   tvEpisode
primaryTitle            Episode #6.13
originalTitle           Episode #6.13
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2011350, dtype: object

(9,)

tconst             tt11835898
titleType               short
primaryTitle           Teresa
originalTitle          Teresa
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes              9
genres            Drama,Short
Name: 2011351, dtype: object

(9,)

tconst                                tt1183589
titleType                             tvEpisode
primaryTitle      Episode dated 8 February 2008
originalTitle     Episode dated 8 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011352, dtype: object

(9,)

tconst                               tt11835900
titleType                             tvEpisode
primaryTitle      Episode dated 31 October 1962
originalTitle     Episode dated 31 October 1962
isAdult                                       0
startYear                                  1962
endYear                                      \N
runtimeMinutes                               \N
genres                            Drama,Romance
Name: 2011353, dtype: object

(9,)

tconst                                                   tt11835902
titleType                                                   tvMovie
primaryTitle      Ludwig Erhard - Ein Porträt des neuen Bundeska...
originalTitle     Ludwig Erhard - Ein Porträt des neuen Bundeska...
isAdult                                                           0
startYear                                                      1963
endYear                                                          \N
runtimeMinutes                                                   45
genres                                                  Documentary
Name: 2011354, dtype: object

(9,)

tconst              tt11835904
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1993
endYear                     \N
runtimeMinutes              \N
genres               Adventure
Name: 2011355, dtype: object

(9,)

tconst                                tt1183590
titleType                             tvEpisode
primaryTitle      Episode dated 24 October 2006
originalTitle     Episode dated 24 October 2006
isAdult                                       0
startYear                                  2006
endYear                                      \N
runtimeMinutes                               \N
genres                           News,Talk-Show
Name: 2011356, dtype: object

(9,)

tconst            tt11835910
titleType              movie
primaryTitle       Mukkaddar
originalTitle      Mukkaddar
isAdult                    0
startYear               2021
endYear                   \N
runtimeMinutes            \N
genres               Romance
Name: 2011357, dtype: object

(9,)

tconst                     tt11835912
titleType                   tvEpisode
primaryTitle            Episode #6.14
originalTitle           Episode #6.14
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2011358, dtype: object

(9,)

tconst                                tt11835914
titleType                              tvEpisode
primaryTitle      Episode dated 17 February 2020
originalTitle     Episode dated 17 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011359, dtype: object

(9,)

tconst                    tt11835916
titleType                  tvEpisode
primaryTitle      Only Crypto: Day 4
originalTitle     Only Crypto: Day 4
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2011360, dtype: object

(9,)

tconst                                tt11835918
titleType                              tvEpisode
primaryTitle      Episode dated 18 February 2020
originalTitle     Episode dated 18 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011361, dtype: object

(9,)

tconst                                tt1183591
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               60
genres                           News,Talk-Show
Name: 2011362, dtype: object

(9,)

tconst                                tt11835920
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011363, dtype: object

(9,)

tconst                                tt11835922
titleType                              tvEpisode
primaryTitle      Episode dated 20 February 2020
originalTitle     Episode dated 20 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011364, dtype: object

(9,)

tconst                     tt11835924
titleType                   tvEpisode
primaryTitle            Episode #6.15
originalTitle           Episode #6.15
isAdult                             0
startYear                        2020
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2011365, dtype: object

(9,)

tconst             tt11835926
titleType            tvSeries
primaryTitle      Chadarangam
originalTitle     Chadarangam
isAdult                     0
startYear                2020
endYear                  2020
runtimeMinutes             \N
genres                  Drama
Name: 2011366, dtype: object

(9,)

tconst                            tt11835928
titleType                          tvEpisode
primaryTitle                 Gekka no kessen
originalTitle                Gekka no kessen
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres            Action,Adventure,Animation
Name: 2011367, dtype: object

(9,)

tconst                                tt1183592
titleType                             tvEpisode
primaryTitle      Episode dated 8 February 2008
originalTitle     Episode dated 8 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               60
genres                           News,Talk-Show
Name: 2011368, dtype: object

(9,)

tconst                  tt11835930
titleType                tvEpisode
primaryTitle         Episode #4.24
originalTitle        Episode #4.24
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2011369, dtype: object

(9,)

tconst                               tt11835932
titleType                             tvEpisode
primaryTitle      Episode dated 20 October 1970
originalTitle     Episode dated 20 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011370, dtype: object

(9,)

tconst                  tt11835934
titleType                tvEpisode
primaryTitle         Episode #4.25
originalTitle        Episode #4.25
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2011371, dtype: object

(9,)

tconst                            tt11835936
titleType                          tvEpisode
primaryTitle      Episode dated 27 June 2017
originalTitle     Episode dated 27 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2011372, dtype: object

(9,)

tconst                tt11835938
titleType                  short
primaryTitle      Namaiki Zakari
originalTitle     Namaiki Zakari
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                11
genres             Romance,Short
Name: 2011373, dtype: object

(9,)

tconst               tt1183593
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2003
endYear                     \N
runtimeMinutes              \N
genres               Adventure
Name: 2011374, dtype: object

(9,)

tconst                            tt11835940
titleType                          tvEpisode
primaryTitle      Episode dated 30 June 2017
originalTitle     Episode dated 30 June 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2011375, dtype: object

(9,)

tconst                           tt11835942
titleType                         tvEpisode
primaryTitle      Episode dated 3 July 2017
originalTitle     Episode dated 3 July 2017
isAdult                                   0
startYear                              2017
endYear                                  \N
runtimeMinutes                           \N
genres                                   \N
Name: 2011376, dtype: object

(9,)

tconst               tt11835944
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2011377, dtype: object

(9,)

tconst                            tt11835946
titleType                          tvEpisode
primaryTitle      Episode dated 26 July 2017
originalTitle     Episode dated 26 July 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2011378, dtype: object

(9,)

tconst                            tt11835948
titleType                          tvEpisode
primaryTitle      Episode dated 27 July 2017
originalTitle     Episode dated 27 July 2017
isAdult                                    0
startYear                               2017
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2011379, dtype: object

(9,)

tconst                                tt1183594
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                     News,Sport,Talk-Show
Name: 2011380, dtype: object

(9,)

tconst                      tt11835950
titleType                     tvSeries
primaryTitle       Mega Sports Weekend
originalTitle      Mega Sports Weekend
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      45
genres            News,Sport,Talk-Show
Name: 2011381, dtype: object

(9,)

tconst               tt11835952
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011382, dtype: object

(9,)

tconst                  tt11835954
titleType                tvEpisode
primaryTitle       Episode #1.1076
originalTitle      Episode #1.1076
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011383, dtype: object

(9,)

tconst               tt11835956
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011384, dtype: object

(9,)

tconst                  tt11835958
titleType                tvEpisode
primaryTitle       Episode #1.1077
originalTitle      Episode #1.1077
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011385, dtype: object

(9,)

tconst                 tt1183595
titleType              tvEpisode
primaryTitle      Episode #2.104
originalTitle     Episode #2.104
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2011386, dtype: object

(9,)

tconst               tt11835960
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011387, dtype: object

(9,)

tconst                  tt11835962
titleType                tvEpisode
primaryTitle       Episode #1.1078
originalTitle      Episode #1.1078
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011388, dtype: object

(9,)

tconst               tt11835964
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011389, dtype: object

(9,)

tconst                  tt11835966
titleType                tvEpisode
primaryTitle       Episode #1.1079
originalTitle      Episode #1.1079
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011390, dtype: object

(9,)

tconst                                       tt11835968
titleType                                     tvEpisode
primaryTitle      Samanta y Gracia discuten por Julieta
originalTitle     Samanta y Gracia discuten por Julieta
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Drama
Name: 2011391, dtype: object

(9,)

tconst                tt1183596
titleType             tvEpisode
primaryTitle      Episode #3.22
originalTitle     Episode #3.22
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011392, dtype: object

(9,)

tconst                           tt11835970
titleType                             short
primaryTitle      The Black History Project
originalTitle     The Black History Project
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                            5
genres                         Family,Short
Name: 2011393, dtype: object

(9,)

tconst                 tt11835972
titleType                   movie
primaryTitle      Pride & Protest
originalTitle     Pride & Protest
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 90
genres                Documentary
Name: 2011394, dtype: object

(9,)

tconst              tt11835974
titleType                movie
primaryTitle      Kinkan-shoku
originalTitle     Kinkan-shoku
isAdult                      0
startYear                 1934
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011395, dtype: object

(9,)

tconst                                            tt11835976
titleType                                          tvEpisode
primaryTitle      Samanta decidió irse a Santiago con Gracia
originalTitle     Samanta decidió irse a Santiago con Gracia
isAdult                                                    0
startYear                                               2020
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                 Drama
Name: 2011396, dtype: object

(9,)

tconst            tt11835978
titleType          tvEpisode
primaryTitle      226. Bolum
originalTitle     226. Bolum
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2011397, dtype: object

(9,)

tconst                  tt1183597
titleType               tvEpisode
primaryTitle       Episode #37.19
originalTitle      Episode #37.19
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres            Game-Show,Sport
Name: 2011398, dtype: object

(9,)

tconst               tt11835980
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011399, dtype: object

(9,)

tconst               tt11835982
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011400, dtype: object

(9,)

tconst               tt11835984
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011401, dtype: object

(9,)

tconst               tt11835986
titleType                 video
primaryTitle      Prem No Nasho
originalTitle     Prem No Nasho
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres              Music,Short
Name: 2011402, dtype: object

(9,)

tconst               tt11835988
titleType             tvEpisode
primaryTitle      Episode #1.42
originalTitle     Episode #1.42
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011403, dtype: object

(9,)

tconst                tt1183598
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                  1991
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011404, dtype: object

(9,)

tconst               tt11835990
titleType             tvEpisode
primaryTitle      Episode #1.43
originalTitle     Episode #1.43
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011405, dtype: object

(9,)

tconst                    tt11835992
titleType                  tvEpisode
primaryTitle           Episode #5.21
originalTitle          Episode #5.21
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011406, dtype: object

(9,)

tconst                               tt11835994
titleType                                 video
primaryTitle      Straight: A Conversion Comedy
originalTitle     Straight: A Conversion Comedy
isAdult                                       0
startYear                                  2002
endYear                                      \N
runtimeMinutes                               99
genres                                   Comedy
Name: 2011407, dtype: object

(9,)

tconst                    tt11835996
titleType                  tvEpisode
primaryTitle           Episode #5.23
originalTitle          Episode #5.23
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011408, dtype: object

(9,)

tconst                    tt11835998
titleType                  tvEpisode
primaryTitle           Episode #5.22
originalTitle          Episode #5.22
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011409, dtype: object

(9,)

tconst                                tt1183599
titleType                             tvEpisode
primaryTitle      Episode dated 8 February 2008
originalTitle     Episode dated 8 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                      Biography,Talk-Show
Name: 2011410, dtype: object

(9,)

tconst                             tt11836000
titleType                           tvEpisode
primaryTitle      La última traición de Nancy
originalTitle     La última traición de Nancy
isAdult                                     0
startYear                                2020
endYear                                    \N
runtimeMinutes                             \N
genres                                  Drama
Name: 2011411, dtype: object

(9,)

tconst                    tt11836002
titleType                  tvEpisode
primaryTitle           Episode #5.24
originalTitle          Episode #5.24
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011412, dtype: object

(9,)

tconst                    tt11836004
titleType                  tvEpisode
primaryTitle           Episode #5.25
originalTitle          Episode #5.25
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011413, dtype: object

(9,)

tconst                    tt11836006
titleType                  tvEpisode
primaryTitle           Episode #5.26
originalTitle          Episode #5.26
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011414, dtype: object

(9,)

tconst                    tt11836008
titleType                  tvEpisode
primaryTitle           Episode #5.27
originalTitle          Episode #5.27
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011415, dtype: object

(9,)

tconst                                tt1183600
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                          Sport,Talk-Show
Name: 2011416, dtype: object

(9,)

tconst                    tt11836010
titleType                  tvEpisode
primaryTitle           Episode #5.28
originalTitle          Episode #5.28
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011417, dtype: object

(9,)

tconst               tt11836012
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011418, dtype: object

(9,)

tconst                    tt11836014
titleType                  tvEpisode
primaryTitle           Episode #5.29
originalTitle          Episode #5.29
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011419, dtype: object

(9,)

tconst                    tt11836016
titleType                  tvEpisode
primaryTitle           Episode #5.30
originalTitle          Episode #5.30
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011420, dtype: object

(9,)

tconst               tt11836018
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011421, dtype: object

(9,)

tconst               tt1183601
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2000
endYear                     \N
runtimeMinutes              22
genres                  Comedy
Name: 2011422, dtype: object

(9,)

tconst                    tt11836020
titleType                  tvEpisode
primaryTitle           Episode #5.31
originalTitle          Episode #5.31
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011423, dtype: object

(9,)

tconst                    tt11836022
titleType                  tvEpisode
primaryTitle           Episode #5.32
originalTitle          Episode #5.32
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011424, dtype: object

(9,)

tconst                    tt11836024
titleType                  tvEpisode
primaryTitle           Episode #5.33
originalTitle          Episode #5.33
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011425, dtype: object

(9,)

tconst                    tt11836026
titleType                  tvEpisode
primaryTitle           Episode #5.34
originalTitle          Episode #5.34
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011426, dtype: object

(9,)

tconst                    tt11836028
titleType                  tvEpisode
primaryTitle           Episode #5.35
originalTitle          Episode #5.35
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011427, dtype: object

(9,)

tconst                                tt1183602
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2008
originalTitle     Episode dated 7 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011428, dtype: object

(9,)

tconst               tt11836030
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011429, dtype: object

(9,)

tconst                    tt11836032
titleType                  tvEpisode
primaryTitle           Episode #5.36
originalTitle          Episode #5.36
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011430, dtype: object

(9,)

tconst                    tt11836034
titleType                  tvEpisode
primaryTitle           Episode #5.37
originalTitle          Episode #5.37
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011431, dtype: object

(9,)

tconst                    tt11836036
titleType                  tvEpisode
primaryTitle           Episode #5.38
originalTitle          Episode #5.38
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011432, dtype: object

(9,)

tconst                    tt11836038
titleType                  tvEpisode
primaryTitle           Episode #5.39
originalTitle          Episode #5.39
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011433, dtype: object

(9,)

tconst                   tt1183603
titleType                tvEpisode
primaryTitle         Episode #1.10
originalTitle        Episode #1.10
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2011434, dtype: object

(9,)

tconst                                                   tt11836040
titleType                                                 tvEpisode
primaryTitle      Hunter x Hunter #57 REACTION!! "Initiative × A...
originalTitle     Hunter x Hunter #57 REACTION!! "Initiative × A...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   22
genres                                                    Talk-Show
Name: 2011435, dtype: object

(9,)

tconst                    tt11836042
titleType                  tvEpisode
primaryTitle           Episode #5.40
originalTitle          Episode #5.40
isAdult                            0
startYear                       1998
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011436, dtype: object

(9,)

tconst               tt11836044
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011437, dtype: object

(9,)

tconst                 tt11836046
titleType               tvEpisode
primaryTitle      Pamilya Mapalad
originalTitle     Pamilya Mapalad
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2011438, dtype: object

(9,)

tconst               tt11836048
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011439, dtype: object

(9,)

tconst                   tt1183604
titleType                tvEpisode
primaryTitle          Episode #1.9
originalTitle         Episode #1.9
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2011440, dtype: object

(9,)

tconst                                                   tt11836052
titleType                                                 tvEpisode
primaryTitle      Top 10 Awesome Anime Moments Ruined by Terribl...
originalTitle     Top 10 Awesome Anime Moments Ruined by Terribl...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                             Comedy,Talk-Show
Name: 2011441, dtype: object

(9,)

tconst              tt11836054
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2011442, dtype: object

(9,)

tconst              tt11836056
titleType            tvEpisode
primaryTitle      Episode #2.7
originalTitle     Episode #2.7
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2011443, dtype: object

(9,)

tconst              tt11836058
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2011444, dtype: object

(9,)

tconst                               tt1183605
titleType                            tvEpisode
primaryTitle      Episode dated 8 October 2007
originalTitle     Episode dated 8 October 2007
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                    Comedy,Drama,Romance
Name: 2011445, dtype: object

(9,)

tconst             tt11836060
titleType               short
primaryTitle      Happy Holly
originalTitle     Happy Holly
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2011446, dtype: object

(9,)

tconst              tt11836062
titleType            tvEpisode
primaryTitle      Episode #2.9
originalTitle     Episode #2.9
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres                 Romance
Name: 2011447, dtype: object

(9,)

tconst               tt11836064
titleType             tvEpisode
primaryTitle      Episode #2.10
originalTitle     Episode #2.10
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011448, dtype: object

(9,)

tconst                                                 tt11836066
titleType                                               tvEpisode
primaryTitle      Chuck 3x18 REACTION!! "Chuck Versus the Subway"
originalTitle     Chuck 3x18 REACTION!! "Chuck Versus the Subway"
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 19
genres                                                  Talk-Show
Name: 2011449, dtype: object

(9,)

tconst               tt11836068
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011450, dtype: object

(9,)

tconst                               tt1183606
titleType                            tvEpisode
primaryTitle      Episode dated 9 October 2007
originalTitle     Episode dated 9 October 2007
isAdult                                      0
startYear                                 2007
endYear                                     \N
runtimeMinutes                              \N
genres                    Comedy,Drama,Romance
Name: 2011451, dtype: object

(9,)

tconst               tt11836070
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011452, dtype: object

(9,)

tconst               tt11836072
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011453, dtype: object

(9,)

tconst               tt11836074
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011454, dtype: object

(9,)

tconst               tt11836076
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011455, dtype: object

(9,)

tconst                                 tt11836078
titleType                               tvEpisode
primaryTitle      Top 10 Fairy Tale Horror Movies
originalTitle     Top 10 Fairy Tale Horror Movies
isAdult                                         0
startYear                                    2020
endYear                                        \N
runtimeMinutes                                 \N
genres                           Comedy,Talk-Show
Name: 2011456, dtype: object

(9,)

tconst               tt1183607
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres              Reality-TV
Name: 2011457, dtype: object

(9,)

tconst               tt11836080
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011458, dtype: object

(9,)

tconst               tt11836082
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011459, dtype: object

(9,)

tconst               tt11836084
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011460, dtype: object

(9,)

tconst               tt11836086
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011461, dtype: object

(9,)

tconst            tt11836088
titleType              short
primaryTitle        Actality
originalTitle       Actality
isAdult                    0
startYear                 \N
endYear                   \N
runtimeMinutes            20
genres                 Short
Name: 2011462, dtype: object

(9,)

tconst                tt1183608
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  1996
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2011463, dtype: object

(9,)

tconst                                       tt11836090
titleType                                     tvEpisode
primaryTitle      Leonardo volvió a atormentar a Eliana
originalTitle     Leonardo volvió a atormentar a Eliana
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                                            Drama
Name: 2011464, dtype: object

(9,)

tconst               tt11836092
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011465, dtype: object

(9,)

tconst               tt11836094
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011466, dtype: object

(9,)

tconst               tt11836096
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011467, dtype: object

(9,)

tconst               tt11836098
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011468, dtype: object

(9,)

tconst                tt1183609
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  1996
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2011469, dtype: object

(9,)

tconst               tt11836100
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011470, dtype: object

(9,)

tconst               tt11836102
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011471, dtype: object

(9,)

tconst               tt11836104
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011472, dtype: object

(9,)

tconst               tt11836106
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011473, dtype: object

(9,)

tconst               tt11836108
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011474, dtype: object

(9,)

tconst                tt1183610
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  1996
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2011475, dtype: object

(9,)

tconst               tt11836110
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011476, dtype: object

(9,)

tconst                             tt11836112
titleType                           tvEpisode
primaryTitle      Episode dated 4 August 2017
originalTitle     Episode dated 4 August 2017
isAdult                                     0
startYear                                2017
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2011477, dtype: object

(9,)

tconst               tt11836114
titleType             tvEpisode
primaryTitle      Mice Business
originalTitle     Mice Business
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2011478, dtype: object

(9,)

tconst               tt11836116
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011479, dtype: object

(9,)

tconst                              tt11836118
titleType                            tvEpisode
primaryTitle      Episode dated 30 August 2017
originalTitle     Episode dated 30 August 2017
isAdult                                      0
startYear                                 2017
endYear                                     \N
runtimeMinutes                              \N
genres                                      \N
Name: 2011480, dtype: object

(9,)

tconst                tt1183611
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  1996
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2011481, dtype: object

(9,)

tconst             tt11836120
titleType               short
primaryTitle           Echoes
originalTitle          Echoes
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres            Drama,Short
Name: 2011482, dtype: object

(9,)

tconst                 tt11836122
titleType               tvEpisode
primaryTitle      Episode #1.2775
originalTitle     Episode #1.2775
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2011483, dtype: object

(9,)

tconst                tt11836124
titleType              tvEpisode
primaryTitle      Episode #1.181
originalTitle     Episode #1.181
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011484, dtype: object

(9,)

tconst                                 tt11836126
titleType                               tvEpisode
primaryTitle      Episode dated 20 September 2017
originalTitle     Episode dated 20 September 2017
isAdult                                         0
startYear                                    2017
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2011485, dtype: object

(9,)

tconst                               tt11836128
titleType                             tvEpisode
primaryTitle      Episode dated 20 October 2017
originalTitle     Episode dated 20 October 2017
isAdult                                       0
startYear                                  2017
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011486, dtype: object

(9,)

tconst               tt1183612
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2011487, dtype: object

(9,)

tconst                 tt11836130
titleType               tvEpisode
primaryTitle      Episode #1.2776
originalTitle     Episode #1.2776
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2011488, dtype: object

(9,)

tconst                                tt11836132
titleType                              tvEpisode
primaryTitle      Episode dated 10 November 2017
originalTitle     Episode dated 10 November 2017
isAdult                                        0
startYear                                   2017
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011489, dtype: object

(9,)

tconst                                tt11836134
titleType                              tvEpisode
primaryTitle      Episode dated 21 February 2020
originalTitle     Episode dated 21 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011490, dtype: object

(9,)

tconst                 tt11836136
titleType               tvEpisode
primaryTitle      Episode #1.2777
originalTitle     Episode #1.2777
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2011491, dtype: object

(9,)

tconst                tt11836138
titleType              tvEpisode
primaryTitle      Episode #1.182
originalTitle     Episode #1.182
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011492, dtype: object

(9,)

tconst               tt1183613
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 1996
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2011493, dtype: object

(9,)

tconst                                tt11836140
titleType                              tvEpisode
primaryTitle      Episode dated 10 February 2020
originalTitle     Episode dated 10 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011494, dtype: object

(9,)

tconst                tt11836142
titleType              tvEpisode
primaryTitle      Episode #1.184
originalTitle     Episode #1.184
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011495, dtype: object

(9,)

tconst                tt11836144
titleType              tvEpisode
primaryTitle      Episode #1.183
originalTitle     Episode #1.183
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011496, dtype: object

(9,)

tconst                 tt11836146
titleType               tvEpisode
primaryTitle      Episode #1.2778
originalTitle     Episode #1.2778
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2011497, dtype: object

(9,)

tconst                                tt11836148
titleType                              tvEpisode
primaryTitle      Episode dated 11 February 2020
originalTitle     Episode dated 11 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011498, dtype: object

(9,)

tconst                   tt1183614
titleType                tvEpisode
primaryTitle         Episode #2.15
originalTitle        Episode #2.15
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Talk-Show
Name: 2011499, dtype: object

(9,)

tconst                                tt11836150
titleType                              tvEpisode
primaryTitle      Episode dated 12 February 2020
originalTitle     Episode dated 12 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011500, dtype: object

(9,)

tconst                tt11836152
titleType              tvEpisode
primaryTitle      Episode #1.185
originalTitle     Episode #1.185
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011501, dtype: object

(9,)

tconst                tt11836154
titleType              tvEpisode
primaryTitle      Episode #1.187
originalTitle     Episode #1.187
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011502, dtype: object

(9,)

tconst                                tt11836156
titleType                              tvEpisode
primaryTitle      Episode dated 13 February 2020
originalTitle     Episode dated 13 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011503, dtype: object

(9,)

tconst                tt11836158
titleType              tvEpisode
primaryTitle      Episode #1.188
originalTitle     Episode #1.188
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011504, dtype: object

(9,)

tconst                 tt1183615
titleType              tvEpisode
primaryTitle      Episode #3.101
originalTitle     Episode #3.101
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                        \N
Name: 2011505, dtype: object

(9,)

tconst                tt11836160
titleType              tvEpisode
primaryTitle      Episode #1.189
originalTitle     Episode #1.189
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011506, dtype: object

(9,)

tconst                tt11836162
titleType              tvEpisode
primaryTitle      Episode #1.186
originalTitle     Episode #1.186
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011507, dtype: object

(9,)

tconst                 tt11836164
titleType               tvEpisode
primaryTitle      Episode #1.2779
originalTitle     Episode #1.2779
isAdult                         0
startYear                    2016
endYear                        \N
runtimeMinutes                 \N
genres                      Drama
Name: 2011508, dtype: object

(9,)

tconst                                tt11836166
titleType                              tvEpisode
primaryTitle      Episode dated 14 February 2020
originalTitle     Episode dated 14 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2011509, dtype: object

(9,)

tconst                               tt11836168
titleType                             tvEpisode
primaryTitle      Episode dated 3 February 2020
originalTitle     Episode dated 3 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011510, dtype: object

(9,)

tconst                           tt1183616
titleType                     tvMiniSeries
primaryTitle      Teni ischezayut v polden
originalTitle     Teni ischezayut v polden
isAdult                                  0
startYear                             1971
endYear                                 \N
runtimeMinutes                         516
genres                       Drama,History
Name: 2011511, dtype: object

(9,)

tconst                tt11836170
titleType              tvEpisode
primaryTitle      Episode #1.190
originalTitle     Episode #1.190
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011512, dtype: object

(9,)

tconst                tt11836172
titleType              tvEpisode
primaryTitle      Episode #1.191
originalTitle     Episode #1.191
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011513, dtype: object

(9,)

tconst                               tt11836174
titleType                             tvEpisode
primaryTitle      Episode dated 4 February 2020
originalTitle     Episode dated 4 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011514, dtype: object

(9,)

tconst                               tt11836176
titleType                             tvEpisode
primaryTitle      Episode dated 5 February 2020
originalTitle     Episode dated 5 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011515, dtype: object

(9,)

tconst                               tt11836178
titleType                             tvEpisode
primaryTitle      Episode dated 6 February 2020
originalTitle     Episode dated 6 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011516, dtype: object

(9,)

tconst                      tt1183617
titleType                   tvEpisode
primaryTitle           Episode #13.61
originalTitle          Episode #13.61
isAdult                             0
startYear                        2007
endYear                            \N
runtimeMinutes                     \N
genres            Action,Comedy,Drama
Name: 2011517, dtype: object

(9,)

tconst                               tt11836180
titleType                             tvEpisode
primaryTitle      Episode dated 7 February 2020
originalTitle     Episode dated 7 February 2020
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011518, dtype: object

(9,)

tconst                 tt11836182
titleType               tvEpisode
primaryTitle      Episode #1.2496
originalTitle     Episode #1.2496
isAdult                         0
startYear                    2017
endYear                        \N
runtimeMinutes                 60
genres                         \N
Name: 2011519, dtype: object

(9,)

tconst            tt11836184
titleType           tvSeries
primaryTitle          Vakuum
originalTitle         Vakuum
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes           103
genres                 Drama
Name: 2011520, dtype: object

(9,)

tconst                tt11836186
titleType              tvEpisode
primaryTitle      Episode #1.193
originalTitle     Episode #1.193
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011521, dtype: object

(9,)

tconst                tt11836188
titleType              tvEpisode
primaryTitle      Episode #1.192
originalTitle     Episode #1.192
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011522, dtype: object

(9,)

tconst                 tt1183618
titleType              tvEpisode
primaryTitle      Save the Whale
originalTitle     Save the Whale
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres               Documentary
Name: 2011523, dtype: object

(9,)

tconst                tt11836190
titleType              tvEpisode
primaryTitle      Episode #1.194
originalTitle     Episode #1.194
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011524, dtype: object

(9,)

tconst                tt11836192
titleType              tvEpisode
primaryTitle      Episode #1.195
originalTitle     Episode #1.195
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011525, dtype: object

(9,)

tconst                  tt11836194
titleType                tvEpisode
primaryTitle       Episode #1.1080
originalTitle      Episode #1.1080
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011526, dtype: object

(9,)

tconst                tt11836196
titleType              tvEpisode
primaryTitle      Episode #1.196
originalTitle     Episode #1.196
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011527, dtype: object

(9,)

tconst                  tt11836198
titleType                tvEpisode
primaryTitle       Episode #1.1081
originalTitle      Episode #1.1081
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011528, dtype: object

(9,)

tconst                             tt1183619
titleType                           tvSeries
primaryTitle      El ultimo matrimonio feliz
originalTitle     El ultimo matrimonio feliz
isAdult                                    0
startYear                               2001
endYear                                   \N
runtimeMinutes                            \N
genres                                 Drama
Name: 2011529, dtype: object

(9,)

tconst                tt11836200
titleType                  movie
primaryTitle      Kare to kanojô
originalTitle     Kare to kanojô
isAdult                        0
startYear                   1935
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011530, dtype: object

(9,)

tconst                  tt11836202
titleType                tvEpisode
primaryTitle       Episode #1.1082
originalTitle      Episode #1.1082
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011531, dtype: object

(9,)

tconst                  tt11836204
titleType                tvEpisode
primaryTitle       Episode #1.1083
originalTitle      Episode #1.1083
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011532, dtype: object

(9,)

tconst                  tt11836206
titleType                tvEpisode
primaryTitle       Episode #1.1084
originalTitle      Episode #1.1084
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011533, dtype: object

(9,)

tconst                                                   tt11836208
titleType                                                 tvEpisode
primaryTitle      Jok'Air reprend Vanessa Paradis, Doc Gyneco, L...
originalTitle     Jok'Air reprend Vanessa Paradis, Doc Gyneco, L...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2011534, dtype: object

(9,)

tconst                            tt1183620
titleType                         tvEpisode
primaryTitle      Get Rich... Or Fry Tryin'
originalTitle     Get Rich... Or Fry Tryin'
isAdult                                   0
startYear                              2008
endYear                                  \N
runtimeMinutes                           \N
genres                               Comedy
Name: 2011535, dtype: object

(9,)

tconst                  tt11836210
titleType                tvEpisode
primaryTitle       Episode #1.1085
originalTitle      Episode #1.1085
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011536, dtype: object

(9,)

tconst                 tt11836212
titleType                   short
primaryTitle           Reflection
originalTitle          Reflection
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 \N
genres            Animation,Short
Name: 2011537, dtype: object

(9,)

tconst                                        tt11836214
titleType                                      tvEpisode
primaryTitle      Rocío se acerca poco a poco a Benjamín
originalTitle     Rocío se acerca poco a poco a Benjamín
isAdult                                                0
startYear                                           2020
endYear                                               \N
runtimeMinutes                                        \N
genres                                             Drama
Name: 2011538, dtype: object

(9,)

tconst                  tt11836216
titleType                tvEpisode
primaryTitle       Episode #1.1086
originalTitle      Episode #1.1086
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011539, dtype: object

(9,)

tconst                  tt11836218
titleType                tvEpisode
primaryTitle       Episode #1.1087
originalTitle      Episode #1.1087
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011540, dtype: object

(9,)

tconst             tt1183621
titleType          tvEpisode
primaryTitle      Oh Brother
originalTitle     Oh Brother
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2011541, dtype: object

(9,)

tconst                  tt11836220
titleType                tvEpisode
primaryTitle       Episode #1.1088
originalTitle      Episode #1.1088
isAdult                          0
startYear                     2015
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011542, dtype: object

(9,)

tconst            tt11836222
titleType          tvEpisode
primaryTitle        Serenity
originalTitle       Serenity
isAdult                    0
startYear               2017
endYear                   \N
runtimeMinutes            60
genres                    \N
Name: 2011543, dtype: object

(9,)

tconst                tt11836224
titleType              tvEpisode
primaryTitle      Episode #1.197
originalTitle     Episode #1.197
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011544, dtype: object

(9,)

tconst                tt11836226
titleType              tvEpisode
primaryTitle      Episode #1.198
originalTitle     Episode #1.198
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011545, dtype: object

(9,)

tconst                tt11836228
titleType              tvEpisode
primaryTitle      Episode #1.199
originalTitle     Episode #1.199
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011546, dtype: object

(9,)

tconst            tt1183622
titleType         tvEpisode
primaryTitle      Handi Man
originalTitle     Handi Man
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2011547, dtype: object

(9,)

tconst                tt11836230
titleType              tvEpisode
primaryTitle      Episode #1.200
originalTitle     Episode #1.200
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011548, dtype: object

(9,)

tconst                 tt11836232
titleType                   short
primaryTitle        Sins for Hire
originalTitle       Sins for Hire
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                 14
genres            Adventure,Short
Name: 2011549, dtype: object

(9,)

tconst                                  tt11836234
titleType                                    video
primaryTitle      Camila Gallardo: Más de la mitad
originalTitle     Camila Gallardo: Más de la mitad
isAdult                                          0
startYear                                     2016
endYear                                         \N
runtimeMinutes                                  \N
genres                                 Music,Short
Name: 2011550, dtype: object

(9,)

tconst               tt11836236
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011551, dtype: object

(9,)

tconst            tt1183623
titleType         tvEpisode
primaryTitle      Baby Beef
originalTitle     Baby Beef
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2011552, dtype: object

(9,)

tconst               tt11836240
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011553, dtype: object

(9,)

tconst               tt11836242
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011554, dtype: object

(9,)

tconst               tt11836244
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011555, dtype: object

(9,)

tconst               tt11836246
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011556, dtype: object

(9,)

tconst               tt11836248
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011557, dtype: object

(9,)

tconst                     tt1183624
titleType                  tvEpisode
primaryTitle      Going, Going, Gone
originalTitle     Going, Going, Gone
isAdult                            0
startYear                       2009
endYear                           \N
runtimeMinutes                    \N
genres                        Comedy
Name: 2011558, dtype: object

(9,)

tconst               tt11836250
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011559, dtype: object

(9,)

tconst                 tt11836252
titleType                   short
primaryTitle              Orestes
originalTitle             Orestes
isAdult                         0
startYear                    2020
endYear                        \N
runtimeMinutes                  5
genres            Animation,Short
Name: 2011560, dtype: object

(9,)

tconst               tt11836254
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011561, dtype: object

(9,)

tconst               tt11836256
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011562, dtype: object

(9,)

tconst               tt11836258
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011563, dtype: object

(9,)

tconst                  tt1183625
titleType               tvEpisode
primaryTitle      Release Therapy
originalTitle     Release Therapy
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2011564, dtype: object

(9,)

tconst               tt11836260
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011565, dtype: object

(9,)

tconst                  tt11836262
titleType                  tvMovie
primaryTitle      Der Liebesdienst
originalTitle     Der Liebesdienst
isAdult                          0
startYear                     1963
endYear                         \N
runtimeMinutes                  30
genres                          \N
Name: 2011566, dtype: object

(9,)

tconst               tt11836264
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011567, dtype: object

(9,)

tconst               tt11836266
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011568, dtype: object

(9,)

tconst               tt11836268
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011569, dtype: object

(9,)

tconst            tt1183626
titleType         tvEpisode
primaryTitle       Cell Out
originalTitle      Cell Out
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2011570, dtype: object

(9,)

tconst               tt11836270
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011571, dtype: object

(9,)

tconst               tt11836272
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011572, dtype: object

(9,)

tconst               tt11836274
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011573, dtype: object

(9,)

tconst               tt11836276
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011574, dtype: object

(9,)

tconst               tt11836278
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011575, dtype: object

(9,)

tconst            tt1183627
titleType         tvEpisode
primaryTitle        Cop Out
originalTitle       Cop Out
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2011576, dtype: object

(9,)

tconst               tt11836280
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011577, dtype: object

(9,)

tconst               tt11836282
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011578, dtype: object

(9,)

tconst               tt11836284
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011579, dtype: object

(9,)

tconst               tt11836286
titleType             tvEpisode
primaryTitle      Episode #1.41
originalTitle     Episode #1.41
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011580, dtype: object

(9,)

tconst                  tt11836288
titleType                 tvSeries
primaryTitle         Pakdam Pakdai
originalTitle        Pakdam Pakdai
isAdult                          0
startYear                     2013
endYear                         \N
runtimeMinutes                  \N
genres            Animation,Comedy
Name: 2011581, dtype: object

(9,)

tconst            tt1183628
titleType         tvEpisode
primaryTitle       Thug Jr.
originalTitle      Thug Jr.
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2011582, dtype: object

(9,)

tconst              tt11836290
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011583, dtype: object

(9,)

tconst              tt11836292
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011584, dtype: object

(9,)

tconst              tt11836294
titleType            tvEpisode
primaryTitle      Episode #1.4
originalTitle     Episode #1.4
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011585, dtype: object

(9,)

tconst              tt11836296
titleType            tvEpisode
primaryTitle      Episode #1.5
originalTitle     Episode #1.5
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011586, dtype: object

(9,)

tconst                                  tt11836298
titleType                                tvEpisode
primaryTitle      Stresemann gestorben, 03.10.1929
originalTitle     Stresemann gestorben, 03.10.1929
isAdult                                          0
startYear                                     1963
endYear                                         \N
runtimeMinutes                                  \N
genres                           Documentary,Short
Name: 2011587, dtype: object

(9,)

tconst                        tt1183629
titleType                     tvEpisode
primaryTitle      The Blacker the Berry
originalTitle     The Blacker the Berry
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres                           Comedy
Name: 2011588, dtype: object

(9,)

tconst              tt11836300
titleType            tvEpisode
primaryTitle      Episode #1.6
originalTitle     Episode #1.6
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011589, dtype: object

(9,)

tconst              tt11836302
titleType            tvEpisode
primaryTitle      Episode #1.7
originalTitle     Episode #1.7
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011590, dtype: object

(9,)

tconst              tt11836304
titleType            tvEpisode
primaryTitle      Episode #1.8
originalTitle     Episode #1.8
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011591, dtype: object

(9,)

tconst                       tt11836306
titleType                     tvEpisode
primaryTitle      Berliner Wintergarten
originalTitle     Berliner Wintergarten
isAdult                               0
startYear                          1963
endYear                              \N
runtimeMinutes                       \N
genres                Documentary,Short
Name: 2011592, dtype: object

(9,)

tconst               tt11836308
titleType             tvEpisode
primaryTitle      Episode #1.10
originalTitle     Episode #1.10
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011593, dtype: object

(9,)

tconst             tt1183630
titleType          tvEpisode
primaryTitle      Say Cheese
originalTitle     Say Cheese
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2011594, dtype: object

(9,)

tconst              tt11836310
titleType            tvEpisode
primaryTitle      Episode #1.9
originalTitle     Episode #1.9
isAdult                      0
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011595, dtype: object

(9,)

tconst               tt11836312
titleType             tvEpisode
primaryTitle      Episode #1.11
originalTitle     Episode #1.11
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011596, dtype: object

(9,)

tconst                                          tt11836314
titleType                                        tvEpisode
primaryTitle      Dwight D. Eisenhower, geboren 14.10.1890
originalTitle     Dwight D. Eisenhower, geboren 14.10.1890
isAdult                                                  0
startYear                                             1963
endYear                                                 \N
runtimeMinutes                                          \N
genres                                   Documentary,Short
Name: 2011597, dtype: object

(9,)

tconst               tt11836316
titleType             tvEpisode
primaryTitle      Episode #1.12
originalTitle     Episode #1.12
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011598, dtype: object

(9,)

tconst               tt11836318
titleType             tvEpisode
primaryTitle      Episode #1.13
originalTitle     Episode #1.13
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011599, dtype: object

(9,)

tconst               tt1183631
titleType            tvEpisode
primaryTitle      Ashley's Mom
originalTitle     Ashley's Mom
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                  Comedy
Name: 2011600, dtype: object

(9,)

tconst               tt11836320
titleType             tvEpisode
primaryTitle      Episode #1.15
originalTitle     Episode #1.15
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011601, dtype: object

(9,)

tconst               tt11836322
titleType             tvEpisode
primaryTitle      Episode #1.14
originalTitle     Episode #1.14
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011602, dtype: object

(9,)

tconst               tt11836324
titleType             tvEpisode
primaryTitle      Episode #1.16
originalTitle     Episode #1.16
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011603, dtype: object

(9,)

tconst               tt11836326
titleType             tvEpisode
primaryTitle      Episode #1.17
originalTitle     Episode #1.17
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011604, dtype: object

(9,)

tconst                                                   tt11836328
titleType                                                 tvEpisode
primaryTitle      George Bernard Shaw, gestorben am 2. November ...
originalTitle     George Bernard Shaw, gestorben am 2. November ...
isAdult                                                           0
startYear                                                      1963
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Documentary,Short
Name: 2011605, dtype: object

(9,)

tconst                 tt1183632
titleType              tvEpisode
primaryTitle      Moose Crossing
originalTitle     Moose Crossing
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011606, dtype: object

(9,)

tconst               tt11836330
titleType             tvEpisode
primaryTitle      Episode #1.18
originalTitle     Episode #1.18
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011607, dtype: object

(9,)

tconst               tt11836332
titleType             tvEpisode
primaryTitle      Episode #1.19
originalTitle     Episode #1.19
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011608, dtype: object

(9,)

tconst               tt11836334
titleType             tvEpisode
primaryTitle      Episode #1.20
originalTitle     Episode #1.20
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011609, dtype: object

(9,)

tconst               tt11836336
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011610, dtype: object

(9,)

tconst               tt11836338
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011611, dtype: object

(9,)

tconst                 tt1183633
titleType              tvEpisode
primaryTitle      Episode #1.116
originalTitle     Episode #1.116
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2011612, dtype: object

(9,)

tconst               tt11836340
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011613, dtype: object

(9,)

tconst                    tt11836342
titleType                  tvEpisode
primaryTitle      Der schwarze Markt
originalTitle     Der schwarze Markt
isAdult                            0
startYear                       1963
endYear                           \N
runtimeMinutes                    \N
genres             Documentary,Short
Name: 2011614, dtype: object

(9,)

tconst               tt11836344
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011615, dtype: object

(9,)

tconst               tt11836346
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011616, dtype: object

(9,)

tconst               tt11836348
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011617, dtype: object

(9,)

tconst                 tt1183634
titleType              tvEpisode
primaryTitle      Episode #1.117
originalTitle     Episode #1.117
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2011618, dtype: object

(9,)

tconst               tt11836350
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011619, dtype: object

(9,)

tconst                                    tt11836352
titleType                                  tvEpisode
primaryTitle      Die ersten deutschen Wochenschauen
originalTitle     Die ersten deutschen Wochenschauen
isAdult                                            0
startYear                                       1963
endYear                                           \N
runtimeMinutes                                    \N
genres                             Documentary,Short
Name: 2011620, dtype: object

(9,)

tconst               tt11836354
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011621, dtype: object

(9,)

tconst               tt11836356
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011622, dtype: object

(9,)

tconst               tt11836358
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011623, dtype: object

(9,)

tconst                 tt1183635
titleType              tvEpisode
primaryTitle      Episode #1.118
originalTitle     Episode #1.118
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2011624, dtype: object

(9,)

tconst               tt11836360
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011625, dtype: object

(9,)

tconst                   tt11836362
titleType                 tvEpisode
primaryTitle       Schaffende Hände
originalTitle      Schaffende Hände
isAdult                           0
startYear                      1963
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2011626, dtype: object

(9,)

tconst               tt11836364
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011627, dtype: object

(9,)

tconst               tt11836366
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011628, dtype: object

(9,)

tconst               tt11836368
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011629, dtype: object

(9,)

tconst                 tt1183636
titleType              tvEpisode
primaryTitle      Episode #1.119
originalTitle     Episode #1.119
isAdult                        0
startYear                   2006
endYear                       \N
runtimeMinutes                \N
genres                 Talk-Show
Name: 2011630, dtype: object

(9,)

tconst               tt11836370
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011631, dtype: object

(9,)

tconst               tt11836372
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011632, dtype: object

(9,)

tconst               tt11836374
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011633, dtype: object

(9,)

tconst               tt11836376
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011634, dtype: object

(9,)

tconst               tt11836378
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011635, dtype: object

(9,)

tconst                               tt1183637
titleType                            tvEpisode
primaryTitle      Episode dated 7 January 2008
originalTitle     Episode dated 7 January 2008
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                    News
Name: 2011636, dtype: object

(9,)

tconst               tt11836380
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011637, dtype: object

(9,)

tconst               tt11836382
titleType             tvEpisode
primaryTitle      Episode #1.21
originalTitle     Episode #1.21
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011638, dtype: object

(9,)

tconst               tt11836384
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011639, dtype: object

(9,)

tconst               tt11836386
titleType             tvEpisode
primaryTitle      Episode #1.23
originalTitle     Episode #1.23
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011640, dtype: object

(9,)

tconst               tt11836388
titleType             tvEpisode
primaryTitle      Episode #1.24
originalTitle     Episode #1.24
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011641, dtype: object

(9,)

tconst                               tt1183638
titleType                            tvEpisode
primaryTitle      Episode dated 8 January 2008
originalTitle     Episode dated 8 January 2008
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                    News
Name: 2011642, dtype: object

(9,)

tconst               tt11836390
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011643, dtype: object

(9,)

tconst               tt11836392
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011644, dtype: object

(9,)

tconst               tt11836394
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011645, dtype: object

(9,)

tconst               tt11836396
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011646, dtype: object

(9,)

tconst               tt11836398
titleType             tvEpisode
primaryTitle      Episode #1.30
originalTitle     Episode #1.30
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011647, dtype: object

(9,)

tconst                               tt1183639
titleType                            tvEpisode
primaryTitle      Episode dated 9 January 2008
originalTitle     Episode dated 9 January 2008
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              \N
genres                                    News
Name: 2011648, dtype: object

(9,)

tconst               tt11836400
titleType             tvEpisode
primaryTitle      Episode #1.29
originalTitle     Episode #1.29
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011649, dtype: object

(9,)

tconst               tt11836402
titleType             tvEpisode
primaryTitle      Episode #1.31
originalTitle     Episode #1.31
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011650, dtype: object

(9,)

tconst               tt11836404
titleType             tvEpisode
primaryTitle      Episode #1.32
originalTitle     Episode #1.32
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011651, dtype: object

(9,)

tconst               tt11836406
titleType             tvEpisode
primaryTitle      Episode #1.33
originalTitle     Episode #1.33
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011652, dtype: object

(9,)

tconst                   tt11836408
titleType                     short
primaryTitle           Second Birth
originalTitle          Second Birth
isAdult                           0
startYear                      1990
endYear                          \N
runtimeMinutes                   14
genres            Documentary,Short
Name: 2011653, dtype: object

(9,)

tconst                                tt1183640
titleType                             tvEpisode
primaryTitle      Episode dated 10 January 2008
originalTitle     Episode dated 10 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011654, dtype: object

(9,)

tconst               tt11836410
titleType             tvEpisode
primaryTitle      Episode #1.34
originalTitle     Episode #1.34
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011655, dtype: object

(9,)

tconst               tt11836412
titleType             tvEpisode
primaryTitle      Episode #1.35
originalTitle     Episode #1.35
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011656, dtype: object

(9,)

tconst               tt11836414
titleType             tvEpisode
primaryTitle      Episode #1.36
originalTitle     Episode #1.36
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011657, dtype: object

(9,)

tconst               tt11836416
titleType             tvEpisode
primaryTitle      Episode #1.38
originalTitle     Episode #1.38
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011658, dtype: object

(9,)

tconst               tt11836418
titleType             tvEpisode
primaryTitle      Episode #1.37
originalTitle     Episode #1.37
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011659, dtype: object

(9,)

tconst                                tt1183641
titleType                             tvEpisode
primaryTitle      Episode dated 11 January 2008
originalTitle     Episode dated 11 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011660, dtype: object

(9,)

tconst               tt11836420
titleType             tvEpisode
primaryTitle      Episode #1.39
originalTitle     Episode #1.39
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011661, dtype: object

(9,)

tconst               tt11836422
titleType             tvEpisode
primaryTitle      Episode #1.40
originalTitle     Episode #1.40
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011662, dtype: object

(9,)

tconst                          tt11836424
titleType                            short
primaryTitle      Executioner: The Musical
originalTitle     Executioner: The Musical
isAdult                                  0
startYear                             1989
endYear                                 \N
runtimeMinutes                          25
genres                       Musical,Short
Name: 2011663, dtype: object

(9,)

tconst                tt11836426
titleType              tvEpisode
primaryTitle      Episode #1.261
originalTitle     Episode #1.261
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011664, dtype: object

(9,)

tconst                          tt11836428
titleType                            movie
primaryTitle      The Incantations: Origin
originalTitle     The Incantations: Origin
isAdult                                  0
startYear                             2020
endYear                                 \N
runtimeMinutes                          50
genres                              Horror
Name: 2011665, dtype: object

(9,)

tconst                                tt1183642
titleType                             tvEpisode
primaryTitle      Episode dated 14 January 2008
originalTitle     Episode dated 14 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011666, dtype: object

(9,)

tconst             tt11836430
titleType           tvEpisode
primaryTitle      Videokrayan
originalTitle     Videokrayan
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres              Talk-Show
Name: 2011667, dtype: object

(9,)

tconst                tt11836432
titleType              tvEpisode
primaryTitle      Episode #1.262
originalTitle     Episode #1.262
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011668, dtype: object

(9,)

tconst                tt11836434
titleType              tvEpisode
primaryTitle      Episode #1.263
originalTitle     Episode #1.263
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011669, dtype: object

(9,)

tconst                           tt11836436
titleType                             short
primaryTitle      The Death of the Reporter
originalTitle     The Death of the Reporter
isAdult                                   0
startYear                              2018
endYear                                  \N
runtimeMinutes                            8
genres                          Drama,Short
Name: 2011670, dtype: object

(9,)

tconst                tt11836438
titleType              tvEpisode
primaryTitle      Episode #1.264
originalTitle     Episode #1.264
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011671, dtype: object

(9,)

tconst                                tt1183643
titleType                             tvEpisode
primaryTitle      Episode dated 15 January 2008
originalTitle     Episode dated 15 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011672, dtype: object

(9,)

tconst                tt11836440
titleType              tvEpisode
primaryTitle      Episode #1.265
originalTitle     Episode #1.265
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011673, dtype: object

(9,)

tconst                tt11836442
titleType              tvEpisode
primaryTitle      Episode #1.266
originalTitle     Episode #1.266
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011674, dtype: object

(9,)

tconst                tt11836444
titleType              tvEpisode
primaryTitle      Episode #1.267
originalTitle     Episode #1.267
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011675, dtype: object

(9,)

tconst                tt11836446
titleType              tvEpisode
primaryTitle      Episode #1.269
originalTitle     Episode #1.269
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011676, dtype: object

(9,)

tconst                tt11836448
titleType              tvEpisode
primaryTitle      Episode #1.268
originalTitle     Episode #1.268
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011677, dtype: object

(9,)

tconst                                tt1183644
titleType                             tvEpisode
primaryTitle      Episode dated 16 January 2008
originalTitle     Episode dated 16 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011678, dtype: object

(9,)

tconst                                      tt11836450
titleType                                     tvSeries
primaryTitle      A Granny's Guide to the Modern World
originalTitle     A Granny's Guide to the Modern World
isAdult                                              0
startYear                                         2016
endYear                                           2016
runtimeMinutes                                      \N
genres                                     Documentary
Name: 2011679, dtype: object

(9,)

tconst                tt11836452
titleType              tvEpisode
primaryTitle      Episode #1.270
originalTitle     Episode #1.270
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011680, dtype: object

(9,)

tconst              tt11836454
titleType                movie
primaryTitle      Îtako ôiwake
originalTitle     Îtako ôiwake
isAdult                      0
startYear                 1936
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011681, dtype: object

(9,)

tconst                tt11836456
titleType              tvEpisode
primaryTitle      Episode #1.271
originalTitle     Episode #1.271
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011682, dtype: object

(9,)

tconst                tt11836458
titleType              tvEpisode
primaryTitle      Episode #1.272
originalTitle     Episode #1.272
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011683, dtype: object

(9,)

tconst                                tt1183645
titleType                             tvEpisode
primaryTitle      Episode dated 17 January 2008
originalTitle     Episode dated 17 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011684, dtype: object

(9,)

tconst                                                   tt11836460
titleType                                                 tvEpisode
primaryTitle      SZANSA NA SUKCES PL LAKE MALAWI - LUCY - EUROV...
originalTitle     SZANSA NA SUKCES PL LAKE MALAWI - LUCY - EUROV...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                    7
genres                                              Music,Talk-Show
Name: 2011685, dtype: object

(9,)

tconst                tt11836462
titleType              tvEpisode
primaryTitle      Episode #1.273
originalTitle     Episode #1.273
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011686, dtype: object

(9,)

tconst                tt11836464
titleType              tvEpisode
primaryTitle      Episode #1.274
originalTitle     Episode #1.274
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011687, dtype: object

(9,)

tconst                tt11836466
titleType              tvEpisode
primaryTitle      Episode #1.275
originalTitle     Episode #1.275
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011688, dtype: object

(9,)

tconst                tt11836468
titleType              tvEpisode
primaryTitle      Episode #1.276
originalTitle     Episode #1.276
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011689, dtype: object

(9,)

tconst                                tt1183646
titleType                             tvEpisode
primaryTitle      Episode dated 18 January 2008
originalTitle     Episode dated 18 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011690, dtype: object

(9,)

tconst                   tt11836470
titleType                  tvSeries
primaryTitle      Invisible Stories
originalTitle     Invisible Stories
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                   \N
genres                        Drama
Name: 2011691, dtype: object

(9,)

tconst                tt11836472
titleType              tvEpisode
primaryTitle      Episode #1.277
originalTitle     Episode #1.277
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011692, dtype: object

(9,)

tconst                tt11836474
titleType              tvEpisode
primaryTitle      Episode #1.278
originalTitle     Episode #1.278
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011693, dtype: object

(9,)

tconst                tt11836476
titleType              tvEpisode
primaryTitle      Episode #1.279
originalTitle     Episode #1.279
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011694, dtype: object

(9,)

tconst                tt11836478
titleType              tvEpisode
primaryTitle      Episode #1.280
originalTitle     Episode #1.280
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011695, dtype: object

(9,)

tconst                                tt1183647
titleType                             tvEpisode
primaryTitle      Episode dated 21 January 2008
originalTitle     Episode dated 21 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011696, dtype: object

(9,)

tconst               tt11836482
titleType             tvEpisode
primaryTitle      Episode #1.61
originalTitle     Episode #1.61
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011697, dtype: object

(9,)

tconst               tt11836484
titleType             tvEpisode
primaryTitle      Episode #1.62
originalTitle     Episode #1.62
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011698, dtype: object

(9,)

tconst               tt11836486
titleType             tvEpisode
primaryTitle      Episode #1.64
originalTitle     Episode #1.64
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011699, dtype: object

(9,)

tconst               tt11836488
titleType             tvEpisode
primaryTitle      Episode #1.63
originalTitle     Episode #1.63
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011700, dtype: object

(9,)

tconst                                tt1183648
titleType                             tvEpisode
primaryTitle      Episode dated 22 January 2008
originalTitle     Episode dated 22 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011701, dtype: object

(9,)

tconst               tt11836490
titleType             tvEpisode
primaryTitle      Episode #1.65
originalTitle     Episode #1.65
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011702, dtype: object

(9,)

tconst               tt11836492
titleType             tvEpisode
primaryTitle      Episode #1.66
originalTitle     Episode #1.66
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011703, dtype: object

(9,)

tconst              tt11836494
titleType            tvEpisode
primaryTitle      Kilpakosijat
originalTitle     Kilpakosijat
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011704, dtype: object

(9,)

tconst               tt11836496
titleType             tvEpisode
primaryTitle      Episode #1.67
originalTitle     Episode #1.67
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011705, dtype: object

(9,)

tconst               tt11836498
titleType             tvEpisode
primaryTitle      Episode #1.68
originalTitle     Episode #1.68
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011706, dtype: object

(9,)

tconst                                tt1183649
titleType                             tvEpisode
primaryTitle      Episode dated 23 January 2008
originalTitle     Episode dated 23 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011707, dtype: object

(9,)

tconst               tt11836500
titleType             tvEpisode
primaryTitle      Episode #1.70
originalTitle     Episode #1.70
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011708, dtype: object

(9,)

tconst               tt11836502
titleType             tvEpisode
primaryTitle      Episode #1.69
originalTitle     Episode #1.69
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011709, dtype: object

(9,)

tconst               tt11836504
titleType             tvEpisode
primaryTitle      Episode #1.71
originalTitle     Episode #1.71
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011710, dtype: object

(9,)

tconst               tt11836506
titleType             tvEpisode
primaryTitle      Episode #1.72
originalTitle     Episode #1.72
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011711, dtype: object

(9,)

tconst              tt11836508
titleType            tvEpisode
primaryTitle      Paljastuksia
originalTitle     Paljastuksia
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2011712, dtype: object

(9,)

tconst                                tt1183650
titleType                             tvEpisode
primaryTitle      Episode dated 24 January 2008
originalTitle     Episode dated 24 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011713, dtype: object

(9,)

tconst               tt11836510
titleType             tvEpisode
primaryTitle      Episode #1.73
originalTitle     Episode #1.73
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011714, dtype: object

(9,)

tconst               tt11836512
titleType             tvEpisode
primaryTitle      Episode #1.74
originalTitle     Episode #1.74
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011715, dtype: object

(9,)

tconst               tt11836514
titleType             tvEpisode
primaryTitle      Episode #1.75
originalTitle     Episode #1.75
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011716, dtype: object

(9,)

tconst               tt11836516
titleType             tvEpisode
primaryTitle      Episode #1.76
originalTitle     Episode #1.76
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011717, dtype: object

(9,)

tconst            tt11836518
titleType          tvEpisode
primaryTitle            Uhka
originalTitle           Uhka
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2011718, dtype: object

(9,)

tconst                                tt1183651
titleType                             tvEpisode
primaryTitle      Episode dated 25 January 2008
originalTitle     Episode dated 25 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011719, dtype: object

(9,)

tconst               tt11836520
titleType             tvEpisode
primaryTitle      Episode #1.77
originalTitle     Episode #1.77
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011720, dtype: object

(9,)

tconst               tt11836522
titleType             tvEpisode
primaryTitle      Episode #1.78
originalTitle     Episode #1.78
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011721, dtype: object

(9,)

tconst               tt11836524
titleType             tvEpisode
primaryTitle      Episode #1.79
originalTitle     Episode #1.79
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011722, dtype: object

(9,)

tconst             tt11836526
titleType           tvEpisode
primaryTitle      Suunnitelma
originalTitle     Suunnitelma
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2011723, dtype: object

(9,)

tconst               tt11836528
titleType             tvEpisode
primaryTitle      Episode #1.80
originalTitle     Episode #1.80
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2011724, dtype: object

(9,)

tconst                                tt1183652
titleType                             tvEpisode
primaryTitle      Episode dated 28 January 2008
originalTitle     Episode dated 28 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011725, dtype: object

(9,)

tconst            tt11836530
titleType          tvEpisode
primaryTitle            Ansa
originalTitle           Ansa
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2011726, dtype: object

(9,)

tconst            tt11836532
titleType          tvEpisode
primaryTitle         Yllätys
originalTitle        Yllätys
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2011727, dtype: object

(9,)

tconst                  tt11836534
titleType                tvEpisode
primaryTitle       Episode #1.1089
originalTitle      Episode #1.1089
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011728, dtype: object

(9,)

tconst                  tt11836536
titleType                tvEpisode
primaryTitle       Episode #1.1090
originalTitle      Episode #1.1090
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011729, dtype: object

(9,)

tconst                  tt11836538
titleType                tvEpisode
primaryTitle       Episode #1.1091
originalTitle      Episode #1.1091
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011730, dtype: object

(9,)

tconst                                tt1183653
titleType                             tvEpisode
primaryTitle      Episode dated 29 January 2008
originalTitle     Episode dated 29 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011731, dtype: object

(9,)

tconst                  tt11836540
titleType                tvEpisode
primaryTitle       Episode #1.1092
originalTitle      Episode #1.1092
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011732, dtype: object

(9,)

tconst                  tt11836542
titleType                tvEpisode
primaryTitle       Episode #1.1093
originalTitle      Episode #1.1093
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011733, dtype: object

(9,)

tconst                  tt11836544
titleType                tvEpisode
primaryTitle       Episode #1.1094
originalTitle      Episode #1.1094
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011734, dtype: object

(9,)

tconst                  tt11836546
titleType                tvEpisode
primaryTitle       Episode #1.1095
originalTitle      Episode #1.1095
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011735, dtype: object

(9,)

tconst                  tt11836548
titleType                tvEpisode
primaryTitle       Episode #1.1096
originalTitle      Episode #1.1096
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011736, dtype: object

(9,)

tconst                                tt1183654
titleType                             tvEpisode
primaryTitle      Episode dated 30 January 2008
originalTitle     Episode dated 30 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011737, dtype: object

(9,)

tconst                  tt11836550
titleType                tvEpisode
primaryTitle       Episode #1.1097
originalTitle      Episode #1.1097
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011738, dtype: object

(9,)

tconst                        tt11836552
titleType                      tvEpisode
primaryTitle               Episode #1.23
originalTitle              Episode #1.23
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Adventure,Comedy,Drama
Name: 2011739, dtype: object

(9,)

tconst                  tt11836554
titleType                tvEpisode
primaryTitle       Episode #1.1098
originalTitle      Episode #1.1098
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011740, dtype: object

(9,)

tconst                                            tt11836558
titleType                                          tvEpisode
primaryTitle      Messter-Woche - die erste Wochenschau 1914
originalTitle     Messter-Woche - die erste Wochenschau 1914
isAdult                                                    0
startYear                                               1964
endYear                                                   \N
runtimeMinutes                                            \N
genres                                     Documentary,Short
Name: 2011741, dtype: object

(9,)

tconst                                tt1183655
titleType                             tvEpisode
primaryTitle      Episode dated 31 January 2008
originalTitle     Episode dated 31 January 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2011742, dtype: object

(9,)

tconst                  tt11836560
titleType                tvEpisode
primaryTitle       Episode #1.1099
originalTitle      Episode #1.1099
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011743, dtype: object

(9,)

tconst                                   tt11836562
titleType                                 tvEpisode
primaryTitle      Mahatma Gandhi, + 30. Januar 1948
originalTitle     Mahatma Gandhi, + 30. Januar 1948
isAdult                                           0
startYear                                      1964
endYear                                          \N
runtimeMinutes                                   \N
genres                            Documentary,Short
Name: 2011744, dtype: object

(9,)

tconst                  tt11836564
titleType                tvEpisode
primaryTitle       Episode #1.1100
originalTitle      Episode #1.1100
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011745, dtype: object

(9,)

tconst                                                   tt11836566
titleType                                                 tvEpisode
primaryTitle      Erstes Sechs-Tage-Rennen in Berlin, 15. März 1909
originalTitle     Erstes Sechs-Tage-Rennen in Berlin, 15. März 1909
isAdult                                                           0
startYear                                                      1964
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Documentary,Short
Name: 2011746, dtype: object

(9,)

tconst                  tt11836568
titleType                tvEpisode
primaryTitle       Episode #1.1101
originalTitle      Episode #1.1101
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011747, dtype: object

(9,)

tconst                tt1183656
titleType             tvEpisode
primaryTitle      Episode #9.25
originalTitle     Episode #9.25
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2011748, dtype: object

(9,)

tconst                                              tt11836570
titleType                                            tvEpisode
primaryTitle      Erdbebenkatastrophe von Agadir, 1. März 1960
originalTitle     Erdbebenkatastrophe von Agadir, 1. März 1960
isAdult                                                      0
startYear                                                 1964
endYear                                                     \N
runtimeMinutes                                              \N
genres                                       Documentary,Short
Name: 2011749, dtype: object

(9,)

tconst                                tt11836572
titleType                              tvEpisode
primaryTitle      Brüsseler Weltausstellung 1958
originalTitle     Brüsseler Weltausstellung 1958
isAdult                                        0
startYear                                   1964
endYear                                       \N
runtimeMinutes                                \N
genres                         Documentary,Short
Name: 2011750, dtype: object

(9,)

tconst                     tt11836574
titleType                   tvEpisode
primaryTitle          Episode #1.6620
originalTitle         Episode #1.6620
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2011751, dtype: object

(9,)

tconst                   tt11836576
titleType                 tvEpisode
primaryTitle            Paul Nipkow
originalTitle           Paul Nipkow
isAdult                           0
startYear                      1964
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2011752, dtype: object

(9,)

tconst                           tt11836578
titleType                         tvEpisode
primaryTitle      Währungsreform, Juni 1948
originalTitle     Währungsreform, Juni 1948
isAdult                                   0
startYear                              1964
endYear                                  \N
runtimeMinutes                           \N
genres                    Documentary,Short
Name: 2011753, dtype: object

(9,)

tconst                         tt1183657
titleType                      tvEpisode
primaryTitle              Michael Sommer
originalTitle             Michael Sommer
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres            Comedy,Game-Show,Music
Name: 2011754, dtype: object

(9,)

tconst                     tt11836580
titleType                   tvEpisode
primaryTitle          Episode #1.6621
originalTitle         Episode #1.6621
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2011755, dtype: object

(9,)

tconst                                tt11836582
titleType                              tvEpisode
primaryTitle      Stalin gestorben, 5. März 1953
originalTitle     Stalin gestorben, 5. März 1953
isAdult                                        0
startYear                                   1964
endYear                                       \N
runtimeMinutes                                \N
genres                         Documentary,Short
Name: 2011756, dtype: object

(9,)

tconst                     tt11836584
titleType                   tvEpisode
primaryTitle          Episode #1.6623
originalTitle         Episode #1.6623
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2011757, dtype: object

(9,)

tconst                     tt11836586
titleType                   tvEpisode
primaryTitle          Episode #1.6624
originalTitle         Episode #1.6624
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2011758, dtype: object

(9,)

tconst                   tt11836588
titleType                 tvEpisode
primaryTitle            Mary Wigman
originalTitle           Mary Wigman
isAdult                           0
startYear                      1965
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2011759, dtype: object

(9,)

tconst                   tt1183658
titleType                    movie
primaryTitle                  1814
originalTitle                 1814
isAdult                          0
startYear                     2007
endYear                         \N
runtimeMinutes                  95
genres            History,Thriller
Name: 2011760, dtype: object

(9,)

tconst                               tt11836590
titleType                             tvEpisode
primaryTitle      Episode dated 21 October 1970
originalTitle     Episode dated 21 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2011761, dtype: object

(9,)

tconst                   tt11836592
titleType                 tvEpisode
primaryTitle              De Gaulle
originalTitle             De Gaulle
isAdult                           0
startYear                      1965
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2011762, dtype: object

(9,)

tconst                                                   tt11836594
titleType                                                 tvEpisode
primaryTitle      Anlässlich des 20. Todestages: Gerhart Hauptma...
originalTitle     Anlässlich des 20. Todestages: Gerhart Hauptma...
isAdult                                                           0
startYear                                                      1965
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                            Documentary,Short
Name: 2011763, dtype: object

(9,)

tconst            tt11836596
titleType          videoGame
primaryTitle         Patent9
originalTitle        Patent9
isAdult                    0
startYear               2018
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2011764, dtype: object

(9,)

tconst                  tt11836598
titleType                tvEpisode
primaryTitle       Episode #1.1102
originalTitle      Episode #1.1102
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011765, dtype: object

(9,)

tconst                              tt1183659
titleType                               video
primaryTitle      All About Anything But Love
originalTitle     All About Anything But Love
isAdult                                     0
startYear                                2007
endYear                                    \N
runtimeMinutes                             \N
genres                                  Short
Name: 2011766, dtype: object

(9,)

tconst                            tt11836600
titleType                          tvEpisode
primaryTitle      The Men in Black (S2, Ep5)
originalTitle     The Men in Black (S2, Ep5)
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            \N
genres                             Talk-Show
Name: 2011767, dtype: object

(9,)

tconst             tt11836602
titleType               short
primaryTitle          Weekend
originalTitle         Weekend
isAdult                     0
startYear                2020
endYear                    \N
runtimeMinutes             12
genres            Drama,Short
Name: 2011768, dtype: object

(9,)

tconst                  tt11836604
titleType                tvEpisode
primaryTitle       Episode #1.1103
originalTitle      Episode #1.1103
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011769, dtype: object

(9,)

tconst                   tt11836606
titleType                 tvEpisode
primaryTitle        Blockade Berlin
originalTitle       Blockade Berlin
isAdult                           0
startYear                      1966
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2011770, dtype: object

(9,)

tconst                    tt11836608
titleType                  tvEpisode
primaryTitle           Episode #6.31
originalTitle          Episode #6.31
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011771, dtype: object

(9,)

tconst                           tt1183660
titleType                            short
primaryTitle      The Anarchic Hand Affair
originalTitle     The Anarchic Hand Affair
isAdult                                  0
startYear                             2005
endYear                                 \N
runtimeMinutes                          15
genres                               Short
Name: 2011772, dtype: object

(9,)

tconst                               tt11836610
titleType                             tvEpisode
primaryTitle      Flug-Atlantiküberquerung 1927
originalTitle     Flug-Atlantiküberquerung 1927
isAdult                                       0
startYear                                  1966
endYear                                      \N
runtimeMinutes                               \N
genres                        Documentary,Short
Name: 2011773, dtype: object

(9,)

tconst                  tt11836612
titleType                tvEpisode
primaryTitle       Episode #1.1104
originalTitle      Episode #1.1104
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011774, dtype: object

(9,)

tconst                   tt11836614
titleType                 tvEpisode
primaryTitle            Wilhelm II.
originalTitle           Wilhelm II.
isAdult                           0
startYear                      1966
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2011775, dtype: object

(9,)

tconst                    tt11836616
titleType                  tvEpisode
primaryTitle           Episode #6.32
originalTitle          Episode #6.32
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011776, dtype: object

(9,)

tconst                 tt11836618
titleType                   short
primaryTitle      Dietro la porta
originalTitle     Dietro la porta
isAdult                         0
startYear                    2019
endYear                        \N
runtimeMinutes                 \N
genres                Drama,Short
Name: 2011777, dtype: object

(9,)

tconst                              tt1183661
titleType                               movie
primaryTitle      Baby Paterno (Dugong pulis)
originalTitle     Baby Paterno (Dugong pulis)
isAdult                                     0
startYear                                1994
endYear                                    \N
runtimeMinutes                             \N
genres                                 Action
Name: 2011778, dtype: object

(9,)

tconst                    tt11836620
titleType                  tvEpisode
primaryTitle           Episode #6.33
originalTitle          Episode #6.33
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011779, dtype: object

(9,)

tconst                    tt11836622
titleType                  tvEpisode
primaryTitle           Episode #6.34
originalTitle          Episode #6.34
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011780, dtype: object

(9,)

tconst                   tt11836624
titleType                 tvEpisode
primaryTitle           Nanga Parbat
originalTitle          Nanga Parbat
isAdult                           0
startYear                      1966
endYear                          \N
runtimeMinutes                   \N
genres            Documentary,Short
Name: 2011781, dtype: object

(9,)

tconst                    tt11836626
titleType                  tvEpisode
primaryTitle           Episode #6.35
originalTitle          Episode #6.35
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011782, dtype: object

(9,)

tconst                    tt11836628
titleType                  tvEpisode
primaryTitle           Episode #6.36
originalTitle          Episode #6.36
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011783, dtype: object

(9,)

tconst                                     tt1183662
titleType                                      movie
primaryTitle      Blip Festival: Reformat the Planet
originalTitle     Blip Festival: Reformat the Planet
isAdult                                            0
startYear                                       2008
endYear                                           \N
runtimeMinutes                                    82
genres                                   Documentary
Name: 2011784, dtype: object

(9,)

tconst                            tt11836630
titleType                          tvEpisode
primaryTitle            Golden Tips Imperial
originalTitle           Golden Tips Imperial
isAdult                                    0
startYear                               2020
endYear                                   \N
runtimeMinutes                            24
genres            Action,Adventure,Animation
Name: 2011785, dtype: object

(9,)

tconst                  tt11836632
titleType                tvEpisode
primaryTitle       Episode #1.1105
originalTitle      Episode #1.1105
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011786, dtype: object

(9,)

tconst                    tt11836634
titleType                  tvEpisode
primaryTitle           Episode #6.37
originalTitle          Episode #6.37
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011787, dtype: object

(9,)

tconst                    tt11836636
titleType                  tvEpisode
primaryTitle           Episode #6.38
originalTitle          Episode #6.38
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011788, dtype: object

(9,)

tconst                    tt11836638
titleType                  tvEpisode
primaryTitle           Episode #6.39
originalTitle          Episode #6.39
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011789, dtype: object

(9,)

tconst                    tt1183663
titleType                     movie
primaryTitle      Bootleg Wisconsin
originalTitle     Bootleg Wisconsin
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   73
genres                        Drama
Name: 2011790, dtype: object

(9,)

tconst                    tt11836640
titleType                  tvEpisode
primaryTitle           Episode #6.40
originalTitle          Episode #6.40
isAdult                            0
startYear                       2019
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011791, dtype: object

(9,)

tconst                  tt11836642
titleType                tvEpisode
primaryTitle       Episode #1.1106
originalTitle      Episode #1.1106
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011792, dtype: object

(9,)

tconst                    tt11836644
titleType                  tvEpisode
primaryTitle           Episode #6.41
originalTitle          Episode #6.41
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011793, dtype: object

(9,)

tconst                    tt11836646
titleType                  tvEpisode
primaryTitle           Episode #6.42
originalTitle          Episode #6.42
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011794, dtype: object

(9,)

tconst                    tt11836648
titleType                  tvEpisode
primaryTitle           Episode #6.43
originalTitle          Episode #6.43
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011795, dtype: object

(9,)

tconst                                             tt1183664
titleType                                              video
primaryTitle      Che gelida manina... lasciatela riscaldare
originalTitle     Che gelida manina... lasciatela riscaldare
isAdult                                                    1
startYear                                               2003
endYear                                                   \N
runtimeMinutes                                            95
genres                                                 Adult
Name: 2011796, dtype: object

(9,)

tconst                    tt11836650
titleType                  tvEpisode
primaryTitle           Episode #6.44
originalTitle          Episode #6.44
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011797, dtype: object

(9,)

tconst                  tt11836652
titleType                tvEpisode
primaryTitle       Episode #1.1107
originalTitle      Episode #1.1107
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011798, dtype: object

(9,)

tconst                    tt11836654
titleType                  tvEpisode
primaryTitle           Episode #6.45
originalTitle          Episode #6.45
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011799, dtype: object

(9,)

tconst                    tt11836656
titleType                  tvEpisode
primaryTitle           Episode #6.46
originalTitle          Episode #6.46
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011800, dtype: object

(9,)

tconst                    tt11836658
titleType                  tvEpisode
primaryTitle           Episode #6.47
originalTitle          Episode #6.47
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011801, dtype: object

(9,)

tconst                 tt1183665
titleType                  movie
primaryTitle              Cracks
originalTitle             Cracks
isAdult                        0
startYear                   2009
endYear                       \N
runtimeMinutes               104
genres            Drama,Thriller
Name: 2011802, dtype: object

(9,)

tconst                  tt11836662
titleType                tvEpisode
primaryTitle       Episode #1.1108
originalTitle      Episode #1.1108
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011803, dtype: object

(9,)

tconst                    tt11836664
titleType                  tvEpisode
primaryTitle           Episode #6.48
originalTitle          Episode #6.48
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011804, dtype: object

(9,)

tconst                    tt11836666
titleType                  tvEpisode
primaryTitle           Episode #6.49
originalTitle          Episode #6.49
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011805, dtype: object

(9,)

tconst                    tt11836668
titleType                  tvEpisode
primaryTitle           Episode #6.50
originalTitle          Episode #6.50
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011806, dtype: object

(9,)

tconst              tt1183666
titleType               movie
primaryTitle         Crawford
originalTitle        Crawford
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             75
genres            Documentary
Name: 2011807, dtype: object

(9,)

tconst                    tt11836670
titleType                  tvEpisode
primaryTitle           Episode #6.51
originalTitle          Episode #6.51
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011808, dtype: object

(9,)

tconst                    tt11836672
titleType                  tvEpisode
primaryTitle           Episode #6.52
originalTitle          Episode #6.52
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011809, dtype: object

(9,)

tconst                    tt11836674
titleType                  tvEpisode
primaryTitle           Episode #6.53
originalTitle          Episode #6.53
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011810, dtype: object

(9,)

tconst                    tt11836676
titleType                  tvEpisode
primaryTitle           Episode #6.54
originalTitle          Episode #6.54
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011811, dtype: object

(9,)

tconst                    tt11836678
titleType                  tvEpisode
primaryTitle           Episode #6.55
originalTitle          Episode #6.55
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011812, dtype: object

(9,)

tconst                    tt11836680
titleType                  tvEpisode
primaryTitle           Episode #6.56
originalTitle          Episode #6.56
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011813, dtype: object

(9,)

tconst                    tt11836682
titleType                  tvEpisode
primaryTitle           Episode #6.57
originalTitle          Episode #6.57
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011814, dtype: object

(9,)

tconst                    tt11836684
titleType                  tvEpisode
primaryTitle           Episode #6.58
originalTitle          Episode #6.58
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011815, dtype: object

(9,)

tconst                    tt11836686
titleType                  tvEpisode
primaryTitle           Episode #6.60
originalTitle          Episode #6.60
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011816, dtype: object

(9,)

tconst                    tt11836688
titleType                  tvEpisode
primaryTitle           Episode #6.59
originalTitle          Episode #6.59
isAdult                            0
startYear                       1999
endYear                           \N
runtimeMinutes                    \N
genres            Comedy,Drama,Music
Name: 2011817, dtype: object

(9,)

tconst                     tt1183668
titleType                      movie
primaryTitle      Le diable au corps
originalTitle     Le diable au corps
isAdult                            0
startYear                       2008
endYear                           \N
runtimeMinutes                    52
genres                   Documentary
Name: 2011818, dtype: object

(9,)

tconst                tt11836692
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011819, dtype: object

(9,)

tconst                tt11836694
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011820, dtype: object

(9,)

tconst                tt11836696
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011821, dtype: object

(9,)

tconst                tt11836698
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011822, dtype: object

(9,)

tconst                  tt1183669
titleType                 tvMovie
primaryTitle      An Eye for Alba
originalTitle     An Eye for Alba
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 22
genres                     Comedy
Name: 2011823, dtype: object

(9,)

tconst                tt11836700
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011824, dtype: object

(9,)

tconst                tt11836702
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011825, dtype: object

(9,)

tconst                tt11836704
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011826, dtype: object

(9,)

tconst                tt11836706
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011827, dtype: object

(9,)

tconst                tt11836708
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011828, dtype: object

(9,)

tconst                           tt1183670
titleType                          tvMovie
primaryTitle      Ein Ferienhaus auf Ibiza
originalTitle     Ein Ferienhaus auf Ibiza
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          88
genres                      Comedy,Romance
Name: 2011829, dtype: object

(9,)

tconst                tt11836710
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011830, dtype: object

(9,)

tconst                tt11836712
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011831, dtype: object

(9,)

tconst                tt11836714
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011832, dtype: object

(9,)

tconst                tt11836716
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011833, dtype: object

(9,)

tconst                tt11836718
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011834, dtype: object

(9,)

tconst                               tt1183671
titleType                              tvMovie
primaryTitle      Ein Ferienhaus in Schottland
originalTitle     Ein Ferienhaus in Schottland
isAdult                                      0
startYear                                 2008
endYear                                     \N
runtimeMinutes                              89
genres                    Drama,Family,Romance
Name: 2011835, dtype: object

(9,)

tconst                tt11836720
titleType              tvEpisode
primaryTitle      Episode #1.115
originalTitle     Episode #1.115
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011836, dtype: object

(9,)

tconst                tt11836722
titleType              tvEpisode
primaryTitle      Episode #1.116
originalTitle     Episode #1.116
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011837, dtype: object

(9,)

tconst                tt11836724
titleType              tvEpisode
primaryTitle      Episode #1.117
originalTitle     Episode #1.117
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011838, dtype: object

(9,)

tconst                                                tt11836726
titleType                                              tvEpisode
primaryTitle      Yoga... And The Trouble With Having A Big Dick
originalTitle     Yoga... And The Trouble With Having A Big Dick
isAdult                                                        0
startYear                                                   2016
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                    Comedy
Name: 2011839, dtype: object

(9,)

tconst                tt11836728
titleType              tvEpisode
primaryTitle      Episode #1.118
originalTitle     Episode #1.118
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011840, dtype: object

(9,)

tconst                        tt1183672
titleType                         movie
primaryTitle      The Girl on the Train
originalTitle           La fille du RER
isAdult                               0
startYear                          2009
endYear                              \N
runtimeMinutes                       97
genres                            Drama
Name: 2011841, dtype: object

(9,)

tconst                tt11836730
titleType              tvEpisode
primaryTitle      Episode #1.119
originalTitle     Episode #1.119
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011842, dtype: object

(9,)

tconst                tt11836732
titleType              tvEpisode
primaryTitle      Episode #1.120
originalTitle     Episode #1.120
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011843, dtype: object

(9,)

tconst                                                   tt11836734
titleType                                                 tvEpisode
primaryTitle      Dirty Talk. When Is It Right And When Is It WR...
originalTitle     Dirty Talk. When Is It Right And When Is It WR...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2011844, dtype: object

(9,)

tconst                tt11836736
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011845, dtype: object

(9,)

tconst                tt11836738
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011846, dtype: object

(9,)

tconst                                                    tt1183673
titleType                                                     video
primaryTitle      From Page to Screen to Stage: Rodgers & Hammer...
originalTitle     From Page to Screen to Stage: Rodgers & Hammer...
isAdult                                                           0
startYear                                                      2005
endYear                                                          \N
runtimeMinutes                                                   30
genres                                                        Short
Name: 2011847, dtype: object

(9,)

tconst                tt11836740
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011848, dtype: object

(9,)

tconst                tt11836742
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011849, dtype: object

(9,)

tconst                tt11836744
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011850, dtype: object

(9,)

tconst                tt11836746
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011851, dtype: object

(9,)

tconst                tt11836748
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011852, dtype: object

(9,)

tconst                tt11836750
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011853, dtype: object

(9,)

tconst                tt11836752
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011854, dtype: object

(9,)

tconst                tt11836754
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011855, dtype: object

(9,)

tconst                tt11836756
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011856, dtype: object

(9,)

tconst                   tt11836758
titleType                     short
primaryTitle               Homesick
originalTitle              Homesick
isAdult                           0
startYear                      2020
endYear                          \N
runtimeMinutes                    7
genres            Documentary,Short
Name: 2011857, dtype: object

(9,)

tconst               tt1183675
titleType                video
primaryTitle      Hairy Boyz 8
originalTitle     Hairy Boyz 8
isAdult                      1
startYear                 2007
endYear                     \N
runtimeMinutes              \N
genres                   Adult
Name: 2011858, dtype: object

(9,)

tconst                tt11836760
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011859, dtype: object

(9,)

tconst                tt11836762
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011860, dtype: object

(9,)

tconst                tt11836764
titleType              tvEpisode
primaryTitle      Episode #1.115
originalTitle     Episode #1.115
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011861, dtype: object

(9,)

tconst                tt11836766
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011862, dtype: object

(9,)

tconst                tt11836768
titleType              tvEpisode
primaryTitle      Episode #1.116
originalTitle     Episode #1.116
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011863, dtype: object

(9,)

tconst                     tt1183676
titleType                      video
primaryTitle      Heatstroke Highway
originalTitle     Heatstroke Highway
isAdult                            1
startYear                       2006
endYear                           \N
runtimeMinutes                    87
genres                         Adult
Name: 2011864, dtype: object

(9,)

tconst                                           tt11836770
titleType                                         tvEpisode
primaryTitle      Porn Introductions Are Far From Normal...
originalTitle     Porn Introductions Are Far From Normal...
isAdult                                                   0
startYear                                              2016
endYear                                                  \N
runtimeMinutes                                           \N
genres                                               Comedy
Name: 2011865, dtype: object

(9,)

tconst                tt11836772
titleType              tvEpisode
primaryTitle      Episode #1.117
originalTitle     Episode #1.117
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011866, dtype: object

(9,)

tconst                tt11836774
titleType              tvEpisode
primaryTitle      Episode #1.118
originalTitle     Episode #1.118
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011867, dtype: object

(9,)

tconst                tt11836776
titleType              tvEpisode
primaryTitle      Episode #1.119
originalTitle     Episode #1.119
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011868, dtype: object

(9,)

tconst                tt11836778
titleType              tvEpisode
primaryTitle      Episode #1.120
originalTitle     Episode #1.120
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011869, dtype: object

(9,)

tconst                           tt1183677
titleType                        tvEpisode
primaryTitle      Aretha Franklin: Respect
originalTitle     Aretha Franklin: Respect
isAdult                                  0
startYear                             2007
endYear                                 \N
runtimeMinutes                          35
genres                   Documentary,Music
Name: 2011870, dtype: object

(9,)

tconst                tt11836780
titleType              tvEpisode
primaryTitle      Episode #1.121
originalTitle     Episode #1.121
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2011871, dtype: object

(9,)

tconst                tt11836782
titleType              tvEpisode
primaryTitle      Episode #1.101
originalTitle     Episode #1.101
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011872, dtype: object

(9,)

tconst                                          tt11836784
titleType                                        tvEpisode
primaryTitle      Kayden Kross gets a very awkward massage
originalTitle     Kayden Kross gets a very awkward massage
isAdult                                                  0
startYear                                             2016
endYear                                                 \N
runtimeMinutes                                          \N
genres                                              Comedy
Name: 2011873, dtype: object

(9,)

tconst                     tt11836786
titleType                   tvEpisode
primaryTitle          Episode #1.6628
originalTitle         Episode #1.6628
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2011874, dtype: object

(9,)

tconst                     tt11836788
titleType                   tvEpisode
primaryTitle          Episode #1.6629
originalTitle         Episode #1.6629
isAdult                             0
startYear                        1981
endYear                            \N
runtimeMinutes                     \N
genres            Crime,Drama,Mystery
Name: 2011875, dtype: object

(9,)

tconst                                         tt1183678
titleType                                      tvEpisode
primaryTitle      Band-Aid: Do They Know It's Christmas?
originalTitle     Band-Aid: Do They Know It's Christmas?
isAdult                                                0
startYear                                           2007
endYear                                               \N
runtimeMinutes                                        35
genres                                 Documentary,Music
Name: 2011876, dtype: object

(9,)

tconst                  tt11836790
titleType                tvEpisode
primaryTitle       Episode #1.1109
originalTitle      Episode #1.1109
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011877, dtype: object

(9,)

tconst                                    tt11836792
titleType                                  tvEpisode
primaryTitle      El encuentro de Agustina y Samanta
originalTitle     El encuentro de Agustina y Samanta
isAdult                                            0
startYear                                       2020
endYear                                           \N
runtimeMinutes                                    \N
genres                                         Drama
Name: 2011878, dtype: object

(9,)

tconst                                   tt11836794
titleType                                 tvEpisode
primaryTitle      Kayden and Manuel's new neighbors
originalTitle     Kayden and Manuel's new neighbors
isAdult                                           0
startYear                                      2016
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Comedy
Name: 2011879, dtype: object

(9,)

tconst                  tt11836796
titleType                tvEpisode
primaryTitle       Episode #1.1110
originalTitle      Episode #1.1110
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011880, dtype: object

(9,)

tconst                  tt11836798
titleType                tvEpisode
primaryTitle       Episode #1.1111
originalTitle      Episode #1.1111
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011881, dtype: object

(9,)

tconst                                tt1183679
titleType                             tvEpisode
primaryTitle      Shania Twain: Any Man of Mine
originalTitle     Shania Twain: Any Man of Mine
isAdult                                       0
startYear                                  2007
endYear                                      \N
runtimeMinutes                               35
genres                        Documentary,Music
Name: 2011882, dtype: object

(9,)

tconst                  tt11836800
titleType                tvEpisode
primaryTitle       Episode #1.1112
originalTitle      Episode #1.1112
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011883, dtype: object

(9,)

tconst                                tt11836802
titleType                              tvEpisode
primaryTitle      Episode dated 19 February 2020
originalTitle     Episode dated 19 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                 Talk-Show
Name: 2011884, dtype: object

(9,)

tconst                                                   tt11836804
titleType                                                 tvEpisode
primaryTitle      It's hard to get life insurance when you're in...
originalTitle     It's hard to get life insurance when you're in...
isAdult                                                           0
startYear                                                      2016
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                       Comedy
Name: 2011885, dtype: object

(9,)

tconst               tt11836806
titleType              tvSeries
primaryTitle      Jabb Love Hua
originalTitle     Jabb Love Hua
isAdult                       0
startYear                  2006
endYear                      \N
runtimeMinutes               \N
genres                  Romance
Name: 2011886, dtype: object

(9,)

tconst                  tt11836808
titleType                tvEpisode
primaryTitle       Episode #1.1113
originalTitle      Episode #1.1113
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011887, dtype: object

(9,)

tconst            tt1183680
titleType           tvMovie
primaryTitle       La juive
originalTitle      La juive
isAdult                   0
startYear              2003
endYear                  \N
runtimeMinutes          176
genres                Music
Name: 2011888, dtype: object

(9,)

tconst                    tt11836810
titleType                      short
primaryTitle      Leur premier matin
originalTitle     Leur premier matin
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                     3
genres                  Comedy,Short
Name: 2011889, dtype: object

(9,)

tconst                    tt11836812
titleType                  tvEpisode
primaryTitle      Safe words in porn
originalTitle     Safe words in porn
isAdult                            0
startYear                       2016
endYear                           \N
runtimeMinutes                    \N
genres                        Comedy
Name: 2011890, dtype: object

(9,)

tconst                                                 tt11836814
titleType                                               tvEpisode
primaryTitle      What does a porn couple do when they are alone?
originalTitle     What does a porn couple do when they are alone?
isAdult                                                         0
startYear                                                    2016
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                     Comedy
Name: 2011891, dtype: object

(9,)

tconst                  tt11836816
titleType                tvEpisode
primaryTitle       Episode #1.1114
originalTitle      Episode #1.1114
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011892, dtype: object

(9,)

tconst               tt11836818
titleType             tvEpisode
primaryTitle      Episode #1.25
originalTitle     Episode #1.25
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2011893, dtype: object

(9,)

tconst               tt1183681
titleType                short
primaryTitle      The Lutheran
originalTitle     The Lutheran
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              25
genres            Comedy,Short
Name: 2011894, dtype: object

(9,)

tconst               tt11836820
titleType             tvEpisode
primaryTitle      Episode #1.26
originalTitle     Episode #1.26
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2011895, dtype: object

(9,)

tconst               tt11836822
titleType             tvEpisode
primaryTitle      Episode #1.27
originalTitle     Episode #1.27
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2011896, dtype: object

(9,)

tconst               tt11836824
titleType             tvEpisode
primaryTitle      Episode #1.28
originalTitle     Episode #1.28
isAdult                       0
startYear                  2020
endYear                      \N
runtimeMinutes               \N
genres                       \N
Name: 2011897, dtype: object

(9,)

tconst                              tt11836826
titleType                            tvEpisode
primaryTitle      Squirting, is it pee or not?
originalTitle     Squirting, is it pee or not?
isAdult                                      0
startYear                                 2016
endYear                                     \N
runtimeMinutes                              \N
genres                                  Comedy
Name: 2011898, dtype: object

(9,)

tconst                                  tt11836828
titleType                                tvEpisode
primaryTitle      El secreto de Ricardo San Martín
originalTitle     El secreto de Ricardo San Martín
isAdult                                          0
startYear                                     2020
endYear                                         \N
runtimeMinutes                                  \N
genres                                       Drama
Name: 2011899, dtype: object

(9,)

tconst                    tt1183682
titleType                     movie
primaryTitle      Merry Mirthquakes
originalTitle     Merry Mirthquakes
isAdult                           0
startYear                      1953
endYear                          \N
runtimeMinutes                   68
genres                 Comedy,Music
Name: 2011900, dtype: object

(9,)

tconst              tt11836830
titleType                video
primaryTitle      Kanae Kitano
originalTitle     Kanae Kitano
isAdult                      1
startYear                 2008
endYear                     \N
runtimeMinutes              67
genres                   Adult
Name: 2011901, dtype: object

(9,)

tconst                                                tt11836832
titleType                                              tvEpisode
primaryTitle      Top 10 Roles British Actors Want You to Forget
originalTitle     Top 10 Roles British Actors Want You to Forget
isAdult                                                        0
startYear                                                   2018
endYear                                                       \N
runtimeMinutes                                                \N
genres                                                 Talk-Show
Name: 2011902, dtype: object

(9,)

tconst                                tt11836834
titleType                              tvEpisode
primaryTitle      Stupid newbie mistakes in porn
originalTitle     Stupid newbie mistakes in porn
isAdult                                        0
startYear                                   2016
endYear                                       \N
runtimeMinutes                                \N
genres                                    Comedy
Name: 2011903, dtype: object

(9,)

tconst                  tt11836836
titleType                tvEpisode
primaryTitle       Episode #1.1115
originalTitle      Episode #1.1115
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011904, dtype: object

(9,)

tconst                  tt11836838
titleType                tvEpisode
primaryTitle       Episode #1.1116
originalTitle      Episode #1.1116
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011905, dtype: object

(9,)

tconst                tt1183683
titleType                 video
primaryTitle      Midnight Date
originalTitle     Midnight Date
isAdult                       0
startYear                  2004
endYear                      \N
runtimeMinutes               \N
genres                    Short
Name: 2011906, dtype: object

(9,)

tconst                  tt11836840
titleType                tvEpisode
primaryTitle       Episode #1.1117
originalTitle      Episode #1.1117
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011907, dtype: object

(9,)

tconst                tt11836842
titleType              tvEpisode
primaryTitle      Episode #1.102
originalTitle     Episode #1.102
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011908, dtype: object

(9,)

tconst                                   tt11836844
titleType                                 tvEpisode
primaryTitle      The Crazy MILF next door - part 1
originalTitle     The Crazy MILF next door - part 1
isAdult                                           0
startYear                                      2016
endYear                                          \N
runtimeMinutes                                   \N
genres                                       Comedy
Name: 2011909, dtype: object

(9,)

tconst                  tt11836846
titleType                tvEpisode
primaryTitle       Episode #1.1118
originalTitle      Episode #1.1118
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011910, dtype: object

(9,)

tconst                  tt11836848
titleType                tvEpisode
primaryTitle       Episode #1.1119
originalTitle      Episode #1.1119
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011911, dtype: object

(9,)

tconst                           tt1183684
titleType                            movie
primaryTitle      My Effortless Brilliance
originalTitle     My Effortless Brilliance
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          79
genres                        Comedy,Drama
Name: 2011912, dtype: object

(9,)

tconst                tt11836850
titleType              tvEpisode
primaryTitle      Episode #1.103
originalTitle     Episode #1.103
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011913, dtype: object

(9,)

tconst                      tt11836852
titleType                      tvMovie
primaryTitle      Love in the Forecast
originalTitle     Love in the Forecast
isAdult                              0
startYear                         2020
endYear                             \N
runtimeMinutes                      82
genres                  Comedy,Romance
Name: 2011914, dtype: object

(9,)

tconst                tt11836854
titleType              tvEpisode
primaryTitle      Episode #1.104
originalTitle     Episode #1.104
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011915, dtype: object

(9,)

tconst            tt11836856
titleType          tvEpisode
primaryTitle      My America
originalTitle     My America
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            10
genres                 Drama
Name: 2011916, dtype: object

(9,)

tconst                tt11836858
titleType              tvEpisode
primaryTitle      Episode #1.105
originalTitle     Episode #1.105
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011917, dtype: object

(9,)

tconst                                                    tt1183685
titleType                                                  tvSeries
primaryTitle      Mémoires du cinéma francais, de la libération ...
originalTitle     Mémoires du cinéma francais, de la libération ...
isAdult                                                           0
startYear                                                      2006
endYear                                                          \N
runtimeMinutes                                                  240
genres                                                  Documentary
Name: 2011918, dtype: object

(9,)

tconst                tt11836860
titleType              tvEpisode
primaryTitle      Episode #1.107
originalTitle     Episode #1.107
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011919, dtype: object

(9,)

tconst                tt11836862
titleType              tvEpisode
primaryTitle      Episode #1.106
originalTitle     Episode #1.106
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011920, dtype: object

(9,)

tconst                tt11836864
titleType              tvEpisode
primaryTitle      Episode #1.108
originalTitle     Episode #1.108
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011921, dtype: object

(9,)

tconst                  tt11836866
titleType                tvEpisode
primaryTitle       Episode #1.1120
originalTitle      Episode #1.1120
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011922, dtype: object

(9,)

tconst                tt11836868
titleType              tvEpisode
primaryTitle      Episode #1.109
originalTitle     Episode #1.109
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011923, dtype: object

(9,)

tconst                         tt1183686
titleType                          video
primaryTitle         No Strings Attached
originalTitle        No Strings Attached
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        87
genres            Action,Comedy,Thriller
Name: 2011924, dtype: object

(9,)

tconst                tt11836870
titleType              tvEpisode
primaryTitle      Episode #1.110
originalTitle     Episode #1.110
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011925, dtype: object

(9,)

tconst                  tt11836872
titleType                tvEpisode
primaryTitle       Episode #1.1121
originalTitle      Episode #1.1121
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2011926, dtype: object

(9,)

tconst                tt11836874
titleType              tvEpisode
primaryTitle      Episode #1.111
originalTitle     Episode #1.111
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011927, dtype: object

(9,)

tconst                tt11836876
titleType              tvEpisode
primaryTitle      Episode #1.112
originalTitle     Episode #1.112
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011928, dtype: object

(9,)

tconst                       tt11836878
titleType                      tvSeries
primaryTitle              Dum Talk Live
originalTitle             Dum Talk Live
isAdult                               0
startYear                          2020
endYear                              \N
runtimeMinutes                       \N
genres            Comedy,News,Talk-Show
Name: 2011929, dtype: object

(9,)

tconst                    tt1183687
titleType                     movie
primaryTitle      Of All the Things
originalTitle     Of All the Things
isAdult                           0
startYear                      2008
endYear                          \N
runtimeMinutes                   85
genres            Documentary,Music
Name: 2011930, dtype: object

(9,)

tconst                    tt11836880
titleType                  tvEpisode
primaryTitle      Porn star training
originalTitle     Porn star training
isAdult                            0
startYear                       2016
endYear                           \N
runtimeMinutes                    \N
genres                        Comedy
Name: 2011931, dtype: object

(9,)

tconst                tt11836882
titleType              tvEpisode
primaryTitle      Episode #1.113
originalTitle     Episode #1.113
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011932, dtype: object

(9,)

tconst                tt11836884
titleType              tvEpisode
primaryTitle      Episode #1.114
originalTitle     Episode #1.114
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011933, dtype: object

(9,)

tconst                tt11836886
titleType              tvEpisode
primaryTitle      Episode #1.115
originalTitle     Episode #1.115
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011934, dtype: object

(9,)

tconst                tt11836888
titleType              tvEpisode
primaryTitle      Episode #1.116
originalTitle     Episode #1.116
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011935, dtype: object

(9,)

tconst                     tt1183688
titleType                    tvMovie
primaryTitle      Ohnostroj v Aspern
originalTitle     Ohnostroj v Aspern
isAdult                            0
startYear                       1987
endYear                           \N
runtimeMinutes                    \N
genres                  Comedy,Drama
Name: 2011936, dtype: object

(9,)

tconst                    tt11836890
titleType                    tvMovie
primaryTitle      Schöpfung der Welt
originalTitle     Schöpfung der Welt
isAdult                            0
startYear                       1963
endYear                           \N
runtimeMinutes                    65
genres                            \N
Name: 2011937, dtype: object

(9,)

tconst                tt11836892
titleType              tvEpisode
primaryTitle      Episode #1.118
originalTitle     Episode #1.118
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011938, dtype: object

(9,)

tconst                tt11836894
titleType              tvEpisode
primaryTitle      Episode #1.117
originalTitle     Episode #1.117
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011939, dtype: object

(9,)

tconst                tt11836896
titleType              tvEpisode
primaryTitle      Episode #1.119
originalTitle     Episode #1.119
isAdult                        0
startYear                   2004
endYear                       \N
runtimeMinutes                \N
genres             Drama,Romance
Name: 2011940, dtype: object

(9,)

tconst                                                    tt1183689
titleType                                                 tvSpecial
primaryTitle      Olivia Newton-John and the Sydney Symphony Orc...
originalTitle     Olivia Newton-John and the Sydney Symphony Orc...
isAdult                                                           0
startYear                                                      2007
endYear                                                          \N
runtimeMinutes                                                  127
genres                                                        Music
Name: 2011941, dtype: object

(9,)

tconst                      tt11836900
titleType                    tvEpisode
primaryTitle                      2756
originalTitle                     2756
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2011942, dtype: object

(9,)

tconst                                             tt11836902
titleType                                           tvEpisode
primaryTitle      The crazy and confusing world of porn lingo
originalTitle     The crazy and confusing world of porn lingo
isAdult                                                     0
startYear                                                2016
endYear                                                    \N
runtimeMinutes                                             \N
genres                                                 Comedy
Name: 2011943, dtype: object

(9,)

tconst                                     tt11836904
titleType                                   tvEpisode
primaryTitle      El reencuentro de Samanta y Ricardo
originalTitle     El reencuentro de Samanta y Ricardo
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     \N
genres                                          Drama
Name: 2011944, dtype: object

(9,)

tconst                tt11836906
titleType              tvEpisode
primaryTitle      Episode #1.781
originalTitle     Episode #1.781
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011945, dtype: object

(9,)

tconst                                               tt11836908
titleType                                             tvEpisode
primaryTitle      Explaining porn expenses to the accountant...
originalTitle     Explaining porn expenses to the accountant...
isAdult                                                       0
startYear                                                  2016
endYear                                                      \N
runtimeMinutes                                               \N
genres                                                   Comedy
Name: 2011946, dtype: object

(9,)

tconst                tt1183690
titleType                 short
primaryTitle      The Only Girl
originalTitle     The Only Girl
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               13
genres             Comedy,Short
Name: 2011947, dtype: object

(9,)

tconst                  tt11836910
titleType                tvEpisode
primaryTitle        School of Duck
originalTitle       School of Duck
isAdult                          0
startYear                     2019
endYear                         \N
runtimeMinutes                  12
genres            Animation,Family
Name: 2011948, dtype: object

(9,)

tconst                tt11836912
titleType              tvEpisode
primaryTitle      Episode #1.782
originalTitle     Episode #1.782
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011949, dtype: object

(9,)

tconst                tt11836914
titleType              tvEpisode
primaryTitle      Episode #1.783
originalTitle     Episode #1.783
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011950, dtype: object

(9,)

tconst                tt11836916
titleType              tvEpisode
primaryTitle      Episode #1.785
originalTitle     Episode #1.785
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011951, dtype: object

(9,)

tconst                tt11836918
titleType              tvEpisode
primaryTitle      Episode #1.784
originalTitle     Episode #1.784
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011952, dtype: object

(9,)

tconst                 tt1183691
titleType                tvMovie
primaryTitle      Palicova dcera
originalTitle     Palicova dcera
isAdult                        0
startYear                   1977
endYear                       \N
runtimeMinutes                78
genres                     Drama
Name: 2011953, dtype: object

(9,)

tconst                tt11836922
titleType              tvEpisode
primaryTitle      Episode #1.786
originalTitle     Episode #1.786
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011954, dtype: object

(9,)

tconst                tt11836924
titleType              tvEpisode
primaryTitle      Episode #1.787
originalTitle     Episode #1.787
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011955, dtype: object

(9,)

tconst                tt11836926
titleType              tvEpisode
primaryTitle      Episode #1.788
originalTitle     Episode #1.788
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011956, dtype: object

(9,)

tconst                tt11836928
titleType              tvEpisode
primaryTitle      Episode #1.790
originalTitle     Episode #1.790
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011957, dtype: object

(9,)

tconst                     tt1183692
titleType                      movie
primaryTitle      Pequenas Histórias
originalTitle     Pequenas Histórias
isAdult                            0
startYear                       2007
endYear                           \N
runtimeMinutes                    83
genres                        Family
Name: 2011958, dtype: object

(9,)

tconst                tt11836930
titleType              tvEpisode
primaryTitle      Episode #1.789
originalTitle     Episode #1.789
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011959, dtype: object

(9,)

tconst                tt11836932
titleType              tvEpisode
primaryTitle      Episode #1.791
originalTitle     Episode #1.791
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011960, dtype: object

(9,)

tconst                tt11836934
titleType              tvEpisode
primaryTitle      Episode #1.792
originalTitle     Episode #1.792
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011961, dtype: object

(9,)

tconst                tt11836936
titleType              tvEpisode
primaryTitle      Episode #1.793
originalTitle     Episode #1.793
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011962, dtype: object

(9,)

tconst                tt11836938
titleType              tvEpisode
primaryTitle      Episode #1.794
originalTitle     Episode #1.794
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011963, dtype: object

(9,)

tconst                 tt1183693
titleType                  movie
primaryTitle      The Pogi Dozen
originalTitle     The Pogi Dozen
isAdult                        0
startYear                   1967
endYear                       \N
runtimeMinutes                \N
genres             Action,Comedy
Name: 2011964, dtype: object

(9,)

tconst                tt11836940
titleType              tvEpisode
primaryTitle      Episode #1.795
originalTitle     Episode #1.795
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011965, dtype: object

(9,)

tconst                tt11836942
titleType              tvEpisode
primaryTitle      Episode #1.796
originalTitle     Episode #1.796
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011966, dtype: object

(9,)

tconst                tt11836944
titleType              tvEpisode
primaryTitle      Episode #1.798
originalTitle     Episode #1.798
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011967, dtype: object

(9,)

tconst                tt11836946
titleType              tvEpisode
primaryTitle      Episode #1.797
originalTitle     Episode #1.797
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011968, dtype: object

(9,)

tconst                tt11836948
titleType              tvEpisode
primaryTitle      Episode #1.799
originalTitle     Episode #1.799
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011969, dtype: object

(9,)

tconst                                     tt1183694
titleType                                  videoGame
primaryTitle      QI Presents: Strictly Come Duncing
originalTitle     QI Presents: Strictly Come Duncing
isAdult                                            0
startYear                                       2007
endYear                                           \N
runtimeMinutes                                    \N
genres                              Comedy,Game-Show
Name: 2011970, dtype: object

(9,)

tconst                tt11836950
titleType              tvEpisode
primaryTitle      Episode #1.800
originalTitle     Episode #1.800
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011971, dtype: object

(9,)

tconst                      tt11836952
titleType                    tvEpisode
primaryTitle                      2764
originalTitle                     2764
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2011972, dtype: object

(9,)

tconst                tt11836954
titleType              tvEpisode
primaryTitle      Episode #1.621
originalTitle     Episode #1.621
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011973, dtype: object

(9,)

tconst                                         tt11836956
titleType                                       tvEpisode
primaryTitle      Top 10 Hardest Things to Kill in Movies
originalTitle     Top 10 Hardest Things to Kill in Movies
isAdult                                                 0
startYear                                            2016
endYear                                                \N
runtimeMinutes                                         \N
genres                                   Comedy,Talk-Show
Name: 2011974, dtype: object

(9,)

tconst                tt11836958
titleType              tvEpisode
primaryTitle      Episode #1.622
originalTitle     Episode #1.622
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011975, dtype: object

(9,)

tconst                   tt1183695
titleType                  tvMovie
primaryTitle       What Love Means
originalTitle     Sa raison d'être
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                 200
genres                       Drama
Name: 2011976, dtype: object

(9,)

tconst                tt11836960
titleType              tvEpisode
primaryTitle      Episode #1.623
originalTitle     Episode #1.623
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011977, dtype: object

(9,)

tconst                tt11836962
titleType              tvEpisode
primaryTitle      Episode #1.624
originalTitle     Episode #1.624
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011978, dtype: object

(9,)

tconst                tt11836964
titleType              tvEpisode
primaryTitle      Episode #1.625
originalTitle     Episode #1.625
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011979, dtype: object

(9,)

tconst                tt11836966
titleType              tvEpisode
primaryTitle      Episode #1.626
originalTitle     Episode #1.626
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011980, dtype: object

(9,)

tconst                tt11836968
titleType              tvEpisode
primaryTitle      Episode #1.627
originalTitle     Episode #1.627
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011981, dtype: object

(9,)

tconst              tt1183696
titleType               movie
primaryTitle      Second Skin
originalTitle     Second Skin
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             94
genres            Documentary
Name: 2011982, dtype: object

(9,)

tconst                tt11836970
titleType              tvEpisode
primaryTitle      Episode #1.628
originalTitle     Episode #1.628
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011983, dtype: object

(9,)

tconst                tt11836972
titleType              tvEpisode
primaryTitle      Episode #1.629
originalTitle     Episode #1.629
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011984, dtype: object

(9,)

tconst                tt11836974
titleType              tvEpisode
primaryTitle      Episode #1.630
originalTitle     Episode #1.630
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011985, dtype: object

(9,)

tconst                tt11836976
titleType              tvEpisode
primaryTitle      Episode #1.631
originalTitle     Episode #1.631
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011986, dtype: object

(9,)

tconst                tt11836978
titleType              tvEpisode
primaryTitle      Episode #1.632
originalTitle     Episode #1.632
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011987, dtype: object

(9,)

tconst               tt1183697
titleType                movie
primaryTitle      Sex Positive
originalTitle     Sex Positive
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              75
genres             Documentary
Name: 2011988, dtype: object

(9,)

tconst                tt11836980
titleType              tvEpisode
primaryTitle      Episode #1.634
originalTitle     Episode #1.634
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011989, dtype: object

(9,)

tconst                tt11836982
titleType              tvEpisode
primaryTitle      Episode #1.633
originalTitle     Episode #1.633
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011990, dtype: object

(9,)

tconst                tt11836984
titleType              tvEpisode
primaryTitle      Episode #1.635
originalTitle     Episode #1.635
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011991, dtype: object

(9,)

tconst                tt11836986
titleType              tvEpisode
primaryTitle      Episode #1.636
originalTitle     Episode #1.636
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011992, dtype: object

(9,)

tconst              tt11836988
titleType             tvSeries
primaryTitle          Herocast
originalTitle         Herocast
isAdult                      0
startYear                 2018
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Drama
Name: 2011993, dtype: object

(9,)

tconst            tt1183698
titleType           tvMovie
primaryTitle          Skaup
originalTitle         Skaup
isAdult                   0
startYear              2007
endYear                  \N
runtimeMinutes           50
genres               Comedy
Name: 2011994, dtype: object

(9,)

tconst                tt11836990
titleType              tvEpisode
primaryTitle      Episode #1.637
originalTitle     Episode #1.637
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011995, dtype: object

(9,)

tconst                tt11836992
titleType              tvEpisode
primaryTitle      Episode #1.638
originalTitle     Episode #1.638
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011996, dtype: object

(9,)

tconst                tt11836994
titleType              tvEpisode
primaryTitle      Episode #1.639
originalTitle     Episode #1.639
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2011997, dtype: object

(9,)

tconst                                                   tt11836998
titleType                                                 tvEpisode
primaryTitle      Top 10 YouTubers You Didn't Know Were Criminal...
originalTitle     Top 10 YouTubers You Didn't Know Were Criminal...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2011998, dtype: object

(9,)

tconst                tt1183699
titleType                 short
primaryTitle      Song of David
originalTitle     Song of David
isAdult                       0
startYear                  2007
endYear                      \N
runtimeMinutes               20
genres              Drama,Short
Name: 2011999, dtype: object

(9,)

tconst                tt11837000
titleType              tvEpisode
primaryTitle      Episode #1.640
originalTitle     Episode #1.640
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012000, dtype: object

(9,)

tconst                tt11837002
titleType              tvEpisode
primaryTitle      Episode #1.341
originalTitle     Episode #1.341
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012001, dtype: object

(9,)

tconst                tt11837004
titleType              tvEpisode
primaryTitle      Episode #1.342
originalTitle     Episode #1.342
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012002, dtype: object

(9,)

tconst                tt11837006
titleType              tvEpisode
primaryTitle      Episode #1.343
originalTitle     Episode #1.343
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012003, dtype: object

(9,)

tconst                tt11837008
titleType              tvEpisode
primaryTitle      Episode #1.344
originalTitle     Episode #1.344
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012004, dtype: object

(9,)

tconst                tt11837010
titleType              tvEpisode
primaryTitle      Episode #1.345
originalTitle     Episode #1.345
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012005, dtype: object

(9,)

tconst                tt11837012
titleType              tvEpisode
primaryTitle      Episode #1.346
originalTitle     Episode #1.346
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012006, dtype: object

(9,)

tconst                                 tt11837014
titleType                               tvEpisode
primaryTitle      Water - Freezing Water and Snow
originalTitle     Water - Freezing Water and Snow
isAdult                                         0
startYear                                    1982
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Family
Name: 2012007, dtype: object

(9,)

tconst                tt11837016
titleType              tvEpisode
primaryTitle      Episode #1.347
originalTitle     Episode #1.347
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012008, dtype: object

(9,)

tconst                tt11837018
titleType              tvEpisode
primaryTitle      Episode #1.349
originalTitle     Episode #1.349
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012009, dtype: object

(9,)

tconst                             tt1183701
titleType                              movie
primaryTitle      They Killed Sister Dorothy
originalTitle     They Killed Sister Dorothy
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            94
genres                           Documentary
Name: 2012010, dtype: object

(9,)

tconst                tt11837020
titleType              tvEpisode
primaryTitle      Episode #1.348
originalTitle     Episode #1.348
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012011, dtype: object

(9,)

tconst                tt11837022
titleType              tvEpisode
primaryTitle      Episode #1.350
originalTitle     Episode #1.350
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012012, dtype: object

(9,)

tconst                tt11837024
titleType              tvEpisode
primaryTitle      Episode #1.351
originalTitle     Episode #1.351
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012013, dtype: object

(9,)

tconst                tt11837026
titleType              tvEpisode
primaryTitle      Episode #1.352
originalTitle     Episode #1.352
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012014, dtype: object

(9,)

tconst                tt11837028
titleType              tvEpisode
primaryTitle      Episode #1.354
originalTitle     Episode #1.354
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012015, dtype: object

(9,)

tconst             tt1183702
titleType              movie
primaryTitle      Up with Me
originalTitle     Up with Me
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            80
genres                 Drama
Name: 2012016, dtype: object

(9,)

tconst                tt11837030
titleType              tvEpisode
primaryTitle      Episode #1.353
originalTitle     Episode #1.353
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012017, dtype: object

(9,)

tconst                tt11837032
titleType              tvEpisode
primaryTitle      Episode #1.355
originalTitle     Episode #1.355
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012018, dtype: object

(9,)

tconst                tt11837034
titleType              tvEpisode
primaryTitle      Episode #1.356
originalTitle     Episode #1.356
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012019, dtype: object

(9,)

tconst                tt11837036
titleType              tvEpisode
primaryTitle      Episode #1.357
originalTitle     Episode #1.357
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012020, dtype: object

(9,)

tconst                tt11837038
titleType              tvEpisode
primaryTitle      Episode #1.358
originalTitle     Episode #1.358
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012021, dtype: object

(9,)

tconst                  tt1183703
titleType                   movie
primaryTitle      Ver van familie
originalTitle     Ver van familie
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                141
genres                      Drama
Name: 2012022, dtype: object

(9,)

tconst                tt11837040
titleType              tvEpisode
primaryTitle      Episode #1.359
originalTitle     Episode #1.359
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012023, dtype: object

(9,)

tconst                     tt11837042
titleType                       movie
primaryTitle      Via Don Minzoni N.6
originalTitle     Via Don Minzoni N.6
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres                          Drama
Name: 2012024, dtype: object

(9,)

tconst                tt11837044
titleType              tvEpisode
primaryTitle      Episode #1.360
originalTitle     Episode #1.360
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012025, dtype: object

(9,)

tconst                      tt11837046
titleType                    tvEpisode
primaryTitle                      2772
originalTitle                     2772
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012026, dtype: object

(9,)

tconst                tt11837048
titleType              tvEpisode
primaryTitle      Episode #1.141
originalTitle     Episode #1.141
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012027, dtype: object

(9,)

tconst                tt11837050
titleType              tvEpisode
primaryTitle      Episode #1.142
originalTitle     Episode #1.142
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012028, dtype: object

(9,)

tconst                tt11837052
titleType              tvEpisode
primaryTitle      Episode #1.144
originalTitle     Episode #1.144
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012029, dtype: object

(9,)

tconst                tt11837054
titleType              tvEpisode
primaryTitle      Episode #1.143
originalTitle     Episode #1.143
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012030, dtype: object

(9,)

tconst                tt11837056
titleType              tvEpisode
primaryTitle      Episode #1.145
originalTitle     Episode #1.145
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012031, dtype: object

(9,)

tconst                tt11837058
titleType              tvEpisode
primaryTitle      Episode #1.146
originalTitle     Episode #1.146
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012032, dtype: object

(9,)

tconst                 tt1183705
titleType                  movie
primaryTitle      We Are Wizards
originalTitle     We Are Wizards
isAdult                        0
startYear                   2008
endYear                       \N
runtimeMinutes                79
genres               Documentary
Name: 2012033, dtype: object

(9,)

tconst                tt11837060
titleType              tvEpisode
primaryTitle      Episode #1.147
originalTitle     Episode #1.147
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012034, dtype: object

(9,)

tconst                tt11837062
titleType              tvEpisode
primaryTitle      Episode #1.148
originalTitle     Episode #1.148
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012035, dtype: object

(9,)

tconst                tt11837064
titleType              tvEpisode
primaryTitle      Episode #1.149
originalTitle     Episode #1.149
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012036, dtype: object

(9,)

tconst                tt11837066
titleType              tvEpisode
primaryTitle      Episode #1.150
originalTitle     Episode #1.150
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012037, dtype: object

(9,)

tconst                   tt11837068
titleType                     short
primaryTitle      Tierra y Silencio
originalTitle     Tierra y Silencio
isAdult                           0
startYear                      2012
endYear                          \N
runtimeMinutes                   23
genres               Short,Thriller
Name: 2012038, dtype: object

(9,)

tconst                   tt1183706
titleType                    movie
primaryTitle      L'âge de passion
originalTitle     L'âge de passion
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  78
genres                 Documentary
Name: 2012039, dtype: object

(9,)

tconst                tt11837070
titleType              tvEpisode
primaryTitle      Episode #1.151
originalTitle     Episode #1.151
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012040, dtype: object

(9,)

tconst                tt11837072
titleType              tvEpisode
primaryTitle      Episode #1.153
originalTitle     Episode #1.153
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012041, dtype: object

(9,)

tconst                tt11837074
titleType              tvEpisode
primaryTitle      Episode #1.152
originalTitle     Episode #1.152
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012042, dtype: object

(9,)

tconst                                            tt11837076
titleType                                          tvEpisode
primaryTitle      Water - Experimenting with Water annd Sand
originalTitle     Water - Experimenting with Water annd Sand
isAdult                                                    0
startYear                                               1982
endYear                                                   \N
runtimeMinutes                                            \N
genres                                                Family
Name: 2012043, dtype: object

(9,)

tconst                tt11837078
titleType              tvEpisode
primaryTitle      Episode #1.154
originalTitle     Episode #1.154
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012044, dtype: object

(9,)

tconst                       tt1183707
titleType                        movie
primaryTitle      The Apple & The Worm
originalTitle            Æblet & ormen
isAdult                              0
startYear                         2009
endYear                             \N
runtimeMinutes                      75
genres                Animation,Family
Name: 2012045, dtype: object

(9,)

tconst                tt11837080
titleType              tvEpisode
primaryTitle      Episode #1.155
originalTitle     Episode #1.155
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012046, dtype: object

(9,)

tconst                               tt11837082
titleType                             tvEpisode
primaryTitle      Episode dated 22 October 1970
originalTitle     Episode dated 22 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2012047, dtype: object

(9,)

tconst                tt11837084
titleType              tvEpisode
primaryTitle      Episode #1.156
originalTitle     Episode #1.156
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012048, dtype: object

(9,)

tconst                tt11837086
titleType              tvEpisode
primaryTitle      Episode #1.157
originalTitle     Episode #1.157
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012049, dtype: object

(9,)

tconst                tt11837088
titleType              tvEpisode
primaryTitle      Episode #1.158
originalTitle     Episode #1.158
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012050, dtype: object

(9,)

tconst                                 tt1183708
titleType                               tvSeries
primaryTitle      Cròniques de la veritat oculta
originalTitle     Cròniques de la veritat oculta
isAdult                                        0
startYear                                   1997
endYear                                     1997
runtimeMinutes                                \N
genres                                        \N
Name: 2012051, dtype: object

(9,)

tconst              tt11837090
titleType                short
primaryTitle             Ducks
originalTitle            Ducks
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              13
genres            Family,Short
Name: 2012052, dtype: object

(9,)

tconst                tt11837092
titleType              tvEpisode
primaryTitle      Episode #1.159
originalTitle     Episode #1.159
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012053, dtype: object

(9,)

tconst                                                 tt11837094
titleType                                               tvEpisode
primaryTitle      Another Top 10 Hardest Things to Kill in Movies
originalTitle     Another Top 10 Hardest Things to Kill in Movies
isAdult                                                         0
startYear                                                    2017
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                           Comedy,Talk-Show
Name: 2012054, dtype: object

(9,)

tconst                tt11837096
titleType              tvEpisode
primaryTitle      Episode #1.160
originalTitle     Episode #1.160
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012055, dtype: object

(9,)

tconst               tt11837098
titleType                 short
primaryTitle      The Carpenter
originalTitle     The Carpenter
isAdult                       0
startYear                  2017
endYear                      \N
runtimeMinutes                5
genres             Horror,Short
Name: 2012056, dtype: object

(9,)

tconst            tt1183709
titleType          tvSeries
primaryTitle         Ecoman
originalTitle        Ecoman
isAdult                   0
startYear              1999
endYear                  \N
runtimeMinutes           \N
genres               Family
Name: 2012057, dtype: object

(9,)

tconst                                       tt11837100
titleType                                     tvEpisode
primaryTitle      Absolute Demonic Front Mesopotamia II
originalTitle     Absolute Demonic Front Mesopotamia II
isAdult                                               0
startYear                                          2020
endYear                                              \N
runtimeMinutes                                       \N
genres                           Action,Animation,Drama
Name: 2012058, dtype: object

(9,)

tconst                        tt11837102
titleType                      tvEpisode
primaryTitle                 Grand Order
originalTitle                Grand Order
isAdult                                0
startYear                           2020
endYear                               \N
runtimeMinutes                        \N
genres            Action,Animation,Drama
Name: 2012059, dtype: object

(9,)

tconst                tt11837104
titleType              tvEpisode
primaryTitle      Episode #1.381
originalTitle     Episode #1.381
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012060, dtype: object

(9,)

tconst                  tt11837106
titleType                    video
primaryTitle      Adidas: The Wall
originalTitle     Adidas: The Wall
isAdult                          0
startYear                     1993
endYear                         \N
runtimeMinutes                   1
genres                       Short
Name: 2012061, dtype: object

(9,)

tconst                      tt11837108
titleType                    tvEpisode
primaryTitle                      2781
originalTitle                     2781
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012062, dtype: object

(9,)

tconst            tt1183710
titleType          tvSeries
primaryTitle      Mak i Zak
originalTitle     Mak i Zak
isAdult                   0
startYear              1986
endYear                  \N
runtimeMinutes           \N
genres               Comedy
Name: 2012063, dtype: object

(9,)

tconst                  tt11837110
titleType                tvEpisode
primaryTitle      Un paso adelante
originalTitle     Un paso adelante
isAdult                          0
startYear                     2020
endYear                         \N
runtimeMinutes                  \N
genres                      Action
Name: 2012064, dtype: object

(9,)

tconst                tt11837112
titleType              tvEpisode
primaryTitle      Episode #1.383
originalTitle     Episode #1.383
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012065, dtype: object

(9,)

tconst                tt11837114
titleType              tvEpisode
primaryTitle      Episode #1.382
originalTitle     Episode #1.382
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012066, dtype: object

(9,)

tconst                tt11837116
titleType              tvEpisode
primaryTitle      Episode #1.385
originalTitle     Episode #1.385
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012067, dtype: object

(9,)

tconst                tt11837118
titleType              tvEpisode
primaryTitle      Episode #1.384
originalTitle     Episode #1.384
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012068, dtype: object

(9,)

tconst                tt1183711
titleType              tvSeries
primaryTitle      Sexta à Noite
originalTitle     Sexta à Noite
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                Talk-Show
Name: 2012069, dtype: object

(9,)

tconst                tt11837120
titleType              tvEpisode
primaryTitle      Episode #1.386
originalTitle     Episode #1.386
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012070, dtype: object

(9,)

tconst                                              tt11837122
titleType                                            tvEpisode
primaryTitle      Water - Uses of Water with Birds and Animals
originalTitle     Water - Uses of Water with Birds and Animals
isAdult                                                      0
startYear                                                 1982
endYear                                                     \N
runtimeMinutes                                              \N
genres                                                  Family
Name: 2012071, dtype: object

(9,)

tconst                tt11837124
titleType              tvEpisode
primaryTitle      Episode #1.387
originalTitle     Episode #1.387
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012072, dtype: object

(9,)

tconst                tt11837126
titleType              tvEpisode
primaryTitle      Episode #1.388
originalTitle     Episode #1.388
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012073, dtype: object

(9,)

tconst                tt11837128
titleType              tvEpisode
primaryTitle      Episode #1.389
originalTitle     Episode #1.389
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012074, dtype: object

(9,)

tconst            tt1183712
titleType          tvSeries
primaryTitle       Taxicash
originalTitle      Taxicash
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           30
genres            Game-Show
Name: 2012075, dtype: object

(9,)

tconst                tt11837130
titleType              tvEpisode
primaryTitle      Episode #1.390
originalTitle     Episode #1.390
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012076, dtype: object

(9,)

tconst                tt11837132
titleType              tvEpisode
primaryTitle      Episode #1.392
originalTitle     Episode #1.392
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012077, dtype: object

(9,)

tconst                tt11837134
titleType              tvEpisode
primaryTitle      Episode #1.391
originalTitle     Episode #1.391
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012078, dtype: object

(9,)

tconst                tt11837136
titleType              tvEpisode
primaryTitle      Episode #1.393
originalTitle     Episode #1.393
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012079, dtype: object

(9,)

tconst                tt11837138
titleType              tvEpisode
primaryTitle      Episode #1.394
originalTitle     Episode #1.394
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012080, dtype: object

(9,)

tconst                       tt1183713
titleType                        movie
primaryTitle      Aimer et vivre libre
originalTitle     Aimer et vivre libre
isAdult                              1
startYear                         1981
endYear                             \N
runtimeMinutes                      75
genres                           Adult
Name: 2012081, dtype: object

(9,)

tconst                tt11837140
titleType              tvEpisode
primaryTitle      Episode #1.395
originalTitle     Episode #1.395
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012082, dtype: object

(9,)

tconst                tt11837142
titleType              tvEpisode
primaryTitle      Episode #1.396
originalTitle     Episode #1.396
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012083, dtype: object

(9,)

tconst                tt11837144
titleType              tvEpisode
primaryTitle      Episode #1.397
originalTitle     Episode #1.397
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012084, dtype: object

(9,)

tconst                tt11837146
titleType              tvEpisode
primaryTitle      Episode #1.399
originalTitle     Episode #1.399
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012085, dtype: object

(9,)

tconst                tt11837148
titleType              tvEpisode
primaryTitle      Episode #1.398
originalTitle     Episode #1.398
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012086, dtype: object

(9,)

tconst                  tt1183714
titleType                   short
primaryTitle              O cerco
originalTitle             O cerco
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 10
genres            Drama,Short,War
Name: 2012087, dtype: object

(9,)

tconst                tt11837152
titleType              tvEpisode
primaryTitle      Episode #1.400
originalTitle     Episode #1.400
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012088, dtype: object

(9,)

tconst                           tt11837154
titleType                         tvEpisode
primaryTitle      Bilanggo ni Madam: Part 1
originalTitle     Bilanggo ni Madam: Part 1
isAdult                                   0
startYear                              2020
endYear                                  \N
runtimeMinutes                           30
genres                                Drama
Name: 2012089, dtype: object

(9,)

tconst              tt11837156
titleType                short
primaryTitle        InstaSkits
originalTitle       InstaSkits
isAdult                      0
startYear                 2020
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2012090, dtype: object

(9,)

tconst                tt11837158
titleType              tvEpisode
primaryTitle      Episode #1.181
originalTitle     Episode #1.181
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012091, dtype: object

(9,)

tconst                                                tt1183715
titleType                                                 short
primaryTitle      Columbia World of Sports: Navy's All-American
originalTitle     Columbia World of Sports: Navy's All-American
isAdult                                                       0
startYear                                                  1956
endYear                                                      \N
runtimeMinutes                                                9
genres                                       Action,Short,Sport
Name: 2012092, dtype: object

(9,)

tconst                tt11837160
titleType              tvEpisode
primaryTitle      Episode #1.182
originalTitle     Episode #1.182
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012093, dtype: object

(9,)

tconst                                      tt11837162
titleType                                    tvEpisode
primaryTitle      Welcome to the Podcast! E3 Thoughts!
originalTitle     Welcome to the Podcast! E3 Thoughts!
isAdult                                              0
startYear                                         2018
endYear                                             \N
runtimeMinutes                                      \N
genres                                    Comedy,Drama
Name: 2012094, dtype: object

(9,)

tconst                tt11837164
titleType              tvEpisode
primaryTitle      Episode #1.183
originalTitle     Episode #1.183
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012095, dtype: object

(9,)

tconst                tt11837166
titleType              tvEpisode
primaryTitle      Episode #1.184
originalTitle     Episode #1.184
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012096, dtype: object

(9,)

tconst                tt11837168
titleType              tvEpisode
primaryTitle      Episode #1.185
originalTitle     Episode #1.185
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012097, dtype: object

(9,)

tconst            tt1183716
titleType             movie
primaryTitle       Devi Maa
originalTitle      Devi Maa
isAdult                   0
startYear              2006
endYear                  \N
runtimeMinutes           \N
genres              Fantasy
Name: 2012098, dtype: object

(9,)

tconst                tt11837170
titleType              tvEpisode
primaryTitle      Episode #1.186
originalTitle     Episode #1.186
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012099, dtype: object

(9,)

tconst                tt11837172
titleType              tvEpisode
primaryTitle      Episode #1.187
originalTitle     Episode #1.187
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012100, dtype: object

(9,)

tconst                tt11837174
titleType              tvEpisode
primaryTitle      Episode #1.188
originalTitle     Episode #1.188
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012101, dtype: object

(9,)

tconst                tt11837178
titleType              tvEpisode
primaryTitle      Episode #1.189
originalTitle     Episode #1.189
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012102, dtype: object

(9,)

tconst                tt1183717
titleType                 movie
primaryTitle      Drôle de show
originalTitle     Drôle de show
isAdult                       1
startYear                  1982
endYear                      \N
runtimeMinutes               54
genres                    Adult
Name: 2012103, dtype: object

(9,)

tconst                tt11837180
titleType              tvEpisode
primaryTitle      Episode #1.190
originalTitle     Episode #1.190
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012104, dtype: object

(9,)

tconst                tt11837182
titleType              tvEpisode
primaryTitle      Episode #1.191
originalTitle     Episode #1.191
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012105, dtype: object

(9,)

tconst                tt11837184
titleType              tvEpisode
primaryTitle      Episode #1.193
originalTitle     Episode #1.193
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012106, dtype: object

(9,)

tconst                tt11837186
titleType              tvEpisode
primaryTitle      Episode #1.192
originalTitle     Episode #1.192
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012107, dtype: object

(9,)

tconst                  tt11837188
titleType                tvEpisode
primaryTitle      Water - Clothing
originalTitle     Water - Clothing
isAdult                          0
startYear                     1982
endYear                         \N
runtimeMinutes                  \N
genres                      Family
Name: 2012108, dtype: object

(9,)

tconst                        tt1183718
titleType                         movie
primaryTitle      Murder in Villa Capri
originalTitle     Murder in Villa Capri
isAdult                               0
startYear                          1955
endYear                              \N
runtimeMinutes                       68
genres            Adventure,Crime,Drama
Name: 2012109, dtype: object

(9,)

tconst                tt11837190
titleType              tvEpisode
primaryTitle      Episode #1.195
originalTitle     Episode #1.195
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012110, dtype: object

(9,)

tconst                tt11837192
titleType              tvEpisode
primaryTitle      Episode #1.194
originalTitle     Episode #1.194
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012111, dtype: object

(9,)

tconst                tt11837196
titleType              tvEpisode
primaryTitle      Episode #1.196
originalTitle     Episode #1.196
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012112, dtype: object

(9,)

tconst                tt11837198
titleType              tvEpisode
primaryTitle      Episode #1.197
originalTitle     Episode #1.197
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012113, dtype: object

(9,)

tconst                      tt1183719
titleType                       movie
primaryTitle          Poor Mrs. Jones
originalTitle         Poor Mrs. Jones
isAdult                             0
startYear                        1926
endYear                            \N
runtimeMinutes                     46
genres            Comedy,Drama,Family
Name: 2012114, dtype: object

(9,)

tconst                tt11837200
titleType              tvEpisode
primaryTitle      Episode #1.198
originalTitle     Episode #1.198
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012115, dtype: object

(9,)

tconst                tt11837202
titleType              tvEpisode
primaryTitle      Episode #1.199
originalTitle     Episode #1.199
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012116, dtype: object

(9,)

tconst                tt11837204
titleType              tvEpisode
primaryTitle      Episode #1.200
originalTitle     Episode #1.200
isAdult                        0
startYear                   2018
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012117, dtype: object

(9,)

tconst                     tt11837206
titleType                   tvEpisode
primaryTitle          Episode #1.1961
originalTitle         Episode #1.1961
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012118, dtype: object

(9,)

tconst                     tt11837208
titleType                   tvEpisode
primaryTitle          Episode #1.1962
originalTitle         Episode #1.1962
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012119, dtype: object

(9,)

tconst             tt1183720
titleType              movie
primaryTitle      Sweet Home
originalTitle     Sweet Home
isAdult                    0
startYear               1924
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2012120, dtype: object

(9,)

tconst                     tt11837212
titleType                   tvEpisode
primaryTitle          Episode #1.1963
originalTitle         Episode #1.1963
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012121, dtype: object

(9,)

tconst                     tt11837214
titleType                   tvEpisode
primaryTitle          Episode #1.1964
originalTitle         Episode #1.1964
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012122, dtype: object

(9,)

tconst                     tt11837216
titleType                   tvEpisode
primaryTitle          Episode #1.1966
originalTitle         Episode #1.1966
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012123, dtype: object

(9,)

tconst                     tt11837218
titleType                   tvEpisode
primaryTitle          Episode #1.1967
originalTitle         Episode #1.1967
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012124, dtype: object

(9,)

tconst                                  tt1183721
titleType                                   movie
primaryTitle      Tantei kitan: Bunmei no fukushû
originalTitle     Tantei kitan: Bunmei no fukushû
isAdult                                         0
startYear                                    1925
endYear                                        \N
runtimeMinutes                                 \N
genres                                         \N
Name: 2012125, dtype: object

(9,)

tconst                     tt11837220
titleType                   tvEpisode
primaryTitle          Episode #1.1965
originalTitle         Episode #1.1965
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012126, dtype: object

(9,)

tconst                     tt11837222
titleType                   tvEpisode
primaryTitle          Episode #1.1968
originalTitle         Episode #1.1968
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012127, dtype: object

(9,)

tconst                     tt11837224
titleType                   tvEpisode
primaryTitle          Episode #1.1969
originalTitle         Episode #1.1969
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012128, dtype: object

(9,)

tconst                     tt11837226
titleType                   tvEpisode
primaryTitle          Episode #1.1970
originalTitle         Episode #1.1970
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012129, dtype: object

(9,)

tconst                  tt11837228
titleType                tvEpisode
primaryTitle       Episode #1.1122
originalTitle      Episode #1.1122
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012130, dtype: object

(9,)

tconst            tt1183722
titleType          tvSeries
primaryTitle        3 i més
originalTitle       3 i més
isAdult                   0
startYear              2006
endYear                2007
runtimeMinutes           70
genres            Talk-Show
Name: 2012131, dtype: object

(9,)

tconst                     tt11837230
titleType                   tvEpisode
primaryTitle          Episode #1.1972
originalTitle         Episode #1.1972
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012132, dtype: object

(9,)

tconst                     tt11837232
titleType                   tvEpisode
primaryTitle          Episode #1.1971
originalTitle         Episode #1.1971
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012133, dtype: object

(9,)

tconst                     tt11837234
titleType                   tvEpisode
primaryTitle          Episode #1.1974
originalTitle         Episode #1.1974
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012134, dtype: object

(9,)

tconst                     tt11837236
titleType                   tvEpisode
primaryTitle          Episode #1.1973
originalTitle         Episode #1.1973
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012135, dtype: object

(9,)

tconst                               tt11837238
titleType                                 movie
primaryTitle      American Hero: Jim McCloughan
originalTitle     American Hero: Jim McCloughan
isAdult                                       0
startYear                                  2020
endYear                                      \N
runtimeMinutes                               \N
genres                              Documentary
Name: 2012136, dtype: object

(9,)

tconst            tt1183723
titleType             movie
primaryTitle          Angel
originalTitle         Angel
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes          108
genres                Drama
Name: 2012137, dtype: object

(9,)

tconst                     tt11837240
titleType                   tvEpisode
primaryTitle          Episode #1.1977
originalTitle         Episode #1.1977
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012138, dtype: object

(9,)

tconst                     tt11837242
titleType                   tvEpisode
primaryTitle          Episode #1.1975
originalTitle         Episode #1.1975
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012139, dtype: object

(9,)

tconst                     tt11837244
titleType                   tvEpisode
primaryTitle          Episode #1.1976
originalTitle         Episode #1.1976
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012140, dtype: object

(9,)

tconst                         tt11837246
titleType                       tvEpisode
primaryTitle      Water - Rain and Floods
originalTitle     Water - Rain and Floods
isAdult                                 0
startYear                            1982
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2012141, dtype: object

(9,)

tconst                     tt11837248
titleType                   tvEpisode
primaryTitle          Episode #1.1978
originalTitle         Episode #1.1978
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012142, dtype: object

(9,)

tconst                            tt1183724
titleType                           tvMovie
primaryTitle      Inside Operation Wildfire
originalTitle     Inside Operation Wildfire
isAdult                                   0
startYear                              2008
endYear                                  \N
runtimeMinutes                           \N
genres                          Documentary
Name: 2012143, dtype: object

(9,)

tconst                     tt11837250
titleType                   tvEpisode
primaryTitle          Episode #1.1979
originalTitle         Episode #1.1979
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012144, dtype: object

(9,)

tconst                     tt11837252
titleType                   tvEpisode
primaryTitle          Episode #1.1980
originalTitle         Episode #1.1980
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012145, dtype: object

(9,)

tconst                     tt11837254
titleType                   tvEpisode
primaryTitle          Episode #1.1721
originalTitle         Episode #1.1721
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012146, dtype: object

(9,)

tconst                     tt11837256
titleType                   tvEpisode
primaryTitle          Episode #1.1722
originalTitle         Episode #1.1722
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012147, dtype: object

(9,)

tconst                     tt11837258
titleType                   tvEpisode
primaryTitle          Episode #1.1723
originalTitle         Episode #1.1723
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012148, dtype: object

(9,)

tconst            tt1183725
titleType             movie
primaryTitle              K
originalTitle             K
isAdult                   0
startYear              2009
endYear                  \N
runtimeMinutes           90
genres             Thriller
Name: 2012149, dtype: object

(9,)

tconst                     tt11837260
titleType                   tvEpisode
primaryTitle          Episode #1.1724
originalTitle         Episode #1.1724
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012150, dtype: object

(9,)

tconst                     tt11837262
titleType                   tvEpisode
primaryTitle          Episode #1.1725
originalTitle         Episode #1.1725
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012151, dtype: object

(9,)

tconst                     tt11837264
titleType                   tvEpisode
primaryTitle          Episode #1.1727
originalTitle         Episode #1.1727
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012152, dtype: object

(9,)

tconst                     tt11837266
titleType                   tvEpisode
primaryTitle          Episode #1.1726
originalTitle         Episode #1.1726
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012153, dtype: object

(9,)

tconst                  tt11837268
titleType                tvEpisode
primaryTitle       Episode #1.1123
originalTitle      Episode #1.1123
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012154, dtype: object

(9,)

tconst                  tt1183726
titleType               tvEpisode
primaryTitle      Kryptonim Gracz
originalTitle     Kryptonim Gracz
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 79
genres                      Drama
Name: 2012155, dtype: object

(9,)

tconst                     tt11837270
titleType                   tvEpisode
primaryTitle          Episode #1.1728
originalTitle         Episode #1.1728
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012156, dtype: object

(9,)

tconst                     tt11837272
titleType                   tvEpisode
primaryTitle          Episode #1.1729
originalTitle         Episode #1.1729
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012157, dtype: object

(9,)

tconst                     tt11837274
titleType                   tvEpisode
primaryTitle          Episode #1.1730
originalTitle         Episode #1.1730
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012158, dtype: object

(9,)

tconst                     tt11837276
titleType                   tvEpisode
primaryTitle          Episode #1.1731
originalTitle         Episode #1.1731
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012159, dtype: object

(9,)

tconst                     tt11837278
titleType                   tvEpisode
primaryTitle          Episode #1.1733
originalTitle         Episode #1.1733
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012160, dtype: object

(9,)

tconst                         tt1183727
titleType                        tvMovie
primaryTitle                  Lava Storm
originalTitle                 Lava Storm
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        92
genres            Action,Adventure,Drama
Name: 2012161, dtype: object

(9,)

tconst                     tt11837280
titleType                   tvEpisode
primaryTitle          Episode #1.1732
originalTitle         Episode #1.1732
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012162, dtype: object

(9,)

tconst                     tt11837282
titleType                   tvEpisode
primaryTitle          Episode #1.1734
originalTitle         Episode #1.1734
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012163, dtype: object

(9,)

tconst                     tt11837284
titleType                   tvEpisode
primaryTitle          Episode #1.1735
originalTitle         Episode #1.1735
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012164, dtype: object

(9,)

tconst                  tt11837286
titleType                tvEpisode
primaryTitle       Episode #1.1124
originalTitle      Episode #1.1124
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012165, dtype: object

(9,)

tconst                     tt11837288
titleType                   tvEpisode
primaryTitle          Episode #1.1736
originalTitle         Episode #1.1736
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012166, dtype: object

(9,)

tconst                         tt1183728
titleType                          short
primaryTitle      Mother's Little Helper
originalTitle     Mother's Little Helper
isAdult                                0
startYear                           2006
endYear                               \N
runtimeMinutes                        14
genres                             Short
Name: 2012167, dtype: object

(9,)

tconst                     tt11837290
titleType                   tvEpisode
primaryTitle          Episode #1.1737
originalTitle         Episode #1.1737
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012168, dtype: object

(9,)

tconst                     tt11837292
titleType                   tvEpisode
primaryTitle          Episode #1.1738
originalTitle         Episode #1.1738
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012169, dtype: object

(9,)

tconst                      tt11837294
titleType                    tvEpisode
primaryTitle                      2782
originalTitle                     2782
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012170, dtype: object

(9,)

tconst                     tt11837296
titleType                   tvEpisode
primaryTitle          Episode #1.1739
originalTitle         Episode #1.1739
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012171, dtype: object

(9,)

tconst                     tt11837298
titleType                   tvEpisode
primaryTitle          Episode #1.1740
originalTitle         Episode #1.1740
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012172, dtype: object

(9,)

tconst                  tt1183729
titleType                   short
primaryTitle      Nun More Deadly
originalTitle     Nun More Deadly
isAdult                         0
startYear                    2005
endYear                        \N
runtimeMinutes                 \N
genres                      Short
Name: 2012173, dtype: object

(9,)

tconst                      tt11837300
titleType                    tvEpisode
primaryTitle      Pokemon Go & Youtube
originalTitle     Pokemon Go & Youtube
isAdult                              0
startYear                         2018
endYear                             \N
runtimeMinutes                      \N
genres                    Comedy,Drama
Name: 2012174, dtype: object

(9,)

tconst                     tt11837302
titleType                   tvEpisode
primaryTitle          Episode #1.1462
originalTitle         Episode #1.1462
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012175, dtype: object

(9,)

tconst                     tt11837304
titleType                   tvEpisode
primaryTitle          Episode #1.1461
originalTitle         Episode #1.1461
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012176, dtype: object

(9,)

tconst                            tt11837306
titleType                              short
primaryTitle      Ghost in America's Kitchen
originalTitle     Ghost in America's Kitchen
isAdult                                    0
startYear                               2019
endYear                                   \N
runtimeMinutes                            \N
genres                         History,Short
Name: 2012177, dtype: object

(9,)

tconst                     tt11837308
titleType                   tvEpisode
primaryTitle          Episode #1.1463
originalTitle         Episode #1.1463
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012178, dtype: object

(9,)

tconst                      tt1183730
titleType                       short
primaryTitle      There's Always Hope
originalTitle     There's Always Hope
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     13
genres                    Drama,Short
Name: 2012179, dtype: object

(9,)

tconst                     tt11837310
titleType                   tvEpisode
primaryTitle          Episode #1.1465
originalTitle         Episode #1.1465
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012180, dtype: object

(9,)

tconst                     tt11837312
titleType                   tvEpisode
primaryTitle          Episode #1.1464
originalTitle         Episode #1.1464
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012181, dtype: object

(9,)

tconst            tt11837314
titleType          tvEpisode
primaryTitle            Hesa
originalTitle           Hesa
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            13
genres                 Drama
Name: 2012182, dtype: object

(9,)

tconst                     tt11837316
titleType                   tvEpisode
primaryTitle          Episode #1.1466
originalTitle         Episode #1.1466
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012183, dtype: object

(9,)

tconst                     tt11837318
titleType                   tvEpisode
primaryTitle          Episode #1.1467
originalTitle         Episode #1.1467
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012184, dtype: object

(9,)

tconst            tt1183731
titleType             movie
primaryTitle       Tkaronto
originalTitle      Tkaronto
isAdult                   0
startYear              2007
endYear                  \N
runtimeMinutes          105
genres                Drama
Name: 2012185, dtype: object

(9,)

tconst                     tt11837320
titleType                   tvEpisode
primaryTitle          Episode #1.1468
originalTitle         Episode #1.1468
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012186, dtype: object

(9,)

tconst                     tt11837322
titleType                   tvEpisode
primaryTitle          Episode #1.1469
originalTitle         Episode #1.1469
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012187, dtype: object

(9,)

tconst                     tt11837324
titleType                   tvEpisode
primaryTitle          Episode #1.1470
originalTitle         Episode #1.1470
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012188, dtype: object

(9,)

tconst                     tt11837326
titleType                   tvEpisode
primaryTitle          Episode #1.1471
originalTitle         Episode #1.1471
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012189, dtype: object

(9,)

tconst                     tt11837328
titleType                   tvEpisode
primaryTitle          Episode #1.1472
originalTitle         Episode #1.1472
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012190, dtype: object

(9,)

tconst                         tt1183732
titleType                          movie
primaryTitle           Tokyo Gore Police
originalTitle     Tôkyô zankoku keisatsu
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                       110
genres              Action,Comedy,Horror
Name: 2012191, dtype: object

(9,)

tconst                     tt11837330
titleType                   tvEpisode
primaryTitle          Episode #1.1473
originalTitle         Episode #1.1473
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012192, dtype: object

(9,)

tconst                     tt11837332
titleType                   tvEpisode
primaryTitle          Episode #1.1474
originalTitle         Episode #1.1474
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012193, dtype: object

(9,)

tconst                     tt11837334
titleType                   tvEpisode
primaryTitle          Episode #1.1475
originalTitle         Episode #1.1475
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012194, dtype: object

(9,)

tconst                     tt11837336
titleType                   tvEpisode
primaryTitle          Episode #1.1476
originalTitle         Episode #1.1476
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012195, dtype: object

(9,)

tconst                         tt11837338
titleType                       tvEpisode
primaryTitle      Battle of the billiards
originalTitle     Battle of the billiards
isAdult                                 0
startYear                            2019
endYear                                \N
runtimeMinutes                         \N
genres             Crime,Drama,Reality-TV
Name: 2012196, dtype: object

(9,)

tconst                                     tt1183733
titleType                                      video
primaryTitle      War of the Worlds 2: The Next Wave
originalTitle     War of the Worlds 2: The Next Wave
isAdult                                            0
startYear                                       2008
endYear                                           \N
runtimeMinutes                                    87
genres                       Action,Adventure,Horror
Name: 2012197, dtype: object

(9,)

tconst                     tt11837340
titleType                   tvEpisode
primaryTitle          Episode #1.1477
originalTitle         Episode #1.1477
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012198, dtype: object

(9,)

tconst                         tt11837342
titleType                       tvEpisode
primaryTitle      Bodies - Bones and Fish
originalTitle     Bodies - Bones and Fish
isAdult                                 0
startYear                            1982
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2012199, dtype: object

(9,)

tconst                     tt11837344
titleType                   tvEpisode
primaryTitle          Episode #1.1479
originalTitle         Episode #1.1479
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012200, dtype: object

(9,)

tconst                     tt11837346
titleType                   tvEpisode
primaryTitle          Episode #1.1478
originalTitle         Episode #1.1478
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012201, dtype: object

(9,)

tconst                  tt11837348
titleType                tvEpisode
primaryTitle       Episode #1.1125
originalTitle      Episode #1.1125
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012202, dtype: object

(9,)

tconst                  tt1183734
titleType                   movie
primaryTitle      Wild, Wild Wong
originalTitle     Wild, Wild Wong
isAdult                         0
startYear                    1967
endYear                        \N
runtimeMinutes                 \N
genres                     Comedy
Name: 2012203, dtype: object

(9,)

tconst                     tt11837350
titleType                   tvEpisode
primaryTitle          Episode #1.1480
originalTitle         Episode #1.1480
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012204, dtype: object

(9,)

tconst                      tt11837352
titleType                    tvEpisode
primaryTitle      The Weather & Gaming
originalTitle     The Weather & Gaming
isAdult                              0
startYear                         2018
endYear                             \N
runtimeMinutes                      \N
genres                    Comedy,Drama
Name: 2012205, dtype: object

(9,)

tconst               tt11837354
titleType             tvEpisode
primaryTitle      Ellen & Vicke
originalTitle     Ellen & Vicke
isAdult                       0
startYear                  2019
endYear                      \N
runtimeMinutes               11
genres                    Drama
Name: 2012206, dtype: object

(9,)

tconst                     tt11837356
titleType                   tvEpisode
primaryTitle          Episode #1.1221
originalTitle         Episode #1.1221
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012207, dtype: object

(9,)

tconst                     tt11837358
titleType                   tvEpisode
primaryTitle          Episode #1.1223
originalTitle         Episode #1.1223
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012208, dtype: object

(9,)

tconst                      tt1183735
titleType                       video
primaryTitle      The Yoga Experience
originalTitle     The Yoga Experience
isAdult                             0
startYear                        2005
endYear                            \N
runtimeMinutes                    120
genres                          Sport
Name: 2012209, dtype: object

(9,)

tconst                     tt11837360
titleType                   tvEpisode
primaryTitle          Episode #1.1222
originalTitle         Episode #1.1222
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012210, dtype: object

(9,)

tconst                  tt11837362
titleType                tvEpisode
primaryTitle       Episode #1.1126
originalTitle      Episode #1.1126
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012211, dtype: object

(9,)

tconst                     tt11837364
titleType                   tvEpisode
primaryTitle          Episode #1.1224
originalTitle         Episode #1.1224
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012212, dtype: object

(9,)

tconst                     tt11837366
titleType                   tvEpisode
primaryTitle          Episode #1.1226
originalTitle         Episode #1.1226
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012213, dtype: object

(9,)

tconst                     tt11837368
titleType                   tvEpisode
primaryTitle          Episode #1.1225
originalTitle         Episode #1.1225
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012214, dtype: object

(9,)

tconst                        tt1183736
titleType                         short
primaryTitle       You Better Watch Out
originalTitle      You Better Watch Out
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       22
genres            Comedy,Short,Thriller
Name: 2012215, dtype: object

(9,)

tconst                     tt11837370
titleType                   tvEpisode
primaryTitle          Episode #1.1228
originalTitle         Episode #1.1228
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012216, dtype: object

(9,)

tconst                     tt11837372
titleType                   tvEpisode
primaryTitle          Episode #1.1227
originalTitle         Episode #1.1227
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012217, dtype: object

(9,)

tconst                     tt11837374
titleType                   tvEpisode
primaryTitle          Episode #1.1229
originalTitle         Episode #1.1229
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012218, dtype: object

(9,)

tconst                             tt11837376
titleType                           tvEpisode
primaryTitle      Backstreet Boys & Midsommar
originalTitle     Backstreet Boys & Midsommar
isAdult                                     0
startYear                                2019
endYear                                    \N
runtimeMinutes                             17
genres                                  Drama
Name: 2012219, dtype: object

(9,)

tconst                     tt11837378
titleType                   tvEpisode
primaryTitle          Episode #1.1231
originalTitle         Episode #1.1231
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012220, dtype: object

(9,)

tconst               tt1183737
titleType            tvEpisode
primaryTitle      Episode #2.6
originalTitle     Episode #2.6
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres               Game-Show
Name: 2012221, dtype: object

(9,)

tconst                     tt11837380
titleType                   tvEpisode
primaryTitle          Episode #1.1230
originalTitle         Episode #1.1230
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012222, dtype: object

(9,)

tconst                     tt11837382
titleType                   tvEpisode
primaryTitle          Episode #1.1232
originalTitle         Episode #1.1232
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012223, dtype: object

(9,)

tconst                     tt11837384
titleType                   tvEpisode
primaryTitle          Episode #1.1233
originalTitle         Episode #1.1233
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012224, dtype: object

(9,)

tconst                     tt11837386
titleType                   tvEpisode
primaryTitle          Episode #1.1234
originalTitle         Episode #1.1234
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012225, dtype: object

(9,)

tconst                     tt11837388
titleType                   tvEpisode
primaryTitle          Episode #1.1235
originalTitle         Episode #1.1235
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012226, dtype: object

(9,)

tconst                   tt1183738
titleType                tvEpisode
primaryTitle          Episode #1.2
originalTitle         Episode #1.2
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres            Comedy,Game-Show
Name: 2012227, dtype: object

(9,)

tconst                                tt11837390
titleType                              tvEpisode
primaryTitle      Episode dated 24 February 2020
originalTitle     Episode dated 24 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2012228, dtype: object

(9,)

tconst                     tt11837392
titleType                   tvEpisode
primaryTitle          Episode #1.1236
originalTitle         Episode #1.1236
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012229, dtype: object

(9,)

tconst                     tt11837394
titleType                   tvEpisode
primaryTitle          Episode #1.1238
originalTitle         Episode #1.1238
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012230, dtype: object

(9,)

tconst                     tt11837396
titleType                   tvEpisode
primaryTitle          Episode #1.1237
originalTitle         Episode #1.1237
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012231, dtype: object

(9,)

tconst                     tt11837398
titleType                   tvEpisode
primaryTitle          Episode #1.1239
originalTitle         Episode #1.1239
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012232, dtype: object

(9,)

tconst                              tt1183739
titleType                           tvEpisode
primaryTitle      Episode dated 22 April 2005
originalTitle     Episode dated 22 April 2005
isAdult                                     0
startYear                                2005
endYear                                    \N
runtimeMinutes                             \N
genres                Adventure,Drama,Romance
Name: 2012233, dtype: object

(9,)

tconst                     tt11837400
titleType                   tvEpisode
primaryTitle          Episode #1.1240
originalTitle         Episode #1.1240
isAdult                             0
startYear                          \N
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Musical,News
Name: 2012234, dtype: object

(9,)

tconst                                   tt11837402
titleType                                 tvEpisode
primaryTitle      Las disculpas de Gracia a Ricardo
originalTitle     Las disculpas de Gracia a Ricardo
isAdult                                           0
startYear                                      2020
endYear                                          \N
runtimeMinutes                                   \N
genres                                        Drama
Name: 2012235, dtype: object

(9,)

tconst                                tt11837404
titleType                              tvEpisode
primaryTitle      Episode dated 25 February 2020
originalTitle     Episode dated 25 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2012236, dtype: object

(9,)

tconst                                         tt11837406
titleType                                       tvEpisode
primaryTitle      Du är den siistigaste kvinnan i världen
originalTitle     Du är den siistigaste kvinnan i världen
isAdult                                                 0
startYear                                            2019
endYear                                                \N
runtimeMinutes                                         13
genres                                              Drama
Name: 2012237, dtype: object

(9,)

tconst                  tt11837408
titleType                tvEpisode
primaryTitle       Episode #1.1127
originalTitle      Episode #1.1127
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012238, dtype: object

(9,)

tconst                              tt1183740
titleType                           tvEpisode
primaryTitle      Episode dated 23 April 2005
originalTitle     Episode dated 23 April 2005
isAdult                                     0
startYear                                2005
endYear                                    \N
runtimeMinutes                             \N
genres                Adventure,Drama,Romance
Name: 2012239, dtype: object

(9,)

tconst            tt11837410
titleType          tvEpisode
primaryTitle       The Horse
originalTitle      The Horse
isAdult                    0
startYear               2020
endYear                   \N
runtimeMinutes            \N
genres                Comedy
Name: 2012240, dtype: object

(9,)

tconst                          tt11837412
titleType                        tvEpisode
primaryTitle      Bodies - Eyes and Ageing
originalTitle     Bodies - Eyes and Ageing
isAdult                                  0
startYear                             1982
endYear                                 \N
runtimeMinutes                          \N
genres                              Family
Name: 2012241, dtype: object

(9,)

tconst                          tt11837414
titleType                        tvEpisode
primaryTitle      E du ihop med han Vicke?
originalTitle     E du ihop med han Vicke?
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          12
genres                               Drama
Name: 2012242, dtype: object

(9,)

tconst                                tt11837416
titleType                              tvEpisode
primaryTitle      Episode dated 26 February 2020
originalTitle     Episode dated 26 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                                        \N
Name: 2012243, dtype: object

(9,)

tconst                tt11837418
titleType              tvEpisode
primaryTitle      Episode #1.281
originalTitle     Episode #1.281
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012244, dtype: object

(9,)

tconst                              tt1183741
titleType                           tvEpisode
primaryTitle      Episode dated 25 April 2005
originalTitle     Episode dated 25 April 2005
isAdult                                     0
startYear                                2005
endYear                                    \N
runtimeMinutes                             \N
genres                Adventure,Drama,Romance
Name: 2012245, dtype: object

(9,)

tconst                tt11837420
titleType              tvEpisode
primaryTitle      Episode #1.283
originalTitle     Episode #1.283
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012246, dtype: object

(9,)

tconst                tt11837422
titleType              tvEpisode
primaryTitle      Episode #1.282
originalTitle     Episode #1.282
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012247, dtype: object

(9,)

tconst                                tt11837424
titleType                              tvEpisode
primaryTitle      Episode dated 27 February 2020
originalTitle     Episode dated 27 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2012248, dtype: object

(9,)

tconst                tt11837426
titleType              tvEpisode
primaryTitle      Episode #1.284
originalTitle     Episode #1.284
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012249, dtype: object

(9,)

tconst                tt11837428
titleType              tvEpisode
primaryTitle      Episode #1.285
originalTitle     Episode #1.285
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012250, dtype: object

(9,)

tconst                              tt1183742
titleType                           tvEpisode
primaryTitle      Episode dated 26 April 2005
originalTitle     Episode dated 26 April 2005
isAdult                                     0
startYear                                2005
endYear                                    \N
runtimeMinutes                             \N
genres                Adventure,Drama,Romance
Name: 2012251, dtype: object

(9,)

tconst                                tt11837430
titleType                              tvEpisode
primaryTitle      Episode dated 28 February 2020
originalTitle     Episode dated 28 February 2020
isAdult                                        0
startYear                                   2020
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2012252, dtype: object

(9,)

tconst                tt11837432
titleType              tvEpisode
primaryTitle      Episode #1.286
originalTitle     Episode #1.286
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012253, dtype: object

(9,)

tconst                tt11837434
titleType              tvEpisode
primaryTitle      Episode #1.287
originalTitle     Episode #1.287
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012254, dtype: object

(9,)

tconst                tt11837436
titleType              tvEpisode
primaryTitle      Episode #1.288
originalTitle     Episode #1.288
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012255, dtype: object

(9,)

tconst            tt11837438
titleType          tvEpisode
primaryTitle         Seglats
originalTitle        Seglats
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            13
genres                 Drama
Name: 2012256, dtype: object

(9,)

tconst                              tt1183743
titleType                           tvEpisode
primaryTitle      Episode dated 27 April 2005
originalTitle     Episode dated 27 April 2005
isAdult                                     0
startYear                                2005
endYear                                    \N
runtimeMinutes                             \N
genres                Adventure,Drama,Romance
Name: 2012257, dtype: object

(9,)

tconst                tt11837440
titleType              tvEpisode
primaryTitle      Episode #1.289
originalTitle     Episode #1.289
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012258, dtype: object

(9,)

tconst                tt11837442
titleType              tvEpisode
primaryTitle      Episode #1.290
originalTitle     Episode #1.290
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012259, dtype: object

(9,)

tconst                tt11837444
titleType              tvEpisode
primaryTitle      Episode #1.292
originalTitle     Episode #1.292
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012260, dtype: object

(9,)

tconst                tt11837446
titleType              tvEpisode
primaryTitle      Episode #1.293
originalTitle     Episode #1.293
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012261, dtype: object

(9,)

tconst                tt11837448
titleType              tvEpisode
primaryTitle      Episode #1.294
originalTitle     Episode #1.294
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012262, dtype: object

(9,)

tconst                              tt1183744
titleType                           tvEpisode
primaryTitle      Episode dated 28 April 2005
originalTitle     Episode dated 28 April 2005
isAdult                                     0
startYear                                2005
endYear                                    \N
runtimeMinutes                             \N
genres                Adventure,Drama,Romance
Name: 2012263, dtype: object

(9,)

tconst                tt11837450
titleType              tvEpisode
primaryTitle      Episode #1.291
originalTitle     Episode #1.291
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012264, dtype: object

(9,)

tconst                tt11837452
titleType              tvEpisode
primaryTitle      Episode #1.295
originalTitle     Episode #1.295
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012265, dtype: object

(9,)

tconst                tt11837454
titleType              tvEpisode
primaryTitle      Episode #1.296
originalTitle     Episode #1.296
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012266, dtype: object

(9,)

tconst                tt11837456
titleType              tvEpisode
primaryTitle      Episode #1.297
originalTitle     Episode #1.297
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012267, dtype: object

(9,)

tconst                              tt11837458
titleType                            tvEpisode
primaryTitle      El beso de Samanta y Ricardo
originalTitle     El beso de Samanta y Ricardo
isAdult                                      0
startYear                                 2020
endYear                                     \N
runtimeMinutes                              \N
genres                                   Drama
Name: 2012268, dtype: object

(9,)

tconst                              tt1183745
titleType                           tvEpisode
primaryTitle      Episode dated 29 April 2005
originalTitle     Episode dated 29 April 2005
isAdult                                     0
startYear                                2005
endYear                                    \N
runtimeMinutes                             \N
genres                Adventure,Drama,Romance
Name: 2012269, dtype: object

(9,)

tconst                tt11837460
titleType              tvEpisode
primaryTitle      Episode #1.298
originalTitle     Episode #1.298
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012270, dtype: object

(9,)

tconst                tt11837462
titleType              tvEpisode
primaryTitle      Episode #1.299
originalTitle     Episode #1.299
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012271, dtype: object

(9,)

tconst                tt11837464
titleType              tvEpisode
primaryTitle      Episode #1.300
originalTitle     Episode #1.300
isAdult                        0
startYear                   2019
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012272, dtype: object

(9,)

tconst                      tt11837466
titleType                    tvEpisode
primaryTitle                      2809
originalTitle                     2809
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012273, dtype: object

(9,)

tconst                                                 tt11837468
titleType                                               tvEpisode
primaryTitle      Top 10 YouTubers You Didn't Know Were Criminals
originalTitle     Top 10 YouTubers You Didn't Know Were Criminals
isAdult                                                         0
startYear                                                    2020
endYear                                                        \N
runtimeMinutes                                                 \N
genres                                                  Talk-Show
Name: 2012274, dtype: object

(9,)

tconst                              tt1183746
titleType                           tvEpisode
primaryTitle      Episode dated 30 April 2005
originalTitle     Episode dated 30 April 2005
isAdult                                     0
startYear                                2005
endYear                                    \N
runtimeMinutes                             \N
genres                Adventure,Drama,Romance
Name: 2012275, dtype: object

(9,)

tconst                  tt11837470
titleType                tvEpisode
primaryTitle       Episode #1.1128
originalTitle      Episode #1.1128
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012276, dtype: object

(9,)

tconst                  tt11837472
titleType                tvEpisode
primaryTitle       Episode #1.1129
originalTitle      Episode #1.1129
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012277, dtype: object

(9,)

tconst                              tt11837474
titleType                            tvEpisode
primaryTitle      Bodies - Body Care and Teeth
originalTitle     Bodies - Body Care and Teeth
isAdult                                      0
startYear                                 1982
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2012278, dtype: object

(9,)

tconst            tt11837476
titleType          tvEpisode
primaryTitle         Kräftis
originalTitle        Kräftis
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            13
genres                 Drama
Name: 2012279, dtype: object

(9,)

tconst                                                    tt1183747
titleType                                                 tvEpisode
primaryTitle      Trauer, Vorwürfe, Misstrauen - Ludwigshafen zw...
originalTitle     Trauer, Vorwürfe, Misstrauen - Ludwigshafen zw...
isAdult                                                           0
startYear                                                      2008
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                    Talk-Show
Name: 2012280, dtype: object

(9,)

tconst                                    tt11837480
titleType                                    tvMovie
primaryTitle      Herz vorhanden, Vermögen erwünscht
originalTitle     Herz vorhanden, Vermögen erwünscht
isAdult                                            0
startYear                                       1963
endYear                                           \N
runtimeMinutes                                    27
genres                                         Music
Name: 2012281, dtype: object

(9,)

tconst                  tt11837482
titleType                tvEpisode
primaryTitle       Episode #1.1130
originalTitle      Episode #1.1130
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012282, dtype: object

(9,)

tconst                      tt11837484
titleType                    tvEpisode
primaryTitle           Episode #1.1101
originalTitle          Episode #1.1101
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012283, dtype: object

(9,)

tconst                  tt11837486
titleType                tvEpisode
primaryTitle       Episode #1.1131
originalTitle      Episode #1.1131
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012284, dtype: object

(9,)

tconst                          tt11837488
titleType                        tvEpisode
primaryTitle      Lycka till med studierna
originalTitle     Lycka till med studierna
isAdult                                  0
startYear                             2019
endYear                                 \N
runtimeMinutes                          15
genres                               Drama
Name: 2012285, dtype: object

(9,)

tconst                           tt1183748
titleType                        tvEpisode
primaryTitle               Ayakashi tsukai
originalTitle              Ayakashi tsukai
isAdult                                  0
startYear                             2008
endYear                                 \N
runtimeMinutes                          23
genres            Action,Animation,Fantasy
Name: 2012286, dtype: object

(9,)

tconst                      tt11837490
titleType                    tvEpisode
primaryTitle           Episode #1.1102
originalTitle          Episode #1.1102
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012287, dtype: object

(9,)

tconst                  tt11837492
titleType                tvEpisode
primaryTitle       Episode #1.1132
originalTitle      Episode #1.1132
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012288, dtype: object

(9,)

tconst                      tt11837494
titleType                    tvEpisode
primaryTitle           Episode #1.1103
originalTitle          Episode #1.1103
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012289, dtype: object

(9,)

tconst                      tt11837496
titleType                    tvEpisode
primaryTitle           Episode #1.1104
originalTitle          Episode #1.1104
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012290, dtype: object

(9,)

tconst                      tt11837498
titleType                    tvEpisode
primaryTitle           Episode #1.1105
originalTitle          Episode #1.1105
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012291, dtype: object

(9,)

tconst                tt1183749
titleType             tvEpisode
primaryTitle      Episode #2.11
originalTitle     Episode #2.11
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2012292, dtype: object

(9,)

tconst                      tt11837500
titleType                    tvEpisode
primaryTitle           Episode #1.1106
originalTitle          Episode #1.1106
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012293, dtype: object

(9,)

tconst                  tt11837502
titleType                tvEpisode
primaryTitle       Episode #1.1133
originalTitle      Episode #1.1133
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012294, dtype: object

(9,)

tconst                  tt11837504
titleType                tvEpisode
primaryTitle       Episode #1.1134
originalTitle      Episode #1.1134
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012295, dtype: object

(9,)

tconst                             tt11837506
titleType                           tvEpisode
primaryTitle      Bodies - Masks and Monsters
originalTitle     Bodies - Masks and Monsters
isAdult                                     0
startYear                                1982
endYear                                    \N
runtimeMinutes                             \N
genres                                 Family
Name: 2012296, dtype: object

(9,)

tconst                  tt11837508
titleType                tvEpisode
primaryTitle       Episode #1.1135
originalTitle      Episode #1.1135
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012297, dtype: object

(9,)

tconst                tt1183750
titleType             tvEpisode
primaryTitle      Episode #2.12
originalTitle     Episode #2.12
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2012298, dtype: object

(9,)

tconst                      tt11837510
titleType                    tvEpisode
primaryTitle           Episode #1.1107
originalTitle          Episode #1.1107
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012299, dtype: object

(9,)

tconst                      tt11837512
titleType                    tvEpisode
primaryTitle           Episode #1.1108
originalTitle          Episode #1.1108
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012300, dtype: object

(9,)

tconst                      tt11837514
titleType                    tvEpisode
primaryTitle           Episode #1.1109
originalTitle          Episode #1.1109
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012301, dtype: object

(9,)

tconst                                                   tt11837516
titleType                                                 tvEpisode
primaryTitle      Weekend Edition: Best of the Week - "Best of t...
originalTitle     Weekend Edition: Best of the Week - "Best of t...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   60
genres                                              Sport,Talk-Show
Name: 2012302, dtype: object

(9,)

tconst                      tt11837518
titleType                    tvEpisode
primaryTitle           Episode #1.1110
originalTitle          Episode #1.1110
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012303, dtype: object

(9,)

tconst                tt1183751
titleType             tvEpisode
primaryTitle      Episode #2.13
originalTitle     Episode #2.13
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2012304, dtype: object

(9,)

tconst                      tt11837520
titleType                    tvEpisode
primaryTitle           Episode #1.1112
originalTitle          Episode #1.1112
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012305, dtype: object

(9,)

tconst                      tt11837522
titleType                    tvEpisode
primaryTitle           Episode #1.1111
originalTitle          Episode #1.1111
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012306, dtype: object

(9,)

tconst                      tt11837524
titleType                    tvEpisode
primaryTitle           Episode #1.1113
originalTitle          Episode #1.1113
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012307, dtype: object

(9,)

tconst                      tt11837526
titleType                    tvEpisode
primaryTitle           Episode #1.1114
originalTitle          Episode #1.1114
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012308, dtype: object

(9,)

tconst                      tt11837528
titleType                    tvEpisode
primaryTitle           Episode #1.1115
originalTitle          Episode #1.1115
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012309, dtype: object

(9,)

tconst                tt1183752
titleType             tvEpisode
primaryTitle      Episode #2.14
originalTitle     Episode #2.14
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2012310, dtype: object

(9,)

tconst                      tt11837530
titleType                    tvEpisode
primaryTitle           Episode #1.1117
originalTitle          Episode #1.1117
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012311, dtype: object

(9,)

tconst                      tt11837532
titleType                    tvEpisode
primaryTitle           Episode #1.1116
originalTitle          Episode #1.1116
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012312, dtype: object

(9,)

tconst                      tt11837534
titleType                    tvEpisode
primaryTitle           Episode #1.1118
originalTitle          Episode #1.1118
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012313, dtype: object

(9,)

tconst                      tt11837536
titleType                    tvEpisode
primaryTitle           Episode #1.1120
originalTitle          Episode #1.1120
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012314, dtype: object

(9,)

tconst                      tt11837538
titleType                    tvEpisode
primaryTitle                      2810
originalTitle                     2810
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012315, dtype: object

(9,)

tconst                tt1183753
titleType             tvEpisode
primaryTitle      Episode #2.15
originalTitle     Episode #2.15
isAdult                       0
startYear                  2008
endYear                      \N
runtimeMinutes               \N
genres                    Drama
Name: 2012316, dtype: object

(9,)

tconst                      tt11837540
titleType                    tvEpisode
primaryTitle           Episode #1.1119
originalTitle          Episode #1.1119
isAdult                              0
startYear                           \N
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012317, dtype: object

(9,)

tconst                  tt11837542
titleType                tvEpisode
primaryTitle       Episode #1.1136
originalTitle      Episode #1.1136
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012318, dtype: object

(9,)

tconst                tt11837544
titleType              tvEpisode
primaryTitle      Episode #1.201
originalTitle     Episode #1.201
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012319, dtype: object

(9,)

tconst                  tt11837546
titleType                tvEpisode
primaryTitle       Episode #1.1137
originalTitle      Episode #1.1137
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012320, dtype: object

(9,)

tconst                     tt11837548
titleType                   tvEpisode
primaryTitle      Bodies - Body Parts
originalTitle     Bodies - Body Parts
isAdult                             0
startYear                        1982
endYear                            \N
runtimeMinutes                     \N
genres                         Family
Name: 2012321, dtype: object

(9,)

tconst                tt1183754
titleType             tvEpisode
primaryTitle      Episode #1.22
originalTitle     Episode #1.22
isAdult                       0
startYear                  1962
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012322, dtype: object

(9,)

tconst                  tt11837550
titleType                tvEpisode
primaryTitle       Episode #1.1138
originalTitle      Episode #1.1138
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012323, dtype: object

(9,)

tconst                tt11837554
titleType              tvEpisode
primaryTitle      Episode #1.203
originalTitle     Episode #1.203
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012324, dtype: object

(9,)

tconst                tt11837556
titleType              tvEpisode
primaryTitle      Episode #1.205
originalTitle     Episode #1.205
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012325, dtype: object

(9,)

tconst                                                   tt11837558
titleType                                                     movie
primaryTitle      I Propose We Never See Each Other Again After ...
originalTitle     I Propose We Never See Each Other Again After ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                  102
genres                                                       Comedy
Name: 2012326, dtype: object

(9,)

tconst                             tt1183755
titleType                          tvEpisode
primaryTitle      Episode dated 1 March 1990
originalTitle     Episode dated 1 March 1990
isAdult                                    0
startYear                               1990
endYear                                   \N
runtimeMinutes                            \N
genres                        News,Talk-Show
Name: 2012327, dtype: object

(9,)

tconst                tt11837560
titleType              tvEpisode
primaryTitle      Episode #1.204
originalTitle     Episode #1.204
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012328, dtype: object

(9,)

tconst                tt11837562
titleType              tvEpisode
primaryTitle      Episode #1.206
originalTitle     Episode #1.206
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012329, dtype: object

(9,)

tconst                  tt11837564
titleType                tvEpisode
primaryTitle       Episode #1.1139
originalTitle      Episode #1.1139
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012330, dtype: object

(9,)

tconst                tt11837566
titleType              tvEpisode
primaryTitle      Episode #1.207
originalTitle     Episode #1.207
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012331, dtype: object

(9,)

tconst               tt1183756
titleType            tvEpisode
primaryTitle      Episode #2.8
originalTitle     Episode #2.8
isAdult                      0
startYear                 1975
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Music
Name: 2012332, dtype: object

(9,)

tconst                tt11837570
titleType              tvEpisode
primaryTitle      Episode #1.209
originalTitle     Episode #1.209
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012333, dtype: object

(9,)

tconst                tt11837572
titleType              tvEpisode
primaryTitle      Episode #1.210
originalTitle     Episode #1.210
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012334, dtype: object

(9,)

tconst                tt11837574
titleType              tvEpisode
primaryTitle      Episode #1.211
originalTitle     Episode #1.211
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012335, dtype: object

(9,)

tconst                tt11837576
titleType              tvEpisode
primaryTitle      Episode #1.212
originalTitle     Episode #1.212
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012336, dtype: object

(9,)

tconst                tt11837578
titleType              tvEpisode
primaryTitle      Episode #1.213
originalTitle     Episode #1.213
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012337, dtype: object

(9,)

tconst                      tt1183757
titleType                   tvEpisode
primaryTitle           Episode #1.128
originalTitle          Episode #1.128
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012338, dtype: object

(9,)

tconst                tt11837580
titleType              tvEpisode
primaryTitle      Episode #1.214
originalTitle     Episode #1.214
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012339, dtype: object

(9,)

tconst                  tt11837582
titleType                tvEpisode
primaryTitle       Episode #1.1140
originalTitle      Episode #1.1140
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012340, dtype: object

(9,)

tconst                tt11837584
titleType              tvEpisode
primaryTitle      Episode #1.215
originalTitle     Episode #1.215
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012341, dtype: object

(9,)

tconst                tt11837586
titleType              tvEpisode
primaryTitle      Episode #1.216
originalTitle     Episode #1.216
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012342, dtype: object

(9,)

tconst                tt11837588
titleType              tvEpisode
primaryTitle      Episode #1.217
originalTitle     Episode #1.217
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012343, dtype: object

(9,)

tconst                      tt1183758
titleType                   tvEpisode
primaryTitle           Episode #1.129
originalTitle          Episode #1.129
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012344, dtype: object

(9,)

tconst                tt11837590
titleType              tvEpisode
primaryTitle      Episode #1.218
originalTitle     Episode #1.218
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012345, dtype: object

(9,)

tconst                tt11837592
titleType              tvEpisode
primaryTitle      Episode #1.219
originalTitle     Episode #1.219
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012346, dtype: object

(9,)

tconst                tt11837594
titleType              tvEpisode
primaryTitle      Episode #1.220
originalTitle     Episode #1.220
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012347, dtype: object

(9,)

tconst                  tt11837596
titleType                tvEpisode
primaryTitle       Episode #1.1141
originalTitle      Episode #1.1141
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012348, dtype: object

(9,)

tconst                 tt11837598
titleType               tvEpisode
primaryTitle      Episode #1.2945
originalTitle     Episode #1.2945
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012349, dtype: object

(9,)

tconst                      tt1183759
titleType                   tvEpisode
primaryTitle           Episode #1.130
originalTitle          Episode #1.130
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012350, dtype: object

(9,)

tconst                tt11837600
titleType              tvEpisode
primaryTitle      Episode #1.442
originalTitle     Episode #1.442
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012351, dtype: object

(9,)

tconst                tt11837602
titleType              tvEpisode
primaryTitle      Episode #1.444
originalTitle     Episode #1.444
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012352, dtype: object

(9,)

tconst                tt11837604
titleType              tvEpisode
primaryTitle      Episode #1.443
originalTitle     Episode #1.443
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012353, dtype: object

(9,)

tconst                tt11837606
titleType              tvEpisode
primaryTitle      Episode #1.445
originalTitle     Episode #1.445
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012354, dtype: object

(9,)

tconst                  tt11837608
titleType                tvEpisode
primaryTitle       Episode #1.1142
originalTitle      Episode #1.1142
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012355, dtype: object

(9,)

tconst                      tt1183760
titleType                   tvEpisode
primaryTitle           Episode #1.131
originalTitle          Episode #1.131
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012356, dtype: object

(9,)

tconst                tt11837610
titleType              tvEpisode
primaryTitle      Episode #1.446
originalTitle     Episode #1.446
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012357, dtype: object

(9,)

tconst                tt11837612
titleType              tvEpisode
primaryTitle      Episode #1.448
originalTitle     Episode #1.448
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012358, dtype: object

(9,)

tconst                tt11837614
titleType              tvEpisode
primaryTitle      Episode #1.447
originalTitle     Episode #1.447
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012359, dtype: object

(9,)

tconst                tt11837616
titleType              tvEpisode
primaryTitle      Episode #1.449
originalTitle     Episode #1.449
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012360, dtype: object

(9,)

tconst                tt11837618
titleType              tvEpisode
primaryTitle      Episode #1.450
originalTitle     Episode #1.450
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012361, dtype: object

(9,)

tconst                      tt1183761
titleType                   tvEpisode
primaryTitle           Episode #1.132
originalTitle          Episode #1.132
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012362, dtype: object

(9,)

tconst                tt11837620
titleType              tvEpisode
primaryTitle      Episode #1.451
originalTitle     Episode #1.451
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012363, dtype: object

(9,)

tconst                tt11837622
titleType              tvEpisode
primaryTitle      Episode #1.452
originalTitle     Episode #1.452
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012364, dtype: object

(9,)

tconst                tt11837624
titleType              tvEpisode
primaryTitle      Episode #1.453
originalTitle     Episode #1.453
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012365, dtype: object

(9,)

tconst                tt11837626
titleType              tvEpisode
primaryTitle      Episode #1.454
originalTitle     Episode #1.454
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012366, dtype: object

(9,)

tconst                tt11837628
titleType              tvEpisode
primaryTitle      Episode #1.456
originalTitle     Episode #1.456
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012367, dtype: object

(9,)

tconst                      tt1183762
titleType                   tvEpisode
primaryTitle           Episode #1.133
originalTitle          Episode #1.133
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012368, dtype: object

(9,)

tconst                tt11837630
titleType              tvEpisode
primaryTitle      Episode #1.455
originalTitle     Episode #1.455
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012369, dtype: object

(9,)

tconst                  tt11837632
titleType                tvEpisode
primaryTitle       Episode #1.1143
originalTitle      Episode #1.1143
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012370, dtype: object

(9,)

tconst             tt11837634
titleType               short
primaryTitle           Boxing
originalTitle          Boxing
isAdult                     0
startYear                2019
endYear                    \N
runtimeMinutes             \N
genres            Short,Sport
Name: 2012371, dtype: object

(9,)

tconst                      tt11837636
titleType                    tvEpisode
primaryTitle                      2811
originalTitle                     2811
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012372, dtype: object

(9,)

tconst                tt11837638
titleType              tvEpisode
primaryTitle      Episode #1.457
originalTitle     Episode #1.457
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012373, dtype: object

(9,)

tconst                      tt1183763
titleType                   tvEpisode
primaryTitle           Episode #1.134
originalTitle          Episode #1.134
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012374, dtype: object

(9,)

tconst                tt11837640
titleType              tvEpisode
primaryTitle      Episode #1.458
originalTitle     Episode #1.458
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012375, dtype: object

(9,)

tconst                tt11837642
titleType              tvEpisode
primaryTitle      Episode #1.459
originalTitle     Episode #1.459
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012376, dtype: object

(9,)

tconst                  tt11837644
titleType                tvEpisode
primaryTitle       Episode #1.1144
originalTitle      Episode #1.1144
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012377, dtype: object

(9,)

tconst                tt11837646
titleType              tvEpisode
primaryTitle      Episode #1.460
originalTitle     Episode #1.460
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012378, dtype: object

(9,)

tconst                  tt11837648
titleType                tvEpisode
primaryTitle       Episode #1.1145
originalTitle      Episode #1.1145
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012379, dtype: object

(9,)

tconst                      tt1183764
titleType                   tvEpisode
primaryTitle           Episode #1.135
originalTitle          Episode #1.135
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012380, dtype: object

(9,)

tconst                tt11837650
titleType              tvEpisode
primaryTitle      Episode #1.701
originalTitle     Episode #1.701
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012381, dtype: object

(9,)

tconst                tt11837652
titleType              tvEpisode
primaryTitle      Episode #1.703
originalTitle     Episode #1.703
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012382, dtype: object

(9,)

tconst                tt11837654
titleType              tvEpisode
primaryTitle      Episode #1.702
originalTitle     Episode #1.702
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012383, dtype: object

(9,)

tconst                tt11837656
titleType              tvEpisode
primaryTitle      Episode #1.704
originalTitle     Episode #1.704
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012384, dtype: object

(9,)

tconst                tt11837658
titleType              tvEpisode
primaryTitle      Episode #1.705
originalTitle     Episode #1.705
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012385, dtype: object

(9,)

tconst                      tt1183765
titleType                   tvEpisode
primaryTitle           Episode #1.136
originalTitle          Episode #1.136
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012386, dtype: object

(9,)

tconst                tt11837660
titleType              tvEpisode
primaryTitle      Episode #1.707
originalTitle     Episode #1.707
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012387, dtype: object

(9,)

tconst                tt11837662
titleType              tvEpisode
primaryTitle      Episode #1.706
originalTitle     Episode #1.706
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012388, dtype: object

(9,)

tconst                tt11837664
titleType              tvEpisode
primaryTitle      Episode #1.709
originalTitle     Episode #1.709
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012389, dtype: object

(9,)

tconst                tt11837666
titleType              tvEpisode
primaryTitle      Episode #1.708
originalTitle     Episode #1.708
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012390, dtype: object

(9,)

tconst                tt11837668
titleType              tvEpisode
primaryTitle      Episode #1.710
originalTitle     Episode #1.710
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012391, dtype: object

(9,)

tconst                      tt1183766
titleType                   tvEpisode
primaryTitle           Episode #1.137
originalTitle          Episode #1.137
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012392, dtype: object

(9,)

tconst                tt11837670
titleType              tvEpisode
primaryTitle      Episode #1.712
originalTitle     Episode #1.712
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012393, dtype: object

(9,)

tconst                tt11837672
titleType              tvEpisode
primaryTitle      Episode #1.711
originalTitle     Episode #1.711
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012394, dtype: object

(9,)

tconst                    tt11837674
titleType                  tvSpecial
primaryTitle      Jazz und Bossanova
originalTitle     Jazz und Bossanova
isAdult                            0
startYear                       1963
endYear                           \N
runtimeMinutes                    20
genres                   Music,Short
Name: 2012395, dtype: object

(9,)

tconst                tt11837676
titleType              tvEpisode
primaryTitle      Episode #1.713
originalTitle     Episode #1.713
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012396, dtype: object

(9,)

tconst                tt11837678
titleType              tvEpisode
primaryTitle      Episode #1.714
originalTitle     Episode #1.714
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012397, dtype: object

(9,)

tconst                      tt1183767
titleType                   tvEpisode
primaryTitle           Episode #1.138
originalTitle          Episode #1.138
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012398, dtype: object

(9,)

tconst                tt11837682
titleType              tvEpisode
primaryTitle      Episode #1.715
originalTitle     Episode #1.715
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012399, dtype: object

(9,)

tconst                tt11837684
titleType              tvEpisode
primaryTitle      Episode #1.716
originalTitle     Episode #1.716
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012400, dtype: object

(9,)

tconst                tt11837686
titleType              tvEpisode
primaryTitle      Episode #1.718
originalTitle     Episode #1.718
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012401, dtype: object

(9,)

tconst                tt11837688
titleType              tvEpisode
primaryTitle      Episode #1.717
originalTitle     Episode #1.717
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012402, dtype: object

(9,)

tconst                      tt1183768
titleType                   tvEpisode
primaryTitle           Episode #1.139
originalTitle          Episode #1.139
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012403, dtype: object

(9,)

tconst                tt11837690
titleType              tvEpisode
primaryTitle      Episode #1.719
originalTitle     Episode #1.719
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012404, dtype: object

(9,)

tconst                tt11837692
titleType              tvEpisode
primaryTitle      Episode #1.720
originalTitle     Episode #1.720
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012405, dtype: object

(9,)

tconst                tt11837694
titleType              tvEpisode
primaryTitle      Episode #1.922
originalTitle     Episode #1.922
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012406, dtype: object

(9,)

tconst                tt11837696
titleType              tvEpisode
primaryTitle      Episode #1.921
originalTitle     Episode #1.921
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012407, dtype: object

(9,)

tconst                      tt1183769
titleType                   tvEpisode
primaryTitle           Episode #1.140
originalTitle          Episode #1.140
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012408, dtype: object

(9,)

tconst                tt11837700
titleType              tvEpisode
primaryTitle      Episode #1.924
originalTitle     Episode #1.924
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012409, dtype: object

(9,)

tconst                tt11837702
titleType              tvEpisode
primaryTitle      Episode #1.925
originalTitle     Episode #1.925
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012410, dtype: object

(9,)

tconst                tt11837704
titleType              tvEpisode
primaryTitle      Episode #1.926
originalTitle     Episode #1.926
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012411, dtype: object

(9,)

tconst                tt11837706
titleType              tvEpisode
primaryTitle      Episode #1.927
originalTitle     Episode #1.927
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012412, dtype: object

(9,)

tconst                                     tt11837708
titleType                                   tvEpisode
primaryTitle      I Love You, You're Perfect, I Think
originalTitle     I Love You, You're Perfect, I Think
isAdult                                             0
startYear                                        2020
endYear                                            \N
runtimeMinutes                                     43
genres                                          Drama
Name: 2012413, dtype: object

(9,)

tconst                      tt1183770
titleType                   tvEpisode
primaryTitle           Episode #1.141
originalTitle          Episode #1.141
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012414, dtype: object

(9,)

tconst                tt11837710
titleType              tvEpisode
primaryTitle      Episode #1.929
originalTitle     Episode #1.929
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012415, dtype: object

(9,)

tconst                       tt11837712
titleType                     tvEpisode
primaryTitle      A Case Of Hit And Run
originalTitle     A Case Of Hit And Run
isAdult                               0
startYear                            \N
endYear                              \N
runtimeMinutes                       \N
genres                            Crime
Name: 2012416, dtype: object

(9,)

tconst                tt11837714
titleType              tvEpisode
primaryTitle      Episode #1.930
originalTitle     Episode #1.930
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012417, dtype: object

(9,)

tconst                tt11837716
titleType              tvEpisode
primaryTitle      Episode #1.931
originalTitle     Episode #1.931
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012418, dtype: object

(9,)

tconst                tt11837718
titleType              tvEpisode
primaryTitle      Episode #1.932
originalTitle     Episode #1.932
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012419, dtype: object

(9,)

tconst                      tt1183771
titleType                   tvEpisode
primaryTitle           Episode #1.142
originalTitle          Episode #1.142
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012420, dtype: object

(9,)

tconst                tt11837720
titleType              tvEpisode
primaryTitle      Episode #1.934
originalTitle     Episode #1.934
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012421, dtype: object

(9,)

tconst                tt11837722
titleType              tvEpisode
primaryTitle      Episode #1.933
originalTitle     Episode #1.933
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012422, dtype: object

(9,)

tconst                tt11837724
titleType              tvEpisode
primaryTitle      Episode #1.935
originalTitle     Episode #1.935
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012423, dtype: object

(9,)

tconst                tt11837726
titleType              tvEpisode
primaryTitle      Episode #1.936
originalTitle     Episode #1.936
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012424, dtype: object

(9,)

tconst                tt11837728
titleType              tvEpisode
primaryTitle      Episode #1.937
originalTitle     Episode #1.937
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012425, dtype: object

(9,)

tconst                      tt1183772
titleType                   tvEpisode
primaryTitle           Episode #1.143
originalTitle          Episode #1.143
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012426, dtype: object

(9,)

tconst                tt11837730
titleType              tvEpisode
primaryTitle      Episode #1.938
originalTitle     Episode #1.938
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012427, dtype: object

(9,)

tconst                tt11837732
titleType              tvEpisode
primaryTitle      Episode #1.939
originalTitle     Episode #1.939
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012428, dtype: object

(9,)

tconst                               tt11837734
titleType                             tvEpisode
primaryTitle      Episode dated 23 October 1970
originalTitle     Episode dated 23 October 1970
isAdult                                       0
startYear                                  1970
endYear                                      \N
runtimeMinutes                               \N
genres                                       \N
Name: 2012429, dtype: object

(9,)

tconst                                                   tt11837736
titleType                                                 tvEpisode
primaryTitle      Eliana advirtió a Agustina de lo que es capaz ...
originalTitle     Eliana advirtió a Agustina de lo que es capaz ...
isAdult                                                           0
startYear                                                      2020
endYear                                                          \N
runtimeMinutes                                                   \N
genres                                                        Drama
Name: 2012430, dtype: object

(9,)

tconst                tt11837738
titleType              tvEpisode
primaryTitle      Episode #1.940
originalTitle     Episode #1.940
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Crime
Name: 2012431, dtype: object

(9,)

tconst                      tt1183773
titleType                   tvEpisode
primaryTitle           Episode #1.144
originalTitle          Episode #1.144
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012432, dtype: object

(9,)

tconst                 tt11837740
titleType               tvEpisode
primaryTitle      Episode #1.1161
originalTitle     Episode #1.1161
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012433, dtype: object

(9,)

tconst            tt11837742
titleType              short
primaryTitle      Country FM
originalTitle     Country FM
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes             9
genres                 Short
Name: 2012434, dtype: object

(9,)

tconst                 tt11837744
titleType               tvEpisode
primaryTitle      Episode #1.1162
originalTitle     Episode #1.1162
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012435, dtype: object

(9,)

tconst                      tt11837746
titleType                    tvEpisode
primaryTitle                      2862
originalTitle                     2862
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012436, dtype: object

(9,)

tconst                 tt11837748
titleType               tvEpisode
primaryTitle      Episode #1.1163
originalTitle     Episode #1.1163
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012437, dtype: object

(9,)

tconst                      tt1183774
titleType                   tvEpisode
primaryTitle           Episode #1.145
originalTitle          Episode #1.145
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012438, dtype: object

(9,)

tconst                 tt11837750
titleType               tvEpisode
primaryTitle      Episode #1.1164
originalTitle     Episode #1.1164
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012439, dtype: object

(9,)

tconst                 tt11837752
titleType               tvEpisode
primaryTitle      Episode #1.1165
originalTitle     Episode #1.1165
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012440, dtype: object

(9,)

tconst                 tt11837754
titleType               tvEpisode
primaryTitle      Episode #1.1167
originalTitle     Episode #1.1167
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012441, dtype: object

(9,)

tconst                 tt11837756
titleType               tvEpisode
primaryTitle      Episode #1.1166
originalTitle     Episode #1.1166
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012442, dtype: object

(9,)

tconst                 tt11837758
titleType               tvEpisode
primaryTitle      Episode #1.1169
originalTitle     Episode #1.1169
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012443, dtype: object

(9,)

tconst                      tt1183775
titleType                   tvEpisode
primaryTitle           Episode #1.146
originalTitle          Episode #1.146
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012444, dtype: object

(9,)

tconst                 tt11837760
titleType               tvEpisode
primaryTitle      Episode #1.1168
originalTitle     Episode #1.1168
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012445, dtype: object

(9,)

tconst                 tt11837762
titleType               tvEpisode
primaryTitle      Episode #1.1170
originalTitle     Episode #1.1170
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012446, dtype: object

(9,)

tconst                 tt11837764
titleType               tvEpisode
primaryTitle      Episode #1.1172
originalTitle     Episode #1.1172
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012447, dtype: object

(9,)

tconst                 tt11837766
titleType               tvEpisode
primaryTitle      Episode #1.1171
originalTitle     Episode #1.1171
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012448, dtype: object

(9,)

tconst                 tt11837768
titleType               tvEpisode
primaryTitle      Episode #1.1173
originalTitle     Episode #1.1173
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012449, dtype: object

(9,)

tconst                      tt1183776
titleType                   tvEpisode
primaryTitle           Episode #1.147
originalTitle          Episode #1.147
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012450, dtype: object

(9,)

tconst                 tt11837770
titleType               tvEpisode
primaryTitle      Episode #1.1174
originalTitle     Episode #1.1174
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012451, dtype: object

(9,)

tconst                 tt11837772
titleType               tvEpisode
primaryTitle      Episode #1.1176
originalTitle     Episode #1.1176
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012452, dtype: object

(9,)

tconst                         tt11837774
titleType                       tvEpisode
primaryTitle      That's Printertainment!
originalTitle     That's Printertainment!
isAdult                                 0
startYear                            2020
endYear                                \N
runtimeMinutes                         \N
genres                    Animation,Short
Name: 2012453, dtype: object

(9,)

tconst                 tt11837776
titleType               tvEpisode
primaryTitle      Episode #1.1175
originalTitle     Episode #1.1175
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012454, dtype: object

(9,)

tconst                 tt11837778
titleType               tvEpisode
primaryTitle      Episode #1.1177
originalTitle     Episode #1.1177
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012455, dtype: object

(9,)

tconst                      tt1183777
titleType                   tvEpisode
primaryTitle           Episode #1.148
originalTitle          Episode #1.148
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012456, dtype: object

(9,)

tconst                 tt11837780
titleType               tvEpisode
primaryTitle      Episode #1.1178
originalTitle     Episode #1.1178
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012457, dtype: object

(9,)

tconst                 tt11837782
titleType               tvEpisode
primaryTitle      Episode #1.1179
originalTitle     Episode #1.1179
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012458, dtype: object

(9,)

tconst                 tt11837784
titleType               tvEpisode
primaryTitle      Episode #1.1180
originalTitle     Episode #1.1180
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012459, dtype: object

(9,)

tconst                 tt11837786
titleType               tvEpisode
primaryTitle      Episode #1.1361
originalTitle     Episode #1.1361
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012460, dtype: object

(9,)

tconst                      tt11837788
titleType                    tvEpisode
primaryTitle                      2863
originalTitle                     2863
isAdult                              0
startYear                         2015
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012461, dtype: object

(9,)

tconst                      tt1183778
titleType                   tvEpisode
primaryTitle           Episode #1.149
originalTitle          Episode #1.149
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012462, dtype: object

(9,)

tconst                                           tt11837790
titleType                                             video
primaryTitle      AronChupa & Little Sis Nora: Thai Massage
originalTitle     AronChupa & Little Sis Nora: Thai Massage
isAdult                                                   0
startYear                                              2020
endYear                                                  \N
runtimeMinutes                                            3
genres                                          Music,Short
Name: 2012463, dtype: object

(9,)

tconst                 tt11837792
titleType               tvEpisode
primaryTitle      Episode #1.1362
originalTitle     Episode #1.1362
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012464, dtype: object

(9,)

tconst                 tt11837794
titleType               tvEpisode
primaryTitle      Episode #1.1363
originalTitle     Episode #1.1363
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012465, dtype: object

(9,)

tconst                 tt11837796
titleType               tvEpisode
primaryTitle      Episode #1.1364
originalTitle     Episode #1.1364
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012466, dtype: object

(9,)

tconst                 tt11837798
titleType               tvEpisode
primaryTitle      Episode #1.1365
originalTitle     Episode #1.1365
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012467, dtype: object

(9,)

tconst                      tt1183779
titleType                   tvEpisode
primaryTitle           Episode #1.150
originalTitle          Episode #1.150
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012468, dtype: object

(9,)

tconst                 tt11837800
titleType               tvEpisode
primaryTitle      Episode #1.1366
originalTitle     Episode #1.1366
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012469, dtype: object

(9,)

tconst                 tt11837802
titleType               tvEpisode
primaryTitle      Episode #1.1367
originalTitle     Episode #1.1367
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012470, dtype: object

(9,)

tconst                 tt11837804
titleType               tvEpisode
primaryTitle      Episode #1.1369
originalTitle     Episode #1.1369
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012471, dtype: object

(9,)

tconst                 tt11837806
titleType               tvEpisode
primaryTitle      Episode #1.1368
originalTitle     Episode #1.1368
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012472, dtype: object

(9,)

tconst                 tt11837808
titleType               tvEpisode
primaryTitle      Episode #1.1370
originalTitle     Episode #1.1370
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012473, dtype: object

(9,)

tconst                      tt1183780
titleType                   tvEpisode
primaryTitle           Episode #1.151
originalTitle          Episode #1.151
isAdult                             0
startYear                        2008
endYear                            \N
runtimeMinutes                     \N
genres            Comedy,Drama,Family
Name: 2012474, dtype: object

(9,)

tconst              tt11837810
titleType                short
primaryTitle        James Cobb
originalTitle       James Cobb
isAdult                      0
startYear                   \N
endYear                     \N
runtimeMinutes              \N
genres            Comedy,Short
Name: 2012475, dtype: object

(9,)

tconst                 tt11837812
titleType               tvEpisode
primaryTitle      Episode #1.1372
originalTitle     Episode #1.1372
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012476, dtype: object

(9,)

tconst                 tt11837814
titleType               tvEpisode
primaryTitle      Episode #1.1371
originalTitle     Episode #1.1371
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012477, dtype: object

(9,)

tconst                 tt11837816
titleType                   movie
primaryTitle      Lake Wörthersee
originalTitle     Lake Wörthersee
isAdult                         0
startYear                    2011
endYear                        \N
runtimeMinutes                 49
genres                Documentary
Name: 2012478, dtype: object

(9,)

tconst                 tt11837818
titleType               tvEpisode
primaryTitle      Episode #1.1373
originalTitle     Episode #1.1373
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012479, dtype: object

(9,)

tconst                             tt1183781
titleType                          tvEpisode
primaryTitle                  Das Casting #5
originalTitle                 Das Casting #5
isAdult                                    0
startYear                               2008
endYear                                   \N
runtimeMinutes                            \N
genres            Game-Show,Music,Reality-TV
Name: 2012480, dtype: object

(9,)

tconst                 tt11837820
titleType               tvEpisode
primaryTitle      Episode #1.1374
originalTitle     Episode #1.1374
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012481, dtype: object

(9,)

tconst                 tt11837824
titleType               tvEpisode
primaryTitle      Episode #1.1376
originalTitle     Episode #1.1376
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012482, dtype: object

(9,)

tconst                 tt11837826
titleType               tvEpisode
primaryTitle      Episode #1.1377
originalTitle     Episode #1.1377
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012483, dtype: object

(9,)

tconst                 tt11837828
titleType               tvEpisode
primaryTitle      Episode #1.1378
originalTitle     Episode #1.1378
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012484, dtype: object

(9,)

tconst                                tt1183782
titleType                             tvEpisode
primaryTitle      Episode dated 8 February 2008
originalTitle     Episode dated 8 February 2008
isAdult                                       0
startYear                                  2008
endYear                                      \N
runtimeMinutes                               \N
genres                                     News
Name: 2012485, dtype: object

(9,)

tconst                 tt11837830
titleType               tvEpisode
primaryTitle      Episode #1.1380
originalTitle     Episode #1.1380
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012486, dtype: object

(9,)

tconst                 tt11837832
titleType               tvEpisode
primaryTitle      Episode #1.1379
originalTitle     Episode #1.1379
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012487, dtype: object

(9,)

tconst                 tt11837834
titleType               tvEpisode
primaryTitle      Episode #1.1661
originalTitle     Episode #1.1661
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012488, dtype: object

(9,)

tconst                 tt11837836
titleType               tvEpisode
primaryTitle      Episode #1.1662
originalTitle     Episode #1.1662
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012489, dtype: object

(9,)

tconst                 tt11837838
titleType               tvEpisode
primaryTitle      Episode #1.1663
originalTitle     Episode #1.1663
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012490, dtype: object

(9,)

tconst                              tt1183783
titleType                           tvEpisode
primaryTitle      Episode dated 30 March 1958
originalTitle     Episode dated 30 March 1958
isAdult                                     0
startYear                                1958
endYear                                    \N
runtimeMinutes                             \N
genres                         News,Talk-Show
Name: 2012491, dtype: object

(9,)

tconst                 tt11837840
titleType               tvEpisode
primaryTitle      Episode #1.1664
originalTitle     Episode #1.1664
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012492, dtype: object

(9,)

tconst                 tt11837842
titleType               tvEpisode
primaryTitle      Episode #1.1665
originalTitle     Episode #1.1665
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012493, dtype: object

(9,)

tconst                 tt11837844
titleType               tvEpisode
primaryTitle      Episode #1.1666
originalTitle     Episode #1.1666
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012494, dtype: object

(9,)

tconst                 tt11837846
titleType               tvEpisode
primaryTitle      Episode #1.1667
originalTitle     Episode #1.1667
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012495, dtype: object

(9,)

tconst                  tt11837848
titleType                    short
primaryTitle      Spanish Proyecto
originalTitle     Spanish Proyecto
isAdult                          0
startYear                     2017
endYear                         \N
runtimeMinutes                   8
genres                Sci-Fi,Short
Name: 2012496, dtype: object

(9,)

tconst                                        tt1183784
titleType                                     tvEpisode
primaryTitle      Debut of Howard K. Smith as Moderator
originalTitle     Debut of Howard K. Smith as Moderator
isAdult                                               0
startYear                                          1960
endYear                                              \N
runtimeMinutes                                       \N
genres                                   News,Talk-Show
Name: 2012497, dtype: object

(9,)

tconst                 tt11837850
titleType               tvEpisode
primaryTitle      Episode #1.1669
originalTitle     Episode #1.1669
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012498, dtype: object

(9,)

tconst                 tt11837852
titleType               tvEpisode
primaryTitle      Episode #1.1668
originalTitle     Episode #1.1668
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012499, dtype: object

(9,)

tconst                 tt11837854
titleType               tvEpisode
primaryTitle      Episode #1.1671
originalTitle     Episode #1.1671
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012500, dtype: object

(9,)

tconst                 tt11837856
titleType               tvEpisode
primaryTitle      Episode #1.1672
originalTitle     Episode #1.1672
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012501, dtype: object

(9,)

tconst                 tt11837858
titleType               tvEpisode
primaryTitle      Episode #1.1670
originalTitle     Episode #1.1670
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012502, dtype: object

(9,)

tconst                              tt1183785
titleType                           tvEpisode
primaryTitle      Episode dated 20 April 1961
originalTitle     Episode dated 20 April 1961
isAdult                                     0
startYear                                1961
endYear                                    \N
runtimeMinutes                             \N
genres                         News,Talk-Show
Name: 2012503, dtype: object

(9,)

tconst                                 tt11837860
titleType                               tvEpisode
primaryTitle      Nonsense - Friends All Together
originalTitle     Nonsense - Friends All Together
isAdult                                         0
startYear                                    2009
endYear                                        \N
runtimeMinutes                                 \N
genres                                     Family
Name: 2012504, dtype: object

(9,)

tconst                 tt11837862
titleType               tvEpisode
primaryTitle      Episode #1.1673
originalTitle     Episode #1.1673
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012505, dtype: object

(9,)

tconst                 tt11837864
titleType               tvEpisode
primaryTitle      Episode #1.1674
originalTitle     Episode #1.1674
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012506, dtype: object

(9,)

tconst                 tt11837866
titleType               tvEpisode
primaryTitle      Episode #1.1675
originalTitle     Episode #1.1675
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012507, dtype: object

(9,)

tconst                 tt11837868
titleType               tvEpisode
primaryTitle      Episode #1.1676
originalTitle     Episode #1.1676
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012508, dtype: object

(9,)

tconst                  tt1183786
titleType               tvEpisode
primaryTitle      Episode #1.3706
originalTitle     Episode #1.3706
isAdult                         0
startYear                    2007
endYear                        \N
runtimeMinutes                 \N
genres               Drama,Family
Name: 2012509, dtype: object

(9,)

tconst                 tt11837870
titleType               tvEpisode
primaryTitle      Episode #1.1678
originalTitle     Episode #1.1678
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012510, dtype: object

(9,)

tconst                 tt11837874
titleType               tvEpisode
primaryTitle      Episode #1.1679
originalTitle     Episode #1.1679
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012511, dtype: object

(9,)

tconst                 tt11837876
titleType               tvEpisode
primaryTitle      Episode #1.1680
originalTitle     Episode #1.1680
isAdult                         0
startYear                      \N
endYear                        \N
runtimeMinutes                 \N
genres                      Crime
Name: 2012512, dtype: object

(9,)

tconst                      tt11837878
titleType                    tvEpisode
primaryTitle      Dogs, Music, Anxiety
originalTitle     Dogs, Music, Anxiety
isAdult                              0
startYear                         2018
endYear                             \N
runtimeMinutes                      \N
genres                    Comedy,Drama
Name: 2012513, dtype: object

(9,)

tconst                       tt1183787
titleType                    tvEpisode
primaryTitle             Episode #1.62
originalTitle            Episode #1.62
isAdult                              0
startYear                         2008
endYear                             \N
runtimeMinutes                      \N
genres            Comedy,Drama,Romance
Name: 2012514, dtype: object

(9,)

tconst                tt11837880
titleType              tvEpisode
primaryTitle      Episode #1.121
originalTitle     Episode #1.121
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012515, dtype: object

(9,)

tconst                    tt11837884
titleType                  tvEpisode
primaryTitle      Only Crypto: Day 5
originalTitle     Only Crypto: Day 5
isAdult                            0
startYear                       2018
endYear                           \N
runtimeMinutes                    \N
genres                   Documentary
Name: 2012516, dtype: object

(9,)

tconst                       tt11837886
titleType                         movie
primaryTitle         Yellow Sulphur Sky
originalTitle     Den svavelgula himlen
isAdult                               0
startYear                          2021
endYear                              \N
runtimeMinutes                      120
genres                            Drama
Name: 2012517, dtype: object

(9,)

tconst                                     tt11837888
titleType                                   tvEpisode
primaryTitle      Smash Ultimate, Twitch, New Digimon
originalTitle     Smash Ultimate, Twitch, New Digimon
isAdult                                             0
startYear                                        2018
endYear                                            \N
runtimeMinutes                                     \N
genres                                   Comedy,Drama
Name: 2012518, dtype: object

(9,)

tconst                   tt1183788
titleType                tvEpisode
primaryTitle      Episode #1.15336
originalTitle     Episode #1.15336
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2012519, dtype: object

(9,)

tconst                tt11837890
titleType              tvEpisode
primaryTitle      Episode #1.122
originalTitle     Episode #1.122
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012520, dtype: object

(9,)

tconst                tt11837892
titleType              tvEpisode
primaryTitle      Episode #1.123
originalTitle     Episode #1.123
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012521, dtype: object

(9,)

tconst                             tt11837894
titleType                               video
primaryTitle      Jevetta Steele: Calling You
originalTitle     Jevetta Steele: Calling You
isAdult                                     0
startYear                                1988
endYear                                    \N
runtimeMinutes                              4
genres                            Music,Short
Name: 2012522, dtype: object

(9,)

tconst                tt11837896
titleType              tvEpisode
primaryTitle      Episode #1.124
originalTitle     Episode #1.124
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012523, dtype: object

(9,)

tconst                tt11837898
titleType              tvEpisode
primaryTitle      Episode #1.126
originalTitle     Episode #1.126
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012524, dtype: object

(9,)

tconst                   tt1183789
titleType                tvEpisode
primaryTitle      Episode #1.15337
originalTitle     Episode #1.15337
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2012525, dtype: object

(9,)

tconst                tt11837900
titleType              tvEpisode
primaryTitle      Episode #1.125
originalTitle     Episode #1.125
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012526, dtype: object

(9,)

tconst                tt11837902
titleType              tvEpisode
primaryTitle      Episode #1.128
originalTitle     Episode #1.128
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012527, dtype: object

(9,)

tconst                tt11837904
titleType              tvEpisode
primaryTitle      Episode #1.127
originalTitle     Episode #1.127
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012528, dtype: object

(9,)

tconst                        tt11837906
titleType                      tvEpisode
primaryTitle      Nonsense - Upside Down
originalTitle     Nonsense - Upside Down
isAdult                                0
startYear                           2009
endYear                               \N
runtimeMinutes                        \N
genres                            Family
Name: 2012529, dtype: object

(9,)

tconst                tt11837908
titleType              tvEpisode
primaryTitle      Episode #1.129
originalTitle     Episode #1.129
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012530, dtype: object

(9,)

tconst                   tt1183790
titleType                tvEpisode
primaryTitle      Episode #1.15338
originalTitle     Episode #1.15338
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2012531, dtype: object

(9,)

tconst                             tt11837912
titleType                           tvEpisode
primaryTitle      Distractions & Things Break
originalTitle     Distractions & Things Break
isAdult                                     0
startYear                                2018
endYear                                    \N
runtimeMinutes                             \N
genres                           Comedy,Drama
Name: 2012532, dtype: object

(9,)

tconst                tt11837914
titleType              tvEpisode
primaryTitle      Episode #1.130
originalTitle     Episode #1.130
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012533, dtype: object

(9,)

tconst                tt11837916
titleType              tvEpisode
primaryTitle      Episode #1.131
originalTitle     Episode #1.131
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012534, dtype: object

(9,)

tconst                tt11837918
titleType              tvEpisode
primaryTitle      Episode #1.132
originalTitle     Episode #1.132
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012535, dtype: object

(9,)

tconst                   tt1183791
titleType                tvEpisode
primaryTitle      Episode #1.15339
originalTitle     Episode #1.15339
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2012536, dtype: object

(9,)

tconst                tt11837920
titleType              tvEpisode
primaryTitle      Episode #1.134
originalTitle     Episode #1.134
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012537, dtype: object

(9,)

tconst                tt11837922
titleType              tvEpisode
primaryTitle      Episode #1.133
originalTitle     Episode #1.133
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012538, dtype: object

(9,)

tconst                tt11837924
titleType              tvEpisode
primaryTitle      Episode #1.136
originalTitle     Episode #1.136
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012539, dtype: object

(9,)

tconst                tt11837926
titleType              tvEpisode
primaryTitle      Episode #1.135
originalTitle     Episode #1.135
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012540, dtype: object

(9,)

tconst                tt11837928
titleType              tvEpisode
primaryTitle      Episode #1.137
originalTitle     Episode #1.137
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012541, dtype: object

(9,)

tconst                   tt1183792
titleType                tvEpisode
primaryTitle      Episode #1.15342
originalTitle     Episode #1.15342
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2012542, dtype: object

(9,)

tconst                tt11837930
titleType              tvEpisode
primaryTitle      Episode #1.138
originalTitle     Episode #1.138
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012543, dtype: object

(9,)

tconst                tt11837932
titleType              tvEpisode
primaryTitle      Episode #1.139
originalTitle     Episode #1.139
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012544, dtype: object

(9,)

tconst                tt11837934
titleType              tvEpisode
primaryTitle      Episode #1.121
originalTitle     Episode #1.121
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012545, dtype: object

(9,)

tconst            tt11837936
titleType              short
primaryTitle            Koma
originalTitle           Koma
isAdult                    0
startYear               2019
endYear                   \N
runtimeMinutes            10
genres                 Short
Name: 2012546, dtype: object

(9,)

tconst                tt11837938
titleType              tvEpisode
primaryTitle      Episode #1.122
originalTitle     Episode #1.122
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012547, dtype: object

(9,)

tconst                   tt1183793
titleType                tvEpisode
primaryTitle      Episode #1.15343
originalTitle     Episode #1.15343
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres               Drama,Romance
Name: 2012548, dtype: object

(9,)

tconst                tt11837942
titleType              tvEpisode
primaryTitle      Episode #1.123
originalTitle     Episode #1.123
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012549, dtype: object

(9,)

tconst                tt11837944
titleType              tvEpisode
primaryTitle      Episode #1.125
originalTitle     Episode #1.125
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012550, dtype: object

(9,)

tconst                tt11837946
titleType              tvEpisode
primaryTitle      Episode #1.124
originalTitle     Episode #1.124
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012551, dtype: object

(9,)

tconst                tt11837948
titleType              tvEpisode
primaryTitle      Episode #1.127
originalTitle     Episode #1.127
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012552, dtype: object

(9,)

tconst                  tt1183794
titleType               tvEpisode
primaryTitle      Episode #1.2230
originalTitle     Episode #1.2230
isAdult                         0
startYear                    2008
endYear                        \N
runtimeMinutes                 \N
genres              Drama,Romance
Name: 2012553, dtype: object

(9,)

tconst                tt11837950
titleType              tvEpisode
primaryTitle      Episode #1.126
originalTitle     Episode #1.126
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012554, dtype: object

(9,)

tconst                                          tt11837952
titleType                                        tvEpisode
primaryTitle      Nonsense - Funny Games and Silly Animals
originalTitle     Nonsense - Funny Games and Silly Animals
isAdult                                                  0
startYear                                             2009
endYear                                                 \N
runtimeMinutes                                          \N
genres                                              Family
Name: 2012555, dtype: object

(9,)

tconst                tt11837954
titleType              tvEpisode
primaryTitle      Episode #1.128
originalTitle     Episode #1.128
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012556, dtype: object

(9,)

tconst                               tt11837956
titleType                                 movie
primaryTitle      Secrets of the Flooded Forest
originalTitle     Secrets of the Flooded Forest
isAdult                                       0
startYear                                  2010
endYear                                      \N
runtimeMinutes                               53
genres                              Documentary
Name: 2012557, dtype: object

(9,)

tconst                tt11837958
titleType              tvEpisode
primaryTitle      Episode #1.129
originalTitle     Episode #1.129
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012558, dtype: object

(9,)

tconst                            tt1183795
titleType                         tvEpisode
primaryTitle      Episode dated 24 May 1964
originalTitle     Episode dated 24 May 1964
isAdult                                   0
startYear                              1964
endYear                                  \N
runtimeMinutes                           \N
genres                                 News
Name: 2012559, dtype: object

(9,)

tconst                tt11837960
titleType              tvEpisode
primaryTitle      Episode #1.130
originalTitle     Episode #1.130
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012560, dtype: object

(9,)

tconst                tt11837962
titleType              tvEpisode
primaryTitle      Episode #1.132
originalTitle     Episode #1.132
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012561, dtype: object

(9,)

tconst                tt11837964
titleType              tvEpisode
primaryTitle      Episode #1.131
originalTitle     Episode #1.131
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012562, dtype: object

(9,)

tconst                tt11837966
titleType              tvEpisode
primaryTitle      Episode #1.134
originalTitle     Episode #1.134
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012563, dtype: object

(9,)

tconst                tt11837968
titleType              tvEpisode
primaryTitle      Episode #1.133
originalTitle     Episode #1.133
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012564, dtype: object

(9,)

tconst                         tt1183796
titleType                      tvEpisode
primaryTitle               Episode #6.21
originalTitle              Episode #6.21
isAdult                                0
startYear                           2008
endYear                               \N
runtimeMinutes                        \N
genres            Comedy,Music,Talk-Show
Name: 2012565, dtype: object

(9,)

tconst                tt11837970
titleType              tvEpisode
primaryTitle      Episode #1.135
originalTitle     Episode #1.135
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012566, dtype: object

(9,)

tconst                tt11837972
titleType              tvEpisode
primaryTitle      Episode #1.136
originalTitle     Episode #1.136
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012567, dtype: object

(9,)

tconst                tt11837974
titleType              tvEpisode
primaryTitle      Episode #1.137
originalTitle     Episode #1.137
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012568, dtype: object

(9,)

tconst                tt11837976
titleType              tvEpisode
primaryTitle      Episode #1.138
originalTitle     Episode #1.138
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012569, dtype: object

(9,)

tconst                tt11837978
titleType              tvEpisode
primaryTitle      Episode #1.139
originalTitle     Episode #1.139
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012570, dtype: object

(9,)

tconst               tt1183797
titleType            tvEpisode
primaryTitle      Episode #2.3
originalTitle     Episode #2.3
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              22
genres                  Comedy
Name: 2012571, dtype: object

(9,)

tconst                tt11837980
titleType              tvEpisode
primaryTitle      Episode #1.140
originalTitle     Episode #1.140
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012572, dtype: object

(9,)

tconst                tt11837982
titleType              tvEpisode
primaryTitle      Episode #1.321
originalTitle     Episode #1.321
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012573, dtype: object

(9,)

tconst                tt11837984
titleType              tvEpisode
primaryTitle      Episode #1.322
originalTitle     Episode #1.322
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012574, dtype: object

(9,)

tconst                tt11837986
titleType              tvEpisode
primaryTitle      Episode #1.323
originalTitle     Episode #1.323
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012575, dtype: object

(9,)

tconst                tt11837988
titleType              tvEpisode
primaryTitle      Episode #1.324
originalTitle     Episode #1.324
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012576, dtype: object

(9,)

tconst              tt1183798
titleType           tvEpisode
primaryTitle      Fatale fout
originalTitle     Fatale fout
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2012577, dtype: object

(9,)

tconst                tt11837990
titleType              tvEpisode
primaryTitle      Episode #1.325
originalTitle     Episode #1.325
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012578, dtype: object

(9,)

tconst                tt11837992
titleType              tvEpisode
primaryTitle      Episode #1.326
originalTitle     Episode #1.326
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012579, dtype: object

(9,)

tconst                tt11837994
titleType              tvEpisode
primaryTitle      Episode #1.327
originalTitle     Episode #1.327
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012580, dtype: object

(9,)

tconst                tt11837998
titleType              tvEpisode
primaryTitle      Episode #1.328
originalTitle     Episode #1.328
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012581, dtype: object

(9,)

tconst             tt1183799
titleType          tvEpisode
primaryTitle      Stuntvrouw
originalTitle     Stuntvrouw
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2012582, dtype: object

(9,)

tconst                tt11838000
titleType              tvEpisode
primaryTitle      Episode #1.329
originalTitle     Episode #1.329
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012583, dtype: object

(9,)

tconst                tt11838002
titleType              tvEpisode
primaryTitle      Episode #1.330
originalTitle     Episode #1.330
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012584, dtype: object

(9,)

tconst                              tt11838004
titleType                            tvEpisode
primaryTitle      Nonsense - Strange Dress Ups
originalTitle     Nonsense - Strange Dress Ups
isAdult                                      0
startYear                                 2009
endYear                                     \N
runtimeMinutes                              \N
genres                                  Family
Name: 2012585, dtype: object

(9,)

tconst                tt11838006
titleType              tvEpisode
primaryTitle      Episode #1.331
originalTitle     Episode #1.331
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012586, dtype: object

(9,)

tconst            tt1183800
titleType         tvEpisode
primaryTitle      Dood zaad
originalTitle     Dood zaad
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2012587, dtype: object

(9,)

tconst                tt11838010
titleType              tvEpisode
primaryTitle      Episode #1.332
originalTitle     Episode #1.332
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012588, dtype: object

(9,)

tconst                tt11838012
titleType              tvEpisode
primaryTitle      Episode #1.334
originalTitle     Episode #1.334
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012589, dtype: object

(9,)

tconst                tt11838014
titleType              tvEpisode
primaryTitle      Episode #1.333
originalTitle     Episode #1.333
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012590, dtype: object

(9,)

tconst                tt11838016
titleType              tvEpisode
primaryTitle      Episode #1.335
originalTitle     Episode #1.335
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012591, dtype: object

(9,)

tconst                tt11838018
titleType              tvEpisode
primaryTitle      Episode #1.336
originalTitle     Episode #1.336
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012592, dtype: object

(9,)

tconst              tt1183801
titleType           tvEpisode
primaryTitle      De marinier
originalTitle     De marinier
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2012593, dtype: object

(9,)

tconst                tt11838020
titleType              tvEpisode
primaryTitle      Episode #1.337
originalTitle     Episode #1.337
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012594, dtype: object

(9,)

tconst                tt11838022
titleType              tvEpisode
primaryTitle      Episode #1.339
originalTitle     Episode #1.339
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012595, dtype: object

(9,)

tconst                tt11838024
titleType              tvEpisode
primaryTitle      Episode #1.338
originalTitle     Episode #1.338
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012596, dtype: object

(9,)

tconst                tt11838026
titleType              tvEpisode
primaryTitle      Episode #1.340
originalTitle     Episode #1.340
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                     Drama
Name: 2012597, dtype: object

(9,)

tconst                            tt11838028
titleType                          tvEpisode
primaryTitle      Episode dated 17 July 2015
originalTitle     Episode dated 17 July 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2012598, dtype: object

(9,)

tconst                        tt1183802
titleType                     tvEpisode
primaryTitle      De waardenfluisteraar
originalTitle     De waardenfluisteraar
isAdult                               0
startYear                          2008
endYear                              \N
runtimeMinutes                       \N
genres                            Drama
Name: 2012599, dtype: object

(9,)

tconst               tt11838032
titleType             tvEpisode
primaryTitle      Episode #1.81
originalTitle     Episode #1.81
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012600, dtype: object

(9,)

tconst                            tt11838034
titleType                          tvEpisode
primaryTitle      Episode dated 24 July 2015
originalTitle     Episode dated 24 July 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2012601, dtype: object

(9,)

tconst                  tt11838036
titleType                tvEpisode
primaryTitle       Episode #1.1146
originalTitle      Episode #1.1146
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012602, dtype: object

(9,)

tconst                                     tt11838038
titleType                                     tvShort
primaryTitle      Internationaler Treffpunkt Salzburg
originalTitle     Internationaler Treffpunkt Salzburg
isAdult                                             0
startYear                                        1955
endYear                                            \N
runtimeMinutes                                     18
genres                              Documentary,Short
Name: 2012603, dtype: object

(9,)

tconst                   tt1183803
titleType                tvEpisode
primaryTitle      Corrigerende tik
originalTitle     Corrigerende tik
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2012604, dtype: object

(9,)

tconst                            tt11838040
titleType                          tvEpisode
primaryTitle      Episode dated 27 July 2015
originalTitle     Episode dated 27 July 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2012605, dtype: object

(9,)

tconst                            tt11838042
titleType                          tvEpisode
primaryTitle      Episode dated 31 July 2015
originalTitle     Episode dated 31 July 2015
isAdult                                    0
startYear                               2015
endYear                                   \N
runtimeMinutes                            \N
genres                                    \N
Name: 2012606, dtype: object

(9,)

tconst               tt11838044
titleType                 video
primaryTitle       Carrom Board
originalTitle      Carrom Board
isAdult                       0
startYear                  2016
endYear                      \N
runtimeMinutes                6
genres            Musical,Short
Name: 2012607, dtype: object

(9,)

tconst               tt11838046
titleType             tvEpisode
primaryTitle      Episode #1.82
originalTitle     Episode #1.82
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012608, dtype: object

(9,)

tconst                         tt11838048
titleType                       tvEpisode
primaryTitle      Nonsense - Unusual food
originalTitle     Nonsense - Unusual food
isAdult                                 0
startYear                            2009
endYear                                \N
runtimeMinutes                         \N
genres                             Family
Name: 2012609, dtype: object

(9,)

tconst              tt1183804
titleType           tvEpisode
primaryTitle      Oude rotten
originalTitle     Oude rotten
isAdult                     0
startYear                2008
endYear                    \N
runtimeMinutes             \N
genres                  Drama
Name: 2012610, dtype: object

(9,)

tconst                  tt11838050
titleType                tvEpisode
primaryTitle       Episode #1.1147
originalTitle      Episode #1.1147
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012611, dtype: object

(9,)

tconst               tt11838052
titleType             tvEpisode
primaryTitle      Episode #1.83
originalTitle     Episode #1.83
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012612, dtype: object

(9,)

tconst               tt11838054
titleType             tvEpisode
primaryTitle      Episode #1.84
originalTitle     Episode #1.84
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012613, dtype: object

(9,)

tconst                             tt11838056
titleType                           tvEpisode
primaryTitle      Episode dated 3 August 2015
originalTitle     Episode dated 3 August 2015
isAdult                                     0
startYear                                2015
endYear                                    \N
runtimeMinutes                             \N
genres                                     \N
Name: 2012614, dtype: object

(9,)

tconst               tt11838058
titleType             tvEpisode
primaryTitle      Episode #1.86
originalTitle     Episode #1.86
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012615, dtype: object

(9,)

tconst               tt1183805
titleType            tvEpisode
primaryTitle      Ben's Garage
originalTitle     Ben's Garage
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2012616, dtype: object

(9,)

tconst               tt11838060
titleType             tvEpisode
primaryTitle      Episode #1.87
originalTitle     Episode #1.87
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012617, dtype: object

(9,)

tconst                tt11838062
titleType              tvEpisode
primaryTitle      Episode #16.47
originalTitle     Episode #16.47
isAdult                        0
startYear                   2020
endYear                       \N
runtimeMinutes                \N
genres                Reality-TV
Name: 2012618, dtype: object

(9,)

tconst               tt11838064
titleType             tvEpisode
primaryTitle      Episode #1.85
originalTitle     Episode #1.85
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012619, dtype: object

(9,)

tconst               tt11838066
titleType             tvEpisode
primaryTitle      Episode #1.88
originalTitle     Episode #1.88
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012620, dtype: object

(9,)

tconst                  tt11838068
titleType                tvEpisode
primaryTitle       Episode #1.1148
originalTitle      Episode #1.1148
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012621, dtype: object

(9,)

tconst            tt1183806
titleType         tvEpisode
primaryTitle       Zebrapad
originalTitle      Zebrapad
isAdult                   0
startYear              2008
endYear                  \N
runtimeMinutes           \N
genres                Drama
Name: 2012622, dtype: object

(9,)

tconst               tt11838070
titleType             tvEpisode
primaryTitle      Episode #1.89
originalTitle     Episode #1.89
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012623, dtype: object

(9,)

tconst               tt11838072
titleType             tvEpisode
primaryTitle      Episode #1.90
originalTitle     Episode #1.90
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012624, dtype: object

(9,)

tconst                  tt11838074
titleType                tvEpisode
primaryTitle       Episode #1.1149
originalTitle      Episode #1.1149
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012625, dtype: object

(9,)

tconst               tt11838076
titleType             tvEpisode
primaryTitle      Episode #1.91
originalTitle     Episode #1.91
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012626, dtype: object

(9,)

tconst               tt11838078
titleType             tvEpisode
primaryTitle      Episode #1.92
originalTitle     Episode #1.92
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012627, dtype: object

(9,)

tconst               tt1183807
titleType            tvEpisode
primaryTitle      Familiedrama
originalTitle     Familiedrama
isAdult                      0
startYear                 2008
endYear                     \N
runtimeMinutes              \N
genres                   Drama
Name: 2012628, dtype: object

(9,)

tconst               tt11838080
titleType             tvEpisode
primaryTitle      Episode #1.93
originalTitle     Episode #1.93
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012629, dtype: object

(9,)

tconst               tt11838082
titleType             tvEpisode
primaryTitle      Episode #1.94
originalTitle     Episode #1.94
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012630, dtype: object

(9,)

tconst               tt11838084
titleType             tvEpisode
primaryTitle      Episode #1.95
originalTitle     Episode #1.95
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012631, dtype: object

(9,)

tconst               tt11838086
titleType             tvEpisode
primaryTitle      Episode #1.96
originalTitle     Episode #1.96
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012632, dtype: object

(9,)

tconst               tt11838088
titleType             tvEpisode
primaryTitle      Episode #1.97
originalTitle     Episode #1.97
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012633, dtype: object

(9,)

tconst                   tt1183808
titleType                tvEpisode
primaryTitle      Anonieme getuige
originalTitle     Anonieme getuige
isAdult                          0
startYear                     2008
endYear                         \N
runtimeMinutes                  \N
genres                       Drama
Name: 2012634, dtype: object

(9,)

tconst               tt11838090
titleType             tvEpisode
primaryTitle      Episode #1.98
originalTitle     Episode #1.98
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012635, dtype: object

(9,)

tconst                  tt11838092
titleType                tvEpisode
primaryTitle       Episode #1.1150
originalTitle      Episode #1.1150
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012636, dtype: object

(9,)

tconst                   tt11838094
titleType                     short
primaryTitle      Heider and Simmel
originalTitle     Heider and Simmel
isAdult                           0
startYear                      1944
endYear                          \N
runtimeMinutes                    2
genres              Animation,Short
Name: 2012637, dtype: object

(9,)

tconst               tt11838096
titleType             tvEpisode
primaryTitle      Episode #1.99
originalTitle     Episode #1.99
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012638, dtype: object

(9,)

tconst                tt11838098
titleType              tvEpisode
primaryTitle      Episode #1.100
originalTitle     Episode #1.100
isAdult                        0
startYear                     \N
endYear                       \N
runtimeMinutes                \N
genres                    Comedy
Name: 2012639, dtype: object

(9,)

tconst             tt1183809
titleType          tvEpisode
primaryTitle      Buitenspel
originalTitle     Buitenspel
isAdult                    0
startYear               2008
endYear                   \N
runtimeMinutes            \N
genres                 Drama
Name: 2012640, dtype: object

(9,)

tconst                  tt11838100
titleType                tvEpisode
primaryTitle       Episode #1.1151
originalTitle      Episode #1.1151
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012641, dtype: object

(9,)

tconst               tt11838102
titleType             tvEpisode
primaryTitle      Episode #2.81
originalTitle     Episode #2.81
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012642, dtype: object

(9,)

tconst               tt11838104
titleType             tvEpisode
primaryTitle      Episode #2.83
originalTitle     Episode #2.83
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012643, dtype: object

(9,)

tconst               tt11838106
titleType             tvEpisode
primaryTitle      Episode #2.82
originalTitle     Episode #2.82
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012644, dtype: object

(9,)

tconst               tt11838108
titleType             tvEpisode
primaryTitle      Episode #2.84
originalTitle     Episode #2.84
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012645, dtype: object

(9,)

tconst                                 tt1183810
titleType                              tvEpisode
primaryTitle      Episode dated 26 November 1993
originalTitle     Episode dated 26 November 1993
isAdult                                        0
startYear                                   1993
endYear                                       \N
runtimeMinutes                                \N
genres                            News,Talk-Show
Name: 2012646, dtype: object

(9,)

tconst                  tt11838110
titleType                tvEpisode
primaryTitle       Episode #1.1152
originalTitle      Episode #1.1152
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012647, dtype: object

(9,)

tconst               tt11838112
titleType             tvEpisode
primaryTitle      Episode #2.85
originalTitle     Episode #2.85
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012648, dtype: object

(9,)

tconst               tt11838114
titleType             tvEpisode
primaryTitle      Episode #2.86
originalTitle     Episode #2.86
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012649, dtype: object

(9,)

tconst               tt11838116
titleType             tvEpisode
primaryTitle      Episode #2.87
originalTitle     Episode #2.87
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012650, dtype: object

(9,)

tconst               tt11838118
titleType             tvEpisode
primaryTitle      Episode #2.88
originalTitle     Episode #2.88
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012651, dtype: object

(9,)

tconst                               tt1183811
titleType                            tvEpisode
primaryTitle      Episode dated 18 August 1999
originalTitle     Episode dated 18 August 1999
isAdult                                      0
startYear                                 1999
endYear                                     \N
runtimeMinutes                              \N
genres                          News,Talk-Show
Name: 2012652, dtype: object

(9,)

tconst               tt11838120
titleType             tvEpisode
primaryTitle      Episode #2.89
originalTitle     Episode #2.89
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012653, dtype: object

(9,)

tconst               tt11838122
titleType             tvEpisode
primaryTitle      Episode #2.90
originalTitle     Episode #2.90
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012654, dtype: object

(9,)

tconst                  tt11838124
titleType                tvEpisode
primaryTitle       Episode #1.1153
originalTitle      Episode #1.1153
isAdult                          0
startYear                     2016
endYear                         \N
runtimeMinutes                  \N
genres            Drama,Reality-TV
Name: 2012655, dtype: object

(9,)

tconst               tt11838126
titleType             tvEpisode
primaryTitle      Episode #2.91
originalTitle     Episode #2.91
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012656, dtype: object

(9,)

tconst               tt11838128
titleType             tvEpisode
primaryTitle      Episode #2.92
originalTitle     Episode #2.92
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012657, dtype: object

(9,)

tconst               tt1183812
titleType            tvEpisode
primaryTitle      Episode #1.2
originalTitle     Episode #1.2
isAdult                      0
startYear                 1977
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2012658, dtype: object

(9,)

tconst               tt11838130
titleType             tvEpisode
primaryTitle      Episode #2.93
originalTitle     Episode #2.93
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012659, dtype: object

(9,)

tconst               tt11838132
titleType             tvEpisode
primaryTitle      Episode #2.95
originalTitle     Episode #2.95
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012660, dtype: object

(9,)

tconst               tt11838134
titleType             tvEpisode
primaryTitle      Episode #2.94
originalTitle     Episode #2.94
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012661, dtype: object

(9,)

tconst               tt11838136
titleType             tvEpisode
primaryTitle      Episode #2.96
originalTitle     Episode #2.96
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012662, dtype: object

(9,)

tconst               tt11838138
titleType             tvEpisode
primaryTitle      Episode #2.97
originalTitle     Episode #2.97
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012663, dtype: object

(9,)

tconst               tt1183813
titleType            tvEpisode
primaryTitle      Episode #1.3
originalTitle     Episode #1.3
isAdult                      0
startYear                 1977
endYear                     \N
runtimeMinutes              \N
genres                      \N
Name: 2012664, dtype: object

(9,)

tconst               tt11838140
titleType             tvEpisode
primaryTitle      Episode #2.98
originalTitle     Episode #2.98
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012665, dtype: object

(9,)

tconst               tt11838142
titleType             tvEpisode
primaryTitle      Episode #2.99
originalTitle     Episode #2.99
isAdult                       0
startYear                    \N
endYear                      \N
runtimeMinutes               \N
genres                   Comedy
Name: 2012666, dtype: object

(9,)

KeyboardInterrupt:

In [31]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 2000110 to 2050109
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          50000 non-null  object
 1   titleType       50000 non-null  object
 2   primaryTitle    50000 non-null  object
 3   originalTitle   50000 non-null  object
 4   isAdult         50000 non-null  object
 5   startYear       50000 non-null  object
 6   endYear         50000 non-null  object
 7   runtimeMinutes  50000 non-null  object
 8   genres          50000 non-null  object
dtypes: object(9)
memory usage: 3.4+ MB

In [34]:
df2['runtimeMinutes'] = df2['runtimeMinutes'].astype(int)

In [35]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 2000110 to 2050109
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          50000 non-null  object
 1   titleType       50000 non-null  object
 2   primaryTitle    50000 non-null  object
 3   originalTitle   50000 non-null  object
 4   isAdult         50000 non-null  object
 5   startYear       50000 non-null  object
 6   endYear         50000 non-null  object
 7   runtimeMinutes  50000 non-null  int64
 8   genres          50000 non-null  object
dtypes: int64(1), object(8)
memory usage: 3.4+ MB

# 3. describe()로 기초 통계량 파악(이상치 파악)

In [36]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [38]:
data.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

# 4. 결측값 찾고, 비율계산 후 대치/삭제하기
* 결측값 비율 계산: isna().sum() / len(데이터프레임) * 100
* 결측값 비율이 5% 미만: 행, 열을 제거, 분석에 크게 영향을 미치지 않음
* 결측값 비율이 5% ~ 30%: 결측값을 대체(Imputation)
  * 수치형 데이터(숫자형, 나이, 가격): 평균(mean), 중앙값(median), 최빈값(mode)으로 대체
  * 범주형 데이터(문자형/(숫자형), 선실등급, 탑승지: 최빈값(mode)으로 대체
* 결측값 비율이 30% ~ 50%: 컬럼의 중요도에 따라서 결측값을 대체 혹은 삭제
  * KNN(K-Nearest Neighbor, 최근접이웃) imputer, 회귀분석을 통해 결측값 대체
* 결측값 비율이 50% 이상: 해당 컬럼 삭제

In [44]:
round(data.isna().sum() / len(data) * 100, 2)

PassengerId     0.00
Survived        0.00
Pclass          0.00
Name            0.00
Sex             0.00
Age            19.87
SibSp           0.00
Parch           0.00
Ticket          0.00
Fare            0.00
Cabin          77.10
Embarked        0.22
dtype: float64

In [45]:
# 결측값 비율이 77%인 cabin은 분석에서 제외
data = data.drop('Cabin', axis=1)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

## 결측 데이터의 종류
* MCAR(완전 무작위 결측): 다른 변수와 무관하게 생긴 결측(랜덤, 이유 없음)
  * 설문 조사중 일부 응답자가 무작위로 답변을 건너뜀
* MAR(무작위 결측): 다른 변수와는 관련 있지만 본인과는 무관
  * 나이가 많은 사람들이 소득란에 응답을 하지 않는 경우(나이와 관련)
  * 직업에 따라서 학력란에 응답하지 않는 경우(가정환경, 소득)
* NMAR(비무작위 결측): 변수 자기 자신과 직접 관련이 있는 경우
  * 소득이 낮은 사람이 자신의 소득을 숨기는 경우(소득과 결측이 직접 관련)
  * 체중이 많이 나가는 경우 자신의 체중을 숨기는 경우
  * 만족도가 낮은 고객이 만족도 조사에 응하지 않는 경우

## 결측치 처리방법
### 1) 단순대치법(simple imputaion)
#### (1) 완전분석: 결측값이 있는 모든 행을 삭제하고 완전한 자료만으로 분석(잘 안씀)
* 결측값을 삭제해도 모델을 만들기에 충분히 많은 데이터가 있는 경우
* 결측값을 삭제한 후에 데이터에 편향이 없다는 전제가 있을 때
* dropna(): 결측값이 있는 모든 행 삭제

In [47]:
df.dropna()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
8407394,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2010,\N,\N,"Action,Drama,Family"
8407395,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
8407396,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
8407397,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
8407398,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [48]:
data.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

#### (2) 평균 대치법: 결측치가 있는 컬럼에서 데이터의 평균을 구한 후 결측값을 대치
* 평균을 이용하기 때문에 간편
* 데이터에 이상치가 있을 경우 평균을 이용할 수 없다.
* 데이터에 이상치가 있는 경우 중앙값이나 최빈값을 이용해야 한다.

In [50]:
# 평균, 중앙값
a = pd.Series([24, 5, 10, 34, 20, 18, 28, 23])
b = pd.Series([24, 5, 10, 34, 20, 18, 28, 2000])

In [51]:
a

0    24
1     5
2    10
3    34
4    20
5    18
6    28
7    23
dtype: int64

In [52]:
b

0      24
1       5
2      10
3      34
4      20
5      18
6      28
7    2000
dtype: int64

In [53]:
# 평균
print(a.mean())
print(b.mean())

20.25
267.375

In [55]:
# 중앙값
print(a.median())
print(b.median())

21.5
22.0

In [56]:
sorted(a)

[5, 10, 18, 20, 23, 24, 28, 34]

In [57]:
sorted(b)

[5, 10, 18, 20, 24, 28, 34, 2000]

* Age 컬럼의 결측값을 평균 대치법으로 대치

In [60]:
data['Age'].mean()

np.float64(29.69911764705882)

In [61]:
data['Age'].fillna(data['Age'].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [62]:
data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [64]:
age_na_idx = data[data['Age'].isna()].index
age_na_idx

Index([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,
       ...
       832, 837, 839, 846, 849, 859, 863, 868, 878, 888],
      dtype='int64', length=177)

In [65]:
data['Age'] = data['Age'].fillna(data['Age'].mean())

In [67]:
data.iloc[age_na_idx,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,29.699118,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S

In [69]:
data.loc[age_na_idx, 'Age'] = np.nan

In [70]:
data.loc[age_na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S

* 중앙값으로 대치

In [71]:
data['Age'] = data['Age'].fillna(data['Age'].median())
data.loc[age_na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,28.0,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28.0,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,28.0,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,28.0,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,28.0,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,28.0,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S

In [72]:
data.loc[age_na_idx, 'Age'] = np.nan

# scikit-learn의 simple imputer를 이용한 대치

In [74]:
# !pip install scikit-learn

In [75]:
from sklearn.impute import SimpleImputer

In [81]:
imp_mean = SimpleImputer(strategy='mean')
imp_mean.fit_transform(data[['Age']])[:,0].shape

(891,)

In [79]:
data['Age'].shape

(891,)

In [82]:
imp_mean = SimpleImputer(strategy='mean')
data['Age'] = imp_mean.fit_transform(data[['Age']])[:,0]

In [83]:
data.loc[age_na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,29.699118,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S

In [84]:
data.loc[age_na_idx, 'Age'] = np.nan

In [85]:
# 중앙값으로 결측 값 처리
imp_median = SimpleImputer(strategy='median')
data['Age'] = imp_median.fit_transform(data[['Age']])[:,0]
data.loc[age_na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,28.0,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28.0,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,28.0,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,28.0,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,28.0,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,28.0,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S

In [86]:
data.loc[age_na_idx, 'Age'] = np.nan

In [87]:
# 최빈값으로 결측 값 처리
imp_most_frequent = SimpleImputer(strategy='most_frequent')
data['Age'] = imp_most_frequent.fit_transform(data[['Age']])[:,0]
data.loc[age_na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,24.0,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,24.0,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,24.0,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,24.0,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,24.0,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,24.0,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,24.0,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,24.0,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,24.0,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S

In [88]:
data.loc[age_na_idx, 'Age'] = np.nan

# 결측값 비율이 30%-50%일 때 KNN최근접 이웃법 을 이용해 대치

In [89]:
from sklearn.impute import KNNImputer

In [90]:
knn_imp = KNNImputer(n_neighbors=5)
data['Age'] = knn_imp.fit_transform(data[['Age']])[:, 0]
data.loc[age_na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,29.699118,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S

In [91]:
data.loc[age_na_idx, 'Age'] = np.nan

In [92]:
knn_imp = KNNImputer(n_neighbors=10)
data['Age'] = knn_imp.fit_transform(data[['Age']])[:, 0]
data.loc[age_na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,29.699118,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S

# 깊은 복사, 얕은 복사

In [93]:
data2 = data

In [96]:
data2.loc[0, 'Name'] = "둘리"

In [97]:
data2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,둘리,male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [98]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,둘리,male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [101]:
print("data의 메모리주소:  ", id(data))
print("data2의 메모리주소: ", id(data2))

data의 메모리주소:   2820188025328
data2의 메모리주소:  2820188025328

In [102]:
data3 = data.copy()
print("data3의 메모리주소: ", id(data3))

data3의 메모리주소:  2820242518896

In [103]:
data3.loc[0, 'Name'] = "또치"

In [104]:
data3.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,또치,male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [105]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,둘리,male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S